/* =====================================================
   德语词根速记 — 联想链 + 换元音(Ablaut) + 前后缀
   两层分明:hooks 的「意象」是记忆钩子(靠字形与读音联想),不是词源主张;
   词干、词义、Ablaut 序列与前后缀都是有据的德语事实。
   ===================================================== */
const CHAIN_DE = {
A:{ line:"张口的 a → 出去、离开 → 工作 → 眼睛看",
  hooks:[{img:"➡️ 往外、离开:aus- 出、ab- 离开", roots:["aus","ab"]},
         {img:"👀 注意与眼:acht 注意、Auge 眼", roots:["acht","aug"]},
         {img:"🔨 干活与职务", roots:["arbeit","amt","akt"]},
         {img:"🕰️ 老与晚", roots:["alt","abend","anfang"]}]},
B:{ line:"房子:建 → 绑 → 带来 → 书",
  hooks:[{img:"🏠 建与山:bauen 建、Berg 山", roots:["bau","berg"]},
         {img:"🪢 绑与弯:binden 绑、biegen 弯", roots:["bind","bieg"]},
         {img:"🤲 带来与提供", roots:["bring","biet","bitt"]},
         {img:"📕 书与信", roots:["buch","brief"]},
         {img:"🔥 烧与破", roots:["brenn","brech"]}]},
C:{ line:"德语本族词几乎不用 C(只在 ch- 与借词里)",
  hooks:[{img:"🧒 -chen 是最常见的小称后缀:Mädchen、Brötchen", roots:["chen"]}]},
D:{ line:"想 → 压 → 盖 → 转",
  hooks:[{img:"🧠 想与感谢", roots:["denk","dank"]},
         {img:"👇 压与盖", roots:["drück","deck"]},
         {img:"🔄 转与持续", roots:["dreh","dauer"]},
         {img:"🤝 服务与穿过", roots:["dien","durch"]}]},
E:{ line:"一 → 进入 → 结束 → 做事的人",
  hooks:[{img:"1️⃣ 一与进入:ein 一/入", roots:["ein","eins","eigen"]},
         {img:"🏁 结束与土地", roots:["end","erd","eis"]},
         {img:"👤 -er 做这件事的人;-ei 场所", roots:["er","ei"]},
         {img:"🍽️ 吃与荣誉", roots:["ess","ehr","erb"]}]},
F:{ line:"落 → 抓 → 走 → 流与飞",
  hooks:[{img:"⬇️ 落与错:fallen 落、fehlen 缺", roots:["fall","fehl"]},
         {img:"✋ 抓与装:fassen 抓、fangen 捉", roots:["fass","fang"]},
         {img:"🚗 行与引:fahren 行驶、führen 引导", roots:["fahr","führ"]},
         {img:"🌊 流与飞:fließen 流、fliegen 飞", roots:["fließ","flieg"]},
         {img:"🙂 感觉与朋友", roots:["fühl","freund","fried"]}]},
G:{ line:"给 → 走 → 抓 → 好",
  hooks:[{img:"🎁 给与得:geben 给", roots:["geb","gelt"]},
         {img:"🚶 走与集合:gehen 走、Ge- 集合前缀", roots:["geh","ge"]},
         {img:"✊ 抓与基础", roots:["greif","grund"]},
         {img:"👍 好与大与幸运", roots:["gut","groß","glück"]},
         {img:"🙏 信与神与精神", roots:["glaub","gott","geist"]}]},
H:{ line:"手 → 持 → 帮 → 高",
  hooks:[{img:"✋ 手与做:Hand 手、handeln 行动", roots:["hand","halt"]},
         {img:"🆘 帮与举:helfen 帮、heben 举", roots:["helf","heb"]},
         {img:"🏠 家与房与心", roots:["haus","heim","herz"]},
         {img:"⬆️ 高与热与听", roots:["hoch","heiß","hör"]}]},
I:{ line:"在里面",
  hooks:[{img:"📥 -in 阴性后缀;in- 在内", roots:["in","ig","isch"]}]},
J:{ line:"年 → 年轻",
  hooks:[{img:"📅 Jahr 年、jung 年轻", roots:["jahr","jung"]}]},
K:{ line:"来 → 能 → 认识 → 买",
  hooks:[{img:"🚪 来与能:kommen 来、können 能", roots:["komm","könn"]},
         {img:"🧠 认识与艺术", roots:["kenn","kunst"]},
         {img:"💰 买与斗", roots:["kauf","kämpf","krieg"]},
         {img:"🧒 孩子与头", roots:["kind","kopf","kraft"]}]},
L:{ line:"躺 → 放 → 活 → 学",
  hooks:[{img:"🛏️ 躺与放:liegen 躺、legen 放", roots:["lieg","leg"]},
         {img:"🏃 跑与让:laufen 跑、lassen 让", roots:["lauf","lass"]},
         {img:"📖 读与学与教", roots:["les","lern"]},
         {img:"❤️ 爱与生活与光", roots:["lieb","leb","licht"]}]},
M:{ line:"做 → 力量 → 人 → 量",
  hooks:[{img:"🔨 做与力:machen 做、Macht 权力", roots:["mach","macht"]},
         {img:"🧑 人与男人", roots:["mensch","mann"]},
         {img:"📏 量与记:messen 量、merken 记住", roots:["mess","merk"]},
         {img:"🌙 月与母与中间", roots:["mond","mutter","mitt"]}]},
N:{ line:"拿 → 名字 → 新 → 需要",
  hooks:[{img:"🤲 拿:nehmen 拿", roots:["nehm"]},
         {img:"🏷️ 名与叫", roots:["nam","nenn"]},
         {img:"🆕 新与近与夜", roots:["neu","nah","nacht"]},
         {img:"❗ 需要与有用", roots:["not","nutz"]}]},
O:{ line:"上面 → 秩序 → 地点",
  hooks:[{img:"⬆️ ober- 上面的", roots:["ober"]},
         {img:"📐 秩序与地点", roots:["ordn","ort"]}]},
P:{ line:"德语的 P 多在借词里",
  hooks:[{img:"📮 Pass、Platz、Preis、Pflicht:多来自拉丁或法语", roots:["pass","platz2","preis","pflicht"]},
         {img:"🐴 马与照料", roots:["pferd","pfleg"]}]},
Q:{ line:"折磨",
  hooks:[{img:"😖 quälen 折磨、Qual 痛苦", roots:["quäl"]}]},
R:{ line:"说 → 正确 → 算 → 休息",
  hooks:[{img:"🗣️ 说与叫:reden 说、rufen 叫", roots:["red","ruf"]},
         {img:"⚖️ 正确与方向:Recht 权利、richten 指向", roots:["recht","richt"]},
         {img:"🔢 算与规则", roots:["rechn","regel"]},
         {img:"😴 休息与旅行与救", roots:["ruh","reis","rett"]}]},
S:{ line:"看 → 站 → 说 → 写",
  hooks:[{img:"👁️ 看:sehen 看、schauen 瞧", roots:["seh","schau"]},
         {img:"🧍 站与坐与放:stehen、sitzen、setzen、stellen", roots:["steh","sitz","setz","stell"]},
         {img:"🗣️ 说与写:sprechen、schreiben、sagen", roots:["sprech","schreib","sag"]},
         {img:"🛡️ 保护与创造与打击", roots:["schutz","schaff","schlag"]},
         {img:"☀️ 太阳与夏与雪", roots:["sonn","sommer","schnee"]}]},
T:{ line:"做 → 带 → 分 → 日",
  hooks:[{img:"✅ 做:tun 做、Tat 行为", roots:["tu"]},
         {img:"🎒 带与拉:tragen 携带", roots:["trag","treib"]},
         {img:"➗ 分与深:teilen 分、tief 深", roots:["teil","tief"]},
         {img:"📅 日与动物与桌", roots:["tag","tier","tisch"]}]},
U:{ line:"围绕 → 下面 → 原初",
  hooks:[{img:"🔄 um- 围绕、unter- 下面", roots:["um","unter"]},
         {img:"🏺 Ur- 最初的:Ursache 原因、Urwald 原始森林", roots:["ur","ur2"]},
         {img:"🚫 un- 否定:unmöglich 不可能", roots:["un","ung"]}]},
V:{ line:"ver- 是最能造词的前缀",
  hooks:[{img:"🔀 ver-:变化、弄错、用尽(verstehen、verlieren、verkaufen)", roots:["ver"]},
         {img:"👨 父与鸟与满", roots:["vater","vogel","voll"]},
         {img:"⏩ vor- 在前、Volk 民族", roots:["vor","volk"]}]},
W:{ line:"变 → 知道 → 想要 → 词",
  hooks:[{img:"🔄 变与转:werden 成为、wenden 转", roots:["werd","wend"]},
         {img:"🧠 知道与指示:wissen 知道、weisen 指", roots:["weis","wirk"]},
         {img:"💭 想要与选:wollen 要、wählen 选", roots:["woll","wähl"]},
         {img:"💬 词与世界与路", roots:["wort","welt","weg"]},
         {img:"💧 水与风与温", roots:["wasser","wind","warm"]}]},
X:{ line:"德语本族词不用 X", hooks:[{img:"🚫 只在借词里:Text、Examen", roots:[]}]},
Y:{ line:"只在借词里", hooks:[{img:"🚫 System、Typ、Physik 都是希腊来源", roots:[]}]},
Z:{ line:"拉 → 数 → 时间 → 二",
  hooks:[{img:"🪢 拉与目标:ziehen 拉、Ziel 目标", roots:["zieh","ziel"]},
         {img:"🔢 数与算:zählen 数、Zahl 数字", roots:["zahl","zeig"]},
         {img:"⏰ 时间与房间", roots:["zeit","zu"]},
         {img:"2️⃣ 二与怀疑:zwei 二、zweifeln 怀疑(两个心)", roots:["zwei","zweifel"]}]},
};

/* ---------- 换元音:德语强变化动词的 Ablaut 系列 ----------
   这是德语最值钱的造词机制:同一副辅音骨架,换一个元音就换一个词性/时态,
   再加前后缀就成一串名词形容词。序列划分依据传统的七类强变化动词。 */
const ABLAUT = [
  { id:"I", name:"第 1 类 ei – ie/i – ie/i", verbs:"schreiben / schrieb / geschrieben",
    words:"die Schrift 文字 · der Schriftsteller 作家 · die Vorschrift 规定 · die Unterschrift 签名",
    more:"bleiben、leihen、reiten、steigen、treiben、scheinen、schweigen" },
  { id:"II", name:"第 2 类 ie/ü – o – o", verbs:"fliegen / flog / geflogen",
    words:"der Flug 飞行 · der Flügel 翅膀 · das Flugzeug 飞机 · der Flughafen 机场",
    more:"biegen(Bogen 弓)、ziehen(Zug 火车)、schließen(Schloss 锁/城堡)、gießen(Guss)" },
  { id:"III", name:"第 3 类 i – a – u/o", verbs:"binden / band / gebunden",
    words:"das Band 带子 · der Bund 联邦 · das Bündnis 同盟 · der Verband 协会 · die Bindung 联系",
    more:"finden(Fund 发现物)、singen(Gesang 歌唱)、trinken(Trank/Trunk)、springen(Sprung 跳)" },
  { id:"IV", name:"第 4 类 e – a – o", verbs:"nehmen / nahm / genommen",
    words:"die Annahme 假定 · die Einnahme 收入 · der Unternehmer 企业家 · die Maßnahme 措施",
    more:"sprechen(Sprache 语言/Spruch 格言)、brechen(Bruch 断裂)、treffen(Treffen 会面)、stehlen(Diebstahl)" },
  { id:"V", name:"第 5 类 e – a – e", verbs:"geben / gab / gegeben",
    words:"die Gabe 天赋 · die Ausgabe 支出/版本 · die Aufgabe 任务 · die Abgabe 缴纳 · das Gift 毒(原义「给的东西」)",
    more:"sehen(Sicht 视野/Gesicht 脸)、lesen(Lesung 朗读)、essen(Essen 饭)、messen(Maß 尺度)" },
  { id:"VI", name:"第 6 类 a – u – a", verbs:"fahren / fuhr / gefahren",
    words:"die Fahrt 行程 · die Erfahrung 经验 · der Fahrer 司机 · die Abfuhr 拒绝 · die Führung 领导",
    more:"tragen(Tracht 服装/Vertrag 合同)、schlagen(Schlag 打击)、graben(Grab 坟墓/Graben 沟)" },
  { id:"VII", name:"第 7 类 元音回原形", verbs:"fallen / fiel / gefallen",
    words:"der Fall 情况/坠落 · der Zufall 偶然 · der Unfall 事故 · der Überfall 袭击 · gefällig 讨喜的",
    more:"halten(Halt 停/Haltung 姿态)、laufen(Lauf 跑)、rufen(Ruf 名声)、heißen(Heißen)" },
];

/* ---------- 前缀与后缀 ---------- */
const AFFIX_DE = {
  pre: [
    { f:"be-", m:"使…、对…直接动作(把不及物变及物)", ex:"kommen 来 → bekommen 得到 · antworten 回答 → beantworten 回答某事" },
    { f:"ge-", m:"完成、集合", ex:"Berg 山 → Gebirge 山脉 · sprechen → Gespräch 谈话" },
    { f:"er-", m:"做成、开始、致死", ex:"finden 找 → erfinden 发明 · schießen 射 → erschießen 射杀" },
    { f:"ver-", m:"弄错、用尽、改变", ex:"laufen 跑 → verlaufen 走错 · kaufen 买 → verkaufen 卖" },
    { f:"zer-", m:"弄碎、拆散", ex:"brechen 破 → zerbrechen 碎 · stören → zerstören 摧毁" },
    { f:"ent-", m:"去掉、脱离、开始", ex:"decken 盖 → entdecken 发现 · fliehen → entfliehen 逃离" },
    { f:"miss-", m:"错、坏", ex:"verstehen 懂 → missverstehen 误解 · Erfolg → Misserfolg 失败" },
    { f:"un-", m:"不、非", ex:"möglich 可能 → unmöglich 不可能 · Glück → Unglück 不幸" },
    { f:"ur-", m:"最初的", ex:"Sache 事 → Ursache 原因 · Wald → Urwald 原始森林" },
    { f:"auf-", m:"向上、打开", ex:"stehen 站 → aufstehen 起床 · machen → aufmachen 打开" },
    { f:"aus-", m:"出、完", ex:"gehen 走 → ausgehen 出门 · trinken → austrinken 喝光" },
    { f:"ein-", m:"进入", ex:"steigen 登 → einsteigen 上车 · laden → einladen 邀请" },
    { f:"mit-", m:"一起", ex:"kommen → mitkommen 一起来 · Arbeiter → Mitarbeiter 同事" },
    { f:"nach-", m:"在后、追", ex:"denken → nachdenken 思考 · Mittag → Nachmittag 下午" },
    { f:"vor-", m:"在前、预先", ex:"stellen 放 → vorstellen 介绍/想象 · Sicht → Vorsicht 小心" },
    { f:"über-", m:"越过、过度", ex:"setzen 放 → übersetzen 翻译 · treiben → übertreiben 夸张" },
    { f:"unter-", m:"在下、中断", ex:"schreiben → unterschreiben 签名 · brechen → unterbrechen 打断" },
    { f:"um-", m:"围绕、改变方向", ex:"ziehen 拉 → umziehen 搬家 · steigen → umsteigen 换乘" },
    { f:"ab-", m:"离开、去掉、完成", ex:"fahren → abfahren 出发 · machen → abmachen 约定" },
    { f:"an-", m:"靠近、开始", ex:"fangen 抓 → anfangen 开始 · rufen → anrufen 打电话" },
  ],
  suf: [
    { f:"-ung", m:"动作或结果(阴性名词)", ex:"bilden 形成 → die Bildung 教育 · wohnen → die Wohnung 住房" },
    { f:"-heit / -keit", m:"抽象性质(阴性)", ex:"frei → die Freiheit 自由 · möglich → die Möglichkeit 可能性" },
    { f:"-schaft", m:"关系、集体(阴性)", ex:"Freund → die Freundschaft 友谊 · Wissen → die Wissenschaft 科学" },
    { f:"-nis", m:"结果、状态", ex:"erlauben → die Erlaubnis 许可 · verstehen → das Verständnis 理解" },
    { f:"-tum", m:"领域、身份(中性)", ex:"Eigen → das Eigentum 财产 · Reich → das Reichtum 财富" },
    { f:"-er / -ler", m:"做这件事的人或工具(阳性)", ex:"lehren → der Lehrer 老师 · Sport → der Sportler 运动员" },
    { f:"-in", m:"女性", ex:"der Lehrer → die Lehrerin 女老师" },
    { f:"-chen / -lein", m:"小(一律中性!)", ex:"Haus → das Häuschen 小屋 · Buch → das Büchlein 小书" },
    { f:"-lich", m:"…的(形容词)", ex:"Freund → freundlich 友好的 · Tag → täglich 每天的" },
    { f:"-ig", m:"具有…的", ex:"Wind → windig 有风的 · Ruhe → ruhig 安静的" },
    { f:"-isch", m:"属于…的(民族、学科)", ex:"Kind → kindisch 幼稚的 · Politik → politisch 政治的" },
    { f:"-bar", m:"可…的", ex:"essen → essbar 可食用的 · sehen → sichtbar 看得见的" },
    { f:"-sam", m:"倾向于…的", ex:"arbeiten → arbeitsam 勤劳的 · langsam 慢的" },
    { f:"-los", m:"没有…的", ex:"Arbeit → arbeitslos 失业的 · Sinn → sinnlos 无意义的" },
    { f:"-voll", m:"充满…的", ex:"Wert → wertvoll 贵重的 · Sinn → sinnvoll 有意义的" },
    { f:"-haft", m:"具有…性质的", ex:"Meister → meisterhaft 精湛的 · Zauber → zauberhaft 迷人的" },
  ],
};
