/* WORD_ART_CAP: one-line description of the artwork shown on each answer card.
   Kept to what the source file documents: title, artist when named, medium, museum.
   Falls back to English when the interface language has no entry. */
const WORD_ART_CAP = {
  abyssus: { zh: "古罗马蓄水池,叙利亚卡纳瓦特——深不见底的地下水窖", en: "Ancient cistern at Qanawat, Syria: a water shaft with no visible bottom" },
  admiratio: { zh: "《赞叹》,布格罗绘,1897年,圣安东尼奥艺术博物馆", en: "\"Admiration\", William-Adolphe Bouguereau, 1897, San Antonio Museum of Art" },
  aeternitas: { zh: "衔尾蛇环绕的世界图式——蛇咬住自己的尾巴,象征无始无终", en: "World-serpent ouroboros: the snake biting its own tail, emblem of endlessness" },
  albus: { zh: "少女像(Kore),雅典卫城出土,约公元前500—490年", en: "Marble Kore from the Acropolis, ca. 500–490 BC" },
  amarus: { zh: "《苏格拉底之死》(局部),雅克-路易·大卫绘", en: "\"The Death of Socrates\" (detail), Jacques-Louis David" },
  amicus: { zh: "两名男子握手的墓碑石,雅典国立考古博物馆", en: "Grave stele of two men clasping hands, National Archaeological Museum, Athens" },
  amor: { zh: "夫妇圆形肖像壁画,庞贝「金手镯之家」", en: "Medallion portrait of a couple, House of the Golden Bracelet, Pompeii" },
  angulus: { zh: "科林斯式柱头,阿尔巴·富肯斯遗址", en: "Corinthian capital, Alba Fucens" },
  anima: { zh: "《追蝴蝶的男孩》,大都会艺术博物馆——蝴蝶在古人眼中就是灵魂", en: "\"Boy Chasing a Butterfly\", Metropolitan Museum of Art: the butterfly was the ancient image of the soul" },
  animus: { zh: "斯巴达战士雕像——古人所说的「气魄」", en: "Sculpture of a Spartan soldier: the ancient image of spirit" },
  annus: { zh: "黄道十二宫马赛克,采波利古会堂", en: "Zodiac mosaic, Tzippori synagogue" },
  ante: { zh: "帕埃斯图姆的希腊神庙,意大利南部", en: "Greek temple at Paestum, southern Italy" },
  anulus: { zh: "罗马时代指环", en: "Roman ring" },
  aper: { zh: "野猪与狮子,阿提卡黑绘双耳杯,科林斯考古博物馆", en: "Boar between lions, Attic black-figure skyphos, Archaeological Museum of Corinth" },
  apis: { zh: "马利亚黄金蜜蜂坠饰,米诺斯文明,伊拉克利翁考古博物馆", en: "Gold bee pendant, Minoan, Archaeological Museum of Heraklion" },
  aqua: { zh: "加尔桥,罗马输水道,法国南部", en: "Pont du Gard, Roman aqueduct, southern France" },
  aquila: { zh: "鹰形青铜牌饰——aquila,罗马军团的鹰旗", en: "Bronze eagle-shaped plaque: the aquila, standard of the Roman legions" },
  ara: { zh: "和平祭坛(Ara Pacis),罗马", en: "Ara Pacis, the Altar of Peace, Rome" },
  arbor: { zh: "《千年橡树》", en: "\"The Thousand-Year-Old Oak\"" },
  arcus: { zh: "提图斯凯旋门,罗马广场", en: "Arch of Titus, Roman Forum" },
  ardor: { zh: "阿喀琉斯的武器,红绘水罐,卢浮宫 E869", en: "The arms of Achilles, red-figure hydria, Louvre E869" },
  argentum: { zh: "博斯科雷阿莱银杯", en: "Silver cup from the Boscoreale hoard" },
  arma: { zh: "希腊重装步兵的整套盔甲,科孚博物馆", en: "Full hoplite armour, Corfu Museum" },
  ars: { zh: "《绘画艺术》,维米尔绘", en: "\"The Art of Painting\", Johannes Vermeer" },
  ascensus: { zh: "《雅各的天梯》,威廉·布莱克绘", en: "\"Jacob's Ladder\", William Blake" },
  aspectus: { zh: "《隆达尼尼的美杜莎》大理石像,慕尼黑古代雕塑展览馆", en: "The Rondanini Medusa, marble, Glyptothek, Munich" },
  auctor: { zh: "荷马胸像,大英博物馆", en: "Portrait bust of Homer, British Museum" },
  aula: { zh: "《马德里王宫王座厅》,威廉·兰肯绘", en: "\"The Throne Room, Royal Palace, Madrid\", William Bruce Ellis Ranken" },
  auris: { zh: "耳形陶制还愿供物,古风时期,纳克索斯考古博物馆", en: "Ear-shaped votive terracotta, Archaic period, Archaeological Museum of Naxos" },
  aurum: { zh: "古希腊黄金花冠,贝纳基博物馆", en: "Ancient Greek gold wreath, Benaki Museum" },
  auxilium: { zh: "《好撒玛利亚人的风景》,伦勃朗绘", en: "\"Landscape with the Good Samaritan\", Rembrandt" },
  avis: { zh: "利维娅别墅餐厅壁画中的飞鸟", en: "Birds in the triclinium fresco, Villa of Livia" },
  bellum: { zh: "罗马士兵墓碑(公元1世纪),布雷西亚圣朱利娅博物馆", en: "Tombstone of a Roman soldier, 1st c. AD, Santa Giulia Museum, Brescia" },
  belua: { zh: "海怪(ketos)马赛克,公元前3世纪,卡乌洛尼亚「龙之家」", en: "Mosaic of a ketos (sea monster), 3rd c. BC, Casa del Drago, Caulonia" },
  blandus: { zh: "《圣母子与幼年施洗约翰》", en: "\"Madonna and Child with the Infant St. John\"" },
  bracchium: { zh: "罗马雕像的青铜手臂残件", en: "Bronze arm from a Roman statue" },
  caelum: { zh: "满天星斗的穹顶,拉韦纳加拉·普拉西提亚陵墓,5世纪", en: "Star-filled dome, Mausoleum of Galla Placidia, Ravenna, 5th c." },
  caeruleus: { zh: "河马小像,埃及蓝釉陶,沃尔特斯艺术博物馆", en: "Hippopotamus figurine, Egyptian blue faience, Walters Art Museum" },
  canis: { zh: "「小心恶犬」(Cave canem)门厅马赛克,庞贝", en: "\"Cave canem\" (Beware of the dog) mosaic, Pompeii" },
  cantus: { zh: "《萨福与阿尔凯奥斯》,阿尔玛-塔德玛绘", en: "\"Sappho and Alcaeus\", Lawrence Alma-Tadema" },
  capillus: { zh: "弗拉维时期发式的女子胸像,阿波罗尼亚(阿尔巴尼亚)", en: "Portrait bust of a woman with Flavian hairstyle, Apollonia, Albania" },
  capra: { zh: "山羊形香膏瓶,东希腊陶器,佛罗伦萨考古博物馆", en: "Goat-shaped aryballos, East Greek pottery, Archaeological Museum, Florence" },
  caput: { zh: "日耳曼尼库斯胸像,盖蒂博物馆", en: "Bust of Germanicus, Getty Museum" },
  carcer: { zh: "马梅尔定监狱旧址,今罗马圣朱塞佩教堂之下", en: "The Mamertine Prison, beneath San Giuseppe dei Falegnami, Rome" },
  carmen: { zh: "《持琴歌者》(Citharoedus)罗马壁画", en: "Citharoedus, the lyre-singer, Roman wall painting" },
  catena: { zh: "罗马时代的铁镣", en: "Roman iron shackle" },
  cauda: { zh: "海马马赛克,英国巴斯罗马浴场", en: "Sea-horse mosaic, Roman Baths, Bath" },
  causa: { zh: "哈德良巴西利卡遗址,明图尔奈——罗马人打官司的地方", en: "Ruins of the Hadrianic basilica at Minturnae, where Romans went to law" },
  caverna: { zh: "《波西利波岩洞远眺》,达尔绘", en: "\"View from a Grotto near Posillipo\", Johan Christian Dahl" },
  celer: { zh: "墨丘利浮雕,奥洛穆茨——足生双翼的快信使", en: "Relief of Mercury, Olomouc: the swift-footed messenger" },
  centum: { zh: "百夫长(centurio)墓碑圆雕像", en: "Funerary medallion of a centurion" },
  cervus: { zh: "《凡尔赛的狄安娜》,与牝鹿同行的女猎神,卢浮宫", en: "Diana of Versailles, the huntress with her deer, Louvre" },
  charta: { zh: "《阴间之书》纸草残片,大都会艺术博物馆", en: "Fragments of a funerary Amduat papyrus, Metropolitan Museum of Art" },
  chorda: { zh: "拨奏基萨拉琴的乐师,巴勒莫考古博物馆", en: "Kithara player, Archaeological Museum of Palermo" },
  cinis: { zh: "骨灰瓮,里昂美术馆", en: "Funerary urn, Musée des Beaux-Arts de Lyon" },
  clamor: { zh: "戏剧面具,八角庭院,梵蒂冈", en: "Theatre masks, Octagonal Court, Vatican" },
  claritas: { zh: "《以马忤斯路上》风景画", en: "\"Landscape with the Walk to Emmaus\"" },
  clavis: { zh: "青铜钥匙,都灵埃及博物馆", en: "Bronze key, Museo Egizio, Turin" },
  clementia: { zh: "《西庇阿的宽仁》,尼古拉-居伊·布勒内绘", en: "\"The Clemency of Scipio\", Nicolas-Guy Brenet" },
  collis: { zh: "罗马广场与七丘,汉森绘", en: "The Roman Forum, painted by Hansen" },
  color: { zh: "听私人演奏的女子们,罗马壁画", en: "Fresco of women listening to a private musical performance" },
  columna: { zh: "多立克柱,雅典卫城山门", en: "Doric column, Propylaea, Acropolis of Athens" },
  concordia: { zh: "和谐女神康科尔狄亚(Concordia)像", en: "Concordia, Roman goddess of harmony" },
  condicio: { zh: "《普罗塞尔庇娜》,罗塞蒂绘——她吃下石榴籽,便受契约所缚", en: "\"Proserpine\", Dante Gabriel Rossetti: the pomegranate seed that bound her to the bargain" },
  consilium: { zh: "《西塞罗在元老院揭发喀提林》,切萨雷·马卡里绘", en: "\"Cicero Denounces Catiline in the Roman Senate\", Cesare Maccari" },
  convivium: { zh: "宴席上的静物壁画:公鸡与石榴、梨、无花果,庞贝", en: "Xenia still-life fresco: a cockerel with pomegranates, pears and figs, Pompeii" },
  cor: { zh: "解剖形还愿供物,公元前3—2世纪,米兰罗瓦蒂基金会", en: "Anatomical votive offerings, 3rd–2nd c. BC, Fondazione Rovati, Milan" },
  corona: { zh: "银骨灰罐与黄金月桂冠,公元前3—2世纪,雅典国立考古博物馆", en: "Silver cinerary vessel and gold laurel wreath, 3rd–2nd c. BC, National Archaeological Museum, Athens" },
  corpus: { zh: "身着托加袍的男子立像,大都会艺术博物馆", en: "Marble statue of a togatus, a man in a toga, Metropolitan Museum of Art" },
  cras: { zh: "厄俄斯(黎明)驾四马车,「奥罗拉画师」绘陶瓶,罗马", en: "Eos, the dawn, in a quadriga; vase by the Aurora Painter, Rome" },
  crimen: { zh: "《玛丽·安托瓦内特听宣起诉状》,爱德华·马修·沃德绘", en: "\"Marie Antoinette Listening to the Act of Accusation\", Edward Matthew Ward" },
  culpa: { zh: "罗马祭坛——赎罪与还愿之处", en: "A Roman altar, where guilt was expiated" },
  cura: { zh: "照料病中修士的场景", en: "Nursing a sick monk" },
  cursus: { zh: "战车赛马赛克,里昂", en: "Circus (chariot race) mosaic, Lyon" },
  custos: { zh: "《赫拉克勒斯与刻耳柏洛斯》,詹波隆那作,沃尔特斯艺术博物馆", en: "\"Hercules and Cerberus\", Giambologna, Walters Art Museum" },
  cymba: { zh: "《卡戎的渡船》", en: "\"Charon's Boat\"" },
  dea: { zh: "《瓦尔瓦基昂的雅典娜》,雅典国立考古博物馆", en: "The Varvakeion Athena, National Archaeological Museum, Athens" },
  decem: { zh: "罗马算盘图解", en: "Diagram of a Roman abacus" },
  dens: { zh: "野猪獠牙头盔,迈锡尼文明,雅典国立考古博物馆", en: "Boar's tusk helmet, Mycenaean, National Archaeological Museum, Athens" },
  descensus: { zh: "《俄耳甫斯》舞台幕布,尚贝里剧院", en: "\"Orpheus\" stage curtain, Théâtre de Chambéry" },
  desiderium: { zh: "《佩涅洛佩与求婚者》,沃特豪斯绘,1912年", en: "\"Penelope and the Suitors\", John William Waterhouse, 1912" },
  desperatio: { zh: "哀恸的妇人陶像,大英博物馆", en: "Terracotta mourning woman, British Museum" },
  deus: { zh: "《奥特里科利的宙斯》胸像,梵蒂冈博物馆", en: "Zeus of Otricoli, bust, Vatican Museums" },
  dexter: { zh: "右手形还愿供物,大都会艺术博物馆", en: "Votive right hand, Metropolitan Museum of Art" },
  diadema: { zh: "黄金冠饰,公元前16世纪,迈锡尼考古博物馆", en: "Gold diadem, 16th c. BC, Archaeological Museum of Mycenae" },
  dies: { zh: "太阳神赫利俄斯浮雕,特洛伊雅典娜神庙陇间板,柏林老博物馆", en: "Helios metope from the Temple of Athena at Troy, Altes Museum, Berlin" },
  digitus: { zh: "君士坦丁巨像的手,罗马卡比托利欧博物馆", en: "The hand of the Colossus of Constantine, Capitoline Museums, Rome" },
  dolor: { zh: "墓碑石,雅典国立考古博物馆", en: "Grave stele, National Archaeological Museum, Athens" },
  domina: { zh: "手持铁笔与蜡板的女子(或称萨福),庞贝壁画", en: "Fresco of a woman (called Sappho) holding stylus and tablet, Pompeii" },
  dominus: { zh: "佩戴护身符(bulla)的罗马少年胸像", en: "Bust of a Roman boy wearing a bulla" },
  domus: { zh: "米南德之家,庞贝", en: "House of Menander, Pompeii" },
  donum: { zh: "《木马入特洛伊》,乔凡尼·多梅尼科·提埃波罗绘", en: "\"The Procession of the Trojan Horse in Troy\", Giovanni Domenico Tiepolo" },
  draco: { zh: "伊阿宋与巨龙,杜里斯绘陶杯,梵蒂冈博物馆", en: "Jason and the dragon, cup by Douris, Vatican Museums" },
  dulcis: { zh: "蜂巢——古人所知最甜的东西", en: "A honeycomb: the sweetest thing the ancients knew" },
  durus: { zh: "采石场中未完成的巨像,公元前7世纪,纳克索斯岛阿波罗纳斯", en: "Unfinished colossal statue in the quarry, 7th c. BC, Apollonas, Naxos" },
  elementum: { zh: "四季马赛克,安塔基亚考古博物馆", en: "Four Seasons mosaic, Antakya Archaeological Museum" },
  eloquentia: { zh: "《西塞罗在元老院揭发喀提林》,切萨雷·马卡里绘——古代雄辩术的名场面", en: "\"Cicero Denounces Catiline in the Roman Senate\", Cesare Maccari: the classic scene of ancient oratory" },
  epistula: { zh: "手持蜡板与铁笔的女子(俗称萨福),庞贝壁画", en: "Fresco of a woman (called Sappho) with wax tablet and stylus, Pompeii" },
  equus: { zh: "《木马入特洛伊》,乔凡尼·多梅尼科·提埃波罗绘", en: "\"The Procession of the Trojan Horse in Troy\", Giovanni Domenico Tiepolo" },
  error: { zh: "《嘲弄波吕斐摩斯的尤利西斯》草稿,透纳绘,泰特美术馆", en: "Sketch for \"Ulysses Deriding Polyphemus\", J. M. W. Turner, Tate Britain" },
  exitus: { zh: "维蒂之家的门道与地面,庞贝", en: "Doorway and flooring, House of the Vettii, Pompeii" },
  fabula: { zh: "《诵读荷马》,阿尔玛-塔德玛绘", en: "\"A Reading from Homer\", Lawrence Alma-Tadema" },
  fama: { zh: "《声誉女神》(La Fama)", en: "\"La Fama\", the personification of Fame" },
  fames: { zh: "庞贝壁画中的圆饼与果盘——两千年前的一餐", en: "Flatbread and fruit in a Pompeian fresco: a meal from two thousand years ago" },
  familia: { zh: "和平祭坛浮雕上的孩子们,罗马", en: "Children on the Ara Pacis, Rome" },
  fatum: { zh: "《三位命运女神》,弗朗切斯科·萨尔维亚蒂绘", en: "\"The Three Fates\", Francesco Salviati" },
  fax: { zh: "密特拉宴饮浮雕,卢浮宫——两侧为持火炬的侍神", en: "Mithraic banquet relief with torch-bearers, Louvre" },
  felis: { zh: "猫捕禽马赛克,那不勒斯国立考古博物馆", en: "Cat mosaic, National Archaeological Museum, Naples" },
  felix: { zh: "命运女神福尔图娜像——罗马人的幸运与丰饶之神", en: "Statue of Fortuna, Roman goddess of luck and plenty" },
  femina: { zh: "夫妇肖像圆形壁画,斯塔比亚阿里安娜别墅", en: "Fresco medallion with portraits of a man and a woman, Villa Arianna, Stabiae" },
  fenestra: { zh: "《窗边读信的少女》,维米尔绘", en: "\"Girl Reading a Letter by an Open Window\", Johannes Vermeer" },
  fera: { zh: "《俄耳甫斯以乐驯兽》,罗兰特·萨弗里绘,莫瑞泰斯皇家美术馆", en: "\"Orpheus Charming the Animals with his Music\", Roelant Savery, Mauritshuis" },
  ferox: { zh: "《阿雷佐的奇美拉》青铜像——狮头、羊身、蛇尾", en: "The Chimera of Arezzo: lion's head, goat's body, serpent's tail" },
  ferrum: { zh: "伊比利亚弯刀(falcata)与罗马短剑(gladius)复制品", en: "Iberian falcata and a replica gladius" },
  festinatio: { zh: "赫尔墨斯(墨丘利)青铜像,盖蒂别墅——足生双翼的快信使", en: "Hermes (Mercury), bronze at the Getty Villa: the messenger with winged feet" },
  fides: { zh: "「右手相握」(dextrarum iunctio)——罗马人以此表示信守之约", en: "Dextrarum iunctio, the Roman clasped-hands sign of a pledge kept" },
  fiducia: { zh: "《坚毅》,波提切利绘,乌菲齐美术馆", en: "\"Fortitude\", Sandro Botticelli, Uffizi" },
  filia: { zh: "少女墓碑石,大理石,出土于比雷埃夫斯,公元前4世纪上半叶", en: "Marble funerary stele of a young girl, Piraeus, first half of the 4th c. BC" },
  filius: { zh: "埃涅阿斯背父携子出逃的戏仿壁画,斯塔比亚,那不勒斯国立考古博物馆", en: "Caricature of Aeneas fleeing with his father and son, Stabiae, National Archaeological Museum, Naples" },
  filum: { zh: "《阿里阿德涅把线团交给忒修斯》,蒂施拜因绘,1779年", en: "\"Ariadne Helping Theseus by Giving Him a Ball of Thread\", J. H. Tischbein, 1779" },
  finis: { zh: "标示罗马帝国疆界的界石(现代立石)", en: "Boundary stone marking the edge of the Roman Empire (modern marker)" },
  flamma: { zh: "《忏悔的抹大拉》,卡洛·萨拉切尼绘,威尼斯学院美术馆", en: "\"The Penitent Magdalene\", Carlo Saraceni, Gallerie dell'Accademia, Venice" },
  flavus: { zh: "古希腊黄金花冠,贝纳基博物馆", en: "Ancient Greek gold wreath, Benaki Museum" },
  flos: { zh: "《春》,波提切利绘,乌菲齐美术馆", en: "\"La Primavera\", Sandro Botticelli, Uffizi" },
  flumen: { zh: "河神像,敖德萨", en: "Sculpture of a river god, Odessa" },
  fluvius: { zh: "台伯河神像,罗马元老宫阶前", en: "The river god Tiber, staircase of the Palazzo Senatorio, Rome" },
  foedus: { zh: "《法美友好通商与同盟条约签订》", en: "\"Signing of the Treaty of Amity and Commerce between France and the United States\"" },
  fons: { zh: "海神俄刻阿诺斯,罗马特雷维喷泉", en: "Oceanus, Trevi Fountain, Rome" },
  fortis: { zh: "赫拉克勒斯马赛克,罗马时期,约公元200年,大英博物馆", en: "Mosaic of Hercules, Roman, ca. AD 200, British Museum" },
  frater: { zh: "狄俄斯库里兄弟还愿浮雕,公元前6世纪,斯巴达考古博物馆", en: "Votive relief of the Dioscuri, 6th c. BC, Archaeological Museum of Sparta" },
  frigus: { zh: "《冬之寓言》,亚伯拉罕·布洛马特绘", en: "\"Allegory of Winter\", Abraham Bloemaert" },
  fuga: { zh: "《埃涅阿斯与安喀塞斯逃离焚烧中的特洛伊》,弗朗索瓦·德·诺梅绘", en: "\"Aeneas and Anchises Fleeing the Burning of Troy\", François de Nomé" },
  funus: { zh: "狄庇隆双耳瓶上的停灵(prothesis)场面,几何风格", en: "Prothesis (lying-in-state) scene, Dipylon amphora, Geometric style" },
  galea: { zh: "科林斯式青铜头盔,雅典国立考古博物馆", en: "Corinthian bronze helmet, National Archaeological Museum, Athens" },
  gaudium: { zh: "起舞的迈那得斯浮雕,大都会艺术博物馆", en: "Marble relief with a dancing maenad, Metropolitan Museum of Art" },
  gelu: { zh: "《冰霜集市》——泰晤士河封冻时在冰上开的集市", en: "\"The Frost Fair\", the market held on the frozen Thames" },
  gemma: { zh: "《奥古斯都宝石浮雕》(Gemma Augustea)", en: "The Gemma Augustea cameo" },
  genius: { zh: "家神(Genius)与蛇,庞贝家庭神龛壁画", en: "Genius with a serpent, lararium painting, Pompeii" },
  genu: { zh: "屈膝托碑的立像,大都会艺术博物馆", en: "Stelophorous kneeling statue of Bay, Metropolitan Museum of Art" },
  gigas: { zh: "《巴列塔巨像》青铜像——高逾五米的晚期罗马皇帝像", en: "The Colossus of Barletta, a late-Roman bronze emperor over five metres tall" },
  glacies: { zh: "《城堡边溜冰的冬景》,亨德里克·阿弗坎普绘", en: "\"A Winter Scene with Skaters near a Castle\", Hendrick Avercamp" },
  gladius: { zh: "美因茨短剑(gladius),罗马军团制式配剑", en: "The Mainz gladius, the standard sword of the Roman legions" },
  gloria: { zh: "凯旋队列浮雕,提图斯凯旋门内壁,罗马广场", en: "Triumphal procession relief, Arch of Titus, Roman Forum" },
  gradus: { zh: "以弗所音乐厅的层层石阶", en: "The tiered steps of the odeon at Ephesus" },
  gurges: { zh: "吉尔雷讽刺版画中的极地漩涡", en: "The polar whirlpool in a Gillray satirical print" },
  gutta: { zh: "荷叶上的一滴水,水珠里困着一只小蛙", en: "A juvenile frog inside a drop of water on a lotus leaf" },
  guttur: { zh: "塞拉皮斯像——脚边常伴三头犬刻耳柏洛斯", en: "Statue of Serapis, usually shown with three-headed Cerberus at his feet" },
  harmonia: { zh: "阿波罗奏琴陶杯,德尔斐考古博物馆", en: "Kylix with Apollo and his lyre, Archaeological Museum of Delphi" },
  hasta: { zh: "铁器时代的矛头", en: "Iron Age spear head" },
  herba: { zh: "利维娅别墅花园壁画(局部),罗马普里马波尔塔,公元前30—20年", en: "Garden fresco from the Villa of Livia, Prima Porta, 30–20 BC (detail)" },
  heri: { zh: "安菲阿剌俄斯圣所遗址:昔日的住宅与集市", en: "Ruins of houses and the agora, sanctuary of Amphiaraus" },
  heros: { zh: "亚历山大大帝胸像", en: "Bust of Alexander the Great" },
  historia: { zh: "《历史女神克利俄》,夏尔·梅尼耶绘", en: "\"Clio, Muse of History\", Charles Meynier" },
  hodie: { zh: "古罗马日晷,柏林古代收藏馆", en: "Ancient Roman sundial, Antikensammlung Berlin" },
  honor: { zh: "《罗马凯旋式》,鲁本斯绘,约1630年", en: "\"A Roman Triumph\", Peter Paul Rubens, ca. 1630" },
  horror: { zh: "戈耳工面具屋檐瓦当,大都会艺术博物馆——古人挂它辟邪", en: "Terracotta gorgoneion antefix, Metropolitan Museum of Art: hung to frighten evil away" },
  hortus: { zh: "利维娅别墅花园壁画,罗马", en: "Garden fresco, Villa of Livia, Rome" },
  hostis: { zh: "波斯弓箭手饰带,苏萨大流士王宫,卢浮宫", en: "Frieze of Persian archers, Palace of Darius at Susa, Louvre" },
  ianua: { zh: "推拉门的门轨,庞贝", en: "Sliding door tracks, Pompeii" },
  ignis: { zh: "维斯塔神庙,罗马广场——庙中圣火终年不熄", en: "Temple of Vesta, Roman Forum, where the sacred fire never went out" },
  immortalitas: { zh: "《普桑、勒叙尔与勒布伦的升天》,卢浮宫", en: "\"The Apotheosis of Poussin, Le Sueur and Le Brun\", Louvre" },
  imperium: { zh: "奥古斯都像", en: "Statue of Augustus" },
  inferi: { zh: "《冥河渡口》,约阿希姆·帕蒂尼尔绘", en: "\"Charon Crossing the Styx\", Joachim Patinir" },
  initium: { zh: "《曙光女神奥罗拉》,圭多·雷尼绘", en: "\"Aurora\", Guido Reni" },
  innocens: { zh: "《天真与诡诈的寓言》,马尔滕·范·海姆斯凯克绘,大英博物馆", en: "\"An Allegory of Innocence and Guile\", Maarten van Heemskerck, British Museum" },
  insula: { zh: "《死亡之岛》第三版,阿诺德·勃克林绘", en: "\"Isle of the Dead\", third version, Arnold Böcklin" },
  intra: { zh: "古罗马住宅内景", en: "Interior of an ancient Roman house" },
  invidia: { zh: "《时间与真理战胜嫉妒与虚伪》,扬·范·登·霍克绘", en: "\"Allegory of Time and Truth Triumphing over Envy and Falsehood\", Jan van den Hoecke" },
  ira: { zh: "战神马尔斯像,罗马卡比托利欧博物馆", en: "Statue of Mars, Capitoline Museums, Rome" },
  iter: { zh: "《阿庇亚大道》,布拉斯卡萨绘,苏格兰国立美术馆", en: "\"La Via Appia\", Jacques Raymond Brascassat, National Galleries of Scotland" },
  iudex: { zh: "《所罗门的审判》,塞巴斯蒂亚诺·德尔·皮翁博绘", en: "\"The Judgment of Solomon\", Sebastiano del Piombo" },
  ius: { zh: "青铜法律铭文残片,大都会艺术博物馆", en: "Fragmentary bronze legal inscription, Metropolitan Museum of Art" },
  iustitia: { zh: "正义之秤雕像,米德尔斯堡", en: "Scales of Justice statue, Middlesbrough" },
  labyrinthus: { zh: "迷宫马赛克,中央为忒修斯与米诺陶,庞贝「迷宫之家」", en: "Labyrinth mosaic with Theseus and the Minotaur at its centre, House of the Labyrinth, Pompeii" },
  lacrima: { zh: "白底细颈瓶,「塔纳托斯画师」绘,沃尔特斯艺术博物馆", en: "White-ground lekythos by the Thanatos Painter, Walters Art Museum" },
  lacus: { zh: "《马焦雷湖风景》,欧金尼奥·吉尼乌斯绘", en: "\"Landscape on Lake Maggiore\", Eugenio Gignous" },
  laetus: { zh: "起舞的迈那得斯,皮同绘陶瓶,大英博物馆 F253", en: "Dancing maenad, vase by Python, British Museum F253" },
  laurus: { zh: "银骨灰罐与黄金月桂冠,公元前3—2世纪,雅典国立考古博物馆", en: "Silver vessel and gold laurel wreath, 3rd–2nd c. BC, National Archaeological Museum, Athens" },
  lector: { zh: "学堂场景陶杯,杜里斯绘", en: "School scene on a cup by Douris" },
  leo: { zh: "狮门,哈图沙(赫梯古都)", en: "The Lion Gate at Hattusa" },
  lex: { zh: "《授维斯帕先权力法》青铜法板,公元69—70年,罗马卡比托利欧博物馆", en: "Lex de Imperio Vespasiani, bronze law tablet, AD 69–70, Capitoline Museums, Rome" },
  liber: { zh: "维吉尔像,《罗马维吉尔》抄本第14叶", en: "Portrait of Virgil, Vergilius Romanus, folio 14r" },
  libertas: { zh: "自由女神像,纽约", en: "Statue of Liberty, New York City" },
  lilium: { zh: "春景壁画(百合与燕子),锡拉岛阿克罗蒂里,雅典国立考古博物馆", en: "Spring landscape fresco with lilies, Akrotiri, Thera, National Archaeological Museum, Athens" },
  limus: { zh: "陶土献版,彭特斯库菲亚——描绘制陶劳作,卢浮宫", en: "Clay votive plaque from Penteskouphia showing potters at work, Louvre" },
  lingua: { zh: "拉丁碑铭,杜加古城(突尼斯)", en: "Latin epigraphy at Dougga, Tunisia" },
  littera: { zh: "罗马墓志铭,公元69年,长音 i 上带尖符(apex)", en: "Roman grave inscription, AD 69, with an apex marking a long i" },
  lucerna: { zh: "罗马陶油灯", en: "Roman terracotta oil lamp" },
  luctus: { zh: "《哭泣的妇女石棺》,伊斯坦布尔考古博物馆", en: "Sarcophagus of the Mourning Women, Istanbul Archaeological Museums" },
  lumen: { zh: "烛光画,乔治·德·拉图尔绘", en: "Candlelight scene, Georges de La Tour" },
  luna: { zh: "月神塞勒涅圆盾浮雕,罗马国立博物馆(戴克里先浴场)", en: "Clipeus with Selene, the moon goddess, Museo Nazionale Romano" },
  lupus: { zh: "《卡比托利欧母狼》青铜像,罗马", en: "The Capitoline Wolf, bronze, Rome" },
  lux: { zh: "《地理学家》,维米尔绘——窗光下的工作台", en: "\"The Geographer\", Johannes Vermeer" },
  lyra: { zh: "巴尔比同琴(barbitos)——古希腊的长臂里拉琴", en: "The barbitos, the long-armed lyre of ancient Greece" },
  magnus: { zh: "君士坦丁巨像残件,罗马卡比托利欧博物馆", en: "Fragments of the Colossus of Constantine, Capitoline Museums, Rome" },
  maiestas: { zh: "《荣耀基督》(Christ in Majesty)镶嵌画,巴黎圣心大教堂", en: "Christ in Majesty, mosaic, Sacré-Cœur, Paris" },
  manus: { zh: "拳斗士的青铜手,大都会艺术博物馆", en: "Bronze hand of a boxer, Metropolitan Museum of Art" },
  mare: { zh: "奥德修斯航海马赛克,突尼斯巴尔多博物馆", en: "Mosaic of Odysseus at sea, Bardo Museum, Tunisia" },
  marmor: { zh: "卡拉拉附近的大理石采石场——古罗马雕像用石的产地", en: "Marble quarry near Carrara, source of the stone for Roman statuary" },
  mater: { zh: "母与子陶像,罗马还愿供物,惠康收藏", en: "Clay-baked mother and child, Roman votive offering, Wellcome Collection" },
  memoria: { zh: "妇人与男孩的墓碑石,希腊埃雷特里亚", en: "Funerary stele of a woman and a boy, Eretria, Greece" },
  mensa: { zh: "戴克里先的石桌(mensa),斯普利特城市博物馆", en: "Diocletian's mensa (table), City Museum, Split" },
  merces: { zh: "「卡戎的船钱」——含在死者口中付给摆渡人的钱币", en: "Charon's obol, the coin placed in the mouth of the dead to pay the ferryman" },
  miles: { zh: "罗马军团士兵浮雕,为图拉真而作,公元2世纪,出土于波佐利", en: "Relief of a Roman legionary honouring Trajan, 2nd c. AD, from Pozzuoli" },
  mille: { zh: "罗马里程碑(milliarium),米德尔顿", en: "Roman milestone, Middleton" },
  mirabilis: { zh: "《罗得岛巨像》,费迪南德·克纳布绘,1886年——古代七大奇迹之一", en: "\"The Colossus of Rhodes\", Ferdinand Knab, 1886: one of the seven wonders" },
  mirus: { zh: "提洛岛,阿波罗诞生的圣岛", en: "Delos, the sacred island where Apollo was born" },
  mollis: { zh: "《谦逊》,大理石像,让-路易·雅莱作,1833年", en: "\"Modesty\", marble, Jean-Louis Jaley, 1833" },
  mons: { zh: "奥林匹斯山,希腊", en: "Mount Olympus, Greece" },
  monstrum: { zh: "《米诺陶》,乔治·弗雷德里克·瓦茨绘", en: "\"The Minotaur\", George Frederic Watts" },
  monumentum: { zh: "图拉真纪功柱,罗马", en: "Trajan's Column, Rome" },
  mors: { zh: "塔纳托斯——希腊人心目中的死神", en: "Thanatos, the Greek personification of death" },
  multitudo: { zh: "《亚历山大进入巴比伦》,夏尔·勒布伦绘", en: "\"Entry of Alexander into Babylon\", Charles Le Brun" },
  mundus: { zh: "古代天球仪", en: "An ancient globe" },
  murmur: { zh: "《耳语》,让-弗朗索瓦·米勒绘,英国国家美术馆", en: "\"The Whisper\", Jean-François Millet, National Gallery" },
  murus: { zh: "奥勒良城墙与阿西纳里门,罗马", en: "The Aurelian Walls at the Porta Asinaria, Rome" },
  mus: { zh: "鼠形油灯,洛杉矶郡艺术博物馆", en: "Mouse-shaped lamp, LACMA" },
  musica: { zh: "缪斯石棺,卢浮宫 MR880", en: "Sarcophagus of the Muses, Louvre MR880" },
  nasus: { zh: "罗马将军胸像", en: "Portrait bust of a Roman general" },
  natura: { zh: "植物壁画,庞贝", en: "Painted plants, fresco from Pompeii" },
  nauta: { zh: "奥德修斯与塞壬,红绘陶瓶,大英博物馆 E440", en: "Odysseus and the Sirens, red-figure vase, British Museum E440" },
  navis: { zh: "《船队巡游》壁画,锡拉岛阿克罗蒂里", en: "\"Ship Procession\" fresco, Akrotiri, Thera" },
  nebula: { zh: "《雾海上的旅人》,卡斯帕·大卫·弗里德里希绘", en: "\"Wanderer above the Sea of Fog\", Caspar David Friedrich" },
  niger: { zh: "黑绘颈式双耳瓶,慕尼黑国立古代艺术博物馆", en: "Black-figure neck amphora, Staatliche Antikensammlungen, Munich" },
  nomen: { zh: "罗马墓碑,公元100年前后——碑上首先刻的就是名字", en: "Roman tombstone, ca. AD 100: the name comes first" },
  novem: { zh: "九位缪斯的石棺,卢浮宫 MR880", en: "Sarcophagus of the nine Muses, Louvre MR880" },
  novus: { zh: "图密善银币,罗马帝国钱币", en: "Coin of Domitian, Roman imperial currency" },
  nubes: { zh: "《云的习作》,约翰·康斯太勃尔绘", en: "\"Cloud Study\", John Constable" },
  numen: { zh: "家庭神龛(lararium)壁画,庞贝切伊之家", en: "Lararium fresco, House of the Ceii, Pompeii" },
  numerus: { zh: "罗马算盘复原件", en: "Reconstruction of a Roman abacus" },
  nummus: { zh: "罗马银币窖藏,出土于波兰奇霍布日", en: "Hoard of Roman silver coins from Cichobórz, Poland" },
  numquam: { zh: "水钟(clepsydra),大都会艺术博物馆——时间从不倒流", en: "Clepsydra, a water clock, Metropolitan Museum of Art: time never runs backwards" },
  nuptiae: { zh: "《阿尔多布兰迪尼婚礼》壁画,梵蒂冈", en: "The Aldobrandini Wedding, Roman fresco, Vatican" },
  nympha: { zh: "《纳克索斯岛上的阿里阿德涅》,伊芙琳·德·摩根绘,1877年", en: "\"Ariadne in Naxos\", Evelyn De Morgan, 1877" },
  oblivio: { zh: "《忘川之水与至福平原》,斯坦霍普绘,1889年", en: "\"The Waters of Lethe by the Plains of Elysium\", J. R. Spencer Stanhope, 1889" },
  obscuritas: { zh: "《林岸夜景》,小汉斯·荷尔拜因绘", en: "\"Night Scene on a Wooded Riverbank\", Hans Holbein the Younger" },
  octo: { zh: "章鱼纹米诺斯陶瓶——八条腕足", en: "Minoan vase with an octopus motif: eight arms" },
  oculus: { zh: "荷鲁斯之眼护身符(Wedjat),古埃及,用以辟除邪眼", en: "Wedjat-eye amulets, ancient Egypt, worn against the evil eye" },
  opes: { zh: "「埃伊纳宝藏」,古希腊金饰,大英博物馆", en: "The Aegina Treasure, ancient Greek goldwork, British Museum" },
  opus: { zh: "《雕塑家的工作室》,赫拉德·托马斯绘", en: "\"Sculptor's Studio\", Gerard Thomas" },
  orbis: { zh: "浑仪(armillary sphere)图版——以圈环表示天体的运行", en: "Armillary sphere: the heavens modelled in rings" },
  ordo: { zh: "凯旋队列浮雕宝石,威尼斯科雷尔博物馆", en: "Roman cameo of a triumphal procession, Museo Correr, Venice" },
  os: { zh: "宙斯戏剧面具复制品,古希腊", en: "Replica of an ancient Greek theatrical mask of Zeus" },
  ovis: { zh: "抱羊人几何风格小像,哈佛萨克勒博物馆", en: "Geometric-style figurine of a man with a ram, Harvard Art Museums" },
  pactum: { zh: "握手道别的墓碑浮雕(dexiosis),埃伊纳,公元前5世纪", en: "Funerary relief with the clasped-hand dexiosis, Aegina, 5th c. BC" },
  palus: { zh: "《冥河渡口》,约阿希姆·帕蒂尼尔绘", en: "\"Charon Crossing the Styx\", Joachim Patinir" },
  parvus: { zh: "塔纳格拉陶俑,柏林老博物馆", en: "Tanagra figurine, Altes Museum, Berlin" },
  passus: { zh: "祭司列队浮雕,阿拉贾霍裕克,安纳托利亚文明博物馆", en: "Procession of priests, orthostat relief, Alacahöyük, Museum of Anatolian Civilizations" },
  pater: { zh: "埃涅阿斯背父逃离特洛伊,「尼科克塞诺斯画师」绘陶瓶", en: "Aeneas escaping from Troy with his father, vase by the Nikoxenos Painter" },
  patientia: { zh: "《织机前的佩涅洛佩》,安杰莉卡·考夫曼绘", en: "\"Penelope at her Loom\", Angelica Kauffman" },
  patria: { zh: "罗马女神(Dea Roma)像,罗马卡比托利欧广场", en: "Dea Roma, Piazza del Campidoglio, Rome" },
  pes: { zh: "着罗马凉鞋的还愿足像,献给伊西斯与塞拉皮斯", en: "Votive foot in a Roman sandal, dedicated to Isis and Serapis" },
  phantasma: { zh: "白底细颈瓶:墓前的祭扫,波士顿美术馆", en: "White-ground lekythos: a visit to the tomb, Museum of Fine Arts, Boston" },
  pictura: { zh: "「鲁弗斯」涂鸦式人像,庞贝神秘别墅", en: "\"Rufus est\" caricature, Villa of the Mysteries, Pompeii" },
  piscis: { zh: "鱼类图谱马赛克,那不勒斯国立考古博物馆", en: "Fish catalogue mosaic, National Archaeological Museum, Naples" },
  plausus: { zh: "锡代古罗马剧场——掌声响起的地方", en: "The Roman theatre at Side, where the applause rang out" },
  poculum: { zh: "带式陶杯(kylix),大都会艺术博物馆", en: "Band-cup kylix, Metropolitan Museum of Art" },
  poeta: { zh: "所谓「萨福」肖像壁画,庞贝", en: "The so-called Sappho fresco, Pompeii" },
  populus: { zh: "罗马广场——公民聚集议事之地", en: "The Roman Forum, where the people gathered" },
  porcus: { zh: "野猪小像,洛杉矶郡艺术博物馆", en: "Figurine of a wild pig, LACMA" },
  porta: { zh: "尼格拉城门(Porta Nigra),特里尔", en: "Porta Nigra, Trier" },
  portitor: { zh: "《卡戎》,奥列克桑德尔·利托夫琴科绘", en: "\"Charon\", Oleksandr Lytovchenko" },
  portus: { zh: "《圣乌尔苏拉登船的海港》,克洛德·洛兰绘", en: "\"Seaport with the Embarkation of Saint Ursula\", Claude Lorrain" },
  post: { zh: "安东尼·庇护所建凯旋门遗迹,埃莱夫西纳德墨忒尔圣所之外", en: "Ruins of the triumphal arch of Antoninus Pius, outside the sanctuary at Eleusis" },
  potentia: { zh: "托勒密三世铜币:宙斯-阿蒙头像与踏雷霆的鹰", en: "Bronze coin of Ptolemy III: Zeus-Ammon and the eagle on a thunderbolt" },
  potestas: { zh: "扈从(lictor)浮雕——肩扛法西斯束棒,维罗纳考古博物馆", en: "Relief of a lictor carrying the fasces, Archaeological Museum, Verona" },
  potio: { zh: "陶制饮杯(kylix)残片,大都会艺术博物馆", en: "Fragments of a terracotta kylix, Metropolitan Museum of Art" },
  praemium: { zh: "泛雅典娜赛会奖品陶瓶,大都会艺术博物馆——瓶内盛橄榄油作彩头", en: "Panathenaic prize amphora, Metropolitan Museum of Art: filled with olive oil as the prize" },
  pratum: { zh: "《黄花的原野》", en: "\"A Field of Yellow Flowers\"" },
  preces: { zh: "宙斯还愿浮雕,德累斯顿", en: "Votive relief to Zeus, Dresden" },
  principium: { zh: "饰有曙光女神奥罗拉的手镯,V&A 博物馆", en: "Bracelet with Aurora, the dawn, Victoria and Albert Museum" },
  profundum: { zh: "沉船残骸——沉入深处的船", en: "A shipwreck lying in the deep" },
  promissum: { zh: "《明斯特和约的宣誓》,赫拉德·特博赫绘,1648年", en: "\"The Ratification of the Treaty of Münster\", Gerard ter Borch, 1648" },
  puella: { zh: "手持铁笔与蜡板的少女,庞贝壁画", en: "Girl with stylus and writing tablets, fresco from Pompeii" },
  puer: { zh: "少年像,大英博物馆", en: "Statue of a young boy, British Museum" },
  pugna: { zh: "角斗士头盔,庞贝角斗士营房出土,公元1世纪", en: "Gladiator helmet from the barracks at Pompeii, 1st c. AD" },
  purpureus: { zh: "查士丁尼镶嵌画,拉韦纳圣维塔莱教堂——紫袍是帝王专用之色", en: "Justinian mosaic, San Vitale, Ravenna: purple was the emperor's colour" },
  quattuor: { zh: "《四季》罗马马赛克", en: "\"The Four Seasons\", Roman mosaic" },
  quinque: { zh: "罗马数字 V", en: "The Roman numeral V" },
  rana: { zh: "青蛙青铜小像,都灵埃及博物馆", en: "Bronze frog statuette, Museo Egizio, Turin" },
  ratis: { zh: "古代小船模型,日内瓦艺术与历史博物馆", en: "Ancient boat model, Musée d'art et d'histoire, Geneva" },
  reditus: { zh: "《尤利西斯归来》,爱德华·阿米蒂奇绘,利兹美术馆", en: "\"The Return of Ulysses\", Edward Armitage, Leeds Art Gallery" },
  regina: { zh: "女子侧面像壁画,或为克娄巴特拉七世肖像", en: "Fresco of a woman in profile, possibly Cleopatra VII" },
  regnum: { zh: "《朱庇特与忒提斯》,安格尔绘", en: "\"Jupiter and Thetis\", Jean-Auguste-Dominique Ingres" },
  remus: { zh: "三列桨战船浮雕残件(勒诺尔曼浮雕),公元前4世纪", en: "Fragment of the Lenormant relief showing a trireme, 4th c. BC" },
  retro: { zh: "俄耳甫斯与欧律狄刻彩陶盘,卡洛·安东尼奥·格鲁埃工坊,沃尔特斯艺术博物馆", en: "Plate with Orpheus and Eurydice, workshop of Carlo Antonio Grue, Walters Art Museum" },
  rex: { zh: "埃勾斯王求问神谕,红绘陶杯,柏林古代收藏馆 F2538", en: "King Aegeus consulting the oracle, red-figure cup, Antikensammlung Berlin F2538" },
  ripa: { zh: "《河岸牧牛的林地风景》,英国画派,英国国民信托藏", en: "\"Wooded Landscape with Cows at a Riverbank\", British School, National Trust" },
  rivus: { zh: "《林中小溪》,大都会艺术博物馆", en: "\"The Brook in the Woods\", Metropolitan Museum of Art" },
  rosa: { zh: "《赫利奥加巴卢斯的玫瑰》,阿尔玛-塔德玛绘", en: "\"The Roses of Heliogabalus\", Lawrence Alma-Tadema" },
  rota: { zh: "命运之轮,《布兰诗歌》抄本插图", en: "The wheel of fortune, from the Carmina Burana manuscript" },
  ruber: { zh: "阿提卡红绘钟形克拉特,约公元前390年", en: "Attic red-figure bell krater, ca. 390 BC" },
  sacrificium: { zh: "罗马妇人的墓前祭坛(局部),德累斯顿", en: "Funerary altar of a Roman woman (detail), Dresden" },
  sagitta: { zh: "斯基泰弓箭手陶盘,埃庇克提托斯绘,大英博物馆 E135", en: "Scythian archer plate by Epiktetos, British Museum E135" },
  sanguis: { zh: "家族墓碑浮雕,大都会艺术博物馆——sanguis 也指血脉亲族", en: "Marble funerary relief of a family, Metropolitan Museum of Art: sanguis also means kinship" },
  sapientia: { zh: "雅典银币:一面雅典娜,一面猫头鹰——智慧的双面", en: "Silver tetradrachm with Athena and her owl: the two faces of wisdom" },
  scaena: { zh: "古罗马剧场舞台后方的遗迹,西西里陶尔米纳", en: "Ruins behind the stage of the Roman theatre, Taormina, Sicily" },
  sceptrum: { zh: "李锡尼铜币:朱庇特手持权杖与胜利女神", en: "Bronze coin of Licinius: Jupiter with sceptre and Victory" },
  scriptor: { zh: "执笔的夫妇像壁画,庞贝,那不勒斯国立考古博物馆", en: "Fresco of a couple with writing implements, Pompeii, National Archaeological Museum, Naples" },
  scutum: { zh: "罗马大盾(scutum)复原件,魏森堡罗马博物馆", en: "Reconstruction of a Roman scutum, Römermuseum Weißenburg" },
  secretum: { zh: "厄琉息斯秘仪题材还愿浮雕,雅典国立考古博物馆", en: "Votive relief with an Eleusinian theme, National Archaeological Museum, Athens" },
  sella: { zh: "「库鲁尔椅」(sella curulis)——罗马高级官员的折叠坐具", en: "The sella curulis, folding seat of high Roman magistrates" },
  semper: { zh: "衔尾蛇——首尾相接,象征永无终止", en: "The ouroboros: head joined to tail, sign of what never ends" },
  sententia: { zh: "罗马投票场景——公民把票板投入筐中", en: "A Roman voting scene: citizens casting their tablets" },
  septem: { zh: "昴星团(Pleiades)——古人肉眼可见的七姊妹星", en: "The Pleiades, the seven sisters visible to the naked eye" },
  sepulcrum: { zh: "《赫格索墓碑》,公元前5世纪,雅典国立考古博物馆", en: "The Grave Stele of Hegeso, 5th c. BC, National Archaeological Museum, Athens" },
  servus: { zh: "厨房劳作马赛克,突尼斯苏塞博物馆", en: "Mosaic of kitchen work, Sousse Museum, Tunisia" },
  sex: { zh: "厄瑞克忒翁神庙的六尊女像柱原件,雅典卫城博物馆", en: "The six original Erechtheion caryatids, Acropolis Museum, Athens" },
  silentium: { zh: "哈波克拉忒斯釉陶护身符,都灵埃及博物馆——手指按唇的静默之神", en: "Faience amulet of Harpocrates, Museo Egizio, Turin: the god with a finger to his lips" },
  silva: { zh: "《森林风景》,朱尔·迪普雷绘", en: "\"Forest Landscape\", Jules Dupré" },
  sinister: { zh: "家神(Lares)祭坛,庞贝", en: "Altar of the Lares, Pompeii" },
  sitis: { zh: "贝维拉夸井栏(puteal),卢浮宫", en: "The Bevilacqua puteal (well-head), Louvre" },
  sol: { zh: "太阳神索尔头像,镶嵌石板残片", en: "Head of the god Sol, opus sectile fragment" },
  somnus: { zh: "《沉睡的阿里阿德涅》,梵蒂冈博物馆", en: "The Sleeping Ariadne, Vatican Museums" },
  sonus: { zh: "吹奏萨尔平克斯号角的人,巴勒莫考古博物馆", en: "Salpinx (trumpet) player, Archaeological Museum of Palermo" },
  soror: { zh: "妇人与孩童的墓碑石,沃尔特斯艺术博物馆", en: "Funeral stele with a seated woman and child, Walters Art Museum" },
  spectrum: { zh: "《幽灵》,欧金纽·沃伊内斯库绘", en: "\"Apparition\", Eugeniu Voinescu" },
  spelunca: { zh: "《有洞穴的风景》,大都会艺术博物馆", en: "\"Landscape with a Cave\", Metropolitan Museum of Art" },
  spes: { zh: "《潘多拉》,沃特豪斯绘——盒中最后留下的是希望", en: "\"Pandora\", John William Waterhouse: hope was the last thing left in the box" },
  spiritus: { zh: "花彩与蝴蝶马赛克——蝴蝶即古人心中的气息与灵魂", en: "Mosaic with festoons and butterflies: the butterfly stood for breath and soul" },
  sponsa: { zh: "《亚历山大的婚礼》壁画,庞贝", en: "\"The Wedding of Alexander\", wall painting from Pompeii" },
  sponsus: { zh: "《希腊罗马式婚礼》,仿古代萨凯蒂浮雕", en: "\"A Grecian-Roman Wedding\", after an antique Sacchetti relief" },
  stagnum: { zh: "《睡莲池上的云影》,莫奈绘", en: "\"Reflections of Clouds on the Water-Lily Pond\", Claude Monet" },
  statua: { zh: "奥古斯都像", en: "Statue of Augustus" },
  stella: { zh: "《伯利恒之星》,乔托绘", en: "\"The Star of Bethlehem\", Giotto" },
  stupor: { zh: "《伯沙撒王的盛宴》,伦勃朗绘——墙上现出字迹的瞬间", en: "\"Belshazzar's Feast\", Rembrandt: the moment the writing appears on the wall" },
  suavitas: { zh: "《俄耳甫斯驯兽》马赛克,马苏鲁斯作,突尼斯巴尔多国家博物馆", en: "\"Orpheus Taming the Animals\", mosaic by Masurus, Bardo National Museum, Tunisia" },
  sub: { zh: "「暗道」(Via Tecta),基耶蒂的古罗马地下通道", en: "Via Tecta, an ancient Roman underground passage at Chieti" },
  sulphur: { zh: "《维苏威火山喷发》,约翰·克里斯蒂安·达尔绘", en: "\"Eruption of the Volcano Vesuvius\", Johan Christian Dahl" },
  super: { zh: "宝座上的宙斯大理石像,约公元前100年", en: "Marble statue of enthroned Zeus, ca. 100 BC" },
  superbia: { zh: "孔雀马赛克,突尼斯苏塞", en: "Peacock mosaic, Sousse, Tunisia" },
  supplicium: { zh: "维蒂之家,庞贝——壁上绘有受罚神话场景", en: "House of the Vettii, Pompeii, whose walls show scenes of mythic punishment" },
  taurus: { zh: "《跳牛》壁画,克诺索斯,伊拉克利翁考古博物馆", en: "Bull-leaping fresco, Knossos, Archaeological Museum of Heraklion" },
  tectum: { zh: "戳印的罗马屋瓦,1961年出土,舍尔丁市立博物馆", en: "Stamped Roman roof tile excavated in 1961, Stadtmuseum Schärding" },
  tempestas: { zh: "海上风暴,艾瓦佐夫斯基绘", en: "Storm at sea, Ivan Aivazovsky" },
  templum: { zh: "帕特农神庙西面,雅典卫城", en: "The Parthenon from the west, Acropolis of Athens" },
  tempus: { zh: "克罗诺斯-埃翁浮雕,维埃纳圣皮埃尔博物馆", en: "Mithraic relief of Chronos-Aion, Musée Saint-Pierre, Vienne" },
  tenebrae: { zh: "《圣马太蒙召》,卡拉瓦乔绘——黑暗中的一道光", en: "\"The Calling of Saint Matthew\", Caravaggio: one shaft of light in the dark" },
  terra: { zh: "大地女神特鲁斯浮雕,罗马和平祭坛", en: "Tellus, the Earth, relief on the Ara Pacis, Rome" },
  testis: { zh: "《荷拉斯兄弟之誓》,雅克-路易·大卫绘——当众立誓,人人为证", en: "\"Oath of the Horatii\", Jacques-Louis David: an oath sworn before witnesses" },
  theatrum: { zh: "埃皮达鲁斯古剧场,以音响效果著称", en: "The ancient theatre of Epidaurus, famous for its acoustics" },
  thesaurus: { zh: "锡弗诺斯人宝库,德尔斐——各城邦存放献礼之所", en: "The Siphnian Treasury at Delphi, where a city stored its offerings" },
  thronus: { zh: "冥界场景的阿普利亚红绘卷缘克拉特,约公元前340—330年,慕尼黑", en: "Apulian red-figure volute krater with Underworld scenes, ca. 340–330 BC, Munich" },
  tibia: { zh: "奏乐壁画,赫库兰尼姆,那不勒斯国立考古博物馆", en: "Concert fresco from Herculaneum, National Archaeological Museum, Naples" },
  timor: { zh: "戈耳工面具壁画残片,大都会艺术博物馆", en: "Wall painting fragment with a Gorgon mask, Metropolitan Museum of Art" },
  turba: { zh: "《西塞罗在元老院揭发喀提林》,马卡里绘——群情激愤的议场", en: "\"Cicero Denounces Catiline in the Roman Senate\", Cesare Maccari: the roused assembly" },
  turris: { zh: "赫拉克勒斯塔,西班牙拉科鲁尼亚——仍在使用的罗马灯塔", en: "Tower of Hercules, A Coruña: a Roman lighthouse still in use" },
  tympanum: { zh: "持手鼓的迈那得斯,斯塔比亚圣马可别墅,那不勒斯国立考古博物馆", en: "Maenad with a tambourine, Villa San Marco, Stabiae, National Archaeological Museum, Naples" },
  umbra: { zh: "《街道的神秘与忧郁》,基里科绘——长长的影子", en: "\"Mystery and Melancholy of a Street\", Giorgio de Chirico" },
  umor: { zh: "勒托昂圣所的水泉建筑(nymphaeum)", en: "The nymphaeum at the Letoon sanctuary" },
  unda: { zh: "《碎浪》,艾瓦佐夫斯基绘", en: "\"Breaking Wave\", Ivan Aivazovsky" },
  ungula: { zh: "青铜马小像,大都会艺术博物馆", en: "Bronze statuette of a horse, Metropolitan Museum of Art" },
  unus: { zh: "玻俄提亚同盟的一枚奥波尔银币", en: "A single obol of the Boeotian federal coinage" },
  ursus: { zh: "熊纹马赛克,庞贝遗址", en: "Bear mosaic, Pompeii" },
  vacca: { zh: "公牛青铜小像,底特律艺术学院", en: "Bronze statuette of a bull, Detroit Institute of Arts" },
  vallis: { zh: "《我也曾在阿卡迪亚》,普桑绘(第二版)", en: "\"Et in Arcadia ego\", Nicolas Poussin (second version)" },
  vapor: { zh: "安东尼浴场遗址,突尼斯迦太基", en: "The Antonine Baths, Carthage, Tunisia" },
  vates: { zh: "《德尔斐女先知》,维托里亚作,威尼斯圣若望及保禄大殿", en: "\"The Delphic Sibyl\", Alessandro Vittoria, Santi Giovanni e Paolo, Venice" },
  velum: { zh: "石棺浮雕:船员在港口前升起风帆,公元3世纪,美因茨古航海博物馆", en: "Sarcophagus relief: a crew raising the sails before a harbour, 3rd c. AD, Museum für Antike Schifffahrt, Mainz" },
  venenum: { zh: "罗马玻璃小瓶", en: "Roman glass vial" },
  venia: { zh: "《浪子回头》,伦勃朗绘", en: "\"The Return of the Prodigal Son\", Rembrandt" },
  ventus: { zh: "西风神仄费罗斯,雅典风之塔浮雕", en: "Zephyros, the west wind, Tower of the Winds, Athens" },
  verbum: { zh: "《奥古斯都功业录》碑文(安卡拉铭文)", en: "Res Gestae Divi Augusti, the Monumentum Ancyranum inscription" },
  veritas: { zh: "「真理之口」,罗马", en: "The Bocca della Verità, Rome" },
  versus: { zh: "维吉尔像,《罗马维吉尔》抄本——史诗诗行的作者", en: "Portrait of Virgil, Vergilius Romanus: the maker of the verses" },
  vetus: { zh: "《罗马广场废墟随想》,克洛德·洛兰绘", en: "\"Capriccio with the Ruins of the Roman Forum\", Claude Lorrain" },
  via: { zh: "庞贝的街道,车辙至今可见", en: "The streets of Pompeii, cart ruts still visible" },
  victor: { zh: "《德尔斐御者》青铜像——赛车获胜者的还愿像", en: "The Charioteer of Delphi, bronze victory dedication" },
  victoria: { zh: "《萨莫色雷斯的胜利女神》,卢浮宫", en: "Nike of Samothrace, Louvre" },
  vinculum: { zh: "罗马铁钥匙", en: "Roman iron key" },
  vir: { zh: "身着托加袍的男子像(后改作奥古斯都),哥本哈根新嘉士伯艺术博物馆", en: "Togate man, later restored as Augustus, Ny Carlsberg Glyptotek" },
  viridis: { zh: "利维娅别墅花园壁画,罗马——满墙的绿", en: "Garden fresco, Villa of Livia, Rome: a wall of green" },
  virtus: { zh: "提比略大铜币,背面为「德性」(Virtus)", en: "Sestertius of Tiberius with the personification of Virtus" },
  visus: { zh: "法尤姆木乃伊肖像,公元160—180年,大英博物馆", en: "Fayum mummy portrait, AD 160–180, British Museum" },
  vita: { zh: "树与狮马赛克,突尼斯", en: "Mosaic with a tree and lions, Tunisia" },
  vortex: { zh: "大漩涡(maelstrom)版画", en: "Engraving of a maelstrom" },
  votum: { zh: "还愿浮雕牌残片,惠康收藏", en: "Fragment of a carved votive plaque, Wellcome Collection" },
  vox: { zh: "《演说者》(Arringatore)青铜像——伸手发言的伊特鲁里亚人", en: "The Arringatore, the bronze orator with hand raised to speak" },
  vulnus: { zh: "罗马青铜外科器械,惠康收藏——治伤的工具", en: "Roman bronze surgical instruments, Wellcome Collection: the tools that treated wounds" },
};
