/* =====================================================
   FUGA MYTHICA — content data
   WORDS: key -> [latin, emoji, zh, en, derivatives, etymNoteZh, etymNoteEn]
   ===================================================== */
const WORDS = {
  /* ---- C1 L1 王宫与家人 Family & People ---- */
  pater:   ["pater","👨","父亲","father","paternal, patriot","印欧词根 pa- 表\"父\":英语 paternal(父亲的)、patriot(爱国者=爱\"父邦\"的人);西班牙语 padre。","PIE root pa- = father: paternal, patriot (one who loves the fatherland); Spanish padre."],
  mater:   ["mater","👩","母亲","mother","maternal, alma mater","maternal(母亲的)、matron(主妇);\"母校\"英语就叫 alma mater(哺育之母);西语 madre。","maternal, matron; your old school is your alma mater (nourishing mother); Spanish madre."],
  filius:  ["filius","👦","儿子","son","filial","filial(孝顺的=为人子的);法语 fils、西语 hijo 都是它变来的。","filial (of a son); French fils and Spanish hijo both grew from it."],
  filia:   ["filia","👧","女儿","daughter","filial","filius 的阴性形式——拉丁语 -a 结尾常是阴性;法语 fille(女儿/女孩)。","Feminine of filius — the -a ending often marks feminine; French fille."],
  rex:     ["rex","🤴","国王","king","regal, T. rex","regal(帝王气派的);霸王龙 T. rex = Tyrannosaurus rex,\"暴君蜥蜴之王\";西语 rey。","regal; T. rex = Tyrannosaurus rex, the tyrant lizard KING; Spanish rey."],
  regina:  ["regina","👸","王后","queen","reign","rex 的阴性;英国女王签名后缀 R 就是 Regina;reign(统治)同族。","Feminine of rex; British queens sign with R for Regina; cousin of reign."],
  puer:    ["puer","🧒","男孩","boy","puerile","puerile(孩子气的)直接来自它;罗马学校里老师喊学生就叫 pueri!","puerile (childish) comes straight from it; Roman teachers called their pupils pueri!"],
  puella:  ["puella","👧","女孩","girl","—","puer 的阴性小称形:puer→puella,又是 -a 表阴性的例子。","Little-girl form of puer — another example of feminine -a."],
  femina:  ["femina","👩","女人","woman","feminine, female","feminine(女性的)、female;法语 femme(女人/妻子)。","feminine, female; French femme (woman, wife)."],
  vir:     ["vir","🧔","男人","man","virile, virtue","virile(有男子气的);virtue(美德)原意\"男子汉的勇气\"——见 virtus!","virile; virtue originally meant \"manly courage\" — see virtus!"],
  frater:  ["frater","👬","兄弟","brother","fraternal, fraternity","fraternal(兄弟般的)、fraternity(兄弟会);法语 frère;英语 brother 是同一印欧词的日耳曼支。","fraternal, fraternity; French frère; English brother is the same ancient word via Germanic."],
  soror:   ["soror","👭","姐妹","sister","sorority","sorority(大学姐妹会);法语 sœur;sister 同印欧根。","sorority (a sisterhood at college); French sœur; sister shares the same root."],
  amicus:  ["amicus","🤝","朋友","friend","amicable, amigo","amare(爱)→amicus(所爱的人=朋友);西语 amigo!amicable(友好的)。","From amare (to love): a friend is one you love; Spanish amigo! amicable."],
  populus: ["populus","👥","人民","people","popular, population","popular(受欢迎=人民喜爱的)、population(人口)、people 本身也是它。","popular (liked by the people), population — and people itself."],
  deus:    ["deus","⚡","神","god","deity, adiós","deity(神明)、divine(神圣的);西语再见 adiós = a Dios,\"把你托付给神\"。","deity, divine; Spanish adiós = a Dios, \"(I entrust you) to God.\""],
  dea:     ["dea","🌟","女神","goddess","deity","deus 的阴性;罗马神庙铭文里女神名前常有 DEA 字样。","Feminine of deus; Roman temple inscriptions write DEA before a goddess's name."],
  heros:   ["heros","🦸","英雄","hero","hero, heroine","从希腊语借入拉丁语再进英语:hero、heroic、heroine(女英雄)一脉相承。","Borrowed from Greek into Latin into English: hero, heroic, heroine."],
  nomen:   ["nomen","📛","名字","name","nominate, noun","nominate(提名)、noun(名词=命名之词)、nominal;name 同印欧根。","nominate, noun (a naming word), nominal; name shares the ancient root."],
  familia: ["familia","👨‍👩‍👧‍👦","家庭","family","family, familiar","原指\"全家老小加仆人\"的大家庭;family、familiar(熟悉的=像家人一样)。","Originally the whole household; family, familiar (as known as one's own family)."],
  domus:   ["domus","🏠","家;房子","home, house","dome, domestic","dome(圆顶)、domestic(家用的)、dominate(当一家之主→支配)。","dome, domestic, dominate (to be master of the house)."],

  /* ---- C1 L2 大海与航行 Sea & Sailing ---- */
  navis:   ["navis","⛵","船","ship","navy, navigate","navy(海军=船队)、navigate(航行,nav+agere\"驾船\")、nave(教堂中殿,形似倒扣的船)。","navy (a fleet of ships), navigate (to drive a ship), nave of a church (shaped like an upturned ship)."],
  aqua:    ["aqua","💧","水","water","aquarium, aqueduct","aquarium(水族馆=水之馆)、aqueduct(古罗马引水渠=引水的管道);西语 agua。","aquarium (a house of water), aqueduct (Roman water-carrier); Spanish agua."],
  mare:    ["mare","🌊","大海","sea","marine, submarine","marine(海洋的)、submarine(海面之下的船)、mermaid(mere+maid 海姑娘)。","marine, submarine (a ship under the sea), mermaid (sea + maid)."],
  ventus:  ["ventus","💨","风","wind","vent, ventilate","vent(通风口)、ventilate(通风);法语 vent;wind 同印欧根。","vent, ventilate; French vent; wind shares the ancient root."],
  caelum:  ["caelum","🌌","天空","sky","celestial","celestial(天上的);西语 cielo、法语 ciel、意语 cielo 全是它的后代。","celestial; Spanish cielo, French ciel, Italian cielo are all its children."],
  stella:  ["stella","⭐","星星","star","stellar, constellation","stellar(明星的)、constellation(星座=一群星);star 同印欧根;意语 stella。","stellar, constellation (stars grouped together); star shares the root; Italian stella."],
  sol:     ["sol","☀️","太阳","sun","solar, parasol","solar(太阳能的)、parasol(阳伞=挡太阳)、solstice(至日=太阳驻足);西语 sol。","solar, parasol (para+sol: it blocks the sun), solstice; Spanish sol."],
  luna:    ["luna","🌙","月亮","moon","lunar, lunatic","lunar(月球的);lunatic(疯子)——古人相信满月使人发疯!西语 luna。","lunar; lunatic — the ancients believed the full moon caused madness! Spanish luna."],
  nauta:   ["nauta","👨‍✈️","水手","sailor","nautical, astronaut","nautical(航海的);astronaut(宇航员)= astro+nauta,\"星际水手\"!","nautical; astronaut = astro + nauta, a sailor among the stars!"],
  insula:  ["insula","🏝️","岛","island","insulate, peninsula","insulate(隔绝=使成孤岛)、peninsula(半岛=paene+insula\"几乎是岛\");意语 isola。","insulate (to make an island of), peninsula (paene+insula, \"almost an island\"); Italian isola."],
  unda:    ["unda","🌊","波浪","wave","undulate, inundate","undulate(如波起伏)、inundate(淹没=波浪涌入)、abundant(丰沛=如水漫溢)。","undulate (to move like waves), inundate (to flood), abundant (overflowing like water)."],
  tempestas:["tempestas","⛈️","风暴","storm","tempest","tempest(暴风雨);由 tempus(时间)而来——原指\"一时的天气\"。","tempest; from tempus (time) — originally \"the weather of the moment.\""],
  portus:  ["portus","⚓","港口","harbor","port, opportunity","port(港口);opportunity(机会)原指 ob portum——顺风正\"朝着港口\"!","port; opportunity originally meant a wind blowing you ob portum — right toward harbor!"],
  terra:   ["terra","🌍","陆地;大地","land, earth","terrain, Mediterranean","terrain(地形)、territory(领土)、Mediterranean(地中海=medi+terra,陆地中间的海)。","terrain, territory, Mediterranean (medi+terra: the sea in the middle of the land)."],
  nubes:   ["nubes","☁️","云","cloud","nuance","西语 nube(云);法语 nuance(细微差别)原指云彩明暗的层次变化!","Spanish nube; French nuance originally meant the subtle shadings of a cloud!"],
  pluvia:  ["pluvia","🌧️","雨","rain","pluvial","pluvial(多雨的);西语 lluvia、法语 pluie 都由它变来。","pluvial (rainy); Spanish lluvia and French pluie both come from it."],
  remus:   ["remus","🚣","桨","oar","trireme","trireme(三列桨战船)= tri+remus,古代海战主力舰就以\"桨\"命名。","trireme = tri + remus, the three-oar-bank warship of ancient navies."],
  velum:   ["velum","🏳️","帆","sail","veil, reveal","veil(面纱=一块遮布,和帆同源);reveal(揭示=揭开面纱)。","veil (a cloth cover, same word family); reveal (to draw back the veil)."],
  piscis:  ["piscis","🐟","鱼","fish","Pisces","Pisces(双鱼座);西语 pez;英语 fish 是同一印欧词的日耳曼支。","Pisces the zodiac fish; Spanish pez; English fish is the Germanic branch of the same root."],
  iter:    ["iter","🗺️","旅程","journey","itinerary","itinerary(行程单=旅程清单)、itinerant(巡游的)。","itinerary (the list of your journey), itinerant (traveling about)."],

  /* ---- C1 L3 米诺斯王宫 The Palace ---- */
  porta:   ["porta","🚪","大门","gate","portal, port","portal(大门/传送门);portare(搬运)同族——门是\"物品进出\"之处;法语 porte。","portal; kin of portare (to carry) — a gate is where things are carried through; French porte."],
  ianua:   ["ianua","🚪","房门","door","January, janitor","看门神雅努斯 Janus 有前后两张脸→ January(一月=一年之门!)、janitor(看门人)。","From Janus, the two-faced door god → January (the door of the year!) and janitor."],
  murus:   ["murus","🧱","墙","wall","mural, intramural","mural(壁画=画在墙上)、intramural(校内的=墙之内的)。","mural (a painting on a wall), intramural (within the walls)."],
  turris:  ["turris","🗼","塔","tower","turret","turret(角楼小塔);法语 tour、意语 torre——比萨斜塔就是 Torre di Pisa。","turret; French tour, Italian torre — the Leaning Tower is the Torre di Pisa."],
  aula:    ["aula","🏛️","大厅","hall","aula","欧洲许多大学的礼堂至今仍叫 Aula——两千年没改名!","Many European universities still call their great hall the Aula — unchanged for 2000 years!"],
  mensa:   ["mensa","🍽️","桌子","table","Mensa, mesa","高智商俱乐部\"门萨 Mensa\"以圆桌为名;西语 mesa 既是桌子也是平顶山。","The Mensa society is named after the round table; Spanish mesa means both table and flat-topped mountain."],
  sella:   ["sella","🪑","椅子","chair","saddle","来自 sedere(坐):sedentary(久坐的)、saddle(马鞍=骑手的座椅)是亲戚。","From sedere (to sit): sedentary and saddle (a rider's seat) are cousins."],
  lucerna: ["lucerna","🪔","油灯","oil lamp","lucent","藏着 lux(光):lucent(发亮的)、translucent(半透光的)同族。","lux (light) hides inside: lucent and translucent are family."],
  fenestra:["fenestra","🪟","窗户","window","defenestration","法语 fenêtre、德语 Fenster;英语 defenestration=\"掷出窗外\",真实的历史事件名词!","French fenêtre, German Fenster; defenestration = throwing someone out a window — a real historical term!"],
  tectum:  ["tectum","🏠","屋顶","roof","protect, architect","tegere(覆盖)→ protect(护在前面遮住)、detect(揭开盖子发现)、architect(总建造师)。","From tegere (to cover): protect (cover in front), detect (take the cover off), architect."],
  columna: ["columna","🏛️","柱子","column","column, colonnade","column(圆柱;报纸专栏也是\"一柱\"文字)、colonnade(柱廊)。","column (a newspaper column is a pillar of text), colonnade."],
  statua:  ["statua","🗿","雕像","statue","statue, static","stare(站立)→ statue(立着的像)、static(静止的)、station(站)。","From stare (to stand): statue, static, station."],
  hortus:  ["hortus","🌷","花园","garden","horticulture","horticulture(园艺学);英语 garden/yard 是同一印欧根的日耳曼支。","horticulture; garden and yard are the Germanic branch of the same root."],
  fons:    ["fons","⛲","泉水;喷泉","fountain, spring","fountain, font","fountain(喷泉);font(字体)原指铸字的\"源\";教堂洗礼池也叫 font。","fountain; font — both the type you read and the baptismal basin flow from this \"source.\""],
  aurum:   ["aurum","🥇","金子","gold","Au, aureate","化学元素金的符号 Au 就是 aurum 的缩写!aureate(金色的);西语 oro。","The chemical symbol Au IS aurum! aureate (golden); Spanish oro."],
  argentum:["argentum","🥈","银子","silver","Ag, Argentina","银的符号 Ag = argentum;阿根廷 Argentina 意为\"白银之国\"!","Silver's symbol Ag = argentum; Argentina means \"land of silver\"!"],
  marmor:  ["marmor","💎","大理石","marble","marble","marble 由它磨损变来;源自希腊语\"闪亮的石头\"。","marble wore down from marmor; from Greek for \"shining stone.\""],
  pictura: ["pictura","🖼️","壁画;图画","painting","picture, paint","pingere(绘画)→ picture、paint、pigment(颜料)一家人。","From pingere (to paint): picture, paint, pigment."],
  servus:  ["servus","🙇","仆人","servant","serve, service","serve、servant、service;奥地利人至今用 Servus! 打招呼——\"愿为您效劳\"。","serve, servant, service; Austrians still greet with Servus! — \"at your service.\""],
  convivium:["convivium","🥂","宴会","banquet","convivial","con(一起)+vivere(生活):convivial(欢宴气氛的)——一起吃饭就是一起生活。","con (together) + vivere (to live): convivial — to feast together is to live together."],

  /* ---- C1 L4 公主的礼物 The Princess's Gifts ---- */
  filum:   ["filum","🧵","线;线团","thread","filament, profile","filament(灯丝=细线)、file(档案,原指穿文件的线绳)、profile(轮廓线)。","filament (a tiny thread), file (papers once strung on a thread), profile (an outline)."],
  gladius: ["gladius","🗡️","剑","sword","gladiator, gladiolus","gladiator(角斗士=持剑之人);gladiolus(剑兰)因叶片如小剑得名。","gladiator (a swordsman); gladiolus, the flower with sword-shaped leaves."],
  donum:   ["donum","🎁","礼物","gift","donate, donor","dare/donare(给予)→ donate(捐赠)、donor(捐赠者)、pardon(完全给予→宽恕)。","From donare (to give): donate, donor, pardon (to give completely → forgive)."],
  corona:  ["corona","👑","王冠;花环","crown","coronation, corona","coronation(加冕礼);日全食时太阳的光环就叫 corona(日冕)。","coronation; the sun's halo in an eclipse is its corona."],
  anulus:  ["anulus","💍","戒指","ring","annular","annular(环形的)——日环食叫 annular eclipse,天空戴了一枚金戒指。","annular — an annular eclipse is the sky wearing a golden ring."],
  gemma:   ["gemma","💎","宝石","gem","gem","gem 直接来自它;原意是\"植物的芽\"——宝石是大地冒出的芽。","gem comes straight from it; originally a plant bud — a gem is the earth's budding."],
  arca:    ["arca","🧰","箱子","chest, box","ark, arcane","诺亚方舟 Noah's Ark 的 ark 就是 arca(大箱子);arcane(神秘的=锁在箱底的)。","Noah's Ark IS arca (a great chest); arcane (secret, locked in the chest)."],
  clavis:  ["clavis","🗝️","钥匙","key","clef, clavicle","音乐谱号 clef(法语\"钥匙\",开启五线谱);clavicle(锁骨,形如小钥匙)。","clef (French for key — it unlocks the staff); clavicle, the little-key-shaped bone."],
  charta:  ["charta","📜","纸;地图","paper, chart","chart, card, Magna Carta","chart(图表)、card(卡片);英国大宪章 Magna Carta =\"大文件\"。","chart, card; the Magna Carta = \"the Great Paper.\""],
  epistula:["epistula","✉️","信","letter","epistle","epistle(书信体文章);《圣经》使徒书信就叫 Epistles。","epistle; the letters of the apostles are the Epistles."],
  liber:   ["liber","📖","书","book","library","原意\"树皮\"——最早的纸!library(图书馆)、意语 libro。","Originally tree bark — the first paper! library; Italian libro."],
  verbum:  ["verbum","💬","词;话语","word","verb, proverb","verb(动词=句子的核心词)、verbal(口头的)、proverb(谚语=流传之言);word 同印欧根。","verb (the key word of a sentence), verbal, proverb; word shares the root."],
  consilium:["consilium","🧠","计划;建议","plan, advice","counsel, consult","counsel(忠告)、counselor(顾问)、consult(咨询)。","counsel, counselor, consult."],
  fides:   ["fides","🤞","信任;忠诚","trust, faith","fidelity, bona fide","fidelity(忠诚)、confide(倾诉=托付信任)、bona fide(真诚的);忠犬名 Fido=\"我信任\"。","fidelity, confide, bona fide; the classic dog name Fido means \"I trust.\""],
  amor:    ["amor","❤️","爱","love","amateur","amateur(业余爱好者)原意\"因爱而做的人\"——不为钱,为爱!西语 amor。","An amateur is literally \"one who does it for love\" — not for money! Spanish amor."],
  cor:     ["cor","🫀","心","heart","cordial, courage","cordial(发自内心的)、courage(勇气=心的力量)、record(记录=重新过一遍心)。","cordial (from the heart), courage (strength of heart), record (to pass through the heart again)."],
  animus:  ["animus","💪","心灵;勇气","spirit, courage","animate, unanimous","animate(赋予生气)、animal(有气息的生灵)、unanimous(一致=一条心)。","animate, animal (a breathing being), unanimous (of one mind)."],
  sapientia:["sapientia","🦉","智慧","wisdom","Homo sapiens","人类的学名 Homo sapiens 就是\"有智慧的人\"——你身上就带着这个词!","Homo sapiens IS this word — \"the wise human.\" You carry it in your own species name!"],
  secretum:["secretum","🤫","秘密","secret","secret, secretary","secret;secretary(秘书)原意\"掌管秘密的人\"。","secret; a secretary was originally the keeper of secrets."],
  auxilium:["auxilium","🆘","帮助","help","auxiliary","auxiliary(辅助的);罗马军团的盟军部队就叫 auxilia。","auxiliary; Rome's allied troops were the auxilia."],

  /* ---- C1 L5 进入迷宫 Into the Labyrinth ---- */
  lux:     ["lux","💡","光","light","lucid, illuminate","lucid(清晰透亮的)、illuminate(照亮);照度单位勒克斯 lx 就是 lux!","lucid, illuminate; the light unit lux IS this word!"],
  tenebrae:["tenebrae","🌑","黑暗","darkness","tenebrous","tenebrous(阴暗的);伦勃朗式明暗画法的极暗背景常用此词形容。","tenebrous; art critics use it for the deep shadows of Rembrandt-style painting."],
  via:     ["via","🛣️","路","road, way","via, viaduct","英语介词 via(经由)原样借用;viaduct(高架桥=路之渠);trivial(琐碎)=三岔路口 tri+via 的闲谈!","English via is borrowed unchanged; viaduct; trivial = tri+via, small talk at the crossroads!"],
  umbra:   ["umbra","👤","影子","shadow","umbrella, sombrero","umbrella(雨伞)原意\"小影子\"!西语 sombrero(宽檐帽=造影子的帽子)。","An umbrella is literally \"a little shadow\"! Spanish sombrero, the shade-making hat."],
  silentium:["silentium","🤐","寂静","silence","silent","silent、silence;图书馆墙上的 SILENTIUM 标牌两千年未变。","silent, silence; SILENTIUM signs have hushed libraries for 2000 years."],
  timor:   ["timor","😨","恐惧","fear","timid, intimidate","timid(胆怯的)、intimidate(恐吓=使害怕)。","timid, intimidate (to put fear into someone)."],
  ignis:   ["ignis","🔥","火","fire","ignite, igneous","ignite(点燃)、igneous rock(火成岩=火造的石头)。","ignite, igneous rock (rock born of fire)."],
  fax:     ["fax","🕯️","火把","torch","facula","罗马婚礼由火把队伍引路;天文学 facula(光斑)=\"小火把\"。","Roman weddings were led by torch-bearers; astronomers call a sun-spot of light a facula, \"little torch.\""],
  flamma:  ["flamma","🔥","火焰","flame","flame, flamingo","flame;flamingo(火烈鸟)=火焰色的鸟;flammable(易燃的)。","flame; flamingo, the flame-colored bird; flammable."],
  saxum:   ["saxum","🪨","岩石","rock","saxifrage","saxifrage(虎耳草)= saxum+frangere\"碎石草\",能在岩缝里开花。","saxifrage = saxum + frangere, the \"rock-breaker\" flower that blooms in stone cracks."],
  labyrinthus:["labyrinthus","🌀","迷宫","labyrinth","labyrinth","就是本关的迷宫!你内耳掌管平衡的结构医学上也叫 labyrinth(迷路)。","THE Labyrinth of this chapter! The balance organ in your inner ear is also called the labyrinth."],
  angulus: ["angulus","📐","角落","corner","angle, triangle","angle(角)、triangle(三角形)、rectangle(矩形=直角形)。","angle, triangle, rectangle (the right-angled shape)."],
  dexter:  ["dexter","👉","右边的","right","dexterous","dexterous(灵巧的)——古人认为右手更巧;ambidextrous(左右开弓=两只手都像右手)。","dexterous — the right hand was the skilled one; ambidextrous = \"right-handed on both sides.\""],
  sinister:["sinister","👈","左边的","left","sinister","英语 sinister(阴险的)就是\"左\"——罗马占卜以左侧飞鸟为凶兆。","English sinister IS \"left\" — Roman augurs read birds on the left as ill omens."],
  ante:    ["ante","⏮️","在…前面","before, in front","a.m., antique","上午 a.m. = ante meridiem(正午之前)!antique(古董=从前之物)、anticipate(预先想到)。","a.m. = ante meridiem, before midday! antique, anticipate."],
  post:    ["post","⏭️","在…后面","after, behind","p.m., postscript","下午 p.m. = post meridiem(正午之后);信末 P.S. = postscript(后写的话);postpone(推后)。","p.m. = post meridiem; P.S. = postscript, written after; postpone."],
  sub:     ["sub","⬇️","在…下面","under","submarine, subway","submarine(海面下的船)、subway(地下之路)、subtitle(片下的字=字幕)。","submarine, subway, subtitle (words under the picture)."],
  super:   ["super","⬆️","在…上面","above","superman, superior","superman(超人=在众人之上)、superior(更高的)、supermarket(超级市场)。","superman (the man above), superior, supermarket."],
  intra:   ["intra","📥","在…里面","inside","intranet, intravenous","intranet(内网=内部之网)、intravenous(静脉注射的 IV=进到血管里)。","intranet, intravenous (the IV that goes inside a vein)."],
  exitus:  ["exitus","🚶","出口","exit","exit","exit(出口)= ex(出)+ire(走):\"走出去\"。电影院的 EXIT 灯就是拉丁语!","exit = ex (out) + ire (to go). Every EXIT sign glows in Latin!"],

  /* ---- C1 L6 感官与身体 Senses & Body ---- */
  vox:     ["vox","🗣️","声音","voice","vocal, vox populi","vocal(嗓音的)、voice;新闻里的 vox populi =\"人民的声音\"(民意采访)。","vocal, voice; vox populi = \"the voice of the people.\""],
  auris:   ["auris","👂","耳朵","ear","aural","aural(听觉的);亲戚 audire(听)→ audio、audience(听众)。","aural; its cousin audire (to hear) gives audio and audience."],
  oculus:  ["oculus","👁️","眼睛","eye","ocular, binoculars","ocular(眼的)、binoculars(双筒望远镜=两只眼)、monocle(单片眼镜)。","ocular, binoculars (two eyes), monocle (one eye)."],
  manus:   ["manus","✋","手","hand","manual, manuscript","manual(手册/手动)、manufacture(制造,原指手工做)、manuscript(手写稿)。","manual, manufacture (originally made by hand), manuscript (hand-written)."],
  pes:     ["pes","🦶","脚","foot","pedal, pedestrian","pedal(脚踏板)、pedestrian(行人=用脚的人)、centipede(蜈蚣=百足)。","pedal, pedestrian (one who goes on foot), centipede (hundred feet)."],
  caput:   ["caput","🗣️","头","head","captain, capital","captain(队长=头儿)、capital(首都=头号城市;大写字母=开头字母)、cap(帽)。","captain (the head man), capital (the head city; capital letters head the sentence), cap."],
  corpus:  ["corpus","🧍","身体","body","corpse, corporation","corpse(尸体)、corps(军团)、corporation(公司=法律拟成的一个\"身体\")。","corpse, corps, corporation (a legal \"body\" of people)."],
  os:      ["os","👄","嘴","mouth","oral","oral(口头的/口腔的)、orifice(开口)。","oral, orifice (an opening)."],
  nasus:   ["nasus","👃","鼻子","nose","nasal","nasal(鼻音的);nose 是同一印欧词的日耳曼支。","nasal; nose is the Germanic branch of the same root."],
  digitus: ["digitus","☝️","手指","finger","digit, digital","digit 既是手指也是数字——古人掰手指数数!digital(数字的)由此而来。","digit means both finger and number — people counted on their fingers! Hence digital."],
  bracchium:["bracchium","💪","手臂","arm","bracelet, embrace","bracelet(手镯=戴在臂上)、embrace(拥抱=揽入双臂)。","bracelet (worn on the arm), embrace (to take into your arms)."],
  genu:    ["genu","🦵","膝盖","knee","genuflect","genuflect(单膝跪礼);knee 同印欧根 genu-。","genuflect (to bend the knee); knee shares the ancient root genu-."],
  capillus:["capillus","💇","头发","hair","capillary","capillary(毛细血管)——细得像一根头发的血管。","capillary — a blood vessel as fine as a hair."],
  dens:    ["dens","🦷","牙齿","tooth","dentist, dandelion","dentist(牙医)、dental;蒲公英 dandelion=法语 dent de lion,\"狮子的牙齿\"(叶缘如齿)!","dentist, dental; dandelion = French dent de lion, \"lion's tooth\" (look at the jagged leaves)!"],
  lingua:  ["lingua","👅","舌头;语言","tongue, language","language, bilingual","language(语言)、bilingual(双语的);意面 linguine =\"小舌头\"。","language, bilingual; linguine pasta = \"little tongues.\""],
  sanguis: ["sanguis","🩸","血","blood","sanguine, sangria","sanguine(乐观的——古医学\"多血质\"性格开朗);西班牙饮料 sangría 因酒色如血得名。","sanguine (the \"full-blooded\" cheerful temperament of old medicine); sangría, the blood-red drink."],
  spiritus:["spiritus","🌬️","呼吸;精神","breath, spirit","spirit, inspire","spirare(呼吸)→ spirit(精神=生命之气)、inspire(吸入灵感)、respiration(呼吸作用)。","From spirare (to breathe): spirit (the breath of life), inspire, respiration."],
  somnus:  ["somnus","😴","睡眠","sleep","insomnia","insomnia(失眠=没有睡眠);somnambulist(梦游者=睡着走路的人)。","insomnia (no sleep); somnambulist (one who walks while asleep)."],
  vita:    ["vita","🌱","生命","life","vital, vitamin","vital(生死攸关的)、vitamin(维他命=维持生命的物质);简历 CV = curriculum vitae\"生命的历程\"。","vital, vitamin (a life-substance); CV = curriculum vitae, \"the course of a life.\""],
  mors:    ["mors","💀","死亡","death","mortal, immortal","mortal(凡人=会死的)、immortal(不朽的);mortgage(房贷)法语原意\"死质押\"!","mortal, immortal; mortgage is literally French for \"death pledge\"!"],

  /* ---- C1 L7 野兽的巢穴 The Beast's Den ---- */
  taurus:  ["taurus","🐂","公牛","bull","Taurus, toreador","金牛座 Taurus;西语 toro(公牛)、toreador(斗牛士);米诺陶 Mino-taurus=\"米诺斯的牛\"!","Taurus the zodiac bull; Spanish toro, toreador; the Mino-taur is \"the bull of Minos\"!"],
  leo:     ["leo","🦁","狮子","lion","Leo, leopard","狮子座 Leo、lion;leopard = leo+pardus(狮+豹)。","Leo the zodiac lion, lion; leopard = leo + pardus."],
  lupus:   ["lupus","🐺","狼","wolf","lupine","lupine(狼一般的);西语 lobo;罗马城的母狼哺育了罗慕路斯与雷穆斯。","lupine; Spanish lobo; a she-wolf nursed Romulus and Remus, founders of Rome."],
  serpens: ["serpens","🐍","蛇","snake","serpent, serpentine","serpere(爬行)→ serpent(爬行者=蛇)、serpentine(蜿蜒如蛇的)。","From serpere (to creep): serpent (the creeper), serpentine."],
  aquila:  ["aquila","🦅","鹰","eagle","aquiline","aquiline nose(鹰钩鼻);罗马军团的军旗就是一只银鹰,也叫 aquila。","aquiline nose; the Roman legion's sacred standard was a silver eagle, the aquila."],
  equus:   ["equus","🐎","马","horse","equestrian","equestrian(马术的);马属动物学名就是 Equus。","equestrian; the horse genus in science is Equus."],
  canis:   ["canis","🐕","狗","dog","canine, Canary Islands","canine(犬齿/犬类);加那利群岛 Canary Islands 原意\"狗岛\"——金丝雀反而因岛得名!","canine; the Canary Islands are \"Dog Islands\" — the canary bird is named after them, not the reverse!"],
  felis:   ["felis","🐈","猫","cat","feline","feline(猫科的);猫属学名 Felis。","feline; the cat genus is Felis."],
  avis:    ["avis","🐦","鸟","bird","aviation, aviary","aviation(航空=学鸟飞行)、aviary(大鸟舍);rara avis(珍稀之鸟=罕见人物)。","aviation (flying like birds), aviary; rara avis, \"a rare bird.\""],
  ursus:   ["ursus","🐻","熊","bear","Ursa Major","大熊座 Ursa Major——北斗七星就在它身上!ursine(熊一般的)。","Ursa Major, the Great Bear — home of the Big Dipper! ursine."],
  aper:    ["aper","🐗","野猪","wild boar","—","罗马史诗里猎野猪是英雄的成人礼;英语 boar 是日耳曼词,两条语言支流并行。","In Roman epic, the boar hunt proved a hero; English boar is the Germanic stream of the story."],
  cervus:  ["cervus","🦌","鹿","deer","cervine","cervine(鹿的);西语 ciervo;词根原意\"有角的\"——和 cornu(角)同源。","cervine; Spanish ciervo; the root means \"horned\" — kin to cornu (horn)."],
  vacca:   ["vacca","🐄","母牛","cow","vaccine","vaccine(疫苗)直接来自它——最早的疫苗是牛痘,牛救了全人类!西语 vaca。","vaccine comes from vacca — the first vaccine was cowpox: the cow saved humanity! Spanish vaca."],
  ovis:    ["ovis","🐑","绵羊","sheep","ovine","ovine(绵羊的);西语 oveja;英语 ewe(母羊)同印欧根。","ovine; Spanish oveja; English ewe shares the ancient root."],
  capra:   ["capra","🐐","山羊","goat","Capricorn, caper","摩羯座 Capricorn(山羊角);caper(雀跃=像小山羊蹦跳);意大利卡普里岛 Capri。","Capricorn (goat-horn); to caper is to leap like a kid goat; the isle of Capri."],
  porcus:  ["porcus","🐖","猪","pig","pork, porcupine","pork(猪肉)——英语动物活着用本土名,端上桌变拉丁名!porcupine(豪猪=带刺的猪)。","pork — in English the animal is native but the meat turns Latin at the table! porcupine, the thorn-pig."],
  mus:     ["mus","🐭","老鼠","mouse","muscle","mouse 同印欧根;muscle(肌肉)原意\"小老鼠\"——鼓起的肌肉像皮下钻动的小鼠!","mouse shares the root; muscle means \"little mouse\" — a flexing biceps scurries under the skin!"],
  rana:    ["rana","🐸","青蛙","frog","Ranidae","西语 rana;蛙科学名 Ranidae;拟声词——听蛙鸣 \"rana, rana\"。","Spanish rana; the frog family is Ranidae; it's onomatopoeic — hear the croak in \"ra-na.\""],
  apis:    ["apis","🐝","蜜蜂","bee","apiary, apiculture","apiary(蜂场)、apiculture(养蜂学)。","apiary, apiculture."],
  monstrum:["monstrum","👹","怪物","monster","monster, demonstrate","monere(警示)→怪物原是\"神的警示\";demonstrate(展示=明白指出)同根。","From monere (to warn): a monster was a divine warning; demonstrate shares the root."],

  /* ---- C1 L8 决战米诺陶 The Battle ---- */
  pugna:   ["pugna","🥊","战斗","fight","pugnacious","pugnacious(好斗的)、pugilist(拳击手);pugnus=拳头,战斗从挥拳开始。","pugnacious, pugilist; pugnus = fist — every fight begins with one."],
  bellum:  ["bellum","⚔️","战争","war","rebel, belligerent","rebel(反叛=再次开战)、belligerent(交战方);格言 Si vis pacem, para bellum(欲得和平,先备战争)。","rebel (to war again), belligerent; Si vis pacem, para bellum — \"if you want peace, prepare for war.\""],
  hasta:   ["hasta","🔱","长矛","spear","hastati","罗马军团前排枪兵就叫 hastati(持矛者)——一支矛命名了一个兵种。","Rome's front-line spearmen were the hastati — a whole rank named for its spear."],
  scutum:  ["scutum","🛡️","盾牌","shield","escutcheon","escutcheon(纹章盾徽)——骑士家徽画在盾形上;罗马大方盾专名就是 scutum。","escutcheon, the shield-shaped coat of arms; the great Roman shield was the scutum."],
  galea:   ["galea","🪖","头盔","helmet","galea","解剖学把头顶的腱膜叫 galea(帽状腱膜)——你的头骨自带一顶\"头盔\"。","Anatomists call the scalp's sheet of tissue the galea — your skull wears a built-in helmet."],
  arma:    ["arma","🗡️","武器","weapons","arms, army, alarm","arms(武器)、army(军队)、armor(盔甲);alarm 来自意语 all'arme!——\"拿起武器!\"","arms, army, armor; alarm is Italian all'arme! — \"To arms!\""],
  sagitta: ["sagitta","🏹","箭","arrow","Sagittarius","射手座 Sagittarius(持箭者);解剖学矢状面 sagittal =\"箭的方向\"。","Sagittarius the archer; the sagittal plane in anatomy runs \"the way of the arrow.\""],
  arcus:   ["arcus","🏹","弓;拱","bow, arch","arc, arch, arcade","arc(弧线)、arch(拱门)、archer(弓手)、arcade(拱廊——后来才变成游戏厅!)。","arc, arch, archer, arcade (a vaulted walk — only later a game hall!)."],
  hostis:  ["hostis","😠","敌人","enemy","hostile","hostile(敌对的)、hostility(敌意)。","hostile, hostility."],
  miles:   ["miles","💂","士兵","soldier","military, militia","military(军事的)、militia(民兵);militant(斗士)。","military, militia, militant."],
  fortis:  ["fortis","🦁","勇敢的;强壮的","brave, strong","fort, effort, forte","fort(堡垒=坚固之地)、effort(努力=使出力气)、comfort(安慰=给人力量)、forte(强项)。","fort (a strong place), effort, comfort (to give strength), forte."],
  magnus:  ["magnus","🔵","大的","big, great","magnify, magnificent","magnify(放大)、magnificent(宏大的);查理曼 Charlemagne = Carolus Magnus\"查理大帝\"。","magnify, magnificent; Charlemagne = Carolus Magnus, \"Charles the Great.\""],
  parvus:  ["parvus","🔹","小的","small","parvovirus","医学细小病毒就叫 parvovirus(小病毒);parvo- 一律表\"小\"。","parvovirus, \"the tiny virus\"; parvo- always means small."],
  celer:   ["celer","🏃","快的","fast","accelerate","accelerate(加速)藏着它!celerity(神速)。","accelerate hides this word! celerity (swiftness)."],
  tardus:  ["tardus","🐢","慢的","slow","tardy","tardy(迟到的)、retard(使变慢);意语音乐术语 ritardando(渐慢)。","tardy, retard (to slow); the music term ritardando, \"slowing down.\""],
  victoria:["victoria","🏆","胜利","victory","victory, Victoria","victory;维多利亚女王、维多利亚湖、悉尼维多利亚州——всё 以\"胜利\"命名。","victory; Queen Victoria, Lake Victoria — all named \"Victory.\""],
  gloria:  ["gloria","✨","荣耀","glory","glory, glorious","glory、glorious;教堂音乐《Gloria》唱的就是这个词。","glory, glorious; the church hymn \"Gloria\" sings this very word."],
  virtus:  ["virtus","🎖️","勇气;美德","courage, virtue","virtue, virtuoso","vir(男子汉)→virtus(男子气概→美德);virtuoso(演奏大师=有极高\"功力\"的人)。","From vir (man): manly excellence → virtue; a virtuoso has mastered his craft's virtus."],
  ferrum:  ["ferrum","⚙️","铁;兵刃","iron, blade","Fe, ferrous","铁的化学符号 Fe = ferrum!ferrous(含铁的);西语铁路 ferrocarril=\"铁之路\"。","Iron's symbol Fe IS ferrum! ferrous; Spanish ferrocarril, the \"iron road\" (railway)."],
  clamor:  ["clamor","📢","呐喊","shout","claim, exclaim","clamare(呼喊)→ claim(主张=喊出要求)、exclaim(惊呼)、proclamation(公告)。","From clamare (to cry out): claim, exclaim, proclamation."],

  /* ---- C1 L9 数字与颜色 Numbers & Colors ---- */
  unus:    ["unus","1️⃣","一","one","unit, unicorn, union","unit(单位)、unicorn(独角兽=一只角)、uniform(一个样式)、union(联合为一)。","unit, unicorn (one horn), uniform (one form), union."],
  duo:     ["duo","2️⃣","二","two","duet, duel","duo(二人组)、duet(二重唱)、dual(双重)、duel(两人决斗)。","duo, duet, dual, duel (a fight of two)."],
  tres:    ["tres","3️⃣","三","three","trio, tripod","trio(三人组)、triple(三倍)、tripod(三脚架)、triangle(三角形)。","trio, triple, tripod (three feet), triangle."],
  quattuor:["quattuor","4️⃣","四","four","quarter, quartet","quarter(四分之一)、quartet(四重奏)、quadruple(四倍)。","quarter, quartet, quadruple."],
  quinque: ["quinque","5️⃣","五","five","quintet, quintessence","quintet(五重奏);quintessence(精髓)原指四元素之外的\"第五元素\"!","quintet; quintessence — the \"fifth element\" beyond earth, water, air and fire!"],
  sex:     ["sex","6️⃣","六","six","sextet, sextant","sextet(六重奏)、sextant(六分仪=圆的六分之一)。","sextet, sextant (one-sixth of a circle)."],
  septem:  ["septem","7️⃣","七","seven","September","September 本是罗马历的七月!后来历法前移两个月,名字却留下了。","September was Rome's SEVENTH month! The calendar shifted; the name stayed."],
  octo:    ["octo","8️⃣","八","eight","octopus, octave, October","octopus(八爪鱼)、octave(八度音)、October(罗马历八月)。","octopus (eight feet), octave, October (Rome's eighth month)."],
  novem:   ["novem","9️⃣","九","nine","November","November=罗马历九月;九日祈祷 novena。","November, Rome's ninth month; a novena is a nine-day prayer."],
  decem:   ["decem","🔟","十","ten","December, decimal","December(罗马历十月)、decimal(十进制)、decade? 来自希腊 deka——同一个印欧\"十\"。","December (Rome's tenth month), decimal; decade is the Greek branch of the same \"ten.\""],
  centum:  ["centum","💯","一百","hundred","percent, century","percent(每百)、century(百年/百人队)、centurion(百夫长)、cent(1/100 元)。","percent, century, centurion (leader of a hundred), cent."],
  mille:   ["mille","🧮","一千","thousand","mile, millennium","mile(英里)原是罗马兵的\"一千步\"mille passus!millennium(千年)、million。","A mile was the Roman soldier's mille passus — a thousand paces! millennium, million."],
  albus:   ["albus","⚪","白色的","white","album, albino","album(相册)原指白板;albino(白化);《哈利·波特》邓布利多名字 Albus 就是\"白\"!","album (once a white tablet), albino; Dumbledore's first name Albus means \"white\"!"],
  niger:   ["niger","⚫","黑色的","black","denigrate","denigrate(抹黑=说人坏话);尼日尔河、尼日利亚由\"黑河\"得名。","denigrate (to blacken a name); the river Niger and Nigeria carry the \"black river.\""],
  ruber:   ["ruber","🔴","红色的","red","ruby, rubric","ruby(红宝石);rubric(标题/评分标准)——中世纪书籍用红字写标题!","ruby; rubric — medieval books wrote their headings in red ink!"],
  viridis: ["viridis","🟢","绿色的","green","verdant","verdant(苍翠的)、verdigris(铜绿);法语 vert、西语 verde。","verdant, verdigris; French vert, Spanish verde."],
  caeruleus:["caeruleus","🔵","蓝色的","blue","cerulean","cerulean(天青色,颜料管上的正式色名);它是 caelum(天空)的亲戚——天空的颜色!","cerulean, the color on paint tubes; kin to caelum (sky) — the sky's own color!"],
  flavus:  ["flavus","🟡","黄色的;金发的","yellow, golden","flavone","化学黄酮类 flavone 因黄色得名;罗马诗人称金发为 flavus。","Chemistry's yellow flavones are named for it; Roman poets called golden hair flavus."],
  purpureus:["purpureus","🟣","紫色的","purple","purple","purple 由它变来;泰尔紫染料贵过黄金,罗马只有皇帝能穿全紫!","purple wore down from it; Tyrian purple cost more than gold — only emperors wore it fully!"],
  color:   ["color","🎨","颜色","color","color, colorful","color/colour、colorful;西语 color——三种语言同一个词。","color/colour, colorful; Spanish color — one word across the languages."],

  /* ---- C1 L10 自由之日 Freedom (boss) ---- */
  libertas:["libertas","🕊️","自由","freedom","liberty, liberate","liberty(自由)——纽约自由女神 Statue of Liberty!liberate(解放)、liberal。","liberty — the Statue of Liberty herself! liberate, liberal."],
  felix:   ["felix","🍀","幸运的;幸福的","lucky, happy","felicity","felicity(幸福)、felicitations(道贺);Felix 至今是常见人名——\"幸运儿\"。","felicity, felicitations; Felix is still a common name — \"the lucky one.\""],
  laetus:  ["laetus","😄","高兴的","glad","Letitia","laetitia(喜悦)→人名 Letitia;考古学家在罗马杯子上常见祝辞 laetus vive(开心地活)!","laetitia (joy) → the name Letitia; Roman cups toast laetus vive — \"live glad!\""],
  victor:  ["victor","🥇","胜利者","winner","Victor, victorious","victorious(胜利的);人名 Victor;运动会总冠军旧称 victor ludorum(赛会之胜者)。","victorious; the name Victor; a games champion was the victor ludorum."],
  patria:  ["patria","🏳️","祖国","homeland","patriot, expatriate","pater(父)→patria(父邦=祖国):patriot(爱国者)、expatriate(旅居国外者)。","From pater: the fatherland; patriot, expatriate (one out of the fatherland)."],
  memoria: ["memoria","🧠","记忆","memory","memory, memorial","memory、memorial(纪念碑=记忆之所)、memorandum(备忘录=该记住的事)。","memory, memorial (a place of remembering), memorandum (a thing to be remembered)."],
  fama:    ["fama","📣","名声","fame","fame, famous","fame、famous;defame(诽谤=毁人名声);罗马神话里 Fama 是长满耳目的流言女神!","fame, famous, defame; in myth Fama was the goddess of rumor, covered in eyes and ears!"],
  historia:["historia","📚","故事;历史","story, history","history, story","history 和 story 本是同一个词分了家——历史就是最了不起的故事。","history and story are the SAME word split in two — history is the greatest story."],
  finis:   ["finis","🏁","结束;边界","end","finish, final, infinite","finish、final、infinite(无限=没有边界);老电影结尾打出 FIN 就是它。","finish, final, infinite (without end); old films end with FIN — this word."],
  initium: ["initium","🌅","开始","beginning","initial, initiate","initial(首字母=开头的)、initiate(开启/引入门)。","initial (the beginning letter), initiate."],
  novus:   ["novus","🆕","新的","new","novel, innovate, nova","novel(新颖的;小说=新故事)、innovate(创新)、nova(新星=突然亮起的星)。","novel (new; a novel is a new story), innovate, nova (a suddenly-new star)."],
  vetus:   ["vetus","🏺","旧的;古老的","old","veteran","veteran(老兵/老手=经历多年的人)、inveterate(积习已久的)。","veteran (one of many years), inveterate."],
  semper:  ["semper","♾️","永远","always","Semper Fidelis","美国海军陆战队格言 Semper Fidelis(永远忠诚),缩写 Semper Fi!","The US Marines' motto: Semper Fidelis — \"Always Faithful,\" Semper Fi!"],
  numquam: ["numquam","🚫","从不","never","—","ne(不)+umquam(任何时候)=\"任何时候都不\";格言 numquam retro——决不后退!","ne (not) + umquam (ever) = \"not ever\"; motto numquam retro — never backward!"],
  hodie:   ["hodie","📅","今天","today","aujourd'hui","hoc die(在这一天)缩成 hodie;法语 aujourd'hui 里的 hui 就是它;西语 hoy。","hoc die (on this day) squeezed into hodie; it hides in French aujourd'hui; Spanish hoy."],
  cras:    ["cras","🌄","明天","tomorrow","procrastinate","procrastinate(拖延)= pro+cras,\"推到明天\"——拖延症的学名里藏着它!","procrastinate = pro + cras, \"to push to tomorrow\" — the very anatomy of putting things off!"],
  heri:    ["heri","🌇","昨天","yesterday","hier","法语 hier、意语 ieri(昨天);英语 yesterday 的 yester- 同印欧根。","French hier, Italian ieri; the yester- of yesterday shares the ancient root."],
  tempus:  ["tempus","⏳","时间","time","temporary, tempo","temporary(暂时的)、tempo(音乐速度)、tense(动词时态);铭言 Tempus fugit——时光飞逝。","temporary, tempo, tense (of verbs); Tempus fugit — time flies."],
  annus:   ["annus","🗓️","年","year","annual, anniversary","annual(每年的)、anniversary(周年=年之回转)、annals(编年史)。","annual, anniversary (the year's turning), annals."],
  dies:    ["dies","🌞","日子;白天","day","diary, carpe diem","diary(日记=逐日之书)、per diem(按日计);名句 Carpe diem——把握今天!","diary (a day-book), per diem; Carpe diem — seize the day!"],
};

/* =====================================================
   ART — public-domain paintings & sculptures (Wikimedia Commons)
   ===================================================== */
const IMG = f => `https://commons.wikimedia.org/wiki/Special:FilePath/${f}?width=800`;

/* =====================================================
   CHAPTERS — 10 great chapters, each with 10 levels
   Only chapter 1 is fully built; others are locked previews.
   ===================================================== */
const CHAPTERS = [
  {
    id: "labyrinthus",
    name: { zh: "第一关 · 克里特迷宫", en: "I · The Labyrinth of Crete" },
    icon: "🌀",
    art: IMG("Ruins_of_the_Minoan_Palace_in_Knossos.jpg"),
    artCaption: {
      zh: "《忒修斯战米诺陶》大理石雕塑,拉梅(Ramey)作,巴黎杜乐丽花园",
      en: "\"Theseus Fighting the Minotaur\", marble, by Ramey, Tuileries Garden, Paris"
    },
    story: {
      zh: "雅典王子忒修斯自愿前往克里特岛,深入代达罗斯建造的无尽迷宫,去消灭吃人的牛头怪米诺陶。公主阿里阿德涅送给他一个线团——进去时放线,回来时收线。这是希腊神话中最著名的逃脱故事。",
      en: "Prince Theseus of Athens sails to Crete and enters the endless Labyrinth built by Daedalus to slay the man-eating Minotaur. Princess Ariadne gives him a ball of thread — unroll it going in, follow it coming out. The most famous escape story in Greek myth."
    },
    levels: [
      { name: { zh: "第1级 · 王宫告别", en: "Level 1 · Farewell at the Palace" },
        story: { zh: "出发前夜,忒修斯在雅典王宫与父亲埃勾斯国王告别。要在克里特的宫廷里生存,先得认识那里的人:国王、王后、公主……", en: "The night before sailing, Theseus bids farewell to his father King Aegeus. To survive the court of Crete, first learn its people: king, queen, princess…" },
        art: IMG("Themis_Aigeus_Antikensammlung_Berlin_F2538.jpg"),
        cap: { zh: "《埃勾斯王求问神谕》红绘陶杯,约公元前440年,柏林古代收藏馆", en: "\"King Aegeus Consults the Oracle\", red-figure kylix, ca. 440 BC, Antikensammlung Berlin" },
        words: ["pater","mater","filius","filia","rex","regina","puer","puella","femina","vir","frater","soror","amicus","populus","deus","dea","heros","nomen","familia","domus"] },
      { name: { zh: "第2级 · 黑帆之船", en: "Level 2 · The Black-Sailed Ship" },
        story: { zh: "载着贡品少年的黑帆船驶向克里特。海风、星辰、波浪——水手们喊出的每一个词,都是航海的密码。", en: "The black-sailed ship carries the tribute youths toward Crete. Wind, stars, waves — every word the sailors shout is a code of the sea." },
        art: IMG("Ship_procession_fresco,_part_1,_Akrotiri,_Greece.jpg"),
        cap: { zh: "《船队巡游》壁画,锡拉岛阿克罗蒂里,约公元前1600年", en: "\"Ship Procession\" fresco, Akrotiri, Thera, ca. 1600 BC" },
        words: ["navis","aqua","mare","ventus","caelum","stella","sol","luna","nauta","insula","unda","tempestas","portus","terra","nubes","pluvia","remus","velum","piscis","iter"] },
      { name: { zh: "第3级 · 米诺斯王宫", en: "Level 3 · The Palace of Minos" },
        story: { zh: "克诺索斯王宫金碧辉煌:大理石柱、壁画、喷泉。但每一扇门后都可能藏着危险。记住宫殿里每样东西的名字。", en: "The palace of Knossos glitters: marble columns, frescoes, fountains. But danger may hide behind every door. Learn the name of everything in the palace." },
        art: IMG("Bull_leaping_minoan_fresco_archmus_Heraklion.jpg"),
        cap: { zh: "《跳牛》壁画,克诺索斯王宫,伊拉克利翁考古博物馆", en: "\"Bull-Leaping\" fresco, Palace of Knossos, Heraklion Archaeological Museum" },
        words: ["porta","ianua","murus","turris","aula","mensa","sella","lucerna","fenestra","tectum","columna","statua","hortus","fons","aurum","argentum","marmor","pictura","servus","convivium"] },
      { name: { zh: "第4级 · 公主的礼物", en: "Level 4 · The Princess's Gifts" },
        story: { zh: "深夜,公主阿里阿德涅悄悄找到忒修斯,交给他一个线团和一把剑:「带上我的爱与智慧,你才能活着回来。」", en: "At midnight Princess Ariadne finds Theseus in secret, pressing a ball of thread and a sword into his hands: \"Take my love and wisdom — only then will you return alive.\"" },
        art: IMG("Johann_Heinrich_Tischbein_-_Ariadne_Helping_Theseus_by_Giving_him_a_Ball_of_Thread,_1779.jpg"),
        cap: { zh: "《阿里阿德涅把线团交给忒修斯》,蒂施拜因绘,1779年", en: "\"Ariadne Helping Theseus by Giving Him a Ball of Thread\", J. H. Tischbein, 1779" },
        words: ["filum","gladius","donum","corona","anulus","gemma","arca","clavis","charta","epistula","liber","verbum","consilium","fides","amor","cor","animus","sapientia","secretum","auxilium"] },
      { name: { zh: "第5级 · 踏入迷宫", en: "Level 5 · Into the Labyrinth" },
        story: { zh: "迷宫之门在身后关闭。黑暗中只有火把的光。左转还是右转?每一个方向词都决定生死。别忘了放线!", en: "The Labyrinth door closes behind you. Only torchlight in the dark. Left or right? Every direction word is life or death. Don't forget the thread!" },
        art: IMG("Cubiculum_42_mosaic_depicting_a_labyrinth_with_Theseus_and_Minotaur_emblem_House_of_the_Labyrinth_Pompeii.jpg"),
        cap: { zh: "迷宫马赛克,庞贝「迷宫之家」,公元前1世纪", en: "Labyrinth mosaic, House of the Labyrinth, Pompeii, 1st c. BC" },
        words: ["lux","tenebrae","via","umbra","silentium","timor","ignis","fax","flamma","saxum","labyrinthus","angulus","dexter","sinister","ante","post","sub","super","intra","exitus"] },
      { name: { zh: "第6级 · 黑暗中的声音", en: "Level 6 · Sounds in the Dark" },
        story: { zh: "深处传来沉重的呼吸声和蹄声。竖起耳朵,睁大眼睛——在黑暗里,你的身体就是你唯一的工具。", en: "From the depths come heavy breathing and hoofbeats. Prick your ears, open your eyes — in the dark, your body is your only tool." },
        art: IMG("George_Frederic_Watts_-_The_Minotaur_-_Google_Art_Project.jpg"),
        cap: { zh: "《米诺陶》,乔治·弗雷德里克·瓦茨绘,1885年,泰特美术馆", en: "\"The Minotaur\", G. F. Watts, 1885, Tate Britain" },
        words: ["vox","auris","oculus","manus","pes","caput","corpus","os","nasus","digitus","bracchium","genu","capillus","dens","lingua","sanguis","spiritus","somnus","vita","mors"] },
      { name: { zh: "第7级 · 野兽的巢穴", en: "Level 7 · The Beast's Den" },
        story: { zh: "巢穴里散落着白骨,墙上刻满了动物:狮、狼、蛇、鹰……还有一头牛。哪一个才是真正的怪物?", en: "Bones litter the den. The walls are carved with beasts: lion, wolf, snake, eagle… and a bull. Which one is the true monster?" },
        art: IMG("Mosaic_of_Orpheus_charming_the_animals,_Nymph%C3%A9as,_Vienne_(St-Rom-en-Gal,_Mus_Gall-Rom)_02.jpg"),
        cap: { zh: "《俄耳甫斯驯服百兽》罗马马赛克,维埃纳,加洛-罗马博物馆", en: "\"Orpheus Charming the Animals\", Roman mosaic, Vienne, Musée gallo-romain" },
        words: ["taurus","leo","lupus","serpens","aquila","equus","canis","felis","avis","ursus","aper","cervus","vacca","ovis","capra","porcus","mus","rana","apis","monstrum"] },
      { name: { zh: "第8级 · 决战米诺陶", en: "Level 8 · Duel with the Minotaur" },
        story: { zh: "米诺陶咆哮着冲来!握紧剑,举起盾。勇气(virtus)不是不害怕,而是害怕时仍然战斗。", en: "The Minotaur charges, roaring! Grip your sword, raise your shield. Courage (virtus) is not being unafraid — it is fighting even when afraid." },
        art: IMG("Mosaic_pavement_oecus_40_House_of_the_Labyrinth_Pompeii.jpg"),
        cap: { zh: "《忒修斯战米诺陶》红绘陶杯,约公元前440年,大英博物馆", en: "\"Theseus Slays the Minotaur\", red-figure kylix, ca. 440 BC, British Museum" },
        words: ["pugna","bellum","hasta","scutum","galea","arma","sagitta","arcus","hostis","miles","fortis","magnus","parvus","celer","tardus","victoria","gloria","virtus","ferrum","clamor"] },
      { name: { zh: "第9级 · 沿线折返", en: "Level 9 · Following the Thread Back" },
        story: { zh: "怪物倒下了!现在沿着线团往回走。岔路口的石板上刻着数字和颜色的暗号——数对了,才能走对路。", en: "The monster falls! Now follow the thread back. Stone tablets at each fork bear codes of numbers and colors — count right to walk right." },
        art: IMG("Ariadne_in_Naxos,_by_Evelyn_De_Morgan,_1877.jpg"),
        cap: { zh: "《纳克索斯岛上的阿里阿德涅》,伊芙琳·德·摩根绘,1877年", en: "\"Ariadne in Naxos\", Evelyn De Morgan, 1877" },
        words: ["unus","duo","tres","quattuor","quinque","sex","septem","octo","novem","decem","centum","mille","albus","niger","ruber","viridis","caeruleus","flavus","purpureus","color"] },
      { name: { zh: "第10级 · 自由之日(关底)", en: "Level 10 · Day of Freedom (Boss)", },
        boss: true,
        story: { zh: "迷宫大门就在眼前!但它由整关所学的词语封印。回忆你走过的每一步——只有真正的英雄才记得来路。", en: "The Labyrinth gate stands before you — sealed by every word of this chapter. Recall each step you took: only a true hero remembers the way." },
        art: IMG("Iwan_Konstantinowitsch_Aiwasowskij_002.jpg"),
        cap: { zh: "《风暴海上的船·日出》,艾瓦佐夫斯基绘", en: "\"Ships on the Stormy Sea, Sunrise\", Ivan Aivazovsky" },
        words: ["libertas","felix","laetus","victor","patria","memoria","fama","historia","finis","initium","novus","vetus","semper","numquam","hodie","cras","heri","tempus","annus","dies"] },
    ],
  },
  {
    id: "orpheus",
    name: { zh: "第二关 · 冥界琴声", en: "II · Orpheus in the Underworld" },
    icon: "🎻",
    art: IMG("Edward_Poynter_-_Orpheus_and_Eurydice.jpg"),
    artCaption: { zh: "《俄耳甫斯与欧律狄刻》,爱德华·波因特绘", en: "\"Orpheus and Eurydice\" by Edward Poynter" },
    story: { zh: "歌手俄耳甫斯为救回亡妻,弹着七弦琴走进冥界,琴声让恶犬安睡、让冥王落泪。冥王答应放人,条件只有一个:走出冥界之前,绝不能回头看她。", en: "The singer Orpheus descends into the Underworld to win back his wife, his lyre lulling the hell-hound and moving Hades to tears. The god agrees — on one condition: he must not look back at her until they reach the light." },
    levels: null,
  },
  {
    id: "olympus",
    name: { zh: "第三关 · 奥林匹斯山", en: "III · Mount Olympus" },
    icon: "⚡",
    art: IMG("Greece_Mount-Olympus_Muses-Plateau_Mytikas-2918m_Christos-Kakkalos-Refuge_Aerial-ISymeonidis-5.jpg"),
    artCaption: { zh: "宙斯(朱庇特)大理石像,卢浮宫藏", en: "Marble statue of Zeus (Jupiter), Louvre Museum" },
    story: { zh: "云端之上的奥林匹斯山住着十二位主神:雷霆之王宙斯、智慧女神雅典娜、海王波塞冬……认识他们的名字,就认识了半个西方语言的词根。", en: "Above the clouds live the Twelve Olympians: Zeus of the thunder, wise Athena, Poseidon of the sea… Learn their names and you learn half the roots of Western languages." },
    levels: null,
  },
  {
    id: "troia",
    name: { zh: "第四关 · 特洛伊木马", en: "IV · The Trojan Horse" },
    icon: "🐴",
    art: IMG("The_Procession_of_the_Trojan_Horse_in_Troy_by_Giovanni_Domenico_Tiepolo.jpg"),
    artCaption: { zh: "《木马进入特洛伊》,提埃坡罗绘", en: "\"The Procession of the Trojan Horse\" by G. D. Tiepolo" },
    story: { zh: "十年攻不下的城墙,被一只藏满士兵的巨大木马攻破。史上最著名的计谋,教会我们一句拉丁语:「小心带礼物的希腊人。」", en: "Walls that held for ten years fall to a giant wooden horse full of soldiers. History's most famous trick teaches a Latin warning: \"Beware of Greeks bearing gifts.\"" },
    levels: null,
  },
  {
    id: "odyssea",
    name: { zh: "第五关 · 奥德赛归途", en: "V · The Odyssey" },
    icon: "🧜‍♀️",
    art: IMG("Siren_Painter_ARV_289_1_Odysseus_and_the_Sirens_-_three_erotes_(02).jpg"),
    artCaption: { zh: "《尤利西斯与塞壬》,德雷珀绘", en: "\"Ulysses and the Sirens\" by H. J. Draper" },
    story: { zh: "特洛伊战争结束了,奥德修斯却用了十年才回到家:独眼巨人、女妖塞壬的歌声、海怪的漩涡……每一站都是一场逃脱。", en: "The war is over, yet Odysseus needs ten more years to reach home: the Cyclops, the Sirens' song, the whirlpool of Charybdis… every stop is an escape room." },
    levels: null,
  },
  {
    id: "hercules",
    name: { zh: "第六关 · 十二试炼", en: "VI · The Labors of Hercules" },
    icon: "🦁",
    art: IMG("Museo_Arqueológico_Nacional_-_38315BIS_-_Mosaico_de_los_trabajos_de_Hércules_01.jpg"),
    artCaption: { zh: "法尔内塞的赫拉克勒斯像,那不勒斯国立考古博物馆", en: "The Farnese Hercules, Naples National Archaeological Museum" },
    story: { zh: "大力神赫拉克勒斯要完成十二件不可能的任务:狮子、九头蛇、金苹果……每一项试炼,都是一关词汇挑战。", en: "Hercules must complete twelve impossible labors: the lion, the Hydra, the golden apples… each labor, a vocabulary trial." },
    levels: null,
  },
  {
    id: "perseus",
    name: { zh: "第七关 · 美杜莎之首", en: "VII · Perseus and Medusa" },
    icon: "🐍",
    art: IMG("Terracotta_painted_gorgoneion_antefix_(roof_tile)_MET_DP233549.jpg"),
    artCaption: { zh: "切利尼《珀耳修斯》青铜像,佛罗伦萨佣兵凉廊", en: "Cellini's bronze \"Perseus\", Loggia dei Lanzi, Florence" },
    story: { zh: "看她一眼就会变成石头。珀耳修斯带着镜面盾牌、飞鞋和隐身头盔,去挑战蛇发女妖美杜莎。", en: "One glance turns you to stone. With a mirror-shield, winged sandals and a helm of invisibility, Perseus hunts the snake-haired Medusa." },
    levels: null,
  },
  {
    id: "argonautae",
    name: { zh: "第八关 · 金羊毛", en: "VIII · The Golden Fleece" },
    icon: "🐏",
    art: IMG("Jason_and_Medea_-_John_William_Waterhouse.jpg"),
    artCaption: { zh: "《伊阿宋与美狄亚》,沃特豪斯绘", en: "\"Jason and Medea\" by J. W. Waterhouse" },
    story: { zh: "伊阿宋召集全希腊的英雄登上阿尔戈号,远航世界尽头,夺取由巨龙看守的金羊毛。", en: "Jason gathers the heroes of Greece aboard the Argo and sails to the world's edge for the Golden Fleece, guarded by a sleepless dragon." },
    levels: null,
  },
  {
    id: "icarus",
    name: { zh: "第九关 · 太阳之翼", en: "IX · The Wings of Icarus" },
    icon: "🪽",
    art: IMG("Relief_of_Daedalus_and_Icarus_MET_217696.jpg"),
    artCaption: { zh: "《伊卡洛斯坠落》,戈维绘,普拉多博物馆", en: "\"The Fall of Icarus\" by J. P. Gowy, Museo del Prado" },
    story: { zh: "建造迷宫的代达罗斯被囚禁在自己的作品里。他用蜡和羽毛造出翅膀带儿子飞离——但伊卡洛斯飞得太高,太阳融化了蜡……", en: "Daedalus, builder of the Labyrinth, is imprisoned in his own creation. He crafts wings of wax and feathers to fly out with his son — but Icarus flies too close to the sun…" },
    levels: null,
  },
  {
    id: "pandora",
    name: { zh: "第十关 · 潘多拉魔盒", en: "X · Pandora's Box" },
    icon: "🏺",
    art: IMG("Pandora_-_John_William_Waterhouse.jpg"),
    artCaption: { zh: "《潘多拉》,沃特豪斯绘", en: "\"Pandora\" by J. W. Waterhouse" },
    story: { zh: "众神送给人类第一位女性一只绝不能打开的盒子。当好奇心战胜警告,所有灾祸飞向人间——盒底只剩下一样东西:希望。", en: "The gods give the first woman a box that must never be opened. When curiosity wins, every evil flies into the world — and one thing remains at the bottom: Hope." },
    levels: null,
  },
];
