/* =====================================================
   FUGA MYTHICA — Chapter II content: Orpheus in the Underworld
   200 new words + 10 levels. Loaded after data.js/extras.js.
   ===================================================== */
const WORDS2 = {
  /* ---- C2 L1 俄耳甫斯的琴 The Lyre ---- */
  musica:  ["musica","🎵","音乐","music","music, musician","希腊缪斯女神 Musae 的技艺=音乐;music、museum(缪斯的殿堂=博物馆)都来自缪斯。","The art of the Muses; music and museum (the Muses' hall) both spring from them."],
  carmen:  ["carmen","🎶","歌;诗","song, poem","charm","carmen(歌)→ 法语 charme → 英语 charm(魅力/咒语)——歌声本来就是魔法!歌剧《卡门》就叫 Carmen。","carmen → French charme → English charm — a song was always magic! The opera Carmen bears this name."],
  lyra:    ["lyra","🎻","里拉琴","lyre","lyric, lyrics","lyric(抒情诗)、lyrics(歌词)=配里拉琴唱的诗;天琴座 Lyra 就是俄耳甫斯的琴!","lyric and lyrics are poems sung to the lyre; the constellation Lyra IS Orpheus's harp!"],
  chorda:  ["chorda","🪢","琴弦","string","chord, cord","chord(和弦)、cord(绳索);吉他六根弦,每根都是一条 chorda。","chord and cord; every guitar string is a chorda."],
  sonus:   ["sonus","🔊","声响","sound","sonic, sonata","sonic(声速的)、sonata(奏鸣曲=用声音演奏的)、resonate(共鸣=再次发声)。","sonic, sonata (a sounded piece), resonate (to sound again)."],
  cantus:  ["cantus","🎤","歌唱","singing","chant, enchant","chant(吟唱)、enchant(施魔法=用歌声迷住)、cantata(康塔塔)。","chant, enchant (to spell-bind by song), cantata."],
  poeta:   ["poeta","✒️","诗人","poet","poet, poetry","希腊 poietes=创作者;poet、poem、poetry——诗人是\"造\"出作品的人。","Greek poietes = maker; a poet is one who makes."],
  ars:     ["ars","🎨","技艺;艺术","art, skill","art, artist","art、artist、artificial(人工的=用技艺造的);格言 ars longa, vita brevis(艺术长存,人生短暂)。","art, artist, artificial (made by skill); ars longa, vita brevis — art is long, life is short."],
  tibia:   ["tibia","🪈","笛子","flute","tibia","古罗马的笛子用胫骨制成——所以你的小腿骨医学名就叫 tibia(胫骨)!","Roman flutes were carved from shin-bones — that's why your shin-bone is the tibia!"],
  tympanum:["tympanum","🥁","鼓","drum","tympani, eardrum","乐队定音鼓 timpani;耳膜医学名 tympanic membrane——耳朵里有一面小鼓。","orchestral timpani; your eardrum is the tympanic membrane — a tiny drum in the ear."],
  numerus: ["numerus","🔢","节拍;数","rhythm, number","number, numerous","number(数字)、numerous(众多的);诗歌的\"格律\"罗马人也叫 numerus——节拍就是数数。","number, numerous; Romans called poetic meter numerus — rhythm is counting."],
  versus:  ["versus","📜","诗行","verse, line","verse, version","vertere(转)→ versus:犁地到头一\"转\"=一行诗;verse(诗节)、version(版本=转出来的样子)。","From vertere (to turn): a verse is the plough's turn at the row's end; verse, version."],
  fabula:  ["fabula","🎭","故事;戏剧","story, play","fable, fabulous","fable(寓言)、fabulous(神奇的=像故事一样);fa-(说)的家族。","fable, fabulous (story-like); from fa- (to speak)."],
  scaena:  ["scaena","🎬","舞台","stage","scene, scenario","scene(场景)、scenario(剧本);电影的每一\"场\"都站在这个词上。","scene, scenario; every movie scene stands on this word."],
  theatrum:["theatrum","🏟️","剧场","theater","theater","希腊 theatron=观看之地;theater、theatrical(戏剧性的)。","Greek theatron = a place for watching; theater, theatrical."],
  plausus: ["plausus","👏","掌声","applause","applause, plausible","applause(掌声)、applaud;plausible(貌似可信的=值得鼓掌的)。","applause, applaud; plausible originally meant worthy of applause."],
  silva:   ["silva","🌲","森林","forest","sylvan, Pennsylvania","sylvan(森林的);宾夕法尼亚 Pennsylvania=\"佩恩的林地\";人名 Silvia=林中女孩。","sylvan; Pennsylvania = \"Penn's woodland\"; the name Silvia, girl of the forest."],
  arbor:   ["arbor","🌳","树","tree","arbor, Arbor Day","Arbor Day(植树节)、arboretum(树木园);凉亭 arbor=绿树搭的棚。","Arbor Day, arboretum; a garden arbor is a bower of trees."],
  fera:    ["fera","🐾","野兽","wild beast","fierce, feral","feral(野生的)、fierce(凶猛的)——俄耳甫斯的琴声连 ferae 都会驯服。","feral, fierce — Orpheus's lyre tamed even the ferae."],
  echo:    ["echo","📣","回声","echo","echo","希腊回声女神 Echo 的名字原样传到今天——她只能重复别人的话。","The nymph Echo's name survives unchanged — she could only repeat others' words."],

  /* ---- C2 L2 婚礼之殇 The Wedding ---- */
  sponsa:  ["sponsa","👰","新娘","bride","spouse, sponsor","spondere(许诺)→ sponsa(被许诺的人=新娘);spouse(配偶)、sponsor(担保人)。","From spondere (to pledge): the promised one; spouse, sponsor."],
  sponsus: ["sponsus","🤵","新郎","bridegroom","spouse","sponsa 的阳性;婚礼就是一场彼此的\"许诺\"。","Masculine of sponsa; a wedding is a mutual pledge."],
  nuptiae: ["nuptiae","💒","婚礼","wedding","nuptial","nuptial(婚礼的);法语 noces;\"新婚的\"都说 nuptial。","nuptial; French noces."],
  taeda:   ["taeda","🕯️","婚礼火把","wedding torch","—","罗马婚礼由松木火把引路;诗人用 taeda 直接代指婚姻。","Roman weddings marched by pine-torch light; poets used taeda to mean marriage itself."],
  flos:    ["flos","🌸","花","flower","flora, flourish","flora(植物群/花神芙罗拉)、floral、flourish(繁荣=开花);flour(面粉)原是\"谷物之花\"!","flora, floral, flourish (to flower); even flour was once the \"flower of grain\"!"],
  rosa:    ["rosa","🌹","玫瑰","rose","rose, rosary","rose;rosary(玫瑰念珠);西语 rosa、法语 rose——玫瑰走遍欧洲没改名。","rose, rosary; Spanish rosa, French rose — the rose crossed Europe unrenamed."],
  lilium:  ["lilium","🌷","百合","lily","lily","lily;法国王室纹章 fleur-de-lis=百合花饰。","lily; the French royal fleur-de-lis is the lily flower."],
  herba:   ["herba","🌿","草","grass, herb","herb, herbivore","herb(香草)、herbivore(食草动物)、herbal tea(草本茶)。","herb, herbivore, herbal."],
  pratum:  ["pratum","🌾","草地","meadow","prairie","法语 pré、西语 prado(马德里普拉多博物馆=草地博物馆!);prairie(北美大草原)。","French pré, Spanish prado (the Prado Museum = \"the Meadow\"!); prairie."],
  vipera:  ["vipera","🐍","毒蛇","viper","viper","viper(毒蛇);vivus+parere\"活着生产\"——古人以为毒蛇直接生小蛇。","viper; from vivus+parere \"live-bearing\" — the ancients thought vipers bore live young."],
  venenum: ["venenum","☠️","毒液","poison, venom","venom","venom(毒液);原意竟是\"爱情药水\"——从维纳斯 Venus 来,后来药变成了毒。","venom; it first meant \"love-potion\" (from Venus) — the potion turned to poison."],
  vulnus:  ["vulnus","🩹","伤口","wound","vulnerable","vulnerable(脆弱的=可以被伤到的)、invulnerable(刀枪不入的)。","vulnerable (woundable), invulnerable."],
  gaudium: ["gaudium","😊","欢乐","joy","joy, rejoice","gaudium → 法语 joie → 英语 joy;rejoice(欢庆);西语 gozo。","gaudium → French joie → English joy; rejoice; Spanish gozo."],
  lacrima: ["lacrima","💧","眼泪","tear","lacrimal, lachrymose","泪腺医学名 lacrimal gland;lachrymose(催泪的);意大利名酒\"基督之泪\"Lacryma Christi。","the lacrimal gland; lachrymose; the wine Lacryma Christi, \"Christ's tear.\""],
  dolor:   ["dolor","💔","悲痛","grief, pain","dolorous, condolence","condolence(吊唁=一同悲伤)、dolorous;西语 dolor(疼痛)天天在用。","condolence (grieving together), dolorous; Spanish dolor is everyday speech."],
  luctus:  ["luctus","🖤","哀悼","mourning","—","罗马人服丧称 in luctu;哀乐、丧期都围绕这个词。","Romans in mourning were in luctu."],
  funus:   ["funus","⚰️","葬礼","funeral","funeral, funereal","funeral(葬礼)、funereal(阴沉如葬礼的)。","funeral, funereal."],
  sepulcrum:["sepulcrum","🪦","坟墓","tomb","sepulcher","sepulcher(圣墓);sepelire(埋葬)+ -crum(场所)。","sepulcher; sepelire (to bury) + -crum (place)."],
  cinis:   ["cinis","🌫️","灰烬","ashes","incinerate","incinerate(焚化=化为灰)、incinerator(焚化炉);灰姑娘 Cinderella 的 cinder 是日耳曼亲戚。","incinerate (turn to ash); Cinderella's cinders are the Germanic cousins."],
  fatum:   ["fatum","🧵","命运","fate","fate, fatal","fa-(说)→ fatum(神\"说\"定的事=命运);fate、fatal(致命的)、fairy(仙女)也从它变来!","From fa- (speak): what the gods have spoken; fate, fatal — and even fairy!"],

  /* ---- C2 L3 冥界之门 Gates of the Underworld ---- */
  inferi:  ["inferi","🌑","冥界;下界诸神","the underworld","inferior, inferno","inferior(下方的/较差的)、inferno(地狱火,但丁《神曲·地狱篇》Inferno)。","inferior (lower), inferno — Dante's Inferno."],
  regnum:  ["regnum","👑","王国","kingdom","reign, interregnum","reg-(统治)家族:reign(统治)、interregnum(王位空缺期=两朝之间)。","The reg- family: reign, interregnum (between reigns)."],
  imperium:["imperium","🏛️","统治权;帝国","rule, empire","empire, imperial","empire(帝国)、imperial(帝国的)、emperor(皇帝)。","empire, imperial, emperor."],
  thronus: ["thronus","🪑","王座","throne","throne","希腊 thronos → throne;王座在哪,权力就在哪。","Greek thronos → throne; where the seat is, the power is."],
  sceptrum:["sceptrum","🪄","权杖","scepter","scepter","scepter(权杖);希腊 skeptron=倚仗之杖。","scepter; Greek skeptron, the staff one leans on."],
  caverna: ["caverna","🕳️","洞穴","cavern","cave, cavern","cave、cavern(大洞穴)、cavity(蛀牙洞!)——都是 cavus(空的)一家。","cave, cavern, cavity (the hole in your tooth!) — all from cavus (hollow)."],
  spelunca:["spelunca","🦇","洞窟","cave","spelunking","spelunking(洞穴探险)——美国探洞爱好者直接用了这个拉丁词。","spelunking — cave explorers took this Latin word whole."],
  abyssus: ["abyssus","🌀","深渊","abyss","abyss, abyssal","abyss(深渊)、abyssal(深海的);希腊 a-byssos=无底。","abyss, abyssal; Greek a-byssos = bottomless."],
  vallis:  ["vallis","⛰️","山谷","valley","valley, vale","valley、vale;Yosemite Valley 的 valley 就是它。","valley, vale."],
  mons:    ["mons","🗻","山","mountain","mountain, Montana","mountain、mount;蒙大拿 Montana=多山之州;勃朗峰 Mont Blanc=白山。","mountain, mount; Montana (mountain state); Mont Blanc, the White Mountain."],
  collis:  ["collis","🌄","小丘","hill","colline","hill 同印欧根;意语 collina(丘陵)。","hill shares the ancient root; Italian collina."],
  ripa:    ["ripa","🏞️","河岸","riverbank","riparian, river","riparian(河岸的);river 经法语 rivière 从\"岸\"变成了\"河\"!","riparian; river came via French rivière — from the bank to the stream itself!"],
  fluvius: ["fluvius","🌊","河流","river","fluvial, fluent","fluere(流)家族:fluvial(河流的)、fluent(流利的=说话像水流)、influence(流入的力量)。","From fluere (to flow): fluvial, fluent (flowing speech), influence (a flowing-in)."],
  stagnum: ["stagnum","🪷","池沼","pool","stagnant","stagnant(死水般停滞的)、stagnate——不流动的水。","stagnant, stagnate — water that will not flow."],
  palus:   ["palus","🐸","沼泽","marsh","paludal","paludal(沼泽的);疟疾旧名 paludism=沼泽病。","paludal; malaria's old name paludism, the marsh disease."],
  nebula:  ["nebula","🌫️","雾","mist, fog","nebula, nebulous","天文星云就叫 nebula!nebulous(模糊如雾的)。","An astronomical nebula IS this word! nebulous."],
  frigus:  ["frigus","🥶","寒冷","cold","frigid, refrigerator","frigid(严寒的)、refrigerator(冰箱=再造寒冷之机)!","frigid, refrigerator — the machine that makes cold again!"],
  gelu:    ["gelu","🧊","冰霜","frost","gel, gelato","gelatin(明胶=冻住的)、意大利冰淇淋 gelato、jelly——全是\"冻\"家族。","gelatin, Italian gelato, jelly — the frozen family."],
  horror:  ["horror","😱","战栗","dread","horror, horrible","horrere(毛发直立)→ horror、horrible;恐怖片 horror film 的词源是\"汗毛倒竖\"。","From horrere (hair standing on end): horror, horrible — the shiver itself."],
  custos:  ["custos","💂","守卫","guardian","custody, custodian","custody(监护/拘留)、custodian(管理员);报纸《卫报》拉丁味十足。","custody, custodian — the keeper's family."],

  /* ---- C2 L4 摆渡人与三头犬 The Ferryman ---- */
  portitor:["portitor","🛶","摆渡人","ferryman","port-","port(渡口)+ -itor(从业者)——卡戎就是冥河的 portitor。","port (crossing) + -itor (worker) — Charon is the portitor of the Styx."],
  cymba:   ["cymba","🚣","小舟","skiff","—","希腊 kymbe(小船);卡戎的渡船在诗里就叫 cymba。","Greek kymbe; Charon's boat is the cymba of the poets."],
  ratis:   ["ratis","🪵","木筏","raft","—","raft 是日耳曼亲戚;诗人也用 ratis 泛指船。","raft is the Germanic cousin; poets used ratis for any vessel."],
  merces:  ["merces","🪙","报酬;船费","fee, wages","mercenary, merchant","mercenary(雇佣兵=为钱打仗)、merchant(商人)、mercy(怜悯,\"上天的报偿\")。","mercenary (paid soldier), merchant, mercy (heaven's recompense)."],
  nummus:  ["nummus","💰","钱币","coin","numismatics","numismatics(钱币学)——收藏古币的学问。","numismatics, the study of coins."],
  latratus:["latratus","🔊","犬吠","barking","—","latrare(吠)的名词;三头犬的 latratus 三倍响亮。","From latrare (to bark); Cerberus's latratus is three times as loud."],
  guttur:  ["guttur","🗣️","咽喉","throat","guttural","guttural(喉音的)——德语的小舌音就是 guttural sound。","guttural — the throaty sounds of language."],
  ungula:  ["ungula","🐾","爪;蹄","claw, hoof","ungulate","ungulate(有蹄类动物)——马、牛、鹿的学名总称。","ungulate — the hoofed animals of zoology."],
  cauda:   ["cauda","🦎","尾巴","tail","coda, queue","音乐术语 coda(尾声)、queue(排队=一条长尾)、西语 cola。","musical coda (the tail of a piece), queue (a waiting tail), Spanish cola."],
  pellis:  ["pellis","🧥","毛皮","hide, pelt","pelt, surplice","pelt(兽皮);film 的祖先? no—surplice 白袍;西语 piel(皮肤)。","pelt; Spanish piel (skin)."],
  belua:   ["belua","🐋","巨兽","huge beast","—","诗人用 belua 称呼一切庞然大物——从鲸鱼到河马。","Poets called any vast creature a belua — whale or hippo alike."],
  draco:   ["draco","🐉","龙;巨蛇","dragon","dragon, Draco","dragon;天龙座 Draco;《哈利·波特》马尔福的名字 Draco 就是\"龙\"!","dragon; the constellation Draco; Draco Malfoy is literally \"Dragon\"!"],
  gigas:   ["gigas","🗿","巨人","giant","giant, gigantic","giant、gigantic;十亿字节 gigabyte 的 giga- 就是\"巨\"!","giant, gigantic; the giga- in gigabyte means giant!"],
  nympha:  ["nympha","🧚","宁芙仙女","nymph","nymph","nymph(自然精灵);蜻蜓若虫也叫 nymph——半成的美丽。","nymph; a dragonfly's young is also a nymph — beauty half-formed."],
  anima:   ["anima","👻","魂灵","soul","animate, animism","anima(气息→灵魂);animism(万物有灵论)、animation(动画=赋予灵魂)。","anima (breath → soul); animism, animation (giving things a soul)."],
  spectrum:["spectrum","🌈","幽灵;幻象","ghost, apparition","spectrum, specter","specter(幽灵);牛顿把彩虹色带命名为 spectrum——光的\"幻象\"!","specter; Newton named the rainbow band a spectrum — light's own apparition!"],
  phantasma:["phantasma","🎭","幻影","phantom","phantom, fantasy","phantom(幻影)、fantasy(幻想)、fantastic——希腊 phainein(显现)家族。","phantom, fantasy, fantastic — from Greek phainein (to appear)."],
  turba:   ["turba","👥","人群;骚乱","crowd","disturb, turbulent","disturb(搅乱)、turbulent(动荡的)、turbine(涡轮=旋转的乱流)。","disturb, turbulent, turbine — the swirling family."],
  multitudo:["multitudo","🧑‍🤝‍🧑","大众","multitude","multitude, multi-","multitude;multi-(多)前缀家族:multiply、multimedia。","multitude; the multi- prefix: multiply, multimedia."],
  ordo:    ["ordo","📏","队列;秩序","row, order","order, ordinary","order(秩序)、ordinary(平常的=按次序的)、coordinate(协调=共同排序)。","order, ordinary (in due order), coordinate."],

  /* ---- C2 L5 忘川之水 Waters of Forgetting ---- */
  oblivio: ["oblivio","🫥","遗忘","oblivion","oblivion, oblivious","oblivion(彻底遗忘)、oblivious(浑然不觉的);忘川 Lethe 的拉丁名就是 Oblivio。","oblivion, oblivious; the river Lethe's Latin name is Oblivio."],
  flumen:  ["flumen","🏞️","大河","river","flume","flume(引水槽/漂流滑道);fluere(流)的中性名词。","flume; the neuter noun of fluere (to flow)."],
  rivus:   ["rivus","💧","小溪","brook","rival, derive","rival(对手)原意\"同饮一溪的人\"——邻居才会争水!derive(源自=从溪里引出)。","A rival was one who shared your brook — neighbors quarrel over water! derive (to draw from the stream)."],
  lacus:   ["lacus","🏊","湖","lake","lake, lagoon","lake、lagoon(潟湖)、西语 lago。","lake, lagoon, Spanish lago."],
  gurges:  ["gurges","🌀","漩涡;深流","whirlpool","gorge, gurgle","gorge(峡谷/吞咽)、gurgle(咕噜声)、regurgitate(反刍)。","gorge, gurgle, regurgitate."],
  vortex:  ["vortex","🌪️","漩涡","vortex","vortex, vertigo","vortex 原样进入英语;亲戚 vertigo(眩晕=天旋地转)。","vortex kept whole; its cousin vertigo, the spinning head."],
  gutta:   ["gutta","💧","水滴","drop","gutter, gout","gutter(排水沟=集水滴之处);医学 gout(痛风,古人以为是\"滴\"下的病)。","gutter (where drops gather); gout, the \"dropping\" disease of old medicine."],
  umor:    ["umor","💦","湿气;体液","moisture","humor, humid","humor(幽默)原是古医学\"四体液\"——体液平衡决定脾气!humid(潮湿的)。","humor was medicine's four fluids — your fluids fixed your mood! humid."],
  vapor:   ["vapor","♨️","蒸汽","steam","vapor, evaporate","vapor(蒸气)、evaporate(蒸发=变成气跑掉)。","vapor, evaporate."],
  ardor:   ["ardor","🔥","灼热;热情","blaze, passion","ardent, arson","ardent(热切的)、arson(纵火罪);ardere(燃烧)家族。","ardent, arson — the burning family of ardere."],
  aestus:  ["aestus","🌡️","热浪;潮汐","heat, tide","estuary","estuary(入海口=潮水进退之处);estival(夏季的)。","estuary (where the tide surges), estival (of summer)."],
  glacies: ["glacies","🧊","冰","ice","glacier, glacial","glacier(冰川)、glacial(冰河期的/极冷的)。","glacier, glacial."],
  sulphur: ["sulphur","🌋","硫磺","sulfur","sulfur","sulfur/sulphur 原样传下;火山口的黄色气味就是它。","sulfur kept whole; the yellow breath of volcanoes."],
  sitis:   ["sitis","🥤","口渴","thirst","—","医学 polydipsia? 希腊系;拉丁 sitis 留在西语 sed 里。","Spanish sed (thirst) carries it on."],
  fames:   ["fames","🍽️","饥饿","hunger","famine, famished","famine(饥荒)、famished(饿极了)。","famine, famished."],
  poculum: ["poculum","🏺","杯","cup","—","罗马宴会祝酒举起 poculum;po-(饮)家族,和 potio 是亲戚。","Romans toasted with the poculum; kin to potio in the drinking family."],
  potio:   ["potio","🧪","饮料;药水","drink, potion","potion, poison","potion(魔药)与 poison(毒药)竟是同一个词的两条路!都从\"喝的东西\"来。","potion and poison are the SAME word down two roads — both \"something to drink.\""],
  limus:   ["limus","🟤","淤泥","mud, slime","limo-","冥河之岸满是 limus;slime 是日耳曼亲戚。","The underworld banks are thick with limus; slime is the Germanic kin."],
  murmur:  ["murmur","🌊","低语;水声","murmur","murmur","murmur 原样传下——拟声词:水声、人语、心脏杂音都用它。","murmur survives unchanged — onomatopoeia for water, whispers, and heart sounds."],
  profundum:["profundum","⬇️","深处","the deep","profound","profound(深刻的)、profundity;pro+fundus(底)=直到底部。","profound, profundity; pro + fundus (bottom) = down to the very bottom."],

  /* ---- C2 L6 审判之庭 The Judges ---- */
  iudex:   ["iudex","⚖️","法官","judge","judge, judicial","ius(法)+ dicere(说)=\"宣法者\";judge、judicial、prejudice(预先判断=偏见)。","ius (law) + dicere (speak) = the law-speaker; judge, judicial, prejudice."],
  iudicium:["iudicium","🏛️","审判","trial, judgment","judgment","judgment;final judgment(最终审判)沿用两千年。","judgment; the \"final judgment\" phrase is two thousand years old."],
  lex:     ["lex","📜","法律","law","legal, legislate","legal(合法的)、legislate(立法)、legitimate(正当的)、loyal(忠诚=守法的)!","legal, legislate, legitimate — and loyal (law-keeping)!"],
  ius:     ["ius","🕊️","法;正义","law, right","just, justice","just(公正的)、justice(正义)、jury(陪审团)、injury(伤害=不合法之事)。","just, justice, jury, injury (an un-right)."],
  iustitia:["iustitia","👩‍⚖️","公正","justice","justice","正义女神 Iustitia(蒙眼持天平)站在全世界法院门口。","Lady Justice — Iustitia with her blindfold and scales — stands before the world's courts."],
  crimen:  ["crimen","🚨","罪行;指控","crime, charge","crime, criminal","crime、criminal、incriminate(牵连入罪)。","crime, criminal, incriminate."],
  culpa:   ["culpa","🙇","过错","fault","culpable, culprit","culpable(有责的)、culprit(罪犯);道歉语 mea culpa(我的错)今天还在用!","culpable, culprit; people still say mea culpa — \"my fault!\""],
  poena:   ["poena","⛓️","惩罚","penalty","penalty, pain","penalty(处罚)、punish、pain(疼痛)——痛苦原是一种\"刑罚\";subpoena(传票=罚则之下)。","penalty, punish, pain (suffering as sentence); subpoena (under penalty)."],
  carcer:  ["carcer","🔒","监狱","prison","incarcerate","incarcerate(监禁);赛车起点的栅栏罗马人也叫 carceres!","incarcerate; Roman race-track starting gates were carceres too!"],
  catena:  ["catena","⛓️","锁链","chain","chain, concatenate","chain(链条);编程术语 concatenate(连接字符串=串成链)!","chain; programmers concatenate strings — chain them together!"],
  vinculum:["vinculum","🪢","束缚","bond","vinculum","数学上分数线/根号顶的横线就叫 vinculum——把数字\"绑\"在一起。","In math the bar that binds numbers together is the vinculum."],
  veritas: ["veritas","💎","真相","truth","verity, verify","verify(验证)、verdict(裁决=说出真相)、very(非常,原意\"真正地\");哈佛校训就是 VERITAS。","verify, verdict (truth spoken), very (originally \"truly\"); Harvard's motto is VERITAS."],
  testis:  ["testis","🗣️","证人","witness","testify, testament","testify(作证)、testament(遗嘱/圣约)、contest(对证→竞争)、protest(公开作证→抗议)。","testify, testament, contest, protest (to witness forth)."],
  causa:   ["causa","❓","案件;原因","case, cause","cause, because, excuse","cause、because(由于)、excuse(开脱=移出案由)、accuse(控告=归入案由)。","cause, because, excuse (out of the case), accuse (into the case)."],
  sententia:["sententia","🧑‍⚖️","判决;见解","sentence, opinion","sentence","sentence(句子/判决)——法官的一句话就是一个 sentence;sentire(感受)家族。","sentence — both the judge's word and the grammar unit; from sentire (to feel)."],
  innocens:["innocens","😇","无辜的","innocent","innocent","in(不)+ nocens(害人的)=innocent;nocere(伤害)家族。","in (not) + nocens (harming) = innocent."],
  nocens:  ["nocens","😈","有罪的","guilty","noxious, innocuous","noxious(有害的)、innocuous(无害的);nocere(伤害)。","noxious, innocuous; from nocere (to harm)."],
  supplicium:["supplicium","⚡","酷刑","torment","supplication","sub+plicare(屈膝跪下)——受刑与哀求共用一个词根;supplication(哀求)。","sub + plicare (to kneel): torment and supplication share the bent knee."],
  labor:   ["labor","💪","苦役;劳动","toil, labor","labor, laboratory","labor(劳动)、laboratory(实验室=劳作之地)、collaborate(协作=共同劳动)。","labor, laboratory (a place of toil), collaborate."],
  rota:    ["rota","☸️","轮","wheel","rotate, rotary","rotate(旋转)、rotary、rotation;伊克西翁被绑在永转的 rota 上!","rotate, rotary, rotation; Ixion spins forever on his rota!"],

  /* ---- C2 L7 冥王的宝座 The Dark Throne ---- */
  dominus: ["dominus","🤴","主人","lord, master","dominate, domain","domus(家)→ dominus(一家之主);dominate、domain(领地)、Dominic(主日出生的)。","From domus: master of the house; dominate, domain, the name Dominic."],
  domina:  ["domina","👸","女主人","lady, mistress","dame, madonna","domina → 意语 donna、madonna(我的女主人)、法语 dame、英语 dame/madam。","domina → Italian donna, madonna (my lady), French dame, English madam."],
  maiestas:["maiestas","👑","威严","majesty","majesty, majestic","majesty(陛下)、majestic(庄严的);magnus(大)的家族。","majesty, majestic; family of magnus (great)."],
  potentia:["potentia","⚡","力量","power","potent, potential","potent(强效的)、potential(潜力=尚未释放的力量)、omnipotent(全能的)。","potent, potential (power not yet loosed), omnipotent."],
  potestas:["potestas","🏛️","权力","authority","power, possess","power 经法语 pouvoir 从这里来;possess(占有)。","power came via French pouvoir; possess."],
  honor:   ["honor","🎖️","荣誉","honor","honor, honest","honor、honest(诚实的=有荣誉感的)、honorary(荣誉的)。","honor, honest (honor-bound), honorary."],
  superbia:["superbia","😤","傲慢","pride","superb","superb(华丽的)——super(在上)的家族;傲慢是把自己放太高。","superb — of the super family; pride is placing yourself too high."],
  ira:     ["ira","😡","愤怒","anger, wrath","irate, irascible","irate(暴怒的)、irascible(易怒的)。","irate, irascible."],
  invidia: ["invidia","👀","嫉妒","envy","envy, invidious","in+videre(盯着看)=envy(嫉妒就是盯着别人的好东西看!);invidious(招人嫉恨的)。","in + videre (to stare at): envy IS staring at another's goods; invidious."],
  misericordia:["misericordia","🤲","怜悯","mercy, pity","misericord","miser(可怜)+ cor(心)=为可怜人而动的心;misericord(慈悲座)。","miser (wretched) + cor (heart): a heart moved for the wretched; misericord."],
  clementia:["clementia","🕊️","仁慈","clemency","clement, inclement","clemency(宽赦)、inclement weather(恶劣天气=不仁慈的天)!","clemency; inclement weather is the sky showing no mercy!"],
  preces:  ["preces","🙏","祈求","prayers","pray, precarious","pray、prayer;precarious(不稳的=全靠恳求维持的)。","pray, prayer; precarious (held only by begging)."],
  votum:   ["votum","🕯️","誓愿","vow","vow, vote, devote","vow(誓言)、vote(投票=表达意愿)、devote(奉献)。","vow, vote (a wish declared), devote."],
  templum: ["templum","🏛️","神庙","temple","temple, contemplate","temple;contemplate(沉思)原指占卜官在 templum 里观天!","temple; contemplate first meant reading the sky within the sacred templum!"],
  ara:     ["ara","🔥","祭坛","altar","—","天坛座 Ara 是南天星座——众神的祭坛挂在星空里。","The constellation Ara, the gods' altar, hangs in the southern sky."],
  sacrificium:["sacrificium","🐑","祭品","sacrifice","sacrifice, sacred","sacer(神圣)+ facere(做)=把东西\"做成神圣\";sacrifice、sacred。","sacer (holy) + facere (make): to make a thing holy; sacrifice, sacred."],
  thesaurus:["thesaurus","📚","宝库","treasury","treasure, thesaurus","treasure(宝藏)由它磨损而来;同义词词典叫 thesaurus——词汇的宝库!","treasure wore down from it; a thesaurus is a treasure-house of words!"],
  opes:    ["opes","💎","财富","wealth","opulent, copious","opulent(豪奢的)、copious(丰富的,co+opes)。","opulent, copious (co + opes)."],
  diadema: ["diadema","👑","冠冕","diadem","diadem","diadem(王冠);希腊 diadein(缠绕)——最早的王冠是一条绸带。","diadem; Greek diadein (to bind round) — the first crown was a ribbon."],
  numen:   ["numen","✨","神意","divine will","numinous","numinous(神圣感的);nuere(点头)——神一点头,万物皆动。","numinous; from nuere (to nod) — creation moves at a god's nod."],

  /* ---- C2 L8 琴动冥府 The Song that Moved Hell ---- */
  eloquentia:["eloquentia","🎙️","口才","eloquence","eloquent, loquacious","e+loqui(说出)=eloquence;loquacious(健谈的)、colloquial(口语的)。","e + loqui (speak out): eloquence; loquacious, colloquial."],
  suavitas:["suavitas","🍯","甜美","sweetness","suave, persuade","suave(温文尔雅的);persuade(说服)藏着 suade——用\"甜\"打动人!","suave; persuade hides the same sweetness — you win people by honey!"],
  dulcis:  ["dulcis","🍬","甜的","sweet","dulcet, dolce","dulcet tones(悦耳之声);意语音乐术语 dolce(柔美地);西语 dulce(糖果)。","dulcet tones; Italian dolce in music; Spanish dulce (candy)."],
  amarus:  ["amarus","☕","苦的","bitter","marinade?","意语 amaro(苦味酒);西语 amargo;和 amor 无关——苦与爱只差一个字母!","Italian amaro (bitter liqueur); Spanish amargo; one letter from amor — bitterness and love!"],
  mollis:  ["mollis","🧸","柔软的","soft","mollify, emollient","mollify(安抚=使变软)、emollient(润肤的)。","mollify (to soften someone), emollient."],
  durus:   ["durus","🪨","坚硬的","hard","durable, endure","durable(耐用的)、endure(忍耐=硬扛)、duration(持续)。","durable, endure (to stay hard), duration."],
  blandus: ["blandus","😊","温柔的","gentle, charming","bland, blandish","blandish(甜言蜜语);bland(平淡的)——太温柔就没味道了!","blandish (to coax); bland — too gentle loses all flavor!"],
  ferox:   ["ferox","🦁","凶猛的","fierce","ferocious","ferocious(凶残的)、ferocity;fera(野兽)的家族。","ferocious, ferocity; family of fera (wild beast)."],
  mirus:   ["mirus","😲","神奇的","wonderful","miracle, admire","miracle(奇迹)、admire(赞叹=朝着看得出神)、mirror(镜子=让人看得出神之物)。","miracle, admire (to wonder at), mirror (a thing to wonder into)."],
  mirabilis:["mirabilis","🌟","奇妙的","marvelous","marvel","marvel(奇观)经法语 merveille 而来;拉丁美洲的\"世界奇观\"都用它。","marvel via French merveille."],
  stupor:  ["stupor","😶","惊愕","amazement","stupor, stupendous","stupor(呆滞)、stupendous(惊人的)、stupefy(使目瞪口呆)。","stupor, stupendous, stupefy."],
  admiratio:["admiratio","👏","赞叹","admiration","admiration","admiration;ad+mirari(对着惊叹)。","admiration; ad + mirari (to wonder at)."],
  desiderium:["desiderium","🌠","思念","longing","desire","desire(渴望)——de+sidus(星):原意\"仰望星空等待\"!","desire — de + sidus (star): to await watching the stars!"],
  spes:    ["spes","🌅","希望","hope","despair, prosper","despair(绝望=失去希望,de+sperare)、prosper(昌盛=如所希望)。","despair (hope lost: de+sperare), prosper (as hoped)."],
  promissum:["promissum","🤝","承诺","promise","promise","pro+mittere(先送出去)=promise——话先送出去,人再跟上。","pro + mittere (send ahead): a promise is a word sent ahead of the deed."],
  condicio:["condicio","📋","条件","condition","condition","condition(条件);冥王的 condicio:不许回头。","condition; Hades' condicio: do not look back."],
  pactum:  ["pactum","🖋️","契约","pact","pact","pact(公约);pacisci(缔约)——和平 pax 是它的姐妹!","pact; from pacisci (to covenant) — pax (peace) is its sister!"],
  foedus:  ["foedus","🤝","盟约","treaty","federal, federation","federal(联邦的)、federation(联盟)——美国的 federal 政府=靠盟约结成的政府。","federal, federation — a federal government is one bound by treaty."],
  gratia:  ["gratia","🙏","恩典;感谢","grace, thanks","grace, gratitude","grace(优雅/恩典)、gratitude(感恩)、congratulate(祝贺)、西语 gracias!","grace, gratitude, congratulate, Spanish gracias!"],
  venia:   ["venia","🕊️","宽恕","pardon","venial","venial sin(可宽恕的小过)——神学沿用至今。","venial — a venial sin is a pardonable one."],

  /* ---- C2 L9 回头之禁 Do Not Look Back ---- */
  aspectus:["aspectus","👀","目光","gaze","aspect","aspect(方面=看的角度);ad+specere(看)——spect 家族的大门。","aspect (an angle of seeing); ad + specere — gateway to the spect- family."],
  visus:   ["visus","👁️","视觉","sight","vision, visible","vision、visible、visit(去看望)、television(远距离看!)。","vision, visible, visit (to go see), television (far-seeing!)."],
  retro:   ["retro","🔙","向后","backward","retro, retrospect","retro(复古风=向后看的风格)、retrospect(回顾)、retrograde(倒退)。","retro style (looking back), retrospect, retrograde."],
  gradus:  ["gradus","🪜","脚步;台阶","step, degree","grade, gradual","grade(等级=台阶)、gradual(逐步的)、graduate(毕业=登上台阶)。","grade (a step), gradual, graduate (to step up)."],
  passus:  ["passus","👣","步伐","pace","pace, pass","pace(步速)、pass(通过)、passage;罗马千步=一英里(mille passus)。","pace, pass, passage; a Roman mile was mille passus."],
  cursus:  ["cursus","🏃","奔跑;路线","course","course, cursor","course(课程/路线)、cursor(光标=屏幕上的奔跑者!)、excursion(远足)。","course, cursor (the little runner on your screen!), excursion."],
  fuga:    ["fuga","🏃‍♂️","逃亡","flight, escape","fugitive, refuge","fugitive(逃亡者)、refuge(避难所)、fugue(赋格曲=声部互相追逃);游戏名 FUGA MYTHICA 就是它!","fugitive, refuge, fugue (voices in flight); the game's own name FUGA MYTHICA!"],
  reditus: ["reditus","🔄","返回","return","—","re(回)+ itus(走)=归途;俄耳甫斯的 reditus 只差最后一步。","re (back) + itus (going): the return; Orpheus's reditus lacked one last step."],
  ascensus:["ascensus","⬆️","上坡","ascent","ascend, ascension","ascend(上升)、ascent;ad+scandere(攀爬)。","ascend, ascent; ad + scandere (to climb)."],
  descensus:["descensus","⬇️","下坡","descent","descend, descendant","descend(下降)、descendant(后代=从祖先降下来的人)。","descend, descendant (one come down the line)."],
  lumen:   ["lumen","💡","光亮","light, lamp","luminous, illuminate","luminous(发光的)、illuminate;流明 lm——灯泡亮度单位就是 lumen!","luminous, illuminate; the lumen (lm) rates your lightbulbs!"],
  claritas:["claritas","🌞","明亮;清晰","brightness","clarity, clear","clarity(清晰)、clear、declare(宣告=说清楚)、claret? 主要三个即可。","clarity, clear, declare (to make clear)."],
  obscuritas:["obscuritas","🌚","昏暗","darkness","obscure","obscure(晦暗的/使模糊)、obscurity(默默无闻)。","obscure, obscurity."],
  dubium:  ["dubium","🤔","怀疑","doubt","doubt, dubious","doubt、dubious(可疑的);duo(二)藏在里面——怀疑就是心分两半!","doubt, dubious; duo hides inside — to doubt is to be of two minds!"],
  cura:    ["cura","🩺","担忧;照料","care","cure, curious, secure","cure(治愈=被照料)、curious(好奇=多操心的)、secure(安全=无忧,se+cura)、manicure。","cure, curious (full of care), secure (se + cura: free of care), manicure."],
  desperatio:["desperatio","🌧️","绝望","despair","desperate","desperate(孤注一掷的)、desperado(亡命徒)。","desperate, desperado."],
  fiducia: ["fiducia","🤝","信心","confidence","fiduciary","fiduciary(受信托的);fid-(信)家族又添一员。","fiduciary; one more branch of the fid- (trust) tree."],
  patientia:["patientia","⏳","耐心","patience","patience, patient","patience、patient(病人=正在忍耐的人!);pati(承受)。","patience; a patient is literally \"one who endures\"; from pati (to suffer)."],
  festinatio:["festinatio","⏩","急躁","haste","festinate","罗马格言 festina lente(慢慢地快=从容不迫)!","The Roman motto festina lente — \"make haste slowly!\""],
  error:   ["error","🌀","错误;迷路","error, wandering","error, erratic","errare(徘徊)→ error(错误原是\"走岔路\");erratic(飘忽不定的);格言 errare humanum est(人皆会犯错)。","From errare (to wander): an error is a wrong turn; erratic; errare humanum est — to err is human."],

  /* ---- C2 L10 永恒之歌 The Eternal Song (boss) ---- */
  aeternitas:["aeternitas","♾️","永恒","eternity","eternal, eternity","eternal、eternity;aevum(时代)家族——medieval(中世纪)也是亲戚。","eternal, eternity; kin of aevum (age) — so is medieval."],
  immortalitas:["immortalitas","🌟","不朽","immortality","immortal","im(不)+ mortal(会死)+ -itas(状态)=不朽;mort-(死)家族的反面。","im (not) + mortal + -itas: deathlessness; the bright side of the mort- family."],
  natura:  ["natura","🌍","自然","nature","nature, natural","nasci(诞生)→ natura(被生出来的一切);nature、native(本地出生的)、nation(民族=同生之人)。","From nasci (to be born): all that is born; nature, native, nation."],
  mundus:  ["mundus","🌐","世界","world","mundane","mundane(尘世的/平凡的);西语 mundo、法语 monde——\"全世界\"tout le monde!","mundane; Spanish mundo, French monde — tout le monde, \"all the world\"!"],
  orbis:   ["orbis","⭕","圆;天下","circle, globe","orbit, orb","orbit(轨道)、orb(圆球);教皇文告 Urbi et Orbi=致罗马城与全世界。","orbit, orb; the papal Urbi et Orbi — to the City and the World."],
  principium:["principium","🌅","本原;开端","beginning","principle, principal","principle(原理)、principal(首要的);primus(第一)+ capere(拿)=第一个拿到的。","principle, principal; primus (first) + capere (take)."],
  elementum:["elementum","🧱","元素","element","element, elementary","element、elementary(基础的);字母表也曾叫 elementa——LMN 三个字母连读!","element, elementary; the alphabet was once elementa — read the letters L-M-N!"],
  harmonia:["harmonia","🎼","和声","harmony","harmony, harmonica","harmony、harmonica(口琴);希腊 harmos(接合)——把不同的音接合在一起。","harmony, harmonica; Greek harmos (a joining) — different notes joined as one."],
  concordia:["concordia","💞","和睦","concord","concord, concordance","con(共同)+ cord(心)=同心;concord(和谐)、concordance(索引/一致)。","con + cord (heart): hearts together; concord, concordance."],
  discordia:["discordia","⚡","不和","discord","discord","dis(分离)+ cord(心)=离心;不和女神 Discordia 扔出了金苹果,特洛伊战争由此而起!","dis + cord: hearts apart; the goddess Discordia threw the golden apple that began the Trojan War!"],
  genius:  ["genius","🧞","守护灵;天赋","guardian spirit, talent","genius, genie","罗马人相信每人生来有一位 genius(守护灵)——天才 genius、精灵 genie 都从这来。","Every Roman was born with a guardian genius — whence genius and genie."],
  laurus:  ["laurus","🌿","月桂","laurel","laurel, laureate","laurel(桂冠)、laureate(桂冠得主)——诺贝尔奖得主 Nobel laureate!人名 Laura。","laurel, laureate — every Nobel laureate wears Apollo's tree; the name Laura."],
  praemium:["praemium","🏅","奖赏","reward, prize","premium","premium(优质的/保费)=prae+emere(先拿到的好东西)。","premium — prae + emere: the thing taken first."],
  monumentum:["monumentum","🗿","纪念碑","monument","monument","monere(提醒)+ -mentum=让人记住之物;monument;贺拉斯诗句:我立起了比青铜更久的纪念碑。","monere (remind) + -mentum: a thing that makes you remember; Horace: \"I have built a monument more lasting than bronze.\""],
  littera: ["littera","🔤","字母;文学","letter, literature","letter, literal, literature","letter(字母/信)、literal(字面的)、literature(文学)、illiterate(不识字的)。","letter, literal, literature, illiterate."],
  scriptor:["scriptor","✍️","作家","writer","scribe, script","scribere(写)家族:scribe(抄写员)、script(剧本)、describe(描写)、manuscript。","The scribere family: scribe, script, describe, manuscript."],
  lector:  ["lector","📖","读者","reader","lecture, lectern","legere(读)家族:lecture(讲读)、lectern(读经台)、legend(传奇=当读之事)、select(选读)。","The legere family: lecture, lectern, legend (what must be read), select."],
  vates:   ["vates","🔮","先知诗人","bard, prophet","vatic","vatic(预言的);梵蒂冈 Vatican 山名可能与占卜者有关——诗人=预言者。","vatic (prophetic); the Vatican hill may recall the old soothsayers — the poet as prophet."],
  opus:    ["opus","🎼","作品","work","opus, opera, operate","opus(作品第几号 Op.1!)、opera(歌剧=众多作品)、operate(工作)、cooperate(合作)。","opus (Op. 1!), opera (works), operate, cooperate."],
  auctor:  ["auctor","🖋️","作者;创始人","author, founder","author, authority","author(作者)、authority(权威=创始者的话语权)、authentic(真实的)。","author, authority (the founder's voice), authentic."],
};

/* merge new words */
Object.assign(WORDS, WORDS2);

/* ---- Chapter II levels ---- */
(function () {
  const ch = CHAPTERS.find(c => c.id === "orpheus");
  const IMG2 = IMG;
  ch.levels = [
    { name: { zh: "第1级 · 俄耳甫斯的琴", en: "Level 1 · The Lyre of Orpheus", es: "Nivel 1 · La lira de Orfeo", fr: "Niveau 1 · La lyre d'Orphée", de: "Level 1 · Die Leier des Orpheus", ja: "レベル1 · オルフェウスの竪琴" },
      story: { zh: "俄耳甫斯是世上最伟大的歌手:琴声一起,树木拔根而来,野兽温顺伏地,石头也落泪。先学会音乐与诗的词语,才能听懂他的力量。", en: "Orpheus is the greatest singer alive: at his lyre trees uproot to follow, beasts lie tame, stones weep. Learn the words of music and poetry to grasp his power.", es: "Orfeo es el mayor cantor: a su lira los árboles lo siguen y las fieras se amansan.", fr: "Orphée est le plus grand chanteur : à sa lyre, les arbres le suivent et les bêtes s'apaisent.", de: "Orpheus ist der größte Sänger: Bei seiner Leier folgen ihm Bäume und Bestien werden zahm.", ja: "オルフェウスは世界一の歌い手。竪琴を弾けば木々は根を抜いて集まり、獣はひれ伏し、石さえ涙を流す。" },
      art: IMG2("Roelant_Savery_-_Orpheus_Charming_the_Animals_with_his_Music_-_157_-_Mauritshuis.jpg"),
      cap: { zh: "《俄耳甫斯以琴声驯服百兽》,鲁兰特·萨弗里绘,莫瑞泰斯皇家美术馆", en: "\"Orpheus Charming the Animals\", Roelant Savery, Mauritshuis", es: "\"Orfeo encantando a los animales\", R. Savery, Mauritshuis", fr: "« Orphée charmant les animaux », R. Savery, Mauritshuis", de: "„Orpheus bezaubert die Tiere“, R. Savery, Mauritshuis", ja: "《動物を魅了するオルフェウス》R・サーフェリー画、マウリッツハイス美術館" },
      words: ["musica","carmen","lyra","chorda","sonus","cantus","poeta","ars","tibia","tympanum","numerus","versus","fabula","scaena","theatrum","plausus","silva","arbor","fera","echo"] },
    { name: { zh: "第2级 · 婚礼之殇", en: "Level 2 · The Wedding Cut Short", es: "Nivel 2 · La boda truncada", fr: "Niveau 2 · Les noces brisées", de: "Level 2 · Die zerbrochene Hochzeit", ja: "レベル2 · 婚礼の悲劇" },
      story: { zh: "婚礼当天,新娘欧律狄刻在花草地上被毒蛇咬伤,倒在了火把与玫瑰之间。欢乐的词语一瞬间全变成了悲伤的词语。", en: "On the wedding day, the bride Eurydice steps on a viper in the meadow and falls among torches and roses. In one instant, every word of joy turns to a word of grief.", es: "El día de la boda, una víbora muerde a Eurídice en el prado. La alegría se vuelve duelo.", fr: "Le jour des noces, une vipère mord Eurydice dans le pré. La joie devient deuil.", de: "Am Hochzeitstag beißt eine Viper Eurydike auf der Wiese. Freude wird zu Trauer.", ja: "婚礼の日、花咲く草地で毒蛇が花嫁エウリュディケを噛んだ。喜びの言葉は一瞬で悲しみの言葉に変わる。" },
      art: IMG2("Eurydice_Bitten_by_the_Snake_MET_ap32.27.jpg"),
      cap: { zh: "《被蛇咬伤的欧律狄刻》,大都会艺术博物馆", en: "\"Eurydice Bitten by the Snake\", The Met, New York", es: "\"Eurídice mordida por la serpiente\", The Met", fr: "« Eurydice mordue par le serpent », The Met", de: "„Eurydike von der Schlange gebissen“, The Met", ja: "《蛇に噛まれるエウリュディケ》メトロポリタン美術館" },
      words: ["sponsa","sponsus","nuptiae","taeda","flos","rosa","lilium","herba","pratum","vipera","venenum","vulnus","gaudium","lacrima","dolor","luctus","funus","sepulcrum","cinis","fatum"] },
    { name: { zh: "第3级 · 冥界之门", en: "Level 3 · The Gates Below", es: "Nivel 3 · Las puertas del inframundo", fr: "Niveau 3 · Les portes des Enfers", de: "Level 3 · Die Tore der Unterwelt", ja: "レベル3 · 冥界の門" },
      story: { zh: "俄耳甫斯背起琴,走向活人不可进入的地方:穿过山谷与洞窟,雾气越来越冷,前方就是冥界的入口。", en: "Orpheus shoulders his lyre and walks where no living soul may go: through valleys and caverns, into colder and colder mist, toward the mouth of the underworld.", es: "Orfeo camina por valles y cavernas hacia la boca del inframundo.", fr: "Orphée marche par vallées et cavernes vers la bouche des Enfers.", de: "Orpheus wandert durch Täler und Höhlen zum Schlund der Unterwelt.", ja: "オルフェウスは竪琴を背に、生者の入れぬ場所へ。谷と洞窟を抜けるほど霧は冷たく——冥界の入口はすぐそこだ。" },
      art: IMG2("Joachim_Patinir_007.jpg"),
      cap: { zh: "《冥河渡舟》,帕蒂尼尔绘,普拉多博物馆", en: "\"Crossing the River Styx\", Joachim Patinir, Museo del Prado", es: "\"El paso de la laguna Estigia\", Patinir, Museo del Prado", fr: "« Le Passage du Styx », Patinir, musée du Prado", de: "„Überfahrt über den Styx“, Patinir, Prado", ja: "《ステュクス川の渡し》パティニール画、プラド美術館" },
      words: ["inferi","regnum","imperium","thronus","sceptrum","caverna","spelunca","abyssus","vallis","mons","collis","ripa","fluvius","stagnum","palus","nebula","frigus","gelu","horror","custos"] },
    { name: { zh: "第4级 · 摆渡人与三头犬", en: "Level 4 · The Ferryman and the Hound", es: "Nivel 4 · El barquero y el can", fr: "Niveau 4 · Le passeur et le chien", de: "Level 4 · Fährmann und Höllenhund", ja: "レベル4 · 渡し守と三つ首の犬" },
      story: { zh: "冥河边,老船夫卡戎只渡亡魂,不渡活人;对岸,三头犬刻耳柏洛斯的吠声震动岩壁。琴声响起——船夫伸出了手,恶犬闭上了六只眼睛。", en: "At the river, old Charon ferries only the dead; on the far bank the three-headed hound Cerberus shakes the rock with his barking. The lyre sounds — the ferryman reaches out his hand, and the hound closes all six eyes.", es: "Caronte solo cruza a los muertos; Cerbero ladra en la otra orilla. Suena la lira y ambos ceden.", fr: "Charon ne passe que les morts ; Cerbère aboie sur l'autre rive. La lyre sonne — tous deux cèdent.", de: "Charon fährt nur Tote über; Zerberus bellt am anderen Ufer. Die Leier erklingt — beide geben nach.", ja: "冥河の渡し守カロンは死者しか運ばない。対岸では三つ首の番犬ケルベロスの咆哮が岩を揺らす。だが竪琴が鳴ると——渡し守は手を差し伸べ、番犬は六つの目を閉じた。" },
      art: IMG2("Lytovchenko_Olexandr_Kharon.jpg"),
      cap: { zh: "《卡戎渡魂》,利托夫琴科绘,俄罗斯博物馆", en: "\"Charon Carries Souls Across the Styx\", O. Lytovchenko, Russian Museum", es: "\"Caronte cruzando almas\", O. Lytovchenko", fr: "« Charon passant les âmes », O. Lytovchenko", de: "„Charon setzt Seelen über“, O. Lytovchenko", ja: "《魂を運ぶカロン》リトフチェンコ画、ロシア美術館" },
      words: ["portitor","cymba","ratis","merces","nummus","latratus","guttur","ungula","cauda","pellis","belua","draco","gigas","nympha","anima","spectrum","phantasma","turba","multitudo","ordo"] },
    { name: { zh: "第5级 · 忘川之水", en: "Level 5 · Waters of Forgetting", es: "Nivel 5 · Las aguas del olvido", fr: "Niveau 5 · Les eaux de l'oubli", de: "Level 5 · Wasser des Vergessens", ja: "レベル5 · 忘却の川" },
      story: { zh: "冥界有五条河:恨水、哀水、火水、誓水,以及最危险的忘川——喝一口,便忘掉一切。俄耳甫斯捂住嘴,一步一步蹚过去。", en: "Five rivers run below: hate, wailing, fire, oaths — and most dangerous, Lethe, the water of forgetting: one sip erases everything. Orpheus covers his mouth and wades on.", es: "Cinco ríos corren abajo; el más peligroso es el Lete: un sorbo borra todo recuerdo.", fr: "Cinq fleuves coulent en bas ; le plus dangereux est le Léthé : une gorgée efface tout.", de: "Fünf Flüsse fließen unten; der gefährlichste ist die Lethe: ein Schluck löscht alles.", ja: "冥界には五つの川が流れる。もっとも危険なのは忘却の川レテ——ひと口飲めば、すべてを忘れてしまう。" },
      art: IMG2("John_Roddam_Spencer_Stanhope_(1829-1908)_-_The_Waters_of_Lethe_by_the_Plains_of_Elysium_-_1889.4_-_Manchester_Art_Gallery.jpg"),
      cap: { zh: "《乐土平原旁的忘川》,斯坦厄普绘,曼彻斯特美术馆", en: "\"The Waters of Lethe by the Plains of Elysium\", J. R. S. Stanhope, Manchester Art Gallery", es: "\"Las aguas del Lete\", Stanhope, Mánchester", fr: "« Les eaux du Léthé », Stanhope, Manchester", de: "„Die Wasser der Lethe“, Stanhope, Manchester", ja: "《エリュシオンの野辺のレテの水》スタンホープ画、マンチェスター美術館" },
      words: ["oblivio","flumen","rivus","lacus","gurges","vortex","gutta","umor","vapor","ardor","aestus","glacies","sulphur","sitis","fames","poculum","potio","limus","murmur","profundum"] },
    { name: { zh: "第6级 · 审判之庭", en: "Level 6 · The Court of the Dead", es: "Nivel 6 · El tribunal de los muertos", fr: "Niveau 6 · Le tribunal des morts", de: "Level 6 · Das Totengericht", ja: "レベル6 · 死者の法廷" },
      story: { zh: "三位判官审理每一个亡魂;远处,西西弗斯推着永远滚落的巨石,伊克西翁绑在永转的火轮上。这里的每个词都关于法律与惩罚——冥界最讲规矩。", en: "Three judges try every soul; beyond, Sisyphus shoulders his ever-falling boulder and Ixion turns on the burning wheel. Every word here is law and punishment — the underworld keeps strict rules.", es: "Tres jueces juzgan cada alma; Sísifo empuja su roca eterna. Aquí todo es ley y castigo.", fr: "Trois juges jugent chaque âme ; Sisyphe pousse son rocher éternel. Ici, tout est loi et châtiment.", de: "Drei Richter richten jede Seele; Sisyphus wälzt seinen ewigen Fels. Hier ist alles Gesetz und Strafe.", ja: "三人の判官がすべての魂を裁く。彼方ではシーシュポスが永遠に転がり落ちる岩を押し上げる。ここの言葉はすべて法と罰——冥界ほど規則に厳しい場所はない。" },
      art: IMG2("Titian_-_Sisyphus_-_Madrid_-_Prado.jpg"),
      cap: { zh: "《西西弗斯》,提香绘,普拉多博物馆", en: "\"Sisyphus\", Titian, Museo del Prado", es: "\"Sísifo\", Tiziano, Museo del Prado", fr: "« Sisyphe », Titien, musée du Prado", de: "„Sisyphus“, Tizian, Prado", ja: "《シーシュポス》ティツィアーノ画、プラド美術館" },
      words: ["iudex","iudicium","lex","ius","iustitia","crimen","culpa","poena","carcer","catena","vinculum","veritas","testis","causa","sententia","innocens","nocens","supplicium","labor","rota"] },
    { name: { zh: "第7级 · 冥王的宝座", en: "Level 7 · The Dark Throne", es: "Nivel 7 · El trono oscuro", fr: "Niveau 7 · Le trône obscur", de: "Level 7 · Der dunkle Thron", ja: "レベル7 · 冥王の玉座" },
      story: { zh: "宝座大殿上,冥王哈得斯与冥后珀耳塞福涅端坐如夜。要在诸神面前开口,先要懂得权力、威严与怜悯的词语。", en: "In the throne hall sit Hades and Persephone, still as night. To speak before gods, first learn the words of power, majesty and mercy.", es: "Hades y Perséfone reinan inmóviles. Aprende las palabras de poder, majestad y piedad.", fr: "Hadès et Perséphone trônent, immobiles. Apprends les mots de pouvoir, de majesté et de pitié.", de: "Hades und Persephone thronen reglos. Lerne die Wörter für Macht, Majestät und Gnade.", ja: "玉座の間には冥王ハデスと冥后ペルセポネが夜のように静かに座す。神々の前で口を開くには、権力と威厳と慈悲の言葉を知らねばならない。" },
      art: IMG2("Apulian_Red_Figure_volute_krater_with_scenes_of_the_Underworld,_ca._340-330_BC,_Staatliche_Antikensammlungen,_Munich_(8956886411).jpg"),
      cap: { zh: "冥界图卷涡形陶瓶,阿普利亚红绘,约公元前340年,慕尼黑国立文物馆", en: "Apulian volute-krater with Underworld scenes, ca. 340 BC, Staatliche Antikensammlungen, Munich", es: "Crátera apulia con escenas del inframundo, Múnich", fr: "Cratère apulien aux scènes des Enfers, Munich", de: "Apulischer Volutenkrater mit Unterweltszenen, München", ja: "冥界図のアプリア式クラテル、前340年頃、ミュンヘン古代美術博物館" },
      words: ["dominus","domina","maiestas","potentia","potestas","honor","superbia","ira","invidia","misericordia","clementia","preces","votum","templum","ara","sacrificium","thesaurus","opes","diadema","numen"] },
    { name: { zh: "第8级 · 琴动冥府", en: "Level 8 · The Song that Moved Hell", es: "Nivel 8 · El canto que movió el infierno", fr: "Niveau 8 · Le chant qui émut les Enfers", de: "Level 8 · Das Lied, das die Hölle rührte", ja: "レベル8 · 冥府を動かす歌" },
      story: { zh: "俄耳甫斯开始歌唱:唱甜美与苦涩,唱柔软与坚硬,唱思念与希望。铁石心肠的冥王第一次落泪,答应放人——但有一个条件(condicio)。", en: "Orpheus sings: of sweet and bitter, soft and hard, longing and hope. For the first time the iron-hearted king weeps, and grants his wish — on one condition (condicio).", es: "Orfeo canta y, por primera vez, el rey de hierro llora y concede el deseo — con una condición.", fr: "Orphée chante et, pour la première fois, le roi de fer pleure et exauce le vœu — à une condition.", de: "Orpheus singt, und zum ersten Mal weint der eiserne König und gewährt den Wunsch — unter einer Bedingung.", ja: "オルフェウスは歌う——甘さと苦さを、柔らかさと硬さを、恋しさと希望を。鉄の心の冥王が初めて涙を流し、願いを聞き入れた。ただし、一つの条件(condicio)とともに。" },
      art: IMG2("Peter_Paul_Rubens_-_Orpheus_und_Eurydike_vor_Pluto_und_Proserpina_-_R_27_-_Kunsthaus_Z%C3%BCrich.jpg"),
      cap: { zh: "《俄耳甫斯与欧律狄刻在冥王座前》,鲁本斯绘,苏黎世美术馆", en: "\"Orpheus and Eurydice before Pluto and Proserpina\", Rubens, Kunsthaus Zürich", es: "\"Orfeo ante Plutón y Proserpina\", Rubens, Zúrich", fr: "« Orphée devant Pluton et Proserpine », Rubens, Zurich", de: "„Orpheus vor Pluto und Proserpina“, Rubens, Kunsthaus Zürich", ja: "《冥王夫妻の前のオルフェウスとエウリュディケ》ルーベンス画、チューリッヒ美術館" },
      words: ["eloquentia","suavitas","dulcis","amarus","mollis","durus","blandus","ferox","mirus","mirabilis","stupor","admiratio","desiderium","spes","promissum","condicio","pactum","foedus","gratia","venia"] },
    { name: { zh: "第9级 · 回头之禁", en: "Level 9 · Do Not Look Back", es: "Nivel 9 · No mires atrás", fr: "Niveau 9 · Ne te retourne pas", de: "Level 9 · Sieh dich nicht um", ja: "レベル9 · 振り返るなかれ" },
      story: { zh: "条件只有一个:走出冥界之前,绝不能回头看她。上坡路又黑又长,身后听不到脚步声。是怀疑?是担忧?就在光亮的门口,俄耳甫斯回了头——只看到她第二次坠落的影子。", en: "One condition only: do not look back at her before the light. The climb is long and dark; no footsteps sound behind. Doubt? Worry? At the very threshold of light, Orpheus turns — and sees her fall a second time.", es: "Una sola condición: no mirarla antes de la luz. En el umbral, Orfeo se vuelve — y la pierde por segunda vez.", fr: "Une seule condition : ne pas la regarder avant la lumière. Au seuil, Orphée se retourne — et la perd une seconde fois.", de: "Eine einzige Bedingung: sie nicht vor dem Licht anzusehen. An der Schwelle wendet sich Orpheus um — und verliert sie zum zweiten Mal.", ja: "条件はただ一つ——光に出るまで、彼女を振り返らないこと。上り坂は長く暗く、背後に足音は聞こえない。疑いか、不安か。光の戸口で、オルフェウスは振り返った——二度目に堕ちていく彼女の影だけが見えた。" },
      art: IMG2("Orpheus_and_Eurydice_by_Peter_Paul_Rubens.jpg"),
      cap: { zh: "《俄耳甫斯与欧律狄刻》,鲁本斯绘,普拉多博物馆", en: "\"Orpheus and Eurydice\", Rubens, Museo del Prado", es: "\"Orfeo y Eurídice\", Rubens, Museo del Prado", fr: "« Orphée et Eurydice », Rubens, musée du Prado", de: "„Orpheus und Eurydike“, Rubens, Prado", ja: "《オルフェウスとエウリュディケ》ルーベンス画、プラド美術館" },
      words: ["aspectus","visus","retro","gradus","passus","cursus","fuga","reditus","ascensus","descensus","lumen","claritas","obscuritas","dubium","cura","desperatio","fiducia","patientia","festinatio","error"] },
    { name: { zh: "第10级 · 永恒之歌(关底)", en: "Level 10 · The Eternal Song (Boss)", es: "Nivel 10 · El canto eterno (Jefe)", fr: "Niveau 10 · Le chant éternel (Boss)", de: "Level 10 · Das ewige Lied (Boss)", ja: "レベル10 · 永遠の歌(ボス)" },
      boss: true,
      story: { zh: "俄耳甫斯失去了她,但他的歌没有消失:里拉琴升上夜空成为天琴座,他的名字活在每一个 lyric 里。用整关所学的词,唱完这首永恒之歌,冥界之门将为你打开。", en: "Orpheus lost her, but the song did not die: his lyre rose into the sky as the constellation Lyra, and his name lives in every \"lyric\". Sing the eternal song with all this chapter's words, and the gates will open for you.", es: "La lira subió al cielo como la constelación Lyra. Canta el canto eterno con todas las palabras del capítulo.", fr: "La lyre monta au ciel : c'est la constellation de la Lyre. Chante le chant éternel avec tous les mots du chapitre.", de: "Die Leier stieg als Sternbild Lyra in den Himmel. Sing das ewige Lied mit allen Wörtern des Kapitels.", ja: "オルフェウスは彼女を失った。だが歌は消えなかった——竪琴は夜空に昇ってこと座になり、その名はすべての「リリック」の中に生きている。この章のすべての言葉で永遠の歌を歌いきれば、冥界の門は開かれる。" },
      art: IMG2("Nymphs_finding_the_Head_of_Orpheus.jpg"),
      cap: { zh: "《宁芙们发现俄耳甫斯的头颅》,沃特豪斯绘,1900年", en: "\"Nymphs Finding the Head of Orpheus\", J. W. Waterhouse, 1900", es: "\"Ninfas hallando la cabeza de Orfeo\", Waterhouse, 1900", fr: "« Nymphes trouvant la tête d'Orphée », Waterhouse, 1900", de: "„Nymphen finden das Haupt des Orpheus“, Waterhouse, 1900", ja: "《オルフェウスの首を見つけるニンフたち》ウォーターハウス画、1900年" },
      words: ["aeternitas","immortalitas","natura","mundus","orbis","principium","elementum","harmonia","concordia","discordia","genius","laurus","praemium","monumentum","littera","scriptor","lector","vates","opus","auctor"] },
  ];
})();
