/* =====================================================
   FUGA MYTHICA — grammar road for the study language "fr": ten stations,
   added to GRAMS through GRAM_ADD() (defined in grammar.js, loaded first).
   ===================================================== */
/* Fuga Mythica — French grammar road, stations 1–5 */
GRAM_ADD("fr", [
{ id: "fr_genre", icon: "🛡️",
  name: { zh: "名词的性与冠词 · 珀耳修斯的盾牌", en: "Gender and articles · Perseus's shield" },
  scene: { zh: "雅典娜借给珀耳修斯一面光亮如镜的盾牌:le bouclier;赫尔墨斯给他一把弯刃:l'épée(阴性,元音前省作 l');他要取回的是美杜莎的头:la tête。法语里每个名词都有性,连盾牌和剑也分阴阳,冠词 le、la 就是名词的身份证。",
           en: "Athena lends Perseus a shield polished like a mirror: le bouclier. Hermes gives him a curved blade: l'épée, feminine, cut to l' before the vowel. And he goes to fetch the head of Medusa: la tête. Every French noun has a gender, even shields and swords, and the article le or la is the noun's identity card." },
  rule: { zh: "法语名词只有阳性和阴性。定冠词:阳性 le,阴性 la,遇元音或哑音 h 省作 l'(l'épée、l'homme),复数一律 les;不定冠词 un、une,复数 des。词尾是线索:-tion、-sion、-té、-ure、-ette、-ence 多为阴性,-ment、-age、-eau、-isme、-oir 多为阳性。著名例外:la plage、la page、l'image、l'eau 都是阴性。嘘音 h 不省音:le héros。最稳妥的办法是连冠词一起记。",
          en: "French has two genders. The definite article is le (m.) or la (f.), cut to l' before a vowel or mute h (l'épée, l'homme), and les in every plural; the indefinite is un, une, plural des. Endings help: -tion, -sion, -té, -ure, -ette, -ence are mostly feminine; -ment, -age, -eau, -isme, -oir mostly masculine. La plage, la page, l'image and l'eau are famous exceptions. An aspirated h blocks elision: le héros. Learn every noun with its article." },
  table: { cap: { zh: "冠词与性", en: "Articles and gender" },
    head: [{ zh: "类型", en: "Type" }, { zh: "阳性", en: "Masculine" }, { zh: "阴性", en: "Feminine" }, { zh: "复数", en: "Plural" }],
    rows: [["定冠词|Definite", "le bouclier", "la tête", "les armes"],
           ["元音、哑音 h 前|Before a vowel or mute h", "l'homme", "l'épée", "les épées"],
           ["不定冠词|Indefinite", "un casque", "une épée", "des étoiles"],
           ["嘘音 h|Aspirated h", "le héros", "la honte", "les héros"],
           ["常见词尾|Typical endings", "-ment, -age, -eau, -isme, -oir", "-tion, -sion, -té, -ure, -ette, -ence", { zh: "复数冠词不分性", en: "plural articles ignore gender" }],
           ["例词|Examples", "le monument, le voyage", "la nation, la liberté", "les monuments, les nations"],
           ["例外|Exceptions", "le silence, le murmure", "la plage, la page, l'image, l'eau", "les plages, les silences"]] },
  notes: { zh: "法语冠词是拉丁语指示代词的后代:ille「那个(阳)」、illa「那个(阴)」在口语里用得太多,意思渐渐虚化,成了 le、la;un、une 来自数词 ūnus、ūna「一」。古典拉丁语根本没有冠词。拉丁语原有三个性,中性后来并入阳性:templum → le temple,vīnum → le vin;一些以 -a 结尾的中性复数被听成阴性单数:folia「许多叶子」→ la feuille,arma → l'arme。「冠词」article 源自拉丁语 articulus「小关节」,译自希腊语 arthron。",
          en: "The French article comes from a Latin demonstrative: ille, illa, ‘that’, so common in speech that it faded into le and la; un, une come from the numeral ūnus. Classical Latin had no article. Its neuter merged into the masculine: templum became le temple, vīnum le vin; some neuter plurals in -a were heard as feminine singulars: folia, leaves, became la feuille, arma l'arme. The word article is Latin articulus, ‘little joint’, after Greek arthron." },
  ex: [
    { q: { zh: "填空:___ épée de Thésée(忒修斯的剑)", en: "Fill in: ___ épée de Thésée (Theseus's sword)" }, opts: ["l'", "la", "le", "les"], a: 0,
      why: { zh: "épée 是阴性,但以元音开头,la 必须省音成 l':l'épée。写成 la épée 是最常见的错误;le 性别不对,les 是复数。", en: "Épée is feminine but begins with a vowel, so la must elide to l': l'épée. La épée is the classic slip; le has the wrong gender and les is plural." } },
    { q: { zh: "下面哪个名词是阴性?", en: "Which of these nouns is feminine?" }, opts: ["liberté", "courage", "monument", "espoir"], a: 0,
      why: { zh: "-té 结尾的名词多为阴性:la liberté、la beauté。courage(-age)、monument(-ment)、espoir(-oir)都是阳性。", en: "Nouns in -té are mostly feminine: la liberté, la beauté. Courage (-age), monument (-ment) and espoir (-oir) are all masculine." } },
    { q: { zh: "-age 结尾的名词多为阳性。下面哪个是阴性的例外?", en: "Nouns in -age are mostly masculine. Which one is a feminine exception?" }, opts: ["plage", "voyage", "courage", "visage"], a: 0,
      why: { zh: "la plage(海滩)是阴性,同类的例外还有 la page、l'image。le voyage、le courage、le visage 都守规则。", en: "La plage, the beach, is feminine, like la page and l'image. Le voyage, le courage and le visage follow the rule." } },
    { q: { zh: "Thésée entre dans ___ labyrinthe.(忒修斯走进迷宫)", en: "Thésée entre dans ___ labyrinthe. (Theseus enters the labyrinth.)" }, opts: ["le", "la", "l'", "les"], a: 0,
      why: { zh: "labyrinthe 是阳性,以辅音 l 开头,不省音:le labyrinthe。省音只看后面的词是否以元音或哑音 h 开头。", en: "Labyrinthe is masculine and begins with a consonant, so there is no elision: le labyrinthe. Elision depends only on a following vowel or mute h." } },
    { q: { zh: "下面哪个写法是错的?", en: "Which of these is wrong?" }, opts: ["la homme", "l'homme", "l'eau", "le héros"], a: 0,
      why: { zh: "homme 是阳性,开头是哑音 h,所以写 l'homme。le héros 没有错:héros 的 h 是嘘音 h,不省音也不联诵。", en: "Homme is masculine and its h is mute, so it takes l'homme. Le héros is correct: the h of héros is aspirated and blocks elision." } },
    { q: { zh: "Ariane donne ___ fil à Thésée.(阿里阿德涅给了忒修斯一根线)", en: "Ariane donne ___ fil à Thésée. (Ariadne gives Theseus a thread.)" }, opts: ["un", "une", "des", "l'"], a: 0,
      why: { zh: "fil 是阳性单数,不定冠词用 un。une 性别不对,des 是复数,l' 只用在元音或哑音 h 前。", en: "Fil is masculine singular, so the indefinite article is un. Une has the wrong gender, des is plural, and l' only stands before a vowel or mute h." } },
    { q: { zh: "法语定冠词 le、la 来自:", en: "The French articles le and la come from:" },
      opts: [{ zh: "拉丁语指示代词 ille、illa「那个」", en: "the Latin demonstratives ille, illa, ‘that’" }, { zh: "拉丁语数词 ūnus「一」", en: "the Latin numeral ūnus, ‘one’" }, { zh: "拉丁语原有的冠词", en: "an article Latin already had" }, { zh: "希腊语冠词 ho、hē", en: "the Greek articles ho, hē" }], a: 0,
      why: { zh: "古典拉丁语没有冠词。口语里「那个」ille、illa 用得太频繁,意思虚化,成了 le、la。ūnus 演变成的是不定冠词 un。", en: "Classical Latin had no article. Speech used ille, illa, ‘that’, so often that they faded into le and la. Ūnus became the indefinite un." } },
    { q: { zh: "la feuille(叶子)是阴性,它的拉丁语来源 folia 原本是:", en: "La feuille, leaf, is feminine. Its Latin source folia was originally:" },
      opts: [{ zh: "中性复数「许多叶子」", en: "a neuter plural, ‘leaves’" }, { zh: "阴性单数「一片叶子」", en: "a feminine singular, ‘a leaf’" }, { zh: "阳性复数", en: "a masculine plural" }, { zh: "属格单数", en: "a genitive singular" }], a: 0,
      why: { zh: "folium(叶)是中性,复数 folia 以 -a 结尾,听起来像第一变格法的阴性单数,于是被重新理解为「一片叶子」,成了阴性的 la feuille。", en: "Folium was neuter; its plural folia ended in -a and sounded like a first-declension feminine singular. Speakers reread it as ‘a leaf’, and it became feminine la feuille." } },
  ] },

{ id: "fr_pluriel", icon: "🌿",
  name: { zh: "复数与形容词 · 太阳神的马", en: "Plurals and adjectives · The horses of the Sun" },
  scene: { zh: "法厄同求父亲太阳神让他驾一天日车。可拉车的不是一匹马(un cheval),而是四匹烈马(quatre chevaux);日车失控,宙斯用雷霆把他击落。他的姐妹们在河边痛哭,化作了白杨树(des peupliers)。法语复数的 -s、-x 大多不发音,要靠冠词去听。",
           en: "Phaethon begs his father the Sun to let him drive the sun chariot for one day. But it is drawn not by one horse, un cheval, but by four wild ones, quatre chevaux; the chariot runs wild and Zeus strikes the boy down. His sisters weep by the river and turn into poplars, des peupliers. The French plural -s or -x is mostly silent: you hear it in the article." },
  rule: { zh: "名词复数加不发音的 -s,靠冠词、联诵听出(les‿enfants);-eau、-eu 多加 -x,-al 多变 -aux,-s、-x、-z 结尾不变。形容词与名词性数一致:阴性 +e,复数 +s;-eux → -euse,-if → -ive,beau → belle,bon → bonne。形容词多在名词后(la mer bleue);beau、bon、grand、petit、jeune、vieux、nouveau、joli、mauvais 常在前,元音开头的阳性单数名词前用 bel、nouvel、vieil。",
          en: "Nouns add a silent -s, heard in les, des and liaison (les‿enfants). -eau, -eu mostly add -x (bateaux); -al mostly becomes -aux (chevaux); -s, -x, -z stay (la voix). Adjectives agree: +e feminine, +s plural; -eux → -euse, -if → -ive, beau → belle, bon → bonne. Most follow the noun (la mer bleue); beau, bon, grand, petit, jeune, vieux, nouveau, joli, mauvais usually precede it, with bel, nouvel, vieil before a vowel in the masculine singular." },
  table: { cap: { zh: "复数与形容词的变化", en: "Plurals and adjective forms" },
    head: [{ zh: "规则", en: "Rule" }, { zh: "原形 / 单数", en: "Base / singular" }, { zh: "变化后", en: "Changed form" }],
    rows: [["名词复数 +s|Noun plural +s", "la nymphe, l'arbre", "les nymphes, les arbres"],
           ["-eau、-eu 多加 -x|-eau, -eu mostly add -x", "le bateau, le jeu", "les bateaux, les jeux"],
           ["-al 多变 -aux|-al mostly becomes -aux", "le cheval, le journal", "les chevaux, les journaux"],
           ["-s、-x、-z 不变|-s, -x, -z unchanged", "le fils, la voix, le nez", "les fils, les voix, les nez"],
           ["形容词阴性 +e|Adjective feminine +e", "grand, bleu, noir", "grande, bleue, noire"],
           ["-eux、-if 的阴性|Feminine of -eux, -if", "heureux, vif", "heureuse, vive"],
           ["不规则阴性|Irregular feminines", "beau, bon, vieux, nouveau", "belle, bonne, vieille, nouvelle"],
           ["元音、哑音 h 前的阳性|Masculine before a vowel or mute h", "beau, nouveau, vieux", "un bel arbre, un nouvel ami, un vieil homme"],
           ["位置|Position", { zh: "多数在名词后", en: "most follow the noun" }, "la mer bleue, mais un petit navire"]] },
  notes: { zh: "复数 -s 来自拉丁语宾格复数:mūrōs → murs,rosās → roses。拉丁语的格逐渐消失,古法语只剩主格和源自宾格的「斜格」两格,最后连主格也丢了,只留斜格。西部罗曼语的复数普遍出自宾格,所以法语、西班牙语、葡萄牙语的复数都带 -s;意大利语的 -i 则来自主格复数(mūrī → muri)。-aux 来自 l 的元音化:辅音前的 l 变成 u,chevals 读成 chevaus;中世纪抄写员常把 -us 缩写成 x,后来 u 又被补写回来,于是成了 chevaux。",
          en: "The plural -s is the Latin accusative plural: mūrōs became murs, rosās roses. As cases wore away, Old French kept a subject case and an oblique one from the accusative, then only the oblique. Western Romance plurals rest on the accusative, hence -s in Spanish and Portuguese too; Italian muri continues the nominative mūrī. -aux is a vocalised l: before a consonant chevals became chevaus; scribes wrote -us as x, the u was later restored: chevaux." },
  ex: [
    { q: { zh: "le cheval 的复数是:", en: "The plural of le cheval is:" }, opts: ["les chevaux", "les chevals", "les chevauxs", "les chevales"], a: 0,
      why: { zh: "-al 结尾的名词复数大多变 -aux:cheval → chevaux,journal → journaux。chevals 是硬套一般规则加 -s 的错误。", en: "Most nouns in -al make their plural in -aux: cheval, chevaux; journal, journaux. Chevals applies the ordinary -s where it does not belong." } },
    { q: { zh: "le taureau(公牛)的复数是:", en: "The plural of le taureau, the bull, is:" }, opts: ["les taureaux", "les taureaus", "les tauraux", "les taureau"], a: 0,
      why: { zh: "-eau 结尾的名词复数加 -x:taureau → taureaux,bateau → bateaux。tauraux 把 -al 的规则错用到了 -eau 上。", en: "Nouns in -eau add -x: taureau, taureaux; bateau, bateaux. Tauraux wrongly applies the -al rule to an -eau noun." } },
    { q: { zh: "众神的声音:les ___ des dieux", en: "The voices of the gods: les ___ des dieux" }, opts: ["voix", "voixs", "voixes", "vois"], a: 0,
      why: { zh: "以 -s、-x、-z 结尾的名词复数不变:la voix → les voix,le fils → les fils。voixs、voixes 是硬加词尾的错误,vois 则把 x 错换成了 s。", en: "Nouns already ending in -s, -x or -z do not change: la voix, les voix; le fils, les fils. Voixs and voixes force on an ending, and vois wrongly swaps the x for an s." } },
    { q: { zh: "Pénélope est enfin ___.(佩涅洛佩终于快乐了)", en: "Pénélope est enfin ___. (Penelope is happy at last.)" }, opts: ["heureuse", "heureux", "heureuxe", "heureuses"], a: 0,
      why: { zh: "形容词要和主语同性同数。Pénélope 是阴性单数,-eux 的阴性是 -euse:heureuse。heureux 是阳性,heureuses 是复数。", en: "The adjective agrees with the subject. Pénélope is feminine singular, and the feminine of -eux is -euse: heureuse. Heureux is masculine, heureuses plural." } },
    { q: { zh: "忒修斯回航时忘了换下的「一面黑帆」(voile 帆,阴性):", en: "The black sail Theseus forgot to change on the voyage home (voile, sail, is feminine):" }, opts: ["une voile noire", "une voile noir", "une voile noires", "une noir voile"], a: 0,
      why: { zh: "颜色形容词放在名词后,并与阴性单数的 voile 一致:une voile noire。noir 少了阴性的 -e,noires 多了复数的 -s。埃勾斯望见黑帆,以为儿子已死,投海自尽。", en: "Colour adjectives follow the noun and agree with feminine singular voile: une voile noire. Noir lacks the feminine -e; noires adds a plural -s. Seeing the black sail, Aegeus thought his son was dead and threw himself into the sea." } },
    { q: { zh: "奥德修斯回到伊塔卡,雅典娜把他变成一个老乞丐:un ___ homme", en: "Back on Ithaca, Athena disguises Odysseus as an old beggar: un ___ homme" }, opts: ["vieil", "vieux", "vieille", "vieils"], a: 0,
      why: { zh: "vieux 放在名词前,遇到元音或哑音 h 开头的阳性单数名词要改成 vieil:un vieil homme。同理有 un bel arbre、un nouvel ami。vieille 是阴性。", en: "Vieux precedes the noun, and before a masculine singular beginning with a vowel or mute h it becomes vieil: un vieil homme. So too un bel arbre, un nouvel ami. Vieille is feminine." } },
    { q: { zh: "下面哪一组不一致?", en: "Which phrase does NOT agree?" }, opts: ["les déesses heureux", "les déesses heureuses", "les dieux heureux", "une déesse heureuse"], a: 0,
      why: { zh: "déesses 是阴性复数,形容词要用阴性复数 heureuses。les dieux heureux 没有错:heureux 已以 -x 结尾,阳性复数不再加 -s。", en: "Déesses is feminine plural, so the adjective must be heureuses. Les dieux heureux is right: heureux already ends in -x and takes no extra -s." } },
    { q: { zh: "法语复数的 -s 来自拉丁语的:", en: "The French plural -s comes from Latin's:" },
      opts: [{ zh: "宾格复数 -ōs、-ās", en: "accusative plural -ōs, -ās" }, { zh: "主格复数 -ī、-ae", en: "nominative plural -ī, -ae" }, { zh: "属格单数 -is", en: "genitive singular -is" }, { zh: "希腊语的复数", en: "Greek plural" }], a: 0,
      why: { zh: "古法语最终只保留了源自宾格的斜格:mūrōs → murs,rosās → roses。保留主格复数的是意大利语:mūrī → muri。", en: "Old French in the end kept only the oblique case, descended from the accusative: mūrōs, murs; rosās, roses. It is Italian that kept the nominative plural: mūrī, muri." } },
  ] },

{ id: "fr_partitif", icon: "🍷",
  name: { zh: "缩合与部分冠词 · 独眼巨人的酒", en: "Contractions and partitives · The Cyclops's wine" },
  scene: { zh: "奥德修斯被困在独眼巨人波吕斐摩斯的洞穴里。洞里有奶酪(du fromage),有奶(du lait)。他把带来的烈酒献给巨人:Ulysse donne du vin au Cyclope。du 是 de + le,表示「一些」;au 是 à + le。巨人喝醉睡去,奥德修斯趁机刺瞎了他的独眼。",
           en: "Odysseus is trapped in the cave of the Cyclops Polyphemus. There is cheese, du fromage, and milk, du lait. He offers the giant the strong wine he brought: Ulysse donne du vin au Cyclope. Du is de + le, ‘some’; au is à + le. The giant drinks, falls asleep, and Odysseus blinds his single eye." },
  rule: { zh: "à、de 遇 le、les 缩合:à + le = au,à + les = aux,de + le = du,de + les = des;à la、à l'、de la、de l' 不缩合。部分冠词 du、de la、de l' 表示不定量「一些」:du vin、de l'eau。否定用 ne … pas 夹住动词(元音前 n')。否定句中宾语前的 un、une、du、de la、des 变成 de(元音前 d'):il n'a pas de vin;être 后不变:ce n'est pas un dieu。",
          en: "À and de fuse with le and les: à + le = au, à + les = aux, de + le = du, de + les = des. À la, à l', de la, de l' never contract: au port, but à la mer, à l'île. The partitive du, de la, de l' means an unspecified amount: du vin, de l'eau. Negation wraps the verb in ne … pas (n' before a vowel), and on the object of a negated verb un, une, du, de la, des become de or d': il n'a pas de vin. After être they stay: ce n'est pas un dieu." },
  table: { cap: { zh: "缩合、部分冠词与否定", en: "Contraction, partitive and negation" },
    head: [{ zh: "组合", en: "Combination" }, { zh: "结果", en: "Result" }, { zh: "例子", en: "Example" }],
    rows: [["à + le", "au", "au port"],
           ["à + les", "aux", "aux Enfers"],
           ["de + le", "du", "le labyrinthe du Minotaure"],
           ["de + les", "des", "la colère des dieux"],
           ["à la, à l', de la, de l'", { zh: "不缩合", en: "no contraction" }, "à la mer, de l'île"],
           ["部分冠词|Partitive", "du, de la, de l'", "du vin, de la viande, de l'eau"],
           ["否定之后|After a negation", "de, d'", "pas de vin, pas d'eau"],
           ["être 之后|After être", { zh: "冠词不变", en: "article unchanged" }, "ce n'est pas un dieu"]] },
  notes: { zh: "du、au 是缩合形:de + le → del → du,a + le → al → au,都是 l 的元音化。部分冠词出现得很晚:拉丁语说 pānem edō「我吃面包」,不用冠词;古法语也常说 mangier pain,后来才用 de「从……中」表示取整体的一部分,du pain 就是「面包中的一些」。否定后的 de 也是这个 de。ne 来自拉丁语 nōn;pas 本是名词「一步」(passus),ne … pas 原指「一步也不」,与 point「一点」、mie「面包屑」同为强化词,后来 pas 胜出。",
          en: "Du and au are fusions: de + le gave del, then du; a + le gave al, then au, with the same vocalised l. The partitive came late. Latin said pānem edō, I eat bread, with no article, and Old French often said mangier pain; later de, ‘out of’, came to mark part of a whole. The de after a negation is the same de. Ne is Latin nōn; pas was a noun, passus, a step: ne … pas meant ‘not a step’, a reinforcer like point, a dot, and mie, a crumb; pas won out." },
  ex: [
    { q: { zh: "Orphée descend ___ Enfers.(俄耳甫斯下到冥府)", en: "Orphée descend ___ Enfers. (Orpheus goes down to the Underworld.)" }, opts: ["aux", "à les", "au", "à l'"], a: 0,
      why: { zh: "à + les 必须缩合成 aux。les Enfers 是复数,所以不能用单数的 au。", en: "À + les must contract to aux. Les Enfers is plural, so the singular au is wrong." } },
    { q: { zh: "米诺陶洛斯的迷宫:le labyrinthe ___ Minotaure", en: "The labyrinth of the Minotaur: le labyrinthe ___ Minotaure" }, opts: ["du", "de le", "de la", "des"], a: 0,
      why: { zh: "de + le 必须缩合成 du,de le 永远不能这样写。Minotaure 是阳性单数,不用 de la,也不用复数 des。", en: "De + le always contracts to du; de le is never written. Minotaure is masculine singular, so neither de la nor the plural des fits." } },
    { q: { zh: "Le Cyclope boit ___ lait.(独眼巨人喝一些奶)", en: "Le Cyclope boit ___ lait. (The Cyclops drinks some milk.)" }, opts: ["du", "de la", "de le", "au"], a: 0,
      why: { zh: "不确定的量用部分冠词。lait 是阳性,所以是 du lait;de la 只配阴性名词,de le 必须缩合。", en: "An unspecified amount takes the partitive. Lait is masculine, so du lait; de la is for feminine nouns, and de le must contract." } },
    { q: { zh: "许拉斯去泉边打水,被水泽仙女拖进了泉里:Hylas va chercher ___ eau.", en: "Hylas goes to a spring for water, and the nymphs pull him in: Hylas va chercher ___ eau." }, opts: ["de l'", "du", "de la", "des"], a: 0,
      why: { zh: "eau 以元音开头,部分冠词用 de l':de l'eau。de la 遇元音要省音,du 只用于辅音开头的阳性名词。", en: "Eau begins with a vowel, so the partitive is de l': de l'eau. De la elides before a vowel, and du is only for masculine nouns beginning with a consonant." } },
    { q: { zh: "把 Il y a du vin. 变成否定句:", en: "Make Il y a du vin. negative:" }, opts: ["Il n'y a pas de vin.", "Il n'y a pas du vin.", "Il n'y a pas vin.", "Il ne y a pas de vin."], a: 0,
      why: { zh: "否定之后,部分冠词 du 变成 de:il n'y a pas de vin。de 不能省掉;ne 在元音前要省成 n',不写 ne y。", en: "After a negation the partitive du becomes de: il n'y a pas de vin. The de cannot be dropped, and ne elides to n' before a vowel, so ne y is wrong." } },
    { q: { zh: "Polyphème n'est pas ___ dieu, c'est le fils de Poséidon.(波吕斐摩斯不是神,而是波塞冬的儿子)", en: "Polyphème n'est pas ___ dieu, c'est le fils de Poséidon. (Polyphemus is no god; he is the son of Poseidon.)" }, opts: ["un", "de", "d'", "du"], a: 0,
      why: { zh: "être 后面是表语,不是宾语,所以冠词在否定句里不变:ce n'est pas un dieu。改成 de 是把规则用过了头——只有否定动词的直接宾语前,冠词才变成 de(il n'a pas de vin)。", en: "What follows être is a complement, not an object, so the article stays in the negative: ce n'est pas un dieu. Changing un to de over-applies the rule, which concerns only the direct object of a negated verb (il n'a pas de vin)." } },
    { q: { zh: "下面哪个写法是错的?", en: "Which of these is wrong?" }, opts: ["à le port", "au port", "à la mer", "à l'île"], a: 0,
      why: { zh: "à + le 必须缩合成 au:au port。à la、à l' 不缩合,所以 à la mer、à l'île 都对。", en: "À + le must contract: au port. À la and à l' never contract, so à la mer and à l'île are both right." } },
    { q: { zh: "ne … pas 里的 pas 原本是什么?", en: "What was the pas of ne … pas originally?" },
      opts: [{ zh: "名词「一步」,来自拉丁语 passus", en: "a noun, ‘a step’, from Latin passus" }, { zh: "拉丁语否定词 nōn", en: "the Latin negator nōn" }, { zh: "拉丁语介词 per「穿过」", en: "the Latin preposition per, ‘through’" }, { zh: "希腊语否定词 ou", en: "the Greek negator ou" }], a: 0,
      why: { zh: "来自 nōn 的是 ne。pas 原是强化词「一步也不」,和 point「一点」、mie「面包屑」一样;后来 pas 用得最广,成了否定的固定部分。", en: "It is ne that comes from nōn. Pas began as a reinforcer, ‘not a step’, like point, a dot, and mie, a crumb; pas spread furthest and became a fixed part of the negation." } },
  ] },

{ id: "fr_present", icon: "🔥",
  name: { zh: "现在时 · 普罗米修斯的火", en: "The present tense · Prometheus's fire" },
  scene: { zh: "普罗米修斯为人类盗来众神的火:Prométhée vole le feu, il donne le feu aux hommes。宙斯大怒,把他锁在高加索山的岩石上,每天派鹰啄食他的肝。voler、donner 是规则的 -er 动词;je suis(我是)、j'ai(我有)则最常用,也最不规则。",
           en: "Prometheus steals fire from the gods and gives it to mankind: Prométhée vole le feu, il donne le feu aux hommes. Zeus, enraged, chains him to a rock in the Caucasus, where an eagle comes every day to eat his liver. Voler and donner are regular -er verbs; je suis, I am, and j'ai, I have, are the commonest and least regular verbs in French." },
  rule: { zh: "主语代词见表;je 在元音或哑音 h 前省作 j'。tu 对亲友和孩子,vous 是「你们」,也是尊称「您」。être:suis, es, est, sommes, êtes, sont;avoir:ai, as, a, avons, avez, ont。第一组 -er 动词去掉 -er,加 -e, -es, -e, -ons, -ez, -ent,其中 parle、parles、parlent 读音相同。-ger 动词在 -ons 前留 e(mangeons),-cer 动词写 ç(commençons)。",
          en: "Subject pronouns: je, tu, il / elle / on, nous, vous, ils / elles; je elides to j' before a vowel or mute h. Tu is for family, friends and children; vous is both ‘you all’ and the polite ‘you’. Être: suis, es, est, sommes, êtes, sont. Avoir: ai, as, a, avons, avez, ont. -er verbs drop -er and add -e, -es, -e, -ons, -ez, -ent; parle, parles and parlent sound alike. -ger verbs keep e before -ons (mangeons), -cer verbs write ç (commençons)." },
  table: { cap: { zh: "être、avoir 与两个 -er 动词", en: "être, avoir and two -er verbs" },
    head: [{ zh: "主语", en: "Subject" }, { zh: "être 是", en: "être, to be" }, { zh: "avoir 有", en: "avoir, to have" }, { zh: "parler 说", en: "parler, to speak" }, { zh: "manger 吃", en: "manger, to eat" }],
    rows: [["je / j'", "suis", "ai", "parle", "mange"],
           ["tu", "es", "as", "parles", "manges"],
           ["il / elle / on", "est", "a", "parle", "mange"],
           ["nous", "sommes", "avons", "parlons", "mangeons"],
           ["vous", "êtes", "avez", "parlez", "mangez"],
           ["ils / elles", "sont", "ont", "parlent", "mangent"]] },
  notes: { zh: "être 来自通俗拉丁语 *essere(古典拉丁语 esse),nous sommes、vous êtes、ils sont 正是 sumus、estis、sunt 的后代;avoir 来自 habēre,h 早已不发音。-er 动词继承拉丁语第一变位 -āre:cantāre → chanter,amāre → aimer,今天新造的动词也几乎都进这一组。代词 je 来自 ego,tu 来自 tū,vous 来自 vōs。用复数 vous 尊称一个人,常见的说法是源于罗马帝国晚期用复数称呼皇帝的习惯(存疑)。",
          en: "Être comes from Vulgar Latin *essere, classical esse; nous sommes, vous êtes, ils sont continue sumus, estis, sunt. Avoir is habēre, its h long silent. The -er verbs continue the Latin first conjugation in -āre: cantāre became chanter, amāre aimer, and nearly all new verbs join them. Je comes from ego, tu from tū, vous from vōs. Polite vous is often traced, though this is disputed, to the late Roman habit of addressing the emperor in the plural." },
  ex: [
    { q: { zh: "Prométhée ___ le feu aux hommes.(donner)", en: "Prométhée ___ le feu aux hommes. (donner)" }, opts: ["donne", "donnes", "donnent", "donnez"], a: 0,
      why: { zh: "主语 Prométhée 是第三人称单数,-er 动词词尾为 -e:il donne。donnes 是 tu 的形式,donnent 要配复数主语。", en: "Prométhée is third person singular, so the -er ending is -e: il donne. Donnes belongs to tu, and donnent needs a plural subject." } },
    { q: { zh: "Nous ___ des héros.(être)", en: "Nous ___ des héros. (être)" }, opts: ["sommes", "êtes", "sont", "suis"], a: 0,
      why: { zh: "être 的 nous 形式是 sommes。êtes 属于 vous,sont 属于 ils/elles,suis 属于 je。", en: "The nous form of être is sommes. Êtes goes with vous, sont with ils or elles, suis with je." } },
    { q: { zh: "Les Argonautes ___ un navire, l'Argo.(avoir)", en: "Les Argonautes ___ un navire, l'Argo. (avoir)" }, opts: ["ont", "sont", "a", "avez"], a: 0,
      why: { zh: "avoir 的第三人称复数是 ont。sont 是 être 的复数;ils ont 读 [ilzɔ̃],ils sont 读 [ilsɔ̃],只差 z 和 s 一个音,初学者很容易混。", en: "The third person plural of avoir is ont. Sont is the plural of être; ils ont [ilzɔ̃] and ils sont [ilsɔ̃] differ only by z against s, so learners easily mix them up." } },
    { q: { zh: "Nous ___ du pain.(manger)", en: "Nous ___ du pain. (manger)" }, opts: ["mangeons", "mangons", "mangeont", "mangent"], a: 0,
      why: { zh: "-ger 动词在 -ons 前保留 e,让 g 继续读软音:nous mangeons。mangons 里的 g 会读成硬音。", en: "-ger verbs keep an e before -ons so that the g stays soft: nous mangeons. In mangons the g would turn hard." } },
    { q: { zh: "在今天的法语里,礼貌地对一位陌生的长者说「您是……」:", en: "In modern French, politely telling an elderly stranger ‘you are …’:" }, opts: ["vous êtes", "tu es", "vous es", "tu êtes"], a: 0,
      why: { zh: "vous 既是「你们」,也用来尊称一个人,动词仍用复数形 êtes。tu 只对亲友和孩子;vous es、tu êtes 主谓不一致。", en: "Vous is ‘you all’ and also the polite ‘you’ for one person, still with the plural verb êtes. Tu is for family, friends and children; vous es and tu êtes do not agree." } },
    { q: { zh: "「我有一面盾牌」:___ un bouclier.", en: "‘I have a shield’: ___ un bouclier." }, opts: ["J'ai", "Je ai", "J'a", "Je as"], a: 0,
      why: { zh: "je 在元音前必须省音:j'ai、j'aime。avoir 的第一人称是 ai,a 是第三人称,as 是第二人称。", en: "Je must elide before a vowel: j'ai, j'aime. The first person of avoir is ai; a is third person and as second." } },
    { q: { zh: "下面四个 parler 的变位形式(不算主语),哪个读音与另外三个不同?", en: "Which of these forms of parler (verb only, no pronoun) sounds different from the other three?" }, opts: ["parlons", "parle", "parles", "parlent"], a: 0,
      why: { zh: "词尾 -e、-es、-ent 都不发音,parle、parles、parlent 读音完全相同,je parle、tu parles、il parle、ils parlent 四个人称都是这个音。只有 -ons 和 -ez 听得出来:parlons。", en: "The endings -e, -es and -ent are silent, so parle, parles and parlent sound exactly alike: je parle, tu parles, il parle and ils parlent share one sound. Only -ons and -ez can be heard: parlons." } },
    { q: { zh: "nous sommes、vous êtes、ils sont 是哪个拉丁语动词的后代?", en: "Nous sommes, vous êtes, ils sont descend from which Latin verb?" },
      opts: [{ zh: "esse「是」", en: "esse, to be" }, { zh: "habēre「有」", en: "habēre, to have" }, { zh: "stāre「站立」", en: "stāre, to stand" }, { zh: "īre「去」", en: "īre, to go" }], a: 0,
      why: { zh: "sumus → sommes,estis → êtes(脱落的 s 留下了扬抑符 ^),sunt → sont。habēre 变成的是 avoir。", en: "Sumus became sommes, estis êtes (the lost s left the circumflex), sunt sont. Habēre became avoir." } },
  ] },

{ id: "fr_groupes", icon: "🗡️",
  name: { zh: "第二、三组与不规则动词 · 巨石下的剑", en: "Second and third groups · The sword under the rock" },
  scene: { zh: "埃勾斯把剑和鞋藏在特洛曾的一块巨石下。忒修斯长大了(il grandit),掀开巨石,拿起剑(il prend l'épée),动身前往雅典(il part)。grandir 属于带 -iss- 的第二组:nous grandissons;prendre、partir 属于第三组,变化要一个一个记。",
           en: "Aegeus hid his sword and sandals under a great rock at Troezen. Theseus grows up (il grandit), heaves the rock aside, takes the sword (il prend l'épée) and sets out for Athens (il part). Grandir belongs to the second group with -iss-: nous grandissons. Prendre and partir belong to the third group, whose forms must be learned one by one." },
  rule: { zh: "第二组以 -ir 结尾,复数插入 -iss-:nous finissons、ils finissent,choisir、réussir、grandir 同此。第三组包括其余动词,多不规则:aller 有 ils vont,faire 有 vous faites,venir、prendre 有 ils viennent、ils prennent,pouvoir、vouloir 的 je、tu 以 -x 结尾。partir、sortir 以 -ir 结尾却没有 -iss-:je pars、nous partons。",
          en: "Second-group verbs end in -ir and insert -iss- in the plural: je finis, nous finissons, ils finissent; so too choisir, réussir, grandir. The third group holds all the rest, and its common verbs are mostly irregular (see the table): aller (je vais, ils vont), faire (vous faites), venir (ils viennent), prendre (ils prennent), pouvoir (je peux), vouloir (je veux). Partir and sortir end in -ir but have no -iss-: je pars, je sors, nous partons." },
  table: { cap: { zh: "第二组 finir 与常用第三组动词(tu 的形式与 je 相同,aller 除外:tu vas)", en: "Second-group finir and common third-group verbs (tu = je form, except aller: tu vas)" },
    head: [{ zh: "动词", en: "Verb" }, "je", "il / elle", "nous", "vous", "ils / elles"],
    rows: [["finir 完成|finir, to finish", "finis", "finit", "finissons", "finissez", "finissent"],
           ["aller 去|aller, to go", "vais", "va", "allons", "allez", "vont"],
           ["faire 做|faire, to do", "fais", "fait", "faisons", "faites", "font"],
           ["venir 来|venir, to come", "viens", "vient", "venons", "venez", "viennent"],
           ["prendre 拿|prendre, to take", "prends", "prend", "prenons", "prenez", "prennent"],
           ["pouvoir 能|pouvoir, can", "peux", "peut", "pouvons", "pouvez", "peuvent"],
           ["vouloir 想要|vouloir, to want", "veux", "veut", "voulons", "voulez", "veulent"],
           ["partir 出发|partir, to leave", "pars", "part", "partons", "partez", "partent"]] },
  notes: { zh: "-iss- 来自拉丁语表示「开始、渐成」的后缀 -isc-/-esc-:flōrēscere「开始开花」。通俗拉丁语把它当作填充成分推广到许多 -īre 动词(*fīnīscō),所以意大利语说 finisco,法语说 finissons。aller 由三个拉丁语动词拼成:vais、vas、va、vont 来自 vādere「走」;allons、allez 来自 *allare,或许出自 ambulāre「散步」(存疑);将来时 irai 则来自 īre「去」。prendre 来自 prehendere「抓住」。",
          en: "The -iss- is the Latin inchoative suffix -isc-/-esc-, ‘begin to, become’: flōrēscere, to begin to bloom. Vulgar Latin spread it to many -īre verbs as a filler (*fīnīscō), so Italian says finisco and French finissons. Aller is stitched from three verbs: vais, vas, va, vont from vādere, to go; allons, allez from *allare, perhaps ambulāre, to walk (disputed); the future irai from īre. Prendre is prehendere, to grasp." },
  ex: [
    { q: { zh: "Nous ___ le combat.(finir)", en: "Nous ___ le combat. (finir)" }, opts: ["finissons", "finons", "finisons", "finissez"], a: 0,
      why: { zh: "第二组动词复数插入 -iss-:nous finissons。finons 漏掉了 -iss-,finissez 是 vous 的形式。", en: "Second-group verbs insert -iss- in the plural: nous finissons. Finons leaves it out; finissez is the vous form." } },
    { q: { zh: "Thésée ___ l'épée de son père.(prendre)", en: "Thésée ___ l'épée de son père. (prendre)" }, opts: ["prend", "prends", "prent", "prennent"], a: 0,
      why: { zh: "prendre 的第三人称单数是 prend,以词干的 d 结尾,不再加 -t。prends 是 je、tu 的形式,prennent 是复数。", en: "The third person singular of prendre is prend, ending in the stem's d with no -t. Prends is the je and tu form, prennent the plural." } },
    { q: { zh: "Les Argonautes ___ en Colchide.(aller)", en: "Les Argonautes ___ en Colchide. (aller)" }, opts: ["vont", "allent", "vas", "allons"], a: 0,
      why: { zh: "aller 的 ils 形式是 vont。allent 是把它当成规则 -er 动词的错误:aller 是 -er 动词里唯一归入第三组的。", en: "The ils form of aller is vont. Allent treats it as a regular -er verb; aller is the one -er verb that belongs to the third group." } },
    { q: { zh: "Ulysse, vous ___ un long voyage.(faire)", en: "Ulysse, vous ___ un long voyage. (faire)" }, opts: ["faites", "faisez", "fais", "font"], a: 0,
      why: { zh: "faire 的 vous 形式是不规则的 faites,和 vous êtes、vous dites 一样以 -tes 结尾。faisez 是从 nous faisons 类推出来的错误。", en: "The vous form of faire is the irregular faites, ending in -tes like vous êtes and vous dites. Faisez is a false analogy from nous faisons." } },
    { q: { zh: "在冥府边,亡魂们来到奥德修斯身边:Les ombres des morts ___ vers Ulysse.(venir)", en: "At the edge of the Underworld the shades come to Odysseus: Les ombres des morts ___ vers Ulysse. (venir)" }, opts: ["viennent", "venent", "viennes", "venons"], a: 0,
      why: { zh: "venir 在 je、tu、il、ils 里词干变成 vien-,ils 的形式还要双写 n:viennent。只有 nous venons、vous venez 保留原词干 ven-。", en: "Venir switches to the stem vien- in je, tu, il and ils, and the ils form doubles the n: viennent. Only nous venons and vous venez keep the plain stem ven-." } },
    { q: { zh: "下面哪个动词不属于带 -iss- 的第二组?", en: "Which verb is NOT a second-group -iss- verb?" }, opts: ["partir", "finir", "choisir", "réussir"], a: 0,
      why: { zh: "partir 虽然以 -ir 结尾,却属于第三组:nous partons,不是 partissons。判断标准是复数有没有 -iss-。", en: "Partir ends in -ir but belongs to the third group: nous partons, not partissons. The test is whether the plural has -iss-." } },
    { q: { zh: "下面哪个形式是错的?", en: "Which form is wrong?" }, opts: ["ils pouvent", "je peux", "tu veux", "il peut"], a: 0,
      why: { zh: "pouvoir 的 ils 形式是 peuvent,元音和单数一样是 eu。je peux、tu veux 以 -x 结尾,这是 pouvoir、vouloir 的特点。", en: "The ils form of pouvoir is peuvent, with the same eu as the singular. Je peux and tu veux end in -x, a quirk of pouvoir and vouloir." } },
    { q: { zh: "finissons 里的 -iss- 来自拉丁语的:", en: "The -iss- of finissons comes from Latin's:" },
      opts: [{ zh: "表示「开始、渐成」的后缀 -isc-、-esc-", en: "inchoative suffix -isc-, -esc-, ‘begin to’" }, { zh: "虚拟式过去完成时的 -iss-", en: "pluperfect subjunctive -iss-" }, { zh: "第三变格法属格 -is", en: "third-declension genitive -is" }, { zh: "希腊语动词后缀 -izein", en: "Greek verb suffix -izein" }], a: 0,
      why: { zh: "拉丁语 flōrēscere「开始开花」里的 -ēsc- 表示「渐渐变成」。通俗拉丁语把 -isc- 推广到许多 -īre 动词(*fīnīscō),意大利语 finisco、法语 finissons 都由此而来。fīnīvissem 里的 -iss- 是另一回事。", en: "In flōrēscere, ‘to begin to bloom’, -ēsc- means becoming. Vulgar Latin spread -isc- to many -īre verbs (*fīnīscō), giving Italian finisco and French finissons. The -iss- of fīnīvissem is unrelated." } },
  ] },
]);

/* Fuga Mythica — French grammar road, stations 6–10 */
GRAM_ADD("fr", [
{ id: "fr_pc", icon: "⚔️",
  name: { zh: "复合过去时 · 忒修斯走出迷宫", en: "Passé composé · Theseus leaves the labyrinth" },
  scene: { zh: "忒修斯讲冒险:Je suis entré dans le labyrinthe. J'ai tué le Minotaure. Je suis sorti. 做完的事用「助动词 + 过去分词」:多数动词借 avoir(j'ai tué),少数移动、变化动词借 être(je suis entré)。",
           en: "Theseus tells his tale: Je suis entré dans le labyrinthe. J'ai tué le Minotaure. Je suis sorti. For finished events French uses an auxiliary plus a past participle: most verbs borrow avoir (j'ai tué), a small band of verbs of motion and change of state borrow être (je suis entré)." },
  rule: { zh: "复合过去时 = avoir/être 现在时 + 过去分词:-er → -é,-ir 多为 -i,-re/-oir 多为 -u,不规则见表(如 venu)。用 être:aller/venir、arriver/partir、entrer/sortir、monter/descendre、naître/mourir、rester、tomber、retourner、devenir、revenir(不带宾语时)及代词式动词,分词一般与主语性数一致:elle est partie。否定夹住助动词:n'a pas vu。",
          en: "Passé composé = avoir or être in the present + past participle: -er → -é, -ir mostly -i, -re/-oir mostly -u; irregulars in the table (venir → venu). Être goes with aller/venir, arriver/partir, entrer/sortir, monter/descendre, naître/mourir, rester, tomber, retourner, devenir, revenir (with no object) and pronominal verbs; its participle usually agrees with the subject: elle est partie, ils sont venus. Negation wraps the auxiliary: il n'a pas vu." },
  table: { cap: { zh: "过去分词与助动词", en: "Participle and auxiliary" },
    head: [{ zh: "不定式", en: "Infinitive" }, { zh: "过去分词", en: "Participle" }, { zh: "助动词", en: "Auxiliary" }, { zh: "例句", en: "Example" }],
    rows: [["parler", "parlé", "avoir", "Ariane a parlé à Thésée."],
           ["finir", "fini", "avoir", "Héraclès a fini ses travaux."],
           ["voir, vouloir, vendre", "vu, voulu, vendu", "avoir", "Le Cyclope n'a pas vu Ulysse."],
           ["prendre, mettre", "pris, mis", "avoir", "Jason a pris la Toison d'or."],
           ["faire, dire, écrire", "fait, dit, écrit", "avoir", "Dédale a fait le labyrinthe."],
           ["être, avoir", "été, eu", "avoir", "Thésée a été roi d'Athènes."],
           ["aller, venir", "allé, venu", "être", "Thésée est allé en Crète."],
           ["partir", "parti", "être", "Les Argonautes sont partis."],
           ["naître, mourir", "né, mort", "être", "Le Minotaure est mort."],
           ["se regarder", "regardé", "être", "Narcisse s'est regardé."]] },
  notes: { zh: "复合过去时是罗曼语自己造的。拉丁语 habeō litterās scrīptās 本义是「我有写好了的信」,分词像形容词一样与宾语一致;后来 habeō 虚化成助动词,整句变成「我写了信」。所以法语至今让分词与前置的宾语一致:la lettre que j'ai écrite。移动动词用 être,意大利语也是如此(sono venuto),西班牙语则统一用 haber。分词也来自拉丁语:-é < -ātum,fait < factum,écrit < scrīptum。",
          en: "Romance built the passé composé itself. Latin habeō litterās scrīptās meant I have the letters written, the participle agreeing like an adjective. As habeō faded into an auxiliary it came to mean I wrote them — so the participle still agrees with an object placed before it: la lettre que j'ai écrite. Italian shares être with motion verbs (sono venuto); Spanish, haber throughout. Participles are Latin: -é < -ātum, fait < factum, écrit < scrīptum." },
  ex: [
    { q: { zh: "「阿佛洛狄忒从海浪的泡沫中诞生。」Aphrodite est ___ de l'écume de la mer.", en: "Aphrodite was born from the foam of the sea: Aphrodite est ___ de l'écume de la mer." },
      opts: ["née", "né", "naissée", "nées"], a: 0,
      why: { zh: "naître 的过去分词是不规则的 né,配 être;主语阿佛洛狄忒是阴性单数,所以加 -e:née。naissée 是照 nous naissons 硬造的,nées 是阴性复数。", en: "Naître has the irregular participle né and takes être; Aphrodite is feminine singular, so it adds -e: née. Naissée is invented from nous naissons, and nées is feminine plural." } },
    { q: { zh: "「奥德修斯藏在一头公羊的肚子底下。」Ulysse s'___ caché sous un bélier.", en: "Odysseus hid beneath a ram: Ulysse s'___ caché sous un bélier." },
      opts: ["est", "a", "es", "ai"], a: 0,
      why: { zh: "se cacher 是代词式动词,所有代词式动词的复合过去时都用 être:il s'est caché。最诱人的 a 属于不带 se 的 cacher:il a caché le trésor。", en: "Se cacher is pronominal, and every pronominal verb forms the passé composé with être: il s'est caché. The tempting a belongs to plain cacher: il a caché le trésor." } },
    { q: { zh: "下面哪个过去分词是正确的?", en: "Which past participle is correct?" },
      opts: ["fait", "prendu", "mouru", "écrivé"], a: 0,
      why: { zh: "faire → fait,来自拉丁语 factum。另外三个都是按规则硬套出来的:prendre 是 pris,mourir 是 mort,écrire 是 écrit。", en: "Faire gives fait, from Latin factum. The other three are over-regularised: prendre gives pris, mourir gives mort, écrire gives écrit." } },
    { q: { zh: "伊卡洛斯飞上天空,又坠入大海。下面哪个动词的复合过去时要用 être?", en: "Icarus flew up, then fell into the sea. Which verb forms its passé composé with être?" },
      opts: ["tomber", "voler", "voir", "perdre"], a: 0,
      why: { zh: "tomber 表示位置的变化,属于用 être 的那一小批:Icare est tombé dans la mer。voler(飞)虽然也是运动,却用 avoir:il a volé——这份名单要背,不能光凭「是不是运动」来猜。", en: "Tomber, a change of position, is on the être list: Icare est tombé dans la mer. Voler, to fly, is movement too but takes avoir — il a volé — so the list must be learnt, not guessed from the idea of motion." } },
    { q: { zh: "哪一句是错的?", en: "Which sentence is wrong?" },
      opts: ["Ariane a allé à Naxos.", "Ariane est allée à Naxos.", "Ariane a vu Naxos.", "Zeus est né en Crète."], a: 0,
      why: { zh: "aller 只能用 être:Ariane est allée à Naxos(阴性加 -e)。a allé 是学习者最常见的错误。其余三句都对。", en: "Aller always takes être: Ariane est allée à Naxos, with -e for the feminine. A allé is the commonest learner slip; the other three sentences are correct." } },
    { q: { zh: "「珀耳修斯没有直视美杜莎。」哪一句对?", en: "Perseus did not look straight at Medusa. Which is right?" },
      opts: ["Persée n'a pas regardé Méduse.", "Persée n'a regardé pas Méduse.", "Persée ne pas a regardé Méduse.", "Persée a ne pas regardé Méduse."], a: 0,
      why: { zh: "ne … pas 夹住的是变位的助动词,分词跟在后面:n'a pas regardé。把 pas 放到分词后面,是照搬了简单时态里「动词 + pas」的语序。", en: "Ne … pas wraps the conjugated auxiliary, and the participle follows: n'a pas regardé. Putting pas after the participle copies the verb + pas order of a simple tense." } },
    { q: { zh: "「亚马逊女战士们来到了雅典。」Les Amazones sont ___ à Athènes.", en: "The Amazons came to Athens: Les Amazones sont ___ à Athènes." },
      opts: ["venues", "venus", "venue", "venu"], a: 0,
      why: { zh: "venir 用 être,分词要与主语一致:Amazones 是阴性复数,所以 venu + e + s = venues。venus 是阳性复数,只有主语是男性或男女混合时才对。", en: "Venir takes être, so the participle agrees: Amazones is feminine plural, giving venu + e + s = venues. Venus is masculine plural, for men or a mixed group." } },
    { q: { zh: "j'ai écrit 这种「avoir + 分词」的说法来自哪种拉丁语结构?", en: "Where does the avoir + participle pattern of j'ai écrit come from?" },
      opts: [{ zh: "habeō litterās scrīptās「我有写好的信」", en: "habeō litterās scrīptās, I have letters written" }, { zh: "完成时 scrīpsī litterās「我写了信」", en: "the perfect scrīpsī litterās, I wrote letters" }, { zh: "被动 litterae scrīptae sunt「信被写好了」", en: "the passive litterae scrīptae sunt, letters were written" }, { zh: "将来时 scrībam litterās「我将写信」", en: "the future scrībam litterās, I shall write letters" }], a: 0,
      why: { zh: "晚期拉丁语的 habeō + 分词本义是「我拥有处于写好状态的信」,habeō 慢慢虚化成助动词。拉丁语完成时并没有消失,它变成了书面语的简单过去时(vīdī → je vis)。", en: "Late Latin habeō plus participle meant I hold the letters in a written state, and habeō slowly faded into an auxiliary. The Latin perfect did not vanish: it became the literary passé simple (vīdī → je vis)." } },
  ] },

{ id: "fr_imparfait", icon: "🕯️",
  name: { zh: "未完成过去时 · 迷宫里的黑暗", en: "Imparfait · Darkness in the labyrinth" },
  scene: { zh: "迷宫深处:Il faisait noir. Le Minotaure attendait. Thésée avançait… Soudain, il a vu le monstre. 前三句是布景——环境、状态、进行中的动作,用未完成过去时;最后一句是推动情节的一次性事件,用复合过去时。",
           en: "Deep in the labyrinth: Il faisait noir. Le Minotaure attendait. Thésée avançait… Soudain, il a vu le monstre. The first three sentences paint the set — the darkness, a state, an action in progress — in the imparfait; the last is a single event that moves the story on, in the passé composé." },
  rule: { zh: "nous 现在时去掉 -ons 得词干,加 -ais, -ais, -ait, -ions, -iez, -aient:finissons → je finissais,buvons → je buvais。唯一不规则的词干是 être → ét-:j'étais。用法:描写(Polyphème était énorme)、过去的习惯(chaque jour…)、事件发生时进行中的背景。单个完成的事件用复合过去时:Quand Thésée est entré, le Minotaure attendait。",
          en: "Take the nous present, drop -ons, add -ais, -ais, -ait, -ions, -iez, -aient: finissons → je finissais, prenons → je prenais, buvons → je buvais. The one irregular stem is être → ét-: j'étais. Uses: description (Polyphème était énorme), habit (chaque jour…), and the background in progress when something happens. A single completed event takes the passé composé: Quand Thésée est entré, le Minotaure attendait." },
  table: { cap: { zh: "词干来自 nous 形", en: "The stem comes from the nous form" },
    head: [{ zh: "不定式", en: "Infinitive" }, { zh: "nous 现在时", en: "nous present" }, { zh: "词干", en: "Stem" }, { zh: "未完成过去时", en: "Imparfait" }],
    rows: [["parler", "nous parlons", "parl-", "je parlais"],
           ["finir", "nous finissons", "finiss-", "tu finissais"],
           ["prendre", "nous prenons", "pren-", "il prenait"],
           ["boire", "nous buvons", "buv-", "nous buvions"],
           ["faire", "nous faisons", "fais-", "vous faisiez"],
           ["avoir", "nous avons", "av-", "ils avaient"],
           ["aller", "nous allons", "all-", "elles allaient"],
           ["être", "nous sommes", { zh: "ét-(唯一例外)", en: "ét- (the one exception)" }, "j'étais"]] },
  notes: { zh: "imparfait 来自拉丁语 imperfectum「未完成的」。词尾也来自拉丁语:habēbam 一类的 -ēba- 在通俗拉丁语里丢了 b,古法语成了 -eie、-oie,并推广到所有动词(je chantoie)。读音后来变成 [ɛ],拼写直到 1835 年法兰西学院词典才改成 -ais,伏尔泰早有此议。意大利语 cantava 还留着 v。être 的 ét- 不来自 eram,而来自 stāre「站」的 stābam:古法语 estoie,s 脱落留下 é,如 estoile → étoile。",
          en: "Imparfait is Latin imperfectum, unfinished. Its endings too: habēbam-type forms lost their b in Vulgar Latin, giving Old French -eie, then -oie, spread to all verbs (je chantoie). The sound became [ɛ], but the spelling -ais came only with the Académie dictionary of 1835, as Voltaire urged. Italian cantava keeps the v. The stem ét- is not from eram but from stābam, of stāre, to stand: Old French estoie, whose s fell away, as in estoile → étoile." },
  ex: [
    { q: { zh: "「那时独眼巨人每天晚上都喝羊奶。」Chaque soir, le Cyclope ___ du lait.", en: "In those days the Cyclops drank milk every evening: Chaque soir, le Cyclope ___ du lait." },
      opts: ["buvait", "boivait", "boiait", "buvais"], a: 0,
      why: { zh: "boire 的 nous 形是 buvons,所以词干是 buv-:il buvait。boivait 错用了 ils boivent 的词干,boiait 直接拿了不定式,buvais 是 je、tu 的形式。", en: "The nous form of boire is buvons, so the stem is buv-: il buvait. Boivait wrongly takes the stem of ils boivent, boiait the infinitive, and buvais is the je/tu form." } },
    { q: { zh: "「美杜莎从前很美。」Autrefois, Méduse ___ belle.", en: "Medusa was once beautiful: Autrefois, Méduse ___ belle." },
      opts: ["était", "sommait", "étaient", "êtait"], a: 0,
      why: { zh: "être 是唯一词干不规则的动词:ét- + -ait = était。照 nous sommes 硬造的 sommait 不存在;étaient 是复数;êtait 的扬抑符是错的。", en: "Être is the one verb with an irregular stem: ét- + -ait = était. Sommait, built from nous sommes, does not exist; étaient is plural; and the circumflex of êtait is wrong." } },
    { q: { zh: "「俄耳甫斯回头的时候,欧律狄刻正走在他身后。」Quand Orphée s'est retourné, Eurydice ___ derrière lui.", en: "When Orpheus turned round, Eurydice was walking behind him: Quand Orphée s'est retourné, Eurydice ___ derrière lui." },
      opts: ["marchait", "a marché", "marchais", "marche"], a: 0,
      why: { zh: "「正走在身后」是事件发生时正在进行的背景,用未完成过去时 marchait;回头这个一次性动作才用复合过去时。a marché 会把背景变成另一件做完的事;marchais 是 je、tu 的形式。", en: "Walking behind him is the background in progress when the event happens, so marchait; the one-off turning round is the passé composé. A marché would make it another completed event, and marchais is the je/tu form." } },
    { q: { zh: "Le jour, Pénélope tissait la toile ; la nuit, elle la défaisait. 这里的未完成过去时表示什么?", en: "Le jour, Pénélope tissait la toile ; la nuit, elle la défaisait. What does the imparfait express here?" },
      opts: [{ zh: "过去反复发生的习惯", en: "a habit repeated in the past" }, { zh: "一次性完成的事件", en: "a single completed event" }, { zh: "说话此刻正在发生的事", en: "something happening as we speak" }, { zh: "将来的计划", en: "a plan for the future" }], a: 0,
      why: { zh: "佩涅洛佩白天织、夜里拆,日复一日,这是过去的习惯,正是未完成过去时的典型用法。一次性完成的事要说 elle a tissé。", en: "Weaving by day and unpicking by night, again and again, is a past habit — a core use of the imparfait. A single completed act would be elle a tissé." } },
    { q: { zh: "阿尔戈英雄们回忆:「每天早上,我们都拿起船桨。」Chaque matin, nous ___ les rames.", en: "The Argonauts remember: every morning we took up the oars. Chaque matin, nous ___ les rames." },
      opts: ["prenions", "prenaient", "prendions", "prennions"], a: 0,
      why: { zh: "词干来自 nous prenons → pren-,加 -ions:prenions。prenaient 是 ils 的形式;prendions 错用了不定式;prennions 错用了 ils prennent 的词干。", en: "The stem comes from nous prenons, pren-, plus -ions: prenions. Prenaient is the ils form; prendions wrongly uses the infinitive, and prennions the stem of ils prennent." } },
    { q: { zh: "下面哪个未完成过去时形式是错的?", en: "Which imparfait form is wrong?" },
      opts: ["ils finaient", "ils finissaient", "nous étions", "vous faisiez"], a: 0,
      why: { zh: "第二组动词的词干带 -iss-:nous finissons → ils finissaient。finaient 漏掉了 -iss-。nous étions 和 vous faisiez 都是对的。", en: "Second-group verbs keep -iss- in the stem: nous finissons gives ils finissaient. Finaient drops the -iss-. Nous étions and vous faisiez are both correct." } },
    { q: { zh: "「你们这些阿尔戈英雄,那时正在寻找金羊毛。」Vous ___ la Toison d'or.", en: "You Argonauts were searching for the Golden Fleece: Vous ___ la Toison d'or." },
      opts: ["cherchiez", "cherchaient", "cherchaiez", "cherchiiez"], a: 0,
      why: { zh: "vous 的词尾是 -iez:cherch- + -iez = cherchiez。cherchaient 是 ils 的形式;cherchaiez 把 -ais 和 -ez 混在了一起;cherchiiez 多了一个 i。", en: "The vous ending is -iez: cherch- + -iez = cherchiez. Cherchaient is the ils form; cherchaiez blends -ais with -ez; cherchiiez has one i too many." } },
    { q: { zh: "j'étais 的词干 ét- 来自哪里?", en: "Where does the stem ét- of j'étais come from?" },
      opts: [{ zh: "拉丁语 stāre「站」的 stābam", en: "stābam, from Latin stāre, to stand" }, { zh: "拉丁语 esse「是」的未完成时 eram", en: "eram, the imperfect of Latin esse, to be" }, { zh: "法兰克人带来的日耳曼语「是」", en: "a Germanic verb to be, brought by the Franks" }, { zh: "希腊语 estin「他是」", en: "Greek estin, he is, borrowed by scholars" }], a: 0,
      why: { zh: "古法语里 iere(< eram)和 estoie(< stābam)曾经并存,后来 estoie 胜出;s 脱落,留下 é,就像 estoile → étoile。分词 été 也来自 statum。", en: "Old French had both iere, from eram, and estoie, from stābam, and estoie won; its s fell away and left é, as in estoile → étoile. The participle été likewise comes from statum." } },
  ] },

{ id: "fr_futur", icon: "🔮",
  name: { zh: "将来时与条件式 · 卡珊德拉的预言", en: "Future and conditional · Cassandra's prophecy" },
  scene: { zh: "卡珊德拉在特洛伊预言:Les Grecs sortiront du cheval. Troie brûlera. 无人相信。她说:Si vous brûliez ce cheval, Troie vivrait(烧掉木马,特洛伊就能活)。将来时和条件式共用词干:不定式,后接 avoir 的残余。",
           en: "On the walls of Troy, Cassandra prophesies: Les Grecs sortiront du cheval. Troie brûlera. No one believes her. Si vous brûliez ce cheval, Troie vivrait — if you burned this horse, Troy would live. Future and conditional share one stem, the infinitive, followed by what remains of avoir." },
  rule: { zh: "将来时 = 不定式 + -ai, -as, -a, -ons, -ez, -ont(finirai;-re 去 e:prendrai)。不规则只在词干(见表),另有 verr-(voir)、saur-(savoir)、devr-(devoir)。最近将来时:aller + 不定式(je vais partir)。条件式 = 将来词干 + 未完成过去时词尾:je serais;je voudrais 表示礼貌。si + 现在时 → 将来时;si + 未完成过去时 → 条件式;条件句的 si 后绝不用将来时或条件式。",
          en: "Future = infinitive + -ai, -as, -a, -ons, -ez, -ont (finirai; -re verbs drop the e: prendrai). Irregulars change only the stem (see the table), plus verr- (voir), saur- (savoir), devr- (devoir). Near future: aller + infinitive (je vais partir). Conditional = future stem + imperfect endings: je serais; je voudrais is polite. Si + present → future; si + imperfect → conditional; a si of condition never takes the future or conditional itself." },
  table: { cap: { zh: "同一个词干,两套词尾", en: "One stem, two sets of endings" },
    head: [{ zh: "不定式", en: "Infinitive" }, { zh: "词干", en: "Stem" }, { zh: "将来时", en: "Future" }, { zh: "条件式", en: "Conditional" }],
    rows: [["parler", "parler-", "je parlerai", "je parlerais"],
           ["finir", "finir-", "tu finiras", "tu finirais"],
           ["prendre", "prendr-", "il prendra", "il prendrait"],
           ["être", "ser-", "nous serons", "nous serions"],
           ["avoir", "aur-", "vous aurez", "vous auriez"],
           ["aller", "ir-", "ils iront", "ils iraient"],
           ["faire", "fer-", "je ferai", "je ferais"],
           ["venir", "viendr-", "tu viendras", "tu viendrais"],
           ["pouvoir", "pourr-", "il pourra", "il pourrait"],
           ["vouloir", "voudr-", "nous voudrons", "nous voudrions"]] },
  notes: { zh: "拉丁语的将来时 cantābit 在 b、v 读音合并后与完成时 cantāvit 难以分辨(常见解释之一),口语于是改说 cantāre habeō「我有(要)唱」。两个词黏成 chanterai,词尾 -ai、-as、-a、-ont 明显是 avoir 的现在时(-ons、-ez 是 avons、avez 的缩短)。条件式也是这一招:cantāre habēbam → chanterais。拉丁语没有条件式,是罗曼语的新发明。葡萄牙语至今还能把代词插在中间:dir-te-ei「我将告诉你」,可见原本是两个词。",
          en: "A common account: once b and v merged, Latin's future cantābit sounded like the perfect cantāvit, so speakers said cantāre habeō, I have to sing. The words fused into chanterai, whose endings -ai, -as, -a, -ont are plainly the present of avoir (-ons, -ez clipped from avons, avez). The conditional, cantāre habēbam, became chanterais. Latin had no conditional; Romance invented it. Portuguese can still split the pieces — dir-te-ei, I will tell you." },
  ex: [
    { q: { zh: "卡珊德拉预言:「特洛伊将会陷落。」Troie ___.", en: "Cassandra prophesies that Troy will fall: Troie ___." },
      opts: ["tombera", "tomberai", "tombra", "tomberra"], a: 0,
      why: { zh: "将来时 = 不定式 + 词尾,第三人称单数是 -a:tomber + a = tombera。tomberai 是 je 的形式;tombra 丢了不定式里的 e;双 r 只属于 pourra、verra 这类不规则词干。", en: "Future = infinitive + ending, and the third singular is -a: tomber + a = tombera. Tomberai is the je form; tombra loses the e of the infinitive; the double r belongs only to irregular stems like pourra and verra." } },
    { q: { zh: "皮提亚对赫拉克勒斯说:「欧律斯透斯要你做什么,你就做什么。」Tu ___ tout ce que veut Eurysthée.", en: "The Pythia tells Heracles to serve Eurystheus: Tu ___ tout ce que veut Eurysthée — you will do whatever Eurystheus wants." },
      opts: ["feras", "fairas", "faisras", "faireras"], a: 0,
      why: { zh: "faire 的将来词干不规则,是 fer-:tu feras。fairas 是照 prendre → prendr- 硬套的;faisras 用了 nous faisons 的词干。词干会变,词尾 -ai, -as, -a… 永远不变。", en: "Faire has the irregular future stem fer-: tu feras. Fairas copies the pattern prendre → prendr-; faisras uses the stem of nous faisons. The stem may change, but the endings -ai, -as, -a… never do." } },
    { q: { zh: "「如果珀耳修斯直视美杜莎,他就会变成石头。」Si Persée ___ Méduse dans les yeux, il sera changé en pierre.", en: "If Perseus looks Medusa in the eye, he will be turned to stone: Si Persée ___ Méduse dans les yeux, il sera changé en pierre." },
      opts: ["regarde", "regardera", "regarderait", "regardait"], a: 0,
      why: { zh: "表示条件的 si 后面用现在时,结果用将来时:Si Persée regarde…, il sera…。regardera、regarderait 犯了「si 后接将来时或条件式」的大忌;regardait 要配条件式 serait,不能配 sera。", en: "A conditional si takes the present, and the result the future: Si Persée regarde…, il sera…. Regardera and regarderait break the rule against future or conditional after si; regardait would need serait, not sera." } },
    { q: { zh: "「要是特洛伊人相信卡珊德拉,他们就会烧掉那匹马。」Si les Troyens croyaient Cassandre, ils ___ le cheval.", en: "If the Trojans believed Cassandra, they would burn the horse: Si les Troyens croyaient Cassandre, ils ___ le cheval." },
      opts: ["brûleraient", "brûleront", "brûlent", "brûlerait"], a: 0,
      why: { zh: "si + 未完成过去时 → 条件式:brûler- + -aient = brûleraient。brûleront 是将来时,只配 si + 现在时;brûlent 是现在时;brûlerait 是单数,和 ils 不一致。", en: "Si + imperfect → conditional: brûler- + -aient = brûleraient. Brûleront is the future, which pairs with si + present; brûlent is the present; brûlerait is singular and clashes with ils." } },
    { q: { zh: "俄耳甫斯礼貌地对冥王说:「我想带回欧律狄刻。」Je ___ ramener Eurydice.", en: "Orpheus says politely to Hades, I would like to bring Eurydice back: Je ___ ramener Eurydice." },
      opts: ["voudrais", "vouloirais", "voudrerais", "vouderais"], a: 0,
      why: { zh: "条件式 = 将来词干 + 未完成过去时词尾:voudr- + -ais = voudrais,用来礼貌地表达愿望。vouloir 的将来词干是 voudr-,不是 vouloir-、voudrer- 或 vouder-。", en: "Conditional = future stem + imperfect ending: voudr- + -ais = voudrais, the polite way to state a wish. The future stem of vouloir is voudr-, not vouloir-, voudrer- or vouder-." } },
    { q: { zh: "「阿尔戈英雄们马上就要出发了。」Les Argonautes ___ partir.", en: "The Argonauts are about to set off: Les Argonautes ___ partir." },
      opts: ["vont", "allent", "va", "vais"], a: 0,
      why: { zh: "最近将来时 = aller 的现在时 + 不定式,ils 对应 vont。allent 是照 -er 动词的 -ent 硬造的,而 aller 的现在时恰恰不规则;va、vais 人称不对。", en: "The near future is aller in the present + infinitive, and ils takes vont. Allent is built on the regular -ent of -er verbs, but aller is irregular; va and vais are the wrong person." } },
    { q: { zh: "哪一句是错的?", en: "Which sentence is wrong?" },
      opts: ["Si Ulysse reviendra, Pénélope sera heureuse.", "Si Ulysse revient, Pénélope sera heureuse.", "Quand Ulysse reviendra, Pénélope sera heureuse.", "Si Ulysse revenait, Pénélope serait heureuse."], a: 0,
      why: { zh: "表示条件的 si 后面不能用将来时,要说 Si Ulysse revient…。而 quand(当…时)后面却要用将来时,这一点和英语不同。表示「是否」的 si 不受此限:Je ne sais pas si Ulysse reviendra。", en: "A conditional si never takes the future: Si Ulysse revient…. Quand, by contrast, does take the future, unlike English when. The si of whether is exempt: Je ne sais pas si Ulysse reviendra." } },
    { q: { zh: "条件式 je chanterais 来自哪个通俗拉丁语组合?", en: "Which Vulgar Latin phrase gave the conditional je chanterais?" },
      opts: [{ zh: "cantāre habēbam(不定式 + 「我曾有」)", en: "cantāre habēbam, infinitive + I had" }, { zh: "cantāvissem(拉丁语虚拟式过去完成时)", en: "cantāvissem, the Latin pluperfect subjunctive" }, { zh: "cantābō(拉丁语将来时)", en: "cantābō, the Latin future" }, { zh: "cantāre volō(不定式 + 「我想要」)", en: "cantāre volō, infinitive + I want" }], a: 0,
      why: { zh: "将来时用 habeō 的现在时,条件式用它的未完成过去时 habēbam,所以条件式的词尾和 avais 的词尾一样是 -ais。cantāre volō 是罗马尼亚语将来时走的路(voi cânta)。", en: "The future used the present of habeō and the conditional its imperfect habēbam, which is why the conditional ends in -ais like avais. Cantāre volō is the road the Romanian future took (voi cânta)." } },
  ] },

{ id: "fr_pronoms", icon: "🎯",
  name: { zh: "宾语代词 · 美杜莎的头", en: "Object pronouns · Medusa's head" },
  scene: { zh: "珀耳修斯砍下美杜莎的头,不敢直视它:il ne la regarde pas。他把它装进袋子带回塞里福斯岛,在国王波吕得克忒斯面前取了出来:il la montre au roi。一个小小的 la 替代了 la tête,而且跑到了动词前面——这就是法语的宾语代词。",
           en: "Perseus has cut off Medusa's head and dares not look at it: il ne la regarde pas. He carries it home to Seriphos in a bag and draws it out before King Polydectes: il la montre au roi. One small la stands in for la tête — and it has jumped in front of the verb. That is the French object pronoun." },
  rule: { zh: "直接宾语 le, la, l', les 代替不带介词的宾语;间接宾语 lui, leur 代替「à + 人」;me, te, nous, vous 两用。位置:变位动词前(je ne le vois pas);有不定式时放在不定式前(je vais le voir);复合过去时放在助动词前(je l'ai vu);只有肯定命令式放在动词后,加连字符(prends-le)。y 代替 à/dans + 地点或 à + 物(j'y vais);en 代替 de + 名词或数量词后的名词(j'en ai deux)。",
          en: "Direct object pronouns le, la, l', les replace whom or what; indirect lui, leur replace à + a person; me, te, nous, vous serve for both. They go before the conjugated verb (je le vois), before an infinitive (je vais le voir), before the auxiliary (je l'ai vu), and only after an affirmative imperative, with a hyphen (prends-le). Y replaces à or dans + place, or à + thing (j'y vais); en replaces de + noun, or a noun after a number (j'en ai deux)." },
  table: { cap: { zh: "代词替换了什么", en: "What each pronoun replaces" },
    head: [{ zh: "代词", en: "Pronoun" }, { zh: "代替", en: "Replaces" }, { zh: "例句", en: "Example" }],
    rows: [["le, l'", "le fil", "Thésée le suit."],
           ["la, l'", "la tête", "Persée ne la regarde pas."],
           ["les", "les béliers", "Le Cyclope les touche."],
           ["lui", "à Ariane", "Thésée lui parle."],
           ["leur", "aux compagnons", "Circé leur donne une boisson."],
           ["me, te, nous, vous", "我、你、我们、你们|me, you, us, you", "Athéna me guide."],
           ["y", "à Athènes", "Thésée y retourne."],
           ["en", { zh: "trois têtes 中的 têtes(trois 留下)", en: "têtes in trois têtes (trois stays)" }, "Cerbère en a trois."],
           ["en", "du labyrinthe", "Thésée en sort."],
           ["l' + avoir", "le lion de Némée", "Héraclès l'a vaincu."]] },
  notes: { zh: "宾语代词和定冠词是亲兄弟:le、la、les 都来自拉丁语指示代词 ille 的宾格 illum、illam、illōs,一支落在名词前成了冠词,一支落在动词前成了代词。leur 来自属格复数 illōrum「他们的」,所以它同时还是主有形容词(leur navire)。lui 来自通俗拉丁语 *illuī。y 一般认为来自 ibi「在那里」,en 来自 inde「从那里」,所以 en 总带着 de 的意思。古法语不许这种轻读代词开头,只好放到动词后面:prends-le 就是这条老规矩的遗迹。",
          en: "Pronoun and article are siblings: le, la, les come from illum, illam, illōs, accusatives of ille — one branch settled before nouns as articles, the other before verbs. Leur is the genitive plural illōrum, of them, hence also a possessive (leur navire). Lui is Vulgar Latin *illuī. Y is usually traced to ibi, there, en to inde, from there — so en carries de. Old French would not open a clause with such a pronoun: prends-le is a relic of that rule." },
  ex: [
    { q: { zh: "Persée cache la tête de Méduse dans un sac. → Persée ___ cache dans un sac.", en: "Persée cache la tête de Méduse dans un sac. → Persée ___ cache dans un sac." },
      opts: ["la", "le", "lui", "en"], a: 0,
      why: { zh: "la tête 是阴性直接宾语,用 la。le 是阳性;lui 只代替「à + 人」;en 代替 de + 名词。", en: "La tête is a feminine direct object, so la. Le is masculine; lui replaces only à + a person; en replaces de + noun." } },
    { q: { zh: "Ariane donne le fil à Thésée. → Ariane ___ donne le fil.", en: "Ariane donne le fil à Thésée. → Ariane ___ donne le fil." },
      opts: ["lui", "le", "la", "leur"], a: 0,
      why: { zh: "à Thésée 是「à + 单数的人」,即间接宾语,用 lui——不论男女都是 lui。le 是直接宾语;leur 用于复数的人。", en: "À Thésée is à + one person, an indirect object, so lui — the same for a man or a woman. Le is a direct object; leur is for several people." } },
    { q: { zh: "Thésée entre dans le labyrinthe. → Thésée ___ entre.", en: "Thésée entre dans le labyrinthe. → Thésée ___ entre." },
      opts: ["y", "en", "le", "lui"], a: 0,
      why: { zh: "dans + 地点用 y 代替:Thésée y entre。en 表示「从那里」,方向正好相反;le、lui 只替代直接宾语或人。", en: "Dans + a place is replaced by y: Thésée y entre. En means from there; le and lui replace a direct object or a person." } },
    { q: { zh: "「格赖埃三姐妹有几只眼睛?——她们只有一只。」Combien d'yeux ont les Grées ? — Elles ___ ont un seul.", en: "How many eyes do the Graeae have? Just one: Combien d'yeux ont les Grées ? — Elles ___ ont un seul." },
      opts: ["en", "y", "les", "l'"], a: 0,
      why: { zh: "数量词后面的名词用 en 代替,数量词本身留下:elles en ont un seul。les 指确定的那些东西,不能和 un 连用;y 代替的是地点。", en: "A noun after a number is replaced by en, and the number stays: elles en ont un seul. Les points to definite things and cannot stand with un; y replaces a place." } },
    { q: { zh: "珀耳修斯说起美杜莎:「我要去找到她。」", en: "Perseus, speaking of Medusa: I am going to find her." },
      opts: ["Je vais la trouver.", "Je vais trouver la.", "Je vais trouver-la.", "Je vais le trouver."], a: 0,
      why: { zh: "有不定式时,代词放在它所属的不定式前:je vais la trouver。连字符只属于肯定命令式;le 是阳性,而美杜莎是阴性。", en: "With an infinitive the pronoun goes right before it: je vais la trouver. The hyphen belongs only to the affirmative imperative, and le is masculine while Medusa is feminine." } },
    { q: { zh: "Thésée a tué le Minotaure. → Thésée ___.", en: "Thésée a tué le Minotaure. → Thésée ___." },
      opts: ["l'a tué", "a le tué", "le a tué", "a tué le"], a: 0,
      why: { zh: "复合过去时里,代词放在助动词前,并在元音前省音:le + a → l'a。le a 忘了省音;a le tué 把代词插进了助动词和分词之间。", en: "In the passé composé the pronoun goes before the auxiliary and elides before the vowel: le + a → l'a. Le a forgets the elision; a le tué wedges it between auxiliary and participle." } },
    { q: { zh: "阿里阿德涅把线团递给忒修斯:「拿着它!」(le fil)", en: "Ariadne hands Theseus the thread: Take it! (le fil)" },
      opts: ["Prends-le !", "Le prends !", "Prends-la !", "Prends-lui !"], a: 0,
      why: { zh: "肯定命令式是唯一让代词跑到动词后面的情况,用连字符相连:Prends-le。le fil 是阳性,所以不是 la;lui 是间接宾语。", en: "The affirmative imperative is the one case where the pronoun follows the verb, joined by a hyphen: Prends-le. Le fil is masculine, so not la; lui is an indirect object." } },
    { q: { zh: "为什么 leur 既是代词(je leur parle)又是主有形容词(leur navire)?", en: "Why is leur both a pronoun (je leur parle) and a possessive (leur navire)?" },
      opts: [{ zh: "都来自拉丁语 illōrum「他们的」", en: "both come from Latin illōrum, of them" }, { zh: "两个词只是碰巧同形", en: "two unrelated words that look alike" }, { zh: "来自拉丁语与格 illīs「给他们」", en: "the Latin dative illīs, to them" }, { zh: "借自法兰克语", en: "a borrowing from Frankish" }], a: 0,
      why: { zh: "illōrum 是 ille 的属格复数,本义「他们的」,既能修饰名词(leur navire),又在通俗拉丁语里接手了「给他们」的功能。因为来自属格,主有形容词 leur 不分阴阳:leur fille、leur fils。", en: "Illōrum, the genitive plural of ille, meant of them: it could qualify a noun (leur navire) and in Vulgar Latin also took over the job of to them. Coming from a genitive, possessive leur has no feminine: leur fille, leur fils." } },
  ] },

{ id: "fr_subj", icon: "🙏",
  name: { zh: "虚拟式 · 埃勾斯的白帆", en: "Subjunctive · Aegeus and the white sail" },
  scene: { zh: "忒修斯启航去克里特之前,父亲埃勾斯叮嘱他:Je veux que tu reviennes. Il faut que tu mettes une voile blanche au retour——我要你回来;归航时必须挂白帆。表达愿望、必要、情感时,que 引出的从句用虚拟式。可惜忒修斯忘了换帆。",
           en: "Before Theseus sails for Crete, his father Aegeus tells him: Je veux que tu reviennes. Il faut que tu mettes une voile blanche au retour — I want you to come back; on the way home you must hoist a white sail. After wishes, needs and feelings, the clause introduced by que takes the subjunctive. Theseus, alas, forgot to change the sail." },
  rule: { zh: "il faut que、vouloir que、être content que、avant que、pour que、bien que 后用虚拟式:ils 现在时词干(finissent → finiss-)+ -e, -es, -e, -ions, -iez, -ent,nous、vous 多同未完成过去时。不规则:aille, fasse, puisse, sache, veuille,être、avoir 见表。同主语时 vouloir 等用不定式;肯定的 penser、espérer que 接直陈式。",
          en: "The subjunctive follows necessity (il faut que), wishing (vouloir que), feeling (être content que), avant que, pour que, bien que. Form: ils-present stem (finissent → finiss-) + -e, -es, -e, -ions, -iez, -ent; nous and vous usually match the imperfect. Irregular: être, avoir (table), aille, fasse, puisse, sache, veuille. With the same subject, vouloir takes the infinitive: je veux partir. Affirmative penser que, espérer que take the indicative." },
  table: { cap: { zh: "虚拟式现在时", en: "Present subjunctive" },
    head: [{ zh: "人称", en: "Person" }, "finir", "prendre", "être", "avoir", "aller"],
    rows: [["que je (j')", "finisse", "prenne", "sois", "aie", "aille"],
           ["que tu", "finisses", "prennes", "sois", "aies", "ailles"],
           ["qu'il, qu'elle", "finisse", "prenne", "soit", "ait", "aille"],
           ["que nous", "finissions", "prenions", "soyons", "ayons", "allions"],
           ["que vous", "finissiez", "preniez", "soyez", "ayez", "alliez"],
           ["qu'ils, qu'elles", "finissent", "prennent", "soient", "aient", "aillent"]] },
  notes: { zh: "subjonctif 来自拉丁语 (modus) subiūnctīvus「连在下面的(语气)」——它主要活在 que 引出的从句里。形式也一脉相承:拉丁语虚拟式现在时 habeam、sapiam、sit 成了 aie、sache、soit;sapiam 的 -pi- 变成 ch,比较西班牙语 sepa、意大利语 sappia。puisse 来自通俗拉丁语 *possiam(古典形式为 possim)。拉丁语还能单用虚拟式表达祝愿:vīvat rēx「愿国王长寿」,法语 Vive le roi ! 正是它的化石。",
          en: "Subjonctif is Latin (modus) subiūnctīvus, the joined-beneath mood: it lives mainly in clauses hanging from que. The forms come from the Latin present subjunctive: habeam, sapiam, sit became aie, sache, soit, the -pi- of sapiam turning into ch (Spanish sepa, Italian sappia). Puisse is Vulgar Latin *possiam (classical possim). Latin could use the subjunctive alone for a wish — vīvat rēx, long live the king — and Vive le roi ! is its fossil." },
  ex: [
    { q: { zh: "「赫拉克勒斯,你必须完成你的任务。」Il faut que tu ___ tes travaux, Héraclès.", en: "Heracles, you must finish your labours: Il faut que tu ___ tes travaux, Héraclès." },
      opts: ["finisses", "finis", "finisse", "finises"], a: 0,
      why: { zh: "il faut que 后面用虚拟式。词干取自 ils finissent → finiss-,tu 的词尾是 -es:finisses。finis 是直陈式;finisse 是 je、il 的形式;finises 少了一个 s。", en: "Il faut que takes the subjunctive. The stem comes from ils finissent, finiss-, and tu takes -es: finisses. Finis is indicative; finisse is the je or il form; finises has lost an s." } },
    { q: { zh: "「埃勾斯要儿子小心谨慎。」Égée veut que son fils ___ prudent.", en: "Aegeus wants his son to be careful: Égée veut que son fils ___ prudent." },
      opts: ["soit", "est", "sois", "être"], a: 0,
      why: { zh: "vouloir que 后接虚拟式,être 的第三人称单数虚拟式是 soit。est 是直陈式;sois 是 je、tu 的形式;être 是不定式,只能在主语相同时用。", en: "Vouloir que takes the subjunctive, and the third singular of être is soit. Est is indicative; sois is the je or tu form; the infinitive être works only when the subject is the same." } },
    { q: { zh: "阿里阿德涅对忒修斯说:「我想和你一起走。」哪一句对?", en: "Ariadne tells Theseus she wants to leave with him. Which is right?" },
      opts: ["Je veux partir avec toi.", "Je veux que je parte avec toi.", "Je veux que je pars avec toi.", "Je veux de partir avec toi."], a: 0,
      why: { zh: "想走的人和要走的人都是「我」,主语相同就直接用不定式:je veux partir。只有主语不同时才用 que + 虚拟式:je veux que tu partes。vouloir 后面也不加 de。", en: "The one who wants and the one who leaves are both I, so the infinitive is used: je veux partir. Que + subjunctive is only for a different subject: je veux que tu partes. Vouloir takes no de." } },
    { q: { zh: "「佩涅洛佩希望奥德修斯会回来。」Pénélope espère qu'Ulysse ___.", en: "Penelope hopes that Odysseus will come back: Pénélope espère qu'Ulysse ___." },
      opts: ["reviendra", "revienne", "revenir", "reviennes"], a: 0,
      why: { zh: "肯定的 espérer que 讲的是期待会实现的事,用直陈式,常用将来时:qu'Ulysse reviendra。revienne 是虚拟式,在这里是常见的过度使用;revenir 是不定式;reviennes 是 tu 的形式。", en: "Affirmative espérer que looks forward to something expected, so it takes the indicative, often the future: qu'Ulysse reviendra. Revienne is the subjunctive, a common over-use here; revenir is the infinitive; reviennes is the tu form." } },
    { q: { zh: "「阿尔戈英雄们必须有勇气。」Il faut que les Argonautes ___ du courage.", en: "The Argonauts must have courage: Il faut que les Argonautes ___ du courage." },
      opts: ["aient", "ont", "ayent", "avent"], a: 0,
      why: { zh: "avoir 的虚拟式不规则:qu'ils aient。ont 是直陈式;ayent 是旧时拼法,今天算拼写错误(只有 nous ayons、vous ayez 才带 y);avent 是硬造的。", en: "Avoir is irregular in the subjunctive: qu'ils aient. Ont is indicative; ayent is an old spelling, wrong today (only ayons and ayez have a y); avent is invented." } },
    { q: { zh: "「俄耳甫斯歌唱,为了让冥王把欧律狄刻送回人间。」Orphée chante pour que le roi des Enfers ___ revenir Eurydice.", en: "Orpheus sings so that the king of the Underworld will bring Eurydice back: Orphée chante pour que le roi des Enfers ___ revenir Eurydice." },
      opts: ["fasse", "fait", "faisse", "fera"], a: 0,
      why: { zh: "pour que(为了让)总接虚拟式,faire 的虚拟式不规则:qu'il fasse。fait 是直陈式,fera 是将来时,faisse 是照 nous faisons 硬造的。", en: "Pour que, so that, always takes the subjunctive, and faire is irregular: qu'il fasse. Fait is indicative, fera is future, and faisse is invented from nous faisons." } },
    { q: { zh: "下面哪个开头后面要用虚拟式?", en: "Which opening is followed by the subjunctive?" },
      opts: ["Il faut que…", "Je pense que…", "J'espère que…", "Je sais que…"], a: 0,
      why: { zh: "il faut que 表示必要,永远接虚拟式。肯定的 penser que、espérer que、savoir que 讲的是认定或期待的事,用直陈式。", en: "Il faut que expresses necessity and always takes the subjunctive. Affirmative penser que, espérer que and savoir que state what one holds or expects to be true, so they take the indicative." } },
    { q: { zh: "Vive le roi !(国王万岁!)里的 vive 是什么?", en: "In Vive le roi !, what is vive?" },
      opts: [{ zh: "vivre 的虚拟式(祝愿)", en: "the subjunctive of vivre (a wish)" }, { zh: "vivre 的命令式", en: "the imperative of vivre" }, { zh: "形容词 vif 的阴性", en: "the feminine of the adjective vif" }, { zh: "vivre 的直陈式现在时", en: "the present indicative of vivre" }], a: 0,
      why: { zh: "拉丁语可以单用虚拟式表达祝愿:vīvat rēx「愿国王活着」。法语 Vive le roi ! 原样保留了这种用法,不需要 que。vivre 的命令式是 vis,直陈式是 il vit。", en: "Latin could use the subjunctive alone for a wish: vīvat rēx, may the king live. French Vive le roi ! keeps that use, with no que. The imperative of vivre is vis, the indicative il vit." } },
  ] },
]);
