/* =====================================================
   FUGA MYTHICA — grammar road for the study language "it": ten stations,
   added to GRAMS through GRAM_ADD() (defined in grammar.js, loaded first).
   ===================================================== */
/* Fuga Mythica — Italian grammar road, stations 1–5 */
GRAM_ADD("it", [
{ id: "it_genere", icon: "🛡️",
  name: { zh: "名词的性与冠词 · 珀耳修斯的装备", en: "Gender and articles · The gear of Perseus" },
  scene: { zh: "珀耳修斯出发去斩美杜莎,众神和仙女为他备好装备:雅典娜的 lo scudo(盾)、赫尔墨斯的 la falce(镰刀)、哈迪斯的 l'elmo(隐身盔)。意大利语的每个名词都有性别,冠词就是它的名牌:看到 il、lo、la,就知道它是阳性还是阴性。",
           en: "Perseus sets out to behead Medusa, and gods and nymphs equip him: Athena's shield, lo scudo; Hermes's sickle, la falce; the helmet of Hades, l'elmo, that makes him invisible. Every Italian noun has a gender, and the article is its name tag: il, lo and la tell you at once which it is." },
  rule: { zh: "意大利语只有阳性和阴性。-o 结尾多为阳性(il toro),-a 多为阴性(la spada),-e 两种都有,要连冠词一起记(il mare,la notte)。阳性定冠词一般用 il,在 s+辅音、z、gn、ps、x、y 前用 lo,元音前用 l';阴性用 la,元音前用 l'。不定冠词是 un、uno、una、un',只有阴性才加撇号:un eroe,un'isola。希腊来源的 -ma 名词大多是阳性(il problema、il poema);la mano 则是 -o 结尾的阴性。",
          en: "Italian has two genders. Nouns in -o are mostly masculine (il toro), in -a mostly feminine (la spada); nouns in -e can be either, so learn them with the article (il mare, la notte). Il becomes lo before s + consonant, z, gn, ps, x, y, and l' before a vowel; la becomes l' before a vowel. Indefinite: un, uno, una, un' — only the feminine elides (un eroe, un'isola). Greek nouns in -ma are mostly masculine (il problema); la mano is feminine." },
  table: { cap: { zh: "冠词怎么选", en: "Choosing the article" },
    head: [{ zh: "场合", en: "When" }, { zh: "定冠词", en: "Definite" }, { zh: "不定冠词", en: "Indefinite" }, { zh: "例子", en: "Examples" }],
    rows: [["阳 · 一般辅音|m. · consonant", "il", "un", "il toro, un mostro"],
           ["阳 · s+辅音、z…|m. · s+cons., z…", "lo", "uno", "lo scudo, uno spettro, lo zolfo"],
           ["阳 · 元音|m. · vowel", "l'", "un", "l'elmo, un eroe"],
           ["阴 · 辅音|f. · consonant", "la", "una", "la spada, una ninfa"],
           ["阴 · 元音|f. · vowel", "l'", "un'", "l'isola, un'onda"],
           ["-e · 阳|-e · m.", "il", "un", "il mare, il sole, il serpente"],
           ["-e · 阴|-e · f.", "la", "una", "la notte, la luce, la nave"],
           ["希腊 -ma · 阳|Greek -ma · m.", "il", "un", "il problema, il poema"],
           ["-o · 阴(少见)|-o · f. (rare)", "la", "una", "la mano"]] },
  notes: { zh: "拉丁语没有冠词。口语里指示词 ille、illa(那个)越用越虚,变成了冠词:(il)lum → lo,(il)la → la,il 也是 lo 的弱化形;不定冠词 un 来自数词 ūnus(一)。拉丁语的中性大多并入了阳性:mare、corpus 成了 il mare、il corpo;希腊中性词 problema、poema 也一样,所以以 -a 结尾却用 il。-e 结尾的词大多来自第三变格法,那里本就三性都有。「冠词」articolo 来自 articulus(小关节),译自希腊语 arthron(关节)。",
          en: "Latin had no articles. In speech the demonstratives ille, illa, that, faded into articles: (il)lum gave lo, (il)la gave la, and il is a reduced lo; un is the numeral ūnus. The Latin neuter mostly merged into the masculine — mare and corpus became il mare, il corpo — and so did Greek neuters like problema. Nouns in -e mostly come from the third declension, which mixed all genders. Articolo is Latin articulus, a little joint, after Greek arthron." },
  ex: [
    { q: { zh: "Atena presta a Perseo ___ scudo lucido.(雅典娜把她那面亮盾借给珀耳修斯)", en: "Atena presta a Perseo ___ scudo lucido. (Athena lends Perseus her polished shield.)" }, opts: ["lo", "il", "la", "l'"], a: 0,
      why: { zh: "scudo 以 s+辅音开头,阳性冠词要用 lo(不定冠词 uno)。il 只用在一般辅音前,所以 il scudo 是最常见的错误。", en: "Scudo begins with s + consonant, so the masculine article is lo (indefinite uno). Il serves ordinary consonants, which makes il scudo the classic mistake." } },
    { q: { zh: "「一位英雄,一座岛」哪一组写对了?", en: "A hero, an island — which pair is right?" }, opts: ["un eroe, un'isola", "un'eroe, un'isola", "un eroe, un isola", "uno eroe, una isola"], a: 0,
      why: { zh: "eroe 是阳性,un 在元音前不加撇号;isola 是阴性,una 在元音前省音成 un'。un'eroe 是最常见的拼写错误。", en: "Eroe is masculine, and un takes no apostrophe before a vowel. Isola is feminine, so una elides to un'. Writing un'eroe is the commonest slip." } },
    { q: { zh: "Per Perseo, Medusa è ___ problema serio.(对珀耳修斯来说,美杜莎是个大问题)", en: "Per Perseo, Medusa è ___ problema serio. (For Perseus, Medusa is a serious problem.)" }, opts: ["un", "una", "un'", "uno"], a: 0,
      why: { zh: "problema 虽以 -a 结尾,却是来自希腊语的阳性词,所以用 un。una problema 是按词尾猜性别的典型错误。", en: "Problema ends in -a but is a masculine word from Greek, so it takes un. Una problema is the classic mistake of guessing gender from the ending." } },
    { q: { zh: "哪一个冠词用错了?", en: "Which article is wrong?" }, opts: ["il spirito", "lo scettro", "l'elmo", "la falce"], a: 0,
      why: { zh: "spirito 以 s+辅音开头,必须说 lo spirito。其余三个都对:lo scettro(s+辅音)、l'elmo(元音)、la falce(阴性)。", en: "Spirito begins with s + consonant, so it must be lo spirito. The others are right: lo scettro (s + consonant), l'elmo (vowel), la falce (feminine)." } },
    { q: { zh: "下面哪个 -e 结尾的名词是阴性?", en: "Which of these nouns in -e is feminine?" }, opts: ["notte", "mare", "sole", "fiume"], a: 0,
      why: { zh: "la notte 是阴性,和拉丁 nox 一样;il mare、il sole、il fiume 都是阳性。-e 结尾的词只能连冠词一起记。", en: "La notte is feminine, like Latin nox; il mare, il sole and il fiume are masculine. Nouns in -e must be learnt together with their article." } },
    { q: { zh: "___ mano di Perseo stringe la falce.(珀耳修斯的手握紧镰刀)", en: "___ mano di Perseo stringe la falce. (Perseus's hand grips the sickle.)" }, opts: ["la", "il", "lo", "l'"], a: 0,
      why: { zh: "mano 是 -o 结尾的阴性词,因为拉丁 manus 本就是阴性。按 -o 猜成 il mano 是常见错误。", en: "Mano is a feminine noun in -o, because Latin manus was feminine. Guessing il mano from the -o is a common error." } },
    { q: { zh: "意大利语的定冠词 il、lo、la 来自哪里?", en: "Where do the Italian definite articles il, lo, la come from?" },
      opts: [{ zh: "拉丁语指示词 ille、illa(那个)", en: "the Latin demonstratives ille, illa (that)" }, { zh: "拉丁语数词 ūnus(一)", en: "the Latin numeral ūnus (one)" }, { zh: "希腊语冠词 ho、hē,经教会传入", en: "the Greek article ho, hē, brought in by the Church" }, { zh: "日耳曼语的 der、die,由伦巴第人带来", en: "Germanic der, die, brought by the Lombards" }], a: 0,
      why: { zh: "拉丁语本没有冠词,口语里「那个」ille、illa 弱化成了 il/lo、la。ūnus 是不定冠词 un 的来源,不是定冠词的。", en: "Latin had no article; in speech ille and illa, that, weakened into il/lo and la. Ūnus, one, is the source of the indefinite un, not of the definite article." } },
    { q: { zh: "il problema 以 -a 结尾却是阳性,为什么?", en: "Il problema ends in -a yet is masculine. Why?" },
      opts: [{ zh: "它原是希腊语的中性词,意大利语把它归入阳性", en: "it was a Greek neuter, and Italian made it masculine" }, { zh: "所有 -a 结尾的名词都是阳性", en: "all nouns in -a are masculine" }, { zh: "它来自拉丁语第一变格法,和 rosa 一样", en: "it comes from the Latin first declension, like rosa" }, { zh: "意大利语的抽象名词一律是阳性", en: "abstract nouns in Italian are always masculine" }], a: 0,
      why: { zh: "problema、poema、tema 在希腊语里是中性,拉丁语照搬为中性;意大利语没有中性,就把它们并入阳性。拉丁第一变格法的 -a 词大多是阴性,恰好相反。", en: "Problema, poema and tema were Greek neuters, borrowed as neuters by Latin; Italian has no neuter and folded them into the masculine. Latin first-declension nouns in -a were mostly feminine — the opposite." } },
  ] },

{ id: "it_plurale", icon: "🌿",
  name: { zh: "复数 · 九头蛇的头", en: "Plurals · The heads of the Hydra" },
  scene: { zh: "赫拉克勒斯砍下勒拿九头蛇的一个头(una testa),断口立刻长出两个(due teste)。意大利语的复数不加 -s,而是换掉词尾元音:-o 变 -i,-a 变 -e,-e 变 -i。il serpente 成了 i serpenti,冠词也跟着变。",
           en: "Heracles cuts off one head of the Hydra of Lerna, una testa, and two grow in its place, due teste. Italian makes plurals not by adding -s but by changing the final vowel: -o becomes -i, -a becomes -e, -e becomes -i. Il serpente turns into i serpenti, and the article changes with it." },
  rule: { zh: "复数靠换词尾元音:-o → -i,-a → -e,-e → -i(i tori,le teste,le notti)。冠词:il → i,lo 和阳性 l' → gli,la 和阴性 l' → le。阳性 -a 词变 -i(i problemi)。重音在末尾的词、单音节词、外来词和 -i 结尾的词复数不变(le città,i re)。阴性 -ca/-ga 变 -che/-ghe;-co/-go 要逐个记(i fuochi,但 gli amici)。少数不规则:gli uomini、gli dei、le uova。",
          en: "-o becomes -i, -a becomes -e, -e becomes -i (i tori, le teste, le notti). Articles: il → i; lo and masculine l' → gli; la and feminine l' → le. Masculine -a nouns take -i (i problemi). Nouns with final stress, monosyllables, foreign words and nouns in -i do not change (le città, i re). Feminine -ca/-ga always give -che/-ghe; -co/-go must be learnt one by one (i fuochi, but gli amici). A few are irregular: gli uomini, gli dei, le uova." },
  table: { cap: { zh: "单数 → 复数", en: "Singular → plural" },
    head: [{ zh: "类型", en: "Type" }, { zh: "单数", en: "Singular" }, { zh: "复数", en: "Plural" }],
    rows: [["-o → -i", "il toro", "i tori"],
           ["-a → -e", "la testa", "le teste"],
           ["-e → -i", "il serpente, la notte", "i serpenti, le notti"],
           ["lo、阳性 l' → gli|lo, m. l' → gli", "lo scudo, l'eroe", "gli scudi, gli eroi"],
           ["-ma → -mi", "il problema", "i problemi"],
           ["不变|invariable", "la città, il re, il film, la crisi", "le città, i re, i film, le crisi"],
           ["阴性 -ca, -ga|f. -ca, -ga", "la barca, la maga", "le barche, le maghe"],
           ["-co, -go", "l'amico, il fuoco, il lago", "gli amici, i fuochi, i laghi"],
           ["不规则|irregular", "l'uomo, il dio", "gli uomini, gli dei"],
           ["-o → -a(阴)|-o → -a (f.)", "il braccio, l'uovo, il dito", "le braccia, le uova, le dita"]] },
  notes: { zh: "意大利语的阳性复数延续拉丁语的主格复数:lupī → lupi(狼)。阴性的 -e 来自主格 -ae(rosae → rose)还是宾格 -ās,学界仍有争论。西班牙语、法语走了另一条路,用宾格复数 lupōs、rosās,所以带 -s:lobos、rosas。le braccia、le uova 是拉丁中性复数 bracchia、ōva 的化石,-a 被重新理解为阴性复数;le dita 的原词 digitus 本是阳性,是后来类推进这个模式的。",
          en: "Italian masculine plurals continue the Latin nominative plural: lupī became lupi. Whether feminine -e continues nominative -ae (rosae, rose) or accusative -ās is still debated. Spanish and French built on the accusative lupōs, rosās, hence lobos, rosas. Le braccia and le uova fossilise the neuter plurals bracchia, ōva, their -a reread as feminine; le dita joined by analogy, as Latin digitus was masculine." },
  ex: [
    { q: { zh: "L'Idra di Lerna ha nove ___(testa 的复数)", en: "L'Idra di Lerna ha nove ___ (plural of testa)" }, opts: ["teste", "testi", "testa", "testas"], a: 0,
      why: { zh: "阴性 -a 的复数是 -e:la testa → le teste。testi 是把阳性的 -i 错套到阴性词上。", en: "Feminine -a makes its plural in -e: la testa, le teste. Testi wrongly applies the masculine -i." } },
    { q: { zh: "il dio(神)的复数是:", en: "The plural of il dio (god) is:" }, opts: ["gli dei", "i dei", "le dee", "gli dio"], a: 0,
      why: { zh: "il dio 的复数不规则:gli dei,而且在辅音 d 前也用 gli。le dee 是 la dea(女神)的复数。", en: "Il dio has an irregular plural, gli dei, with gli even before the consonant d. Le dee is the plural of la dea, goddess." } },
    { q: { zh: "___ eroi tornano a casa.(英雄们回家了)", en: "___ eroi tornano a casa. (The heroes come home.)" }, opts: ["gli", "i", "le", "l'"], a: 0,
      why: { zh: "阳性复数在元音前用 gli:l'eroe → gli eroi。i 只用在一般辅音前(i tori),le 是阴性复数。", en: "Masculine plurals take gli before a vowel: l'eroe, gli eroi. I is for ordinary consonants (i tori), and le is feminine." } },
    { q: { zh: "Teseo e Piritoo sono ___(amico 的复数)", en: "Teseo e Piritoo sono ___ (plural of amico)" }, opts: ["amici", "amichi", "amicos", "amice"], a: 0,
      why: { zh: "amico 的复数是 amici,c 变软音;但 fuoco、lago 却保持硬音(fuochi、laghi),-co/-go 要逐个记。amicos 是西班牙语式的 -s 复数。", en: "Amico gives amici, with a soft c, while fuoco and lago keep the hard sound (fuochi, laghi): -co/-go nouns must be learnt one by one. Amicos is a Spanish-style -s plural." } },
    { q: { zh: "哪一个复数是错的?", en: "Which plural is wrong?" }, opts: ["i fuoci", "i laghi", "le barche", "i re"], a: 0,
      why: { zh: "fuoco 的复数是 fuochi,加 h 保住硬音 k;laghi、barche 同理。re 是单音节词,复数不变:i re。", en: "Fuoco makes fuochi, adding h to keep the hard k; laghi and barche do the same. Re is a monosyllable and does not change: i re." } },
    { q: { zh: "某些版本里,勒达生下两枚蛋:Leda depone due ___", en: "In some versions Leda lays two eggs: Leda depone due ___" }, opts: ["uova", "uovi", "uove", "uovo"], a: 0,
      why: { zh: "l'uovo 的复数是阴性的 le uova,保留了拉丁中性复数 ōva 的 -a。uovi 是按 -o → -i 过度规则化的错误。", en: "L'uovo has the feminine plural le uova, keeping the -a of the Latin neuter plural ōva. Uovi over-applies the -o → -i rule." } },
    { q: { zh: "Troia e Micene sono due ___(città 的复数)", en: "Troia e Micene sono due ___ (plural of città)" }, opts: ["città", "citte", "cittàe", "cittì"], a: 0,
      why: { zh: "重音落在最后一个元音上的名词,复数不变:la città → le città。citte 是硬套 -a → -e 的错误。", en: "Nouns stressed on the final vowel do not change in the plural: la città, le città. Citte forces the -a → -e rule where it does not apply." } },
    { q: { zh: "「狼」的复数,意大利语是 lupi,西班牙语是 lobos。为什么一个没有 -s?", en: "Wolves: Italian lupi, Spanish lobos. Why does one lack the -s?" },
      opts: [{ zh: "意大利语延续主格 lupī,西班牙语延续宾格 lupōs", en: "Italian kept the nominative lupī, Spanish the accusative lupōs" }, { zh: "西班牙语延续主格 lupī,意大利语延续宾格 lupōs", en: "Spanish kept the nominative lupī, Italian the accusative lupōs" }, { zh: "意大利语的 -i 借自希腊语的复数", en: "Italian -i was borrowed from Greek plurals" }, { zh: "意大利人中世纪时不再书写词尾 -s", en: "Italians stopped writing the final -s in the Middle Ages" }], a: 0,
      why: { zh: "lupi 延续主格复数 lupī,lobos 延续宾格复数 lupōs。所以意大利语复数没有 -s,而西班牙语、法语、葡萄牙语都有。", en: "Lupi continues the nominative plural lupī, lobos the accusative lupōs. That is why Italian plurals have no -s, while Spanish, French and Portuguese do." } },
  ] },

{ id: "it_prep", icon: "🧭",
  name: { zh: "介词 + 冠词 · 奥德修斯的航程", en: "Preposition + article · The voyage of Odysseus" },
  scene: { zh: "奥德修斯驶近塞壬的岛,让水手们用蜡封住耳朵,自己被绑在桅杆上:legato all'albero della nave。all' 是 a + l',della 是 di + la。意大利语的介词一碰到定冠词就合成一个词,一句话里能出现好几次。",
           en: "Odysseus nears the island of the Sirens. His sailors stop their ears with wax, and he has himself tied to the mast: legato all'albero della nave. All' is a + l', della is di + la. When an Italian preposition meets the definite article the two melt into one word, often several times in a sentence." },
  rule: { zh: "di、a、da、in、su 遇到定冠词必须合写:di + il = del,a + la = alla,da + l' = dall',su + gli = sugli;in 变成 ne-:nel、nella、negli。con 和 per 现代一般分写(con il,per la;口语也说 col)。用法:城市用 a(a Troia),国家和地区用 in(in Grecia);da 表示来源(dall'isola)和「在某人那里」(dal re);di 表示所属(la spada del re)。",
          en: "Di, a, da, in and su fuse with the definite article: di + il = del, a + la = alla, da + l' = dall', su + gli = sugli; in turns into ne-: nel, nella, negli. Con and per are normally kept apart today (con il, per la; speech also has col). Use a for cities (a Troia) and in for countries and regions (in Grecia); da for origin (dall'isola) and someone's place (dal re); di for possession (del re)." },
  table: { cap: { zh: "介词 + 定冠词", en: "Preposition + definite article" },
    head: [{ zh: "冠词", en: "Article" }, "di", "a", "da", "in", "su"],
    rows: [["il", "del", "al", "dal", "nel", "sul"],
           ["lo", "dello", "allo", "dallo", "nello", "sullo"],
           ["l'", "dell'", "all'", "dall'", "nell'", "sull'"],
           ["la", "della", "alla", "dalla", "nella", "sulla"],
           ["i", "dei", "ai", "dai", "nei", "sui"],
           ["gli", "degli", "agli", "dagli", "negli", "sugli"],
           ["le", "delle", "alle", "dalle", "nelle", "sulle"]] },
  notes: { zh: "拉丁语用格表示关系,意大利语把这件事交给介词:属格换成 di(来自 dē),与格换成 a(来自 ad)。da 的来源有争议,常见说法是 dē + ab(存疑);su 来自 sūsum(向上)。古意大利语文献里介词和冠词常常分写:de la、ne lo、a la,ne 是 in 的古老变体。della 中间的双 l 正是拉丁 illa 原有的 ll:它夹在两个元音之间保住了,而单独开头的冠词则简化成 la。",
          en: "Latin marked relations with cases; Italian gave the job to prepositions: the genitive gave way to di (from dē), the dative to a (from ad). The origin of da is debated — often dē + ab (disputed); su is from sūsum, upward. Old Italian texts often wrote the pieces apart: de la, ne lo, a la, ne being an old variant of in. The double l of della is the ll of Latin illa, kept safe between two vowels; the article standing alone shrank to la." },
  ex: [
    { q: { zh: "Teseo solleva il sasso e trova la spada ___ padre.(忒修斯掀起巨石,找到父亲的剑)", en: "Teseo solleva il sasso e trova la spada ___ padre. (Theseus lifts the rock and finds his father's sword.)" }, opts: ["del", "di il", "dello", "della"], a: 0,
      why: { zh: "di + il 必须合写成 del:la spada del padre。di il 分开写是错的;dello 用于 s+辅音等,della 用于阴性。", en: "Di + il must fuse into del: la spada del padre. Writing di il apart is wrong; dello is for s + consonant and the like, della for feminines." } },
    { q: { zh: "Ulisse è legato ___ albero della nave.(奥德修斯被绑在桅杆上)", en: "Ulisse è legato ___ albero della nave. (Odysseus is tied to the mast.)" }, opts: ["all'", "al", "allo", "a l'"], a: 0,
      why: { zh: "albero 是元音开头的阳性词,冠词是 l',a + l' = all'。albero 既是「树」也是「桅杆」。", en: "Albero is masculine and begins with a vowel, so its article is l', and a + l' = all'. Albero means both tree and mast." } },
    { q: { zh: "Polifemo dorme ___ grotta.(波吕斐摩斯在山洞里睡觉)", en: "Polifemo dorme ___ grotta. (Polyphemus sleeps in the cave.)" }, opts: ["nella", "in la", "nel", "nello"], a: 0,
      why: { zh: "grotta 是阴性,in + la = nella。in 遇到定冠词要变成 ne- 并合写,in la 不能分开。", en: "Grotta is feminine, and in + la = nella. Before the definite article in becomes ne- and fuses; in la is never written apart." } },
    { q: { zh: "Menelao regna ___ Sparta, ___ Grecia.(墨涅拉俄斯在希腊的斯巴达称王)", en: "Menelao regna ___ Sparta, ___ Grecia. (Menelaus reigns at Sparta, in Greece.)" }, opts: ["a … in", "in … a", "a … a", "alla … in"], a: 0,
      why: { zh: "城市用 a,国家和地区用 in:a Sparta,in Grecia。把两者对调是最常见的错误;不带修饰语的城市名前也不加冠词,所以 alla Sparta 是错的。", en: "Cities take a, countries and regions take in: a Sparta, in Grecia. Swapping the two is the usual mistake, and a bare city name takes no article, so alla Sparta is wrong." } },
    { q: { zh: "Teseo è dal re Minosse 的意思是:", en: "Teseo è dal re Minosse means:" },
      opts: [{ zh: "忒修斯在米诺斯王那里", en: "Theseus is at King Minos’s court" }, { zh: "忒修斯属于米诺斯王", en: "Theseus belongs to King Minos" }, { zh: "忒修斯就是米诺斯王", en: "Theseus is King Minos himself" }, { zh: "忒修斯站在米诺斯王身上", en: "Theseus is standing on top of King Minos" }], a: 0,
      why: { zh: "da + 人表示「在某人那里」:dal re 就是「在国王那里」。表示所属要用 di:del re。", en: "Da with a person means at that person’s place: dal re, at the king’s. Possession would need di: del re." } },
    { q: { zh: "Gli dei siedono ___ troni d'oro.(众神坐在金宝座上)", en: "Gli dei siedono ___ troni d'oro. (The gods sit on golden thrones.)" }, opts: ["sui", "sugli", "su i", "sulle"], a: 0,
      why: { zh: "troni 是一般辅音开头的阳性复数,冠词是 i,su + i = sui。sugli 用在元音、s+辅音、z 等前面(sugli scudi)。", en: "Troni is a masculine plural beginning with an ordinary consonant, so the article is i, and su + i = sui. Sugli is for vowels, s + consonant, z and the like (sugli scudi)." } },
    { q: { zh: "哪一个写错了?", en: "Which one is wrong?" }, opts: ["nel specchio", "nello scudo", "dall'isola", "sullo scoglio"], a: 0,
      why: { zh: "specchio 以 s+辅音开头,冠词是 lo,in + lo = nello specchio。其余三个都正确。", en: "Specchio begins with s + consonant, so its article is lo, and in + lo = nello specchio. The other three are correct." } },
    { q: { zh: "della 为什么有两个 l?", en: "Why does della have two l’s?" },
      opts: [{ zh: "拉丁 illa 原有的 ll 夹在元音之间保留了下来", en: "the ll of Latin illa survived between vowels" }, { zh: "为了读起来更响亮而特意加倍", en: "it was doubled so that it would sound louder" }, { zh: "照搬了希腊语冠词的拼法", en: "it copies the spelling of the Greek article" }, { zh: "文艺复兴时期印刷工人的习惯固定了下来", en: "a habit of Renaissance printers became the rule" }], a: 0,
      why: { zh: "冠词 la 来自 (il)la。单独开头时双辅音简化了;跟在 de 后面时它处在两个元音之间,原来的 ll 得以保留:della。", en: "La comes from (il)la. Standing alone it lost the double consonant, but after de it sat between two vowels and kept it: della." } },
  ] },

{ id: "it_presente", icon: "🔥",
  name: { zh: "现在时 · 普罗米修斯盗火", en: "Present tense · Prometheus steals fire" },
  scene: { zh: "普罗米修斯把火种藏在一根空心的茴香茎里,带给人类:ruba il fuoco(他偷火)、scende dall'Olimpo(他走下奥林波斯)、apre la mano(他张开手)。意大利语通常不说主语代词——ruba 的词尾 -a 已经说明是「他」。",
           en: "Prometheus hides a spark in a hollow fennel stalk and carries it to mankind: ruba il fuoco, he steals the fire; scende dall'Olimpo, he comes down from Olympus; apre la mano, he opens his hand. Italian usually leaves out the subject pronoun — the -a of ruba already says he." },
  rule: { zh: "动词按不定式分三类:-are、-ere、-ire。去掉词尾,按表加上人称词尾;三类的 noi 都是 -iamo。很多 -ire 动词在三个单数人称和第三人称复数插入 -isc-:finisco、finisci、finisce、finiamo、finite、finiscono(capire、preferire 同)。-care/-gare 在 i 前加 h 保住硬音:cerchi、paghiamo。尊称 Lei(您)用第三人称单数:Lei parla。词尾已经标明人称,主语代词通常省略。",
          en: "Verbs fall into three classes by infinitive: -are, -ere, -ire. Drop the ending and add the personal endings in the table; noi always ends in -iamo. Many -ire verbs insert -isc- in the singular and the third plural: finisco, finisci, finisce, finiamo, finite, finiscono (also capire, preferire). -care/-gare add h before i to keep the hard sound: cerchi, paghiamo. Formal Lei takes the third singular: Lei parla. Subject pronouns are usually dropped." },
  table: { cap: { zh: "四个模板动词", en: "Four model verbs" },
    head: [{ zh: "人称", en: "Person" }, "parlare", "credere", "dormire", "finire"],
    rows: [["io 我|io", "parlo", "credo", "dormo", "finisco"],
           ["tu 你|tu", "parli", "credi", "dormi", "finisci"],
           ["lui, lei, Lei 他/她/您|lui, lei, Lei", "parla", "crede", "dorme", "finisce"],
           ["noi 我们|noi", "parliamo", "crediamo", "dormiamo", "finiamo"],
           ["voi 你们|voi", "parlate", "credete", "dormite", "finite"],
           ["loro 他们|loro", "parlano", "credono", "dormono", "finiscono"]] },
  notes: { zh: "拉丁语有四种变位(-āre、-ēre、-ere、-īre),意大利语把第二、第三种合并成 -ere,但重音还记得旧的分别:vedére 来自 vidēre,重音在词尾;crédere 来自 crēdere,重音在词干。-isc- 来自拉丁语表示「开始」的后缀 -scō(flōrēscō 开始开花):「开始」的意思早已消失,如今它只让重音落在 -isc- 上而不落在词根上。noi 的 -iamo 原是虚拟式词尾(habeāmus、audiāmus),后来扩展到所有动词。",
          en: "Latin had four conjugations (-āre, -ēre, -ere, -īre); Italian merged the second and third into -ere, yet the stress remembers: vedére, from vidēre, stresses the ending, crédere, from crēdere, the stem. The -isc- of finisco is the Latin inchoative -scō, as in flōrēscō, I begin to bloom; the sense of beginning faded, and it now keeps the stress off the root. Noi -iamo was a subjunctive ending (habeāmus) that spread to all verbs." },
  ex: [
    { q: { zh: "Prometeo ___ il fuoco agli dei.(rubare,普罗米修斯从众神那里偷火)", en: "Prometeo ___ il fuoco agli dei. (rubare — Prometheus steals fire from the gods.)" }, opts: ["ruba", "rubo", "rubi", "rube"], a: 0,
      why: { zh: "rubare 是 -are 动词,第三人称单数词尾是 -a:ruba。rubo 是「我偷」,rubi 是「你偷」。", en: "Rubare is an -are verb, and its third singular ends in -a: ruba. Rubo is I steal, rubi you steal." } },
    { q: { zh: "Di notte noi ___ nella caverna.(dormire,夜里我们睡在洞里)", en: "Di notte noi ___ nella caverna. (dormire — at night we sleep in the cave.)" }, opts: ["dormiamo", "dormite", "dormisciamo", "dormono"], a: 0,
      why: { zh: "noi 的词尾三类动词都是 -iamo:dormiamo。dormire 不带 -isc-,dormite 是 voi(你们)的形式,dormono 是 loro 的。", en: "The noi ending is -iamo in all three classes: dormiamo. Dormire takes no -isc-; dormite is the voi form, dormono the loro form." } },
    { q: { zh: "Gli uomini ___ il valore del fuoco.(capire,人类懂得火的价值)", en: "Gli uomini ___ il valore del fuoco. (capire — men understand the worth of fire.)" }, opts: ["capiscono", "capono", "capiamo", "capisciono"], a: 0,
      why: { zh: "capire 是 -isc- 动词,第三人称复数是 capiscono。capono 漏掉了 -isc-,capiamo 是「我们明白」。", en: "Capire is an -isc- verb, so the third plural is capiscono. Capono leaves out -isc-, and capiamo means we understand." } },
    { q: { zh: "冥界的达那伊得斯姐妹说:«Noi non ___ mai il lavoro.»(finire)", en: "The Danaids in the underworld say: «Noi non ___ mai il lavoro.» (finire)" }, opts: ["finiamo", "finisciamo", "finischiamo", "finiscono"], a: 0,
      why: { zh: "-isc- 只出现在三个单数人称和第三人称复数,noi 和 voi 没有:finiamo、finite。finisciamo 是把 -isc- 过度套用。", en: "-isc- appears only in the three singular persons and the third plural; noi and voi lack it: finiamo, finite. Finisciamo over-applies it." } },
    { q: { zh: "Teseo, tu ___ l'uscita del labirinto?(cercare,忒修斯,你在找迷宫出口吗?)", en: "Teseo, tu ___ l'uscita del labirinto? (cercare — Theseus, are you looking for the way out?)" }, opts: ["cerchi", "cerci", "cerchii", "cercate"], a: 0,
      why: { zh: "cercare 在 i 前要加 h 保住硬音 k:tu cerchi。写成 cerci 就会读成软音 [tʃ]。cercate 是 voi 的形式。", en: "Cercare adds h before i to keep the hard k: tu cerchi. Cerci would be read with a soft [tʃ]. Cercate is the voi form." } },
    { q: { zh: "奥德修斯对王后阿瑞塔说:«Regina, Lei ___ alla mia storia?»(credere)", en: "Odysseus to Queen Arete: «Regina, Lei ___ alla mia storia?» (credere)" }, opts: ["crede", "credi", "credete", "credo"], a: 0,
      why: { zh: "尊称 Lei(您)用第三人称单数:Lei crede。credi 是对熟人说的 tu 形式,不能和 Lei 搭配。", en: "Formal Lei takes the third singular: Lei crede. Credi is the familiar tu form and cannot go with Lei." } },
    { q: { zh: "Dormo nella grotta. 是谁在睡?", en: "Dormo nella grotta. Who is sleeping?" },
      opts: [{ zh: "我", en: "I" }, { zh: "他", en: "he" }, { zh: "我们", en: "we" }, { zh: "没有主语,无法判断", en: "impossible to tell without a subject" }], a: 0,
      why: { zh: "词尾 -o 表示第一人称单数,所以 dormo 就是「我睡」。意大利语只在强调或对比时才加 io。", en: "The ending -o marks the first person singular, so dormo means I sleep. Italian adds io only for emphasis or contrast." } },
    { q: { zh: "finisco 里的 -isc- 来自哪里?", en: "Where does the -isc- of finisco come from?" },
      opts: [{ zh: "拉丁语表示「开始」的后缀 -scō", en: "the Latin inchoative -scō, ‘begin to’" }, { zh: "拉丁语完成时的词尾", en: "an ending of the Latin perfect tense" }, { zh: "借入拉丁语的希腊将来时标记", en: "a Greek future marker borrowed by Latin" }, { zh: "伦巴第人带来的日耳曼后缀", en: "a Germanic suffix brought by the Lombards" }], a: 0,
      why: { zh: "拉丁语 flōrēscō 是「开始开花」,-scō 表示开始。意大利语里这层意思消失了,-isc- 只负责让重音不落在词根上。", en: "Latin flōrēscō means I begin to bloom; -scō marks the beginning. Italian lost that sense and keeps -isc- only to hold the stress off the root." } },
  ] },

{ id: "it_irregolari", icon: "🗡️",
  name: { zh: "常用不规则动词 · 阿尔戈英雄", en: "Irregular verbs · The Argonauts" },
  scene: { zh: "伊阿宋召集英雄,登上阿尔戈号去科尔基斯取金羊毛:«Siamo eroi, abbiamo una nave, andiamo in Colchide!» siamo、abbiamo、andiamo 都出自不规则动词。越常用的动词磨损得越快,也越不容易被规则化,所以最不规则的恰恰是「是、有、去、做」。",
           en: "Jason gathers the heroes aboard the Argo to fetch the Golden Fleece from Colchis: «Siamo eroi, abbiamo una nave, andiamo in Colchide!» — we are heroes, we have a ship, we sail for Colchis. The most used verbs wear down fastest and best resist regularisation, so to be, to have, to go and to do are the least regular of all." },
  rule: { zh: "越常用的动词越不规则,要整套记住(见表)。avere 的 ho、hai、ha、hanno 里 h 不发音。andare 的单数和 loro 用 v- 词干(vado、vanno),noi、voi 用 and- 词干(andiamo)。fare、dire 有时露出长词干(faccio、diciamo)。dare 的 dà 加重音,区别于介词 da。情态动词 potere、volere、dovere 后面直接跟不定式:devo andare。c'è / ci sono 表示「某处有」:c'è un drago。",
          en: "The commonest verbs are the most irregular: learn them whole (see the table). The h of ho, hai, ha, hanno is silent. Andare uses a v- stem in the singular and in loro (vado, vanno), an and- stem in noi and voi (andiamo). Fare and dire show a long stem in some persons (faccio, diciamo). Dare writes dà with an accent, unlike the preposition da. Potere, volere, dovere take a bare infinitive: devo andare. C'è / ci sono: there is / there are." },
  table: { cap: { zh: "十个高频动词", en: "Ten everyday verbs" },
    head: [{ zh: "动词", en: "Verb" }, { zh: "io · tu · lui", en: "io · tu · lui" }, { zh: "noi · voi · loro", en: "noi · voi · loro" }],
    rows: [["essere 是|essere (be)", "sono, sei, è", "siamo, siete, sono"],
           ["avere 有|avere (have)", "ho, hai, ha", "abbiamo, avete, hanno"],
           ["andare 去|andare (go)", "vado, vai, va", "andiamo, andate, vanno"],
           ["fare 做|fare (do)", "faccio, fai, fa", "facciamo, fate, fanno"],
           ["venire 来|venire (come)", "vengo, vieni, viene", "veniamo, venite, vengono"],
           ["stare 待|stare (stay)", "sto, stai, sta", "stiamo, state, stanno"],
           ["dire 说|dire (say)", "dico, dici, dice", "diciamo, dite, dicono"],
           ["potere 能|potere (can)", "posso, puoi, può", "possiamo, potete, possono"],
           ["volere 要|volere (want)", "voglio, vuoi, vuole", "vogliamo, volete, vogliono"],
           ["dovere 必须|dovere (must)", "devo, devi, deve", "dobbiamo, dovete, devono"]] },
  notes: { zh: "andare 由两个动词拼成:vado、vai、va、vanno 来自 vādere(走去),andiamo、andate 和不定式 andare 出自另一个来源有争议的词,一说是 ambulāre(行走)。fare、dire 是 facere、dīcere 的缩短形,长词干留在 faccio、dico、diciamo 里。avere 来自 habēre。拉丁语的 h 意大利语不发音,拼写也大多删去(homo → uomo),唯有 ho、hai、ha、hanno 保留,好和 o(或)、a(到)、anno(年)区分。",
          en: "Andare is two verbs stitched together: vado, vai, va, vanno come from Latin vādere, to go; andiamo, andate and the infinitive from another verb of debated origin, perhaps ambulāre, to walk. Fare and dire are shortened facere, dīcere; the long stems survive in faccio, dico, diciamo. Avere is habēre. Italian never sounds Latin h and mostly dropped it (homo → uomo); only ho, hai, ha, hanno keep it, to stand apart from o (or), a (to), anno (year)." },
  ex: [
    { q: { zh: "Gli Argonauti ___ in Colchide.(andare,阿尔戈英雄们去科尔基斯)", en: "Gli Argonauti ___ in Colchide. (andare — the Argonauts go to Colchis.)" }, opts: ["vanno", "andano", "vadono", "andono"], a: 0,
      why: { zh: "andare 的 loro 形式是 vanno,来自拉丁 vādere。andano 是按 -are 规则硬套的错误。", en: "The loro form of andare is vanno, from Latin vādere. Andano forces the regular -are pattern onto it." } },
    { q: { zh: "«Noi ___ una nave veloce», dice Giasone.(avere,伊阿宋说:我们有一艘快船)", en: "«Noi ___ una nave veloce», dice Giasone. (avere — we have a swift ship.)" }, opts: ["abbiamo", "aviamo", "hanno", "abbiate"], a: 0,
      why: { zh: "avere 的 noi 形式是 abbiamo。aviamo 是按规则推出来的错误;hanno 是「他们有」,abbiate 也不是 noi 的形式。", en: "The noi form of avere is abbiamo. Aviamo is a regularised error; hanno means they have, and abbiate is not a noi form either." } },
    { q: { zh: "Giasone ___ greco, di Iolco.(essere,伊阿宋是希腊人,来自伊奥尔科斯)", en: "Giasone ___ greco, di Iolco. (essere — Jason is Greek, from Iolcus.)" }, opts: ["è", "e", "ha", "sei"], a: 0,
      why: { zh: "essere 的第三人称单数是 è,必须带重音符号;不带重音的 e 是连词「和」。sei 是「你是」。", en: "The third singular of essere is è, with its accent; e without it is the conjunction and. Sei means you are." } },
    { q: { zh: "Giasone ___ aggiogare due tori che sputano fuoco.(dovere,伊阿宋必须给两头喷火的公牛套上轭)", en: "Giasone ___ aggiogare due tori che sputano fuoco. (dovere — Jason must yoke two fire-breathing bulls.)" }, opts: ["deve", "dove", "dova", "debe"], a: 0,
      why: { zh: "dovere 的第三人称单数是 deve,后面直接跟不定式 aggiogare。dove 是「哪里」,debe 是西班牙语。", en: "Dovere makes deve in the third singular, followed directly by the infinitive aggiogare. Dove means where, and debe is Spanish." } },
    { q: { zh: "国王埃厄忒斯问:«Che cosa ___ voi qui?»(fare)", en: "King Aeetes asks: «Che cosa ___ voi qui?» (fare)" }, opts: ["fate", "facete", "fatte", "fanno"], a: 0,
      why: { zh: "fare 的 voi 形式是很短的 fate;现在时里长词干 facc- 只出现在 faccio、facciamo。fanno 是 loro 的形式。", en: "The voi form of fare is the short fate; in the present the long stem facc- appears only in faccio and facciamo. Fanno is the loro form." } },
    { q: { zh: "Nel bosco di Ares ___ un drago.(阿瑞斯的圣林里有一条龙)", en: "Nel bosco di Ares ___ un drago. (In the grove of Ares there is a dragon.)" }, opts: ["c'è", "ci sono", "ce", "ci siamo"], a: 0,
      why: { zh: "drago 是单数,所以用 c'è(ci + è);ci sono 配复数。ce 没有撇号和重音,是另一个词。", en: "Drago is singular, so it is c'è (ci + è); ci sono goes with plurals. Ce, without apostrophe or accent, is a different word." } },
    { q: { zh: "哪一个形式是错的?", en: "Which form is wrong?" }, opts: ["voi dicete", "loro dicono", "io vengo", "io voglio"], a: 0,
      why: { zh: "dire 的 voi 形式是 dite,不是按长词干推出来的 dicete。dicono、vengo、voglio 都正确。", en: "The voi form of dire is dite, not dicete built on the long stem. Dicono, vengo and voglio are all correct." } },
    { q: { zh: "为什么 vado、vai、va 和 andiamo、andate 的词干完全不同?", en: "Why do vado, vai, va and andiamo, andate have different stems?" },
      opts: [{ zh: "它们出自两个不同的动词", en: "they come from two different verbs" }, { zh: "vado 其实是将来时", en: "vado is really a future tense" }, { zh: "andiamo 是中世纪借自西班牙语的", en: "andiamo was borrowed from Spanish in the Middle Ages" }, { zh: "是十九世纪的一次拼写改革造成的", en: "a nineteenth-century spelling reform caused it" }], a: 0,
      why: { zh: "vado、vai、va、vanno 来自 vādere,andiamo、andate 来自 andare(来源有争议)。英语 go 和 went 也是两个动词拼成的。", en: "Vado, vai, va, vanno come from vādere; andiamo and andate from andare, whose origin is debated. English go and went are likewise two verbs combined." } },
  ] },
]);

/* Fuga Mythica — Italian grammar road, stations 6–10 */
GRAM_ADD("it", [
{ id: "it_aggettivo", icon: "🎨",
  name: { zh: "形容词与 bello · 帕里斯的评判", en: "Adjectives and bello · The judgement of Paris" },
  scene: { zh: "不和女神厄里斯把一只金苹果扔进珀琉斯与忒提斯的婚宴,上面写着「献给最美的」。帕里斯要在三位女神之间作评判。阿佛洛狄忒许给他 la bella Elena(美丽的海伦)——un bel premio(一份美好的奖赏)。同一个 bello,放在名词前会像冠词一样变形:bel、bella、begli。",
           en: "Eris, goddess of strife, rolls a golden apple into the wedding feast of Peleus and Thetis, inscribed ‘for the fairest’. Paris must judge between three goddesses. Aphrodite promises him la bella Elena, beautiful Helen — un bel premio, a fine prize. Placed before a noun, bello changes its shape like the article: bel, bella, begli." },
  rule: { zh: "形容词与名词性数一致。第一类有四个词尾:rosso、rossa、rossi、rosse;第二类只有两个,阴阳同形:grande、grandi。阴阳混合时用阳性复数:Filemone e Bauci sono vecchi。形容词一般放名词后;少数放前放后意思不同:un grande uomo 是伟人,un uomo grande 是大个子。bello、buono 在名词前变形:bello 照定冠词变(bel、bello、bell'、bei、begli),buono 照不定冠词变(buon、buono、buona)。",
          en: "An adjective agrees with its noun in gender and number. Class one has four endings: rosso, rossa, rossi, rosse; class two has two, the same for both genders: grande, grandi. A mixed group takes the masculine plural: Filemone e Bauci sono vecchi. Most adjectives follow the noun; a few change meaning with position: un grande uomo, a great man; un uomo grande, a big man. Before a noun bello inflects like the article il/lo, buono like un/uno." },
  table: { cap: { zh: "bello 跟着定冠词变,buono 跟着不定冠词变", en: "bello follows the definite article, buono the indefinite" },
    head: [{ zh: "名词开头", en: "Noun begins with" }, { zh: "定冠词", en: "Def. art." }, { zh: "bello", en: "bello" }, { zh: "不定冠词", en: "Indef. art." }, { zh: "buono", en: "buono" }],
    rows: [["阳单 · 辅音|m. sg. · consonant", "il", "bel", "un", "buon"],
           ["阳单 · s+辅音、z、gn、ps|m. sg. · s + cons., z, gn, ps", "lo", "bello", "uno", "buono"],
           ["阳单 · 元音|m. sg. · vowel", "l'", "bell'", "un", "buon"],
           ["阴单 · 辅音|f. sg. · consonant", "la", "bella", "una", "buona"],
           ["阴单 · 元音|f. sg. · vowel", "l'", "bell' / bella", "un'", "buon' / buona"],
           ["阳复 · 辅音|m. pl. · consonant", "i", "bei", "—", "buoni"],
           ["阳复 · s+辅音、z、元音|m. pl. · s + cons., z, vowel", "gli", "begli", "—", "buoni"],
           ["阴复|f. pl.", "le", "belle", "—", "buone"]] },
  notes: { zh: "形容词的两类直接来自拉丁语:bonus, bona → buono, buona(第一、二变格法);fortis → forte(第三变格法,本就阴阳同形)。bello 来自拉丁口语 bellus「可爱的」,一般认为是 bonus 古形 duenos 的指小词——bello 和 buono 本是一家。bello、quello 和冠词的来源 ille 都带 -ll-,在名词前经历了同样的音变:辅音前缩短为 bel、quel、il,复数在元音前腭化为 begli、quegli、gli。",
          en: "The two adjective classes are Latin’s: bonus, bona gave buono, buona; third-declension fortis, alike in both genders, gave forte. Bello is colloquial Latin bellus, pretty, usually seen as a diminutive of duenos, old Latin for bonus — so bello and buono are kin. Bello, quello and the article (from ille) share -ll- and changed alike before nouns: shortened before consonants (bel, quel, il), palatalised in plurals before vowels (begli, quegli, gli)." },
  ex: [
    { q: { zh: "阿佛洛狄忒许给帕里斯一份奖赏:Afrodite promette a Paride un ___ premio.", en: "Aphrodite promises Paris a prize: Afrodite promette a Paride un ___ premio." }, opts: ["bel", "bello", "bell'", "bella"], a: 0,
      why: { zh: "premio 是阳性,以普通辅音 p 开头,这个位置冠词用 il,所以 bello 缩短为 bel。完整的 bello 只用在 s+辅音、z 等前面:un bello scudo。", en: "Premio is masculine and begins with a plain consonant, the il position, so bello shortens to bel. The full bello is kept for s + consonant, z and the like: un bello scudo." } },
    { q: { zh: "看,阿尔戈英雄们漂亮的盾牌:Ecco i ___ scudi degli Argonauti.", en: "Here are the Argonauts’ fine shields: Ecco i ___ scudi degli Argonauti." }, opts: ["begli", "bei", "belli", "bel"], a: 0,
      why: { zh: "scudi 以 s+辅音开头,是冠词用 gli 的位置,所以 bello 取 begli。冠词只看紧挨着的那个词:begli 以 b 开头,所以前面是 i——i begli scudi。", en: "Scudi begins with s + consonant, the gli position, so bello becomes begli. The article looks only at the next word: begli starts with b, hence i begli scudi." } },
    { q: { zh: "菲勒蒙和包喀斯是一对老夫妻:Filemone e Bauci sono ___.", en: "Philemon and Baucis are an old couple: Filemone e Bauci sono ___." }, opts: ["vecchi", "vecchie", "vecchio", "vecchia"], a: 0,
      why: { zh: "一男一女合在一起,形容词用阳性复数 vecchi。vecchie 只用于全是阴性的一组;vecchio、vecchia 是单数。", en: "A man and a woman together take the masculine plural, vecchi. Vecchie is only for an all-feminine group; vecchio and vecchia are singular." } },
    { q: { zh: "哪个形容词的阳性和阴性单数是同一个形式?", en: "Which adjective has one and the same form for masculine and feminine singular?" }, opts: ["grande", "rosso", "nuovo", "piccolo"], a: 0,
      why: { zh: "grande 属于第二类(-e / -i):il grande re、la grande regina。rosso、nuovo、piccolo 属于第一类,阴性要变成 -a。", en: "Grande belongs to the second class (-e / -i): il grande re, la grande regina. Rosso, nuovo and piccolo are first-class and take -a in the feminine." } },
    { q: { zh: "下面哪个搭配是错的?", en: "Which phrase is wrong?" }, opts: ["le Amazzoni forte", "le Amazzoni forti", "l'Amazzone forte", "gli eroi forti"], a: 0,
      why: { zh: "forte 属于第二类,复数是 forti,阴阳都一样。le Amazzoni 是复数,必须用 forti;把 forte 当成阴性复数是常见错误。", en: "Forte is a second-class adjective whose plural is forti for both genders. Le Amazzoni is plural and needs forti; using forte as a feminine plural is a common slip." } },
    { q: { zh: "说奥德修斯是 un grande uomo,意思是他是:", en: "Calling Odysseus un grande uomo means he is:" },
      opts: [{ zh: "一个伟大的人", en: "a great man" }, { zh: "一个身材高大的人", en: "a tall, big man" }, { zh: "一个年老的人", en: "an old man" }, { zh: "一个富有的人", en: "a rich man" }], a: 0,
      why: { zh: "grande 放在名词前是比喻义「伟大」;放在后面 un uomo grande 才是字面的「高大」。前置的形容词往往更主观、更抽象。", en: "Before the noun grande is figurative, great; after it, un uomo grande, it is literal, big or tall. A preposed adjective tends to be more subjective and abstract." } },
    { q: { zh: "门托耳是奥德修斯的好朋友:Mentore è un ___ amico di Ulisse.", en: "Mentor is a good friend of Odysseus: Mentore è un ___ amico di Ulisse." }, opts: ["buon", "buon'", "buono", "buona"], a: 0,
      why: { zh: "buono 跟着不定冠词走:un amico 没有撇号,所以是 buon amico。只有阴性才加撇号:un'amica、buon'amica。", en: "Buono follows the indefinite article: un amico has no apostrophe, so it is buon amico. Only the feminine elides with an apostrophe: un'amica, buon'amica." } },
    { q: { zh: "为什么 bello 在名词前会像定冠词一样变成 bel、bei、begli?", en: "Why does bello turn into bel, bei, begli before a noun, just like the article?" },
      opts: [{ zh: "它和冠词的来源 ille 一样带 -ll-,经历了同样的音变", en: "like ille, the source of il/lo, it has -ll- and went through the same sound changes" }, { zh: "bello 原本就是一个冠词", en: "bello was originally an article" }, { zh: "语法学家为了让形容词和冠词整齐对应而人为规定", en: "grammarians imposed it to make adjectives match the articles neatly" }, { zh: "这条规则是中世纪从法语 beau 借来的", en: "the rule was borrowed from French beau in the Middle Ages" }], a: 0,
      why: { zh: "冠词来自 ille,bello 来自 bellus,quello 来自 eccu(m) illum,三者都有 -ll-:辅音前缩短(il、bel、quel),复数在元音前腭化(gli、begli、quegli)。", en: "The article comes from ille, bello from bellus, quello from eccu(m) illum; all three have -ll-, reduced before consonants (il, bel, quel) and palatalised before vowels in the plural (gli, begli, quegli)." } },
  ] },

{ id: "it_passato", icon: "⚔️",
  name: { zh: "近过去时 · 伊卡洛斯坠海", en: "Passato prossimo · Icarus has fallen" },
  scene: { zh: "代达罗斯 ha fatto le ali(做好了翅膀),父子 sono partiti(出发了)。伊卡洛斯飞得太高,太阳 ha sciolto la cera(融化了蜡),他 è caduto in mare(坠海了)。「做」「融化」带宾语,用 avere;「出发」「坠落」是位移,用 essere。",
           en: "Daedalus ha fatto le ali, has made the wings, and father and son sono partiti, have set off. Icarus flies too high, the sun ha sciolto la cera, has melted the wax, and he è caduto in mare, has fallen into the sea. Making and melting take an object and use avere; setting off and falling are movements and use essere." },
  rule: { zh: "近过去时 = avere/essere 现在时 + 过去分词(-are → -ato,-ere → -uto,-ire → -ito;不规则的如 fatto、preso、visto)。及物动词和 parlare 等许多不及物动词用 avere;多数表示去向或状态变化的不及物动词(partire、cadere、nascere)及 essere、stare、自反动词用 essere。用 essere 时分词与主语性数一致:Arianna è partita;用 avere 时不变:Arianna ha parlato。",
          en: "The passato prossimo is the present of avere or essere + past participle (-are → -ato, -ere → -uto, -ire → -ito; irregular: fatto, preso, visto). Transitives and many intransitives like parlare take avere; most intransitives of going somewhere or changing state (partire, cadere, nascere), essere, stare and reflexives take essere. With essere the participle agrees with the subject: Arianna è partita; with avere it does not: Arianna ha parlato." },
  table: { cap: { zh: "过去分词与助动词", en: "Participles and auxiliaries" },
    head: [{ zh: "不定式", en: "Infinitive" }, { zh: "过去分词", en: "Participle" }, { zh: "助动词", en: "Auxiliary" }, { zh: "例句", en: "Example" }],
    rows: [["parlare", "parlato", "avere", "Arianna ha parlato con Teseo."],
           ["conoscere", "conosciuto", "avere", "Ulisse ha conosciuto Circe."],
           ["partire", "partito", "essere", "Teseo è partito da Atene."],
           ["cadere", "caduto", "essere", "Icaro è caduto in mare."],
           ["fare", "fatto", "avere", "Dedalo ha fatto le ali."],
           ["vedere", "visto", "avere", "Egeo ha visto la vela nera."],
           ["prendere", "preso", "avere", "Perseo ha preso la testa di Medusa."],
           ["vincere", "vinto", "avere", "Ulisse ha vinto la gara dell'arco."],
           ["nascere", "nato", "essere", "Atena è nata dalla testa di Zeus."],
           ["essere / stare", "stato", "essere", "Ulisse è stato un anno da Circe."]] },
  notes: { zh: "古典拉丁语的完成时是一个词:scrīpsī(我写了)。近过去时是罗马口语的新造:habeō epistulam scrīptam,本意是「我有一封写好的信」,分词是修饰宾语的形容词。后来 habeō 虚化为助动词,意思变成「我已经写了」。essere 这一支也有拉丁源头:异态动词的完成时本来就是 sum + 分词,nātus est → è nato,mortuus est → è morto,几乎原样保留。分词跟主语一致,正是它当年身为形容词的遗迹。古西班牙语也说 es nacido,后来才全部改用 haber。",
          en: "Classical Latin said I wrote in one word, scrīpsī. The passato prossimo arose in spoken Latin: habeō epistulam scrīptam, I have a letter written, the participle describing the object; then habeō faded into an auxiliary. The essere type is Latin too: deponents made their perfect with sum, and nātus est, mortuus est live on as è nato, è morto — agreement is the old adjective showing through. Old Spanish said es nacido too, before haber took over." },
  ex: [
    { q: { zh: "阿里阿德涅随忒修斯离开了克里特:Arianna ___ partita da Creta.", en: "Ariadne left Crete with Theseus: Arianna ___ partita da Creta." }, opts: ["è", "ha", "sono", "hanno"], a: 0,
      why: { zh: "partire 表示位移,用 essere;主语是单数第三人称,所以是 è。partita 的 -a 也透露了答案——只有 essere 才让分词跟主语一致。", en: "Partire is a verb of motion and takes essere; with a third-person singular subject that is è. The -a of partita gives it away too: only with essere does the participle agree with the subject." } },
    { q: { zh: "珀耳修斯拿走了美杜莎的头:Perseo ha ___ la testa di Medusa.", en: "Perseus took Medusa’s head: Perseo ha ___ la testa di Medusa." }, opts: ["preso", "prenduto", "prendito", "prendato"], a: 0,
      why: { zh: "prendere 的分词是不规则的 preso。按规则推出的 prenduto 是典型的过度类推;同类的还有 mettere → messo、vedere → visto。", en: "Prendere has the irregular participle preso. Prenduto is the classic over-regularisation; compare mettere → messo, vedere → visto." } },
    { q: { zh: "阿尔戈英雄们到达了科尔基斯:Gli Argonauti sono ___ in Colchide.", en: "The Argonauts reached Colchis: Gli Argonauti sono ___ in Colchide." }, opts: ["arrivati", "arrivato", "arrivate", "arrivata"], a: 0,
      why: { zh: "essere 做助动词时,分词要和主语一致:Argonauti 是阳性复数,所以是 arrivati。arrivato 是忘了一致的常见错误。", en: "With essere the participle agrees with the subject: Argonauti is masculine plural, so arrivati. Arrivato is the common slip of forgetting the agreement." } },
    { q: { zh: "为什么说 Ulisse ha visto il Ciclope,却说 Ulisse è tornato a Itaca?", en: "Why is it Ulisse ha visto il Ciclope, but Ulisse è tornato a Itaca?" },
      opts: [{ zh: "vedere 带直接宾语用 avere,tornare 表示位移用 essere", en: "vedere takes a direct object, so avere; tornare is motion, so essere" }, { zh: "不规则分词用 avere,规则分词用 essere", en: "irregular participles take avere, regular ones essere" }, { zh: "所有 -are 动词都用 essere", en: "all -are verbs take essere" }, { zh: "句子以地名结尾时一律要用 essere", en: "essere is required whenever the sentence ends with the name of a place" }], a: 0,
      why: { zh: "选助动词看动词的意义,不看分词规则与否,也不看变位类型:parlare 是 -are 动词,却用 avere(ho parlato)。", en: "The auxiliary depends on the verb’s meaning, not on whether the participle is regular or on the conjugation: parlare is an -are verb, yet ho parlato." } },
    { q: { zh: "下面哪一句是错的?", en: "Which sentence is wrong?" }, opts: ["Icaro ha caduto in mare.", "Icaro è caduto in mare.", "Dedalo ha costruito il labirinto.", "Dedalo ha fatto le ali."], a: 0,
      why: { zh: "cadere 是表示位移的不及物动词,要用 essere:Icaro è caduto。costruire、fare 带直接宾语,用 avere 是对的。", en: "Cadere is an intransitive verb of motion and needs essere: Icaro è caduto. Costruire and fare take a direct object, so avere is right." } },
    { q: { zh: "奥德修斯在喀耳刻那里待了一年:Ulisse ___ un anno da Circe.", en: "Odysseus stayed a year with Circe: Ulisse ___ un anno da Circe." }, opts: ["è stato", "ha stato", "è stata", "ha stata"], a: 0,
      why: { zh: "stare 和 essere 共用分词 stato,都用 essere 做助动词。ha stato 是照英语 has been 直译的错误;è stata 和阳性主语不一致。", en: "Stare and essere share the participle stato and both take essere. Ha stato copies English has been; è stata clashes with the masculine subject." } },
    { q: { zh: "佩涅洛佩等了奥德修斯二十年:Penelope ha ___ Ulisse per vent'anni.", en: "Penelope waited twenty years for Odysseus: Penelope ha ___ Ulisse per vent'anni." }, opts: ["aspettato", "aspettata", "aspettati", "aspettate"], a: 0,
      why: { zh: "用 avere 时,分词不跟主语变:主语 Penelope 虽是阴性,仍说 ha aspettato。aspettata 是把 essere 的一致规则错套到 avere 上。", en: "With avere the participle does not follow the subject: even with feminine Penelope it is ha aspettato. Aspettata wrongly applies the essere agreement rule to avere." } },
    { q: { zh: "ho scritto 这种说法最早来自拉丁口语的哪种结构?", en: "Ho scritto goes back to which spoken-Latin construction?" },
      opts: [{ zh: "habeō + 分词:「我有(一封)写好的(信)」", en: "habeō + participle: I have (a letter) written" }, { zh: "古典完成时 scrīpsī 的音变", en: "a sound change of the classical perfect scrīpsī" }, { zh: "sum scrīptus:「我被写了」", en: "sum scrīptus, I have been written" }, { zh: "从希腊语借来的完成时", en: "a perfect tense borrowed from Greek" }], a: 0,
      why: { zh: "habeō epistulam scrīptam 本义是拥有一件已完成的东西,后来 habeō 虚化为助动词。scrīpsī 也活了下来,变成了远过去时 scrissi。", en: "Habeō epistulam scrīptam first meant owning a finished thing; habeō then became an auxiliary. Scrīpsī survived too, as the passato remoto scrissi." } },
  ] },

{ id: "it_imperfetto", icon: "🕯️",
  name: { zh: "未完成过去时 · 佩涅洛佩的织机", en: "Imperfetto · Penelope’s loom" },
  scene: { zh: "奥德修斯久久未归。佩涅洛佩许诺为拉厄耳忒斯织完寿衣就改嫁。她白天 tesseva(织),夜里 disfaceva(拆),求婚者 aspettavano(干等):习惯、背景用未完成过去时。直到女仆告密,i Proci hanno scoperto il trucco(识破诡计):一次性事件用近过去时。",
           en: "With Odysseus long gone, Penelope promises the suitors she will choose one of them once she finishes a shroud for Laertes. By day she tesseva, wove; by night she disfaceva, unpicked; the suitors aspettavano, kept waiting. Habit and background take the imperfetto. Then a maid betrays her and i Proci hanno scoperto il trucco — a single event, in the passato prossimo." },
  rule: { zh: "去掉不定式的 -re,加 -vo、-vi、-va、-vamo、-vate、-vano:parlavo、credevo、dormivo。essere 不规则:ero、eri、era、eravamo、eravate、erano。fare、dire、bere 用较长的拉丁词干:facevo、dicevo、bevevo。它描写背景、状态(il mare era calmo)、过去的习惯和别的事发生时正在进行的动作;一次性完成的事件用近过去时:Mentre Arianna dormiva, Teseo è partito。",
          en: "Drop the -re of the infinitive and add -vo, -vi, -va, -vamo, -vate, -vano: parlavo, credevo, dormivo. Essere is irregular: ero, eri, era, eravamo, eravate, erano. Fare, dire, bere use a longer Latin stem: facevo, dicevo, bevevo. It paints background and states (il mare era calmo), past habits, and actions in progress when something else happened; a single completed event takes the passato prossimo: Mentre Arianna dormiva, Teseo è partito." },
  table: { cap: { zh: "parlare · dormire · essere · fare", en: "parlare · dormire · essere · fare" },
    head: [{ zh: "人称", en: "Person" }, { zh: "parlare", en: "parlare" }, { zh: "dormire", en: "dormire" }, { zh: "essere", en: "essere" }, { zh: "fare", en: "fare" }],
    rows: [["1 单 io|1 sg. io", "parlavo", "dormivo", "ero", "facevo"],
           ["2 单 tu|2 sg. tu", "parlavi", "dormivi", "eri", "facevi"],
           ["3 单 lui/lei|3 sg. lui/lei", "parlava", "dormiva", "era", "faceva"],
           ["1 复 noi|1 pl. noi", "parlavamo", "dormivamo", "eravamo", "facevamo"],
           ["2 复 voi|2 pl. voi", "parlavate", "dormivate", "eravate", "facevate"],
           ["3 复 loro|3 pl. loro", "parlavano", "dormivano", "erano", "facevano"]] },
  notes: { zh: "未完成过去时几乎原样来自拉丁语:amābat → amava,amābant → amavano,erat → era。第一人称本来也是 -a(amābam 的 -m 脱落了):但丁时代说 io amava,-vo 是后来照现在时 amo 的 -o 类推出来的,到十九世纪才成为标准。不定式 fare、dire、bere 是 facere、dīcere、bibere 的缩短形,未完成过去时却保留了完整的词干。术语 imperfetto 来自 imperfectum「未完成的」——动作没有画上句号。",
          en: "The imperfetto comes almost unchanged from Latin: amābat → amava, amābant → amavano, erat → era. The first person once ended in -a too, the -m of amābam having fallen: Dante’s Italian has io amava; -vo came later, by analogy with amo, standard only from the nineteenth century. Fare, dire, bere are shortened facere, dīcere, bibere, but the imperfetto keeps the full stems. The term is Latin imperfectum, unfinished — an action with no full stop." },
  ex: [
    { q: { zh: "fare 的未完成过去时,第一人称单数(io)是:", en: "The imperfetto of fare, first person singular (io):" }, opts: ["facevo", "favo", "farevo", "facivo"], a: 0,
      why: { zh: "fare 用拉丁语 facere 的完整词干 fac-:facevo。favo 是照现在时 fa 硬造的,farevo 是照不定式 far- 硬造的。", en: "Fare uses the full stem of Latin facere: facevo. Favo is built on the present fa, farevo on the infinitive — both wrong." } },
    { q: { zh: "奥德修斯睡着的时候,同伴们打开了风袋:Mentre Ulisse ___, i compagni hanno aperto l'otre dei venti.", en: "While Odysseus ___, his men opened the bag of winds: Mentre Ulisse ___, i compagni hanno aperto l'otre dei venti." }, opts: ["dormiva", "ha dormito", "dormivo", "dormava"], a: 0,
      why: { zh: "「睡着」是正在进行的背景,用未完成过去时 dormiva;「打开」是插进来的一次性事件,用近过去时。dormava 是把 -ire 动词错当成 -are 变位。", en: "Sleeping is the ongoing background, so imperfetto dormiva; opening the bag is the single event that breaks in, so passato prossimo. Dormava conjugates an -ire verb as if it were -are." } },
    { q: { zh: "奥德修斯进洞时,独眼巨人在外面放羊:Quando Ulisse è entrato nella grotta, Polifemo ___ fuori con le pecore.", en: "When Odysseus entered the cave, the Cyclops was out with his sheep: Quando Ulisse è entrato nella grotta, Polifemo ___ fuori con le pecore." }, opts: ["era", "è stato", "erava", "eri"], a: 0,
      why: { zh: "「在外面放羊」是奥德修斯进洞那一刻的背景状态,用 era。è stato 会把它说成一件已结束的事件;erava 是把 essere 当成规则动词。", en: "Being out with the sheep is the background state at the moment Odysseus entered: era. È stato would present it as a finished event; erava treats essere as regular." } },
    { q: { zh: "Di giorno Penelope tesseva, di notte disfaceva la tela。这里的未完成过去时表示:", en: "Di giorno Penelope tesseva, di notte disfaceva la tela. The imperfetto here expresses:" },
      opts: [{ zh: "过去反复发生的习惯", en: "a repeated habit in the past" }, { zh: "一次性完成的动作", en: "a single completed action" }, { zh: "将来的计划", en: "a plan for the future" }, { zh: "客气的请求", en: "a polite request" }], a: 0,
      why: { zh: "白天织、夜里拆,天天如此,是反复的习惯,所以用未完成过去时。一次性的事件——比如她最后被识破——才用近过去时。", en: "Weaving by day and unpicking by night, again and again, is a habit, hence the imperfetto. A single event, such as her being found out, takes the passato prossimo." } },
    { q: { zh: "忒修斯走进迷宫,杀死了牛头怪:Teseo ___ nel labirinto e ha ucciso il Minotauro.", en: "Theseus went into the labyrinth and killed the Minotaur: Teseo ___ nel labirinto e ha ucciso il Minotauro." }, opts: ["è entrato", "entrava", "ha entrato", "è entrata"], a: 0,
      why: { zh: "「进入」和「杀死」是先后完成的两个事件,都用近过去时;entrare 表示位移,助动词是 essere。entrava 会把「进入」变成背景,和后面的 ha ucciso 接不上。", en: "Entering and killing are successive completed events, both in the passato prossimo, and entrare, a verb of motion, takes essere. Entrava would turn the entering into background, which does not fit the ha ucciso that follows." } },
    { q: { zh: "下面哪个形式是错的?", en: "Which form is wrong?" }, opts: ["io dicivo", "io dicevo", "tu dicevi", "loro dicevano"], a: 0,
      why: { zh: "dire 虽然以 -ire 结尾,却来自拉丁语 dīcere,未完成过去时是 dic- + -evo:dicevo。dicivo 是把它当成 dormire 一类的常见错误。", en: "Dire ends in -ire but comes from Latin dīcere, so its imperfetto is dic- + -evo: dicevo. Dicivo treats it like dormire — a common mistake." } },
    { q: { zh: "每天晚上,波吕斐摩斯都喝自己羊群的奶:Ogni sera Polifemo ___ il latte delle sue pecore.", en: "Every evening Polyphemus drank the milk of his sheep: Ogni sera Polifemo ___ il latte delle sue pecore." }, opts: ["beveva", "berava", "bevava", "beviva"], a: 0,
      why: { zh: "bere 是 bibere 的缩短形,未完成过去时用完整词干 bev-:beveva;ogni sera 表示习惯。berava 是照不定式 ber- 硬造的。", en: "Bere is a shortened bibere, and the imperfetto uses the full stem bev-: beveva. Ogni sera marks a habit. Berava is built on the infinitive." } },
    { q: { zh: "为什么 facevo、dicevo、bevevo 的词干比不定式 fare、dire、bere 长?", en: "Why do facevo, dicevo, bevevo have a longer stem than fare, dire, bere?" },
      opts: [{ zh: "它们保留了拉丁语 facere、dīcere、bibere 的完整词干", en: "they keep the full stems of Latin facere, dīcere, bibere" }, { zh: "为了发音方便后加的连接音", en: "a linking sound was added for ease of speech" }, { zh: "借用了希腊语的未完成过去时词尾", en: "they borrowed the Greek imperfect ending" }, { zh: "是现在时 fa、dice 这些形式后来的音变", en: "they are later sound changes of the present-tense forms fa and dice" }], a: 0,
      why: { zh: "不定式 fare、dire、bere 是缩短形;完整的拉丁词干保留在未完成过去时里,也保留在 faccio、dico、bevo 等形式里。", en: "Fare, dire and bere are contracted infinitives; the full Latin stems survive in the imperfetto and in forms such as faccio, dico, bevo." } },
  ] },

{ id: "it_futuro", icon: "🔮",
  name: { zh: "将来时与条件式 · 德尔斐的神谕", en: "Future and conditional · The oracle at Delphi" },
  scene: { zh: "俄狄浦斯在德尔斐问:Vorrei sapere chi sono i miei genitori(我想知道父母是谁)。神谕不答,只预言:Ucciderai tuo padre e sposerai tua madre(你将杀父娶母)。将来时讲会发生的事;条件式 vorrei 表达愿望,让请求更客气。",
           en: "At Delphi Oedipus asks: Vorrei sapere chi sono i miei genitori, I would like to know who my parents are. The oracle does not answer but foretells: Ucciderai tuo padre e sposerai tua madre, you will kill your father and marry your mother. The future tells what will happen; the conditional vorrei voices a wish and makes a request polite." },
  rule: { zh: "将来时以不定式为底:-are 动词 a 变 e(parler-),-ere、-ire 去掉 -e,再加 -ò、-ai、-à、-emo、-ete、-anno;-care、-gare 加 h 保持硬音:cercherò。不规则词干单独记:sarò、avrò、andrò、farò、verrò、vorrò、potrò、dovrò、vedrò、berrò。条件式用同一词干加 -ei、-esti、-ebbe、-emmo、-este、-ebbero,表示客气和假设。将来时还能表示推测:sarà vero(大概是真的)。",
          en: "The future builds on the infinitive: -are verbs turn a into e (parler-), -ere and -ire drop their -e; then add -ò, -ai, -à, -emo, -ete, -anno, with h after c and g: cercherò. Learn the irregular stems: sarò, avrò, andrò, farò, verrò, vorrò, potrò, dovrò, vedrò, berrò. The conditional takes the same stem plus -ei, -esti, -ebbe, -emmo, -este, -ebbero for politeness and hypotheses. The future also guesses: sarà vero, it is probably true." },
  table: { cap: { zh: "将来时与条件式", en: "Future and conditional" },
    head: [{ zh: "人称", en: "Person" }, { zh: "parlare · 将来", en: "parlare · future" }, { zh: "essere · 将来", en: "essere · future" }, { zh: "parlare · 条件", en: "parlare · cond." }, { zh: "volere · 条件", en: "volere · cond." }],
    rows: [["1 单 io|1 sg. io", "parlerò", "sarò", "parlerei", "vorrei"],
           ["2 单 tu|2 sg. tu", "parlerai", "sarai", "parleresti", "vorresti"],
           ["3 单 lui/lei|3 sg. lui/lei", "parlerà", "sarà", "parlerebbe", "vorrebbe"],
           ["1 复 noi|1 pl. noi", "parleremo", "saremo", "parleremmo", "vorremmo"],
           ["2 复 voi|2 pl. voi", "parlerete", "sarete", "parlereste", "vorreste"],
           ["3 复 loro|3 pl. loro", "parleranno", "saranno", "parlerebbero", "vorrebbero"]] },
  notes: { zh: "拉丁语将来时 amābō 在口语里被短语 amāre habeō(本义「我得去爱」)取代,两词融合:amar-ho → amerò,所以词尾 -ò、-ai、-à、-anno 就是 avere 的 ho、hai、ha、hanno。条件式是不定式 + habēre 的完成时(俗拉丁语 *hebui,即 ebbi):amāre *hebui → amerei,*hebuit → amerebbe,词尾和 ebbi、ebbe 对应。法语 aimerais、西班牙语 amaría 却用未完成过去时 habēbam。",
          en: "Latin’s future amābō gave way in speech to amāre habeō, I have to love, and the two words fused: amar-ho → amerò. So the endings -ò, -ai, -à, -anno are simply ho, hai, ha, hanno. The conditional joins the infinitive to the perfect of habēre, Vulgar Latin *hebui, Italian ebbi: amāre *hebui → amerei, *hebuit → amerebbe, its endings matching ebbi and ebbe. French aimerais and Spanish amaría used the imperfect habēbam instead." },
  ex: [
    { q: { zh: "忒瑞西阿斯向奥德修斯预言:«___ a Itaca, ma senza compagni.»(你将回到伊萨卡,但没有同伴。)", en: "Tiresias prophesies to Odysseus: «___ a Itaca, ma senza compagni» — you will return to Ithaca, but without companions." }, opts: ["Tornerai", "Tornarai", "Tornerò", "Tornerei"], a: 0,
      why: { zh: "-are 动词的将来时要把 a 变成 e:torner- + -ai = tornerai。tornarai 忘了 a → e;tornerò 是第一人称;tornerei 是条件式。", en: "In the future, -are verbs change a to e: torner- + -ai, tornerai. Tornarai misses the change, tornerò is first person, tornerei is conditional." } },
    { q: { zh: "明天我们要去德尔斐求神谕:Domani noi ___ a Delfi dall'oracolo.", en: "Tomorrow we are off to the oracle at Delphi: Domani noi ___ a Delfi dall'oracolo." }, opts: ["andremo", "anderemo", "andaremo", "andremmo"], a: 0,
      why: { zh: "andare 的将来词干缩短为 andr-:andremo。anderemo 是硬套 a → e 的规则;andremmo(双 m)是条件式「我们会去」。", en: "Andare has the short future stem andr-: andremo. Anderemo applies the regular a → e; andremmo, with double m, is the conditional, we would go." } },
    { q: { zh: "代达罗斯将为伊卡洛斯做翅膀:Dedalo ___ le ali per Icaro.", en: "Daedalus will make wings for Icarus: Dedalo ___ le ali per Icaro." }, opts: ["farà", "ferà", "farerà", "facerà"], a: 0,
      why: { zh: "fare 不套 a → e 的规则,保持 far-:farò, farai, farà;dare、stare 也一样(darò、starò)。ferà 是把 -are 规则用过了头;facerà 错借了未完成过去时的词干。", en: "Fare keeps its a: farò, farai, farà, like darò and starò. Ferà overapplies the -are rule; facerà wrongly borrows the imperfetto stem." } },
    { q: { zh: "奥德修斯客气地向费埃克斯国王请求:«___ tornare a Itaca.»(我想回伊萨卡。)", en: "Odysseus politely asks the Phaeacian king: «___ tornare a Itaca» — I would like to go home to Ithaca." }, opts: ["Vorrei", "Volerei", "Vorrebbe", "Vorrò"], a: 0,
      why: { zh: "客气的「我想要」用条件式 vorrei。volerei 是按规则硬造的(volere 的词干是 vorr-);vorrebbe 是第三人称;vorrò 是将来时「我将会想要」。", en: "The polite I would like is the conditional vorrei. Volerei is over-regularised — the stem of volere is vorr-; vorrebbe is third person; vorrò is the future, I shall want." } },
    { q: { zh: "有人敲佩涅洛佩的门。——Sarà il mendicante. 这里的 sarà 表示:", en: "Someone knocks at Penelope’s door. — Sarà il mendicante. Here sarà expresses:" },
      opts: [{ zh: "对现在的推测:大概是那个乞丐", en: "a guess about now: it must be the beggar" }, { zh: "将来:他总有一天会变成乞丐", en: "the future: one day he will become a beggar" }, { zh: "命令:让他去当乞丐", en: "an order: let him be a beggar" }, { zh: "过去:那曾经是乞丐", en: "the past: it was the beggar" }], a: 0,
      why: { zh: "将来时常用来对现在的情况作推测:Sarà il mendicante =「大概是那个乞丐」。在佩涅洛佩的宫中,这个乞丐正是乔装的奥德修斯。", en: "The future often guesses about the present: Sarà il mendicante, it must be the beggar — who, in Penelope’s palace, is Odysseus in disguise." } },
    { q: { zh: "下面哪个将来时形式是错的?", en: "Which future form is wrong?" }, opts: ["io averò", "io avrò", "io sarò", "io andrò"], a: 0,
      why: { zh: "avere 的将来词干缩短为 avr-:avrò。averò 是按规则硬推出来的,同类错误还有 poterò(应为 potrò)、vederò(应为 vedrò)。", en: "Avere has the short stem avr-: avrò. Averò is over-regularised, like poterò for potrò or vederò for vedrò." } },
    { q: { zh: "阿尔戈英雄们将去科尔基斯寻找金羊毛:Gli Argonauti ___ il vello d'oro in Colchide.", en: "The Argonauts will seek the Golden Fleece in Colchis: Gli Argonauti ___ il vello d'oro in Colchide." }, opts: ["cercheranno", "cerceranno", "cercaranno", "cercherano"], a: 0,
      why: { zh: "-care 动词在 e 前加 h,保持 /k/ 的硬音:cercheranno。cerceranno 会读成 /tʃ/;cercaranno 忘了 a → e;cercherano 少了一个 n。", en: "Verbs in -care add h before e to keep the hard k sound: cercheranno. Cerceranno would be read with a ch sound, cercaranno misses a → e, and cercherano lacks one n." } },
    { q: { zh: "意大利语条件式 amerei、amerebbe 的来源是:", en: "The Italian conditional amerei, amerebbe comes from:" },
      opts: [{ zh: "不定式 + habēre 的完成时(*hebui,即 ebbi)", en: "the infinitive + the perfect of habēre (*hebui, Italian ebbi)" }, { zh: "不定式 + habēre 的未完成过去时 habēbam", en: "the infinitive + habēbam, the imperfect of habēre" }, { zh: "拉丁语的未完成虚拟式 amārem", en: "the Latin imperfect subjunctive amārem" }, { zh: "希腊语的祈愿式", en: "the Greek optative" }], a: 0,
      why: { zh: "amāre *hebui → amerei,amāre *hebuit → amerebbe,词尾和 ebbi、ebbe 对应。法语 aimerais、西班牙语 amaría 才是用 habēbam 构成的。", en: "Amāre *hebui gave amerei and amāre *hebuit amerebbe, matching ebbi and ebbe. It is French aimerais and Spanish amaría that are built on habēbam." } },
  ] },

{ id: "it_pronomi", icon: "🎯",
  name: { zh: "代词 · 潘多拉的罐子", en: "Pronouns · Pandora’s jar" },
  scene: { zh: "宙斯 le dà un vaso(给她一只罐子),叮嘱她不许打开。潘多拉还是 lo apre(把它打开了):ne escono tutti i mali(所有灾祸从里面飞出),只有希望 ci resta(留在了里面)。le、lo、ne、ci 这几个小词各自替代一整个短语,而且都站在动词前面。",
           en: "Zeus le dà un vaso — gives her a jar — and forbids her to open it. Pandora lo apre, opens it anyway: ne escono tutti i mali, out of it fly all the evils, and only Hope ci resta, stays in there. Le, lo, ne and ci each stand for a whole phrase, and each sits right before the verb." },
  rule: { zh: "直接宾语:lo(他、它)、la(她、它)、li、le(阳/阴性复数),单数遇元音常省作 l'。间接宾语:gli(给他)、le(给她)、Le(给您);mi、ti、ci、vi 兼作两者。代词放变位动词前(lo vedo),接在不定式、命令式后(vederlo、prendilo!);用情态动词时,两种位置都对:lo voglio vedere = voglio vederlo。ci 指那里(ci vado),ne 指其中(ne ho due)。近过去时里前置的 lo/la/li/le 使分词一致:le ho viste。",
          en: "Direct: lo (him, it), la (her, it), li and le (them, m./f.); lo, la often elide to l'. Indirect: gli (to him), le (to her), formal Le; mi, ti, ci, vi serve both. They precede a conjugated verb (lo vedo) but attach to an infinitive or imperative (vederlo, prendilo!); with modals, either order: lo voglio vedere = voglio vederlo. Ci means there (ci vado), ne of it, some (ne ho due). A preceding lo, la, li, le makes the participle agree: le ho viste." },
  table: { cap: { zh: "小代词替代整个短语", en: "Small pronouns stand for whole phrases" },
    head: [{ zh: "代词", en: "Pronoun" }, { zh: "替代什么", en: "Stands for" }, { zh: "例句", en: "Example" }],
    rows: [["lo / l'", { zh: "阳性单数直接宾语:他、它", en: "him, it (m. sg., direct)" }, "Il filo? Arianna lo dà a Teseo."],
           ["la / l'", { zh: "阴性单数直接宾语:她、它", en: "her, it (f. sg., direct)" }, "La testa di Medusa? Perseo la mette nella bisaccia."],
           ["li", { zh: "阳性复数直接宾语:他们", en: "them (m. pl., direct)" }, "I compagni? Polifemo li chiude nella grotta."],
           ["le", { zh: "阴性复数直接宾语:她们", en: "them (f. pl., direct)" }, "Le sirene? Ulisse le ascolta legato all'albero."],
           ["gli", { zh: "间接宾语:给他", en: "to him (indirect)" }, "Arianna gli dà il filo."],
           ["le", { zh: "间接宾语:给她", en: "to her (indirect)" }, "Zeus le dà un vaso."],
           ["Le / La", { zh: "尊称「您」:间接 Le,直接 La", en: "formal you: Le indirect, La direct" }, "Le do la mia parola."],
           ["mi / ti / ci / vi", { zh: "我、你、我们、你们(直接间接同形)", en: "me, you, us, you all (direct or indirect)" }, "Arianna mi aspetta all'ingresso."],
           ["ci", { zh: "那里、对那件事", en: "there, to it" }, "Itaca? Ulisse ci torna dopo vent'anni."],
           ["ne", { zh: "其中的、关于它、从那里", en: "of it, some of it, from there" }, "Sorelle? Medusa ne ha due."]] },
  notes: { zh: "宾语代词和定冠词同出一源——拉丁语指示词 ille「那个」:illum → lo,illam → la,复数 li、le 也出自它的复数形式;与格 illī → gli(li 在元音前腭化,和冠词 gli 一样)。所以 lo、la、le 既是冠词又是代词。ci 来自 ecce hīc「瞧,这里」,vi 来自 ibi「在那里」,ne 来自 inde「从那里」——所以 ne 表示「从中、其中」。古意大利语的代词通常不放在句首(如 vidilo「我看见了他」),命令式 prendilo 的后置常被认为与这种老语序有关。",
          en: "Object pronouns and the article share one source, Latin ille, that: illum → lo, illam → la, li and le from its plurals, and the dative illī → gli, palatalised like the article gli. Ci comes from ecce hīc, look, here; vi from ibi, there; ne from inde, from there — hence ne, of it, out of it. Old Italian avoided a clause-initial pronoun (vidilo, I saw him), and the trailing pronoun of the imperative prendilo is often linked to that old order." },
  ex: [
    { q: { zh: "线?阿里阿德涅把它交给忒修斯:Il filo? Arianna ___ dà a Teseo.", en: "The thread? Ariadne gives it to Theseus: Il filo? Arianna ___ dà a Teseo." }, opts: ["lo", "la", "gli", "li"], a: 0,
      why: { zh: "il filo 是阳性单数、直接宾语,用 lo。gli 是间接宾语「给他」,而这个角色已经由 a Teseo 担任了。", en: "Il filo is a masculine singular direct object: lo. Gli means to him, and that role is already filled by a Teseo." } },
    { q: { zh: "阿里阿德涅把线交给忒修斯:Arianna ___ dà il filo.", en: "Ariadne hands Theseus the thread: Arianna ___ dà il filo." }, opts: ["gli", "lo", "le", "la"], a: 0,
      why: { zh: "「给他」(忒修斯)是间接宾语,用 gli。le 做间接宾语是「给她」;lo 是直接宾语,而直接宾语已经是 il filo。", en: "To him, Theseus, is the indirect object: gli. Indirect le means to her, and lo is a direct object — but the direct object is already il filo." } },
    { q: { zh: "美杜莎:Perseo usa lo scudo per non ___ direttamente.(珀耳修斯用盾牌,以免直视她。)", en: "Medusa: Perseo usa lo scudo per non ___ direttamente — Perseus uses his shield so as not to look straight at her." }, opts: ["guardarla", "guardarlo", "guardarle", "guardargli"], a: 0,
      why: { zh: "guardare 带直接宾语,美杜莎是阴性单数,用 la,连写在不定式后面:guardar(e) + la = guardarla。lo 是阳性,le 是复数,gli 是间接宾语。", en: "Guardare takes a direct object, and Medusa is feminine singular, so la, attached to the infinitive: guardar(e) + la, guardarla. Lo is masculine, le plural, gli indirect." } },
    { q: { zh: "波吕斐摩斯有几只眼睛?Quanti occhi ha Polifemo? — ___ ha uno solo.", en: "How many eyes has Polyphemus? Quanti occhi ha Polifemo? — ___ ha uno solo." }, opts: ["Ne", "Li", "Lo", "Ci"], a: 0,
      why: { zh: "跟数量连用、表示「其中的几个」时要用 ne:ne ha uno =「(眼睛)他有一只」。li 指的是全部,不能再接数量。", en: "With a number, meaning so many of them, use ne: ne ha uno, he has one of them. Li would mean all of them and cannot take a number." } },
    { q: { zh: "忒勒马科斯,你去皮洛斯吗?Telemaco, vai a Pilo? — Sì, ___ vado.", en: "Telemachus, are you going to Pylos? Telemaco, vai a Pilo? — Sì, ___ vado." }, opts: ["ci", "ne", "lo", "gli"], a: 0,
      why: { zh: "ci 替代地点「到那里」:ci vado = vado a Pilo。ne 表示「从那里、其中」;lo、gli 指人或物,不能替代目的地。", en: "Ci replaces a place, there: ci vado = vado a Pilo. Ne means from there or of it, and lo and gli stand for persons or things, not for a destination." } },
    { q: { zh: "海妖?奥德修斯听到了她们的歌:Le sirene? Ulisse le ha ___.", en: "The Sirens? Odysseus heard them: Le sirene? Ulisse le ha ___." }, opts: ["sentite", "sentito", "sentiti", "sentita"], a: 0,
      why: { zh: "近过去时里,直接宾语代词 le 放在 avere 前面时,分词要和它一致:le ha sentite。sentito 是忘了一致;sentiti 是阳性,sentita 是单数。", en: "When the direct object pronoun le precedes avere, the participle agrees with it: le ha sentite. Sentito forgets the agreement; sentiti is masculine, sentita singular." } },
    { q: { zh: "下面哪一句是错的?", en: "Which sentence is wrong?" }, opts: ["Lo voglio vederlo.", "Lo voglio vedere.", "Voglio vederlo.", "Non lo vedo."], a: 0,
      why: { zh: "情态动词 + 不定式时,代词可以放在情态动词前(lo voglio vedere),也可以接在不定式后(voglio vederlo),两种都对;但只能出现一次,不能两头都放。", en: "With a modal plus infinitive the pronoun may go before the modal (lo voglio vedere) or onto the infinitive (voglio vederlo) — both are correct — but only once, never in both places." } },
    { q: { zh: "为什么代词 lo、la、le 和定冠词长得一模一样?", en: "Why do the pronouns lo, la, le look exactly like the articles?" },
      opts: [{ zh: "两者都来自拉丁语指示词 ille 的变格形式", en: "both come from case forms of the Latin demonstrative ille" }, { zh: "代词是中世纪书写时从冠词缩写出来的", en: "the pronouns were cut down from the articles in medieval writing" }, { zh: "纯属巧合", en: "it is pure coincidence" }, { zh: "来自希腊语冠词 ho、hē", en: "they come from the Greek article ho, hē" }], a: 0,
      why: { zh: "ille「那个」在名词前弱化成冠词,单独替代名词时成了代词:illum → lo,illam → la。法语 le、la、les 和西班牙语 lo、la 也是同样的分化。", en: "Ille, that, weakened into the article before a noun and became the pronoun when standing alone: illum → lo, illam → la. French le, la, les and Spanish lo, la split the same way." } },
  ] },
]);
