/* =====================================================
   FUGA MYTHICA — grammar road for the study language "es": ten stations,
   added to GRAMS through GRAM_ADD() (defined in grammar.js, loaded first).
   ===================================================== */
/* Fuga Mythica — Spanish grammar road, stations 1–5 */
GRAM_ADD("es", [
{ id: "es_genero", icon: "🛡️",
  name: { zh: "名词的性与冠词 · 剑与线", en: "Gender and articles · The sword and the thread" },
  scene: { zh: "阿里阿德涅把一团线(el hilo)交给忒修斯,有的版本里还有一把剑(la espada)。迷宫(el laberinto)深处等着米诺陶。西班牙语的每个名词都有性:阳性用冠词 el,阴性用 la。词尾往往透露名词的性,但也有几个著名的例外。",
           en: "Ariadne hands Theseus a ball of thread, el hilo — in some tellings a sword too, la espada. Deep in the labyrinth, el laberinto, the Minotaur waits. Every Spanish noun has a gender: masculine nouns take el, feminine nouns take la. The ending usually gives the gender away — but a few famous exceptions do not." },
  rule: { zh: "名词分阳性和阴性。-o 结尾多为阳性(el hilo),-a 结尾多为阴性(la isla);-ción、-sión、-dad、-tad、-tud 结尾一律阴性。希腊语来的 -ma 词多为阳性:el problema, el poema。例外:la mano, el día, el mapa。重读 a-/ha- 开头的阴性名词单数用 el,但仍是阴性:el agua fría, las aguas。a + el = al,de + el = del。中性 lo 加形容词表示抽象概念:lo bueno。",
          en: "Nouns in -o are mostly masculine (el hilo), nouns in -a mostly feminine (la isla); nouns in -ción, -sión, -dad, -tad and -tud are always feminine. Greek nouns in -ma are mostly masculine: el problema, el poema. Exceptions: la mano, el día, el mapa. A feminine noun with stressed a- or ha- takes el in the singular yet stays feminine: el agua fría, las aguas. A + el = al, de + el = del. Neuter lo plus an adjective makes an abstract idea: lo bueno." },
  table: { cap: { zh: "名词的性:看词尾,记例外", en: "Gender: read the ending, learn the exceptions" },
    head: [{ zh: "类型", en: "Type" }, { zh: "例子", en: "Examples" }, { zh: "性 / 说明", en: "Gender / note" }],
    rows: [["-o 结尾|ending in -o", "el hilo, el toro, el cielo", "阳性|masculine"],
           ["-a 结尾|ending in -a", "la espada, la isla, la luna", "阴性|feminine"],
           ["-ción / -sión", "la canción, la decisión", "阴性|feminine"],
           ["-dad / -tad / -tud", "la ciudad, la libertad, la virtud", "阴性|feminine"],
           ["希腊语 -ma|Greek -ma", "el problema, el tema, el poema", "阳性|masculine"],
           ["例外|exceptions", "la mano, el día, el mapa", { zh: "阴、阳、阳", en: "fem., masc., masc." }],
           ["重读 a- / ha-|stressed a- / ha-", "el agua fría, el hacha, las aguas", { zh: "阴性,单数冠词用 el", en: "feminine, el in the singular" }],
           ["缩合|contractions", "al laberinto, del mar", "a + el, de + el"],
           ["中性 lo|neuter lo", "lo bueno, lo difícil", { zh: "抽象概念,不接名词", en: "an abstract idea, never with a noun" }]] },
  notes: { zh: "西班牙语的冠词来自拉丁语指示词 ille, illa, illud(那个):ille → el,illa → la,中性 illud → lo。古西班牙语的阴性冠词有一个形式 ela,在元音前缩成 el,中世纪文本里常见 el espada;后来只在重读 a- 前保留——所以 el agua 的 el 其实是阴性冠词的化石。拉丁语的中性名词大多并入阳性,希腊语中性的 -ma 词(problēma、poiēma)也就成了阳性。「冠词」artículo 来自 articulus「小关节」。",
           en: "The articles come from the Latin demonstrative ille, illa, illud, ‘that’: el, la and neuter lo. Old Spanish had a feminine form ela, which shrank to el before a vowel — medieval texts write el espada. Today it survives only before stressed a-, so the el of el agua is a fossil of the feminine article. Latin neuters mostly joined the masculine, so Greek neuters in -ma (problēma, poiēma) became masculine. Artículo is Latin articulus, a little joint." },
  ex: [
    { q: { zh: "下面哪个名词是阳性?", en: "Which of these nouns is masculine?" }, opts: ["poema", "canción", "virtud", "mano"], a: 0,
      why: { zh: "poema 是希腊语中性的 -ma 词,在西班牙语里归入阳性:el poema。canción(-ción)和 virtud(-tud)按词尾是阴性;mano 虽以 -o 结尾,却是著名的阴性例外。", en: "Poema is a Greek neuter in -ma and became masculine: el poema. Canción (-ción) and virtud (-tud) are feminine by their endings, and mano, despite its -o, is the famous feminine exception." } },
    { q: { zh: "「冰冷的水」怎么说?", en: "How do you say ‘the cold water’?" }, opts: ["el agua fría", "la agua fría", "el agua frío", "la agua frío"], a: 0,
      why: { zh: "agua 以重读 a- 开头,单数冠词用 el,但它仍是阴性,形容词要用 fría。la agua 是最常见的错误;el agua frío 则误把 el 当成了阳性的标志。", en: "Agua begins with stressed a-, so its singular article is el, but the noun is still feminine and the adjective must be fría. La agua is the commonest slip; el agua frío wrongly reads el as a sign of masculine gender." } },
    { q: { zh: "Teseo llega ___ laberinto.(忒修斯来到迷宫。)", en: "Teseo llega ___ laberinto. — Theseus reaches the labyrinth." }, opts: ["al", "a el", "a la", "a lo"], a: 0,
      why: { zh: "介词 a 遇到冠词 el 要缩合成 al,不能写 a el laberinto。laberinto 是阳性,不用 la;中性的 lo 从不放在名词前。", en: "The preposition a fuses with the article el into al, so a el laberinto is wrong. Laberinto is masculine, so not la, and neuter lo never stands before a noun." } },
    { q: { zh: "la espada ___ héroe(英雄的剑)", en: "la espada ___ héroe — the hero's sword" }, opts: ["del", "de el", "de la", "al"], a: 0,
      why: { zh: "de + 冠词 el 要缩合为 del。héroe 是阳性,所以不是 de la。带重音的代词 él 则不缩合:la espada de él。", en: "De plus the article el contracts to del. Héroe is masculine, so de la is wrong. The stressed pronoun él, by contrast, stays apart: la espada de él." } },
    { q: { zh: "el agua 的复数是:", en: "The plural of el agua is:" }, opts: ["las aguas", "los aguas", "el aguas", "las agua"], a: 0,
      why: { zh: "el 只在单数、紧贴重读 a- 时出现;复数照常用阴性的 las:las aguas。los aguas 把 agua 误当成了阳性。", en: "El appears only in the singular, right before the stressed a-; the plural takes the ordinary feminine las: las aguas. Los aguas treats agua as masculine." } },
    { q: { zh: "Lo difícil es salir del laberinto. 这里的 lo 是:", en: "Lo difícil es salir del laberinto. What is lo here?" },
      opts: [{ zh: "中性冠词,把形容词变成抽象概念「难处」", en: "the neuter article: ‘the hard part’" }, { zh: "阳性定冠词,修饰省略的 laberinto", en: "the masculine article, standing for an omitted laberinto" }, { zh: "阴性冠词的古形", en: "an old form of the feminine article" }, { zh: "复数冠词", en: "a plural article" }], a: 0,
      why: { zh: "lo 后接形容词、不接名词,表示「…的东西、…之处」:lo bueno, lo difícil。阳性定冠词是 el,不会写成 lo。", en: "Lo takes an adjective, never a noun, and means ‘what is …, the … part’: lo bueno, lo difícil. The masculine article is el, never lo." } },
    { q: { zh: "哪一个是错的?", en: "Which one is wrong?" }, opts: ["la día", "el día", "la mano", "el problema"], a: 0,
      why: { zh: "día 虽以 -a 结尾,却是阳性:el día。它来自拉丁语 diēs(本来多用作阳性),不是希腊语 -ma 词,所以要单独记。", en: "Día ends in -a but is masculine: el día. It comes from Latin diēs, mostly masculine, and is not a Greek -ma word, so it has to be learned on its own." } },
    { q: { zh: "el agua 里的 el,历史上其实是:", en: "Historically, the el in el agua is:" },
      opts: [{ zh: "阴性冠词的古形(illa → ela → el)", en: "an old form of the feminine article (illa → ela → el)" }, { zh: "阳性冠词,因为 agua 原本是阳性", en: "the masculine article, because agua was once masculine" }, { zh: "中性冠词 lo 的变体", en: "a variant of the neuter lo" }, { zh: "借自阿拉伯语的冠词 al-", en: "the Arabic article al-, borrowed" }], a: 0,
      why: { zh: "阴性冠词 ela 在元音前失去 a,变成 el。拉丁语 aqua 是阴性,从来不是阳性;阿拉伯语 al- 只留在 algodón、alcalde 这类借词的开头。", en: "The feminine article ela lost its a before a vowel and became el. Latin aqua was feminine, never masculine; Arabic al- survives only at the start of loans such as algodón and alcalde." } },
  ] },

{ id: "es_plural", icon: "🌿",
  name: { zh: "复数与形容词 · 阿尔戈英雄", en: "Plurals and adjectives · The Argonauts" },
  scene: { zh: "伊阿宋召集了约五十位英雄(los héroes),乘阿尔戈号驶过一座座岛屿(las islas)和一道道海浪(las olas),去寻找金羊毛。一个变成许多:元音后加 -s,辅音后加 -es。形容词也跟着变:un gran héroe, unos héroes valientes。",
           en: "Jason gathers some fifty heroes, los héroes, and the Argo carries them past islands, las islas, and waves, las olas, in search of the Golden Fleece. One becomes many: add -s after a vowel and -es after a consonant. The adjectives follow: un gran héroe, unos héroes valientes." },
  rule: { zh: "元音后加 -s:islas;辅音后加 -es:dioses, ciudades;-z 变 -ces:luces。重音符号会变:canciones(去掉),jóvenes(加上)。末音节不重读的 -s 词不变:las crisis。形容词与名词性数一致;-e 和辅音结尾的大多只变数(fuertes, azules),国籍词和 -dor 词却有阴性:española, trabajadora。形容词多在名词后;bueno、malo 在阳性单数名词前变 buen、mal,grande 在单数名词前变 gran。",
          en: "Add -s after a vowel, -es after a consonant (dioses, ciudades); -z → -ces. Accents may shift: canciones, jóvenes. Nouns in unstressed -s stay: las crisis. Adjectives agree; most in -e or a consonant vary only in number (fuertes, azules), but nationality and -dor adjectives take -a: española, trabajadora. They usually follow the noun; bueno and malo shorten to buen and mal before a masculine singular noun, grande to gran before any singular one." },
  table: { cap: { zh: "复数构成与形容词一致", en: "Making plurals, and agreement" },
    head: [{ zh: "规则", en: "Rule" }, { zh: "单数", en: "Singular" }, { zh: "复数", en: "Plural" }],
    rows: [["元音 + -s|vowel + -s", "la isla, el héroe", "las islas, los héroes"],
           ["辅音 + -es|consonant + -es", "el dios, la ciudad, el rey", "los dioses, las ciudades, los reyes"],
           ["-z → -ces", "la luz, el pez", "las luces, los peces"],
           ["重音符号变化|accent shifts", "la canción, el joven", "las canciones, los jóvenes"],
           ["非重读 -s 不变|unstressed -s unchanged", "la crisis, el lunes", "las crisis, los lunes"],
           ["形容词 -o|adjectives in -o", "rápido, rápida", "rápidos, rápidas"],
           ["形容词 -e / 辅音|adjectives in -e / consonant", "fuerte, feliz, azul", "fuertes, felices, azules"],
           ["国籍形容词|nationality", "español, española", "españoles, españolas"],
           ["-dor 形容词|adjectives in -dor", "trabajador, trabajadora", "trabajadores, trabajadoras"],
           ["名词前短形|short forms before a noun", "un buen héroe, un gran rey", "unos buenos héroes, unos grandes reyes"]] },
  notes: { zh: "复数的 -s 来自拉丁语宾格复数:dominōs、rosās、rēgēs。口语拉丁语的格逐渐消失,西部罗曼语(西班牙语、葡萄牙语、法语)留下的是宾格形;意大利语丢了词尾 -s,阳性复数取自主格(lupī → lupi)。辅音后的 -es 是第三变格法的 -ēs:rēgēs → reyes,cīvitātēs → ciudades。luz 与 luces 的 z、c 读音相同,都承自拉丁语 lūcem、lūcēs 里的 c。plural 来自拉丁语 plūrālis,源于 plūs「更多」。",
           en: "The plural -s is the Latin accusative plural: dominōs, rosās, rēgēs. As spoken Latin lost its cases, western Romance (Spanish, Portuguese, French) kept the accusatives; Italian lost final -s and took masculine plurals from the nominative: lupī → lupi. After a consonant, -es is third-declension -ēs: rēgēs → reyes, cīvitātēs → ciudades. The z of luz and c of luces are one sound, Latin c: lūcem, lūcēs. Plural is Latin plūrālis, from plūs, more." },
  ex: [
    { q: { zh: "el dios(神)的复数是:", en: "The plural of el dios, the god:" }, opts: ["los dioses", "los dios", "los díoses", "las dioses"], a: 0,
      why: { zh: "dios 以辅音 -s 结尾,而它唯一的音节是重读的,所以加 -es:los dioses。只有末音节不重读的 -s 词(la crisis, el lunes)才保持不变。", en: "Dios ends in a consonant and its only syllable is stressed, so it takes -es: los dioses. Only words whose final -s syllable is unstressed, like la crisis and el lunes, stay unchanged." } },
    { q: { zh: "la luz(光)的复数是:", en: "The plural of la luz, the light:" }, opts: ["las luces", "las luzes", "las luz", "los luces"], a: 0,
      why: { zh: "-z 结尾加 -es 时,z 在 e 前改写成 c:luces、peces、felices。luzes 是最常见的拼写错误。z 和 c 在这里读音相同,都承自拉丁语 lūcem、lūcēs 里的 c。", en: "Before -es a final z is spelled c: luces, peces, felices. Luzes is the classic spelling mistake. Here z and c spell one sound, inherited from the c of Latin lūcem, lūcēs." } },
    { q: { zh: "下面哪个复数拼写正确?", en: "Which plural is spelled correctly?" }, opts: ["los jóvenes", "las canciónes", "los jovenes", "las cancións"], a: 0,
      why: { zh: "joven 重音在 jo-,加 -es 后变成倒数第三音节重读,必须标重音:jóvenes。canción 正相反:canciones 的重音落在倒数第二音节,词又以 -s 结尾,所以去掉重音符号。", en: "Joven is stressed on jo-; with -es that becomes the third syllable from the end, which needs a written accent: jóvenes. Canción is the opposite: canciones is stressed on the next-to-last syllable and ends in -s, so the accent goes." } },
    { q: { zh: "la crisis 的复数是:", en: "The plural of la crisis:" }, opts: ["las crisis", "las crisises", "los crisis", "las crises"], a: 0,
      why: { zh: "crisis 重音在 cri-,末音节 -sis 不重读,所以复数不变,只换冠词:las crisis。同理 el lunes → los lunes。crises 是英语的复数。", en: "Crisis is stressed on cri-, so its final syllable is unstressed and the plural is unchanged; only the article shows it: las crisis. Likewise el lunes, los lunes. Crises is the English plural." } },
    { q: { zh: "las olas ___(蓝色的)", en: "las olas ___ — the blue waves" }, opts: ["azules", "azulas", "azul", "azuls"], a: 0,
      why: { zh: "azul 以辅音结尾,阴阳同形,只变数:辅音后加 -es。azulas 是把 -o/-a 形容词的规则套错了地方。", en: "Azul ends in a consonant, so it has one form for both genders and changes only for number, adding -es. Azulas wrongly applies the -o/-a pattern." } },
    { q: { zh: "las islas ___(西班牙的)", en: "las islas ___ — the Spanish islands" }, opts: ["españolas", "españoles", "español", "españolos"], a: 0,
      why: { zh: "国籍形容词即使以辅音结尾,也有阴性形 -a:español, española, españolas。españoles 是阳性复数,和 islas 不一致。", en: "Nationality adjectives take a feminine -a even when they end in a consonant: español, española, españolas. Españoles is masculine plural and clashes with islas." } },
    { q: { zh: "「一位好英雄」怎么说?", en: "How do you say ‘a good hero’?" }, opts: ["un buen héroe", "un bueno héroe", "una buena héroe", "un héroe buen"], a: 0,
      why: { zh: "bueno 放在阳性单数名词前要缩成 buen;放在名词后则用全形:un héroe bueno。un héroe buen 把短形放错了位置;héroe 是阳性,不用 una。", en: "Before a masculine singular noun bueno shortens to buen; after the noun it keeps its full form: un héroe bueno. Un héroe buen puts the short form in the wrong place, and héroe is masculine, so not una." } },
    { q: { zh: "西班牙语复数的 -s 来自拉丁语的:", en: "The Spanish plural -s comes from the Latin:" },
      opts: [{ zh: "宾格复数(-ōs, -ās, -ēs)", en: "accusative plural (-ōs, -ās, -ēs)" }, { zh: "主格复数(-ī, -ae)", en: "nominative plural (-ī, -ae)" }, { zh: "属格复数(-ōrum, -ārum, -um)", en: "genitive plural (-ōrum, -ārum, -um)" }, { zh: "与格复数(-īs)", en: "dative plural (-īs)" }], a: 0,
      why: { zh: "西部罗曼语保留的是宾格形:lupōs → lobos,rosās → rosas。意大利语的阳性复数则取自主格:lupī → lupi。", en: "Western Romance kept the accusative: lupōs → lobos, rosās → rosas. Italian took its masculine plurals from the nominative instead: lupī → lupi." } },
  ] },

{ id: "es_serestar", icon: "⚖️",
  name: { zh: "两个「是」· 迷宫中的忒修斯", en: "Ser and estar · Theseus in the maze" },
  scene: { zh: "忒修斯是雅典人(es de Atenas),生性勇敢(es valiente)。此刻他在迷宫里(está en el laberinto),很累(está cansado)。迷宫里有一头怪物(hay un monstruo)。西班牙语有两个「是」:ser 说他是什么,estar 说他在哪里、怎么样。",
           en: "Theseus is from Athens, es de Atenas, and brave by nature, es valiente. Right now he is in the labyrinth, está en el laberinto, and tired, está cansado. There is a monster in there: hay un monstruo. Spanish has two verbs for ‘to be’: ser says what someone is; estar says where and how they are." },
  rule: { zh: "ser 说身份、职业、来源、材料、时间和本质:Orfeo es poeta, la espada es de hierro;事件的地点也用 ser:la boda es en el palacio。estar 说位置、暂时状态和进行中的动作:está en el laberinto, está buscando la salida。有些形容词换动词就换意思:es listo 聪明,está listo 准备好。新提到的事物用 hay:hay un monstruo;已知的那一个用 estar。",
          en: "Ser gives identity, profession, origin, material, time and nature: Orfeo es poeta, la espada es de hierro; also where an event is held: la boda es en el palacio. Estar gives location, temporary states and actions in progress: está en el laberinto, está buscando la salida. Some adjectives shift meaning: es listo, clever; está listo, ready. A thing mentioned for the first time takes hay: hay un monstruo; a known one takes estar." },
  table: { cap: { zh: "ser 与 estar:现在时与用法", en: "Ser and estar: present tense and uses" },
    head: [{ zh: "人称", en: "Person" }, { zh: "ser", en: "ser" }, { zh: "estar", en: "estar" }],
    rows: [["yo", "soy", "estoy"],
           ["tú", "eres", "estás"],
           ["él / ella / usted", "es", "está"],
           ["nosotros", "somos", "estamos"],
           ["vosotros", "sois", "estáis"],
           ["ellos / ustedes", "son", "están"],
           ["用途|use", { zh: "身份、来源、材料、职业、时间、本质、事件地点", en: "identity, origin, material, profession, time, nature, where an event is held" }, { zh: "位置、暂时状态、进行中的动作", en: "location, temporary state, action in progress" }],
           ["例句|example", "Teseo es de Atenas.", "Teseo está en el laberinto."],
           ["形容词|adjectives", { zh: "es listo 聪明 · es aburrido 乏味", en: "es listo clever · es aburrido boring" }, { zh: "está listo 准备好了 · está aburrido 觉得无聊", en: "está listo ready · está aburrido bored" }]] },
  notes: { zh: "ser 由两个拉丁语动词合成:soy、es、somos、son 来自 esse(是),eres 甚至来自 esse 的将来时 eris;不定式 ser 和虚拟式 sea 则来自 sedēre(坐):sedēre → seer → ser。estar 来自 stāre(站立),词首 s + 辅音前加了 e-,和 spatha → espada 一样。「站在某处」自然引出「位于、处于某种状态」。hay 是 ha(有)加古副词 y(那里,来自 ibī);soy、estoy 末尾的 -y 是否也是这个 y,存疑。",
           en: "Ser fuses two Latin verbs: soy, es, somos, son come from esse, eres even from its future eris, ‘you will be’; the infinitive ser and subjunctive sea from sedēre, to sit (sedēre → seer → ser). Estar is stāre, to stand, with the e- Spanish adds before s + consonant (spatha → espada); standing somewhere shades into being there, or being in a state. Hay is ha, has, plus old y, there (from ibī); whether soy and estoy end in that same y is disputed." },
  ex: [
    { q: { zh: "Teseo ___ buscando la salida.(忒修斯正在找出口。)", en: "Teseo ___ buscando la salida. — Theseus is looking for the way out." }, opts: ["está", "es", "hay", "estás"], a: 0,
      why: { zh: "正在进行的动作用 estar + 副动词:está buscando。ser 不和副动词连用;estás 是第二人称「你」。", en: "An action in progress is estar plus the gerund: está buscando. Ser never combines with the gerund, and estás is the second person, you." } },
    { q: { zh: "Teseo ___ de Atenas.(忒修斯是雅典人。)", en: "Teseo ___ de Atenas. — Theseus is from Athens." }, opts: ["es", "está", "hay", "eres"], a: 0,
      why: { zh: "来源属于身份,用 ser:es de Atenas。está de Atenas 是常见错误——来源不是暂时状态。eres 是第二人称「你是」。", en: "Origin is part of identity, so ser: es de Atenas. Está de Atenas is a common slip — where you come from is not a passing state. Eres is the second person, you are." } },
    { q: { zh: "La boda de Perseo y Andrómeda ___ en el palacio de Cefeo.(婚礼在刻甫斯的王宫举行。)", en: "La boda de Perseo y Andrómeda ___ en el palacio de Cefeo. — The wedding is held in Cepheus's palace." }, opts: ["es", "está", "hay", "son"], a: 0,
      why: { zh: "事件(婚礼、宴会、比赛)在哪里「举行」用 ser,不用 estar:la boda es en el palacio。estar 只给人和物定位。", en: "Where an event — a wedding, a feast, a contest — takes place is ser, not estar: la boda es en el palacio. Estar locates people and things." } },
    { q: { zh: "___ un monstruo en el laberinto.(迷宫里有一头怪物。)", en: "___ un monstruo en el laberinto. — There is a monster in the labyrinth." }, opts: ["Hay", "Está", "Es", "Son"], a: 0,
      why: { zh: "第一次提到、不确定的事物用 hay(有):hay un monstruo。说已知的那一个在哪里,才用 estar:el Minotauro está en el centro。", en: "Something mentioned for the first time, with un, takes hay, there is: hay un monstruo. Estar locates a known thing: el Minotauro está en el centro." } },
    { q: { zh: "Nosotros ___ en la isla de Naxos.(我们在纳克索斯岛上。)", en: "Nosotros ___ en la isla de Naxos. — We are on the island of Naxos." }, opts: ["estamos", "somos", "estáis", "están"], a: 0,
      why: { zh: "位置用 estar,nosotros 对应 estamos。somos 是 ser 的形,不能表示位置;estáis 配 vosotros,están 配 ellos 或 ustedes。", en: "Location calls for estar, and nosotros takes estamos. Somos belongs to ser and cannot locate; estáis goes with vosotros and están with ellos or ustedes." } },
    { q: { zh: "Ariadna está lista. 的意思是:", en: "Ariadna está lista means:" },
      opts: [{ zh: "阿里阿德涅准备好了", en: "Ariadne is ready" }, { zh: "阿里阿德涅很聪明", en: "Ariadne is clever" }, { zh: "阿里阿德涅很乏味", en: "Ariadne is boring" }, { zh: "阿里阿德涅在迷宫里", en: "Ariadne is in the labyrinth" }], a: 0,
      why: { zh: "listo 跟 estar 是「准备好了」,跟 ser 才是「聪明」:Ariadna es lista。动词一换,意思就换。", en: "With estar, listo means ready; with ser it means clever: Ariadna es lista. Change the verb and the meaning changes." } },
    { q: { zh: "哪一句是错的?", en: "Which sentence is wrong?" }, opts: ["Penélope es en Ítaca.", "Penélope está en Ítaca.", "Penélope es paciente.", "Penélope está triste."], a: 0,
      why: { zh: "人在某地用 estar:Penélope está en Ítaca。es paciente 说她的本性,está triste 说她此刻的心情,都对。", en: "A person's location takes estar: Penélope está en Ítaca. Es paciente states her nature and está triste her present mood; both are right." } },
    { q: { zh: "estar 来自哪个拉丁语动词?", en: "Which Latin verb does estar come from?" },
      opts: [{ zh: "stāre(站立)", en: "stāre, to stand" }, { zh: "esse(是)", en: "esse, to be" }, { zh: "sedēre(坐)", en: "sedēre, to sit" }, { zh: "habēre(拥有)", en: "habēre, to have" }], a: 0,
      why: { zh: "stāre → estar,词首加了 e-。esse 和 sedēre 合起来成了 ser;habēre 变成了 haber,hay 就出自它。", en: "Stāre became estar with a prothetic e-. Esse and sedēre merged into ser, and habēre became haber, the source of hay." } },
  ] },

{ id: "es_presente", icon: "🔥",
  name: { zh: "现在时 · 普罗米修斯的火", en: "Present tense · Prometheus's fire" },
  scene: { zh: "普罗米修斯从众神那里盗来火种,藏在一根茴香秆里带给人类。从此人们围着火生活(viven)、吃饭(comen)、交谈(hablan)。西班牙语的规则动词按不定式分三类:-ar、-er、-ir。去掉不定式词尾,换上表示人称的词尾,就得到现在时。",
           en: "Prometheus steals fire from the gods, hides it in a fennel stalk and brings it to mortals. From then on people live, eat and talk around the fire: viven, comen, hablan. Regular Spanish verbs fall into three groups by their infinitive, -ar, -er and -ir. Drop the infinitive ending, add the ending for the person, and you have the present." },
  rule: { zh: "-ar(hablar):-o, -as, -a, -amos, -áis, -an。-er(comer):-o, -es, -e, -emos, -éis, -en。-ir(vivir):-o, -es, -e, -imos, -ís, -en,与 -er 只差 nosotros、vosotros。主语代词通常省略:hablo 就是「我说」。tú 是熟人间的「你」,尊称 usted 配第三人称动词。复数在西班牙分 vosotros(熟)和 ustedes(尊),拉丁美洲都用 ustedes。",
          en: "-ar (hablar): -o, -as, -a, -amos, -áis, -an. -er (comer): -o, -es, -e, -emos, -éis, -en. -ir (vivir): -o, -es, -e, -imos, -ís, -en — unlike -er only in nosotros and vosotros. The ending names the person, so pronouns are usually dropped: hablo, I speak. Tú is the familiar you; polite usted takes the third person: ¿Habla usted griego? Spain has plural vosotros (familiar) and ustedes (polite); Latin America uses ustedes for both." },
  table: { cap: { zh: "三类规则动词的现在时", en: "The present of the three regular conjugations" },
    head: [{ zh: "人称", en: "Person" }, { zh: "hablar 说", en: "hablar, speak" }, { zh: "comer 吃", en: "comer, eat" }, { zh: "vivir 生活", en: "vivir, live" }],
    rows: [["yo", "hablo", "como", "vivo"],
           ["tú", "hablas", "comes", "vives"],
           ["él / ella / usted", "habla", "come", "vive"],
           ["nosotros / nosotras", "hablamos", "comemos", "vivimos"],
           ["vosotros / vosotras", "habláis", "coméis", "vivís"],
           ["ellos / ellas / ustedes", "hablan", "comen", "viven"],
           ["拉丁语来源|from Latin", "fābulārī", "comedere", "vīvere"]] },
  notes: { zh: "这些词尾几乎原样承自拉丁语:amō, amās, amat, amāmus, amātis, amant → amo, amas, ama, amamos, amáis, aman,只丢了 -t;-áis 经过古西语 -ades。usted 来自 vuestra merced「阁下的恩典」,本是第三人称名词短语,所以动词用第三人称。nosotros、vosotros 是 nos、vos 加 otros「别人」。hablar 来自 fābulārī「闲谈」(fābula「故事」),词首 f- 变成了不发音的 h-。",
           en: "These endings are Latin almost unchanged: amō, amās, amat, amāmus, amātis, amant became amo, amas, ama, amamos, amáis, aman, losing only the final -t; -áis passed through Old Spanish -ades. Usted is vuestra merced, ‘your grace’, a third-person noun phrase, so its verb is still third person. Nosotros and vosotros are nos and vos plus otros, others. Hablar is fābulārī, to chat (from fābula, a tale), with Castilian f- turned into silent h-." },
  ex: [
    { q: { zh: "Nosotros ___ en Ítaca.(vivir)", en: "Nosotros ___ en Ítaca. (vivir)" }, opts: ["vivimos", "vivemos", "vivís", "viven"], a: 0,
      why: { zh: "-ir 动词的 nosotros 形以 -imos 结尾:vivimos。vivemos 把 -er 的词尾套到了 -ir 动词上——两类动词正是在这里分开的。", en: "The nosotros form of an -ir verb ends in -imos: vivimos. Vivemos borrows the -er ending, and this is exactly where the two classes part." } },
    { q: { zh: "Penélope ___ un sudario.(tejer 织)", en: "Penélope ___ un sudario. (tejer, to weave)" }, opts: ["teje", "teja", "tejes", "tejen"], a: 0,
      why: { zh: "-er 动词第三人称单数以 -e 结尾:teje。teja 是把 -ar 动词的词尾 -a 用错了;tejes 是「你」,tejen 是「他们」。", en: "An -er verb's third person singular ends in -e: teje. Teja wrongly uses the -ar ending; tejes is you and tejen they." } },
    { q: { zh: "Vosotros ___ con los dioses.(hablar)", en: "Vosotros ___ con los dioses. (hablar)" }, opts: ["habláis", "hablais", "hablaís", "hablan"], a: 0,
      why: { zh: "vosotros 的词尾是 -áis,重音落在 á 上,必须标重音符号。hablan 是 ellos 或 ustedes 的形,不能配 vosotros。", en: "The vosotros ending is -áis, stressed on the á, which must carry the accent. Hablan belongs to ellos or ustedes, never to vosotros." } },
    { q: { zh: "¿___ usted griego?(您说希腊语吗?)", en: "¿___ usted griego? — Do you speak Greek? (polite)" }, opts: ["Habla", "Hablas", "Hablo", "Habláis"], a: 0,
      why: { zh: "usted 意思是「您」,动词却用第三人称:habla。hablas 是 tú 的形,不能和 usted 混用。", en: "Usted means you but takes a third-person verb: habla. Hablas is the tú form and cannot go with usted." } },
    { q: { zh: "Vivo en Creta. 这句话的主语是谁?", en: "Vivo en Creta. Who is the subject?" },
      opts: [{ zh: "我——词尾 -o 已经说明", en: "I — the ending -o says so" }, { zh: "他——第三人称", en: "he — third person" }, { zh: "你——第二人称", en: "you — second person" }, { zh: "没有主语,句子不完整", en: "there is none; the sentence is incomplete" }], a: 0,
      why: { zh: "西班牙语把人称写在词尾里,-o 就是「我」,所以 yo 通常省略。说 Yo vivo en Creta 是在强调「是我」。", en: "Spanish writes the person into the ending; -o means I, so yo is usually left out. Yo vivo en Creta stresses that it is I." } },
    { q: { zh: "Ustedes ___ con los argonautas.(comer)", en: "Ustedes ___ con los argonautas. (comer)" }, opts: ["comen", "come", "comes", "comemos"], a: 0,
      why: { zh: "ustedes 是 usted 的复数,配第三人称复数:comen。come 是单数 usted 的形;comes 是 tú 的形。", en: "Ustedes is the plural of usted and takes the third person plural: comen. Come is the singular usted form, and comes the tú form." } },
    { q: { zh: "-er 动词和 -ir 动词的现在时,只在哪两个人称上不同?", en: "In the present, -er and -ir verbs differ only in which two persons?" },
      opts: [{ zh: "nosotros 和 vosotros", en: "nosotros and vosotros" }, { zh: "yo 和 tú", en: "yo and tú" }, { zh: "él 和 ellos", en: "él and ellos / ellas" }, { zh: "tú 和 usted", en: "familiar tú and polite usted" }], a: 0,
      why: { zh: "comemos / vivimos,coméis / vivís;其余四个人称 -er 和 -ir 完全一样:como / vivo, comes / vives……", en: "Comemos and vivimos, coméis and vivís; in the other four persons -er and -ir are identical: como / vivo, comes / vives …" } },
    { q: { zh: "usted 为什么配第三人称动词?", en: "Why does usted take a third-person verb?" },
      opts: [{ zh: "它来自 vuestra merced「阁下的恩典」,本是第三人称名词短语", en: "from vuestra merced, ‘your grace’, a third-person phrase" }, { zh: "因为它原本是复数,和今天的 vosotros 一样", en: "because it was originally a plural form, like vosotros today" }, { zh: "因为它来自拉丁语 ille「他、那个」", en: "because it comes from Latin ille, ‘he, that one’" }, { zh: "因为它只是 tú 磨损后的古形", en: "because it is simply an old, worn-down form of tú" }], a: 0,
      why: { zh: "vuestra merced 一路磨损成 vusted,再成 usted。「阁下的恩典想要……」动词自然是第三人称,短语缩短后语法照旧。", en: "Vuestra merced wore down to vusted and then usted. ‘Your grace wishes …’ naturally takes a third-person verb, and the grammar stayed when the phrase shrank." } },
  ] },

{ id: "es_diptongo", icon: "🌳",
  name: { zh: "词干变化 · 俄耳甫斯回头", en: "Stem changes · Orpheus looks back" },
  scene: { zh: "俄耳甫斯想要(quiere)从冥府带回欧律狄刻。冥王答应了:「你可以(puedes)带她走,但不许回头。」他一路想着(piensa)她,终于忍不住回头,欧律狄刻又回到(vuelve)了阴影里。quiere、puedes、piensa、vuelve:重读的词干元音裂成了两个。",
           en: "Orpheus wants, quiere, to lead Eurydice back from the underworld. Hades agrees: ‘You can, puedes, take her — but do not look back.’ He thinks, piensa, of her all the way up, turns at last, and she returns, vuelve, to the shades. Quiere, puedes, piensa, vuelve: the stressed stem vowel has split in two." },
  rule: { zh: "许多动词的词干元音重读时变成二合元音:e → ie(quiero, pienso),o → ue(puedo, duermo),jugar 是 u → ue(juego)。一些 -ir 动词 e → i:pido, sirvo。nosotros、vosotros 重音在词尾,词干不重读,所以不变:queremos, podemos, pedimos——变化的形连成一只「靴子」。词族同理:puerta / portal, tierra / terrestre, muerte / mortal。",
          en: "Many verbs turn a stressed stem vowel into a diphthong: e → ie (quiero, pienso), o → ue (puedo, duermo, vuelvo), and jugar alone u → ue (juego). Some -ir verbs change e → i: pido, sirvo, repito. In nosotros and vosotros the stress is on the ending, so the stem stays: queremos, podemos, pedimos — the changed forms make a boot. Word families alternate too: puerta / portal, tierra / terrestre, muerte / mortal." },
  table: { cap: { zh: "重读就裂变,不重读就保持", en: "Stressed, it splits; unstressed, it stays" },
    head: [{ zh: "变化", en: "Change" }, { zh: "词 / 意思", en: "Word / meaning" }, { zh: "重读词干", en: "Stressed stem" }, { zh: "不重读词干", en: "Unstressed stem" }],
    rows: [["e → ie", "querer", "quiero, quieres, quieren", "queremos, queréis"],
           ["o → ue", "poder", "puedo, puedes, pueden", "podemos, podéis"],
           ["o → ue", "dormir", "duermo, duermes, duermen", "dormimos, dormís"],
           ["u → ue", "jugar", "juego, juegas, juegan", "jugamos, jugáis"],
           ["e → i", "pedir", "pido, pides, piden", "pedimos, pedís"],
           ["词族|word family", { zh: "土地", en: "earth" }, "tierra", "terrestre"],
           ["词族|word family", { zh: "门", en: "door" }, "puerta", "portal"],
           ["词族|word family", { zh: "火", en: "fire" }, "fuego", "fogata"],
           ["词族|word family", { zh: "九", en: "nine" }, "nueve", "noveno"]] },
  notes: { zh: "口语拉丁语里,短 ĕ、ŏ 读成开口的 [ɛ]、[ɔ],卡斯蒂利亚语在重读时把它们裂成二合元音:pĕtra → piedra, pŏrta → puerta, fŏcus → fuego, mŏrtem → muerte;后面紧跟腭音时例外:nŏctem → noche。不重读就不变:pedrero、portal。长 ē、ō 和短 ĭ、ŭ 变成闭口的 e、o,从不裂变:bĭbō → bebo。terrestre 则是后来从书面拉丁语借入的学者词。diptongo 来自希腊语 diphthongos「两个声音」。",
           en: "In spoken Latin short ĕ and ŏ became open [ɛ] and [ɔ], and Castilian split them into diphthongs when stressed: pĕtra → piedra, pŏrta → puerta, fŏcus → fuego, mŏrtem → muerte — unless a palatal followed: nŏctem → noche. Unstressed they stayed: pedrero, portal. Long ē, ō and short ĭ, ŭ became close e, o and never split: bĭbō → bebo. Terrestre was later borrowed from written Latin. Diptongo is Greek diphthongos, two sounds." },
  ex: [
    { q: { zh: "Orfeo ___ salir del Hades con Eurídice.(querer)", en: "Orfeo ___ salir del Hades con Eurídice. (querer)" }, opts: ["quiere", "quere", "quire", "quieres"], a: 0,
      why: { zh: "querer 的词干 e 重读时变成 ie:quiere。quere 忘了变化;quire 是把 pedir 类的 e → i 用错了动词;quieres 是「你」。", en: "Querer's stressed stem e becomes ie: quiere. Quere forgets the change, quire applies the e → i of pedir-type verbs to the wrong verb, and quieres is you." } },
    { q: { zh: "Nosotros no ___ mirar atrás.(poder)", en: "Nosotros no ___ mirar atrás. (poder)" }, opts: ["podemos", "puedemos", "puedimos", "pueden"], a: 0,
      why: { zh: "nosotros 的重音落在词尾 -emos 上,词干 o 不重读,所以不变:podemos。puedemos 把 ue 带到了「靴子」外面。", en: "In nosotros the stress falls on -emos, so the stem o is unstressed and stays: podemos. Puedemos carries the ue outside the boot." } },
    { q: { zh: "Medusa ___ cuando llega Perseo.(dormir)", en: "Medusa ___ cuando llega Perseo. (dormir)" }, opts: ["duerme", "dorme", "durme", "duermes"], a: 0,
      why: { zh: "dormir 是 o → ue 动词,重读词干变成 duer-:duerme。dorme 是葡萄牙语和意大利语的形,西班牙语必须裂变。珀耳修斯正是趁戈耳工们熟睡时下手的。", en: "Dormir is an o → ue verb, so its stressed stem is duer-: duerme. Dorme is the Portuguese and Italian form; Spanish must split the vowel. Perseus struck while the Gorgons slept." } },
    { q: { zh: "jugar 的 yo 形是:", en: "The yo form of jugar is:" }, opts: ["juego", "jugo", "jiego", "juogo"], a: 0,
      why: { zh: "jugar 是唯一 u → ue 的动词:juego, juegas, juega……jugo 是名词「果汁」。jugar 来自拉丁语 iocārī「开玩笑」(iŏcus「玩笑」),重读的 ŏ 照例裂成 ue。", en: "Jugar is the only verb with u → ue: juego, juegas, juega … Jugo is a noun, juice. Jugar comes from Latin iocārī, to joke (iŏcus, a joke), whose stressed ŏ split as usual." } },
    { q: { zh: "Penélope ___ ayuda a Atenea.(pedir)", en: "Penélope ___ ayuda a Atenea. (pedir)" }, opts: ["pide", "piede", "pede", "pidi"], a: 0,
      why: { zh: "pedir 属于 e → i 的 -ir 动词:pido, pides, pide。piede 是把 e → ie 用到了不该用的地方;pede 忘了变化。", en: "Pedir is one of the -ir verbs with e → i: pido, pides, pide. Piede wrongly applies e → ie, and pede forgets the change." } },
    { q: { zh: "为什么是 queremos,而不是 quieremos?", en: "Why queremos and not quieremos?" },
      opts: [{ zh: "重音落在词尾 -emos,词干元音不重读,所以不裂变", en: "the stress is on -emos, so the stem is unstressed" }, { zh: "因为复数形式从不变化", en: "because plural verb forms never change their stem" }, { zh: "因为 querer 只在 yo 形变化", en: "because querer changes only in the yo form" }, { zh: "为了和 quiero 区分开", en: "to keep it apart from quiero" }], a: 0,
      why: { zh: "关键是重音,不是单复数:quieren 也是复数,却照样裂变,因为它的重音在词干上(QUIE-ren)。", en: "The key is stress, not number: quieren is plural too, yet it splits, because its stress falls on the stem, QUIE-ren." } },
    { q: { zh: "哪一对词和 poder / puedo 体现同一种交替?", en: "Which pair shows the same alternation as poder / puedo?" }, opts: ["mortal / muerte", "tierra / terrestre", "pedir / pido", "comer / como"], a: 0,
      why: { zh: "poder / puedo 是 o 与 ue 的交替,mortal / muerte 也是:重读的 muer- 裂变,不重读的 mor- 不变。tierra / terrestre 是 e 与 ie,pedir / pido 是 e 与 i,comer / como 没有变化。", en: "Poder / puedo alternates o and ue, and so does mortal / muerte: stressed muer- splits, unstressed mor- does not. Tierra / terrestre is e and ie, pedir / pido e and i, and comer / como has no change." } },
    { q: { zh: "拉丁语 pŏrta → puerta,pĕtra → piedra。短 ĕ、ŏ 在什么条件下变成 ie、ue?", en: "Latin pŏrta → puerta, pĕtra → piedra. When did short ĕ and ŏ become ie and ue?" },
      opts: [{ zh: "在重读音节里", en: "in stressed syllables" }, { zh: "在词尾", en: "at the very end of a word" }, { zh: "在 r 之前", en: "only before the consonant r" }, { zh: "在所有位置", en: "in every position in the word" }], a: 0,
      why: { zh: "只有重读的短 ĕ、ŏ 裂变;不重读时保持原样,所以有 pedrero(石匠)、portal(门廊)。「在 r 之前」只是巧合:fŏcus → fuego 里就没有 r。", en: "Only stressed short ĕ and ŏ split; unstressed they stayed, hence pedrero, a stonecutter, and portal, a porch. ‘Before r’ is a coincidence: fŏcus → fuego has no r." } },
  ] },
]);

/* Fuga Mythica — Spanish grammar road, stations 6–10 */
GRAM_ADD("es", [
{ id: "es_irreg", icon: "🗝️",
  name: { zh: "不规则动词与 gustar · 宙斯的怒火", en: "Irregular verbs and gustar · The wrath of Zeus" },
  scene: { zh: "普罗米修斯盗来天火,对人类说:Vengo del Olimpo, traigo el fuego(我从奥林匹斯来,带来了火)。越常用的动词越不守规矩。人们围着火欢喜:a los hombres les gusta el fuego;宙斯却震怒:a Zeus no le gusta nada。",
           en: "Prometheus steals fire from Olympus and tells mankind: Vengo del Olimpo, traigo el fuego — I come from Olympus, I bring fire. The commonest verbs are the least regular. The humans gather round, delighted: a los hombres les gusta el fuego. Zeus is furious: a Zeus no le gusta nada." },
  rule: { zh: "不少常用动词只在 yo 形不规则,如 hago, conozco, sé, doy, veo。tener、venir、decir 的 yo 形也是 -go,tú、él、ellos 形还变词干;ir 全不规则。gustar 与汉语相反:被喜欢的是主语,单数或不定式用 gusta,复数用 gustan;人用间接宾语:me gustan las islas。具体的人加 a 并保留 le:a Teseo le gusta el mar;a mí me… 表强调。encantar、interesar、doler 同理。",
          en: "Many common verbs are irregular only in yo: hago, conozco, sé, doy, veo. Tener, venir and decir have -go plus a stem change (tienes, dicen); ir is irregular throughout. With gustar the thing liked is the subject, gusta if singular or an infinitive, gustan if plural, and the person an indirect object: me gustan las islas. A named person adds a and keeps le: a Teseo le gusta el mar; a mí me… is emphatic. Encantar, interesar and doler work alike." },
  table: { cap: { zh: "tener、decir、venir、ir 全表,另附只在 yo 形不规则的动词", en: "tener, decir, venir and ir in full, plus verbs irregular only in yo" },
    head: [{ zh: "人称", en: "Person" }, { zh: "tener 有", en: "tener, to have" }, { zh: "decir 说", en: "decir, to say" }, { zh: "venir 来", en: "venir, to come" }, { zh: "ir 去", en: "ir, to go" }],
    rows: [["yo", "tengo", "digo", "vengo", "voy"],
           ["tú", "tienes", "dices", "vienes", "vas"],
           ["él / ella / usted", "tiene", "dice", "viene", "va"],
           ["nosotros", "tenemos", "decimos", "venimos", "vamos"],
           ["vosotros", "tenéis", "decís", "venís", "vais"],
           ["ellos / ustedes", "tienen", "dicen", "vienen", "van"],
           ["拉丁语|Latin", "tenēre", "dīcere", "venīre", "īre · vādere"],
           ["只在 yo 形不规则|irregular only in yo", "hago (hacer)", "pongo (poner)", "salgo (salir)", "traigo (traer)"],
           ["只在 yo 形不规则|irregular only in yo", "conozco (conocer)", "sé (saber)", "doy (dar)", "veo (ver)"]] },
  notes: { zh: "-go 并非个个有来历:digo 的 g 是 dīcō 的 c 在元音间浊化而成;teneō、veniō、pōnō、saliō 没有 g,tengo、vengo、pongo、salgo 的 g 是类推来的(模型存疑)。conozco 承自 cognōscō(古西语 conosco),z 是仿 conoces 改的。ir 是拼凑的:ir 出自 īre,voy、vas、va 出自 vādere「迈步」。gustar 即 gustāre「品尝」;me gusta 的构造同 mihi placet「它令我满意」:人用与格。",
           en: "Not every -go has a pedigree. Digo's g is the c of dīcō, voiced between vowels; teneō, veniō, pōnō and saliō had no g, so tengo, vengo, pongo and salgo got theirs by analogy (the model is disputed). Conozco is cognōscō (Old Spanish conosco), its z copied from conoces. Ir is patched together: ir from īre, voy, vas, va from vādere, to stride. Gustar is gustāre, to taste; me gusta is built like mihi placet, it pleases me, the person in the dative." },
  ex: [
    { q: { zh: "代达罗斯说:「Yo ___ unas alas para Ícaro.」(hacer)", en: "Daedalus says: “Yo ___ unas alas para Ícaro.” (hacer)" }, opts: ["hago", "hazo", "haco", "hace"], a: 0,
      why: { zh: "hacer 属于 -go 型:hago。hazo 错套了 vencer → venzo 那种 c→z 的拼写规则;hace 是第三人称「他做」。", en: "Hacer belongs to the -go group: hago. Hazo wrongly applies the c→z spelling of verbs like vencer (venzo); hace is the third person, he makes." } },
    { q: { zh: "赫尔墨斯说:「Yo ___ del Olimpo con un mensaje.」(venir)", en: "Hermes says: “Yo ___ del Olimpo con un mensaje.” (venir)" }, opts: ["vengo", "veno", "vieno", "viengo"], a: 0,
      why: { zh: "venir 的 yo 形是 -go 型的 vengo,不带 ie。ie 只出现在 vienes、viene、vienen 里,vieno 和 viengo 把它错带进了 yo 形。", en: "Venir gives vengo, a -go form without the diphthong. The ie appears only in vienes, viene and vienen; vieno and viengo wrongly carry it into the yo form." } },
    { q: { zh: "美狄亚说:「Yo ___ con Jasón a Grecia.」(ir)", en: "Medea says: “Yo ___ con Jasón a Grecia.” (ir)" }, opts: ["voy", "iro", "va", "vas"], a: 0,
      why: { zh: "ir 的现在时全不规则:voy, vas, va, vamos, vais, van。iro 是按 -o 规则硬推出来的错形;va 是「他去」,vas 是「你去」。", en: "Ir is irregular throughout the present: voy, vas, va, vamos, vais, van. Iro is an over-regularised error; va means he goes and vas you go." } },
    { q: { zh: "下面哪个 yo 形是错的?", en: "Which yo form is wrong?" }, opts: ["sabo", "sé", "pongo", "conozco"], a: 0,
      why: { zh: "saber 的 yo 形是 sé,重音符号把它和代词 se 区分开。sabo 是按规则硬推出来的错形;pongo、conozco 都正确。", en: "Saber gives sé, whose accent sets it apart from the pronoun se. Sabo is an over-regularised error; pongo and conozco are correct." } },
    { q: { zh: "A Ariadna le ___ las estrellas.(阿里阿德涅喜欢星星)", en: "A Ariadna le ___ las estrellas. (Ariadne likes the stars)" }, opts: ["gustan", "gusta", "gusto", "gustas"], a: 0,
      why: { zh: "被喜欢的 las estrellas 才是主语,而且是复数,所以用 gustan。gusta 是最常见的错误:把阿里阿德涅当成了主语。", en: "The thing liked, las estrellas, is the subject, and it is plural, so gustan. Gusta is the classic slip: treating Ariadne as the subject." } },
    { q: { zh: "A Orfeo le gusta la música。这句话的语法主语是什么?", en: "A Orfeo le gusta la música. What is the grammatical subject?" },
      opts: [{ zh: "la música(被喜欢的东西)", en: "la música — the thing liked" }, { zh: "Orfeo(喜欢的人)", en: "Orfeo — the one who likes" }, { zh: "代词 le", en: "the pronoun le" }, { zh: "这句话没有主语", en: "the sentence has no subject" }], a: 0,
      why: { zh: "gusta 和 la música 一致:换成 las canciones 就得说 gustan。俄耳甫斯是间接宾语(「音乐令他愉悦」),所以不能说 Orfeo gusta la música。", en: "Gusta agrees with la música: make it las canciones and the verb becomes gustan. Orpheus is the indirect object — music pleases him — so Orfeo gusta la música is wrong." } },
    { q: { zh: "A Prometeo le ___ el hígado.(doler;每天都有鹰来啄食他的肝)", en: "A Prometeo le ___ el hígado. (doler — every day an eagle feeds on his liver)" }, opts: ["duele", "dole", "duelen", "duelo"], a: 0,
      why: { zh: "doler 和 gustar 一样用:疼的部位 el hígado 是主语,单数,所以是 duele(o 重读变 ue)。duelen 要配复数,如 le duelen las heridas。", en: "Doler works like gustar: the aching part, el hígado, is a singular subject, so duele, with o → ue under stress. Duelen needs a plural, as in le duelen las heridas." } },
    { q: { zh: "voy、vas、va 来自哪个拉丁动词?", en: "Voy, vas, va come from which Latin verb?" }, opts: ["vādere", "īre", "venīre", "esse"], a: 0,
      why: { zh: "ir 的不定式来自 īre,现在时却取自 vādere「迈步、前行」:vādō → 古西语 vo → voy。由不同词根拼成一个动词,叫异干互补。", en: "The infinitive ir is from īre, but the present comes from vādere, to stride: vādō → Old Spanish vo → voy. A verb patched together from different roots is called suppletive." } },
  ] },

{ id: "es_indefinido", icon: "⚔️",
  name: { zh: "简单过去时 · 忒修斯斩杀米诺陶", en: "The preterite · Theseus slays the Minotaur" },
  scene: { zh: "一串完成的动作就是一个故事:Teseo llegó a Creta, entró en el laberinto, mató al Minotauro y salió(忒修斯到了克里特,进了迷宫,杀了米诺陶,又顺着阿里阿德涅的线走了出来)。每一步都有始有终——这正是简单过去时的本分。",
           en: "A chain of finished actions makes a story: Teseo llegó a Creta, entró en el laberinto, mató al Minotauro y salió — Theseus reached Crete, entered the labyrinth, killed the Minotaur and came out again along Ariadne's thread. Each step begins and ends. That is what the preterite is for." },
  rule: { zh: "简单过去时讲一次完成的动作。规则词尾:-ar 是 -é, -aste, -ó…,-er/-ir 是 -í, -iste, -ió…。重音符号区分时态:hablo「我说」,habló「他说了」。拼写变化:llegué、busqué、empecé。强变化形重读词干、不标重音:tuve、pude、puse、hice/hizo、vine、quise、dije、traje;j 词干用 -eron:dijeron。ser 与 ir 共用 fui … fueron。另记 di、vi、leyó、cayó、pidió、durmió。",
          en: "The preterite is for finished past actions. -ar: -é, -aste, -ó, -amos, -asteis, -aron; -er/-ir: -í, -iste, -ió, -imos, -isteis, -ieron. The accent marks the tense: hablo, I speak; habló, he spoke. Yo forms respell: llegué, busqué, empecé. Strong preterites stress the stem and take no accent: tuve, pude, puse, hice/hizo, vine, quise, dije, traje; j-stems take -eron: dijeron. Ser and ir share fui … fueron. Note di, vi, leyó, cayó, pidió, durmió." },
  table: { cap: { zh: "llegar 到达 · vivir 生活 · tener 有 · ser/ir", en: "llegar, to arrive · vivir, to live · tener, to have · ser/ir" },
    head: [{ zh: "人称", en: "Person" }, { zh: "llegar", en: "llegar" }, { zh: "vivir", en: "vivir" }, { zh: "tener(强变化)", en: "tener (strong)" }, { zh: "ser / ir", en: "ser / ir" }],
    rows: [["yo 我|yo — I", "llegué", "viví", "tuve", "fui"],
           ["tú 你|tú — you", "llegaste", "viviste", "tuviste", "fuiste"],
           ["él/ella 他/她|él, ella — he, she", "llegó", "vivió", "tuvo", "fue"],
           ["nosotros 我们|nosotros — we", "llegamos", "vivimos", "tuvimos", "fuimos"],
           ["vosotros 你们|vosotros — you (pl.)", "llegasteis", "vivisteis", "tuvisteis", "fuisteis"],
           ["ellos 他们|ellos — they", "llegaron", "vivieron", "tuvieron", "fueron"]] },
  notes: { zh: "简单过去时就是拉丁语的完成时。规则形由缩约而来:cantāvī → cantai → canté,cantāvit → cantaut → cantó。强变化形保留拉丁语落在词干上的重音:fēcī → 古西语 fize → hice(词尾 -ī 把 e 抬成 i),habuī → hube,potuī → pude;tuve 仿照 hube 而成。ir 借用了 esse 的 fuī,所以 fui 兼作「我是」「我去」。pretérito 来自 praeteritum「已经过去的」(praeter + īre)。",
           en: "The preterite is the Latin perfect. Regular forms are contractions: cantāvī → cantai → canté, cantāvit → cantaut → cantó. Strong forms keep the Latin stress on the stem: fēcī → Old Spanish fize → hice (final -ī raised e to i), habuī → hube, potuī → pude; tuve was modelled on hube. Ir borrowed fuī from esse, so fui is both I was and I went. Pretérito is Latin praeteritum, gone by: praeter, beyond, plus īre, to go." },
  ex: [
    { q: { zh: "Teseo ___ al Minotauro.(matar,忒修斯杀死了米诺陶)", en: "Teseo ___ al Minotauro. (matar — Theseus killed the Minotaur)" }, opts: ["mató", "mato", "matió", "matí"], a: 0,
      why: { zh: "-ar 动词第三人称单数是 -ó,必须写重音符号。mato 是现在时「我杀」;matió 把 -er/-ir 的 -ió 错套在 -ar 动词上。", en: "An -ar verb takes -ó in the third person singular, with its written accent. Mato is the present, I kill; matió wrongly borrows the -ió of -er and -ir verbs." } },
    { q: { zh: "Ayer yo ___ a Creta.(llegar)", en: "Ayer yo ___ a Creta. (llegar)" }, opts: ["llegué", "llegé", "llegue", "llegó"], a: 0,
      why: { zh: "-é 前的 g 要写成 gu 才保持 /g/ 音:llegué。llegé 会读成 j 的音;llegue 没有重音符号,是另一个形式(虚拟式);llegó 是「他到了」。", en: "Before -é the g must be written gu to keep its hard sound: llegué. Llegé would be read with a j-sound; llegue without the accent is another form (the subjunctive); llegó means he arrived." } },
    { q: { zh: "Dédalo ___ unas alas de plumas y cera.(hacer,代达罗斯做了羽毛和蜡的翅膀)", en: "Dédalo ___ unas alas de plumas y cera. (hacer — Daedalus made wings of feathers and wax)" }, opts: ["hizo", "hició", "hizó", "hico"], a: 0,
      why: { zh: "hacer 是强变化过去时:hice, hiciste, hizo。重音在词干上,所以不写重音符号(hizó 错);c 在 o 前写成 z 才保持原音,hico 会读成 k。", en: "Hacer has a strong preterite: hice, hiciste, hizo. The stress is on the stem, so no written accent (not hizó), and c becomes z before o to keep its sound — hico would be read with a k." } },
    { q: { zh: "Los argonautas ___ a la Cólquide en la nave Argo.(ir)", en: "Los argonautas ___ a la Cólquide en la nave Argo. (ir)" }, opts: ["fueron", "iron", "fuieron", "fue"], a: 0,
      why: { zh: "ir 和 ser 共用一套过去时:fui … fueron。iron 是按规则硬推的错形,fuieron 多了一个 i,fue 是单数「他去了」,和复数主语不一致。", en: "Ir shares its preterite with ser: fui … fueron. Iron is an over-regularised error, fuieron has a stray i, and fue is singular, he went, which clashes with the plural subject." } },
    { q: { zh: "Ayer fue un gran día. / Ayer Teseo fue a Creta. 两个 fue 分别属于哪个动词?", en: "Ayer fue un gran día. / Ayer Teseo fue a Creta. Which verb is each fue?" },
      opts: [{ zh: "前一个是 ser,后一个是 ir", en: "the first is ser, the second ir" }, { zh: "两个都是 ser", en: "both are ser" }, { zh: "两个都是 ir", en: "both are ir" }, { zh: "前一个是 ir,后一个是 ser", en: "the first is ir, the second ser" }], a: 0,
      why: { zh: "形式相同,要看句子:「昨天是个好日子」是 ser;后面接 a + 地点、表示移动的是 ir。", en: "The forms are identical, so the sentence decides: yesterday was a great day is ser; movement with a plus a place is ir." } },
    { q: { zh: "下面哪个过去时形式是错的?", en: "Which preterite form is wrong?" }, opts: ["dijieron", "dijeron", "trajo", "pudo"], a: 0,
      why: { zh: "词干以 j 结尾的强变化过去时,第三人称复数只用 -eron:dijeron、trajeron。dijieron 把普通的 -ieron 套了上去,是最常见的错误。", en: "In strong preterites whose stem ends in j, the third person plural is plain -eron: dijeron, trajeron. Dijieron, with the usual -ieron, is the commonest slip." } },
    { q: { zh: "Un día el rey Midas ___ a Dioniso el don del oro.(pedir)", en: "Un día el rey Midas ___ a Dioniso el don del oro. (pedir)" }, opts: ["pidió", "pedió", "pidó", "pedí"], a: 0,
      why: { zh: "pedir 这类 e→i 的 -ir 动词,在过去时的第三人称里也变 i:pidió、pidieron。pedió 漏了这个变化,pidó 丢了 i,pedí 是「我要求了」。", en: "-ir verbs like pedir change e to i in the third persons of the preterite: pidió, pidieron. Pedió misses the change, pidó loses the i, and pedí means I asked." } },
    { q: { zh: "hice 继承的是拉丁语哪个完成时形式?", en: "Hice continues which Latin perfect form?" }, opts: ["fēcī", "faciō", "facere", "factum"], a: 0,
      why: { zh: "fēcī「我做了」→ 古西语 fize → hice:f 变 h,词尾 -ī 把 e 抬成 i。faciō 是现在时,facere 是不定式(hacer 的来源),factum 是过去分词(hecho 的来源)。", en: "Fēcī, I made, became Old Spanish fize and then hice: f turned to h, and the final -ī raised e to i. Faciō is the present, facere the infinitive (source of hacer), factum the past participle (source of hecho)." } },
  ] },

{ id: "es_imperfecto", icon: "🕯️",
  name: { zh: "未完成过去时 · 佩涅洛佩的织布机", en: "The imperfect · Penelope's loom" },
  scene: { zh: "奥德修斯离家二十年。佩涅洛佩白天织寿衣,夜里又拆掉:cada día tejía el sudario y cada noche lo deshacía。求婚者在宫中吃喝:comían y bebían。这是背景和习惯,用未完成过去时。后来 llegó Odiseo——事情发生了,换成简单过去时。",
           en: "Odysseus has been gone for twenty years. Penelope weaves a shroud by day and unpicks it by night: cada día tejía el sudario y cada noche lo deshacía. The suitors eat and drink in the hall: comían y bebían. That is background and habit — the imperfect. Then one day llegó Odiseo: something happens, and the story switches to the preterite." },
  rule: { zh: "-ar:-aba, -abas, -aba, -ábamos, -abais, -aban;-er/-ir:-ía, -ías, -ía, -íamos, -íais, -ían。只有三个不规则:ser(era)、ir(iba)、ver(veía)。未完成过去时描绘背景与状态(era de noche)、习惯和进行中的动作(tejía);简单过去时讲完成的事件。mientras 多接未完成过去时;cuando 引出打断它的事件,用简单过去时:Penélope tejía cuando llegó Odiseo。",
          en: "-ar: -aba, -abas, -aba, -ábamos, -abais, -aban; -er/-ir: -ía, -ías, -ía, -íamos, -íais, -ían. Only three verbs are irregular: ser (era), ir (iba), ver (veía). The imperfect paints background and states (era de noche), habits (cada noche deshacía) and actions in progress (tejía); the preterite tells the events. Mientras usually takes the imperfect; cuando brings in the interrupting event in the preterite: Penélope tejía cuando llegó Odiseo." },
  table: { cap: { zh: "esperar 等待 · tejer 织 · ser 是 · ir 去", en: "esperar, to wait · tejer, to weave · ser, to be · ir, to go" },
    head: [{ zh: "人称", en: "Person" }, { zh: "esperar", en: "esperar" }, { zh: "tejer", en: "tejer" }, { zh: "ser", en: "ser" }, { zh: "ir", en: "ir" }],
    rows: [["yo 我|yo — I", "esperaba", "tejía", "era", "iba"],
           ["tú 你|tú — you", "esperabas", "tejías", "eras", "ibas"],
           ["él/ella 他/她|él, ella — he, she", "esperaba", "tejía", "era", "iba"],
           ["nosotros 我们|nosotros — we", "esperábamos", "tejíamos", "éramos", "íbamos"],
           ["vosotros 你们|vosotros — you (pl.)", "esperabais", "tejíais", "erais", "ibais"],
           ["ellos 他们|ellos — they", "esperaban", "tejían", "eran", "iban"]] },
  notes: { zh: "-aba 几乎原样继承拉丁语的 -ābam:amābam → amaba。-er/-ir 的 -ía 来自 -ēbam 和 -ībam(古典拉丁语作 -iēbam),其中的 b 很早就脱落了(habēbam → había)。三个不规则形也直承拉丁语:eram → era,ībam → iba,vidēbam → veía(保留了 e)。一般认为拉丁语的 -bam 本身与 fuī 同根,出自印欧语词根 *bʰuH-「成为」。imperfecto 来自 imperfectum「未完成的」——动作在画面里仍在进行。",
           en: "-aba is Latin -ābam almost unchanged: amābam → amaba. The -ía of -er and -ir verbs comes from -ēbam and -ībam (classical -iēbam), whose b dropped out early (habēbam → había). The three irregulars are direct heirs too: eram → era, ībam → iba, vidēbam → veía, keeping its e. Latin -bam is usually traced to the root *bʰuH-, to become, the root of fuī. Imperfecto is imperfectum, not finished: the action is still going on in the picture." },
  ex: [
    { q: { zh: "Cada día Penélope ___ el sudario.(tejer)", en: "Cada día Penélope ___ el sudario. (tejer)" }, opts: ["tejía", "tejaba", "tejiba", "tejeba"], a: 0,
      why: { zh: "-er 动词用 -ía:tejía。-aba 只属于 -ar 动词;tejiba 是仿照 iba 造出的错形;tejeba 留着拉丁 -ēbam 的 b,而西班牙语早已把它丢了。", en: "-er verbs take -ía: tejía. -aba belongs only to -ar verbs; tejiba copies iba; tejeba keeps the b of Latin -ēbam, which Spanish lost long ago." } },
    { q: { zh: "阿尔戈英雄们说:「Cada día ___ más lejos de casa.」(ir,nosotros)", en: "The Argonauts say: “Cada día ___ más lejos de casa.” (ir, nosotros)" }, opts: ["íbamos", "ibamos", "ibámos", "ivamos"], a: 0,
      why: { zh: "ir 的未完成过去时是不规则的 iba,nosotros 形 íbamos 重音在第一个音节,必须写重音符号——和 -ábamos、-íamos、éramos 一样。ivamos 是拼写错误:b 和 v 读音相同,但这里照词源写 b(拉丁 ībāmus)。", en: "Ir has the irregular imperfect iba; the nosotros form íbamos is stressed on the first syllable and needs its accent, like -ábamos, -íamos and éramos. Ivamos is a spelling slip: b and v sound alike, but the word keeps the b of Latin ībāmus." } },
    { q: { zh: "下面哪个动词的未完成过去时不规则?", en: "Which verb is irregular in the imperfect?" }, opts: ["ver", "tener", "hacer", "decir"], a: 0,
      why: { zh: "未完成过去时只有三个不规则:ser(era)、ir(iba)、ver(veía,保留了 e)。tener、hacer、decir 在现在时不规则,在这里却很规矩:tenía、hacía、decía。", en: "Only three verbs are irregular in the imperfect: ser (era), ir (iba) and ver (veía, keeping its e). Tener, hacer and decir, irregular in the present, are regular here: tenía, hacía, decía." } },
    { q: { zh: "Cada noche Penélope deshacía el sudario。这里的未完成过去时表示:", en: "Cada noche Penélope deshacía el sudario. The imperfect here expresses:" },
      opts: [{ zh: "过去反复发生的习惯", en: "a repeated habit in the past" }, { zh: "一次完成的动作", en: "a single finished action" }, { zh: "打断别的动作的事件", en: "an event that cuts into another" }, { zh: "将来的计划", en: "a plan for the future" }], a: 0,
      why: { zh: "cada noche「每天夜里」说明这是反复发生的事,正是未完成过去时的典型用法。一次完成的动作才用简单过去时。", en: "Cada noche, every night, marks a repeated action — a textbook use of the imperfect. A single finished action would take the preterite." } },
    { q: { zh: "Mientras los pretendientes ___, Penélope deshacía el sudario.(dormir)", en: "Mientras los pretendientes ___, Penélope deshacía el sudario. (dormir)" }, opts: ["dormían", "durmían", "dormaban", "dormiban"], a: 0,
      why: { zh: "mientras 引出同时进行的背景,用未完成过去时:dormían。这个时态没有词干变化,所以不是 durmían(u 只出现在 durmió 这类形式里);-aba、-iba 也不属于 -ir 动词。", en: "Mientras introduces a background action going on at the same time, in the imperfect: dormían. This tense has no stem change, so not durmían — the u belongs to forms like durmió; and -aba or -iba never attach to an -ir verb." } },
    { q: { zh: "Penélope tejía cuando entró un mendigo。entró 为什么用简单过去时?", en: "Penélope tejía cuando entró un mendigo. Why is entró in the preterite?" },
      opts: [{ zh: "它是打断背景动作的事件", en: "it is the event that breaks into the background" }, { zh: "它是持续很久的状态", en: "it is a long-lasting state" }, { zh: "它是过去的习惯", en: "it is a past habit" }, { zh: "cuando 后面永远不能用未完成过去时", en: "cuando can never take the imperfect" }], a: 0,
      why: { zh: "tejía 是正在进行的背景,entró 是突然插进来的一次性事件——那个乞丐正是乔装的奥德修斯。cuando 本身不决定时态:cuando era niño 就用未完成过去时。", en: "Tejía is the ongoing background; entró is the single event that breaks in — the beggar is Odysseus in disguise. Cuando does not fix the tense by itself: cuando era niño takes the imperfect." } },
    { q: { zh: "下面哪个形式是错的?", en: "Which form is wrong?" }, opts: ["erábamos", "esperábamos", "íbamos", "veíamos"], a: 0,
      why: { zh: "ser 的未完成过去时不规则:era, eras, era, éramos, erais, eran。erábamos 是把 -ábamos 错接在 era 上。", en: "Ser is irregular: era, eras, era, éramos, erais, eran. Erábamos wrongly grafts -ábamos onto era." } },
    { q: { zh: "esperaba 的 -aba 来自拉丁语的哪个词尾?", en: "The -aba of esperaba comes from which Latin ending?" }, opts: ["-ābam", "-āvī", "-ābō", "-ātus"], a: 0,
      why: { zh: "拉丁语未完成过去时 amābam、spērābam 的 -ābam 几乎原封不动地传了下来。-āvī 是完成时词尾(后来成了 -é),-ābō 是将来时(已消失),-ātus 是过去分词(后来成了 -ado)。", en: "The Latin imperfect ending -ābam, as in amābam and spērābam, came through almost untouched. -āvī was the perfect (later -é), -ābō the future (lost), -ātus the past participle (later -ado)." } },
  ] },

{ id: "es_futuro", icon: "🔮",
  name: { zh: "将来时与条件式 · 卡珊德拉的预言", en: "Future and conditional · Cassandra's prophecy" },
  scene: { zh: "卡珊德拉在特洛伊城头预言:Troya caerá, los griegos saldrán del caballo(特洛伊将陷落,希腊人会从木马里出来)。无人相信。多年后幸存者回忆:Casandra dijo que Troya caería——同一词干换上 -ía,就成了「从过去望见的将来」。",
           en: "On the walls of Troy, Cassandra prophesies: Troya caerá, los griegos saldrán del caballo — Troy will fall, the Greeks will come out of the horse. No one believes her. Years later the survivors remember: Casandra dijo que Troya caería. The same stem with -ía gives the future as seen from the past." },
  rule: { zh: "将来时 = 不定式 + -é, -ás, -á, -emos, -éis, -án,三类动词通用:hablaré、viviré。不规则的只是词干:tendr-、vendr-、pondr-、saldr-、podr-、sabr-、habr-、querr-、har-、dir-。口语常用 ir a + 不定式:voy a navegar。条件式 = 同一词干 + -ía 系列词尾:tendría,用于礼貌(¿Podría ayudarme?)和假设。将来时还能推测现在:serán las diez「大概十点了」。",
          en: "Future = the whole infinitive + -é, -ás, -á, -emos, -éis, -án, for all verbs: hablaré, viviré. Irregulars change only the stem: tendr-, vendr-, pondr-, saldr-, podr-, sabr-, habr-, querr-, har-, dir-. Speech often uses ir a + infinitive: voy a navegar. The conditional puts the -ía endings on the same stem: tendría. It softens requests (¿Podría ayudarme?) and states hypotheses. The future can also guess about now: serán las diez." },
  table: { cap: { zh: "hablar 说 · tener 有 · hacer 做", en: "hablar, to speak · tener, to have · hacer, to do" },
    head: [{ zh: "人称", en: "Person" }, { zh: "hablar 将来时", en: "hablar, future" }, { zh: "tener 将来时", en: "tener, future" }, { zh: "hacer 将来时", en: "hacer, future" }, { zh: "tener 条件式", en: "tener, conditional" }],
    rows: [["yo 我|yo — I", "hablaré", "tendré", "haré", "tendría"],
           ["tú 你|tú — you", "hablarás", "tendrás", "harás", "tendrías"],
           ["él/ella 他/她|él, ella — he, she", "hablará", "tendrá", "hará", "tendría"],
           ["nosotros 我们|nosotros — we", "hablaremos", "tendremos", "haremos", "tendríamos"],
           ["vosotros 你们|vosotros — you (pl.)", "hablaréis", "tendréis", "haréis", "tendríais"],
           ["ellos 他们|ellos — they", "hablarán", "tendrán", "harán", "tendrían"]] },
  notes: { zh: "古典拉丁语的将来时 cantābō 在通俗拉丁语里消失了(常举的原因之一:b、v 合流后,cantābit 和完成时 cantāvit 难以分辨)。人们改说 cantāre habeō「我得唱」,后来连写成 cantaré——所以词尾 -é、-ás、-á、-emos、-án 正是 haber 的 he、has、ha、hemos、han。古西语还能把代词插在中间:darlo he「我将给它」。条件式同理:cantāre habēbam → cantaría。tendré 则是 tenré 中间添了一个 d。",
           en: "Classical Latin's future cantābō died out in speech; one reason often given is that once b and v merged, cantābit sounded like the perfect cantāvit. People said cantāre habeō, I have to sing, which fused into cantaré: the endings -é, -ás, -á, -emos, -án are haber's he, has, ha, hemos, han. Old Spanish could still split them: darlo he, I will give it. The conditional is cantāre habēbam → cantaría. Tendré is tenré with a d slipped in." },
  ex: [
    { q: { zh: "卡珊德拉:「Los griegos ___ del caballo.」(salir,将来时)", en: "Cassandra: “Los griegos ___ del caballo.” (salir, future)" }, opts: ["saldrán", "salirán", "salrán", "saldarán"], a: 0,
      why: { zh: "salir 的将来时词干是 saldr-:i 脱落,l 和 r 之间添一个 d。salirán 是按规则硬推的错形;salrán 只脱落、不添 d。", en: "Salir has the future stem saldr-: the i drops and a d slips in between l and r. Salirán is over-regularised; salrán drops the vowel but forgets the d." } },
    { q: { zh: "忒瑞西阿斯对奥德修斯说:「___ a Ítaca, pero tarde y solo.」(volver,tú)", en: "Tiresias to Odysseus: “___ a Ítaca, pero tarde y solo.” (volver, tú)" }, opts: ["Volverás", "Vuelverás", "Volvrás", "Volverés"], a: 0,
      why: { zh: "volver 的将来时是规则的:整个不定式 + -ás。重音落在词尾,词干不重读,所以没有 ue——ue 只属于 vuelvo 这类重读词干的形式。", en: "Volver has a regular future: the whole infinitive plus -ás. The stress falls on the ending, so the stem has no ue — that belongs to stressed forms like vuelvo." } },
    { q: { zh: "阿里阿德涅:「Esta noche yo ___ un plan.」(hacer,将来时)", en: "Ariadne: “Esta noche yo ___ un plan.” (hacer, future)" }, opts: ["haré", "haceré", "hacré", "harré"], a: 0,
      why: { zh: "hacer 的将来时词干是 har-(古西语 faré),词尾照常:haré。haceré 是按规则硬推的错形;harré 错抄了 querr- 的双 r。", en: "Hacer has the future stem har- (Old Spanish faré): haré. Haceré is over-regularised, and harré wrongly copies the double r of querr-." } },
    { q: { zh: "礼貌地向雅典娜求助:「¿___ ayudarme, Atenea?」(poder,条件式)", en: "A polite request: “¿___ ayudarme, Atenea?” (poder, conditional)" }, opts: ["Podría", "Podería", "Puedería", "Pudería"], a: 0,
      why: { zh: "poder 的词干是 podr-(e 脱落),条件式 podría。podería 没有脱落元音;puedería 把现在时的 ue 带了进来。条件式是让请求变客气的标准手段。", en: "Poder has the stem podr-, with the e dropped: podría. Podería keeps the vowel; puedería drags in the ue of the present. The conditional is the standard way to soften a request." } },
    { q: { zh: "—¿Qué hora es? —No lo sé, serán las diez。这里的 serán 表示:", en: "—¿Qué hora es? —No lo sé, serán las diez. Here serán expresses:" },
      opts: [{ zh: "对现在的推测(大概十点了)", en: "a guess about now: it must be about ten" }, { zh: "将来的某一时刻", en: "a moment in the future" }, { zh: "过去的事实", en: "a past fact" }, { zh: "礼貌的请求", en: "a polite request" }], a: 0,
      why: { zh: "回答的人说「不知道」,所以 serán 不是预告将来,而是推测现在:将来时可以表示「大概」。推测过去用条件式:serían las diez「那时大概十点」。", en: "The speaker does not know, so serán is not a forecast but a guess about now: the future can mean probably. A guess about the past uses the conditional: serían las diez, it must have been ten." } },
    { q: { zh: "下面哪个将来时形式是错的?", en: "Which future form is wrong?" }, opts: ["quererá", "querrá", "dirá", "pondrá"], a: 0,
      why: { zh: "querer 的将来时词干是 querr-:e 脱落后两个 r 相连。quererá 是常见错误;dirá、pondrá 都正确。", en: "Querer has the future stem querr-: the e drops and the two r's meet. Quererá is a common error; dirá and pondrá are correct." } },
    { q: { zh: "Mañana Perseo ___ buscar a Medusa.(ir a + 不定式)", en: "Mañana Perseo ___ buscar a Medusa. (ir a + infinitive)" }, opts: ["va a", "va", "van a", "vas a"], a: 0,
      why: { zh: "近将来用 ir a + 不定式,ir 要和主语一致:Perseo 是第三人称单数,所以 va a buscar。漏掉 a(va buscar)是常见错误。", en: "The near future is ir a + infinitive, with ir agreeing with the subject: Perseo takes va a buscar. Leaving out the a (va buscar) is a common slip." } },
    { q: { zh: "cantaré 来自通俗拉丁语的哪种说法?", en: "Cantaré comes from which Vulgar Latin phrase?" }, opts: ["cantāre habeō", "cantābō", "cantāvī", "cantāre volō"], a: 0,
      why: { zh: "cantāre habeō「我得唱」连写成 cantaré,所以将来时词尾就是 haber 的现在时。cantābō 是古典拉丁语的将来时,已经消失;用 volō「我想」构成将来时的是罗马尼亚语:voi cânta。", en: "Cantāre habeō, I have to sing, fused into cantaré, so the future endings are the present of haber. Cantābō was the classical future, which died out; Romanian built its future on volō, I want: voi cânta." } },
  ] },

{ id: "es_pronombres", icon: "🎯",
  name: { zh: "宾语代词与 a personal · 珀耳修斯与美杜莎", en: "Object pronouns and personal a · Perseus and Medusa" },
  scene: { zh: "雅典娜把一面锃亮的盾交给珀耳修斯:Atenea le da el escudo——se lo da。珀耳修斯不能直视美杜莎,只在盾里看她:no mira a Medusa, la ve en el escudo。特定的人作直接宾语要加 a,物不加:Perseo levanta el escudo。",
           en: "Athena hands Perseus a polished shield: Atenea le da el escudo — se lo da. Perseus must not look at Medusa directly; he sees her in the shield: no mira a Medusa, la ve en el escudo. A specific person as direct object takes a; a thing does not: Perseo levanta el escudo." },
  rule: { zh: "直接宾语用 lo、la、los、las,间接宾语用 le、les;me、te、nos、os 两用。代词放在变位动词前:lo veo;贴在不定式、副动词和肯定命令式后:verlo、mirándola、¡dámelo!。voy a verlo = lo voy a ver,两种位置都对。间接在前:me lo da;le、les 遇到 lo、la 等变成 se:se lo doy。特定的人作直接宾语要加 a:Teseo ve a Ariadna;物不加:ve el barco。指男人时,西班牙也用 le 作直接宾语。",
          en: "Direct: lo, la, los, las; indirect: le, les; me, te, nos, os serve both. They precede a conjugated verb (lo veo) and attach to an infinitive, a gerund or a positive command (verlo, mirándola, ¡dámelo!). Voy a verlo = lo voy a ver: both work. Indirect comes first; le, les become se before lo, la etc.: se lo doy. A specific person as direct object takes a: Teseo ve a Ariadna, but ve el barco. For a man, Spain also accepts le as direct object." },
  table: { cap: { zh: "宾语代词", en: "Object pronouns" },
    head: [{ zh: "指代", en: "Refers to" }, { zh: "直接宾语", en: "Direct object" }, { zh: "间接宾语", en: "Indirect object" }, { zh: "例句", en: "Example" }],
    rows: [["我|me", "me", "me", "Atenea me ayuda."],
           ["你|you", "te", "te", "Te doy el hilo."],
           ["他 · 阳性的物|him, a masculine thing", "lo", "le", "El escudo: lo levanta."],
           ["她 · 阴性的物|her, a feminine thing", "la", "le", "La espada: la toma."],
           ["我们|us", "nos", "nos", "Nos mira."],
           ["你们|you (pl.)", "os", "os", "Os da la nave."],
           ["他们 · 阳性复数|them (masc.)", "los", "les", "Los remos: los deja."],
           ["她们 · 阴性复数|them (fem.)", "las", "les", "Las islas: las ve."],
           ["两个代词连用|two pronouns together", "lo · la · los · las", "se", "Se lo doy a Perseo."]] },
  notes: { zh: "这些代词和定冠词同出一源——拉丁指示代词 ille「那个」:illum → lo,illam → la,illōs → los,illās → las,与格 illī → le,illīs → les。me、te、nos 来自 mē、tē、nōs,os 来自 vōs(v 后来脱落)。se lo 原是古西语 gelo,来自 illī illum「给他—它」,后与反身的 se 混同。a personal 来自拉丁介词 ad,《熙德之歌》里已很常见。clítico 出自希腊语 klinein「倚靠」——它们靠在动词身上。",
           en: "These pronouns share a source with the articles: Latin ille, that. Illum → lo, illam → la, illōs → los, illās → las, dative illī → le, illīs → les. Me and te are mē and tē, nos is nōs, os is vōs that lost its v. Se lo was Old Spanish gelo, from illī illum, to him — it, later confused with reflexive se. Personal a is Latin ad, common already in the Cantar de mio Cid. Clitic is from Greek klinein, to lean: these words lean on the verb." },
  ex: [
    { q: { zh: "Perseo tiene la espada. ___ tiene en la mano.", en: "Perseo tiene la espada. ___ tiene en la mano." }, opts: ["La", "Lo", "Le", "Las"], a: 0,
      why: { zh: "la espada 是阴性单数的物,作直接宾语,代词用 la。le 是间接宾语代词,不能指代被拿着的东西;lo 性不对,las 数不对。", en: "La espada is a feminine singular thing as direct object, so la. Le is the indirect pronoun and cannot stand for the thing held; lo has the wrong gender, las the wrong number." } },
    { q: { zh: "Atenea da el escudo a Perseo → 换成两个代词:Atenea ___ da.", en: "Atenea da el escudo a Perseo — with two pronouns: Atenea ___ da." }, opts: ["se lo", "le lo", "lo le", "se la"], a: 0,
      why: { zh: "间接在前、直接在后;le 遇到 lo 必须变成 se:se lo da。le lo 这种组合不存在;se la 性不对(el escudo 是阳性)。", en: "Indirect comes before direct, and le turns into se before lo: se lo da. Le lo never occurs; se la has the wrong gender, since el escudo is masculine." } },
    { q: { zh: "下面哪一句是错的?", en: "Which sentence is wrong?" }, opts: ["Teseo quiere lo matar.", "Teseo lo quiere matar.", "Teseo quiere matarlo.", "Teseo no lo teme."], a: 0,
      why: { zh: "代词要么放在变位动词 quiere 前面,要么贴在不定式后面:lo quiere matar 和 quiere matarlo 都对。夹在两个动词之间、又不和不定式连写,就错了。", en: "The pronoun goes either before the conjugated quiere or onto the end of the infinitive: lo quiere matar and quiere matarlo are both right. Floating loose between the two verbs is wrong." } },
    { q: { zh: "忒修斯对阿里阿德涅说「把线(el hilo)给我!」:¡___!", en: "Theseus to Ariadne, “Give me the thread (el hilo)!”: ¡___!" }, opts: ["Dámelo", "Damelo", "Dalome", "Dame lo"], a: 0,
      why: { zh: "肯定命令式后面连写代词,间接在前、直接在后:da + me + lo。重音仍在 da 上,成了倒数第三个音节,所以要写重音符号:dámelo。", en: "Pronouns attach to a positive command, indirect before direct: da + me + lo. The stress stays on da, now third from the end, so it needs a written accent: dámelo." } },
    { q: { zh: "哪一句正确?(珀耳修斯寻找美杜莎)", en: "Which sentence is correct? (Perseus looks for Medusa)" }, opts: ["Perseo busca a Medusa.", "Perseo busca Medusa.", "Perseo busca al Medusa.", "Perseo busca de Medusa."], a: 0,
      why: { zh: "特定的人(或拟人的生物)作直接宾语,前面要加 a personal:busca a Medusa。漏掉 a 是最常见的错误;al = a + el,只能用在阳性名词前。", en: "A specific person, or a personified being, as direct object takes personal a: busca a Medusa. Leaving it out is the commonest slip; al is a + el and goes only before a masculine noun." } },
    { q: { zh: "Egeo ve ___ vela negra en el mar.(埃勾斯望见海上的黑帆)", en: "Egeo ve ___ vela negra en el mar. (Aegeus sees the black sail)" }, opts: ["la", "a la", "al", "a"], a: 0,
      why: { zh: "帆是物,不加 a personal,只要冠词:ve la vela negra。a personal 只用在特定的人或拟人的对象前面。", en: "A sail is a thing, so no personal a, just the article: ve la vela negra. Personal a goes only before specific people or personified beings." } },
    { q: { zh: "Ariadna le da el hilo a Teseo。le 是什么?", en: "Ariadna le da el hilo a Teseo. What is le?" },
      opts: [{ zh: "间接宾语(给谁:忒修斯)", en: "the indirect object — to whom: Theseus" }, { zh: "直接宾语(给什么:线)", en: "the direct object — what: the thread" }, { zh: "句子的主语", en: "the subject of the sentence" }, { zh: "反身代词", en: "a reflexive pronoun" }], a: 0,
      why: { zh: "le 指「给谁」,和后面的 a Teseo 是同一个人——西班牙语常这样重复间接宾语。被给的东西 el hilo 才是直接宾语。", en: "Le stands for to whom and doubles a Teseo — Spanish routinely repeats the indirect object this way. The thing given, el hilo, is the direct object." } },
    { q: { zh: "lo、la、le 和定冠词 el、la 都来自哪个拉丁词?", en: "Lo, la, le and the articles el, la all come from which Latin word?" }, opts: ["ille", "hic", "is", "ipse"], a: 0,
      why: { zh: "指示代词 ille「那个」发展出两组词:冠词 el、la,和宾语代词 lo、la、le(来自 illum、illam、illī)。hic 和 is 作为代词几乎没有留下后代,ipse 则成了 ese。", en: "The demonstrative ille, that, produced two sets: the articles el and la, and the object pronouns lo, la, le from illum, illam, illī. Hic and is left almost no pronoun heirs, while ipse became ese." } },
  ] },
]);
