/* =====================================================
   FUGA MYTHICA — grammar road for the study language "de": ten stations,
   added to GRAMS through GRAM_ADD() (defined in grammar.js, loaded first).
   ===================================================== */
/* Fuga Mythica — German grammar road, stations 1–5 */
GRAM_ADD("de", [
{ id: "de_genus", icon: "🛡️",
  name: { zh: "名词的性 · 三位命运女神", en: "Gender · The three Fates" },
  scene: { zh: "命运女神有三位:克洛托纺线,拉刻西斯量线,阿特洛波斯剪线。德语名词也分三性,各有冠词:阿里阿德涅给的 der Faden(线,阳性)、她头上的 die Krone(王冠,阴性)、忒修斯腰间的 das Schwert(剑,中性)。性写在冠词上,不在意思里——「女孩」das Mädchen 竟是中性。",
           en: "There are three Fates: Clotho spins the thread, Lachesis measures it, Atropos cuts it. German nouns come in three genders too, each with its article: the thread Ariadne gives, der Faden (masculine); her crown, die Krone (feminine); Theseus' sword, das Schwert (neuter). Gender sits in the article, not in the meaning: das Mädchen, the girl, is neuter." },
  rule: { zh: "德语名词分阳性、阴性、中性,主格定冠词是 der、die、das;所有名词首字母大写。性要连冠词一起背,后缀可作线索:-ung、-heit、-keit、-schaft、-ion、-tät 一律 die;指小词 -chen、-lein 一律 das,-ment 和拉丁外来词 -um 多为 das;-ling、表示「做事的人」的 -er,以及星期、月份、季节都是 der。复合词的性看最后一个成分:das Schiff + der Kapitän → der Schiffskapitän。语法性不等于自然性别。",
          en: "German nouns are masculine, feminine or neuter — nominative der, die, das — and every noun is capitalised. Learn each with its article, but suffixes help: -ung, -heit, -keit, -schaft, -ion, -tät → die; diminutives in -chen, -lein → always das; -ment and Latin -um → mostly das; -ling, agent -er, days, months, seasons → der. A compound follows its last part: das Schiff + der Kapitän → der Schiffskapitän. Grammatical gender is not natural sex." },
  table: { cap: { zh: "三性与词尾线索", en: "Three genders and their clues" },
    head: [{ zh: "线索", en: "Clue" }, { zh: "冠词", en: "Article" }, { zh: "例词", en: "Examples" }, { zh: "意思", en: "Meaning" }],
    rows: [["-ung · -heit · -keit", "die", "die Hoffnung · die Freiheit · die Gerechtigkeit", "希望 · 自由 · 正义|hope · freedom · justice"],
           ["-schaft · -ion · -tät", "die", "die Freundschaft · die Nation · die Majestät", "友谊 · 民族 · 威严|friendship · nation · majesty"],
           ["指小词 -chen · -lein|diminutive -chen · -lein", "das", "das Mädchen · das Büchlein", "女孩 · 小书|girl · little book"],
           ["-ment · -um(多数)|-ment · -um (mostly)", "das", "das Element · das Museum", "元素 · 博物馆|element · museum"],
           ["-ling · 施事 -er|-ling · agent -er", "der", "der Lehrling · der Sieger", "学徒 · 胜利者|apprentice · victor"],
           ["星期 · 月份 · 季节|days · months · seasons", "der", "der Montag · der Mai · der Winter", "星期一 · 五月 · 冬天|Monday · May · winter"],
           ["复合词看最后一个成分|compound: the last part rules", "der", "der Seemann (die See + der Mann)", "水手|sailor"],
           ["复合词看最后一个成分|compound: the last part rules", "das", "das Vaterland (der Vater + das Land)", "祖国|fatherland"],
           ["性不由意思决定|meaning does not decide gender", "die · der", "die Sonne · der Mond", "太阳 · 月亮(与拉丁语 sōl 阳、lūna 阴正相反)|sun · moon (the reverse of Latin sōl m., lūna f.)"]] },
  notes: { zh: "der、die、das 出自印欧语的指示代词:阳 *so、阴 *seh₂、中 *tod;其余各格都以 *t- 开头(日耳曼语变成 þ,德语再变成 d),德语把这个辅音推广到了所有形式。希腊语冠词 ho、hē、to 与它们同源。英语 the、that 是近亲——das 与 that 的 s/t 之别来自高地德语辅音音变,低地德语至今说 dat。拉丁语也分三性;罗曼语大多丢了中性,英语在中古时期丢了全部语法性,德语却三性俱全。德语称「性」为 Genus,即拉丁语 genus「种类」,与英语 kin 同源。",
          en: "Der, die, das come from the Indo-European demonstrative *so, *seh₂, *tod (Greek ho, hē, to), whose other cases began with *t- (Germanic þ, German d); German spread it to every form. English the and that are kin; das has s for t through the High German consonant shift (Low German dat). Romance mostly lost the Latin neuter and Middle English lost gender; German keeps all three and calls gender Genus: Latin genus, kind, kin to English kin." },
  ex: [
    { q: { zh: "只看词尾,哪个名词是阴性?", en: "Judging by the ending alone, which noun is feminine?" }, opts: ["Wahrheit", "Mädchen", "Frühling", "Museum"], a: 0,
      why: { zh: "-heit 结尾一律阴性:die Wahrheit。Mädchen 是指小词 -chen(das),Frühling 是 -ling(der),Museum 是拉丁外来词 -um(das)。", en: "Nouns in -heit are always feminine: die Wahrheit. Mädchen is a -chen diminutive (das), Frühling ends in -ling (der), and Museum is a Latin loan in -um (das)." } },
    { q: { zh: "das Mädchen(女孩)为什么是中性?", en: "Why is das Mädchen, the girl, neuter?" },
      opts: [{ zh: "因为指小词尾 -chen 让名词变成中性", en: "because the diminutive -chen makes nouns neuter" }, { zh: "因为女孩还没成年,不算阴性", en: "because a girl is not yet a grown woman" }, { zh: "因为指人的名词都是中性", en: "because all nouns for people are neuter" }, { zh: "因为以 -en 结尾的名词都是中性", en: "because all nouns ending in -en are neuter" }], a: 0,
      why: { zh: "Mädchen 原是 Magd(少女)加指小词尾 -chen;-chen、-lein 能把任何名词变成中性,连 der Tisch 也变成 das Tischchen。语法性跟着词形走,不跟着生理性别走。", en: "Mädchen is Magd, maiden, plus the diminutive -chen, and -chen or -lein makes any noun neuter — even der Tisch becomes das Tischchen. Grammatical gender follows the form of the word, not the sex of the person." } },
    { q: { zh: "das Öl(油)+ die Lampe(灯)= Öllampe(油灯)。它的性是?", en: "das Öl, oil, + die Lampe, lamp = Öllampe, oil lamp. Its gender?" },
      opts: [{ zh: "die,随最后的 Lampe", en: "die, from the last part, Lampe" }, { zh: "das,随最前的 Öl", en: "das, from the first part, Öl" }, { zh: "der,复合词一律阳性", en: "der, since compounds are always masculine" }, { zh: "das,无生命的东西一律中性", en: "das, since lifeless things are always neuter" }], a: 0,
      why: { zh: "复合词的性由最后一个成分决定:die Öllampe。同理 der Vater + das Land → das Vaterland。der Stuhl、die Insel 也都是无生命的东西,可见「无生命就是中性」不成立。", en: "A compound takes the gender of its last element: die Öllampe. Likewise der Vater + das Land → das Vaterland. Der Stuhl and die Insel are lifeless too, so lifeless does not mean neuter." } },
    { q: { zh: "Theseus nimmt das schwert. 这句里哪个词的大小写错了?", en: "Theseus nimmt das schwert. Which word has the wrong capitalisation?" }, opts: ["schwert", "Theseus", "nimmt", "das"], a: 0,
      why: { zh: "德语所有名词首字母大写:das Schwert。nimmt 是动词,das 是句中的冠词,都应小写;Theseus 是专有名词,本来就大写。", en: "Every German noun takes a capital: das Schwert. Nimmt is a verb and das an article inside the sentence, so both stay lower-case; Theseus is a name and is capitalised anyway." } },
    { q: { zh: "填空:___ Hoffnung stirbt zuletzt.(希望最后才死)", en: "Fill the gap: ___ Hoffnung stirbt zuletzt — hope dies last." }, opts: ["Die", "Der", "Das", "Den"], a: 0,
      why: { zh: "-ung 结尾的名词一律阴性,主格冠词是 die。这句德语谚语正合潘多拉的故事:灾祸全都从她的罐子(俗称「魔盒」)里飞走,只有希望留在里面。", en: "Nouns in -ung are always feminine, so the nominative article is die. The saying fits Pandora: every evil flew out of her jar, and hope alone stayed inside." } },
    { q: { zh: "哪个搭配是错的?", en: "Which article–noun pair is wrong?" }, opts: ["das Freundschaft", "der Lehrling", "das Element", "die Nation"], a: 0,
      why: { zh: "-schaft 结尾一律阴性:die Freundschaft。其余三个都对:-ling 阳性,-ment 多为中性,-ion 阴性。", en: "Nouns in -schaft are always feminine: die Freundschaft. The other three are right: -ling is masculine, -ment mostly neuter, -ion feminine." } },
    { q: { zh: "下面哪个名词是阳性?", en: "Which of these nouns is masculine?" }, opts: ["Winter", "Fenster", "Wolke", "Stille"], a: 0,
      why: { zh: "季节、月份、星期都是阳性:der Winter、der Mai、der Montag。Fenster 虽然也以 -er 结尾,却不是「做事的人」,它是中性 das Fenster(借自拉丁语 fenestra)。", en: "Seasons, months and days are masculine: der Winter, der Mai, der Montag. Fenster also ends in -er, but it is no agent; it is neuter, das Fenster, borrowed from Latin fenestra." } },
    { q: { zh: "der、die、das 与下面哪一组同源?", en: "Der, die, das share their origin with:" },
      opts: [{ zh: "希腊语冠词 ho、hē、to", en: "the Greek article ho, hē, to" }, { zh: "法语冠词 le、la", en: "the French articles le, la" }, { zh: "拉丁语指示代词 hic、haec、hoc", en: "the Latin demonstratives hic, haec, hoc" }, { zh: "意大利语冠词 il、la", en: "the Italian articles il, la" }], a: 0,
      why: { zh: "两者都出自印欧语的指示代词 *so、*seh₂、*tod。法语 le、la 和意大利语 il、la 来自拉丁语 ille「那个」,是罗曼语后来另起炉灶造出的冠词。", en: "Both come from the Indo-European demonstrative *so, *seh₂, *tod. French le, la and Italian il, la come from Latin ille, that: Romance built its articles later, from a different word." } },
  ] },

{ id: "de_plural", icon: "📜",
  name: { zh: "复数 · 九头蛇许德拉", en: "Plurals · The Hydra" },
  scene: { zh: "赫拉克勒斯砍下许德拉的一个头 der Kopf,原处立刻长出两个 die Köpfe。德语的复数也这样难以预料:有的加 -e,有的加 -er,有的加 -(e)n 或 -s,有的什么都不加,还常常顺手把元音变成 ä、ö、ü。只有冠词最老实:复数主格一律 die。",
           en: "Heracles strikes off one of the Hydra's heads, der Kopf, and two grow in its place: die Köpfe. German plurals grow just as unpredictably — with -e, -er, -(e)n, -s or nothing at all, often with an umlaut on the vowel. Only the article behaves: in the nominative plural it is always die." },
  rule: { zh: "复数主格定冠词一律 die。五种模式:① -e,常带变音(Tag → Tage,Hand → Hände);② -er,能变音的必变音(Buch → Bücher,Mann → Männer);③ -(e)n,多数阴性(Frau → Frauen,Blume → Blumen);④ -s,多为外来词(Auto → Autos);⑤ 不加词尾,有时只变音(Lehrer → Lehrer,Vater → Väter,Mutter → Mütter)。名词都要连冠词和复数一起背:der Kopf, die Köpfe。",
          en: "In the nominative the plural article is always die. Five patterns: -e, often with umlaut (Tag → Tage, Hand → Hände); -er, umlauted wherever possible (Buch → Bücher, Mann → Männer); -(e)n, the pattern of most feminines (Frau → Frauen, Blume → Blumen); -s, mostly loanwords (Auto → Autos); no ending, sometimes umlaut alone (Lehrer → Lehrer, Vater → Väter, Mutter → Mütter). Learn every noun with article and plural: der Kopf, die Köpfe." },
  table: { cap: { zh: "五种复数", en: "The five plural patterns" },
    head: [{ zh: "模式", en: "Pattern" }, { zh: "单数", en: "Singular" }, { zh: "复数", en: "Plural" }, { zh: "常见于", en: "Typical of" }],
    rows: [["① -e", "der Tag · das Schiff", "die Tage · die Schiffe", { zh: "阳性、中性最常见", en: "commonest with masculines and neuters" }],
           ["① -e + 变音|① -e + umlaut", "der Kopf · die Hand", "die Köpfe · die Hände", { zh: "许多单音节阳性,少数阴性", en: "many one-syllable masculines, a few feminines" }],
           ["② -er + 变音|② -er + umlaut", "das Buch · der Mann", "die Bücher · die Männer", { zh: "多为单音节中性", en: "mostly one-syllable neuters" }],
           ["③ -n", "die Blume · die Insel", "die Blumen · die Inseln", { zh: "以 -e、-el 结尾的阴性", en: "feminines in -e and -el" }],
           ["③ -en", "die Frau · die Hoffnung", "die Frauen · die Hoffnungen", { zh: "其他阴性大多如此;-ung、-heit 等一律如此", en: "most other feminines; always for -ung, -heit and the like" }],
           ["③ -en(阳性)|③ -en (masculine)", "der Held · der Bär", "die Helden · die Bären", { zh: "少数阳性,多指人或动物", en: "a few masculines, mostly people and animals" }],
           ["④ -s", "das Auto · das Echo", "die Autos · die Echos", { zh: "外来词,尤其以 -a、-o 结尾的", en: "loanwords, especially in -a and -o" }],
           ["⑤ 无词尾|⑤ no ending", "der Lehrer · das Mädchen", "die Lehrer · die Mädchen", { zh: "以 -er、-el、-chen 结尾的阳性和中性", en: "masculines and neuters in -er, -el, -chen" }],
           ["⑤ 只变音|⑤ umlaut only", "der Vater · die Mutter", "die Väter · die Mütter", { zh: "一些阳性,加上阴性 Mutter、Tochter", en: "some masculines, plus feminine Mutter and Tochter" }]] },
  notes: { zh: "变音来自「i 变音」:古高地德语 gast(客人)的复数是 gesti,词尾的 i 把 a 同化成了 e。后来 i 弱化成 e,变了的元音却留下来,自己成了复数标记——Gast → Gäste。英语 foot/feet、mouse/mice、man/men 是同一个过程。-er 复数原是少数中性词的词干后缀(古高地德语 lamb → lembir),与拉丁语 genus、generis 的 -er- 同出印欧语 *-es-;英语 children 的 r 是它的残迹,-en 复数在英语里只剩 oxen 等几个。",
          en: "Umlaut comes from i-mutation. Old High German gast, guest, had the plural gesti: the ending's i drew the a to e. The i later faded to e, but the changed vowel stayed and became a plural sign by itself: Gast → Gäste. English foot/feet, mouse/mice, man/men show the same process. The -er plural was a stem suffix of a few neuters (lamb, plural lembir): Indo-European *-es-, the -er- of Latin genus, generis. Children keeps its r, oxen the old -en." },
  ex: [
    { q: { zh: "die Hand(手)的复数是?", en: "The plural of die Hand, the hand?" }, opts: ["die Hände", "die Handen", "die Hands", "die Hande"], a: 0,
      why: { zh: "Hand 属于「-e + 变音」:die Hände。大多数阴性名词加 -(e)n,但 Hand 是例外,和 die Nacht → die Nächte、die Maus → die Mäuse 是一伙;-s 多给外来词。", en: "Hand takes -e plus umlaut: die Hände. Most feminines add -(e)n, but Hand goes with die Nacht → die Nächte and die Maus → die Mäuse; -s is mostly for loanwords." } },
    { q: { zh: "奥林匹斯众神:der Gott(神)的复数是?", en: "The gods of Olympus: the plural of der Gott?" }, opts: ["die Götter", "die Götte", "die Gotten", "die Gotts"], a: 0,
      why: { zh: "Gott 属于 -er 类,能变音的必定变音:die Götter,就像 der Mann → die Männer、das Buch → die Bücher。Götte、Gotten 都是套错了复数类型。", en: "Gott belongs to the -er class, and an -er plural umlauts whatever it can: die Götter, like der Mann → die Männer and das Buch → die Bücher. Götte and Gotten put it in the wrong class." } },
    { q: { zh: "奥德修斯漂过许多岛。die Insel(岛)的复数是?", en: "Odysseus drifts past many islands. The plural of die Insel?" }, opts: ["die Inseln", "die Inselen", "die Insel", "die Insels"], a: 0,
      why: { zh: "阴性名词大多加 -(e)n,以 -el、-e 结尾的只加 -n:die Inseln、die Fackeln、die Wellen。零词尾是以 -el 结尾的阳性、中性的做法(der Engel → die Engel)。", en: "Most feminines add -(e)n, and those in -el or -e add just -n: die Inseln, die Fackeln, die Wellen. A zero plural is what masculines and neuters in -el do (der Engel → die Engel)." } },
    { q: { zh: "填空:Theseus hat zwei ___: Aigeus und Poseidon.", en: "Fill the gap: Theseus hat zwei ___: Aigeus und Poseidon." }, opts: ["Väter", "Vater", "Vaters", "Vatern"], a: 0,
      why: { zh: "Vater 属于「无词尾 + 变音」:der Vater → die Väter,和 die Mutter → die Mütter、der Bruder → die Brüder 一样。Vater 是单数,Vaters 是单数属格。传说埃特拉同一夜与埃勾斯和波塞冬结合,所以忒修斯有两位父亲。", en: "Vater takes no ending but umlauts: der Vater → die Väter, like die Mutter → die Mütter and der Bruder → die Brüder. Vater is singular, Vaters a genitive singular. Legend says Aethra lay with Aegeus and Poseidon on one night, so Theseus had two fathers." } },
    { q: { zh: "das Echo(回声,也是仙女厄科的名字)→ die Echos。这是哪种复数?", en: "das Echo (also the name of the nymph Echo) → die Echos. Which plural is this?" },
      opts: [{ zh: "-s 复数,多见于外来词", en: "the -s plural, typical of loanwords" }, { zh: "-e 复数,阳性最常见", en: "the -e plural, commonest with masculines" }, { zh: "变音复数", en: "the umlaut plural" }, { zh: "中性名词一律加 -s", en: "every neuter noun adds -s" }], a: 0,
      why: { zh: "Echo 源自希腊语 ēchō,外来词、尤其以 -a、-o 结尾的多用 -s:das Auto → die Autos。中性名词并不都加 -s:das Schiff → die Schiffe、das Buch → die Bücher。", en: "Echo comes from Greek ēchō, and loanwords, especially in -a and -o, tend to take -s: das Auto → die Autos. Neuters in general do not: das Schiff → die Schiffe, das Buch → die Bücher." } },
    { q: { zh: "哪个复数是错的?", en: "Which plural is wrong?" }, opts: ["die Mutters", "die Väter", "die Lehrer", "die Frauen"], a: 0,
      why: { zh: "Mutter 的复数是 die Mütter——不加词尾,只变音;-s 复数主要属于外来词。die Lehrer 不加词尾是对的:以 -er 结尾的阳性名词复数通常与单数同形。", en: "The plural of Mutter is die Mütter — no ending, only an umlaut; the -s plural is mainly for loanwords. Die Lehrer with no ending is right: masculines in -er usually look the same in the plural." } },
    { q: { zh: "填空:___ Helden rudern die Argo.(英雄们划着阿尔戈号)", en: "Fill the gap: ___ Helden rudern die Argo — the heroes row the Argo." }, opts: ["Die", "Der", "Das", "Den"], a: 0,
      why: { zh: "复数主格的定冠词一律是 die,不管单数是 der Held、die Frau 还是 das Schiff。Held 是阳性,复数照样是 die Helden。", en: "The nominative plural article is always die, whether the singular is der Held, die Frau or das Schiff. Held is masculine, yet its plural is die Helden." } },
    { q: { zh: "英语里哪一对单复数,和德语 Gast → Gäste 是同一种变化?", en: "Which English singular–plural pair shows the same change as German Gast → Gäste?" }, opts: ["mouse / mice", "house / houses", "cat / cats", "sheep / sheep"], a: 0,
      why: { zh: "mouse/mice 来自古英语 mūs/mȳs:复数原有词尾 -iz,其中的 i 把前面的元音同化;后来词尾消失,变了的元音留了下来。德语 die Maus → die Mäuse 正是同一个词、同一种变化。", en: "Mouse and mice go back to Old English mūs, mȳs: the plural once ended in -iz, whose i pulled the vowel forward; the ending vanished and the changed vowel stayed. German die Maus → die Mäuse is the same word with the same change." } },
  ] },

{ id: "de_kasus", icon: "⚖️",
  name: { zh: "四个格 · 帕里斯的金苹果", en: "The four cases · The apple of Paris" },
  scene: { zh: "在珀琉斯与忒提斯的婚宴上,不和女神厄里斯扔下一只金苹果,上面写着「献给最美者」。帕里斯把它判给了阿佛洛狄忒。四个格在这里一次到齐:Paris(谁?)gibt der Göttin(给谁?)den Apfel(什么?)——那是 der Apfel der Zwietracht(谁的?),不和之果。",
           en: "At the wedding of Peleus and Thetis, Eris, goddess of discord, throws in a golden apple marked ‘for the fairest’. Paris awards it to Aphrodite, and all four cases appear at once: Paris (who?) gibt der Göttin (to whom?) den Apfel (what?) — der Apfel der Zwietracht (whose?), the apple of discord." },
  rule: { zh: "德语有四个格,靠疑问词来认:主格 Nominativ(wer? 谁)作主语;宾格 Akkusativ(wen? 谁、was? 什么)作直接宾语;与格 Dativ(wem? 给谁)作间接宾语;属格 Genitiv(wessen? 谁的)表示所属。定冠词随格变化。要点:① 宾格只有阳性变,der → den;② 复数与格名词加 -n:den Kindern(-n、-s 结尾的不加);③ 阳性、中性属格名词加 -(e)s:des Mannes、des Schiffes(Held 等少数阳性例外:des Helden)。",
          en: "Four cases and their questions: nominative (wer? who), subject; accusative (wen? whom, was? what), direct object; dative (wem? to whom), indirect object; genitive (wessen? whose), possession. The article shows the case. Three rules: in the accusative only der changes, to den; dative plurals add -n, den Kindern (not after -n or -s); masculine and neuter genitives add -(e)s, des Mannes, des Schiffes (a few like Held take -en: des Helden)." },
  table: { cap: { zh: "定冠词的四个格", en: "The definite article in four cases" },
    head: [{ zh: "格", en: "Case" }, { zh: "阳性", en: "Masc." }, { zh: "阴性", en: "Fem." }, { zh: "中性", en: "Neut." }, { zh: "复数", en: "Plural" }, { zh: "问句与作用", en: "Question and role" }],
    rows: [["主格 Nominativ|Nominative", "der Mann", "die Frau", "das Kind", "die Kinder", { zh: "wer? 谁——主语", en: "wer? who — subject" }],
           ["宾格 Akkusativ|Accusative", "den Mann", "die Frau", "das Kind", "die Kinder", { zh: "wen? was? 谁、什么——直接宾语", en: "wen? was? whom, what — direct object" }],
           ["与格 Dativ|Dative", "dem Mann", "der Frau", "dem Kind", "den Kindern", { zh: "wem? 给谁——间接宾语", en: "wem? to whom — indirect object" }],
           ["属格 Genitiv|Genitive", "des Mannes", "der Frau", "des Kindes", "der Kinder", { zh: "wessen? 谁的——所属", en: "wessen? whose — possession" }]] },
  notes: { zh: "德语管「格」叫 Fall,是拉丁语 casus「落下」的仿译,casus 又仿译希腊语 ptōsis;学校里也叫 Werfall、Wenfall、Wemfall、Wesfall。四个格是印欧语八格的残余:拉丁语留下六个,英语只剩代词和所有格 's 里的痕迹——who、whom、whose 正对应 wer、wem、wessen。den 的 -n 和希腊语冠词 tón 的 -n 一样,来自印欧语宾格 *-m,拉丁语 puellam 还保留着 -m;dem 的 -m 和英语 him(原是与格)的 -m 同出一源。",
          en: "German calls a case Fall, a loan-translation of Latin casus, a falling, itself rendering Greek ptōsis; schools also say Werfall, Wenfall, Wemfall, Wesfall. The four remain of eight Indo-European cases: Latin kept six, English only traces in pronouns and possessive 's — who, whom, whose answer to wer, wem, wessen. The -n of den, like that of Greek tón, is the accusative *-m kept in Latin puellam; the -m of dem is that of him, once a dative too." },
  ex: [
    { q: { zh: "填空:Paris gibt ___ Göttin den Apfel.(帕里斯把苹果给女神)", en: "Fill the gap: Paris gibt ___ Göttin den Apfel — Paris gives the goddess the apple." }, opts: ["der", "die", "dem", "den"], a: 0,
      why: { zh: "「给谁」用与格(wem?),阴性与格冠词是 der。die 是阴性主格或宾格;dem 只属于阳性和中性。", en: "To whom is the dative (wem?), and the feminine dative article is der. Die is the feminine nominative or accusative; dem belongs only to masculines and neuters." } },
    { q: { zh: "填空:Der Held tötet ___ Minotaurus.", en: "Fill the gap: Der Held tötet ___ Minotaurus." }, opts: ["den", "der", "dem", "des"], a: 0,
      why: { zh: "被杀的是直接宾语,用宾格(wen?)。阳性是唯一在宾格里变形的:der → den。照搬主格 der 是最常见的错误。", en: "The one killed is the direct object, in the accusative (wen?). The masculine is the only gender that changes there: der → den. Keeping the nominative der is the commonest slip." } },
    { q: { zh: "填空:Ariadne ist die Tochter ___.(国王的女儿)", en: "Fill the gap: Ariadne ist die Tochter ___ — the king's daughter." }, opts: ["des Königs", "der König", "dem König", "den Königs"], a: 0,
      why: { zh: "「谁的」用属格(wessen?):阳性属格冠词 des,名词再加 -(e)s,即 des Königs。只改冠词或只改名词都不完整。", en: "Whose is the genitive (wessen?): the masculine article des, plus -(e)s on the noun: des Königs. Changing only the article, or only the noun, is not enough." } },
    { q: { zh: "填空:Orpheus singt den ___ ein Lied.(俄耳甫斯给动物们唱歌)", en: "Fill the gap: Orpheus singt den ___ ein Lied — Orpheus sings the animals a song." }, opts: ["Tieren", "Tiere", "Tier", "Tiers"], a: 0,
      why: { zh: "「给谁」是与格,复数与格的名词要加 -n:den Tieren、den Kindern。den Tiere 漏掉了这个 -n。已经以 -n 或 -s 结尾的复数不再加(den Frauen、den Autos)。", en: "To whom is the dative, and a dative plural noun adds -n: den Tieren, den Kindern. Den Tiere forgets that -n. Plurals already ending in -n or -s add nothing (den Frauen, den Autos)." } },
    { q: { zh: "Perseus zeigt dem König das Haupt der Medusa. 句中 das Haupt 是什么格?", en: "Perseus zeigt dem König das Haupt der Medusa. What case is das Haupt?" },
      opts: [{ zh: "宾格:它是被展示的东西", en: "accusative: it is the thing shown" }, { zh: "主格:因为冠词是 das", en: "nominative, because the article is das" }, { zh: "与格:因为它跟在 dem König 后面", en: "dative, because it follows dem König" }, { zh: "属格:因为后面跟着 der Medusa", en: "genitive, because der Medusa follows it" }], a: 0,
      why: { zh: "中性的主格和宾格同形,都是 das,要看作用:被展示的东西是直接宾语,所以是宾格;主语是 Perseus。珀耳修斯正是用美杜莎的头把国王波吕得克忒斯变成了石头。", en: "In the neuter, nominative and accusative share the form das, so the role decides: the thing shown is the direct object, hence accusative; the subject is Perseus — who used Medusa's head to turn King Polydectes to stone." } },
    { q: { zh: "哪一句有错?", en: "Which sentence contains an error?" }, opts: ["Ich sehe der Stier.", "Ich sehe den Stier.", "Ich sehe die Schlange.", "Ich sehe das Schiff."], a: 0,
      why: { zh: "sehen 的宾语用宾格,阳性宾格冠词是 den:Ich sehe den Stier。阴性 die、中性 das 在宾格里不变,所以另外两句是对的。", en: "The object of sehen is accusative, and the masculine accusative article is den: Ich sehe den Stier. Feminine die and neuter das do not change in the accusative, so the other two are right." } },
    { q: { zh: "定冠词在宾格里,哪一列和主格不同?", en: "In the accusative, which column of the article differs from the nominative?" },
      opts: [{ zh: "只有阳性:der → den", en: "only the masculine: der → den" }, { zh: "只有阴性:die → der", en: "only the feminine: die → der" }, { zh: "阳性和中性都变", en: "masculine and neuter both change" }, { zh: "四列全都变", en: "all four columns change" }], a: 0,
      why: { zh: "宾格里只有阳性变:der → den。阴性 die、中性 das、复数 die 都与主格相同。这是四个格里最该先记住的一条。", en: "In the accusative only the masculine changes: der → den. Feminine die, neuter das and plural die stay as in the nominative — the first thing to learn about the four cases." } },
    { q: { zh: "古英语 hwā、hwām、hwæs 分别是「谁」的主格、与格、属格。从词源看,英语 whom 对应德语的:", en: "Old English hwā, hwām, hwæs were the nominative, dative and genitive of who. By origin, English whom matches German:" }, opts: ["wem", "wen", "wer", "wessen"], a: 0,
      why: { zh: "whom 来自古英语与格 hwām,德语对应的就是与格 wem,两者的 -m 同出一源(还有 him ~ ihm)。wen 对应的是古英语宾格 hwone,这个形式后来被 whom 取代了。", en: "Whom comes from the Old English dative hwām, so its German match is the dative wem, with the same -m (compare him and ihm). Wen matches the Old English accusative hwone, which whom later replaced." } },
  ] },

{ id: "de_ein", icon: "🎁",
  name: { zh: "不定冠词与物主代词 · 珀耳修斯的礼物", en: "Ein-words · The gifts of Perseus" },
  scene: { zh: "珀耳修斯要去斩美杜莎,神与仙女赠礼:赫尔墨斯给 ein Sichelschwert(镰刀剑),雅典娜借 einen Schild(盾),仙女送 eine Tasche(袋子)和隐身头盔。ein 和 der 一样随性、格而变;mein Schwert(我的剑)的词尾也和 ein Schwert 相同。",
           en: "Perseus sets out to behead Medusa, and gods and nymphs equip him: Hermes gives him ein Sichelschwert, a sickle-sword; Athena lends him einen Schild, a shield; the nymphs give him eine Tasche, a bag, and a helmet of invisibility. Ein changes with gender and case just as der does, and mein Schwert, my sword, has exactly the endings of ein Schwert." },
  rule: { zh: "不定冠词随性、格变化:阳性 ein、einen、einem、eines,阴性 eine、eine、einer、einer,中性 ein、ein、einem、eines。ein 没有复数;kein(没有)变化相同,复数 keine。物主代词 mein、dein、sein(他的)、ihr(她的)、unser、euer、ihr(他们的)、Ihr(您的)也用这套词尾,统称 ein 类词;euer 加词尾时去掉 e:eure。关键:ein 类词在阳性主格、中性主格和宾格不加词尾:ein Helm、mein Schwert。",
          en: "Ein declines by gender and case: masculine ein, einen, einem, eines; feminine eine, eine, einer, einer; neuter ein, ein, einem, eines. It has no plural, but kein, no, declines alike and has keine. The possessives mein, dein, sein, ihr, unser, euer, ihr, Ihr take the same endings (euer drops its e: eure). Key point: ein-words are bare in the masculine nominative and the neuter nominative and accusative." },
  table: { cap: { zh: "ein · kein · mein 的变格", en: "ein, kein, mein through the cases" },
    head: [{ zh: "格", en: "Case" }, { zh: "阳性", en: "Masc." }, { zh: "阴性", en: "Fem." }, { zh: "中性", en: "Neut." }, { zh: "复数", en: "Plural" }],
    rows: [["主格|Nominative", "ein Helm", "eine Tasche", "ein Schwert", "keine Schuhe"],
           ["宾格|Accusative", "einen Helm", "eine Tasche", "ein Schwert", "keine Schuhe"],
           ["与格|Dative", "einem Helm", "einer Tasche", "einem Schwert", "keinen Schuhen"],
           ["属格|Genitive", "eines Helmes", "einer Tasche", "eines Schwertes", "keiner Schuhe"],
           ["mein 主格|mein, nominative", "mein", "meine", "mein", "meine"],
           ["mein 宾格|mein, accusative", "meinen", "meine", "mein", "meine"],
           ["unser 主格|unser, nominative", "unser", "unsere", "unser", "unsere"],
           ["euer 主格|euer, nominative", "euer", "eure", "euer", "eure"]] },
  notes: { zh: "ein 本来就是数词「一」:原始日耳曼语 *ainaz,与拉丁语 ūnus(古拉丁语 oinos)同源。英语也一样,只是古英语 ān 弱读成 an,又在辅音前丢掉 n 成了 a;德语的冠词和数词至今同形。kein 一般认为来自古高地德语 nih ein「连一个也不」等形式的融合(细节存疑)。mein、dein、sein 与英语 mine、thine 同源,本是由人称代词派生的形容词,和 ein 一样保留了古老的无词尾形式,所以两者词尾相同。",
          en: "Ein is the numeral one: Proto-Germanic *ainaz, kin to Latin ūnus (Old Latin oinos), and German article and numeral are still one word. Old English ān weakened to an, then a before consonants. Kein is usually traced to a blend of forms like Old High German nih ein, not even one (details disputed). Mein, dein, sein match English mine, thine: pronoun-based adjectives which, like ein, kept the old endingless forms, hence the shared endings." },
  ex: [
    { q: { zh: "填空:Die Nymphen geben ihm ___ Helm.(仙女们给他一顶头盔)", en: "Fill the gap: Die Nymphen geben ihm ___ Helm — the nymphs give him a helmet." }, opts: ["einen", "ein", "einem", "einer"], a: 0,
      why: { zh: "Helm 是阳性,在句中是直接宾语,要用宾格 einen。ein 是阳性主格,在宾格里不能用;einem 是与格。这顶冥王的隐身头盔让珀耳修斯躲过了戈耳工姐妹的追杀。", en: "Helm is masculine and the direct object, so it takes the accusative einen. Ein is the masculine nominative and will not do here; einem is dative. This helmet of Hades hid Perseus from Medusa's Gorgon sisters." } },
    { q: { zh: "填空:Medusa hat ___ Freunde.(美杜莎没有朋友)", en: "Fill the gap: Medusa hat ___ Freunde — Medusa has no friends." }, opts: ["keine", "kein", "keinen", "keiner"], a: 0,
      why: { zh: "ein 没有复数,kein 却有:复数主格和宾格都是 keine。kein 是阳性主格或中性的形式;keinen 是阳性宾格或复数与格。", en: "Ein has no plural, but kein does: keine in the nominative and accusative plural. Kein is the masculine nominative or neuter form; keinen is masculine accusative or dative plural." } },
    { q: { zh: "填空:Penelope gibt ___ Sohn einen Rat.(珀涅罗珀给她的儿子一个建议)", en: "Fill the gap: Penelope gibt ___ Sohn einen Rat — Penelope gives her son advice." }, opts: ["ihrem", "ihren", "ihr", "ihres"], a: 0,
      why: { zh: "「给谁」用与格,阳性与格词尾是 -em:ihrem Sohn,和 einem Sohn 完全一样。ihren 是宾格,而这句的宾格位置已经给了 einen Rat。", en: "To whom is the dative, and the masculine dative ending is -em: ihrem Sohn, exactly like einem Sohn. Ihren is accusative, and the accusative slot is already taken by einen Rat." } },
    { q: { zh: "珀耳修斯说:「这是我的剑。」Das ist ___ Schwert.", en: "Perseus says: Das ist ___ Schwert — this is my sword." }, opts: ["mein", "meines", "meine", "meinen"], a: 0,
      why: { zh: "Schwert 是中性,中性主格(和宾格)正是 ein 类词不加词尾的地方:mein Schwert,就像 ein Schwert。meines 是属格,meine 属于阴性或复数。", en: "Schwert is neuter, and the neuter nominative (and accusative) is where ein-words take no ending: mein Schwert, just like ein Schwert. Meines is genitive; meine is feminine or plural." } },
    { q: { zh: "哪个形式是错的?", en: "Which form is wrong?" }, opts: ["einen Schwert", "ein Schwert", "einem Schwert", "eines Schwertes"], a: 0,
      why: { zh: "中性的宾格和主格同形,都是 ein:Er hat ein Schwert。宾格词尾 -en 只属于阳性(einen Helm)。其余三个分别是主格/宾格、与格、属格,都对。", en: "The neuter accusative equals the nominative: ein — Er hat ein Schwert. The accusative -en belongs to masculines only (einen Helm). The other three — nominative or accusative, dative, genitive — are all correct." } },
    { q: { zh: "ein 类词在哪三处没有词尾?", en: "In which three slots do ein-words have no ending?" },
      opts: [{ zh: "阳性主格、中性主格、中性宾格", en: "masculine nominative, neuter nominative and accusative" }, { zh: "阴性主格、阴性宾格、复数主格", en: "feminine nominative and accusative, plural nominative" }, { zh: "所有的与格", en: "every dative" }, { zh: "阳性宾格、中性与格、阴性属格", en: "masculine accusative, neuter dative and feminine genitive" }], a: 0,
      why: { zh: "ein、kein 和所有物主代词在这三处光秃秃:ein Helm(阳性主格)、ein Schwert(中性主格、宾格)。其他位置的词尾和 der、die、das 的末尾对应:einen ~ den、einem ~ dem、einer ~ der。", en: "Ein, kein and every possessive are bare in these three slots: ein Helm (masculine nominative), ein Schwert (neuter nominative and accusative). Elsewhere the ending echoes the article: einen ~ den, einem ~ dem, einer ~ der." } },
    { q: { zh: "填空:Argonauten, wo ist ___ Schiff?(阿尔戈英雄们,你们的船在哪?)", en: "Fill the gap: Argonauten, wo ist ___ Schiff? — Argonauts, where is your ship?" }, opts: ["euer", "eure", "euren", "eures"], a: 0,
      why: { zh: "中性主格不加词尾:euer Schiff。只有加了词尾时 euer 才丢掉中间的 e:eure Insel、euren Helm。", en: "The neuter nominative takes no ending: euer Schiff. Only when an ending is added does euer drop its middle e: eure Insel, euren Helm." } },
    { q: { zh: "不定冠词 ein 和下面哪组词同源?", en: "The indefinite article ein is related to:" },
      opts: [{ zh: "英语 one 和拉丁语 ūnus", en: "English one and Latin ūnus" }, { zh: "英语 in 和拉丁语 in", en: "English in and Latin in" }, { zh: "英语 end 和德语 Ende", en: "English end and German Ende" }, { zh: "希腊语 en「在…里」", en: "Greek en, in" }], a: 0,
      why: { zh: "ein 本来就是数词「一」,出自原始日耳曼语 *ainaz,与英语 one、拉丁语 ūnus(古拉丁语 oinos)同源。英语的 an、a 也是 one 弱读而来。", en: "Ein is simply the numeral one, from Proto-Germanic *ainaz, kin to English one and Latin ūnus (Old Latin oinos). English an and a are weakened forms of that same one." } },
  ] },

{ id: "de_praesens", icon: "🔥",
  name: { zh: "动词现在时 · 普罗米修斯的火", en: "Present tense · Prometheus' fire" },
  scene: { zh: "普罗米修斯偷来天火,交给人类:Prometheus gibt den Menschen das Feuer。宙斯看在眼里:Zeus sieht alles。动词词尾随主语而变——ich gebe、du gibst、er gibt;有些动词还在 du 和 er 里换元音:sehen → sieht。",
           en: "Prometheus steals fire from heaven and gives it to mankind: Prometheus gibt den Menschen das Feuer. Zeus sees it all: Zeus sieht alles. A German verb changes its ending with its subject — ich gebe, du gibst, er gibt — and some verbs change their vowel too, in du and er only: sehen → sieht." },
  rule: { zh: "现在时词尾:ich -e、du -st、er/sie/es -t、wir -en、ihr -t、sie/Sie -en。sein、haben、werden 不规则。许多强变化动词只在 du、er/sie/es 换元音:e → i(gibt、spricht),e → ie(sieht、liest),a → ä(fährt、schläft)。词干以 -t、-d 结尾加 e:du arbeitest、er findet,换元音的不加(er hält)。熟人一个用 du,几个用 ihr;尊称 Sie 大写,用第三人称复数。",
          en: "Endings: ich -e, du -st, er/sie/es -t, wir -en, ihr -t, sie/Sie -en. Sein, haben, werden are irregular. Many strong verbs change their vowel in du and er/sie/es only: e → i (gibt, spricht), e → ie (sieht, liest), a → ä (fährt, schläft). Stems in -t, -d add e: du arbeitest, er findet — but not after a vowel change: er hält. Du is one friend, ihr several; formal Sie is capitalised and takes the third person plural." },
  table: { cap: { zh: "规则动词、三个不规则动词与两个换元音动词", en: "A regular verb, three irregulars and two vowel-changers" },
    head: [{ zh: "人称", en: "Person" }, { zh: "machen 做", en: "machen, do" }, { zh: "sein 是", en: "sein, be" }, { zh: "haben 有", en: "haben, have" }, { zh: "werden 成为", en: "werden, become" }, { zh: "geben 给(e→i)", en: "geben, give (e→i)" }, { zh: "fahren 行驶(a→ä)", en: "fahren, travel (a→ä)" }],
    rows: [["ich", "mache", "bin", "habe", "werde", "gebe", "fahre"],
           ["du", "machst", "bist", "hast", "wirst", "gibst", "fährst"],
           ["er / sie / es", "macht", "ist", "hat", "wird", "gibt", "fährt"],
           ["wir", "machen", "sind", "haben", "werden", "geben", "fahren"],
           ["ihr", "macht", "seid", "habt", "werdet", "gebt", "fahrt"],
           ["sie / Sie", "machen", "sind", "haben", "werden", "geben", "fahren"]] },
  notes: { zh: "德语的人称词尾和拉丁语同出印欧语:er gibt 的 -t 对应拉丁语 amat 的 -t,早期英语 he giveth 的 -th 也是它;第三人称复数 -en 原是 -nt,古高地德语 sie gebant 还留着。ist 与拉丁语 est、英语 is 同源,bin 则与英语 be 同根。gibt 的 i 也有来历:古高地德语 du gibis、er gibit 里,词尾的 i 把 e 抬成了 i;fährt 的 ä 就是第二站讲过的 i 变音。动词的德语旧称是 Zeitwort「时间词」,因为它标出时态。",
          en: "German person endings share an Indo-European source with Latin: the -t of er gibt is the -t of amat and the -th of early English he giveth, and the third-person plural -en was once -nt (Old High German sie gebant). Ist matches Latin est and English is; bin shares its root with be. In Old High German du gibis, er gibit the i of the ending raised e to i; fährt shows the i-umlaut of station two. The verb's old German name is Zeitwort, time word." },
  ex: [
    { q: { zh: "填空:Prometheus ___ den Menschen das Feuer.(geben)", en: "Fill the gap: Prometheus ___ den Menschen das Feuer (geben)." }, opts: ["gibt", "gebt", "gibst", "geben"], a: 0,
      why: { zh: "geben 在 du 和 er/sie/es 里把 e 变成 i:du gibst、er gibt。gebt 是 ihr 的形式——忘了换元音就会写成它;gibst 是 du 的形式。", en: "Geben turns e into i for du and er/sie/es: du gibst, er gibt. Gebt is the ihr form — the slip you make if you forget the vowel change; gibst belongs to du." } },
    { q: { zh: "「忒修斯,你乘船去克里特。」Theseus, du ___ nach Kreta.", en: "Theseus, du ___ nach Kreta — Theseus, you sail to Crete." }, opts: ["fährst", "fahrst", "fährt", "fahren"], a: 0,
      why: { zh: "fahren 在 du 和 er 里 a → ä:du fährst、er fährt。fahrst 漏了变音;fährt 是第三人称。ich 和复数不变:ich fahre、ihr fahrt。", en: "Fahren turns a into ä for du and er: du fährst, er fährt. Fahrst misses the umlaut, and fährt is third person. Ich and the plurals keep a: ich fahre, ihr fahrt." } },
    { q: { zh: "母亲埃特拉对少年忒修斯说:Du ___ ein Held.(你会成为英雄)", en: "Aethra tells the young Theseus: Du ___ ein Held — you will become a hero." }, opts: ["wirst", "werdst", "wird", "werdet"], a: 0,
      why: { zh: "werden 不规则:ich werde、du wirst、er wird、wir werden、ihr werdet。du 的形式里 e 变 i,d 也消失了;werdst 是按规则硬套出来的错形。", en: "Werden is irregular: ich werde, du wirst, er wird, wir werden, ihr werdet. In the du form e becomes i and the d disappears; werdst is the over-regularised mistake." } },
    { q: { zh: "填空:Theseus ___ den Ausgang.(finden)", en: "Fill the gap: Theseus ___ den Ausgang (finden)." }, opts: ["findet", "findt", "findest", "finden"], a: 0,
      why: { zh: "词干以 -d、-t 结尾时,在 -t、-st 前加 e,才念得出来:er findet、du findest、ihr findet。findt 把辅音挤在一起,不合规则;findest 是 du 的形式。", en: "When a stem ends in -d or -t, an e goes in before -t and -st so it can be pronounced: er findet, du findest, ihr findet. Findt jams the consonants together; findest is the du form." } },
    { q: { zh: "填空:Argonauten, ihr ___ mutig!(阿尔戈英雄们,你们真勇敢!)", en: "Fill the gap: Argonauten, ihr ___ mutig! — Argonauts, you are brave!" }, opts: ["seid", "seit", "sind", "ist"], a: 0,
      why: { zh: "sein 的 ihr 形式是 seid,结尾是 d。seit(自从)是介词,读音相同,连德国人自己也常写错。sind 属于 wir 和 sie/Sie。", en: "The ihr form of sein is seid, ending in d. Seit, since, is a preposition pronounced the same — a misspelling even native speakers make. Sind belongs to wir and sie/Sie." } },
    { q: { zh: "尊称 Sie(您)的动词用哪种形式?", en: "Which verb form goes with formal Sie?" },
      opts: [{ zh: "第三人称复数(和 sie「他们」一样)", en: "third person plural, as with sie, they" }, { zh: "第二人称单数(和 du 一样)", en: "second person singular, as with du" }, { zh: "第二人称复数(和 ihr 一样)", en: "second person plural, as with ihr" }, { zh: "第三人称单数(和 sie「她」一样)", en: "third person singular, as with sie, she" }], a: 0,
      why: { zh: "尊称 Sie 大写,动词用第三人称复数:Sie sind、Sie haben,和 sie「他们」同形。对一个熟人说 du,对几个熟人说 ihr。", en: "Formal Sie is capitalised and takes the third person plural: Sie sind, Sie haben — the same forms as sie, they. One friend is du; several friends are ihr." } },
    { q: { zh: "哪个形式是错的?", en: "Which form is wrong?" }, opts: ["du lest", "du liest", "er hilft", "ihr helft"], a: 0,
      why: { zh: "lesen 在 du、er 里 e → ie:du liest、er liest(词干已经以 s 结尾,du 只加 -t)。ihr helft 没错:元音变化只发生在 du 和 er/sie/es。", en: "Lesen turns e into ie for du and er: du liest, er liest (the stem already ends in s, so du adds only -t). Ihr helft is right: the vowel change touches only du and er/sie/es." } },
    { q: { zh: "er ist(他是)的 ist 与下面哪组词同源?", en: "The ist of er ist, he is, is related to:" },
      opts: [{ zh: "拉丁语 est 和英语 is", en: "Latin est and English is" }, { zh: "拉丁语 iste「这个」", en: "Latin iste, this one" }, { zh: "英语 east「东方」", en: "English east, the direction" }, { zh: "希腊语 eis「进入、朝向」", en: "Greek eis, into, towards" }], a: 0,
      why: { zh: "ist、拉丁语 est、希腊语 esti、英语 is 都来自印欧语 *h₁ésti「他是」。连词尾 -t 也是印欧语的 *-ti:拉丁语 amat 的 -t、早期英语 he giveth 的 -th,和德语 er gibt 的 -t 是一家。", en: "Ist, Latin est, Greek esti and English is all go back to Indo-European *h₁ésti, he is. Even the ending -t is Indo-European *-ti: the -t of Latin amat, the -th of early English he giveth and the -t of German er gibt are one family." } },
  ] },
]);

/* Fuga Mythica — German grammar road, stations 6–10 */
GRAM_ADD("de", [
{ id: "de_satz", icon: "🧭",
  name: { zh: "语序 · 奥德修斯与塞壬", en: "Word order · Odysseus and the Sirens" },
  scene: { zh: "塞壬在歌唱,奥德修斯让水手把他绑在桅杆上:Odysseus hört die Sirenen。换个开头——Heute hört Odysseus die Sirenen——hört 仍守在第二位,像罗盘指针一样不动。可 weil 一出现,动词就被赶到句末:…, weil er sie hört。",
           en: "The Sirens are singing, and Odysseus has his men bind him to the mast: Odysseus hört die Sirenen. Start the sentence elsewhere — Heute hört Odysseus die Sirenen — and the verb hört still holds second place, steady as a compass needle. But let weil appear, and the verb is driven to the end: …, weil er sie hört." },
  rule: { zh: "陈述句里变位动词永远在第 2 位。第 1 位只放一个成分:主语、时间、宾语或整个从句;若非主语,主语就退到动词后。一般疑问句动词居首:Hört er die Sirenen?特殊疑问句:疑问词 + 动词,Was hört Odysseus?情态动词 können、müssen、wollen、dürfen、sollen、möchte 占第 2 位,不定式放句末,形成「句框」:Odysseus will die Sirenen hören。dass、weil、wenn、ob 从句前加逗号,连词占左框,变位动词放最后。",
          en: "In a statement the finite verb stands second. Slot 1 holds one element — subject, time, object or a whole clause; a subject not in slot 1 follows the verb. Yes/no questions start with the verb: Hört er die Sirenen? W-questions: Was hört Odysseus? A modal (können, müssen, wollen, dürfen, sollen, möchte) takes slot 2 and sends the infinitive to the end: Odysseus will die Sirenen hören. After a comma, dass, weil, wenn, ob send the finite verb last." },
  table: { cap: { zh: "句子的场域:前场 · 左框 · 中场 · 右框", en: "Sentence fields: prefield · left bracket · middle · right bracket" },
    head: [{ zh: "句型", en: "Clause" }, { zh: "前场(第 1 位)", en: "Prefield (slot 1)" }, { zh: "左框(变位动词或连词)", en: "Left bracket (finite verb or conjunction)" }, { zh: "中场", en: "Middle field" }, { zh: "右框(句末)", en: "Right bracket (end)" }],
    rows: [["陈述句|Statement", "Odysseus", "hört", "die Sirenen", "—"],
           ["时间开头|Time first", "Heute", "hört", "Odysseus die Sirenen", "—"],
           ["特殊疑问句|W-question", "Was", "hört", "Odysseus?", "—"],
           ["一般疑问句|Yes/no question", "(空)|(empty)", "Hört", "Odysseus die Sirenen?", "—"],
           ["情态动词|Modal verb", "Odysseus", "will", "die Sirenen", "hören"],
           ["情态 + 时间|Modal, time first", "Jetzt", "müssen", "die Seeleute", "rudern"],
           ["dass 从句|dass-clause", "(无)|(none)", "dass", "Odysseus die Sirenen", "hört"],
           ["weil 从句|weil-clause", "(无)|(none)", "weil", "er die Sirenen", "hören will"]] },
  notes: { zh: "「动词第二位」是日耳曼语的共同特征:古英语说 Þā cōm hē(于是来了他),现代英语只剩 Here comes the hero 和疑问句 Can you…? 这类残迹。从句里动词居末,通常被看作更古老的语序——拉丁语和重建的原始印欧语都偏爱动词放在句末。主句动词为何偏偏移到第二位,原因存疑:Wackernagel(1892)把它与印欧语「轻读小词放在句中第二位」的规律联系起来。「前场、中场」的场域模型由 Erich Drach 在 1937 年系统提出。",
           en: "Verb-second is a shared Germanic trait: Old English said Þā cōm hē, ‘then came he’, and English still says Here comes the hero and Can you…? Verb-final subordinate clauses are usually seen as older: Latin and reconstructed Indo-European favoured the verb at the end. Why the main-clause verb moved second is disputed; Wackernagel (1892) tied it to the Indo-European habit of putting light words second. Erich Drach set out the field model in 1937." },
  ex: [
    { q: { zh: "「今天忒修斯打败弥诺陶洛斯。」哪句语序正确?", en: "‘Today Theseus defeats the Minotaur.’ Which word order is right?" },
      opts: ["Heute besiegt Theseus den Minotaurus.", "Heute Theseus besiegt den Minotaurus.", "Heute Theseus den Minotaurus besiegt.", "Heute den Minotaurus Theseus besiegt."], a: 0,
      why: { zh: "heute 已经占了第 1 位,变位动词 besiegt 必须紧跟在第 2 位,主语 Theseus 退到动词后面。照英语习惯写成 Heute Theseus besiegt…,动词就落到了第 3 位。", en: "Heute fills slot 1, so the finite verb besiegt must come next and the subject Theseus moves behind it. The English habit, Heute Theseus besiegt…, leaves the verb in third place." } },
    { q: { zh: "「忒修斯什么时候来?」德语怎么问?", en: "‘When is Theseus coming?’ How do you ask it in German?" },
      opts: ["Wann kommt Theseus?", "Theseus wann kommt?", "Wann Theseus kommen?", "Wann kommen Theseus?"], a: 0,
      why: { zh: "特殊疑问句里疑问词占第 1 位,变位动词紧跟在第 2 位:Wann kommt Theseus?照中文语序写成 Theseus wann kommt,动词就跑到了第 3 位。", en: "In a W-question the question word takes slot 1 and the finite verb follows in slot 2: Wann kommt Theseus? Copying the Chinese order, Theseus wann kommt, pushes the verb to third place." } },
    { q: { zh: "「珀涅罗珀能织这块布吗?」哪一句正确?", en: "‘Can Penelope weave the cloth?’ Which is right?" },
      opts: ["Kann Penelope das Tuch weben?", "Kann Penelope weben das Tuch?", "Penelope kann weben das Tuch?", "Kann weben Penelope das Tuch?"], a: 0,
      why: { zh: "一般疑问句把变位动词 kann 放到最前面;情态动词和不定式组成句框,weben 必须留在句末。像英语那样把 weben 紧贴在 kann 后面,是最常见的错误。", en: "A yes/no question puts the finite verb kann first; modal and infinitive form a bracket, so weben must wait at the end. Placing weben right after kann, as English does, is the classic error." } },
    { q: { zh: "Penelope hofft, dass ___.(珀涅罗珀希望奥德修斯很快就来)", en: "Penelope hofft, dass ___. (Penelope hopes Odysseus will come soon.)" },
      opts: ["Odysseus bald kommt", "Odysseus kommt bald", "kommt Odysseus bald", "bald kommt Odysseus"], a: 0,
      why: { zh: "dass 引出从句,变位动词被送到句末:dass Odysseus bald kommt。「动词第二位」只管主句,在从句里不适用。", en: "Dass opens a subordinate clause, which sends the finite verb to the very end: dass Odysseus bald kommt. Verb-second belongs to main clauses only." } },
    { q: { zh: "哪一句违反了「动词第二位」?", en: "Which sentence breaks the verb-second rule?" },
      opts: ["Heute die Argonauten segeln nach Kolchis.", "Heute segeln die Argonauten nach Kolchis.", "Die Argonauten segeln heute nach Kolchis.", "Nach Kolchis segeln heute die Argonauten."], a: 0,
      why: { zh: "Heute 已占第 1 位,segeln 必须紧跟其后。其余三句的第 1 位分别是 heute、主语和介词短语 nach Kolchis,动词都在第二位,全都正确。", en: "Heute already fills slot 1, so segeln must follow at once. The other three put heute, the subject or the phrase nach Kolchis first, with the verb second — all correct." } },
    { q: { zh: "Wenn Orpheus singt, ___.(俄耳甫斯一唱歌,野兽就走过来)", en: "Wenn Orpheus singt, ___. (When Orpheus sings, the animals come.)" },
      opts: ["kommen die Tiere", "die Tiere kommen", "die Tiere kommt", "kommt die Tiere"], a: 0,
      why: { zh: "整个 wenn 从句占据了主句的第 1 位,所以主句动词紧跟在逗号后面,主语 die Tiere 排在动词之后。die Tiere 是复数,动词用 kommen 而不是 kommt。", en: "The whole wenn-clause fills slot 1 of the main clause, so the verb follows the comma directly and the subject comes after it. Die Tiere is plural: kommen, not kommt." } },
    { q: { zh: "Nach zwanzig Jahren kommt Odysseus nach Hause. 句中占据第 1 位的是:", en: "Nach zwanzig Jahren kommt Odysseus nach Hause. What fills slot 1?" },
      opts: [{ zh: "整个短语 Nach zwanzig Jahren", en: "the whole phrase Nach zwanzig Jahren" }, { zh: "只有介词 Nach 这一个词", en: "only the preposition Nach on its own" }, { zh: "主语 Odysseus,主语总是排第一", en: "the subject Odysseus, which always leads" }, { zh: "动词 kommt,和疑问句一样", en: "the verb kommt, as in a question" }], a: 0,
      why: { zh: "「第 1 位」按句子成分算,不按单词数算:三个词组成的时间短语只占一个位置,所以 kommt 仍在第二位。主语并不一定在第 1 位。", en: "Slots count sentence parts, not words: a three-word time phrase is one slot, so kommt is still second. The subject need not come first." } },
    { q: { zh: "英语 Here comes the hero(英雄来了)里动词排在主语前面,这是:", en: "In English Here comes the hero, the verb precedes the subject. This is:" },
      opts: [{ zh: "古日耳曼语动词第二位的残留", en: "a relic of old Germanic verb-second" }, { zh: "从诺曼法语借来的语序", en: "word order borrowed from Norman French" }, { zh: "现代英语的新发明", en: "an invention of modern English" }, { zh: "诗歌里的笔误变成了语法", en: "a poetic slip that became grammar" }], a: 0,
      why: { zh: "古英语和德语一样是动词第二位:Þā cōm hē(于是来了他)。现代英语大多丢掉了这条规则,只在 here comes 和疑问句等少数结构里留下痕迹。", en: "Old English was verb-second like German: Þā cōm hē, then came he. Modern English lost the rule almost everywhere, keeping traces in here comes…, in questions and a few other patterns." } },
  ] },

{ id: "de_praep", icon: "🚪",
  name: { zh: "介词与格 · 走进迷宫,还是在迷宫里", en: "Prepositions · Into the labyrinth, or inside it" },
  scene: { zh: "忒修斯握着阿里阿德涅的线团(mit dem Faden)走进迷宫:Er geht ins Labyrinth——回答「去哪里?」,用宾格。随后他在黑暗里摸索:Er ist im Labyrinth——回答「在哪里?」,用与格。同一个 in,换一个格,意思就从「进入」变成「在里面」。",
           en: "Holding Ariadne's thread — mit dem Faden — Theseus walks into the labyrinth: Er geht ins Labyrinth. That answers ‘where to?’, so accusative. Then he gropes in the dark: Er ist im Labyrinth — ‘where?’, so dative. One preposition, in, and the case alone turns ‘into’ into ‘inside’." },
  rule: { zh: "德语介词规定后面名词的格。只接宾格:durch、für、gegen、ohne、um。只接与格:aus、bei、mit、nach、seit、von、zu、gegenüber。九个两可介词 an、auf、hinter、in、neben、über、unter、vor、zwischen:问「去哪里?」(wohin?移到新位置)用宾格,问「在哪里?」(wo?停在某处)用与格。介词常和冠词缩合:im(in dem)、ins(in das)、am、ans、zum、zur(zu der)、vom、beim。",
          en: "Each German preposition fixes the case of its noun. Accusative only: durch, für, gegen, ohne, um. Dative only: aus, bei, mit, nach, seit, von, zu, gegenüber. The nine two-way prepositions — an, auf, hinter, in, neben, über, unter, vor, zwischen — take the accusative for wohin? (motion to a new place) and the dative for wo? (location). Many merge with the article: im, ins, am, ans, zum, zur, vom, beim." },
  table: { cap: { zh: "三类介词", en: "Three kinds of preposition" },
    head: [{ zh: "介词", en: "Preposition" }, { zh: "格", en: "Case" }, { zh: "例子", en: "Example" }, { zh: "意思", en: "Meaning" }],
    rows: [["durch, für, gegen, ohne, um", "宾格|Accusative", "durch den Wald", "穿过森林|through the forest"],
           ["aus, bei, mit, nach, seit, von, zu", "与格|Dative", "mit dem Faden", "带着线|with the thread"],
           ["in + wohin?", "宾格|Accusative", "ins Labyrinth (in das)", "走进迷宫|into the labyrinth"],
           ["in + wo?", "与格|Dative", "im Labyrinth (in dem)", "在迷宫里|in the labyrinth"],
           ["auf + wohin?", "宾格|Accusative", "auf den Tisch", "放到桌上|onto the table"],
           ["auf + wo?", "与格|Dative", "auf dem Tisch", "在桌上|on the table"],
           ["an + wohin?", "宾格|Accusative", "ans Ufer (an das)", "到岸边|to the shore"],
           ["an + wo?", "与格|Dative", "am Ufer (an dem)", "在岸边|on the shore"],
           ["zu", "与格|Dative", "zum Hafen, zur Insel", "去港口、去岛上|to the harbour, to the island"]] },
  notes: { zh: "早期印欧语还没有真正的介词,只有表示方位的副词,意思主要靠名词的格:宾格表示目标,处所格、夺格表示位置和来源。日耳曼语把处所格、工具格、夺格并进了与格,于是与格接管了「在哪里」,宾格保留「去哪里」。许多介词与英语同源:über = over,unter = under,aus = out,durch = through;nach 来自 nah(近,英语 nigh)。古英语也分 hwider(whither,往哪里)和 hwǣr(where,在哪里),正如德语分 wohin 与 wo。",
           en: "Early Indo-European had place adverbs, not prepositions; the case did the work: accusative for goal, locative and ablative for place and source. Germanic merged locative, instrumental and ablative into the dative, so the dative took ‘where?’ and the accusative kept ‘where to?’. Cognates: über over, unter under, aus out, durch through; nach is from nah, near (English nigh). Old English split hwider, whither, from hwǣr, where, like wohin and wo." },
  ex: [
    { q: { zh: "Theseus geht ___ Labyrinth.(走进迷宫)", en: "Theseus geht ___ Labyrinth. (walks into the labyrinth)" },
      opts: ["ins", "im", "in dem", "am"], a: 0,
      why: { zh: "「走进」回答 wohin?,两可介词 in 要接宾格:in das,缩合为 ins。im = in dem 是与格,表示人已经在里面。", en: "Walking into answers wohin?, so the two-way in takes the accusative: in das, contracted to ins. Im = in dem is dative and means already inside." } },
    { q: { zh: "Das Schwert liegt ___ Tisch.(剑放在桌上)", en: "Das Schwert liegt ___ Tisch. (The sword lies on the table.)" },
      opts: ["auf dem", "auf den", "auf der", "auf das"], a: 0,
      why: { zh: "liegen 描述静止的位置,回答 wo?,auf 接与格;Tisch 是阳性,与格冠词是 dem。auf den Tisch 表示「放到桌上」的方向。", en: "Liegen describes a position, answering wo?, so auf takes the dative; Tisch is masculine, dative dem. Auf den Tisch would mean motion onto the table." } },
    { q: { zh: "Orpheus geht durch ___ Wald.(俄耳甫斯穿过森林)", en: "Orpheus geht durch ___ Wald. (Orpheus walks through the forest.)" },
      opts: ["den", "dem", "der", "das"], a: 0,
      why: { zh: "durch 永远接宾格,Wald 是阳性,宾格冠词是 den。它不是两可介词,不会因为涉及地点就改用与格 dem。", en: "Durch always takes the accusative, and Wald is masculine: den. It is not a two-way preposition, so it never switches to dative dem." } },
    { q: { zh: "Theseus findet den Weg mit ___ Faden.(忒修斯靠线团找到出路)", en: "Theseus findet den Weg mit ___ Faden. (Theseus finds the way with the thread.)" },
      opts: ["dem", "den", "der", "des"], a: 0,
      why: { zh: "mit 永远接与格,Faden 是阳性,与格是 dem。den 是宾格——mit 后面从不用宾格。", en: "Mit always takes the dative; Faden is masculine, so dem. Den is accusative, which never follows mit." } },
    { q: { zh: "哪一个短语是错的?", en: "Which phrase is wrong?" },
      opts: ["für dem König", "für den König", "mit dem König", "ohne den König"], a: 0,
      why: { zh: "für 只接宾格,应为 für den König。ohne 也只接宾格,mit 只接与格,所以另外三个都对。", en: "Für takes only the accusative: für den König. Ohne is accusative-only too and mit dative-only, so the other three are right." } },
    { q: { zh: "Penelope legt den Bogen auf den Tisch. — Der Bogen liegt auf dem Tisch. 为什么一个用 den,一个用 dem?", en: "Penelope legt den Bogen auf den Tisch. — Der Bogen liegt auf dem Tisch. Why den in one and dem in the other?" },
      opts: [{ zh: "legen 是放到哪里,liegen 是在哪里", en: "legen = put (wohin?), liegen = lie (wo?)" }, { zh: "第一句的 Tisch 是复数形式", en: "Tisch is a plural form in the first sentence" }, { zh: "auf 只接宾格,dem 是印刷错误", en: "auf takes only the accusative, so dem is a typo" }, { zh: "Bogen 作主语时,Tisch 就得用与格", en: "when Bogen is the subject, Tisch must be dative" }], a: 0,
      why: { zh: "两可介词看动词的意思:legen(放)把弓移到新位置,用宾格;liegen(躺着)描述它在哪里,用与格。setzen / sitzen、stellen / stehen 也同样成对。", en: "A two-way preposition follows the verb's meaning: legen moves the bow to a new place, accusative; liegen says where it lies, dative. Setzen / sitzen and stellen / stehen pair up the same way." } },
    { q: { zh: "Die Seeleute gehen ___ Schiff.(水手们走到船那里)", en: "Die Seeleute gehen ___ Schiff. (The sailors go to the ship.)" },
      opts: ["zum", "zur", "zu das", "zu den"], a: 0,
      why: { zh: "zu 接与格,Schiff 是中性,zu dem 缩合为 zum。zur = zu der 只用于阴性;zu das 错用了宾格。", en: "Zu takes the dative; Schiff is neuter, so zu dem, contracted to zum. Zur = zu der is for feminines, and zu das wrongly uses the accusative." } },
    { q: { zh: "两可介词表示「在哪里」时为什么用与格?", en: "Why do two-way prepositions take the dative for ‘where?’" },
      opts: [{ zh: "日耳曼语的与格吞并了古老的处所格", en: "the dative absorbed the old locative" }, { zh: "与格原本就表示方向", en: "the dative originally meant direction" }, { zh: "这条规则借自拉丁语语法", en: "the rule was borrowed from Latin grammar" }, { zh: "中世纪语法学家的规定", en: "medieval grammarians decreed it so" }], a: 0,
      why: { zh: "日耳曼语把处所格、工具格、夺格逐步并入与格,与格因此继承了「位置」的意思;宾格则一直表示「目标」。拉丁语用夺格表示位置,是平行的演变,不是来源。", en: "Germanic gradually merged the locative, instrumental and ablative into the dative, which thus inherited the sense of place; the accusative had always marked the goal. Latin's ablative of place is a parallel development, not the source." } },
  ] },

{ id: "de_adj", icon: "🎨",
  name: { zh: "形容词词尾 · 金羊毛", en: "Adjective endings · The Golden Fleece" },
  scene: { zh: "伊阿宋率领阿尔戈英雄远航科尔基斯,去取金毛公羊的皮。同一个 golden 在德语里有好几副面孔:das goldene Fell、ein goldenes Fell、mit dem goldenen Fell。可一旦放在 ist 后面——Das Fell ist golden——它就一个词尾也不加。",
           en: "Jason leads the Argonauts to Colchis to win the fleece of the golden ram. One adjective, golden, wears several faces in German: das goldene Fell, ein goldenes Fell, mit dem goldenen Fell. Yet after ist — Das Fell ist golden — it takes no ending at all." },
  rule: { zh: "sein 后的表语形容词不加词尾:Der Held ist mutig。放在名词前必须加词尾,原则是:性和格的信号只出现一次。der、die、das 之后用弱词尾:单数主格及阴性、中性宾格用 -e,其余一律 -en(den mutigen Helden)。ein、kein、mein 在阳性主格和中性主、宾格没有词尾,形容词就替它补上:ein mutiger Held, ein kleines Schiff;其余同弱词尾。无冠词时用强词尾,照搬定冠词:kaltes Wasser, mit kaltem Wasser。",
          en: "After sein an adjective is bare: Der Held ist mutig. Before a noun it needs an ending, but the gender-and-case signal appears once. After der, die, das it is weak: -e in nominative singular and feminine/neuter accusative, else -en. Where ein-words are bare (masc. nom., neut. nom./acc.), the adjective carries the signal: ein mutiger Held, ein kleines Schiff; elsewhere weak. No article: strong, like der, das, dem: kaltes Wasser, mit kaltem Wasser." },
  table: { cap: { zh: "三套词尾:弱、混合、强(属格从略)", en: "Three sets of endings: weak, mixed, strong (genitive left out)" },
    head: [{ zh: "冠词 · 格", en: "Article · case" }, { zh: "阳性", en: "Masculine" }, { zh: "中性", en: "Neuter" }, { zh: "阴性", en: "Feminine" }, { zh: "复数", en: "Plural" }],
    rows: [["der 类 · 主格|der-word · nom.", "der mutige Held", "das kleine Schiff", "die schöne Insel", "die mutigen Helden"],
           ["der 类 · 宾格|der-word · acc.", "den mutigen Helden", "das kleine Schiff", "die schöne Insel", "die mutigen Helden"],
           ["der 类 · 与格|der-word · dat.", "dem mutigen Helden", "dem kleinen Schiff", "der schönen Insel", "den mutigen Helden"],
           ["ein 类 · 主格|ein-word · nom.", "ein mutiger Held", "ein kleines Schiff", "eine schöne Insel", "keine mutigen Helden"],
           ["ein 类 · 宾格|ein-word · acc.", "einen mutigen Helden", "ein kleines Schiff", "eine schöne Insel", "keine mutigen Helden"],
           ["ein 类 · 与格|ein-word · dat.", "einem mutigen Helden", "einem kleinen Schiff", "einer schönen Insel", "keinen mutigen Helden"],
           ["无冠词 · 主格|no article · nom.", "starker Wind", "kaltes Wasser", "große Freude", "mutige Helden"],
           ["无冠词 · 宾格|no article · acc.", "starken Wind", "kaltes Wasser", "große Freude", "mutige Helden"],
           ["无冠词 · 与格|no article · dat.", "mit starkem Wind", "mit kaltem Wasser", "mit großer Freude", "mit mutigen Helden"]] },
  notes: { zh: "「强变化」「弱变化」这对术语出自雅各布·格林(Jacob Grimm)1819 年起出版的《德语语法》。弱词尾 -en 来自原始日耳曼语的 n 词干:加上它,形容词就变成「那个……的人」,好比拉丁语 catus(精明)→ Catō(「精明者」,属格 Catōnis)。强词尾则多半借自代词,所以和 der、dem 长得很像。古英语同样区分 se gōda cyning(那位好国王,弱)和 gōd cyning(好国王,强);现代英语把词尾全丢了,只剩一个 good。",
           en: "Strong and weak are Jacob Grimm's terms, from his Deutsche Grammatik (1819 on). The weak -en comes from a Proto-Germanic n-stem that made an adjective mean ‘the … one’, as Latin catus, shrewd, gave Catō, Catōnis, ‘the shrewd one’. Strong endings largely borrowed the pronoun's, which is why they look like der and dem. Old English had se gōda cyning, the good king (weak), beside gōd cyning (strong); English then lost every ending." },
  ex: [
    { q: { zh: "Der Held ist ___.(英雄很勇敢)", en: "Der Held ist ___. (The hero is brave.)" },
      opts: ["mutig", "mutige", "mutiger", "mutigen"], a: 0,
      why: { zh: "形容词放在 sein 后面作表语时不变,永远用原形 mutig。只有放在名词前才加词尾:der mutige Held。", en: "After sein the adjective is predicative and never changes: mutig. Only before a noun does it take an ending: der mutige Held." } },
    { q: { zh: "Jason sucht das ___ Fell.(伊阿宋寻找金羊毛)", en: "Jason sucht das ___ Fell. (Jason seeks the golden fleece.)" },
      opts: ["goldene", "goldenen", "goldenes", "golden"], a: 0,
      why: { zh: "das 已经标明中性宾格,形容词用弱词尾;中性宾格单数是 -e:das goldene Fell。goldenes 会把信号重复一次。", en: "Das already signals the neuter accusative, so the adjective is weak, and the neuter accusative singular is -e: das goldene Fell. Goldenes would repeat the signal." } },
    { q: { zh: "Jason segelt mit dem ___ Schiff.(伊阿宋乘着那艘快船航行)", en: "Jason segelt mit dem ___ Schiff. (Jason sails in the swift ship.)" },
      opts: ["schnellen", "schnelle", "schnelles", "schnellem"], a: 0,
      why: { zh: "dem 已经带有与格信号,弱词尾在与格一律是 -en。schnellem 是没有冠词时才用的强词尾。", en: "Dem carries the dative signal, and weak adjectives in the dative always take -en. Schnellem is the strong ending, used only with no article." } },
    { q: { zh: "Die Argo ist ein ___ Schiff.(阿尔戈号是一艘快船)", en: "Die Argo ist ein ___ Schiff. (The Argo is a swift ship.)" },
      opts: ["schnelles", "schnelle", "schneller", "schnellen"], a: 0,
      why: { zh: "中性主格的 ein 没有词尾,性的信号只能由形容词给出:-es(对应 das)。schnelle 是 das schnelle Schiff 里的弱词尾。", en: "Neuter nominative ein has no ending, so the adjective must give the signal: -es, matching das. Schnelle is the weak ending of das schnelle Schiff." } },
    { q: { zh: "Medea sieht einen ___ Helden.(美狄亚看见一位勇敢的英雄)", en: "Medea sieht einen ___ Helden. (Medea sees a brave hero.)" },
      opts: ["mutigen", "mutiger", "mutige", "mutiges"], a: 0,
      why: { zh: "einen 已经带有阳性宾格的信号,形容词随之用 -en。ein 后面的 mutiger 只用于阳性主格:ein mutiger Held。", en: "Einen already carries the masculine accusative signal, so the adjective takes -en. After ein, mutiger is the masculine nominative: ein mutiger Held." } },
    { q: { zh: "Hylas holt ___ Wasser aus der Quelle.(许拉斯从泉中汲取冷水)", en: "Hylas holt ___ Wasser aus der Quelle. (Hylas fetches cold water from the spring.)" },
      opts: ["kaltes", "kalte", "kalten", "kalter"], a: 0,
      why: { zh: "没有冠词,形容词要自己承担信号,用强词尾;Wasser 是中性宾格,词尾 -es,与 das 相对应。kalte、kalten 是跟在冠词后的弱词尾:das kalte Wasser、mit dem kalten Wasser。", en: "With no article the adjective must carry the signal itself — the strong ending. Wasser is neuter accusative, so -es, echoing das. Kalte and kalten are weak endings that need an article: das kalte Wasser, mit dem kalten Wasser." } },
    { q: { zh: "哪一个短语是错的?", en: "Which phrase is wrong?" },
      opts: ["ein mutige Held", "ein mutiger Held", "der mutige Held", "mit kaltem Wasser"], a: 0,
      why: { zh: "阳性主格的 ein 没有词尾,信号必须由形容词补上:ein mutiger Held。ein mutige Held 里,信号哪里都没有出现。", en: "Masculine nominative ein has no ending, so the adjective must supply it: ein mutiger Held. In ein mutige Held the signal appears nowhere." } },
    { q: { zh: "弱变化形容词的 -en 来自哪里?", en: "Where does the weak adjective ending -en come from?" },
      opts: [{ zh: "日耳曼语的 n 词干", en: "a Germanic n-stem" }, { zh: "动词不定式的 -en", en: "the -en of the infinitive" }, { zh: "拉丁语的复数词尾", en: "a Latin plural ending" }, { zh: "中世纪抄写员的习惯", en: "a habit of medieval scribes" }], a: 0,
      why: { zh: "原始日耳曼语给形容词加上 n 词干后缀,使它变成「那个……的」,类似拉丁语 catus → Catō。不定式的 -en 是另一个后缀,只是碰巧同形。", en: "Proto-Germanic added an n-stem suffix that turned the adjective into ‘the … one’, like Latin catus → Catō. The infinitive -en is a different suffix that merely looks the same." } },
  ] },

{ id: "de_perfekt", icon: "⏳",
  name: { zh: "完成时 · 被缚的普罗米修斯", en: "Perfect tense · Prometheus bound" },
  scene: { zh: "宙斯震怒:Prometheus hat das Feuer gestohlen!他把火藏在茴香秆里,带给了人类:Er hat den Menschen das Feuer gebracht。宙斯把他锁在山崖上,每天派一只鹰飞来:Der Adler ist gekommen。德语口语讲过去多用完成时。",
           en: "Zeus is furious: Prometheus hat das Feuer gestohlen! Prometheus hid the fire in a hollow fennel stalk and gave it to mankind: Er hat den Menschen das Feuer gebracht. Zeus chains him to a crag and each day sends an eagle: Der Adler ist gekommen. For past events, spoken German mostly uses the Perfekt." },
  rule: { zh: "完成时 = haben 或 sein(第 2 位)+ 过去分词(句末)。多数动词用 haben;位移或状态变化的不及物动词用 sein(gehen、kommen、sterben、werden),sein、bleiben 也是。弱变化 ge-…-t(gemacht);强变化 ge-…-en,常换元音(gesungen);混合变化 -t 加换元音(gebracht)。-ieren 动词和不可分前缀不加 ge-:studiert、besucht。书面叙事和 sein、haben、情态动词常用过去时 war、hatte。",
          en: "Perfekt = haben or sein (slot 2) + past participle (end). Most verbs take haben; sein with intransitive verbs of motion or change of state (gehen, kommen, sterben, werden), plus sein, bleiben. Weak: ge-…-t (gemacht). Strong: ge-…-en, often a new vowel (gesungen). Mixed: -t plus a new vowel (gebracht). No ge- for -ieren verbs or inseparable prefixes: studiert, besucht. Written narrative, sein, haben and modals prefer the Präteritum: war, hatte." },
  table: { cap: { zh: "基本形式与完成时", en: "Principal parts and the Perfekt" },
    head: [{ zh: "不定式", en: "Infinitive" }, { zh: "类型", en: "Type" }, { zh: "过去时", en: "Präteritum" }, { zh: "过去分词", en: "Participle II" }, { zh: "完成时", en: "Perfekt" }],
    rows: [["machen", "弱|weak", "machte", "gemacht", "er hat gemacht"],
           ["spielen", "弱|weak", "spielte", "gespielt", "er hat gespielt"],
           ["singen", "强|strong", "sang", "gesungen", "er hat gesungen"],
           ["finden", "强|strong", "fand", "gefunden", "er hat gefunden"],
           ["sprechen", "强|strong", "sprach", "gesprochen", "er hat gesprochen"],
           ["gehen", "强 · 用 sein|strong · with sein", "ging", "gegangen", "er ist gegangen"],
           ["fliegen", "强 · 用 sein|strong · with sein", "flog", "geflogen", "er ist geflogen"],
           ["bringen", "混合|mixed", "brachte", "gebracht", "er hat gebracht"],
           ["denken", "混合|mixed", "dachte", "gedacht", "er hat gedacht"],
           ["studieren / besuchen", "不加 ge-|no ge-", "studierte / besuchte", "studiert / besucht", "er hat studiert / besucht"]] },
  notes: { zh: "完成时起初表示「拥有」:er hat den Brief geschrieben 原意近于「他有一封写好的信」,后来 haben 虚化成助动词,正如拉丁语 habeō + 分词变成法语 j'ai écrit。前缀 ge-(哥特语 ga-)原义大概是「一起」,后来表示完成;英语只在 enough(古英语 genōg)等词里留有痕迹。强变化的元音交替继承自印欧语:singen–sang–gesungen 对应 sing–sang–sung;混合变化 bringen–gebracht 也对应 bring–brought。",
           en: "The Perfekt began as possession: er hat den Brief geschrieben meant roughly ‘he has the letter, written’; then haben faded into an auxiliary, as Latin habeō + participle became French j'ai écrit. Ge- (Gothic ga-) probably first meant ‘together’, then marked completion; English kept it only in words like enough (Old English genōg). Ablaut is inherited: singen–sang–gesungen matches sing–sang–sung; so do mixed verbs: bringen–gebracht, bring–brought." },
  ex: [
    { q: { zh: "Orpheus hat in der Unterwelt ___.(singen)", en: "Orpheus hat in der Unterwelt ___. (singen)" },
      opts: ["gesungen", "gesingt", "gesangen", "singte"], a: 0,
      why: { zh: "singen 是强变化动词,分词是 ge-…-en 并换元音:gesungen,与英语 sung 是同一个元音。gesingt 把它当成了弱变化。", en: "Singen is strong: ge-…-en with a new vowel, gesungen — the same vowel as English sung. Gesingt treats it as weak." } },
    { q: { zh: "Die Argonauten ___ nach Kolchis gefahren.", en: "Die Argonauten ___ nach Kolchis gefahren." },
      opts: ["sind", "haben", "ist", "hat"], a: 0,
      why: { zh: "fahren 在这里表示位移,不带宾语,用 sein;主语是复数,所以是 sind。haben gefahren 只用于「驾驶某物」这类带宾语的情况。", en: "Fahren here is motion with no object, so it takes sein; the subject is plural, hence sind. Haben gefahren is for driving something, with an object." } },
    { q: { zh: "Theseus ___ den Minotaurus getötet.", en: "Theseus ___ den Minotaurus getötet." },
      opts: ["hat", "ist", "hast", "habt"], a: 0,
      why: { zh: "töten 带宾语,用 haben;主语 Theseus 是第三人称单数,所以是 hat。sein 只留给位移和状态变化。", en: "Töten takes an object, so its auxiliary is haben, and Theseus is third person singular: hat. Sein is kept for motion and change of state." } },
    { q: { zh: "Prometheus hat den Menschen das Feuer ___.(bringen)", en: "Prometheus hat den Menschen das Feuer ___. (bringen)" },
      opts: ["gebracht", "gebringt", "gebrungen", "gebrachen"], a: 0,
      why: { zh: "bringen 是混合变化:像弱变化一样用 -t,又像强变化一样换元音:gebracht。英语 bring–brought 是同一种模式。", en: "Bringen is mixed: the weak -t, but a strong-style vowel change — gebracht. English bring–brought shows the same pattern." } },
    { q: { zh: "Herakles hat die Unterwelt ___.(besuchen;他下冥界去带回刻耳柏洛斯)", en: "Herakles hat die Unterwelt ___. (besuchen — he went down to fetch Cerberus)" },
      opts: ["besucht", "gebesucht", "besuchen", "begesucht"], a: 0,
      why: { zh: "be- 是不重读的不可分前缀,这样的动词分词不加 ge-:besucht。gebesucht 是最常见的过度类推。", en: "Be- is an unstressed, inseparable prefix, and such verbs take no ge-: besucht. Gebesucht is the commonest over-regularisation." } },
    { q: { zh: "Eurydike ___ an einem Schlangenbiss gestorben.", en: "Eurydike ___ an einem Schlangenbiss gestorben." },
      opts: ["ist", "hat", "sind", "hatte"], a: 0,
      why: { zh: "sterben 表示状态的改变(由生到死),用 sein:ist gestorben。它不是位移动词,规则照样适用;werden 和 bleiben 也用 sein。", en: "Sterben is a change of state, from living to dead, so it takes sein: ist gestorben. It is no verb of motion, yet the rule applies; werden and bleiben also take sein." } },
    { q: { zh: "哪一句是错的?", en: "Which sentence is wrong?" },
      opts: ["Perseus hat über das Meer geflogen.", "Perseus ist über das Meer geflogen.", "Perseus hat Andromeda gerettet.", "Perseus hat Medusa gefunden."], a: 0,
      why: { zh: "fliegen 表示位移、没有宾语,助动词必须用 sein:Perseus ist geflogen。retten 和 finden 带宾语,用 haben。", en: "Fliegen is motion with no object, so the auxiliary must be sein: Perseus ist geflogen. Retten and finden take objects and use haben." } },
    { q: { zh: "singen – sang – gesungen 与英语 sing – sang – sung 元音一一对应,原因是:", en: "Singen – sang – gesungen matches sing – sang – sung vowel for vowel because:" },
      opts: [{ zh: "两者都继承了印欧语的元音交替", en: "both inherit Indo-European ablaut" }, { zh: "英语借用了德语的形式", en: "English borrowed the German forms" }, { zh: "德语借用了英语的形式", en: "German borrowed the English forms" }, { zh: "中世纪的一次拼写改革", en: "a medieval spelling reform" }], a: 0,
      why: { zh: "强变化动词靠元音交替(Ablaut)区分时态,这套机制可以追溯到原始印欧语的 e / o / 零级交替;英语和德语各自从共同祖先继承,并非互相借用。", en: "Strong verbs mark tense by ablaut, a vowel alternation going back to the Indo-European e / o / zero grades; English and German each inherited it from their common ancestor." } },
  ] },

{ id: "de_praefix", icon: "🧩",
  name: { zh: "动词前缀 · 代达罗斯的翅膀", en: "Verb prefixes · Daedalus's wings" },
  scene: { zh: "天一亮,代达罗斯起身:Dädalus steht früh auf——auf 甩到句末。他用羽毛和蜡做成翅膀,带伊卡洛斯逃离克里特:Sie entkommen——ent- 却牢牢粘着动词。前缀一换,stehen「站」就成了 verstehen「懂」、entstehen「产生」——一个词根,一族动词。",
           en: "At first light Daedalus gets up: Dädalus steht früh auf — the prefix auf is flung to the end. With feathers and wax he makes wings and escapes Crete with Icarus: Sie entkommen — and ent- stays glued to its verb. Change the prefix and stehen, to stand, becomes verstehen, to understand, or entstehen, to arise: one root, a whole family of verbs." },
  rule: { zh: "可分前缀(an-、auf-、aus-、ein-、mit-、ab-、zu-、zurück- 等)重读,在主句现在时里与动词分开,跑到句末:Theseus steht früh auf。分词把 ge- 夹在中间:aufgestanden;zu 不定式也一样:aufzustehen。从句里前缀与动词重新合写:…, weil er früh aufsteht。不可分前缀(be-、emp-、ent-、er-、ge-、miss-、ver-、zer-)不重读,永不分开,分词不加 ge-:verstanden、bekommen。",
          en: "Separable prefixes (an-, auf-, aus-, ein-, mit-, ab-, zu-, zurück- …) are stressed and split off to the end in a main-clause present: Theseus steht früh auf. Ge- slips inside the participle, aufgestanden, and so does zu: aufzustehen. In a subordinate clause they rejoin: …, weil er früh aufsteht. Inseparable prefixes (be-, emp-, ent-, er-, ge-, miss-, ver-, zer-) are unstressed, never split, and take no ge-: verstanden, bekommen." },
  table: { cap: { zh: "一个词根,一族动词:stehen 与 kommen", en: "One root, one family: stehen and kommen" },
    head: [{ zh: "动词", en: "Verb" }, { zh: "前缀", en: "Prefix" }, { zh: "意思", en: "Meaning" }, { zh: "完成时", en: "Perfekt" }],
    rows: [["stehen", "词根|root", "站|to stand", "hat gestanden"],
           ["aufstehen", "可分|separable", "起身|to get up", "ist aufgestanden"],
           ["verstehen", "不可分|inseparable", "理解|to understand", "hat verstanden"],
           ["bestehen", "不可分|inseparable", "经受住(考验)|to pass (a test)", "hat bestanden"],
           ["entstehen", "不可分|inseparable", "产生|to arise", "ist entstanden"],
           ["gestehen", "不可分|inseparable", "招认|to confess", "hat gestanden"],
           ["kommen", "词根|root", "来|to come", "ist gekommen"],
           ["ankommen", "可分|separable", "到达|to arrive", "ist angekommen"],
           ["bekommen", "不可分|inseparable", "得到|to receive", "hat bekommen"],
           ["entkommen", "不可分|inseparable", "逃脱|to escape", "ist entkommen"]] },
  notes: { zh: "可分前缀原本是独立的副词:古高地德语 ūf(向上)、ūz(向外)、ana(在…上)。主句动词移到第二位时,副词留在原处——可分性其实是动词第二位规则的副产品。英语短语动词用的也是这批老副词:aufstehen ≈ stand up。不可分前缀不重读,很早就和动词长在一起:ver- 对应英语 for-(vergessen = forget,vergeben = forgive);be- 对应英语 be-,但 bekommen(得到)和 become(变成)早已分道扬镳,成了「假朋友」。",
           en: "Separable prefixes were once free adverbs — Old High German ūf, up; ūz, out; ana, on. When the main-clause verb moved second, the adverb stayed behind: separability is a by-product of verb-second. English phrasal verbs like stand up use the same adverbs. Inseparable prefixes were unstressed and fused early: ver- is English for- (vergessen forget, vergeben forgive); be- is English be-, yet bekommen, to receive, and become are false friends." },
  ex: [
    { q: { zh: "「代达罗斯起得很早。」哪句正确?", en: "‘Daedalus gets up early.’ Which is right?" },
      opts: ["Dädalus steht früh auf.", "Dädalus aufsteht früh.", "Dädalus steht auf früh.", "Dädalus früh aufsteht."], a: 0,
      why: { zh: "主句现在时里,可分前缀 auf 与动词分开:变位的 steht 占第二位,auf 留在句末,früh 夹在中间。", en: "In a main-clause present the separable auf splits off: steht takes slot 2, auf waits at the end, and früh sits in between." } },
    { q: { zh: "Die Argonauten sind in Kolchis ___.(ankommen)", en: "Die Argonauten sind in Kolchis ___. (ankommen)" },
      opts: ["angekommen", "geankommen", "angekommt", "ankommen"], a: 0,
      why: { zh: "可分动词的分词把 ge- 夹在前缀和词干之间:an-ge-kommen。把 ge- 加在最前面(geankommen)是典型错误。", en: "With a separable verb ge- goes between prefix and stem: an-ge-kommen. Putting it in front, geankommen, is the typical mistake." } },
    { q: { zh: "Dädalus hat das Labyrinth ___.(entwerfen 设计)", en: "Dädalus hat das Labyrinth ___. (entwerfen, to design)" },
      opts: ["entworfen", "entgeworfen", "geentworfen", "entwerft"], a: 0,
      why: { zh: "ent- 是不可分前缀,分词不加 ge-;werfen 是强变化(geworfen),所以 entwerfen → entworfen。entgeworfen 把 ent- 当成了可分前缀。", en: "Ent- is inseparable, so no ge-; werfen is strong (geworfen), hence entworfen. Entgeworfen treats ent- as if it were separable." } },
    { q: { zh: "Ikarus beginnt, zur Sonne ___.(aufsteigen)", en: "Ikarus beginnt, zur Sonne ___. (aufsteigen)" },
      opts: ["aufzusteigen", "zu aufsteigen", "aufsteigen zu", "zuaufsteigen"], a: 0,
      why: { zh: "可分动词的 zu 不定式把 zu 夹在前缀和词干之间,连写成一个词:aufzusteigen。不可分动词则把 zu 放在前面:zu verstehen。", en: "For a separable verb zu goes between prefix and stem, written as one word: aufzusteigen. An inseparable verb keeps zu in front: zu verstehen." } },
    { q: { zh: "下面哪个动词在主句现在时会把前缀分到句末?", en: "Which verb splits off its prefix in a main-clause present?" },
      opts: ["ankommen", "bekommen", "entkommen", "verkommen"], a: 0,
      why: { zh: "an- 是重读的可分前缀:Theseus kommt in Athen an。be-、ent-、ver- 都是不重读的不可分前缀:er bekommt、er entkommt、er verkommt。", en: "An- is a stressed separable prefix: Theseus kommt in Athen an. Be-, ent- and ver- are unstressed and inseparable: er bekommt, er entkommt, er verkommt." } },
    { q: { zh: "哪一句是错的?", en: "Which sentence is wrong?" },
      opts: ["Theseus kommt dem Labyrinth ent.", "Theseus entkommt dem Labyrinth.", "Theseus kommt in Athen an.", "Dädalus steht früh am Morgen auf."], a: 0,
      why: { zh: "ent- 是不可分前缀,永远不能拆开:Theseus entkommt dem Labyrinth。只有重读的可分前缀(如 an-、auf-)才会跑到句末。", en: "Ent- is inseparable and never splits: Theseus entkommt dem Labyrinth. Only stressed separable prefixes such as an- and auf- move to the end." } },
    { q: { zh: "Penelope weiß nicht, ob Odysseus ___.(珀涅罗珀不知道奥德修斯是否会回来)", en: "Penelope weiß nicht, ob Odysseus ___. (Penelope does not know whether Odysseus will return.)" },
      opts: ["zurückkommt", "kommt zurück", "zurück kommt", "zurückgekommen"], a: 0,
      why: { zh: "ob 从句把变位动词送到句末,可分前缀与动词重新合写成一个词:zurückkommt。kommt zurück 是主句语序。", en: "An ob-clause sends the finite verb to the end, where the separable prefix rejoins it as one word: zurückkommt. Kommt zurück is main-clause order." } },
    { q: { zh: "英语 forget、forgive 里的 for- 对应德语哪个前缀?", en: "Which German prefix matches the for- of English forget and forgive?" },
      opts: ["ver-", "vor-", "für-", "fort-"], a: 0,
      why: { zh: "vergessen = forget,vergeben = forgive:德语 ver- 与英语 for- 同源,都是不重读的不可分前缀。vor- 对应的是英语 fore-(如 foresee)。", en: "Vergessen is forget and vergeben forgive: German ver- and English for- are cognate unstressed prefixes. Vor- matches English fore-, as in foresee." } },
  ] },
]);
