/* LEVEL_INTRO: a short Latin motto for each level, with translations.
   Shown under the level artwork: Latin line first, then the interface language.
   Key = "c<chapter><level>", both 1-based. */
const LEVEL_INTRO = {
  /* ---- Chapter I · The Labyrinth of Crete ---- */
  c1l1: { la: "Nox est. Theseus patrem regem valere iubet.",
          zh: "夜已深。忒修斯向父王告别。",
          en: "Night has come. Theseus bids his father the king farewell." },
  c1l2: { la: "Navis vela nigra tollit; mare et ventus iter monstrant.",
          zh: "船升起黑帆;大海与风指出航路。",
          en: "The ship raises its black sails; sea and wind show the way." },
  c1l3: { la: "In regia Minois columnae marmoreae lucent.",
          zh: "在米诺斯的王宫里,大理石柱熠熠生光。",
          en: "In the palace of Minos the marble columns shine." },
  c1l4: { la: "Ariadna heroi filum et gladium dat.",
          zh: "阿里阿德涅把线团和剑交给英雄。",
          en: "Ariadne gives the hero a thread and a sword." },
  c1l5: { la: "Ante portam sto; intra labyrinthum via caeca est.",
          zh: "我站在门前;迷宫之内,路是盲的。",
          en: "I stand before the gate; inside the labyrinth the way is blind." },
  c1l6: { la: "In tenebris nihil video; auribus viam quaero.",
          zh: "黑暗中我什么也看不见;我用耳朵寻路。",
          en: "In the dark I see nothing; I search out the way by ear." },
  c1l7: { la: "Leo, lupus, aquila — sed hic monstrum maius habitat.",
          zh: "狮、狼、鹰——但住在这里的是更大的怪物。",
          en: "Lion, wolf, eagle — but a greater monster lives here." },
  c1l8: { la: "Arma capit heros: hastam, scutum, galeam.",
          zh: "英雄拿起武器:长矛、盾牌、头盔。",
          en: "The hero takes up his arms: spear, shield, helmet." },
  c1l9: { la: "Filum tenet et gradum retro fert.",
          zh: "他握紧线,一步步向后退回。",
          en: "He holds the thread and carries his step back." },
  c1l10: { la: "Libertas! Navis domum redit; memoria manet.",
           zh: "自由!船驶回家乡;记忆长存。",
           en: "Freedom! The ship returns home; the memory remains." },

  /* ---- Chapter II · Orpheus in the Underworld ---- */
  c2l1: { la: "Orpheus lyram tangit: silvae et ferae audiunt.",
          zh: "俄耳甫斯拨动琴弦:森林与野兽都在听。",
          en: "Orpheus touches his lyre: woods and wild beasts listen." },
  c2l2: { la: "In nuptiis serpens latet; Eurydice cadit.",
          zh: "婚礼上藏着一条蛇;欧律狄刻倒下了。",
          en: "A snake lies hidden at the wedding; Eurydice falls." },
  c2l3: { la: "Porta inferorum patet; umbrae sine numero descendunt.",
          zh: "冥界之门敞开;无数亡魂走下去。",
          en: "The gate of the underworld stands open; shades without number go down." },
  c2l4: { la: "Charon navem agit; Cerberus guttur triplex aperit.",
          zh: "卡戎撑船;刻耳柏洛斯张开三张咽喉。",
          en: "Charon drives his boat; Cerberus opens his threefold throat." },
  c2l5: { la: "Flumen Lethe fluit: qui aquam bibit, omnia obliviscitur.",
          zh: "忘川流淌:饮下这水的人,忘记一切。",
          en: "The river Lethe flows: whoever drinks its water forgets everything." },
  c2l6: { la: "Iudices leges tenent; nemo culpam celat.",
          zh: "判官们握着法律;无人能藏起自己的罪。",
          en: "The judges hold the laws; no one hides his guilt." },
  c2l7: { la: "Dominus umbrarum in throno sedet; regina adest.",
          zh: "亡魂之主端坐王座;王后在侧。",
          en: "The lord of the shades sits on his throne; the queen is at his side." },
  c2l8: { la: "Carmen dulce etiam saxa et umbras movet.",
          zh: "甜美的歌连岩石与亡魂也能打动。",
          en: "A sweet song moves even stones and shades." },
  c2l9: { la: "Noli respicere: unus aspectus omnia perdit.",
          zh: "不要回头:一次回望,毁掉一切。",
          en: "Do not look back: one glance destroys everything." },
  c2l10: { la: "Cantus manet: quod amamus, non perit.",
           zh: "歌声长留:我们所爱的,不会消亡。",
           en: "The song remains: what we love does not perish." },
};
