/* =====================================================
   FUGA MYTHICA — VIVA: the closest LIVING descendants of each Latin word
   (modern Romance languages & friends — proof the word never died)
   key -> "🇮🇹 word · 🇪🇸 word · 🇫🇷 word"  (occasionally with a short zh note)
   ===================================================== */
const VIVA = {
  /* C1 L1 */
  pater:"🇮🇹 padre · 🇪🇸 padre · 🇫🇷 père", mater:"🇮🇹 madre · 🇪🇸 madre · 🇫🇷 mère",
  filius:"🇮🇹 figlio · 🇪🇸 hijo · 🇫🇷 fils", filia:"🇮🇹 figlia · 🇪🇸 hija · 🇫🇷 fille",
  rex:"🇪🇸 rey · 🇫🇷 roi · 🇮🇹 re", regina:"🇮🇹 regina · 🇪🇸 reina · 🇫🇷 reine",
  puer:"🇬🇧 puerile · 🇮🇹 puerile", puella:"🇫🇷 pucelle(少女——圣女贞德别号 la Pucelle!)",
  femina:"🇫🇷 femme · 🇮🇹 femmina · 🇪🇸 hembra", vir:"🇮🇹 virile · 🇬🇧 virile",
  frater:"🇮🇹 fratello · 🇫🇷 frère · 🇷🇴 frate", soror:"🇮🇹 sorella · 🇫🇷 sœur · 🇷🇴 soră",
  amicus:"🇮🇹 amico · 🇪🇸 amigo · 🇫🇷 ami", populus:"🇮🇹 popolo · 🇪🇸 pueblo · 🇫🇷 peuple",
  deus:"🇮🇹 dio · 🇪🇸 dios · 🇫🇷 dieu", dea:"🇮🇹 dea · 🇪🇸 diosa · 🇫🇷 déesse",
  heros:"🇮🇹 eroe · 🇪🇸 héroe · 🇫🇷 héros", nomen:"🇮🇹 nome · 🇪🇸 nombre · 🇫🇷 nom",
  familia:"🇮🇹 famiglia · 🇪🇸 familia · 🇫🇷 famille", domus:"🇮🇹 duomo(主教座堂=神之家)· 🇷🇴 domn(先生)",
  /* C1 L2 */
  navis:"🇮🇹 nave · 🇪🇸 nave · 🇫🇷 navire", aqua:"🇪🇸 agua · 🇮🇹 acqua · 🇵🇹 água",
  mare:"🇮🇹 mare · 🇪🇸 mar · 🇫🇷 mer", ventus:"🇮🇹 vento · 🇪🇸 viento · 🇫🇷 vent",
  caelum:"🇮🇹 cielo · 🇪🇸 cielo · 🇫🇷 ciel", stella:"🇮🇹 stella · 🇪🇸 estrella · 🇫🇷 étoile",
  sol:"🇪🇸 sol · 🇮🇹 sole · 🇫🇷 soleil", luna:"🇪🇸 luna · 🇮🇹 luna · 🇫🇷 lune",
  nauta:"🇬🇷 naftis(现代希腊语的\"水手\"!)· 🇬🇧 -naut (astronaut)", insula:"🇮🇹 isola · 🇪🇸 isla · 🇫🇷 île",
  unda:"🇮🇹 onda · 🇪🇸 onda · 🇫🇷 onde", tempestas:"🇮🇹 tempesta · 🇪🇸 tempestad · 🇫🇷 tempête",
  portus:"🇮🇹 porto · 🇪🇸 puerto · 🇫🇷 port", terra:"🇮🇹 terra · 🇪🇸 tierra · 🇫🇷 terre",
  nubes:"🇪🇸 nube · 🇮🇹 nube/nuvola · 🇫🇷 nuage", pluvia:"🇪🇸 lluvia · 🇮🇹 pioggia · 🇫🇷 pluie",
  remus:"🇪🇸 remo · 🇮🇹 remo · 🇫🇷 rame", velum:"🇮🇹 velo · 🇪🇸 velo · 🇫🇷 voile",
  piscis:"🇮🇹 pesce · 🇪🇸 pez · 🇫🇷 poisson", iter:"🇮🇹 itinerario · 🇬🇧 itinerary",
  /* C1 L3 */
  porta:"🇮🇹 porta · 🇪🇸 puerta · 🇫🇷 porte", ianua:"🇮🇹 gennaio(一月)· 🇷🇴 ianuarie",
  murus:"🇮🇹 muro · 🇪🇸 muro · 🇫🇷 mur", turris:"🇮🇹 torre · 🇪🇸 torre · 🇫🇷 tour",
  aula:"🇪🇸 aula(教室!)· 🇮🇹 aula · 🇩🇪 Aula", mensa:"🇪🇸 mesa · 🇵🇹 mesa · 🇷🇴 masă",
  sella:"🇮🇹 sella · 🇪🇸 silla(椅子)· 🇫🇷 selle", lucerna:"🇮🇹 lucerna · 🇪🇸 lucerna",
  fenestra:"🇮🇹 finestra · 🇫🇷 fenêtre · 🇩🇪 Fenster", tectum:"🇮🇹 tetto · 🇪🇸 techo · 🇫🇷 toit",
  columna:"🇪🇸 columna · 🇮🇹 colonna · 🇫🇷 colonne", statua:"🇮🇹 statua · 🇪🇸 estatua · 🇫🇷 statue",
  hortus:"🇮🇹 orto · 🇪🇸 huerto · 🇵🇹 horta", fons:"🇮🇹 fonte · 🇪🇸 fuente · 🇫🇷 fontaine",
  aurum:"🇮🇹 oro · 🇪🇸 oro · 🇫🇷 or · 🇷🇴 aur", argentum:"🇫🇷 argent(银/钱)· 🇮🇹 argento · 🇷🇴 argint",
  marmor:"🇮🇹 marmo · 🇪🇸 mármol · 🇫🇷 marbre", pictura:"🇮🇹 pittura · 🇪🇸 pintura · 🇫🇷 peinture",
  servus:"🇮🇹 servo · 🇪🇸 siervo · 🇫🇷 serf", convivium:"🇮🇹 convivio · 🇪🇸 convite",
  /* C1 L4 */
  filum:"🇮🇹 filo · 🇪🇸 hilo · 🇫🇷 fil", gladius:"🇫🇷 glaive · 🇮🇹 gladiolo",
  donum:"🇮🇹 dono · 🇪🇸 don · 🇫🇷 don", corona:"🇮🇹 corona · 🇪🇸 corona · 🇫🇷 couronne",
  anulus:"🇮🇹 anello · 🇪🇸 anillo · 🇫🇷 anneau", gemma:"🇮🇹 gemma · 🇪🇸 yema(芽/蛋黄)· 🇫🇷 gemme",
  arca:"🇮🇹 arca · 🇪🇸 arca · 🇫🇷 arche", clavis:"🇮🇹 chiave · 🇪🇸 llave · 🇫🇷 clé",
  charta:"🇮🇹 carta · 🇪🇸 carta(信)· 🇫🇷 carte", epistula:"🇮🇹 epistola · 🇪🇸 epístola · 🇫🇷 épître",
  liber:"🇮🇹 libro · 🇪🇸 libro · 🇫🇷 livre", verbum:"🇮🇹 verbo · 🇪🇸 verbo · 🇫🇷 verbe",
  consilium:"🇮🇹 consiglio · 🇪🇸 consejo · 🇫🇷 conseil", fides:"🇮🇹 fede · 🇪🇸 fe · 🇫🇷 foi",
  amor:"🇮🇹 amore · 🇪🇸 amor · 🇫🇷 amour", cor:"🇮🇹 cuore · 🇪🇸 corazón · 🇫🇷 cœur",
  animus:"🇪🇸 ánimo(¡Ánimo! 加油!)· 🇮🇹 animo", sapientia:"🇮🇹 sapienza · 🇪🇸 sabiduría",
  secretum:"🇮🇹 segreto · 🇪🇸 secreto · 🇫🇷 secret", auxilium:"🇪🇸 auxilio(¡Auxilio! 救命!)· 🇮🇹 ausilio",
  /* C1 L5 */
  lux:"🇪🇸 luz · 🇮🇹 luce", tenebrae:"🇮🇹 tenebre · 🇪🇸 tinieblas · 🇫🇷 ténèbres",
  via:"🇮🇹 via · 🇪🇸 vía · 🇫🇷 voie", umbra:"🇮🇹 ombra · 🇪🇸 sombra · 🇫🇷 ombre",
  silentium:"🇮🇹 silenzio · 🇪🇸 silencio · 🇫🇷 silence", timor:"🇮🇹 timore · 🇪🇸 temor",
  ignis:"🇬🇧 ignite · 🇮🇳 agni(梵语同根——印度火神!)", fax:"🇮🇹 fiaccola(火把,来自 facula)",
  flamma:"🇮🇹 fiamma · 🇪🇸 llama · 🇫🇷 flamme", saxum:"🇮🇹 sasso(石头,现代意语常用)",
  labyrinthus:"🇮🇹 labirinto · 🇪🇸 laberinto · 🇫🇷 labyrinthe", angulus:"🇮🇹 angolo · 🇪🇸 ángulo · 🇫🇷 angle",
  dexter:"🇮🇹 destro · 🇪🇸 diestro", sinister:"🇮🇹 sinistro(左=意语日常词!)· 🇪🇸 siniestro · 🇫🇷 sinistre",
  ante:"🇪🇸 antes · 🇮🇹 avanti · 🇫🇷 avant", post:"🇮🇹 poi · 🇪🇸 pues · 🇫🇷 puis",
  sub:"🇮🇹 sotto · 🇫🇷 sous", super:"🇮🇹 sopra · 🇪🇸 sobre · 🇫🇷 sur",
  intra:"🇮🇹 entro · 🇪🇸 entre", exitus:"🇪🇸 éxito(竟变成了\"成功\"!)· 🇮🇹 esito(结果)",
  /* C1 L6 */
  vox:"🇮🇹 voce · 🇪🇸 voz · 🇫🇷 voix", auris:"🇮🇹 orecchio · 🇪🇸 oreja · 🇫🇷 oreille",
  oculus:"🇮🇹 occhio · 🇪🇸 ojo · 🇫🇷 œil", manus:"🇮🇹 mano · 🇪🇸 mano · 🇫🇷 main",
  pes:"🇮🇹 piede · 🇪🇸 pie · 🇫🇷 pied", caput:"🇮🇹 capo(头儿/老大!)· 🇪🇸 cabo · 🇫🇷 chef",
  corpus:"🇮🇹 corpo · 🇪🇸 cuerpo · 🇫🇷 corps", os:"🇪🇸 orificio · 🇬🇧 oral",
  nasus:"🇮🇹 naso · 🇪🇸 nariz · 🇫🇷 nez", digitus:"🇮🇹 dito · 🇪🇸 dedo · 🇫🇷 doigt",
  bracchium:"🇮🇹 braccio · 🇪🇸 brazo · 🇫🇷 bras", genu:"🇮🇹 ginocchio · 🇫🇷 genou",
  capillus:"🇮🇹 capello · 🇪🇸 cabello", dens:"🇮🇹 dente · 🇪🇸 diente · 🇫🇷 dent",
  lingua:"🇮🇹 lingua · 🇪🇸 lengua · 🇫🇷 langue", sanguis:"🇮🇹 sangue · 🇪🇸 sangre · 🇫🇷 sang",
  spiritus:"🇮🇹 spirito · 🇪🇸 espíritu · 🇫🇷 esprit", somnus:"🇮🇹 sonno · 🇪🇸 sueño · 🇫🇷 sommeil",
  vita:"🇮🇹 vita · 🇪🇸 vida · 🇫🇷 vie", mors:"🇮🇹 morte · 🇪🇸 muerte · 🇫🇷 mort",
  /* C1 L7 */
  taurus:"🇮🇹 toro · 🇪🇸 toro · 🇫🇷 taureau", leo:"🇮🇹 leone · 🇪🇸 león · 🇫🇷 lion",
  lupus:"🇮🇹 lupo · 🇪🇸 lobo · 🇫🇷 loup", serpens:"🇮🇹 serpente · 🇪🇸 serpiente · 🇫🇷 serpent",
  aquila:"🇮🇹 aquila · 🇪🇸 águila · 🇫🇷 aigle", equus:"🇪🇸 yegua(母马)· 🇷🇴 iapă",
  canis:"🇮🇹 cane · 🇫🇷 chien · 🇪🇸 can", felis:"🇮🇹 felino · 🇪🇸 felino",
  avis:"🇪🇸 ave · 🇮🇹 uccello(=avicellus 小鸟)", ursus:"🇮🇹 orso · 🇪🇸 oso · 🇫🇷 ours",
  aper:"🇩🇪 Eber(同根日耳曼词)", cervus:"🇮🇹 cervo · 🇪🇸 ciervo · 🇫🇷 cerf",
  vacca:"🇪🇸 vaca · 🇮🇹 vacca · 🇫🇷 vache", ovis:"🇪🇸 oveja · 🇷🇴 oaie",
  capra:"🇮🇹 capra · 🇪🇸 cabra · 🇫🇷 chèvre", porcus:"🇮🇹 porco · 🇪🇸 puerco · 🇫🇷 porc",
  mus:"🇬🇧 mouse · 🇩🇪 Maus(同印欧根)", rana:"🇮🇹 rana · 🇪🇸 rana",
  apis:"🇮🇹 ape(蜜蜂,现代意语!)· 🇫🇷 abeille", monstrum:"🇮🇹 mostro · 🇪🇸 monstruo · 🇫🇷 monstre",
  /* C1 L8 */
  pugna:"🇮🇹 pugno(拳)· 🇪🇸 puño", bellum:"🇬🇧 rebel/belligerent(借词存续)",
  hasta:"🇪🇸 asta(旗杆/角)· 🇮🇹 asta(拍卖!)", scutum:"🇮🇹 scudo · 🇪🇸 escudo · 🇫🇷 écu",
  galea:"🇬🇧 galea(解剖学沿用)", arma:"🇮🇹 arma · 🇪🇸 arma · 🇫🇷 arme",
  sagitta:"🇮🇹 saetta · 🇪🇸 saeta · 🇷🇴 săgeată", arcus:"🇮🇹 arco · 🇪🇸 arco · 🇫🇷 arc",
  hostis:"🇪🇸 hueste(军旅)", miles:"🇮🇹 milite · 🇪🇸 militar",
  fortis:"🇮🇹 forte · 🇪🇸 fuerte · 🇫🇷 fort", magnus:"🇪🇸 tamaño(=tam magnus \"这么大\"→尺寸!)· 🇮🇹 magno",
  parvus:"🇵🇹 parvo(词义漂移:傻的)· 🇬🇧 parvovirus", celer:"🇮🇹 celere(快,现代意语)· 🇬🇧 accelerate",
  tardus:"🇪🇸 tarde(下午/晚!)· 🇮🇹 tardi · 🇫🇷 tard", victoria:"🇮🇹 vittoria · 🇪🇸 victoria · 🇫🇷 victoire",
  gloria:"🇮🇹 gloria · 🇪🇸 gloria · 🇫🇷 gloire", virtus:"🇮🇹 virtù · 🇪🇸 virtud · 🇫🇷 vertu",
  ferrum:"🇮🇹 ferro · 🇪🇸 hierro · 🇫🇷 fer", clamor:"🇪🇸 clamor · 🇮🇹 clamore · 🇫🇷 clameur",
  /* C1 L9 */
  unus:"🇮🇹 uno · 🇪🇸 uno · 🇫🇷 un", duo:"🇮🇹 due · 🇪🇸 dos · 🇫🇷 deux",
  tres:"🇮🇹 tre · 🇪🇸 tres · 🇫🇷 trois", quattuor:"🇮🇹 quattro · 🇪🇸 cuatro · 🇫🇷 quatre",
  quinque:"🇮🇹 cinque · 🇪🇸 cinco · 🇫🇷 cinq", sex:"🇮🇹 sei · 🇪🇸 seis · 🇫🇷 six",
  septem:"🇮🇹 sette · 🇪🇸 siete · 🇫🇷 sept", octo:"🇮🇹 otto · 🇪🇸 ocho · 🇫🇷 huit",
  novem:"🇮🇹 nove · 🇪🇸 nueve · 🇫🇷 neuf", decem:"🇮🇹 dieci · 🇪🇸 diez · 🇫🇷 dix",
  centum:"🇮🇹 cento · 🇪🇸 cien(to) · 🇫🇷 cent", mille:"🇮🇹 mille · 🇪🇸 mil · 🇫🇷 mille",
  albus:"🇷🇴 alb(白,罗语日常词)· 🇮🇹 alba(黎明=天发白)", niger:"🇮🇹 nero · 🇪🇸 negro · 🇫🇷 noir",
  ruber:"🇪🇸 rubio(金发的)· 🇵🇹 rubro", viridis:"🇮🇹 verde · 🇪🇸 verde · 🇫🇷 vert",
  caeruleus:"🇮🇹 ceruleo · 🇬🇧 cerulean", flavus:"🇬🇧 flavone(化学传承)",
  purpureus:"🇮🇹 porpora · 🇪🇸 púrpura · 🇫🇷 pourpre", color:"🇮🇹 colore · 🇪🇸 color · 🇫🇷 couleur",
  /* C1 L10 */
  libertas:"🇮🇹 libertà · 🇪🇸 libertad · 🇫🇷 liberté", felix:"🇮🇹 felice · 🇪🇸 feliz(¡Feliz Navidad!)· 🇵🇹 feliz",
  laetus:"🇮🇹 lieto(高兴,现代意语)", victor:"🇮🇹 vincitore · 🇬🇧 victor",
  patria:"🇮🇹 patria · 🇪🇸 patria · 🇫🇷 patrie", memoria:"🇮🇹 memoria · 🇪🇸 memoria · 🇫🇷 mémoire",
  fama:"🇮🇹 fama · 🇪🇸 fama", historia:"🇮🇹 storia · 🇪🇸 historia · 🇫🇷 histoire",
  finis:"🇮🇹 fine · 🇪🇸 fin · 🇫🇷 fin", initium:"🇮🇹 inizio · 🇪🇸 inicio",
  novus:"🇮🇹 nuovo · 🇪🇸 nuevo · 🇫🇷 neuf", vetus:"🇮🇹 vecchio · 🇪🇸 viejo · 🇫🇷 vieux",
  semper:"🇮🇹 sempre · 🇪🇸 siempre", numquam:"🇪🇸 nunca · 🇵🇹 nunca",
  hodie:"🇮🇹 oggi · 🇪🇸 hoy · 🇫🇷 (aujourd')hui", cras:"🏝️ 撒丁语 cras(至今仍是\"明天\"!)",
  heri:"🇮🇹 ieri · 🇫🇷 hier · 🇪🇸 ayer", tempus:"🇮🇹 tempo · 🇪🇸 tiempo · 🇫🇷 temps",
  annus:"🇮🇹 anno · 🇪🇸 año · 🇫🇷 an", dies:"🇪🇸 día · 🇷🇴 zi · 🇮🇹 dì",
  /* C2 L1 */
  musica:"🇮🇹 musica · 🇪🇸 música · 🇫🇷 musique", carmen:"🇪🇸 Carmen(人名=歌!)· 🇮🇹 carme",
  lyra:"🇮🇹 lira · 🇪🇸 lira", chorda:"🇮🇹 corda · 🇪🇸 cuerda · 🇫🇷 corde",
  sonus:"🇮🇹 suono · 🇪🇸 sonido · 🇫🇷 son", cantus:"🇮🇹 canto · 🇪🇸 canto · 🇫🇷 chant",
  poeta:"🇮🇹 poeta · 🇪🇸 poeta · 🇫🇷 poète", ars:"🇮🇹 arte · 🇪🇸 arte · 🇫🇷 art",
  tibia:"🇪🇸 tibia · 🇮🇹 tibia(解剖通用)", tympanum:"🇮🇹 timpano · 🇪🇸 tímpano",
  numerus:"🇮🇹 numero · 🇪🇸 número · 🇫🇷 nombre", versus:"🇮🇹 verso · 🇪🇸 verso · 🇫🇷 vers",
  fabula:"🇪🇸 habla(\"说话\"就是 fabula!)· 🇮🇹 favola", scaena:"🇮🇹 scena · 🇪🇸 escena · 🇫🇷 scène",
  theatrum:"🇮🇹 teatro · 🇪🇸 teatro · 🇫🇷 théâtre", plausus:"🇮🇹 plauso · 🇪🇸 aplauso",
  silva:"🇪🇸 selva(丛林)· 🇮🇹 selva", arbor:"🇮🇹 albero · 🇪🇸 árbol · 🇫🇷 arbre",
  fera:"🇮🇹 fiera · 🇪🇸 fiera", echo:"🇮🇹 eco · 🇪🇸 eco · 🇫🇷 écho",
  /* C2 L2 */
  sponsa:"🇮🇹 sposa(新娘)· 🇪🇸 esposa(妻子)· 🇫🇷 épouse", sponsus:"🇮🇹 sposo · 🇪🇸 esposo",
  nuptiae:"🇮🇹 nozze · 🇫🇷 noces", taeda:"🇪🇸 tea(松明)",
  flos:"🇮🇹 fiore · 🇪🇸 flor · 🇫🇷 fleur", rosa:"🇮🇹 rosa · 🇪🇸 rosa · 🇫🇷 rose",
  lilium:"🇮🇹 giglio · 🇪🇸 lirio · 🇫🇷 lis", herba:"🇮🇹 erba · 🇪🇸 hierba · 🇫🇷 herbe",
  pratum:"🇮🇹 prato · 🇪🇸 prado · 🇫🇷 pré", vipera:"🇮🇹 vipera · 🇪🇸 víbora · 🇫🇷 vipère",
  venenum:"🇮🇹 veleno · 🇪🇸 veneno · 🇫🇷 venin", vulnus:"🇪🇸 vulnerar · 🇬🇧 vulnerable",
  gaudium:"🇮🇹 gioia · 🇪🇸 gozo · 🇫🇷 joie", lacrima:"🇮🇹 lacrima · 🇪🇸 lágrima · 🇫🇷 larme",
  dolor:"🇮🇹 dolore · 🇪🇸 dolor · 🇫🇷 douleur", luctus:"🇪🇸 luto(丧,现代西语)· 🇮🇹 lutto",
  funus:"🇮🇹 funerale · 🇪🇸 funeral · 🇫🇷 funérailles", sepulcrum:"🇮🇹 sepolcro · 🇪🇸 sepulcro",
  cinis:"🇮🇹 cenere · 🇪🇸 ceniza · 🇫🇷 cendre", fatum:"🇮🇹 fato · 🇪🇸 hado",
  /* C2 L3 */
  inferi:"🇮🇹 inferno · 🇪🇸 infierno · 🇫🇷 enfer", regnum:"🇮🇹 regno · 🇪🇸 reino · 🇫🇷 règne",
  imperium:"🇮🇹 impero · 🇪🇸 imperio · 🇫🇷 empire", thronus:"🇮🇹 trono · 🇪🇸 trono · 🇫🇷 trône",
  sceptrum:"🇮🇹 scettro · 🇪🇸 cetro · 🇫🇷 sceptre", caverna:"🇮🇹 caverna · 🇪🇸 caverna · 🇫🇷 caverne",
  spelunca:"🇮🇹 spelonca", abyssus:"🇮🇹 abisso · 🇪🇸 abismo · 🇫🇷 abîme",
  vallis:"🇮🇹 valle · 🇪🇸 valle · 🇫🇷 val", mons:"🇮🇹 monte · 🇪🇸 monte · 🇫🇷 mont",
  collis:"🇮🇹 colle/collina · 🇪🇸 colina", ripa:"🇮🇹 riva · 🇫🇷 rive · 🇪🇸 ribera",
  fluvius:"🇪🇸 fluvial · 🇮🇹 fluviale", stagnum:"🇫🇷 étang(池塘!)· 🇮🇹 stagno · 🇪🇸 estanque",
  palus:"🇮🇹 palude(现代意语常用)", nebula:"🇮🇹 nebbia(雾)· 🇪🇸 niebla",
  frigus:"🇮🇹 freddo · 🇪🇸 frío · 🇫🇷 froid", gelu:"🇮🇹 gelo · 🇪🇸 hielo · 🇫🇷 gel",
  horror:"🇮🇹 orrore · 🇪🇸 horror · 🇫🇷 horreur", custos:"🇮🇹 custode · 🇪🇸 custodio",
  /* C2 L4 */
  portitor:"🇫🇷 porteur · 🇬🇧 porter", cymba:"🇮🇹 cimba(诗语)",
  ratis:"🇬🇧 raft(同根)", merces:"🇪🇸 merced(usted=vuestra merced \"您\"!)· 🇮🇹 mercede",
  nummus:"🇬🇷 nómisma(现代希腊语\"货币\")", latratus:"🇪🇸 ladrido(犬吠)· 🇮🇹 latrato",
  guttur:"🇬🇧 guttural", ungula:"🇪🇸 uña(指甲!)· 🇮🇹 unghia · 🇫🇷 ongle",
  cauda:"🇮🇹 coda · 🇪🇸 cola · 🇫🇷 queue", pellis:"🇮🇹 pelle(皮肤)· 🇪🇸 piel · 🇫🇷 peau",
  belua:"—(仅存于诗中)", draco:"🇮🇹 drago · 🇪🇸 dragón · 🇫🇷 dragon",
  gigas:"🇮🇹 gigante · 🇪🇸 gigante · 🇫🇷 géant", nympha:"🇮🇹 ninfa · 🇪🇸 ninfa · 🇫🇷 nymphe",
  anima:"🇪🇸 alma(灵魂)· 🇮🇹 anima · 🇫🇷 âme", spectrum:"🇮🇹 spettro · 🇪🇸 espectro · 🇫🇷 spectre",
  phantasma:"🇮🇹 fantasma · 🇪🇸 fantasma · 🇫🇷 fantôme", turba:"🇪🇸 turba · 🇮🇹 turba",
  multitudo:"🇪🇸 multitud · 🇮🇹 moltitudine · 🇫🇷 multitude", ordo:"🇮🇹 ordine · 🇪🇸 orden · 🇫🇷 ordre",
  /* C2 L5 */
  oblivio:"🇪🇸 olvido(遗忘,现代西语核心词!)· 🇮🇹 oblio · 🇫🇷 oubli",
  flumen:"🇮🇹 fiume(河,现代意语日常词)", rivus:"🇪🇸 río!· 🇮🇹 rio · 🇫🇷 ru",
  lacus:"🇮🇹 lago · 🇪🇸 lago · 🇫🇷 lac", gurges:"🇮🇹 gorgo · 🇫🇷 gorge",
  vortex:"🇪🇸 vórtice · 🇮🇹 vortice", gutta:"🇮🇹 goccia · 🇪🇸 gota · 🇫🇷 goutte",
  umor:"🇮🇹 umore(心情)· 🇪🇸 humor · 🇫🇷 humeur", vapor:"🇮🇹 vapore · 🇪🇸 vapor · 🇫🇷 vapeur",
  ardor:"🇮🇹 ardore · 🇪🇸 ardor · 🇫🇷 ardeur", aestus:"🇮🇹 estate(夏天)· 🇪🇸 estío",
  glacies:"🇮🇹 ghiaccio · 🇫🇷 glace", sulphur:"🇮🇹 zolfo · 🇪🇸 azufre · 🇫🇷 soufre",
  sitis:"🇪🇸 sed · 🇮🇹 sete · 🇫🇷 soif", fames:"🇮🇹 fame · 🇪🇸 hambre · 🇫🇷 faim",
  poculum:"🇬🇧 potable(可饮的)", potio:"🇮🇹 pozione · 🇪🇸 poción · 🇫🇷 potion",
  limus:"🇪🇸 limo · 🇮🇹 limo", murmur:"🇮🇹 mormorio · 🇪🇸 murmullo · 🇫🇷 murmure",
  profundum:"🇮🇹 profondo · 🇪🇸 profundo · 🇫🇷 profond",
  /* C2 L6 */
  iudex:"🇮🇹 giudice · 🇪🇸 juez · 🇫🇷 juge", iudicium:"🇮🇹 giudizio · 🇪🇸 juicio",
  lex:"🇮🇹 legge · 🇪🇸 ley · 🇫🇷 loi", ius:"🇮🇹 giusto · 🇬🇧 justice",
  iustitia:"🇮🇹 giustizia · 🇪🇸 justicia · 🇫🇷 justice", crimen:"🇮🇹 crimine · 🇪🇸 crimen · 🇫🇷 crime",
  culpa:"🇮🇹 colpa(现代意语日常词)· 🇪🇸 culpa", poena:"🇮🇹 pena · 🇪🇸 pena(¡Qué pena!)· 🇫🇷 peine",
  carcer:"🇮🇹 carcere · 🇪🇸 cárcel", catena:"🇮🇹 catena · 🇪🇸 cadena · 🇫🇷 chaîne",
  vinculum:"🇪🇸 vínculo · 🇮🇹 vincolo", veritas:"🇮🇹 verità · 🇪🇸 verdad · 🇫🇷 vérité",
  testis:"🇮🇹 testimone · 🇪🇸 testigo · 🇫🇷 témoin", causa:"🇮🇹/🇪🇸 cosa(\"东西\"就是 causa!)· 🇫🇷 chose",
  sententia:"🇮🇹 sentenza · 🇪🇸 sentencia · 🇫🇷 sentence", innocens:"🇮🇹 innocente · 🇪🇸 inocente · 🇫🇷 innocent",
  nocens:"🇬🇧 noxious", supplicium:"🇪🇸 suplicio · 🇮🇹 supplizio · 🇫🇷 supplice",
  labor:"🇮🇹 lavoro(工作,意语核心词!)· 🇪🇸 labor · 🇫🇷 labeur", rota:"🇮🇹 ruota · 🇪🇸 rueda · 🇫🇷 roue",
  /* C2 L7 */
  dominus:"🇪🇸 don(堂·吉诃德的 Don!)· 🇷🇴 domn(先生)· 🇮🇹 don",
  domina:"🇮🇹 donna(女人)· 🇪🇸 doña · 🇫🇷 dame", maiestas:"🇮🇹 maestà · 🇪🇸 majestad · 🇫🇷 majesté",
  potentia:"🇮🇹 potenza · 🇪🇸 potencia · 🇫🇷 puissance", potestas:"🇮🇹 podestà · 🇪🇸 potestad",
  honor:"🇮🇹 onore · 🇪🇸 honor · 🇫🇷 honneur", superbia:"🇮🇹 superbia · 🇪🇸 soberbia",
  ira:"🇮🇹 ira · 🇪🇸 ira · 🇫🇷 ire", invidia:"🇮🇹 invidia · 🇪🇸 envidia · 🇫🇷 envie",
  misericordia:"🇮🇹 misericordia · 🇪🇸 misericordia · 🇫🇷 miséricorde", clementia:"🇮🇹 clemenza · 🇪🇸 clemencia · 🇫🇷 clémence",
  preces:"🇮🇹 preghiera · 🇪🇸 plegaria · 🇫🇷 prière", votum:"🇮🇹 voto · 🇪🇸 voto · 🇫🇷 vœu",
  templum:"🇮🇹 tempio · 🇪🇸 templo · 🇫🇷 temple", ara:"🇪🇸 ara(书面语)· 🇮🇹 ara",
  sacrificium:"🇮🇹 sacrificio · 🇪🇸 sacrificio · 🇫🇷 sacrifice", thesaurus:"🇮🇹 tesoro · 🇪🇸 tesoro · 🇫🇷 trésor",
  opes:"🇬🇧 opulent", diadema:"🇮🇹 diadema · 🇪🇸 diadema · 🇫🇷 diadème",
  numen:"🇬🇧 numinous",
  /* C2 L8 */
  eloquentia:"🇮🇹 eloquenza · 🇪🇸 elocuencia · 🇫🇷 éloquence", suavitas:"🇪🇸 suave(现代西语超常用!)· 🇮🇹 soave",
  dulcis:"🇮🇹 dolce!· 🇪🇸 dulce · 🇫🇷 doux", amarus:"🇮🇹 amaro · 🇪🇸 amargo · 🇫🇷 amer",
  mollis:"🇮🇹 molle · 🇪🇸 muelle · 🇫🇷 mou", durus:"🇮🇹 duro · 🇪🇸 duro · 🇫🇷 dur",
  blandus:"🇪🇸 blando(软的,现代西语)· 🇮🇹 blando", ferox:"🇮🇹 feroce · 🇪🇸 feroz · 🇫🇷 féroce",
  mirus:"🇪🇸 mirar(\"看\"就来自 mirari!)· 🇮🇹 mirare(瞄准)", mirabilis:"🇮🇹 meraviglia · 🇪🇸 maravilla · 🇫🇷 merveille",
  stupor:"🇮🇹 stupore · 🇪🇸 estupor", admiratio:"🇮🇹 ammirazione · 🇪🇸 admiración · 🇫🇷 admiration",
  desiderium:"🇮🇹 desiderio · 🇪🇸 deseo · 🇫🇷 désir", spes:"🇮🇹 speranza · 🇪🇸 esperanza · 🇫🇷 espoir",
  promissum:"🇮🇹 promessa · 🇪🇸 promesa · 🇫🇷 promesse", condicio:"🇮🇹 condizione · 🇪🇸 condición · 🇫🇷 condition",
  pactum:"🇮🇹 patto · 🇪🇸 pacto · 🇫🇷 pacte", foedus:"🇬🇧 federal/federation",
  gratia:"🇮🇹 grazie!· 🇪🇸 gracias!· 🇫🇷 grâce", venia:"🇪🇸 venia(拉美:许可/致意)",
  /* C2 L9 */
  aspectus:"🇮🇹 aspetto · 🇪🇸 aspecto · 🇫🇷 aspect", visus:"🇮🇹 viso(脸!)· 🇫🇷 visage",
  retro:"🇫🇷 derrière(=de retro)· 🇮🇹 dietro(=de retro)", gradus:"🇮🇹 grado · 🇪🇸 grado · 🇫🇷 degré",
  passus:"🇮🇹 passo · 🇪🇸 paso · 🇫🇷 pas(ne...pas=一步也不!)", cursus:"🇮🇹 corso · 🇪🇸 curso · 🇫🇷 cours",
  fuga:"🇮🇹 fuga · 🇪🇸 fuga · 🇫🇷 fugue", reditus:"🇮🇹 reddito(收入=回来的钱!)· 🇪🇸 rédito(利息)",
  ascensus:"🇮🇹 ascesa · 🇪🇸 ascenso · 🇫🇷 ascension", descensus:"🇮🇹 discesa · 🇪🇸 descenso · 🇫🇷 descente",
  lumen:"🇮🇹 lume · 🇪🇸 lumbre · 🇫🇷 lumière", claritas:"🇪🇸 claridad · 🇫🇷 clarté",
  obscuritas:"🇮🇹 oscurità · 🇪🇸 oscuridad · 🇫🇷 obscurité", dubium:"🇮🇹 dubbio · 🇪🇸 duda · 🇫🇷 doute",
  cura:"🇮🇹 cura · 🇪🇸 cura · 🇫🇷 cure", desperatio:"🇮🇹 disperazione · 🇪🇸 desesperación · 🇫🇷 désespoir",
  fiducia:"🇮🇹 fiducia(信任,意语核心词!)", patientia:"🇮🇹 pazienza · 🇪🇸 paciencia · 🇫🇷 patience",
  festinatio:"🇮🇹 festina lente(格言仍在引用)", error:"🇮🇹 errore · 🇪🇸 error · 🇫🇷 erreur",
  /* C2 L10 */
  aeternitas:"🇮🇹 eternità · 🇪🇸 eternidad · 🇫🇷 éternité", immortalitas:"🇮🇹 immortalità · 🇪🇸 inmortalidad · 🇫🇷 immortalité",
  natura:"🇮🇹 natura · 🇪🇸 naturaleza · 🇫🇷 nature", mundus:"🇮🇹 mondo · 🇪🇸 mundo · 🇫🇷 monde",
  orbis:"🇪🇸 orbe · 🇮🇹 orbe", principium:"🇮🇹 principio · 🇪🇸 principio · 🇫🇷 principe",
  elementum:"🇮🇹 elemento · 🇪🇸 elemento · 🇫🇷 élément", harmonia:"🇮🇹 armonia · 🇪🇸 armonía · 🇫🇷 harmonie",
  concordia:"🇮🇹 concordia · 🇪🇸 concordia · 🇫🇷 concorde", discordia:"🇮🇹 discordia · 🇪🇸 discordia · 🇫🇷 discorde",
  genius:"🇮🇹 genio · 🇪🇸 genio · 🇫🇷 génie", laurus:"🇮🇹 alloro · 🇪🇸 laurel · 🇫🇷 laurier",
  praemium:"🇮🇹 premio(奖)· 🇪🇸 premio · 🇫🇷 prix", monumentum:"🇮🇹 monumento · 🇪🇸 monumento · 🇫🇷 monument",
  littera:"🇮🇹 lettera · 🇪🇸 letra · 🇫🇷 lettre", scriptor:"🇮🇹 scrittore · 🇪🇸 escritor · 🇫🇷 écrivain",
  lector:"🇮🇹 lettore · 🇪🇸 lector · 🇫🇷 lecteur", vates:"🇪🇸 vate(诗人雅称)· 🇮🇹 vate",
  opus:"🇮🇹 opera · 🇪🇸 obra · 🇫🇷 œuvre", auctor:"🇮🇹 autore · 🇪🇸 autor · 🇫🇷 auteur",
};
