/* =====================================================
   FUGA MYTHICA — ROOT_STORIES batch 11: roots for the map-adventure words
   in French / Italian / Spanish (and Latin loans in German) that had no root.
   One line per root: id | 中文 | English. Shared by fr/it/es; German loans
   reach these through ROOT_STORIES.deMap (set in tgroots.js).
   Disputed etymologies are labelled as disputed.
   ===================================================== */
(function () {
  const RAW = String.raw`
g_ragazz|意大利语 ragazzo/ragazza(男孩/女孩)的来历至今有争议。最常见的说法是来自阿拉伯语 raqqāṣ(跑腿的信使),经西西里的阿拉伯-诺曼宫廷进入意大利语,起初指"小厮、跑腿的",后来才泛指少年;另一说是来自希腊语 rhakos(破布)——"穿破衣的小孩"。两说都没有定论。可以确定的是:它在中世纪意大利语里先有"仆役"义,文艺复兴以后才成为最普通的"男孩/女孩"。同一个词族:ragazzata(孩子气的举动)、ragazzino(小男孩)、ragazzaccio(坏小子)。|Italian ragazzo/ragazza (boy/girl) has a disputed origin. The most common view derives it from Arabic raqqāṣ (a running messenger), entering Italian through the Arab-Norman court of Sicily and meaning first a page or errand-boy; another view points to Greek rhakos (a rag) — the ragged child. Neither is settled. What is certain is that medieval Italian used it for a servant lad, and only after the Renaissance did it become the everyday word for boy or girl. Family: ragazzata (a childish prank), ragazzino (a little boy), ragazzaccio (a rascal).
g_garc|法语 garçon(男孩)来自古法语 gars(属格/宾格 garçon),可能出自法兰克语 *wrakjo(被放逐者、雇佣兵——与古英语 wrecca 流亡者、英语 wretch 可怜人同源)。中世纪的 garçon 是"小厮、马夫",带贬义;到 17 世纪才变成中性的"男孩",同时保留"侍者"义——咖啡馆里喊 Garçon! 就是这层旧义。gars(小伙子)至今是口语。同族:garçonnet(小男孩)、garçonnière(单身公寓)。|French garçon (boy) comes from Old French gars (oblique case garçon), probably from Frankish *wrakjo (an outcast, a mercenary — cognate with Old English wrecca, an exile, and English wretch). In the Middle Ages a garçon was a servant or groom, with a sneer in it; only in the 17th century did it become the neutral word for boy, keeping the sense of waiter — which is why you call Garçon! in a café. Gars (lad) survives in speech. Family: garçonnet (little boy), garçonnière (a bachelor flat).
g_rem|remus(桨)来自印欧语 *h₁reh₁-(划船),与希腊语 eretmos(桨)、梵语 aritra(桨)、英语 rudder(舵——古英语 rōðor)、row(划)、德语 Ruder 同根:意大利语 remo、西班牙语 remo 直接继承;法语 rame 是 remus 受 ramus(树枝)影响的形式。trireme(三列桨战船)=tri+remus——雅典的三列桨战船在萨拉米斯海战(公元前 480 年)击败波斯。同族:意 remare/西 remar(划桨)、法 ramer、rameur(桨手)。|Latin remus (an oar) goes back to PIE *h₁reh₁- (to row), cognate with Greek eretmos (oar), Sanskrit aritra, English rudder (Old English rōðor) and row, German Ruder. Italian remo and Spanish remo inherit it directly; French rame is remus reshaped by ramus (a branch). A trireme is tri- + remus — the Athenian triremes that beat Persia at Salamis in 480 BC. Family: Italian remare, Spanish remar (to row), French ramer, rameur (an oarsman).
g_usc|意大利语 uscio(房门)来自拉丁语 ustium,是 ostium(门口、河口)的俗拉丁形;ostium 又出自 os(嘴)——门是房子的"嘴"。同一个词给了 uscire(出去——"走出门口")、uscita(出口,地图里的 exitus 也是它)、usciere(门房、法警)。Ostia(罗马的海港)就是"台伯河口"。|Italian uscio (a door) comes from Latin ustium, a Vulgar form of ostium (a doorway, a river mouth), itself from os (mouth): the door is the house's mouth. The same word gave uscire (to go out — to pass the doorway), uscita (an exit), usciere (a doorkeeper, a bailiff). Ostia, Rome's port, is simply the mouth of the Tiber.
g_lamp|希腊语 lampas(火炬、灯)来自 lampein(发光),印欧语 *leh₂p-(照耀),与古爱尔兰语 lassair(火焰)同根。拉丁语借为 lampas,俗拉丁 *lampada 给出法语 lampe、意大利语 lampada、西班牙语 lámpara;德语 Lampe 借自法语。希腊的 lampadēdromia 是持火炬接力赛——奥运圣火传递的古代原型。同族:lampadaire(路灯)、lampion(灯笼)、意 lampadario(吊灯)、lampo(闪电)。|Greek lampas (a torch, a lamp) comes from lampein (to shine), PIE *leh₂p- (to glow), cognate with Old Irish lassair (flame). Latin borrowed lampas, and Vulgar *lampada gave French lampe, Italian lampada, Spanish lámpara; German Lampe came from French. The Greek lampadēdromia was a torch relay — the ancient model of the Olympic torch run. Family: lampadaire (a street lamp), lampion (a lantern), Italian lampadario (a chandelier), lampo (lightning).
g_luc|lucere(发光)来自印欧语 *lewk-(光、亮),与 lux(光)、luna(月——*louksnā)、lumen、希腊语 leukos(白)、英语 light、德语 Licht 同根。lucerna(油灯)就是"发光的东西";意大利语 lucerna 至今指油灯,lucciola 是萤火虫,luce 是光。同族:lucido(明亮、清醒)、lucente(闪亮的)、Lucifer("带来光的"——晨星)。|Latin lucere (to shine) comes from PIE *lewk- (light), kin to lux (light), luna (the moon, from *louksnā), lumen, Greek leukos (white), English light, German Licht. A lucerna is the shining thing, an oil lamp; Italian lucerna still means one, lucciola is a firefly, luce is light. Family: lucido (bright, lucid), lucente (gleaming), Lucifer (the light-bringer — the morning star).
g_column|columna(柱子)与 culmen(顶点)、collis(山丘)、celsus(高)同根:印欧语 *kelH-(升起、突出)——英语 hill、holm 也是它。柱子是"耸起的东西"。罗马人的 columna rostrata 装饰着缴获的船首,图拉真柱(113 年)用螺旋浮雕讲述达契亚战争。法语 colonne、意大利语 colonna、西班牙语 columna;军队的纵队、报纸的专栏都叫它(英语 column、德语 Kolumne 是借词)。同族:colonnade(柱廊)、colonnello(上校——"纵队长"!colonel)。|Latin columna (a column) shares a root with culmen (the summit), collis (a hill) and celsus (lofty): PIE *kelH- (to rise, to stand out) — English hill and holm too. A column is the thing that towers up. The Romans decorated the columna rostrata with captured ship-prows, and Trajan's Column (113) tells the Dacian wars in a spiral frieze. French colonne, Italian colonna, Spanish columna; the word also means a marching column and a newspaper column (English column, German Kolumne are loans). Family: colonnade, colonnello (a colonel — the commander of a column!).
g_banc|意大利语 banco(长凳、柜台)来自日耳曼语 *bankiz(长凳——德语 Bank、英语 bench),伦巴第人带入意大利。宴席摆长凳,于是 banchetto(小长凳→宴会)在 14 世纪出现,传到法语 banquet、西班牙语 banquete。换钱商坐在市场长凳上营业,banco 又变成"银行"(bank);破产的钱商被砸断长凳——banca rotta,就是 bankrupt(破产)!|Italian banco (a bench, a counter) comes from Germanic *bankiz (a bench — German Bank, English bench), brought in by the Lombards. Feasts were served at benches, so banchetto (a little bench, then a feast) appears in the 14th century and passes to French banquet and Spanish banquete. Money-changers traded at benches in the market, so banco also became the bank; a failed changer's bench was broken — banca rotta, whence bankrupt!
g_anul|anulus(戒指)是 anus(环)的小称——"小环";印欧语 *h₂eh₂no-(环)存疑,与古爱尔兰语 ánne(环)比较。罗马的 anulus aureus(金戒指)是骑士阶层的身份标志,元老院投票用戒指盖印。法语 anneau、意大利语 anello、西班牙语 anillo 都是它;annulaire(无名指——"戴戒指的指头")、annular eclipse(日环食)同族。|Latin anulus (a ring) is the diminutive of anus (a ring) — a little ring; PIE *h₂eh₂no- is uncertain, compared with Old Irish ánne. The Roman anulus aureus, the gold ring, marked the equestrian order, and seals were pressed with rings. French anneau, Italian anello and Spanish anillo all continue it; annulaire (the ring finger) and an annular eclipse belong here too.
g_gemm|gemma(宝石)本义是"芽、花苞"——罗马园艺用 gemma 指葡萄藤上的芽,因芽的光泽而转指宝石。词源不明,可能与 gignere(生)有关(存疑)。法语 gemme、意大利语 gemma、西班牙语 gema;gemmologie(宝石学)、gemmation(发芽)两义都还活着。维吉尔用 gemmare 形容葡萄"出芽"。|Latin gemma (a gem) first meant a bud: Roman gardeners called the vine's bud a gemma, and its gloss carried the word over to jewels. The origin is unclear, perhaps linked to gignere (to beget) — disputed. French gemme, Italian gemma, Spanish gema; both senses live on in gemmology and gemmation (budding). Virgil uses gemmare of vines coming into bud.
g_consul|consilium(商议、计划、建议)与 consul(执政官)、consulere(商议、征询)同根:con-(一起)+ *sel-(拿、取)存疑——"一起拿主意"。罗马共和国每年选两名 consul 共同执政,元老院是 consilium 的最高形式。法语 conseil、意大利语 consiglio、西班牙语 consejo;conseiller(顾问)、consulter(咨询)、consultant、欧盟的 Conseil européen 都是它。|Latin consilium (deliberation, a plan, advice) shares its root with consul and consulere (to deliberate, to consult): con- (together) plus a disputed *sel- (to take) — taking counsel together. The Roman Republic elected two consuls each year to govern jointly, and the Senate was the highest consilium. French conseil, Italian consiglio, Spanish consejo; conseiller (an adviser), consulter, consultant and the European Council all descend from it.
g_tenebr|tenebrae(黑暗,只用复数)来自印欧语 *temH-(暗),与梵语 tamas(黑暗)、德语 Dämmerung(黄昏)、英语 dim?(存疑)同根。拉丁语的 -br- 是 *-sr- 的音变(*temasrai)。天主教圣周的 Tenebrae 仪式逐一熄灭烛火,最后在黑暗中结束。法语 ténèbres、意大利语 tenebre、西班牙语 tinieblas(都保留复数!);ténébreux(阴沉的)、tenebroso 同族。|Latin tenebrae (darkness, plural only) comes from PIE *temH- (dark), cognate with Sanskrit tamas (darkness) and German Dämmerung (twilight). The Latin -br- is a sound change from *-sr- (*temasrai). In the Holy Week service of Tenebrae the candles are put out one by one until it ends in darkness. French ténèbres, Italian tenebre and Spanish tinieblas all keep the plural; ténébreux (gloomy) and tenebroso are kin.
g_fac|fax(火把,属格 facis)的小称 facula(小火把)给出意大利语 fiaccola、德语 Fackel(早期借词)。印欧语来源不明。罗马婚礼上,新娘由 fax nuptialis(婚礼火把)照着送到新郎家——所以意大利语 face nuziale 就是"婚礼火把"。法语的 torche 和西班牙语 antorcha 则来自 torquere(拧)——拧成股的火把,见 tort。|Latin fax (a torch, genitive facis) had the diminutive facula, which gave Italian fiaccola and the early German loan Fackel. Its PIE source is unknown. At a Roman wedding the bride was escorted to the groom's house by the fax nuptialis — hence Italian face nuziale, the wedding torch. French torche and Spanish antorcha come instead from torquere, to twist: a twisted torch (see tort).
g_labyr|labyrinthos(迷宫)是前希腊语词,最流行的解释把它连到吕底亚语 labrys(双刃斧)——克诺索斯宫殿到处刻着双斧标志,"双斧之宫"就成了迷宫。这个解释很有名但并未证实。代达罗斯为米诺斯王建迷宫关住牛头怪,忒修斯靠阿里阿德涅的线走出。法语 labyrinthe、意大利语 labirinto、西班牙语 laberinto、德语 Labyrinth;内耳的 labyrinth(迷路)也是它。|Greek labyrinthos is a pre-Greek word, most famously linked to Lydian labrys (a double axe) — the palace of Knossos is carved everywhere with double axes, so the house of the double axe became the maze. The explanation is famous but unproven. Daedalus built it for King Minos to hold the Minotaur, and Theseus escaped with Ariadne's thread. French labyrinthe, Italian labirinto, Spanish laberinto, German Labyrinth; the inner ear's labyrinth is the same word.
g_gauch|法语 gauche(左)在 15 世纪才取代古法语 senestre(<sinister)。它来自动词 gauchir(弯曲、歪斜),可能出自法兰克语 *walkan(踩、揉——英语 walk 原义"滚动"),受古法语 guenchir(闪避)影响——左手是"笨拙歪斜"的手。所以 gauche 至今兼"笨拙"义(英语借去 gauche"粗鲁笨拙")。1789 年国民议会里激进派坐在议长左边——政治的"左派"la gauche 由此而来。|French gauche (left) displaced Old French senestre (from sinister) only in the 15th century. It comes from the verb gauchir (to warp, to swerve), probably Frankish *walkan (to tread, to full cloth — English walk once meant to roll), influenced by Old French guenchir (to dodge): the left is the crooked, clumsy hand. So gauche still means awkward (English borrowed it in that sense). In 1789 the radicals sat to the left of the president of the National Assembly — and that is where the political left, la gauche, comes from.
g_sinistr|sinister(左的)来源不明。罗马占卜里,鸟从左方出现是吉兆(与希腊相反!),但后来受希腊习惯影响,左方转为不祥——sinister 于是兼有"左"与"凶"。意大利语 sinistro 至今两义俱全:a sinistra(在左边)、un sinistro(一起事故,保险术语!)、la sinistra(政治左派)。英语 sinister 只剩"凶险";纹章学里的 bend sinister 是"左斜带"。|Latin sinister (left) has no clear etymology. In Roman augury birds appearing on the left were a GOOD sign (the reverse of Greek practice), but under Greek influence the left turned ominous, so sinister came to mean both left and baleful. Italian sinistro keeps both: a sinistra (on the left), un sinistro (an accident — insurance jargon!), la sinistra (the political left). English sinister kept only the menace; heraldry's bend sinister is the left-hand band.
g_izquierd|西班牙语 izquierdo(左)是罗曼语里最特别的"左":它来自巴斯克语 ezker(左、左手),是伊比利亚半岛前罗马语言留在西班牙语里的少数常用词之一(葡萄牙语 esquerdo、加泰罗尼亚语 esquerre 同源)。拉丁语的 sinister 在这里被挤掉了——也许正因为"左"是忌讳词,人们爱换新说法。同族:izquierda(左派,la izquierda)、izquierdista(左翼的)。|Spanish izquierdo (left) is the most unusual left in Romance: it comes from Basque ezker (left, the left hand), one of the few everyday words the pre-Roman languages of Iberia left in Spanish (Portuguese esquerdo and Catalan esquerre share it). Latin sinister was pushed out here — perhaps because left was a taboo word people kept replacing. Family: la izquierda (the political left), izquierdista (left-wing).
g_capill|capillus(头发)通常解释为 caput(头)的派生——"头上的"(存疑,也有人认为与 pilus 毛发有关)。罗马人把头发(capillus)与体毛(pilus)分开。法语 cheveu、意大利语 capello、西班牙语 cabello 都来自它;capillaire(毛细血管——"像头发一样细的"!)、capillarité(毛细现象)同族,cappellino(细面)?不同——那是 cappello(帽)。|Latin capillus (the hair of the head) is usually explained as a derivative of caput (the head) — though some link it to pilus (hair), so it is disputed. The Romans distinguished capillus from body hair, pilus. French cheveu, Italian capello and Spanish cabello all come from it; capillaire (a capillary — as fine as a hair!) and capillarity belong here, while Italian cappello (a hat) is a different word.
g_taur|taurus(公牛)来自印欧语 *(s)táwros,与希腊语 tauros、古爱尔兰语 tarb、哥特语 stiur——德语 Stier、英语 steer(阉牛)同根。克里特的米诺陶(Minotauros)="米诺斯的牛"。法语 taureau、意大利语 toro、西班牙语 toro;斗牛士 torero、斗牛 tauromaquia、星座 Taurus(金牛座)。|Latin taurus (a bull) comes from PIE *(s)táwros, cognate with Greek tauros, Old Irish tarb, Gothic stiur — German Stier and English steer. Crete's Minotauros is Minos's bull. French taureau, Italian toro, Spanish toro; the torero, tauromaquia (bullfighting) and the constellation Taurus.
g_aquil|aquila(鹰)可能来自 aquilus(暗褐色的)——"黑褐色的鸟"(存疑)。罗马军团的 aquila(鹰旗)是最神圣的军旗,马略在公元前 104 年把它定为唯一军团标志;丢失鹰旗是奇耻大辱(条顿堡森林,9 年)。法语 aigle、意大利语 aquila、西班牙语 águila;aquilin(鹰钩的——aquiline nose)同族。|Latin aquila (an eagle) may come from aquilus (dark brown) — the dusky bird — though this is disputed. The legion's aquila was its most sacred standard, made the sole legionary emblem by Marius in 104 BC; losing an eagle was the worst disgrace (the Teutoburg Forest, AD 9). French aigle, Italian aquila, Spanish águila; aquiline (hooked, like an eagle's beak) is kin.
g_catt|cattus(猫)在拉丁语里 4 世纪才出现,取代古典的 feles——家猫本身晚期才从埃及-近东传入欧洲,词与动物一起旅行,来源不明(常被推测为非洲语言,如努比亚语 kadīs,属推测)。法语 chat、意大利语 gatto、西班牙语 gato、德语 Katze、英语 cat 都是这个流浪词。同族:法 chaton(小猫)、意 gattino、西 gatito。|Latin cattus (a cat) appears only in the 4th century, replacing classical feles — the domestic cat itself reached Europe late from Egypt and the Near East, and word and animal travelled together; the source is unknown (an African language such as Nubian kadīs is often guessed). French chat, Italian gatto, Spanish gato, German Katze and English cat are all this Wanderwort. Family: French chaton (kitten), Italian gattino, Spanish gatito.
g_cerv|cervus(鹿)来自印欧语 *ḱerh₂-(角、头),"有角的"——与 cornu(角)、希腊语 keras(角)、英语 horn、hart(雄鹿)同根。法语 cerf、意大利语 cervo、西班牙语 ciervo。cervical(颈的)不是它——那是 cervix(颈)。|Latin cervus (a stag) comes from PIE *ḱerh₂- (horn, head): the horned one — kin to cornu (horn), Greek keras, English horn and hart. French cerf, Italian cervo, Spanish ciervo. Cervical is not related — that is cervix, the neck.
g_capr|capra(母山羊)、caper(公山羊)来自印欧语 *kapro-(公羊),与古爱尔兰语 gabor、古挪威语 hafr 同根。法语 chèvre(c→ch,a→è 是法语的规则音变)、意大利语 capra、西班牙语 cabra。capriccio(随想曲——"山羊般跳跃的念头"!)、caprice、摩羯座 Capricorn("山羊角")、意大利卡普里岛(Capri,可能是"山羊岛")同族。|Latin capra (a she-goat) and caper (a he-goat) come from PIE *kapro- (a buck), cognate with Old Irish gabor and Old Norse hafr. French chèvre (c→ch and a→è are regular French sound changes), Italian capra, Spanish cabra. Capriccio and caprice (a goat-like leap of fancy!), Capricorn (goat-horn) and perhaps the isle of Capri (goat island) belong here.
g_ran|rana(青蛙)可能是拟声词(模仿蛙鸣),印欧语亲缘不明。意大利语、西班牙语都叫 rana;法语 grenouille 来自俗拉丁 *ranucula(小青蛙),在古法语 reinoille 上加了拟声的 gr-。raninculus("小青蛙")是毛茛属 Ranunculus 的名字——因为它长在青蛙出没的湿地。|Latin rana (a frog) is probably imitative of croaking; no sure Indo-European kin. Italian and Spanish both say rana; French grenouille comes from Vulgar *ranucula (a little frog), Old French reinoille, with an imitative gr- added. The buttercup genus Ranunculus is the little frog — it grows where frogs live.
g_lanc|lancea(长矛)被罗马作家认为是西班牙语(伊比利亚)或高卢语的借词,原是辅助部队的投枪。法语 lance、意大利语 lancia、西班牙语 lanza;动词 lancer/lanciare/lanzar(投掷——"像掷矛一样")、élan(冲劲)、lancette(柳叶刀)、中世纪骑士的 lance 马上长枪同族。|Latin lancea (a lance) was said by Roman writers to be an Iberian or Gaulish loan, originally the javelin of auxiliary troops. French lance, Italian lancia, Spanish lanza; the verbs lancer, lanciare, lanzar (to throw, as one hurls a spear), élan, the lancet and the knight's lance all belong to it.
g_scut|scutum(盾)来自印欧语 *skewH-(遮盖)——与 obscurus(暗的)、英语 sky("云遮")、hide 同根存疑。罗马军团的 scutum 是弧形长方大盾,龟甲阵(testudo)就用它们拼成。意大利语 scudo、西班牙语 escudo(也是葡萄牙旧货币名——盾徽铸在币上);法语的 bouclier 是另一词,见 bucc。|Latin scutum (a shield) is probably from PIE *skewH- (to cover), with obscurus (dark) and English sky and hide as possible kin. The legion's scutum was the curved oblong shield locked together in the testudo. Italian scudo and Spanish escudo (also the old Portuguese coin, stamped with a shield); French bouclier is a different word — see bucc.
g_inimic|inimicus(敌人)= in-(不)+ amicus(朋友)——"不是朋友的人"。罗马人区分 inimicus(私敌)与 hostis(国敌)。法语 ennemi、意大利语 nemico、西班牙语 enemigo 都继承 inimicus;英语 enemy、inimical(敌意的)同族。amicus 又来自 amare(爱),见 am。|Latin inimicus (an enemy) is in- (not) + amicus (a friend): the one who is not a friend. Romans kept inimicus (a personal enemy) apart from hostis (an enemy of the state). French ennemi, Italian nemico and Spanish enemigo all inherit inimicus; English enemy and inimical belong here. Amicus itself comes from amare, to love — see am.
g_purpur|purpura(紫色、骨螺)借自希腊语 porphyra——从地中海骨螺里提取的染料,一万只螺才染一件袍子,所以紫色成了帝王色:罗马元老袍镶紫边,拜占庭皇子称 porphyrogennetos("生于紫室")。法语 pourpre、意大利语 porpora/purpureo、西班牙语 púrpura;德语 Purpur 借自拉丁语。porphyre(斑岩)是同一个希腊词。|Latin purpura (purple, the murex) is Greek porphyra — the dye taken from Mediterranean sea-snails, some ten thousand of them for one robe, which made purple the colour of rulers: senators' togas had a purple stripe, and a Byzantine prince was porphyrogennetos, born in the purple. French pourpre, Italian porpora and purpureo, Spanish púrpura; German Purpur is borrowed from Latin. Porphyry, the rock, is the same Greek word.
g_but|法语 début(开始)是 de + but(靶、目标)——"从靶子出发":原是投掷游戏或射箭的术语,指第一掷。but 可能来自法兰克语 *but(树桩、靶子,存疑)。débuter(开始、首次登台)、débutant(新手)、英语借去的 debut 同族;but 本身至今是"目标、球门"(marquer un but 进球!)。|French début (a beginning) is de + but (a target): to start from the mark — originally a term of throwing games or archery for the first throw. But may come from Frankish *but (a stump, a target), though this is disputed. Débuter (to begin, to make a first appearance), débutant and English debut belong here, and but itself still means a goal (marquer un but, to score!).
g_init|initium(开始)= in-(进入)+ ire(走)——"走进去"。罗马的 initia 也指秘仪的入门礼(initiatio 入教)。西班牙语 inicio、意大利语 inizio;initial(最初的、首字母)、initiative(主动)、initiation 同族。见 it(ire)。|Latin initium (a beginning) is in- (into) + ire (to go): going in. The Roman initia were also the rites of admission to the mysteries (initiatio). Spanish inicio, Italian inizio; initial, initiative and initiation belong here. See it (ire).
g_lyr|lyra(里拉琴)借自希腊语 lyra,来源不明(可能是前希腊语)。传说赫尔墨斯用龟壳做出第一把里拉琴送给阿波罗;俄耳甫斯用它让冥王落泪。法语 lyre、意大利语 lira(注意:与旧货币 lira 无关,那来自 libra 磅!)、西班牙语 lira、德语 Leier。lyrique(抒情的——"配里拉琴唱的")、lyrics(歌词)同族。|Latin lyra is Greek lyra, of unknown, probably pre-Greek, origin. Legend has Hermes make the first lyre from a tortoise shell and give it to Apollo; Orpheus used it to make the king of the dead weep. French lyre, Italian lira (unrelated to the old currency lira, which is libra, a pound!), Spanish lira, German Leier. Lyric (sung to the lyre) and lyrics belong here.
g_art|ars(技艺,属格 artis)来自印欧语 *h₂er-(接合、装配)——与 arma(武器)、artus(关节)、希腊语 harmonia(接合)、英语 arm 同根:技艺就是"把东西恰当地组装起来"。罗马的 artes liberales(自由七艺)是中世纪大学的课程。法语 art、意大利语 arte、西班牙语 arte;artiste、artisan(工匠)、artifice(技巧)、artificiel 同族。|Latin ars (skill, genitive artis) comes from PIE *h₂er- (to fit together) — kin to arma (weapons), artus (a joint), Greek harmonia and English arm: skill is fitting things together properly. The Roman artes liberales became the curriculum of the medieval university. French art, Italian arte, Spanish arte; artiste, artisan, artifice and artificial belong here.
g_best|bestia(野兽)来源不明。罗马竞技场的 bestiarius 是与野兽搏斗的人,damnatio ad bestias 是"喂野兽"的死刑。法语 bête(古法语 beste,s 脱落后留下长音符号)、西班牙语 bestia、意大利语 bestia;bêtise(蠢事——"像畜生一样")、bestial(兽性的)、中世纪的 bestiaire(动物寓言集)同族。|Latin bestia (a beast) has no clear origin. In the arena a bestiarius fought wild animals, and damnatio ad bestias was death by the beasts. French bête (Old French beste — the circumflex marks the lost s), Spanish bestia, Italian bestia; bêtise (foolishness, acting like an animal), bestial and the medieval bestiaire (a book of animal fables) belong here.
g_fera|ferus(野的)、fera(野兽)来自印欧语 *ǵʰwer-(野兽),与希腊语 thēr(野兽——theriac)、古教会斯拉夫语 zvěrĭ 同根。意大利语、西班牙语 fiera(野兽,也是"集市"?不——集市 fiera 来自 feria 节日,同形异源!)。féroce/feroce/feroz(凶猛)、fierce、fier(骄傲——古义"野性的")同族。注意:与 ferre(携带)、ferrum(铁)都无关。|Latin ferus (wild) and fera (a wild beast) come from PIE *ǵʰwer- (a beast), cognate with Greek thēr (theriac) and Old Church Slavonic zvěrĭ. Italian and Spanish fiera is a wild beast (while Italian fiera, a fair, is a different word, from feria, a holiday — same shape, other source!). Féroce, feroce, feroz (ferocious), fierce, and French fier (proud — originally wild) are kin. Unrelated to ferre (to carry) or ferrum (iron).
g_ech|希腊语 ēchō(回声)来自 ēchē(声响),印欧语 *(s)weh₂gʰ-(响)。神话里山林仙女厄科被赫拉惩罚,只能重复别人最后的话;她爱上那喀索斯而不得,形体消散,只剩声音。法语 écho、意大利语 eco、西班牙语 eco、德语 Echo;échographie(超声检查)、catéchisme("反复念诵"——教理问答)同族。|Greek ēchō (an echo) comes from ēchē (a sound), PIE *(s)weh₂gʰ- (to resound). In myth the nymph Echo was punished by Hera so that she could only repeat others' last words; loving Narcissus in vain, she wasted away until only her voice remained. French écho, Italian eco, Spanish eco, German Echo; échographie (ultrasound) and catechism (teaching by repeated sounding) belong here.
g_taed|taeda(松脂火把)本指多脂的松木(Pinus 的一种),引申为火把,尤其是婚礼火把——罗马诗人用 taeda 直接指"婚姻"。来源不明。西班牙语 tea(松明火把)直接继承。|Latin taeda was resinous pine wood, then a torch made of it, especially the wedding torch — Roman poets use taeda to mean marriage itself. Its origin is unknown. Spanish tea (a pine torch) inherits it directly.
g_prat|pratum(草地)来源不明(可能与 parare 准备无关)。罗马农书区分 pratum(割草的草地)与 pascuum(放牧地)。法语 pré(préau 学校操场!)、意大利语 prato、西班牙语 prado——马德里的普拉多博物馆(Museo del Prado)就建在"草地"上。prairie(草原)是古法语 praerie。|Latin pratum (a meadow) has no clear origin. Roman agronomists distinguished pratum (a mowing meadow) from pascuum (a pasture). French pré (and préau, a school playground!), Italian prato, Spanish prado — Madrid's Prado Museum stands on the meadow. Prairie is Old French praerie.
g_viper|vipera(蝰蛇)通常解释为 vivus(活的)+ parere(生)——"胎生的":古人观察到蝰蛇不产蛋而产幼蛇(实为卵胎生)。这个解释古已有之,语言学上也站得住。法语 vipère、意大利语 vipera、西班牙语 víbora、德语 Viper;英语 wyvern(双足飞龙)是它的古法语变体。|Latin vipera (a viper) is usually taken as vivus (alive) + parere (to bear): the one that bears live young — the ancients noticed vipers give birth to young rather than laying eggs (they are ovoviviparous). The explanation is ancient and linguistically sound. French vipère, Italian vipera, Spanish víbora, German Viper; English wyvern is its Old French variant.
g_venen|venenum(毒药)最可信的解释是 *wenes-no-(爱药),与 Venus(爱神)同根:本义是"春药、魔药",后来才专指毒药——药与毒在古人眼里是同一件事(希腊语 pharmakon 同样兼"药"与"毒")。法语 venin、意大利语 veleno(n→l 异化)、西班牙语 veneno;venimeux(有毒的)、venomous 同族。注意:与 venire(来)无关。|Latin venenum (poison) is best explained as *wenes-no-, a love-potion, from the root of Venus: it first meant a charm or magic draught and only later poison — to the ancients drug and poison were one thing (Greek pharmakon likewise means both). French venin, Italian veleno (n→l by dissimilation), Spanish veneno; venomous belongs here. Unrelated to venire (to come).
g_ciner|cinis(灰,属格 cineris)来自印欧语 *ḱenis-(灰),与希腊语 konis(尘土)同根。罗马人火葬后把骨灰装进 urna cineraria(骨灰瓮)。法语 cendre、意大利语 cenere、西班牙语 ceniza;灰姑娘 Cendrillon/Cenerentola/Cenicienta 都是"坐在炉灰里的女孩"!Mercredi des Cendres(圣灰星期三)、incinérer(焚化)同族。|Latin cinis (ash, genitive cineris) comes from PIE *ḱenis-, cognate with Greek konis (dust). After cremation Romans put the ashes in an urna cineraria. French cendre, Italian cenere, Spanish ceniza; Cinderella is Cendrillon, Cenerentola, Cenicienta — the girl who sits in the ashes! Ash Wednesday (Mercredi des Cendres) and incinerate belong here.
g_destin|法语 destin(命运)来自 destiner(注定、指定),拉丁语 destinare(固定、确定)= de- + *stanare,出自 stare(站)——"让它站定"。命运就是"被定下来的"。destination(目的地)、destinée、destinataire(收件人)同族。见 sta。|French destin (fate) comes from destiner (to destine), Latin destinare (to fix, to settle) = de- + *stanare, from stare (to stand): to make something stand fast. Fate is what has been fixed. Destination, destinée and destinataire (an addressee) belong here. See sta.
g_infer|inferus(下面的)、inferi(下界的人/神——冥界)来自印欧语 *n̥dʰer-(下面),与英语 under、德语 unter 同根。infernus(下界的)给出教会拉丁的 infernum(地狱)。法语 enfers(希腊罗马冥界,复数)与 enfer(基督教地狱)有别;意大利语 inferi/inferno(但丁《地狱篇》Inferno!)、西班牙语 infierno/infiernos。inférieur(下级的)同族。|Latin inferus (below) and inferi (those below — the underworld) come from PIE *n̥dʰer- (under), cognate with English under and German unter. Infernus (of the lower world) became Church Latin infernum, hell. French distinguishes les enfers (the classical underworld, plural) from l'enfer (the Christian hell); Italian inferi and inferno (Dante's Inferno!), Spanish infiernos and infierno. Inferior belongs here.
g_thron|希腊语 thronos(座椅、宝座)来自印欧语 *dʰer-(持、撑)——与拉丁语 firmus(稳固)、梵语 dhāraṇa(支撑)同根:宝座就是"撑住人的"。宙斯的宝座在奥林匹斯山上。法语 trône、意大利语 trono、西班牙语 trono、德语 Thron;détrôner(废黜)、天使九品中的 Thrones 同族。|Greek thronos (a seat, a throne) comes from PIE *dʰer- (to hold, to support) — kin to Latin firmus (firm) and Sanskrit dhāraṇa (support): a throne is what holds a person up. Zeus's throne stood on Olympus. French trône, Italian trono, Spanish trono, German Thron; détrôner (to dethrone) and the angelic order of Thrones belong here.
g_scept|希腊语 skēptron(权杖、拐杖)来自 skēptesthai(倚靠),印欧语 *skeh₂p-(杖),与拉丁语 scapus(杆)、scipio(杖——西庇阿 Scipio 的名字!)同根。荷马史诗里持 skēptron 的人才有权在集会上发言。法语 sceptre、意大利语 scettro、西班牙语 cetro、德语 Zepter。|Greek skēptron (a staff, a sceptre) comes from skēptesthai (to lean on), PIE *skeh₂p- (a staff), kin to Latin scapus (a shaft) and scipio (a staff — the name of Scipio!). In Homer only the one holding the skēptron may speak in the assembly. French sceptre, Italian scettro, Spanish cetro, German Zepter.
g_abyss|希腊语 abyssos(无底的)= a-(无)+ byssos(海底、深处)。七十士译本用它译希伯来语 tehom(原始深渊)。法语 abîme(古法语 abisme,来自俗拉丁 *abyssimus"最深的")、意大利语 abisso、西班牙语 abismo;abysmal(极糟的)、深海带 abyssal zone 同族。|Greek abyssos (bottomless) is a- (without) + byssos (the depth of the sea). The Septuagint used it for Hebrew tehom, the primeval deep. French abîme (Old French abisme, from Vulgar *abyssimus, the deepest), Italian abisso, Spanish abismo; abysmal and the abyssal zone of the ocean belong here.
g_stagn|stagnum(池、沼)来自印欧语 *steh₂g-(渗、滴)存疑,与希腊语 stazein(滴)比较。积水不流,所以 stagnare(停滞)、stagnant、stagnation 都是它。法语 étang(s 脱落,é 是痕迹)、西班牙语 estanque、意大利语 stagno;英语 tank(水箱、坦克)是葡萄牙语 tanque 借回的同一个词!|Latin stagnum (a pool, a pond) is perhaps from PIE *steh₂g- (to seep), compared with Greek stazein (to drip). Standing water does not flow, hence stagnare, stagnant and stagnation. French étang (the é marks a lost s), Spanish estanque, Italian stagno; English tank came back from Portuguese tanque — the same word!
g_brouill|法语 brouillard(雾)来自古法语 brouée(雾气),再上溯到 breu/brou(汤、肉汤),出自日耳曼语 *brod(汤——英语 broth、德语 Brühe)。雾是"像一锅汤一样浑";同一族的 brouiller(搅乱、弄混)、brouillon(草稿——"搅乱的稿子")、embrouiller。|French brouillard (fog) comes from Old French brouée (mist), and further from breu, brou (broth), Germanic *brod (English broth, German Brühe). Fog is thick as soup; the same family gives brouiller (to mix up), brouillon (a rough draft — a muddled copy) and embrouiller.
g_rivus|rivus(小溪)来自印欧语 *h₃rey-(流),与梵语 rīyate(流)、英语 rivulet?(借词)同根。两个邻居共用一条 rivus,所以 rivalis 是"共用一条溪的人"——rival(对手)就从争水而来!法语 ruisseau(<*rivuscellus)、意大利语 rivo;dérivé/derivare(引水→派生:derivation!)同族。注意:river 来自 ripa(河岸),见 riv。|Latin rivus (a brook) comes from PIE *h₃rey- (to flow), cognate with Sanskrit rīyate. Neighbours sharing a brook were rivales — so a rival is someone you fight over water with! French ruisseau (from *rivuscellus), Italian rivo; derivare (to draw off water, hence to derive: derivation!) belongs here. English river is a different word, from ripa (a bank) — see riv.
g_ratis|ratis(木筏)来源不明。它的小称 *ratellus 给出法语 radeau(木筏)——géricault 的名画《梅杜萨之筏》Le Radeau de la Méduse(1819)画的正是一场真实海难。|Latin ratis (a raft) is of unknown origin. Its diminutive *ratellus gave French radeau — Géricault's The Raft of the Medusa (Le Radeau de la Méduse, 1819) paints a real shipwreck.
g_zatter|意大利语 zattera(木筏)来源不明:有人认为来自中古拉丁语 zatta(木料),可能出自阿拉伯语或巴尔干语言,均属推测。威尼斯的 Zattere 河岸就是木筏卸木材的码头。|Italian zattera (a raft) has an unknown origin: some derive it from Medieval Latin zatta (timber), perhaps from Arabic or a Balkan language — all guesswork. Venice's Zattere quay was where timber rafts were unloaded.
g_bals|西班牙语 balsa(木筏;也指水塘、轻木)是前罗马的伊比利亚词,来源不明,在罗马人到来之前就在半岛上使用。它有两个意思:"池塘、积水"和"木筏"——可能都出自"浮在水上"的原义。南美的轻木因为做木筏最合适而得名 balsa,这个西班牙语词随后进入英语(balsa wood,航模材料)。1947 年海尔达尔的"康提基号"就是一只轻木筏。|Spanish balsa (a raft; also a pool, and balsa wood) is a pre-Roman Iberian word of unknown origin. Balsa wood is named for being ideal for rafts — and the Spanish word then passed into English.
g_aboi|法语 aboyer(吠)来自俗拉丁 *abbaudiare,出自拟声的 *baubari(汪汪叫——卢克莱修用 baubari 描写狗吠)。aboiement(吠声)、aux abois(穷途末路——"被猎狗围着吠")同族。|French aboyer (to bark) comes from Vulgar Latin *abbaudiare, from imitative *baubari (to woof — Lucretius uses baubari for dogs barking). Aboiement (barking) and aux abois (at bay — surrounded by baying hounds) belong here.
g_latrat|latrare(狗吠)是拟声的拉丁词,印欧语亲缘不明。latratus(吠声)给出意大利语 latrato;西班牙语 ladrar(吠)、ladrido(吠声)是同一个词。冥界的三头犬刻耳柏洛斯在但丁笔下"latra"。注意:与 latro(强盗)同形不同源?——有人把 ladrón(贼)也连过来,但 latro 本义"雇佣兵",来自希腊语 latron(工钱),两者无关。|Latin latrare (to bark) is an imitative word with no clear Indo-European kin. Latratus (barking) gave Italian latrato; Spanish ladrar (to bark) and ladrido (barking) are the same word. Dante's Cerberus latra. Beware: latro (a robber), whence Spanish ladrón, looks similar but first meant a mercenary, from Greek latron (wages) — a different word.
g_gorg|俗拉丁 *gurga(喉咙、漩涡)出自 gurges(深流、漩涡)——喉咙是"吞水的漩涡"。法语 gorge(喉咙,也是峡谷!)、gorgée(一口)、engorger(阻塞)、意大利语 gorgo(漩涡)、gorgheggio(颤音)同族。英语 gorge、gargle(漱口)来自它的拟声近亲。|Vulgar Latin *gurga (throat, whirlpool) comes from gurges (a deep current, an eddy) — the throat is a swallowing whirlpool. French gorge (throat, and a gorge!), gorgée (a mouthful), engorger (to clog), Italian gorgo (a whirlpool) and gorgheggio (a trill) belong here; English gorge and gargle come from this imitative family.
g_gul|gula(喉咙、贪吃)来自印欧语 *gʷelH-(吞),与英语 glut?(存疑)比较。罗马人 gula 兼"喉咙"与"贪食";基督教七宗罪的"暴食"就是 gula。意大利语 gola(喉咙、峡谷,也指渴望:far gola 让人眼馋!)、法语 gueule(兽口)、gueuler(吼)、goulot(瓶颈)、西班牙语 gula(贪食)。|Latin gula (throat, gluttony) comes from PIE *gʷelH- (to swallow). Romans used gula for both the throat and greed, and the deadly sin of gluttony is gula. Italian gola (throat, gorge, and craving: far gola, to be tempting!), French gueule (an animal's mouth), gueuler (to bawl), goulot (a bottle neck), Spanish gula (gluttony).
g_garg|西班牙语 garganta(喉咙)来自拟声词根 garg-——模仿咕噜、漱口的声音。同一个声音遍布欧洲:法语 gargouille(滴水兽——吐水的喉咙!)、gargariser(漱口)、英语 gargle、意大利语 gargarozzo。拉伯雷的巨人 Gargantua 也出自这个"大喉咙"。|Spanish garganta (throat) comes from the imitative root garg-, the sound of gurgling and gargling. The same sound runs across Europe: French gargouille (a gargoyle — a water-spouting throat!), gargariser, English gargle, Italian gargarozzo. Rabelais's giant Gargantua is the great throat too.
g_belu|belua(巨兽、怪兽)来源不明,可能与 bestia 有关(存疑)。罗马作家用 belua 指大象、鲸之类的庞然大物,也骂人"畜生"。意大利语 belva(猛兽)直接继承。|Latin belua (a monster, a huge beast) is of unknown origin, perhaps linked to bestia (disputed). Roman writers used it for elephants, whales and other giants, and as an insult. Italian belva (a wild beast) inherits it directly.
g_drac|希腊语 drakōn(巨蛇、龙)来自 derkesthai(看、凝视)——"目光锐利者":印欧语 *derḱ-(看),与梵语 dṛś-(看)同根。古人相信蛇的目光能震慑人。拉丁语 draco 给出法语 dragon、意大利语 drago、西班牙语 dragón、德语 Drache;dragoon(龙骑兵)、雅典立法者 Draco(德拉古)与 draconian(严苛的)同族。|Greek drakōn (a serpent, a dragon) comes from derkesthai (to look, to stare) — the sharp-eyed one: PIE *derḱ- (to see), cognate with Sanskrit dṛś-. The ancients believed a snake's gaze could paralyse. Latin draco gave French dragon, Italian drago, Spanish dragón, German Drache; the dragoon, the Athenian lawgiver Draco and draconian belong here.
g_gigant|希腊语 gigas(巨人,属格 gigantos)来源不明(可能是前希腊语)。神话中巨人是大地母神该亚所生,与奥林匹斯诸神大战(Gigantomachia——帕加马祭坛的浮雕,今藏柏林)。法语 géant、意大利语 gigante、西班牙语 gigante;gigantesque、giga-(十亿——"巨大")同族。德语 Riese 是本族词。|Greek gigas (a giant, genitive gigantos) is of unknown, probably pre-Greek, origin. In myth the Giants were born of Gaia and fought the Olympians (the Gigantomachy — the Pergamon Altar frieze, now in Berlin). French géant, Italian gigante, Spanish gigante; gigantic and giga- (a billion — the huge one) belong here. German Riese is a native word.
g_nymph|希腊语 nymphē(新娘、少女、仙女)来源不明,可能与拉丁语 nubere(出嫁)同根(存疑)。宁芙是住在泉水、山林、海洋里的女神:Naiad(水泽)、Dryad(树)、Nereid(海)。法语 nymphe、意大利语 ninfa、西班牙语 ninfa、德语 Nymphe;昆虫的若虫(nymph)也是它。|Greek nymphē (a bride, a young woman, a nymph) is of unknown origin, possibly related to Latin nubere (to marry) — disputed. Nymphs were goddesses of springs, woods and seas: Naiads, Dryads, Nereids. French nymphe, Italian ninfa, Spanish ninfa, German Nymphe; an insect nymph is the same word.
g_golf|希腊语 kolpos(胸怀、海湾)经俗拉丁 colphus 给出意大利语 golfo(海湾)、法语 golfe;法语 gouffre(深渊、漩涡)是它的变体——"吞没一切的海湾"。墨西哥湾 Golfe du Mexique、Gulf Stream(湾流)同族。|Greek kolpos (the bosom, a bay) came through Vulgar Latin colphus to Italian golfo and French golfe (a gulf); French gouffre (an abyss, a whirlpool) is a variant — the gulf that swallows all. The Gulf of Mexico and the Gulf Stream belong here.
g_ard|ardere(燃烧)来自印欧语 *h₂eh₁s-(烧、干),与 area(空地——"烧干的地")、arid(干旱)同根存疑。ardor(灼热)从火焰转指热情。法语 ardeur、意大利语 ardore、西班牙语 ardor(也指"胃灼热"ardor de estómago!);ardent(热烈的)、arson(纵火)同族。|Latin ardere (to burn) is probably from PIE *h₂eh₁s- (to burn, to dry), kin to arid and perhaps area (burnt, cleared ground). Ardor went from flame to passion. French ardeur, Italian ardore, Spanish ardor (also heartburn, ardor de estómago!); ardent and arson belong here.
g_sulf|sulphur/sulpur(硫)来源不明,可能借自某种地中海语言。罗马人用硫熏蒸消毒、漂白羊毛;《奥德赛》里奥德修斯杀死求婚者后用硫磺熏屋净化。法语 soufre、意大利语 zolfo、西班牙语 azufre(a- 受阿拉伯冠词 al- 影响)、德语 Schwefel(本族词,见德语条);sulfate、sulfure 同族。|Latin sulphur (sulfur) is of unknown origin, perhaps from a Mediterranean language. Romans fumigated with sulfur and bleached wool with it; in the Odyssey Odysseus purifies his house with sulfur after killing the suitors. French soufre, Italian zolfo, Spanish azufre (the a- influenced by the Arabic article al-), German Schwefel (a native word, see its entry); sulfate and sulfide belong here.
g_cupp|晚期拉丁语 cuppa(杯)是 cupa(桶)的变体,印欧语 *kewp-(容器、弯)。法语 coupe(杯;奖杯 la Coupe du monde 世界杯!)、意大利语 coppa、西班牙语 copa;英语 cup、德语 Kopf(头——原义"杯状的碗"!)同源。copa 也是西班牙扑克的"圣杯"花色。注意:法语 coupe"剪"是另一个词(coup)。|Late Latin cuppa (a cup) is a variant of cupa (a tub), PIE *kewp- (a vessel, a hollow). French coupe (a cup — la Coupe du monde, the World Cup!), Italian coppa, Spanish copa; English cup and German Kopf (head — originally a bowl!) are cognate. Copa is also the cups suit of Spanish cards. French coupe meaning a cut is a different word (coup).
g_potio|potare(喝)、potio(饮料、药水)来自印欧语 *peh₃-(喝),与 bibere(喝)、希腊语 pinein、梵语 pibati 同根。potio 在医学里是"药剂",在神话里是"魔药";它还给出法语 poison(毒药!——最初只是"一剂")。法语 potion、意大利语 pozione、西班牙语 poción;potable(可饮用的)同族。|Latin potare (to drink) and potio (a drink, a draught) come from PIE *peh₃- (to drink), kin to bibere, Greek pinein and Sanskrit pibati. Potio was a medicine in medicine and a magic draught in myth; it also gave French poison — at first just a dose! French potion, Italian pozione, Spanish poción; potable belongs here.
g_murmur|murmur(低语、潺潺声)是拟声的重叠词,印欧语 *mormor-,与梵语 marmara(沙沙作响)、希腊语 mormyrein(汩汩流)同根——很多语言都用重复的 m-r 模仿低沉的声音。法语 murmure、意大利语 mormorio、西班牙语 murmullo、德语 murmeln。|Latin murmur (a murmur) is an imitative reduplicated word, PIE *mormor-, cognate with Sanskrit marmara (rustling) and Greek mormyrein (to gurgle) — many languages use a doubled m-r for a low rumbling sound. French murmure, Italian mormorio, Spanish murmullo, German murmeln.
g_clem|clemens(温和的)、clementia(宽仁)来源不明。恺撒以 clementia Caesaris(恺撒的宽仁)著称——他在内战中赦免对手,这成了他的政治招牌;教宗 Clemens(克雷芒)取的也是这个美德。法语 clémence、意大利语 clemenza、西班牙语 clemencia;inclement(天气恶劣的——"不宽仁的")同族。|Latin clemens (mild) and clementia (mercy) are of unknown origin. Caesar was famous for his clementia, sparing his opponents in the civil war as a political trademark; the popes named Clement took the virtue as their name. French clémence, Italian clemenza, Spanish clemencia; inclement weather is weather without mercy.
g_altar|altare/altaria(祭坛)的来历有争议:古人把它解释为 altus(高)——"高起的台",现代多数学者认为来自 adolere(焚烧供物)——"烧祭品的地方"。两说至今并存。法语 autel、意大利语 altare、西班牙语 altar、德语 Altar。拉丁语另有 ara(祭坛,见 ara 一词)。|Latin altare (an altar) has a disputed source: the ancients explained it from altus (high) — the raised platform; most modern scholars prefer adolere (to burn offerings) — the place of burnt sacrifice. Both views stand. French autel, Italian altare, Spanish altar, German Altar. Latin also had ara, an altar.
g_thesaur|希腊语 thēsauros(宝库、宝藏)来自 tithēmi(放置)——"存放东西的地方"(存疑,但通说)。德尔斐的 thēsauroi 是各城邦存放献礼的小宝库。法语 trésor(r 为插入音)、意大利语 tesoro、西班牙语 tesoro、德语 Tresor(保险柜——借自法语!);英语 thesaurus(同义词词典——"词的宝库")同族。|Greek thēsauros (a treasury, a treasure) is usually derived from tithēmi (to put): a place where things are stored. At Delphi the thēsauroi were small treasuries where cities kept their offerings. French trésor (with an intrusive r), Italian tesoro, Spanish tesoro, German Tresor (a safe — borrowed from French!); English thesaurus (a treasury of words) belongs here.
g_diadem|希腊语 diadēma(头带)= dia-(环绕)+ dein(绑)——"绑在头上的带子"。亚历山大大帝采用波斯王的白色头带作为王权标志,从此 diadem 成了王冠的代名词。法语 diadème、意大利语 diadema、西班牙语 diadema、德语 Diadem。|Greek diadēma (a headband) is dia- (around) + dein (to bind): a band tied round the head. Alexander the Great adopted the Persian king's white headband as a sign of royalty, and diadem became a word for a crown. French diadème, Italian diadema, Spanish diadema, German Diadem.
g_numen|numen(神意、神性)来自 nuere(点头)——神点头即是应允:印欧语 *new-(点头),与希腊语 neuein(点头)同根。罗马宗教里 numen 是神灵的意志与力量,每个地方、每道门都有自己的 numen。意大利语 nume、西班牙语 numen;numinous(神圣而令人敬畏的——奥托《论神圣》1917)同族。|Latin numen (divine will, divinity) comes from nuere (to nod): the god nods assent. PIE *new- (to nod), cognate with Greek neuein. In Roman religion the numen was a god's will and power, and every place and every door had its own. Italian nume, Spanish numen; numinous (Otto's The Idea of the Holy, 1917) belongs here.
g_suav|suavis(甜的、宜人的)来自印欧语 *sweh₂dus(甜),与英语 sweet、德语 süß、希腊语 hēdys(甜——hedonism 享乐主义!)同根。法语 suave、suavité、意大利语 soave(白葡萄酒 Soave 就是"柔和")、西班牙语 suave;persuader(说服——"使觉得甜"!)同族。|Latin suavis (sweet, pleasant) comes from PIE *sweh₂dus (sweet), cognate with English sweet, German süß and Greek hēdys (sweet — whence hedonism!). French suave and suavité, Italian soave (the white wine Soave is the gentle one), Spanish suave; persuade (to make something sweet to someone!) belongs here.
g_amar|amarus(苦的)来自印欧语 *h₂eh₃mó-(生的、苦的),与梵语 āma-(生的)、古挪威语 apr(尖刻)同根。法语 amer、意大利语 amaro(也是意大利苦味酒)、西班牙语 amargo(<*amaricus);amertume(苦涩)同族。西班牙语 amarillo(黄)被认为来自 amarellus("微苦的"——胆汁色),属通说。|Latin amarus (bitter) comes from PIE *h₂eh₃mó- (raw, bitter), cognate with Sanskrit āma- (raw). French amer, Italian amaro (also the Italian bitters), Spanish amargo (from *amaricus); amertume (bitterness) belongs here. Spanish amarillo (yellow) is generally derived from amarellus, somewhat bitter — the colour of bile.
g_moll|mollis(软的)来自印欧语 *mld-u-(软),与梵语 mṛdu(软)、英语 melt、mild、德语 mild 同根。音乐的 moll(小调——"柔和的调")就是它。法语 mou/molle、意大利语 molle(弹簧!)、mollusque(软体动物)、amollir(软化)同族。|Latin mollis (soft) comes from PIE *mld-u- (soft), cognate with Sanskrit mṛdu and English melt and mild. The minor key, Moll (the soft mode), is this word. French mou/molle, Italian molle (also a spring!), mollusc and amollir (to soften) belong here.
g_bland|blandus(温柔的、讨好的)来源不明。罗马作家用它形容甜言蜜语;blanditiae 是"奉承话"。意大利语 blando(温和的)、西班牙语 blando(软的——取代了 mollis!)、blandir;英语 bland(平淡的)、blandishment(甜言蜜语)同族。|Latin blandus (gentle, coaxing) is of unknown origin. Roman writers used it for smooth talk, and blanditiae were flatteries. Italian blando (mild), Spanish blando (soft — which replaced mollis!), English bland and blandishment belong here.
g_halag|西班牙语 halagar(奉承、讨好)、halagador(甜言蜜语的)的来源有争议:常见说法是阿拉伯语 ḫalaqa(使光滑、磨光)——"把话说得光滑";也有人认为来自哥特语 *thlaihan(抚爱)。两说并存。|Spanish halagar (to flatter) and halagador (flattering) have a disputed origin: the common view is Arabic ḫalaqa (to make smooth) — smoothing one's words; others propose Gothic *thlaihan (to caress). Both views stand.
g_retro|retro(向后)= re-(回)+ -tro(方向后缀)。晚期拉丁 ad retro("到后面")给出法语 arrière(en arrière 向后、arrière-pays 腹地)、意大利语 indietro(in + de + retro)。rétrograde(倒退的)、rétroviseur(后视镜)、retro 风格同族。|Latin retro (backwards) is re- (back) + -tro (a directional suffix). Late Latin ad retro (to the back) gave French arrière (en arrière, backwards; arrière-pays, the hinterland) and Italian indietro (in + de + retro). Retrograde, rétroviseur (a rear-view mirror) and retro style belong here.
g_solicit|sollicitare(搅动、使不安)= sollus(整个)+ ciere(推动)——"整个被搅动"。法语 souci(担忧)来自 se soucier(<sollicitare)。solliciter(恳求)、sollicitude(关切)、insouciant(无忧无虑的)同族——Sans Souci(无忧宫,波茨坦)就是"没有担忧"。|Latin sollicitare (to stir, to disquiet) is sollus (whole) + ciere (to set in motion): to be stirred through and through. French souci (worry) comes from se soucier (from sollicitare). Solliciter (to request), sollicitude and insouciant belong here — and Frederick the Great's palace Sanssouci in Potsdam means without care.
g_cogit|cogitare(思考)= co-(一起)+ agitare(推动、翻来覆去)——"在心里翻来覆去"。笛卡尔的 cogito ergo sum(我思故我在,1637)。西班牙语 cuidar(照料)、cuidado(小心!、关照)是它的后代:思虑→挂念→照料。|Latin cogitare (to think) is co- (together) + agitare (to drive, to turn over): to turn things over in the mind. Descartes's cogito ergo sum (1637). Spanish cuidar (to look after) and cuidado (care — ¡cuidado!, careful!) descend from it: to ponder, to worry about, to take care of.
g_hate|法语 hâte(急忙)来自法兰克语 *haist(急躁、猛烈——古英语 hǣst 暴力,英语 haste 借自古法语)。长音符号标出消失的 s。se hâter(赶紧)、hâtif(仓促的)同族。|French hâte (haste) comes from Frankish *haist (violence, impetuousness — Old English hǣst; English haste was borrowed from Old French). The circumflex marks the lost s. Se hâter (to hurry) and hâtif (hasty) belong here.
g_aetern|aeternus(永恒的)来自 aeviternus——aevum(一生、时代)+ 形容词后缀:印欧语 *h₂eyu-(生命力、年岁),与希腊语 aiōn(永世)、英语 aye、ever、德语 ewig 同根。法语 éternel/éternité、意大利语 eterno/eternità、西班牙语 eterno/eternidad;罗马被称为 Urbs aeterna(永恒之城)。|Latin aeternus (eternal) is from aeviternus — aevum (a lifetime, an age) plus an adjective suffix: PIE *h₂eyu- (vital force, age), cognate with Greek aiōn, English aye and ever, German ewig. French éternel, éternité; Italian eterno, eternità; Spanish eterno, eternidad; Rome was the Urbs aeterna, the Eternal City.
g_element|elementum(元素、字母)来源不明。一个古老而流行的解释说它来自 L-M-N 三个字母——"像字母表里的 l、m、n 一样按顺序排列的基本单位",但这只是猜测。罗马人用它译希腊语 stoicheion(字母、元素)。法语 élément、意大利语 elemento、西班牙语 elemento、德语 Element;elementary(初级的)同族。|Latin elementum (an element, a letter of the alphabet) is of unknown origin. An old and popular explanation derives it from the letters L-M-N — basic units in order like l, m, n in the alphabet — but it is only a guess. The Romans used it to translate Greek stoicheion (a letter, an element). French élément, Italian elemento, Spanish elemento, German Element; elementary belongs here.
g_laur|laurus(月桂)可能借自某种地中海语言(存疑)。月桂是阿波罗的圣树——达芙妮为躲避阿波罗化作月桂;胜利者戴月桂冠,所以 laureatus 是"戴桂冠的"(poet laureate 桂冠诗人、Nobel laureate)。法语 laurier、意大利语 lauro/alloro(al- 是冠词粘合)、西班牙语 laurel、德语 Lorbeer(Lor+Beere 浆果);baccalauréat(法国高中会考——"月桂浆果"的民间词源!)同族。|Latin laurus (the bay laurel) is probably a loan from a Mediterranean language. The laurel was Apollo's sacred tree — Daphne turned into one to escape him — and victors wore laurel wreaths, so laureatus means crowned with laurel (poet laureate, Nobel laureate). French laurier, Italian lauro and alloro (the article fused on), Spanish laurel, German Lorbeer (Lor + Beere, berry); French baccalauréat was reshaped by folk etymology into laurel berries.
g_praem|praemium(奖赏)= prae-(在前)+ emere(拿、买)——原义是"先拿走的那份"(战利品中先分给有功者的)。西班牙语 premio、意大利语 premio(诺贝尔奖 Premio Nobel)、英语 premium(保险费、溢价)同族。emere 又给出 exemplum、redemption(赎回)。|Latin praemium (a reward) is prae- (before) + emere (to take, to buy): originally the portion taken first, the share of booty awarded to the brave. Spanish premio, Italian premio (Premio Nobel), English premium belong here. Emere also gave exemplum and redemption.
g_vat|vates(先知诗人)是凯尔特-意大利共有的词,与古爱尔兰语 fáith(先知)、哥特语 wods(狂热)、古英语 wōd(疯狂)——以及主神 Wodan/Odin("狂热者")同根:先知是神灵附体的狂热者。维吉尔自称 vates。意大利语 vate、西班牙语 vate(雅语)。|Latin vates (a seer-poet) is a word shared by Celtic and Italic, cognate with Old Irish fáith (a prophet), Gothic wods (raving), Old English wōd (mad) — and the god Wodan/Odin, the frenzied one: the seer is possessed by the god. Virgil calls himself a vates. Italian vate, Spanish vate (literary).
g_famul|familia(家庭)来自 famulus(家奴)——罗马的 familia 本义是"一户的全部奴仆",后扩大为户主(pater familias)权力下的所有人与财产。famulus 可能借自奥斯坎语 famel(存疑)。法语 famille、意大利语 famiglia、西班牙语 familia、德语 Familie;familiar(熟悉的——"一家的")同族。|Latin familia (a household) comes from famulus (a household slave): the Roman familia was first all the slaves of a house, then everyone and everything under the power of the paterfamilias. Famulus may be an Oscan loan (famel) — disputed. French famille, Italian famiglia, Spanish familia, German Familie; familiar (of the household) belongs here.
g_vague|法语 vague(波浪)来自古诺斯语 vágr(海、波浪),诺曼人带入法语——与德语 Woge、英语 wave?(存疑)同源。注意法语里还有另一个 vague(模糊的,来自拉丁 vagus 游荡)——两个 vague 同形不同源!la Nouvelle Vague(新浪潮电影,1950 年代末)用的是"波浪"。|French vague (a wave) comes from Old Norse vágr (the sea, a wave), brought by the Normans — cognate with German Woge. French has a second vague (vague, from Latin vagus, wandering): two homographs of different origin! The Nouvelle Vague of late-1950s cinema is the wave.
g_ola|西班牙语 ola(波浪)来源有争议:一说来自阿拉伯语 hawl(恐惧、巨浪),一说来自动词 olear(起伏)或拉丁 olla(锅——沸腾翻滚),均未定论。它取代了拉丁的 unda 在西班牙语里的日常地位(onda 仍指"波"——电波、声波)。|Spanish ola (a wave) has a disputed origin: from Arabic hawl (terror, a great wave), from a verb olear (to surge), or from Latin olla (a pot — boiling and rolling); none is settled. It displaced Latin unda in everyday Spanish, though onda survives for radio and sound waves.
g_saal|日耳曼语 *salą(大厅、单间房屋——德语 Saal、古英语 sele)随法兰克人与伦巴第人进入罗曼语:法语 salle(厅)、意大利语 sala、西班牙语 sala;salon(沙龙)、saloon 是意大利语 salone(大厅)的后代。印欧语 *sel-(住所),与拉丁语 solum(地)存疑。|Germanic *salą (a hall, a one-roomed house — German Saal, Old English sele) entered Romance with the Franks and Lombards: French salle, Italian sala, Spanish sala; salon and saloon descend from Italian salone, a great hall. PIE *sel- (a dwelling) is the proposed source.
g_cathedr|希腊语 kathedra(座椅)= kata-(向下)+ hedra(座)——与拉丁 sedere 同根(*sed-)。主教的座位 cathedra 所在的教堂就是 cathedral(主教座堂);ex cathedra(教宗"从座上"宣布)。法语 chaise(椅子)是 chaire(讲座、讲台)在巴黎方言里 r→z 的音变形——同一个词分成"椅子"与"讲台"两个!|Greek kathedra (a seat) is kata- (down) + hedra (a seat), from the root *sed- of Latin sedere. The church holding a bishop's cathedra is a cathedral, and a pope speaks ex cathedra. French chaise (a chair) is a Parisian variant of chaire (a pulpit, a professorial chair) with r→z: one word split into chair and lectern!
g_jard|日耳曼语 *gardaz(围起的地——德语 Garten、英语 yard)经法兰克语进入古法语 jart/jardin("围起来的园子"),再传到意大利语 giardino、西班牙语 jardín。它与拉丁 hortus 同根(*ǵʰerdʰ-,围)——罗曼语用日耳曼借词取代了自己的同源词。jardinier(园丁)、jardinière 同族。|Germanic *gardaz (enclosed land — German Garten, English yard) entered Old French through Frankish as jart and jardin (the enclosed garden), and passed to Italian giardino and Spanish jardín. It is cognate with Latin hortus (*ǵʰerdʰ-, to enclose) — Romance replaced its own inherited word with a Germanic cousin. Jardinier (a gardener) belongs here.
g_font|fons(泉,属格 fontis)来自印欧语 *dʰen-(流)存疑。罗马的 Fontinalia(10 月 13 日)向泉水之神 Fons 献花环。俗拉丁 *fontana(泉水的)给出法语 fontaine、意大利语 fontana(特雷维喷泉 Fontana di Trevi!)、西班牙语 fuente(直接来自 fons)。教堂的 font(洗礼池)同族。|Latin fons (a spring, genitive fontis) is perhaps from PIE *dʰen- (to flow). Rome's Fontinalia (13 October) garlanded the springs for the god Fons. Vulgar *fontana gave French fontaine and Italian fontana (the Trevi Fountain!); Spanish fuente comes straight from fons. The baptismal font belongs here.
g_marmor|希腊语 marmaros(闪光的石头、大理石)来自 marmairein(闪光)——大理石是"闪亮的石"。奥古斯都夸口说他"接手一座砖城,留下一座大理石城"(苏埃托尼乌斯记载)。法语 marbre(m→b 异化)、意大利语 marmo、西班牙语 mármol、德语 Marmor;marbled(大理石纹的)同族。|Greek marmaros (a gleaming stone, marble) comes from marmairein (to sparkle): marble is the shining stone. Augustus boasted that he found Rome a city of brick and left it one of marble (Suetonius). French marbre (m→b by dissimilation), Italian marmo, Spanish mármol, German Marmor; marbled belongs here.
g_coffr|希腊语 kophinos(篮子)经拉丁 cophinus 给出法语 coffre(箱子)与 coffin(棺材——"盛放的箱子")。coffre-fort(保险柜)、coffret(小盒)同族。|Greek kophinos (a basket) came through Latin cophinus to French coffre (a chest) and English coffin (a box for the dead). Coffre-fort (a safe) and coffret (a casket) belong here.
g_scrin|scrinium(书卷箱、文件盒)来源不明。罗马皇帝的 scrinia 是存放公文的档案处。意大利语 scrigno(珠宝盒)、英语 shrine(圣龛——"盛圣物的盒子")、德语 Schrein 同族。|Latin scrinium (a case for scrolls, a document box) is of unknown origin. The emperors' scrinia were the chancery archives. Italian scrigno (a jewel box), English shrine (a box for relics) and German Schrein belong here.
g_arca|arca(箱子、柜)来自 arcere(关住、挡住),印欧语 *h₂erk-(锁住、保护)——与希腊语 arkein(抵挡)同根。挪亚方舟在拉丁语圣经里是 arca Noe,约柜是 arca foederis。西班牙语 arca 直接继承;arcane(神秘的——"锁在箱里的")同族。|Latin arca (a chest) comes from arcere (to shut in, to keep off), PIE *h₂erk- (to lock, to protect), cognate with Greek arkein. Noah's ark in the Latin Bible is arca Noe and the Ark of the Covenant arca foederis. Spanish arca inherits it directly; arcane (shut in a chest) belongs here.
g_silent|silere(沉默)、silentium(寂静)来源不明,可能与哥特语 anasilan(平静下来)同根。罗马宗教仪式要求 favete linguis("管住舌头")保持肃静。法语 silence、意大利语 silenzio、西班牙语 silencio;silencieux(消音器)同族。|Latin silere (to be silent) and silentium are of unknown origin, possibly related to Gothic anasilan (to die down). Roman rites demanded favete linguis — hold your tongues — for silence. French silence, Italian silenzio, Spanish silencio; silencieux (a silencer) belongs here.
g_roc|俗拉丁 *rocca(岩石)来源不明,很可能是前罗马语言的遗存。法语 roche/rocher、意大利语 rocca(要塞——建在岩上的城堡)、西班牙语 roca;英语 rock 借自古法语。rococo(洛可可——"卵石贝壳饰"rocaille)同族。|Vulgar Latin *rocca (a rock) is of unknown origin, very probably a relic of a pre-Roman language. French roche and rocher, Italian rocca (a fortress on a crag), Spanish roca; English rock was borrowed from Old French. Rococo (from rocaille, pebble-and-shell ornament) belongs here.
g_sax|saxum(岩石、巨石)与 secare(切)同根存疑——"切下的石块"。罗马的 Saxum Tarpeium(塔尔佩亚岩)是处决叛徒的悬崖。意大利语 sasso(石头);萨克森人 Saxones 的名字并不是它(那来自 seax 短刀)。|Latin saxum (a rock, a boulder) is perhaps related to secare (to cut) — a cut stone (disputed). The Tarpeian Rock, Saxum Tarpeium, was the cliff for executing traitors. Italian sasso (a stone). The Saxons are not named from it (that is seax, a knife).
g_intus|intus(在里面)来自 in 加表来源的后缀 -tus;晚期拉丁 de intus("从里面")给出法语 dedans、意大利语 dentro、西班牙语 dentro。intestine(肠——"里面的")同族。|Latin intus (within) is in plus the ablative suffix -tus; Late Latin de intus (from within) gave French dedans, Italian dentro and Spanish dentro. Intestine (the inner part) belongs here.
g_nas|nasus(鼻子)来自印欧语 *neh₂s-(鼻),与梵语 nās、英语 nose、德语 Nase 同根。奥维德的姓 Naso 就是"大鼻子"。法语 nez、意大利语 naso;西班牙语 nariz 来自复数 nares(鼻孔)。nasal(鼻音)同族。|Latin nasus (the nose) comes from PIE *neh₂s-, cognate with Sanskrit nās, English nose and German Nase. Ovid's cognomen Naso means big nose. French nez, Italian naso; Spanish nariz comes from the plural nares (nostrils). Nasal belongs here.
g_brach|bracchium(前臂、手臂)借自希腊语 brachiōn(上臂——"较短的"那段,来自 brachys 短)。法语 bras、意大利语 braccio(也是长度单位"臂")、西班牙语 brazo;bracelet(手镯)、brassard(臂章)、embrasser(拥抱——"张开双臂"→亲吻!)同族。|Latin bracchium (the forearm, the arm) is borrowed from Greek brachiōn (the upper arm — the shorter part, from brachys, short). French bras, Italian braccio (also a unit of length), Spanish brazo; bracelet, brassard and embrasser (to embrace, then to kiss!) belong here.
g_genu|genu(膝)来自印欧语 *ǵónu(膝),与希腊语 gony、英语 knee、德语 Knie 同根。拉丁 genuflectere(屈膝)。俗拉丁 *genuculum(小膝)给出法语 genou、意大利语 ginocchio;西班牙语改用 rodilla("小轮子"——膝盖骨像个小轮)。|Latin genu (the knee) comes from PIE *ǵónu, cognate with Greek gony, English knee and German Knie; genuflect is to bend the knee. Vulgar *genuculum (a little knee) gave French genou and Italian ginocchio; Spanish switched to rodilla, the little wheel — the kneecap looks like one.
g_urs|ursus(熊)来自印欧语 *h₂ŕ̥tḱos(熊),与希腊语 arktos(熊——北方的大熊星座 → Arctic 北极!)、梵语 ṛkṣa 同根。日耳曼人对熊用了避讳语"棕色的"(bear、Bär),所以没有继承这个词。法语 ours、意大利语 orso、西班牙语 oso;Ursula(小熊)同族。|Latin ursus (a bear) comes from PIE *h₂ŕ̥tḱos, cognate with Greek arktos (the Bear constellation in the north — hence Arctic!) and Sanskrit ṛkṣa. The Germanic peoples used a taboo word, the brown one (bear, Bär), so they did not inherit it. French ours, Italian orso, Spanish oso; Ursula is the little she-bear.
g_jabal|西班牙语 jabalí(野猪)来自安达卢斯阿拉伯语 jabalī("山里的"——ḫinzīr jabalī 山猪)。这是阿拉伯统治伊比利亚近八百年留下的四千多个借词之一。|Spanish jabalí (a wild boar) comes from Andalusian Arabic jabalī (of the mountain — ḫinzīr jabalī, the mountain pig). It is one of the four thousand or so loans left by nearly eight centuries of Arab rule in Iberia.
g_vacc|vacca(母牛)来源不明,可能与梵语 vaśā(母牛)同根。1796 年英国医生琴纳用牛痘(variolae vaccinae)预防天花,于是 vaccine(疫苗)="牛的"!法语 vache、意大利语 vacca、西班牙语 vaca;vacher(牛仔)、vaquero(西班牙牛仔——buckaroo 的来源)同族。|Latin vacca (a cow) is of uncertain origin, possibly cognate with Sanskrit vaśā. In 1796 the English doctor Jenner used cowpox (variolae vaccinae) against smallpox — so a vaccine is literally of the cow! French vache, Italian vacca, Spanish vaca; vacher and the Spanish vaquero (source of buckaroo) belong here.
g_mout|法语 mouton(羊)来自高卢语 *multon-(阉羊),与古爱尔兰语 molt、威尔士语 mollt 同根——高卢语在法语里留下的少数动物词之一。1066 年后英语借去指"羊肉"(mutton),而活羊仍叫 sheep:诺曼贵族吃肉、撒克逊农夫养羊。|French mouton (a sheep) comes from Gaulish *multon- (a wether), cognate with Old Irish molt and Welsh mollt — one of the few animal words Gaulish left in French. After 1066 English borrowed it for the meat (mutton) while the living animal stayed sheep: Norman lords ate it, Saxon peasants herded it.
g_ovis|ovis(羊)来自印欧语 *h₂ówis(羊),与希腊语 ois、梵语 avi、英语 ewe(母羊)、立陶宛语 avis 同根——印欧人的羊。俗拉丁 ovicula(小羊)给出西班牙语 oveja。ovin(羊的)同族。|Latin ovis (a sheep) comes from PIE *h₂ówis, cognate with Greek ois, Sanskrit avi, English ewe and Lithuanian avis — the Indo-Europeans' sheep. Vulgar ovicula (a little sheep) gave Spanish oveja. Ovine belongs here.
g_porc|porcus(猪)来自印欧语 *pórḱos(小猪),与英语 farrow(一窝小猪)、德语 Ferkel(小猪)同根。法语 porc、意大利语 porco;porcelaine(瓷器)来自意大利语 porcellana(宝贝贝壳——形似小猪的背!)、porc-épic(豪猪)同族。|Latin porcus (a pig) comes from PIE *pórḱos (a young pig), cognate with English farrow and German Ferkel. French porc, Italian porco; porcelain comes from Italian porcellana (a cowrie shell, shaped like a piglet's back!), and porc-épic (a porcupine) belongs here.
g_cerd|西班牙语 cerdo(猪)来源有争议:最常见的说法是它来自 cerda(鬃毛——猪的硬鬃),即"有鬃毛的";cerda 可能来自俗拉丁 *cirra(卷毛)。原本是避讳说法,取代了 puerco。|Spanish cerdo (a pig) has a disputed origin; the usual view derives it from cerda (a bristle — the pig's stiff hair), the bristly one, with cerda perhaps from Vulgar *cirra (a curl). It began as a euphemism that displaced puerco.
g_sorex|sorex(鼩鼱)来自印欧语 *swer-(嗡嗡叫)——"吱吱叫的"。俗拉丁 *soricem 给出法语 souris(老鼠;也是电脑"鼠标")。希腊语 hyrax(蹄兔)同根。|Latin sorex (a shrew) comes from PIE *swer- (to buzz) — the squeaker. Vulgar *soricem gave French souris (a mouse — and a computer mouse). Greek hyrax is cognate.
g_talp|talpa(鼹鼠)来源不明,可能是前拉丁的地中海词。罗马农书把鼹鼠当作田地的害兽。意大利语 topo(老鼠)正是来自 talpa——意大利人把鼹鼠的名字转给了老鼠,这是词义转移的一个好例子(两者都是"地里跑的小兽")。Topolino("小老鼠")是米老鼠的意大利名;talpa 本身在意大利语里仍指鼹鼠,也指"内鬼"。|Latin talpa (a mole) is of unknown origin. Italian topo (a mouse) comes from talpa — Italians moved the mole's name onto the mouse. Topolino, little mouse, is Mickey Mouse's Italian name!
g_raton|西班牙语 ratón(老鼠)是 rata(大鼠)的派生,rata 来自民间拟声词 *ratt-(可能模仿啃咬声),在日耳曼语与罗曼语里都有(德语 Ratte、英语 rat)。来源不明,可能在中世纪随家鼠一起扩散。|Spanish ratón (a mouse) derives from rata (a rat), from a popular imitative *ratt- (perhaps the sound of gnawing) found in both Germanic and Romance (German Ratte, English rat). The origin is unknown; the word may have spread with the black rat in the Middle Ages.
g_api|apis(蜜蜂)来源不明。罗马人养蜂很讲究,维吉尔《农事诗》第四卷整卷写蜜蜂。俗拉丁 apicula(小蜜蜂)给出法语 abeille、西班牙语 abeja;意大利语 ape 直接来自 apis。apiculture(养蜂)同族。|Latin apis (a bee) is of unknown origin. Romans were serious beekeepers; Book Four of Virgil's Georgics is all about bees. Vulgar apicula (a little bee) gave French abeille and Spanish abeja; Italian ape comes straight from apis. Apiculture belongs here.
g_casc|法语 casque(头盔)借自西班牙语 casco(头盔、颅骨、碎片),来自 cascar(敲碎),俗拉丁 *quassicare(<quassare 摇碎)。头盔本义是"(破成两半的)壳"。|French casque (a helmet) was borrowed from Spanish casco (a helmet, skull, shard), from cascar (to crack), Vulgar *quassicare (from quassare, to shatter): a helmet was originally a shell.
g_helm|日耳曼语 *helmaz(遮盖物、头盔)来自印欧语 *ḱel-(遮盖,与 celare 藏同根),给出德语 Helm、英语 helmet(helm 的小称)。罗曼语从日耳曼借入:意大利语 elmo、西班牙语 yelmo。同一词根的德语 Hülle(外壳)、Hölle(地狱——"遮住的地方")。|Germanic *helmaz (a covering, a helmet) comes from PIE *ḱel- (to cover, as in Latin celare), giving German Helm and English helmet (a diminutive of helm). Romance borrowed it from Germanic: Italian elmo, Spanish yelmo. The same root gives German Hülle (a cover) and Hölle (hell — the hidden place).
g_flech|法语 flèche(箭)来自法兰克语 *fliugika(飞的东西),与德语 fliegen(飞)、英语 fly 同根——箭是"飞的"。意大利语 freccia、西班牙语 flecha 都借自古法语。fléchette(飞镖)、flécher(用箭头标示)同族。|French flèche (an arrow) comes from Frankish *fliugika (the flying thing), kin to German fliegen and English fly — the arrow is the flier. Italian freccia and Spanish flecha were borrowed from Old French. Fléchette and flécher (to mark with arrows) belong here.
g_quinqu|quinque(五)来自印欧语 *pénkʷe,与希腊语 pente(pentagon)、梵语 pañca、英语 five、德语 fünf 同根——拉丁语的第一个 p 同化成了 qu。法语 cinq、意大利语 cinque、西班牙语 cinco;quintette、quinzaine(两周——15 天)同族。|Latin quinque (five) comes from PIE *pénkʷe, cognate with Greek pente (pentagon), Sanskrit pañca, English five and German fünf — Latin assimilated the first p to qu. French cinq, Italian cinque, Spanish cinco; quintet and quinzaine (a fortnight — fifteen days) belong here.
g_sex|sex(六)来自印欧语 *swéḱs,与希腊语 hex(hexagon)、英语 six、德语 sechs 同根。罗马历法的 sextilis(第六月——后改名 Augustus 八月);siesta(午睡)来自 sexta hora(白天第六个钟头——正午!)。法语 six、意大利语 sei、西班牙语 seis。|Latin sex (six) comes from PIE *swéḱs, cognate with Greek hex (hexagon), English six and German sechs. The Roman month Sextilis (the sixth) was renamed Augustus; siesta comes from sexta hora, the sixth hour of the day — noon! French six, Italian sei, Spanish seis.
g_novem|novem(九)来自印欧语 *h₁néwn̥,与希腊语 ennea、梵语 nava、英语 nine、德语 neun 同根——它与 novus(新)在拉丁语里只是碰巧相似(有人猜测古人数到九是"新的一轮",属猜想)。November 本是第九月。法语 neuf(九、新同形!)、意大利语 nove、西班牙语 nueve。|Latin novem (nine) comes from PIE *h₁néwn̥, cognate with Greek ennea, Sanskrit nava, English nine and German neun; its likeness to novus (new) is accidental in Latin (the idea that nine began a new count is only a guess). November was the ninth month. French neuf (nine and new, the same form!), Italian nove, Spanish nueve.
g_galb|galbus/galbinus(黄绿色的)可能借自日耳曼语 *gelwaz(黄——德语 gelb)或同源(见德语 gelb 条)。法语 jaune(<galbinus)、意大利语 giallo(经古法语 jalne)同族。|Latin galbus and galbinus (yellowish green) may be borrowed from Germanic *gelwaz (yellow — German gelb) or cognate with it (see gelb). French jaune (from galbinus) and Italian giallo (through Old French jalne) belong here.
g_magis|magis(更多)与 magnus(大)同根(*meǵ-)。俗拉丁里 magis 取代 plus 构成比较级(西班牙语 más、葡萄牙语 mais)。法语 jamais = ja(已经,<iam)+ mais(<magis)——"再也"→"永不";mais 本身变成"但是"。意大利语 mai(从不)也来自 magis。|Latin magis (more) shares the root of magnus (*meǵ-). In Vulgar Latin magis replaced plus in comparatives (Spanish más, Portuguese mais). French jamais is ja (already, from iam) + mais (from magis): ever more, hence never; mais on its own became but. Italian mai (never) also comes from magis.
g_numquam|numquam(从不)= ne(不)+ umquam(曾经)——"没有一次"。西班牙语 nunca 直接继承。umquam 来自 quis(谁)的古老代词词干。|Latin numquam (never) is ne (not) + umquam (ever): not once. Spanish nunca inherits it directly. Umquam is built on the old pronoun stem of quis (who).
g_heri|heri(昨天)来自印欧语 *ǵʰyés(昨天),与希腊语 chthes、英语 yesterday、德语 gestern 同根——德英的 g/y 与拉丁的 h 是同一个古音的不同反映。法语 hier、意大利语 ieri、西班牙语 ayer。|Latin heri (yesterday) comes from PIE *ǵʰyés, cognate with Greek chthes, English yesterday and German gestern — the German g, English y and Latin h all reflect one ancient sound. French hier, Italian ieri, Spanish ayer.
g_chord|希腊语 chordē(肠、肠线琴弦)借入拉丁语 chorda。古代琴弦用羊肠制成——所以"肠"变成"弦"。法语 corde(绳、弦)、意大利语 corda、西班牙语 cuerda;chord(和弦)、cordon、accorder(调音、使一致——accord!)同族。|Greek chordē (gut, catgut string) became Latin chorda. Ancient strings were made of sheep gut, so gut became string. French corde (rope, string), Italian corda, Spanish cuerda; chord, cordon and accorder (to tune, to agree — accord!) belong here.
g_flaut|法语 flûte、意大利语 flauto、西班牙语 flauta 的来源不明:通常认为来自古普罗旺斯语 flaüt,可能是拟声词(模仿吹气声),或受拉丁 flare(吹)影响。德语 Flöte 借自古法语。|French flûte, Italian flauto and Spanish flauta are of uncertain origin: usually traced to Old Provençal flaüt, probably imitative of blowing, perhaps influenced by Latin flare (to blow). German Flöte was borrowed from Old French.
g_tambur|法语 tambour、意大利语 tamburo、西班牙语 tambor 来自阿拉伯语 ṭunbūr(一种弦乐器)与波斯语 tabīr(鼓)的混合,十字军时代传入欧洲。拉丁语原词 tympanum(鼓)留在了解剖学里:tympan(鼓膜)。|French tambour, Italian tamburo and Spanish tambor come from a blend of Arabic ṭunbūr (a stringed instrument) and Persian tabīr (a drum), brought to Europe in the crusading era. The Latin tympanum (a drum) survives in anatomy: the tympanum, the eardrum.
g_scen|希腊语 skēnē(帐篷、棚屋→舞台后的布景棚)——演员在棚里换装,棚的立面成了背景,于是 skēnē 变成"舞台"。拉丁 scaena 给出法语 scène、意大利语 scena、西班牙语 escena;scenery(布景)、scenario(剧本提纲)同族。|Greek skēnē (a tent, a hut — the booth behind the stage): actors changed in it and its front became the backdrop, so skēnē came to mean the stage. Latin scaena gave French scène, Italian scena, Spanish escena; scenery and scenario belong here.
g_theatr|希腊语 theatron(观看的地方)来自 theasthai(观看)——与 thea(景象)、theōria(观察→理论!)同根。雅典酒神剧场可容一万七千人。法语 théâtre、意大利语 teatro、西班牙语 teatro、德语 Theater;théâtral 同族。注意:theatron 指观众席,舞台是 skēnē。|Greek theatron (a place for watching) comes from theasthai (to watch), kin to thea (a sight) and theōria (observation, then theory!). The Theatre of Dionysus in Athens held about seventeen thousand. French théâtre, Italian teatro, Spanish teatro, German Theater. Note that theatron was the seating; the stage was the skēnē.
g_forest|中世纪拉丁语 forestis(silva)指"王室禁猎林"——可能来自 foris(外面)——"在公共土地之外的林子",也有人认为来自法兰克语 *forhist(松林)。两说并存。法语 forêt(s 脱落)、英语 forest。|Medieval Latin forestis (silva) was the royal hunting forest — perhaps from foris (outside): the wood outside common land; others derive it from Frankish *forhist (a pine wood). Both views stand. French forêt (with the lost s), English forest.
g_ros|rosa(玫瑰)借自希腊语 rhodon(Rhodes 罗得岛——"玫瑰岛"),而希腊语又可能借自伊朗语 *wr̥da-(花)。玫瑰是维纳斯的花;sub rosa("在玫瑰下")指保密——宴会厅天花板挂玫瑰表示"此间所说不外传"。法语 rose、意大利语 rosa、西班牙语 rosa、德语 Rose;rosaire(念珠——"玫瑰园")同族。|Latin rosa (a rose) is borrowed from Greek rhodon (Rhodes, the rose island), itself probably from Iranian *wr̥da- (a flower). The rose was Venus's flower; sub rosa, under the rose, means in confidence — a rose hung over a banquet table meant what was said there stayed there. French rose, Italian rosa, Spanish rosa, German Rose; the rosary (a rose garden) belongs here.
g_lili|lilium(百合)借自希腊语 leirion,再上溯可能是埃及语或某种地中海语言。法语 lis(lys——法国王室的鸢尾/百合花徽 fleur de lis!)、意大利语 giglio(佛罗伦萨城徽)、西班牙语 lirio(实为鸢尾)、德语 Lilie。|Latin lilium (a lily) is borrowed from Greek leirion, perhaps ultimately Egyptian or another Mediterranean language. French lis (lys — the fleur-de-lis of the French kings!), Italian giglio (the emblem of Florence), Spanish lirio (actually the iris), German Lilie.
g_funer|funus(葬礼,属格 funeris)来源不明。罗马的葬礼游行里,演员戴着死者祖先的蜡面具走在前面。法语 funérailles、意大利语 funerale、西班牙语 funeral;funeste(致命的——"带来葬礼的")、funèbre 同族。|Latin funus (a funeral, genitive funeris) is of unknown origin. In a Roman funeral procession actors walked ahead wearing the wax masks of the dead man's ancestors. French funérailles, Italian funerale, Spanish funeral; funeste (fatal — bringing a funeral) and funèbre belong here.
g_imper|imperare(命令)= in- + parare(准备、安排)——"下令安排"。imperium 是罗马高级官员的指挥权,后来指帝国;imperator 本是士兵为得胜将军欢呼的称号,奥古斯都以后成为皇帝头衔(emperor)。法语 empire、意大利语 impero、西班牙语 imperio、德语 Imperium;impératif(命令式)同族。|Latin imperare (to command) is in- + parare (to prepare, to arrange): to order things done. Imperium was the command held by senior Roman magistrates, and then the empire; imperator was the title soldiers hailed a victorious general with, and after Augustus the emperor's title. French empire, Italian impero, Spanish imperio, German Imperium; the imperative mood belongs here.
g_spelunc|希腊语 spēlynx/spēlaion(洞穴)借入拉丁语 spelunca。意大利语 spelonca 直接继承;speleology(洞穴学)同族。法语 grotte、西班牙语 gruta、德语 Grotte 则来自希腊语 kryptē(隐秘处),见 crypt。|Greek spēlynx and spēlaion (a cave) entered Latin as spelunca. Italian spelonca inherits it directly; speleology belongs here. French grotte, Spanish gruta and German Grotte come instead from Greek kryptē (a hidden place) — see crypt.
g_vall|vallis(山谷)来源不明,可能与 volvere(滚)有关(存疑)。法语 vallée(val + -ée)、意大利语 valle、西班牙语 valle;aval(下游)与 avalanche(雪崩——"往山谷落")同族;加利福尼亚的 Silicon Valley 是英语借来的 valley。|Latin vallis (a valley) is of unknown origin, possibly related to volvere (to roll) — disputed. French vallée (val + -ée), Italian valle, Spanish valle; aval (downstream) and avalanche (falling down to the valley) belong here, and English valley came from Old French.
g_piec|法语 pièce(一块、硬币、房间、剧本)来自中世纪拉丁 pettia,出自高卢语 *pettiā(一块),与威尔士语 peth(东西)同根。一个高卢词在法语里生出无数用法:pièce de monnaie(硬币)、pièce de théâtre(剧本)、pièce d'identité(证件);英语 piece 借自它。|French pièce (a piece, a coin, a room, a play) comes from Medieval Latin pettia, from Gaulish *pettiā (a piece), cognate with Welsh peth (a thing). One Gaulish word spread into countless French uses: pièce de monnaie (a coin), pièce de théâtre (a play), pièce d'identité (an ID); English piece was borrowed from it.
g_griff|法语 griffe(爪)来自 griffer(抓),出自法兰克语 *grīpan(抓——德语 greifen、英语 grip、grab)。griffe 也是"签名印章"与"品牌标签"(la griffe Chanel)。|French griffe (a claw) comes from griffer (to scratch), from Frankish *grīpan (to seize — German greifen, English grip). Griffe is also a signature stamp and a designer label (la griffe Chanel).
g_ungu|unguis(指甲、爪)来自印欧语 *h₃nogʰ-(指甲),与希腊语 onyx(指甲——缟玛瑙因颜色像指甲而得名!)、英语 nail、德语 Nagel 同根。ungula(蹄、爪)是小称。意大利语 unghia、西班牙语 uña;ungulate(有蹄类)同族。|Latin unguis (a nail, a claw) comes from PIE *h₃nogʰ-, cognate with Greek onyx (a nail — the gem is named for its nail colour!), English nail and German Nagel. Ungula (a hoof, a claw) is its diminutive. Italian unghia, Spanish uña; ungulates belong here.
g_caud|cauda/coda(尾巴)来源不明。俗拉丁 coda 给出意大利语 coda(也是乐曲的"尾声")、法语 queue(尾巴、排队!)、西班牙语 cola(尾巴、排队)。coward(胆小鬼)来自古法语 couard——"夹着尾巴的"!|Latin cauda, coda (a tail) is of unknown origin. Vulgar coda gave Italian coda (also a musical coda), French queue (a tail, and a queue!) and Spanish cola (a tail, a queue). Coward comes from Old French couard — with its tail between its legs!
g_pell|pellis(皮、兽皮)来自印欧语 *pel-(皮),与希腊语 pella(皮)、英语 fell(兽皮)、film(薄膜)、德语 Fell 同根。法语 peau(<pellem)、意大利语 pelle、西班牙语 piel;pelisse(皮外套)、pellicule(薄膜、胶片)同族。|Latin pellis (skin, a hide) comes from PIE *pel- (skin), cognate with Greek pella, English fell (a pelt) and film, German Fell. French peau (from pellem), Italian pelle, Spanish piel; pelisse and pellicule (a film) belong here.
g_lac|lacus(湖)来自印欧语 *lókus(湖、池),与古爱尔兰语 loch(尼斯湖 Loch Ness!)、英语 lake?(经法语)同根。法语 lac、意大利语 lago(科莫湖 Lago di Como)、西班牙语 lago;lagoon(潟湖——意大利语 laguna,威尼斯!)同族。|Latin lacus (a lake) comes from PIE *lókus (a lake, a pool), cognate with Old Irish loch (Loch Ness!). French lac, Italian lago (Lago di Como), Spanish lago; lagoon (Italian laguna — Venice!) belongs here.
g_gutt|gutta(水滴)来源不明。医学的 gout(痛风)来自 gutta——中世纪医学认为是"一滴一滴"渗入关节的病液所致。法语 goutte、意大利语 goccia、西班牙语 gota;goutte-à-goutte(点滴)同族。|Latin gutta (a drop) is of unknown origin. Gout comes from it — medieval medicine blamed the disease on morbid humours seeping drop by drop into the joints. French goutte, Italian goccia, Spanish gota; goutte-à-goutte (a drip) belongs here.
g_umor|umor/humor(液体、湿气)来自印欧语 *wegʷ-(湿)存疑。希腊-罗马医学的四体液说(血、黏液、黄胆汁、黑胆汁)用 humor 指体液,体液的比例决定性情——所以 humour 后来指"气质"再到"幽默"。humide(湿的)、humidité 同族。|Latin umor or humor (a liquid, moisture) is perhaps from PIE *wegʷ- (wet). Greco-Roman medicine's four humours (blood, phlegm, yellow bile, black bile) used humor for bodily fluids, whose balance set one's temperament — so humour came to mean temperament and then comedy. Humid and humidity belong here.
g_sit|sitis(口渴)来源不明,可能与希腊语 phthisis(消耗、痨病)同根(存疑)。罗马医学把口渴看作体内干燥的征兆。法语 soif、意大利语 sete、西班牙语 sed 都直接继承了它,形式因各语言的音变而不同:法语掉了中间的 t,加了 f;西班牙语只剩一个音节。assoiffé(口渴的)、sitibondo(意大利语"渴望的")同族。|Latin sitis (thirst) is of unknown origin, possibly related to Greek phthisis (wasting) — disputed. French soif, Italian sete, Spanish sed.
g_fames|fames(饥饿)来源不明。famine(饥荒)来自 fames。法语 faim、意大利语 fame、西班牙语 hambre(<famine-,f→h 是西班牙语的规则音变)。注意:与 fama(名声)无关。|Latin fames (hunger) is of unknown origin. Famine comes from it. French faim, Italian fame, Spanish hambre (from famine-, with the regular Spanish change f→h). Unrelated to fama (fame).
g_boue|法语 boue(泥)来自高卢语 *bawa(泥、污秽),与威尔士语 baw(泥)同根——又一个留在法语里的高卢词。boueux(泥泞的)、éboueur(清道夫)同族。|French boue (mud) comes from Gaulish *bawa (dirt), cognate with Welsh baw — another Gaulish word surviving in French. Boueux (muddy) and éboueur (a dustman) belong here.
g_limus|limus(淤泥)来自印欧语 *(s)leymH-(黏),与英语 slime(黏液)、lime(石灰——黏合用的)、德语 Leim(胶)同根:淤泥就是"黏糊糊的东西"。罗马人用 limus 指河底的泥;尼罗河泛滥留下的肥沃淤泥也叫 limus。意大利语 limo、西班牙语 limo 都指河泥、淤泥;limoso(多泥的)同族。|Latin limus (mud, slime) comes from PIE *(s)leymH- (sticky), cognate with English slime and lime (the binding stuff). Italian limo, Spanish limo (river silt).
g_carcer|carcer(监狱)来源不明,可能是重叠词。罗马的 Carcer Tullianum 是关押重犯的地下牢,传说圣彼得曾被关在这里。竞技场起跑的栅门也叫 carceres。意大利语 carcere、西班牙语 cárcel;incarcerate 同族。|Latin carcer (a prison) is of unknown origin, possibly reduplicated. Rome's Carcer Tullianum was the underground dungeon for great prisoners, where legend puts St Peter. The starting gates of the circus were also carceres. Italian carcere, Spanish cárcel; incarcerate belongs here.
g_caten|catena(锁链)来源不明。法语 chaîne(古法语 chaeine)、意大利语 catena、西班牙语 cadena、德语 Kette(早期借词);enchaîner(锁住、连接)、concatenate(串联)同族。|Latin catena (a chain) is of unknown origin. French chaîne (Old French chaeine), Italian catena, Spanish cadena and German Kette (an early loan); enchaîner (to chain, to link) and concatenate belong here.
g_orgueil|法语 orgueil(傲慢)来自法兰克语 *urgōlī(骄傲、卓越),与古高地德语 urguol(著名的)同根。orgueilleux(傲慢的)同族。它取代了拉丁的 superbia 在法语里的位置。|French orgueil (pride) comes from Frankish *urgōlī (pride, excellence), cognate with Old High German urguol (famous). Orgueilleux (proud) belongs here. It took the place of Latin superbia in French.
g_colere|法语 colère(愤怒)来自拉丁 cholera(胆汁病),借自希腊语 cholē(胆汁,见 Glanz/gelb 条的 *ǵʰel- 家族):体液说认为黄胆汁过多使人易怒,所以"胆汁"就成了"怒气"——英语 choleric(暴躁的)同理。cholera(霍乱)是同一个词的医学支。|French colère (anger) comes from Latin cholera (a bilious disorder), from Greek cholē (bile — the *ǵʰel- family of the gelb entry): humoral theory held that excess yellow bile made people irascible, so bile became anger — as in English choleric. Cholera, the disease, is the medical branch of the same word.
g_templ|templum(神庙)本义是占卜官在天空或地面上划出的"观测区"——来自印欧语 *temh₁-(切),"划出来的地方",与 tempus(时间——"切出的一段")、希腊语 temenos(圣域)同根。法语 temple、意大利语 tempio、西班牙语 templo、德语 Tempel;contempler(凝视——"在观测区里看"!)同族。|Latin templum (a temple) was first the space an augur marked out in the sky or on the ground for observing omens — from PIE *temh₁- (to cut): a cut-out space, kin to tempus (a cut-off stretch of time) and Greek temenos (a sacred precinct). French temple, Italian tempio, Spanish templo, German Tempel; contemplate (to gaze within the templum!) belongs here.
g_obscur|obscurus(暗的)= ob- + *skuro-(遮盖——印欧语 *skewH-,与 scutum 盾、英语 sky 同根存疑)。法语 obscur/obscurité、意大利语 oscuro/oscurità、西班牙语 oscuro/oscuridad;obscurantisme、中世纪的 "Dark Ages" 同理。|Latin obscurus (dark) is ob- + *skuro- (covered — PIE *skewH-, perhaps kin to scutum and English sky). French obscur, obscurité; Italian oscuro, oscurità; Spanish oscuro, oscuridad; obscurantism belongs here.
g_pat|pati(忍受,分词 passus)来自印欧语 *peh₁-(伤害、受苦)存疑,与希腊语 pēma(痛苦)比较。patientia(忍耐)、patiens(病人——"受苦的人"!)、passio(受难——耶稣受难 Passion)同族。法语 patience、意大利语 pazienza、西班牙语 paciencia;compassion(同情——"一起受苦")同族。|Latin pati (to suffer, participle passus) is perhaps from PIE *peh₁- (to hurt), compared with Greek pēma (pain). Patientia (endurance), patiens (a patient — the one who suffers!) and passio (the Passion) belong here. French patience, Italian pazienza, Spanish paciencia; compassion (suffering together) is kin.
g_turr|turris(塔)借自希腊语 tyrsis/tyrris,可能再上溯到小亚细亚语言(存疑)。法语 tour、意大利语 torre(比萨斜塔 Torre di Pisa)、西班牙语 torre、德语 Turm(借自古法语 tor,m 可能受 Sturm 类推)。tourelle(炮塔)、turret 同族。|Latin turris (a tower) is borrowed from Greek tyrsis or tyrris, perhaps from a language of Asia Minor (disputed). French tour, Italian torre (the Leaning Tower of Pisa), Spanish torre, German Turm (from Old French tor, the m perhaps by analogy); turret belongs here.
g_laet|laetus(欢喜的)来源不明。原为农业词,指土地"肥沃、丰饶"(laetamen 粪肥!)——丰收的田地让人欢喜。意大利语 lieto(欢喜的,lieto fine 大团圆结局);Letizia/Leticia("欢乐")是人名。|Latin laetus (joyful) is of unknown origin. It began as a farming word for fertile, flourishing land (laetamen, manure!) — a rich field makes people glad. Italian lieto (glad; lieto fine, a happy ending); Letizia and Leticia (joy) are names.
g_carm|carmen(歌、诗、咒语)来自 canere(唱),*can-men 音变而来——罗马最古老的法律与祷词都以 carmen(韵文咒语)的形式念诵。意大利语 carme(颂诗)、英语 charm(魔力——经古法语 charme"咒语")同族。见 cant。|Latin carmen (a song, a poem, a spell) comes from canere (to sing), by a sound change from *can-men: Rome's oldest laws and prayers were recited as carmina, chanted formulas. Italian carme (an ode) and English charm (through Old French charme, a spell) belong here. See cant.
g_collis|collis(山丘)与 columna、culmen 同根:印欧语 *kelH-(升起),英语 hill 同源。罗马七丘里有 Collis Quirinalis(奎里纳尔山)。意大利语 colle(Colle 也是意大利总统府的代称!)、法语 col(山口)。|Latin collis (a hill) shares its root with columna and culmen: PIE *kelH- (to rise), cognate with English hill. Among Rome's seven hills is the Collis Quirinalis. Italian colle (Il Colle is also shorthand for the Italian presidency on the Quirinal!), French col (a mountain pass).
g_palud|palus(沼泽,属格 paludis)来源不明。罗马南边的蓬蒂内沼泽(Pomptinae paludes)直到 1930 年代才排干。意大利语 palude;paludisme(疟疾——"沼泽病")同族。|Latin palus (a marsh, genitive paludis) is of unknown origin. The Pontine Marshes south of Rome were drained only in the 1930s. Italian palude; paludisme (malaria — the marsh disease) belongs here.
g_pantan|西班牙语 pantano(沼泽、水库)来源不明,可能是前罗马词,也有人认为来自意大利语 pantano(泥潭)。在现代西班牙语里它还指"水库"——佛朗哥时代大量修建的 pantanos。|Spanish pantano (a marsh, a reservoir) is of unknown origin, possibly pre-Roman, or borrowed from Italian pantano (a quagmire). In modern Spanish it also means a reservoir — the many pantanos built in the Franco era.
g_luctus|lugere(哀悼)、luctus(哀恸)来自印欧语 *lewg-(破碎、悲痛)存疑,与希腊语 lygros(悲惨的)比较。罗马的哀悼期有法定长度,寡妇服丧十个月。意大利语 lutto、西班牙语 luto(丧服、服丧)。|Latin lugere (to mourn) and luctus (grief) are perhaps from PIE *lewg- (to break, to grieve), compared with Greek lygros (wretched). Roman mourning had legal lengths; a widow mourned ten months. Italian lutto, Spanish luto (mourning, mourning dress).
g_vincl|vincire(捆绑)、vinculum(绳索、镣铐)来源不明,可能与 viere(编)有关。罗马法把债务关系称为 vinculum iuris("法律的绳索")。意大利语 vincolo、西班牙语 vínculo(纽带)。注意:与 vincere(胜利)同形不同源。|Latin vincire (to bind) and vinculum (a cord, a fetter) are of uncertain origin, perhaps linked to viere (to plait). Roman law called an obligation a vinculum iuris, a bond of law. Italian vincolo, Spanish vínculo (a tie). Unrelated to vincere (to conquer), despite the look.
g_pelo|西班牙语 pelear(打斗)来自 pelo(毛发,<拉丁语 pilus)——本义"揪头发",扭打时互相揪头发!这个画面感很强的动词在中世纪西班牙语里出现,取代了拉丁的 pugnare。pelea(打斗)、peleador(好斗的人)、pelotón?(否,那是 pelota 球)同族;pelo 本身还给出 pelado(秃的)、pelar(剥皮、拔毛)。|Spanish pelear (to fight) comes from pelo (hair, from Latin pilus): originally to pull hair, as brawlers do! Pelea (a fight) and peleador belong here.
g_semper|semper(总是)来自 *sem-(一)+ per——"一次到底"。美国海军陆战队的格言 Semper Fidelis(永远忠诚)。意大利语 sempre、西班牙语 siempre;sempiternal(永恒的)同族。|Latin semper (always) is *sem- (one) + per: once and throughout. The US Marines' motto is Semper Fidelis. Italian sempre, Spanish siempre; sempiternal belongs here.
g_azur|意大利语 azzurro、西班牙语 azul、法语 azur 来自阿拉伯语 lāzaward,再上溯到波斯语 lājvard(青金石,阿富汗巴达赫尚的产地名)——青金石的蓝就是"天蓝"。开头的 l- 被误当成冠词脱落了。意大利国家队叫 Gli Azzurri(蓝衣军团)。|Italian azzurro, Spanish azul and French azur come from Arabic lāzaward, from Persian lājvard, lapis lazuli (named after its source in Badakhshan) — the blue of lapis is sky blue. The initial l- was taken for an article and dropped. Italy's national team are Gli Azzurri.
g_sold|solidus(结实的)后来是罗马帝国的金币名(君士坦丁 309 年发行);领这种钱的人就是 soldato("领饷的")——意大利语 soldato、法语 soldat、西班牙语 soldado、德语 Soldat(16 世纪借自意大利语)。solde(军饷、打折)同族。|Latin solidus (solid) became the name of the Roman gold coin issued by Constantine in 309; a man paid in it was a soldato, one who draws pay — Italian soldato, French soldat, Spanish soldado, German Soldat (borrowed from Italian in the 16th century). Solde (pay, a sale) belongs here.
g_nebul|nebula(雾)来自印欧语 *nebʰ-(云、湿气),与希腊语 nephelē(云)、梵语 nábhas(天空)、德语 Nebel(雾——同一个词!)、Nibelungen 同根;拉丁语 nubes(云)可能也是远亲。天文学用 nebula 指星云。意大利语 nebbia、西班牙语 niebla、nebuloso(模糊的)同族;法语日常的"雾"改用 brouillard,但 nébuleux(模糊的)、nébuleuse(星云)保留了拉丁词根。|Latin nebula (mist) comes from PIE *nebʰ- (cloud, moisture), cognate with Greek nephelē (a cloud), Sanskrit nábhas (the sky) and German Nebel (fog — the same word!), and the Nibelungen; Latin nubes (a cloud) may be a distant relative. Astronomy uses nebula for a star-cloud. Italian nebbia, Spanish niebla and nebuloso (hazy) belong here; everyday French switched to brouillard, but nébuleux (nebulous) and nébuleuse (a nebula) keep the Latin root.
petit|法语 petit(小)来自俗拉丁 *pittitus,出自一个表示"小"的儿语/表情词根 *pitt-(存疑,非古典拉丁)。同一个表情词根可能也给了意大利语 piccolo、西班牙语 pequeño 的某些形式——"小"是人类最爱用新造的亲昵词替换的概念之一,所以罗曼语三种"小"各不相同,都来源不明。古典拉丁的 parvus(小)在日常语里消失了。petit-fils(孙子——"小儿子")、petit déjeuner(早餐)、rapetisser(变小)同族。|French petit (small) comes from Vulgar Latin *pittitus, from an expressive nursery root *pitt- for smallness (disputed, not classical Latin). Small is one of the ideas languages most love to renew with fresh endearing words, so the three Romance words for small all differ and all are of unclear origin; classical parvus vanished from everyday speech. Petit-fils (grandson — little son), petit déjeuner (breakfast) and rapetisser (to shrink) belong here.
picc|意大利语 piccolo(小)来源不明,很可能出自表情性的"小"词根 *pikk-(存疑),与法语 petit 的 *pitt- 平行。它给音乐留下了 piccolo(短笛——"小笛子")。piccino、picciolo(叶柄)、Piccolomini(家族名"小个子")同族。|Italian piccolo (small) is of unknown origin, probably from an expressive root *pikk- for littleness (disputed), parallel to the *pitt- of French petit. It gave music the piccolo (the little flute). Piccino and the family name Piccolomini (little man) belong here.
pequeñ|西班牙语 pequeño(小)来源不明,可能出自表情性词根 *pikk-(与意大利语 piccolo 同,存疑),加上指小后缀 -eño。古西班牙语还用 chico(<ciccum 小东西)——chico 今天是"男孩"。pequeñez(渺小)、empequeñecer(缩小)同族。|Spanish pequeño (small) is of unknown origin, perhaps from the same expressive *pikk- as Italian piccolo (disputed), with the suffix -eño. Old Spanish also used chico (from ciccum, a trifle) — today chico means boy. Pequeñez (smallness) and empequeñecer (to belittle) belong here.
blanc|法语 blanc、意大利语 bianco、西班牙语 blanco(白)都来自日耳曼语 *blankaz(闪亮的、白的)——法兰克人、伦巴第人、西哥特人把它带进罗曼语,取代了拉丁的 albus。它与德语 blank(光亮的、赤裸的)、blinken(闪)、英语 blank 同根。所以罗曼语的"白"是一个日耳曼借词(见德语 weiß 条)。carte blanche(全权——"白纸")、blanchir(漂白、洗钱)、Montblanc、Casablanca(白房子)同族。|French blanc, Italian bianco and Spanish blanco (white) all come from Germanic *blankaz (shining, white) — brought into Romance by Franks, Lombards and Visigoths, displacing Latin albus. It is cognate with German blank (shiny, bare), blinken (to flash) and English blank. So the Romance word for white is a Germanic loan (see German weiß). Carte blanche, blanchir (to bleach, to launder money), Mont Blanc and Casablanca (the white house) belong here.
bleu|法语 bleu(蓝)来自法兰克语 *blāo(蓝、铅灰色),与德语 blau、英语 blue(英语借自古法语!)同根:罗曼语的"蓝"也是日耳曼借词(见德语 blau 条)。意大利语 blu 是较晚从法语借的;azzurro/azul 另有波斯来源。cordon bleu(蓝绶带——最高厨艺)、bleuet(矢车菊)、bleu 也指"新手"(bleu = 菜鸟)同族。|French bleu (blue) comes from Frankish *blāo (blue, leaden), cognate with German blau and English blue (which English borrowed from Old French!): the Romance blue is a Germanic loan too (see German blau). Italian blu is a later loan from French; azzurro and azul have a Persian source. Cordon bleu (the blue ribbon — top cooking), bleuet (a cornflower) and un bleu (a rookie) belong here.
niñ|西班牙语 niño/niña(孩子)来源有争议:最常见的说法是它来自儿语的 *ninno(模仿婴儿咿呀声——与意大利语 ninnare 哄睡、ninna nanna 摇篮曲同源),属于"表情词",没有古典拉丁来源。1997–98 年的厄尔尼诺现象 El Niño("圣婴")因在圣诞节前后出现而得名。niñez(童年)、niñera(保姆)同族。|Spanish niño/niña (a child) has a disputed origin; the commonest view derives it from nursery *ninno (imitating a baby's babble — cognate with Italian ninnare, to lull, and ninna nanna, a lullaby), an expressive word with no classical Latin source. El Niño (the Christ Child) is named for appearing around Christmas. Niñez (childhood) and niñera (a nanny) belong here.
perr|西班牙语 perro(狗)来源不明——这是罗曼语里有名的谜词:它在中世纪先作贬义出现("野狗、贱狗"),可能来自牧人赶狗的吆喝声 prrr(拟声,存疑),后来取代了拉丁 canis 的后代 can(今天 can 只剩文雅用法)。perrera(狗舍)、perrito caliente(热狗)同族。|Spanish perro (a dog) is of unknown origin — a famous puzzle word of Romance. It first appears in medieval texts as an insult (a cur), perhaps from herders' call to dogs, prrr (imitative, disputed), and later displaced can, the heir of Latin canis (can survives only in literary use). Perrera (a kennel) and perrito caliente (a hot dog) belong here.
g_foul|法语 foule(人群)来自 fouler(踩、压),出自俗拉丁 *fullare(踩洗毛呢——fullo 漂洗工,罗马的 fullonica 洗衣坊里工人在桶里用脚踩布!)。人群就是"挤压在一起的"。refouler(压回、排斥)、défouler(发泄)同族。|French foule (a crowd) comes from fouler (to tread, to press), from Vulgar *fullare (to full cloth — the fullo, the Roman fuller, trod cloth underfoot in the vats of the fullonica!). A crowd is people pressed together. Refouler (to push back, to repress) and se défouler (to let off steam) belong here.
g_arrug|西班牙语 arroyo(小溪)来自拉丁语 arrugia(矿坑道、引水沟)——普林尼描写西班牙金矿用 arrugia 引水冲山(ruina montium)。arrugia 本身是前罗马的伊比利亚词。今天美国西南部的 arroyo(干河床)就是它。|Spanish arroyo (a stream) comes from Latin arrugia (a mining gallery, a water channel) — Pliny describes the Spanish gold mines using arrugiae to wash down mountains (ruina montium). Arrugia itself is a pre-Roman Iberian word. The arroyo of the American Southwest, a dry gully, is the same word.
g_frett|意大利语 fretta(急忙)来源有争议:通常认为来自动词 frettare(擦洗、赶快),出自俗拉丁 *frictare——frictus(摩擦,fricare 的分词,friction 摩擦力就是它)——"急急忙忙地擦"。另有学者认为是拟声。in fretta(匆忙地)、frettoloso(仓促的)、affrettarsi(赶紧)同族。|Italian fretta (haste) has a disputed origin; the usual view derives it from the verb frettare (to scrub, to hurry), from Vulgar *frictare — frictus, the participle of fricare (to rub), as in friction: rubbing in a hurry. Others think it imitative. In fretta (in a hurry), frettoloso (hasty) and affrettarsi (to hurry up) belong here.
`;
  RAW.trim().split("\n").forEach(line => {
    const i = line.indexOf("|"), j = line.lastIndexOf("|");
    if (i < 0 || i === j) return;
    ROOT_STORIES.shared[line.slice(0, i)] = [line.slice(i + 1, j), line.slice(j + 1)];
  });
})();
ROOT_STORIES.alias.mujer = "mulier";
ROOT_STORIES.alias.bianc = "blanc";
