/* =====================================================
   FUGA MYTHICA — CURSUS English 🇬🇧 · batch 2 (frequency band 1000–2000)
   Merges into VOCAB.en: more Latin/Greek roots, academic & news vocabulary.
   ===================================================== */
(function () {
  const p = VOCAB.en;
  Object.assign(p.roots, {
    anim: ["anim", "灵魂,生命", "spirit, life"], art: ["art", "技艺", "skill"], aug: ["aug / auct", "增加", "increase"], cas: ["cad / cas / cid", "落", "fall"],
    cant: ["cant / chant", "唱", "sing"], cis: ["cid / cis", "切,杀", "cut, kill"], cit: ["cit", "召唤,引", "summon"], clam: ["clam / claim", "喊", "shout"],
    clin: ["clin / cline", "倾", "lean"], cur: ["cur / cura", "关心", "care"], dign: ["dign", "值得", "worthy"], doc: ["doc / doct", "教", "teach"],
    don: ["don / dot", "给", "give"], dorm: ["dorm", "睡", "sleep"], equ: ["equ", "相等", "equal"], err: ["err", "游荡,错", "wander"],
    fall: ["fall / fals", "欺骗", "deceive"], fig: ["fig / fict", "塑造", "shape"], flect: ["flect / flex", "弯", "bend"], form: ["form", "形", "shape"],
    fract: ["frag / fract", "打碎", "break"], fug: ["fug", "逃", "flee"], fus: ["fund / fus", "倒,融", "pour"], greg: ["greg", "群", "flock"],
    hab: ["hab / hib", "有,住", "have, hold"], her: ["her / hes", "粘", "stick"], hosp: ["hosp / host", "客,主", "guest, host"], it: ["it", "走", "go"],
    junct: ["junct / join", "连接", "join"], labor: ["labor", "劳动", "work"], lat: ["lat / later", "边", "side"], liter: ["liter", "字母", "letter"],
    lud: ["lud / lus", "玩", "play"], medi: ["medi", "中间", "middle"], merg: ["merg / mers", "沉", "dip"], migr: ["migr", "迁移", "move"],
    mod: ["mod", "方式,度", "manner, measure"], mon: ["mon / monit", "警告", "warn"], nom: ["nom / nomin", "名", "name"], not: ["not", "标记,知", "mark, know"],
    opt: ["opt", "选择", "choose"], ord: ["ord / ordin", "秩序", "order"], orig: ["ori / orig", "升起", "rise"], pass: ["pass / pat / path", "受苦,感受", "suffer, feel"],
    pet: ["pet / petit", "寻求", "seek"], plac: ["plac", "取悦", "please"], plen: ["plen / plet", "满", "fill"], plic: ["plic / ply", "折", "fold"],
    pot: ["pot / poss", "能", "able"], prehend: ["prehend / prehens", "抓", "grasp"], prob: ["prob / prov", "测试,好", "test, good"], punct: ["punct / pung", "点,刺", "point, prick"],
    put: ["put", "想,算", "think, reckon"], quir: ["quir / quest / quis", "寻求,问", "seek, ask"], rad: ["rad / radic", "根", "root"], rat: ["rat / ratio", "推理,算", "reason"],
    rid: ["rid / ris", "笑", "laugh"], sacr: ["sacr / secr / sanct", "神圣", "holy"], sal: ["sal / salv / salut", "健康,盐", "health, salt"], sat: ["sat / satis", "够", "enough"],
    sequ: ["sequ / secut", "跟随", "follow"], sign: ["sign", "记号", "mark"], simil: ["simil / simul", "像", "like"], soci: ["soci", "伙伴", "companion"],
    son: ["son", "声", "sound"], spir: ["spir", "呼吸", "breathe"], tempt: ["tempt", "试", "try"], term: ["term / termin", "边界,末", "limit, end"],
    test: ["test", "见证", "witness"], tort: ["tort / tors", "扭", "twist"], trib: ["trib / tribut", "给,分", "give, assign"], turb: ["turb", "搅动", "disturb"],
    umbr: ["umbr", "影", "shade"], vac: ["vac / van", "空", "empty"], vad: ["vad / vas", "走", "go"], vag: ["vag", "游荡", "wander"],
    via: ["via / voy", "路", "way"], vulg: ["vulg", "大众", "common people"], ple: ["pleb / publ", "民众", "people"], cur2: ["cur / curr", "跑", "run"],
    /* Greek batch 2 */ agog: ["agog", "引导", "lead"], alg: ["alg / algia", "痛", "pain"], bar: ["bar", "重,压", "weight, pressure"], bibl: ["bibli", "书", "book"],
    chrom: ["chrom", "颜色", "color"], crypt: ["crypt", "隐藏", "hidden"], dox: ["dox / dog", "意见", "opinion"], gam: ["gam", "婚", "marriage"],
    gastr: ["gastr", "胃", "stomach"], glot: ["glot / gloss", "舌,语", "tongue"], gon: ["gon", "角", "angle"], helio: ["helio", "太阳", "sun"],
    hem: ["hem / hemat", "血", "blood"], iatr: ["iatr", "医", "heal"], idio: ["idio", "自己的,特有", "own, peculiar"], kilo: ["kilo", "千", "thousand"],
    lith: ["lith", "石", "stone"], lys: ["lys / lyt", "分解", "loosen"], naut: ["naut / nav", "船", "ship"], nomos: ["nom / nomy", "法,规律", "law"],
    orth: ["orth", "正,直", "straight, correct"], ox: ["ox / oxy", "尖,酸", "sharp, acid"], paed: ["ped / paed", "孩子", "child"], phan: ["phan / phen", "显现", "show"],
    phor: ["phor / pher", "带", "carry"], plast: ["plast", "塑", "mold"], pneum: ["pneum", "气,肺", "breath, lung"], prot: ["prot", "第一", "first"],
    schiz: ["schiz", "分裂", "split"], seism: ["seism", "震", "shake"], stat: ["stat", "站,静", "stand"], tax: ["tax / tact", "排列", "arrange"],
    tom: ["tom", "切", "cut"], top: ["top", "地方", "place"], trop: ["trop", "转", "turn"], typ: ["typ", "印,型", "impression, type"],
    xen: ["xen", "外来", "foreign"], zo: ["zo", "动物", "animal"], hier: ["hier", "神圣", "sacred"], kine: ["kine / cine", "动", "move"],
    ge: ["gen / geno", "种族,出生", "race, birth"], mis: ["mis", "恨", "hate"], nec: ["necr", "死", "dead"], oligo: ["olig", "少", "few"],
    ped2: ["ped", "教育", "teach child"], phag: ["phag", "吃", "eat"], sphere: ["spher", "球", "ball"], the: ["thes / thet", "放置", "put"],
  });
  p.words.push(
    ["animal","动物","living being","anim"], ["animate","使有生气","give life","anim"], ["unanimous","一致的","one spirit","anim"], ["magnanimous","宽宏的","great-souled","anim"], ["animosity","敌意","hostile spirit","anim"], ["inanimate","无生命的","lifeless","anim"],
    ["artisan","工匠","craftsman","art"], ["artifact","人工制品","made thing","art"], ["artificial","人造的","made by skill","art"], ["artistic","艺术的","skillful","art"], ["inert","惰性的","without skill","art"],
    ["augment","增加","increase","aug"], ["auction","拍卖","increasing bids","aug"], ["author","作者","one who increases","aug"], ["authority","权威","author's power","aug"], ["august","威严的","majestic","aug"],
    ["cascade","瀑布","falling water","cas"], ["casualty","伤亡","one who fell","cas"], ["occasion","场合","falling toward","cas"], ["decadent","颓废的","falling away","cas"], ["accident","事故","what falls to","cas"], ["incident","事件","what falls in","cas"], ["coincide","巧合","fall together","cas"], ["deciduous","落叶的","falling off","cas"],
    ["chant","吟唱","sing","cant"], ["enchant","使着迷","sing into","cant"], ["incantation","咒语","singing upon","cant"], ["cantata","康塔塔","sung piece","cant"], ["recant","撤回","sing back","cant"],
    ["decide","决定","cut off","cis"], ["precise","精确的","cut short","cis"], ["concise","简明的","cut together","cis"], ["incision","切口","cut in","cis"], ["scissors","剪刀","cutters","cis"], ["homicide","杀人","man-killing","cis"], ["pesticide","杀虫剂","pest-killer","cis"], ["excise","切除","cut out","cis"],
    ["cite","引用","summon","cit"], ["recite","背诵","call back","cit"], ["excite","激发","call out","cit"], ["incite","煽动","call in","cit"], ["solicit","恳求","stir up","cit"], ["citation","引文","summons","cit"],
    ["claim","声称","call out","clam"], ["exclaim","惊叫","cry out","clam"], ["proclaim","宣布","cry forth","clam"], ["acclaim","喝彩","shout to","clam"], ["clamor","喧闹","loud cry","clam"], ["disclaim","否认","cry apart","clam"],
    ["incline","倾向","lean toward","clin"], ["decline","下降,拒绝","lean down","clin"], ["recline","斜倚","lean back","clin"], ["climate","气候","slope of earth","clin"], ["clinic","诊所","bedside","clin"],
    ["cure","治愈","care","cur"], ["curious","好奇的","full of care","cur"], ["accurate","准确的","done with care","cur"], ["secure","安全的","free from care","cur"], ["curator","策展人","caretaker","cur"], ["manicure","美甲","hand care","cur"], ["procure","获得","take care for","cur"],
    ["dignity","尊严","worthiness","dign"], ["dignify","使有尊严","make worthy","dign"], ["indignant","愤慨的","unworthy treatment","dign"], ["condign","应得的","fully deserved","dign"],
    ["doctor","医生","teacher","doc"], ["doctrine","教义","teaching","doc"], ["document","文件","teaching paper","doc"], ["docile","温顺的","teachable","doc"], ["indoctrinate","灌输","teach into","doc"],
    ["donate","捐赠","give","don"], ["donor","捐赠者","giver","don"], ["pardon","原谅","give thoroughly","don"], ["condone","宽恕","give together","don"], ["antidote","解毒剂","given against","don"], ["anecdote","轶事","unpublished","don"],
    ["dormitory","宿舍","sleeping place","dorm"], ["dormant","休眠的","sleeping","dorm"],
    ["equal","相等的","same","equ"], ["equation","方程","making equal","equ"], ["equator","赤道","equalizer","equ"], ["equivalent","等价的","equal worth","equ"], ["adequate","足够的","made equal to","equ"], ["equilibrium","平衡","equal balance","equ"], ["equity","公平","equalness","equ"], ["equinox","昼夜平分点","equal night","equ"],
    ["error","错误","wandering","err"], ["erratic","不稳定的","wandering","err"], ["aberration","偏差","wandering away","err"], ["errand","差事","journey","err"],
    ["false","假的","deceiving","fall"], ["fallacy","谬误","deception","fall"], ["falsify","伪造","make false","fall"], ["fail","失败","deceive expectations","fall"], ["fault","过错","failing","fall"], ["default","默认,违约","failure","fall"],
    ["figure","图形,人物","shape","fig"], ["figment","虚构","thing shaped","fig"], ["effigy","肖像","shaped out","fig"], ["configure","配置","shape together","fig"], ["disfigure","毁容","shape apart","fig"],
    ["reflect","反射,反思","bend back","flect"], ["deflect","偏转","bend away","flect"], ["inflect","变调,变形","bend in","flect"], ["flexible","灵活的","bendable","flect"], ["reflex","反射","bent back","flect"], ["genuflect","跪拜","bend the knee","flect"],
    ["formal","正式的","by form","form"], ["formula","公式","little form","form"], ["reform","改革","form again","form"], ["conform","符合","form with","form"], ["deform","变形","form badly","form"], ["inform","告知","form in mind","form"], ["transform","转变","form across","form"], ["uniform","制服","one form","form"],
    ["fragile","易碎的","breakable","fract"], ["fragment","碎片","broken piece","fract"], ["fraction","分数","broken part","fract"], ["fracture","骨折","break","fract"], ["refract","折射","break back","fract"], ["infraction","违规","breaking in","fract"],
    ["fugitive","逃犯","one fleeing","fug"], ["refuge","避难所","flee back","fug"], ["refugee","难民","one who fled","fug"], ["centrifugal","离心的","fleeing the center","fug"], ["subterfuge","托词","secret flight","fug"],
    ["fuse","融合","pour together","fus"], ["confuse","使困惑","pour together","fus"], ["refuse","拒绝","pour back","fus"], ["diffuse","扩散","pour apart","fus"], ["profuse","大量的","poured forth","fus"], ["transfusion","输血","pouring across","fus"], ["refund","退款","pour back","fus"], ["foundry","铸造厂","pouring place","fus"],
    ["gregarious","合群的","of the flock","greg"], ["congregate","聚集","flock together","greg"], ["segregate","隔离","flock apart","greg"], ["aggregate","总计","flock to","greg"], ["egregious","极坏的","out of the flock","greg"],
    ["habit","习惯","what one has","hab"], ["inhabit","居住","dwell in","hab"], ["habitat","栖息地","dwelling","hab"], ["exhibit","展出","hold out","hab"], ["prohibit","禁止","hold before","hab"], ["inhibit","抑制","hold in","hab"], ["able","能够的","having power","hab"],
    ["adhere","粘附","stick to","her"], ["cohere","连贯","stick together","her"], ["inherent","固有的","sticking in","her"], ["hesitate","犹豫","stick","her"], ["adhesive","胶粘剂","sticker","her"],
    ["hospital","医院","guest house","hosp"], ["hospitality","好客","guest-friendliness","hosp"], ["host","主人","receiver of guests","hosp"], ["hostage","人质","guest held","hosp"], ["hostile","敌对的","of the enemy","hosp"], ["hotel","旅馆","guest house","hosp"],
    ["exit","出口","go out","it"], ["initial","最初的","going in","it"], ["initiate","开始","go in","it"], ["transit","运输","go across","it"], ["circuit","电路,环路","go around","it"], ["ambition","野心","going around (for votes)","it"], ["itinerary","行程","journey plan","it"], ["obituary","讣告","gone toward death","it"], ["sedition","煽动叛乱","going apart","it"],
    ["junction","交叉口","joining","junct"], ["conjunction","连词","joined together","junct"], ["adjunct","附属物","joined to","junct"], ["injunction","禁令","joined in","junct"], ["joint","关节","join","junct"], ["subjugate","征服","bring under yoke","junct"],
    ["labor","劳动","work","labor"], ["laboratory","实验室","work place","labor"], ["collaborate","合作","work together","labor"], ["elaborate","精心的","worked out","labor"], ["laborious","费力的","full of work","labor"],
    ["lateral","侧面的","of the side","lat"], ["bilateral","双边的","two-sided","lat"], ["unilateral","单边的","one-sided","lat"], ["collateral","抵押品,附带的","side by side","lat"], ["latitude","纬度","breadth","lat"],
    ["literal","字面的","by the letter","liter"], ["literate","识字的","lettered","liter"], ["literature","文学","letters","liter"], ["obliterate","抹去","blot out letters","liter"], ["alliteration","头韵","letters to","liter"],
    ["illusion","幻觉","playing on","lud"], ["delude","欺骗","play false","lud"], ["elude","逃避","play out","lud"], ["allude","暗指","play toward","lud"], ["prelude","前奏","play before","lud"], ["interlude","插曲","play between","lud"], ["ludicrous","荒唐的","playful","lud"], ["collusion","勾结","playing together","lud"],
    ["medium","媒介,中等","middle","medi"], ["mediate","调解","go between","medi"], ["immediate","立即的","no middle","medi"], ["medieval","中世纪的","middle age","medi"], ["intermediate","中间的","between middle","medi"], ["mediocre","平庸的","halfway up","medi"], ["Mediterranean","地中海","middle of lands","medi"],
    ["merge","合并","dip together","merg"], ["emerge","出现","rise out","merg"], ["submerge","淹没","dip under","merg"], ["immerse","沉浸","dip in","merg"], ["emergency","紧急情况","sudden rising","merg"],
    ["migrate","迁移","move","migr"], ["immigrate","移入","move in","migr"], ["emigrate","移出","move out","migr"], ["migratory","迁徙的","moving","migr"],
    ["mode","方式","manner","mod"], ["model","模型","little measure","mod"], ["modern","现代的","of the present measure","mod"], ["moderate","适度的","measured","mod"], ["modest","谦虚的","keeping measure","mod"], ["modify","修改","make a measure","mod"], ["accommodate","容纳","fit to measure","mod"], ["commodity","商品","convenient thing","mod"],
    ["monitor","监视器","warner","mon"], ["admonish","告诫","warn to","mon"], ["premonition","预感","forewarning","mon"], ["monument","纪念碑","reminder","mon"], ["summon","召唤","warn secretly","mon"], ["monster","怪物","warning sign","mon"],
    ["nominate","提名","name","nom"], ["nominal","名义上的","in name","nom"], ["denomination","面额,教派","naming","nom"], ["ignominy","耻辱","no name","nom"], ["misnomer","误称","wrong name","nom"], ["renown","名望","re-naming","nom"],
    ["note","笔记","mark","not"], ["notable","显著的","worth marking","not"], ["notify","通知","make known","not"], ["notion","观念","idea","not"], ["notorious","臭名昭著的","well known","not"], ["annotate","注释","mark on","not"], ["denote","表示","mark out","not"],
    ["option","选项","choice","opt"], ["optional","可选的","by choice","opt"], ["adopt","采纳","choose to","opt"], ["opt","选择","choose","opt"], ["co-opt","吸收","choose together","opt"],
    ["order","秩序","arrangement","ord"], ["ordinary","普通的","in order","ord"], ["coordinate","协调","order together","ord"], ["subordinate","下级","ordered under","ord"], ["extraordinary","非凡的","outside order","ord"], ["ordain","任命","set in order","ord"], ["inordinate","过度的","out of order","ord"],
    ["origin","起源","rising","orig"], ["original","原始的","from the origin","orig"], ["orient","东方,定向","rising sun","orig"], ["aboriginal","原住民的","from the origin","orig"], ["abort","中止","miscarry","orig"],
    ["passion","激情","suffering","pass"], ["passive","被动的","suffering","pass"], ["patient","病人,耐心的","suffering","pass"], ["compassion","同情","suffering with","pass"], ["compatible","兼容的","suffering together","pass"], ["dispassionate","冷静的","without passion","pass"], ["impassive","无动于衷的","not feeling","pass"],
    ["petition","请愿","seeking","pet"], ["compete","竞争","seek together","pet"], ["competent","称职的","seeking adequately","pet"], ["appetite","食欲","seeking toward","pet"], ["repeat","重复","seek again","pet"], ["perpetual","永久的","seeking through","pet"], ["impetus","推动力","attack","pet"], ["centripetal","向心的","seeking the center","pet"],
    ["please","取悦","give pleasure","plac"], ["pleasant","令人愉快的","pleasing","plac"], ["placid","平静的","pleasing","plac"], ["placate","安抚","make pleased","plac"], ["complacent","自满的","pleased with self","plac"], ["placebo","安慰剂","I shall please","plac"],
    ["plenty","充足","fullness","plen"], ["plentiful","丰富的","full","plen"], ["complete","完整的","filled up","plen"], ["deplete","耗尽","empty out","plen"], ["replete","充满的","filled again","plen"], ["supplement","补充","fill up","plen"], ["implement","实施","fill in","plen"], ["compliment","恭维","fulfilment","plen"],
    ["complicate","使复杂","fold together","plic"], ["explicit","明确的","unfolded","plic"], ["implicit","含蓄的","folded in","plic"], ["replica","复制品","folded again","plic"], ["apply","申请,应用","fold to","plic"], ["imply","暗示","fold in","plic"], ["reply","回复","fold back","plic"], ["multiply","乘","many folds","plic"], ["duplicate","复制","two-fold","plic"], ["accomplice","同谋","folded together","plic"],
    ["potent","强效的","able","pot"], ["potential","潜在的","having power","pot"], ["impotent","无能的","powerless","pot"], ["omnipotent","全能的","all-powerful","pot"], ["possible","可能的","able to be","pot"], ["possess","拥有","have power over","pot"],
    ["comprehend","理解","grasp fully","prehend"], ["apprehend","逮捕,领会","seize","prehend"], ["apprehensive","忧虑的","grasping fear","prehend"], ["reprehensible","应受谴责的","to be held back","prehend"], ["prison","监狱","seized place","prehend"], ["comprehensive","全面的","grasping all","prehend"],
    ["probe","探查","test","prob"], ["probable","很可能的","provable","prob"], ["approve","批准","find good","prob"], ["prove","证明","test","prob"], ["improve","改善","make good","prob"], ["reprove","责备","find bad","prob"], ["probation","试用期","testing","prob"],
    ["punctual","准时的","to the point","punct"], ["punctuate","加标点","mark with points","punct"], ["puncture","刺穿","pricking","punct"], ["pungent","刺鼻的","pricking","punct"], ["acupuncture","针灸","needle pricking","punct"], ["expunge","删除","prick out","punct"],
    ["compute","计算","reckon together","put"], ["computer","电脑","reckoner","put"], ["dispute","争论","reckon apart","put"], ["repute","名声","reckon again","put"], ["deputy","代理人","assigned","put"], ["impute","归咎","reckon to","put"], ["amputate","截肢","cut around","put"],
    ["require","需要","seek","quir"], ["inquire","询问","seek into","quir"], ["acquire","获得","seek to","quir"], ["exquisite","精美的","sought out","quir"], ["question","问题","asking","quir"], ["quest","探索","seeking","quir"], ["request","请求","ask again","quir"], ["conquest","征服","seeking together","quir"], ["inquisitive","好问的","seeking into","quir"], ["prerequisite","先决条件","required before","quir"],
    ["radical","激进的,根本的","from the root","rad"], ["eradicate","根除","root out","rad"], ["radish","萝卜","root","rad"], ["radius","半径","spoke","rad"],
    ["ratio","比率","reckoning","rat"], ["rational","理性的","reasoning","rat"], ["ration","配给","reckoned share","rat"], ["rate","比率","reckoned amount","rat"], ["reason","理由","reckoning","rat"], ["irrational","不理性的","without reason","rat"],
    ["ridicule","嘲笑","make laugh","rid"], ["ridiculous","荒谬的","laughable","rid"], ["deride","嘲弄","laugh down","rid"], ["derision","嘲笑","laughing down","rid"],
    ["sacred","神圣的","holy","sacr"], ["sacrifice","牺牲","make holy","sacr"], ["sacrament","圣礼","holy rite","sacr"], ["consecrate","祝圣","make holy","sacr"], ["desecrate","亵渎","unmake holy","sacr"], ["sanctuary","避难所,圣所","holy place","sacr"], ["sanction","批准,制裁","holy decree","sacr"], ["saint","圣人","holy one","sacr"],
    ["salute","致敬","wish health","sal"], ["salutary","有益的","healthful","sal"], ["salvage","打捞","save","sal"], ["salvation","救赎","saving","sal"], ["salary","薪水","salt money","sal"], ["salad","沙拉","salted","sal"], ["saline","含盐的","salty","sal"],
    ["satisfy","满足","make enough","sat"], ["satisfaction","满足","making enough","sat"], ["saturate","饱和","fill up","sat"], ["insatiable","贪得无厌的","never enough","sat"], ["satire","讽刺","full dish","sat"],
    ["sequence","序列","following","sequ"], ["consequence","后果","following with","sequ"], ["subsequent","随后的","following under","sequ"], ["sequel","续集","what follows","sequ"], ["consecutive","连续的","following together","sequ"], ["execute","执行","follow out","sequ"], ["prosecute","起诉","follow forward","sequ"], ["persecute","迫害","follow through","sequ"], ["obsequious","谄媚的","following after","sequ"], ["suit","诉讼,套装","following","sequ"], ["pursue","追求","follow forth","sequ"],
    ["signal","信号","sign","sign"], ["signature","签名","sign","sign"], ["significant","重要的","sign-making","sign"], ["designate","指定","mark out","sign"], ["resign","辞职","sign back","sign"], ["assign","分配","mark to","sign"], ["insignia","徽章","marks","sign"], ["design","设计","mark out","sign"],
    ["similar","相似的","like","simil"], ["simulate","模拟","make like","simil"], ["assimilate","同化","make like to","simil"], ["simultaneous","同时的","at like time","simil"], ["facsimile","传真,摹本","make alike","simil"], ["resemble","像","be like again","simil"], ["dissimilar","不同的","not alike","simil"],
    ["social","社会的","of companions","soci"], ["society","社会","companionship","soci"], ["associate","联系,同事","join with","soci"], ["sociable","好交际的","companionable","soci"], ["dissociate","分离","separate from","soci"],
    ["sonic","声音的","of sound","son"], ["resonate","共鸣","sound again","son"], ["consonant","辅音","sounding with","son"], ["dissonance","不和谐","sounding apart","son"], ["unison","齐声","one sound","son"], ["sonnet","十四行诗","little sound","son"], ["sonar","声呐","sound navigation","son"],
    ["spirit","精神","breath","spir"], ["inspire","激励","breathe into","spir"], ["expire","到期,死","breathe out","spir"], ["respire","呼吸","breathe again","spir"], ["conspire","密谋","breathe together","spir"], ["aspire","渴望","breathe toward","spir"], ["perspire","出汗","breathe through","spir"], ["transpire","发生,蒸发","breathe across","spir"],
    ["tempt","诱惑","try","tempt"], ["attempt","尝试","try at","tempt"], ["temptation","诱惑","trying","tempt"], ["contempt","蔑视","scorn","tempt"],
    ["term","术语,期限","limit","term"], ["terminal","终点站,末期的","at the end","term"], ["terminate","终止","end","term"], ["determine","决定","set limits","term"], ["exterminate","消灭","drive beyond limits","term"], ["interminable","无休止的","without end","term"],
    ["testify","作证","bear witness","test"], ["testimony","证词","witness","test"], ["contest","竞赛","call to witness","test"], ["protest","抗议","witness forth","test"], ["detest","憎恶","curse by witness","test"], ["attest","证实","witness to","test"], ["testament","遗嘱,约","witnessing","test"],
    ["torture","折磨","twisting","tort"], ["distort","扭曲","twist apart","tort"], ["extort","勒索","twist out","tort"], ["retort","反驳","twist back","tort"], ["torment","折磨","twisting","tort"], ["contort","扭曲","twist together","tort"], ["tortuous","曲折的","twisting","tort"],
    ["tribute","贡品,致敬","thing given","trib"], ["contribute","贡献","give together","trib"], ["distribute","分发","give apart","trib"], ["attribute","属性,归因","assign to","trib"], ["retribution","报应","paying back","trib"], ["tributary","支流","paying stream","trib"],
    ["disturb","打扰","stir apart","turb"], ["turbulent","动荡的","stirred up","turb"], ["turbine","涡轮","spinner","turb"], ["perturb","扰乱","stir through","turb"], ["turmoil","混乱","disturbance","turb"],
    ["umbrella","雨伞","little shade","umbr"], ["umbrage","不快","shade, offense","umbr"], ["penumbra","半影","almost shade","umbr"], ["adumbrate","预示","shadow forth","umbr"],
    ["vacant","空的","empty","vac"], ["vacation","假期","emptying","vac"], ["vacuum","真空","empty space","vac"], ["evacuate","撤离","empty out","vac"], ["vanish","消失","become empty","vac"], ["vain","徒劳的","empty","vac"], ["vanity","虚荣","emptiness","vac"],
    ["invade","入侵","go in","vad"], ["evade","逃避","go out","vad"], ["pervade","弥漫","go through","vad"], ["wade","涉水","go","vad"], ["evasive","回避的","going out","vad"],
    ["vague","模糊的","wandering","vag"], ["vagrant","流浪者","wanderer","vag"], ["extravagant","奢侈的","wandering beyond","vag"], ["vagabond","流浪者","wanderer","vag"],
    ["trivial","琐碎的","of the crossroads","via"], ["obvious","明显的","in the way","via"], ["previous","以前的","way before","via"], ["deviate","偏离","off the way","via"], ["voyage","航行","journey","via"], ["convoy","护送","go with","via"], ["envoy","使者","one sent on the way","via"], ["viaduct","高架桥","way leading","via"], ["impervious","不受影响的","no way through","via"],
    ["vulgar","粗俗的","of the common people","vulg"], ["divulge","泄露","make common","vulg"], ["Vulgate","拉丁通俗译本","common version","vulg"],
    /* Greek batch 2 */ ["pedagogue","教师","child-leader","agog"], ["demagogue","煽动者","people-leader","agog"], ["synagogue","犹太会堂","bringing together","agog"],
    ["analgesic","止痛药","without pain","alg"], ["nostalgia","怀旧","homecoming pain","alg"], ["neuralgia","神经痛","nerve pain","alg"],
    ["barometer","气压计","weight measure","bar"], ["baritone","男中音","heavy tone","bar"], ["isobar","等压线","equal pressure","bar"],
    ["Bible","圣经","the books","bibl"], ["bibliography","参考书目","book-writing","bibl"], ["bibliophile","藏书家","book lover","bibl"],
    ["chromosome","染色体","color body","chrom"], ["monochrome","单色","one color","chrom"], ["chromatic","彩色的","of color","chrom"],
    ["cryptic","神秘的","hidden","crypt"], ["encrypt","加密","put in hiding","crypt"], ["crypt","地下室","hidden vault","crypt"], ["cryptography","密码学","hidden writing","crypt"],
    ["orthodox","正统的","right opinion","dox"], ["paradox","悖论","beside opinion","dox"], ["heterodox","异端的","other opinion","dox"], ["dogma","教条","opinion","dox"], ["doxology","颂歌","praise speech","dox"],
    ["monogamy","一夫一妻制","one marriage","gam"], ["polygamy","多配偶制","many marriages","gam"], ["bigamy","重婚","two marriages","gam"],
    ["gastric","胃的","of the stomach","gastr"], ["gastronomy","美食学","stomach law","gastr"], ["gastritis","胃炎","stomach inflammation","gastr"],
    ["polyglot","通晓多语者","many tongues","glot"], ["glossary","词汇表","tongue list","glot"], ["epiglottis","会厌","upon the tongue","glot"],
    ["polygon","多边形","many angles","gon"], ["pentagon","五边形","five angles","gon"], ["diagonal","对角线","through angles","gon"], ["trigonometry","三角学","triangle measuring","gon"],
    ["heliocentric","日心的","sun-centered","helio"], ["helium","氦","sun element","helio"], ["heliotrope","向日性植物","sun-turner","helio"],
    ["hemorrhage","大出血","blood burst","hem"], ["hemoglobin","血红蛋白","blood globe","hem"], ["anemia","贫血","no blood","hem"], ["hemophilia","血友病","blood-loving","hem"],
    ["psychiatrist","精神科医生","mind healer","iatr"], ["pediatrician","儿科医生","child healer","iatr"], ["geriatric","老年病的","old-age healing","iatr"],
    ["idiom","习语","own expression","idio"], ["idiosyncrasy","特质","own mixture","idio"], ["idiot","傻瓜","private person","idio"],
    ["kilometer","千米","thousand meters","kilo"], ["kilogram","千克","thousand grams","kilo"], ["kilowatt","千瓦","thousand watts","kilo"],
    ["monolith","巨石","single stone","lith"], ["lithography","平版印刷","stone writing","lith"], ["Neolithic","新石器时代","new stone","lith"], ["lithium","锂","stone element","lith"],
    ["analysis","分析","loosening up","lys"], ["paralysis","瘫痪","loosening beside","lys"], ["catalyst","催化剂","dissolver","lys"], ["electrolyte","电解质","loosened by electricity","lys"], ["dialysis","透析","loosening through","lys"],
    ["nautical","航海的","of ships","naut"], ["astronaut","宇航员","star sailor","naut"], ["nausea","恶心","ship sickness","naut"], ["navigate","导航","drive a ship","naut"], ["navy","海军","ships","naut"],
    ["economy","经济","household law","nomos"], ["astronomy","天文学","star law","nomos"], ["autonomy","自治","self law","nomos"], ["gastronomy","美食学","stomach law","nomos"], ["taxonomy","分类学","arrangement law","nomos"],
    ["orthodontist","正畸医生","straight teeth","orth"], ["orthopedic","矫形的","straight child","orth"], ["orthography","正字法","correct writing","orth"],
    ["oxygen","氧","acid-maker","ox"], ["oxide","氧化物","oxygen compound","ox"], ["paroxysm","发作","sharpening beside","ox"], ["oxymoron","矛盾修辞","sharp-dull","ox"],
    ["pediatrics","儿科","child healing","paed"], ["pedagogy","教育学","child-leading","paed"], ["encyclopedia","百科全书","circle of child-learning","paed"],
    ["phenomenon","现象","thing appearing","phan"], ["fantasy","幻想","appearance","phan"], ["phantom","幽灵","apparition","phan"], ["epiphany","顿悟","showing upon","phan"], ["diaphanous","透明的","showing through","phan"], ["emphasis","强调","showing in","phan"],
    ["metaphor","隐喻","carry across","phor"], ["semaphore","信号旗","sign-bearer","phor"], ["euphoria","欣快","well-bearing","phor"], ["phosphorus","磷","light-bearer","phor"], ["periphery","外围","carried around","phor"],
    ["plastic","塑料","moldable","plast"], ["plaster","石膏","molded","plast"], ["protoplasm","原生质","first molded","plast"],
    ["pneumonia","肺炎","lung disease","pneum"], ["pneumatic","气动的","of air","pneum"],
    ["prototype","原型","first type","prot"], ["protein","蛋白质","first substance","prot"], ["protagonist","主角","first actor","prot"], ["protocol","协议","first glued sheet","prot"], ["proton","质子","first particle","prot"],
    ["schizophrenia","精神分裂症","split mind","schiz"], ["schism","分裂","split","schiz"],
    ["seismic","地震的","of shaking","seism"], ["seismograph","地震仪","shake-writer","seism"],
    ["static","静态的","standing","stat"], ["statistics","统计学","state facts","stat"], ["thermostat","恒温器","heat-stander","stat"], ["ecstasy","狂喜","standing out","stat"], ["apostasy","背教","standing away","stat"], ["hemostat","止血钳","blood stopper","stat"],
    ["syntax","句法","arranging together","tax"], ["taxonomy","分类学","arrangement law","tax"], ["tactics","战术","arrangement","tax"], ["ataxia","共济失调","no order","tax"],
    ["anatomy","解剖学","cutting up","tom"], ["atom","原子","uncuttable","tom"], ["epitome","缩影","cut upon","tom"], ["dichotomy","二分法","cut in two","tom"], ["appendectomy","阑尾切除","cutting out appendix","tom"],
    ["topic","主题","place","top"], ["topography","地形学","place-writing","top"], ["utopia","乌托邦","no place","top"], ["topical","时事的","of the place","top"],
    ["tropical","热带的","of the turning","trop"], ["trophy","奖杯","turning point","trop"], ["entropy","熵","turning within","trop"], ["heliotrope","向日","sun-turner","trop"],
    ["type","类型","impression","typ"], ["typical","典型的","of the type","typ"], ["stereotype","刻板印象","solid type","typ"], ["prototype","原型","first type","typ"], ["archetype","原型","first type","typ"], ["typography","排版","type writing","typ"],
    ["xenophobia","仇外","fear of foreigners","xen"], ["xenon","氙","stranger element","xen"], ["xenophile","亲外者","foreign-lover","xen"],
    ["zoo","动物园","animal park","zo"], ["zoology","动物学","animal study","zo"], ["protozoa","原生动物","first animals","zo"], ["zodiac","黄道带","circle of animals","zo"],
    ["hierarchy","等级制","sacred rule","hier"], ["hieroglyph","象形文字","sacred carving","hier"],
    ["kinetic","动的","of motion","kine"], ["cinema","电影院","moving pictures","kine"], ["telekinesis","隔空移物","far movement","kine"],
    ["genocide","种族灭绝","race killing","ge"], ["genealogy","家谱","race study","ge"], ["eugenics","优生学","well-born","ge"],
    ["misanthrope","厌世者","hater of humans","mis"], ["misogyny","厌女","hatred of women","mis"],
    ["necropolis","墓地","city of the dead","nec"], ["necrosis","坏死","death of tissue","nec"],
    ["oligarchy","寡头政治","rule of few","oligo"], ["oligopoly","寡头垄断","few sellers","oligo"],
    ["esophagus","食道","eating tube","phag"], ["sarcophagus","石棺","flesh-eater","phag"], ["bacteriophage","噬菌体","bacteria eater","phag"],
    ["sphere","球体","ball","sphere"], ["atmosphere","大气","vapor ball","sphere"], ["hemisphere","半球","half ball","sphere"],
    ["thesis","论文","placing","the"], ["synthesis","合成","placing together","the"], ["hypothesis","假设","placing under","the"], ["antithesis","对立","placing against","the"], ["parenthesis","括号","placing beside","the"], ["epithet","绰号","placed upon","the"]
  );
})();
