/* =====================================================
   FUGA MYTHICA — CURSUS Latin 🏛️ · extra batch 2
   Adjective/noun families and the remaining high-frequency verb stems; merged into LATIN_EXTRA
   before buildLatinPack() runs.
   ===================================================== */
(function () {
  Object.assign(LATIN_EXTRA.roots, {
    ars: ["art-", "技艺", "skill"], animus: ["anim-", "灵魂,心", "spirit, mind"], augeo: ["aug- / auct-", "增加", "increase"], cano: ["can- / cant-", "唱", "sing"],
    civis: ["civ-", "公民", "citizen"], colo: ["col- / cult-", "耕,崇拜", "till, worship"], cumbo: ["cub- / cumb-", "躺", "lie"], debeo: ["deb- / debit-", "欠", "owe"],
    divido: ["divid- / divis-", "分", "divide"], durus: ["dur-", "硬", "hard"], emo: ["em- / empt-", "买", "buy"], sum: ["es- / ent-", "是", "be"],
    faber: ["fabr-", "工匠", "craftsman"], for: ["fa- / fat-", "说", "speak"], fendo: ["fend- / fens-", "打击", "strike"], festus: ["fest-", "节日", "festive"],
    flos: ["flor-", "花", "flower"], folium: ["foli-", "叶", "leaf"], gero: ["ger- / gest-", "携带,做", "carry, do"], gratus: ["grat-", "感激,悦人", "pleasing"],
    humus: ["hum-", "土", "earth"], ignis2: ["ign-", "火", "fire"], imago: ["imag- / imit-", "像", "image"], integer: ["integr-", "完整", "whole"],
    ius: ["iur- / ius-", "法,誓", "law, oath"], lac: ["lact-", "奶", "milk"], labor: ["lab- / laps-", "滑,劳", "slip, toil"], laxus: ["lax-", "松", "loose"],
    ligo: ["lig-", "绑", "bind"], lingua: ["lingu-", "舌,语", "tongue"], liqueo: ["liqu-", "液", "liquid"], loquor: ["loqu- / locut-", "说", "speak"],
    magister: ["magistr-", "老师", "master"], medeor: ["med- / medic-", "治", "heal"], metior: ["met- / mens-", "量", "measure"], merx: ["merc-", "商品", "goods"],
    miror: ["mir-", "惊奇", "wonder"], misceo: ["misc- / mixt-", "混", "mix"], mundus: ["mund-", "世界", "world"], munus: ["mun-", "职责,礼", "duty, gift"],
    murus: ["mur-", "墙", "wall"], muto: ["mut-", "变", "change"], necto: ["nect- / nex-", "绑", "bind"], nihil: ["nihil / null-", "无", "nothing"],
    noceo: ["noc- / nox-", "害", "harm"], norma: ["norm-", "规则", "rule"], numerus: ["numer-", "数", "number"], nutrio: ["nutr-", "喂养", "nourish"],
    opus: ["oper-", "工作", "work"], os: ["or- / orat-", "口", "mouth"], orno: ["orn-", "装饰", "adorn"], panis: ["pan-", "面包", "bread"],
    par: ["par-", "相等", "equal"], paro: ["par- / parat-", "准备", "prepare"], passus: ["pass-", "步", "step"], pasco: ["pasc- / past-", "喂,牧", "feed"],
    poena: ["poen- / pun-", "罚", "punish"], plaudo: ["plaud- / plos-", "拍手", "clap"], precor: ["prec-", "祈求", "pray"], privus: ["priv-", "私", "private"],
    pugno: ["pugn-", "打", "fight"], purus: ["pur- / purg-", "净", "pure"], queror: ["quer- / quest-", "抱怨", "complain"], radius: ["radi-", "光线", "ray"],
    rapio: ["rap- / rapt-", "抓", "seize"], rota: ["rot-", "轮", "wheel"], rus: ["rur- / rust-", "乡村", "country"], sanus: ["san-", "健康", "healthy"],
    sapio: ["sap-", "尝,智", "taste, be wise"], scindo: ["scind- / sciss-", "切", "cut"], sculpo: ["sculp-", "雕", "carve"], seco: ["sec- / sect-", "切", "cut"],
    senex: ["sen-", "老", "old"], severus: ["sever-", "严厉", "strict"], solus: ["sol-", "独", "alone"], somnus: ["somn-", "睡", "sleep"],
    sors: ["sort-", "命运", "lot"], spargo: ["sparg- / spers-", "撒", "scatter"], spondeo: ["spond- / spons-", "承诺", "pledge"], stimulus: ["stimul- / stinct-", "刺", "goad"],
    stringo: ["string- / strict-", "拉紧", "bind tight"], stupeo: ["stup-", "惊呆", "be stunned"], sumo: ["sum- / sumpt-", "拿", "take"], taceo: ["tac- / tacit-", "沉默", "be silent"],
    terreo: ["terr-", "吓", "frighten"], texo: ["tex- / text-", "织", "weave"], timeo: ["tim-", "怕", "fear"], tingo: ["ting- / tinct-", "染", "dye"],
    tueor: ["tu- / tut-", "保护", "guard"], ultimus: ["ult-", "最远", "last"], unda: ["und-", "波", "wave"], utor: ["ut- / us-", "用", "use"],
    vestis: ["vest-", "衣", "garment"], volo2: ["vol- / volat-", "飞", "fly"], volvo: ["volv- / volut-", "滚", "roll"], vulnus: ["vulner-", "伤", "wound"],
    urbs: ["urb-", "城", "city"], populus: ["popul-", "人民", "people"], civitas: ["civit-", "国家", "state"], lex: ["leg- / legis-", "法律", "law"],
    iudex: ["iudic-", "法官", "judge"], pax: ["pac-", "和平", "peace"], hostis: ["host-", "敌人", "enemy"], hospes: ["hospit-", "客,主", "guest, host"],
    omnis: ["omn-", "全", "all"], multus: ["mult-", "多", "many"], primus: ["prim-", "第一", "first"], medius: ["medi-", "中间", "middle"],
    longus: ["long-", "长", "long"], brevis: ["brev-", "短", "short"], altus: ["alt-", "高,深", "high, deep"], latus2: ["lat- / later-", "宽,边", "wide, side"],
    candidus: ["cand-", "白,亮", "white, bright"], clarus: ["clar-", "明亮", "clear"], durus2: ["dur-", "硬", "hard"], mollis: ["moll-", "软", "soft"],
    fortuna: ["fortun-", "运气", "fortune"], felix: ["felic-", "幸福", "happy"], miser: ["miser-", "悲惨", "wretched"], caritas: ["car-", "亲爱,贵", "dear"],
  });
  LATIN_EXTRA.words.push(
    ["ars","技艺","skill","ars"], ["artifex","工匠","craftsman","ars"], ["artificium","技巧","craft","ars"], ["iners","无能的","unskilled","ars"], ["sollers","灵巧的","skilful","ars"],
    ["animus","心灵","mind","animus"], ["anima","灵魂,气息","soul, breath","animus"], ["animal","动物","animal","animus"], ["animosus","勇敢的","spirited","animus"], ["unanimus","一心的","of one mind","animus"], ["magnanimus","宽宏的","great-souled","animus"], ["exanimis","无生命的","lifeless","animus"],
    ["augeo","增加","increase","augeo"], ["auctor","作者,创始者","author","augeo"], ["auctoritas","权威","authority","augeo"], ["augustus","威严的","majestic","augeo"], ["auxilium","援助","help","augeo"], ["augmentum","增长","increase","augeo"],
    ["cano","唱","sing","cano"], ["cantus","歌","song","cano"], ["canto","歌唱","sing","cano"], ["cantor","歌手","singer","cano"], ["carmen","诗歌","song, poem","cano"], ["incanto","念咒","enchant","cano"], ["recanto","撤回","recant","cano"],
    ["civis","公民","citizen","civis"], ["civitas","国家,公民权","state","civis"], ["civilis","公民的","civil","civis"], ["civicus","市民的","civic","civis"],
    ["colo","耕,崇拜","till, worship","colo"], ["cultus","崇拜,培养","worship, culture","colo"], ["cultura","耕作","cultivation","colo"], ["colonia","殖民地","colony","colo"], ["colonus","农夫","farmer","colo"], ["agricola","农民","farmer","colo"], ["incola","居民","inhabitant","colo"],
    ["cubo","躺","lie","cumbo"], ["incumbo","靠在,致力","lean on","cumbo"], ["succumbo","屈服","succumb","cumbo"], ["recumbo","躺下","recline","cumbo"], ["cubiculum","卧室","bedroom","cumbo"], ["incubo","孵","brood","cumbo"],
    ["debeo","欠,应该","owe, ought","debeo"], ["debitum","债","debt","debeo"], ["debitor","债务人","debtor","debeo"],
    ["divido","分","divide","divido"], ["divisio","分割","division","divido"], ["individuus","不可分的","indivisible","divido"], ["dividuus","可分的","divisible","divido"],
    ["durus","硬的","hard","durus"], ["duro","持续,硬化","last, harden","durus"], ["durabilis","持久的","lasting","durus"], ["obduro","坚持","persist","durus"], ["induro","使硬","harden","durus"],
    ["emo","买","buy","emo"], ["adimo","夺走","take away","emo"], ["eximo","取出","take out","emo"], ["eximius","杰出的","exceptional","emo"], ["redimo","赎回","buy back","emo"], ["exemptus","被免除的","exempt","emo"], ["praemium","奖赏","reward","emo"], ["sumo","拿","take","emo"],
    ["sum","是","be","sum"], ["absum","缺席","be away","sum"], ["adsum","在场","be present","sum"], ["desum","缺乏","be lacking","sum"], ["intersum","在中间,有关","be between","sum"], ["praesum","主持","be in charge","sum"], ["prosum","有益","benefit","sum"], ["essentia","本质","essence","sum"], ["praesens","在场的","present","sum"], ["absens","缺席的","absent","sum"],
    ["faber","工匠","craftsman","faber"], ["fabrica","工坊","workshop","faber"], ["fabricor","制造","build","faber"],
    ["for","说","speak","for"], ["fatum","命运","fate","for"], ["fabula","故事","story","for"], ["fama","名声","fame","for"], ["infans","婴儿","infant","for"], ["affabilis","和蔼的","affable","for"], ["ineffabilis","不可言说的","ineffable","for"], ["praefatio","序言","preface","for"], ["confiteor","承认","confess","for"], ["profiteor","公开声明","profess","for"],
    ["defendo","保卫","defend","fendo"], ["offendo","冒犯","offend","fendo"], ["defensio","防御","defence","fendo"], ["offensa","冒犯","offence","fendo"], ["infensus","敌对的","hostile","fendo"],
    ["festus","节日的","festive","festus"], ["festum","节日","feast","festus"], ["festivus","欢乐的","festive","festus"], ["feriae","假日","holidays","festus"],
    ["flos","花","flower","flos"], ["floreo","开花,繁荣","bloom","flos"], ["flora","花神","Flora","flos"], ["floridus","花开的","flowery","flos"],
    ["folium","叶","leaf","folium"], ["foliatus","有叶的","leafy","folium"], ["trifolium","三叶草","clover","folium"],
    ["gero","携带,做","carry, do","gero"], ["gestus","姿态","gesture","gero"], ["gesta","事迹","deeds","gero"], ["digero","分开,消化","digest","gero"], ["suggero","提供,建议","suggest","gero"], ["congero","堆积","heap up","gero"], ["exaggero","堆高,夸大","exaggerate","gero"], ["registrum","登记簿","register","gero"], ["belligero","作战","wage war","gero"],
    ["gratus","感激的,悦人的","pleasing, grateful","gratus"], ["gratia","恩惠,感谢","favour, thanks","gratus"], ["gratulor","祝贺","congratulate","gratus"], ["ingratus","忘恩的","ungrateful","gratus"], ["gratis","免费","for free","gratus"], ["gratuitus","无偿的","free","gratus"],
    ["humus","土","earth","humus"], ["humilis","低的,谦卑","low, humble","humus"], ["humanus","人的","human","humus"], ["homo","人","human being","humus"], ["humanitas","人性,教养","humanity","humus"], ["exhumo","挖出","exhume","humus"], ["posthumus","死后的","posthumous","humus"],
    ["ignis","火","fire","ignis2"], ["igneus","火的","fiery","ignis2"], ["ignitus","点燃的","ignited","ignis2"],
    ["imago","像","image","imago"], ["imaginor","想象","imagine","imago"], ["imitor","模仿","imitate","imago"], ["imitatio","模仿","imitation","imago"],
    ["integer","完整的","whole","integer"], ["integritas","完整,正直","integrity","integer"], ["integro","恢复","renew","integer"], ["redintegro","重整","restore","integer"],
    ["ius","法,权利","law, right","ius"], ["iustus","正义的","just","ius"], ["iustitia","正义","justice","ius"], ["iuro","发誓","swear","ius"], ["iudex","法官","judge","ius"], ["iudico","判断","judge","ius"], ["iudicium","判决","judgment","ius"], ["iniuria","不公,伤害","injury","ius"], ["iurisdictio","司法权","jurisdiction","ius"], ["periurium","伪证","perjury","ius"], ["coniuro","共谋","conspire","ius"],
    ["lac","奶","milk","lac"], ["lacteus","奶的","milky","lac"], ["lactuca","莴苣","lettuce","lac"],
    ["labor","劳动,滑","toil, slip","labor"], ["laboro","劳作","work","labor"], ["laboriosus","费力的","laborious","labor"], ["collabor","合作","collaborate","labor"], ["elaboro","精心制作","work out","labor"], ["lapsus","滑倒,失误","slip","labor"], ["collapsus","倒塌","collapse","labor"],
    ["laxus","松的","loose","laxus"], ["laxo","放松","loosen","laxus"], ["relaxo","放松","relax","laxus"],
    ["ligo","绑","bind","ligo"], ["obligo","约束","bind","ligo"], ["obligatio","义务","obligation","ligo"], ["religio","宗教","religion","ligo"], ["alligo","绑上","tie to","ligo"], ["colligo","连接","bind together","ligo"], ["ligamentum","绷带","bandage","ligo"],
    ["lingua","舌,语言","tongue, language","lingua"], ["bilinguis","双语的","bilingual","lingua"], ["linguosus","多嘴的","talkative","lingua"],
    ["liquor","液体","liquid","liqueo"], ["liquidus","液态的","liquid","liqueo"], ["liquesco","融化","melt","liqueo"],
    ["loquor","说","speak","loquor"], ["eloquens","雄辩的","eloquent","loquor"], ["eloquentia","口才","eloquence","loquor"], ["colloquium","谈话","conversation","loquor"], ["alloquor","对…说","address","loquor"], ["locutio","说法","expression","loquor"], ["loquax","健谈的","talkative","loquor"], ["soliloquium","独白","soliloquy","loquor"],
    ["magister","老师,主","master","magister"], ["magistratus","官员","magistrate","magister"], ["magisterium","教职","teaching authority","magister"],
    ["medeor","治","heal","medeor"], ["medicus","医生","doctor","medeor"], ["medicina","医学","medicine","medeor"], ["remedium","补救","remedy","medeor"], ["medicamentum","药","drug","medeor"],
    ["metior","量","measure","metior"], ["mensura","尺度","measure","metior"], ["mensis","月","month","metior"], ["dimensio","尺寸","dimension","metior"], ["immensus","无量的","immense","metior"],
    ["merx","商品","goods","merx"], ["mercator","商人","merchant","merx"], ["mercatus","市场","market","merx"], ["merces","报酬","wages","merx"], ["commercium","贸易","commerce","merx"], ["mercenarius","雇佣的","hired","merx"],
    ["miror","惊奇","wonder","miror"], ["mirus","奇妙的","wonderful","miror"], ["miraculum","奇迹","miracle","miror"], ["admiror","钦佩","admire","miror"], ["mirabilis","奇妙的","marvellous","miror"],
    ["misceo","混","mix","misceo"], ["mixtura","混合","mixture","misceo"], ["miscellaneus","混杂的","miscellaneous","misceo"], ["promiscuus","混杂的","mixed","misceo"], ["commisceo","混合","mix together","misceo"],
    ["mundus","世界","world","mundus"], ["mundanus","世俗的","worldly","mundus"],
    ["munus","职责,礼","duty, gift","munus"], ["municipium","自治市","municipality","munus"], ["communis","共同的","common","munus"], ["communico","分享","share","munus"], ["communitas","共同体","community","munus"], ["immunis","免除的","exempt","munus"], ["remuneror","报酬","reward","munus"],
    ["murus","墙","wall","murus"], ["muralis","墙的","of a wall","murus"], ["immuro","围墙","wall in","murus"],
    ["muto","变","change","muto"], ["mutatio","变化","change","muto"], ["mutuus","相互的","mutual","muto"], ["commuto","交换","exchange","muto"], ["immutabilis","不变的","immutable","muto"], ["permuto","交换","exchange","muto"],
    ["necto","绑","bind","necto"], ["connecto","连接","connect","necto"], ["annecto","附加","attach","necto"], ["nexus","联结","bond","necto"],
    ["nihil","无","nothing","nihil"], ["nullus","没有的","none","nihil"], ["annihilo","消灭","annihilate","nihil"],
    ["noceo","害","harm","noceo"], ["nocens","有罪的","guilty","noceo"], ["innocens","无辜的","innocent","noceo"], ["noxius","有害的","harmful","noceo"], ["innocuus","无害的","harmless","noceo"], ["noxa","伤害","harm","noceo"],
    ["norma","规则,尺","rule","norma"], ["normalis","按规则的","normal","norma"], ["enormis","异常的","enormous","norma"], ["abnormis","异常的","abnormal","norma"],
    ["numerus","数","number","numerus"], ["numero","数","count","numerus"], ["enumero","列举","enumerate","numerus"], ["innumerabilis","无数的","innumerable","numerus"], ["numerosus","众多的","numerous","numerus"],
    ["nutrio","喂养","nourish","nutrio"], ["nutrix","奶妈","nurse","nutrio"], ["nutrimentum","营养","nourishment","nutrio"], ["nutritio","喂养","nutrition","nutrio"],
    ["opus","作品","work","opus"], ["opera","劳动","effort","opus"], ["operor","工作","work","opus"], ["operarius","工人","worker","opus"], ["cooperor","合作","cooperate","opus"], ["opificium","工艺","craft","opus"], ["opifex","工匠","craftsman","opus"],
    ["os","口","mouth","os"], ["oro","祈求,说","pray, speak","os"], ["oratio","演说","speech","os"], ["orator","演说家","orator","os"], ["oraculum","神谕","oracle","os"], ["adoro","崇拜","adore","os"], ["exoro","恳求","entreat","os"], ["osculum","吻","kiss","os"],
    ["orno","装饰","adorn","orno"], ["ornamentum","装饰","ornament","orno"], ["ornatus","华丽的","adorned","orno"], ["adorno","装饰","adorn","orno"],
    ["panis","面包","bread","panis"], ["panarium","面包篮","bread basket","panis"], ["companio","伙伴","companion","panis"],
    ["par","相等的","equal","par"], ["paritas","平等","equality","par"], ["compar","相等的","equal","par"], ["comparo","比较","compare","par"], ["dispar","不等的","unequal","par"], ["impar","奇数的","odd","par"],
    ["paro","准备","prepare","paro"], ["praeparo","预备","prepare","paro"], ["reparo","修理","repair","paro"], ["separo","分开","separate","paro"], ["apparatus","装备","apparatus","paro"], ["imperator","统帅","commander","paro"], ["impero","命令","command","paro"], ["imperium","权力,帝国","command, empire","paro"],
    ["passus","步","step","passus"], ["passim","到处","everywhere","passus"],
    ["pasco","喂,牧","feed","pasco"], ["pastor","牧人","shepherd","pasco"], ["pastio","放牧","pasture","pasco"], ["pabulum","饲料","fodder","pasco"], ["pastoralis","牧人的","pastoral","pasco"],
    ["poena","惩罚","punishment","poena"], ["punio","惩罚","punish","poena"], ["poenalis","刑罚的","penal","poena"], ["impunitas","免罚","impunity","poena"], ["paeniteo","后悔","repent","poena"], ["paenitentia","悔改","penitence","poena"],
    ["plaudo","拍手","clap","plaudo"], ["applaudo","鼓掌","applaud","plaudo"], ["plausus","掌声","applause","plaudo"], ["plausibilis","值得赞许的","plausible","plaudo"], ["explodo","喝倒彩,赶下台","drive off stage","plaudo"],
    ["precor","祈求","pray","precor"], ["preces","祈祷","prayers","precor"], ["deprecor","恳求免除","deprecate","precor"], ["imprecor","诅咒","curse","precor"], ["precarius","靠恳求的","precarious","precor"],
    ["privus","个别的","individual","privus"], ["privatus","私人的","private","privus"], ["privo","剥夺","deprive","privus"], ["privilegium","特权","privilege","privus"],
    ["pugno","打","fight","pugno"], ["pugna","战斗","fight","pugno"], ["pugnax","好斗的","pugnacious","pugno"], ["impugno","攻击","attack","pugno"], ["repugno","反抗","resist","pugno"], ["oppugno","围攻","assault","pugno"], ["pugil","拳手","boxer","pugno"],
    ["purus","纯的","pure","purus"], ["purgo","清洗","cleanse","purus"], ["purifico","净化","purify","purus"], ["puritas","纯洁","purity","purus"], ["expurgo","清除","purge","purus"],
    ["queror","抱怨","complain","queror"], ["querela","抱怨","complaint","queror"], ["querulus","爱抱怨的","querulous","queror"], ["conqueror","控诉","complain","queror"],
    ["radius","光线,辐条","ray, spoke","radius"], ["radio","发光","radiate","radius"], ["radiatus","有光线的","rayed","radius"], ["irradio","照射","irradiate","radius"],
    ["rapio","抓","seize","rapio"], ["rapidus","迅速的","rapid","rapio"], ["raptor","强盗","robber","rapio"], ["rapina","抢劫","robbery","rapio"], ["eripio","夺走","snatch away","rapio"], ["corripio","抓住","seize","rapio"], ["surripio","偷","steal","rapio"], ["raptus","劫持","abduction","rapio"],
    ["rota","轮","wheel","rota"], ["roto","旋转","rotate","rota"], ["rotundus","圆的","round","rota"], ["rotula","小轮","small wheel","rota"],
    ["rus","乡村","countryside","rus"], ["rusticus","乡村的","rustic","rus"], ["ruralis","乡村的","rural","rus"],
    ["sanus","健康的","healthy","sanus"], ["sano","治愈","heal","sanus"], ["sanitas","健康","health","sanus"], ["insanus","疯狂的","insane","sanus"], ["insania","疯狂","madness","sanus"],
    ["sapio","尝,明智","taste, be wise","sapio"], ["sapiens","智者","wise","sapio"], ["sapientia","智慧","wisdom","sapio"], ["sapor","味道","taste","sapio"], ["insipidus","无味的","insipid","sapio"],
    ["scindo","切","cut","scindo"], ["rescindo","废除","rescind","scindo"], ["discindo","撕开","tear apart","scindo"], ["scissus","撕裂的","split","scindo"],
    ["sculpo","雕","carve","sculpo"], ["sculptor","雕刻家","sculptor","sculpo"], ["sculptura","雕塑","sculpture","sculpo"],
    ["seco","切","cut","seco"], ["sectio","切割","section","seco"], ["sector","部门,切割者","cutter","seco"], ["insectum","昆虫","insect","seco"], ["disseco","解剖","dissect","seco"], ["segmentum","片段","segment","seco"], ["secta","派别","sect","seco"], ["securis","斧","axe","seco"],
    ["senex","老人","old man","senex"], ["senior","年长的","older","senex"], ["senatus","元老院","senate","senex"], ["senator","元老","senator","senex"], ["senectus","老年","old age","senex"], ["senilis","老年的","senile","senex"],
    ["severus","严厉的","strict","severus"], ["severitas","严厉","severity","severus"], ["persevero","坚持","persevere","severus"],
    ["solus","独自的","alone","solus"], ["solitudo","孤独","solitude","solus"], ["solitarius","孤独的","solitary","solus"], ["desolo","荒废","desolate","solus"], ["solum","仅","only","solus"],
    ["somnus","睡","sleep","somnus"], ["somnium","梦","dream","somnus"], ["insomnia","失眠","sleeplessness","somnus"], ["somnolentus","困倦的","sleepy","somnus"], ["somnifer","催眠的","sleep-bringing","somnus"],
    ["sors","命运,签","lot","sors"], ["sortior","抽签","draw lots","sors"], ["consors","分享者","partner","sors"], ["sortilegus","占卜者","fortune-teller","sors"],
    ["spargo","撒","scatter","spargo"], ["dispergo","分散","disperse","spargo"], ["aspergo","洒","sprinkle","spargo"], ["sparsus","分散的","scattered","spargo"],
    ["spondeo","承诺","pledge","spondeo"], ["sponsor","担保人","guarantor","spondeo"], ["sponsa","未婚妻","bride","spondeo"], ["sponsus","未婚夫","bridegroom","spondeo"], ["respondeo","回答","answer","spondeo"], ["responsum","回答","reply","spondeo"], ["correspondeo","对应","correspond","spondeo"],
    ["stimulus","刺,鞭策","goad","stimulus"], ["stimulo","激励","stimulate","stimulus"], ["instigo","煽动","instigate","stimulus"], ["distinguo","区分","distinguish","stimulus"], ["exstinguo","熄灭","extinguish","stimulus"], ["instinctus","本能","instinct","stimulus"],
    ["stringo","拉紧","bind tight","stringo"], ["strictus","紧的,严格的","strict","stringo"], ["restringo","限制","restrict","stringo"], ["constringo","束缚","constrain","stringo"], ["districtus","地区","district","stringo"], ["praestigiae","幻术","illusions","stringo"],
    ["stupeo","惊呆","be stunned","stupeo"], ["stupidus","迟钝的","stupid","stupeo"], ["stupor","麻木","stupor","stupeo"], ["stupendus","惊人的","stupendous","stupeo"], ["stupefacio","使惊呆","stupefy","stupeo"],
    ["assumo","采取","take up","sumo"], ["consumo","消耗","consume","sumo"], ["praesumo","预先假定","presume","sumo"], ["resumo","恢复","resume","sumo"], ["sumptus","开支","expense","sumo"], ["sumptuosus","奢华的","sumptuous","sumo"],
    ["taceo","沉默","be silent","taceo"], ["tacitus","沉默的","silent","taceo"], ["taciturnus","寡言的","taciturn","taceo"], ["reticeo","保持沉默","keep silent","taceo"],
    ["terreo","吓","frighten","terreo"], ["terror","恐怖","terror","terreo"], ["terribilis","可怕的","terrible","terreo"], ["deterreo","吓退","deter","terreo"], ["perterreo","吓坏","terrify","terreo"],
    ["texo","织","weave","texo"], ["textus","织物,文本","text","texo"], ["textilis","纺织的","woven","texo"], ["textura","织法","texture","texo"], ["contextus","连接,上下文","context","texo"], ["praetextus","借口","pretext","texo"], ["tela","织机,网","web","texo"],
    ["timeo","怕","fear","timeo"], ["timor","恐惧","fear","timeo"], ["timidus","胆小的","timid","timeo"], ["intimido","恐吓","intimidate","timeo"], ["timiditas","胆怯","timidity","timeo"],
    ["tingo","染","dye","tingo"], ["tinctura","染料","tincture","tingo"], ["tinctus","染色的","dyed","tingo"],
    ["tueor","看护","guard","tueor"], ["tutor","监护人","guardian","tueor"], ["tutela","保护","guardianship","tueor"], ["tutus","安全的","safe","tueor"], ["intueor","注视","gaze at","tueor"], ["intuitus","直觉","insight","tueor"],
    ["ultimus","最后的","last","ultimus"], ["ulterior","更远的","farther","ultimus"], ["ultra","超过","beyond","ultimus"],
    ["unda","波","wave","unda"], ["undo","起伏","undulate","unda"], ["abundo","丰富","abound","unda"], ["abundantia","丰富","abundance","unda"], ["redundo","溢出","overflow","unda"], ["inundo","淹没","flood","unda"],
    ["utor","用","use","utor"], ["usus","用法","use","utor"], ["utilis","有用的","useful","utor"], ["utilitas","效用","usefulness","utor"], ["inutilis","无用的","useless","utor"], ["abutor","滥用","abuse","utor"], ["usurpo","篡夺","usurp","utor"], ["utensilis","可用的","usable","utor"],
    ["vestis","衣","garment","vestis"], ["vestio","穿衣","clothe","vestis"], ["vestimentum","衣服","clothing","vestis"], ["investio","授予","invest","vestis"], ["vestibulum","门厅","entrance hall","vestis"],
    ["volo","飞","fly","volo2"], ["volatilis","飞的","flying","volo2"], ["volucris","鸟","bird","volo2"], ["advolo","飞来","fly to","volo2"],
    ["volvo","滚","roll","volvo"], ["revolvo","滚回","roll back","volvo"], ["evolvo","展开","unroll","volvo"], ["involvo","卷入","involve","volvo"], ["volumen","卷","scroll","volvo"], ["revolutio","旋转","revolution","volvo"], ["devolvo","滚下","roll down","volvo"],
    ["vulnus","伤","wound","vulnus"], ["vulnero","伤害","wound","vulnus"], ["vulnerabilis","易受伤的","vulnerable","vulnus"], ["invulnerabilis","无懈可击的","invulnerable","vulnus"],
    ["urbs","城","city","urbs"], ["urbanus","城市的","urban","urbs"], ["suburbium","郊区","suburb","urbs"], ["urbanitas","文雅","urbanity","urbs"],
    ["populus","人民","people","populus"], ["popularis","民众的","popular","populus"], ["publicus","公共的","public","populus"], ["publico","公布","publish","populus"], ["respublica","共和国","republic","populus"], ["populor","蹂躏","ravage","populus"],
    ["lex","法律","law","lex"], ["legalis","合法的","legal","lex"], ["legitimus","合法的","legitimate","lex"], ["legislator","立法者","lawgiver","lex"], ["privilegium","特权","privilege","lex"], ["collega","同事","colleague","lex"], ["legatus","使者","envoy","lex"],
    ["pax","和平","peace","pax"], ["paco","平定","pacify","pax"], ["pacificus","和平的","peaceful","pax"], ["pactum","协定","pact","pax"], ["paciscor","缔约","make a pact","pax"],
    ["hostis","敌人","enemy","hostis"], ["hostilis","敌对的","hostile","hostis"], ["hostilitas","敌意","hostility","hostis"],
    ["hospes","客,主","guest, host","hospes"], ["hospitium","款待","hospitality","hospes"], ["hospitalis","好客的","hospitable","hospes"], ["hospitale","客房","guest room","hospes"],
    ["omnis","全部的","all","omnis"], ["omnipotens","全能的","almighty","omnis"], ["omnino","完全","entirely","omnis"],
    ["multus","多的","many","multus"], ["multitudo","众多","multitude","multus"], ["multiplico","增加","multiply","multus"], ["multiplex","多重的","manifold","multus"],
    ["primus","第一","first","primus"], ["primarius","首要的","primary","primus"], ["princeps","首领","chief","primus"], ["principalis","主要的","principal","primus"], ["primitivus","最初的","primitive","primus"], ["primordium","起源","origin","primus"],
    ["medius","中间的","middle","medius"], ["medium","中间","middle","medius"], ["mediocris","平常的","mediocre","medius"], ["intermedius","中间的","intermediate","medius"], ["meridies","正午","midday","medius"], ["mediterraneus","内陆的","inland","medius"],
    ["longus","长的","long","longus"], ["longitudo","长度","length","longus"], ["prolongo","延长","prolong","longus"], ["longinquus","遥远的","distant","longus"], ["elongo","拉长","elongate","longus"],
    ["brevis","短的","short","brevis"], ["brevitas","简短","brevity","brevis"], ["abbrevio","缩短","abbreviate","brevis"], ["breviarium","摘要","summary","brevis"],
    ["altus","高的,深的","high, deep","altus"], ["altitudo","高度","height","altus"], ["exalto","提升","exalt","altus"], ["altare","祭坛","altar","altus"],
    ["latus","宽的","wide","latus2"], ["latitudo","宽度","width","latus2"], ["dilato","扩大","dilate","latus2"], ["lateralis","侧面的","lateral","latus2"], ["collateralis","并列的","collateral","latus2"],
    ["candidus","白的","white","candidus"], ["candor","洁白,坦率","whiteness, candour","candidus"], ["candidatus","候选人","candidate","candidus"], ["candela","蜡烛","candle","candidus"], ["incendium","火灾","fire","candidus"], ["incendo","点燃","set fire","candidus"],
    ["clarus","明亮的","clear","clarus"], ["claritas","清晰","clarity","clarus"], ["declaro","宣布","declare","clarus"], ["clarifico","阐明","clarify","clarus"],
    ["mollis","软的","soft","mollis"], ["mollio","软化","soften","mollis"], ["emollio","使柔软","soften","mollis"],
    ["fortuna","运气","fortune","fortuna"], ["fortunatus","幸运的","fortunate","fortuna"], ["fors","偶然","chance","fortuna"], ["forte","碰巧","by chance","fortuna"], ["fortuitus","偶然的","fortuitous","fortuna"],
    ["felix","幸福的","happy","felix"], ["felicitas","幸福","happiness","felix"], ["infelix","不幸的","unhappy","felix"], ["felicito","祝贺","congratulate","felix"],
    ["miser","悲惨的","wretched","miser"], ["miseria","苦难","misery","miser"], ["misereor","怜悯","pity","miser"], ["misericordia","怜悯","mercy","miser"], ["miserabilis","可怜的","miserable","miser"],
    ["carus","亲爱的,贵的","dear","caritas"], ["caritas","爱,昂贵","love, dearness","caritas"]
  );
})();
