/* =====================================================
   FUGA MYTHICA — CURSUS Spanish 🇪🇸 · batch 11 — topical vocabulary 3: adverbs & connectors, time & quantity, hobbies, sport, music, nationalities, animals, plants, house, office, abstract nouns
   ===================================================== */
(function () {
  const p = VOCAB.es;
  Object.assign(p.roots, {});
  p.words.push(
    ["no obstante", "尽管如此", "even so", "topic"],
    ["en consecuencia", "结果", "as a result", "topic"],
    ["asimismo", "而且", "in addition", "topic"],
    ["de lo contrario", "否则", "if not", "topic"],
    ["mientras tanto", "同时", "at the same time", "topic"],
    ["de antemano", "事先", "in advance", "topic"],
    ["inmediatamente", "立刻", "at once", "topic"],
    ["recientemente", "最近", "not long ago", "topic"],
    ["últimamente", "近来", "recently", "topic"],
    ["hoy en día", "如今", "these days", "topic"],
    ["antiguamente", "以前", "in the past", "topic"],
    ["actualmente", "目前", "now", "topic"],
    ["temporalmente", "暂时", "for a short time", "topic"],
    ["permanentemente", "永久地", "for ever", "topic"],
    ["rara vez", "难得", "rarely", "topic"],
    ["frecuentemente", "经常", "often", "topic"],
    ["constantemente", "不断地", "all the time", "topic"],
    ["diariamente", "每天", "every day", "topic"],
    ["semanalmente", "每周", "every week", "topic"],
    ["mensualmente", "每月", "every month", "topic"],
    ["anualmente", "每年", "every year", "topic"],
    ["dos veces", "两次", "two times", "topic"],
    ["una vez", "一次", "one time", "topic"],
    ["apenas", "几乎不", "barely", "topic"],
    ["más bien", "宁可,相当", "fairly", "topic"],
    ["extremadamente", "极其", "very", "topic"],
    ["ligeramente", "稍微", "a little", "topic"],
    ["enteramente", "完全", "completely", "topic"],
    ["en parte", "部分地", "not completely", "topic"],
    ["principalmente", "主要地", "mostly", "topic"],
    ["especialmente", "尤其", "particularly", "topic"],
    ["particularmente", "特别", "especially", "topic"],
    ["exactamente", "恰好", "precisely", "topic"],
    ["precisamente", "精确地", "exactly", "topic"],
    ["aparentemente", "显然", "it seems", "topic"],
    ["obviamente", "明显地", "clearly", "topic"],
    ["ciertamente", "当然", "surely", "topic"],
    ["probablemente", "可能", "likely", "topic"],
    ["posiblemente", "也许", "maybe", "topic"],
    ["desafortunadamente", "不幸地", "sadly", "topic"],
    ["afortunadamente", "幸运地", "luckily", "topic"],
    ["sorprendentemente", "令人惊讶地", "unexpectedly", "topic"],
    ["honestamente", "老实说", "truthfully", "topic"],
    ["básicamente", "基本上", "essentially", "topic"],
    ["específicamente", "具体地", "in particular", "topic"],
    ["a saber", "即", "that is", "topic"],
    ["en otras palabras", "换句话说", "that is to say", "topic"],
    ["por otro lado", "另一方面", "conversely", "topic"],
    ["en resumen", "简而言之", "briefly", "topic"],
    ["al menos", "至少", "minimum", "topic"],
    ["como máximo", "至多", "maximum", "topic"],
    ["en lugar de", "代替", "as an alternative", "topic"],
    ["de todos modos", "无论如何", "in any case", "topic"],
    ["mientras que", "然而", "while", "topic"],
    ["tan pronto como", "一…就", "immediately when", "topic"],
    ["por si acaso", "以防", "if it happens", "topic"],
    ["respecto a", "关于", "about", "topic"],
    ["a lo largo de", "贯穿", "during all of", "topic"],
    ["más allá de", "超过", "further than", "topic"],
    ["el alba", "黎明", "first light", "topic"],
    ["el crepúsculo", "黄昏", "evening twilight", "topic"],
    ["la quincena", "两周", "two weeks", "topic"],
    ["la era", "时代", "period", "topic"],
    ["la fecha límite", "期限", "time limit", "topic"],
    ["el retraso", "延迟", "lateness", "topic"],
    ["la víspera", "前夕", "day before", "topic"],
    ["el año bisiesto", "闰年", "366-day year", "topic"],
    ["el puñado", "一把", "small number", "topic"],
    ["el montón", "一堆", "heap", "topic"],
    ["el ramo", "一束", "group", "topic"],
    ["la rebanada", "一片", "thin piece", "topic"],
    ["la gota", "一滴", "small amount of liquid", "topic"],
    ["la miga", "面包屑", "tiny piece", "topic"],
    ["el trozo", "块", "piece", "topic"],
    ["la cucharada", "一勺", "spoon amount", "topic"],
    ["la pizca", "一撮", "tiny amount", "topic"],
    ["la capa", "层", "level", "topic"],
    ["la afición", "爱好", "pastime", "topic"],
    ["el ocio", "休闲", "free time", "topic"],
    ["el pasatiempo", "消遣", "hobby", "topic"],
    ["la jardinería", "园艺", "growing plants", "topic"],
    ["el dibujo", "素描", "sketch", "topic"],
    ["la cerámica", "陶艺", "clay work", "topic"],
    ["el punto", "编织", "wool craft", "topic"],
    ["la costura", "缝纫", "needlework", "topic"],
    ["la carpintería", "木工", "woodwork", "topic"],
    ["el coleccionismo", "收藏", "gathering items", "topic"],
    ["el coleccionista", "收藏家", "one who collects", "topic"],
    ["el rompecabezas", "拼图", "jigsaw", "topic"],
    ["el juego de mesa", "桌游", "table game", "topic"],
    ["las cartas", "扑克牌", "playing cards", "topic"],
    ["los dados", "骰子", "dice", "topic"],
    ["el videojuego", "电子游戏", "video game", "topic"],
    ["la consola", "游戏机", "games machine", "topic"],
    ["el karaoke", "卡拉OK", "karaoke", "topic"],
    ["el picnic", "野餐", "outdoor meal", "topic"],
    ["la barbacoa", "烧烤", "grill party", "topic"],
    ["la caña de pescar", "钓竿", "fishing pole", "topic"],
    ["los prismáticos", "双筒望远镜", "field glasses", "topic"],
    ["la raqueta", "球拍", "bat", "topic"],
    ["el balón", "球", "ball", "topic"],
    ["el árbitro", "裁判", "umpire", "topic"],
    ["el silbato", "哨子", "whistle", "topic"],
    ["la pista", "跑道", "running course", "topic"],
    ["el maratón", "马拉松", "long race", "topic"],
    ["el esprint", "短跑", "fast run", "topic"],
    ["la valla", "跨栏", "barrier", "topic"],
    ["la jabalina", "标枪", "throwing spear", "topic"],
    ["el boxeo", "拳击", "fist fighting", "topic"],
    ["la esgrima", "击剑", "sword sport", "topic"],
    ["el tiro con arco", "射箭", "bow sport", "topic"],
    ["el remo", "赛艇", "oar sport", "topic"],
    ["el surf", "冲浪", "wave riding", "topic"],
    ["el buceo", "潜水", "underwater sport", "topic"],
    ["la escalada", "攀岩", "rock sport", "topic"],
    ["el patinaje", "滑冰", "ice sport", "topic"],
    ["el monopatín", "滑板", "board", "topic"],
    ["el casco", "头盔", "head protection", "topic"],
    ["el trofeo", "奖杯", "prize cup", "topic"],
    ["el torneo", "锦标赛", "competition", "topic"],
    ["la semifinal", "半决赛", "match before final", "topic"],
    ["el penalti", "点球", "penalty kick", "topic"],
    ["el fuera de juego", "越位", "offside", "topic"],
    ["el córner", "角球", "corner kick", "topic"],
    ["el descanso", "中场休息", "break", "topic"],
    ["la prórroga", "加时赛", "added time", "topic"],
    ["la música clásica", "古典音乐", "classical", "topic"],
    ["el jazz", "爵士乐", "jazz", "topic"],
    ["el rock", "摇滚", "rock", "topic"],
    ["la música pop", "流行音乐", "pop", "topic"],
    ["la música folk", "民谣", "folk", "topic"],
    ["el rap", "说唱", "rap", "topic"],
    ["el acorde", "和弦", "chord", "topic"],
    ["la escala", "音阶", "scale", "topic"],
    ["el álbum", "专辑", "record", "topic"],
    ["el grupo", "乐队", "group", "topic"],
    ["el baterista", "鼓手", "drum player", "topic"],
    ["el guitarrista", "吉他手", "guitar player", "topic"],
    ["el pianista", "钢琴家", "piano player", "topic"],
    ["el violinista", "小提琴手", "violin player", "topic"],
    ["el compositor", "作曲家", "music writer", "topic"],
    ["el altavoz", "扬声器", "speaker", "topic"],
    ["los auriculares", "耳机", "earphones", "topic"],
    ["británico", "英国的", "from Britain", "topic"],
    ["irlandés", "爱尔兰的", "from Ireland", "topic"],
    ["escocés", "苏格兰的", "from Scotland", "topic"],
    ["holandés", "荷兰的", "from the Netherlands", "topic"],
    ["belga", "比利时的", "from Belgium", "topic"],
    ["suizo", "瑞士的", "from Switzerland", "topic"],
    ["austriaco", "奥地利的", "from Austria", "topic"],
    ["polaco", "波兰的", "from Poland", "topic"],
    ["checo", "捷克的", "from Czechia", "topic"],
    ["húngaro", "匈牙利的", "from Hungary", "topic"],
    ["sueco", "瑞典的", "from Sweden", "topic"],
    ["noruego", "挪威的", "from Norway", "topic"],
    ["danés", "丹麦的", "from Denmark", "topic"],
    ["finlandés", "芬兰的", "from Finland", "topic"],
    ["portugués", "葡萄牙的", "from Portugal", "topic"],
    ["turco", "土耳其的", "from Turkey", "topic"],
    ["egipcio", "埃及的", "from Egypt", "topic"],
    ["marroquí", "摩洛哥的", "from Morocco", "topic"],
    ["indio", "印度的", "from India", "topic"],
    ["coreano", "韩国的", "from Korea", "topic"],
    ["vietnamita", "越南的", "from Vietnam", "topic"],
    ["tailandés", "泰国的", "from Thailand", "topic"],
    ["australiano", "澳大利亚的", "from Australia", "topic"],
    ["canadiense", "加拿大的", "from Canada", "topic"],
    ["mexicano", "墨西哥的", "from Mexico", "topic"],
    ["brasileño", "巴西的", "from Brazil", "topic"],
    ["argentino", "阿根廷的", "from Argentina", "topic"],
    ["el escarabajo", "甲虫", "beetle", "topic"],
    ["la mariquita", "瓢虫", "ladybird", "topic"],
    ["el saltamontes", "蚱蜢", "grasshopper", "topic"],
    ["el grillo", "蟋蟀", "cricket", "topic"],
    ["la avispa", "黄蜂", "wasp", "topic"],
    ["la polilla", "飞蛾", "moth", "topic"],
    ["el caracol", "蜗牛", "snail", "topic"],
    ["la babosa", "鼻涕虫", "slug", "topic"],
    ["el gusano", "蠕虫", "worm", "topic"],
    ["el lagarto", "蜥蜴", "lizard", "topic"],
    ["el cocodrilo", "鳄鱼", "crocodile", "topic"],
    ["el sapo", "蟾蜍", "toad", "topic"],
    ["la foca", "海豹", "seal", "topic"],
    ["la morsa", "海象", "walrus", "topic"],
    ["el tiburón", "鲨鱼", "shark", "topic"],
    ["la medusa", "水母", "jellyfish", "topic"],
    ["la estrella de mar", "海星", "starfish", "topic"],
    ["el caballito de mar", "海马", "seahorse", "topic"],
    ["la langosta", "龙虾", "lobster", "topic"],
    ["el camarón", "虾", "shrimp", "topic"],
    ["el mejillón", "贻贝", "mussel", "topic"],
    ["el calamar", "鱿鱼", "squid", "topic"],
    ["la trucha", "鳟鱼", "trout", "topic"],
    ["el salmón", "三文鱼", "salmon", "topic"],
    ["el bacalao", "鳕鱼", "cod", "topic"],
    ["la sardina", "沙丁鱼", "sardine", "topic"],
    ["la anguila", "鳗鱼", "eel", "topic"],
    ["el loro", "鹦鹉", "parrot", "topic"],
    ["el pingüino", "企鹅", "penguin", "topic"],
    ["el avestruz", "鸵鸟", "ostrich", "topic"],
    ["la cigüeña", "鹳", "stork", "topic"],
    ["la garza", "鹭", "heron", "topic"],
    ["la gaviota", "海鸥", "seagull", "topic"],
    ["el cuervo", "乌鸦", "crow", "topic"],
    ["la urraca", "喜鹊", "magpie", "topic"],
    ["el pájaro carpintero", "啄木鸟", "woodpecker", "topic"],
    ["el petirrojo", "知更鸟", "robin", "topic"],
    ["la paloma", "鸽子", "pigeon", "topic"],
    ["el pavo", "火鸡", "turkey", "topic"],
    ["el murciélago", "蝙蝠", "bat", "topic"],
    ["el erizo", "刺猬", "hedgehog", "topic"],
    ["la ardilla", "松鼠", "squirrel", "topic"],
    ["el topo", "鼹鼠", "mole", "topic"],
    ["la rata", "大鼠", "rat", "topic"],
    ["el hámster", "仓鼠", "hamster", "topic"],
    ["la nutria", "水獭", "otter", "topic"],
    ["el castor", "海狸", "beaver", "topic"],
    ["el alce", "驼鹿", "moose", "topic"],
    ["el reno", "驯鹿", "reindeer", "topic"],
    ["el jabalí", "野猪", "boar", "topic"],
    ["el burro", "驴", "donkey", "topic"],
    ["la mula", "骡子", "mule", "topic"],
    ["el poni", "小马", "pony", "topic"],
    ["el ternero", "小牛", "calf", "topic"],
    ["el gatito", "小猫", "kitten", "topic"],
    ["el cachorro", "小狗", "puppy", "topic"],
    ["la jirafa", "长颈鹿", "giraffe", "topic"],
    ["la cebra", "斑马", "zebra", "topic"],
    ["el rinoceronte", "犀牛", "rhino", "topic"],
    ["el leopardo", "豹", "leopard", "topic"],
    ["el guepardo", "猎豹", "cheetah", "topic"],
    ["el gorila", "大猩猩", "gorilla", "topic"],
    ["el canguro", "袋鼠", "kangaroo", "topic"],
    ["el koala", "考拉", "koala", "topic"],
    ["el panda", "熊猫", "panda", "topic"],
    ["el oso polar", "北极熊", "polar bear", "topic"],
    ["la ballena", "鲸", "whale", "topic"],
    ["el delfín", "海豚", "dolphin", "topic"],
    ["el pelaje", "毛皮", "fur", "topic"],
    ["la garra", "爪子", "claw", "topic"],
    ["la pata", "爪", "paw", "topic"],
    ["el pico", "喙", "beak", "topic"],
    ["la pluma", "羽毛", "feather", "topic"],
    ["el ala", "翅膀", "wing", "topic"],
    ["la cola", "尾巴", "tail", "topic"],
    ["el cuerno", "角", "horn", "topic"],
    ["la pezuña", "蹄", "hoof", "topic"],
    ["la crin", "鬃毛", "mane", "topic"],
    ["la concha", "壳", "shell", "topic"],
    ["la aleta", "鳍", "fin", "topic"],
    ["el nido", "巢", "nest", "topic"],
    ["la guarida", "兽穴", "den", "topic"],
    ["la colmena", "蜂巢", "hive", "topic"],
    ["la manada", "兽群", "herd", "topic"],
    ["el rebaño", "羊群", "flock", "topic"],
    ["el tulipán", "郁金香", "tulip", "topic"],
    ["la margarita", "雏菊", "daisy", "topic"],
    ["el lirio", "百合", "lily", "topic"],
    ["la orquídea", "兰花", "orchid", "topic"],
    ["la amapola", "罂粟花", "poppy", "topic"],
    ["la lavanda", "薰衣草", "lavender", "topic"],
    ["la hiedra", "常春藤", "ivy", "topic"],
    ["el musgo", "苔藓", "moss", "topic"],
    ["el helecho", "蕨类", "fern", "topic"],
    ["el cactus", "仙人掌", "cactus", "topic"],
    ["el arbusto", "灌木", "bush", "topic"],
    ["el seto", "树篱", "hedge", "topic"],
    ["el césped", "草坪", "lawn", "topic"],
    ["la mala hierba", "杂草", "weed", "topic"],
    ["el pétalo", "花瓣", "petal", "topic"],
    ["la espina", "刺", "thorn", "topic"],
    ["la corteza", "树皮", "bark", "topic"],
    ["la ramita", "细枝", "twig", "topic"],
    ["el abedul", "桦树", "birch", "topic"],
    ["el haya", "山毛榉", "beech", "topic"],
    ["el arce", "枫树", "maple", "topic"],
    ["el sauce", "柳树", "willow", "topic"],
    ["el álamo", "杨树", "poplar", "topic"],
    ["el abeto", "冷杉", "fir", "topic"],
    ["el ciprés", "柏树", "cypress", "topic"],
    ["la palmera", "棕榈树", "palm", "topic"],
    ["la castaña", "栗子", "chestnut", "topic"],
    ["la nuez", "核桃", "walnut", "topic"],
    ["la almendra", "杏仁", "almond", "topic"],
    ["la avellana", "榛子", "hazelnut", "topic"],
    ["el albaricoque", "杏", "apricot", "topic"],
    ["la ciruela", "李子", "plum", "topic"],
    ["el higo", "无花果", "fig", "topic"],
    ["el melón", "甜瓜", "melon", "topic"],
    ["la piña", "菠萝", "pineapple", "topic"],
    ["el coco", "椰子", "coconut", "topic"],
    ["la frambuesa", "覆盆子", "raspberry", "topic"],
    ["el arándano", "蓝莓", "blueberry", "topic"],
    ["el pomelo", "柚子", "grapefruit", "topic"],
    ["la calabaza", "南瓜", "pumpkin", "topic"],
    ["el pepino", "黄瓜", "cucumber", "topic"],
    ["el pimiento", "甜椒", "pepper", "topic"],
    ["el calabacín", "西葫芦", "courgette", "topic"],
    ["las espinacas", "菠菜", "spinach", "topic"],
    ["la col", "卷心菜", "cabbage", "topic"],
    ["la coliflor", "花椰菜", "cauliflower", "topic"],
    ["el brócoli", "西兰花", "broccoli", "topic"],
    ["el apio", "芹菜", "celery", "topic"],
    ["el puerro", "韭葱", "leek", "topic"],
    ["el guisante", "豌豆", "pea", "topic"],
    ["la judía", "豆", "bean", "topic"],
    ["la lenteja", "扁豆", "lentil", "topic"],
    ["el garbanzo", "鹰嘴豆", "chickpea", "topic"],
    ["la avena", "燕麦", "oats", "topic"],
    ["la cebada", "大麦", "barley", "topic"],
    ["el centeno", "黑麦", "rye", "topic"],
    ["la chimenea", "烟囱", "chimney", "topic"],
    ["el canalón", "排水沟", "gutter", "topic"],
    ["el ático", "阁楼", "attic", "topic"],
    ["el porche", "门廊", "porch", "topic"],
    ["la verja", "大门", "gate", "topic"],
    ["el cobertizo", "棚屋", "shed", "topic"],
    ["el timbre", "门铃", "doorbell", "topic"],
    ["la bisagra", "铰链", "hinge", "topic"],
    ["la persiana", "百叶窗", "shutter", "topic"],
    ["el papel pintado", "壁纸", "wallpaper", "topic"],
    ["la tabla del suelo", "地板条", "floorboard", "topic"],
    ["el radiador", "暖气片", "radiator", "topic"],
    ["la caldera", "锅炉", "boiler", "topic"],
    ["la tubería", "管道", "pipe", "topic"],
    ["el enchufe", "插头", "plug", "topic"],
    ["la toma de corriente", "插座", "socket", "topic"],
    ["el interruptor", "开关", "switch", "topic"],
    ["la bombilla", "灯泡", "bulb", "topic"],
    ["el fusible", "保险丝", "fuse", "topic"],
    ["el cable", "电缆", "cable", "topic"],
    ["el contador", "电表", "meter", "topic"],
    ["el casero", "房东", "landlord", "topic"],
    ["el inquilino", "房客", "tenant", "topic"],
    ["el contrato de alquiler", "租约", "lease", "topic"],
    ["el cajón", "抽屉", "drawer", "topic"],
    ["el archivador", "文件柜", "filing cabinet", "topic"],
    ["la grapadora", "订书机", "stapler", "topic"],
    ["el clip", "回形针", "paper clip", "topic"],
    ["la nota adhesiva", "便利贴", "sticky note", "topic"],
    ["el rotulador fluorescente", "荧光笔", "highlighter", "topic"],
    ["la fotocopiadora", "复印机", "photocopier", "topic"],
    ["la trituradora", "碎纸机", "shredder", "topic"],
    ["la pizarra blanca", "白板", "whiteboard", "topic"],
    ["el proyector", "投影仪", "projector", "topic"],
    ["el calendario", "日历", "calendar", "topic"],
    ["la tarjeta de identificación", "工牌", "badge", "topic"],
    ["el becario", "实习生", "intern", "topic"],
    ["el recepcionista", "前台", "receptionist", "topic"],
    ["la crueldad", "残忍", "cruelty", "topic"],
    ["la honestidad", "诚实", "honesty", "topic"],
    ["la lealtad", "忠诚", "loyalty", "topic"],
    ["la paciencia", "耐心", "patience", "topic"],
    ["la codicia", "贪婪", "greed", "topic"],
    ["la pereza", "懒惰", "laziness", "topic"],
    ["la terquedad", "固执", "stubbornness", "topic"],
    ["la creatividad", "创造力", "creativity", "topic"],
    ["la estupidez", "愚蠢", "stupidity", "topic"],
    ["la locura", "疯狂", "madness", "topic"],
    ["la fealdad", "丑", "ugliness", "topic"],
    ["la debilidad", "弱点", "weakness", "topic"],
    ["la lentitud", "缓慢", "slowness", "topic"],
    ["el silencio", "寂静", "silence", "topic"],
    ["el ruido", "噪音", "noise", "topic"],
    ["la oscuridad", "黑暗", "darkness", "topic"],
    ["el brillo", "明亮", "brightness", "topic"],
    ["la frialdad", "冷淡", "coldness", "topic"],
    ["la limpieza", "清洁", "cleanliness", "topic"],
    ["la suciedad", "污垢", "dirt", "topic"],
    ["la suerte", "运气", "luck", "topic"],
    ["la desgracia", "不幸", "misfortune", "topic"],
    ["el fracaso", "失败", "failure", "topic"],
    ["la rutina", "例行公事", "routine", "topic"],
    ["la oportunidad", "机会", "opportunity", "topic"],
    ["el riesgo", "风险", "risk", "topic"],
    ["la ventaja", "优势", "advantage", "topic"],
    ["el propósito", "目的", "purpose", "topic"],
    ["la razón", "原因", "reason", "topic"],
    ["la excusa", "借口", "excuse", "topic"],
    ["el chiste", "笑话", "joke", "topic"],
    ["la mentira", "谎言", "lie", "topic"],
    ["el rumor", "谣言", "rumour", "topic"],
    ["la discusión", "争吵", "quarrel", "topic"],
    ["el favor", "恩惠", "favour", "topic"],
    ["la pesadilla", "噩梦", "nightmare", "topic"],
    ["la infancia", "童年", "childhood", "topic"],
    ["la adolescencia", "青春期", "adolescence", "topic"],
    ["la edad adulta", "成年", "adulthood", "topic"]
  );
})();
