/* =====================================================
   FUGA MYTHICA — CURSUS French 🇫🇷 · batch 3 (band 2000–3000)
   Academic / news vocabulary by Latin root (third group), plus Greek roots as used in French.
   ===================================================== */
(function () {
  const p = VOCAB.fr;
  Object.assign(p.roots, {
    agr: ["agr- / champ", "田", "field"], ambul: ["ambul- / all-", "走", "walk"], apt: ["apt- / ept-", "合适", "fit"], cert: ["cert-", "确定", "sure"],
    cult: ["cult- / col-", "耕,培养", "cultivate"], dur: ["dur-", "硬,持久", "hard, last"], div: ["div- / divis-", "分", "divide"], ess: ["ess- / ent-", "存在", "be"],
    fabr: ["fabr- / forg-", "制作", "make"], fat: ["fa- / fab-", "说", "speak"], fend: ["fend- / fens-", "打击", "strike"], flor: ["flor- / fleur", "花", "flower"],
    gest: ["gest- / gér-", "携带,做", "carry, do"], glob: ["glob-", "球", "ball"], grat: ["grat- / gré", "感谢,愉快", "thankful"], hum: ["hum-", "土,人", "earth, human"],
    imag: ["imag- / imit-", "像", "image"], integr: ["intégr- / entier", "完整", "whole"], jur: ["jur- / jus-", "法,誓", "law, swear"], lig: ["lig- / li-", "绑", "bind"],
    lingu: ["lingu- / langu-", "舌,语", "tongue"], loqu: ["loqu- / locut-", "说", "speak"], medic: ["médic- / méd-", "治", "heal"], mens: ["mens- / mesur-", "量", "measure"],
    merc: ["merc- / march-", "买卖", "trade"], mir: ["mir-", "惊奇", "wonder"], misc: ["misc- / mêl-", "混", "mix"], mun: ["mun-", "职责,公共", "duty, public"],
    mut: ["mut-", "变", "change"], noc: ["noc- / nuis-", "害", "harm"], norm: ["norm-", "规则", "rule"], numer: ["numér- / nombr-", "数", "number"],
    nutr: ["nutr- / nourr-", "喂养", "nourish"], oper: ["opér- / œuvr-", "工作", "work"], or: ["or- / orat-", "口,说", "mouth, speak"], par: ["par- / pair", "相等", "equal"],
    part: ["part-", "部分", "part"], pass: ["pass-", "步", "step"], pen: ["pén- / pun-", "罚", "punish"], plaud: ["plaud- / plos-", "拍手", "clap"],
    priv: ["priv-", "私,夺", "private, deprive"], prud: ["prud-", "远见", "foresight"], pur: ["pur-", "净", "pure"], radi: ["radi- / ray-", "光线", "ray"],
    rap: ["rap- / rav-", "抓", "seize"], rot: ["rot- / rou-", "轮", "wheel"], rur: ["rur- / rust-", "乡村", "country"], san: ["san-", "健康", "healthy"],
    sec: ["sec- / sect-", "切", "cut"], sen: ["sén- / sen-", "老", "old"], sol2: ["sol- / seul", "独", "alone"], somn: ["somn- / somm-", "睡", "sleep"],
    spond: ["spond- / spons-", "承诺", "pledge"], string: ["string- / strict-", "拉紧", "bind tight"], sum: ["sum- / sompt-", "拿", "take"], tex: ["tex- / tiss-", "织", "weave"],
    tim: ["tim-", "怕", "fear"], tox: ["tox-", "毒", "poison"], ult: ["ult-", "最远", "last"], und: ["ond-", "波", "wave"],
    ut: ["ut- / us-", "用", "use"], vest: ["vest- / vêt-", "衣", "clothe"], volv: ["volv- / volu-", "滚", "roll"], vulner: ["vulnér- / bless-", "伤", "wound"],
    /* Greek in French */ log: ["-logie / log-", "学,言", "study, word"], graph: ["graph- / -gramme", "写", "write"], phon: ["phon-", "声", "sound"], bio: ["bio-", "生命", "life"],
    geo: ["géo-", "地", "earth"], chron: ["chron-", "时间", "time"], path: ["path-", "感受,病", "feeling, disease"], tele: ["télé-", "远", "far"],
    micro: ["micro-", "小", "small"], scop: ["-scope", "看", "look"], meter: ["-mètre", "量", "measure"], crat: ["-cratie", "统治", "rule"],
    anthrop: ["anthrop-", "人", "human"], psych: ["psych-", "心灵", "mind"], phil: ["phil-", "爱", "love"], theo: ["théo-", "神", "god"],
    hydr: ["hydr-", "水", "water"], cycl: ["cycl-", "圈", "circle"], phob: ["-phobie", "怕", "fear"], onym: ["-onyme", "名", "name"],
    syn: ["syn- / sym-", "一起", "together"], anti: ["anti-", "反", "against"], hyper: ["hyper-", "过度", "over"], mono: ["mono-", "单", "one"],
    poly: ["poly-", "多", "many"], neo: ["néo-", "新", "new"], dia: ["dia-", "穿过", "through"], a: ["a- / an-", "无", "without"],
  });
  p.words.push(
    ["l'agriculture","农业","agriculture","agr"], ["l'agriculteur","农民","farmer","agr"], ["agricole","农业的","agricultural","agr"], ["le pèlerin","朝圣者","pilgrim","agr"],
    ["l'ambulance","救护车","ambulance","ambul"], ["ambulant","流动的","itinerant","ambul"], ["le préambule","序言","preamble","ambul"], ["aller","去","go","ambul"], ["l'allée","小路","path","ambul"],
    ["apte","适合的","fit","apt"], ["adapter","适应","adapt","apt"], ["l'aptitude","天资","aptitude","apt"], ["inepte","无能的","inept","apt"], ["l'adaptation","适应","adaptation","apt"],
    ["certain","确定的","certain","cert"], ["certifier","证明","certify","cert"], ["le certificat","证书","certificate","cert"], ["certes","当然","certainly","cert"], ["la certitude","确信","certainty","cert"], ["le concert","音乐会","concert","cert"],
    ["la culture","文化","culture","cult"], ["cultiver","培养","cultivate","cult"], ["la colonie","殖民地","colony","cult"], ["le culte","崇拜","cult","cult"], ["cultivé","有教养的","cultured","cult"],
    ["durable","持久的","durable","dur"], ["durer","持续","last","dur"], ["la durée","时长","duration","dur"], ["endurer","忍受","endure","dur"], ["dur","硬的","hard","dur"], ["durant","在…期间","during","dur"],
    ["diviser","分","divide","div"], ["la division","分割","division","div"], ["l'individu","个人","individual","div"], ["le dividende","红利","dividend","div"], ["la devise","格言,货币","motto, currency","div"],
    ["l'essence","本质,汽油","essence, petrol","ess"], ["essentiel","必要的","essential","ess"], ["l'entité","实体","entity","ess"], ["présent","在场的","present","ess"], ["absent","缺席的","absent","ess"], ["l'intérêt","兴趣,利息","interest","ess"], ["l'être","存在","being","ess"],
    ["la fabrique","工厂","factory","fabr"], ["fabriquer","制造","make","fabr"], ["la fabrication","制造","manufacture","fabr"], ["forger","锻造","forge","fabr"], ["le forgeron","铁匠","blacksmith","fabr"],
    ["la fable","寓言","fable","fat"], ["fabuleux","传奇的","fabulous","fat"], ["l'enfant","孩子","child","fat"], ["la préface","前言","preface","fat"], ["avouer","承认","confess","fat"], ["ineffable","难以言喻的","ineffable","fat"], ["la renommée","名声","fame","fat"],
    ["défendre","保卫,禁止","defend, forbid","fend"], ["la défense","防御","defence","fend"], ["offenser","冒犯","offend","fend"], ["l'offense","冒犯","offence","fend"], ["offensif","进攻的","offensive","fend"],
    ["la fleur","花","flower","flor"], ["fleurir","开花","bloom","flor"], ["le fleuriste","花商","florist","flor"], ["florissant","繁荣的","flourishing","flor"], ["la flore","植物群","flora","flor"], ["la farine","面粉","flour","flor"],
    ["le geste","手势","gesture","gest"], ["digérer","消化","digest","gest"], ["suggérer","建议","suggest","gest"], ["gérer","管理","manage","gest"], ["le gérant","经理","manager","gest"], ["le registre","登记簿","register","gest"], ["exagérer","夸张","exaggerate","gest"], ["la gestion","管理","management","gest"],
    ["le globe","地球仪","globe","glob"], ["global","全球的","global","glob"], ["le globule","小球","globule","glob"], ["englober","包括","encompass","glob"],
    ["gratuit","免费的","free","grat"], ["la gratitude","感激","gratitude","grat"], ["gracieux","优雅的","graceful","grat"], ["le gré","意愿","will","grat"], ["agréable","愉快的","pleasant","grat"], ["agréer","同意","agree","grat"], ["féliciter","祝贺","congratulate","grat"], ["la grâce","优雅,恩典","grace","grat"],
    ["humain","人的","human","hum"], ["l'humanité","人类","humanity","hum"], ["humble","谦逊的","humble","hum"], ["l'humilité","谦卑","humility","hum"], ["humilier","羞辱","humiliate","hum"], ["exhumer","挖出","exhume","hum"], ["posthume","死后的","posthumous","hum"],
    ["l'image","图像","image","imag"], ["imaginer","想象","imagine","imag"], ["imiter","模仿","imitate","imag"], ["l'imagination","想象力","imagination","imag"], ["l'imitation","模仿","imitation","imag"],
    ["entier","整个的","whole","integr"], ["l'intégrité","诚信","integrity","integr"], ["intégrer","整合","integrate","integr"], ["l'intégration","整合","integration","integr"], ["intègre","正直的","honest","integr"],
    ["le jury","陪审团","jury","jur"], ["jurer","发誓","swear","jur"], ["le juriste","法学家","jurist","jur"], ["la juridiction","管辖权","jurisdiction","jur"], ["l'injure","侮辱","insult","jur"], ["le juré","陪审员","juror","jur"], ["conjurer","恳求,避开","beseech, ward off","jur"],
    ["lier","绑","bind","lig"], ["le lien","联系","link","lig"], ["obliger","迫使","oblige","lig"], ["la religion","宗教","religion","lig"], ["l'allié","盟友","ally","lig"], ["la ligue","联盟","league","lig"], ["l'obligation","义务","obligation","lig"], ["relier","连接","connect","lig"],
    ["la langue","舌,语言","tongue, language","lingu"], ["le langage","语言","language","lingu"], ["le linguiste","语言学家","linguist","lingu"], ["bilingue","双语的","bilingual","lingu"], ["la linguistique","语言学","linguistics","lingu"],
    ["éloquent","雄辩的","eloquent","loqu"], ["l'éloquence","口才","eloquence","loqu"], ["le colloque","研讨会","colloquium","loqu"], ["le soliloque","独白","soliloquy","loqu"], ["loquace","健谈的","talkative","loqu"], ["la locution","短语","phrase","loqu"],
    ["la médecine","医学","medicine","medic"], ["le médecin","医生","doctor","medic"], ["médical","医学的","medical","medic"], ["le remède","补救","remedy","medic"], ["le médicament","药物","medication","medic"],
    ["mesurer","测量","measure","mens"], ["la mesure","测量,措施","measure","mens"], ["la dimension","维度","dimension","mens"], ["immense","巨大的","immense","mens"], ["démesuré","过度的","excessive","mens"],
    ["le marchand","商人","merchant","merc"], ["le commerce","商业","commerce","merc"], ["le marché","市场","market","merc"], ["la marchandise","商品","merchandise","merc"], ["commercial","商业的","commercial","merc"], ["merci","谢谢","thank you","merc"], ["le mercenaire","雇佣兵","mercenary","merc"],
    ["le miracle","奇迹","miracle","mir"], ["admirer","钦佩","admire","mir"], ["le miroir","镜子","mirror","mir"], ["le mirage","海市蜃楼","mirage","mir"], ["la merveille","奇迹","marvel","mir"], ["admirable","令人钦佩的","admirable","mir"], ["se mirer","照镜子","look at oneself","mir"],
    ["mélanger","混合","mix","misc"], ["le mélange","混合物","mixture","misc"], ["mêler","混杂","mingle","misc"], ["la mêlée","混战","melee","misc"], ["se mêler de","插手","meddle","misc"],
    ["municipal","市政的","municipal","mun"], ["la communauté","社区","community","mun"], ["communiquer","交流","communicate","mun"], ["immunisé","免疫的","immune","mun"], ["commun","共同的","common","mun"], ["la commune","市镇","municipality","mun"], ["la communication","交流","communication","mun"],
    ["muter","调动,突变","transfer, mutate","mut"], ["la mutation","突变","mutation","mut"], ["mutuel","相互的","mutual","mut"], ["immuable","不变的","immutable","mut"], ["commuer","减刑","commute","mut"],
    ["innocent","无辜的","innocent","noc"], ["nocif","有害的","harmful","noc"], ["nuire","伤害","harm","noc"], ["nuisible","有害的","harmful","noc"], ["la nuisance","危害","nuisance","noc"], ["l'innocence","清白","innocence","noc"],
    ["normal","正常的","normal","norm"], ["énorme","巨大的","enormous","norm"], ["anormal","异常的","abnormal","norm"], ["la norme","标准","norm","norm"], ["normalement","通常","normally","norm"],
    ["le nombre","数","number","numer"], ["nombreux","众多的","numerous","numer"], ["énumérer","列举","enumerate","numer"], ["le numéro","号码","number","numer"], ["innombrable","无数的","innumerable","numer"], ["dénombrer","清点","count","numer"],
    ["la nutrition","营养","nutrition","nutr"], ["nourrir","喂养","feed","nutr"], ["la nourriture","食物","food","nutr"], ["la nourrice","奶妈","nurse","nutr"], ["nutritif","有营养的","nutritious","nutr"],
    ["opérer","操作,手术","operate","oper"], ["coopérer","合作","cooperate","oper"], ["l'opéra","歌剧","opera","oper"], ["l'œuvre","作品","work","oper"], ["l'opération","操作,手术","operation","oper"], ["l'ouvrier","工人","worker","oper"], ["l'ouvrage","著作","work","oper"], ["la manœuvre","操作","manoeuvre","oper"],
    ["oral","口头的","oral","or"], ["l'orateur","演说家","orator","or"], ["l'oracle","神谕","oracle","or"], ["adorer","崇拜,喜爱","adore","or"], ["inexorable","不可阻挡的","inexorable","or"], ["l'oraison","祷文","prayer","or"],
    ["pair","偶数的","even","par"], ["la parité","平等","parity","par"], ["comparer","比较","compare","par"], ["la comparaison","比较","comparison","par"], ["pareil","相似的","similar","par"], ["la paire","一对","pair","par"], ["la disparité","差异","disparity","par"],
    ["la partie","部分","part","part"], ["la particule","粒子","particle","part"], ["partiel","部分的","partial","part"], ["particulier","特别的","particular","part"], ["partager","分享","share","part"], ["le partage","分享","sharing","part"], ["partir","离开","leave","part"], ["le parti","政党","party","part"], ["répartir","分配","distribute","part"],
    ["le passage","通道","passage","pass"], ["le passager","乘客","passenger","pass"], ["surpasser","超越","surpass","pass"], ["le pas","步","step","pass"], ["l'impasse","僵局","dead end","pass"], ["dépasser","超过","exceed","pass"], ["le passé","过去","past","pass"],
    ["la peine","痛苦,刑罚","pain, penalty","pen"], ["pénal","刑事的","penal","pen"], ["punir","惩罚","punish","pen"], ["la punition","惩罚","punishment","pen"], ["l'impunité","免罚","impunity","pen"], ["se repentir","悔改","repent","pen"], ["pénible","痛苦的","painful","pen"],
    ["applaudir","鼓掌","applaud","plaud"], ["plausible","貌似合理的","plausible","plaud"], ["exploser","爆炸","explode","plaud"], ["l'explosion","爆炸","explosion","plaud"],
    ["privé","私人的","private","priv"], ["priver","剥夺","deprive","priv"], ["la privation","剥夺","deprivation","priv"], ["le privilège","特权","privilege","priv"], ["privatiser","私有化","privatize","priv"],
    ["prudent","谨慎的","prudent","prud"], ["la prudence","谨慎","prudence","prud"], ["imprudent","轻率的","imprudent","prud"], ["la jurisprudence","判例法","case law","prud"],
    ["pur","纯的","pure","pur"], ["purifier","净化","purify","pur"], ["la pureté","纯洁","purity","pur"], ["épurer","净化","purify","pur"], ["la purge","清洗","purge","pur"],
    ["le rayon","光线,货架","ray, shelf","radi"], ["rayonner","辐射","radiate","radi"], ["le radis","萝卜","radish","radi"], ["la radio","收音机","radio","radi"], ["radieux","光芒四射的","radiant","radi"], ["irradier","照射","irradiate","radi"],
    ["rapide","快速的","rapid","rap"], ["la rapidité","速度","speed","rap"], ["ravir","使狂喜,夺走","delight, snatch","rap"], ["ravissant","迷人的","ravishing","rap"], ["le rapt","绑架","abduction","rap"],
    ["la roue","轮子","wheel","rot"], ["rouler","滚动","roll","rot"], ["la rotation","旋转","rotation","rot"], ["le rouleau","卷","roll","rot"], ["contrôler","控制","control","rot"], ["le contrôle","控制","control","rot"], ["enrôler","招募","enrol","rot"], ["le rond","圆","circle","rot"],
    ["rural","乡村的","rural","rur"], ["rustique","乡土的","rustic","rur"],
    ["sain","健康的","healthy","san"], ["la santé","健康","health","san"], ["sanitaire","卫生的","sanitary","san"], ["insensé","疯狂的","insane","san"], ["assainir","净化","clean up","san"],
    ["la section","部分","section","sec"], ["le secteur","部门","sector","sec"], ["l'insecte","昆虫","insect","sec"], ["disséquer","解剖","dissect","sec"], ["le segment","段","segment","sec"], ["la secte","教派","sect","sec"],
    ["le sénat","参议院","senate","sen"], ["le sénateur","参议员","senator","sen"], ["sénile","衰老的","senile","sen"], ["le seigneur","领主","lord","sen"], ["le sire","陛下","sire","sen"],
    ["seul","独自的","alone","sol2"], ["la solitude","孤独","solitude","sol2"], ["solitaire","孤独的","solitary","sol2"], ["désolé","抱歉的","sorry","sol2"], ["isoler","隔离","isolate","sol2"], ["le solo","独奏","solo","sol2"],
    ["le sommeil","睡眠","sleep","somn"], ["l'insomnie","失眠","insomnia","somn"], ["somnoler","打盹","doze","somn"], ["le somnambule","梦游者","sleepwalker","somn"], ["le somnifère","安眠药","sleeping pill","somn"],
    ["le sponsor","赞助者","sponsor","spond"], ["répondre","回答","answer","spond"], ["la réponse","回答","answer","spond"], ["correspondre","符合,通信","correspond","spond"], ["l'époux","丈夫","husband","spond"], ["l'épouse","妻子","wife","spond"], ["épouser","娶,嫁","marry","spond"], ["responsable","负责的","responsible","spond"],
    ["strict","严格的","strict","string"], ["restreindre","限制","restrict","string"], ["la restriction","限制","restriction","string"], ["le district","地区","district","string"], ["étreindre","拥抱","embrace","string"], ["contraindre","强迫","constrain","string"], ["la contrainte","约束","constraint","string"], ["le prestige","威望","prestige","string"],
    ["assumer","承担","assume","sum"], ["consommer","消费","consume","sum"], ["la consommation","消费","consumption","sum"], ["présumer","推测","presume","sum"], ["résumer","总结","summarize","sum"], ["le résumé","摘要","summary","sum"], ["somptueux","奢华的","sumptuous","sum"],
    ["le texte","文本","text","tex"], ["le textile","纺织品","textile","tex"], ["la texture","质地","texture","tex"], ["le contexte","语境","context","tex"], ["le prétexte","借口","pretext","tex"], ["le tissu","织物","fabric","tex"], ["tisser","织","weave","tex"],
    ["timide","胆小的","timid","tim"], ["intimider","恐吓","intimidate","tim"], ["la timidité","胆怯","shyness","tim"],
    ["toxique","有毒的","toxic","tox"], ["la toxine","毒素","toxin","tox"], ["intoxiquer","使中毒","poison","tox"], ["l'intoxication","中毒","poisoning","tox"],
    ["ultime","最终的","ultimate","ult"], ["l'ultimatum","最后通牒","ultimatum","ult"], ["ultérieur","之后的","later","ult"], ["outre","除了","beyond","ult"],
    ["l'onde","波","wave","und"], ["onduler","起伏","undulate","und"], ["abondant","丰富的","abundant","und"], ["l'abondance","丰富","abundance","und"], ["inonder","淹没","flood","und"], ["l'inondation","洪水","flood","und"], ["redondant","多余的","redundant","und"],
    ["utile","有用的","useful","ut"], ["l'utilité","效用","utility","ut"], ["utiliser","使用","use","ut"], ["l'ustensile","器具","utensil","ut"], ["l'usage","用法","usage","ut"], ["abuser","滥用","abuse","ut"], ["l'usine","工厂","factory","ut"], ["usé","用旧的","worn","ut"],
    ["le vêtement","衣服","garment","vest"], ["vêtir","穿衣","clothe","vest"], ["investir","投资","invest","vest"], ["l'investissement","投资","investment","vest"], ["la veste","夹克","jacket","vest"], ["revêtir","披上","put on","vest"],
    ["évoluer","进化","evolve","volv"], ["l'évolution","进化","evolution","volv"], ["la révolution","革命","revolution","volv"], ["le volume","卷,体积","volume","volv"], ["envelopper","包裹","wrap","volv"], ["l'enveloppe","信封","envelope","volv"], ["développer","发展","develop","volv"], ["se dévouer","献身","devote oneself","volv"],
    ["vulnérable","脆弱的","vulnerable","vulner"], ["la vulnérabilité","脆弱性","vulnerability","vulner"], ["blesser","伤害","wound","vulner"], ["la blessure","伤口","wound","vulner"],
    /* Greek in French */ ["la logique","逻辑","logic","log"], ["la biologie","生物学","biology","log"], ["le dialogue","对话","dialogue","log"], ["la technologie","技术","technology","log"], ["la psychologie","心理学","psychology","log"], ["le catalogue","目录","catalogue","log"], ["le prologue","序言","prologue","log"], ["l'archéologie","考古学","archaeology","log"], ["l'écologie","生态学","ecology","log"],
    ["le graphique","图表","graph","graph"], ["la photographie","照片","photograph","graph"], ["l'autographe","亲笔签名","autograph","graph"], ["la biographie","传记","biography","graph"], ["la géographie","地理","geography","graph"], ["le paragraphe","段落","paragraph","graph"], ["le télégramme","电报","telegram","graph"], ["la grammaire","语法","grammar","graph"], ["l'orthographe","拼写","spelling","graph"],
    ["le téléphone","电话","telephone","phon"], ["le microphone","麦克风","microphone","phon"], ["la symphonie","交响乐","symphony","phon"], ["phonétique","语音的","phonetic","phon"], ["le saxophone","萨克斯","saxophone","phon"],
    ["la biographie","传记","biography","bio"], ["l'antibiotique","抗生素","antibiotic","bio"], ["biologique","生物的,有机的","biological, organic","bio"], ["la symbiose","共生","symbiosis","bio"],
    ["la géologie","地质学","geology","geo"], ["la géométrie","几何","geometry","geo"], ["géographique","地理的","geographical","geo"],
    ["chronique","慢性的,专栏","chronic, column","chron"], ["la chronologie","年表","chronology","chron"], ["synchroniser","同步","synchronize","chron"], ["le chronomètre","秒表","stopwatch","chron"],
    ["la sympathie","好感","sympathy","path"], ["l'empathie","共情","empathy","path"], ["l'apathie","冷漠","apathy","path"], ["pathétique","可悲的","pathetic","path"], ["la pathologie","病理学","pathology","path"],
    ["la télévision","电视","television","tele"], ["le télescope","望远镜","telescope","tele"], ["télécharger","下载","download","tele"], ["la télécommande","遥控器","remote control","tele"],
    ["le microscope","显微镜","microscope","micro"], ["le microbe","微生物","microbe","micro"], ["le micro-onde","微波炉","microwave","micro"],
    ["le périscope","潜望镜","periscope","scop"], ["l'horoscope","星座运势","horoscope","scop"], ["le kaléidoscope","万花筒","kaleidoscope","scop"],
    ["le thermomètre","温度计","thermometer","meter"], ["le diamètre","直径","diameter","meter"], ["le périmètre","周长","perimeter","meter"], ["la symétrie","对称","symmetry","meter"], ["le kilomètre","千米","kilometre","meter"],
    ["la démocratie","民主","democracy","crat"], ["l'aristocratie","贵族","aristocracy","crat"], ["la bureaucratie","官僚制","bureaucracy","crat"], ["démocratique","民主的","democratic","crat"],
    ["l'anthropologie","人类学","anthropology","anthrop"], ["la philanthropie","慈善","philanthropy","anthrop"], ["le misanthrope","厌世者","misanthrope","anthrop"],
    ["psychique","心理的","psychic","psych"], ["la psychiatrie","精神病学","psychiatry","psych"], ["le psychologue","心理学家","psychologist","psych"],
    ["la philosophie","哲学","philosophy","phil"], ["le philosophe","哲学家","philosopher","phil"], ["philharmonique","爱乐的","philharmonic","phil"],
    ["la théologie","神学","theology","theo"], ["l'athée","无神论者","atheist","theo"], ["le monothéisme","一神教","monotheism","theo"], ["l'enthousiasme","热情","enthusiasm","theo"],
    ["l'hydrogène","氢","hydrogen","hydr"], ["hydraulique","水力的","hydraulic","hydr"], ["déshydrater","脱水","dehydrate","hydr"],
    ["le cycle","循环","cycle","cycl"], ["la bicyclette","自行车","bicycle","cycl"], ["recycler","回收","recycle","cycl"], ["le cyclone","气旋","cyclone","cycl"], ["l'encyclopédie","百科全书","encyclopedia","cycl"],
    ["la phobie","恐惧症","phobia","phob"], ["la claustrophobie","幽闭恐惧","claustrophobia","phob"], ["la xénophobie","仇外","xenophobia","phob"],
    ["le synonyme","同义词","synonym","onym"], ["l'antonyme","反义词","antonym","onym"], ["anonyme","匿名的","anonymous","onym"], ["le pseudonyme","笔名","pseudonym","onym"],
    ["la synthèse","合成","synthesis","syn"], ["le symbole","符号","symbol","syn"], ["le système","系统","system","syn"], ["la syntaxe","句法","syntax","syn"],
    ["l'antibiotique","抗生素","antibiotic","anti"], ["l'antidote","解毒剂","antidote","anti"], ["antisocial","反社会的","antisocial","anti"], ["l'antiquité","古代","antiquity","anti"],
    ["hyperactif","过度活跃的","hyperactive","hyper"], ["l'hypermarché","大型超市","hypermarket","hyper"], ["l'hypertension","高血压","hypertension","hyper"],
    ["le monopole","垄断","monopoly","mono"], ["le monologue","独白","monologue","mono"], ["monotone","单调的","monotonous","mono"], ["le monarque","君主","monarch","mono"],
    ["le polygone","多边形","polygon","poly"], ["polyglotte","通晓多语的","polyglot","poly"], ["la polyclinique","综合诊所","polyclinic","poly"],
    ["le néon","氖","neon","neo"], ["le néologisme","新词","neologism","neo"], ["néolithique","新石器的","Neolithic","neo"],
    ["le diamètre","直径","diameter","dia"], ["le diagnostic","诊断","diagnosis","dia"], ["la diagonale","对角线","diagonal","dia"],
    ["l'atome","原子","atom","a"], ["l'athée","无神论者","atheist","a"], ["anonyme","匿名的","anonymous","a"], ["l'anarchie","无政府","anarchy","a"], ["l'amnésie","失忆","amnesia","a"]
  );
})();
