/* =====================================================
   FUGA MYTHICA — CURSUS Italian 🇮🇹 · batch 8 — Greek scientific / medical / cultural families
   ===================================================== */
(function () {
  const p = VOCAB.it;
  Object.assign(p.roots, {"cardi": ["cardi-", "心", "heart"], "ophthalm": ["ophthalm-", "眼", "eye"], "nephr": ["nephr-", "肾", "kidney"], "phot": ["phot-", "光", "light"], "astr": ["astr- / aster-", "星", "star"], "polit": ["polit- / polis", "城邦,政治", "city, politics"], "econ": ["econom- / oik-", "家,经济", "household, economy"], "chem": ["chem-", "化学", "chemistry"], "math": ["mathem-", "学习,数学", "learning, maths"], "geometr": ["geometr-", "测地,几何", "geometry"], "gram": ["gram- / gramm-", "写下的东西", "written thing"], "troph": ["troph-", "营养", "nourishment"], "zoo": ["zo- / zoo-", "动物", "animal"], "ornith": ["ornith-", "鸟", "bird"], "ichthy": ["ichthy-", "鱼", "fish"], "entom": ["entom-", "昆虫", "insect"], "hipp": ["hipp-", "马", "horse"], "aut": ["aut- / auto-", "自己", "self"], "homo": ["homo- / homeo-", "相同", "same"], "meta": ["meta-", "之后,变化", "after, change"], "para": ["para-", "旁边,反常", "beside, beyond"], "epi": ["epi-", "在上", "upon"], "endo": ["endo- / ento-", "内", "inside"], "exo": ["exo- / ecto-", "外", "outside"], "hemi": ["hemi-", "半", "half"], "tetra": ["tetra-", "四", "four"], "penta": ["penta-", "五", "five"], "hexa": ["hexa-", "六", "six"], "deca": ["deca- / deka-", "十", "ten"], "proto": ["prot- / proto-", "第一", "first"], "pseudo": ["pseud- / pseudo-", "假", "false"], "sthen": ["sthen-", "力量", "strength"], "algia": ["-algia / alg-", "痛", "pain"], "itis": ["-itis", "炎症", "inflammation"], "oma": ["-oma", "肿瘤", "tumour"], "osis": ["-osis", "病态,过程", "condition, process"], "ectomy": ["-ectomy / tom-", "切除", "cutting out"], "podo": ["pod- / -pus", "足", "foot"], "arthr": ["arthr-", "关节", "joint"], "my": ["my- / myo-", "肌肉", "muscle"], "encephal": ["encephal-", "脑", "brain"], "glyc": ["glyc- / gluc-", "甜,糖", "sweet, sugar"], "cyt": ["cyt- / -cyte", "细胞", "cell"], "nucle": ["nucle-", "核", "nucleus"], "phyll": ["phyll-", "叶", "leaf"], "rhiz": ["rhiz-", "根", "root"], "zym": ["zym- / -ase", "发酵", "ferment"], "magnet": ["magnet-", "磁", "magnet"], "atom": ["atom- / tom-", "不可分", "uncuttable"], "latr": ["-latry / latr-", "崇拜", "worship"], "drom": ["drom-", "跑,路", "running, course"], "bolo": ["ball- / bol-", "投掷", "throw"], "thes": ["thes- / thet-", "放置", "placing"], "phen": ["phen- / phan-", "显现", "show"], "ops": ["ops- / opt-", "视觉", "sight"], "acou": ["acou- / acous-", "听", "hearing"], "aesth": ["aesth- / esth-", "感觉", "feeling"], "mnem": ["mnem- / mnes-", "记忆", "memory"], "gloss": ["gloss- / glott-", "舌,语言", "tongue, language"], "rhet": ["rhet-", "说话", "speaking"], "chore": ["chore-", "舞蹈", "dance"], "melo": ["mel- / melo-", "歌,曲", "song"], "harmon": ["harmon-", "接合,和谐", "fitting together"], "hier": ["hier-", "神圣", "sacred"], "icon": ["icon-", "图像", "image"], "idio": ["idi- / idio-", "个人的", "one's own"], "cine": ["cine- / kine-", "动", "movement"], "ergo": ["erg- / -urgy", "工作", "work"], "heli": ["helic-", "螺旋", "spiral"], "heter": ["heter-", "不同", "different"], "aristo": ["arist-", "最好", "best"], "olig": ["olig-", "少", "few"], "pleth": ["pleth- / plethor-", "充满", "fullness"], "thanat": ["thanat-", "死", "death"], "ger": ["ger- / geront-", "老", "old age"], "paed": ["paed- / ped-", "儿童", "child"], "gyn": ["gyn- / gynec-", "女", "woman"], "andr": ["andr-", "男", "man"], "ecol": ["ec- / oec-", "家,栖息地", "house, habitat"], "steno": ["sten-", "窄", "narrow"], "brady": ["brady-", "慢", "slow"], "tachy": ["tachy-", "快", "fast"], "baro": ["bar- / baro-", "重,压", "weight, pressure"], "seism": ["seism-", "震动", "shaking"], "cryo": ["cry- / cryo-", "冷", "cold"], "xero": ["xer- / xero-", "干", "dry"], "hygr": ["hygr-", "湿", "moist"], "meteor": ["meteor-", "高空之物", "thing in the air"], "ocean": ["ocean-", "大洋", "ocean"], "nes": ["nes- / -nesia", "岛", "island"], "potam": ["potam-", "河", "river"], "thalass": ["thalass-", "海", "sea"], "ur": ["ur- / uro-", "尿", "urine"], "pyret": ["pyret-", "发热", "fever"], "narc": ["narc-", "麻木", "numbness"], "hypn": ["hypn-", "睡", "sleep"], "phren": ["phren-", "心智", "mind"], "nous": ["no- / noe-", "心智", "mind"], "ethic": ["eth- / ethic-", "习俗,品格", "custom, character"], "dox": ["dox- / -doxy", "意见,教义", "opinion"], "heres": ["heres- / haer-", "选择", "choice"], "martyr": ["martyr-", "见证", "witness"], "angel": ["angel-", "信使", "messenger"], "evangel": ["evangel-", "好消息", "good news"], "apocal": ["apocalyp- / calyp-", "揭开", "uncover"], "myst": ["myst-", "闭口,秘密", "secret"]});
  p.words.push(
    ["cardiaco", "心脏的", "of the heart", "cardi"],
    ["la cardiologia", "心脏病学", "heart medicine", "cardi"],
    ["il cardiologo", "心脏科医生", "heart doctor", "cardi"],
    ["il cardiogramma", "心电图", "heart trace", "cardi"],
    ["cardiovascolare", "心血管的", "heart and vessels", "cardi"],
    ["la tachicardia", "心动过速", "fast heartbeat", "cardi"],
    ["il miocardio", "心肌", "heart muscle", "cardi"],
    ["il pericardio", "心包", "heart sac", "cardi"],
    ["l'oftalmologia", "眼科学", "eye medicine", "ophthalm"],
    ["l'oftalmologo", "眼科医生", "eye doctor", "ophthalm"],
    ["oftalmico", "眼的", "of the eye", "ophthalm"],
    ["la nefrologia", "肾脏病学", "kidney medicine", "nephr"],
    ["la nefrite", "肾炎", "kidney inflammation", "nephr"],
    ["il nefrologo", "肾科医生", "kidney doctor", "nephr"],
    ["il fotografo", "摄影师", "photo-taker", "phot"],
    ["fotografico", "摄影的", "of photos", "phot"],
    ["la fotocopia", "复印件", "copy", "phot"],
    ["il fotone", "光子", "light particle", "phot"],
    ["la fotosintesi", "光合作用", "light-making", "phot"],
    ["la fototerapia", "光疗", "light treatment", "phot"],
    ["fotogenico", "上镜的", "looks good in photos", "phot"],
    ["fotovoltaico", "光伏的", "light-to-electricity", "phot"],
    ["l'astronomo", "天文学家", "star scientist", "astr"],
    ["astronomico", "天文的,巨大的", "of stars; huge", "astr"],
    ["l'astrologia", "占星术", "star fortune-telling", "astr"],
    ["l'asteroide", "小行星", "small planet", "astr"],
    ["l'astrofisica", "天体物理", "star physics", "astr"],
    ["la politica", "政治", "government affairs", "polit"],
    ["politico", "政治的", "of government", "polit"],
    ["il politico", "政治家", "political figure", "polit"],
    ["la polizia", "警察", "law enforcement", "polit"],
    ["la metropoli", "大都市", "major city", "polit"],
    ["metropolitano", "大都市的", "of a big city", "polit"],
    ["cosmopolita", "世界主义的", "worldly", "polit"],
    ["l'economista", "经济学家", "economy expert", "econ"],
    ["economizzare", "节省", "save", "econ"],
    ["ecologico", "生态的", "environmental", "ecol"],
    ["l'ecologista", "生态学家", "environment expert", "ecol"],
    ["chimico", "化学的", "of chemistry", "chem"],
    ["il chimico", "化学家", "chemistry expert", "chem"],
    ["la biochimica", "生物化学", "chemistry of life", "chem"],
    ["petrolchimico", "石化的", "oil-chemistry", "chem"],
    ["l'alchimia", "炼金术", "old chemistry", "chem"],
    ["l'alchimista", "炼金术士", "old chemist", "chem"],
    ["matematico", "数学的", "of maths", "math"],
    ["il matematico", "数学家", "maths expert", "math"],
    ["il poliedrico", "博学者", "widely learned person", "math"],
    ["geometrico", "几何的", "of shapes", "geometr"],
    ["grammaticale", "语法的", "of grammar", "gram"],
    ["il programmatore", "程序员", "software writer", "gram"],
    ["il diagramma", "图表", "drawing", "gram"],
    ["l'anagramma", "字谜", "letter-swap word", "gram"],
    ["l'epigramma", "警句", "witty saying", "gram"],
    ["il monogramma", "花押字", "initials design", "gram"],
    ["il chilogrammo", "千克", "1000 grams", "gram"],
    ["l'ologramma", "全息图", "3D image", "gram"],
    ["l'atrofia", "萎缩", "wasting away", "troph"],
    ["l'ipertrofia", "肥大", "overgrowth", "troph"],
    ["la distrofia", "营养不良", "faulty growth", "troph"],
    ["trofico", "营养的", "of nutrition", "troph"],
    ["lo zoo", "动物园", "animal park", "zoo"],
    ["la zoologia", "动物学", "animal science", "zoo"],
    ["lo zoologo", "动物学家", "animal scientist", "zoo"],
    ["lo zodiaco", "黄道带", "star-sign circle", "zoo"],
    ["il protozoo", "原生动物", "single-celled animal", "zoo"],
    ["l'ornitologia", "鸟类学", "bird science", "ornith"],
    ["l'ornitologo", "鸟类学家", "bird scientist", "ornith"],
    ["l'ittiologia", "鱼类学", "fish science", "ichthy"],
    ["l'entomologia", "昆虫学", "insect science", "entom"],
    ["l'entomologo", "昆虫学家", "insect scientist", "entom"],
    ["l'ippopotamo", "河马", "river horse", "hipp"],
    ["l'ippodromo", "赛马场", "horse track", "hipp"],
    ["l'autobiografia", "自传", "own life story", "aut"],
    ["autonomo", "自主的", "self-governing", "aut"],
    ["l'autocrazia", "独裁", "one-person rule", "aut"],
    ["autentico", "真正的", "genuine", "aut"],
    ["l'autenticità", "真实性", "genuineness", "aut"],
    ["l'autopsia", "尸检", "post-mortem exam", "aut"],
    ["l'automazione", "自动化", "machine operation", "aut"],
    ["l'autismo", "自闭症", "autism", "aut"],
    ["omogeneo", "同质的", "uniform", "homo"],
    ["l'omonimo", "同音词", "same-name word", "homo"],
    ["omosessuale", "同性恋的", "same-sex", "homo"],
    ["l'omeopatia", "顺势疗法", "like-cures-like", "homo"],
    ["omologo", "同源的", "corresponding", "homo"],
    ["la metafora", "隐喻", "figure of speech", "meta"],
    ["metaforico", "隐喻的", "figurative", "meta"],
    ["la metamorfosi", "变形", "transformation", "meta"],
    ["la metafisica", "形而上学", "philosophy of being", "meta"],
    ["metodico", "有条理的", "systematic", "meta"],
    ["la metodologia", "方法论", "system of methods", "meta"],
    ["il paradosso", "悖论", "self-contradiction", "para"],
    ["paradossale", "自相矛盾的", "contradictory", "para"],
    ["il parassita", "寄生虫", "freeloader organism", "para"],
    ["parallelo", "平行的", "side by side", "para"],
    ["il parametro", "参数", "setting", "para"],
    ["il paramedico", "急救员", "emergency medic", "para"],
    ["la paranoia", "偏执", "irrational suspicion", "para"],
    ["la paralisi", "瘫痪", "loss of movement", "para"],
    ["paralizzare", "使瘫痪", "disable", "para"],
    ["l'epidemia", "流行病", "widespread disease", "epi"],
    ["l'epidermide", "表皮", "outer skin", "epi"],
    ["l'epilessia", "癫痫", "seizure disorder", "epi"],
    ["l'epitaffio", "墓志铭", "tomb inscription", "epi"],
    ["l'epicentro", "震中", "quake centre", "epi"],
    ["l'epilogo", "尾声", "closing section", "epi"],
    ["l'epifania", "顿悟,主显节", "sudden insight", "epi"],
    ["l'endoscopia", "内窥镜检查", "inside viewing", "endo"],
    ["endocrino", "内分泌的", "internal-secreting", "endo"],
    ["endogeno", "内生的", "from within", "endo"],
    ["esotico", "异国的", "foreign", "exo"],
    ["esogeno", "外源的", "from outside", "exo"],
    ["l'esoscheletro", "外骨骼", "outer skeleton", "exo"],
    ["l'emisfero", "半球", "half-globe", "hemi"],
    ["l'emiciclo", "半圆形会场", "half-circle", "hemi"],
    ["l'esagono", "六边形", "six-sided shape", "hexa"],
    ["esagonale", "六边形的", "six-sided", "hexa"],
    ["il decennio", "十年", "ten years", "deca"],
    ["il decathlon", "十项全能", "ten-event contest", "deca"],
    ["il decalogo", "十诫", "ten commandments", "deca"],
    ["decimale", "十进制的", "base-ten", "deca"],
    ["il prototipo", "原型", "first model", "proto"],
    ["il protocollo", "协议,礼仪", "set of rules", "proto"],
    ["il protagonista", "主角", "main character", "proto"],
    ["il protone", "质子", "positive particle", "proto"],
    ["la proteina", "蛋白质", "body-building nutrient", "proto"],
    ["la pseudoscienza", "伪科学", "fake science", "pseudo"],
    ["l'astenia", "无力", "weakness", "sthen"],
    ["la nevrastenia", "神经衰弱", "nerve exhaustion", "sthen"],
    ["la nevralgia", "神经痛", "nerve pain", "algia"],
    ["la nostalgia", "怀旧", "homesickness", "algia"],
    ["nostalgico", "怀旧的", "longing for the past", "algia"],
    ["l'analgesico", "止痛药", "painkiller", "algia"],
    ["la mialgia", "肌肉痛", "muscle pain", "algia"],
    ["la bronchite", "支气管炎", "airway inflammation", "itis"],
    ["l'artrite", "关节炎", "joint inflammation", "itis"],
    ["l'epatite", "肝炎", "liver inflammation", "itis"],
    ["la gastrite", "胃炎", "stomach inflammation", "itis"],
    ["la dermatite", "皮炎", "skin inflammation", "itis"],
    ["l'appendicite", "阑尾炎", "appendix inflammation", "itis"],
    ["la meningite", "脑膜炎", "brain-lining inflammation", "itis"],
    ["la tonsillite", "扁桃体炎", "tonsil inflammation", "itis"],
    ["la sinusite", "鼻窦炎", "sinus inflammation", "itis"],
    ["la congiuntivite", "结膜炎", "eye inflammation", "itis"],
    ["il carcinoma", "癌", "cancer tumour", "oma"],
    ["il melanoma", "黑色素瘤", "skin cancer", "oma"],
    ["il linfoma", "淋巴瘤", "lymph tumour", "oma"],
    ["il glaucoma", "青光眼", "eye-pressure disease", "oma"],
    ["il sarcoma", "肉瘤", "tissue tumour", "oma"],
    ["la prognosi", "预后", "forecast", "osis"],
    ["la nevrosi", "神经症", "anxiety disorder", "osis"],
    ["la psicosi", "精神病", "loss of reality", "osis"],
    ["la tubercolosi", "结核病", "lung disease", "osis"],
    ["l'osmosi", "渗透", "gradual absorption", "osis"],
    ["l'ipnosi", "催眠", "trance state", "osis"],
    ["la trombosi", "血栓", "blood clot", "osis"],
    ["l'appendicectomia", "阑尾切除", "appendix removal", "ectomy"],
    ["la tonsillectomia", "扁桃体切除", "tonsil removal", "ectomy"],
    ["l'anatomia", "解剖学", "body structure", "ectomy"],
    ["anatomico", "解剖的", "of body structure", "ectomy"],
    ["la dicotomia", "二分法", "split in two", "ectomy"],
    ["il podio", "讲台,领奖台", "platform", "podo"],
    ["il podologo", "足科医生", "foot doctor", "podo"],
    ["gli antipodi", "对跖点", "opposite side of earth", "podo"],
    ["l'artropodo", "节肢动物", "jointed-leg animal", "arthr"],
    ["l'artroscopia", "关节镜检查", "joint viewing", "arthr"],
    ["la miopia", "近视", "short-sightedness", "ops"],
    ["miope", "近视的", "short-sighted", "ops"],
    ["la miocardite", "心肌炎", "heart-muscle inflammation", "my"],
    ["la miologia", "肌学", "muscle science", "my"],
    ["l'encefalite", "脑炎", "brain inflammation", "encephal"],
    ["l'elettroencefalogramma", "脑电图", "brain-wave trace", "encephal"],
    ["il glucosio", "葡萄糖", "blood sugar", "glyc"],
    ["la glicerina", "甘油", "sweet oil", "glyc"],
    ["l'ipoglicemia", "低血糖", "low blood sugar", "glyc"],
    ["la citologia", "细胞学", "cell science", "cyt"],
    ["il citoplasma", "细胞质", "cell substance", "cyt"],
    ["il leucocita", "白细胞", "white blood cell", "cyt"],
    ["l'eritrocita", "红细胞", "red blood cell", "cyt"],
    ["il linfocita", "淋巴细胞", "immune cell", "cyt"],
    ["il nucleo", "核", "centre", "nucle"],
    ["nucleare", "核的", "atomic", "nucle"],
    ["il nucleotide", "核苷酸", "DNA unit", "nucle"],
    ["la clorofilla", "叶绿素", "green leaf pigment", "phyll"],
    ["il rizoma", "根茎", "underground stem", "rhiz"],
    ["l'enzima", "酶", "biological catalyst", "zym"],
    ["il magnete", "磁铁", "attracting metal", "magnet"],
    ["magnetico", "磁的", "attracting", "magnet"],
    ["il magnetismo", "磁性", "magnetic force", "magnet"],
    ["elettromagnetico", "电磁的", "electric-magnetic", "magnet"],
    ["atomico", "原子的", "of atoms", "atom"],
    ["l'idolatria", "偶像崇拜", "image worship", "latr"],
    ["l'idolatra", "偶像崇拜者", "image worshipper", "latr"],
    ["la sindrome", "综合征", "set of symptoms", "drom"],
    ["l'aerodromo", "小型机场", "airfield", "drom"],
    ["il palindromo", "回文", "reads-same-backwards", "drom"],
    ["il velodromo", "自行车赛场", "cycling track", "drom"],
    ["il dromedario", "单峰驼", "running camel", "drom"],
    ["balistico", "弹道的", "of projectiles", "bolo"],
    ["la balistica", "弹道学", "projectile science", "bolo"],
    ["problematico", "有问题的", "difficult", "bolo"],
    ["simbolico", "象征的", "representing", "bolo"],
    ["simboleggiare", "象征", "stand for", "bolo"],
    ["diabolico", "恶魔般的", "devilish", "bolo"],
    ["la tesi", "论文,论点", "argument", "thes"],
    ["l'ipotesi", "假设", "proposed explanation", "thes"],
    ["ipotetico", "假设的", "supposed", "thes"],
    ["sintetico", "合成的", "artificial", "thes"],
    ["sintetizzare", "合成", "combine", "thes"],
    ["l'antitesi", "对立面", "direct opposite", "thes"],
    ["la parentesi", "括号", "bracket", "thes"],
    ["la protesi", "假体", "artificial body part", "thes"],
    ["il tema", "主题", "subject", "thes"],
    ["tematico", "主题的", "of the subject", "thes"],
    ["l'epiteto", "称号", "descriptive name", "thes"],
    ["il fenomeno", "现象", "observable event", "phen"],
    ["fenomenale", "非凡的", "remarkable", "phen"],
    ["la fase", "阶段", "stage", "phen"],
    ["l'enfasi", "强调", "stress", "phen"],
    ["enfatizzare", "强调", "stress", "phen"],
    ["la fantasia", "幻想", "imagination", "phen"],
    ["fantastico", "极好的,奇幻的", "wonderful", "phen"],
    ["il fantasma", "幽灵", "ghost", "phen"],
    ["diafano", "透明的", "see-through", "phen"],
    ["l'ottica", "光学", "science of light", "ops"],
    ["ottico", "光学的,视觉的", "of sight", "ops"],
    ["l'ottico", "配镜师", "glasses-maker", "ops"],
    ["la sinossi", "概要", "summary", "ops"],
    ["la biopsia", "活检", "tissue sample test", "ops"],
    ["acustico", "声学的", "of sound", "acou"],
    ["l'acustica", "声学", "sound science", "acou"],
    ["estetico", "美学的", "of beauty", "aesth"],
    ["l'estetica", "美学", "study of beauty", "aesth"],
    ["l'anestesia", "麻醉", "numbing", "aesth"],
    ["l'anestetico", "麻醉剂", "numbing drug", "aesth"],
    ["l'anestesista", "麻醉师", "numbing doctor", "aesth"],
    ["mnemonico", "助记的", "memory-aiding", "mnem"],
    ["l'amnistia", "大赦", "official pardon", "mnem"],
    ["il glossario", "词汇表", "word list", "gloss"],
    ["il poliglotta", "通晓多语者", "many-language speaker", "gloss"],
    ["l'epiglottide", "会厌", "throat flap", "gloss"],
    ["la glossa", "注释", "explanatory note", "gloss"],
    ["la retorica", "修辞", "art of persuasion", "rhet"],
    ["retorico", "修辞的", "for effect", "rhet"],
    ["la coreografia", "编舞", "dance design", "chore"],
    ["il coreografo", "编舞者", "dance designer", "chore"],
    ["il coro", "合唱团", "choir", "chore"],
    ["corale", "合唱的", "of a choir", "chore"],
    ["melodico", "旋律的", "tuneful", "melo"],
    ["melodrammatico", "夸张的", "over-dramatic", "melo"],
    ["l'armonia", "和谐", "agreement", "harmon"],
    ["armonioso", "和谐的", "well-matched", "harmon"],
    ["armonizzare", "使和谐", "bring into agreement", "harmon"],
    ["l'armonica", "口琴", "mouth organ", "harmon"],
    ["la gerarchia", "等级制", "ranking order", "hier"],
    ["gerarchico", "等级的", "ranked", "hier"],
    ["il geroglifico", "象形文字", "sacred carving", "hier"],
    ["l'icona", "图标,圣像", "image", "icon"],
    ["iconico", "标志性的", "symbolic", "icon"],
    ["l'iconoclasta", "破除偶像者", "image-breaker", "icon"],
    ["l'iconografia", "图像学", "image study", "icon"],
    ["l'idioma", "习语,语言", "expression; language", "idio"],
    ["idiomatico", "地道的", "natural-sounding", "idio"],
    ["l'idiota", "傻瓜", "fool", "idio"],
    ["idiota", "愚蠢的", "foolish", "idio"],
    ["l'idiosincrasia", "个人癖好", "personal quirk", "idio"],
    ["cinematografico", "电影的", "of film", "cine"],
    ["cinetico", "动力的", "of motion", "cine"],
    ["la chinesiologia", "运动机能学", "movement science", "cine"],
    ["la telecinesi", "隔空移物", "mind-moving", "cine"],
    ["l'energia", "能量", "power", "ergo"],
    ["energico", "精力充沛的", "full of energy", "ergo"],
    ["ergonomico", "符合人体工学的", "comfortable to use", "ergo"],
    ["la chirurgia", "外科手术", "operation", "ergo"],
    ["il chirurgo", "外科医生", "operating doctor", "ergo"],
    ["chirurgico", "外科的", "of operations", "ergo"],
    ["la metallurgia", "冶金", "metal-working", "ergo"],
    ["la liturgia", "礼拜仪式", "worship service", "ergo"],
    ["l'allergia", "过敏", "allergic reaction", "ergo"],
    ["allergico", "过敏的", "reacting badly", "ergo"],
    ["l'elica", "螺旋", "spiral", "heli"],
    ["l'elicottero", "直升机", "rotor aircraft", "heli"],
    ["elicoidale", "螺旋形的", "spiral-shaped", "heli"],
    ["eterogeneo", "异质的", "mixed", "heter"],
    ["eterosessuale", "异性恋的", "opposite-sex", "heter"],
    ["eterodosso", "非正统的", "unorthodox", "heter"],
    ["l'aristocratico", "贵族", "noble person", "aristo"],
    ["aristocratico", "贵族的", "noble", "aristo"],
    ["l'oligarchia", "寡头政治", "rule by few", "olig"],
    ["l'oligarca", "寡头", "powerful few", "olig"],
    ["la pletora", "过多", "excess", "pleth"],
    ["l'eutanasia", "安乐死", "mercy killing", "thanat"],
    ["geriatrico", "老年病的", "of old age", "ger"],
    ["la geriatria", "老年医学", "old-age medicine", "ger"],
    ["la gerontologia", "老年学", "ageing science", "ger"],
    ["la pediatria", "儿科", "child medicine", "paed"],
    ["il pediatra", "儿科医生", "child doctor", "paed"],
    ["la pedagogia", "教育学", "teaching method", "paed"],
    ["pedagogico", "教学的", "of teaching", "paed"],
    ["ortopedico", "骨科的", "bone-correcting", "paed"],
    ["la ginecologia", "妇科", "women's medicine", "gyn"],
    ["il ginecologo", "妇科医生", "women's doctor", "gyn"],
    ["la misoginia", "厌女", "hatred of women", "gyn"],
    ["l'androide", "人形机器人", "human-like robot", "andr"],
    ["androgino", "雌雄同体的", "both-sex", "andr"],
    ["la poliandria", "一妻多夫", "many husbands", "andr"],
    ["la stenografia", "速记", "shorthand", "steno"],
    ["la stenosi", "狭窄", "narrowing", "steno"],
    ["la bradicardia", "心动过缓", "slow heartbeat", "brady"],
    ["il tachimetro", "转速表", "speed gauge", "tachy"],
    ["il barometro", "气压计", "pressure gauge", "baro"],
    ["barometrico", "气压的", "of pressure", "baro"],
    ["il baritono", "男中音", "deep male voice", "baro"],
    ["sismico", "地震的", "of earthquakes", "seism"],
    ["la sismologia", "地震学", "earthquake science", "seism"],
    ["il sismografo", "地震仪", "quake recorder", "seism"],
    ["criogenico", "低温的", "very cold", "cryo"],
    ["la crioterapia", "冷冻疗法", "cold treatment", "cryo"],
    ["la xerofita", "旱生植物", "dry-land plant", "xero"],
    ["l'igrometro", "湿度计", "moisture gauge", "hygr"],
    ["l'igiene", "卫生", "cleanliness", "hygr"],
    ["igienico", "卫生的", "clean", "hygr"],
    ["la meteora", "流星", "shooting star", "meteor"],
    ["il meteorite", "陨石", "fallen space rock", "meteor"],
    ["la meteorologia", "气象学", "weather science", "meteor"],
    ["il meteorologo", "气象学家", "weather scientist", "meteor"],
    ["l'oceano", "海洋", "sea", "ocean"],
    ["oceanico", "海洋的", "of the ocean", "ocean"],
    ["l'oceanografia", "海洋学", "ocean science", "ocean"],
    ["la Polinesia", "波利尼西亚", "many islands", "nes"],
    ["l'Indonesia", "印度尼西亚", "Indian islands", "nes"],
    ["il Peloponneso", "伯罗奔尼撒", "island of Pelops", "nes"],
    ["la Mesopotamia", "美索不达米亚", "between rivers", "potam"],
    ["la talassoterapia", "海水疗法", "sea treatment", "thalass"],
    ["l'urologia", "泌尿科", "urinary medicine", "ur"],
    ["l'urologo", "泌尿科医生", "urinary doctor", "ur"],
    ["l'urina", "尿", "urine", "ur"],
    ["il diuretico", "利尿剂", "water pill", "ur"],
    ["l'antipiretico", "退烧药", "fever-reducer", "pyret"],
    ["il narcotico", "麻醉品", "numbing drug", "narc"],
    ["la narcosi", "麻醉状态", "drug stupor", "narc"],
    ["la narcolessia", "发作性睡病", "sleep attacks", "narc"],
    ["ipnotico", "催眠的", "sleep-inducing", "hypn"],
    ["ipnotizzare", "催眠", "put in a trance", "hypn"],
    ["l'ipnotizzatore", "催眠师", "trance-inducer", "hypn"],
    ["la schizofrenia", "精神分裂症", "split mind", "phren"],
    ["frenetico", "狂热的", "frantic", "phren"],
    ["la frenesia", "狂乱", "wild excitement", "phren"],
    ["paranoico", "偏执的", "irrationally suspicious", "nous"],
    ["l'ethos", "精神特质", "character", "ethic"],
    ["ortodosso", "正统的", "conventional", "dox"],
    ["l'ortodossia", "正统", "accepted belief", "dox"],
    ["la dossologia", "荣耀颂", "hymn of praise", "dox"],
    ["l'eresia", "异端", "false belief", "heres"],
    ["l'eretico", "异端者", "dissenter", "heres"],
    ["eretico", "异端的", "against doctrine", "heres"],
    ["il martire", "殉道者", "one who dies for belief", "martyr"],
    ["il martirio", "殉道", "death for belief", "martyr"],
    ["l'angelo", "天使", "heavenly messenger", "angel"],
    ["angelico", "天使般的", "like an angel", "angel"],
    ["l'arcangelo", "大天使", "chief angel", "angel"],
    ["evangelico", "福音派的", "of the gospel", "evangel"],
    ["l'evangelista", "传福音者", "gospel preacher", "evangel"],
    ["il vangelo", "福音", "good news", "evangel"],
    ["l'apocalisse", "天启,末日", "revelation; end of world", "apocal"],
    ["apocalittico", "末日的", "world-ending", "apocal"],
    ["il mistero", "神秘", "secret", "myst"],
    ["misterioso", "神秘的", "puzzling", "myst"],
    ["il mistico", "神秘主义者", "spiritual seeker", "myst"],
    ["mistico", "神秘主义的", "spiritual", "myst"],
    ["il misticismo", "神秘主义", "spiritual belief", "myst"],
    ["mistificare", "使迷惑", "puzzle", "myst"]
  );
})();
