/* =====================================================
   FUGA MYTHICA — CURSUS Spanish 🇪🇸 · batch 8 — Greek scientific / medical / cultural families
   ===================================================== */
(function () {
  const p = VOCAB.es;
  Object.assign(p.roots, {"cardi": ["cardi-", "心", "heart"], "ophthalm": ["ophthalm-", "眼", "eye"], "nephr": ["nephr-", "肾", "kidney"], "phot": ["phot-", "光", "light"], "astr": ["astr- / aster-", "星", "star"], "polit": ["polit- / polis", "城邦,政治", "city, politics"], "econ": ["econom- / oik-", "家,经济", "household, economy"], "chem": ["chem-", "化学", "chemistry"], "math": ["mathem-", "学习,数学", "learning, maths"], "geometr": ["geometr-", "测地,几何", "geometry"], "gram": ["gram- / gramm-", "写下的东西", "written thing"], "troph": ["troph-", "营养", "nourishment"], "zoo": ["zo- / zoo-", "动物", "animal"], "ornith": ["ornith-", "鸟", "bird"], "ichthy": ["ichthy-", "鱼", "fish"], "entom": ["entom-", "昆虫", "insect"], "hipp": ["hipp-", "马", "horse"], "aut": ["aut- / auto-", "自己", "self"], "homo": ["homo- / homeo-", "相同", "same"], "meta": ["meta-", "之后,变化", "after, change"], "para": ["para-", "旁边,反常", "beside, beyond"], "epi": ["epi-", "在上", "upon"], "endo": ["endo- / ento-", "内", "inside"], "exo": ["exo- / ecto-", "外", "outside"], "hemi": ["hemi-", "半", "half"], "tetra": ["tetra-", "四", "four"], "penta": ["penta-", "五", "five"], "hexa": ["hexa-", "六", "six"], "deca": ["deca- / deka-", "十", "ten"], "proto": ["prot- / proto-", "第一", "first"], "pseudo": ["pseud- / pseudo-", "假", "false"], "sthen": ["sthen-", "力量", "strength"], "algia": ["-algia / alg-", "痛", "pain"], "itis": ["-itis", "炎症", "inflammation"], "oma": ["-oma", "肿瘤", "tumour"], "osis": ["-osis", "病态,过程", "condition, process"], "ectomy": ["-ectomy / tom-", "切除", "cutting out"], "podo": ["pod- / -pus", "足", "foot"], "arthr": ["arthr-", "关节", "joint"], "my": ["my- / myo-", "肌肉", "muscle"], "encephal": ["encephal-", "脑", "brain"], "glyc": ["glyc- / gluc-", "甜,糖", "sweet, sugar"], "cyt": ["cyt- / -cyte", "细胞", "cell"], "nucle": ["nucle-", "核", "nucleus"], "phyll": ["phyll-", "叶", "leaf"], "rhiz": ["rhiz-", "根", "root"], "zym": ["zym- / -ase", "发酵", "ferment"], "magnet": ["magnet-", "磁", "magnet"], "atom": ["atom- / tom-", "不可分", "uncuttable"], "latr": ["-latry / latr-", "崇拜", "worship"], "drom": ["drom-", "跑,路", "running, course"], "bolo": ["ball- / bol-", "投掷", "throw"], "thes": ["thes- / thet-", "放置", "placing"], "phen": ["phen- / phan-", "显现", "show"], "ops": ["ops- / opt-", "视觉", "sight"], "acou": ["acou- / acous-", "听", "hearing"], "aesth": ["aesth- / esth-", "感觉", "feeling"], "mnem": ["mnem- / mnes-", "记忆", "memory"], "gloss": ["gloss- / glott-", "舌,语言", "tongue, language"], "rhet": ["rhet-", "说话", "speaking"], "chore": ["chore-", "舞蹈", "dance"], "melo": ["mel- / melo-", "歌,曲", "song"], "harmon": ["harmon-", "接合,和谐", "fitting together"], "hier": ["hier-", "神圣", "sacred"], "icon": ["icon-", "图像", "image"], "idio": ["idi- / idio-", "个人的", "one's own"], "cine": ["cine- / kine-", "动", "movement"], "ergo": ["erg- / -urgy", "工作", "work"], "heli": ["helic-", "螺旋", "spiral"], "heter": ["heter-", "不同", "different"], "aristo": ["arist-", "最好", "best"], "olig": ["olig-", "少", "few"], "pleth": ["pleth- / plethor-", "充满", "fullness"], "thanat": ["thanat-", "死", "death"], "ger": ["ger- / geront-", "老", "old age"], "paed": ["paed- / ped-", "儿童", "child"], "gyn": ["gyn- / gynec-", "女", "woman"], "andr": ["andr-", "男", "man"], "ecol": ["ec- / oec-", "家,栖息地", "house, habitat"], "steno": ["sten-", "窄", "narrow"], "brady": ["brady-", "慢", "slow"], "tachy": ["tachy-", "快", "fast"], "baro": ["bar- / baro-", "重,压", "weight, pressure"], "seism": ["seism-", "震动", "shaking"], "cryo": ["cry- / cryo-", "冷", "cold"], "xero": ["xer- / xero-", "干", "dry"], "hygr": ["hygr-", "湿", "moist"], "meteor": ["meteor-", "高空之物", "thing in the air"], "ocean": ["ocean-", "大洋", "ocean"], "nes": ["nes- / -nesia", "岛", "island"], "potam": ["potam-", "河", "river"], "thalass": ["thalass-", "海", "sea"], "ur": ["ur- / uro-", "尿", "urine"], "pyret": ["pyret-", "发热", "fever"], "narc": ["narc-", "麻木", "numbness"], "hypn": ["hypn-", "睡", "sleep"], "phren": ["phren-", "心智", "mind"], "nous": ["no- / noe-", "心智", "mind"], "ethic": ["eth- / ethic-", "习俗,品格", "custom, character"], "dox": ["dox- / -doxy", "意见,教义", "opinion"], "heres": ["heres- / haer-", "选择", "choice"], "martyr": ["martyr-", "见证", "witness"], "angel": ["angel-", "信使", "messenger"], "evangel": ["evangel-", "好消息", "good news"], "apocal": ["apocalyp- / calyp-", "揭开", "uncover"], "myst": ["myst-", "闭口,秘密", "secret"]});
  p.words.push(
    ["cardíaco", "心脏的", "of the heart", "cardi"],
    ["la cardiología", "心脏病学", "heart medicine", "cardi"],
    ["el cardiólogo", "心脏科医生", "heart doctor", "cardi"],
    ["el cardiograma", "心电图", "heart trace", "cardi"],
    ["cardiovascular", "心血管的", "heart and vessels", "cardi"],
    ["la taquicardia", "心动过速", "fast heartbeat", "cardi"],
    ["el miocardio", "心肌", "heart muscle", "cardi"],
    ["el pericardio", "心包", "heart sac", "cardi"],
    ["la oftalmología", "眼科学", "eye medicine", "ophthalm"],
    ["el oftalmólogo", "眼科医生", "eye doctor", "ophthalm"],
    ["oftálmico", "眼的", "of the eye", "ophthalm"],
    ["la nefrología", "肾脏病学", "kidney medicine", "nephr"],
    ["la nefritis", "肾炎", "kidney inflammation", "nephr"],
    ["el nefrólogo", "肾科医生", "kidney doctor", "nephr"],
    ["el fotógrafo", "摄影师", "photo-taker", "phot"],
    ["fotográfico", "摄影的", "of photos", "phot"],
    ["la fotocopia", "复印件", "copy", "phot"],
    ["el fotón", "光子", "light particle", "phot"],
    ["la fotosíntesis", "光合作用", "light-making", "phot"],
    ["la fototerapia", "光疗", "light treatment", "phot"],
    ["fotogénico", "上镜的", "looks good in photos", "phot"],
    ["fotovoltaico", "光伏的", "light-to-electricity", "phot"],
    ["el astrónomo", "天文学家", "star scientist", "astr"],
    ["astronómico", "天文的,巨大的", "of stars; huge", "astr"],
    ["la astrología", "占星术", "star fortune-telling", "astr"],
    ["el asteroide", "小行星", "small planet", "astr"],
    ["la astrofísica", "天体物理", "star physics", "astr"],
    ["la política", "政治", "government affairs", "polit"],
    ["político", "政治的", "of government", "polit"],
    ["el político", "政治家", "political figure", "polit"],
    ["la policía", "警察", "law enforcement", "polit"],
    ["la metrópoli", "大都市", "major city", "polit"],
    ["metropolitano", "大都市的", "of a big city", "polit"],
    ["cosmopolita", "世界主义的", "worldly", "polit"],
    ["el economista", "经济学家", "economy expert", "econ"],
    ["economizar", "节省", "save", "econ"],
    ["ecológico", "生态的", "environmental", "ecol"],
    ["el ecologista", "生态学家", "environment expert", "ecol"],
    ["químico", "化学的", "of chemistry", "chem"],
    ["el químico", "化学家", "chemistry expert", "chem"],
    ["la bioquímica", "生物化学", "chemistry of life", "chem"],
    ["petroquímico", "石化的", "oil-chemistry", "chem"],
    ["la alquimia", "炼金术", "old chemistry", "chem"],
    ["el alquimista", "炼金术士", "old chemist", "chem"],
    ["matemático", "数学的", "of maths", "math"],
    ["el matemático", "数学家", "maths expert", "math"],
    ["el polímata", "博学者", "widely learned person", "math"],
    ["geométrico", "几何的", "of shapes", "geometr"],
    ["gramatical", "语法的", "of grammar", "gram"],
    ["el diagrama", "图表", "drawing", "gram"],
    ["el anagrama", "字谜", "letter-swap word", "gram"],
    ["el epigrama", "警句", "witty saying", "gram"],
    ["el monograma", "花押字", "initials design", "gram"],
    ["el kilogramo", "千克", "1000 grams", "gram"],
    ["el holograma", "全息图", "3D image", "gram"],
    ["la atrofia", "萎缩", "wasting away", "troph"],
    ["la hipertrofia", "肥大", "overgrowth", "troph"],
    ["la distrofia", "营养不良", "faulty growth", "troph"],
    ["trófico", "营养的", "of nutrition", "troph"],
    ["el zoo", "动物园", "animal park", "zoo"],
    ["la zoología", "动物学", "animal science", "zoo"],
    ["el zoólogo", "动物学家", "animal scientist", "zoo"],
    ["el zodíaco", "黄道带", "star-sign circle", "zoo"],
    ["el protozoo", "原生动物", "single-celled animal", "zoo"],
    ["la ornitología", "鸟类学", "bird science", "ornith"],
    ["el ornitólogo", "鸟类学家", "bird scientist", "ornith"],
    ["la ictiología", "鱼类学", "fish science", "ichthy"],
    ["la entomología", "昆虫学", "insect science", "entom"],
    ["el entomólogo", "昆虫学家", "insect scientist", "entom"],
    ["el hipopótamo", "河马", "river horse", "hipp"],
    ["el hipódromo", "赛马场", "horse track", "hipp"],
    ["la autobiografía", "自传", "own life story", "aut"],
    ["autónomo", "自主的", "self-governing", "aut"],
    ["la autocracia", "独裁", "one-person rule", "aut"],
    ["auténtico", "真正的", "genuine", "aut"],
    ["la autenticidad", "真实性", "genuineness", "aut"],
    ["la autopsia", "尸检", "post-mortem exam", "aut"],
    ["la automatización", "自动化", "machine operation", "aut"],
    ["el autismo", "自闭症", "autism", "aut"],
    ["homogéneo", "同质的", "uniform", "homo"],
    ["el homónimo", "同音词", "same-name word", "homo"],
    ["homosexual", "同性恋的", "same-sex", "homo"],
    ["la homeopatía", "顺势疗法", "like-cures-like", "homo"],
    ["homólogo", "同源的", "corresponding", "homo"],
    ["la metáfora", "隐喻", "figure of speech", "meta"],
    ["metafórico", "隐喻的", "figurative", "meta"],
    ["la metamorfosis", "变形", "transformation", "meta"],
    ["la metafísica", "形而上学", "philosophy of being", "meta"],
    ["metódico", "有条理的", "systematic", "meta"],
    ["la metodología", "方法论", "system of methods", "meta"],
    ["la paradoja", "悖论", "self-contradiction", "para"],
    ["paradójico", "自相矛盾的", "contradictory", "para"],
    ["el parásito", "寄生虫", "freeloader organism", "para"],
    ["paralelo", "平行的", "side by side", "para"],
    ["el parámetro", "参数", "setting", "para"],
    ["el paramédico", "急救员", "emergency medic", "para"],
    ["la paranoia", "偏执", "irrational suspicion", "para"],
    ["la parálisis", "瘫痪", "loss of movement", "para"],
    ["paralizar", "使瘫痪", "disable", "para"],
    ["la epidemia", "流行病", "widespread disease", "epi"],
    ["la epidermis", "表皮", "outer skin", "epi"],
    ["la epilepsia", "癫痫", "seizure disorder", "epi"],
    ["el epitafio", "墓志铭", "tomb inscription", "epi"],
    ["el epicentro", "震中", "quake centre", "epi"],
    ["el epílogo", "尾声", "closing section", "epi"],
    ["la epifanía", "顿悟,主显节", "sudden insight", "epi"],
    ["la endoscopia", "内窥镜检查", "inside viewing", "endo"],
    ["endocrino", "内分泌的", "internal-secreting", "endo"],
    ["endógeno", "内生的", "from within", "endo"],
    ["exótico", "异国的", "foreign", "exo"],
    ["exógeno", "外源的", "from outside", "exo"],
    ["el exoesqueleto", "外骨骼", "outer skeleton", "exo"],
    ["el hemisferio", "半球", "half-globe", "hemi"],
    ["el hemiciclo", "半圆形会场", "half-circle", "hemi"],
    ["el hexágono", "六边形", "six-sided shape", "hexa"],
    ["hexagonal", "六边形的", "six-sided", "hexa"],
    ["la década", "十年", "ten years", "deca"],
    ["el decatlón", "十项全能", "ten-event contest", "deca"],
    ["el decálogo", "十诫", "ten commandments", "deca"],
    ["decimal", "十进制的", "base-ten", "deca"],
    ["el prototipo", "原型", "first model", "proto"],
    ["el protocolo", "协议,礼仪", "set of rules", "proto"],
    ["el protagonista", "主角", "main character", "proto"],
    ["el protón", "质子", "positive particle", "proto"],
    ["la proteína", "蛋白质", "body-building nutrient", "proto"],
    ["la pseudociencia", "伪科学", "fake science", "pseudo"],
    ["la astenia", "无力", "weakness", "sthen"],
    ["la neurastenia", "神经衰弱", "nerve exhaustion", "sthen"],
    ["la neuralgia", "神经痛", "nerve pain", "algia"],
    ["la nostalgia", "怀旧", "homesickness", "algia"],
    ["nostálgico", "怀旧的", "longing for the past", "algia"],
    ["el analgésico", "止痛药", "painkiller", "algia"],
    ["la mialgia", "肌肉痛", "muscle pain", "algia"],
    ["la bronquitis", "支气管炎", "airway inflammation", "itis"],
    ["la artritis", "关节炎", "joint inflammation", "itis"],
    ["la hepatitis", "肝炎", "liver inflammation", "itis"],
    ["la gastritis", "胃炎", "stomach inflammation", "itis"],
    ["la dermatitis", "皮炎", "skin inflammation", "itis"],
    ["la apendicitis", "阑尾炎", "appendix inflammation", "itis"],
    ["la meningitis", "脑膜炎", "brain-lining inflammation", "itis"],
    ["la amigdalitis", "扁桃体炎", "tonsil inflammation", "itis"],
    ["la sinusitis", "鼻窦炎", "sinus inflammation", "itis"],
    ["la conjuntivitis", "结膜炎", "eye inflammation", "itis"],
    ["el carcinoma", "癌", "cancer tumour", "oma"],
    ["el melanoma", "黑色素瘤", "skin cancer", "oma"],
    ["el linfoma", "淋巴瘤", "lymph tumour", "oma"],
    ["el glaucoma", "青光眼", "eye-pressure disease", "oma"],
    ["el sarcoma", "肉瘤", "tissue tumour", "oma"],
    ["el pronóstico", "预后", "forecast", "osis"],
    ["la neurosis", "神经症", "anxiety disorder", "osis"],
    ["la psicosis", "精神病", "loss of reality", "osis"],
    ["la tuberculosis", "结核病", "lung disease", "osis"],
    ["la ósmosis", "渗透", "gradual absorption", "osis"],
    ["la hipnosis", "催眠", "trance state", "osis"],
    ["la trombosis", "血栓", "blood clot", "osis"],
    ["la apendicectomía", "阑尾切除", "appendix removal", "ectomy"],
    ["la amigdalectomía", "扁桃体切除", "tonsil removal", "ectomy"],
    ["la anatomía", "解剖学", "body structure", "ectomy"],
    ["anatómico", "解剖的", "of body structure", "ectomy"],
    ["la dicotomía", "二分法", "split in two", "ectomy"],
    ["el podio", "讲台,领奖台", "platform", "podo"],
    ["el podólogo", "足科医生", "foot doctor", "podo"],
    ["las antípodas", "对跖点", "opposite side of earth", "podo"],
    ["el artrópodo", "节肢动物", "jointed-leg animal", "arthr"],
    ["la artroscopia", "关节镜检查", "joint viewing", "arthr"],
    ["la miopía", "近视", "short-sightedness", "ops"],
    ["miope", "近视的", "short-sighted", "ops"],
    ["la miocarditis", "心肌炎", "heart-muscle inflammation", "my"],
    ["la miología", "肌学", "muscle science", "my"],
    ["la encefalitis", "脑炎", "brain inflammation", "encephal"],
    ["el electroencefalograma", "脑电图", "brain-wave trace", "encephal"],
    ["la glucosa", "葡萄糖", "blood sugar", "glyc"],
    ["la glicerina", "甘油", "sweet oil", "glyc"],
    ["la hipoglucemia", "低血糖", "low blood sugar", "glyc"],
    ["la citología", "细胞学", "cell science", "cyt"],
    ["el citoplasma", "细胞质", "cell substance", "cyt"],
    ["el leucocito", "白细胞", "white blood cell", "cyt"],
    ["el eritrocito", "红细胞", "red blood cell", "cyt"],
    ["el linfocito", "淋巴细胞", "immune cell", "cyt"],
    ["el núcleo", "核", "centre", "nucle"],
    ["nuclear", "核的", "atomic", "nucle"],
    ["el nucleótido", "核苷酸", "DNA unit", "nucle"],
    ["la clorofila", "叶绿素", "green leaf pigment", "phyll"],
    ["el rizoma", "根茎", "underground stem", "rhiz"],
    ["la enzima", "酶", "biological catalyst", "zym"],
    ["el imán", "磁铁", "attracting metal", "magnet"],
    ["magnético", "磁的", "attracting", "magnet"],
    ["el magnetismo", "磁性", "magnetic force", "magnet"],
    ["electromagnético", "电磁的", "electric-magnetic", "magnet"],
    ["atómico", "原子的", "of atoms", "atom"],
    ["la idolatría", "偶像崇拜", "image worship", "latr"],
    ["el idólatra", "偶像崇拜者", "image worshipper", "latr"],
    ["el síndrome", "综合征", "set of symptoms", "drom"],
    ["el aeródromo", "小型机场", "airfield", "drom"],
    ["el palíndromo", "回文", "reads-same-backwards", "drom"],
    ["el velódromo", "自行车赛场", "cycling track", "drom"],
    ["el dromedario", "单峰驼", "running camel", "drom"],
    ["balístico", "弹道的", "of projectiles", "bolo"],
    ["la balística", "弹道学", "projectile science", "bolo"],
    ["problemático", "有问题的", "difficult", "bolo"],
    ["simbólico", "象征的", "representing", "bolo"],
    ["simbolizar", "象征", "stand for", "bolo"],
    ["diabólico", "恶魔般的", "devilish", "bolo"],
    ["la tesis", "论文,论点", "argument", "thes"],
    ["la hipótesis", "假设", "proposed explanation", "thes"],
    ["hipotético", "假设的", "supposed", "thes"],
    ["sintético", "合成的", "artificial", "thes"],
    ["sintetizar", "合成", "combine", "thes"],
    ["la antítesis", "对立面", "direct opposite", "thes"],
    ["el paréntesis", "括号", "bracket", "thes"],
    ["la prótesis", "假体", "artificial body part", "thes"],
    ["el tema", "主题", "subject", "thes"],
    ["temático", "主题的", "of the subject", "thes"],
    ["el epíteto", "称号", "descriptive name", "thes"],
    ["el fenómeno", "现象", "observable event", "phen"],
    ["fenomenal", "非凡的", "remarkable", "phen"],
    ["la fase", "阶段", "stage", "phen"],
    ["el énfasis", "强调", "stress", "phen"],
    ["enfatizar", "强调", "stress", "phen"],
    ["la fantasía", "幻想", "imagination", "phen"],
    ["fantástico", "极好的,奇幻的", "wonderful", "phen"],
    ["el fantasma", "幽灵", "ghost", "phen"],
    ["diáfano", "透明的", "see-through", "phen"],
    ["la óptica", "光学", "science of light", "ops"],
    ["óptico", "光学的,视觉的", "of sight", "ops"],
    ["el óptico", "配镜师", "glasses-maker", "ops"],
    ["la sinopsis", "概要", "summary", "ops"],
    ["la biopsia", "活检", "tissue sample test", "ops"],
    ["acústico", "声学的", "of sound", "acou"],
    ["la acústica", "声学", "sound science", "acou"],
    ["estético", "美学的", "of beauty", "aesth"],
    ["la estética", "美学", "study of beauty", "aesth"],
    ["la anestesia", "麻醉", "numbing", "aesth"],
    ["el anestésico", "麻醉剂", "numbing drug", "aesth"],
    ["el anestesista", "麻醉师", "numbing doctor", "aesth"],
    ["mnemotécnico", "助记的", "memory-aiding", "mnem"],
    ["la amnistía", "大赦", "official pardon", "mnem"],
    ["el glosario", "词汇表", "word list", "gloss"],
    ["el políglota", "通晓多语者", "many-language speaker", "gloss"],
    ["la epiglotis", "会厌", "throat flap", "gloss"],
    ["la glosa", "注释", "explanatory note", "gloss"],
    ["la retórica", "修辞", "art of persuasion", "rhet"],
    ["retórico", "修辞的", "for effect", "rhet"],
    ["la coreografía", "编舞", "dance design", "chore"],
    ["el coreógrafo", "编舞者", "dance designer", "chore"],
    ["el coro", "合唱团", "choir", "chore"],
    ["coral", "合唱的", "of a choir", "chore"],
    ["melódico", "旋律的", "tuneful", "melo"],
    ["melodramático", "夸张的", "over-dramatic", "melo"],
    ["la armonía", "和谐", "agreement", "harmon"],
    ["armonioso", "和谐的", "well-matched", "harmon"],
    ["armonizar", "使和谐", "bring into agreement", "harmon"],
    ["la armónica", "口琴", "mouth organ", "harmon"],
    ["la jerarquía", "等级制", "ranking order", "hier"],
    ["jerárquico", "等级的", "ranked", "hier"],
    ["el jeroglífico", "象形文字", "sacred carving", "hier"],
    ["el icono", "图标,圣像", "image", "icon"],
    ["icónico", "标志性的", "symbolic", "icon"],
    ["el iconoclasta", "破除偶像者", "image-breaker", "icon"],
    ["la iconografía", "图像学", "image study", "icon"],
    ["el idioma", "习语,语言", "expression; language", "idio"],
    ["idiomático", "地道的", "natural-sounding", "idio"],
    ["el idiota", "傻瓜", "fool", "idio"],
    ["idiota", "愚蠢的", "foolish", "idio"],
    ["la idiosincrasia", "个人癖好", "personal quirk", "idio"],
    ["cinematográfico", "电影的", "of film", "cine"],
    ["cinético", "动力的", "of motion", "cine"],
    ["la kinesiología", "运动机能学", "movement science", "cine"],
    ["la telequinesis", "隔空移物", "mind-moving", "cine"],
    ["la energía", "能量", "power", "ergo"],
    ["enérgico", "精力充沛的", "full of energy", "ergo"],
    ["ergonómico", "符合人体工学的", "comfortable to use", "ergo"],
    ["la cirugía", "外科手术", "operation", "ergo"],
    ["el cirujano", "外科医生", "operating doctor", "ergo"],
    ["quirúrgico", "外科的", "of operations", "ergo"],
    ["la metalurgia", "冶金", "metal-working", "ergo"],
    ["la liturgia", "礼拜仪式", "worship service", "ergo"],
    ["la alergia", "过敏", "allergic reaction", "ergo"],
    ["alérgico", "过敏的", "reacting badly", "ergo"],
    ["la hélice", "螺旋", "spiral", "heli"],
    ["el helicóptero", "直升机", "rotor aircraft", "heli"],
    ["helicoidal", "螺旋形的", "spiral-shaped", "heli"],
    ["heterogéneo", "异质的", "mixed", "heter"],
    ["heterosexual", "异性恋的", "opposite-sex", "heter"],
    ["heterodoxo", "非正统的", "unorthodox", "heter"],
    ["el aristócrata", "贵族", "noble person", "aristo"],
    ["aristocrático", "贵族的", "noble", "aristo"],
    ["la oligarquía", "寡头政治", "rule by few", "olig"],
    ["el oligarca", "寡头", "powerful few", "olig"],
    ["la plétora", "过多", "excess", "pleth"],
    ["la eutanasia", "安乐死", "mercy killing", "thanat"],
    ["geriátrico", "老年病的", "of old age", "ger"],
    ["la geriatría", "老年医学", "old-age medicine", "ger"],
    ["la gerontología", "老年学", "ageing science", "ger"],
    ["la pediatría", "儿科", "child medicine", "paed"],
    ["el pediatra", "儿科医生", "child doctor", "paed"],
    ["la pedagogía", "教育学", "teaching method", "paed"],
    ["pedagógico", "教学的", "of teaching", "paed"],
    ["ortopédico", "骨科的", "bone-correcting", "paed"],
    ["la ginecología", "妇科", "women's medicine", "gyn"],
    ["el ginecólogo", "妇科医生", "women's doctor", "gyn"],
    ["la misoginia", "厌女", "hatred of women", "gyn"],
    ["el androide", "人形机器人", "human-like robot", "andr"],
    ["andrógino", "雌雄同体的", "both-sex", "andr"],
    ["la poliandria", "一妻多夫", "many husbands", "andr"],
    ["la estenografía", "速记", "shorthand", "steno"],
    ["la estenosis", "狭窄", "narrowing", "steno"],
    ["la bradicardia", "心动过缓", "slow heartbeat", "brady"],
    ["el tacómetro", "转速表", "speed gauge", "tachy"],
    ["el barómetro", "气压计", "pressure gauge", "baro"],
    ["barométrico", "气压的", "of pressure", "baro"],
    ["el barítono", "男中音", "deep male voice", "baro"],
    ["sísmico", "地震的", "of earthquakes", "seism"],
    ["la sismología", "地震学", "earthquake science", "seism"],
    ["el sismógrafo", "地震仪", "quake recorder", "seism"],
    ["criogénico", "低温的", "very cold", "cryo"],
    ["la crioterapia", "冷冻疗法", "cold treatment", "cryo"],
    ["la xerófita", "旱生植物", "dry-land plant", "xero"],
    ["el higrómetro", "湿度计", "moisture gauge", "hygr"],
    ["la higiene", "卫生", "cleanliness", "hygr"],
    ["higiénico", "卫生的", "clean", "hygr"],
    ["el meteoro", "流星", "shooting star", "meteor"],
    ["el meteorito", "陨石", "fallen space rock", "meteor"],
    ["la meteorología", "气象学", "weather science", "meteor"],
    ["el meteorólogo", "气象学家", "weather scientist", "meteor"],
    ["el océano", "海洋", "sea", "ocean"],
    ["oceánico", "海洋的", "of the ocean", "ocean"],
    ["la oceanografía", "海洋学", "ocean science", "ocean"],
    ["la Polinesia", "波利尼西亚", "many islands", "nes"],
    ["Indonesia", "印度尼西亚", "Indian islands", "nes"],
    ["el Peloponeso", "伯罗奔尼撒", "island of Pelops", "nes"],
    ["Mesopotamia", "美索不达米亚", "between rivers", "potam"],
    ["la talasoterapia", "海水疗法", "sea treatment", "thalass"],
    ["la urología", "泌尿科", "urinary medicine", "ur"],
    ["el urólogo", "泌尿科医生", "urinary doctor", "ur"],
    ["la orina", "尿", "urine", "ur"],
    ["el diurético", "利尿剂", "water pill", "ur"],
    ["el antipirético", "退烧药", "fever-reducer", "pyret"],
    ["el narcótico", "麻醉品", "numbing drug", "narc"],
    ["la narcosis", "麻醉状态", "drug stupor", "narc"],
    ["la narcolepsia", "发作性睡病", "sleep attacks", "narc"],
    ["hipnótico", "催眠的", "sleep-inducing", "hypn"],
    ["hipnotizar", "催眠", "put in a trance", "hypn"],
    ["el hipnotizador", "催眠师", "trance-inducer", "hypn"],
    ["la esquizofrenia", "精神分裂症", "split mind", "phren"],
    ["frenético", "狂热的", "frantic", "phren"],
    ["el frenesí", "狂乱", "wild excitement", "phren"],
    ["paranoico", "偏执的", "irrationally suspicious", "nous"],
    ["el ethos", "精神特质", "character", "ethic"],
    ["ortodoxo", "正统的", "conventional", "dox"],
    ["la ortodoxia", "正统", "accepted belief", "dox"],
    ["la doxología", "荣耀颂", "hymn of praise", "dox"],
    ["la herejía", "异端", "false belief", "heres"],
    ["el hereje", "异端者", "dissenter", "heres"],
    ["herético", "异端的", "against doctrine", "heres"],
    ["el mártir", "殉道者", "one who dies for belief", "martyr"],
    ["el martirio", "殉道", "death for belief", "martyr"],
    ["el ángel", "天使", "heavenly messenger", "angel"],
    ["angelical", "天使般的", "like an angel", "angel"],
    ["el arcángel", "大天使", "chief angel", "angel"],
    ["evangélico", "福音派的", "of the gospel", "evangel"],
    ["el evangelista", "传福音者", "gospel preacher", "evangel"],
    ["el evangelio", "福音", "good news", "evangel"],
    ["el apocalipsis", "天启,末日", "revelation; end of world", "apocal"],
    ["apocalíptico", "末日的", "world-ending", "apocal"],
    ["el misterio", "神秘", "secret", "myst"],
    ["misterioso", "神秘的", "puzzling", "myst"],
    ["el místico", "神秘主义者", "spiritual seeker", "myst"],
    ["místico", "神秘主义的", "spiritual", "myst"],
    ["el misticismo", "神秘主义", "spiritual belief", "myst"],
    ["mistificar", "使迷惑", "puzzle", "myst"]
  );
})();
