/* =====================================================
   FUGA MYTHICA — CURSUS German 🇩🇪 · batch 13 — everyday topical vocabulary (verbs, adjectives, materials, tools, car, kitchen,
   family, personal care, fashion, shopping, food, travel, emergencies, colours, geography, celebrations, phone & mail)
   ===================================================== */
(function () {
  const p = VOCAB.de;
  Object.assign(p.roots, { topic: ["主题词汇", "领域词汇,无词根", "everyday topics"] });
  p.words.push(
    ["reiben", "磨碎", "grate", "topic"],
    ["dämpfen", "蒸", "steam", "topic"],
    ["marinieren", "腌", "marinate", "topic"],
    ["gießen", "倒,浇", "pour", "topic"],
    ["verschütten", "洒出", "spill", "topic"],
    ["schmelzen", "融化", "melt", "topic"],
    ["einfrieren", "冷冻", "freeze", "topic"],
    ["auftauen", "解冻", "thaw", "topic"],
    ["kauen", "咀嚼", "chew", "topic"],
    ["schlucken", "吞咽", "swallow", "topic"],
    ["nippen", "小口喝", "sip", "topic"],
    ["beißen", "咬", "bite", "topic"],
    ["lecken", "舔", "lick", "topic"],
    ["schnüffeln", "嗅", "sniff", "topic"],
    ["niesen", "打喷嚏", "sneeze", "topic"],
    ["gähnen", "打哈欠", "yawn", "topic"],
    ["blinzeln", "眨眼", "blink", "topic"],
    ["zwinkern", "使眼色", "wink", "topic"],
    ["nicken", "点头", "nod", "topic"],
    ["winken", "挥手", "wave", "topic"],
    ["klatschen", "鼓掌", "clap", "topic"],
    ["pfeifen", "吹口哨", "whistle", "topic"],
    ["summen", "哼唱", "hum", "topic"],
    ["flüstern", "耳语", "whisper", "topic"],
    ["murmeln", "嘟囔", "mutter", "topic"],
    ["kreischen", "尖叫", "scream", "topic"],
    ["schluchzen", "抽泣", "sob", "topic"],
    ["kichern", "傻笑", "giggle", "topic"],
    ["grinsen", "咧嘴笑", "grin", "topic"],
    ["starren", "凝视", "stare", "topic"],
    ["spähen", "窥视", "peek", "topic"],
    ["krabbeln", "爬行", "crawl", "topic"],
    ["schleichen", "蹑手蹑脚", "creep", "topic"],
    ["stolpern", "绊倒", "stumble", "topic"],
    ["ausrutschen", "滑倒", "slip", "topic"],
    ["hinken", "跛行", "limp", "topic"],
    ["schlendern", "闲逛", "stroll", "topic"],
    ["marschieren", "行军", "march", "topic"],
    ["rennen", "奔跑", "run", "topic"],
    ["hüpfen", "蹦跳", "hop", "topic"],
    ["rudern", "划船", "row", "topic"],
    ["segeln", "航行", "sail", "topic"],
    ["lenken", "驾驶,操控", "steer", "topic"],
    ["rückwärtsfahren", "倒车", "reverse", "topic"],
    ["schleudern", "打滑", "skid", "topic"],
    ["abschleppen", "拖车", "tow", "topic"],
    ["trampen", "搭便车", "hitchhike", "topic"],
    ["pendeln", "通勤", "commute", "topic"],
    ["einchecken", "办理登机", "check in", "topic"],
    ["auspacken", "打开行李", "unpack", "topic"],
    ["stricken", "织毛衣", "knit", "topic"],
    ["falten", "折叠", "fold", "topic"],
    ["wischen", "擦", "wipe", "topic"],
    ["schrubben", "刷洗", "scrub", "topic"],
    ["fegen", "扫", "sweep", "topic"],
    ["abstauben", "除尘", "dust", "topic"],
    ["polieren", "抛光", "polish", "topic"],
    ["spülen", "冲洗", "rinse", "topic"],
    ["einweichen", "浸泡", "soak", "topic"],
    ["abtropfen", "沥干", "drain", "topic"],
    ["auspressen", "挤压", "squeeze", "topic"],
    ["einwickeln", "包裹", "wrap", "topic"],
    ["auswickeln", "拆开", "unwrap", "topic"],
    ["zuknöpfen", "扣扣子", "button up", "topic"],
    ["hämmern", "锤打", "hammer", "topic"],
    ["bohren", "钻", "drill", "topic"],
    ["schrauben", "拧螺丝", "screw", "topic"],
    ["sägen", "锯", "saw", "topic"],
    ["nageln", "钉", "nail", "topic"],
    ["kleben", "粘", "glue", "topic"],
    ["streichen", "刷漆", "paint", "topic"],
    ["schleifen", "打磨", "sand", "topic"],
    ["schweißen", "焊接", "weld", "topic"],
    ["graben", "挖", "dig", "topic"],
    ["pflanzen", "种植", "plant", "topic"],
    ["beschneiden", "修剪", "prune", "topic"],
    ["mähen", "割草", "mow", "topic"],
    ["melken", "挤奶", "milk", "topic"],
    ["füttern", "喂", "feed", "topic"],
    ["züchten", "饲养", "breed", "topic"],
    ["jagen", "打猎", "hunt", "topic"],
    ["verstecken", "隐藏", "hide", "topic"],
    ["schnappen", "夺", "snatch", "topic"],
    ["boxen", "用拳打", "punch", "topic"],
    ["ohrfeigen", "打耳光", "slap", "topic"],
    ["streicheln", "抚摸", "stroke", "topic"],
    ["kitzeln", "挠痒", "tickle", "topic"],
    ["kratzen", "抓挠", "scratch", "topic"],
    ["kneifen", "捏", "pinch", "topic"],
    ["schütteln", "摇晃", "shake", "topic"],
    ["zittern", "颤抖", "tremble", "topic"],
    ["frösteln", "发抖", "shiver", "topic"],
    ["schwitzen", "出汗", "sweat", "topic"],
    ["ohnmächtig werden", "晕倒", "faint", "topic"],
    ["husten", "咳嗽", "cough", "topic"],
    ["sich übergeben", "呕吐", "vomit", "topic"],
    ["jucken", "发痒", "itch", "topic"],
    ["spritzen", "注射", "inject", "topic"],
    ["verschreiben", "开处方", "prescribe", "topic"],
    ["feilschen", "讨价还价", "bargain", "topic"],
    ["einstellen", "雇用", "hire", "topic"],
    ["leihen", "借", "lend", "topic"],
    ["sich leihen", "借入", "borrow", "topic"],
    ["erstatten", "退款", "refund", "topic"],
    ["sich leisten", "负担得起", "afford", "topic"],
    ["verschwenden", "浪费", "waste", "topic"],
    ["spenden", "捐赠", "donate", "topic"],
    ["freisprechen", "宣告无罪", "acquit", "topic"],
    ["Berufung einlegen", "上诉", "appeal", "topic"],
    ["aussagen", "作证", "testify", "topic"],
    ["verhaften", "逮捕", "arrest", "topic"],
    ["entführen", "绑架", "kidnap", "topic"],
    ["ausrauben", "抢劫", "rob", "topic"],
    ["bestechen", "贿赂", "bribe", "topic"],
    ["schmuggeln", "走私", "smuggle", "topic"],
    ["spionieren", "监视", "spy", "topic"],
    ["drohen", "威胁", "threaten", "topic"],
    ["erpressen", "敲诈", "blackmail", "topic"],
    ["protestieren", "抗议", "protest", "topic"],
    ["reformieren", "改革", "reform", "topic"],
    ["sich anmelden", "登录", "log in", "topic"],
    ["sich abmelden", "登出", "log out", "topic"],
    ["hochladen", "上传", "upload", "topic"],
    ["herunterladen", "下载", "download", "topic"],
    ["surfen", "浏览", "browse", "topic"],
    ["klicken", "点击", "click", "topic"],
    ["scrollen", "滚动", "scroll", "topic"],
    ["tippen", "打字", "type", "topic"],
    ["löschen", "删除", "delete", "topic"],
    ["scannen", "扫描", "scan", "topic"],
    ["installieren", "安装", "install", "topic"],
    ["aktualisieren", "更新", "update", "topic"],
    ["neu starten", "重启", "restart", "topic"],
    ["abstürzen", "崩溃", "crash", "topic"],
    ["verschlüsseln", "加密", "encrypt", "topic"],
    ["streamen", "流播", "stream", "topic"],
    ["abonnieren", "订阅", "subscribe", "topic"],
    ["dolmetschen", "口译", "interpret", "topic"],
    ["aufsagen", "背诵", "recite", "topic"],
    ["schummeln", "作弊", "cheat", "topic"],
    ["sich einschreiben", "注册入学", "enrol", "topic"],
    ["schwänzen", "逃课", "skip class", "topic"],
    ["schimpfen", "责骂", "scold", "topic"],
    ["verwöhnen", "宠坏", "spoil", "topic"],
    ["adoptieren", "收养", "adopt", "topic"],
    ["großziehen", "抚养", "raise", "topic"],
    ["babysitten", "照看孩子", "babysit", "topic"],
    ["sich verloben", "订婚", "get engaged", "topic"],
    ["sich scheiden lassen", "离婚", "get divorced", "topic"],
    ["flirten", "调情", "flirt", "topic"],
    ["sich trennen", "分手", "break up", "topic"],
    ["tratschen", "八卦", "gossip", "topic"],
    ["necken", "取笑", "tease", "topic"],
    ["mobben", "欺凌", "bully", "topic"],
    ["beleidigen", "侮辱", "insult", "topic"],
    ["sich entschuldigen", "道歉", "apologize", "topic"],
    ["beneiden", "嫉妒", "envy", "topic"],
    ["bewundern", "钦佩", "admire", "topic"],
    ["trauern", "哀悼", "grieve", "topic"],
    ["bestehen auf", "坚持", "insist", "topic"],
    ["ablehnen", "拒绝", "refuse", "topic"],
    ["sich beschweren", "抱怨", "complain", "topic"],
    ["prahlen", "吹嘘", "boast", "topic"],
    ["vortäuschen", "假装", "pretend", "topic"],
    ["gestehen", "承认", "confess", "topic"],
    ["leugnen", "否认", "deny", "topic"],
    ["sich fragen", "想知道", "wonder", "topic"],
    ["sich erinnern", "回忆", "recall", "topic"],
    ["schlussfolgern", "得出结论", "conclude", "topic"],
    ["vorhersagen", "预测", "predict", "topic"],
    ["einordnen", "分类", "classify", "topic"],
    ["betonen", "强调", "emphasize", "topic"],
    ["andeuten", "暗示", "imply", "topic"],
    ["veranschaulichen", "说明", "illustrate", "topic"],
    ["kontaktfreudig", "外向的", "outgoing", "topic"],
    ["gesprächig", "健谈的", "talkative", "topic"],
    ["empfindlich", "敏感的", "sensitive", "topic"],
    ["gerissen", "狡猾的", "cunning", "topic"],
    ["witzig", "机智的", "witty", "topic"],
    ["zerstreut", "心不在焉的", "absent-minded", "topic"],
    ["unordentlich", "凌乱的", "messy", "topic"],
    ["robust", "结实的", "sturdy", "topic"],
    ["glatt", "光滑的", "smooth", "topic"],
    ["rau", "粗糙的", "rough", "topic"],
    ["stumpf", "钝的", "blunt", "topic"],
    ["klebrig", "黏的", "sticky", "topic"],
    ["rutschig", "滑的", "slippery", "topic"],
    ["steif", "僵硬的", "stiff", "topic"],
    ["hohl", "空心的", "hollow", "topic"],
    ["massiv", "坚固的", "solid", "topic"],
    ["durchsichtig", "透明的", "transparent", "topic"],
    ["undurchsichtig", "不透明的", "opaque", "topic"],
    ["matt", "暗淡的", "dull", "topic"],
    ["feucht", "潮湿的", "damp", "topic"],
    ["durchnässt", "湿透的", "soaked", "topic"],
    ["knusprig", "脆的", "crisp", "topic"],
    ["zart", "嫩的", "tender", "topic"],
    ["zäh", "硬的", "tough", "topic"],
    ["altbacken", "不新鲜的", "stale", "topic"],
    ["reif", "成熟的", "ripe", "topic"],
    ["verfault", "腐烂的", "rotten", "topic"],
    ["fade", "淡而无味的", "bland", "topic"],
    ["fettig", "油腻的", "greasy", "topic"],
    ["saftig", "多汁的", "juicy", "topic"],
    ["der Stahl", "钢", "steel", "topic"],
    ["das Kupfer", "铜", "copper", "topic"],
    ["das Messing", "黄铜", "brass", "topic"],
    ["das Aluminium", "铝", "aluminium", "topic"],
    ["das Zinn", "锡", "tin", "topic"],
    ["das Blei", "铅", "lead", "topic"],
    ["der Gummi", "橡胶", "rubber", "topic"],
    ["das Leinen", "亚麻", "linen", "topic"],
    ["der Samt", "天鹅绒", "velvet", "topic"],
    ["der Zement", "水泥", "cement", "topic"],
    ["der Ziegel", "砖", "brick", "topic"],
    ["die Fliese", "瓷砖", "tile", "topic"],
    ["der Marmor", "大理石", "marble", "topic"],
    ["der Ton", "黏土", "clay", "topic"],
    ["die Pappe", "硬纸板", "cardboard", "topic"],
    ["der Schaumstoff", "泡沫", "foam", "topic"],
    ["der Draht", "铁丝", "wire", "topic"],
    ["das Seil", "绳子", "rope", "topic"],
    ["die Schnur", "细绳", "string", "topic"],
    ["der Faden", "线", "thread", "topic"],
    ["der Haken", "钩子", "hook", "topic"],
    ["der Nagel", "钉子", "nail", "topic"],
    ["die Schraube", "螺丝", "screw", "topic"],
    ["der Bolzen", "螺栓", "bolt", "topic"],
    ["der Schraubenzieher", "螺丝刀", "screwdriver", "topic"],
    ["der Schraubenschlüssel", "扳手", "wrench", "topic"],
    ["die Zange", "钳子", "pliers", "topic"],
    ["die Säge", "锯", "saw", "topic"],
    ["die Leiter", "梯子", "ladder", "topic"],
    ["der Eimer", "水桶", "bucket", "topic"],
    ["die Schaufel", "铲子", "shovel", "topic"],
    ["der Rechen", "耙子", "rake", "topic"],
    ["die Axt", "斧头", "axe", "topic"],
    ["das Maßband", "卷尺", "tape measure", "topic"],
    ["der Werkzeugkasten", "工具箱", "toolbox", "topic"],
    ["das Rad", "车轮", "wheel", "topic"],
    ["der Scheinwerfer", "前灯", "headlight", "topic"],
    ["der Scheibenwischer", "雨刷", "wiper", "topic"],
    ["die Motorhaube", "引擎盖", "bonnet", "topic"],
    ["der Kofferraum", "后备箱", "boot", "topic"],
    ["der Rückspiegel", "后视镜", "mirror", "topic"],
    ["die Hupe", "喇叭", "horn", "topic"],
    ["die Kupplung", "离合器", "clutch", "topic"],
    ["der Kraftstoff", "燃料", "fuel", "topic"],
    ["der Auspuff", "排气管", "exhaust", "topic"],
    ["das Nummernschild", "车牌", "number plate", "topic"],
    ["der Kochtopf", "炖锅", "saucepan", "topic"],
    ["die Bratpfanne", "煎锅", "frying pan", "topic"],
    ["die Teekanne", "茶壶", "teapot", "topic"],
    ["der Krug", "壶", "jug", "topic"],
    ["das Tablett", "托盘", "tray", "topic"],
    ["die Kelle", "长柄勺", "ladle", "topic"],
    ["der Schneebesen", "打蛋器", "whisk", "topic"],
    ["das Nudelholz", "擀面杖", "rolling pin", "topic"],
    ["das Schneidebrett", "砧板", "chopping board", "topic"],
    ["der Korkenzieher", "开瓶器", "corkscrew", "topic"],
    ["der Dosenöffner", "开罐器", "tin opener", "topic"],
    ["die Gefriertruhe", "冷冻柜", "freezer", "topic"],
    ["die Schürze", "围裙", "apron", "topic"],
    ["die Tischdecke", "桌布", "tablecloth", "topic"],
    ["die Dose", "罐头", "tin", "topic"],
    ["der Korken", "软木塞", "cork", "topic"],
    ["die Tube", "管", "tube", "topic"],
    ["die Kiste", "板条箱", "crate", "topic"],
    ["der Korb", "篮子", "basket", "topic"],
    ["das Quadrat", "正方形", "square", "topic"],
    ["das Oval", "椭圆", "oval", "topic"],
    ["die Kugel", "球体", "sphere", "topic"],
    ["der Zylinder", "圆柱", "cylinder", "topic"],
    ["der Kegel", "圆锥", "cone", "topic"],
    ["die Pyramide", "金字塔", "pyramid", "topic"],
    ["die Kurve", "曲线", "curve", "topic"],
    ["der Winkel", "角", "angle", "topic"],
    ["die Breite", "宽度", "width", "topic"],
    ["das Volumen", "体积", "volume", "topic"],
    ["der Prozentsatz", "百分比", "percentage", "topic"],
    ["die Summe", "总和", "sum", "topic"],
    ["der Taschenrechner", "计算器", "calculator", "topic"],
    ["der Kompass", "指南针", "compass", "topic"],
    ["der Stiefvater", "继父", "stepfather", "topic"],
    ["die Stiefmutter", "继母", "stepmother", "topic"],
    ["der Schwiegervater", "岳父,公公", "father-in-law", "topic"],
    ["die Schwiegermutter", "岳母,婆婆", "mother-in-law", "topic"],
    ["der Schwiegersohn", "女婿", "son-in-law", "topic"],
    ["die Schwiegertochter", "儿媳", "daughter-in-law", "topic"],
    ["der Schwager", "姐夫,妹夫", "brother-in-law", "topic"],
    ["die Schwägerin", "嫂子,弟媳", "sister-in-law", "topic"],
    ["der Enkel", "孙子", "grandson", "topic"],
    ["die Enkelin", "孙女", "granddaughter", "topic"],
    ["das Einzelkind", "独生子女", "only child", "topic"],
    ["die Waise", "孤儿", "orphan", "topic"],
    ["die Witwe", "寡妇", "widow", "topic"],
    ["der Witwer", "鳏夫", "widower", "topic"],
    ["die Braut", "新娘", "bride", "topic"],
    ["der Bräutigam", "新郎", "groom", "topic"],
    ["der Pate", "教父", "godfather", "topic"],
    ["der Fremde", "陌生人", "stranger", "topic"],
    ["der Mitbewohner", "室友", "roommate", "topic"],
    ["die Flitterwochen", "蜜月", "honeymoon", "topic"],
    ["die Taufe", "洗礼", "christening", "topic"],
    ["der Sarg", "棺材", "coffin", "topic"],
    ["das Grab", "坟墓", "grave", "topic"],
    ["die Zahnbürste", "牙刷", "toothbrush", "topic"],
    ["die Zahnpasta", "牙膏", "toothpaste", "topic"],
    ["das Shampoo", "洗发水", "shampoo", "topic"],
    ["der Rasierer", "剃须刀", "razor", "topic"],
    ["der Kamm", "梳子", "comb", "topic"],
    ["die Haarbürste", "发刷", "hairbrush", "topic"],
    ["der Föhn", "吹风机", "hairdryer", "topic"],
    ["das Parfüm", "香水", "perfume", "topic"],
    ["das Deo", "除臭剂", "deodorant", "topic"],
    ["der Lippenstift", "口红", "lipstick", "topic"],
    ["die Schminke", "化妆品", "make-up", "topic"],
    ["der Nagellack", "指甲油", "nail polish", "topic"],
    ["die Sonnencreme", "防晒霜", "sunscreen", "topic"],
    ["das Taschentuch", "纸巾", "tissue", "topic"],
    ["das Toilettenpapier", "卫生纸", "toilet paper", "topic"],
    ["die Windel", "尿布", "nappy", "topic"],
    ["der Haarschnitt", "理发", "haircut", "topic"],
    ["der Bart", "胡子", "beard", "topic"],
    ["der Schnurrbart", "小胡子", "moustache", "topic"],
    ["der Pony", "刘海", "fringe", "topic"],
    ["der Pferdeschwanz", "马尾辫", "ponytail", "topic"],
    ["die Falte", "皱纹", "wrinkle", "topic"],
    ["die Sommersprosse", "雀斑", "freckle", "topic"],
    ["die Narbe", "疤痕", "scar", "topic"],
    ["die Tätowierung", "纹身", "tattoo", "topic"],
    ["der Ärmel", "袖子", "sleeve", "topic"],
    ["der Kragen", "衣领", "collar", "topic"],
    ["der Reißverschluss", "拉链", "zip", "topic"],
    ["die Kapuze", "兜帽", "hood", "topic"],
    ["die Spitze", "蕾丝", "lace", "topic"],
    ["der Streifen", "条纹", "stripe", "topic"],
    ["das Muster", "花纹", "pattern", "topic"],
    ["gepunktet", "圆点的", "spotted", "topic"],
    ["einfarbig", "素色的", "plain", "topic"],
    ["geblümt", "花卉图案的", "floral", "topic"],
    ["die Weste", "马甲", "waistcoat", "topic"],
    ["die Strickjacke", "开襟毛衣", "cardigan", "topic"],
    ["der Kapuzenpullover", "连帽衫", "hoodie", "topic"],
    ["der Trainingsanzug", "运动服", "tracksuit", "topic"],
    ["die Shorts", "短裤", "shorts", "topic"],
    ["der Bademantel", "睡袍", "dressing gown", "topic"],
    ["der Badeanzug", "泳衣", "swimsuit", "topic"],
    ["die Sandalen", "凉鞋", "sandals", "topic"],
    ["die Hausschuhe", "拖鞋", "slippers", "topic"],
    ["die Turnschuhe", "运动鞋", "trainers", "topic"],
    ["die Stöckelschuhe", "高跟鞋", "high heels", "topic"],
    ["der Schnürsenkel", "鞋带", "shoelace", "topic"],
    ["die Sohle", "鞋底", "sole", "topic"],
    ["die Halskette", "项链", "necklace", "topic"],
    ["das Armband", "手镯", "bracelet", "topic"],
    ["die Brosche", "胸针", "brooch", "topic"],
    ["die Warteschlange", "队列", "queue", "topic"],
    ["das Schnäppchen", "便宜货", "bargain", "topic"],
    ["die Rückerstattung", "退款", "refund", "topic"],
    ["der Umtausch", "换货", "exchange", "topic"],
    ["die Garantie", "保修", "guarantee", "topic"],
    ["das Etikett", "标签", "label", "topic"],
    ["der Strichcode", "条形码", "barcode", "topic"],
    ["der Gutschein", "优惠券", "voucher", "topic"],
    ["die Kundenkarte", "会员卡", "loyalty card", "topic"],
    ["der Online-Einkauf", "网购", "online shopping", "topic"],
    ["der Kundendienst", "客服", "customer service", "topic"],
    ["die Beschwerde", "投诉", "complaint", "topic"],
    ["das Blumengeschäft", "花店", "florist", "topic"],
    ["der Juwelier", "珠宝店", "jeweller", "topic"],
    ["der Gemüsehändler", "蔬果店", "greengrocer", "topic"],
    ["das Fischgeschäft", "鱼店", "fishmonger", "topic"],
    ["das Feinkostgeschäft", "熟食店", "deli", "topic"],
    ["das Schreibwarengeschäft", "文具店", "stationer", "topic"],
    ["der Baumarkt", "五金店", "hardware store", "topic"],
    ["die Reinigung", "干洗店", "dry cleaner", "topic"],
    ["der Waschsalon", "自助洗衣店", "launderette", "topic"],
    ["das Tagesmenü", "套餐", "set menu", "topic"],
    ["die Spezialität", "特色菜", "speciality", "topic"],
    ["der Eintopf", "炖菜", "stew", "topic"],
    ["der Braten", "烤肉", "roast", "topic"],
    ["das Omelett", "煎蛋卷", "omelette", "topic"],
    ["das Sandwich", "三明治", "sandwich", "topic"],
    ["der Pfannkuchen", "薄饼", "pancake", "topic"],
    ["der Blätterteig", "酥皮", "puff pastry", "topic"],
    ["das Ketchup", "番茄酱", "ketchup", "topic"],
    ["die Mayonnaise", "蛋黄酱", "mayonnaise", "topic"],
    ["das Kraut", "香草", "herb", "topic"],
    ["der Zimt", "肉桂", "cinnamon", "topic"],
    ["der Ingwer", "姜", "ginger", "topic"],
    ["die Vanille", "香草", "vanilla", "topic"],
    ["der Kaugummi", "口香糖", "chewing gum", "topic"],
    ["die Chips", "薯片", "crisps", "topic"],
    ["das Popcorn", "爆米花", "popcorn", "topic"],
    ["der Smoothie", "果昔", "smoothie", "topic"],
    ["der Cocktail", "鸡尾酒", "cocktail", "topic"],
    ["der Apfelwein", "苹果酒", "cider", "topic"],
    ["der Likör", "利口酒", "liqueur", "topic"],
    ["der Strohhalm", "吸管", "straw", "topic"],
    ["der Eiswürfel", "冰块", "ice cube", "topic"],
    ["hausgemacht", "自制的", "homemade", "topic"],
    ["zum Mitnehmen", "外带", "takeaway", "topic"],
    ["das Terminal", "航站楼", "terminal", "topic"],
    ["das Gate", "登机口", "gate", "topic"],
    ["das Gepäckband", "传送带", "conveyor belt", "topic"],
    ["die Sicherheitskontrolle", "安检", "security check", "topic"],
    ["die Startbahn", "跑道", "runway", "topic"],
    ["die Besatzung", "机组", "crew", "topic"],
    ["die Flugbegleiterin", "空姐", "stewardess", "topic"],
    ["der Fensterplatz", "靠窗座位", "window seat", "topic"],
    ["die Turbulenz", "颠簸", "turbulence", "topic"],
    ["der Jetlag", "时差", "jet lag", "topic"],
    ["der Zwischenstopp", "中途停留", "stopover", "topic"],
    ["die Rückfahrkarte", "往返票", "return ticket", "topic"],
    ["die einfache Fahrt", "单程票", "single ticket", "topic"],
    ["das Abteil", "隔间", "compartment", "topic"],
    ["der Schlafwagen", "卧铺车", "sleeper", "topic"],
    ["die Lobby", "大堂", "lobby", "topic"],
    ["die Suite", "套房", "suite", "topic"],
    ["der Zimmerservice", "客房服务", "room service", "topic"],
    ["die Vollpension", "全食宿", "full board", "topic"],
    ["die Pauschalreise", "跟团游", "package holiday", "topic"],
    ["die Wechselstube", "货币兑换处", "exchange office", "topic"],
    ["das Feuerwehrauto", "消防车", "fire engine", "topic"],
    ["der Feuerlöscher", "灭火器", "fire extinguisher", "topic"],
    ["der Feueralarm", "火警", "fire alarm", "topic"],
    ["die Erste Hilfe", "急救", "first aid", "topic"],
    ["der Verbandskasten", "急救箱", "first aid kit", "topic"],
    ["die Trage", "担架", "stretcher", "topic"],
    ["die Krücke", "拐杖", "crutch", "topic"],
    ["der Rollstuhl", "轮椅", "wheelchair", "topic"],
    ["der Knochenbruch", "骨折", "fracture", "topic"],
    ["die Vergiftung", "中毒", "poisoning", "topic"],
    ["der Rettungsschwimmer", "救生员", "lifeguard", "topic"],
    ["die Warnung", "警告", "warning", "topic"],
    ["die Sirene", "警报器", "siren", "topic"],
    ["die Evakuierung", "疏散", "evacuation", "topic"],
    ["der Unterschlupf", "避难所", "shelter", "topic"],
    ["der Überlebende", "幸存者", "survivor", "topic"],
    ["das Opfer", "受害者", "victim", "topic"],
    ["beige", "米色", "beige", "topic"],
    ["türkis", "绿松石色", "turquoise", "topic"],
    ["dunkelblau", "深蓝", "navy blue", "topic"],
    ["purpurrot", "深红", "crimson", "topic"],
    ["violett", "紫罗兰色", "violet", "topic"],
    ["olivgrün", "橄榄绿", "olive green", "topic"],
    ["smaragdgrün", "翡翠绿", "emerald", "topic"],
    ["elfenbeinfarben", "象牙色", "ivory", "topic"],
    ["bronzefarben", "青铜色", "bronze", "topic"],
    ["khaki", "卡其色", "khaki", "topic"],
    ["bernsteinfarben", "琥珀色", "amber", "topic"],
    ["blass", "苍白的", "pale", "topic"],
    ["verblasst", "褪色的", "faded", "topic"],
    ["der Farbton", "色调", "shade", "topic"],
    ["der Kontinent", "大陆", "continent", "topic"],
    ["Europa", "欧洲", "Europe", "topic"],
    ["Asien", "亚洲", "Asia", "topic"],
    ["Afrika", "非洲", "Africa", "topic"],
    ["Nordamerika", "北美洲", "North America", "topic"],
    ["Südamerika", "南美洲", "South America", "topic"],
    ["Ozeanien", "大洋洲", "Oceania", "topic"],
    ["die Antarktis", "南极洲", "Antarctica", "topic"],
    ["der Atlantik", "大西洋", "Atlantic", "topic"],
    ["der Pazifik", "太平洋", "Pacific", "topic"],
    ["die Alpen", "阿尔卑斯山", "Alps", "topic"],
    ["der Rhein", "莱茵河", "Rhine", "topic"],
    ["die Donau", "多瑙河", "Danube", "topic"],
    ["der Nil", "尼罗河", "Nile", "topic"],
    ["der Äquator", "赤道", "equator", "topic"],
    ["der Nordpol", "北极", "North Pole", "topic"],
    ["die Tropen", "热带", "tropics", "topic"],
    ["die Halbkugel", "半球", "hemisphere", "topic"],
    ["der Breitengrad", "纬度", "latitude", "topic"],
    ["der Längengrad", "经度", "longitude", "topic"],
    ["die Provinz", "省", "province", "topic"],
    ["Deutschland", "德国", "Germany", "topic"],
    ["Frankreich", "法国", "France", "topic"],
    ["Spanien", "西班牙", "Spain", "topic"],
    ["Italien", "意大利", "Italy", "topic"],
    ["England", "英格兰", "England", "topic"],
    ["das Vereinigte Königreich", "英国", "UK", "topic"],
    ["die Vereinigten Staaten", "美国", "USA", "topic"],
    ["China", "中国", "China", "topic"],
    ["Japan", "日本", "Japan", "topic"],
    ["Russland", "俄罗斯", "Russia", "topic"],
    ["Griechenland", "希腊", "Greece", "topic"],
    ["die Schweiz", "瑞士", "Switzerland", "topic"],
    ["die Niederlande", "荷兰", "Netherlands", "topic"],
    ["Ägypten", "埃及", "Egypt", "topic"],
    ["Indien", "印度", "India", "topic"],
    ["Brasilien", "巴西", "Brazil", "topic"],
    ["das Osterei", "复活节彩蛋", "Easter egg", "topic"],
    ["der Valentinstag", "情人节", "Valentine's Day", "topic"],
    ["der Muttertag", "母亲节", "Mother's Day", "topic"],
    ["die Geburtstagsfeier", "生日派对", "birthday party", "topic"],
    ["der Geburtstagskuchen", "生日蛋糕", "birthday cake", "topic"],
    ["die Kerze", "蜡烛", "candle", "topic"],
    ["der Gastgeber", "主人", "host", "topic"],
    ["der Trinkspruch", "祝酒", "toast", "topic"],
    ["die Glückwunschkarte", "贺卡", "greeting card", "topic"],
    ["das Geschenkpapier", "礼品包装纸", "gift wrap", "topic"],
    ["die Mailbox", "语音信箱", "voicemail", "topic"],
    ["der verpasste Anruf", "未接来电", "missed call", "topic"],
    ["der Klingelton", "铃声", "ringtone", "topic"],
    ["das Ladegerät", "充电器", "charger", "topic"],
    ["die SIM-Karte", "SIM卡", "SIM card", "topic"],
    ["das Festnetz", "座机", "landline", "topic"],
    ["die Postkarte", "明信片", "postcard", "topic"],
    ["das Einschreiben", "挂号信", "registered letter", "topic"],
    ["die Betreffzeile", "主题行", "subject line", "topic"],
    ["die Weiterleitung", "转发", "forward", "topic"],
    ["die Spam-Mail", "垃圾邮件", "spam", "topic"],
    ["der Posteingang", "收件箱", "inbox", "topic"]
  );
})();
