/* =====================================================
   FUGA MYTHICA — CURSUS English 🇬🇧 · batch 8 — topical vocabulary: business, law, IT, media, environment, science, health, society, arts, travel, weather
   ===================================================== */
(function () {
  const p = VOCAB.en;
  Object.assign(p.roots, {"topic": ["主题词汇", "领域词汇,无词根", "everyday topics"]});
  p.words.push(
    ["shareholder", "股东", "shareholder", "topic"],
    ["share", "股票", "share", "topic"],
    ["stock exchange", "证券交易所", "stock market", "topic"],
    ["bond", "债券", "bond", "topic"],
    ["investment", "投资", "investment", "topic"],
    ["investor", "投资者", "investor", "topic"],
    ["profit", "利润", "profit", "topic"],
    ["loss", "亏损", "loss", "topic"],
    ["turnover", "营业额", "turnover", "topic"],
    ["budget", "预算", "budget", "topic"],
    ["balance sheet", "资产负债表", "balance sheet", "topic"],
    ["invoice", "发票", "invoice", "topic"],
    ["deadline", "截止日期", "deadline", "topic"],
    ["loan", "贷款", "loan", "topic"],
    ["interest rate", "利率", "interest rate", "topic"],
    ["savings", "储蓄", "savings", "topic"],
    ["account", "账户", "account", "topic"],
    ["withdrawal", "取款", "withdrawal", "topic"],
    ["exchange rate", "汇率", "exchange rate", "topic"],
    ["inflation", "通胀", "inflation", "topic"],
    ["growth", "增长", "growth", "topic"],
    ["supply", "供给", "supply", "topic"],
    ["competition", "竞争", "competition", "topic"],
    ["competitor", "竞争者", "competitor", "topic"],
    ["customer", "客户", "customer", "topic"],
    ["supplier", "供应商", "supplier", "topic"],
    ["delivery", "交货", "delivery", "topic"],
    ["warehouse", "仓库", "warehouse", "topic"],
    ["stock", "库存", "stock", "topic"],
    ["brand", "品牌", "brand", "topic"],
    ["advertisement", "广告", "advert", "topic"],
    ["marketing", "市场营销", "marketing", "topic"],
    ["sale", "销售", "sale", "topic"],
    ["wholesale", "批发", "wholesale", "topic"],
    ["trade", "贸易", "trade", "topic"],
    ["tariff", "关税", "tariff", "topic"],
    ["VAT", "增值税", "VAT", "topic"],
    ["taxpayer", "纳税人", "taxpayer", "topic"],
    ["accountant", "会计", "accountant", "topic"],
    ["manager", "经理", "manager", "topic"],
    ["employee", "雇员", "employee", "topic"],
    ["employer", "雇主", "employer", "topic"],
    ["staff", "员工", "staff", "topic"],
    ["recruitment", "招聘", "recruitment", "topic"],
    ["redundancy", "裁员", "dismissal", "topic"],
    ["trade union", "工会", "trade union", "topic"],
    ["unemployment", "失业", "unemployment", "topic"],
    ["shift", "班次", "shift", "topic"],
    ["overtime", "加班", "overtime", "topic"],
    ["meeting", "会议", "meeting", "topic"],
    ["agenda", "议程", "agenda", "topic"],
    ["minutes", "会议记录", "minutes", "topic"],
    ["goal", "目标", "goal", "topic"],
    ["negotiation", "谈判", "negotiation", "topic"],
    ["agreement", "协议", "agreement", "topic"],
    ["partnership", "合作关系", "partnership", "topic"],
    ["merger", "合并", "merger", "topic"],
    ["takeover", "收购", "takeover", "topic"],
    ["bankruptcy", "破产", "bankruptcy", "topic"],
    ["startup", "初创公司", "startup", "topic"],
    ["entrepreneur", "企业家", "entrepreneur", "topic"],
    ["law", "法律", "law", "topic"],
    ["bill", "法案", "bill", "topic"],
    ["parliament", "议会", "parliament", "topic"],
    ["government", "政府", "government", "topic"],
    ["prime minister", "总理", "prime minister", "topic"],
    ["ministry", "部", "ministry", "topic"],
    ["mayor", "市长", "mayor", "topic"],
    ["town hall", "市政厅", "town hall", "topic"],
    ["voter", "选民", "voter", "topic"],
    ["poll", "民调", "poll", "topic"],
    ["majority", "多数", "majority", "topic"],
    ["minority", "少数", "minority", "topic"],
    ["coalition", "联合政府", "coalition", "topic"],
    ["referendum", "公投", "referendum", "topic"],
    ["dictatorship", "独裁", "dictatorship", "topic"],
    ["monarchy", "君主制", "monarchy", "topic"],
    ["citizen", "公民", "citizen", "topic"],
    ["citizenship", "公民身份", "citizenship", "topic"],
    ["equality", "平等", "equality", "topic"],
    ["court", "法院", "court", "topic"],
    ["lawyer", "律师", "lawyer", "topic"],
    ["prosecutor", "检察官", "prosecutor", "topic"],
    ["defendant", "被告", "defendant", "topic"],
    ["witness", "证人", "witness", "topic"],
    ["trial", "审判", "trial", "topic"],
    ["prisoner", "囚犯", "prisoner", "topic"],
    ["theft", "盗窃", "theft", "topic"],
    ["thief", "小偷", "thief", "topic"],
    ["murder", "谋杀", "murder", "topic"],
    ["fraud", "欺诈", "fraud", "topic"],
    ["corruption", "腐败", "corruption", "topic"],
    ["bribe", "贿赂", "bribe", "topic"],
    ["smuggling", "走私", "smuggling", "topic"],
    ["investigation", "调查", "investigation", "topic"],
    ["police station", "警察局", "police station", "topic"],
    ["clause", "条款", "clause", "topic"],
    ["notary", "公证人", "notary", "topic"],
    ["inheritance", "遗产", "inheritance", "topic"],
    ["border", "边境", "border", "topic"],
    ["immigrant", "移民", "immigrant", "topic"],
    ["asylum", "庇护", "asylum", "topic"],
    ["embassy", "大使馆", "embassy", "topic"],
    ["ambassador", "大使", "ambassador", "topic"],
    ["alliance", "联盟", "alliance", "topic"],
    ["war", "战争", "war", "topic"],
    ["peace", "和平", "peace", "topic"],
    ["weapon", "武器", "weapon", "topic"],
    ["attack", "攻击", "attack", "topic"],
    ["defence", "防御", "defence", "topic"],
    ["terrorism", "恐怖主义", "terrorism", "topic"],
    ["human rights", "人权", "human rights", "topic"],
    ["laptop", "笔记本电脑", "laptop", "topic"],
    ["tablet", "平板电脑", "tablet", "topic"],
    ["smartphone", "智能手机", "smartphone", "topic"],
    ["screen", "屏幕", "screen", "topic"],
    ["keyboard", "键盘", "keyboard", "topic"],
    ["printer", "打印机", "printer", "topic"],
    ["folder", "文件夹", "folder", "topic"],
    ["software", "软件", "software", "topic"],
    ["hardware", "硬件", "hardware", "topic"],
    ["update", "更新", "update", "topic"],
    ["download", "下载", "download", "topic"],
    ["network", "网络", "network", "topic"],
    ["internet", "互联网", "internet", "topic"],
    ["website", "网站", "website", "topic"],
    ["browser", "浏览器", "browser", "topic"],
    ["search engine", "搜索引擎", "search engine", "topic"],
    ["link", "链接", "link", "topic"],
    ["email", "电子邮件", "email", "topic"],
    ["attachment", "附件", "attachment", "topic"],
    ["password", "密码", "password", "topic"],
    ["user", "用户", "user", "topic"],
    ["server", "服务器", "server", "topic"],
    ["virus", "病毒", "virus", "topic"],
    ["hacker", "黑客", "hacker", "topic"],
    ["artificial intelligence", "人工智能", "AI", "topic"],
    ["robot", "机器人", "robot", "topic"],
    ["algorithm", "算法", "algorithm", "topic"],
    ["code", "代码", "code", "topic"],
    ["social network", "社交网络", "social network", "topic"],
    ["follower", "关注者", "follower", "topic"],
    ["podcast", "播客", "podcast", "topic"],
    ["newspaper", "报纸", "newspaper", "topic"],
    ["magazine", "杂志", "magazine", "topic"],
    ["headline", "标题", "headline", "topic"],
    ["article", "文章", "article", "topic"],
    ["journalist", "记者", "journalist", "topic"],
    ["press conference", "新闻发布会", "press conference", "topic"],
    ["broadcast", "广播节目", "broadcast", "topic"],
    ["channel", "频道", "channel", "topic"],
    ["viewer", "观众", "viewer", "topic"],
    ["listener", "听众", "listener", "topic"],
    ["fake news", "假新闻", "fake news", "topic"],
    ["censorship", "审查", "censorship", "topic"],
    ["environment", "环境", "environment", "topic"],
    ["pollution", "污染", "pollution", "topic"],
    ["climate change", "气候变化", "climate change", "topic"],
    ["global warming", "全球变暖", "global warming", "topic"],
    ["greenhouse effect", "温室效应", "greenhouse effect", "topic"],
    ["emission", "排放", "emission", "topic"],
    ["carbon dioxide", "二氧化碳", "CO2", "topic"],
    ["renewable energy", "可再生能源", "renewable energy", "topic"],
    ["solar panel", "太阳能板", "solar panel", "topic"],
    ["wind turbine", "风力涡轮机", "wind turbine", "topic"],
    ["fossil fuel", "化石燃料", "fossil fuel", "topic"],
    ["oil", "石油", "oil", "topic"],
    ["coal", "煤", "coal", "topic"],
    ["natural gas", "天然气", "natural gas", "topic"],
    ["nuclear power", "核能", "nuclear power", "topic"],
    ["power station", "发电厂", "power station", "topic"],
    ["recycling", "回收", "recycling", "topic"],
    ["waste", "废物", "waste", "topic"],
    ["drought", "干旱", "drought", "topic"],
    ["flood", "洪水", "flood", "topic"],
    ["earthquake", "地震", "earthquake", "topic"],
    ["hurricane", "飓风", "hurricane", "topic"],
    ["wildfire", "野火", "wildfire", "topic"],
    ["deforestation", "森林砍伐", "deforestation", "topic"],
    ["biodiversity", "生物多样性", "biodiversity", "topic"],
    ["endangered species", "濒危物种", "endangered species", "topic"],
    ["wildlife", "野生动物", "wildlife", "topic"],
    ["ozone layer", "臭氧层", "ozone layer", "topic"],
    ["sustainability", "可持续性", "sustainability", "topic"],
    ["experiment", "实验", "experiment", "topic"],
    ["research", "研究", "research", "topic"],
    ["discovery", "发现", "discovery", "topic"],
    ["theory", "理论", "theory", "topic"],
    ["measurement", "测量", "measurement", "topic"],
    ["DNA", "DNA", "DNA", "topic"],
    ["evolution", "进化", "evolution", "topic"],
    ["speed of light", "光速", "speed of light", "topic"],
    ["galaxy", "星系", "galaxy", "topic"],
    ["satellite", "卫星", "satellite", "topic"],
    ["spacecraft", "宇宙飞船", "spacecraft", "topic"],
    ["vaccine", "疫苗", "vaccine", "topic"],
    ["treatment", "治疗", "treatment", "topic"],
    ["symptom", "症状", "symptom", "topic"],
    ["infection", "感染", "infection", "topic"],
    ["blood pressure", "血压", "blood pressure", "topic"],
    ["heart attack", "心脏病发作", "heart attack", "topic"],
    ["stroke", "中风", "stroke", "topic"],
    ["cancer", "癌症", "cancer", "topic"],
    ["diabetes", "糖尿病", "diabetes", "topic"],
    ["obesity", "肥胖", "obesity", "topic"],
    ["diet", "饮食", "diet", "topic"],
    ["mental health", "心理健康", "mental health", "topic"],
    ["stress", "压力", "stress", "topic"],
    ["youth", "青年", "youth", "topic"],
    ["elderly", "老年人", "elderly", "topic"],
    ["inequality", "不平等", "inequality", "topic"],
    ["homelessness", "无家可归", "homelessness", "topic"],
    ["charity", "慈善机构", "charity", "topic"],
    ["welfare", "社会福利", "welfare", "topic"],
    ["healthcare", "医疗保健", "healthcare", "topic"],
    ["scholarship", "奖学金", "scholarship", "topic"],
    ["seminar", "研讨会", "seminar", "topic"],
    ["tuition fees", "学费", "tuition fees", "topic"],
    ["discrimination", "歧视", "discrimination", "topic"],
    ["racism", "种族主义", "racism", "topic"],
    ["feminism", "女权主义", "feminism", "topic"],
    ["custom", "习俗", "custom", "topic"],
    ["belief", "信仰", "belief", "topic"],
    ["church", "教堂", "church", "topic"],
    ["mosque", "清真寺", "mosque", "topic"],
    ["temple", "寺庙", "temple", "topic"],
    ["priest", "神父", "priest", "topic"],
    ["prayer", "祈祷", "prayer", "topic"],
    ["faith", "信仰", "faith", "topic"],
    ["soul", "灵魂", "soul", "topic"],
    ["hell", "地狱", "hell", "topic"],
    ["sin", "罪", "sin", "topic"],
    ["wedding", "婚礼", "wedding", "topic"],
    ["funeral", "葬礼", "funeral", "topic"],
    ["cemetery", "墓地", "cemetery", "topic"],
    ["baptism", "洗礼", "baptism", "topic"],
    ["architecture", "建筑学", "architecture", "topic"],
    ["painting", "绘画", "painting", "topic"],
    ["gallery", "画廊", "gallery", "topic"],
    ["masterpiece", "杰作", "masterpiece", "topic"],
    ["orchestra", "管弦乐队", "orchestra", "topic"],
    ["ballet", "芭蕾", "ballet", "topic"],
    ["piano", "钢琴", "piano", "topic"],
    ["violin", "小提琴", "violin", "topic"],
    ["guitar", "吉他", "guitar", "topic"],
    ["drum", "鼓", "drum", "topic"],
    ["flute", "长笛", "flute", "topic"],
    ["trumpet", "小号", "trumpet", "topic"],
    ["rehearsal", "排练", "rehearsal", "topic"],
    ["applause", "掌声", "applause", "topic"],
    ["plot", "情节", "plot", "topic"],
    ["character", "角色", "character", "topic"],
    ["publisher", "出版社", "publisher", "topic"],
    ["translator", "译者", "translator", "topic"],
    ["fairy tale", "童话", "fairy tale", "topic"],
    ["hero", "英雄", "hero", "topic"],
    ["villain", "反派", "villain", "topic"],
    ["subtitle", "字幕", "subtitle", "topic"],
    ["soundtrack", "原声音乐", "soundtrack", "topic"],
    ["fireworks", "烟花", "fireworks", "topic"],
    ["costume", "服装", "costume", "topic"],
    ["tourist", "游客", "tourist", "topic"],
    ["tourism", "旅游业", "tourism", "topic"],
    ["sightseeing", "观光", "sightseeing", "topic"],
    ["guide", "导游", "guide", "topic"],
    ["map", "地图", "map", "topic"],
    ["cruise", "游轮", "cruise", "topic"],
    ["campsite", "营地", "campsite", "topic"],
    ["hiking", "徒步", "hiking", "topic"],
    ["summit", "山顶", "summit", "topic"],
    ["waterfall", "瀑布", "waterfall", "topic"],
    ["volcano", "火山", "volcano", "topic"],
    ["cliff", "悬崖", "cliff", "topic"],
    ["harbour", "港口", "harbour", "topic"],
    ["lighthouse", "灯塔", "lighthouse", "topic"],
    ["tide", "潮汐", "tide", "topic"],
    ["sunrise", "日出", "sunrise", "topic"],
    ["sunset", "日落", "sunset", "topic"],
    ["rainbow", "彩虹", "rainbow", "topic"],
    ["thunder", "雷", "thunder", "topic"],
    ["lightning", "闪电", "lightning", "topic"],
    ["hail", "冰雹", "hail", "topic"],
    ["frost", "霜冻", "frost", "topic"],
    ["breeze", "微风", "breeze", "topic"],
    ["heatwave", "热浪", "heatwave", "topic"],
    ["forecast", "天气预报", "forecast", "topic"],
    ["humidity", "湿度", "humidity", "topic"]
  );
})();
