/* =====================================================
   FUGA MYTHICA — CURSUS Spanish 🇪🇸 · batch 3 (band 2000–3000)
   Academic / news vocabulary by Latin root (third group), plus Greek roots as used in Spanish.
   ===================================================== */
(function () {
  const p = VOCAB.es;
  Object.assign(p.roots, {
    agr: ["agr- / campo", "田", "field"], ambul: ["ambul- / and-", "走", "walk"], apt: ["apt-", "合适", "fit"], cert: ["cert- / ciert-", "确定", "sure"],
    cult: ["cult- / col-", "耕,培养", "cultivate"], dur: ["dur-", "硬,持久", "hard, last"], div: ["div- / divis-", "分", "divide"], ess: ["es- / ent-", "存在", "be"],
    fabr: ["fabr- / forj-", "制作", "make"], fat: ["fa- / fab-", "说", "speak"], fend: ["fend- / fens-", "打击", "strike"], flor: ["flor-", "花", "flower"],
    gest: ["gest- / ger-", "携带,做", "carry, do"], glob: ["glob-", "球", "ball"], grat: ["grat- / grad-", "感谢,愉快", "thankful"], hum: ["hum-", "土,人", "earth, human"],
    imag: ["imag- / imit-", "像", "image"], integr: ["íntegr- / enter-", "完整", "whole"], jur: ["jur- / jus-", "法,誓", "law, swear"], lig: ["lig- / li-", "绑", "bind"],
    lingu: ["lingu- / lengu-", "舌,语", "tongue"], loqu: ["locu- / loc-", "说", "speak"], medic: ["médic- / méd-", "治", "heal"], mens: ["mens- / medi-", "量", "measure"],
    merc: ["merc-", "买卖", "trade"], mir: ["mir-", "惊奇,看", "wonder, look"], misc: ["misc- / mezcl-", "混", "mix"], mun: ["mun-", "职责,公共", "duty, public"],
    mut: ["mut- / mud-", "变", "change"], noc: ["noc-", "害", "harm"], norm: ["norm-", "规则", "rule"], numer: ["númer-", "数", "number"],
    nutr: ["nutr-", "喂养", "nourish"], oper: ["oper- / obr-", "工作", "work"], or: ["or- / orat-", "口,说", "mouth, speak"], par: ["par-", "相等", "equal"],
    part: ["part-", "部分", "part"], pass: ["pas-", "步", "step"], pen: ["pen- / pun-", "罚", "punish"], plaud: ["plaud- / plos-", "拍手", "clap"],
    priv: ["priv-", "私,夺", "private, deprive"], prud: ["prud-", "远见", "foresight"], pur: ["pur-", "净", "pure"], radi: ["radi- / ray-", "光线", "ray"],
    rap: ["rap- / rab-", "抓", "seize"], rot: ["rot- / rued-", "轮", "wheel"], rur: ["rur- / rúst-", "乡村", "country"], san: ["san-", "健康", "healthy"],
    sec: ["sec- / sect-", "切", "cut"], sen: ["sen- / señ-", "老", "old"], sol2: ["sol-", "独", "alone"], somn: ["somn- / sueñ-", "睡", "sleep"],
    spond: ["spond- / spons-", "承诺", "pledge"], string: ["string- / strict- / streñ-", "拉紧", "bind tight"], sum: ["sum- / sunt-", "拿", "take"], tex: ["tex- / tej-", "织", "weave"],
    tim: ["tim-", "怕", "fear"], tox: ["tox-", "毒", "poison"], ult: ["ult-", "最远", "last"], und: ["ond- / und-", "波", "wave"],
    ut: ["ut- / us-", "用", "use"], vest: ["vest-", "衣", "clothe"], volv: ["volv- / volu-", "滚", "roll"], vulner: ["vulner- / her-", "伤", "wound"],
    log: ["-logía / log-", "学,言", "study, word"], graph: ["graf- / -grama", "写", "write"], phon: ["fon-", "声", "sound"], bio: ["bio-", "生命", "life"],
    geo: ["geo-", "地", "earth"], chron: ["cron-", "时间", "time"], path: ["pat-", "感受,病", "feeling, disease"], tele: ["tele-", "远", "far"],
    micro: ["micro-", "小", "small"], scop: ["-scopio", "看", "look"], meter: ["-metro", "量", "measure"], crat: ["-cracia", "统治", "rule"],
    anthrop: ["antrop-", "人", "human"], psych: ["psic- / sic-", "心灵", "mind"], phil: ["fil-", "爱", "love"], theo: ["teo-", "神", "god"],
    hydr: ["hidr-", "水", "water"], cycl: ["cicl-", "圈", "circle"], phob: ["-fobia", "怕", "fear"], onym: ["-ónimo", "名", "name"],
    syn: ["sin- / sim-", "一起", "together"], anti: ["anti-", "反", "against"], hyper: ["hiper-", "过度", "over"], mono: ["mono-", "单", "one"],
    poly: ["poli-", "多", "many"], neo: ["neo-", "新", "new"], dia: ["dia-", "穿过", "through"], a: ["a- / an-", "无", "without"],
  });
  p.words.push(
    ["la agricultura","农业","agriculture","agr"], ["el agricultor","农民","farmer","agr"], ["agrícola","农业的","agricultural","agr"], ["el peregrino","朝圣者","pilgrim","agr"], ["agrario","农业的","agrarian","agr"],
    ["la ambulancia","救护车","ambulance","ambul"], ["ambulante","流动的","itinerant","ambul"], ["el preámbulo","序言","preamble","ambul"], ["andar","走","walk","ambul"], ["deambular","漫步","wander","ambul"],
    ["apto","适合的","fit","apt"], ["adaptar","适应","adapt","apt"], ["la aptitud","天资","aptitude","apt"], ["inepto","无能的","inept","apt"], ["la adaptación","适应","adaptation","apt"],
    ["cierto","确定的","certain","cert"], ["certificar","证明","certify","cert"], ["el certificado","证书","certificate","cert"], ["la certeza","确信","certainty","cert"], ["el concierto","音乐会","concert","cert"], ["acertar","猜对","get right","cert"], ["la incertidumbre","不确定","uncertainty","cert"],
    ["la cultura","文化","culture","cult"], ["cultivar","培养","cultivate","cult"], ["el cultivo","种植","crop","cult"], ["la colonia","殖民地","colony","cult"], ["el culto","崇拜","cult","cult"], ["culto","有教养的","cultured","cult"],
    ["durable","持久的","durable","dur"], ["durar","持续","last","dur"], ["la duración","时长","duration","dur"], ["duro","硬的","hard","dur"], ["durante","在…期间","during","dur"], ["endurecer","变硬","harden","dur"], ["la dureza","硬度","hardness","dur"],
    ["dividir","分","divide","div"], ["la división","分割","division","div"], ["el individuo","个人","individual","div"], ["el dividendo","红利","dividend","div"], ["la divisa","货币","currency","div"], ["individual","个人的","individual","div"],
    ["la esencia","本质","essence","ess"], ["esencial","必要的","essential","ess"], ["la entidad","实体","entity","ess"], ["presente","在场的","present","ess"], ["ausente","缺席的","absent","ess"], ["el interés","兴趣,利息","interest","ess"], ["el ser","存在","being","ess"], ["el ente","实体","entity","ess"],
    ["la fábrica","工厂","factory","fabr"], ["fabricar","制造","make","fabr"], ["la fabricación","制造","manufacture","fabr"], ["forjar","锻造","forge","fabr"], ["la fragua","锻炉","forge","fabr"],
    ["la fábula","寓言","fable","fat"], ["fabuloso","传奇的","fabulous","fat"], ["el infante","王子,婴儿","infante","fat"], ["el prefacio","前言","preface","fat"], ["confesar","承认","confess","fat"], ["inefable","难以言喻的","ineffable","fat"], ["la fama","名声","fame","fat"], ["afable","和蔼的","affable","fat"],
    ["defender","保卫","defend","fend"], ["la defensa","防御","defence","fend"], ["ofender","冒犯","offend","fend"], ["la ofensa","冒犯","offence","fend"], ["ofensivo","进攻的","offensive","fend"], ["el defensor","捍卫者","defender","fend"],
    ["la flor","花","flower","flor"], ["florecer","开花","bloom","flor"], ["la florería","花店","florist","flor"], ["floreciente","繁荣的","flourishing","flor"], ["la flora","植物群","flora","flor"], ["Florida","佛罗里达","Florida","flor"],
    ["el gesto","手势","gesture","gest"], ["digerir","消化","digest","gest"], ["sugerir","建议","suggest","gest"], ["gestionar","管理","manage","gest"], ["la gestión","管理","management","gest"], ["el registro","登记","register","gest"], ["exagerar","夸张","exaggerate","gest"], ["la sugerencia","建议","suggestion","gest"],
    ["el globo","气球,地球","balloon, globe","glob"], ["global","全球的","global","glob"], ["el glóbulo","血球","globule","glob"], ["englobar","包括","encompass","glob"],
    ["gratis","免费","free","grat"], ["la gratitud","感激","gratitude","grat"], ["gracioso","有趣的","funny","grat"], ["agradable","愉快的","pleasant","grat"], ["agradecer","感谢","thank","grat"], ["felicitar","祝贺","congratulate","grat"], ["la gracia","优雅,恩典","grace","grat"], ["gratuito","免费的","free","grat"],
    ["humano","人的","human","hum"], ["la humanidad","人类","humanity","hum"], ["humilde","谦逊的","humble","hum"], ["la humildad","谦卑","humility","hum"], ["humillar","羞辱","humiliate","hum"], ["exhumar","挖出","exhume","hum"], ["póstumo","死后的","posthumous","hum"],
    ["la imagen","图像","image","imag"], ["imaginar","想象","imagine","imag"], ["imitar","模仿","imitate","imag"], ["la imaginación","想象力","imagination","imag"], ["la imitación","模仿","imitation","imag"],
    ["entero","整个的","whole","integr"], ["la integridad","诚信","integrity","integr"], ["integrar","整合","integrate","integr"], ["la integración","整合","integration","integr"], ["íntegro","正直的","honest","integr"],
    ["el jurado","陪审团","jury","jur"], ["jurar","发誓","swear","jur"], ["el jurista","法学家","jurist","jur"], ["la jurisdicción","管辖权","jurisdiction","jur"], ["la injuria","侮辱","insult","jur"], ["el juramento","誓言","oath","jur"], ["conjurar","避开","ward off","jur"],
    ["ligar","绑","bind","lig"], ["la liga","联盟","league","lig"], ["obligar","迫使","oblige","lig"], ["la religión","宗教","religion","lig"], ["el aliado","盟友","ally","lig"], ["la obligación","义务","obligation","lig"], ["el ligamento","韧带","ligament","lig"],
    ["la lengua","舌,语言","tongue, language","lingu"], ["el lenguaje","语言","language","lingu"], ["el lingüista","语言学家","linguist","lingu"], ["bilingüe","双语的","bilingual","lingu"], ["la lingüística","语言学","linguistics","lingu"],
    ["elocuente","雄辩的","eloquent","loqu"], ["la elocuencia","口才","eloquence","loqu"], ["el coloquio","研讨会","colloquium","loqu"], ["el soliloquio","独白","soliloquy","loqu"], ["locuaz","健谈的","talkative","loqu"], ["la locución","短语","phrase","loqu"],
    ["la medicina","医学","medicine","medic"], ["el médico","医生","doctor","medic"], ["médico","医学的","medical","medic"], ["el remedio","补救","remedy","medic"], ["el medicamento","药物","medication","medic"],
    ["medir","测量","measure","mens"], ["la medida","测量,措施","measure","mens"], ["la dimensión","维度","dimension","mens"], ["inmenso","巨大的","immense","mens"], ["desmesurado","过度的","excessive","mens"], ["el mes","月","month","mens"],
    ["el mercado","市场","market","merc"], ["el comercio","商业","commerce","merc"], ["la mercancía","商品","merchandise","merc"], ["comercial","商业的","commercial","merc"], ["la merced","恩惠","mercy","merc"], ["el mercenario","雇佣兵","mercenary","merc"], ["el comerciante","商人","merchant","merc"],
    ["el milagro","奇迹","miracle","mir"], ["admirar","钦佩","admire","mir"], ["mirar","看","look","mir"], ["la mirada","目光","gaze","mir"], ["la maravilla","奇迹","marvel","mir"], ["admirable","令人钦佩的","admirable","mir"], ["el espejismo","海市蜃楼","mirage","mir"],
    ["mezclar","混合","mix","misc"], ["la mezcla","混合物","mixture","misc"], ["misceláneo","混杂的","miscellaneous","misc"], ["mixto","混合的","mixed","misc"], ["entremezclar","混杂","intermingle","misc"],
    ["municipal","市政的","municipal","mun"], ["el municipio","市镇","municipality","mun"], ["la comunidad","社区","community","mun"], ["comunicar","交流","communicate","mun"], ["inmune","免疫的","immune","mun"], ["común","共同的","common","mun"], ["la comunicación","交流","communication","mun"],
    ["mudar","改变,搬家","change, move","mut"], ["la mudanza","搬家","move","mut"], ["la mutación","突变","mutation","mut"], ["mutuo","相互的","mutual","mut"], ["inmutable","不变的","immutable","mut"], ["conmutar","减刑,交换","commute","mut"],
    ["inocente","无辜的","innocent","noc"], ["nocivo","有害的","harmful","noc"], ["la inocencia","清白","innocence","noc"], ["inocuo","无害的","innocuous","noc"],
    ["normal","正常的","normal","norm"], ["enorme","巨大的","enormous","norm"], ["anormal","异常的","abnormal","norm"], ["la norma","标准","norm","norm"], ["normalmente","通常","normally","norm"],
    ["el número","数","number","numer"], ["numeroso","众多的","numerous","numer"], ["enumerar","列举","enumerate","numer"], ["innumerable","无数的","innumerable","numer"], ["numérico","数字的","numerical","numer"],
    ["la nutrición","营养","nutrition","nutr"], ["nutrir","喂养","nourish","nutr"], ["nutritivo","有营养的","nutritious","nutr"], ["el nutriente","养分","nutrient","nutr"], ["la nodriza","奶妈","wet nurse","nutr"],
    ["operar","操作,手术","operate","oper"], ["cooperar","合作","cooperate","oper"], ["la ópera","歌剧","opera","oper"], ["la obra","作品","work","oper"], ["la operación","操作,手术","operation","oper"], ["el obrero","工人","worker","oper"], ["la maniobra","操作","manoeuvre","oper"],
    ["oral","口头的","oral","or"], ["el orador","演说家","orator","or"], ["el oráculo","神谕","oracle","or"], ["adorar","崇拜","adore","or"], ["inexorable","不可阻挡的","inexorable","or"], ["la oración","句子,祷告","sentence, prayer","or"], ["orar","祈祷","pray","or"],
    ["par","偶数的","even","par"], ["la paridad","平等","parity","par"], ["comparar","比较","compare","par"], ["la comparación","比较","comparison","par"], ["parejo","相似的","even","par"], ["la pareja","一对,伴侣","pair, partner","par"], ["la disparidad","差异","disparity","par"],
    ["la parte","部分","part","part"], ["la partícula","粒子","particle","part"], ["parcial","部分的","partial","part"], ["particular","特别的","particular","part"], ["compartir","分享","share","part"], ["partir","离开,切分","leave, split","part"], ["el partido","政党,比赛","party, match","part"], ["repartir","分配","distribute","part"], ["apartar","分开","set aside","part"],
    ["el pasaje","通道,票","passage, ticket","pass"], ["el pasajero","乘客","passenger","pass"], ["sobrepasar","超越","surpass","pass"], ["el paso","步","step","pass"], ["pasar","经过","pass","pass"], ["el pasado","过去","past","pass"], ["el pasillo","走廊","corridor","pass"],
    ["la pena","痛苦,刑罚","pain, penalty","pen"], ["penal","刑事的","penal","pen"], ["castigar","惩罚","punish","pen"], ["la impunidad","免罚","impunity","pen"], ["arrepentirse","悔改","repent","pen"], ["penoso","痛苦的","painful","pen"],
    ["aplaudir","鼓掌","applaud","plaud"], ["el aplauso","掌声","applause","plaud"], ["plausible","貌似合理的","plausible","plaud"], ["explotar","爆炸,开发","explode, exploit","plaud"], ["la explosión","爆炸","explosion","plaud"],
    ["privado","私人的","private","priv"], ["privar","剥夺","deprive","priv"], ["la privacidad","隐私","privacy","priv"], ["el privilegio","特权","privilege","priv"], ["privatizar","私有化","privatize","priv"],
    ["prudente","谨慎的","prudent","prud"], ["la prudencia","谨慎","prudence","prud"], ["imprudente","轻率的","imprudent","prud"], ["la jurisprudencia","判例法","case law","prud"],
    ["puro","纯的","pure","pur"], ["purificar","净化","purify","pur"], ["la pureza","纯洁","purity","pur"], ["depurar","净化","purify","pur"], ["la purga","清洗","purge","pur"],
    ["el rayo","光线,闪电","ray, lightning","radi"], ["radiar","辐射","radiate","radi"], ["el rábano","萝卜","radish","radi"], ["la radio","收音机","radio","radi"], ["radiante","光芒四射的","radiant","radi"], ["irradiar","照射","irradiate","radi"], ["el radio","半径","radius","radi"],
    ["rápido","快速的","rapid","rap"], ["la rapidez","速度","speed","rap"], ["raptar","绑架","abduct","rap"], ["el rapto","绑架","abduction","rap"], ["rapaz","贪婪的,猛禽","rapacious, raptor","rap"], ["arrebatar","夺走","snatch","rap"],
    ["la rueda","轮子","wheel","rot"], ["rodar","滚动","roll","rot"], ["la rotación","旋转","rotation","rot"], ["el rollo","卷","roll","rot"], ["controlar","控制","control","rot"], ["el control","控制","control","rot"], ["rotar","轮换","rotate","rot"], ["redondo","圆的","round","rot"],
    ["rural","乡村的","rural","rur"], ["rústico","乡土的","rustic","rur"],
    ["sano","健康的","healthy","san"], ["la sanidad","卫生","health service","san"], ["sanitario","卫生的","sanitary","san"], ["insano","不健康的","unhealthy","san"], ["sanar","痊愈","heal","san"], ["sanear","清理","clean up","san"],
    ["la sección","部分","section","sec"], ["el sector","部门","sector","sec"], ["el insecto","昆虫","insect","sec"], ["disecar","解剖","dissect","sec"], ["el segmento","段","segment","sec"], ["la secta","教派","sect","sec"],
    ["el senado","参议院","senate","sen"], ["el senador","参议员","senator","sen"], ["senil","衰老的","senile","sen"], ["el señor","先生","sir","sen"], ["la señora","女士","madam","sen"], ["el señorío","领主权","lordship","sen"],
    ["solo","独自的","alone","sol2"], ["la soledad","孤独","solitude","sol2"], ["solitario","孤独的","solitary","sol2"], ["desolado","荒凉的","desolate","sol2"], ["aislar","隔离","isolate","sol2"], ["el solista","独奏者","soloist","sol2"],
    ["el sueño","睡眠,梦","sleep, dream","somn"], ["el insomnio","失眠","insomnia","somn"], ["soñar","做梦","dream","somn"], ["el sonámbulo","梦游者","sleepwalker","somn"], ["el somnífero","安眠药","sleeping pill","somn"], ["soñoliento","昏昏欲睡的","drowsy","somn"],
    ["el patrocinador","赞助者","sponsor","spond"], ["responder","回答","answer","spond"], ["la respuesta","回答","answer","spond"], ["corresponder","符合","correspond","spond"], ["el esposo","丈夫","husband","spond"], ["la esposa","妻子","wife","spond"], ["responsable","负责的","responsible","spond"], ["la responsabilidad","责任","responsibility","spond"],
    ["estricto","严格的","strict","string"], ["restringir","限制","restrict","string"], ["la restricción","限制","restriction","string"], ["el distrito","地区","district","string"], ["estrecho","狭窄的","narrow","string"], ["estreñir","便秘","constipate","string"], ["constreñir","强迫","constrain","string"], ["el prestigio","威望","prestige","string"],
    ["asumir","承担","assume","sum"], ["consumir","消费","consume","sum"], ["el consumo","消费","consumption","sum"], ["presumir","炫耀,推测","show off, presume","sum"], ["resumir","总结","summarize","sum"], ["el resumen","摘要","summary","sum"], ["suntuoso","奢华的","sumptuous","sum"],
    ["el texto","文本","text","tex"], ["el textil","纺织品","textile","tex"], ["la textura","质地","texture","tex"], ["el contexto","语境","context","tex"], ["el pretexto","借口","pretext","tex"], ["el tejido","织物,组织","fabric, tissue","tex"], ["tejer","织","weave","tex"],
    ["tímido","胆小的","timid","tim"], ["intimidar","恐吓","intimidate","tim"], ["la timidez","胆怯","shyness","tim"], ["temer","害怕","fear","tim"], ["el temor","恐惧","fear","tim"],
    ["tóxico","有毒的","toxic","tox"], ["la toxina","毒素","toxin","tox"], ["intoxicar","使中毒","poison","tox"], ["la intoxicación","中毒","poisoning","tox"],
    ["último","最后的","last","ult"], ["el ultimátum","最后通牒","ultimatum","ult"], ["ulterior","之后的","later","ult"], ["ultimar","完成","finalize","ult"],
    ["la onda","波","wave","und"], ["ondular","起伏","undulate","und"], ["abundante","丰富的","abundant","und"], ["la abundancia","丰富","abundance","und"], ["inundar","淹没","flood","und"], ["la inundación","洪水","flood","und"], ["redundante","多余的","redundant","und"],
    ["útil","有用的","useful","ut"], ["la utilidad","效用","utility","ut"], ["utilizar","使用","use","ut"], ["el utensilio","器具","utensil","ut"], ["el uso","用法","usage","ut"], ["abusar","滥用","abuse","ut"], ["usar","用","use","ut"], ["usado","用过的","used","ut"],
    ["el vestido","裙子","dress","vest"], ["vestir","穿衣","clothe","vest"], ["invertir","投资","invest","vest"], ["la inversión","投资","investment","vest"], ["la vestimenta","服装","clothing","vest"], ["revestir","覆盖","coat","vest"],
    ["evolucionar","进化","evolve","volv"], ["la evolución","进化","evolution","volv"], ["la revolución","革命","revolution","volv"], ["el volumen","卷,体积","volume","volv"], ["envolver","包裹","wrap","volv"], ["desarrollar","发展","develop","volv"], ["volver","返回","return","volv"], ["devolver","归还","give back","volv"], ["revolver","搅动","stir","volv"],
    ["vulnerable","脆弱的","vulnerable","vulner"], ["la vulnerabilidad","脆弱性","vulnerability","vulner"], ["herir","伤害","wound","vulner"], ["la herida","伤口","wound","vulner"],
    /* Greek in Spanish */ ["la lógica","逻辑","logic","log"], ["la biología","生物学","biology","log"], ["el diálogo","对话","dialogue","log"], ["la tecnología","技术","technology","log"], ["la psicología","心理学","psychology","log"], ["el catálogo","目录","catalogue","log"], ["el prólogo","序言","prologue","log"], ["la arqueología","考古学","archaeology","log"], ["la ecología","生态学","ecology","log"],
    ["el gráfico","图表","graph","graph"], ["la fotografía","照片","photograph","graph"], ["el autógrafo","亲笔签名","autograph","graph"], ["la biografía","传记","biography","graph"], ["la geografía","地理","geography","graph"], ["el párrafo","段落","paragraph","graph"], ["el telegrama","电报","telegram","graph"], ["la gramática","语法","grammar","graph"], ["la ortografía","拼写","spelling","graph"],
    ["el teléfono","电话","telephone","phon"], ["el micrófono","麦克风","microphone","phon"], ["la sinfonía","交响乐","symphony","phon"], ["fonético","语音的","phonetic","phon"], ["el saxofón","萨克斯","saxophone","phon"],
    ["el antibiótico","抗生素","antibiotic","bio"], ["biológico","生物的","biological","bio"], ["la simbiosis","共生","symbiosis","bio"], ["la biodiversidad","生物多样性","biodiversity","bio"],
    ["la geología","地质学","geology","geo"], ["la geometría","几何","geometry","geo"], ["geográfico","地理的","geographical","geo"],
    ["crónico","慢性的","chronic","chron"], ["la crónica","编年史,专栏","chronicle","chron"], ["la cronología","年表","chronology","chron"], ["sincronizar","同步","synchronize","chron"], ["el cronómetro","秒表","stopwatch","chron"],
    ["la simpatía","好感","sympathy","path"], ["la empatía","共情","empathy","path"], ["la apatía","冷漠","apathy","path"], ["patético","可悲的","pathetic","path"], ["la patología","病理学","pathology","path"],
    ["la televisión","电视","television","tele"], ["el telescopio","望远镜","telescope","tele"], ["la telenovela","电视剧","soap opera","tele"], ["el telediario","电视新闻","TV news","tele"],
    ["el microscopio","显微镜","microscope","micro"], ["el microbio","微生物","microbe","micro"], ["el microondas","微波炉","microwave","micro"],
    ["el periscopio","潜望镜","periscope","scop"], ["el horóscopo","星座运势","horoscope","scop"], ["el caleidoscopio","万花筒","kaleidoscope","scop"],
    ["el termómetro","温度计","thermometer","meter"], ["el diámetro","直径","diameter","meter"], ["el perímetro","周长","perimeter","meter"], ["la simetría","对称","symmetry","meter"], ["el kilómetro","千米","kilometre","meter"],
    ["la democracia","民主","democracy","crat"], ["la aristocracia","贵族","aristocracy","crat"], ["la burocracia","官僚制","bureaucracy","crat"], ["democrático","民主的","democratic","crat"],
    ["la antropología","人类学","anthropology","anthrop"], ["la filantropía","慈善","philanthropy","anthrop"], ["el misántropo","厌世者","misanthrope","anthrop"],
    ["psíquico","心理的","psychic","psych"], ["la psiquiatría","精神病学","psychiatry","psych"], ["el psicólogo","心理学家","psychologist","psych"],
    ["la filosofía","哲学","philosophy","phil"], ["el filósofo","哲学家","philosopher","phil"], ["filarmónico","爱乐的","philharmonic","phil"],
    ["la teología","神学","theology","theo"], ["el ateo","无神论者","atheist","theo"], ["el monoteísmo","一神教","monotheism","theo"], ["el entusiasmo","热情","enthusiasm","theo"],
    ["el hidrógeno","氢","hydrogen","hydr"], ["hidráulico","水力的","hydraulic","hydr"], ["deshidratar","脱水","dehydrate","hydr"],
    ["el ciclo","循环","cycle","cycl"], ["la bicicleta","自行车","bicycle","cycl"], ["reciclar","回收","recycle","cycl"], ["el ciclón","气旋","cyclone","cycl"], ["la enciclopedia","百科全书","encyclopedia","cycl"],
    ["la fobia","恐惧症","phobia","phob"], ["la claustrofobia","幽闭恐惧","claustrophobia","phob"], ["la xenofobia","仇外","xenophobia","phob"],
    ["el sinónimo","同义词","synonym","onym"], ["el antónimo","反义词","antonym","onym"], ["anónimo","匿名的","anonymous","onym"], ["el seudónimo","笔名","pseudonym","onym"],
    ["la síntesis","合成","synthesis","syn"], ["el símbolo","符号","symbol","syn"], ["el sistema","系统","system","syn"], ["la sintaxis","句法","syntax","syn"],
    ["el antídoto","解毒剂","antidote","anti"], ["antisocial","反社会的","antisocial","anti"], ["la antigüedad","古代","antiquity","anti"], ["el anticuerpo","抗体","antibody","anti"],
    ["hiperactivo","过度活跃的","hyperactive","hyper"], ["el hipermercado","大型超市","hypermarket","hyper"], ["la hipertensión","高血压","hypertension","hyper"],
    ["el monopolio","垄断","monopoly","mono"], ["el monólogo","独白","monologue","mono"], ["monótono","单调的","monotonous","mono"], ["el monarca","君主","monarch","mono"],
    ["el polígono","多边形","polygon","poly"], ["políglota","通晓多语的","polyglot","poly"], ["la policlínica","综合诊所","polyclinic","poly"],
    ["el neón","氖","neon","neo"], ["el neologismo","新词","neologism","neo"], ["neolítico","新石器的","Neolithic","neo"],
    ["el diagnóstico","诊断","diagnosis","dia"], ["la diagonal","对角线","diagonal","dia"], ["la diapositiva","幻灯片","slide","dia"],
    ["el átomo","原子","atom","a"], ["la anarquía","无政府","anarchy","a"], ["la amnesia","失忆","amnesia","a"], ["apático","冷漠的","apathetic","a"]
  );
})();
