/* =====================================================
   FUGA MYTHICA — CURSUS English 🇬🇧 · batch 4
   Fill the big families to 8–12 derivatives each. English gist = modern synonym (never the etymology).
   ===================================================== */
(function () {
  const p = VOCAB.en;
  Object.assign(p.roots, {
    fac2: ["fac / fic / feit / feas", "做", "make, do"], dat2: ["dat / dit / don", "给", "give"], sta: ["sta / stit", "站,立", "stand, set"], ver3: ["vert / vers / vorc", "转", "turn"],
    ced2: ["ced / ceed / cess", "走", "go"], cap3: ["cap / cip / ceipt / chas", "抓", "take"], leg3: ["leg / lig / lect", "选,读,绑", "choose, read, bind"], mit2: ["mit / mis / mess", "送", "send"],
    tent: ["tent / tin / tain", "持", "hold"], pos2: ["pos / post / pon", "放", "put"], spec2: ["spec / spic / spy", "看", "look"], scrib2: ["scrib / scrip / scrib", "写", "write"],
    fer2: ["fer / lat / ferous", "带", "carry"], tract2: ["tract / trait / treat", "拉", "pull"], duc2: ["duc / duce / duct", "引", "lead"], pend2: ["pend / pens / pond", "挂,称", "hang, weigh"], sent2: ["sent / sens", "感", "feel"], grad2: ["grad / gred / gress", "步", "step"], vid: ["vid / vis / view", "看", "see"],
    dic2: ["dic / dict", "说", "say"], cur3: ["cur / cour / curs", "跑", "run"], fin2: ["fin / finit", "结束", "end"],
    form2: ["form / forma", "形", "shape"], gen2: ["gen / gn / kin", "生,种", "birth, kind"], nat2: ["nat / nasc / nais", "出生", "born"],
    par3: ["par / pare / pair", "相等,准备", "equal, prepare"], plic2: ["plic / ploy / ply", "折", "fold"], press2: ["press / print", "压", "press"], reg3: ["reg / rect / roy", "统治,直", "rule, straight"],
    sequ2: ["sequ / secut / sue / suit", "跟随", "follow"], solv2: ["solv / solu", "松开", "loosen"], tang2: ["tang / tact / tag / tig", "触", "touch"], ten2: ["tend / tens / tent", "伸", "stretch"],
    voc2: ["voc / vok / vow", "叫", "call"], val2: ["val / vail", "强,值", "strong, worth"], viv2: ["viv / vit / vig", "活", "live"], vinc2: ["vinc / vict / vanq", "征服", "conquer"],
  });
  p.words.push(
    /* fac */ ["fact","事实","true thing","fac2"], ["feat","壮举","achievement","fac2"], ["feature","特征","characteristic","fac2"], ["feasible","可行的","possible","fac2"], ["facility","设施","building, ease","fac2"], ["faculty","能力,教员","ability; staff","fac2"], ["fashion","时尚,方式","style","fac2"], ["counterfeit","伪造的","fake","fac2"], ["forfeit","丧失","lose as penalty","fac2"], ["surfeit","过量","excess","fac2"], ["proficient","熟练的","skilled","fac2"], ["deficient","不足的","lacking","fac2"], ["beneficial","有益的","helpful","fac2"], ["certificate","证书","official document","fac2"], ["qualify","使合格","meet requirements","fac2"], ["amplify","放大","enlarge","fac2"], ["identify","识别","recognize","fac2"], ["affair","事务","matter","fac2"],
    /* dat */ ["donor","捐赠者","giver","dat2"], ["endow","捐赠","provide funds","dat2"], ["condition","条件","requirement","dat2"], ["edition","版本","published version","dat2"], ["editor","编辑","text reviser","dat2"], ["tradition","传统","custom","dat2"], ["traitor","叛徒","betrayer","dat2"], ["betray","背叛","be disloyal to","dat2"], ["dose","剂量","measured amount","dat2"], ["anecdote","轶事","short story","dat2"], ["antidote","解毒剂","poison cure","dat2"], ["pardon","原谅","forgiveness","dat2"], ["rent","租金","payment for use","dat2"], ["render","呈现","provide","dat2"], ["vend","售卖","sell","dat2"], ["vendor","小贩","seller","dat2"],
    /* sta */ ["establish","建立","set up","sta"], ["institute","机构","organization","sta"], ["institution","制度,机构","established organization","sta"], ["constitute","构成","make up","sta"], ["constitution","宪法","fundamental law","sta"], ["substitute","替代","replacement","sta"], ["destitute","赤贫的","penniless","sta"], ["restitution","归还","restoration","sta"], ["superstition","迷信","irrational belief","sta"], ["stationary","静止的","not moving","sta"], ["stationery","文具","writing materials","sta"], ["statistics","统计","numerical data","sta"], ["statute","法规","law","sta"], ["stature","身高,声望","height; standing","sta"], ["estate","地产","property","sta"], ["stance","立场","position","sta"], ["circumstance","情况","situation","sta"], ["stage","舞台","platform","sta"], ["staple","主食,主要的","basic item","sta"], ["arrest","逮捕","take into custody","sta"], ["contrast","对比","difference","sta"], ["cost","成本","price","sta"], ["ecstasy","狂喜","intense joy","sta"], ["armistice","停战","truce","sta"], ["solstice","至日","sun's extreme point","sta"], ["obstinate","固执的","stubborn","sta"], ["steady","稳定的","stable","sta"],
    /* vert */ ["version","版本","variant","ver3"], ["adverse","不利的","unfavourable","ver3"], ["adversity","逆境","hardship","ver3"], ["averse","反对的","opposed","ver3"], ["avert","避免","prevent","ver3"], ["conversation","对话","talk","ver3"], ["converse","交谈","talk","ver3"], ["divorce","离婚","end of marriage","ver3"], ["perverse","反常的","contrary","ver3"], ["subvert","颠覆","undermine","ver3"], ["traverse","穿过","cross","ver3"], ["versatile","多才多艺的","adaptable","ver3"], ["vertigo","眩晕","dizziness","ver3"], ["vertebra","脊椎骨","spine bone","ver3"], ["vortex","漩涡","whirlpool","ver3"], ["prose","散文","ordinary writing","ver3"], ["verse","诗句","poetry line","ver3"], ["anniversary","周年","yearly date","ver3"], ["inadvertent","无意的","unintentional","ver3"], ["introversion","内向","inward focus","ver3"],
    /* ced */ ["exceed","超过","surpass","ced2"], ["succession","连续,继承","sequence; inheritance","ced2"], ["successor","继任者","one who follows","ced2"], ["procession","队列","parade","ced2"], ["recession","衰退","economic decline","ced2"], ["concession","让步","compromise","ced2"], ["accessible","可到达的","reachable","ced2"], ["accessory","配件","extra item","ced2"], ["intercede","调解","plead on behalf","ced2"], ["antecedent","先行词","preceding thing","ced2"], ["unprecedented","史无前例的","never done before","ced2"], ["secede","退出","withdraw","ced2"], ["decease","死亡","death","ced2"], ["incessant","不断的","constant","ced2"], ["abscess","脓肿","pus swelling","ced2"], ["cede","割让","give up","ced2"],
    /* cap */ ["capable","有能力的","able","cap3"], ["captivate","迷住","charm","cap3"], ["caption","标题","title text","cap3"], ["chase","追","pursue","cap3"], ["catch","抓住","grab","cap3"], ["purchase","购买","buy","cap3"], ["occupy","占据","take up","cap3"], ["occupation","职业,占领","job; takeover","cap3"], ["recipe","食谱","cooking instructions","cap3"], ["recipient","接受者","receiver","cap3"], ["receipt","收据","proof of payment","cap3"], ["receptacle","容器","container","cap3"], ["reception","接待","welcome","cap3"], ["deception","欺骗","trickery","cap3"], ["conception","概念,受孕","idea; pregnancy","cap3"], ["perception","感知","awareness","cap3"], ["exception","例外","special case","cap3"], ["inception","开始","beginning","cap3"], ["susceptible","易受影响的","vulnerable","cap3"], ["capsule","胶囊","small container","cap3"], ["municipal","市政的","of a town","cap3"], ["prince","王子","royal son","cap3"], ["principle","原则","basic rule","cap3"], ["emancipate","解放","set free","cap3"], ["forceps","镊子","surgical pincers","cap3"],
    /* leg */ ["legend","传说","myth","leg3"], ["legible","易读的","clear","leg3"], ["lesson","课","teaching unit","leg3"], ["lecture","讲座","talk","leg3"], ["lectern","讲台","reading stand","leg3"], ["collection","收藏","gathered set","leg3"], ["selection","选择","choice","leg3"], ["election","选举","vote","leg3"], ["recollect","回忆","remember","leg3"], ["dialect","方言","regional language","leg3"], ["eclectic","折中的","drawn from many sources","leg3"], ["intellect","智力","mind","leg3"], ["diligent","勤奋的","hardworking","leg3"], ["sacrilege","亵渎","violation of the sacred","leg3"], ["privilege","特权","special right","leg3"], ["colleague","同事","coworker","leg3"], ["college","学院","school","leg3"], ["delegate","代表","representative","leg3"], ["relegate","降级","demote","leg3"], ["legacy","遗产","inheritance","leg3"], ["legion","军团","large army","leg3"], ["allegiance","忠诚","loyalty","leg3"], ["liaison","联络","link","leg3"], ["obligation","义务","duty","leg3"],
    /* mit */ ["permission","许可","consent","mit2"], ["admission","承认,准入","entry; confession","mit2"], ["commission","委托,佣金","assignment; fee","mit2"], ["submission","提交,屈服","handing in; yielding","mit2"], ["transmission","传输","sending","mit2"], ["omission","遗漏","leaving out","mit2"], ["remission","缓解","lessening","mit2"], ["intermission","幕间休息","break","mit2"], ["demise","死亡","death","mit2"], ["premise","前提","assumption","mit2"], ["surmise","推测","guess","mit2"], ["compromise","妥协","settlement","mit2"], ["message","消息","communication","mit2"], ["messenger","信使","courier","mit2"], ["missionary","传教士","religious envoy","mit2"], ["emissary","使者","envoy","mit2"], ["committee","委员会","group assigned a task","mit2"],
    /* tent / tain */ ["tenant","租户","occupier","tent"], ["tenure","任期","holding of office","tent"], ["tenet","信条","principle","tent"], ["tenor","要旨,男高音","general sense; voice","tent"], ["content","内容","what is inside","tent"], ["continue","继续","go on","tent"], ["continuous","连续的","unbroken","tent"], ["container","容器","box, vessel","tent"], ["countenance","面容","facial expression","tent"], ["lieutenant","中尉","deputy officer","tent"], ["maintenance","维护","upkeep","tent"], ["pertinent","相关的","relevant","tent"], ["impertinent","无礼的","rude","tent"], ["retentive","记性好的","able to retain","tent"], ["sustenance","食物","nourishment","tent"], ["abstinence","禁欲","self-denial","tent"], ["detention","拘留","confinement","tent"], ["entertainment","娱乐","amusement","tent"],
    /* pos */ ["positive","积极的","affirmative","pos2"], ["posture","姿势","body position","pos2"], ["post","岗位,邮寄","job; mail","pos2"], ["compost","堆肥","decayed matter","pos2"], ["composure","镇静","calmness","pos2"], ["composition","作文,构成","written work; makeup","pos2"], ["exposition","阐述","explanation","pos2"], ["opposition","反对","resistance","pos2"], ["proposition","提议","proposal","pos2"], ["disposition","性情","temperament","pos2"], ["preposition","介词","relation word","pos2"], ["imposition","强加","burden","pos2"], ["repository","仓库","storage place","pos2"], ["depot","仓库,车站","storehouse","pos2"], ["apposite","恰当的","apt","pos2"], ["pose","姿势","position","pos2"], ["purpose","目的","aim","pos2"], ["suppository","栓剂","medicine insert","pos2"], ["opponent","对手","rival","pos2"], ["exponent","倡导者,指数","advocate; power","pos2"], ["postpone","推迟","delay","pos2"],
    /* spec */ ["species","物种","biological kind","spec2"], ["special","特别的","particular","spec2"], ["especially","尤其","particularly","spec2"], ["spectrum","光谱,范围","range","spec2"], ["speculation","推测","guesswork","spec2"], ["auspicious","吉利的","favourable","spec2"], ["expect","期待","anticipate","spec2"], ["aspect","方面","feature","spec2"], ["respectable","体面的","decent","spec2"], ["disrespect","不敬","rudeness","spec2"], ["spectacles","眼镜","glasses","spec2"], ["spy","间谍","secret agent","spec2"], ["espionage","间谍活动","spying","spec2"], ["specify","具体说明","state exactly","spec2"], ["specific","具体的","precise","spec2"], ["specious","似是而非的","misleadingly plausible","spec2"], ["introspection","内省","self-examination","spec2"], ["frontispiece","卷首插画","book's front illustration","spec2"],
    /* scrib */ ["scribe","抄写员","copyist","scrib2"], ["script","剧本,字体","text; handwriting","scrib2"], ["ascribe","归因于","attribute","scrib2"], ["circumscribe","限制","restrict","scrib2"], ["nondescript","不起眼的","undistinguished","scrib2"], ["description","描述","account","scrib2"], ["prescription","处方","doctor's order","scrib2"], ["subscription","订阅","paid membership","scrib2"], ["inscription","铭文","engraved words","scrib2"], ["superscript","上标","raised character","scrib2"], ["shrive","听忏悔","hear confession","scrib2"], ["scrivener","文书","clerk","scrib2"],
    /* fer */ ["fertility","生育力","productiveness","fer2"], ["conference","会议","meeting","fer2"], ["reference","参考","citation","fer2"], ["preference","偏好","liking","fer2"], ["difference","差异","distinction","fer2"], ["inference","推论","conclusion","fer2"], ["offering","供品,提供","gift","fer2"], ["vociferous","喧哗的","loud","fer2"], ["coniferous","针叶的","cone-bearing","fer2"], ["aquifer","含水层","water-bearing rock","fer2"], ["Lucifer","路西法","light-bearer","fer2"], ["circumference","周长","boundary of a circle","fer2"], ["indifferent","冷漠的","uninterested","fer2"], ["ferry","渡船","boat crossing","fer2"], ["elation","兴高采烈","great joy","fer2"], ["oblation","供奉","religious offering","fer2"], ["superlative","最高级的","supreme","fer2"], ["legislature","立法机构","law-making body","fer2"], ["dilatory","拖延的","slow","fer2"], ["collate","核对","compare texts","fer2"], ["prelate","高级教士","bishop","fer2"],
    /* tract */ ["tractable","温顺的","manageable","tract2"], ["intractable","难驾驭的","unmanageable","tract2"], ["attraction","吸引力","appeal","tract2"], ["contraction","收缩","shrinking","tract2"], ["distraction","分心","diversion","tract2"], ["extraction","提取,出身","removal; origin","tract2"], ["treat","对待,款待","deal with; entertain","tract2"], ["treatise","论文","scholarly work","tract2"], ["treaty","条约","agreement","tract2"], ["trait","特征","characteristic","tract2"], ["portrait","肖像","likeness","tract2"], ["portray","描绘","depict","tract2"], ["trace","痕迹","mark, track","tract2"], ["track","轨道,追踪","path; follow","tract2"], ["trail","小径","path","tract2"], ["train","火车,训练","railway; teach","tract2"], ["retreat","撤退","withdrawal","tract2"], ["entreat","恳求","beg","tract2"], ["maltreat","虐待","abuse","tract2"], ["tractor","拖拉机","farm vehicle","tract2"],
    /* duc */ ["deduction","推论,扣除","inference; subtraction","duc2"], ["induction","归纳,就职","inference from cases; installation","duc2"], ["conducive","有助于的","helpful","duc2"], ["conduit","管道","channel","duc2"], ["duct","管","tube","duc2"], ["ductile","可延展的","malleable","duc2"], ["duke","公爵","nobleman","duc2"], ["ducal","公爵的","of a duke","duc2"], ["educe","引出","draw out","duc2"], ["subdue","制服","overcome","duc2"], ["endue","赋予","endow","duc2"], ["redoubt","堡垒","fortification","duc2"], ["production","生产","output","duc2"], ["reduction","减少","decrease","duc2"], ["seduction","诱惑","temptation","duc2"], ["introduction","介绍","preface","duc2"], ["reproduce","复制,繁殖","copy; breed","duc2"], ["misconduct","不当行为","wrongdoing","duc2"],
    /* port */ ["portage","搬运","carrying overland","port"], ["purport","声称","claim","port"], ["rapport","融洽","harmony","port"], ["comport","举止","behave","port"], ["sport","运动","game","port"], ["disport","嬉戏","amuse oneself","port"], ["portal","门户","gateway","port"], ["porch","门廊","covered entrance","port"], ["portly","肥胖的","stout","port"], ["importance","重要性","significance","port"], ["supportive","支持的","helpful","port"], ["transportation","运输","transport","port"], ["reporter","记者","journalist","port"], ["passport","护照","travel document","port"], ["seaport","海港","harbour town","port"],
    /* pend */ ["pendulum","钟摆","swinging weight","pend2"], ["independent","独立的","self-reliant","pend2"], ["dependence","依赖","reliance","pend2"], ["suspense","悬念","anxious waiting","pend2"], ["expenditure","支出","spending","pend2"], ["expensive","昂贵的","costly","pend2"], ["dispense","分发","distribute","pend2"], ["indispensable","不可缺的","essential","pend2"], ["propensity","倾向","tendency","pend2"], ["recompense","报酬","compensation","pend2"], ["stipend","津贴","fixed pay","pend2"], ["ponder","思考","think over","pend2"], ["ponderous","笨重的","heavy, dull","pend2"], ["preponderance","优势","majority","pend2"], ["pound","磅","weight unit","pend2"], ["perpendicular","垂直的","at right angles","pend2"], ["appendix","附录,阑尾","supplement; organ","pend2"], ["impending","即将发生的","imminent","pend2"],
    /* sent */ ["sensation","感觉,轰动","feeling; excitement","sent2"], ["sensory","感官的","of the senses","sent2"], ["sensual","感官享受的","pleasure-loving","sent2"], ["sensor","传感器","detector","sent2"], ["sentence","句子,判决","word group; verdict","sent2"], ["sentinel","哨兵","guard","sent2"], ["sentry","哨兵","guard","sent2"], ["sentimental","多愁善感的","emotional","sent2"], ["presentiment","预感","foreboding","sent2"], ["assent","同意","agreement","sent2"], ["scent","气味","smell","sent2"], ["insensible","无知觉的","unconscious","sent2"], ["consensus","共识","general agreement","sent2"], ["desensitize","使不敏感","make less sensitive","sent2"],
    /* grad */ ["grade","等级","level","grad2"], ["gradient","坡度","slope","grad2"], ["graduation","毕业","completion ceremony","grad2"], ["degree","程度,学位","level; qualification","grad2"], ["degradation","退化","decline","grad2"], ["retrograde","倒退的","backward","grad2"], ["centigrade","摄氏","hundred-degree scale","grad2"], ["progressive","进步的","forward-looking","grad2"], ["aggression","侵略","hostility","grad2"], ["egress","出口","exit","grad2"], ["ingress","进入","entrance","grad2"], ["regression","回归,退步","return to earlier state","grad2"], ["transgression","违法","offence","grad2"], ["digression","离题","aside","grad2"],
    /* vid / view */ ["view","视野,观点","sight; opinion","vid"], ["review","评论","assessment","vid"], ["interview","面试","formal meeting","vid"], ["visual","视觉的","of sight","vid"], ["visit","拜访","go to see","vid"], ["visor","面罩","face shield","vid"], ["vista","景色","view","vid"], ["advisor","顾问","counsellor","vid"], ["envisage","设想","imagine","vid"], ["revision","修订","amendment","vid"], ["supervision","监督","oversight","vid"], ["providence","天意","divine care","vid"], ["provision","供应,条款","supply; clause","vid"], ["proviso","附文","condition","vid"], ["prudence","谨慎","caution","vid"], ["clairvoyant","千里眼的","psychic","vid"], ["survey","调查","study","vid"], ["surveillance","监视","close watch","vid"], ["evidence","证据","proof","vid"], ["wise","明智的","sensible","vid"], ["wit","机智","cleverness","vid"], ["idea","想法","thought","vid"], ["idol","偶像","worshipped image","vid"],
    /* dic */ ["diction","措辞","word choice","dic2"], ["indict","起诉","charge with crime","dic2"], ["interdict","禁止","prohibit","dic2"], ["malediction","诅咒","curse","dic2"], ["valediction","告别辞","farewell","dic2"], ["dictum","格言","saying","dic2"], ["predictable","可预测的","foreseeable","dic2"], ["contradiction","矛盾","inconsistency","dic2"], ["abdicate","退位","give up the throne","dic2"], ["vindicate","证明清白","clear of blame","dic2"], ["condition","条件","requirement","dic2"], ["ditto","同上","the same","dic2"], ["preach","布道","give a sermon","dic2"], ["dictionary","词典","word book","dic2"],
    /* ven */ ["venture","冒险","risky undertaking","ven"], ["conventional","传统的","customary","ven"], ["intervention","干预","interference","ven"], ["prevention","预防","stopping","ven"], ["invention","发明","creation","ven"], ["inventory","库存","stock list","ven"], ["eventual","最终的","final","ven"], ["advent","到来","arrival","ven"], ["circumvent","规避","get around","ven"], ["covenant","契约","agreement","ven"], ["parvenu","暴发户","upstart","ven"], ["revenue","收入","income","ven"], ["convenient","方便的","handy","ven"], ["coven","女巫团","witches' group","ven"], ["misadventure","不幸","mishap","ven"],
    /* cur / cour */ ["courier","快递员","messenger","cur3"], ["curriculum","课程","course of study","cur3"], ["excursion","远足","trip","cur3"], ["incursion","入侵","raid","cur3"], ["precursor","先驱","forerunner","cur3"], ["recourse","求助","source of help","cur3"], ["discourse","话语","discussion","cur3"], ["intercourse","交往","dealings","cur3"], ["concourse","大厅","open hall","cur3"], ["succour","援助","help","cur3"], ["cursory","粗略的","hasty","cur3"], ["occurrence","发生","event","cur3"], ["recurrent","反复的","repeated","cur3"], ["currency","货币","money","cur3"], ["corsair","海盗","pirate","cur3"], ["hussar","轻骑兵","cavalryman","cur3"],
    /* fin */ ["finale","终曲","ending","fin2"], ["finalize","敲定","complete","fin2"], ["finite","有限的","limited","fin2"], ["definite","明确的","clear","fin2"], ["definition","定义","meaning","fin2"], ["confinement","监禁","imprisonment","fin2"], ["refinement","精致","elegance","fin2"], ["refinery","炼油厂","purifying plant","fin2"], ["financial","金融的","monetary","fin2"], ["affinity","亲和力","attraction","fin2"], ["infinity","无限","endlessness","fin2"], ["fine","罚款,精细的","penalty; delicate","fin2"], ["finesse","技巧","skill","fin2"], ["paraffin","石蜡","waxy substance","fin2"],
    /* form */ ["formation","形成","creation","form2"], ["format","格式","layout","form2"], ["formulate","制定","devise","form2"], ["formidable","可怕的,强大的","impressive, daunting","form2"], ["formality","形式","official procedure","form2"], ["informal","非正式的","casual","form2"], ["information","信息","facts","form2"], ["informant","线人","informer","form2"], ["reformation","改革","reform","form2"], ["deformity","畸形","malformation","form2"], ["conformity","一致","compliance","form2"], ["transformation","转变","change","form2"], ["platform","平台","raised stage","form2"], ["cuneiform","楔形文字","wedge-shaped writing","form2"], ["uniformity","统一","sameness","form2"],
    /* gen */ ["gene","基因","hereditary unit","gen2"], ["genesis","起源","origin","gen2"], ["genre","体裁","category","gen2"], ["gentle","温柔的","mild","gen2"], ["gentleman","绅士","courteous man","gen2"], ["genteel","文雅的","refined","gen2"], ["gender","性别","sex category","gen2"], ["genial","亲切的","friendly","gen2"], ["genocide","种族灭绝","mass killing","gen2"], ["indigenous","本土的","native","gen2"], ["ingenuous","天真的","innocent","gen2"], ["progeny","后代","offspring","gen2"], ["degenerate","堕落","decline","gen2"], ["regenerate","再生","renew","gen2"], ["generous","慷慨的","giving","gen2"], ["genealogy","家谱","family history","gen2"], ["congenital","先天的","present from birth","gen2"], ["pregnant","怀孕的","expecting a child","gen2"], ["kin","亲属","relatives","gen2"], ["kind","种类,善良的","type; caring","gen2"], ["king","国王","monarch","gen2"], ["nitrogen","氮","gas element","gen2"], ["carcinogen","致癌物","cancer-causing agent","gen2"], ["photogenic","上镜的","looking good in photos","gen2"],
    /* mot */ ["motivate","激励","inspire","mov"], ["motivation","动机","drive","mov"], ["momentum","势头","impetus","mov"], ["moment","时刻","instant","mov"], ["momentous","重大的","very important","mov"], ["movement","运动","motion","mov"], ["movie","电影","film","mov"], ["locomotion","移动","movement","mov"], ["automobile","汽车","car","mov"], ["mobility","流动性","ability to move","mov"], ["immobile","不动的","motionless","mov"], ["mob","暴民","unruly crowd","mov"], ["demote","降职","lower in rank","mov"], ["remote","遥远的","distant","mov"], ["emotional","情绪的","of feelings","mov"], ["motif","主题","recurring theme","mov"], ["motor","马达","engine","mov"],
    /* nat */ ["natal","出生的","of birth","nat2"], ["neonatal","新生儿的","newborn","nat2"], ["nativity","诞生","birth","nat2"], ["national","国家的","of a nation","nat2"], ["nationality","国籍","citizenship","nat2"], ["international","国际的","between nations","nat2"], ["naive","天真的","innocent","nat2"], ["nascent","初生的","emerging","nat2"], ["cognate","同源的","related","nat2"], ["innate","天生的","inborn","nat2"], ["naturalize","归化","grant citizenship","nat2"], ["supernatural","超自然的","beyond nature","nat2"], ["renaissance","文艺复兴","cultural rebirth","nat2"], ["puny","弱小的","tiny, weak","nat2"], ["noel","圣诞","Christmas","nat2"],
    /* par */ ["parity","平等","equality","par3"], ["disparage","贬低","belittle","par3"], ["nonpareil","无与伦比的","unrivalled","par3"], ["umpire","裁判","referee","par3"], ["peerless","无双的","unmatched","par3"], ["separation","分离","division","par3"], ["preparation","准备","readiness","par3"], ["reparation","赔偿","compensation","par3"], ["apparel","服装","clothing","par3"], ["parade","游行","procession","par3"], ["parry","挡开","deflect","par3"], ["rampart","壁垒","defensive wall","par3"], ["emperor","皇帝","ruler of an empire","par3"], ["empire","帝国","group of nations","par3"], ["imperative","必要的,命令的","essential; commanding","par3"], ["imperial","帝国的","of an empire","par3"], ["sever","切断","cut off","par3"], ["several","几个","some","par3"], ["pare","削皮","trim","par3"],
    /* plic */ ["complex","复杂的","complicated","plic2"], ["complexion","肤色","skin colour","plic2"], ["perplex","使困惑","puzzle","plic2"], ["explicate","阐释","explain in detail","plic2"], ["implication","含义","suggested meaning","plic2"], ["application","申请,应用","request; use","plic2"], ["appliance","器具","device","plic2"], ["pliable","柔韧的","flexible","plic2"], ["pliers","钳子","gripping tool","plic2"], ["deploy","部署","position for use","plic2"], ["employ","雇用","hire","plic2"], ["exploit","利用","use unfairly","plic2"], ["display","展示","show","plic2"], ["supple","柔软的","flexible","plic2"], ["supplicate","恳求","beg humbly","plic2"], ["triplicate","一式三份","three copies","plic2"], ["plait","辫子","braid","plic2"], ["pleat","褶","fold in cloth","plic2"],
    /* press */ ["print","印刷","reproduce on paper","press2"], ["imprint","印记","mark","press2"], ["reprint","重印","print again","press2"], ["blueprint","蓝图","plan","press2"], ["expression","表达,表情","statement; look","press2"], ["impression","印象","effect on the mind","press2"], ["depression","抑郁,萧条","low mood; slump","press2"], ["oppression","压迫","cruel rule","press2"], ["suppression","镇压","crushing","press2"], ["repression","压抑","holding back","press2"], ["compression","压缩","squeezing","press2"], ["espresso","浓缩咖啡","pressed coffee","press2"], ["irrepressible","压抑不住的","uncontrollable","press2"], ["pressing","紧迫的","urgent","press2"],
    /* reg */ ["regal","帝王的","royal","reg3"], ["regime","政权","government","reg3"], ["regimen","养生法","health routine","reg3"], ["regiment","团","army unit","reg3"], ["regent","摄政者","acting ruler","reg3"], ["regicide","弑君","king-killing","reg3"], ["regulation","规章","rule","reg3"], ["irregular","不规则的","uneven","reg3"], ["rectify","纠正","correct","reg3"], ["rectitude","正直","honesty","reg3"], ["rector","校长,牧师","head; parish priest","reg3"], ["rectangle","矩形","four-sided shape","reg3"], ["direction","方向","course","reg3"], ["director","导演,主管","head","reg3"], ["indirect","间接的","roundabout","reg3"], ["insurrection","起义","uprising","reg3"], ["resurrection","复活","rising again","reg3"], ["surge","激增","sudden rise","reg3"], ["source","来源","origin","reg3"], ["resource","资源","supply","reg3"], ["royalty","王室,版税","royal family; payment","reg3"], ["viceroy","总督","king's deputy","reg3"], ["realm","领域","kingdom","reg3"], ["rule","规则","law","reg3"], ["ruler","统治者,尺","leader; measuring stick","reg3"],
    /* sequ / sue */ ["sequel","续集","follow-up","sequ2"], ["sequence","序列","order","sequ2"], ["consequent","随之而来的","resulting","sequ2"], ["inconsequential","无关紧要的","unimportant","sequ2"], ["obsequies","葬礼","funeral rites","sequ2"], ["execution","执行,处决","carrying out; death penalty","sequ2"], ["executive","主管","manager","sequ2"], ["persecution","迫害","oppression","sequ2"], ["prosecution","起诉","legal action","sequ2"], ["sue","起诉","take to court","sequ2"], ["suit","诉讼,套装","lawsuit; outfit","sequ2"], ["suitable","合适的","appropriate","sequ2"], ["suite","套房","set of rooms","sequ2"], ["ensue","接着发生","follow","sequ2"], ["pursuit","追求","chase","sequ2"], ["sect","教派","religious group","sequ2"], ["second","第二,秒","next after first; time unit","sequ2"], ["secondary","次要的","less important","sequ2"],
    /* solv */ ["solvent","有偿付能力的,溶剂","able to pay; dissolver","solv2"], ["insolvent","破产的","unable to pay","solv2"], ["dissolution","解散","breaking up","solv2"], ["resolution","决心,决议","determination; decision","solv2"], ["absolution","赦免","forgiveness","solv2"], ["absolve","赦免","free from blame","solv2"], ["soluble","可溶的","dissolvable","solv2"], ["dissolute","放荡的","immoral","solv2"], ["unresolved","未解决的","not settled","solv2"],
    /* tang */ ["tangent","切线","touching line","tang2"], ["tangential","离题的","only slightly related","tang2"], ["tact","机智","sensitivity","tang2"], ["tactful","得体的","diplomatic","tang2"], ["intangible","无形的","untouchable","tang2"], ["contingent","视情况而定的","dependent","tang2"], ["contiguous","相邻的","adjoining","tang2"], ["contamination","污染","pollution","tang2"], ["attain","达到","achieve","tang2"], ["taste","味道","flavour","tang2"], ["tax","税","government charge","tang2"], ["task","任务","job","tang2"], ["entire","整个的","whole","tang2"], ["integrity","诚信","honesty","tang2"],
    /* tend */ ["tent","帐篷","canvas shelter","ten2"], ["tense","紧张的,时态","strained; verb form","ten2"], ["tensile","抗拉的","stretchable","ten2"], ["extension","延伸","lengthening","ten2"], ["extensive","广泛的","wide-ranging","ten2"], ["intention","意图","aim","ten2"], ["intensive","密集的","concentrated","ten2"], ["attention","注意","focus","ten2"], ["attentive","专注的","alert","ten2"], ["contention","争论","dispute","ten2"], ["contentious","有争议的","controversial","ten2"], ["pretentious","做作的","showy","ten2"], ["portent","预兆","omen","ten2"], ["ostensible","表面的","apparent","ten2"], ["ostentatious","炫耀的","showy","ten2"], ["superintendent","主管","supervisor","ten2"], ["distend","膨胀","swell","ten2"], ["tendon","肌腱","tissue cord","ten2"], ["tender","温柔的","gentle","ten2"],
    /* voc / vow */ ["vocation","职业","calling","voc2"], ["avocation","副业","hobby","voc2"], ["vociferous","喧哗的","loud","voc2"], ["vouch","担保","confirm","voc2"], ["vowel","元音","open speech sound","voc2"], ["avow","公开承认","declare","voc2"], ["disavow","否认","deny","voc2"], ["convocation","集会","assembly","voc2"], ["equivocal","模棱两可的","ambiguous","voc2"], ["unequivocal","明确的","clear","voc2"], ["irrevocable","不可撤销的","final","voc2"], ["provocative","挑衅的","provoking","voc2"], ["evocative","引起回忆的","reminiscent","voc2"], ["advocacy","倡导","support","voc2"],
    /* val */ ["valor","英勇","bravery","val2"], ["valedictorian","毕业生代表","top graduate","val2"], ["validate","验证","confirm","val2"], ["invalid","无效的,病人","not valid; sick person","val2"], ["ambivalent","矛盾的","having mixed feelings","val2"], ["equivalence","等价","equality","val2"], ["convalesce","康复","recover","val2"], ["avail","有用","be of use","val2"], ["available","可用的","obtainable","val2"], ["countervail","抵消","counterbalance","val2"], ["valuable","有价值的","precious","val2"], ["devalue","贬值","reduce the value","val2"], ["evaluation","评估","assessment","val2"],
    /* viv */ ["vivacity","活泼","liveliness","viv2"], ["vivisection","活体解剖","live dissection","viv2"], ["convivial","欢乐的","festive","viv2"], ["viable","可行的","workable","viv2"], ["vitality","活力","energy","viv2"], ["vitamin","维生素","essential nutrient","viv2"], ["revitalize","复兴","bring back to life","viv2"], ["vigor","活力","energy","viv2"], ["vigorous","精力充沛的","energetic","viv2"], ["invigorate","使精神","energize","viv2"], ["vigilant","警惕的","watchful","viv2"], ["vigil","守夜","night watch","viv2"], ["viand","食物","food","viv2"],
    /* vinc */ ["vanquish","击败","defeat","vinc2"], ["conviction","定罪,信念","guilty verdict; belief","vinc2"], ["convincing","有说服力的","persuasive","vinc2"], ["invincible","无敌的","unbeatable","vinc2"], ["evince","表明","show clearly","vinc2"], ["victorious","胜利的","winning","vinc2"], ["provincial","省的,狭隘的","of a province; narrow","vinc2"], ["Vincent","文森特","conquering (name)","vinc2"]
  );
})();
