/* =====================================================
   FUGA MYTHICA — CURSUS French 🇫🇷 · batch 8 — topical everyday vocabulary + derivations
   ===================================================== */
(function () {
  const p = VOCAB.fr;
  p.words.push(
    ["l'électricien", "电工", "electrician", "topic"],
    ["le maçon", "泥瓦匠", "bricklayer", "topic"],
    ["le menuisier", "木匠", "carpenter", "topic"],
    ["le mécanicien", "机械师", "mechanic", "topic"],
    ["le coiffeur", "理发师", "hairdresser", "topic"],
    ["le boulanger", "面包师", "baker", "topic"],
    ["le boucher", "屠夫", "butcher", "topic"],
    ["le cuisinier", "厨师", "cook", "topic"],
    ["le pompier", "消防员", "firefighter", "topic"],
    ["le policier", "警察", "police officer", "topic"],
    ["le comptable", "会计", "accountant", "topic"],
    ["le scientifique", "科学家", "scientist", "topic"],
    ["le programmeur", "程序员", "programmer", "topic"],
    ["le pilote", "飞行员", "pilot", "topic"],
    ["le caissier", "收银员", "cashier", "topic"],
    ["le facteur", "邮递员", "postman", "topic"],
    ["le vétérinaire", "兽医", "vet", "topic"],
    ["le compte bancaire", "银行账户", "bank account", "topic"],
    ["le distributeur", "自动取款机", "ATM", "topic"],
    ["le virement", "转账", "transfer", "topic"],
    ["le prêt", "贷款", "loan", "topic"],
    ["l'assurance", "保险", "insurance", "topic"],
    ["le bureau de poste", "邮局", "post office", "topic"],
    ["le timbre", "邮票", "stamp", "topic"],
    ["le colis", "包裹", "parcel", "topic"],
    ["le commissariat", "警察局", "police station", "topic"],
    ["la cathédrale", "大教堂", "cathedral", "topic"],
    ["la fontaine", "喷泉", "fountain", "topic"],
    ["le parc", "公园", "park", "topic"],
    ["le zoo", "动物园", "zoo", "topic"],
    ["la gare routière", "汽车站", "bus station", "topic"],
    ["l'atelier", "车间", "workshop", "topic"],
    ["l'entrepôt", "仓库", "warehouse", "topic"],
    ["le potager", "菜园", "vegetable garden", "topic"],
    ["l'olive", "橄榄", "olive", "topic"],
    ["le pin", "松树", "pine", "topic"],
    ["la rose", "玫瑰", "rose", "topic"],
    ["la graine", "种子", "seed", "topic"],
    ["la branche", "树枝", "branch", "topic"],
    ["le tronc", "树干", "trunk", "topic"],
    ["la racine", "根", "root", "topic"],
    ["le sable", "沙子", "sand", "topic"],
    ["le rocher", "岩石", "rock", "topic"],
    ["la vallée", "山谷", "valley", "topic"],
    ["la côte", "海岸", "coast", "topic"],
    ["l'aube", "黎明", "dawn", "topic"],
    ["le crépuscule", "黄昏", "dusk", "topic"],
    ["midi", "正午", "noon", "topic"],
    ["minuit", "午夜", "midnight", "topic"],
    ["la tristesse", "悲伤", "sadness", "topic"],
    ["la jalousie", "嫉妒", "jealousy", "topic"],
    ["la colère", "愤怒", "anger", "topic"],
    ["l'ennui", "无聊", "boredom", "topic"],
    ["le chagrin", "悲痛", "grief", "topic"],
    ["le soulagement", "宽慰", "relief", "topic"],
    ["le dégoût", "厌恶", "disgust", "topic"],
    ["le goûter", "下午点心", "afternoon snack", "topic"],
    ["le jambon", "火腿", "ham", "topic"],
    ["l'agneau", "羔羊肉", "lamb", "topic"],
    ["le thon", "金枪鱼", "tuna", "topic"],
    ["les fruits de mer", "海鲜", "seafood", "topic"],
    ["la crevette", "虾", "prawn", "topic"],
    ["l'huile", "油", "oil", "topic"],
    ["le poivre", "胡椒", "pepper", "topic"],
    ["la tomate", "番茄", "tomato", "topic"],
    ["l'oignon", "洋葱", "onion", "topic"],
    ["l'ail", "大蒜", "garlic", "topic"],
    ["la carotte", "胡萝卜", "carrot", "topic"],
    ["le champignon", "蘑菇", "mushroom", "topic"],
    ["la poire", "梨", "pear", "topic"],
    ["la pêche", "桃", "peach", "topic"],
    ["l'orange", "橙子", "orange", "topic"],
    ["le citron", "柠檬", "lemon", "topic"],
    ["le raisin", "葡萄", "grapes", "topic"],
    ["la fraise", "草莓", "strawberry", "topic"],
    ["la cerise", "樱桃", "cherry", "topic"],
    ["la pastèque", "西瓜", "watermelon", "topic"],
    ["la banane", "香蕉", "banana", "topic"],
    ["le biscuit", "饼干", "biscuit", "topic"],
    ["le verre", "玻璃杯", "glass", "topic"],
    ["l'assiette", "盘子", "plate", "topic"],
    ["la fourchette", "叉子", "fork", "topic"],
    ["le couteau", "刀", "knife", "topic"],
    ["la cuillère", "勺子", "spoon", "topic"],
    ["la serviette", "餐巾,毛巾", "napkin", "topic"],
    ["l'addition", "账单", "bill", "topic"],
    ["le pourboire", "小费", "tip", "topic"],
    ["le serveur", "服务员", "waiter", "topic"],
    ["la joue", "脸颊", "cheek", "topic"],
    ["le menton", "下巴", "chin", "topic"],
    ["le coude", "肘", "elbow", "topic"],
    ["le poignet", "手腕", "wrist", "topic"],
    ["l'ongle", "指甲", "nail", "topic"],
    ["la poitrine", "胸", "chest", "topic"],
    ["la cheville", "脚踝", "ankle", "topic"],
    ["le cerveau", "大脑", "brain", "topic"],
    ["le poumon", "肺", "lung", "topic"],
    ["l'estomac", "胃", "stomach", "topic"],
    ["le foie", "肝", "liver", "topic"],
    ["le rein", "肾", "kidney", "topic"],
    ["le mal de tête", "头痛", "headache", "topic"],
    ["les urgences", "急诊", "emergency room", "topic"],
    ["l'immeuble", "大楼", "building", "topic"],
    ["l'ascenseur", "电梯", "lift", "topic"],
    ["la salle de bains", "浴室", "bathroom", "topic"],
    ["le balcon", "阳台", "balcony", "topic"],
    ["l'oreiller", "枕头", "pillow", "topic"],
    ["la couverture", "毯子", "blanket", "topic"],
    ["le canapé", "沙发", "sofa", "topic"],
    ["l'étagère", "书架", "shelf", "topic"],
    ["la lampe", "灯", "lamp", "topic"],
    ["le rideau", "窗帘", "curtain", "topic"],
    ["le réfrigérateur", "冰箱", "fridge", "topic"],
    ["le four", "烤箱", "oven", "topic"],
    ["le lave-linge", "洗衣机", "washing machine", "topic"],
    ["le lave-vaisselle", "洗碗机", "dishwasher", "topic"],
    ["l'aspirateur", "吸尘器", "vacuum cleaner", "topic"],
    ["la poubelle", "垃圾桶", "bin", "topic"],
    ["le tee-shirt", "T恤", "T-shirt", "topic"],
    ["le jean", "牛仔裤", "jeans", "topic"],
    ["les bottes", "靴子", "boots", "topic"],
    ["les chaussettes", "袜子", "socks", "topic"],
    ["la casquette", "鸭舌帽", "cap", "topic"],
    ["les gants", "手套", "gloves", "topic"],
    ["la ceinture", "腰带", "belt", "topic"],
    ["la boulangerie", "面包店", "bakery", "topic"],
    ["la boucherie", "肉店", "butcher's", "topic"],
    ["le kiosque", "报刊亭", "newsstand", "topic"],
    ["le centre commercial", "购物中心", "shopping centre", "topic"],
    ["les espèces", "现金", "cash", "topic"],
    ["le tramway", "有轨电车", "tram", "topic"],
    ["l'autoroute", "高速公路", "motorway", "topic"],
    ["le feu rouge", "红灯", "traffic light", "topic"],
    ["le trottoir", "人行道", "pavement", "topic"],
    ["le sac à dos", "背包", "backpack", "topic"],
    ["la douane", "海关", "customs", "topic"],
    ["l'auberge", "客栈", "inn", "topic"],
    ["le lac", "湖", "lake", "topic"],
    ["la crèche", "托儿所", "nursery", "topic"],
    ["la salle de classe", "教室", "classroom", "topic"],
    ["les devoirs", "作业", "homework", "topic"],
    ["l'informatique", "计算机", "computer science", "topic"],
    ["le site web", "网站", "website", "topic"]
  );
})();
