/* =====================================================
   FUGA MYTHICA — CURSUS Spanish 🇪🇸 · batch 12 — topical vocabulary 4: family & life events, personal care, fashion, shopping, restaurant & drinks, airport & hotel, emergencies, colours, geography names, celebrations, phone & mail
   ===================================================== */
(function () {
  const p = VOCAB.es;
  Object.assign(p.roots, {});
  p.words.push(
    ["el hermanastro", "继兄弟", "stepbrother", "topic"],
    ["la media hermana", "同父异母姐妹", "half-sister", "topic"],
    ["el suegro", "岳父,公公", "father-in-law", "topic"],
    ["la suegra", "岳母,婆婆", "mother-in-law", "topic"],
    ["la nuera", "儿媳", "daughter-in-law", "topic"],
    ["el cuñado", "姐夫,妹夫", "brother-in-law", "topic"],
    ["la cuñada", "嫂子,弟媳", "sister-in-law", "topic"],
    ["el nieto", "孙子", "grandson", "topic"],
    ["la nieta", "孙女", "granddaughter", "topic"],
    ["el bisabuelo", "曾祖父", "great-grandfather", "topic"],
    ["el sobrino", "侄子", "nephew", "topic"],
    ["la sobrina", "侄女", "niece", "topic"],
    ["el gemelo", "双胞胎", "twin", "topic"],
    ["el hijo único", "独生子女", "only child", "topic"],
    ["el huérfano", "孤儿", "orphan", "topic"],
    ["la viuda", "寡妇", "widow", "topic"],
    ["el viudo", "鳏夫", "widower", "topic"],
    ["el prometido", "未婚夫", "fiancé", "topic"],
    ["el descendiente", "后代", "descendant", "topic"],
    ["el pariente", "亲戚", "relative", "topic"],
    ["el tutor", "监护人", "guardian", "topic"],
    ["el conocido", "熟人", "acquaintance", "topic"],
    ["el desconocido", "陌生人", "stranger", "topic"],
    ["el compañero de piso", "室友", "roommate", "topic"],
    ["el embarazo", "怀孕", "pregnancy", "topic"],
    ["el niño pequeño", "幼儿", "toddler", "topic"],
    ["el adolescente", "青少年", "teenager", "topic"],
    ["el adulto", "成年人", "adult", "topic"],
    ["el jubilado", "退休者", "pensioner", "topic"],
    ["la luna de miel", "蜜月", "honeymoon", "topic"],
    ["la graduación", "毕业典礼", "graduation", "topic"],
    ["el luto", "哀悼", "mourning", "topic"],
    ["el ataúd", "棺材", "coffin", "topic"],
    ["el cepillo de dientes", "牙刷", "toothbrush", "topic"],
    ["la pasta de dientes", "牙膏", "toothpaste", "topic"],
    ["el champú", "洗发水", "shampoo", "topic"],
    ["la maquinilla de afeitar", "剃须刀", "razor", "topic"],
    ["el peine", "梳子", "comb", "topic"],
    ["el cepillo", "发刷", "hairbrush", "topic"],
    ["el secador", "吹风机", "hairdryer", "topic"],
    ["el perfume", "香水", "perfume", "topic"],
    ["el pintalabios", "口红", "lipstick", "topic"],
    ["el maquillaje", "化妆品", "make-up", "topic"],
    ["el esmalte de uñas", "指甲油", "nail polish", "topic"],
    ["la crema", "面霜", "cream", "topic"],
    ["el protector solar", "防晒霜", "sunscreen", "topic"],
    ["el pañuelo de papel", "纸巾", "tissue", "topic"],
    ["el papel higiénico", "卫生纸", "toilet paper", "topic"],
    ["el pañal", "尿布", "nappy", "topic"],
    ["el corte de pelo", "理发", "haircut", "topic"],
    ["la barba", "胡子", "beard", "topic"],
    ["el bigote", "小胡子", "moustache", "topic"],
    ["el flequillo", "刘海", "fringe", "topic"],
    ["la coleta", "马尾辫", "ponytail", "topic"],
    ["la arruga", "皱纹", "wrinkle", "topic"],
    ["la peca", "雀斑", "freckle", "topic"],
    ["la cicatriz", "疤痕", "scar", "topic"],
    ["el tatuaje", "纹身", "tattoo", "topic"],
    ["el piercing", "穿孔", "piercing", "topic"],
    ["el bolsillo", "口袋", "pocket", "topic"],
    ["el botón", "纽扣", "button", "topic"],
    ["la cremallera", "拉链", "zip", "topic"],
    ["la capucha", "兜帽", "hood", "topic"],
    ["el encaje", "蕾丝", "lace", "topic"],
    ["la raya", "条纹", "stripe", "topic"],
    ["el estampado", "花纹", "pattern", "topic"],
    ["a rayas", "条纹的", "with stripes", "topic"],
    ["a cuadros", "格子的", "with squares", "topic"],
    ["de lunares", "圆点的", "with dots", "topic"],
    ["floral", "花卉图案的", "with flowers", "topic"],
    ["el traje", "西装", "suit", "topic"],
    ["la corbata", "领带", "tie", "topic"],
    ["la pajarita", "领结", "bow tie", "topic"],
    ["el chaleco", "马甲", "waistcoat", "topic"],
    ["la blusa", "女衬衫", "blouse", "topic"],
    ["la rebeca", "开襟毛衣", "cardigan", "topic"],
    ["la sudadera", "连帽衫", "hoodie", "topic"],
    ["el chándal", "运动服", "tracksuit", "topic"],
    ["los pantalones cortos", "短裤", "shorts", "topic"],
    ["las medias", "连裤袜", "tights", "topic"],
    ["la ropa interior", "内衣", "underwear", "topic"],
    ["el pijama", "睡衣", "pyjamas", "topic"],
    ["la bata", "睡袍", "dressing gown", "topic"],
    ["el bañador", "泳衣", "swimsuit", "topic"],
    ["el impermeable", "雨衣", "raincoat", "topic"],
    ["las sandalias", "凉鞋", "sandals", "topic"],
    ["las zapatillas", "拖鞋", "slippers", "topic"],
    ["las zapatillas deportivas", "运动鞋", "trainers", "topic"],
    ["los tacones", "高跟鞋", "high heels", "topic"],
    ["la suela", "鞋底", "sole", "topic"],
    ["la pulsera", "手镯", "bracelet", "topic"],
    ["el anillo", "戒指", "ring", "topic"],
    ["el broche", "胸针", "brooch", "topic"],
    ["el monedero", "零钱包", "purse", "topic"],
    ["el paraguas", "雨伞", "umbrella", "topic"],
    ["las gafas de sol", "太阳镜", "sunglasses", "topic"],
    ["el probador", "试衣间", "changing room", "topic"],
    ["el escaparate", "橱窗", "shop window", "topic"],
    ["el carrito", "购物车", "trolley", "topic"],
    ["la ganga", "便宜货", "bargain", "topic"],
    ["el reembolso", "退款", "refund", "topic"],
    ["la garantía", "保修", "guarantee", "topic"],
    ["la etiqueta", "标签", "label", "topic"],
    ["el código de barras", "条形码", "barcode", "topic"],
    ["el vale", "优惠券", "voucher", "topic"],
    ["la tarjeta de fidelidad", "会员卡", "loyalty card", "topic"],
    ["las compras en línea", "网购", "online shopping", "topic"],
    ["la atención al cliente", "客服", "customer service", "topic"],
    ["la floristería", "花店", "florist", "topic"],
    ["la joyería", "珠宝店", "jeweller", "topic"],
    ["la frutería", "蔬果店", "greengrocer", "topic"],
    ["la charcutería", "熟食店", "deli", "topic"],
    ["la papelería", "文具店", "stationer", "topic"],
    ["la ferretería", "五金店", "hardware store", "topic"],
    ["la tintorería", "干洗店", "dry cleaner", "topic"],
    ["el entrante", "前菜", "starter", "topic"],
    ["el plato principal", "主菜", "main course", "topic"],
    ["el postre", "甜点", "dessert", "topic"],
    ["la guarnición", "配菜", "side dish", "topic"],
    ["el menú del día", "套餐", "set menu", "topic"],
    ["la ración", "一份", "portion", "topic"],
    ["el aliño", "沙拉酱", "dressing", "topic"],
    ["el asado", "烤肉", "roast", "topic"],
    ["la tortilla", "煎蛋卷", "omelette", "topic"],
    ["el bocadillo", "三明治", "sandwich", "topic"],
    ["el panqueque", "薄饼", "pancake", "topic"],
    ["el pastel", "馅饼", "pie", "topic"],
    ["el hojaldre", "酥皮糕点", "pastry", "topic"],
    ["el bollo", "小圆面包", "bun", "topic"],
    ["la mermelada", "果酱", "jam", "topic"],
    ["la miel", "蜂蜜", "honey", "topic"],
    ["los cereales", "麦片", "cereal", "topic"],
    ["el yogur", "酸奶", "yoghurt", "topic"],
    ["la nata", "奶油", "cream", "topic"],
    ["la mostaza", "芥末", "mustard", "topic"],
    ["el kétchup", "番茄酱", "ketchup", "topic"],
    ["la mayonesa", "蛋黄酱", "mayonnaise", "topic"],
    ["la especia", "香料", "spice", "topic"],
    ["la canela", "肉桂", "cinnamon", "topic"],
    ["el jengibre", "姜", "ginger", "topic"],
    ["la vainilla", "香草", "vanilla", "topic"],
    ["el chocolate", "巧克力", "chocolate", "topic"],
    ["el caramelo", "糖果", "sweet", "topic"],
    ["el chicle", "口香糖", "chewing gum", "topic"],
    ["las patatas fritas", "薯片", "crisps", "topic"],
    ["las palomitas", "爆米花", "popcorn", "topic"],
    ["la limonada", "柠檬水", "lemonade", "topic"],
    ["el refresco", "汽水", "fizzy drink", "topic"],
    ["el batido", "果昔", "smoothie", "topic"],
    ["el cóctel", "鸡尾酒", "cocktail", "topic"],
    ["el champán", "香槟", "champagne", "topic"],
    ["la sidra", "苹果酒", "cider", "topic"],
    ["el whisky", "威士忌", "whisky", "topic"],
    ["el licor", "利口酒", "liqueur", "topic"],
    ["la pajita", "吸管", "straw", "topic"],
    ["el cubito de hielo", "冰块", "ice cube", "topic"],
    ["vegetariano", "素食的", "no meat", "topic"],
    ["vegano", "纯素的", "no animal products", "topic"],
    ["para llevar", "外带", "takeaway", "topic"],
    ["la terminal", "航站楼", "terminal", "topic"],
    ["la puerta de embarque", "登机口", "gate", "topic"],
    ["la tarjeta de embarque", "登机牌", "boarding pass", "topic"],
    ["el equipaje de mano", "手提行李", "hand luggage", "topic"],
    ["la cinta transportadora", "传送带", "conveyor belt", "topic"],
    ["el control de seguridad", "安检", "security check", "topic"],
    ["la tripulación", "机组", "crew", "topic"],
    ["la azafata", "空姐", "stewardess", "topic"],
    ["el asiento de ventanilla", "靠窗座位", "window seat", "topic"],
    ["las turbulencias", "颠簸", "turbulence", "topic"],
    ["el jet lag", "时差", "jet lag", "topic"],
    ["el billete de ida y vuelta", "往返票", "return ticket", "topic"],
    ["el billete de ida", "单程票", "single ticket", "topic"],
    ["el vagón", "车厢", "carriage", "topic"],
    ["el compartimento", "隔间", "compartment", "topic"],
    ["la litera", "卧铺", "sleeper", "topic"],
    ["el revisor", "检票员", "ticket inspector", "topic"],
    ["el vestíbulo", "大堂", "lobby", "topic"],
    ["la habitación individual", "单人间", "single room", "topic"],
    ["la habitación doble", "双人间", "double room", "topic"],
    ["la suite", "套房", "suite", "topic"],
    ["el servicio de habitaciones", "客房服务", "room service", "topic"],
    ["la media pensión", "半食宿", "half board", "topic"],
    ["la pensión completa", "全食宿", "full board", "topic"],
    ["el albergue juvenil", "青年旅舍", "youth hostel", "topic"],
    ["la casa de huéspedes", "旅社", "guesthouse", "topic"],
    ["la agencia de viajes", "旅行社", "travel agency", "topic"],
    ["el viaje organizado", "跟团游", "package holiday", "topic"],
    ["la casa de cambio", "货币兑换处", "exchange office", "topic"],
    ["el camión de bomberos", "消防车", "fire engine", "topic"],
    ["el extintor", "灭火器", "fire extinguisher", "topic"],
    ["la alarma de incendios", "火警", "fire alarm", "topic"],
    ["la salida de emergencia", "紧急出口", "emergency exit", "topic"],
    ["los primeros auxilios", "急救", "first aid", "topic"],
    ["el botiquín", "急救箱", "first aid kit", "topic"],
    ["la tirita", "创可贴", "plaster", "topic"],
    ["la camilla", "担架", "stretcher", "topic"],
    ["la muleta", "拐杖", "crutch", "topic"],
    ["la silla de ruedas", "轮椅", "wheelchair", "topic"],
    ["la lesión", "受伤", "injury", "topic"],
    ["la quemadura", "烧伤", "burn", "topic"],
    ["el envenenamiento", "中毒", "poisoning", "topic"],
    ["el rescate", "救援", "rescue", "topic"],
    ["el socorrista", "救生员", "lifeguard", "topic"],
    ["el bote salvavidas", "救生艇", "lifeboat", "topic"],
    ["el chaleco salvavidas", "救生衣", "life jacket", "topic"],
    ["la señal de peligro", "危险标志", "danger sign", "topic"],
    ["la sirena", "警报器", "siren", "topic"],
    ["el beige", "米色", "beige", "topic"],
    ["el turquesa", "绿松石色", "turquoise", "topic"],
    ["el azul marino", "海军蓝", "navy", "topic"],
    ["el carmesí", "深红", "crimson", "topic"],
    ["el escarlata", "猩红", "scarlet", "topic"],
    ["el granate", "栗色", "maroon", "topic"],
    ["el lila", "淡紫", "lilac", "topic"],
    ["el violeta", "紫罗兰色", "violet", "topic"],
    ["el verde oliva", "橄榄绿", "olive green", "topic"],
    ["el esmeralda", "翡翠绿", "emerald", "topic"],
    ["el bronce", "青铜色", "bronze", "topic"],
    ["el caqui", "卡其色", "khaki", "topic"],
    ["oscuro", "深色的", "dark", "topic"],
    ["desteñido", "褪色的", "faded", "topic"],
    ["Europa", "欧洲", "Europe", "topic"],
    ["Asia", "亚洲", "Asia", "topic"],
    ["África", "非洲", "Africa", "topic"],
    ["América del Norte", "北美洲", "North America", "topic"],
    ["América del Sur", "南美洲", "South America", "topic"],
    ["Oceanía", "大洋洲", "Oceania", "topic"],
    ["la Antártida", "南极洲", "Antarctica", "topic"],
    ["el Atlántico", "大西洋", "Atlantic", "topic"],
    ["el Pacífico", "太平洋", "Pacific", "topic"],
    ["los Alpes", "阿尔卑斯山", "Alps", "topic"],
    ["los Pirineos", "比利牛斯山", "Pyrenees", "topic"],
    ["el Rin", "莱茵河", "Rhine", "topic"],
    ["el Danubio", "多瑙河", "Danube", "topic"],
    ["el Nilo", "尼罗河", "Nile", "topic"],
    ["el Polo Norte", "北极", "North Pole", "topic"],
    ["los trópicos", "热带", "tropics", "topic"],
    ["la zona horaria", "时区", "time zone", "topic"],
    ["el condado", "郡", "county", "topic"],
    ["el imperio", "帝国", "empire", "topic"],
    ["Alemania", "德国", "Germany", "topic"],
    ["Francia", "法国", "France", "topic"],
    ["España", "西班牙", "Spain", "topic"],
    ["Italia", "意大利", "Italy", "topic"],
    ["Inglaterra", "英格兰", "England", "topic"],
    ["el Reino Unido", "英国", "UK", "topic"],
    ["los Estados Unidos", "美国", "USA", "topic"],
    ["China", "中国", "China", "topic"],
    ["Japón", "日本", "Japan", "topic"],
    ["Rusia", "俄罗斯", "Russia", "topic"],
    ["Grecia", "希腊", "Greece", "topic"],
    ["Suiza", "瑞士", "Switzerland", "topic"],
    ["los Países Bajos", "荷兰", "Netherlands", "topic"],
    ["Egipto", "埃及", "Egypt", "topic"],
    ["la India", "印度", "India", "topic"],
    ["Brasil", "巴西", "Brazil", "topic"],
    ["el Año Nuevo", "新年", "New Year", "topic"],
    ["la Nochebuena", "平安夜", "Christmas Eve", "topic"],
    ["el árbol de Navidad", "圣诞树", "Christmas tree", "topic"],
    ["el huevo de Pascua", "复活节彩蛋", "Easter egg", "topic"],
    ["el Día de San Valentín", "情人节", "Valentine's Day", "topic"],
    ["el Día de la Madre", "母亲节", "Mother's Day", "topic"],
    ["Halloween", "万圣节", "Halloween", "topic"],
    ["la fiesta nacional", "国庆日", "national holiday", "topic"],
    ["el día festivo", "公共假日", "public holiday", "topic"],
    ["la fiesta de cumpleaños", "生日派对", "birthday party", "topic"],
    ["la tarta de cumpleaños", "生日蛋糕", "birthday cake", "topic"],
    ["la invitación", "邀请", "invitation", "topic"],
    ["el invitado", "客人", "guest", "topic"],
    ["el anfitrión", "主人", "host", "topic"],
    ["el brindis", "祝酒", "toast", "topic"],
    ["la tarjeta de felicitación", "贺卡", "greeting card", "topic"],
    ["el papel de regalo", "礼品包装纸", "gift wrap", "topic"],
    ["la cinta", "丝带", "ribbon", "topic"],
    ["el número de teléfono", "电话号码", "phone number", "topic"],
    ["el prefijo", "区号", "area code", "topic"],
    ["el buzón de voz", "语音信箱", "voicemail", "topic"],
    ["el mensaje de texto", "短信", "text message", "topic"],
    ["la llamada perdida", "未接来电", "missed call", "topic"],
    ["el tono de llamada", "铃声", "ringtone", "topic"],
    ["el cargador", "充电器", "charger", "topic"],
    ["la tarjeta SIM", "SIM卡", "SIM card", "topic"],
    ["el teléfono fijo", "座机", "landline", "topic"],
    ["el remitente", "寄件人", "sender", "topic"],
    ["el destinatario", "收件人", "recipient", "topic"],
    ["el código postal", "邮编", "postcode", "topic"],
    ["la postal", "明信片", "postcard", "topic"],
    ["la carta certificada", "挂号信", "registered letter", "topic"],
    ["el buzón", "邮箱", "mailbox", "topic"],
    ["atentamente", "此致敬礼", "yours sincerely", "topic"],
    ["el adjunto", "附件", "attachment", "topic"],
    ["el asunto", "主题行", "subject", "topic"],
    ["el reenvío", "转发", "forward", "topic"],
    ["el correo basura", "垃圾邮件", "spam", "topic"],
    ["la bandeja de entrada", "收件箱", "inbox", "topic"]
  );
})();
