/* =====================================================
   FUGA MYTHICA — CURSUS German 🇩🇪 · batch 3 (band 2000–3000)
   Native Germanic root families (the strong-verb stems and their nouns/adjectives), separable-prefix
   families (aus-/ein-/über-/unter-/durch-/um-/zu-/nach-/weg-/zurück-), and compound nouns by head.
   ===================================================== */
(function () {
  const p = VOCAB.de;
  Object.assign(p.roots, {
    aus: ["aus-", "出,完", "out, finished"], ein: ["ein-", "入", "in"], über: ["über-", "越过", "over"], unter: ["unter-", "下,之间", "under, among"],
    durch: ["durch-", "穿过", "through"], um: ["um-", "环绕,改变", "around, change"], zu: ["zu-", "关,向", "to, shut"], nach: ["nach-", "后,跟随", "after"],
    weg: ["weg-", "离开", "away"], zurück: ["zurück-", "回", "back"], her: ["her- / hin-", "来,去", "hither, thither"],
    /* strong-verb stems */ geh: ["geh- / gang-", "走", "go"], steh: ["steh- / stand-", "站", "stand"], nehm: ["nehm- / nahm-", "拿", "take"], geb: ["geb- / gab-", "给", "give"],
    seh: ["seh- / sicht-", "看", "see"], sprech: ["sprech- / sprach-", "说", "speak"], schreib: ["schreib- / schrift-", "写", "write"], les: ["les-", "读", "read"],
    fahr: ["fahr- / fuhr-", "行驶", "drive"], trag: ["trag- / tracht-", "携带", "carry"], zieh: ["zieh- / zug-", "拉", "pull"], fall: ["fall-", "落", "fall"],
    halt: ["halt-", "持", "hold"], schlag: ["schlag-", "打", "strike"], brech: ["brech- / bruch-", "破", "break"], bind: ["bind- / bund-", "绑", "bind"],
    find: ["find- / fund-", "找", "find"], spring: ["spring- / sprung-", "跳", "jump"], schließ: ["schließ- / schluss-", "关", "shut"], werf: ["werf- / wurf-", "扔", "throw"],
    zwing: ["zwing- / zwang-", "强迫", "force"], setz: ["setz- / satz-", "放", "set"], leg: ["leg- / lag-", "放", "lay"], stell: ["stell-", "放", "place"],
    denk: ["denk- / dacht-", "想", "think"], wiss: ["wiss- / wuss-", "知", "know"], kenn: ["kenn- / kannt-", "认识", "know"], bring: ["bring- / bracht-", "带来", "bring"],
    sitz: ["sitz- / sass-", "坐", "sit"], lieg: ["lieg- / lag-", "躺", "lie"], lauf: ["lauf- / lief-", "跑", "run"], flieg: ["flieg- / flug-", "飞", "fly"],
    wachs: ["wachs- / wuchs-", "生长", "grow"], sterb: ["sterb- / starb-", "死", "die"], leb: ["leb-", "活", "live"], lieb: ["lieb-", "爱", "love"],
    /* compound heads */ haus: ["-haus", "屋", "house"], zeug: ["-zeug", "工具", "tool, stuff"], werk: ["-werk", "作品,厂", "work"], schaft2: ["-schaft", "集体", "collective"],
    zeit: ["-zeit", "时间", "time"], platz: ["-platz", "场所", "place"], raum: ["-raum", "空间", "room"], stück: ["-stück", "件", "piece"],
  });
  p.words.push(
    /* aus- */ ["ausgehen","出去","go out","aus"], ["ausmachen","关掉,约定","turn off, arrange","aus"], ["aussehen","看起来","look","aus"], ["ausbilden","培训","train","aus"], ["die Ausbildung","培训","training","aus"], ["ausdrücken","表达","express","aus"], ["der Ausdruck","表达","expression","aus"], ["ausgeben","花费","spend","aus"], ["die Ausgabe","支出,版本","expense, edition","aus"], ["ausschließen","排除","exclude","aus"], ["ausstellen","展出","exhibit","aus"], ["die Ausstellung","展览","exhibition","aus"], ["auswählen","选择","select","aus"], ["die Auswahl","选择","selection","aus"], ["auswandern","移民","emigrate","aus"], ["der Ausgang","出口","exit","aus"], ["die Ausnahme","例外","exception","aus"], ["die Aussicht","景色,前景","view, prospect","aus"],
    /* ein- */ ["einkaufen","购物","shop","ein"], ["einladen","邀请","invite","ein"], ["die Einladung","邀请","invitation","ein"], ["einschlafen","入睡","fall asleep","ein"], ["einsteigen","上车","get in","ein"], ["eintreten","进入","enter","ein"], ["der Eintritt","入场","entry","ein"], ["einführen","引进","introduce","ein"], ["der Eingang","入口","entrance","ein"], ["der Einfluss","影响","influence","ein"], ["einsetzen","投入","deploy","ein"], ["die Einstellung","态度,设置","attitude, setting","ein"], ["einrichten","布置","furnish","ein"], ["der Eindruck","印象","impression","ein"], ["die Einheit","单位,统一","unit, unity","ein"],
    /* über- */ ["übersetzen","翻译","translate","über"], ["die Übersetzung","翻译","translation","über"], ["überzeugen","说服","convince","über"], ["überlegen","考虑","consider","über"], ["überraschen","使惊讶","surprise","über"], ["die Überraschung","惊喜","surprise","über"], ["überleben","幸存","survive","über"], ["übernehmen","接管","take over","über"], ["überprüfen","检查","check","über"], ["die Überschrift","标题","heading","über"], ["der Überblick","概览","overview","über"], ["übertreiben","夸张","exaggerate","über"], ["überall","到处","everywhere","über"],
    /* unter- */ ["unterrichten","教","teach","unter"], ["der Unterricht","课","lesson","unter"], ["unterscheiden","区分","distinguish","unter"], ["der Unterschied","区别","difference","unter"], ["unterstützen","支持","support","unter"], ["die Unterstützung","支持","support","unter"], ["untersuchen","检查","examine","unter"], ["die Untersuchung","检查","examination","unter"], ["unterhalten","娱乐,交谈","entertain, converse","unter"], ["die Unterhaltung","娱乐","entertainment","unter"], ["unterschreiben","签字","sign","unter"], ["das Unternehmen","企业","company","unter"], ["unterbrechen","打断","interrupt","unter"], ["die Unterkunft","住宿","accommodation","unter"],
    /* durch- / um- */ ["durchführen","实施","carry out","durch"], ["durchsetzen","贯彻","enforce","durch"], ["der Durchschnitt","平均","average","durch"], ["durchsuchen","搜查","search","durch"], ["der Durchbruch","突破","breakthrough","durch"], ["durchaus","完全","absolutely","durch"], ["umziehen","搬家","move house","um"], ["der Umzug","搬家","move","um"], ["umsteigen","换乘","change trains","um"], ["die Umwelt","环境","environment","um"], ["der Umweg","绕路","detour","um"], ["umgehen","应对","deal with","um"], ["die Umfrage","调查","survey","um"], ["umfassen","包括","comprise","um"], ["der Umsatz","营业额","turnover","um"], ["umsonst","免费,徒劳","free, in vain","um"],
    /* zu- / nach- / weg- / zurück- / her- */ ["zumachen","关上","close","zu"], ["zuhören","倾听","listen","zu"], ["zunehmen","增加","increase","zu"], ["die Zukunft","未来","future","zu"], ["der Zugang","通道","access","zu"], ["zustimmen","同意","agree","zu"], ["der Zustand","状态","condition","zu"], ["die Zusammenarbeit","合作","cooperation","zu"], ["nachdenken","思考","reflect","nach"], ["nachfragen","询问","inquire","nach"], ["die Nachfrage","需求","demand","nach"], ["die Nachricht","消息","news","nach"], ["der Nachteil","缺点","disadvantage","nach"], ["der Nachbar","邻居","neighbour","nach"], ["der Nachmittag","下午","afternoon","nach"], ["weggehen","离开","go away","weg"], ["wegwerfen","扔掉","throw away","weg"], ["wegnehmen","拿走","take away","weg"], ["zurückkommen","回来","come back","zurück"], ["zurückgeben","归还","give back","zurück"], ["die Zurückhaltung","克制","restraint","zurück"], ["herstellen","生产","produce","her"], ["die Herstellung","生产","production","her"], ["die Herkunft","出身","origin","her"], ["hinweisen","指出","point out","her"], ["der Hinweis","提示","hint","her"], ["der Hintergrund","背景","background","her"],
    /* strong-verb families */ ["gehen","走","go","geh"], ["der Gang","走廊,步态","corridor, gait","geh"], ["vergehen","消逝","pass","geh"], ["die Vergangenheit","过去","past","geh"], ["der Vorgang","过程","process","geh"], ["der Übergang","过渡","transition","geh"], ["zugänglich","可进入的","accessible","geh"],
    ["stehen","站","stand","steh"], ["der Stand","状态,摊位","state, stall","steh"], ["verstehen","理解","understand","steh"], ["das Verständnis","理解","understanding","steh"], ["entstehen","产生","arise","steh"], ["der Zustand","状态","condition","steh"], ["der Abstand","距离","distance","steh"], ["der Aufstand","起义","uprising","steh"], ["ständig","持续的","constant","steh"], ["der Gegenstand","物体","object","steh"], ["selbstständig","独立的","independent","steh"],
    ["nehmen","拿","take","nehm"], ["die Aufnahme","录音,接纳","recording, admission","nehm"], ["die Ausnahme","例外","exception","nehm"], ["die Teilnahme","参与","participation","nehm"], ["teilnehmen","参加","take part","nehm"], ["angenehm","舒适的","pleasant","nehm"], ["die Unternehmung","事业","undertaking","nehm"], ["vernehmen","听到","hear","nehm"],
    ["geben","给","give","geb"], ["die Gabe","天赋,礼物","gift","geb"], ["die Aufgabe","任务","task","geb"], ["die Abgabe","上交,税","submission, levy","geb"], ["die Angabe","说明","statement","geb"], ["das Ergebnis","结果","result","geb"], ["ergeben","产生","result in","geb"], ["die Umgebung","周围","surroundings","geb"], ["begabt","有天赋的","gifted","geb"],
    ["sehen","看","see","seh"], ["die Sicht","视野","view","seh"], ["die Absicht","意图","intention","seh"], ["die Aufsicht","监督","supervision","seh"], ["die Rücksicht","顾及","consideration","seh"], ["die Vorsicht","小心","caution","seh"], ["offensichtlich","明显的","obvious","seh"], ["die Ansicht","观点","view","seh"], ["besichtigen","参观","visit","seh"],
    ["sprechen","说","speak","sprech"], ["die Sprache","语言","language","sprech"], ["das Gespräch","谈话","conversation","sprech"], ["versprechen","承诺","promise","sprech"], ["das Versprechen","承诺","promise","sprech"], ["der Spruch","格言","saying","sprech"], ["der Anspruch","要求","claim","sprech"], ["entsprechend","相应的","corresponding","sprech"], ["widersprechen","反驳","contradict","sprech"], ["der Widerspruch","矛盾","contradiction","sprech"],
    ["schreiben","写","write","schreib"], ["die Schrift","文字","script","schreib"], ["der Schriftsteller","作家","writer","schreib"], ["die Vorschrift","规定","regulation","schreib"], ["die Unterschrift","签名","signature","schreib"], ["die Zeitschrift","杂志","magazine","schreib"], ["beschreiben","描述","describe","schreib"], ["die Beschreibung","描述","description","schreib"], ["abschreiben","抄写","copy","schreib"],
    ["lesen","读","read","les"], ["der Leser","读者","reader","les"], ["die Lesung","朗读会","reading","les"], ["vorlesen","朗读","read aloud","les"], ["auslesen","挑选","pick out","les"], ["die Auslese","精选","selection","les"],
    ["fahren","行驶","drive","fahr"], ["die Fahrt","行程","journey","fahr"], ["die Erfahrung","经验","experience","fahr"], ["die Gefahr","危险","danger","fahr"], ["gefährlich","危险的","dangerous","fahr"], ["der Fahrer","司机","driver","fahr"], ["das Fahrrad","自行车","bicycle","fahr"], ["das Verfahren","程序","procedure","fahr"], ["die Abfahrt","出发","departure","fahr"],
    ["tragen","携带","carry","trag"], ["der Vertrag","合同","contract","trag"], ["der Antrag","申请","application","trag"], ["der Auftrag","委托","order","trag"], ["der Beitrag","贡献","contribution","trag"], ["beitragen","贡献","contribute","trag"], ["der Vortrag","报告","lecture","trag"], ["ertragen","忍受","bear","trag"], ["die Tracht","传统服装","costume","trag"],
    ["ziehen","拉","pull","zieh"], ["der Zug","火车","train","zieh"], ["der Bezug","关系","relation","zieh"], ["der Vorzug","优点","advantage","zieh"], ["erziehen","教育","educate","zieh"], ["die Erziehung","教育","upbringing","zieh"], ["die Beziehung","关系","relationship","zieh"], ["beziehen","获得,涉及","obtain, relate","zieh"], ["der Anzug","西装","suit","zieh"], ["der Umzug","搬家,游行","move, parade","zieh"],
    ["fallen","落","fall","fall"], ["der Fall","情况,案例","case","fall"], ["der Unfall","事故","accident","fall"], ["der Zufall","巧合","coincidence","fall"], ["zufällig","偶然的","by chance","fall"], ["der Abfall","垃圾","waste","fall"], ["der Beifall","掌声","applause","fall"], ["gefallen","喜欢","please","fall"], ["auffallen","引人注目","stand out","fall"], ["der Vorfall","事件","incident","fall"], ["der Einfall","想法","idea","fall"],
    ["halten","持","hold","halt"], ["der Halt","停止,支撑","stop, hold","halt"], ["der Inhalt","内容","content","halt"], ["das Verhalten","行为","behaviour","halt"], ["sich verhalten","表现","behave","halt"], ["das Verhältnis","关系","relationship","halt"], ["erhalten","收到","receive","halt"], ["der Haushalt","家务,预算","household, budget","halt"], ["die Haltung","姿态","posture","halt"], ["der Aufenthalt","逗留","stay","halt"],
    ["schlagen","打","strike","schlag"], ["der Schlag","打击","blow","schlag"], ["der Vorschlag","建议","proposal","schlag"], ["vorschlagen","建议","suggest","schlag"], ["der Anschlag","袭击","attack","schlag"], ["der Zuschlag","附加费","surcharge","schlag"], ["die Niederlage","失败","defeat","schlag"], ["der Umschlag","信封","envelope","schlag"], ["nachschlagen","查阅","look up","schlag"],
    ["brechen","破","break","brech"], ["der Bruch","断裂","break","brech"], ["der Ausbruch","爆发","outbreak","brech"], ["der Einbruch","入室盗窃","burglary","brech"], ["die Unterbrechung","中断","interruption","brech"], ["der Abbruch","拆除,中止","demolition, abort","brech"], ["zerbrechlich","易碎的","fragile","brech"], ["das Verbrechen","犯罪","crime","brech"], ["der Verbrecher","罪犯","criminal","brech"],
    ["binden","绑","bind","bind"], ["der Bund","联邦","federation","bind"], ["das Bündnis","联盟","alliance","bind"], ["die Verbindung","连接","connection","bind"], ["verbinden","连接","connect","bind"], ["das Band","带子","ribbon","bind"], ["der Verband","协会,绷带","association, bandage","bind"], ["verbindlich","有约束力的","binding","bind"],
    ["finden","找","find","find"], ["der Fund","发现物","find","find"], ["erfinden","发明","invent","find"], ["die Erfindung","发明","invention","find"], ["der Erfinder","发明家","inventor","find"], ["empfinden","感受","feel","find"], ["die Empfindung","感受","sensation","find"], ["befinden","位于","be located","find"], ["stattfinden","举行","take place","find"],
    ["springen","跳","jump","spring"], ["der Sprung","跳跃","jump","spring"], ["der Ursprung","起源","origin","spring"], ["ursprünglich","原始的","original","spring"], ["der Vorsprung","领先","lead","spring"], ["entspringen","发源","originate","spring"],
    ["schließen","关","shut","schließ"], ["der Schluss","结束","end","schließ"], ["der Beschluss","决议","resolution","schließ"], ["der Abschluss","结业","completion","schließ"], ["der Anschluss","连接","connection","schließ"], ["der Ausschluss","排除","exclusion","schließ"], ["die Entschlossenheit","决心","determination","schließ"], ["der Schlüssel","钥匙","key","schließ"], ["schließlich","最终","finally","schließ"],
    ["werfen","扔","throw","werf"], ["der Wurf","投掷","throw","werf"], ["der Entwurf","草案","draft","werf"], ["der Vorwurf","指责","reproach","werf"], ["vorwerfen","指责","reproach","werf"], ["der Auswurf","排出物","ejection","werf"], ["unterwerfen","征服","subjugate","werf"],
    ["zwingen","强迫","force","zwing"], ["der Zwang","强迫","compulsion","zwing"], ["zwingend","强制的","compelling","zwing"], ["erzwingen","强行获得","force","zwing"], ["bezwingen","征服","overcome","zwing"],
    ["setzen","放","set","setz"], ["der Satz","句子","sentence","setz"], ["das Gesetz","法律","law","setz"], ["der Einsatz","投入","deployment","setz"], ["der Ersatz","替代","replacement","setz"], ["ersetzen","替换","replace","setz"], ["die Übersetzung","翻译","translation","setz"], ["besetzen","占据","occupy","setz"], ["fortsetzen","继续","continue","setz"], ["der Gegensatz","对立","contrast","setz"], ["der Vorsatz","决心","resolution","setz"],
    ["legen","放","lay","leg"], ["die Lage","位置,形势","position, situation","leg"], ["die Anlage","设施,附件","facility, attachment","leg"], ["die Grundlage","基础","basis","leg"], ["die Vorlage","模板","template","leg"], ["die Unterlage","文件","document","leg"], ["überlegen","考虑","consider","leg"], ["erlegen","击毙","kill","leg"], ["die Niederlage","失败","defeat","leg"], ["der Verlag","出版社","publisher","leg"], ["die Beilage","附页,配菜","supplement, side dish","leg"],
    ["stellen","放","place","stell"], ["die Stelle","位置,职位","place, job","stell"], ["die Stellung","地位","position","stell"], ["die Vorstellung","介绍,想象","introduction, idea","stell"], ["die Herstellung","生产","production","stell"], ["die Ausstellung","展览","exhibition","stell"], ["die Einstellung","态度","attitude","stell"], ["die Bestellung","订单","order","stell"], ["die Feststellung","确定","finding","stell"], ["darstellen","描绘","depict","stell"], ["die Darstellung","描绘","depiction","stell"],
    ["denken","想","think","denk"], ["der Gedanke","想法","thought","denk"], ["das Andenken","纪念品","souvenir","denk"], ["das Bedenken","顾虑","concern","denk"], ["bedenken","考虑","consider","denk"], ["das Denkmal","纪念碑","monument","denk"], ["nachdenklich","沉思的","thoughtful","denk"], ["undenkbar","不可想象的","unthinkable","denk"], ["das Gedächtnis","记忆","memory","denk"],
    ["wissen","知道","know","wiss"], ["das Wissen","知识","knowledge","wiss"], ["die Wissenschaft","科学","science","wiss"], ["der Wissenschaftler","科学家","scientist","wiss"], ["das Gewissen","良心","conscience","wiss"], ["gewiss","确定的","certain","wiss"], ["bewusst","有意识的","conscious","wiss"], ["das Bewusstsein","意识","consciousness","wiss"], ["der Beweis","证据","proof","wiss"],
    ["kennen","认识","know","kenn"], ["die Kenntnis","知识","knowledge","kenn"], ["erkennen","认出","recognize","kenn"], ["die Erkenntnis","认识","insight","kenn"], ["bekannt","著名的","well-known","kenn"], ["der Bekannte","熟人","acquaintance","kenn"], ["anerkennen","承认","acknowledge","kenn"], ["das Kennzeichen","标志,车牌","mark, licence plate","kenn"],
    ["bringen","带来","bring","bring"], ["verbringen","度过","spend (time)","bring"], ["umbringen","杀死","kill","bring"], ["unterbringen","安置","accommodate","bring"], ["beibringen","教会","teach","bring"], ["aufbringen","筹集","raise","bring"], ["hervorbringen","产生","produce","bring"],
    ["sitzen","坐","sit","sitz"], ["der Sitz","座位,总部","seat, headquarters","sitz"], ["der Besitz","财产","possession","sitz"], ["besitzen","拥有","own","sitz"], ["der Besitzer","主人","owner","sitz"], ["der Vorsitz","主席职位","chairmanship","sitz"], ["die Sitzung","会议","session","sitz"], ["der Wohnsitz","住所","residence","sitz"],
    ["liegen","躺","lie","lieg"], ["die Lage","位置","location","lieg"], ["gelegen","位于","situated","lieg"], ["die Gelegenheit","机会","opportunity","lieg"], ["das Anliegen","关切","concern","lieg"], ["vorliegen","存在","be present","lieg"], ["unterliegen","受制于","be subject to","lieg"], ["zugrunde liegen","是…的基础","underlie","lieg"],
    ["laufen","跑","run","lauf"], ["der Lauf","跑,进程","run, course","lauf"], ["der Verlauf","过程","course","lauf"], ["verlaufen","进行","proceed","lauf"], ["der Ablauf","流程","sequence","lauf"], ["das Laufwerk","驱动器","drive","lauf"], ["der Läufer","跑者","runner","lauf"], ["vorläufig","暂时的","provisional","lauf"], ["geläufig","常见的","common","lauf"],
    ["fliegen","飞","fly","flieg"], ["der Flug","航班","flight","flieg"], ["der Flughafen","机场","airport","flieg"], ["das Flugzeug","飞机","aeroplane","flieg"], ["die Fliege","苍蝇","fly","flieg"], ["der Ausflug","远足","excursion","flieg"], ["flüchtig","短暂的","fleeting","flieg"],
    ["wachsen","生长","grow","wachs"], ["das Wachstum","增长","growth","wachs"], ["erwachsen","成年的","grown-up","wachs"], ["der Erwachsene","成年人","adult","wachs"], ["der Zuwachs","增长","increase","wachs"], ["das Gewächs","植物","plant","wachs"],
    ["sterben","死","die","sterb"], ["der Tod","死亡","death","sterb"], ["sterblich","凡人的","mortal","sterb"], ["unsterblich","不朽的","immortal","sterb"], ["aussterben","灭绝","die out","sterb"], ["der Sterbliche","凡人","mortal","sterb"],
    ["leben","活","live","leb"], ["das Leben","生活","life","leb"], ["lebendig","活的","alive","leb"], ["das Erlebnis","经历","experience","leb"], ["erleben","经历","experience","leb"], ["überleben","幸存","survive","leb"], ["das Lebewesen","生物","living being","leb"], ["lebhaft","活泼的","lively","leb"], ["der Lebenslauf","简历","CV","leb"],
    ["lieben","爱","love","lieb"], ["die Liebe","爱","love","lieb"], ["lieb","亲爱的","dear","lieb"], ["der Liebling","宠儿","darling","lieb"], ["beliebt","受欢迎的","popular","lieb"], ["verlieben","爱上","fall in love","lieb"], ["liebevoll","充满爱的","loving","lieb"], ["die Vorliebe","偏好","preference","lieb"],
    /* compound heads */ ["das Krankenhaus","医院","hospital","haus"], ["das Rathaus","市政厅","town hall","haus"], ["das Kaufhaus","百货商店","department store","haus"], ["das Hochhaus","高楼","high-rise","haus"], ["das Gasthaus","客栈","inn","haus"], ["das Werkzeug","工具","tool","zeug"], ["das Spielzeug","玩具","toy","zeug"], ["das Fahrzeug","车辆","vehicle","zeug"], ["das Feuerzeug","打火机","lighter","zeug"], ["das Zeugnis","成绩单","report card","zeug"], ["das Kunstwerk","艺术品","artwork","werk"], ["das Handwerk","手工艺","craft","werk"], ["das Kraftwerk","发电厂","power plant","werk"], ["das Netzwerk","网络","network","werk"], ["die Werkstatt","车间","workshop","werk"], ["die Freizeit","空闲","leisure","zeit"], ["die Mahlzeit","一餐","meal","zeit"], ["die Jahreszeit","季节","season","zeit"], ["die Gegenwart","现在","present","zeit"], ["der Zeitpunkt","时刻","point in time","zeit"], ["der Zeitraum","时期","period","zeit"], ["der Arbeitsplatz","工作岗位","workplace","platz"], ["der Marktplatz","集市广场","market square","platz"], ["der Spielplatz","游乐场","playground","platz"], ["der Parkplatz","停车场","car park","platz"], ["das Wohnzimmer","客厅","living room","raum"], ["der Weltraum","太空","outer space","raum"], ["der Spielraum","余地","leeway","raum"], ["der Lebensraum","生存空间","habitat","raum"], ["das Frühstück","早餐","breakfast","stück"], ["das Bruchstück","碎片","fragment","stück"], ["das Schmuckstück","首饰","piece of jewellery","stück"], ["das Meisterstück","杰作","masterpiece","stück"]
  );
})();
