/* =====================================================
   FUGA MYTHICA — CURSUS French 🇫🇷 · batch 10 — topical vocabulary: business, law, IT, media, environment, science, health, society, arts, travel, weather
   ===================================================== */
(function () {
  const p = VOCAB.fr;
  Object.assign(p.roots, {});
  p.words.push(
    ["la société anonyme", "股份公司", "corporation", "topic"],
    ["l'actionnaire", "股东", "shareholder", "topic"],
    ["la Bourse", "证券交易所", "stock market", "topic"],
    ["l'investisseur", "投资者", "investor", "topic"],
    ["le chiffre d'affaires", "营业额", "turnover", "topic"],
    ["les recettes", "收入", "revenue", "topic"],
    ["le budget", "预算", "budget", "topic"],
    ["le bilan", "资产负债表", "balance sheet", "topic"],
    ["la date limite", "截止日期", "deadline", "topic"],
    ["l'hypothèque", "抵押贷款", "mortgage", "topic"],
    ["le taux d'intérêt", "利率", "interest rate", "topic"],
    ["le retrait", "取款", "withdrawal", "topic"],
    ["le taux de change", "汇率", "exchange rate", "topic"],
    ["l'inflation", "通胀", "inflation", "topic"],
    ["la concurrence", "竞争", "competition", "topic"],
    ["le concurrent", "竞争者", "competitor", "topic"],
    ["le fournisseur", "供应商", "supplier", "topic"],
    ["le stock", "库存", "stock", "topic"],
    ["la marque", "品牌", "brand", "topic"],
    ["le marketing", "市场营销", "marketing", "topic"],
    ["le commerce de détail", "零售", "retail", "topic"],
    ["le commerce de gros", "批发", "wholesale", "topic"],
    ["le droit de douane", "关税", "tariff", "topic"],
    ["la TVA", "增值税", "VAT", "topic"],
    ["le contribuable", "纳税人", "taxpayer", "topic"],
    ["l'audit", "审计", "audit", "topic"],
    ["l'employeur", "雇主", "employer", "topic"],
    ["le personnel", "员工", "staff", "topic"],
    ["le recrutement", "招聘", "recruitment", "topic"],
    ["le licenciement", "裁员", "dismissal", "topic"],
    ["la grève", "罢工", "strike", "topic"],
    ["le syndicat", "工会", "trade union", "topic"],
    ["les heures supplémentaires", "加班", "overtime", "topic"],
    ["le procès-verbal", "会议记录", "minutes", "topic"],
    ["l'objectif", "目标", "goal", "topic"],
    ["la négociation", "谈判", "negotiation", "topic"],
    ["le partenariat", "合作关系", "partnership", "topic"],
    ["le rachat", "收购", "takeover", "topic"],
    ["la faillite", "破产", "bankruptcy", "topic"],
    ["la start-up", "初创公司", "startup", "topic"],
    ["l'entrepreneur", "企业家", "entrepreneur", "topic"],
    ["le projet de loi", "法案", "bill", "topic"],
    ["le premier ministre", "总理", "prime minister", "topic"],
    ["la coalition", "联合政府", "coalition", "topic"],
    ["le référendum", "公投", "referendum", "topic"],
    ["la dictature", "独裁", "dictatorship", "topic"],
    ["la monarchie", "君主制", "monarchy", "topic"],
    ["le procureur", "检察官", "prosecutor", "topic"],
    ["l'accusé", "被告", "defendant", "topic"],
    ["le témoin", "证人", "witness", "topic"],
    ["l'amende", "罚款", "fine", "topic"],
    ["le prisonnier", "囚犯", "prisoner", "topic"],
    ["la fraude", "欺诈", "fraud", "topic"],
    ["la corruption", "腐败", "corruption", "topic"],
    ["le pot-de-vin", "贿赂", "bribe", "topic"],
    ["la contrebande", "走私", "smuggling", "topic"],
    ["le suspect", "嫌疑人", "suspect", "topic"],
    ["l'arrestation", "逮捕", "arrest", "topic"],
    ["la clause", "条款", "clause", "topic"],
    ["le notaire", "公证人", "notary", "topic"],
    ["le testament", "遗嘱", "will", "topic"],
    ["l'asile", "庇护", "asylum", "topic"],
    ["l'ambassade", "大使馆", "embassy", "topic"],
    ["l'ambassadeur", "大使", "ambassador", "topic"],
    ["l'alliance", "联盟", "alliance", "topic"],
    ["l'attaque", "攻击", "attack", "topic"],
    ["le terrorisme", "恐怖主义", "terrorism", "topic"],
    ["la manifestation", "示威", "demonstration", "topic"],
    ["les droits de l'homme", "人权", "human rights", "topic"],
    ["l'ordinateur portable", "笔记本电脑", "laptop", "topic"],
    ["la tablette", "平板电脑", "tablet", "topic"],
    ["le smartphone", "智能手机", "smartphone", "topic"],
    ["l'imprimante", "打印机", "printer", "topic"],
    ["le fichier", "文件", "file", "topic"],
    ["le dossier", "文件夹", "folder", "topic"],
    ["le logiciel", "软件", "software", "topic"],
    ["le matériel", "硬件", "hardware", "topic"],
    ["l'application", "应用程序", "app", "topic"],
    ["la mise à jour", "更新", "update", "topic"],
    ["le téléchargement", "下载", "download", "topic"],
    ["l'internet", "互联网", "internet", "topic"],
    ["le navigateur", "浏览器", "browser", "topic"],
    ["le moteur de recherche", "搜索引擎", "search engine", "topic"],
    ["la pièce jointe", "附件", "attachment", "topic"],
    ["l'utilisateur", "用户", "user", "topic"],
    ["les données", "数据", "data", "topic"],
    ["la base de données", "数据库", "database", "topic"],
    ["le virus", "病毒", "virus", "topic"],
    ["le pirate informatique", "黑客", "hacker", "topic"],
    ["la vie privée", "隐私", "privacy", "topic"],
    ["l'intelligence artificielle", "人工智能", "AI", "topic"],
    ["l'algorithme", "算法", "algorithm", "topic"],
    ["le code", "代码", "code", "topic"],
    ["le réseau social", "社交网络", "social network", "topic"],
    ["l'abonné", "关注者", "follower", "topic"],
    ["le podcast", "播客", "podcast", "topic"],
    ["le titre", "标题", "headline", "topic"],
    ["le rédacteur en chef", "编辑", "editor", "topic"],
    ["la conférence de presse", "新闻发布会", "press conference", "topic"],
    ["la chaîne", "频道", "channel", "topic"],
    ["le téléspectateur", "观众", "viewer", "topic"],
    ["les fausses nouvelles", "假新闻", "fake news", "topic"],
    ["la censure", "审查", "censorship", "topic"],
    ["le changement climatique", "气候变化", "climate change", "topic"],
    ["le réchauffement climatique", "全球变暖", "global warming", "topic"],
    ["l'effet de serre", "温室效应", "greenhouse effect", "topic"],
    ["le dioxyde de carbone", "二氧化碳", "CO2", "topic"],
    ["l'énergie renouvelable", "可再生能源", "renewable energy", "topic"],
    ["le panneau solaire", "太阳能板", "solar panel", "topic"],
    ["l'éolienne", "风力涡轮机", "wind turbine", "topic"],
    ["le combustible fossile", "化石燃料", "fossil fuel", "topic"],
    ["le gaz naturel", "天然气", "natural gas", "topic"],
    ["l'énergie nucléaire", "核能", "nuclear power", "topic"],
    ["la centrale", "发电厂", "power station", "topic"],
    ["le plastique", "塑料", "plastic", "topic"],
    ["la sécheresse", "干旱", "drought", "topic"],
    ["le tremblement de terre", "地震", "earthquake", "topic"],
    ["l'ouragan", "飓风", "hurricane", "topic"],
    ["l'incendie de forêt", "野火", "wildfire", "topic"],
    ["la déforestation", "森林砍伐", "deforestation", "topic"],
    ["la biodiversité", "生物多样性", "biodiversity", "topic"],
    ["l'espèce menacée", "濒危物种", "endangered species", "topic"],
    ["l'habitat", "栖息地", "habitat", "topic"],
    ["la faune", "野生动物", "wildlife", "topic"],
    ["la couche d'ozone", "臭氧层", "ozone layer", "topic"],
    ["la durabilité", "可持续性", "sustainability", "topic"],
    ["la théorie", "理论", "theory", "topic"],
    ["l'ADN", "DNA", "DNA", "topic"],
    ["la vitesse de la lumière", "光速", "speed of light", "topic"],
    ["la galaxie", "星系", "galaxy", "topic"],
    ["le satellite", "卫星", "satellite", "topic"],
    ["le vaisseau spatial", "宇宙飞船", "spacecraft", "topic"],
    ["le symptôme", "症状", "symptom", "topic"],
    ["l'infection", "感染", "infection", "topic"],
    ["la pandémie", "大流行", "pandemic", "topic"],
    ["la tension artérielle", "血压", "blood pressure", "topic"],
    ["la crise cardiaque", "心脏病发作", "heart attack", "topic"],
    ["l'accident vasculaire cérébral", "中风", "stroke", "topic"],
    ["le cancer", "癌症", "cancer", "topic"],
    ["le diabète", "糖尿病", "diabetes", "topic"],
    ["la santé mentale", "心理健康", "mental health", "topic"],
    ["la dépression", "抑郁症", "depression", "topic"],
    ["le stress", "压力", "stress", "topic"],
    ["les personnes âgées", "老年人", "elderly", "topic"],
    ["l'inégalité", "不平等", "inequality", "topic"],
    ["le sans-abrisme", "无家可归", "homelessness", "topic"],
    ["l'association caritative", "慈善机构", "charity", "topic"],
    ["le bénévole", "志愿者", "volunteer", "topic"],
    ["l'aide sociale", "社会福利", "welfare", "topic"],
    ["les soins de santé", "医疗保健", "healthcare", "topic"],
    ["la bourse", "奖学金", "scholarship", "topic"],
    ["le cours magistral", "讲座", "lecture", "topic"],
    ["le séminaire", "研讨会", "seminar", "topic"],
    ["le mémoire", "论文", "thesis", "topic"],
    ["les frais de scolarité", "学费", "tuition fees", "topic"],
    ["le racisme", "种族主义", "racism", "topic"],
    ["le féminisme", "女权主义", "feminism", "topic"],
    ["la tradition", "传统", "tradition", "topic"],
    ["la coutume", "习俗", "custom", "topic"],
    ["la mosquée", "清真寺", "mosque", "topic"],
    ["la synagogue", "犹太会堂", "synagogue", "topic"],
    ["le temple", "寺庙", "temple", "topic"],
    ["le prêtre", "神父", "priest", "topic"],
    ["la prière", "祈祷", "prayer", "topic"],
    ["le paradis", "天堂", "heaven", "topic"],
    ["l'enfer", "地狱", "hell", "topic"],
    ["les funérailles", "葬礼", "funeral", "topic"],
    ["le cimetière", "墓地", "cemetery", "topic"],
    ["le baptême", "洗礼", "baptism", "topic"],
    ["l'architecture", "建筑学", "architecture", "topic"],
    ["la sculpture", "雕塑", "sculpture", "topic"],
    ["la galerie", "画廊", "gallery", "topic"],
    ["l'orchestre", "管弦乐队", "orchestra", "topic"],
    ["le chef d'orchestre", "指挥", "conductor", "topic"],
    ["le ballet", "芭蕾", "ballet", "topic"],
    ["la chorale", "合唱团", "choir", "topic"],
    ["le piano", "钢琴", "piano", "topic"],
    ["le violon", "小提琴", "violin", "topic"],
    ["la guitare", "吉他", "guitar", "topic"],
    ["le tambour", "鼓", "drum", "topic"],
    ["la flûte", "长笛", "flute", "topic"],
    ["la trompette", "小号", "trumpet", "topic"],
    ["la répétition", "排练", "rehearsal", "topic"],
    ["la scène", "舞台", "stage", "topic"],
    ["les applaudissements", "掌声", "applause", "topic"],
    ["l'intrigue", "情节", "plot", "topic"],
    ["le personnage", "角色", "character", "topic"],
    ["l'éditeur", "出版社", "publisher", "topic"],
    ["le conte de fées", "童话", "fairy tale", "topic"],
    ["le méchant", "反派", "villain", "topic"],
    ["le dessin animé", "动画片", "cartoon", "topic"],
    ["la bande originale", "原声音乐", "soundtrack", "topic"],
    ["le feu d'artifice", "烟花", "fireworks", "topic"],
    ["le carnaval", "狂欢节", "carnival", "topic"],
    ["le costume", "服装", "costume", "topic"],
    ["l'itinéraire", "行程", "itinerary", "topic"],
    ["le sentier", "小径", "trail", "topic"],
    ["le sommet", "山顶", "summit", "topic"],
    ["la grotte", "洞穴", "cave", "topic"],
    ["la cascade", "瀑布", "waterfall", "topic"],
    ["le volcan", "火山", "volcano", "topic"],
    ["la falaise", "悬崖", "cliff", "topic"],
    ["le phare", "灯塔", "lighthouse", "topic"],
    ["le lever du soleil", "日出", "sunrise", "topic"],
    ["le coucher du soleil", "日落", "sunset", "topic"],
    ["le tonnerre", "雷", "thunder", "topic"],
    ["la grêle", "冰雹", "hail", "topic"],
    ["la brise", "微风", "breeze", "topic"],
    ["la canicule", "热浪", "heatwave", "topic"],
    ["les prévisions", "天气预报", "forecast", "topic"],
    ["l'humidité", "湿度", "humidity", "topic"]
  );
})();
