/* =====================================================
   FUGA MYTHICA — CURSUS Latin · extra 7 — compound verbs of core stems + topical vocabulary
   (topic tags t_* are domains, not roots)
   ===================================================== */
(function () {
  if (typeof LATIN_EXTRA === "undefined") return;
  Object.assign(LATIN_EXTRA.roots, {
    t_mil: ["主题:军事", "领域词汇", "war & army"], t_dom: ["主题:家居与器物", "领域词汇", "house & objects"], t_nat: ["主题:自然与天气", "领域词汇", "nature & weather"],
    t_fauna: ["主题:动物", "领域词汇", "animals"], t_flora: ["主题:植物与农事", "领域词汇", "plants & farming"], t_cib: ["主题:饮食", "领域词汇", "food & drink"],
    t_relig: ["主题:宗教与神话", "领域词汇", "religion & myth"], t_iur: ["主题:法律与政治", "领域词汇", "law & politics"], t_mar: ["主题:航海与旅行", "领域词汇", "sea & travel"],
    t_corp: ["主题:身体与疾病", "领域词汇", "body & illness"], t_adj: ["常用形容词", "无词根,高频必备", "common adjectives"], t_adv: ["常用副词", "无词根,高频必备", "common adverbs"],
    t_abstr: ["抽象名词", "常见后缀 -tas/-tudo/-ia", "abstract nouns"], t_urb: ["主题:城市与建筑", "领域词汇", "city & buildings"], t_ars: ["主题:艺术与学问", "领域词汇", "arts & learning"],
  });
  LATIN_EXTRA.words.push(
    ["adduco", "引来,引导", "bring to", "duco"],
    ["circumduco", "领着绕行", "lead around", "duco"],
    ["deduco", "引下,引出", "lead down", "duco"],
    ["induco", "引入", "lead in", "duco"],
    ["perduco", "引到底", "lead through", "duco"],
    ["seduco", "引开", "lead aside", "duco"],
    ["subduco", "抽走", "draw away", "duco"],
    ["adficio", "影响", "affect", "facio"],
    ["inficio", "染,污染", "infect", "facio"],
    ["praeficio", "委任主管", "put in charge", "facio"],
    ["reficio", "修复", "repair", "facio"],
    ["facinus", "行为,罪行", "deed, crime", "facio"],
    ["appono", "放置旁边", "put beside", "pono"],
    ["praepono", "置于前", "put before", "pono"],
    ["transpono", "转移", "transpose", "pono"],
    ["positus", "放置的", "placed", "pono"],
    ["amitto", "失去", "lose", "mitto"],
    ["demitto", "放下", "let down", "mitto"],
    ["immitto", "放入", "send in", "mitto"],
    ["intermitto", "中断", "interrupt", "mitto"],
    ["praemitto", "先派", "send ahead", "mitto"],
    ["submitto", "置于下", "submit", "mitto"],
    ["missus", "被派的", "sent", "mitto"],
    ["intercipio", "截取", "intercept", "capio"],
    ["captus", "被抓的", "captured", "capio"],
    ["occupo", "占据", "occupy", "capio"],
    ["recupero", "恢复", "recover", "capio"],
    ["adscribo", "添写", "add in writing", "scribo"],
    ["perscribo", "详细写", "write out", "scribo"],
    ["rescribo", "回信", "write back", "scribo"],
    ["transcribo", "抄写", "copy", "scribo"],
    ["scriptum", "著作", "writing", "scribo"],
    ["perlego", "通读", "read through", "lego"],
    ["averto", "转开", "turn away", "verto"],
    ["diverto", "转离", "turn aside", "verto"],
    ["inverto", "颠倒", "invert", "verto"],
    ["perverto", "颠覆", "pervert", "verto"],
    ["subverto", "颠覆", "subvert", "verto"],
    ["devenio", "来到", "arrive", "venio"],
    ["intervenio", "介入", "intervene", "venio"],
    ["praevenio", "先到", "precede", "venio"],
    ["provenio", "产生", "come forth", "venio"],
    ["supervenio", "突然来", "come upon", "venio"],
    ["discurro", "跑散", "run about", "curro"],
    ["percurro", "跑遍", "run through", "curro"],
    ["praecurro", "跑在前", "run ahead", "curro"],
    ["addico", "判给", "assign", "dico"],
    ["condico", "约定", "agree", "dico"],
    ["circumfero", "带着绕", "carry around", "fero"],
    ["effero", "抬出", "carry out", "fero"],
    ["perfero", "忍受", "endure", "fero"],
    ["praefero", "更喜欢", "prefer", "fero"],
    ["profero", "拿出", "bring forth", "fero"],
    ["suffero", "承受", "suffer", "fero"],
    ["fertilis", "肥沃的", "fertile", "fero"],
    ["conicio", "投掷,推测", "throw together", "iacio"],
    ["disicio", "驱散", "scatter", "iacio"],
    ["traicio", "穿过", "throw across", "iacio"],
    ["iactus", "投掷", "throw", "iacio"],
    ["distraho", "拉开", "pull apart", "traho"],
    ["pertraho", "拉到", "drag to", "traho"],
    ["protraho", "拖延", "prolong", "traho"],
    ["exstruo", "建起", "build up", "struo"],
    ["digredior", "离开", "depart", "gradior"],
    ["decedo", "离开,死", "depart", "cedo"],
    ["intercedo", "介入", "intervene", "cedo"],
    ["secedo", "退出", "secede", "cedo"],
    ["cessus", "退让", "yielding", "cedo"],
    ["cesso", "停止", "cease", "cedo"],
    ["irrumpo", "闯入", "burst in", "rumpo"],
    ["perrumpo", "冲破", "break through", "rumpo"],
    ["ruptus", "破裂的", "broken", "rumpo"],
    ["occludo", "封闭", "shut up", "claudo"],
    ["praecludo", "关闭", "close off", "claudo"],
    ["recludo", "打开", "open", "claudo"],
    ["secludo", "隔离", "seclude", "claudo"],
    ["depello", "赶走", "drive off", "pello"],
    ["dispello", "驱散", "dispel", "pello"],
    ["pulso", "敲打", "strike", "pello"],
    ["reprimo", "压制", "repress", "premo"],
    ["pressus", "压的", "pressed", "premo"],
    ["distendo", "拉伸", "stretch out", "tendo"],
    ["protendo", "伸出", "stretch forth", "tendo"],
    ["pervinco", "完全征服", "prevail", "vinco"],
    ["exsolvo", "解开", "release", "solvo"],
    ["admoveo", "移近", "move to", "moveo"],
    ["demoveo", "移走", "move away", "moveo"],
    ["emoveo", "移出", "move out", "moveo"],
    ["permoveo", "深深打动", "move thoroughly", "moveo"],
    ["submoveo", "驱离", "move away", "moveo"],
    ["defluo", "流下", "flow down", "fluo"],
    ["perfluo", "流过", "flow through", "fluo"],
    ["profluo", "涌出", "flow forth", "fluo"],
    ["refluo", "回流", "flow back", "fluo"],
    ["fluxus", "流动", "flow", "fluo"],
    ["dependo", "付出", "pay", "pendo"],
    ["impendo", "花费", "spend", "pendo"],
    ["perpendo", "仔细权衡", "weigh carefully", "pendo"],
    ["scala", "梯子", "ladder", "scando"],
    ["assentio", "同意", "assent", "sentio"],
    ["vivax", "长寿的", "long-lived", "vivo"],
    ["enascor", "长出", "spring up", "nascor"],
    ["innascor", "天生", "be born in", "nascor"],
    ["genitus", "所生的", "begotten", "gigno"],
    ["excresco", "长出", "grow out", "cresco"],
    ["crescens", "增长的", "growing", "cresco"],
    ["circumspicio", "环顾", "look around", "specio"],
    ["adigo", "驱使", "drive to", "ago"],
    ["perago", "完成", "carry through", "ago"],
    ["transigo", "了结", "settle", "ago"],
    ["abscido", "切断", "cut off", "caedo"],
    ["excido", "砍掉", "cut out", "caedo"],
    ["succido", "砍倒", "cut down", "caedo"],
    ["caesus", "被砍的", "cut", "caedo"],
    ["declivis", "下坡的", "sloping", "clino"],
    ["curatio", "治疗", "treatment", "curo"],
    ["donator", "捐赠者", "donor", "dono"],
    ["erratum", "错误", "mistake", "erro"],
    ["refringo", "折断", "break open", "frango"],
    ["fragor", "巨响", "crash", "frango"],
    ["defugio", "逃避", "shun", "fugio"],
    ["profugio", "逃亡", "flee", "fugio"],
    ["fugax", "易逝的", "fleeting", "fugio"],
    ["affundo", "倒入", "pour on", "fundo"],
    ["offundo", "覆盖", "pour over", "fundo"],
    ["perfundo", "浇遍", "drench", "fundo"],
    ["suffundo", "注入下面", "suffuse", "fundo"],
    ["cohibeo", "抑制", "restrain", "habeo"],
    ["habitatio", "住所", "dwelling", "habeo"],
    ["habena", "缰绳", "rein", "habeo"],
    ["iniungo", "加于", "impose", "iungo"],
    ["subiungo", "附加", "subjoin", "iungo"],
    ["iunctura", "接合", "joint", "iungo"],
    ["praeludo", "预演", "prelude", "ludo"],
    ["ludicrum", "娱乐", "amusement", "ludo"],
    ["lusus", "游戏", "play", "ludo"],
    ["mersus", "被淹的", "sunk", "mergo"],
    ["monitum", "警告", "warning", "moneo"],
    ["adnuntio", "宣布", "announce", "nuntio"],
    ["nuntia", "女信使", "messenger", "nuntio"],
    ["impeto", "攻击", "attack", "peto"],
    ["oppeto", "遭遇", "encounter", "peto"],
    ["suppeto", "够用", "be available", "peto"],
    ["plica", "褶", "fold", "plico"],
    ["perquiro", "详查", "search thoroughly", "quaero"],
    ["quaestus", "收益", "gain", "quaero"],
    ["assequor", "追上", "attain", "sequor"],
    ["obsequor", "顺从", "comply", "sequor"],
    ["spiraculum", "气孔", "air-hole", "spiro"],
    ["pertempto", "试探", "test thoroughly", "tempto"],
    ["temptator", "诱惑者", "tempter", "tempto"],
    ["torques", "项圈", "collar", "torqueo"],
    ["tribunus", "保民官", "tribune", "tribuo"],
    ["tribunal", "法庭", "tribunal", "tribuo"],
    ["exturbo", "赶出", "drive out", "turbo"],
    ["vadosus", "浅的", "shallow", "vado"],
    ["circumeo", "绕行", "go around", "eo"],
    ["coeo", "聚合", "come together", "eo"],
    ["intereo", "灭亡", "perish", "eo"],
    ["praeeo", "走在前", "go before", "eo"],
    ["prodeo", "出现", "come forth", "eo"],
    ["subeo", "承受", "undergo", "eo"],
    ["itus", "去", "going", "eo"],
    ["insum", "在其中", "be in", "sum"],
    ["obsum", "有害", "be against", "sum"],
    ["subsum", "在下面", "be under", "sum"],
    ["supersum", "剩余", "survive", "sum"],
    ["potens", "有力的", "powerful", "sum"],
    ["credo2", "托付", "entrust", "do"],
    ["edo2", "发出,产生", "give out", "do"],
    ["indo", "放入", "put in", "do"],
    ["subdo", "置于下", "put under", "do"],
    ["donatus", "被赠的", "given", "do"],
    ["perditus", "毁掉的", "ruined", "do"],
    ["porta2", "城门", "gate", "porto"],
    ["attineo", "涉及", "pertain", "teneo"],
    ["tenor", "连续,方向", "course", "teneo"],
    ["tentus2", "被握的", "held", "teneo"],
    ["continuus", "连续的", "continuous", "teneo"],
    ["contentus", "满足的", "content", "teneo"],
    ["pertinax", "固执的", "stubborn", "teneo"],
    ["consido", "坐下,定居", "settle", "sedeo"],
    ["desideo", "闲坐", "sit idle", "sedeo"],
    ["dissideo", "不和", "disagree", "sedeo"],
    ["insideo", "坐于上", "sit upon", "sedeo"],
    ["subsido", "沉降", "sink down", "sedeo"],
    ["sedile", "座椅", "seat", "sedeo"],
    ["obsidio", "围攻", "siege", "sedeo"],
    ["disto", "相距", "be distant", "sto"],
    ["supersto", "站在上面", "stand over", "sto"],
    ["obstaculum", "障碍", "obstacle", "sto"],
    ["concido2", "倒下", "collapse", "cado"],
    ["excido2", "落出", "fall out", "cado"],
    ["occido2", "落下", "set", "cado"],
    ["procido", "向前倒", "fall forward", "cado"],
    ["recido2", "倒回", "fall back", "cado"],
    ["caducus", "易落的", "falling", "cado"],
    ["auditorium", "听讲堂", "lecture hall", "audio"],
    ["revideo", "再看", "see again", "video"],
    ["invisus", "遭恨的", "hated", "video"],
    ["prudentia", "审慎", "prudence", "video"],
    ["exercitus", "军队", "army", "t_mil"],
    ["centurio", "百夫长", "centurion", "t_mil"],
    ["cohors", "大队", "cohort", "t_mil"],
    ["acies", "战线", "battle line", "t_mil"],
    ["proelium", "战斗", "battle", "t_mil"],
    ["impedimenta", "辎重", "baggage", "t_mil"],
    ["lorica", "胸甲", "breastplate", "t_mil"],
    ["telum", "投掷武器", "missile", "t_mil"],
    ["peditatus", "步兵", "infantry", "t_mil"],
    ["auxilia", "辅助部队", "auxiliaries", "t_mil"],
    ["praesidium", "守备", "garrison", "t_mil"],
    ["vallum", "壁垒", "rampart", "t_mil"],
    ["moenia", "城墙", "city walls", "t_mil"],
    ["triumphus", "凯旋", "triumph", "t_mil"],
    ["clades", "惨败", "disaster", "t_mil"],
    ["insidiae", "埋伏", "ambush", "t_mil"],
    ["tuba", "号角", "trumpet", "t_mil"],
    ["classis", "舰队", "fleet", "t_mil"],
    ["socii", "盟友", "allies", "t_mil"],
    ["indutiae", "休战", "truce", "t_mil"],
    ["paries", "墙", "wall", "t_dom"],
    ["atrium", "前厅", "hall", "t_dom"],
    ["lectus", "床", "bed", "t_dom"],
    ["scamnum", "长凳", "stool", "t_dom"],
    ["armarium", "柜子", "cupboard", "t_dom"],
    ["vas", "容器", "vessel", "t_dom"],
    ["patera", "浅盘", "dish", "t_dom"],
    ["olla", "锅", "pot", "t_dom"],
    ["amphora", "双耳瓶", "amphora", "t_dom"],
    ["urna", "瓮", "urn", "t_dom"],
    ["culter", "刀", "knife", "t_dom"],
    ["malleus", "锤", "hammer", "t_dom"],
    ["funis", "绳", "rope", "t_dom"],
    ["saccus", "袋", "sack", "t_dom"],
    ["cista", "篮", "basket", "t_dom"],
    ["lana", "羊毛", "wool", "t_dom"],
    ["tunica", "内衣", "tunic", "t_dom"],
    ["pallium", "外袍", "cloak", "t_dom"],
    ["calceus", "鞋", "shoe", "t_dom"],
    ["margarita", "珍珠", "pearl", "t_dom"],
    ["puteus", "井", "well", "t_dom"],
    ["balneum", "浴室", "bath", "t_dom"],
    ["fumus", "烟", "smoke", "t_dom"],
    ["carbo", "炭", "coal", "t_dom"],
    ["imber", "阵雨", "rain", "t_nat"],
    ["fulmen", "闪电", "lightning", "t_nat"],
    ["pruina", "霜", "frost", "t_nat"],
    ["ros", "露", "dew", "t_nat"],
    ["calor", "热", "heat", "t_nat"],
    ["aer", "空气", "air", "t_nat"],
    ["aether", "苍穹", "upper air", "t_nat"],
    ["crepusculum", "黄昏", "twilight", "t_nat"],
    ["vesper", "傍晚", "evening", "t_nat"],
    ["ver", "春", "spring", "t_nat"],
    ["aestas", "夏", "summer", "t_nat"],
    ["autumnus", "秋", "autumn", "t_nat"],
    ["hiems", "冬", "winter", "t_nat"],
    ["rupes", "悬崖", "cliff", "t_nat"],
    ["desertum", "荒漠", "desert", "t_nat"],
    ["litus", "海岸", "shore", "t_nat"],
    ["harena", "沙", "sand", "t_nat"],
    ["pulvis", "尘土", "dust", "t_nat"],
    ["argilla", "黏土", "clay", "t_nat"],
    ["aes", "铜", "bronze", "t_nat"],
    ["sulpur", "硫磺", "sulphur", "t_nat"],
    ["vitulus", "小牛", "calf", "t_fauna"],
    ["agnus", "羔羊", "lamb", "t_fauna"],
    ["caper", "山羊", "goat", "t_fauna"],
    ["sus", "猪", "swine", "t_fauna"],
    ["asinus", "驴", "donkey", "t_fauna"],
    ["mulus", "骡", "mule", "t_fauna"],
    ["vulpes", "狐狸", "fox", "t_fauna"],
    ["lepus", "野兔", "hare", "t_fauna"],
    ["feles", "猫", "cat", "t_fauna"],
    ["simia", "猴", "monkey", "t_fauna"],
    ["elephantus", "象", "elephant", "t_fauna"],
    ["camelus", "骆驼", "camel", "t_fauna"],
    ["tigris", "虎", "tiger", "t_fauna"],
    ["testudo", "龟", "tortoise", "t_fauna"],
    ["gallus", "公鸡", "rooster", "t_fauna"],
    ["gallina", "母鸡", "hen", "t_fauna"],
    ["anser", "鹅", "goose", "t_fauna"],
    ["anas", "鸭", "duck", "t_fauna"],
    ["columba", "鸽子", "dove", "t_fauna"],
    ["corvus", "乌鸦", "raven", "t_fauna"],
    ["accipiter", "鹞鹰", "hawk", "t_fauna"],
    ["passer", "麻雀", "sparrow", "t_fauna"],
    ["hirundo", "燕子", "swallow", "t_fauna"],
    ["luscinia", "夜莺", "nightingale", "t_fauna"],
    ["cycnus", "天鹅", "swan", "t_fauna"],
    ["pavo", "孔雀", "peacock", "t_fauna"],
    ["musca", "苍蝇", "fly", "t_fauna"],
    ["formica", "蚂蚁", "ant", "t_fauna"],
    ["aranea", "蜘蛛", "spider", "t_fauna"],
    ["papilio", "蝴蝶", "butterfly", "t_fauna"],
    ["vermis", "虫", "worm", "t_fauna"],
    ["delphinus", "海豚", "dolphin", "t_fauna"],
    ["balaena", "鲸", "whale", "t_fauna"],
    ["cancer", "螃蟹", "crab", "t_fauna"],
    ["ostrea", "牡蛎", "oyster", "t_fauna"],
    ["cornu", "角", "horn", "t_fauna"],
    ["ala", "翅膀", "wing", "t_fauna"],
    ["penna", "羽毛", "feather", "t_fauna"],
    ["nidus", "巢", "nest", "t_fauna"],
    ["grex", "畜群", "flock", "t_fauna"],
    ["venator", "猎人", "hunter", "t_fauna"],
    ["quercus", "橡树", "oak", "t_flora"],
    ["pinus", "松树", "pine", "t_flora"],
    ["olea", "橄榄树", "olive tree", "t_flora"],
    ["oliva", "橄榄", "olive", "t_flora"],
    ["vitis", "葡萄藤", "vine", "t_flora"],
    ["uva", "葡萄", "grape", "t_flora"],
    ["ficus", "无花果", "fig", "t_flora"],
    ["malum", "苹果", "apple", "t_flora"],
    ["pirum", "梨", "pear", "t_flora"],
    ["nux", "坚果", "nut", "t_flora"],
    ["viola", "紫罗兰", "violet", "t_flora"],
    ["hedera", "常春藤", "ivy", "t_flora"],
    ["ramus", "树枝", "branch", "t_flora"],
    ["truncus", "树干", "trunk", "t_flora"],
    ["cortex", "树皮", "bark", "t_flora"],
    ["gramen", "草", "grass", "t_flora"],
    ["triticum", "小麦", "wheat", "t_flora"],
    ["hordeum", "大麦", "barley", "t_flora"],
    ["faba", "蚕豆", "bean", "t_flora"],
    ["lens", "扁豆", "lentil", "t_flora"],
    ["brassica", "卷心菜", "cabbage", "t_flora"],
    ["rapum", "萝卜", "turnip", "t_flora"],
    ["cepa", "洋葱", "onion", "t_flora"],
    ["alium", "大蒜", "garlic", "t_flora"],
    ["messis", "收获", "harvest", "t_flora"],
    ["falx", "镰刀", "sickle", "t_flora"],
    ["pomum", "果实", "fruit", "t_flora"],
    ["villa", "农庄", "country house", "t_flora"],
    ["stabulum", "畜棚", "stable", "t_flora"],
    ["horreum", "谷仓", "barn", "t_flora"],
    ["cibus", "食物", "food", "t_cib"],
    ["cena", "晚餐", "dinner", "t_cib"],
    ["prandium", "午餐", "lunch", "t_cib"],
    ["ientaculum", "早餐", "breakfast", "t_cib"],
    ["caseus", "奶酪", "cheese", "t_cib"],
    ["mel", "蜂蜜", "honey", "t_cib"],
    ["oleum", "油", "oil", "t_cib"],
    ["acetum", "醋", "vinegar", "t_cib"],
    ["piper", "胡椒", "pepper", "t_cib"],
    ["mulsum", "蜜酒", "honeyed wine", "t_cib"],
    ["cervisia", "啤酒", "beer", "t_cib"],
    ["pistor", "面包师", "baker", "t_cib"],
    ["farina", "面粉", "flour", "t_cib"],
    ["placenta", "糕饼", "cake", "t_cib"],
    ["puls", "粥", "porridge", "t_cib"],
    ["esurio", "饿", "be hungry", "t_cib"],
    ["sitio", "渴", "be thirsty", "t_cib"],
    ["gusto", "品尝", "taste", "t_cib"],
    ["gustus", "味道", "taste", "t_cib"],
    ["crudus", "生的", "raw", "t_cib"],
    ["victima", "祭牲", "victim", "t_relig"],
    ["omen", "预兆", "omen", "t_relig"],
    ["manes", "亡灵", "spirits of the dead", "t_relig"],
    ["Tartarus", "地狱", "Tartarus", "t_relig"],
    ["Elysium", "极乐世界", "Elysium", "t_relig"],
    ["Olympus", "奥林匹斯", "Olympus", "t_relig"],
    ["Musa", "缪斯", "Muse", "t_relig"],
    ["hymnus", "颂歌", "hymn", "t_relig"],
    ["sacrum", "圣物", "sacred rite", "t_relig"],
    ["profanus", "世俗的", "profane", "t_relig"],
    ["pius", "虔诚的", "pious", "t_relig"],
    ["impius", "不敬的", "impious", "t_relig"],
    ["pietas", "虔敬", "piety", "t_relig"],
    ["superstitio", "迷信", "superstition", "t_relig"],
    ["praetor", "裁判官", "praetor", "t_iur"],
    ["censor", "监察官", "censor", "t_iur"],
    ["comitia", "公民大会", "assembly", "t_iur"],
    ["suffragium", "投票", "vote", "t_iur"],
    ["nobilis", "贵族的", "noble", "t_iur"],
    ["forum", "广场", "forum", "t_iur"],
    ["curia", "元老院会堂", "senate house", "t_iur"],
    ["rostra", "讲坛", "speaker's platform", "t_iur"],
    ["reus", "被告", "defendant", "t_iur"],
    ["exsilium", "流放", "exile", "t_iur"],
    ["vincula", "镣铐", "chains", "t_iur"],
    ["furtum", "盗窃", "theft", "t_iur"],
    ["fraus", "欺诈", "fraud", "t_iur"],
    ["scelus", "罪行", "crime", "t_iur"],
    ["coniuratio", "阴谋", "conspiracy", "t_iur"],
    ["tyrannus", "暴君", "tyrant", "t_iur"],
    ["cliens", "门客", "client", "t_iur"],
    ["vectigal", "税收", "revenue", "t_iur"],
    ["aerarium", "国库", "treasury", "t_iur"],
    ["gubernator", "舵手", "helmsman", "t_mar"],
    ["ancora", "锚", "anchor", "t_mar"],
    ["procella", "风暴", "gale", "t_mar"],
    ["pelagus", "大海", "open sea", "t_mar"],
    ["fretum", "海峡", "strait", "t_mar"],
    ["ora", "海岸", "coast", "t_mar"],
    ["caupona", "酒馆", "inn", "t_mar"],
    ["onus", "负担", "load", "t_mar"],
    ["plaustrum", "大车", "wagon", "t_mar"],
    ["raeda", "马车", "carriage", "t_mar"],
    ["pons", "桥", "bridge", "t_mar"],
    ["semita", "小径", "path", "t_mar"],
    ["miliarium", "里程碑", "milestone", "t_mar"],
    ["supercilium", "眉", "eyebrow", "t_corp"],
    ["gena", "面颊", "cheek", "t_corp"],
    ["labrum", "嘴唇", "lip", "t_corp"],
    ["mentum", "下巴", "chin", "t_corp"],
    ["barba", "胡须", "beard", "t_corp"],
    ["collum", "脖子", "neck", "t_corp"],
    ["umerus", "肩", "shoulder", "t_corp"],
    ["cubitum", "肘", "elbow", "t_corp"],
    ["pollex", "拇指", "thumb", "t_corp"],
    ["unguis", "指甲", "nail", "t_corp"],
    ["pectus", "胸", "chest", "t_corp"],
    ["venter", "腹", "belly", "t_corp"],
    ["dorsum", "背", "back", "t_corp"],
    ["tergum", "背部", "back", "t_corp"],
    ["femur", "大腿", "thigh", "t_corp"],
    ["crus", "小腿", "leg", "t_corp"],
    ["calx", "脚跟", "heel", "t_corp"],
    ["cutis", "皮肤", "skin", "t_corp"],
    ["vena", "血管", "vein", "t_corp"],
    ["cerebrum", "脑", "brain", "t_corp"],
    ["pulmo", "肺", "lung", "t_corp"],
    ["iecur", "肝", "liver", "t_corp"],
    ["stomachus", "胃", "stomach", "t_corp"],
    ["viscera", "内脏", "entrails", "t_corp"],
    ["sudor", "汗", "sweat", "t_corp"],
    ["febris", "发烧", "fever", "t_corp"],
    ["cicatrix", "伤疤", "scar", "t_corp"],
    ["tussis", "咳嗽", "cough", "t_corp"],
    ["pestis", "瘟疫", "plague", "t_corp"],
    ["caecus", "盲的", "blind", "t_corp"],
    ["surdus", "聋的", "deaf", "t_corp"],
    ["mutus", "哑的", "mute", "t_corp"],
    ["claudus", "跛的", "lame", "t_corp"],
    ["lassus", "疲倦的", "weary", "t_corp"],
    ["fessus", "疲惫的", "tired", "t_corp"],
    ["acutus", "尖的", "acute", "t_adj"],
    ["obtusus", "钝的", "blunt", "t_adj"],
    ["asper", "粗糙的", "rough", "t_adj"],
    ["lenis", "温和的", "gentle", "t_adj"],
    ["ferus", "野的", "wild", "t_adj"],
    ["callidus", "狡猾的", "cunning", "t_adj"],
    ["maestus", "忧伤的", "sorrowful", "t_adj"],
    ["sedulus", "勤勉的", "diligent", "t_adj"],
    ["strenuus", "积极的", "vigorous", "t_adj"],
    ["largus", "慷慨的", "generous", "t_adj"],
    ["benignus", "仁慈的", "kind", "t_adj"],
    ["saevus", "凶残的", "savage", "t_adj"],
    ["nitidus", "光亮的", "shining", "t_adj"],
    ["argenteus", "银的", "silvery", "t_adj"],
    ["ligneus", "木的", "wooden", "t_adj"],
    ["lapideus", "石的", "stony", "t_adj"],
    ["vitreus", "玻璃的", "glassy", "t_adj"],
    ["gracilis", "纤细的", "slender", "t_adj"],
    ["pinguis", "肥的", "fat", "t_adj"],
    ["macer", "瘦的", "thin", "t_adj"],
    ["madidus", "湿透的", "wet", "t_adj"],
    ["tepidus", "温的", "lukewarm", "t_adj"],
    ["vastus", "广阔的", "vast", "t_adj"],
    ["amplus", "宽大的", "ample", "t_adj"],
    ["interior", "内部的", "inner", "t_adj"],
    ["exterior", "外部的", "outer", "t_adj"],
    ["citerior", "更近的", "nearer", "t_adj"],
    ["priscus", "古代的", "ancient", "t_adj"],
    ["recens", "新近的", "recent", "t_adj"],
    ["aeternus", "永恒的", "eternal", "t_adj"],
    ["sempiternus", "永远的", "everlasting", "t_adj"],
    ["subitus", "突然的", "sudden", "t_adj"],
    ["repentinus", "突发的", "sudden", "t_adj"],
    ["frequens", "频繁的", "frequent", "t_adj"],
    ["assiduus", "持续的", "constant", "t_adj"],
    ["reliquus", "剩下的", "remaining", "t_adj"],
    ["cunctus", "全部的", "all", "t_adj"],
    ["ineptus", "不合适的", "inept", "t_adj"],
    ["manifestus", "明显的", "obvious", "t_adj"],
    ["inclitus", "著名的", "renowned", "t_adj"],
    ["externus", "外来的", "external", "t_adj"],
    ["beatus", "幸福的", "blessed", "t_adj"],
    ["egenus", "匮乏的", "needy", "t_adj"],
    ["uber", "丰饶的", "fertile", "t_adj"],
    ["sterilis", "不育的", "barren", "t_adj"],
    ["fecundus", "多产的", "fruitful", "t_adj"],
    ["incolumis", "安然无恙的", "unharmed", "t_adj"],
    ["saucius", "受伤的", "wounded", "t_adj"],
    ["immanis", "庞大的", "monstrous", "t_adj"],
    ["exiguus", "微小的", "scanty", "t_adj"],
    ["minutus", "细小的", "tiny", "t_adj"],
    ["tantus", "这么大的", "so great", "t_adj"],
    ["aliquantus", "相当的", "considerable", "t_adj"],
    ["ullus", "任何的", "any", "t_adj"],
    ["nonnullus", "一些", "some", "t_adj"],
    ["neuter", "两者都不", "neither", "t_adj"],
    ["quilibet", "任何", "any you like", "t_adj"],
    ["nuper", "最近", "recently", "t_adv"],
    ["mane", "早晨", "in the morning", "t_adv"],
    ["umquam", "曾经", "ever", "t_adv"],
    ["dudum", "不久前", "a while ago", "t_adv"],
    ["postremo", "最终", "lastly", "t_adv"],
    ["interim", "其间", "meanwhile", "t_adv"],
    ["item", "同样", "likewise", "t_adv"],
    ["usquam", "在任何地方", "anywhere", "t_adv"],
    ["nusquam", "无处", "nowhere", "t_adv"],
    ["undique", "从四面", "from all sides", "t_adv"],
    ["ferme", "差不多", "nearly", "t_adv"],
    ["prorsus", "绝对", "absolutely", "t_adv"],
    ["plane", "清楚地,完全", "plainly", "t_adv"],
    ["aegre", "艰难地", "with difficulty", "t_adv"],
    ["praesertim", "尤其", "especially", "t_adv"],
    ["praecipue", "特别", "chiefly", "t_adv"],
    ["forsitan", "或许", "perhaps", "t_adv"],
    ["sane", "的确", "certainly", "t_adv"],
    ["nempe", "当然", "surely", "t_adv"],
    ["equidem", "我确实", "indeed", "t_adv"],
    ["nequiquam", "白白地", "in vain", "t_adv"],
    ["ultro", "主动", "of one's own accord", "t_adv"],
    ["seorsum", "分开", "separately", "t_adv"],
    ["aliter", "否则", "otherwise", "t_adv"],
    ["aliquando", "有时", "sometimes", "t_adv"],
    ["aliquo", "到某处", "somewhere", "t_adv"],
    ["totiens", "那么多次", "so often", "t_adv"],
    ["quater", "四次", "four times", "t_adv"],
    ["quinquies", "五次", "five times", "t_adv"],
    ["deciens", "十次", "ten times", "t_adv"],
    ["centiens", "百次", "a hundred times", "t_adv"],
    ["milies", "千次", "a thousand times", "t_adv"],
    ["bonitas", "善良", "goodness", "t_abstr"],
    ["crudelitas", "残忍", "cruelty", "t_abstr"],
    ["necessitas", "必要", "necessity", "t_abstr"],
    ["voluptas", "快乐", "pleasure", "t_abstr"],
    ["nobilitas", "高贵", "nobility", "t_abstr"],
    ["antiquitas", "古代", "antiquity", "t_abstr"],
    ["aetas", "年龄,时代", "age", "t_abstr"],
    ["iuventus", "青年", "youth", "t_abstr"],
    ["magnitudo", "大小", "magnitude", "t_abstr"],
    ["fortitudo", "勇气", "courage", "t_abstr"],
    ["consuetudo", "习惯", "custom", "t_abstr"],
    ["pulchritudo", "美", "beauty", "t_abstr"],
    ["turpitudo", "丑恶", "baseness", "t_abstr"],
    ["inimicitia", "敌意", "enmity", "t_abstr"],
    ["iniustitia", "不义", "injustice", "t_abstr"],
    ["diligentia", "勤勉", "diligence", "t_abstr"],
    ["neglegentia", "疏忽", "negligence", "t_abstr"],
    ["audacia", "大胆", "boldness", "t_abstr"],
    ["avaritia", "贪婪", "greed", "t_abstr"],
    ["absentia", "缺席", "absence", "t_abstr"],
    ["praesentia", "在场", "presence", "t_abstr"],
    ["violentia", "暴力", "violence", "t_abstr"],
    ["innocentia", "清白", "innocence", "t_abstr"],
    ["opinio", "看法", "opinion", "t_abstr"],
    ["legatio", "使团", "embassy", "t_abstr"],
    ["cupido", "渴望", "longing", "t_abstr"],
    ["libido", "欲望", "lust", "t_abstr"],
    ["metus", "恐惧", "fear", "t_abstr"],
    ["pavor", "惊恐", "terror", "t_abstr"],
    ["maeror", "悲痛", "sorrow", "t_abstr"],
    ["angor", "焦虑", "anguish", "t_abstr"],
    ["sollicitudo", "担忧", "anxiety", "t_abstr"],
    ["laetitia", "欢乐", "joy", "t_abstr"],
    ["hilaritas", "欢快", "cheerfulness", "t_abstr"],
    ["gemitus", "呻吟", "groan", "t_abstr"],
    ["diffidentia", "不信任", "distrust", "t_abstr"],
    ["verecundia", "羞耻心", "modesty", "t_abstr"],
    ["maleficium", "恶行", "evil deed", "t_abstr"],
    ["meritum", "功劳", "merit", "t_abstr"],
    ["vitium", "缺点", "vice", "t_abstr"],
    ["delictum", "过失", "offence", "t_abstr"],
    ["ultio", "报复", "revenge", "t_abstr"],
    ["vindicta", "惩罚", "vengeance", "t_abstr"],
    ["lis", "诉讼", "lawsuit", "t_abstr"],
    ["controversia", "争论", "controversy", "t_abstr"],
    ["exemplum", "例子", "example", "t_abstr"],
    ["argumentum", "论据", "argument", "t_abstr"],
    ["indicium", "迹象", "sign", "t_abstr"],
    ["vestigium", "足迹", "trace", "t_abstr"],
    ["exordium", "开端", "beginning", "t_abstr"],
    ["ritus", "仪式", "rite", "t_abstr"],
    ["amphitheatrum", "圆形剧场", "amphitheatre", "t_urb"],
    ["thermae", "公共浴场", "public baths", "t_urb"],
    ["cloaca", "下水道", "sewer", "t_urb"],
    ["taberna", "商铺", "shop", "t_urb"],
    ["macellum", "市场", "food market", "t_urb"],
    ["palatium", "宫殿", "palace", "t_urb"],
    ["arx", "城堡", "citadel", "t_urb"],
    ["oppidum", "城镇", "town", "t_urb"],
    ["pagus", "乡区", "district", "t_urb"],
    ["platea", "大街", "broad street", "t_urb"],
    ["angiportus", "小巷", "alley", "t_urb"],
    ["fornix", "拱顶", "vault", "t_urb"],
    ["architectus", "建筑师", "architect", "t_urb"],
    ["later", "砖", "brick", "t_urb"],
    ["trabs", "梁", "beam", "t_urb"],
    ["tignum", "木料", "timber", "t_urb"],
    ["fundamentum", "地基", "foundation", "t_urb"],
    ["poema", "诗", "poem", "t_ars"],
    ["tabula", "写字板,画", "tablet", "t_ars"],
    ["stilus", "铁笔", "stylus", "t_ars"],
    ["cera", "蜡", "wax", "t_ars"],
    ["papyrus", "纸草", "papyrus", "t_ars"],
    ["codex", "抄本", "book", "t_ars"],
    ["schola", "学校", "school", "t_ars"],
    ["grammaticus", "语法学家", "grammarian", "t_ars"],
    ["rhetor", "修辞教师", "rhetorician", "t_ars"],
    ["philosophus", "哲学家", "philosopher", "t_ars"],
    ["philosophia", "哲学", "philosophy", "t_ars"],
    ["litterae", "文学,信", "literature", "t_ars"],
    ["syllaba", "音节", "syllable", "t_ars"],
    ["cithara", "竖琴", "cithara", "t_ars"],
    ["chorus", "合唱", "chorus", "t_ars"],
    ["histrio", "演员", "actor", "t_ars"],
    ["persona", "面具,人物", "mask", "t_ars"],
    ["tragoedia", "悲剧", "tragedy", "t_ars"],
    ["comoedia", "喜剧", "comedy", "t_ars"],
    ["gladiator", "角斗士", "gladiator", "t_ars"],
    ["auriga", "驾车手", "charioteer", "t_ars"],
    ["athleta", "运动员", "athlete", "t_ars"],
    ["palaestra", "角力场", "wrestling school", "t_ars"],
    ["stadium", "跑道", "stadium", "t_ars"],
    ["palma", "棕榈,胜利", "palm", "t_ars"],
    ["mathematicus", "数学家", "mathematician", "t_ars"],
    ["astrologus", "占星家", "astrologer", "t_ars"],
    ["geometria", "几何", "geometry", "t_ars"]
  );
})();
