/* =====================================================
   FUGA MYTHICA — CURSUS Italian 🇮🇹 · batch 7 — topical everyday vocabulary + derivations
   ===================================================== */
(function () {
  const p = VOCAB.it;
  Object.assign(p.roots, { topic: ["主题词汇", "领域词汇,无词根", "everyday topics"] });
  p.words.push(
    ["la merenda", "点心", "snack", "topic"],
    ["il prosciutto", "火腿", "ham", "topic"],
    ["l'agnello", "羔羊肉", "lamb", "topic"],
    ["il tonno", "金枪鱼", "tuna", "topic"],
    ["l'olio", "油", "oil", "topic"],
    ["il pepe", "胡椒", "pepper", "topic"],
    ["la farina", "面粉", "flour", "topic"],
    ["il pomodoro", "番茄", "tomato", "topic"],
    ["la cipolla", "洋葱", "onion", "topic"],
    ["l'aglio", "大蒜", "garlic", "topic"],
    ["la carota", "胡萝卜", "carrot", "topic"],
    ["il fungo", "蘑菇", "mushroom", "topic"],
    ["la pera", "梨", "pear", "topic"],
    ["la pesca", "桃", "peach", "topic"],
    ["l'uva", "葡萄", "grapes", "topic"],
    ["la fragola", "草莓", "strawberry", "topic"],
    ["la ciliegia", "樱桃", "cherry", "topic"],
    ["l'anguria", "西瓜", "watermelon", "topic"],
    ["la banana", "香蕉", "banana", "topic"],
    ["la torta", "蛋糕", "cake", "topic"],
    ["il biscotto", "饼干", "biscuit", "topic"],
    ["l'acqua minerale", "矿泉水", "mineral water", "topic"],
    ["il bicchiere", "玻璃杯", "glass", "topic"],
    ["la forchetta", "叉子", "fork", "topic"],
    ["il coltello", "刀", "knife", "topic"],
    ["il cucchiaio", "勺子", "spoon", "topic"],
    ["il tovagliolo", "餐巾", "napkin", "topic"],
    ["la mancia", "小费", "tip", "topic"],
    ["il cameriere", "服务员", "waiter", "topic"],
    ["il menù", "菜单", "menu", "topic"],
    ["la prenotazione", "预订", "reservation", "topic"],
    ["il mento", "下巴", "chin", "topic"],
    ["il gomito", "肘", "elbow", "topic"],
    ["l'unghia", "指甲", "nail", "topic"],
    ["il petto", "胸", "chest", "topic"],
    ["la caviglia", "脚踝", "ankle", "topic"],
    ["il cervello", "大脑", "brain", "topic"],
    ["il polmone", "肺", "lung", "topic"],
    ["lo stomaco", "胃", "stomach", "topic"],
    ["il fegato", "肝", "liver", "topic"],
    ["il rene", "肾", "kidney", "topic"],
    ["il raffreddore", "感冒", "cold", "topic"],
    ["la febbre", "发烧", "fever", "topic"],
    ["la tosse", "咳嗽", "cough", "topic"],
    ["il mal di testa", "头痛", "headache", "topic"],
    ["il pronto soccorso", "急诊", "emergency room", "topic"],
    ["il palazzo", "大楼", "building", "topic"],
    ["la scala", "楼梯", "stairs", "topic"],
    ["l'ascensore", "电梯", "lift", "topic"],
    ["il soggiorno", "客厅", "living room", "topic"],
    ["la camera da letto", "卧室", "bedroom", "topic"],
    ["il garage", "车库", "garage", "topic"],
    ["la cantina", "地窖", "cellar", "topic"],
    ["il cuscino", "枕头", "pillow", "topic"],
    ["la coperta", "毯子", "blanket", "topic"],
    ["la poltrona", "扶手椅", "armchair", "topic"],
    ["la lampada", "灯", "lamp", "topic"],
    ["il tappeto", "地毯", "carpet", "topic"],
    ["il forno", "烤箱", "oven", "topic"],
    ["la lavastoviglie", "洗碗机", "dishwasher", "topic"],
    ["l'aspirapolvere", "吸尘器", "vacuum cleaner", "topic"],
    ["la spazzatura", "垃圾", "rubbish", "topic"],
    ["l'affitto", "房租", "rent", "topic"],
    ["la maglietta", "T恤", "T-shirt", "topic"],
    ["la camicia", "衬衫", "shirt", "topic"],
    ["i pantaloni", "裤子", "trousers", "topic"],
    ["la gonna", "裙子", "skirt", "topic"],
    ["la giacca", "夹克", "jacket", "topic"],
    ["il cappotto", "大衣", "coat", "topic"],
    ["il maglione", "毛衣", "sweater", "topic"],
    ["le scarpe", "鞋", "shoes", "topic"],
    ["gli stivali", "靴子", "boots", "topic"],
    ["i calzini", "袜子", "socks", "topic"],
    ["il cappello", "帽子", "hat", "topic"],
    ["la sciarpa", "围巾", "scarf", "topic"],
    ["i guanti", "手套", "gloves", "topic"],
    ["la cintura", "腰带", "belt", "topic"],
    ["la borsa", "包", "bag", "topic"],
    ["il supermercato", "超市", "supermarket", "topic"],
    ["la panetteria", "面包店", "bakery", "topic"],
    ["la macelleria", "肉店", "butcher's", "topic"],
    ["l'edicola", "报刊亭", "newsstand", "topic"],
    ["il centro commerciale", "购物中心", "shopping centre", "topic"],
    ["lo sconto", "折扣", "discount", "topic"],
    ["i saldi", "打折季", "sales", "topic"],
    ["la cassa", "收银台", "till", "topic"],
    ["lo scontrino", "收据", "receipt", "topic"],
    ["la carta di credito", "信用卡", "credit card", "topic"],
    ["i contanti", "现金", "cash", "topic"],
    ["il binario", "站台", "platform", "topic"],
    ["il biglietto", "票", "ticket", "topic"],
    ["la metropolitana", "地铁", "underground", "topic"],
    ["il tram", "有轨电车", "tram", "topic"],
    ["il taxi", "出租车", "taxi", "topic"],
    ["il traghetto", "渡轮", "ferry", "topic"],
    ["la patente", "驾照", "driving licence", "topic"],
    ["la benzina", "汽油", "petrol", "topic"],
    ["il parcheggio", "停车场", "car park", "topic"],
    ["l'autostrada", "高速公路", "motorway", "topic"],
    ["il marciapiede", "人行道", "pavement", "topic"],
    ["la valigia", "行李箱", "suitcase", "topic"],
    ["lo zaino", "背包", "backpack", "topic"],
    ["l'albergo", "旅馆", "hotel", "topic"],
    ["il lago", "湖", "lake", "topic"],
    ["l'asilo", "幼儿园", "nursery", "topic"],
    ["il liceo", "高中", "high school", "topic"],
    ["la classe", "班级", "class", "topic"],
    ["l'aula", "教室", "classroom", "topic"],
    ["la lavagna", "黑板", "blackboard", "topic"],
    ["il quaderno", "练习本", "exercise book", "topic"],
    ["la penna", "钢笔", "pen", "topic"],
    ["la matita", "铅笔", "pencil", "topic"],
    ["la gomma", "橡皮", "eraser", "topic"],
    ["i compiti", "作业", "homework", "topic"],
    ["l'esame", "考试", "exam", "topic"],
    ["la matematica", "数学", "maths", "topic"],
    ["la fisica", "物理", "physics", "topic"],
    ["la chimica", "化学", "chemistry", "topic"],
    ["il computer", "电脑", "computer", "topic"],
    ["la tastiera", "键盘", "keyboard", "topic"],
    ["la password", "密码", "password", "topic"],
    ["la rete", "网络", "network", "topic"],
    ["il sito", "网站", "website", "topic"],
    ["la telefonata", "电话", "phone call", "topic"],
    ["la nebbia", "雾", "fog", "topic"],
    ["il caldo", "热", "heat", "topic"],
    ["il freddo", "冷", "cold", "topic"],
    ["l'umidità", "湿度", "humidity", "topic"],
    ["il gatto", "猫", "cat", "topic"],
    ["la mucca", "奶牛", "cow", "topic"],
    ["la pecora", "羊", "sheep", "topic"],
    ["la capra", "山羊", "goat", "topic"],
    ["la gallina", "母鸡", "hen", "topic"],
    ["il topo", "老鼠", "mouse", "topic"],
    ["il coniglio", "兔子", "rabbit", "topic"],
    ["il lupo", "狼", "wolf", "topic"],
    ["l'orso", "熊", "bear", "topic"],
    ["la volpe", "狐狸", "fox", "topic"],
    ["il cervo", "鹿", "deer", "topic"],
    ["il leone", "狮子", "lion", "topic"],
    ["la tigre", "老虎", "tiger", "topic"],
    ["l'elefante", "大象", "elephant", "topic"],
    ["la scimmia", "猴子", "monkey", "topic"],
    ["il serpente", "蛇", "snake", "topic"],
    ["la farfalla", "蝴蝶", "butterfly", "topic"],
    ["l'ape", "蜜蜂", "bee", "topic"],
    ["la mosca", "苍蝇", "fly", "topic"],
    ["la zanzara", "蚊子", "mosquito", "topic"],
    ["il ragno", "蜘蛛", "spider", "topic"],
    ["la foglia", "叶子", "leaf", "topic"],
    ["l'erba", "草", "grass", "topic"],
    ["il calcio", "足球", "football", "topic"],
    ["la pallacanestro", "篮球", "basketball", "topic"],
    ["la pallavolo", "排球", "volleyball", "topic"],
    ["il tennis", "网球", "tennis", "topic"],
    ["il ciclismo", "自行车运动", "cycling", "topic"],
    ["la palestra", "健身房", "gym", "topic"],
    ["l'allenatore", "教练", "coach", "topic"],
    ["il tifoso", "球迷", "fan", "topic"],
    ["la sconfitta", "失败", "defeat", "topic"],
    ["il pareggio", "平局", "draw", "topic"],
    ["il gol", "进球", "goal", "topic"],
    ["lo stadio", "体育场", "stadium", "topic"],
    ["la medaglia", "奖牌", "medal", "topic"],
    ["il campionato", "锦标赛", "championship", "topic"],
    ["la musica", "音乐", "music", "topic"],
    ["il film", "电影", "film", "topic"],
    ["il cinema", "电影院", "cinema", "topic"],
    ["il regista", "导演", "director", "topic"],
    ["il teatro", "剧院", "theatre", "topic"],
    ["il museo", "博物馆", "museum", "topic"],
    ["il romanzo", "小说", "novel", "topic"],
    ["la rivista", "杂志", "magazine", "topic"],
    ["il programma", "节目", "programme", "topic"],
    ["il compleanno", "生日", "birthday", "topic"],
    ["il Natale", "圣诞节", "Christmas", "topic"],
    ["la Pasqua", "复活节", "Easter", "topic"],
    ["il Capodanno", "新年", "New Year", "topic"],
    ["le ferie", "假期", "holidays", "topic"],
    ["l'annuale", "年度的", "yearly", "ann"],
    ["l'annunciatore", "播音员", "announcer", "nunc"],
    ["la dormita", "一觉", "sleep", "dorm"],
    ["il dormiglione", "贪睡者", "sleepyhead", "dorm"],
    ["la manetta", "手铐", "handcuff", "man"],
    ["la manopola", "旋钮", "knob", "man"],
    ["la pedata", "踢", "kick", "ped"],
    ["il cordone", "绳索", "cord", "cord"],
    ["la corporatura", "体格", "build", "corp"],
    ["il corpetto", "紧身胸衣", "bodice", "corp"],
    ["il sotterraneo", "地下室", "basement", "terr"],
    ["l'amabilità", "亲切", "kindness", "am"],
    ["la capienza", "容量", "capacity", "cap"],
    ["il conduttore", "主持人", "presenter", "duc"],
    ["la conduttura", "管道", "pipeline", "duc"],
    ["lo scrivano", "书记", "scribe", "scrib"],
    ["la dicitura", "措辞", "wording", "dic"],
    ["il ponente", "西方", "west", "pon"],
    ["la posa", "姿势", "pose", "pon"],
    ["la missiva", "信函", "missive", "mitt"],
    ["la corsia", "车道", "lane", "curr"],
    ["la cessione", "转让", "transfer", "ced"],
    ["il rottame", "残骸", "scrap", "rupt"],
    ["la spinta", "推动", "push", "core"],
    ["la pressa", "压力机", "press", "press"],
    ["il pressappoco", "大约", "roughly", "press"],
    ["l'attentato", "袭击", "attack", "tend"],
    ["il movente", "动机", "motive", "mov"],
    ["la mobilia", "家具", "furniture", "mov"],
    ["la fluidità", "流畅", "fluidity", "flu"],
    ["la regia", "导演", "direction", "reg"],
    ["nascente", "新生的", "rising", "nasc"],
    ["la genitrice", "母亲", "mother", "gen"],
    ["lo specchietto", "小镜子", "small mirror", "spec"],
    ["la specialità", "特色菜", "speciality", "spec"],
    ["l'incidente", "事故", "accident", "cid"],
    ["il caso", "情况", "case", "cid"],
    ["il richiamo", "召唤", "call", "clam"],
    ["il reclamo", "投诉", "complaint", "clam"],
    ["l'inclinazione", "倾向", "inclination", "clin"],
    ["il docente", "教师", "lecturer", "doc"],
    ["la docenza", "教学", "teaching", "doc"],
    ["la donazione", "捐赠", "donation", "don"],
    ["l'abito", "衣服", "dress", "hab"],
    ["l'ammonimento", "警告", "warning", "mon"],
    ["la piega", "褶", "fold", "plic"],
    ["l'approvazione", "批准", "approval", "prob"],
    ["il respiro", "呼吸", "breath", "spir"],
    ["il tentativo", "尝试", "attempt", "core"],
    ["la tentazione", "诱惑", "temptation", "core"],
    ["il turbine", "旋风", "whirlwind", "core"],
    ["l'invasione", "入侵", "invasion", "core"],
    ["l'evasione", "逃避", "evasion", "core"]
  );
})();
