/* =====================================================
   FUGA MYTHICA — CURSUS Spanish 🇪🇸 · batch 10 — topical vocabulary 2: action verbs, character & texture adjectives, materials, tools, car, kitchen, containers, shapes, measures
   ===================================================== */
(function () {
  const p = VOCAB.es;
  Object.assign(p.roots, {});
  p.words.push(
    ["picar", "切碎", "cut into pieces", "topic"],
    ["cortar en rodajas", "切片", "cut into slices", "topic"],
    ["pelar", "削皮", "remove skin", "topic"],
    ["rallar", "磨碎", "shred", "topic"],
    ["amasar", "揉面", "work dough", "topic"],
    ["hervir", "煮沸", "cook in water", "topic"],
    ["cocer a fuego lento", "炖", "cook gently", "topic"],
    ["freír", "油炸", "cook in oil", "topic"],
    ["asar", "烤", "cook in oven", "topic"],
    ["asar a la parrilla", "烧烤", "cook on grill", "topic"],
    ["hornear", "烘焙", "cook in oven", "topic"],
    ["cocer al vapor", "蒸", "cook with steam", "topic"],
    ["marinar", "腌", "soak in sauce", "topic"],
    ["sazonar", "调味", "add flavour", "topic"],
    ["derramar", "洒出", "let fall", "topic"],
    ["derretir", "融化", "turn to liquid", "topic"],
    ["masticar", "咀嚼", "grind with teeth", "topic"],
    ["tragar", "吞咽", "take down throat", "topic"],
    ["morder", "咬", "cut with teeth", "topic"],
    ["lamer", "舔", "touch with tongue", "topic"],
    ["olfatear", "嗅", "smell", "topic"],
    ["estornudar", "打喷嚏", "expel air", "topic"],
    ["bostezar", "打哈欠", "open mouth tired", "topic"],
    ["parpadear", "眨眼", "shut eyes briefly", "topic"],
    ["guiñar", "使眼色", "close one eye", "topic"],
    ["encogerse de hombros", "耸肩", "raise shoulders", "topic"],
    ["saludar con la mano", "挥手", "move hand", "topic"],
    ["silbar", "吹口哨", "make sound with lips", "topic"],
    ["tararear", "哼唱", "sing softly", "topic"],
    ["susurrar", "耳语", "speak softly", "topic"],
    ["murmurar", "嘟囔", "speak unclearly", "topic"],
    ["chillar", "尖叫", "cry loudly", "topic"],
    ["sollozar", "抽泣", "cry with gasps", "topic"],
    ["reírse tontamente", "傻笑", "laugh lightly", "topic"],
    ["sonreír ampliamente", "咧嘴笑", "smile widely", "topic"],
    ["fruncir el ceño", "皱眉", "show displeasure", "topic"],
    ["mirar fijamente", "凝视", "look steadily", "topic"],
    ["echar un vistazo", "瞥一眼", "look briefly", "topic"],
    ["gatear", "爬行", "move on hands and knees", "topic"],
    ["deslizarse", "蹑手蹑脚", "move quietly", "topic"],
    ["tropezar", "绊倒", "trip", "topic"],
    ["resbalar", "滑倒", "lose footing", "topic"],
    ["cojear", "跛行", "walk unevenly", "topic"],
    ["vagar", "漫步", "walk aimlessly", "topic"],
    ["marchar", "行军", "walk in step", "topic"],
    ["apresurarse", "冲", "hurry", "topic"],
    ["esprintar", "冲刺", "run at top speed", "topic"],
    ["brincar", "单脚跳", "small jump", "topic"],
    ["bucear", "跳水", "jump into water", "topic"],
    ["flotar", "漂浮", "stay on surface", "topic"],
    ["hundirse", "下沉", "go under", "topic"],
    ["ahogarse", "溺水", "die in water", "topic"],
    ["remar", "划船", "use oars", "topic"],
    ["frenar", "刹车", "slow down", "topic"],
    ["adelantar", "超车", "pass a vehicle", "topic"],
    ["aparcar", "停车", "leave a car", "topic"],
    ["dar marcha atrás", "倒车", "go backwards", "topic"],
    ["patinar", "打滑", "slide", "topic"],
    ["chocar", "撞车", "collide", "topic"],
    ["remolcar", "拖车", "pull a vehicle", "topic"],
    ["hacer autostop", "搭便车", "get free lifts", "topic"],
    ["desplazarse al trabajo", "通勤", "travel to work", "topic"],
    ["despegar", "起飞", "leave the ground", "topic"],
    ["facturar", "办理登机", "register", "topic"],
    ["desempacar", "打开行李", "take out", "topic"],
    ["coser", "缝", "join with thread", "topic"],
    ["planchar", "熨烫", "smooth clothes", "topic"],
    ["colgar", "挂", "suspend", "topic"],
    ["fregar", "刷洗", "clean hard", "topic"],
    ["barrer", "扫", "clean with broom", "topic"],
    ["fregar el suelo", "拖地", "clean floor", "topic"],
    ["quitar el polvo", "除尘", "remove dust", "topic"],
    ["ordenar", "整理", "put in order", "topic"],
    ["pulir", "抛光", "make shiny", "topic"],
    ["enjuagar", "冲洗", "wash with water", "topic"],
    ["remojar", "浸泡", "leave in liquid", "topic"],
    ["escurrir", "沥干", "let liquid out", "topic"],
    ["exprimir", "挤压", "press hard", "topic"],
    ["desenvolver", "拆开", "uncover", "topic"],
    ["atar", "系", "fasten with string", "topic"],
    ["desatar", "解开", "unfasten", "topic"],
    ["abrochar", "扣紧", "fix firmly", "topic"],
    ["cerrar la cremallera", "拉拉链", "close with zip", "topic"],
    ["abotonar", "扣扣子", "close with buttons", "topic"],
    ["martillar", "锤打", "hit with hammer", "topic"],
    ["taladrar", "钻", "make hole", "topic"],
    ["atornillar", "拧螺丝", "fix with screw", "topic"],
    ["serrar", "锯", "cut with saw", "topic"],
    ["pegar", "粘", "stick", "topic"],
    ["pintar", "刷漆", "colour", "topic"],
    ["lijar", "打磨", "smooth", "topic"],
    ["plantar", "种植", "put in soil", "topic"],
    ["regar", "浇水", "give water", "topic"],
    ["podar", "修剪", "cut branches", "topic"],
    ["cortar el césped", "割草", "cut grass", "topic"],
    ["cosechar", "收获", "gather crops", "topic"],
    ["sembrar", "播种", "plant seeds", "topic"],
    ["ordeñar", "挤奶", "take milk", "topic"],
    ["alimentar", "喂", "give food", "topic"],
    ["criar", "饲养", "raise animals", "topic"],
    ["atrapar", "抓住", "seize", "topic"],
    ["agarrar", "抓", "take suddenly", "topic"],
    ["lanzar", "扔", "throw lightly", "topic"],
    ["arrojar", "猛扔", "throw hard", "topic"],
    ["patear", "踢", "hit with foot", "topic"],
    ["dar un puñetazo", "用拳打", "hit with fist", "topic"],
    ["abofetear", "打耳光", "hit with open hand", "topic"],
    ["acariciar", "抚摸", "touch gently", "topic"],
    ["hacer cosquillas", "挠痒", "touch to cause laughter", "topic"],
    ["rascar", "抓挠", "rub with nails", "topic"],
    ["pellizcar", "捏", "squeeze skin", "topic"],
    ["sacudir", "摇晃", "move quickly", "topic"],
    ["temblar", "颤抖", "shake", "topic"],
    ["tiritar", "发抖", "shake with cold", "topic"],
    ["sudar", "出汗", "give off sweat", "topic"],
    ["desmayarse", "晕倒", "lose consciousness", "topic"],
    ["recuperarse", "康复", "get better", "topic"],
    ["magullar", "淤青", "mark skin", "topic"],
    ["toser", "咳嗽", "expel air", "topic"],
    ["vomitar", "呕吐", "throw up", "topic"],
    ["recetar", "开处方", "order medicine", "topic"],
    ["examinar", "检查", "look at carefully", "topic"],
    ["negociar", "谈判", "discuss terms", "topic"],
    ["regatear", "讨价还价", "argue about price", "topic"],
    ["despedir", "解雇", "dismiss", "topic"],
    ["jubilarse", "退休", "stop working", "topic"],
    ["ascender", "晋升", "raise in rank", "topic"],
    ["prestar", "借出", "give temporarily", "topic"],
    ["pedir prestado", "借入", "take temporarily", "topic"],
    ["reembolsar", "退款", "give money back", "topic"],
    ["permitirse", "负担得起", "have enough money", "topic"],
    ["desperdiciar", "浪费", "use badly", "topic"],
    ["acusar", "指控", "blame", "topic"],
    ["apelar", "上诉", "ask for review", "topic"],
    ["testificar", "作证", "give evidence", "topic"],
    ["sobornar", "贿赂", "pay illegally", "topic"],
    ["falsificar", "伪造", "make fake", "topic"],
    ["contrabandear", "走私", "move illegally", "topic"],
    ["amenazar", "威胁", "warn of harm", "topic"],
    ["chantajear", "敲诈", "threaten for money", "topic"],
    ["protestar", "抗议", "object publicly", "topic"],
    ["hacer campaña", "竞选", "work for election", "topic"],
    ["abolir", "废除", "end officially", "topic"],
    ["hacer cumplir", "执行", "make people obey", "topic"],
    ["iniciar sesión", "登录", "enter account", "topic"],
    ["cerrar sesión", "登出", "leave account", "topic"],
    ["hacer clic", "点击", "press button", "topic"],
    ["desplazarse", "滚动", "move screen", "topic"],
    ["teclear", "打字", "write with keys", "topic"],
    ["borrar", "删除", "remove", "topic"],
    ["imprimir", "打印", "make paper copy", "topic"],
    ["escanear", "扫描", "copy digitally", "topic"],
    ["instalar", "安装", "set up", "topic"],
    ["actualizar", "更新", "make current", "topic"],
    ["reiniciar", "重启", "start again", "topic"],
    ["bloquearse", "崩溃", "stop working", "topic"],
    ["hackear", "黑入", "break into", "topic"],
    ["cifrar", "加密", "code", "topic"],
    ["suscribirse", "订阅", "sign up", "topic"],
    ["dar me gusta", "点赞", "approve online", "topic"],
    ["comentar", "评论", "write remarks", "topic"],
    ["editar", "编辑", "change text", "topic"],
    ["interpretar", "口译", "explain meaning", "topic"],
    ["repasar", "复习", "study again", "topic"],
    ["hacer trampa", "作弊", "act dishonestly", "topic"],
    ["matricularse", "注册入学", "register", "topic"],
    ["asistir a", "出席", "go to", "topic"],
    ["saltarse", "逃课", "not attend", "topic"],
    ["recompensar", "奖励", "give prize", "topic"],
    ["elogiar", "表扬", "say good things", "topic"],
    ["regañar", "责骂", "tell off", "topic"],
    ["cuidar niños", "照看孩子", "look after children", "topic"],
    ["comprometerse", "订婚", "promise to marry", "topic"],
    ["coquetear", "调情", "show attraction", "topic"],
    ["salir con", "约会", "go out with", "topic"],
    ["chismear", "八卦", "talk about others", "topic"],
    ["burlarse", "取笑", "make fun gently", "topic"],
    ["acosar", "欺凌", "hurt weaker person", "topic"],
    ["disculparse", "道歉", "say sorry", "topic"],
    ["traicionar", "背叛", "be disloyal", "topic"],
    ["llorar la pérdida", "哀悼", "feel sorrow", "topic"],
    ["consolar", "安慰", "make feel better", "topic"],
    ["objetar", "反对", "disagree", "topic"],
    ["quejarse", "抱怨", "express annoyance", "topic"],
    ["fingir", "假装", "act falsely", "topic"],
    ["preguntarse", "想知道", "ask oneself", "topic"],
    ["darse cuenta", "意识到", "become aware", "topic"],
    ["estimar", "估计", "guess amount", "topic"],
    ["analizar", "分析", "examine in detail", "topic"],
    ["clasificar", "分类", "put in groups", "topic"],
    ["distinguir", "区分", "tell apart", "topic"],
    ["ilustrar", "说明", "show by example", "topic"],
    ["terco", "固执的", "refusing to change", "topic"],
    ["extrovertido", "外向的", "sociable", "topic"],
    ["hablador", "健谈的", "talking a lot", "topic"],
    ["gruñón", "脾气坏的", "bad-tempered", "topic"],
    ["malhumorado", "喜怒无常的", "changing mood", "topic"],
    ["quisquilloso", "挑剔的", "hard to please", "topic"],
    ["perezoso", "懒惰的", "not wanting to work", "topic"],
    ["trabajador", "勤奋的", "working hard", "topic"],
    ["fiable", "可靠的", "dependable", "topic"],
    ["honesto", "诚实的", "truthful", "topic"],
    ["deshonesto", "不诚实的", "not truthful", "topic"],
    ["leal", "忠诚的", "faithful", "topic"],
    ["tacaño", "吝啬的", "not generous", "topic"],
    ["egoísta", "自私的", "thinking of self", "topic"],
    ["educado", "有礼貌的", "courteous", "topic"],
    ["grosero", "粗鲁的", "not polite", "topic"],
    ["arrogante", "傲慢的", "too proud", "topic"],
    ["cauteloso", "谨慎的", "careful", "topic"],
    ["cobarde", "懦弱的", "afraid", "topic"],
    ["astuto", "狡猾的", "clever and deceitful", "topic"],
    ["ingenioso", "机智的", "clever and funny", "topic"],
    ["torpe", "笨拙的", "awkward", "topic"],
    ["paciente", "有耐心的", "able to wait", "topic"],
    ["impaciente", "不耐烦的", "unable to wait", "topic"],
    ["creativo", "有创造力的", "imaginative", "topic"],
    ["despistado", "心不在焉的", "forgetful", "topic"],
    ["ordenado", "整洁的", "neat", "topic"],
    ["liso", "光滑的", "even surface", "topic"],
    ["áspero", "粗糙的", "uneven", "topic"],
    ["afilado", "锋利的", "able to cut", "topic"],
    ["desafilado", "钝的", "not sharp", "topic"],
    ["pegajoso", "黏的", "adhering", "topic"],
    ["resbaladizo", "滑的", "hard to hold", "topic"],
    ["hueco", "空心的", "empty inside", "topic"],
    ["transparente", "透明的", "see-through", "topic"],
    ["opaco", "不透明的", "not see-through", "topic"],
    ["brillante", "闪亮的", "reflecting light", "topic"],
    ["apagado", "暗淡的", "not bright", "topic"],
    ["húmedo", "潮湿的", "slightly wet", "topic"],
    ["empapado", "湿透的", "very wet", "topic"],
    ["crujiente", "脆的", "firm and dry", "topic"],
    ["rancio", "不新鲜的", "old", "topic"],
    ["podrido", "腐烂的", "decayed", "topic"],
    ["picante", "辣的", "hot-tasting", "topic"],
    ["soso", "淡而无味的", "without flavour", "topic"],
    ["agrio", "酸的", "acid taste", "topic"],
    ["grasiento", "油腻的", "oily", "topic"],
    ["jugoso", "多汁的", "full of juice", "topic"],
    ["la madera", "木材", "wood", "topic"],
    ["el acero", "钢", "steel", "topic"],
    ["el hierro", "铁", "iron", "topic"],
    ["el cobre", "铜", "copper", "topic"],
    ["el latón", "黄铜", "brass", "topic"],
    ["el aluminio", "铝", "aluminium", "topic"],
    ["el estaño", "锡", "tin", "topic"],
    ["el caucho", "橡胶", "rubber", "topic"],
    ["el cuero", "皮革", "leather", "topic"],
    ["la lana", "羊毛", "wool", "topic"],
    ["el algodón", "棉", "cotton", "topic"],
    ["la seda", "丝绸", "silk", "topic"],
    ["el terciopelo", "天鹅绒", "velvet", "topic"],
    ["el hormigón", "混凝土", "concrete", "topic"],
    ["el cemento", "水泥", "cement", "topic"],
    ["el ladrillo", "砖", "brick", "topic"],
    ["el mármol", "大理石", "marble", "topic"],
    ["la arcilla", "黏土", "clay", "topic"],
    ["el vidrio", "玻璃", "glass", "topic"],
    ["la espuma", "泡沫", "foam", "topic"],
    ["el alambre", "铁丝", "wire", "topic"],
    ["la cuerda", "绳子", "rope", "topic"],
    ["el cordel", "细绳", "string", "topic"],
    ["la cadena", "链条", "chain", "topic"],
    ["el gancho", "钩子", "hook", "topic"],
    ["el tornillo", "螺丝", "screw", "topic"],
    ["el perno", "螺栓", "bolt", "topic"],
    ["el martillo", "锤子", "hammer", "topic"],
    ["el destornillador", "螺丝刀", "screwdriver", "topic"],
    ["la llave inglesa", "扳手", "wrench", "topic"],
    ["los alicates", "钳子", "pliers", "topic"],
    ["la sierra", "锯", "saw", "topic"],
    ["el taladro", "钻机", "drill", "topic"],
    ["la escalera de mano", "梯子", "ladder", "topic"],
    ["el cubo", "水桶", "bucket", "topic"],
    ["la pala", "铲子", "shovel", "topic"],
    ["el rastrillo", "耙子", "rake", "topic"],
    ["el hacha", "斧头", "axe", "topic"],
    ["la cinta métrica", "卷尺", "tape measure", "topic"],
    ["la caja de herramientas", "工具箱", "toolbox", "topic"],
    ["el volante", "方向盘", "steering wheel", "topic"],
    ["el freno", "刹车", "brake", "topic"],
    ["el neumático", "轮胎", "tyre", "topic"],
    ["el parabrisas", "挡风玻璃", "windscreen", "topic"],
    ["el limpiaparabrisas", "雨刷", "wiper", "topic"],
    ["el capó", "引擎盖", "bonnet", "topic"],
    ["el maletero", "后备箱", "boot", "topic"],
    ["el cinturón de seguridad", "安全带", "seat belt", "topic"],
    ["el retrovisor", "后视镜", "mirror", "topic"],
    ["la bocina", "喇叭", "horn", "topic"],
    ["la marcha", "挡位", "gear", "topic"],
    ["el embrague", "离合器", "clutch", "topic"],
    ["la batería", "电池", "battery", "topic"],
    ["el combustible", "燃料", "fuel", "topic"],
    ["el tubo de escape", "排气管", "exhaust", "topic"],
    ["la cacerola", "炖锅", "saucepan", "topic"],
    ["la sartén", "煎锅", "frying pan", "topic"],
    ["el hervidor", "水壶", "kettle", "topic"],
    ["la tetera", "茶壶", "teapot", "topic"],
    ["el cuenco", "碗", "bowl", "topic"],
    ["la bandeja", "托盘", "tray", "topic"],
    ["el rallador", "刨丝器", "grater", "topic"],
    ["el cucharón", "长柄勺", "ladle", "topic"],
    ["el batidor", "打蛋器", "whisk", "topic"],
    ["el rodillo", "擀面杖", "rolling pin", "topic"],
    ["la tabla de cortar", "砧板", "chopping board", "topic"],
    ["el colador", "筛子", "sieve", "topic"],
    ["el sacacorchos", "开瓶器", "corkscrew", "topic"],
    ["el abrelatas", "开罐器", "tin opener", "topic"],
    ["la batidora", "搅拌机", "blender", "topic"],
    ["la tostadora", "烤面包机", "toaster", "topic"],
    ["el fregadero", "水槽", "sink", "topic"],
    ["el grifo", "水龙头", "tap", "topic"],
    ["la esponja", "海绵", "sponge", "topic"],
    ["el delantal", "围裙", "apron", "topic"],
    ["el mantel", "桌布", "tablecloth", "topic"],
    ["el tarro", "罐子", "jar", "topic"],
    ["la lata", "罐头", "tin", "topic"],
    ["la botella", "瓶子", "bottle", "topic"],
    ["el corcho", "软木塞", "cork", "topic"],
    ["el tubo", "管", "tube", "topic"],
    ["el barril", "桶", "barrel", "topic"],
    ["la cesta", "篮子", "basket", "topic"],
    ["el cuadrado", "正方形", "square", "topic"],
    ["el óvalo", "椭圆", "oval", "topic"],
    ["la esfera", "球体", "sphere", "topic"],
    ["el cilindro", "圆柱", "cylinder", "topic"],
    ["el cono", "圆锥", "cone", "topic"],
    ["la pirámide", "金字塔", "pyramid", "topic"],
    ["la curva", "曲线", "curve", "topic"],
    ["el borde", "边缘", "edge", "topic"],
    ["la esquina", "角落", "corner", "topic"],
    ["la superficie", "表面", "surface", "topic"],
    ["la anchura", "宽度", "width", "topic"],
    ["la profundidad", "深度", "depth", "topic"],
    ["la longitud", "长度", "length", "topic"],
    ["el par", "一双", "pair", "topic"],
    ["el porcentaje", "百分比", "percentage", "topic"],
    ["la media", "平均", "average", "topic"],
    ["la suma", "总和", "sum", "topic"],
    ["el decimal", "小数", "decimal", "topic"],
    ["la calculadora", "计算器", "calculator", "topic"],
    ["la brújula", "指南针", "compass", "topic"],
    ["la báscula", "秤", "scales", "topic"]
  );
})();
