/* =====================================================
   FUGA MYTHICA — CURSUS Spanish 🇪🇸 · batch 7 — topical everyday vocabulary + derivations
   ===================================================== */
(function () {
  const p = VOCAB.es;
  Object.assign(p.roots, { topic: ["主题词汇", "领域词汇,无词根", "everyday topics"] });
  p.words.push(
    ["la merienda", "下午茶", "snack", "topic"],
    ["el jamón", "火腿", "ham", "topic"],
    ["el chorizo", "香肠", "chorizo", "topic"],
    ["el cordero", "羔羊肉", "lamb", "topic"],
    ["el atún", "金枪鱼", "tuna", "topic"],
    ["los mariscos", "海鲜", "seafood", "topic"],
    ["la gamba", "虾", "prawn", "topic"],
    ["la pimienta", "胡椒", "pepper", "topic"],
    ["la harina", "面粉", "flour", "topic"],
    ["el tomate", "番茄", "tomato", "topic"],
    ["la cebolla", "洋葱", "onion", "topic"],
    ["el ajo", "大蒜", "garlic", "topic"],
    ["el champiñón", "蘑菇", "mushroom", "topic"],
    ["la pera", "梨", "pear", "topic"],
    ["el melocotón", "桃", "peach", "topic"],
    ["la uva", "葡萄", "grape", "topic"],
    ["la fresa", "草莓", "strawberry", "topic"],
    ["la cereza", "樱桃", "cherry", "topic"],
    ["el plátano", "香蕉", "banana", "topic"],
    ["la tarta", "蛋糕", "cake", "topic"],
    ["la galleta", "饼干", "biscuit", "topic"],
    ["el agua mineral", "矿泉水", "mineral water", "topic"],
    ["el vaso", "玻璃杯", "glass", "topic"],
    ["el cuchillo", "刀", "knife", "topic"],
    ["la cuchara", "勺子", "spoon", "topic"],
    ["la servilleta", "餐巾", "napkin", "topic"],
    ["la propina", "小费", "tip", "topic"],
    ["el camarero", "服务员", "waiter", "topic"],
    ["la reserva", "预订", "reservation", "topic"],
    ["la mejilla", "脸颊", "cheek", "topic"],
    ["la barbilla", "下巴", "chin", "topic"],
    ["el codo", "肘", "elbow", "topic"],
    ["la muñeca", "手腕,娃娃", "wrist", "topic"],
    ["la uña", "指甲", "nail", "topic"],
    ["el pecho", "胸", "chest", "topic"],
    ["la barriga", "肚子", "belly", "topic"],
    ["el tobillo", "脚踝", "ankle", "topic"],
    ["el cerebro", "大脑", "brain", "topic"],
    ["el pulmón", "肺", "lung", "topic"],
    ["el estómago", "胃", "stomach", "topic"],
    ["el hígado", "肝", "liver", "topic"],
    ["el riñón", "肾", "kidney", "topic"],
    ["el resfriado", "感冒", "cold", "topic"],
    ["la fiebre", "发烧", "fever", "topic"],
    ["la tos", "咳嗽", "cough", "topic"],
    ["el dolor de cabeza", "头痛", "headache", "topic"],
    ["urgencias", "急诊", "emergency room", "topic"],
    ["el enfermero", "护士", "nurse", "topic"],
    ["la planta", "楼层,植物", "floor", "topic"],
    ["el ascensor", "电梯", "lift", "topic"],
    ["el salón", "客厅", "living room", "topic"],
    ["el cuarto de baño", "浴室", "bathroom", "topic"],
    ["el balcón", "阳台", "balcony", "topic"],
    ["el garaje", "车库", "garage", "topic"],
    ["la manta", "毯子", "blanket", "topic"],
    ["el sofá", "沙发", "sofa", "topic"],
    ["el sillón", "扶手椅", "armchair", "topic"],
    ["la estantería", "书架", "shelf", "topic"],
    ["la lámpara", "灯", "lamp", "topic"],
    ["la cortina", "窗帘", "curtain", "topic"],
    ["la nevera", "冰箱", "fridge", "topic"],
    ["el horno", "烤箱", "oven", "topic"],
    ["el lavavajillas", "洗碗机", "dishwasher", "topic"],
    ["la aspiradora", "吸尘器", "vacuum cleaner", "topic"],
    ["la basura", "垃圾", "rubbish", "topic"],
    ["la camiseta", "T恤", "T-shirt", "topic"],
    ["la camisa", "衬衫", "shirt", "topic"],
    ["los pantalones", "裤子", "trousers", "topic"],
    ["los vaqueros", "牛仔裤", "jeans", "topic"],
    ["la chaqueta", "夹克", "jacket", "topic"],
    ["el abrigo", "大衣", "coat", "topic"],
    ["el jersey", "毛衣", "sweater", "topic"],
    ["los zapatos", "鞋", "shoes", "topic"],
    ["las botas", "靴子", "boots", "topic"],
    ["los calcetines", "袜子", "socks", "topic"],
    ["la gorra", "鸭舌帽", "cap", "topic"],
    ["la bufanda", "围巾", "scarf", "topic"],
    ["los guantes", "手套", "gloves", "topic"],
    ["el cinturón", "腰带", "belt", "topic"],
    ["el bolso", "包", "bag", "topic"],
    ["las gafas", "眼镜", "glasses", "topic"],
    ["el supermercado", "超市", "supermarket", "topic"],
    ["la carnicería", "肉店", "butcher's", "topic"],
    ["el quiosco", "报刊亭", "newsstand", "topic"],
    ["el centro comercial", "购物中心", "shopping centre", "topic"],
    ["el descuento", "折扣", "discount", "topic"],
    ["las rebajas", "打折季", "sales", "topic"],
    ["la caja", "收银台,盒子", "till", "topic"],
    ["la tarjeta de crédito", "信用卡", "credit card", "topic"],
    ["el efectivo", "现金", "cash", "topic"],
    ["el andén", "站台", "platform", "topic"],
    ["el billete", "票", "ticket", "topic"],
    ["la parada", "站点", "stop", "topic"],
    ["el metro", "地铁", "underground", "topic"],
    ["el tranvía", "有轨电车", "tram", "topic"],
    ["el taxi", "出租车", "taxi", "topic"],
    ["el carné de conducir", "驾照", "driving licence", "topic"],
    ["la gasolina", "汽油", "petrol", "topic"],
    ["el aparcamiento", "停车场", "car park", "topic"],
    ["la autopista", "高速公路", "motorway", "topic"],
    ["la acera", "人行道", "pavement", "topic"],
    ["la maleta", "行李箱", "suitcase", "topic"],
    ["la mochila", "背包", "backpack", "topic"],
    ["el hotel", "旅馆", "hotel", "topic"],
    ["el lago", "湖", "lake", "topic"],
    ["la guardería", "幼儿园", "nursery", "topic"],
    ["la clase", "班级,课", "class", "topic"],
    ["el aula", "教室", "classroom", "topic"],
    ["la pizarra", "黑板", "blackboard", "topic"],
    ["el pupitre", "课桌", "desk", "topic"],
    ["el cuaderno", "练习本", "exercise book", "topic"],
    ["el bolígrafo", "圆珠笔", "pen", "topic"],
    ["el lápiz", "铅笔", "pencil", "topic"],
    ["la goma", "橡皮", "eraser", "topic"],
    ["los deberes", "作业", "homework", "topic"],
    ["el examen", "考试", "exam", "topic"],
    ["la asignatura", "科目", "subject", "topic"],
    ["las matemáticas", "数学", "maths", "topic"],
    ["la física", "物理", "physics", "topic"],
    ["la química", "化学", "chemistry", "topic"],
    ["la pantalla", "屏幕", "screen", "topic"],
    ["el teclado", "键盘", "keyboard", "topic"],
    ["el ratón", "鼠标,老鼠", "mouse", "topic"],
    ["la contraseña", "密码", "password", "topic"],
    ["la red", "网络", "network", "topic"],
    ["el sitio web", "网站", "website", "topic"],
    ["el correo electrónico", "电子邮件", "email", "topic"],
    ["la niebla", "雾", "fog", "topic"],
    ["la tormenta", "暴风雨", "storm", "topic"],
    ["el frío", "冷", "cold", "topic"],
    ["la humedad", "湿度", "humidity", "topic"],
    ["el gato", "猫", "cat", "topic"],
    ["la vaca", "奶牛", "cow", "topic"],
    ["la oveja", "羊", "sheep", "topic"],
    ["la cabra", "山羊", "goat", "topic"],
    ["la gallina", "母鸡", "hen", "topic"],
    ["el conejo", "兔子", "rabbit", "topic"],
    ["el lobo", "狼", "wolf", "topic"],
    ["el oso", "熊", "bear", "topic"],
    ["el zorro", "狐狸", "fox", "topic"],
    ["el ciervo", "鹿", "deer", "topic"],
    ["el león", "狮子", "lion", "topic"],
    ["el tigre", "老虎", "tiger", "topic"],
    ["el elefante", "大象", "elephant", "topic"],
    ["el mono", "猴子", "monkey", "topic"],
    ["la serpiente", "蛇", "snake", "topic"],
    ["la mariposa", "蝴蝶", "butterfly", "topic"],
    ["la abeja", "蜜蜂", "bee", "topic"],
    ["la mosca", "苍蝇", "fly", "topic"],
    ["el mosquito", "蚊子", "mosquito", "topic"],
    ["la araña", "蜘蛛", "spider", "topic"],
    ["la hoja", "叶子,纸张", "leaf", "topic"],
    ["la raíz", "根", "root", "topic"],
    ["la hierba", "草", "grass", "topic"],
    ["el fútbol", "足球", "football", "topic"],
    ["el baloncesto", "篮球", "basketball", "topic"],
    ["el voleibol", "排球", "volleyball", "topic"],
    ["el tenis", "网球", "tennis", "topic"],
    ["el ciclismo", "自行车运动", "cycling", "topic"],
    ["el gimnasio", "健身房", "gym", "topic"],
    ["el entrenador", "教练", "coach", "topic"],
    ["el aficionado", "球迷", "fan", "topic"],
    ["la derrota", "失败", "defeat", "topic"],
    ["el empate", "平局", "draw", "topic"],
    ["el gol", "进球", "goal", "topic"],
    ["el estadio", "体育场", "stadium", "topic"],
    ["la medalla", "奖牌", "medal", "topic"],
    ["el campeonato", "锦标赛", "championship", "topic"],
    ["la música", "音乐", "music", "topic"],
    ["la película", "电影", "film", "topic"],
    ["el cine", "电影院", "cinema", "topic"],
    ["el teatro", "剧院", "theatre", "topic"],
    ["el museo", "博物馆", "museum", "topic"],
    ["el pintor", "画家", "painter", "topic"],
    ["el periódico", "报纸", "newspaper", "topic"],
    ["la revista", "杂志", "magazine", "topic"],
    ["el programa", "节目", "programme", "topic"],
    ["el cumpleaños", "生日", "birthday", "topic"],
    ["la boda", "婚礼", "wedding", "topic"],
    ["la Navidad", "圣诞节", "Christmas", "topic"],
    ["la Nochevieja", "除夕", "New Year's Eve", "topic"],
    ["la Semana Santa", "圣周", "Holy Week", "topic"],
    ["la empresa", "公司", "company", "topic"],
    ["el empleado", "雇员", "employee", "topic"],
    ["el sueldo", "薪水", "salary", "topic"],
    ["el cliente", "客户", "customer", "topic"],
    ["el currículum", "简历", "CV", "topic"],
    ["el paro", "失业", "unemployment", "topic"],
    ["la jubilación", "退休", "retirement", "topic"],
    ["el anunciante", "广告主", "advertiser", "nunc"],
    ["la dormida", "睡眠", "sleep", "dorm"],
    ["el dormilón", "贪睡者", "sleepyhead", "dorm"],
    ["la manilla", "把手", "handle", "man"],
    ["el manubrio", "把手", "handlebar", "man"],
    ["el cordón", "鞋带", "lace", "cord"],
    ["la corpulencia", "魁梧", "bulk", "corp"],
    ["el terrado", "平屋顶", "flat roof", "terr"],
    ["el subterráneo", "地下的", "underground", "terr"],
    ["el terrateniente", "地主", "landowner", "terr"],
    ["la amabilidad", "亲切", "kindness", "am"],
    ["el portátil", "笔记本电脑", "laptop", "port"],
    ["el escribano", "书记", "scribe", "scrib"],
    ["la hacienda", "庄园", "estate", "fac"],
    ["el poniente", "西方", "west", "pon"],
    ["la pose", "姿势", "pose", "pon"],
    ["la misiva", "信函", "missive", "mitt"],
    ["el carril", "车道", "lane", "curr"],
    ["la cesión", "转让", "transfer", "ced"],
    ["la rotura", "破裂", "breakage", "rupt"],
    ["la clausura", "关闭", "closure", "core"],
    ["la prensa", "新闻界", "press", "core"],
    ["el mobiliario", "家具", "furniture", "mov"],
    ["la fluidez", "流畅", "fluency", "flu"],
    ["creciente", "增长的", "growing", "core"],
    ["la especialidad", "特色菜", "speciality", "spec"],
    ["el espécimen", "标本", "specimen", "spec"],
    ["el accidente", "事故", "accident", "cid"],
    ["el caso", "情况", "case", "cid"],
    ["la reclamación", "投诉", "complaint", "clam"],
    ["la inclinación", "倾向", "inclination", "clin"],
    ["el docente", "教师", "lecturer", "doc"],
    ["la docencia", "教学", "teaching", "doc"],
    ["la donación", "捐赠", "donation", "don"],
    ["la fuga", "逃跑", "escape", "fug"],
    ["la amonestación", "警告", "warning", "mon"],
    ["el pliegue", "褶", "fold", "plic"],
    ["la aprobación", "批准", "approval", "prob"],
    ["la respiración", "呼吸", "breathing", "spir"],
    ["el turbión", "暴雨", "downpour", "core"],
    ["la invasión", "入侵", "invasion", "core"],
    ["la evasión", "逃避", "evasion", "core"],
    ["el fontanero", "水管工", "plumber", "topic"],
    ["el electricista", "电工", "electrician", "topic"],
    ["el carpintero", "木匠", "carpenter", "topic"],
    ["el mecánico", "机械师", "mechanic", "topic"],
    ["el peluquero", "理发师", "hairdresser", "topic"],
    ["el panadero", "面包师", "baker", "topic"],
    ["el carnicero", "屠夫", "butcher", "topic"],
    ["el cocinero", "厨师", "cook", "topic"],
    ["el bombero", "消防员", "firefighter", "topic"],
    ["el policía", "警察", "police officer", "topic"],
    ["el contable", "会计", "accountant", "topic"],
    ["el científico", "科学家", "scientist", "topic"],
    ["el investigador", "研究员", "researcher", "topic"],
    ["el programador", "程序员", "programmer", "topic"],
    ["el piloto", "飞行员", "pilot", "topic"],
    ["el azafato", "空乘", "flight attendant", "topic"],
    ["el dependiente", "店员", "shop assistant", "topic"],
    ["el cajero", "收银员", "cashier", "topic"],
    ["el cartero", "邮递员", "postman", "topic"],
    ["la cuenta bancaria", "银行账户", "bank account", "topic"],
    ["el cajero automático", "自动取款机", "ATM", "topic"],
    ["el préstamo", "贷款", "loan", "topic"],
    ["la hipoteca", "抵押贷款", "mortgage", "topic"],
    ["el ahorro", "储蓄", "savings", "topic"],
    ["el seguro", "保险", "insurance", "topic"],
    ["la oficina de correos", "邮局", "post office", "topic"],
    ["el sello", "邮票", "stamp", "topic"],
    ["el sobre", "信封", "envelope", "topic"],
    ["el paquete", "包裹", "parcel", "topic"],
    ["el ayuntamiento", "市政厅", "town hall", "topic"],
    ["la comisaría", "警察局", "police station", "topic"],
    ["la biblioteca", "图书馆", "library", "topic"],
    ["la catedral", "大教堂", "cathedral", "topic"],
    ["la torre", "塔", "tower", "topic"],
    ["el parque", "公园", "park", "topic"],
    ["el zoológico", "动物园", "zoo", "topic"],
    ["el polideportivo", "体育中心", "sports centre", "topic"],
    ["la peluquería", "理发店", "hairdresser's", "topic"],
    ["la gasolinera", "加油站", "petrol station", "topic"],
    ["la granja", "农场", "farm", "topic"],
    ["el huerto", "菜园", "vegetable garden", "topic"],
    ["el trigo", "小麦", "wheat", "topic"],
    ["el maíz", "玉米", "maize", "topic"],
    ["el olivo", "橄榄树", "olive tree", "topic"],
    ["el pino", "松树", "pine", "topic"],
    ["la rosa", "玫瑰", "rose", "topic"],
    ["el clavel", "康乃馨", "carnation", "topic"],
    ["la semilla", "种子", "seed", "topic"],
    ["la rama", "树枝", "branch", "topic"],
    ["el tronco", "树干", "trunk", "topic"],
    ["la arena", "沙子", "sand", "topic"],
    ["la roca", "岩石", "rock", "topic"],
    ["el valle", "山谷", "valley", "topic"],
    ["la selva", "丛林", "jungle", "topic"],
    ["la costa", "海岸", "coast", "topic"],
    ["la ola", "海浪", "wave", "topic"],
    ["el amanecer", "黎明", "dawn", "topic"],
    ["el atardecer", "黄昏", "dusk", "topic"],
    ["los celos", "吃醋", "jealousy", "topic"],
    ["el enfado", "生气", "anger", "topic"],
    ["la sorpresa", "惊讶", "surprise", "topic"],
    ["el aburrimiento", "无聊", "boredom", "topic"],
    ["el cariño", "喜爱", "affection", "topic"]
  );
})();
