/* =====================================================
   FUGA MYTHICA — CURSUS English 🇬🇧 · batch 10 — topical vocabulary 3: adverbs & connectors, time & quantity, hobbies, sport, music, nationalities, animals, plants, house, office, abstract nouns
   ===================================================== */
(function () {
  const p = VOCAB.en;
  Object.assign(p.roots, {});
  p.words.push(
    ["nevertheless", "尽管如此", "even so", "topic"],
    ["moreover", "此外", "also", "topic"],
    ["furthermore", "而且", "in addition", "topic"],
    ["afterwards", "之后", "later", "topic"],
    ["beforehand", "事先", "in advance", "topic"],
    ["immediately", "立刻", "at once", "topic"],
    ["suddenly", "突然", "without warning", "topic"],
    ["gradually", "逐渐", "step by step", "topic"],
    ["recently", "最近", "not long ago", "topic"],
    ["lately", "近来", "recently", "topic"],
    ["nowadays", "如今", "these days", "topic"],
    ["formerly", "以前", "in the past", "topic"],
    ["currently", "目前", "now", "topic"],
    ["temporarily", "暂时", "for a short time", "topic"],
    ["permanently", "永久地", "for ever", "topic"],
    ["rarely", "很少", "not often", "topic"],
    ["occasionally", "偶尔", "sometimes", "topic"],
    ["frequently", "经常", "often", "topic"],
    ["constantly", "不断地", "all the time", "topic"],
    ["daily", "每天", "every day", "topic"],
    ["weekly", "每周", "every week", "topic"],
    ["monthly", "每月", "every month", "topic"],
    ["yearly", "每年", "every year", "topic"],
    ["hardly", "几乎不", "barely", "topic"],
    ["extremely", "极其", "very", "topic"],
    ["slightly", "稍微", "a little", "topic"],
    ["entirely", "完全", "completely", "topic"],
    ["partly", "部分地", "not completely", "topic"],
    ["mainly", "主要地", "mostly", "topic"],
    ["particularly", "特别", "especially", "topic"],
    ["approximately", "大约", "about", "topic"],
    ["exactly", "恰好", "precisely", "topic"],
    ["precisely", "精确地", "exactly", "topic"],
    ["apparently", "显然", "it seems", "topic"],
    ["obviously", "明显地", "clearly", "topic"],
    ["certainly", "当然", "surely", "topic"],
    ["probably", "可能", "likely", "topic"],
    ["possibly", "也许", "maybe", "topic"],
    ["definitely", "肯定", "for sure", "topic"],
    ["hopefully", "但愿", "it is hoped", "topic"],
    ["unfortunately", "不幸地", "sadly", "topic"],
    ["fortunately", "幸运地", "luckily", "topic"],
    ["surprisingly", "令人惊讶地", "unexpectedly", "topic"],
    ["honestly", "老实说", "truthfully", "topic"],
    ["basically", "基本上", "essentially", "topic"],
    ["generally", "一般来说", "usually", "topic"],
    ["specifically", "具体地", "in particular", "topic"],
    ["namely", "即", "that is", "topic"],
    ["for instance", "例如", "for example", "topic"],
    ["in other words", "换句话说", "that is to say", "topic"],
    ["on the other hand", "另一方面", "conversely", "topic"],
    ["in addition", "此外", "also", "topic"],
    ["in short", "简而言之", "briefly", "topic"],
    ["at least", "至少", "minimum", "topic"],
    ["at most", "至多", "maximum", "topic"],
    ["as well", "也", "too", "topic"],
    ["besides", "况且", "also", "topic"],
    ["as soon as", "一…就", "immediately when", "topic"],
    ["as long as", "只要", "provided that", "topic"],
    ["in case", "以防", "if it happens", "topic"],
    ["even though", "即使", "despite", "topic"],
    ["in spite of", "尽管", "despite", "topic"],
    ["because of", "因为", "due to", "topic"],
    ["thanks to", "多亏", "owing to", "topic"],
    ["according to", "根据", "as stated by", "topic"],
    ["regarding", "关于", "about", "topic"],
    ["throughout", "贯穿", "during all of", "topic"],
    ["towards", "朝向", "in the direction of", "topic"],
    ["dawn", "黎明", "first light", "topic"],
    ["dusk", "黄昏", "evening twilight", "topic"],
    ["fortnight", "两周", "two weeks", "topic"],
    ["era", "时代", "period", "topic"],
    ["schedule", "时间表", "timetable", "topic"],
    ["appointment", "预约", "arranged meeting", "topic"],
    ["delay", "延迟", "lateness", "topic"],
    ["eve", "前夕", "day before", "topic"],
    ["leap year", "闰年", "366-day year", "topic"],
    ["quantity", "数量", "amount", "topic"],
    ["amount", "数额", "quantity", "topic"],
    ["handful", "一把", "small number", "topic"],
    ["heap", "堆", "pile", "topic"],
    ["bunch", "一束", "group", "topic"],
    ["drop", "一滴", "small amount of liquid", "topic"],
    ["crumb", "面包屑", "tiny piece", "topic"],
    ["lump", "块", "piece", "topic"],
    ["spoonful", "一勺", "spoon amount", "topic"],
    ["layer", "层", "level", "topic"],
    ["stack", "叠", "pile", "topic"],
    ["hobby", "爱好", "pastime", "topic"],
    ["leisure", "休闲", "free time", "topic"],
    ["pastime", "消遣", "hobby", "topic"],
    ["gardening", "园艺", "growing plants", "topic"],
    ["photography", "摄影", "taking photos", "topic"],
    ["drawing", "素描", "sketch", "topic"],
    ["pottery", "陶艺", "clay work", "topic"],
    ["knitting", "编织", "wool craft", "topic"],
    ["sewing", "缝纫", "needlework", "topic"],
    ["carpentry", "木工", "woodwork", "topic"],
    ["collecting", "收藏", "gathering items", "topic"],
    ["collector", "收藏家", "one who collects", "topic"],
    ["puzzle", "拼图", "jigsaw", "topic"],
    ["crossword", "填字游戏", "word puzzle", "topic"],
    ["board game", "桌游", "table game", "topic"],
    ["chess", "国际象棋", "chess", "topic"],
    ["cards", "扑克牌", "playing cards", "topic"],
    ["dice", "骰子", "dice", "topic"],
    ["video game", "电子游戏", "video game", "topic"],
    ["console", "游戏机", "games machine", "topic"],
    ["karaoke", "卡拉OK", "karaoke", "topic"],
    ["picnic", "野餐", "outdoor meal", "topic"],
    ["barbecue", "烧烤", "grill party", "topic"],
    ["fishing rod", "钓竿", "fishing pole", "topic"],
    ["racket", "球拍", "bat", "topic"],
    ["ball", "球", "ball", "topic"],
    ["net", "网", "net", "topic"],
    ["goalkeeper", "守门员", "goalie", "topic"],
    ["referee", "裁判", "umpire", "topic"],
    ["pitch", "球场", "field", "topic"],
    ["lap", "一圈", "circuit", "topic"],
    ["marathon", "马拉松", "long race", "topic"],
    ["hurdle", "跨栏", "barrier", "topic"],
    ["javelin", "标枪", "throwing spear", "topic"],
    ["wrestling", "摔跤", "grappling sport", "topic"],
    ["boxing", "拳击", "fist fighting", "topic"],
    ["fencing", "击剑", "sword sport", "topic"],
    ["archery", "射箭", "bow sport", "topic"],
    ["rowing", "赛艇", "oar sport", "topic"],
    ["sailing", "帆船", "boat sport", "topic"],
    ["surfing", "冲浪", "wave riding", "topic"],
    ["diving", "潜水", "underwater sport", "topic"],
    ["climbing", "攀岩", "rock sport", "topic"],
    ["skating", "滑冰", "ice sport", "topic"],
    ["skateboard", "滑板", "board", "topic"],
    ["helmet", "头盔", "head protection", "topic"],
    ["tournament", "锦标赛", "competition", "topic"],
    ["semi-final", "半决赛", "match before final", "topic"],
    ["offside", "越位", "offside", "topic"],
    ["half-time", "中场休息", "break", "topic"],
    ["extra time", "加时赛", "added time", "topic"],
    ["classical music", "古典音乐", "classical", "topic"],
    ["jazz", "爵士乐", "jazz", "topic"],
    ["rock", "摇滚", "rock", "topic"],
    ["pop music", "流行音乐", "pop", "topic"],
    ["folk music", "民谣", "folk", "topic"],
    ["rap", "说唱", "rap", "topic"],
    ["lyrics", "歌词", "song words", "topic"],
    ["chord", "和弦", "chord", "topic"],
    ["tune", "曲调", "melody", "topic"],
    ["album", "专辑", "record", "topic"],
    ["band", "乐队", "group", "topic"],
    ["drummer", "鼓手", "drum player", "topic"],
    ["guitarist", "吉他手", "guitar player", "topic"],
    ["pianist", "钢琴家", "piano player", "topic"],
    ["violinist", "小提琴手", "violin player", "topic"],
    ["composer", "作曲家", "music writer", "topic"],
    ["loudspeaker", "扬声器", "speaker", "topic"],
    ["headphones", "耳机", "earphones", "topic"],
    ["British", "英国的", "from Britain", "topic"],
    ["Irish", "爱尔兰的", "from Ireland", "topic"],
    ["Scottish", "苏格兰的", "from Scotland", "topic"],
    ["Dutch", "荷兰的", "from the Netherlands", "topic"],
    ["Belgian", "比利时的", "from Belgium", "topic"],
    ["Swiss", "瑞士的", "from Switzerland", "topic"],
    ["Austrian", "奥地利的", "from Austria", "topic"],
    ["Polish", "波兰的", "from Poland", "topic"],
    ["Czech", "捷克的", "from Czechia", "topic"],
    ["Hungarian", "匈牙利的", "from Hungary", "topic"],
    ["Swedish", "瑞典的", "from Sweden", "topic"],
    ["Norwegian", "挪威的", "from Norway", "topic"],
    ["Danish", "丹麦的", "from Denmark", "topic"],
    ["Finnish", "芬兰的", "from Finland", "topic"],
    ["Portuguese", "葡萄牙的", "from Portugal", "topic"],
    ["Turkish", "土耳其的", "from Turkey", "topic"],
    ["Egyptian", "埃及的", "from Egypt", "topic"],
    ["Moroccan", "摩洛哥的", "from Morocco", "topic"],
    ["Indian", "印度的", "from India", "topic"],
    ["Korean", "韩国的", "from Korea", "topic"],
    ["Vietnamese", "越南的", "from Vietnam", "topic"],
    ["Thai", "泰国的", "from Thailand", "topic"],
    ["Australian", "澳大利亚的", "from Australia", "topic"],
    ["Canadian", "加拿大的", "from Canada", "topic"],
    ["Mexican", "墨西哥的", "from Mexico", "topic"],
    ["Brazilian", "巴西的", "from Brazil", "topic"],
    ["Argentinian", "阿根廷的", "from Argentina", "topic"],
    ["beetle", "甲虫", "beetle", "topic"],
    ["ladybird", "瓢虫", "ladybird", "topic"],
    ["grasshopper", "蚱蜢", "grasshopper", "topic"],
    ["cricket", "蟋蟀", "cricket", "topic"],
    ["wasp", "黄蜂", "wasp", "topic"],
    ["moth", "飞蛾", "moth", "topic"],
    ["snail", "蜗牛", "snail", "topic"],
    ["slug", "鼻涕虫", "slug", "topic"],
    ["worm", "蠕虫", "worm", "topic"],
    ["lizard", "蜥蜴", "lizard", "topic"],
    ["crocodile", "鳄鱼", "crocodile", "topic"],
    ["toad", "蟾蜍", "toad", "topic"],
    ["walrus", "海象", "walrus", "topic"],
    ["shark", "鲨鱼", "shark", "topic"],
    ["jellyfish", "水母", "jellyfish", "topic"],
    ["starfish", "海星", "starfish", "topic"],
    ["seahorse", "海马", "seahorse", "topic"],
    ["lobster", "龙虾", "lobster", "topic"],
    ["shrimp", "虾", "shrimp", "topic"],
    ["mussel", "贻贝", "mussel", "topic"],
    ["squid", "鱿鱼", "squid", "topic"],
    ["trout", "鳟鱼", "trout", "topic"],
    ["salmon", "三文鱼", "salmon", "topic"],
    ["cod", "鳕鱼", "cod", "topic"],
    ["sardine", "沙丁鱼", "sardine", "topic"],
    ["eel", "鳗鱼", "eel", "topic"],
    ["parrot", "鹦鹉", "parrot", "topic"],
    ["penguin", "企鹅", "penguin", "topic"],
    ["ostrich", "鸵鸟", "ostrich", "topic"],
    ["stork", "鹳", "stork", "topic"],
    ["heron", "鹭", "heron", "topic"],
    ["seagull", "海鸥", "seagull", "topic"],
    ["crow", "乌鸦", "crow", "topic"],
    ["magpie", "喜鹊", "magpie", "topic"],
    ["woodpecker", "啄木鸟", "woodpecker", "topic"],
    ["robin", "知更鸟", "robin", "topic"],
    ["pigeon", "鸽子", "pigeon", "topic"],
    ["turkey", "火鸡", "turkey", "topic"],
    ["bat", "蝙蝠", "bat", "topic"],
    ["hedgehog", "刺猬", "hedgehog", "topic"],
    ["squirrel", "松鼠", "squirrel", "topic"],
    ["rat", "大鼠", "rat", "topic"],
    ["hamster", "仓鼠", "hamster", "topic"],
    ["badger", "獾", "badger", "topic"],
    ["otter", "水獭", "otter", "topic"],
    ["beaver", "海狸", "beaver", "topic"],
    ["moose", "驼鹿", "moose", "topic"],
    ["reindeer", "驯鹿", "reindeer", "topic"],
    ["boar", "野猪", "boar", "topic"],
    ["donkey", "驴", "donkey", "topic"],
    ["mule", "骡子", "mule", "topic"],
    ["pony", "小马", "pony", "topic"],
    ["lamb", "羔羊", "lamb", "topic"],
    ["calf", "小牛", "calf", "topic"],
    ["kitten", "小猫", "kitten", "topic"],
    ["puppy", "小狗", "puppy", "topic"],
    ["giraffe", "长颈鹿", "giraffe", "topic"],
    ["zebra", "斑马", "zebra", "topic"],
    ["hippo", "河马", "hippo", "topic"],
    ["rhino", "犀牛", "rhino", "topic"],
    ["leopard", "豹", "leopard", "topic"],
    ["cheetah", "猎豹", "cheetah", "topic"],
    ["gorilla", "大猩猩", "gorilla", "topic"],
    ["kangaroo", "袋鼠", "kangaroo", "topic"],
    ["koala", "考拉", "koala", "topic"],
    ["panda", "熊猫", "panda", "topic"],
    ["polar bear", "北极熊", "polar bear", "topic"],
    ["whale", "鲸", "whale", "topic"],
    ["dolphin", "海豚", "dolphin", "topic"],
    ["fur", "毛皮", "fur", "topic"],
    ["claw", "爪子", "claw", "topic"],
    ["paw", "爪", "paw", "topic"],
    ["beak", "喙", "beak", "topic"],
    ["feather", "羽毛", "feather", "topic"],
    ["wing", "翅膀", "wing", "topic"],
    ["tail", "尾巴", "tail", "topic"],
    ["hoof", "蹄", "hoof", "topic"],
    ["mane", "鬃毛", "mane", "topic"],
    ["shell", "壳", "shell", "topic"],
    ["fin", "鳍", "fin", "topic"],
    ["nest", "巢", "nest", "topic"],
    ["den", "兽穴", "den", "topic"],
    ["hive", "蜂巢", "hive", "topic"],
    ["herd", "兽群", "herd", "topic"],
    ["flock", "羊群", "flock", "topic"],
    ["tulip", "郁金香", "tulip", "topic"],
    ["daisy", "雏菊", "daisy", "topic"],
    ["sunflower", "向日葵", "sunflower", "topic"],
    ["lily", "百合", "lily", "topic"],
    ["orchid", "兰花", "orchid", "topic"],
    ["poppy", "罂粟花", "poppy", "topic"],
    ["lavender", "薰衣草", "lavender", "topic"],
    ["jasmine", "茉莉", "jasmine", "topic"],
    ["ivy", "常春藤", "ivy", "topic"],
    ["moss", "苔藓", "moss", "topic"],
    ["fern", "蕨类", "fern", "topic"],
    ["cactus", "仙人掌", "cactus", "topic"],
    ["bush", "灌木", "bush", "topic"],
    ["hedge", "树篱", "hedge", "topic"],
    ["lawn", "草坪", "lawn", "topic"],
    ["weed", "杂草", "weed", "topic"],
    ["bud", "花蕾", "bud", "topic"],
    ["petal", "花瓣", "petal", "topic"],
    ["stem", "茎", "stem", "topic"],
    ["thorn", "刺", "thorn", "topic"],
    ["bark", "树皮", "bark", "topic"],
    ["twig", "细枝", "twig", "topic"],
    ["birch", "桦树", "birch", "topic"],
    ["beech", "山毛榉", "beech", "topic"],
    ["maple", "枫树", "maple", "topic"],
    ["willow", "柳树", "willow", "topic"],
    ["poplar", "杨树", "poplar", "topic"],
    ["fir", "冷杉", "fir", "topic"],
    ["cypress", "柏树", "cypress", "topic"],
    ["palm tree", "棕榈树", "palm", "topic"],
    ["chestnut", "栗子", "chestnut", "topic"],
    ["walnut", "核桃", "walnut", "topic"],
    ["almond", "杏仁", "almond", "topic"],
    ["hazelnut", "榛子", "hazelnut", "topic"],
    ["apricot", "杏", "apricot", "topic"],
    ["plum", "李子", "plum", "topic"],
    ["fig", "无花果", "fig", "topic"],
    ["melon", "甜瓜", "melon", "topic"],
    ["pineapple", "菠萝", "pineapple", "topic"],
    ["mango", "芒果", "mango", "topic"],
    ["coconut", "椰子", "coconut", "topic"],
    ["raspberry", "覆盆子", "raspberry", "topic"],
    ["blueberry", "蓝莓", "blueberry", "topic"],
    ["grapefruit", "柚子", "grapefruit", "topic"],
    ["pumpkin", "南瓜", "pumpkin", "topic"],
    ["cucumber", "黄瓜", "cucumber", "topic"],
    ["pepper", "甜椒", "pepper", "topic"],
    ["aubergine", "茄子", "aubergine", "topic"],
    ["courgette", "西葫芦", "courgette", "topic"],
    ["spinach", "菠菜", "spinach", "topic"],
    ["cabbage", "卷心菜", "cabbage", "topic"],
    ["cauliflower", "花椰菜", "cauliflower", "topic"],
    ["broccoli", "西兰花", "broccoli", "topic"],
    ["celery", "芹菜", "celery", "topic"],
    ["leek", "韭葱", "leek", "topic"],
    ["pea", "豌豆", "pea", "topic"],
    ["bean", "豆", "bean", "topic"],
    ["lentil", "扁豆", "lentil", "topic"],
    ["chickpea", "鹰嘴豆", "chickpea", "topic"],
    ["oats", "燕麦", "oats", "topic"],
    ["barley", "大麦", "barley", "topic"],
    ["rye", "黑麦", "rye", "topic"],
    ["chimney", "烟囱", "chimney", "topic"],
    ["gutter", "排水沟", "gutter", "topic"],
    ["attic", "阁楼", "attic", "topic"],
    ["gate", "大门", "gate", "topic"],
    ["driveway", "车道", "driveway", "topic"],
    ["shed", "棚屋", "shed", "topic"],
    ["doorbell", "门铃", "doorbell", "topic"],
    ["lock", "锁", "lock", "topic"],
    ["hinge", "铰链", "hinge", "topic"],
    ["handle", "把手", "handle", "topic"],
    ["shutter", "百叶窗", "shutter", "topic"],
    ["blind", "窗帘", "blind", "topic"],
    ["wallpaper", "壁纸", "wallpaper", "topic"],
    ["ceiling", "天花板", "ceiling", "topic"],
    ["floorboard", "地板条", "floorboard", "topic"],
    ["radiator", "暖气片", "radiator", "topic"],
    ["boiler", "锅炉", "boiler", "topic"],
    ["pipe", "管道", "pipe", "topic"],
    ["leak", "漏水", "leak", "topic"],
    ["plug", "插头", "plug", "topic"],
    ["socket", "插座", "socket", "topic"],
    ["switch", "开关", "switch", "topic"],
    ["bulb", "灯泡", "bulb", "topic"],
    ["cable", "电缆", "cable", "topic"],
    ["meter", "电表", "meter", "topic"],
    ["landlord", "房东", "landlord", "topic"],
    ["lease", "租约", "lease", "topic"],
    ["removal", "搬家", "move", "topic"],
    ["desk", "办公桌", "desk", "topic"],
    ["drawer", "抽屉", "drawer", "topic"],
    ["filing cabinet", "文件柜", "filing cabinet", "topic"],
    ["stapler", "订书机", "stapler", "topic"],
    ["paper clip", "回形针", "paper clip", "topic"],
    ["sticky note", "便利贴", "sticky note", "topic"],
    ["highlighter", "荧光笔", "highlighter", "topic"],
    ["envelope", "信封", "envelope", "topic"],
    ["photocopier", "复印机", "photocopier", "topic"],
    ["shredder", "碎纸机", "shredder", "topic"],
    ["whiteboard", "白板", "whiteboard", "topic"],
    ["projector", "投影仪", "projector", "topic"],
    ["calendar", "日历", "calendar", "topic"],
    ["diary", "日程本", "diary", "topic"],
    ["badge", "工牌", "badge", "topic"],
    ["intern", "实习生", "intern", "topic"],
    ["receptionist", "前台", "receptionist", "topic"],
    ["cruelty", "残忍", "cruelty", "topic"],
    ["honesty", "诚实", "honesty", "topic"],
    ["loyalty", "忠诚", "loyalty", "topic"],
    ["patience", "耐心", "patience", "topic"],
    ["greed", "贪婪", "greed", "topic"],
    ["laziness", "懒惰", "laziness", "topic"],
    ["stubbornness", "固执", "stubbornness", "topic"],
    ["shyness", "害羞", "shyness", "topic"],
    ["confidence", "自信", "confidence", "topic"],
    ["generosity", "慷慨", "generosity", "topic"],
    ["curiosity", "好奇心", "curiosity", "topic"],
    ["creativity", "创造力", "creativity", "topic"],
    ["intelligence", "智力", "intelligence", "topic"],
    ["stupidity", "愚蠢", "stupidity", "topic"],
    ["madness", "疯狂", "madness", "topic"],
    ["beauty", "美", "beauty", "topic"],
    ["ugliness", "丑", "ugliness", "topic"],
    ["weakness", "弱点", "weakness", "topic"],
    ["speed", "速度", "speed", "topic"],
    ["slowness", "缓慢", "slowness", "topic"],
    ["silence", "寂静", "silence", "topic"],
    ["noise", "噪音", "noise", "topic"],
    ["brightness", "明亮", "brightness", "topic"],
    ["warmth", "温暖", "warmth", "topic"],
    ["coldness", "冷淡", "coldness", "topic"],
    ["softness", "柔软", "softness", "topic"],
    ["hardness", "硬度", "hardness", "topic"],
    ["cleanliness", "清洁", "cleanliness", "topic"],
    ["dirt", "污垢", "dirt", "topic"],
    ["safety", "安全", "safety", "topic"],
    ["danger", "危险", "danger", "topic"],
    ["luck", "运气", "luck", "topic"],
    ["misfortune", "不幸", "misfortune", "topic"],
    ["success", "成功", "success", "topic"],
    ["failure", "失败", "failure", "topic"],
    ["routine", "例行公事", "routine", "topic"],
    ["risk", "风险", "risk", "topic"],
    ["advantage", "优势", "advantage", "topic"],
    ["disadvantage", "劣势", "disadvantage", "topic"],
    ["mistake", "错误", "mistake", "topic"],
    ["excuse", "借口", "excuse", "topic"],
    ["surprise", "惊喜", "surprise", "topic"],
    ["joke", "笑话", "joke", "topic"],
    ["rumour", "谣言", "rumour", "topic"],
    ["argument", "争吵", "quarrel", "topic"],
    ["favour", "恩惠", "favour", "topic"],
    ["wish", "愿望", "wish", "topic"],
    ["nightmare", "噩梦", "nightmare", "topic"],
    ["adolescence", "青春期", "adolescence", "topic"],
    ["adulthood", "成年", "adulthood", "topic"],
    ["old age", "老年", "old age", "topic"],
    ["birth", "出生", "birth", "topic"]
  );
})();
