/* =====================================================
   FUGA MYTHICA — CURSUS English 🇬🇧 · batch 5
   ~110 mid-frequency Latin roots not yet covered, 4–7 words each. Gist = modern synonym.
   ===================================================== */
(function () {
  const p = VOCAB.en;
  Object.assign(p.roots, {
    ali: ["ali / alter", "其他", "other"], ambi: ["ambi", "两边", "both"], ang: ["ang / anx", "角,窄,痛", "angle; narrow"], aper: ["aper / overt", "开", "open"],
    arc: ["arc / arch", "弓,拱", "bow, arch"], arm: ["arm", "武器,手臂", "weapon, arm"], ax: ["ax", "轴", "axle"], bas: ["bas", "底", "base"],
    camp: ["camp / champ", "田野", "field"], cast: ["cast", "纯洁,城堡", "pure; fort"], cav: ["cav", "空", "hollow"], cel: ["cel / ceal", "藏", "hide"],
    celer: ["celer", "快", "swift"], cern: ["cern / cret / cert", "分辨", "sift, decide"], chart: ["chart / card", "纸", "paper"], cinct: ["cinct / cing", "束", "gird"],
    circ: ["circ", "圈", "circle"], clar: ["clar", "明", "clear"], clav: ["clav / clos", "钥匙,关", "key"], cop: ["cop", "丰富", "plenty"],
    coron: ["coron", "冠", "crown"], crim: ["crim", "罪", "charge"], cruc: ["cruc / cross", "十字", "cross"], culp: ["culp", "过错", "blame"],
    cumul: ["cumul", "堆", "heap"], cust: ["cust", "看守", "guard"], dam: ["dam / demn", "损害", "harm"], dec: ["dec / decor", "得体", "fitting"],
    dei: ["dei / div", "神", "god"], dens: ["dens", "密", "thick"], dexter: ["dexter", "右,巧", "right, skilful"], digit: ["digit", "指,数字", "finger"],
    dol: ["dol", "痛", "grief"], du: ["du / duo", "二", "two"], emin: ["emin / min", "突出", "jut out"], fam: ["fam", "名声", "report"],
    fil: ["fil", "线", "thread"], firm: ["firm", "牢", "steady"], flam: ["flam / flagr", "火焰", "flame"], fisc: ["fisc", "国库", "treasury"],
    foc: ["foc", "炉,焦点", "hearth"], front: ["front", "前额,前", "forehead, front"], fruct: ["fruct / frug / fruit", "果", "fruit"], gel: ["gel", "冻", "freeze"],
    grand: ["grand", "大", "great"], hered: ["hered / heir", "继承", "heir"], hor: ["hor / horr", "颤抖", "shudder"], insul: ["insul / isol", "岛", "island"],
    ir: ["ir / ira", "怒", "anger"], lav: ["lav / lut / luv", "洗", "wash"], lib: ["libr", "秤", "balance"], lim: ["lim / limin", "门槛,界", "threshold"],
    lin: ["lin", "线", "line"], lun: ["lun", "月", "moon"], mand: ["mand / mend", "命令,托", "order, entrust"], matur: ["matur", "熟", "ripe"],
    memb: ["membr", "肢,膜", "limb"], mol: ["mol", "堆,磨", "mass; grind"], mor: ["mor", "习俗", "custom"], nerv: ["nerv", "神经,筋", "sinew"],
    noct: ["noct / nox", "夜", "night"], nunc: ["nunc / nounce", "宣告", "announce"], oct: ["oct", "八", "eight"], ol: ["ol / odor", "闻", "smell"],
    orb: ["orb", "圆", "circle"], ov: ["ov", "卵", "egg"], pal: ["pal / pall", "苍白", "pale"], pauc: ["pauc / paup / pov", "少", "few"],
    pecc: ["pecc", "犯错", "sin"], pil: ["pil", "堆,柱", "pillar, pile"], plan: ["plan / plain", "平", "flat"], plat: ["plat", "平", "flat, broad"],
    pleb: ["pleb", "平民", "common people"], plor: ["plor", "哭喊", "cry out"], plumb: ["plumb", "铅", "lead"], prec2: ["preci / prais", "价", "price"],
    pred: ["pred / prey", "掠夺", "prey"], propr: ["propr / proper", "自己的", "one's own"], prox: ["prox / proach", "近", "near"], pud: ["pud", "羞", "shame"],
    quadr: ["quadr / quart / squar", "四", "four"], quies: ["quies / quiet / quil", "静", "rest"], quot: ["quot", "多少", "how many"], rar: ["rar", "稀", "rare"],
    rig: ["rig", "硬", "stiff"], riv: ["riv / rip", "河岸", "river bank"], rob: ["rob", "橡,强", "oak, strong"], rud: ["rud", "粗", "raw"],
    scrut: ["scrut", "细查", "search"], sept: ["sept", "七", "seven"], ser: ["ser / sert", "连接", "join, put"], sid: ["sid / sider", "星", "star"],
    sing: ["singul", "单", "single"], sinu: ["sinu", "弯", "curve"], solid: ["solid / sold", "固", "solid"], sorb: ["sorb / sorpt", "吸", "suck in"],
    sper: ["sper", "希望", "hope"], splend: ["splend", "光辉", "shine"], stud: ["stud", "热心,学", "zeal, study"], suad: ["suad / suas", "劝", "urge"],
    sult: ["sult / sal", "跳", "leap"], tal: ["tal / tail", "切,如此", "cut; such"], tard: ["tard", "慢", "slow"], tect: ["tect / teg", "盖", "cover"],
    tenu: ["tenu", "薄", "thin"], tol: ["tol / toll", "举,忍", "lift, bear"], ton: ["ton", "音,张力", "tone"], tot: ["tot", "全", "whole"],
    trud: ["trud / trus", "推", "thrust"], tum: ["tum", "肿", "swell"], ung: ["ung / oint", "涂", "smear"], vap: ["vap", "汽", "steam"],
    var: ["var", "变", "vary"], veh: ["veh / vex / vey", "运", "carry"], vel: ["vel / veal", "遮,速", "veil; speed"], verb: ["verb", "词", "word"],
    verg: ["verg", "倾向", "bend"], vic: ["vic", "代替,邻", "substitute; near"], vil: ["vil", "贱", "cheap"], vin: ["vin", "酒,藤", "wine"], vot: ["vot / vow", "誓", "vow"],
  });
  p.words.push(
    ["alien","外国的,外星人","foreign; extraterrestrial","ali"], ["alias","化名","false name","ali"], ["alibi","不在场证明","proof of absence","ali"], ["alter","改变","change","ali"], ["alternate","交替","take turns","ali"], ["alternative","替代方案","other option","ali"], ["altruism","利他","selflessness","ali"], ["alienate","疏远","estrange","ali"], ["inalienable","不可剥夺的","absolute","ali"],
    ["ambiguous","模糊的","unclear","ambi"], ["ambivalent","矛盾的","undecided","ambi"], ["ambient","周围的","surrounding","ambi"], ["ambidextrous","双手灵巧的","using both hands","ambi"], ["ambition","野心","drive to succeed","ambi"],
    ["angle","角","corner","ang"], ["angular","有角的","sharp-cornered","ang"], ["triangle","三角形","three-sided shape","ang"], ["anguish","痛苦","agony","ang"], ["anxious","焦虑的","worried","ang"], ["anxiety","焦虑","worry","ang"], ["angina","心绞痛","chest pain","ang"],
    ["aperture","孔","opening","aper"], ["April","四月","fourth month","aper"], ["overt","公开的","open","aper"], ["overture","序曲","opening piece","aper"], ["apéritif","开胃酒","pre-meal drink","aper"],
    ["arc","弧","curve","arc"], ["arch","拱","curved structure","arc"], ["archer","弓箭手","bowman","arc"], ["arcade","拱廊","arched passage","arc"], ["arcane","神秘的","secret","arc"],
    ["arm","手臂,武器","limb; weapon","arm"], ["army","军队","armed force","arm"], ["armor","盔甲","protective covering","arm"], ["disarm","解除武装","take weapons away","arm"], ["armistice","停战","truce","arm"], ["alarm","警报","warning","arm"], ["armada","舰队","fleet","arm"],
    ["axis","轴","central line","ax"], ["axle","轮轴","wheel shaft","ax"], ["axial","轴的","of the axis","ax"],
    ["base","基础","foundation","bas"], ["basis","基础","foundation","bas"], ["basement","地下室","underground floor","bas"], ["basic","基本的","fundamental","bas"], ["debase","贬低","degrade","bas"], ["abase","贬抑","humble","bas"],
    ["camp","营地","tent site","camp"], ["campus","校园","college grounds","camp"], ["campaign","运动,战役","organized effort","camp"], ["champion","冠军","winner","camp"], ["encamp","扎营","set up camp","camp"], ["scamper","蹦跳","run playfully","camp"],
    ["castle","城堡","fortress","cast"], ["chaste","贞洁的","pure","cast"], ["castigate","严惩","scold","cast"], ["chasten","惩戒","discipline","cast"], ["incest","乱伦","forbidden relation","cast"], ["caste","种姓","social class","cast"],
    ["cave","洞穴","hollow","cav"], ["cavity","空腔","hole","cav"], ["excavate","挖掘","dig out","cav"], ["concave","凹的","curved inward","cav"], ["cavern","大洞穴","large cave","cav"], ["cage","笼子","enclosure","cav"],
    ["cell","细胞,牢房","small room","cel"], ["cellar","地窖","basement","cel"], ["conceal","隐藏","hide","cel"], ["cellular","细胞的","of cells","cel"], ["occult","神秘的","hidden","cel"],
    ["accelerate","加速","speed up","celer"], ["celerity","迅速","speed","celer"], ["decelerate","减速","slow down","celer"], ["accelerator","油门","speed control","celer"],
    ["discern","辨别","perceive","cern"], ["concern","关心,涉及","worry; involve","cern"], ["secret","秘密","hidden thing","cern"], ["secretary","秘书","office assistant","cern"], ["discreet","谨慎的","tactful","cern"], ["discrete","离散的","separate","cern"], ["excrete","排泄","expel waste","cern"], ["decree","法令","official order","cern"], ["crisis","危机","turning point","cern"], ["certain","确定的","sure","cern"], ["certificate","证书","official paper","cern"],
    ["chart","图表","diagram","chart"], ["charter","宪章","founding document","chart"], ["card","卡片","stiff paper","chart"], ["cardboard","纸板","thick paper","chart"], ["cartoon","卡通","drawing","chart"], ["cartridge","弹药筒","case","chart"], ["carton","纸盒","box","chart"],
    ["precinct","辖区","district","cinct"], ["succinct","简洁的","brief","cinct"], ["cincture","腰带","belt","cinct"],
    ["circle","圆","ring","circ"], ["circus","马戏团","ring show","circ"], ["circuit","电路,环路","loop","circ"], ["circulate","循环","move around","circ"], ["circular","圆的,传单","round; leaflet","circ"], ["encircle","环绕","surround","circ"],
    ["clear","清楚的","obvious","clar"], ["clarity","清晰","clearness","clar"], ["clarify","澄清","make clear","clar"], ["declare","宣布","state","clar"], ["clarion","嘹亮的","loud and clear","clar"], ["clairvoyant","通灵的","psychic","clar"],
    ["clavicle","锁骨","collarbone","clav"], ["clef","谱号","music sign","clav"], ["conclave","秘密会议","private meeting","clav"], ["enclave","飞地","enclosed territory","clav"], ["close","关闭,近的","shut; near","clav"], ["closet","壁橱","cupboard","clav"],
    ["copious","丰富的","abundant","cop"], ["copy","复制","duplicate","cop"], ["cornucopia","丰饶角","horn of plenty","cop"],
    ["crown","王冠","royal headpiece","coron"], ["coronation","加冕","crowning","coron"], ["corona","日冕,冠状","halo","coron"], ["coroner","验尸官","death investigator","coron"], ["coronary","冠状动脉的","of the heart arteries","coron"],
    ["crime","犯罪","offence","crim"], ["criminal","罪犯","offender","crim"], ["discriminate","歧视,区分","treat differently; distinguish","crim"], ["incriminate","牵连","implicate","crim"], ["recrimination","反责","counter-accusation","crim"],
    ["crucial","关键的","decisive","cruc"], ["crucify","钉十字架","execute on a cross","cruc"], ["cross","十字,穿过","X shape; go across","cruc"], ["crusade","十字军","holy war","cruc"], ["excruciating","极痛苦的","agonizing","cruc"], ["crux","关键","central point","cruc"],
    ["culpable","有罪的","blameworthy","culp"], ["culprit","罪犯","guilty one","culp"], ["exculpate","开脱","clear of blame","culp"], ["inculpate","归罪","accuse","culp"],
    ["cumulative","累积的","increasing","cumul"], ["accumulate","积累","gather","cumul"], ["cumulus","积云","heaped cloud","cumul"],
    ["custody","监护","guardianship","cust"], ["custodian","看管人","caretaker","cust"],
    ["damage","损害","harm","dam"], ["condemn","谴责","denounce","dam"], ["indemnity","赔偿","compensation","dam"], ["damn","诅咒","curse","dam"],
    ["decent","得体的","proper","dec"], ["decorate","装饰","adorn","dec"], ["decorum","礼节","propriety","dec"], ["decor","装潢","decoration","dec"], ["indecent","不雅的","improper","dec"],
    ["deity","神","god","dei"], ["divine","神圣的","godly","dei"], ["divinity","神性","godhood","dei"], ["deify","神化","make a god","dei"], ["divination","占卜","fortune-telling","dei"],
    ["dense","密集的","thick","dens"], ["density","密度","thickness","dens"], ["condense","浓缩","compress","dens"], ["condensation","冷凝","liquid droplets","dens"],
    ["dexterity","灵巧","skill","dexter"], ["dexterous","灵巧的","skilful","dexter"], ["ambidextrous","双手灵巧的","using both hands","dexter"],
    ["digit","数字,手指","number; finger","digit"], ["digital","数字的","electronic","digit"], ["digitize","数字化","convert to digital","digit"],
    ["dolorous","悲伤的","sorrowful","dol"], ["condolence","慰问","sympathy","dol"], ["indolent","懒惰的","lazy","dol"], ["doleful","悲哀的","mournful","dol"],
    ["dual","双重的","twofold","du"], ["duel","决斗","fight between two","du"], ["duet","二重唱","piece for two","du"], ["duplex","双层的","two-part","du"], ["duplicity","欺骗","deceit","du"], ["dozen","一打","twelve","du"],
    ["eminent","杰出的","distinguished","emin"], ["prominent","显著的","noticeable","emin"], ["imminent","即将的","about to happen","emin"], ["eminence","显赫","distinction","emin"],
    ["fame","名声","renown","fam"], ["famous","著名的","well-known","fam"], ["infamous","臭名昭著的","notorious","fam"], ["defame","诽谤","slander","fam"], ["infamy","恶名","disgrace","fam"],
    ["filament","细丝","thin wire","fil"], ["file","文件,锉","folder; tool","fil"], ["profile","轮廓","outline","fil"], ["fillet","肉片","boneless cut","fil"], ["defile","玷污","pollute","fil"],
    ["firm","坚固的,公司","solid; company","firm"], ["confirm","确认","verify","firm"], ["affirm","肯定","assert","firm"], ["infirm","虚弱的","weak","firm"], ["infirmary","医务室","sick bay","firm"], ["firmament","苍穹","sky","firm"],
    ["flame","火焰","fire","flam"], ["inflammable","易燃的","flammable","flam"], ["inflammation","炎症","swelling","flam"], ["flagrant","公然的","blatant","flam"], ["conflagration","大火","huge fire","flam"], ["flamboyant","炫耀的","showy","flam"],
    ["fiscal","财政的","of public money","fisc"], ["confiscate","没收","seize","fisc"],
    ["focus","焦点","center of attention","foc"], ["focal","焦点的","central","foc"], ["fuel","燃料","energy source","foc"],
    ["front","前面","face","front"], ["confront","面对","face","front"], ["affront","冒犯","insult","front"], ["frontier","边境","border","front"], ["effrontery","厚颜","boldness","front"], ["frontal","正面的","from the front","front"],
    ["fruit","水果","edible produce","fruct"], ["fructose","果糖","fruit sugar","fruct"], ["frugal","节俭的","thrifty","fruct"], ["fruitful","多产的","productive","fruct"], ["fruition","实现","fulfilment","fruct"],
    ["gelatin","明胶","jelly substance","gel"], ["congeal","凝结","solidify","gel"], ["jelly","果冻","soft sweet","gel"], ["gel","凝胶","semi-solid","gel"], ["glacier","冰川","ice river","gel"],
    ["grand","宏伟的","magnificent","grand"], ["grandeur","壮丽","splendour","grand"], ["aggrandize","扩大","increase power","grand"], ["grandiose","浮夸的","overly grand","grand"], ["grandparent","祖父母","parent's parent","grand"],
    ["heredity","遗传","inheritance of traits","hered"], ["hereditary","遗传的","inherited","hered"], ["heir","继承人","inheritor","hered"], ["inherit","继承","receive from ancestors","hered"], ["heritage","遗产","inheritance","hered"],
    ["horror","恐怖","terror","hor"], ["horrid","可怕的","dreadful","hor"], ["horrible","可怕的","terrible","hor"], ["abhor","憎恶","detest","hor"], ["horrify","使恐惧","shock","hor"],
    ["insular","孤立的","narrow-minded","insul"], ["peninsula","半岛","almost-island","insul"], ["isolate","隔离","set apart","insul"], ["insulate","绝缘","protect from heat/cold","insul"], ["island","岛","land in water","insul"],
    ["irate","愤怒的","angry","ir"], ["irascible","易怒的","hot-tempered","ir"], ["ire","怒火","anger","ir"],
    ["lavatory","洗手间","toilet","lav"], ["lavish","慷慨的","generous","lav"], ["launder","洗涤","wash clothes","lav"], ["deluge","洪水","flood","lav"], ["dilute","稀释","water down","lav"], ["ablution","沐浴","washing","lav"], ["lotion","乳液","skin liquid","lav"],
    ["deliberate","故意的","intentional","lib"], ["equilibrium","平衡","balance","lib"], ["libra","天秤座","the scales","lib"],
    ["limit","限制","boundary","lim"], ["eliminate","消除","remove","lim"], ["preliminary","初步的","introductory","lim"], ["sublime","崇高的","awe-inspiring","lim"], ["subliminal","潜意识的","below awareness","lim"], ["unlimited","无限的","without limit","lim"],
    ["line","线","long mark","lin"], ["linear","线性的","in a line","lin"], ["lineage","血统","ancestry","lin"], ["delineate","描绘","outline","lin"], ["outline","轮廓","summary","lin"], ["linen","亚麻布","flax cloth","lin"],
    ["lunar","月球的","of the moon","lun"], ["lunatic","疯子","mad person","lun"], ["lunacy","疯狂","madness","lun"],
    ["mandate","授权","official order","mand"], ["command","命令","order","mand"], ["demand","要求","insist on","mand"], ["recommend","推荐","suggest","mand"], ["commend","称赞","praise","mand"], ["mandatory","强制的","compulsory","mand"], ["countermand","撤销命令","cancel an order","mand"],
    ["mature","成熟的","fully grown","matur"], ["premature","过早的","too early","matur"], ["immature","不成熟的","childish","matur"], ["maturity","成熟","adulthood","matur"],
    ["member","成员","part of a group","memb"], ["membrane","膜","thin layer","memb"], ["dismember","肢解","tear apart","memb"], ["remember","记得","recall","memb"],
    ["mole","鼹鼠,痣","burrowing animal; skin spot","mol"], ["demolish","拆除","destroy","mol"], ["molecule","分子","tiny particle","mol"], ["molar","臼齿","grinding tooth","mol"], ["mill","磨坊","grinding building","mol"],
    ["moral","道德的","ethical","mor"], ["morale","士气","spirit","mor"], ["morality","道德","ethics","mor"], ["immoral","不道德的","wicked","mor"], ["morose","阴郁的","gloomy","mor"], ["mores","习俗","customs","mor"],
    ["nerve","神经","fibre; courage","nerv"], ["nervous","紧张的","anxious","nerv"], ["enervate","使衰弱","weaken","nerv"], ["unnerve","使不安","frighten","nerv"],
    ["nocturnal","夜间的","active at night","noct"], ["equinox","昼夜平分点","equal day and night","noct"], ["nocturne","夜曲","night piece","noct"],
    ["announce","宣布","declare","nunc"], ["pronounce","发音","say aloud","nunc"], ["renounce","放弃","give up","nunc"], ["denounce","谴责","condemn","nunc"], ["enunciate","清晰发音","speak clearly","nunc"], ["nuncio","教廷大使","papal envoy","nunc"],
    ["octave","八度","eight-note interval","oct"], ["October","十月","tenth month","oct"], ["octopus","章鱼","eight-armed animal","oct"], ["octagon","八边形","eight-sided shape","oct"],
    ["olfactory","嗅觉的","of smell","ol"], ["odor","气味","smell","ol"], ["redolent","芳香的","fragrant","ol"], ["deodorant","除臭剂","odour remover","ol"],
    ["orbit","轨道","circular path","orb"], ["orb","球体","sphere","orb"], ["exorbitant","过高的","excessive","orb"], ["orbital","轨道的","of an orbit","orb"],
    ["oval","椭圆的","egg-shaped","ov"], ["ovary","卵巢","egg organ","ov"], ["ovum","卵子","egg cell","ov"],
    ["pale","苍白的","whitish","pal"], ["pallid","苍白的","pale","pal"], ["appall","使震惊","horrify","pal"], ["pallor","苍白","paleness","pal"],
    ["paucity","缺乏","scarcity","pauc"], ["pauper","穷人","poor person","pauc"], ["poverty","贫穷","being poor","pauc"], ["poor","穷的","lacking money","pauc"], ["impoverish","使贫穷","make poor","pauc"],
    ["impeccable","无可挑剔的","flawless","pecc"], ["peccadillo","小过失","minor fault","pecc"],
    ["pile","堆","heap","pil"], ["compile","汇编","gather","pil"], ["pillar","柱子","column","pil"], ["caterpillar","毛毛虫","larva","pil"],
    ["plan","计划","scheme","plan"], ["plane","平面,飞机","flat surface; aircraft","plan"], ["plain","平原,朴素的","flat land; simple","plan"], ["explain","解释","make clear","plan"], ["esplanade","广场","open walkway","plan"], ["planet","行星","wandering star","plan"],
    ["plate","盘子","flat dish","plat"], ["plateau","高原","flat highland","plat"], ["platform","平台","raised stage","plat"], ["platitude","陈词滥调","cliché","plat"], ["plaza","广场","public square","plat"],
    ["plebeian","平民的","common","pleb"], ["plebiscite","公民投票","popular vote","pleb"],
    ["deplore","谴责","regret strongly","plor"], ["explore","探索","investigate","plor"], ["implore","恳求","beg","plor"], ["deplorable","可悲的","shameful","plor"],
    ["plumber","水管工","pipe worker","plumb"], ["plummet","暴跌","fall sharply","plumb"], ["plumb","垂直的","exactly vertical","plumb"], ["aplomb","沉着","self-confidence","plumb"],
    ["precious","珍贵的","valuable","prec2"], ["appreciate","感激,欣赏","value; be grateful","prec2"], ["price","价格","cost","prec2"], ["praise","赞扬","commend","prec2"], ["depreciate","贬值","lose value","prec2"], ["appraise","评估","assess","prec2"],
    ["predator","捕食者","hunter animal","pred"], ["prey","猎物","hunted animal","pred"], ["depredation","掠夺","plundering","pred"], ["predatory","掠夺性的","preying","pred"],
    ["proper","恰当的","suitable","propr"], ["property","财产","possessions","propr"], ["appropriate","合适的,挪用","suitable; take","propr"], ["proprietor","业主","owner","propr"], ["propriety","得体","correctness","propr"], ["expropriate","征用","take from owner","propr"],
    ["proximity","接近","nearness","prox"], ["approximate","近似的","close to","prox"], ["approach","接近","come near","prox"], ["reproach","责备","blame","prox"], ["proxy","代理","substitute","prox"],
    ["impudent","无礼的","cheeky","pud"], ["repudiate","否认","reject","pud"], ["pudency","羞怯","modesty","pud"],
    ["quadrant","象限","quarter of a circle","quadr"], ["quarter","四分之一","one fourth","quadr"], ["squad","小队","small group","quadr"], ["square","正方形","four-sided shape","quadr"], ["quadruple","四倍","four times","quadr"], ["quarantine","隔离","isolation period","quadr"],
    ["quiet","安静的","silent","quies"], ["acquiesce","默许","accept reluctantly","quies"], ["requiem","安魂曲","mass for the dead","quies"], ["tranquil","宁静的","calm","quies"], ["quit","退出","leave","quies"], ["quite","相当","fairly","quies"],
    ["quota","配额","share","quot"], ["quotient","商","division result","quot"], ["quote","引用","repeat words","quot"], ["quotidian","日常的","everyday","quot"],
    ["rare","稀有的","uncommon","rar"], ["rarity","稀有","scarcity","rar"], ["rarefy","稀薄化","make less dense","rar"],
    ["rigid","僵硬的","stiff","rig"], ["rigor","严格","strictness","rig"], ["rigorous","严谨的","thorough","rig"],
    ["river","河","stream","riv"], ["rival","对手","competitor","riv"], ["derive","源自","obtain from","riv"], ["arrive","到达","reach","riv"], ["riparian","河岸的","of a riverbank","riv"],
    ["robust","强健的","sturdy","rob"], ["corroborate","证实","confirm","rob"],
    ["rude","粗鲁的","impolite","rud"], ["erudite","博学的","learned","rud"], ["rudiment","基础","basic element","rud"], ["rudimentary","初步的","basic","rud"],
    ["scrutiny","细查","close examination","scrut"], ["scrutinize","仔细检查","examine closely","scrut"], ["inscrutable","难以理解的","mysterious","scrut"],
    ["September","九月","ninth month","sept"], ["septet","七重奏","group of seven","sept"], ["septuagenarian","七旬老人","person in their 70s","sept"],
    ["series","系列","sequence","ser"], ["insert","插入","put in","ser"], ["desert","沙漠,抛弃","wasteland; abandon","ser"], ["exert","施加","apply","ser"], ["assert","断言","state firmly","ser"], ["dissertation","论文","thesis","ser"], ["sermon","布道","religious talk","ser"], ["serial","连续的","in a series","ser"],
    ["consider","考虑","think about","sid"], ["desire","渴望","wish for","sid"], ["sidereal","恒星的","of the stars","sid"], ["considerable","相当大的","large","sid"],
    ["single","单个的","one only","sing"], ["singular","单数的,非凡的","one; remarkable","sing"], ["singularity","奇点","uniqueness","sing"],
    ["sinuous","蜿蜒的","winding","sinu"], ["insinuate","暗示","hint","sinu"], ["sinus","鼻窦","cavity","sinu"],
    ["solid","固体","firm","solid"], ["consolidate","巩固","strengthen","solid"], ["solder","焊接","join metal","solid"], ["soldier","士兵","army member","solid"], ["solidarity","团结","unity","solid"],
    ["absorb","吸收","soak up","sorb"], ["absorbent","吸水的","soaking up","sorb"], ["adsorb","吸附","hold on surface","sorb"],
    ["prosper","繁荣","thrive","sper"], ["desperate","绝望的","hopeless","sper"], ["despair","绝望","loss of hope","sper"], ["prosperity","繁荣","wealth","sper"],
    ["splendid","极好的","magnificent","splend"], ["splendor","光辉","brilliance","splend"], ["resplendent","灿烂的","shining","splend"],
    ["student","学生","learner","stud"], ["study","学习","learn","stud"], ["studio","工作室","artist's room","stud"], ["studious","勤奋的","hardworking","stud"],
    ["persuade","说服","convince","suad"], ["dissuade","劝阻","advise against","suad"], ["suave","圆滑的","charming","suad"], ["persuasive","有说服力的","convincing","suad"],
    ["result","结果","outcome","sult"], ["insult","侮辱","offend","sult"], ["exult","欢欣","rejoice","sult"], ["consult","咨询","ask advice","sult"], ["assault","袭击","attack","sult"], ["somersault","翻筋斗","acrobatic roll","sult"],
    ["talent","天赋","natural ability","tal"], ["retaliate","报复","strike back","tal"], ["tailor","裁缝","clothes maker","tal"], ["retail","零售","selling to consumers","tal"], ["detail","细节","particular","tal"], ["entail","需要","involve","tal"],
    ["tardy","迟到的","late","tard"], ["retard","延迟","slow down","tard"], ["tardiness","迟缓","lateness","tard"],
    ["protect","保护","keep safe","tect"], ["detect","发现","discover","tect"], ["architect","建筑师","building designer","tect"], ["detective","侦探","investigator","tect"], ["protégé","门生","person under protection","tect"],
    ["tenuous","脆弱的","weak","tenu"], ["attenuate","减弱","weaken","tenu"], ["extenuate","减轻","lessen guilt","tenu"], ["thin","薄的","slender","tenu"],
    ["tolerate","容忍","put up with","tol"], ["extol","赞美","praise","tol"], ["toll","通行费","charge","tol"], ["tolerance","宽容","acceptance","tol"], ["intolerable","无法忍受的","unbearable","tol"],
    ["tone","音调","sound quality","ton"], ["intone","吟诵","chant","ton"], ["monotone","单调","one tone","ton"], ["tonic","补药,主音","restorative; key note","ton"], ["atone","赎罪","make amends","ton"],
    ["total","总的","whole","tot"], ["totalitarian","极权的","dictatorial","tot"], ["totality","全部","entirety","tot"],
    ["intrude","闯入","enter uninvited","trud"], ["protrude","突出","stick out","trud"], ["extrude","挤出","force out","trud"], ["abstruse","深奥的","hard to understand","trud"], ["obtrusive","显眼的","intrusive","trud"], ["thrust","推","push hard","trud"],
    ["tumor","肿瘤","abnormal growth","tum"], ["tumult","骚动","uproar","tum"], ["tumid","肿胀的","swollen","tum"], ["contumely","侮辱","insolence","tum"],
    ["unguent","软膏","ointment","ung"], ["ointment","药膏","healing cream","ung"], ["anoint","涂油","smear with oil","ung"],
    ["vapor","蒸气","steam","vap"], ["evaporate","蒸发","turn to vapour","vap"], ["vaporize","汽化","turn into gas","vap"], ["vapid","乏味的","dull","vap"],
    ["vary","变化","change","var"], ["various","各种的","different","var"], ["variety","多样性","diversity","var"], ["variable","可变的","changeable","var"], ["invariable","不变的","constant","var"], ["variant","变体","version","var"],
    ["vehicle","车辆","means of transport","veh"], ["vehement","激烈的","forceful","veh"], ["convey","传达","communicate","veh"], ["convex","凸的","curved outward","veh"], ["vector","矢量","carrier","veh"], ["invective","辱骂","abuse","veh"],
    ["velocity","速度","speed","vel"], ["veil","面纱","covering","vel"], ["reveal","揭示","disclose","vel"], ["revelation","启示","disclosure","vel"], ["unveil","揭幕","uncover","vel"],
    ["verb","动词","action word","verb"], ["verbal","口头的","spoken","verb"], ["proverb","谚语","saying","verb"], ["adverb","副词","modifier word","verb"], ["verbatim","逐字地","word for word","verb"], ["verbose","啰嗦的","wordy","verb"],
    ["verge","边缘","edge","verg"], ["converge","汇聚","come together","verg"], ["diverge","分岔","go apart","verg"], ["divergent","分歧的","differing","verg"],
    ["vicinity","附近","neighbourhood","vic"], ["vicar","牧师","parish priest","vic"], ["vicarious","替代的","experienced through another","vic"], ["vicissitude","变迁","change of fortune","vic"], ["vice versa","反之亦然","the other way round","vic"], ["vice president","副总统","deputy leader","vic"],
    ["vile","卑劣的","despicable","vil"], ["vilify","诽谤","defame","vil"], ["revile","辱骂","abuse","vil"],
    ["vine","藤","climbing plant","vin"], ["wine","酒","grape drink","vin"], ["vinegar","醋","sour liquid","vin"], ["vintage","年份酒,复古","old and fine","vin"], ["vineyard","葡萄园","grape farm","vin"],
    ["vote","投票","cast a ballot","vot"], ["devote","奉献","dedicate","vot"], ["vow","誓言","solemn promise","vot"], ["devout","虔诚的","pious","vot"], ["votary","信徒","devotee","vot"]
  );
})();
