/* =====================================================
   FUGA MYTHICA — CURSUS English 🇬🇧 · batch 3 (band 2000–3000)
   Third wave of Latin roots (academic & news vocabulary) and Greek scientific roots.
   ===================================================== */
(function () {
  const p = VOCAB.en;
  Object.assign(p.roots, {
    agr: ["agr", "田", "field"], ambul: ["ambul", "走", "walk"], apt: ["apt / ept", "合适", "fit"], arbit: ["arbit", "裁判", "judge"],
    cens: ["cens", "评估", "assess"], cert: ["cert", "确定", "sure"], cult: ["col / cult", "耕,培养", "till, cultivate"], cumb: ["cub / cumb", "躺", "lie"],
    dat: ["dat / don", "给", "give"], deb: ["deb / debit", "欠", "owe"], div: ["div / divid", "分", "divide"], dur: ["dur", "硬,持久", "hard, last"],
    ego: ["ego", "我", "I"], empt: ["em / empt", "买", "buy"], ess: ["ess / ent", "存在", "be"], fabr: ["fabr", "制作", "make"],
    fat: ["fa / fat", "说", "speak"], fend: ["fend / fens", "打击", "strike"], fest: ["fest", "节日", "feast"], flor: ["flor", "花", "flower"],
    foli: ["foli", "叶", "leaf"], fum: ["fum", "烟", "smoke"], gest: ["ger / gest", "携带,做", "carry, do"], glob: ["glob", "球", "ball"],
    gran: ["gran", "谷粒", "grain"], grat: ["grat", "感谢,愉快", "thankful, pleasing"], hum: ["hum", "土,人", "earth, human"], ign: ["ign", "火", "fire"],
    imag: ["imag / imit", "像,模仿", "image, imitate"], integr: ["integr", "完整", "whole"], iter: ["iter", "再", "again"], jur: ["jur / jus", "法,誓", "law, swear"],
    lact: ["lact", "奶", "milk"], laps: ["lab / laps", "滑", "slip"], lax: ["lax / leas", "松", "loose"], lig: ["lig / ly", "绑", "bind"],
    lingu: ["lingu", "舌,语", "tongue"], liqu: ["liqu", "液", "liquid"], loqu: ["loqu / locut", "说", "speak"], magist: ["magist", "老师,主", "master"],
    medic: ["med / medic", "治", "heal"], mens: ["mens / metr", "量", "measure"], merc: ["merc", "买卖", "trade"], mir: ["mir", "惊奇", "wonder"],
    misc: ["misc / mix", "混", "mix"], mund: ["mund", "世界", "world"], mun: ["mun", "职责,公共", "duty, public"], mur: ["mur", "墙", "wall"],
    mut: ["mut", "变", "change"], nect: ["nect / nex", "绑", "bind"], nihil: ["nihil / nul", "无", "nothing"], noc: ["noc / nox", "害", "harm"],
    norm: ["norm", "规则", "rule"], numer: ["numer", "数", "number"], nutr: ["nutr", "喂养", "nourish"], oper: ["oper", "工作", "work"],
    or: ["or / orat", "口,说", "mouth, speak"], orn: ["orn", "装饰", "adorn"], pan: ["pan", "面包", "bread"], par: ["par", "相等", "equal"],
    par2: ["par / para", "准备", "prepare"], part: ["part", "部分", "part"], pass: ["pass", "步", "step"], pastor: ["past / pastor", "喂养,牧", "feed, shepherd"],
    pen: ["pen / pun", "罚", "punish"], plaud: ["plaud / plod", "拍手", "clap"], plur: ["plur / plus", "更多", "more"], prec: ["prec", "祈求", "pray"],
    priv: ["priv", "私,夺", "private, deprive"], prud: ["prud / provid", "远见", "foresight"], pugn: ["pugn", "打", "fight"], pur: ["pur / purg", "净", "pure"],
    quer: ["quer / quest", "抱怨", "complain"], radi: ["radi", "光线", "ray"], rap: ["rap / rapt", "抓", "seize"], rot: ["rot", "轮", "wheel"],
    rur: ["rur / rus", "乡村", "country"], san: ["san", "健康", "healthy"], sap: ["sap / sav", "尝,智", "taste, wise"], scind: ["scind / sciss", "切", "cut"],
    sculp: ["sculp", "雕", "carve"], sec: ["sec / sect / seg", "切", "cut"], sen: ["sen", "老", "old"], sever: ["sever", "严厉", "strict"],
    sol2: ["sol", "独", "alone"], somn: ["somn", "睡", "sleep"], sort: ["sort", "命运,类", "lot, kind"], spers: ["sperg / spers", "撒", "scatter"],
    spond: ["spond / spons", "承诺", "pledge"], stimul: ["stimul / sting", "刺", "goad"], string: ["string / strict", "拉紧", "bind tight"], stup: ["stup", "惊呆", "stun"],
    sum: ["sum / sumpt", "拿", "take"], tac: ["tac / tic", "沉默", "silent"], terr2: ["terr", "吓", "frighten"], tex: ["tex / text", "织", "weave"],
    tim: ["tim", "怕", "fear"], ting: ["ting / tinct", "染", "dye"], tox: ["tox", "毒", "poison"], tut: ["tut / tui", "保护", "guard"],
    ult: ["ult / ultim", "最远", "last"], und: ["und", "波", "wave"], ut: ["ut / us", "用", "use"], venat: ["venat", "打猎", "hunt"],
    vest: ["vest", "衣", "clothe"], vol2: ["vol", "飞", "fly"], volv: ["volv / volut", "滚", "roll"], vulner: ["vulner", "伤", "wound"],
    /* Greek batch 3 */ acr: ["acr / acu", "尖,顶", "sharp, top"], aer: ["aer", "空气", "air"], arithm: ["arithm", "数", "number"], bol: ["bol / ball", "扔", "throw"],
    cal: ["cal / calli", "美", "beautiful"], centr: ["centr", "中心", "center"], cephal: ["cephal", "头", "head"], chor: ["chor", "舞,合唱", "dance, chorus"],
    cri: ["cri / crit", "判断", "judge"], dendr: ["dendr", "树", "tree"], dram: ["dram", "行动,剧", "act, drama"], eco: ["eco / oik", "家", "house"],
    electr: ["electr", "电", "electric"], eth: ["eth", "习俗", "custom"], ethn: ["ethn", "民族", "people"], gymn: ["gymn", "裸,体操", "naked, exercise"],
    gyn: ["gyn", "女", "woman"], hepat: ["hepat", "肝", "liver"], hex: ["hex", "六", "six"], hist: ["hist", "组织", "tissue"],
    hod: ["hod / od", "路", "way"], hol: ["hol", "全", "whole"], hor: ["hor", "时", "hour"], icon: ["icon", "像", "image"],
    iso: ["iso", "相等", "equal"], lex: ["lex / lect", "词", "word"], lip: ["lip", "脂", "fat"], mel: ["mel / melod", "歌", "song"],
    mim: ["mim", "模仿", "imitate"], mne: ["mne / mnem", "记忆", "memory"], myth: ["myth", "故事", "story"], narc: ["narc", "麻木", "numb"],
    od: ["od / ode", "歌", "song"], ont: ["ont", "存在", "being"], oste: ["oste", "骨", "bone"], pent: ["pent", "五", "five"],
    petr: ["petr", "石", "rock"], pharm: ["pharm", "药", "drug"], phras: ["phras", "说", "speak"], phren: ["phren", "心,膈", "mind"],
    phyt: ["phyt", "植物", "plant"], plut: ["plut", "财富", "wealth"], poe: ["poe / poie", "做", "make"], pract: ["pract / prag", "做", "do"],
    rhin: ["rhin", "鼻", "nose"], rhythm: ["rhythm / rhe", "流", "flow"], sarc: ["sarc", "肉", "flesh"], scler: ["scler", "硬", "hard"],
    sem: ["sem / semi", "符号", "sign"], som: ["som / somat", "身体", "body"], spor: ["spor", "种子", "seed"], stereo: ["stereo", "立体", "solid"],
    strat: ["strat", "军队,层", "army, layer"], styl: ["styl", "柱,笔", "pillar, pen"], tach: ["tach", "快", "fast"], tetr: ["tetr", "四", "four"],
    thanat: ["thanat", "死", "death"], ther: ["ther", "野兽", "beast"], tyr: ["tyr / tyrann", "暴君", "tyrant"], ur: ["ur", "尿", "urine"],
  });
  p.words.push(
    ["agriculture","农业","field cultivation","agr"], ["agrarian","农业的","of fields","agr"], ["agronomy","农学","field law","agr"], ["peregrine","漫游的","through the field","agr"], ["pilgrim","朝圣者","one across fields","agr"],
    ["ambulance","救护车","walking hospital","ambul"], ["amble","漫步","stroll","ambul"], ["preamble","序言","introduction","ambul"], ["somnambulist","梦游者","sleep-walker","ambul"], ["perambulate","漫步","stroll","ambul"],
    ["apt","恰当的","fit","apt"], ["adapt","适应","adjust","apt"], ["aptitude","天资","fitness","apt"], ["inept","无能的","unfit","apt"], ["adept","熟练的","attained","apt"],
    ["arbiter","仲裁者","judge","arbit"], ["arbitrary","武断的","by judgment alone","arbit"], ["arbitrate","仲裁","settle a dispute","arbit"], ["arbitration","仲裁","judging","arbit"],
    ["census","人口普查","assessment","cens"], ["censor","审查","assessor","cens"], ["censure","谴责","judgment","cens"], ["recension","校订","reassessment","cens"],
    ["certain","确定的","sure","cert"], ["certify","证明","confirm officially","cert"], ["certificate","证书","sure-making paper","cert"], ["ascertain","查明","find out","cert"], ["concert","音乐会,协同","musical performance","cert"],
    ["culture","文化","cultivation","cult"], ["cultivate","培养","till","cult"], ["agriculture","农业","field tilling","cult"], ["colony","殖民地","tilled settlement","cult"], ["cult","邪教,崇拜","worship","cult"], ["horticulture","园艺","garden tilling","cult"],
    ["incumbent","现任的","current holder","cumb"], ["succumb","屈服","give in","cumb"], ["recumbent","躺着的","lying down","cumb"], ["incubate","孵化","hatch, develop","cumb"], ["cubicle","隔间","little bedroom","cumb"],
    ["data","数据","facts, figures","dat"], ["date","日期","calendar day","dat"], ["donation","捐赠","giving","dat"], ["edit","编辑","revise text","dat"], ["tradition","传统","custom","dat"], ["render","呈现,给予","provide; depict","dat"], ["surrender","投降","give up","dat"], ["add","加","join to","dat"],
    ["debt","债务","money owed","deb"], ["debit","借记","owed","deb"], ["due","应付的","owed","deb"], ["duty","责任","obligation","deb"], ["indebted","负债的","owing","deb"],
    ["divide","分","split","div"], ["dividend","红利","profit share","div"], ["individual","个人","not divisible","div"], ["division","分割","dividing","div"], ["devise","设计","invent","div"], ["device","装置","plan","div"],
    ["durable","耐用的","lasting","dur"], ["endure","忍受","harden","dur"], ["duration","持续时间","lasting","dur"], ["obdurate","顽固的","hardened","dur"], ["during","在…期间","lasting","dur"],
    ["ego","自我","I","ego"], ["egoist","自我主义者","I-person","ego"], ["egocentric","自我中心的","I-centered","ego"], ["alter ego","第二自我","other I","ego"],
    ["exempt","免除的","excused","empt"], ["redeem","赎回","buy back; save","empt"], ["preempt","先占","forestall","empt"], ["ransom","赎金","release payment","empt"], ["premium","保费,优质","reward","empt"],
    ["essence","本质","being","ess"], ["essential","必要的","necessary","ess"], ["entity","实体","a being","ess"], ["present","在场的","here; gift","ess"], ["absent","缺席的","not here","ess"], ["interest","兴趣","curiosity; profit","ess"],
    ["fabric","织物","cloth","fabr"], ["fabricate","捏造,制造","make up","fabr"], ["prefabricated","预制的","built in advance","fabr"], ["forge","锻造","workshop","fabr"],
    ["fate","命运","destiny","fat"], ["fatal","致命的","of fate","fat"], ["infant","婴儿","not speaking","fat"], ["fable","寓言","story told","fat"], ["fame","名声","talk","fat"], ["affable","和蔼的","friendly","fat"], ["ineffable","难以言喻的","unspeakable","fat"], ["preface","前言","introduction","fat"], ["confess","承认","admit","fat"], ["profess","声称","declare","fat"],
    ["defend","保卫","protect","fend"], ["offend","冒犯","upset","fend"], ["fence","栅栏","defence","fend"], ["offensive","冒犯的,进攻","insulting; attack","fend"], ["fend","抵挡","ward off","fend"],
    ["festival","节日","feast day","fest"], ["festive","喜庆的","of a feast","fest"], ["feast","盛宴","festival","fest"], ["fiesta","节日","feast","fest"],
    ["flower","花","bloom","flor"], ["flourish","繁荣","bloom","flor"], ["florist","花商","flower seller","flor"], ["flora","植物群","goddess of flowers","flor"], ["floral","花的","of flowers","flor"], ["Florida","佛罗里达","flowery","flor"],
    ["foliage","树叶","leaves","foli"], ["portfolio","作品集","leaf carrier","foli"], ["folio","对开本","leaf","foli"], ["exfoliate","去角质","strip leaves","foli"],
    ["fume","烟,发怒","smoke","fum"], ["perfume","香水","scent","fum"], ["fumigate","熏蒸","disinfect with smoke","fum"],
    ["gesture","手势","carrying (of body)","gest"], ["digest","消化","break down food","gest"], ["suggest","建议","propose","gest"], ["congestion","拥堵","overcrowding","gest"], ["register","登记","official list","gest"], ["gestation","妊娠","carrying","gest"], ["exaggerate","夸张","overstate","gest"],
    ["globe","地球","ball","glob"], ["global","全球的","worldwide","glob"], ["globule","小球","little ball","glob"], ["conglomerate","联合企业","corporate group","glob"],
    ["grain","谷物","seed","gran"], ["granary","谷仓","grain store","gran"], ["granule","颗粒","little grain","gran"], ["granite","花岗岩","grained rock","gran"], ["pomegranate","石榴","seedy apple","gran"],
    ["grateful","感激的","full of thanks","grat"], ["gratitude","感激","thankfulness","grat"], ["gratify","使满足","please","grat"], ["congratulate","祝贺","praise for success","grat"], ["ingratiate","讨好","bring into favor","grat"], ["gratis","免费","for thanks","grat"], ["grace","优雅,恩典","favor","grat"], ["agree","同意","consent","grat"],
    ["human","人","person","hum"], ["humble","谦逊的","low to the ground","hum"], ["humility","谦卑","lowliness","hum"], ["humiliate","羞辱","bring low","hum"], ["exhume","挖出","dig up","hum"], ["posthumous","死后的","after burial","hum"],
    ["ignite","点燃","set fire","ign"], ["ignition","点火","setting fire","ign"], ["igneous","火成的","of fire","ign"],
    ["image","图像","likeness","imag"], ["imagine","想象","form an image","imag"], ["imitate","模仿","copy","imag"], ["imagery","意象","images","imag"],
    ["integer","整数","whole","integr"], ["integrity","诚信","wholeness","integr"], ["integrate","整合","combine into a whole","integr"], ["disintegrate","瓦解","unmake whole","integr"], ["entire","整个的","whole","integr"],
    ["iterate","迭代","repeat","iter"], ["reiterate","重申","repeat again","iter"], ["iteration","迭代","repetition","iter"],
    ["jury","陪审团","sworn ones","jur"], ["perjury","伪证","lying under oath","jur"], ["jurisdiction","管辖权","law-saying","jur"], ["injury","伤害","wrong","jur"], ["conjure","召唤","summon magically","jur"], ["abjure","发誓放弃","renounce","jur"], ["juror","陪审员","jury member","jur"],
    ["lactose","乳糖","milk sugar","lact"], ["lactate","泌乳","produce milk","lact"], ["lettuce","生菜","milky plant","lact"],
    ["lapse","失误,流逝","slip","laps"], ["collapse","倒塌","fall down","laps"], ["relapse","复发","fall ill again","laps"], ["elapse","流逝","pass (time)","laps"],
    ["relax","放松","rest","lax"], ["release","释放","set free","lax"], ["lax","松懈的","loose","lax"], ["laxative","泻药","loosener","lax"],
    ["ligament","韧带","binder","lig"], ["oblige","迫使","require","lig"], ["religion","宗教","faith system","lig"], ["ally","盟友","partner","lig"], ["rely","依赖","depend","lig"], ["liable","有责任的","bindable","lig"], ["league","联盟","binding","lig"],
    ["language","语言","tongue","lingu"], ["linguist","语言学家","tongue expert","lingu"], ["bilingual","双语的","two tongues","lingu"], ["linguine","扁面条","little tongues","lingu"],
    ["liquid","液体","fluid","liqu"], ["liquor","烈酒","liquid","liqu"], ["liquidate","清算","wind up a business","liqu"], ["liquefy","液化","turn to liquid","liqu"],
    ["eloquent","雄辩的","well-spoken","loqu"], ["colloquial","口语的","informal","loqu"], ["soliloquy","独白","speaking alone","loqu"], ["loquacious","健谈的","talkative","loqu"], ["circumlocution","迂回说法","roundabout wording","loqu"], ["ventriloquist","腹语者","belly speaker","loqu"], ["elocution","演讲术","public speaking skill","loqu"],
    ["magistrate","地方法官","master official","magist"], ["master","主人","greater one","magist"], ["magisterial","权威的","masterly","magist"],
    ["medicine","医学","healing","medic"], ["medical","医学的","of healing","medic"], ["remedy","补救","heal again","medic"], ["medication","药物","healing","medic"],
    ["measure","测量","measuring","mens"], ["dimension","维度","measurement","mens"], ["immense","巨大的","unmeasurable","mens"], ["commensurate","相称的","proportionate","mens"],
    ["merchant","商人","trader","merc"], ["commerce","商业","trade","merc"], ["mercenary","雇佣兵","paid one","merc"], ["market","市场","trading place","merc"], ["merchandise","商品","goods","merc"], ["mercy","仁慈","reward","merc"],
    ["miracle","奇迹","wonder","mir"], ["admire","钦佩","wonder at","mir"], ["mirror","镜子","wonder-glass","mir"], ["mirage","海市蜃楼","wonder-sight","mir"], ["marvel","惊奇","wonder","mir"],
    ["mix","混合","mingle","misc"], ["miscellaneous","混杂的","mixed","misc"], ["promiscuous","混杂的","indiscriminate","misc"], ["mixture","混合物","mixing","misc"],
    ["mundane","世俗的","ordinary","mund"], ["extramundane","世外的","beyond the world","mund"],
    ["municipal","市政的","of a town","mun"], ["community","社区","shared duty","mun"], ["communicate","交流","share","mun"], ["immune","免疫的","free from duty","mun"], ["remunerate","报酬","reward","mun"], ["common","共同的","shared duty","mun"],
    ["mural","壁画","wall painting","mur"], ["immure","禁闭","imprison","mur"], ["intramural","校内的","within walls","mur"],
    ["mutate","突变","change","mut"], ["mutual","相互的","exchanged","mut"], ["commute","通勤","travel to work","mut"], ["immutable","不变的","unchangeable","mut"], ["permutation","排列","thorough change","mut"],
    ["connect","连接","link","nect"], ["annex","附加","add territory","nect"], ["nexus","联结","binding","nect"],
    ["nihilism","虚无主义","nothing-ism","nihil"], ["annihilate","消灭","destroy completely","nihil"], ["null","无效的","none","nihil"], ["nullify","使无效","cancel","nihil"],
    ["innocent","无辜的","not harming","noc"], ["noxious","有害的","harmful","noc"], ["obnoxious","讨厌的","exposed to harm","noc"], ["innocuous","无害的","not harmful","noc"],
    ["normal","正常的","by rule","norm"], ["enormous","巨大的","out of rule","norm"], ["abnormal","异常的","away from rule","norm"], ["norm","标准","rule","norm"],
    ["number","数","count","numer"], ["numerous","众多的","many","numer"], ["enumerate","列举","list","numer"], ["numeral","数字","of number","numer"], ["innumerable","无数的","uncountable","numer"],
    ["nutrition","营养","nourishing","nutr"], ["nurture","养育","nourish","nutr"], ["nurse","护士","nourisher","nutr"], ["nutrient","养分","nourishing substance","nutr"],
    ["operate","操作","work","oper"], ["cooperate","合作","work together","oper"], ["opera","歌剧","work","oper"], ["opus","作品","work","oper"], ["operation","操作,手术","working","oper"],
    ["oral","口头的","of the mouth","or"], ["orator","演说家","speaker","or"], ["oracle","神谕","divine speech","or"], ["adore","崇拜","love deeply","or"], ["inexorable","不可阻挡的","not to be moved by prayer","or"],
    ["ornament","装饰","adornment","orn"], ["adorn","装饰","add ornament","orn"], ["ornate","华丽的","adorned","orn"], ["suborn","收买","furnish secretly","orn"],
    ["pantry","食品储藏室","bread room","pan"], ["companion","同伴","bread-sharer","pan"], ["company","公司,陪伴","firm; companionship","pan"], ["accompany","陪伴","go along with","pan"],
    ["par","标准","equal","par"], ["parity","平等","equality","par"], ["compare","比较","examine similarities","par"], ["peer","同辈","equal","par"], ["disparity","差异","inequality","par"], ["pair","一对","equals","par"],
    ["prepare","准备","get ready","par2"], ["repair","修理","fix","par2"], ["apparatus","仪器","equipment","par2"], ["separate","分开","divide","par2"], ["parade","游行","preparation","par2"], ["irreparable","无法修复的","not repairable","par2"],
    ["particle","粒子","little part","part"], ["partial","部分的","of a part","part"], ["participate","参与","take part","part"], ["particular","特别的","of a small part","part"], ["partition","分隔","dividing","part"], ["impart","传授","give","part"], ["depart","离开","leave","part"], ["apartment","公寓","flat","part"], ["party","聚会,党","part","part"],
    ["passage","通道","corridor; excerpt","pass"], ["passenger","乘客","passer","pass"], ["surpass","超越","exceed","pass"], ["trespass","侵入","enter unlawfully","pass"], ["compass","罗盘","direction finder","pass"], ["pace","步伐","speed of walking","pass"], ["impasse","僵局","no passage","pass"],
    ["pastor","牧师","shepherd","pastor"], ["pasture","牧场","feeding ground","pastor"], ["pastoral","田园的","of shepherds","pastor"], ["repast","餐","feeding","pastor"], ["antipasto","开胃菜","before the meal","pastor"],
    ["penalty","惩罚","punishment","pen"], ["penal","刑事的","of punishment","pen"], ["punish","惩罚","penalize","pen"], ["impunity","免罚","without punishment","pen"], ["repent","悔改","punish oneself","pen"], ["penitent","忏悔的","repenting","pen"],
    ["applaud","鼓掌","clap","plaud"], ["plausible","貌似合理的","worth applause","plaud"], ["explode","爆炸","clap off stage","plaud"], ["implode","内爆","burst inward","plaud"],
    ["plural","复数的","more","plur"], ["plus","加","more","plur"], ["surplus","剩余","over-more","plur"], ["nonplus","使困惑","no more","plur"],
    ["pray","祈祷","ask","prec"], ["precarious","不稳的","obtained by prayer","prec"], ["deprecate","反对","disapprove of","prec"], ["imprecation","诅咒","curse","prec"],
    ["private","私人的","personal","priv"], ["privacy","隐私","being private","priv"], ["deprive","剥夺","take away from","priv"], ["privilege","特权","private law","priv"], ["privy","知情的","private","priv"],
    ["prudent","谨慎的","foreseeing","prud"], ["jurisprudence","法理学","law-foresight","prud"], ["imprudent","轻率的","not foreseeing","prud"], ["providence","天意","foresight","prud"],
    ["pugnacious","好斗的","fighting","pugn"], ["impugn","质疑","challenge","pugn"], ["repugnant","令人反感的","disgusting","pugn"], ["pugilist","拳击手","fighter","pugn"],
    ["pure","纯的","clean","pur"], ["purify","净化","cleanse","pur"], ["purge","清洗","cleanse","pur"], ["puritan","清教徒","purity-seeker","pur"], ["expurgate","删改","censor","pur"],
    ["quarrel","争吵","complaint","quer"], ["querulous","爱抱怨的","complaining","quer"], ["query","询问","complaint, question","quer"],
    ["radiate","辐射","emit rays","radi"], ["radius","半径","ray","radi"], ["radio","无线电","rays","radi"], ["radiant","光芒四射的","shining","radi"], ["irradiate","照射","expose to radiation","radi"],
    ["rapid","快速的","seizing","rap"], ["rapture","狂喜","seized","rap"], ["rapacious","贪婪的","seizing","rap"], ["ravenous","饥饿的","seizing","rap"], ["surreptitious","偷偷的","seized secretly","rap"],
    ["rotate","旋转","wheel","rot"], ["rotation","旋转","wheeling","rot"], ["rotary","旋转的","wheel-like","rot"], ["rotund","圆胖的","round","rot"], ["control","控制","command","rot"], ["enroll","登记","register","rot"],
    ["rural","乡村的","of the country","rur"], ["rustic","乡土的","of the country","rur"],
    ["sane","理智的","healthy","san"], ["sanitary","卫生的","of health","san"], ["insane","疯狂的","unhealthy","san"], ["sanitation","卫生设施","health measures","san"], ["sanatorium","疗养院","health clinic","san"],
    ["savor","品味","taste","sap"], ["sapient","智慧的","wise","sap"], ["insipid","乏味的","tasteless","sap"], ["homo sapiens","智人","wise human","sap"], ["savant","学者","wise one","sap"],
    ["rescind","废除","cancel","scind"], ["scissors","剪刀","cutters","scind"], ["schism","分裂","split","scind"],
    ["sculpture","雕塑","carving","sculp"], ["sculptor","雕塑家","carver","sculp"], ["sculpt","雕刻","carve","sculp"],
    ["section","部分","cutting","sec"], ["sector","部门","division","sec"], ["insect","昆虫","bug","sec"], ["dissect","解剖","cut up for study","sec"], ["bisect","二等分","halve","sec"], ["intersect","相交","cross","sec"], ["segment","段","section","sec"], ["secant","割线","cutting","sec"],
    ["senior","年长的","older","sen"], ["senate","参议院","council of elders","sen"], ["senile","衰老的","old","sen"], ["sire","父亲,陛下","elder","sen"], ["señor","先生","elder","sen"],
    ["severe","严厉的","strict","sever"], ["persevere","坚持","keep trying","sever"], ["severity","严重性","strictness","sever"], ["asseverate","断言","affirm strictly","sever"],
    ["solo","独奏","alone","sol2"], ["solitude","独处","aloneness","sol2"], ["solitary","孤独的","alone","sol2"], ["desolate","荒凉的","left alone","sol2"], ["sole","唯一的","alone","sol2"], ["soliloquy","独白","speaking alone","sol2"],
    ["insomnia","失眠","no sleep","somn"], ["somnolent","昏昏欲睡的","sleepy","somn"], ["somnambulism","梦游","sleep-walking","somn"],
    ["sort","种类","lot","sort"], ["assort","分类","classify","sort"], ["consort","配偶","sharer of lot","sort"], ["sorcerer","巫师","lot-caster","sort"],
    ["disperse","驱散","scatter","spers"], ["intersperse","散布","scatter among","spers"], ["sparse","稀疏的","scattered","spers"], ["aspersion","诽谤","slander","spers"],
    ["sponsor","赞助者","pledger","spond"], ["respond","回应","answer","spond"], ["correspond","符合,通信","match; exchange letters","spond"], ["spouse","配偶","pledged one","spond"], ["despondent","沮丧的","hopeless","spond"], ["responsible","负责的","answerable","spond"],
    ["stimulate","刺激","excite","stimul"], ["stimulus","刺激物","trigger","stimul"], ["sting","刺","prick painfully","stimul"], ["instigate","煽动","provoke","stimul"], ["distinguish","区分","tell apart","stimul"], ["extinguish","熄灭","put out","stimul"], ["instinct","本能","inner prick","stimul"],
    ["strict","严格的","tight","string"], ["restrict","限制","limit","string"], ["district","地区","area","string"], ["constrict","收缩","narrow","string"], ["stringent","严格的","binding","string"], ["strain","拉紧","tighten","string"], ["restrain","克制","hold back","string"], ["constrain","强迫","limit","string"], ["prestige","威望","binding illusion","string"],
    ["stupid","愚蠢的","stunned","stup"], ["stupendous","惊人的","stunning","stup"], ["stupor","昏迷","stunned state","stup"], ["stupefy","使惊呆","astonish","stup"],
    ["assume","假定,承担","suppose; take on","sum"], ["consume","消耗","use up","sum"], ["presume","推测","suppose","sum"], ["resume","恢复","continue","sum"], ["sumptuous","奢华的","costly","sum"], ["subsume","归入","include within","sum"],
    ["tacit","默契的","silent","tac"], ["taciturn","沉默寡言的","silent","tac"], ["reticent","缄默的","keeping silent","tac"],
    ["terror","恐怖","fright","terr2"], ["terrible","可怕的","frightful","terr2"], ["terrify","使恐惧","frighten","terr2"], ["deter","阻止","discourage","terr2"], ["terrific","极好的","frightful (now: great)","terr2"],
    ["text","文本","woven","tex"], ["textile","纺织品","woven cloth","tex"], ["texture","质地","weaving","tex"], ["context","语境","surrounding circumstances","tex"], ["pretext","借口","woven in front","tex"], ["tissue","组织","woven","tex"],
    ["timid","胆小的","fearful","tim"], ["intimidate","恐吓","frighten","tim"], ["timorous","胆怯的","fearful","tim"],
    ["tint","色调","shade of colour","ting"], ["tinge","轻染","slight trace","ting"], ["tincture","酊剂","dyeing","ting"], ["stain","污渍","dis-tinge","ting"],
    ["toxic","有毒的","poisonous","tox"], ["toxin","毒素","poison","tox"], ["intoxicate","使醉","make drunk","tox"], ["detox","排毒","remove poison","tox"], ["antitoxin","抗毒素","against poison","tox"],
    ["tutor","导师","guardian","tut"], ["tuition","学费","guardianship","tut"], ["intuition","直觉","instinctive knowing","tut"], ["tutelage","监护","guardianship","tut"],
    ["ultimate","最终的","farthest","ult"], ["ultimatum","最后通牒","last word","ult"], ["penultimate","倒数第二的","almost last","ult"], ["ulterior","隐秘的","farther","ult"],
    ["undulate","起伏","wave","und"], ["abundant","丰富的","overflowing","und"], ["redundant","多余的","unnecessary","und"], ["inundate","淹没","flood","und"], ["surround","围绕","overflow","und"],
    ["utility","效用","usefulness","ut"], ["utilize","利用","use","ut"], ["utensil","器具","tool","ut"], ["abuse","滥用","misuse","ut"], ["usual","通常的","in use","ut"], ["usurp","篡夺","seize power","ut"],
    ["venison","鹿肉","hunted meat","venat"], ["venery","狩猎","hunting","venat"],
    ["vest","背心","garment","vest"], ["invest","投资","put money into","vest"], ["divest","剥夺","unclothe","vest"], ["travesty","滑稽模仿","cross-dressed","vest"], ["vestry","法衣室","robe room","vest"],
    ["volatile","不稳定的","flying","vol2"], ["volley","齐射","flight","vol2"], ["volant","飞行的","flying","vol2"],
    ["revolve","旋转","rotate","volv"], ["evolve","进化","develop gradually","volv"], ["involve","涉及","include","volv"], ["revolution","革命","overthrow; rotation","volv"], ["volume","卷,体积","book; amount","volv"], ["convoluted","复杂的","complicated","volv"], ["devolve","移交","transfer downward","volv"],
    ["vulnerable","脆弱的","woundable","vulner"], ["invulnerable","无懈可击的","not woundable","vulner"],
    /* Greek batch 3 */ ["acrobat","杂技演员","walking on tiptoe","acr"], ["acronym","首字母缩略词","tip name","acr"], ["acropolis","卫城","high city","acr"], ["acute","尖锐的","sharp","acr"], ["acid","酸","sharp","acr"], ["acme","顶点","peak","acr"],
    ["aerial","空中的","of air","aer"], ["aerobic","有氧的","air-living","aer"], ["aerosol","气溶胶","air solution","aer"], ["aeronautics","航空学","air sailing","aer"],
    ["arithmetic","算术","number art","arithm"], ["logarithm","对数","ratio number","arithm"],
    ["symbol","符号","sign representing something","bol"], ["problem","问题","difficulty","bol"], ["parable","寓言","moral story","bol"], ["hyperbole","夸张","exaggeration","bol"], ["emblem","徽章","badge","bol"], ["metabolism","新陈代谢","body chemistry","bol"], ["diabolical","恶魔的","devilish","bol"], ["ballistic","弹道的","throwing","bol"],
    ["calligraphy","书法","beautiful writing","cal"], ["kaleidoscope","万花筒","beautiful-form viewer","cal"], ["callisthenics","健美操","beautiful strength","cal"],
    ["center","中心","middle point","centr"], ["concentrate","集中","bring to center","centr"], ["eccentric","古怪的","off center","centr"], ["egocentric","自我中心的","self-centered","centr"], ["centrifuge","离心机","center-fleer","centr"],
    ["encephalitis","脑炎","brain inflammation","cephal"], ["cephalopod","头足类","head-foot","cephal"], ["hydrocephalus","脑积水","water head","cephal"],
    ["chorus","合唱","dance group","chor"], ["choreography","编舞","dance writing","chor"], ["choir","唱诗班","chorus","chor"],
    ["crisis","危机","decision point","cri"], ["critic","评论家","judge","cri"], ["criterion","标准","means of judging","cri"], ["hypocrite","伪君子","actor under mask","cri"], ["critical","关键的,批评的","judging","cri"],
    ["rhododendron","杜鹃花","rose tree","dendr"], ["dendrology","树木学","tree study","dendr"], ["dendrite","树突","tree-like","dendr"],
    ["drama","戏剧","action","dram"], ["dramatic","戏剧性的","of drama","dram"], ["melodrama","情节剧","song drama","dram"],
    ["economy","经济","household law","eco"], ["ecology","生态学","house study","eco"], ["ecosystem","生态系统","house system","eco"], ["ecumenical","普世的","worldwide (church)","eco"], ["parish","教区","church district","eco"],
    ["electric","电的","of amber","electr"], ["electron","电子","amber particle","electr"], ["electrode","电极","electric way","electr"],
    ["ethic","伦理","custom","eth"], ["ethos","精神特质","character","eth"], ["ethical","道德的","of custom","eth"],
    ["ethnic","民族的","of a people","ethn"], ["ethnicity","族裔","peoplehood","ethn"], ["ethnography","民族志","people-writing","ethn"],
    ["gymnasium","体育馆","sports hall","gymn"], ["gymnastics","体操","exercises","gymn"], ["gymnosperm","裸子植物","naked seed","gymn"],
    ["gynecology","妇科","woman study","gyn"], ["misogyny","厌女","woman-hating","gyn"], ["androgynous","雌雄同体的","man-woman","gyn"],
    ["hepatitis","肝炎","liver inflammation","hepat"], ["hepatic","肝的","of the liver","hepat"],
    ["hexagon","六边形","six angles","hex"], ["hexameter","六步格","six measures","hex"],
    ["histology","组织学","tissue study","hist"], ["histamine","组胺","tissue amine","hist"],
    ["method","方法","way after","hod"], ["period","周期","span of time","hod"], ["episode","插曲","single event","hod"], ["exodus","出走","mass departure","hod"], ["synod","宗教会议","church council","hod"], ["odometer","里程表","way measure","hod"], ["cathode","阴极","negative electrode","hod"], ["anode","阳极","positive electrode","hod"],
    ["holistic","整体的","whole","hol"], ["catholic","普世的","universal","hol"], ["hologram","全息图","whole writing","hol"],
    ["hour","小时","time","hor"], ["horoscope","占星","hour watching","hor"], ["horology","钟表学","hour study","hor"],
    ["icon","图标","image","icon"], ["iconoclast","反传统者","image-breaker","icon"], ["iconic","标志性的","image-like","icon"],
    ["isosceles","等腰的","equal legs","iso"], ["isotope","同位素","atom variant","iso"], ["isometric","等长的","equal measure","iso"], ["isolate","隔离","set apart","iso"],
    ["lexicon","词典","word book","lex"], ["dyslexia","阅读障碍","bad words","lex"], ["alexia","失读症","no words","lex"], ["lexical","词汇的","of words","lex"],
    ["lipid","脂质","fat","lip"], ["liposuction","吸脂","fat suction","lip"],
    ["melody","旋律","song-way","mel"], ["melodrama","情节剧","song drama","mel"], ["melodious","悦耳的","songful","mel"],
    ["mime","哑剧","imitator","mim"], ["mimic","模仿","imitate","mim"], ["pantomime","哑剧","all-imitating","mim"], ["mimesis","模仿","imitation","mim"],
    ["mnemonic","助记的","of memory","mne"], ["amnesia","失忆","no memory","mne"], ["amnesty","大赦","forgetting","mne"],
    ["myth","神话","story","myth"], ["mythology","神话学","story study","myth"], ["mythical","神话的","of story","myth"],
    ["narcotic","麻醉剂","numbing","narc"], ["narcissism","自恋","Narcissus-ism","narc"], ["narcolepsy","嗜睡症","numb seizure","narc"],
    ["ode","颂歌","song","od"], ["melody","旋律","song-way","od"], ["parody","戏仿","comic imitation","od"], ["rhapsody","狂想曲","stitched song","od"], ["tragedy","悲剧","goat song","od"], ["comedy","喜剧","revel song","od"], ["prosody","韵律","verse rhythm","od"],
    ["ontology","本体论","being study","ont"], ["paleontology","古生物学","ancient being study","ont"],
    ["osteoporosis","骨质疏松","porous bone","oste"], ["osteopath","整骨医生","bone healer","oste"], ["periosteum","骨膜","around bone","oste"],
    ["pentagon","五边形","five angles","pent"], ["pentathlon","五项全能","five contests","pent"], ["Pentecost","五旬节","fiftieth","pent"],
    ["petroleum","石油","rock oil","petr"], ["petrify","石化","turn to stone; terrify","petr"], ["Peter","彼得","rock","petr"],
    ["pharmacy","药房","drug shop","pharm"], ["pharmaceutical","制药的","of drugs","pharm"], ["pharmacology","药理学","drug study","pharm"],
    ["phrase","短语","speech","phras"], ["paraphrase","改述","reword","phras"], ["periphrasis","迂说","roundabout expression","phras"],
    ["schizophrenia","精神分裂症","split mind","phren"], ["frenzy","狂乱","mind disorder","phren"], ["phrenology","颅相学","mind study","phren"],
    ["phytoplankton","浮游植物","plant drifters","phyt"], ["neophyte","新手","new plant","phyt"],
    ["plutocracy","财阀统治","wealth rule","plut"], ["Pluto","冥王星","the rich one","plut"],
    ["poem","诗","verse composition","poe"], ["poet","诗人","maker","poe"], ["poetry","诗歌","making","poe"], ["onomatopoeia","拟声","name-making","poe"],
    ["practice","实践","doing","pract"], ["practical","实用的","of doing","pract"], ["pragmatic","务实的","of deeds","pract"], ["chiropractor","脊椎按摩师","hand-doer","pract"],
    ["rhinoceros","犀牛","nose-horn","rhin"], ["rhinitis","鼻炎","nose inflammation","rhin"],
    ["rhythm","节奏","regular beat","rhythm"], ["rheumatism","风湿","joint pain","rhythm"], ["diarrhea","腹泻","loose bowels","rhythm"], ["catarrh","卡他","mucus buildup","rhythm"],
    ["sarcasm","讽刺","tearing flesh","sarc"], ["sarcophagus","石棺","flesh eater","sarc"], ["sarcoma","肉瘤","fleshy growth","sarc"],
    ["sclerosis","硬化","hardening","scler"], ["arteriosclerosis","动脉硬化","artery hardening","scler"],
    ["semantic","语义的","of signs","sem"], ["semaphore","信号旗","sign carrier","sem"], ["semiotics","符号学","sign study","sem"],
    ["somatic","身体的","of the body","som"], ["psychosomatic","心身的","mind-body","som"], ["chromosome","染色体","color body","som"],
    ["spore","孢子","seed","spor"], ["sporadic","零星的","scattered","spor"], ["diaspora","流散","scattered people","spor"],
    ["stereo","立体声","solid","stereo"], ["stereotype","刻板印象","solid type","stereo"], ["cholesterol","胆固醇","bile solid","stereo"],
    ["strategy","战略","army leading","strat"], ["stratum","地层","layer","strat"], ["stratosphere","平流层","layer sphere","strat"], ["stratify","分层","arrange in layers","strat"],
    ["style","风格","writing pen","styl"], ["stylus","触笔","pen","styl"], ["peristyle","柱廊","around columns","styl"],
    ["tachometer","转速表","speed measure","tach"], ["tachycardia","心动过速","fast heart","tach"],
    ["tetrahedron","四面体","four faces","tetr"], ["tetrapod","四足动物","four feet","tetr"],
    ["euthanasia","安乐死","good death","thanat"], ["thanatology","死亡学","death study","thanat"],
    ["therapy","治疗","attending","ther"], ["theropod","兽脚类","beast foot","ther"],
    ["tyrant","暴君","absolute ruler","tyr"], ["tyranny","暴政","tyrant rule","tyr"],
    ["urine","尿","urine","ur"], ["urology","泌尿科","urine study","ur"], ["diuretic","利尿剂","through urine","ur"]
  );
})();
