/* =====================================================
   FUGA MYTHICA — CURSUS French 🇫🇷 · batch 11 — topical vocabulary 2: action verbs, character & texture adjectives, materials, tools, car, kitchen, containers, shapes, measures
   ===================================================== */
(function () {
  const p = VOCAB.fr;
  Object.assign(p.roots, {});
  p.words.push(
    ["hacher", "切碎", "cut into pieces", "topic"],
    ["trancher", "切片", "cut into slices", "topic"],
    ["éplucher", "削皮", "remove skin", "topic"],
    ["râper", "磨碎", "shred", "topic"],
    ["remuer", "搅拌", "mix", "topic"],
    ["fouetter", "打发", "beat", "topic"],
    ["pétrir", "揉面", "work dough", "topic"],
    ["bouillir", "煮沸", "cook in water", "topic"],
    ["mijoter", "炖", "cook gently", "topic"],
    ["frire", "油炸", "cook in oil", "topic"],
    ["griller", "烧烤", "cook on grill", "topic"],
    ["cuire au four", "烘焙", "cook in oven", "topic"],
    ["cuire à la vapeur", "蒸", "cook with steam", "topic"],
    ["mariner", "腌", "soak in sauce", "topic"],
    ["assaisonner", "调味", "add flavour", "topic"],
    ["décongeler", "解冻", "unfreeze", "topic"],
    ["goûter", "尝", "try food", "topic"],
    ["mâcher", "咀嚼", "grind with teeth", "topic"],
    ["avaler", "吞咽", "take down throat", "topic"],
    ["siroter", "小口喝", "drink slowly", "topic"],
    ["mordre", "咬", "cut with teeth", "topic"],
    ["lécher", "舔", "touch with tongue", "topic"],
    ["renifler", "嗅", "smell", "topic"],
    ["éternuer", "打喷嚏", "expel air", "topic"],
    ["bâiller", "打哈欠", "open mouth tired", "topic"],
    ["cligner des yeux", "眨眼", "shut eyes briefly", "topic"],
    ["faire un clin d'œil", "使眼色", "close one eye", "topic"],
    ["hocher la tête", "点头", "move head yes", "topic"],
    ["hausser les épaules", "耸肩", "raise shoulders", "topic"],
    ["faire signe", "挥手", "move hand", "topic"],
    ["siffler", "吹口哨", "make sound with lips", "topic"],
    ["fredonner", "哼唱", "sing softly", "topic"],
    ["chuchoter", "耳语", "speak softly", "topic"],
    ["marmonner", "嘟囔", "speak unclearly", "topic"],
    ["hurler", "尖叫", "cry loudly", "topic"],
    ["sangloter", "抽泣", "cry with gasps", "topic"],
    ["glousser", "傻笑", "laugh lightly", "topic"],
    ["sourire largement", "咧嘴笑", "smile widely", "topic"],
    ["froncer les sourcils", "皱眉", "show displeasure", "topic"],
    ["fixer", "凝视", "look steadily", "topic"],
    ["jeter un coup d'œil", "瞥一眼", "look briefly", "topic"],
    ["jeter un œil", "偷看", "look secretly", "topic"],
    ["ramper", "爬行", "move on hands and knees", "topic"],
    ["se glisser", "蹑手蹑脚", "move quietly", "topic"],
    ["trébucher", "绊倒", "trip", "topic"],
    ["glisser", "滑倒", "lose footing", "topic"],
    ["boiter", "跛行", "walk unevenly", "topic"],
    ["marcher au pas", "行军", "walk in step", "topic"],
    ["se précipiter", "冲", "hurry", "topic"],
    ["foncer", "猛冲", "run quickly", "topic"],
    ["sprinter", "冲刺", "run at top speed", "topic"],
    ["bondir", "跳跃", "jump", "topic"],
    ["sautiller", "单脚跳", "small jump", "topic"],
    ["sauter à la corde", "蹦跳", "jump lightly", "topic"],
    ["flotter", "漂浮", "stay on surface", "topic"],
    ["couler", "下沉", "go under", "topic"],
    ["se noyer", "溺水", "die in water", "topic"],
    ["ramer", "划船", "use oars", "topic"],
    ["freiner", "刹车", "slow down", "topic"],
    ["se garer", "停车", "leave a car", "topic"],
    ["reculer", "倒车", "go backwards", "topic"],
    ["déraper", "打滑", "slide", "topic"],
    ["s'écraser", "撞车", "collide", "topic"],
    ["remorquer", "拖车", "pull a vehicle", "topic"],
    ["faire du stop", "搭便车", "get free lifts", "topic"],
    ["faire la navette", "通勤", "travel to work", "topic"],
    ["embarquer", "登机", "get on", "topic"],
    ["décoller", "起飞", "leave the ground", "topic"],
    ["s'enregistrer", "办理登机", "register", "topic"],
    ["déballer", "打开行李", "take out", "topic"],
    ["coudre", "缝", "join with thread", "topic"],
    ["tricoter", "织毛衣", "make with needles", "topic"],
    ["repasser", "熨烫", "smooth clothes", "topic"],
    ["accrocher", "挂", "suspend", "topic"],
    ["essuyer", "擦", "clean with cloth", "topic"],
    ["frotter", "刷洗", "clean hard", "topic"],
    ["balayer", "扫", "clean with broom", "topic"],
    ["passer la serpillière", "拖地", "clean floor", "topic"],
    ["épousseter", "除尘", "remove dust", "topic"],
    ["ranger", "整理", "put in order", "topic"],
    ["cirer", "抛光", "make shiny", "topic"],
    ["rincer", "冲洗", "wash with water", "topic"],
    ["tremper", "浸泡", "leave in liquid", "topic"],
    ["égoutter", "沥干", "let liquid out", "topic"],
    ["emballer", "包裹", "cover", "topic"],
    ["attacher", "系", "fasten with string", "topic"],
    ["fermer la fermeture éclair", "拉拉链", "close with zip", "topic"],
    ["boutonner", "扣扣子", "close with buttons", "topic"],
    ["marteler", "锤打", "hit with hammer", "topic"],
    ["percer", "钻", "make hole", "topic"],
    ["visser", "拧螺丝", "fix with screw", "topic"],
    ["scier", "锯", "cut with saw", "topic"],
    ["clouer", "钉", "fix with nail", "topic"],
    ["coller", "粘", "stick", "topic"],
    ["peindre", "刷漆", "colour", "topic"],
    ["poncer", "打磨", "smooth", "topic"],
    ["planter", "种植", "put in soil", "topic"],
    ["arroser", "浇水", "give water", "topic"],
    ["tondre", "割草", "cut grass", "topic"],
    ["récolter", "收获", "gather crops", "topic"],
    ["semer", "播种", "plant seeds", "topic"],
    ["traire", "挤奶", "take milk", "topic"],
    ["attraper", "抓住", "seize", "topic"],
    ["piéger", "诱捕", "catch in trap", "topic"],
    ["saisir", "抓", "take suddenly", "topic"],
    ["arracher", "夺", "take quickly", "topic"],
    ["lancer", "扔", "throw lightly", "topic"],
    ["donner un coup de pied", "踢", "hit with foot", "topic"],
    ["donner un coup de poing", "用拳打", "hit with fist", "topic"],
    ["gifler", "打耳光", "hit with open hand", "topic"],
    ["serrer dans ses bras", "拥抱", "hold close", "topic"],
    ["embrasser", "吻", "touch with lips", "topic"],
    ["caresser", "抚摸", "touch gently", "topic"],
    ["chatouiller", "挠痒", "touch to cause laughter", "topic"],
    ["gratter", "抓挠", "rub with nails", "topic"],
    ["pincer", "捏", "squeeze skin", "topic"],
    ["secouer", "摇晃", "move quickly", "topic"],
    ["trembler", "颤抖", "shake", "topic"],
    ["frissonner", "发抖", "shake with cold", "topic"],
    ["transpirer", "出汗", "give off sweat", "topic"],
    ["se rétablir", "康复", "get better", "topic"],
    ["guérir", "治愈", "make well", "topic"],
    ["se faire un bleu", "淤青", "mark skin", "topic"],
    ["tousser", "咳嗽", "expel air", "topic"],
    ["vomir", "呕吐", "throw up", "topic"],
    ["démanger", "发痒", "feel itchy", "topic"],
    ["faire mal", "疼痛", "hurt", "topic"],
    ["examiner", "检查", "look at carefully", "topic"],
    ["bander", "包扎", "wrap wound", "topic"],
    ["négocier", "谈判", "discuss terms", "topic"],
    ["marchander", "讨价还价", "argue about price", "topic"],
    ["embaucher", "雇用", "employ", "topic"],
    ["renvoyer", "解雇", "dismiss", "topic"],
    ["prendre sa retraite", "退休", "stop working", "topic"],
    ["postuler", "申请", "ask for job", "topic"],
    ["prêter", "借出", "give temporarily", "topic"],
    ["emprunter", "借入", "take temporarily", "topic"],
    ["rembourser", "退款", "give money back", "topic"],
    ["avoir les moyens", "负担得起", "have enough money", "topic"],
    ["gaspiller", "浪费", "use badly", "topic"],
    ["faire un don", "捐赠", "give to charity", "topic"],
    ["poursuivre en justice", "起诉", "take to court", "topic"],
    ["accuser", "指控", "blame", "topic"],
    ["acquitter", "宣告无罪", "find not guilty", "topic"],
    ["faire appel", "上诉", "ask for review", "topic"],
    ["témoigner", "作证", "give evidence", "topic"],
    ["dévaliser", "抢劫", "steal from", "topic"],
    ["soudoyer", "贿赂", "pay illegally", "topic"],
    ["falsifier", "伪造", "make fake", "topic"],
    ["faire de la contrebande", "走私", "move illegally", "topic"],
    ["espionner", "监视", "watch secretly", "topic"],
    ["menacer", "威胁", "warn of harm", "topic"],
    ["faire chanter", "敲诈", "threaten for money", "topic"],
    ["manifester", "抗议", "object publicly", "topic"],
    ["faire campagne", "竞选", "work for election", "topic"],
    ["abolir", "废除", "end officially", "topic"],
    ["faire respecter", "执行", "make people obey", "topic"],
    ["se connecter", "登录", "enter account", "topic"],
    ["se déconnecter", "登出", "leave account", "topic"],
    ["cliquer", "点击", "press button", "topic"],
    ["faire défiler", "滚动", "move screen", "topic"],
    ["taper", "打字", "write with keys", "topic"],
    ["enregistrer", "保存", "keep", "topic"],
    ["imprimer", "打印", "make paper copy", "topic"],
    ["scanner", "扫描", "copy digitally", "topic"],
    ["installer", "安装", "set up", "topic"],
    ["mettre à jour", "更新", "make current", "topic"],
    ["redémarrer", "重启", "start again", "topic"],
    ["pirater", "黑入", "break into", "topic"],
    ["chiffrer", "加密", "code", "topic"],
    ["diffuser en continu", "流播", "play online", "topic"],
    ["s'abonner", "订阅", "sign up", "topic"],
    ["commenter", "评论", "write remarks", "topic"],
    ["éditer", "编辑", "change text", "topic"],
    ["interpréter", "口译", "explain meaning", "topic"],
    ["tricher", "作弊", "act dishonestly", "topic"],
    ["obtenir son diplôme", "毕业", "finish studies", "topic"],
    ["s'inscrire", "注册入学", "register", "topic"],
    ["assister à", "出席", "go to", "topic"],
    ["sécher", "逃课", "not attend", "topic"],
    ["récompenser", "奖励", "give prize", "topic"],
    ["gronder", "责骂", "tell off", "topic"],
    ["se fiancer", "订婚", "promise to marry", "topic"],
    ["se marier", "结婚", "become spouses", "topic"],
    ["flirter", "调情", "show attraction", "topic"],
    ["sortir avec", "约会", "go out with", "topic"],
    ["bavarder", "八卦", "talk about others", "topic"],
    ["taquiner", "取笑", "make fun gently", "topic"],
    ["harceler", "欺凌", "hurt weaker person", "topic"],
    ["s'excuser", "道歉", "say sorry", "topic"],
    ["faire confiance", "信任", "believe in", "topic"],
    ["trahir", "背叛", "be disloyal", "topic"],
    ["envier", "嫉妒", "want what others have", "topic"],
    ["en vouloir à", "怨恨", "feel bitter", "topic"],
    ["hésiter", "犹豫", "pause unsure", "topic"],
    ["s'opposer", "反对", "disagree", "topic"],
    ["se plaindre", "抱怨", "express annoyance", "topic"],
    ["se vanter", "吹嘘", "brag", "topic"],
    ["faire semblant", "假装", "act falsely", "topic"],
    ["mentir", "撒谎", "say untruth", "topic"],
    ["deviner", "猜", "estimate", "topic"],
    ["se demander", "想知道", "ask oneself", "topic"],
    ["se rendre compte", "意识到", "become aware", "topic"],
    ["se rappeler", "回忆", "bring to mind", "topic"],
    ["estimer", "估计", "guess amount", "topic"],
    ["analyser", "分析", "examine in detail", "topic"],
    ["classer", "分类", "put in groups", "topic"],
    ["distinguer", "区分", "tell apart", "topic"],
    ["illustrer", "说明", "show by example", "topic"],
    ["têtu", "固执的", "refusing to change", "topic"],
    ["extraverti", "外向的", "sociable", "topic"],
    ["bavard", "健谈的", "talking a lot", "topic"],
    ["grincheux", "脾气坏的", "bad-tempered", "topic"],
    ["décontracté", "随和的", "relaxed", "topic"],
    ["paresseux", "懒惰的", "not wanting to work", "topic"],
    ["travailleur", "勤奋的", "working hard", "topic"],
    ["fiable", "可靠的", "dependable", "topic"],
    ["malhonnête", "不诚实的", "not truthful", "topic"],
    ["radin", "吝啬的", "not generous", "topic"],
    ["égoïste", "自私的", "thinking of self", "topic"],
    ["poli", "有礼貌的", "courteous", "topic"],
    ["impoli", "粗鲁的", "not polite", "topic"],
    ["arrogant", "傲慢的", "too proud", "topic"],
    ["lâche", "懦弱的", "afraid", "topic"],
    ["raisonnable", "明智的", "reasonable", "topic"],
    ["rusé", "狡猾的", "clever and deceitful", "topic"],
    ["spirituel", "机智的", "clever and funny", "topic"],
    ["maladroit", "笨拙的", "awkward", "topic"],
    ["patient", "有耐心的", "able to wait", "topic"],
    ["impatient", "不耐烦的", "unable to wait", "topic"],
    ["créatif", "有创造力的", "imaginative", "topic"],
    ["distrait", "心不在焉的", "forgetful", "topic"],
    ["ordonné", "整洁的", "neat", "topic"],
    ["désordonné", "凌乱的", "untidy", "topic"],
    ["lisse", "光滑的", "even surface", "topic"],
    ["rugueux", "粗糙的", "uneven", "topic"],
    ["tranchant", "锋利的", "able to cut", "topic"],
    ["émoussé", "钝的", "not sharp", "topic"],
    ["collant", "黏的", "adhering", "topic"],
    ["glissant", "滑的", "hard to hold", "topic"],
    ["raide", "僵硬的", "not bending", "topic"],
    ["transparent", "透明的", "see-through", "topic"],
    ["opaque", "不透明的", "not see-through", "topic"],
    ["brillant", "闪亮的", "reflecting light", "topic"],
    ["terne", "暗淡的", "not bright", "topic"],
    ["humide", "潮湿的", "slightly wet", "topic"],
    ["trempé", "湿透的", "very wet", "topic"],
    ["croustillant", "脆的", "firm and dry", "topic"],
    ["rassis", "不新鲜的", "old", "topic"],
    ["pourri", "腐烂的", "decayed", "topic"],
    ["épicé", "辣的", "hot-tasting", "topic"],
    ["fade", "淡而无味的", "without flavour", "topic"],
    ["aigre", "酸的", "acid taste", "topic"],
    ["gras", "油腻的", "oily", "topic"],
    ["juteux", "多汁的", "full of juice", "topic"],
    ["l'acier", "钢", "steel", "topic"],
    ["le fer", "铁", "iron", "topic"],
    ["le cuivre", "铜", "copper", "topic"],
    ["le laiton", "黄铜", "brass", "topic"],
    ["l'aluminium", "铝", "aluminium", "topic"],
    ["l'étain", "锡", "tin", "topic"],
    ["le caoutchouc", "橡胶", "rubber", "topic"],
    ["le cuir", "皮革", "leather", "topic"],
    ["la laine", "羊毛", "wool", "topic"],
    ["le coton", "棉", "cotton", "topic"],
    ["la soie", "丝绸", "silk", "topic"],
    ["le velours", "天鹅绒", "velvet", "topic"],
    ["le béton", "混凝土", "concrete", "topic"],
    ["le ciment", "水泥", "cement", "topic"],
    ["le carreau", "瓷砖", "tile", "topic"],
    ["le marbre", "大理石", "marble", "topic"],
    ["l'argile", "黏土", "clay", "topic"],
    ["la mousse", "泡沫", "foam", "topic"],
    ["le fil de fer", "铁丝", "wire", "topic"],
    ["la corde", "绳子", "rope", "topic"],
    ["la ficelle", "细绳", "string", "topic"],
    ["le crochet", "钩子", "hook", "topic"],
    ["le clou", "钉子", "nail", "topic"],
    ["la vis", "螺丝", "screw", "topic"],
    ["le boulon", "螺栓", "bolt", "topic"],
    ["le marteau", "锤子", "hammer", "topic"],
    ["le tournevis", "螺丝刀", "screwdriver", "topic"],
    ["la pince", "钳子", "pliers", "topic"],
    ["la scie", "锯", "saw", "topic"],
    ["la perceuse", "钻机", "drill", "topic"],
    ["l'échelle", "梯子", "ladder", "topic"],
    ["le seau", "水桶", "bucket", "topic"],
    ["la pelle", "铲子", "shovel", "topic"],
    ["le râteau", "耙子", "rake", "topic"],
    ["le mètre ruban", "卷尺", "tape measure", "topic"],
    ["la boîte à outils", "工具箱", "toolbox", "topic"],
    ["le volant", "方向盘", "steering wheel", "topic"],
    ["le frein", "刹车", "brake", "topic"],
    ["le pneu", "轮胎", "tyre", "topic"],
    ["le pare-brise", "挡风玻璃", "windscreen", "topic"],
    ["l'essuie-glace", "雨刷", "wiper", "topic"],
    ["le capot", "引擎盖", "bonnet", "topic"],
    ["le coffre", "后备箱", "boot", "topic"],
    ["la ceinture de sécurité", "安全带", "seat belt", "topic"],
    ["le rétroviseur", "后视镜", "mirror", "topic"],
    ["le klaxon", "喇叭", "horn", "topic"],
    ["l'embrayage", "离合器", "clutch", "topic"],
    ["la batterie", "电池", "battery", "topic"],
    ["le carburant", "燃料", "fuel", "topic"],
    ["le pot d'échappement", "排气管", "exhaust", "topic"],
    ["la plaque d'immatriculation", "车牌", "number plate", "topic"],
    ["la casserole", "炖锅", "saucepan", "topic"],
    ["la poêle", "煎锅", "frying pan", "topic"],
    ["le couvercle", "盖子", "lid", "topic"],
    ["la bouilloire", "水壶", "kettle", "topic"],
    ["la théière", "茶壶", "teapot", "topic"],
    ["la cruche", "壶", "jug", "topic"],
    ["le bol", "碗", "bowl", "topic"],
    ["la râpe", "刨丝器", "grater", "topic"],
    ["la louche", "长柄勺", "ladle", "topic"],
    ["le fouet", "打蛋器", "whisk", "topic"],
    ["le rouleau à pâtisserie", "擀面杖", "rolling pin", "topic"],
    ["la planche à découper", "砧板", "chopping board", "topic"],
    ["la passoire", "筛子", "sieve", "topic"],
    ["le tire-bouchon", "开瓶器", "corkscrew", "topic"],
    ["l'ouvre-boîte", "开罐器", "tin opener", "topic"],
    ["le mixeur", "搅拌机", "blender", "topic"],
    ["le grille-pain", "烤面包机", "toaster", "topic"],
    ["le micro-ondes", "微波炉", "microwave", "topic"],
    ["l'évier", "水槽", "sink", "topic"],
    ["le robinet", "水龙头", "tap", "topic"],
    ["l'éponge", "海绵", "sponge", "topic"],
    ["le tablier", "围裙", "apron", "topic"],
    ["la nappe", "桌布", "tablecloth", "topic"],
    ["le bocal", "罐子", "jar", "topic"],
    ["la boîte de conserve", "罐头", "tin", "topic"],
    ["la bouteille", "瓶子", "bottle", "topic"],
    ["le bouchon", "软木塞", "cork", "topic"],
    ["le sachet", "小袋", "sachet", "topic"],
    ["le tube", "管", "tube", "topic"],
    ["le tonneau", "桶", "barrel", "topic"],
    ["l'ovale", "椭圆", "oval", "topic"],
    ["le cube", "立方体", "cube", "topic"],
    ["la sphère", "球体", "sphere", "topic"],
    ["le cylindre", "圆柱", "cylinder", "topic"],
    ["le cône", "圆锥", "cone", "topic"],
    ["la pyramide", "金字塔", "pyramid", "topic"],
    ["la courbe", "曲线", "curve", "topic"],
    ["le coin", "角落", "corner", "topic"],
    ["la surface", "表面", "surface", "topic"],
    ["la largeur", "宽度", "width", "topic"],
    ["la profondeur", "深度", "depth", "topic"],
    ["la moyenne", "平均", "average", "topic"],
    ["la somme", "总和", "sum", "topic"],
    ["la décimale", "小数", "decimal", "topic"],
    ["la calculatrice", "计算器", "calculator", "topic"],
    ["la boussole", "指南针", "compass", "topic"],
    ["la balance", "秤", "scales", "topic"]
  );
})();
