/* =====================================================
   FUGA MYTHICA — CURSUS Italian 🇮🇹 · batch 10 — topical vocabulary 2: action verbs, character & texture adjectives, materials, tools, car, kitchen, containers, shapes, measures
   ===================================================== */
(function () {
  const p = VOCAB.it;
  Object.assign(p.roots, {});
  p.words.push(
    ["tritare", "切碎", "cut into pieces", "topic"],
    ["affettare", "切片", "cut into slices", "topic"],
    ["sbucciare", "削皮", "remove skin", "topic"],
    ["grattugiare", "磨碎", "shred", "topic"],
    ["sbattere", "打发", "beat", "topic"],
    ["impastare", "揉面", "work dough", "topic"],
    ["bollire", "煮沸", "cook in water", "topic"],
    ["sobbollire", "炖", "cook gently", "topic"],
    ["friggere", "油炸", "cook in oil", "topic"],
    ["arrostire", "烤", "cook in oven", "topic"],
    ["grigliare", "烧烤", "cook on grill", "topic"],
    ["cuocere al forno", "烘焙", "cook in oven", "topic"],
    ["cuocere a vapore", "蒸", "cook with steam", "topic"],
    ["marinare", "腌", "soak in sauce", "topic"],
    ["condire", "调味", "add flavour", "topic"],
    ["assaggiare", "尝", "try food", "topic"],
    ["masticare", "咀嚼", "grind with teeth", "topic"],
    ["inghiottire", "吞咽", "take down throat", "topic"],
    ["sorseggiare", "小口喝", "drink slowly", "topic"],
    ["mordere", "咬", "cut with teeth", "topic"],
    ["leccare", "舔", "touch with tongue", "topic"],
    ["annusare", "嗅", "smell", "topic"],
    ["starnutire", "打喷嚏", "expel air", "topic"],
    ["sbadigliare", "打哈欠", "open mouth tired", "topic"],
    ["sbattere le palpebre", "眨眼", "shut eyes briefly", "topic"],
    ["fare l'occhiolino", "使眼色", "close one eye", "topic"],
    ["annuire", "点头", "move head yes", "topic"],
    ["fare spallucce", "耸肩", "raise shoulders", "topic"],
    ["salutare con la mano", "挥手", "move hand", "topic"],
    ["fischiare", "吹口哨", "make sound with lips", "topic"],
    ["canticchiare", "哼唱", "sing softly", "topic"],
    ["sussurrare", "耳语", "speak softly", "topic"],
    ["borbottare", "嘟囔", "speak unclearly", "topic"],
    ["urlare", "尖叫", "cry loudly", "topic"],
    ["singhiozzare", "抽泣", "cry with gasps", "topic"],
    ["ridacchiare", "傻笑", "laugh lightly", "topic"],
    ["aggrottare le sopracciglia", "皱眉", "show displeasure", "topic"],
    ["fissare", "凝视", "look steadily", "topic"],
    ["dare un'occhiata", "瞥一眼", "look briefly", "topic"],
    ["sbirciare", "偷看", "look secretly", "topic"],
    ["gattonare", "爬行", "move on hands and knees", "topic"],
    ["strisciare", "蹑手蹑脚", "move quietly", "topic"],
    ["inciampare", "绊倒", "trip", "topic"],
    ["scivolare", "滑倒", "lose footing", "topic"],
    ["zoppicare", "跛行", "walk unevenly", "topic"],
    ["vagare", "漫步", "walk aimlessly", "topic"],
    ["marciare", "行军", "walk in step", "topic"],
    ["precipitarsi", "冲", "hurry", "topic"],
    ["sfrecciare", "猛冲", "run quickly", "topic"],
    ["scattare", "冲刺", "run at top speed", "topic"],
    ["balzare", "跳跃", "jump", "topic"],
    ["saltellare", "单脚跳", "small jump", "topic"],
    ["galleggiare", "漂浮", "stay on surface", "topic"],
    ["affondare", "下沉", "go under", "topic"],
    ["annegare", "溺水", "die in water", "topic"],
    ["remare", "划船", "use oars", "topic"],
    ["frenare", "刹车", "slow down", "topic"],
    ["parcheggiare", "停车", "leave a car", "topic"],
    ["fare retromarcia", "倒车", "go backwards", "topic"],
    ["slittare", "打滑", "slide", "topic"],
    ["schiantarsi", "撞车", "collide", "topic"],
    ["rimorchiare", "拖车", "pull a vehicle", "topic"],
    ["fare l'autostop", "搭便车", "get free lifts", "topic"],
    ["fare il pendolare", "通勤", "travel to work", "topic"],
    ["imbarcarsi", "登机", "get on", "topic"],
    ["decollare", "起飞", "leave the ground", "topic"],
    ["fare il check-in", "办理登机", "register", "topic"],
    ["disfare le valigie", "打开行李", "take out", "topic"],
    ["cucire", "缝", "join with thread", "topic"],
    ["lavorare a maglia", "织毛衣", "make with needles", "topic"],
    ["stirare", "熨烫", "smooth clothes", "topic"],
    ["appendere", "挂", "suspend", "topic"],
    ["strofinare", "刷洗", "clean hard", "topic"],
    ["spazzare", "扫", "clean with broom", "topic"],
    ["lavare il pavimento", "拖地", "clean floor", "topic"],
    ["spolverare", "除尘", "remove dust", "topic"],
    ["riordinare", "整理", "put in order", "topic"],
    ["lucidare", "抛光", "make shiny", "topic"],
    ["sciacquare", "冲洗", "wash with water", "topic"],
    ["mettere a bagno", "浸泡", "leave in liquid", "topic"],
    ["scolare", "沥干", "let liquid out", "topic"],
    ["spremere", "挤压", "press hard", "topic"],
    ["scartare", "拆开", "uncover", "topic"],
    ["slegare", "解开", "unfasten", "topic"],
    ["allacciare", "扣紧", "fix firmly", "topic"],
    ["chiudere la cerniera", "拉拉链", "close with zip", "topic"],
    ["abbottonare", "扣扣子", "close with buttons", "topic"],
    ["martellare", "锤打", "hit with hammer", "topic"],
    ["trapanare", "钻", "make hole", "topic"],
    ["avvitare", "拧螺丝", "fix with screw", "topic"],
    ["segare", "锯", "cut with saw", "topic"],
    ["inchiodare", "钉", "fix with nail", "topic"],
    ["incollare", "粘", "stick", "topic"],
    ["dipingere", "刷漆", "colour", "topic"],
    ["carteggiare", "打磨", "smooth", "topic"],
    ["piantare", "种植", "put in soil", "topic"],
    ["annaffiare", "浇水", "give water", "topic"],
    ["potare", "修剪", "cut branches", "topic"],
    ["falciare", "割草", "cut grass", "topic"],
    ["seminare", "播种", "plant seeds", "topic"],
    ["mungere", "挤奶", "take milk", "topic"],
    ["acchiappare", "抓住", "seize", "topic"],
    ["intrappolare", "诱捕", "catch in trap", "topic"],
    ["afferrare", "抓", "take suddenly", "topic"],
    ["strappare", "夺", "take quickly", "topic"],
    ["lanciare", "扔", "throw lightly", "topic"],
    ["scagliare", "猛扔", "throw hard", "topic"],
    ["calciare", "踢", "hit with foot", "topic"],
    ["dare un pugno", "用拳打", "hit with fist", "topic"],
    ["schiaffeggiare", "打耳光", "hit with open hand", "topic"],
    ["accarezzare", "抚摸", "touch gently", "topic"],
    ["solleticare", "挠痒", "touch to cause laughter", "topic"],
    ["grattare", "抓挠", "rub with nails", "topic"],
    ["pizzicare", "捏", "squeeze skin", "topic"],
    ["scuotere", "摇晃", "move quickly", "topic"],
    ["tremare", "颤抖", "shake", "topic"],
    ["rabbrividire", "发抖", "shake with cold", "topic"],
    ["sudare", "出汗", "give off sweat", "topic"],
    ["guarire", "康复", "get better", "topic"],
    ["farsi un livido", "淤青", "mark skin", "topic"],
    ["tossire", "咳嗽", "expel air", "topic"],
    ["vomitare", "呕吐", "throw up", "topic"],
    ["prudere", "发痒", "feel itchy", "topic"],
    ["esaminare", "检查", "look at carefully", "topic"],
    ["bendare", "包扎", "wrap wound", "topic"],
    ["negoziare", "谈判", "discuss terms", "topic"],
    ["contrattare", "讨价还价", "argue about price", "topic"],
    ["licenziare", "解雇", "dismiss", "topic"],
    ["andare in pensione", "退休", "stop working", "topic"],
    ["candidarsi", "申请", "ask for job", "topic"],
    ["prestare", "借出", "give temporarily", "topic"],
    ["prendere in prestito", "借入", "take temporarily", "topic"],
    ["rimborsare", "退款", "give money back", "topic"],
    ["permettersi", "负担得起", "have enough money", "topic"],
    ["sprecare", "浪费", "use badly", "topic"],
    ["fare causa", "起诉", "take to court", "topic"],
    ["accusare", "指控", "blame", "topic"],
    ["ricorrere in appello", "上诉", "ask for review", "topic"],
    ["testimoniare", "作证", "give evidence", "topic"],
    ["rilasciare", "释放", "set free", "topic"],
    ["rapinare", "抢劫", "steal from", "topic"],
    ["falsificare", "伪造", "make fake", "topic"],
    ["contrabbandare", "走私", "move illegally", "topic"],
    ["minacciare", "威胁", "warn of harm", "topic"],
    ["ricattare", "敲诈", "threaten for money", "topic"],
    ["protestare", "抗议", "object publicly", "topic"],
    ["fare campagna", "竞选", "work for election", "topic"],
    ["abolire", "废除", "end officially", "topic"],
    ["far rispettare", "执行", "make people obey", "topic"],
    ["caricare", "上传", "send to server", "topic"],
    ["cliccare", "点击", "press button", "topic"],
    ["cancellare", "删除", "remove", "topic"],
    ["stampare", "打印", "make paper copy", "topic"],
    ["scansionare", "扫描", "copy digitally", "topic"],
    ["installare", "安装", "set up", "topic"],
    ["aggiornare", "更新", "make current", "topic"],
    ["riavviare", "重启", "start again", "topic"],
    ["bloccarsi", "崩溃", "stop working", "topic"],
    ["hackerare", "黑入", "break into", "topic"],
    ["criptare", "加密", "code", "topic"],
    ["trasmettere in streaming", "流播", "play online", "topic"],
    ["abbonarsi", "订阅", "sign up", "topic"],
    ["mettere mi piace", "点赞", "approve online", "topic"],
    ["commentare", "评论", "write remarks", "topic"],
    ["interpretare", "口译", "explain meaning", "topic"],
    ["ripassare", "复习", "study again", "topic"],
    ["imbrogliare", "作弊", "act dishonestly", "topic"],
    ["iscriversi", "注册入学", "register", "topic"],
    ["frequentare", "出席", "go to", "topic"],
    ["ricompensare", "奖励", "give prize", "topic"],
    ["sgridare", "责骂", "tell off", "topic"],
    ["viziare", "宠坏", "indulge", "topic"],
    ["fare da babysitter", "照看孩子", "look after children", "topic"],
    ["fidanzarsi", "订婚", "promise to marry", "topic"],
    ["flirtare", "调情", "show attraction", "topic"],
    ["uscire con", "约会", "go out with", "topic"],
    ["lasciarsi", "分手", "end relationship", "topic"],
    ["spettegolare", "八卦", "talk about others", "topic"],
    ["prendere in giro", "取笑", "make fun gently", "topic"],
    ["bullizzare", "欺凌", "hurt weaker person", "topic"],
    ["scusarsi", "道歉", "say sorry", "topic"],
    ["tradire", "背叛", "be disloyal", "topic"],
    ["provare risentimento", "怨恨", "feel bitter", "topic"],
    ["consolare", "安慰", "make feel better", "topic"],
    ["esitare", "犹豫", "pause unsure", "topic"],
    ["obiettare", "反对", "disagree", "topic"],
    ["lamentarsi", "抱怨", "express annoyance", "topic"],
    ["vantarsi", "吹嘘", "brag", "topic"],
    ["chiedersi", "想知道", "ask oneself", "topic"],
    ["rendersi conto", "意识到", "become aware", "topic"],
    ["stimare", "估计", "guess amount", "topic"],
    ["analizzare", "分析", "examine in detail", "topic"],
    ["classificare", "分类", "put in groups", "topic"],
    ["distinguere", "区分", "tell apart", "topic"],
    ["illustrare", "说明", "show by example", "topic"],
    ["testardo", "固执的", "refusing to change", "topic"],
    ["estroverso", "外向的", "sociable", "topic"],
    ["allegro", "愉快的", "happy", "topic"],
    ["scontroso", "脾气坏的", "bad-tempered", "topic"],
    ["accomodante", "随和的", "relaxed", "topic"],
    ["pignolo", "挑剔的", "hard to please", "topic"],
    ["pigro", "懒惰的", "not wanting to work", "topic"],
    ["laborioso", "勤奋的", "working hard", "topic"],
    ["affidabile", "可靠的", "dependable", "topic"],
    ["leale", "忠诚的", "faithful", "topic"],
    ["tirchio", "吝啬的", "not generous", "topic"],
    ["egoista", "自私的", "thinking of self", "topic"],
    ["educato", "有礼貌的", "courteous", "topic"],
    ["maleducato", "粗鲁的", "not polite", "topic"],
    ["arrogante", "傲慢的", "too proud", "topic"],
    ["cauto", "谨慎的", "careful", "topic"],
    ["avventato", "鲁莽的", "not careful", "topic"],
    ["codardo", "懦弱的", "afraid", "topic"],
    ["astuto", "狡猾的", "clever and deceitful", "topic"],
    ["spiritoso", "机智的", "clever and funny", "topic"],
    ["goffo", "笨拙的", "awkward", "topic"],
    ["paziente", "有耐心的", "able to wait", "topic"],
    ["impaziente", "不耐烦的", "unable to wait", "topic"],
    ["creativo", "有创造力的", "imaginative", "topic"],
    ["distratto", "心不在焉的", "forgetful", "topic"],
    ["ordinato", "整洁的", "neat", "topic"],
    ["liscio", "光滑的", "even surface", "topic"],
    ["ruvido", "粗糙的", "uneven", "topic"],
    ["affilato", "锋利的", "able to cut", "topic"],
    ["smussato", "钝的", "not sharp", "topic"],
    ["appiccicoso", "黏的", "adhering", "topic"],
    ["scivoloso", "滑的", "hard to hold", "topic"],
    ["trasparente", "透明的", "see-through", "topic"],
    ["opaco", "不透明的", "not see-through", "topic"],
    ["spento", "暗淡的", "not bright", "topic"],
    ["umido", "潮湿的", "slightly wet", "topic"],
    ["fradicio", "湿透的", "very wet", "topic"],
    ["croccante", "脆的", "firm and dry", "topic"],
    ["raffermo", "不新鲜的", "old", "topic"],
    ["marcio", "腐烂的", "decayed", "topic"],
    ["piccante", "辣的", "hot-tasting", "topic"],
    ["insipido", "淡而无味的", "without flavour", "topic"],
    ["aspro", "酸的", "acid taste", "topic"],
    ["unto", "油腻的", "oily", "topic"],
    ["succoso", "多汁的", "full of juice", "topic"],
    ["il legno", "木材", "wood", "topic"],
    ["l'acciaio", "钢", "steel", "topic"],
    ["il ferro", "铁", "iron", "topic"],
    ["il rame", "铜", "copper", "topic"],
    ["l'ottone", "黄铜", "brass", "topic"],
    ["l'alluminio", "铝", "aluminium", "topic"],
    ["la lana", "羊毛", "wool", "topic"],
    ["la seta", "丝绸", "silk", "topic"],
    ["il velluto", "天鹅绒", "velvet", "topic"],
    ["il calcestruzzo", "混凝土", "concrete", "topic"],
    ["il cemento", "水泥", "cement", "topic"],
    ["il mattone", "砖", "brick", "topic"],
    ["la piastrella", "瓷砖", "tile", "topic"],
    ["il marmo", "大理石", "marble", "topic"],
    ["l'argilla", "黏土", "clay", "topic"],
    ["il vetro", "玻璃", "glass", "topic"],
    ["la schiuma", "泡沫", "foam", "topic"],
    ["il filo di ferro", "铁丝", "wire", "topic"],
    ["la corda", "绳子", "rope", "topic"],
    ["lo spago", "细绳", "string", "topic"],
    ["la catena", "链条", "chain", "topic"],
    ["il gancio", "钩子", "hook", "topic"],
    ["la vite", "螺丝", "screw", "topic"],
    ["il bullone", "螺栓", "bolt", "topic"],
    ["il martello", "锤子", "hammer", "topic"],
    ["il cacciavite", "螺丝刀", "screwdriver", "topic"],
    ["la chiave inglese", "扳手", "wrench", "topic"],
    ["le pinze", "钳子", "pliers", "topic"],
    ["la sega", "锯", "saw", "topic"],
    ["il trapano", "钻机", "drill", "topic"],
    ["la scala a pioli", "梯子", "ladder", "topic"],
    ["il secchio", "水桶", "bucket", "topic"],
    ["la pala", "铲子", "shovel", "topic"],
    ["il rastrello", "耙子", "rake", "topic"],
    ["l'ascia", "斧头", "axe", "topic"],
    ["il metro a nastro", "卷尺", "tape measure", "topic"],
    ["la cassetta degli attrezzi", "工具箱", "toolbox", "topic"],
    ["il volante", "方向盘", "steering wheel", "topic"],
    ["il freno", "刹车", "brake", "topic"],
    ["lo pneumatico", "轮胎", "tyre", "topic"],
    ["il parabrezza", "挡风玻璃", "windscreen", "topic"],
    ["il tergicristallo", "雨刷", "wiper", "topic"],
    ["il cofano", "引擎盖", "bonnet", "topic"],
    ["il bagagliaio", "后备箱", "boot", "topic"],
    ["la cintura di sicurezza", "安全带", "seat belt", "topic"],
    ["il clacson", "喇叭", "horn", "topic"],
    ["la marcia", "挡位", "gear", "topic"],
    ["la frizione", "离合器", "clutch", "topic"],
    ["la batteria", "电池", "battery", "topic"],
    ["il carburante", "燃料", "fuel", "topic"],
    ["la marmitta", "排气管", "exhaust", "topic"],
    ["la targa", "车牌", "number plate", "topic"],
    ["la pentola", "炖锅", "saucepan", "topic"],
    ["la padella", "煎锅", "frying pan", "topic"],
    ["il coperchio", "盖子", "lid", "topic"],
    ["il bollitore", "水壶", "kettle", "topic"],
    ["la teiera", "茶壶", "teapot", "topic"],
    ["la brocca", "壶", "jug", "topic"],
    ["la ciotola", "碗", "bowl", "topic"],
    ["il vassoio", "托盘", "tray", "topic"],
    ["la grattugia", "刨丝器", "grater", "topic"],
    ["il mestolo", "长柄勺", "ladle", "topic"],
    ["la frusta", "打蛋器", "whisk", "topic"],
    ["il mattarello", "擀面杖", "rolling pin", "topic"],
    ["il tagliere", "砧板", "chopping board", "topic"],
    ["il colino", "筛子", "sieve", "topic"],
    ["il cavatappi", "开瓶器", "corkscrew", "topic"],
    ["l'apriscatole", "开罐器", "tin opener", "topic"],
    ["il frullatore", "搅拌机", "blender", "topic"],
    ["il tostapane", "烤面包机", "toaster", "topic"],
    ["il lavandino", "水槽", "sink", "topic"],
    ["il rubinetto", "水龙头", "tap", "topic"],
    ["la spugna", "海绵", "sponge", "topic"],
    ["il grembiule", "围裙", "apron", "topic"],
    ["il barattolo", "罐子", "jar", "topic"],
    ["la lattina", "罐头", "tin", "topic"],
    ["la bottiglia", "瓶子", "bottle", "topic"],
    ["la bustina", "小袋", "sachet", "topic"],
    ["il tubo", "管", "tube", "topic"],
    ["il barile", "桶", "barrel", "topic"],
    ["il cesto", "篮子", "basket", "topic"],
    ["il quadrato", "正方形", "square", "topic"],
    ["l'ovale", "椭圆", "oval", "topic"],
    ["il cubo", "立方体", "cube", "topic"],
    ["la sfera", "球体", "sphere", "topic"],
    ["il cilindro", "圆柱", "cylinder", "topic"],
    ["il cono", "圆锥", "cone", "topic"],
    ["la piramide", "金字塔", "pyramid", "topic"],
    ["la curva", "曲线", "curve", "topic"],
    ["il bordo", "边缘", "edge", "topic"],
    ["la superficie", "表面", "surface", "topic"],
    ["la larghezza", "宽度", "width", "topic"],
    ["la profondità", "深度", "depth", "topic"],
    ["la percentuale", "百分比", "percentage", "topic"],
    ["la media", "平均", "average", "topic"],
    ["la somma", "总和", "sum", "topic"],
    ["il decimale", "小数", "decimal", "topic"],
    ["la calcolatrice", "计算器", "calculator", "topic"],
    ["il righello", "尺子", "ruler", "topic"],
    ["la bussola", "指南针", "compass", "topic"],
    ["la bilancia", "秤", "scales", "topic"]
  );
})();
