/* =====================================================
   FUGA MYTHICA — CURSUS Italian 🇮🇹 · batch 11 — topical vocabulary 3: adverbs & connectors, time & quantity, hobbies, sport, music, nationalities, animals, plants, house, office, abstract nouns
   ===================================================== */
(function () {
  const p = VOCAB.it;
  Object.assign(p.roots, {});
  p.words.push(
    ["ciononostante", "尽管如此", "even so", "topic"],
    ["di conseguenza", "结果", "as a result", "topic"],
    ["per di più", "而且", "in addition", "topic"],
    ["nel frattempo", "同时", "at the same time", "topic"],
    ["in anticipo", "事先", "in advance", "topic"],
    ["alla fine", "最终", "in the end", "topic"],
    ["immediatamente", "立刻", "at once", "topic"],
    ["improvvisamente", "突然", "without warning", "topic"],
    ["recentemente", "最近", "not long ago", "topic"],
    ["ultimamente", "近来", "recently", "topic"],
    ["oggigiorno", "如今", "these days", "topic"],
    ["un tempo", "以前", "in the past", "topic"],
    ["attualmente", "目前", "now", "topic"],
    ["temporaneamente", "暂时", "for a short time", "topic"],
    ["permanentemente", "永久地", "for ever", "topic"],
    ["di rado", "难得", "rarely", "topic"],
    ["frequentemente", "经常", "often", "topic"],
    ["costantemente", "不断地", "all the time", "topic"],
    ["quotidianamente", "每天", "every day", "topic"],
    ["settimanalmente", "每周", "every week", "topic"],
    ["mensilmente", "每月", "every month", "topic"],
    ["annualmente", "每年", "every year", "topic"],
    ["due volte", "两次", "two times", "topic"],
    ["una volta", "一次", "one time", "topic"],
    ["a malapena", "几乎不", "barely", "topic"],
    ["estremamente", "极其", "very", "topic"],
    ["leggermente", "稍微", "a little", "topic"],
    ["interamente", "完全", "completely", "topic"],
    ["in parte", "部分地", "not completely", "topic"],
    ["principalmente", "主要地", "mostly", "topic"],
    ["specialmente", "尤其", "particularly", "topic"],
    ["particolarmente", "特别", "especially", "topic"],
    ["esattamente", "恰好", "precisely", "topic"],
    ["precisamente", "精确地", "exactly", "topic"],
    ["apparentemente", "显然", "it seems", "topic"],
    ["ovviamente", "明显地", "clearly", "topic"],
    ["certamente", "当然", "surely", "topic"],
    ["probabilmente", "可能", "likely", "topic"],
    ["sicuramente", "肯定", "for sure", "topic"],
    ["si spera", "但愿", "it is hoped", "topic"],
    ["purtroppo", "不幸地", "sadly", "topic"],
    ["fortunatamente", "幸运地", "luckily", "topic"],
    ["sorprendentemente", "令人惊讶地", "unexpectedly", "topic"],
    ["onestamente", "老实说", "truthfully", "topic"],
    ["fondamentalmente", "基本上", "essentially", "topic"],
    ["specificamente", "具体地", "in particular", "topic"],
    ["in altre parole", "换句话说", "that is to say", "topic"],
    ["d'altra parte", "另一方面", "conversely", "topic"],
    ["in aggiunta", "此外", "also", "topic"],
    ["in breve", "简而言之", "briefly", "topic"],
    ["al massimo", "至多", "maximum", "topic"],
    ["invece", "代替", "as an alternative", "topic"],
    ["del resto", "况且", "also", "topic"],
    ["finché", "直到", "up to the time", "topic"],
    ["non appena", "一…就", "immediately when", "topic"],
    ["nel caso", "以防", "if it happens", "topic"],
    ["anche se", "即使", "despite", "topic"],
    ["malgrado", "尽管", "in spite of", "topic"],
    ["durante tutto", "贯穿", "during all of", "topic"],
    ["entro", "在…之内", "inside", "topic"],
    ["il crepuscolo", "黄昏", "evening twilight", "topic"],
    ["le due settimane", "两周", "two weeks", "topic"],
    ["l'era", "时代", "period", "topic"],
    ["il termine", "期限", "time limit", "topic"],
    ["l'appuntamento", "预约", "arranged meeting", "topic"],
    ["l'anno bisestile", "闰年", "366-day year", "topic"],
    ["l'ammontare", "数额", "quantity", "topic"],
    ["la maggior parte", "大多数", "most", "topic"],
    ["il mucchio", "堆", "pile", "topic"],
    ["il mazzo", "一束", "group", "topic"],
    ["la fetta", "一片", "thin piece", "topic"],
    ["la goccia", "一滴", "small amount of liquid", "topic"],
    ["la briciola", "面包屑", "tiny piece", "topic"],
    ["il pezzo", "块", "piece", "topic"],
    ["la cucchiaiata", "一勺", "spoon amount", "topic"],
    ["il pizzico", "一撮", "tiny amount", "topic"],
    ["l'hobby", "爱好", "pastime", "topic"],
    ["il tempo libero", "休闲", "free time", "topic"],
    ["il passatempo", "消遣", "hobby", "topic"],
    ["il giardinaggio", "园艺", "growing plants", "topic"],
    ["la ceramica", "陶艺", "clay work", "topic"],
    ["la maglia", "编织", "wool craft", "topic"],
    ["il cucito", "缝纫", "needlework", "topic"],
    ["la falegnameria", "木工", "woodwork", "topic"],
    ["il collezionismo", "收藏", "gathering items", "topic"],
    ["il collezionista", "收藏家", "one who collects", "topic"],
    ["il puzzle", "拼图", "jigsaw", "topic"],
    ["il cruciverba", "填字游戏", "word puzzle", "topic"],
    ["il gioco da tavolo", "桌游", "table game", "topic"],
    ["le carte", "扑克牌", "playing cards", "topic"],
    ["i dadi", "骰子", "dice", "topic"],
    ["il videogioco", "电子游戏", "video game", "topic"],
    ["la console", "游戏机", "games machine", "topic"],
    ["il karaoke", "卡拉OK", "karaoke", "topic"],
    ["il picnic", "野餐", "outdoor meal", "topic"],
    ["il barbecue", "烧烤", "grill party", "topic"],
    ["la canna da pesca", "钓竿", "fishing pole", "topic"],
    ["la racchetta", "球拍", "bat", "topic"],
    ["il pallone", "球", "ball", "topic"],
    ["l'arbitro", "裁判", "umpire", "topic"],
    ["il fischietto", "哨子", "whistle", "topic"],
    ["la pista", "跑道", "running course", "topic"],
    ["la maratona", "马拉松", "long race", "topic"],
    ["lo sprint", "短跑", "fast run", "topic"],
    ["il giavellotto", "标枪", "throwing spear", "topic"],
    ["la lotta", "摔跤", "grappling sport", "topic"],
    ["il pugilato", "拳击", "fist fighting", "topic"],
    ["il tiro con l'arco", "射箭", "bow sport", "topic"],
    ["il canottaggio", "赛艇", "oar sport", "topic"],
    ["il surf", "冲浪", "wave riding", "topic"],
    ["le immersioni", "潜水", "underwater sport", "topic"],
    ["l'arrampicata", "攀岩", "rock sport", "topic"],
    ["il pattinaggio", "滑冰", "ice sport", "topic"],
    ["lo skateboard", "滑板", "board", "topic"],
    ["il casco", "头盔", "head protection", "topic"],
    ["il trofeo", "奖杯", "prize cup", "topic"],
    ["il torneo", "锦标赛", "competition", "topic"],
    ["la semifinale", "半决赛", "match before final", "topic"],
    ["il fuorigioco", "越位", "offside", "topic"],
    ["il calcio d'angolo", "角球", "corner kick", "topic"],
    ["i tempi supplementari", "加时赛", "added time", "topic"],
    ["la musica classica", "古典音乐", "classical", "topic"],
    ["il jazz", "爵士乐", "jazz", "topic"],
    ["il rock", "摇滚", "rock", "topic"],
    ["la musica pop", "流行音乐", "pop", "topic"],
    ["la musica folk", "民谣", "folk", "topic"],
    ["il rap", "说唱", "rap", "topic"],
    ["l'album", "专辑", "record", "topic"],
    ["la band", "乐队", "group", "topic"],
    ["il batterista", "鼓手", "drum player", "topic"],
    ["il chitarrista", "吉他手", "guitar player", "topic"],
    ["il pianista", "钢琴家", "piano player", "topic"],
    ["il violinista", "小提琴手", "violin player", "topic"],
    ["il compositore", "作曲家", "music writer", "topic"],
    ["l'altoparlante", "扬声器", "speaker", "topic"],
    ["le cuffie", "耳机", "earphones", "topic"],
    ["britannico", "英国的", "from Britain", "topic"],
    ["irlandese", "爱尔兰的", "from Ireland", "topic"],
    ["scozzese", "苏格兰的", "from Scotland", "topic"],
    ["olandese", "荷兰的", "from the Netherlands", "topic"],
    ["belga", "比利时的", "from Belgium", "topic"],
    ["svizzero", "瑞士的", "from Switzerland", "topic"],
    ["austriaco", "奥地利的", "from Austria", "topic"],
    ["polacco", "波兰的", "from Poland", "topic"],
    ["ceco", "捷克的", "from Czechia", "topic"],
    ["ungherese", "匈牙利的", "from Hungary", "topic"],
    ["svedese", "瑞典的", "from Sweden", "topic"],
    ["norvegese", "挪威的", "from Norway", "topic"],
    ["danese", "丹麦的", "from Denmark", "topic"],
    ["finlandese", "芬兰的", "from Finland", "topic"],
    ["portoghese", "葡萄牙的", "from Portugal", "topic"],
    ["turco", "土耳其的", "from Turkey", "topic"],
    ["egiziano", "埃及的", "from Egypt", "topic"],
    ["marocchino", "摩洛哥的", "from Morocco", "topic"],
    ["indiano", "印度的", "from India", "topic"],
    ["coreano", "韩国的", "from Korea", "topic"],
    ["vietnamita", "越南的", "from Vietnam", "topic"],
    ["thailandese", "泰国的", "from Thailand", "topic"],
    ["australiano", "澳大利亚的", "from Australia", "topic"],
    ["canadese", "加拿大的", "from Canada", "topic"],
    ["messicano", "墨西哥的", "from Mexico", "topic"],
    ["brasiliano", "巴西的", "from Brazil", "topic"],
    ["argentino", "阿根廷的", "from Argentina", "topic"],
    ["lo scarabeo", "甲虫", "beetle", "topic"],
    ["la coccinella", "瓢虫", "ladybird", "topic"],
    ["la cavalletta", "蚱蜢", "grasshopper", "topic"],
    ["il grillo", "蟋蟀", "cricket", "topic"],
    ["la vespa", "黄蜂", "wasp", "topic"],
    ["la falena", "飞蛾", "moth", "topic"],
    ["la lumaca", "蜗牛", "snail", "topic"],
    ["la lumaca senza guscio", "鼻涕虫", "slug", "topic"],
    ["il verme", "蠕虫", "worm", "topic"],
    ["la lucertola", "蜥蜴", "lizard", "topic"],
    ["il coccodrillo", "鳄鱼", "crocodile", "topic"],
    ["il rospo", "蟾蜍", "toad", "topic"],
    ["la foca", "海豹", "seal", "topic"],
    ["il tricheco", "海象", "walrus", "topic"],
    ["lo squalo", "鲨鱼", "shark", "topic"],
    ["la medusa", "水母", "jellyfish", "topic"],
    ["la stella marina", "海星", "starfish", "topic"],
    ["il cavalluccio marino", "海马", "seahorse", "topic"],
    ["l'aragosta", "龙虾", "lobster", "topic"],
    ["il gamberetto", "虾", "shrimp", "topic"],
    ["la cozza", "贻贝", "mussel", "topic"],
    ["il calamaro", "鱿鱼", "squid", "topic"],
    ["la trota", "鳟鱼", "trout", "topic"],
    ["il salmone", "三文鱼", "salmon", "topic"],
    ["il merluzzo", "鳕鱼", "cod", "topic"],
    ["la sardina", "沙丁鱼", "sardine", "topic"],
    ["l'anguilla", "鳗鱼", "eel", "topic"],
    ["il pappagallo", "鹦鹉", "parrot", "topic"],
    ["il pinguino", "企鹅", "penguin", "topic"],
    ["lo struzzo", "鸵鸟", "ostrich", "topic"],
    ["la cicogna", "鹳", "stork", "topic"],
    ["l'airone", "鹭", "heron", "topic"],
    ["il gabbiano", "海鸥", "seagull", "topic"],
    ["il corvo", "乌鸦", "crow", "topic"],
    ["la gazza", "喜鹊", "magpie", "topic"],
    ["il picchio", "啄木鸟", "woodpecker", "topic"],
    ["il pettirosso", "知更鸟", "robin", "topic"],
    ["il piccione", "鸽子", "pigeon", "topic"],
    ["il tacchino", "火鸡", "turkey", "topic"],
    ["il pipistrello", "蝙蝠", "bat", "topic"],
    ["il riccio", "刺猬", "hedgehog", "topic"],
    ["lo scoiattolo", "松鼠", "squirrel", "topic"],
    ["la talpa", "鼹鼠", "mole", "topic"],
    ["il ratto", "大鼠", "rat", "topic"],
    ["il criceto", "仓鼠", "hamster", "topic"],
    ["il tasso", "獾", "badger", "topic"],
    ["la lontra", "水獭", "otter", "topic"],
    ["il castoro", "海狸", "beaver", "topic"],
    ["l'alce", "驼鹿", "moose", "topic"],
    ["la renna", "驯鹿", "reindeer", "topic"],
    ["il cinghiale", "野猪", "boar", "topic"],
    ["l'asino", "驴", "donkey", "topic"],
    ["il mulo", "骡子", "mule", "topic"],
    ["il pony", "小马", "pony", "topic"],
    ["il vitello", "小牛", "calf", "topic"],
    ["il gattino", "小猫", "kitten", "topic"],
    ["il cucciolo", "小狗", "puppy", "topic"],
    ["la giraffa", "长颈鹿", "giraffe", "topic"],
    ["la zebra", "斑马", "zebra", "topic"],
    ["il rinoceronte", "犀牛", "rhino", "topic"],
    ["il leopardo", "豹", "leopard", "topic"],
    ["il ghepardo", "猎豹", "cheetah", "topic"],
    ["il gorilla", "大猩猩", "gorilla", "topic"],
    ["il canguro", "袋鼠", "kangaroo", "topic"],
    ["il koala", "考拉", "koala", "topic"],
    ["il panda", "熊猫", "panda", "topic"],
    ["l'orso polare", "北极熊", "polar bear", "topic"],
    ["la balena", "鲸", "whale", "topic"],
    ["il delfino", "海豚", "dolphin", "topic"],
    ["la pelliccia", "毛皮", "fur", "topic"],
    ["l'artiglio", "爪子", "claw", "topic"],
    ["la zampa", "爪", "paw", "topic"],
    ["il becco", "喙", "beak", "topic"],
    ["la piuma", "羽毛", "feather", "topic"],
    ["l'ala", "翅膀", "wing", "topic"],
    ["la coda", "尾巴", "tail", "topic"],
    ["il corno", "角", "horn", "topic"],
    ["lo zoccolo", "蹄", "hoof", "topic"],
    ["la criniera", "鬃毛", "mane", "topic"],
    ["il guscio", "壳", "shell", "topic"],
    ["la pinna", "鳍", "fin", "topic"],
    ["il nido", "巢", "nest", "topic"],
    ["la tana", "兽穴", "den", "topic"],
    ["l'alveare", "蜂巢", "hive", "topic"],
    ["la mandria", "兽群", "herd", "topic"],
    ["il tulipano", "郁金香", "tulip", "topic"],
    ["la margherita", "雏菊", "daisy", "topic"],
    ["il giglio", "百合", "lily", "topic"],
    ["l'orchidea", "兰花", "orchid", "topic"],
    ["il papavero", "罂粟花", "poppy", "topic"],
    ["la lavanda", "薰衣草", "lavender", "topic"],
    ["l'edera", "常春藤", "ivy", "topic"],
    ["il muschio", "苔藓", "moss", "topic"],
    ["la felce", "蕨类", "fern", "topic"],
    ["il cactus", "仙人掌", "cactus", "topic"],
    ["il cespuglio", "灌木", "bush", "topic"],
    ["la siepe", "树篱", "hedge", "topic"],
    ["il prato", "草坪", "lawn", "topic"],
    ["l'erbaccia", "杂草", "weed", "topic"],
    ["il germoglio", "花蕾", "bud", "topic"],
    ["il petalo", "花瓣", "petal", "topic"],
    ["lo stelo", "茎", "stem", "topic"],
    ["la spina", "刺", "thorn", "topic"],
    ["la corteccia", "树皮", "bark", "topic"],
    ["il rametto", "细枝", "twig", "topic"],
    ["la betulla", "桦树", "birch", "topic"],
    ["il faggio", "山毛榉", "beech", "topic"],
    ["l'acero", "枫树", "maple", "topic"],
    ["il salice", "柳树", "willow", "topic"],
    ["il pioppo", "杨树", "poplar", "topic"],
    ["l'abete", "冷杉", "fir", "topic"],
    ["il cipresso", "柏树", "cypress", "topic"],
    ["la palma", "棕榈树", "palm", "topic"],
    ["la castagna", "栗子", "chestnut", "topic"],
    ["la noce", "核桃", "walnut", "topic"],
    ["la mandorla", "杏仁", "almond", "topic"],
    ["la nocciola", "榛子", "hazelnut", "topic"],
    ["la prugna", "李子", "plum", "topic"],
    ["il fico", "无花果", "fig", "topic"],
    ["il melone", "甜瓜", "melon", "topic"],
    ["l'ananas", "菠萝", "pineapple", "topic"],
    ["il mango", "芒果", "mango", "topic"],
    ["la noce di cocco", "椰子", "coconut", "topic"],
    ["il lampone", "覆盆子", "raspberry", "topic"],
    ["il mirtillo", "蓝莓", "blueberry", "topic"],
    ["il pompelmo", "柚子", "grapefruit", "topic"],
    ["la zucca", "南瓜", "pumpkin", "topic"],
    ["il cetriolo", "黄瓜", "cucumber", "topic"],
    ["il peperone", "甜椒", "pepper", "topic"],
    ["la zucchina", "西葫芦", "courgette", "topic"],
    ["il cavolo", "卷心菜", "cabbage", "topic"],
    ["il cavolfiore", "花椰菜", "cauliflower", "topic"],
    ["i broccoli", "西兰花", "broccoli", "topic"],
    ["il sedano", "芹菜", "celery", "topic"],
    ["il porro", "韭葱", "leek", "topic"],
    ["il pisello", "豌豆", "pea", "topic"],
    ["il fagiolo", "豆", "bean", "topic"],
    ["la lenticchia", "扁豆", "lentil", "topic"],
    ["il cece", "鹰嘴豆", "chickpea", "topic"],
    ["il mais", "玉米", "corn", "topic"],
    ["l'avena", "燕麦", "oats", "topic"],
    ["l'orzo", "大麦", "barley", "topic"],
    ["la segale", "黑麦", "rye", "topic"],
    ["il camino", "烟囱", "chimney", "topic"],
    ["la grondaia", "排水沟", "gutter", "topic"],
    ["la soffitta", "阁楼", "attic", "topic"],
    ["il portico", "门廊", "porch", "topic"],
    ["la recinzione", "栅栏", "fence", "topic"],
    ["il cancello", "大门", "gate", "topic"],
    ["il vialetto", "车道", "driveway", "topic"],
    ["il capanno", "棚屋", "shed", "topic"],
    ["il campanello", "门铃", "doorbell", "topic"],
    ["la serratura", "锁", "lock", "topic"],
    ["il cardine", "铰链", "hinge", "topic"],
    ["la maniglia", "把手", "handle", "topic"],
    ["la persiana", "百叶窗", "shutter", "topic"],
    ["la tapparella", "窗帘", "blind", "topic"],
    ["la carta da parati", "壁纸", "wallpaper", "topic"],
    ["il soffitto", "天花板", "ceiling", "topic"],
    ["l'asse del pavimento", "地板条", "floorboard", "topic"],
    ["il termosifone", "暖气片", "radiator", "topic"],
    ["la caldaia", "锅炉", "boiler", "topic"],
    ["l'interruttore", "开关", "switch", "topic"],
    ["la lampadina", "灯泡", "bulb", "topic"],
    ["il fusibile", "保险丝", "fuse", "topic"],
    ["il cavo", "电缆", "cable", "topic"],
    ["il contatore", "电表", "meter", "topic"],
    ["la bolletta", "账单", "utility bill", "topic"],
    ["il padrone di casa", "房东", "landlord", "topic"],
    ["l'inquilino", "房客", "tenant", "topic"],
    ["il contratto d'affitto", "租约", "lease", "topic"],
    ["il trasloco", "搬家", "move", "topic"],
    ["il cassetto", "抽屉", "drawer", "topic"],
    ["lo schedario", "文件柜", "filing cabinet", "topic"],
    ["la cucitrice", "订书机", "stapler", "topic"],
    ["la graffetta", "回形针", "paper clip", "topic"],
    ["il post-it", "便利贴", "sticky note", "topic"],
    ["l'evidenziatore", "荧光笔", "highlighter", "topic"],
    ["la busta", "信封", "envelope", "topic"],
    ["la fotocopiatrice", "复印机", "photocopier", "topic"],
    ["il distruggidocumenti", "碎纸机", "shredder", "topic"],
    ["la lavagna bianca", "白板", "whiteboard", "topic"],
    ["il proiettore", "投影仪", "projector", "topic"],
    ["il calendario", "日历", "calendar", "topic"],
    ["il badge", "工牌", "badge", "topic"],
    ["lo stagista", "实习生", "intern", "topic"],
    ["il receptionist", "前台", "receptionist", "topic"],
    ["la crudeltà", "残忍", "cruelty", "topic"],
    ["l'onestà", "诚实", "honesty", "topic"],
    ["la lealtà", "忠诚", "loyalty", "topic"],
    ["la pazienza", "耐心", "patience", "topic"],
    ["la saggezza", "智慧", "wisdom", "topic"],
    ["l'avidità", "贪婪", "greed", "topic"],
    ["la pigrizia", "懒惰", "laziness", "topic"],
    ["la testardaggine", "固执", "stubbornness", "topic"],
    ["la creatività", "创造力", "creativity", "topic"],
    ["la stupidità", "愚蠢", "stupidity", "topic"],
    ["la follia", "疯狂", "madness", "topic"],
    ["la bruttezza", "丑", "ugliness", "topic"],
    ["la debolezza", "弱点", "weakness", "topic"],
    ["la lentezza", "缓慢", "slowness", "topic"],
    ["il silenzio", "寂静", "silence", "topic"],
    ["il rumore", "噪音", "noise", "topic"],
    ["l'oscurità", "黑暗", "darkness", "topic"],
    ["la luminosità", "明亮", "brightness", "topic"],
    ["la freddezza", "冷淡", "coldness", "topic"],
    ["la morbidezza", "柔软", "softness", "topic"],
    ["la pulizia", "清洁", "cleanliness", "topic"],
    ["lo sporco", "污垢", "dirt", "topic"],
    ["la fortuna", "运气", "luck", "topic"],
    ["la sfortuna", "不幸", "misfortune", "topic"],
    ["la routine", "例行公事", "routine", "topic"],
    ["il rischio", "风险", "risk", "topic"],
    ["il vantaggio", "优势", "advantage", "topic"],
    ["lo scopo", "目的", "purpose", "topic"],
    ["la ragione", "原因", "reason", "topic"],
    ["la scusa", "借口", "excuse", "topic"],
    ["la barzelletta", "笑话", "joke", "topic"],
    ["la bugia", "谎言", "lie", "topic"],
    ["il litigio", "争吵", "quarrel", "topic"],
    ["il favore", "恩惠", "favour", "topic"],
    ["l'incubo", "噩梦", "nightmare", "topic"],
    ["l'infanzia", "童年", "childhood", "topic"],
    ["l'adolescenza", "青春期", "adolescence", "topic"],
    ["l'età adulta", "成年", "adulthood", "topic"]
  );
})();
