/* =====================================================
   FUGA MYTHICA — CURSUS Latin 🏛️ · extra batch 4
   The mid-frequency families of batch 5 (English/Romance) in their Latin originals.
   ===================================================== */
(function () {
  Object.assign(LATIN_EXTRA.roots, {
    alius: ["ali- / alter-", "其他", "other"], angulus: ["angul- / angust-", "角,窄", "angle; narrow"], aperio: ["aper- / apert-", "开", "open"], arcus: ["arc-", "弓", "bow"],
    arma2: ["arm-", "武器", "weapon"], basis: ["bas-", "底", "base"], campus: ["camp-", "田野", "field"], castus: ["cast-", "纯洁", "pure"],
    cavus: ["cav-", "空", "hollow"], celo: ["cel- / cult-", "藏", "hide"], celer: ["celer-", "快", "swift"], cerno: ["cern- / cret-", "分辨", "sift, decide"],
    charta: ["chart-", "纸", "paper"], cingo: ["cing- / cinct-", "束", "gird"], circus: ["circ-", "圈", "circle"], clarus2: ["clar-", "明", "clear"],
    clavis: ["clav-", "钥匙", "key"], copia: ["copi-", "丰富", "plenty"], corona: ["coron-", "冠", "crown"], crimen: ["crimin-", "罪", "charge"],
    crux: ["cruc-", "十字", "cross"], cumulus: ["cumul-", "堆", "heap"], custos: ["custod-", "看守", "guard"], damnum2: ["damn-", "损害", "harm"],
    decet: ["dec- / decor-", "得体", "fitting"], densus: ["dens-", "密", "thick"], dexter: ["dexter-", "右", "right"], digitus: ["digit-", "指", "finger"],
    duo: ["du- / dupl-", "二", "two"], emineo: ["emin- / min-", "突出", "jut out"], filum: ["fil-", "线", "thread"], firmus: ["firm-", "牢", "steady"],
    fiscus: ["fisc-", "国库", "treasury"], focus: ["foc-", "炉", "hearth"], frons: ["front-", "前额", "forehead"], fructus: ["fruct- / frug-", "果", "fruit"],
    gelu: ["gel- / glaci-", "冻", "freeze"], grandis: ["grand-", "大", "great"], heres: ["hered-", "继承", "heir"], horreo: ["horr-", "颤抖", "shudder"],
    insula: ["insul-", "岛", "island"], ira: ["ir-", "怒", "anger"], lavo: ["lav- / lut- / luv-", "洗", "wash"], libra: ["libr-", "秤", "balance"],
    limen: ["limin- / limit-", "门槛,界", "threshold"], linea: ["line-", "线", "line"], luna: ["lun-", "月", "moon"], maturus: ["matur-", "熟", "ripe"],
    membrum: ["membr-", "肢", "limb"], mola: ["mol-", "磨", "mill"], mos: ["mor-", "习俗", "custom"], nervus: ["nerv-", "神经,筋", "sinew"],
    nox: ["noct-", "夜", "night"], octo: ["oct-", "八", "eight"], oleo: ["ol- / odor-", "闻", "smell"], orbis: ["orb-", "圆", "circle"],
    ovum: ["ov-", "卵", "egg"], pallidus: ["pall-", "苍白", "pale"], paucus: ["pauc- / pauper-", "少", "few"], pecco: ["pecc-", "犯错", "sin"],
    pila: ["pil-", "柱,球", "pillar, ball"], planus: ["plan-", "平", "flat"], plebs: ["pleb-", "平民", "common people"], ploro: ["plor-", "哭喊", "cry out"],
    plumbum: ["plumb-", "铅", "lead"], praeda: ["praed-", "掠夺", "prey"], proprius: ["propri-", "自己的", "one's own"], proximus: ["prox- / prop-", "近", "near"],
    pudor: ["pud-", "羞", "shame"], quattuor: ["quadr- / quart-", "四", "four"], quies: ["quies- / quiet-", "静", "rest"], quot: ["quot-", "多少", "how many"],
    rarus: ["rar-", "稀", "rare"], rigeo: ["rig-", "硬", "stiff"], ripa: ["rip- / riv-", "河岸", "river bank"], robur: ["robor-", "橡,强", "oak, strong"],
    rudis: ["rud-", "粗", "raw"], scrutor: ["scrut-", "细查", "search"], septem: ["sept-", "七", "seven"], sero2: ["ser- / sert-", "连接", "join"],
    sidus: ["sider-", "星", "star"], singulus: ["singul-", "单", "single"], sinus: ["sinu-", "弯", "curve"], solidus: ["solid-", "固", "solid"],
    sorbeo: ["sorb-", "吸", "suck in"], splendeo: ["splend-", "光辉", "shine"], studeo: ["stud-", "热心,学", "zeal, study"], suadeo: ["suad- / suas-", "劝", "urge"],
    talis: ["tal-", "如此", "such"], tardus: ["tard-", "慢", "slow"], tego: ["teg- / tect-", "盖", "cover"], tenuis: ["tenu-", "薄", "thin"],
    tollo: ["toll- / tol-", "举", "lift"], tonus: ["ton-", "音", "tone"], totus: ["tot-", "全", "whole"], trudo: ["trud- / trus-", "推", "thrust"],
    tumeo: ["tum-", "肿", "swell"], unguo: ["ungu- / unct-", "涂", "smear"], vapor: ["vapor-", "汽", "steam"], varius: ["vari-", "变", "vary"],
    veho: ["veh- / vect-", "运", "carry"], velum: ["vel-", "遮,帆", "veil, sail"], velox: ["veloc-", "快", "swift"], verbum: ["verb-", "词", "word"],
    vergo: ["verg-", "倾向", "bend"], vicis: ["vic-", "代替", "turn, substitute"], vicinus: ["vicin-", "邻", "near"], vilis: ["vil-", "贱", "cheap"],
    vinum: ["vin-", "酒", "wine"], voveo: ["vov- / vot-", "誓", "vow"],
  });
  LATIN_EXTRA.words.push(
    ["alius","其他的","other","alius"], ["alter","另一个","the other","alius"], ["alienus","别人的","belonging to another","alius"], ["alieno","疏远","alienate","alius"], ["alibi","在别处","elsewhere","alius"], ["alias","另一次","at another time","alius"], ["alterno","交替","alternate","alius"], ["altero","改变","alter","alius"],
    ["angulus","角","angle","angulus"], ["angustus","狭窄的","narrow","angulus"], ["angustia","狭窄,困境","narrowness; distress","angulus"], ["ango","使窒息,使痛苦","choke; distress","angulus"], ["anxius","焦虑的","anxious","angulus"], ["triangulus","三角的","triangular","angulus"],
    ["aperio","打开","open","aperio"], ["apertus","开着的","open","aperio"], ["apertura","开口","opening","aperio"], ["Aprilis","四月","April","aperio"], ["operio","盖住","cover","aperio"], ["cooperio","覆盖","cover over","aperio"],
    ["arcus","弓,拱","bow, arch","arcus"], ["arcuatus","弓形的","arched","arcus"], ["arcarius","弓箭手","archer","arcus"],
    ["arma","武器","arms","arma2"], ["armo","武装","arm","arma2"], ["armatus","武装的","armed","arma2"], ["armatura","装备","armour","arma2"], ["armilla","手镯","bracelet","arma2"], ["inermis","无武装的","unarmed","arma2"],
    ["basis","基础","base","basis"], ["basilica","大会堂","basilica","basis"],
    ["campus","田野","field","campus"], ["campester","平原的","of the plain","campus"], ["campio","斗士","champion","campus"],
    ["castus","纯洁的","chaste","castus"], ["castitas","贞洁","chastity","castus"], ["castigo","惩戒","chastise","castus"], ["incestus","不洁的","impure","castus"], ["castellum","堡垒","fort","castus"], ["castra","军营","camp","castus"],
    ["cavus","空的","hollow","cavus"], ["cavea","笼,洞","cage; hollow","cavus"], ["caverna","洞穴","cavern","cavus"], ["cavo","挖空","hollow out","cavus"], ["excavo","挖出","excavate","cavus"], ["concavus","凹的","concave","cavus"],
    ["celo","藏","hide","celo"], ["occulo","隐藏","conceal","celo"], ["occultus","隐藏的","hidden","celo"], ["cella","小室","chamber","celo"], ["cellula","小房间","small cell","celo"], ["clam","秘密地","secretly","celo"], ["clandestinus","秘密的","clandestine","celo"],
    ["celer","快的","swift","celer"], ["celeritas","速度","speed","celer"], ["accelero","加速","accelerate","celer"], ["celeriter","迅速地","quickly","celer"],
    ["cerno","分辨","distinguish","cerno"], ["decerno","决定","decide","cerno"], ["decretum","法令","decree","cerno"], ["discerno","辨别","discern","cerno"], ["secerno","分开","separate","cerno"], ["secretus","秘密的","secret","cerno"], ["excerno","筛出","sift out","cerno"], ["certus","确定的","certain","cerno"], ["certo","竞争","contend","cerno"], ["certamen","竞赛","contest","cerno"], ["crimen","指控","charge","cerno"], ["discrimen","区分,危机","distinction; crisis","cerno"], ["concerno","涉及","concern","cerno"],
    ["charta","纸","paper","charta"], ["chartula","小纸片","small paper","charta"],
    ["cingo","束","gird","cingo"], ["cinctus","腰带","belt","cingo"], ["cingulum","带子","girdle","cingo"], ["praecingo","围绕","gird","cingo"], ["succinctus","简洁的","succinct","cingo"],
    ["circus","圆,竞技场","circle; circus","circus"], ["circulus","小圆","circle","circus"], ["circum","环绕","around","circus"], ["circuitus","环绕","circuit","circus"], ["circulor","聚集","gather round","circus"],
    ["clarus","明亮的","clear","clarus2"], ["claritas","清晰","clarity","clarus2"], ["declaro","宣布","declare","clarus2"], ["clareo","发光","shine","clarus2"], ["praeclarus","杰出的","illustrious","clarus2"],
    ["clavis","钥匙","key","clavis"], ["clavus","钉","nail","clavis"], ["clavicula","小钥匙,锁骨","little key; collarbone","clavis"], ["conclave","密室","locked room","clavis"],
    ["copia","丰富","plenty","copia"], ["copiosus","丰富的","copious","copia"], ["copiae","军队","troops","copia"], ["inopia","缺乏","want","copia"], ["inops","贫乏的","destitute","copia"],
    ["corona","冠","crown","corona"], ["corono","加冕","crown","corona"], ["coronarius","花冠的","of garlands","corona"],
    ["crimen","罪","crime","crimen"], ["criminalis","犯罪的","criminal","crimen"], ["criminor","控告","accuse","crimen"], ["discrimino","区分","distinguish","crimen"],
    ["crux","十字架","cross","crux"], ["crucio","折磨","torture","crux"], ["cruciatus","酷刑","torture","crux"], ["excrucio","折磨","torment","crux"], ["crucifigo","钉十字架","crucify","crux"],
    ["cumulus","堆","heap","cumulus"], ["cumulo","堆积","heap up","cumulus"], ["accumulo","积累","accumulate","cumulus"],
    ["custos","守卫","guard","custos"], ["custodia","监护","custody","custos"], ["custodio","看守","guard","custos"],
    ["damnum","损失","loss","damnum2"], ["damno","定罪","condemn","damnum2"], ["indemnis","未受损的","unharmed","damnum2"], ["condemno","判罪","condemn","damnum2"],
    ["decet","适合","it is fitting","decet"], ["decor","优雅","grace","decet"], ["decorus","得体的","seemly","decet"], ["decoro","装饰","adorn","decet"], ["decus","荣誉","honour","decet"], ["dedecus","耻辱","disgrace","decet"],
    ["densus","密的","dense","densus"], ["densitas","密度","density","densus"], ["condenso","压缩","condense","densus"],
    ["dexter","右的","right","dexter"], ["dextra","右手","right hand","dexter"], ["dexteritas","灵巧","dexterity","dexter"], ["ambidexter","双手灵巧的","ambidextrous","dexter"],
    ["digitus","手指","finger","digitus"], ["digitalis","手指的","of a finger","digitus"], ["digitulus","小指","little finger","digitus"],
    ["duo","二","two","duo"], ["duplex","双重的","double","duo"], ["duplico","加倍","double","duo"], ["dubius","可疑的","doubtful","duo"], ["dubito","怀疑","doubt","duo"], ["duellum","决斗","duel","duo"], ["duodecim","十二","twelve","duo"], ["bis","两次","twice","duo"],
    ["emineo","突出","stand out","emineo"], ["eminens","杰出的","eminent","emineo"], ["promineo","突出","project","emineo"], ["immineo","逼近","threaten","emineo"], ["imminens","即将的","imminent","emineo"],
    ["filum","线","thread","filum"], ["filamentum","细丝","filament","filum"], ["filatim","一线一线地","thread by thread","filum"],
    ["firmus","牢固的","firm","firmus"], ["firmo","加固","strengthen","firmus"], ["firmitas","牢固","firmness","firmus"], ["affirmo","肯定","affirm","firmus"], ["confirmo","确认","confirm","firmus"], ["infirmus","虚弱的","weak","firmus"], ["infirmitas","虚弱","weakness","firmus"], ["firmamentum","支撑,苍穹","support; firmament","firmus"],
    ["fiscus","国库","treasury","fiscus"], ["fiscalis","财政的","fiscal","fiscus"], ["confisco","没收","confiscate","fiscus"],
    ["focus","炉","hearth","focus"], ["focarius","炉边的","of the hearth","focus"],
    ["frons","前额","forehead","frons"], ["frontalis","前额的","frontal","frons"], ["confronto","对质","confront","frons"], ["effrons","厚颜的","shameless","frons"],
    ["fructus","果实","fruit","fructus"], ["fruor","享受","enjoy","fructus"], ["fructuosus","多产的","fruitful","fructus"], ["frugalis","节俭的","frugal","fructus"], ["frux","谷物","crops","fructus"], ["frumentum","谷物","grain","fructus"],
    ["gelu","冰","frost","gelu"], ["gelidus","冰冷的","icy","gelu"], ["gelo","冻","freeze","gelu"], ["congelo","冻结","congeal","gelu"], ["glacies","冰","ice","gelu"], ["glacialis","冰的","icy","gelu"],
    ["grandis","大的","great","grandis"], ["grandaevus","高龄的","aged","grandis"], ["grandio","扩大","enlarge","grandis"], ["grando","冰雹","hail","grandis"],
    ["heres","继承人","heir","heres"], ["hereditas","遗产","inheritance","heres"], ["hereditarius","继承的","hereditary","heres"], ["exheredo","剥夺继承权","disinherit","heres"],
    ["horreo","颤抖","shudder","horreo"], ["horror","恐怖","horror","horreo"], ["horridus","可怕的","horrid","horreo"], ["horribilis","可怕的","horrible","horreo"], ["abhorreo","憎恶","abhor","horreo"], ["horrendus","可怕的","dreadful","horreo"],
    ["insula","岛,公寓楼","island; tenement","insula"], ["insularis","岛的","insular","insula"], ["paeninsula","半岛","peninsula","insula"],
    ["ira","怒","anger","ira"], ["iratus","愤怒的","angry","ira"], ["irascor","发怒","get angry","ira"], ["iracundus","易怒的","irascible","ira"], ["irascibilis","易怒的","irascible","ira"],
    ["lavo","洗","wash","lavo"], ["lavatio","洗涤","washing","lavo"], ["lavacrum","浴池","bath","lavo"], ["lotio","洗","washing","lavo"], ["diluo","稀释","dilute","lavo"], ["diluvium","洪水","flood","lavo"], ["abluo","洗去","wash away","lavo"], ["ablutio","洗涤","ablution","lavo"], ["lutum","泥","mud","lavo"],
    ["libra","秤,磅","balance; pound","libra"], ["libro","称量","weigh","libra"], ["delibero","考虑","deliberate","libra"], ["deliberatio","考虑","deliberation","libra"], ["aequilibrium","平衡","equilibrium","libra"],
    ["limen","门槛","threshold","limen"], ["limes","边界","boundary","limen"], ["limito","限制","limit","limen"], ["elimino","逐出","eliminate","limen"], ["sublimis","崇高的","sublime","limen"], ["praeliminaris","初步的","preliminary","limen"],
    ["linea","线","line","linea"], ["linum","亚麻","flax","linea"], ["lineamentum","轮廓","outline","linea"], ["delineo","描绘","delineate","linea"], ["linearis","线性的","linear","linea"],
    ["luna","月亮","moon","luna"], ["lunaris","月球的","lunar","luna"], ["lunaticus","疯的","moonstruck","luna"], ["dies Lunae","星期一","Monday","luna"],
    ["maturus","成熟的","ripe","maturus"], ["maturo","使成熟","ripen","maturus"], ["maturitas","成熟","maturity","maturus"], ["praematurus","过早的","premature","maturus"], ["immaturus","未熟的","immature","maturus"],
    ["membrum","肢体","limb","membrum"], ["membrana","膜","membrane","membrum"], ["membratim","一肢一肢地","limb by limb","membrum"],
    ["mola","磨石","millstone","mola"], ["molo","磨","grind","mola"], ["molaris","磨的","of a mill","mola"], ["molendinum","磨坊","mill","mola"], ["moles","巨物","mass","mola"], ["molestus","烦人的","troublesome","mola"], ["demolior","拆毁","demolish","mola"],
    ["mos","习俗","custom","mos"], ["mores","风俗","morals","mos"], ["moralis","道德的","moral","mos"], ["morosus","挑剔的","peevish","mos"], ["immoralis","不道德的","immoral","mos"],
    ["nervus","筋,神经","sinew","nervus"], ["nervosus","多筋的","sinewy","nervus"], ["enervo","使衰弱","enervate","nervus"],
    ["nox","夜","night","nox"], ["nocturnus","夜间的","nocturnal","nox"], ["noctu","在夜里","by night","nox"], ["aequinoctium","昼夜平分","equinox","nox"], ["pernocto","过夜","spend the night","nox"], ["noctua","猫头鹰","owl","nox"],
    ["octo","八","eight","octo"], ["octavus","第八","eighth","octo"], ["October","十月","October","octo"], ["octoginta","八十","eighty","octo"],
    ["oleo","有气味","smell","oleo"], ["odor","气味","smell","oleo"], ["odoratus","嗅觉","sense of smell","oleo"], ["olfacio","嗅","smell","oleo"], ["redoleo","散发香气","be fragrant","oleo"], ["odorus","芳香的","fragrant","oleo"],
    ["orbis","圆,世界","circle; world","orbis"], ["orbita","轨道","track","orbis"], ["orbiculus","小圆","small circle","orbis"], ["exorbito","越轨","go off track","orbis"],
    ["ovum","卵","egg","ovum"], ["ovalis","卵形的","oval","ovum"], ["ovarium","卵巢","ovary","ovum"],
    ["pallidus","苍白的","pale","pallidus"], ["palleo","苍白","be pale","pallidus"], ["pallor","苍白","pallor","pallidus"],
    ["paucus","少的","few","paucus"], ["paucitas","缺乏","fewness","paucus"], ["pauper","穷的","poor","paucus"], ["paupertas","贫穷","poverty","paucus"], ["paulus","小的","little","paucus"], ["paulum","一点","a little","paucus"],
    ["pecco","犯错","sin","pecco"], ["peccatum","罪","sin","pecco"], ["peccator","罪人","sinner","pecco"], ["impeccabilis","无过失的","impeccable","pecco"],
    ["pila","球,柱","ball; pillar","pila"], ["pilum","标枪","javelin","pila"], ["compilo","抢劫,汇编","plunder; compile","pila"], ["pilarius","柱","pillar","pila"],
    ["planus","平的","flat","planus"], ["planities","平原","plain","planus"], ["explano","解释","explain","planus"], ["planeta","行星","planet","planus"], ["planta","脚掌,植物","sole; plant","planus"], ["planto","种植","plant","planus"],
    ["plebs","平民","common people","plebs"], ["plebeius","平民的","plebeian","plebs"], ["plebiscitum","公民决议","plebiscite","plebs"],
    ["ploro","哭喊","wail","ploro"], ["deploro","哀叹","deplore","ploro"], ["exploro","探查","explore","ploro"], ["explorator","侦察兵","scout","ploro"], ["imploro","恳求","implore","ploro"],
    ["plumbum","铅","lead","plumbum"], ["plumbeus","铅的","leaden","plumbum"], ["plumbarius","铅工","plumber","plumbum"],
    ["praeda","战利品,猎物","booty; prey","praeda"], ["praedor","掠夺","plunder","praeda"], ["praedo","强盗","robber","praeda"], ["praedator","掠夺者","plunderer","praeda"], ["depraedor","劫掠","pillage","praeda"],
    ["proprius","自己的","one's own","proprius"], ["proprietas","特性,财产","property","proprius"], ["proprie","恰当地","properly","proprius"], ["approprio","据为己有","appropriate","proprius"],
    ["proximus","最近的","nearest","proximus"], ["prope","近","near","proximus"], ["propinquus","邻近的,亲戚","near; relative","proximus"], ["appropinquo","接近","approach","proximus"], ["proximitas","接近","proximity","proximus"], ["propter","由于","because of","proximus"],
    ["pudor","羞耻","shame","pudor"], ["pudet","感到羞耻","it shames","pudor"], ["pudicus","端庄的","modest","pudor"], ["impudens","无耻的","shameless","pudor"], ["repudio","拒绝","repudiate","pudor"],
    ["quattuor","四","four","quattuor"], ["quartus","第四","fourth","quattuor"], ["quadratus","方的","square","quattuor"], ["quadrans","四分之一","quarter","quattuor"], ["quadraginta","四十","forty","quattuor"], ["quadrupes","四足的","four-footed","quattuor"], ["quaternio","四人组","group of four","quattuor"],
    ["quies","休息","rest","quies"], ["quietus","安静的","quiet","quies"], ["quiesco","休息","rest","quies"], ["acquiesco","默许","acquiesce","quies"], ["tranquillus","宁静的","tranquil","quies"], ["tranquillitas","宁静","tranquillity","quies"], ["inquietus","不安的","restless","quies"], ["requies","安息","rest","quies"], ["requiesco","安息","rest","quies"],
    ["quot","多少","how many","quot"], ["quota","份额","share","quot"], ["quotiens","多少次","how often","quot"], ["quotidianus","每日的","daily","quot"],
    ["rarus","稀有的","rare","rarus"], ["raritas","稀有","rarity","rarus"], ["raro","很少","rarely","rarus"], ["rarefacio","使稀薄","rarefy","rarus"],
    ["rigeo","僵硬","be stiff","rigeo"], ["rigidus","僵硬的","rigid","rigeo"], ["rigor","严格,僵硬","rigour","rigeo"], ["rigidus","严格的","strict","rigeo"],
    ["ripa","河岸","bank","ripa"], ["riparius","河岸的","riparian","ripa"], ["rivus","小溪","stream","ripa"], ["rivalis","竞争者","rival","ripa"], ["derivo","引流","derive","ripa"],
    ["robur","橡木,力量","oak; strength","robur"], ["robustus","强健的","robust","robur"], ["roboro","加强","strengthen","robur"], ["corroboro","加固","corroborate","robur"],
    ["rudis","粗糙的","raw","rudis"], ["rudimentum","初步","rudiment","rudis"], ["erudio","教育","educate","rudis"], ["eruditus","博学的","learned","rudis"], ["eruditio","博学","erudition","rudis"],
    ["scrutor","细查","search","scrutor"], ["scrutinium","审查","scrutiny","scrutor"], ["perscrutor","彻查","examine thoroughly","scrutor"], ["inscrutabilis","不可测的","inscrutable","scrutor"],
    ["septem","七","seven","septem"], ["septimus","第七","seventh","septem"], ["September","九月","September","septem"], ["septuaginta","七十","seventy","septem"],
    ["sero","连接","join","sero2"], ["series","系列","series","sero2"], ["sermo","谈话","talk","sero2"], ["assero","断言","assert","sero2"], ["desero","抛弃","desert","sero2"], ["desertus","荒废的","deserted","sero2"], ["dissero","讨论","discuss","sero2"], ["dissertatio","论述","dissertation","sero2"], ["exsero","伸出","thrust out","sero2"], ["insero","插入","insert","sero2"],
    ["sidus","星","star","sidus"], ["sidereus","星的","starry","sidus"], ["considero","考虑","consider","sidus"], ["consideratio","考虑","consideration","sidus"], ["desidero","渴望","desire","sidus"], ["desiderium","渴望","longing","sidus"],
    ["singulus","单个的","single","singulus"], ["singularis","单数的,独特的","singular","singulus"], ["singulatim","一个一个地","one by one","singulus"],
    ["sinus","弯,胸","curve; bosom","sinus"], ["sinuosus","蜿蜒的","sinuous","sinus"], ["insinuo","插入","insinuate","sinus"],
    ["solidus","固体的","solid","solidus"], ["soliditas","坚固","solidity","solidus"], ["solido","加固","consolidate","solidus"], ["consolido","巩固","consolidate","solidus"],
    ["sorbeo","吸","suck in","sorbeo"], ["absorbeo","吸收","absorb","sorbeo"], ["resorbeo","再吸收","reabsorb","sorbeo"],
    ["splendeo","发光","shine","splendeo"], ["splendidus","灿烂的","splendid","splendeo"], ["splendor","光辉","splendour","splendeo"], ["resplendeo","闪耀","shine brightly","splendeo"],
    ["studeo","热心","be eager","studeo"], ["studium","热情,学习","zeal; study","studeo"], ["studiosus","勤奋的","studious","studeo"],
    ["suadeo","劝","urge","suadeo"], ["persuadeo","说服","persuade","suadeo"], ["persuasio","说服","persuasion","suadeo"], ["dissuadeo","劝阻","dissuade","suadeo"], ["suavis","甜美的","sweet","suadeo"], ["suavitas","甜美","sweetness","suadeo"],
    ["talis","这样的","such","talis"], ["talio","报复","retaliation","talis"], ["talea","切段","cutting","talis"], ["talentum","塔兰特,天赋","talent","talis"],
    ["tardus","慢的","slow","tardus"], ["tardo","延迟","delay","tardus"], ["tarditas","缓慢","slowness","tardus"], ["retardo","阻延","retard","tardus"],
    ["tego","盖","cover","tego"], ["tectum","屋顶","roof","tego"], ["protego","保护","protect","tego"], ["protectio","保护","protection","tego"], ["detego","揭露","uncover","tego"], ["tegula","瓦","tile","tego"], ["integumentum","覆盖物","covering","tego"], ["toga","托加袍","toga","tego"],
    ["tenuis","薄的","thin","tenuis"], ["tenuitas","薄","thinness","tenuis"], ["attenuo","减弱","weaken","tenuis"], ["extenuo","减轻","lessen","tenuis"],
    ["tollo","举起","lift","tollo"], ["extollo","抬高","extol","tollo"], ["tolero","忍受","tolerate","tollo"], ["tolerantia","忍耐","tolerance","tollo"], ["tolerabilis","可忍受的","tolerable","tollo"], ["intolerabilis","无法忍受的","intolerable","tollo"],
    ["tonus","音调","tone","tonus"], ["tono","打雷","thunder","tonus"], ["tonitrus","雷","thunder","tonus"], ["intono","吟诵","intone","tonus"], ["detono","停止打雷","cease thundering","tonus"],
    ["totus","全部的","whole","totus"], ["totalis","全部的","total","totus"], ["totaliter","完全地","totally","totus"],
    ["trudo","推","thrust","trudo"], ["intrudo","闯入","intrude","trudo"], ["extrudo","挤出","extrude","trudo"], ["protrudo","突出","protrude","trudo"], ["abstrudo","藏","hide away","trudo"], ["abstrusus","深奥的","abstruse","trudo"],
    ["tumeo","肿","swell","tumeo"], ["tumor","肿胀","swelling","tumeo"], ["tumultus","骚动","tumult","tumeo"], ["tumulus","坟丘","mound","tumeo"], ["tumidus","肿胀的","swollen","tumeo"],
    ["unguo","涂油","anoint","unguo"], ["unguentum","软膏","ointment","unguo"], ["unctio","涂油","anointing","unguo"], ["unctus","涂了油的","anointed","unguo"],
    ["vapor","蒸汽","steam","vapor"], ["vaporo","蒸发","steam","vapor"], ["evaporo","蒸发","evaporate","vapor"], ["vapidus","走味的","flat","vapor"],
    ["varius","多样的","various","varius"], ["vario","变化","vary","varius"], ["varietas","多样性","variety","varius"], ["variabilis","可变的","variable","varius"], ["invariabilis","不变的","invariable","varius"],
    ["veho","运","carry","veho"], ["vehiculum","车","vehicle","veho"], ["vehemens","激烈的","vehement","veho"], ["vector","乘客,承运者","carrier","veho"], ["conveho","运到一起","bring together","veho"], ["convexus","凸的","convex","veho"], ["inveho","运入,攻击","carry in; attack","veho"], ["invectiva","辱骂","invective","veho"], ["vexo","骚扰","vex","veho"],
    ["velum","帆,幕","sail; veil","velum"], ["velo","遮盖","veil","velum"], ["revelo","揭示","reveal","velum"], ["revelatio","启示","revelation","velum"], ["velarium","天幕","awning","velum"],
    ["velox","快的","swift","velox"], ["velocitas","速度","speed","velox"], ["velociter","迅速地","swiftly","velox"],
    ["verbum","词","word","verbum"], ["verbalis","言语的","verbal","verbum"], ["proverbium","谚语","proverb","verbum"], ["adverbium","副词","adverb","verbum"], ["verbosus","啰嗦的","wordy","verbum"], ["verbatim","逐字地","word for word","verbum"],
    ["vergo","倾向","incline","vergo"], ["convergo","汇聚","converge","vergo"], ["divergo","分岔","diverge","vergo"],
    ["vicis","轮流,代替","turn; substitute","vicis"], ["vicissim","轮流地","in turn","vicis"], ["vicissitudo","变迁","vicissitude","vicis"], ["vicarius","代理人","substitute","vicis"], ["vice","代替","in place of","vicis"],
    ["vicinus","邻近的","neighbouring","vicinus"], ["vicinia","邻里","neighbourhood","vicinus"], ["vicinitas","邻近","vicinity","vicinus"], ["vicus","村,街","village; street","vicinus"],
    ["vilis","便宜的,卑贱的","cheap; vile","vilis"], ["vilitas","低贱","cheapness","vilis"], ["vilesco","变贱","become cheap","vilis"], ["vilipendo","轻视","vilify","vilis"],
    ["vinum","酒","wine","vinum"], ["vinea","葡萄园","vineyard","vinum"], ["vinetum","葡萄园","vineyard","vinum"], ["vindemia","葡萄收获","vintage","vinum"], ["vinosus","嗜酒的","fond of wine","vinum"], ["vinarius","酒商","wine merchant","vinum"],
    ["voveo","许愿","vow","voveo"], ["votum","誓愿,投票","vow; vote","voveo"], ["devoveo","奉献","devote","voveo"], ["devotus","忠诚的","devoted","voveo"], ["devotio","奉献","devotion","voveo"], ["votivus","还愿的","votive","voveo"]
  );
})();
