/* =====================================================
   FUGA MYTHICA — CURSUS vocabulary pack: French 🇫🇷
   roots: id -> [rootForm, zhGist, enGist]  (mostly Latin roots — the same ones Fuga Mythica teaches)
   words: [word, zhGist, enGist, rootId]
   ===================================================== */
VOCAB.fr = {
  name: { zh: "法语", en: "French" }, flag: "🇫🇷",
  roots: {
    ven:  ["ven-", "来", "come"],
    port: ["port-", "带,运", "carry"],
    mett: ["mett-/mis-", "放", "put"],
    ten:  ["ten-/tien-", "持", "hold"],
    pren: ["pren-/pris-", "拿", "take"],
    dic:  ["dire/dict-", "说", "say"],
    voir: ["voir/vis-/vu-", "看", "see"],
    fair: ["faire/fact-/fais-", "做", "make"],
    pos:  ["pos-", "放置", "place"],
    duc:  ["duire/duct-", "引导", "lead"],
    scrib:["écri-/script-", "写", "write"],
    lect: ["lire/lect-", "读", "read"],
    sav:  ["sav-/sci-", "知", "know"],
    conn: ["conn-", "认识", "know (person)"],
    cour: ["cour-/curs-", "跑", "run"],
    pass: ["pass-", "经过", "pass"],
    part: ["part-", "部分,离开", "part, leave"],
    fin:  ["fin-", "结束", "end"],
    form: ["form-", "形状", "shape"],
    port2:["port-", "门,港", "door, harbour"],
    terr: ["terr-", "土地", "land"],
    aqu:  ["eau/aqu-", "水", "water"],
    lum:  ["lum-/luc-", "光", "light"],
    man:  ["main/manu-", "手", "hand"],
    ped:  ["pied/ped-", "脚", "foot"],
    cœur: ["cœur/cord-", "心", "heart"],
    tête: ["tête/capit-", "头", "head"],
    vit:  ["vie/viv-", "生命", "life"],
    mort: ["mort-", "死", "death"],
    am:   ["am-", "爱", "love"],
    temps:["temps/tempor-", "时间", "time"],
    jour: ["jour/journ-", "日", "day"],
    an:   ["an/ann-", "年", "year"],
    nuit: ["nuit/noct-", "夜", "night"],
    sol:  ["soleil/sol-", "太阳", "sun"],
    lun:  ["lune/lun-", "月", "moon"],
    étoil:["étoile/stell-", "星", "star"],
    mer:  ["mer/mar-", "海", "sea"],
    mont: ["mont-", "山", "mountain"],
    ville:["ville/vill-", "城", "town"],
    voi:  ["voie/via-", "路", "way"],
    grand:["grand-", "大", "big"],
    petit:["petit-", "小", "small"],
    haut: ["haut/alt-", "高", "high"],
    long: ["long-", "长", "long"],
    fort: ["fort-", "强", "strong"],
    bon:  ["bon-/bien", "好", "good"],
    mal:  ["mal-", "坏", "bad"],
    nouv: ["nouv-/nov-", "新", "new"],
    vieux:["vieux/vét-", "老", "old"],
    jeun: ["jeun-/juv-", "年轻", "young"],
    beau: ["beau/bell-", "美", "beautiful"],
    chaud:["chaud/chal-", "热", "hot"],
    froid:["froid/frig-", "冷", "cold"],
    clair:["clair/clar-", "清楚,亮", "clear"],
    noir: ["noir/nigr-", "黑", "black"],
    blanc:["blanc-", "白", "white"],
    roug: ["roug-/rub-", "红", "red"],
    vert: ["vert/vir-", "绿", "green"],
    bleu: ["bleu-", "蓝", "blue"],
    un:   ["un/uni-", "一", "one"],
    deux: ["deux/du-/bi-", "二", "two"],
    trois:["trois/tri-", "三", "three"],
    cent: ["cent-", "百", "hundred"],
    mill: ["mille/mill-", "千", "thousand"],
    père: ["père/patr-", "父", "father"],
    mère: ["mère/matr-", "母", "mother"],
    fils: ["fils/fili-", "子女", "child"],
    frère:["frère/frater-", "兄弟", "brother"],
    sœur: ["sœur/soror-", "姐妹", "sister"],
    ami:  ["ami/amic-", "朋友", "friend"],
    roi:  ["roi/rég-", "国王", "king"],
    dieu: ["dieu/div-", "神", "god"],
    femm: ["femme/fémin-", "女人", "woman"],
    enf:  ["enfant-", "孩子", "child"],
    peupl:["peuple/popul-", "人民", "people"],
    mond: ["monde/mond-", "世界", "world"],
    ciel: ["ciel/céleste", "天", "sky"],
    feu:  ["feu-", "火", "fire"],
    air:  ["air-", "空气", "air"],
    pierr:["pierre/pétr-", "石", "stone"],
    arbr: ["arbre/arbor-", "树", "tree"],
    fleur:["fleur/flor-", "花", "flower"],
    anim: ["anim-", "灵魂,动物", "soul, animal"],
    ois:  ["oiseau/avi-", "鸟", "bird"],
    chev: ["cheval-", "马", "horse"],
    chien:["chien/can-", "狗", "dog"],
    pois: ["poisson/pisc-", "鱼", "fish"],
    mais: ["maison-", "房子", "house"],
    chambr:["chambre-", "房间", "room"],
    livr: ["livre/libr-", "书", "book"],
    nom:  ["nom-", "名", "name"],
    parl: ["parl-", "说话", "speak"],
    chant:["chant-", "唱", "sing"],
    dans: ["dans-", "跳舞", "dance"],
    jou:  ["jou-/jeu", "玩", "play"],
    trav: ["travail-", "工作", "work"],
    œuvr: ["œuvre/oper-", "作品,劳作", "work"],
    ach:  ["achet-", "买", "buy"],
    pay:  ["pay-", "付", "pay"],
    arg:  ["argent-", "钱,银", "money, silver"],
    or:   ["or/aur-", "金", "gold"],
    prix: ["prix/préci-", "价格", "price"],
    march:["march-", "走,市场", "walk, market"],
    dorm: ["dorm-", "睡", "sleep"],
    mang: ["mang-", "吃", "eat"],
    boi:  ["boi-/buv-", "喝", "drink"],
    cuis: ["cuis-/coct-", "煮", "cook"],
    pain: ["pain/pan-", "面包", "bread"],
    habit:["habit-", "住", "dwell"],
    bât:  ["bât-", "建造", "build"],
    croi: ["croî-/cresc-", "生长", "grow"],
    croir:["croi-/créd-", "相信", "believe"],
    esp:  ["espér-/spér-", "希望", "hope"],
    peur: ["peur-", "怕", "fear"],
    joi:  ["joie/jou-", "喜悦", "joy"],
    pleur:["pleur-", "哭", "cry"],
    cri:  ["cri-", "喊", "shout"],
    aim:  ["aim-", "爱", "love"],
    voul: ["voul-/volont-", "想要", "want"],
    pouv: ["pouv-/puiss-", "能", "can"],
    dev:  ["dev-/dû", "应该,欠", "must, owe"],
    fall: ["fall-/faut", "需要", "be necessary"],
    demand:["demand-", "问,要求", "ask"],
    répond:["répond-", "回答", "answer"],
    pens: ["pens-", "想", "think"],
    sent: ["sent-", "感觉", "feel"],
    souv: ["souven-", "记得", "remember"],
    oubli:["oubli-", "忘", "forget"],
    cherch:["cherch-", "找", "seek"],
    trouv:["trouv-", "找到", "find"],
    perd: ["perd-", "丢失", "lose"],
    gagn: ["gagn-", "赢,赚", "win, earn"],
    recev:["recev-/recep-", "收到", "receive"],
    env:  ["envoy-", "送", "send"],
    ouvr: ["ouvr-", "开", "open"],
    ferm: ["ferm-", "关,牢固", "close, firm"],
    tomb: ["tomb-", "落", "fall"],
    lev:  ["lev-", "举起", "raise"],
    mont2:["mont-", "上升", "go up"],
    descend:["descend-", "下降", "go down"],
    entr: ["entr-", "进入", "enter"],
    sort: ["sort-", "出去", "go out"],
    rest: ["rest-", "留下", "stay"],
    chang:["chang-", "换", "change"],
    tourn:["tourn-", "转", "turn"],
    suiv: ["suiv-/sécut-", "跟随", "follow"],
    atteind:["atteind-", "到达", "reach"],
    arriv:["arriv-", "到达", "arrive"],
    commenc:["commenc-", "开始", "begin"],
    apprend:["apprend-", "学", "learn"],
    enseign:["enseign-/sign-", "教,符号", "teach, sign"],
    prehend: ["prehend- / pris-", "抓,理解", "grasp, understand"], mémoir:["mémoir-", "记忆", "memory"],
    vér:  ["vér-", "真", "true"],
    just: ["just-", "正义", "just"],
    droit:["droit/direct-", "右,权利,直", "right, straight"],
    pai:  ["paix/pac-", "和平", "peace"],
    guerr:["guerr-", "战争", "war"],
    combat:["combat-", "战斗", "fight"],
    vainc:["vainc-/vict-", "征服", "conquer"],
    forc: ["forc-", "力", "force"],
    santé:["san-", "健康", "health"],
    doul: ["doul-/dol-", "痛", "pain"],
    médec:["médec-/médic-", "医", "medicine"],
    corps:["corps/corpor-", "身体", "body"],
    esprit:["esprit/spirit-", "精神", "spirit"],
    âm:   ["âme/anim-", "灵魂", "soul"],
    œil:  ["œil/yeux/ocul-", "眼", "eye"],
    bouch:["bouche-", "嘴", "mouth"],
    voix: ["voix/voc-", "声音", "voice"],
    oreil:["oreille/aur-", "耳", "ear"],
    sang: ["sang/sanguin-", "血", "blood"],
    dent: ["dent-", "牙", "tooth"],
    lieu: ["lieu/loc-", "地方", "place"],
    pays: ["pays-", "国家", "country"],
    rue:  ["rue-", "街", "street"],
    pont: ["pont-", "桥", "bridge"],
    voit: ["voiture-", "车", "car"],
    vol:  ["vol-", "飞,偷", "fly, steal"],
    nag:  ["nag-", "游泳", "swim"],
    port3:["porte-", "门", "door"],
    fenêtr:["fenêtre-", "窗", "window"],
    tabl: ["table-", "桌", "table"],
    lit:  ["lit-", "床", "bed"],
    vêt:  ["vêt-/vest-", "衣", "clothing"],
    chauss:["chauss-", "鞋", "shoe"],
    matin:["matin-", "早晨", "morning"],
    soir: ["soir-", "晚上", "evening"],
    semain:["semaine-", "周", "week"],
    mois: ["mois/mens-", "月份", "month"],
    heur: ["heure/hor-", "小时", "hour"],
    tout: ["tout/tot-", "全部", "all"],
    plein:["plein/plén-", "满", "full"],
    vid:  ["vide/vac-", "空", "empty"],
    seul: ["seul/sol-", "单独", "alone"],
    ensembl:["ensemble-", "一起", "together"],
    autr: ["autr-/alter-", "其他", "other"],
    mêm: ["même-", "同样", "same"],
    milieu:["milieu/médi-", "中间", "middle"],
    dessus:["dessus/sur-", "上", "above"],
    dessous:["dessous/sous-", "下", "below"],
    avant:["avant-", "前", "before"],
    après:["après-", "后", "after"],
    loin: ["loin-", "远", "far"],
    près: ["près/proche", "近", "near"],
    vit2: ["vite-", "快", "fast"],
    lent: ["lent-", "慢", "slow"],
    dur:  ["dur-", "硬,难,持续", "hard, last"],
    doux: ["doux/douc-", "柔软,甜", "soft, sweet"],
    riche:["rich-", "富", "rich"],
    pauvr:["pauvr-", "穷", "poor"],
    cher: ["cher/char-", "贵,亲爱", "dear"],
    facil:["facil-", "容易", "easy"],
    diffic:["diffic-", "难", "difficult"],
    poss: ["poss-", "可能", "possible"],
    nécess:["nécess-", "必要", "necessary"],
    import:["import-", "重要", "important"],
    utile:["util-", "有用", "useful"],
    dang: ["danger-", "危险", "danger"],
    sûr:  ["sûr/sécur-", "确定,安全", "sure, safe"],
    saint:["saint/sanct-", "神圣", "holy"],
    honn: ["honn-/honor-", "荣誉", "honor"],
    fidèl:["fidèl-/fid-", "忠诚", "faithful"],
    cour2:["cour/court-", "庭院,宫廷", "court"],
    sold: ["soldat-", "士兵", "soldier"],
    ép:   ["épée-", "剑", "sword"],
    hér:  ["héro-", "英雄", "hero"],
    magi: ["magi-", "魔法", "magic"],
    merveil:["merveil-", "奇妙", "marvel"],
    chât: ["château-", "城堡", "castle"],
    égl:  ["église-", "教堂", "church"],
    écol: ["école-", "学校", "school"],
    maîtr:["maître/magistr-", "主人,老师", "master"],
    élèv: ["élève/élev-", "学生,抬高", "pupil, raise"],
    histoir:["histoire-", "历史,故事", "history, story"],
    image:["image/imag-", "图像", "image"],
    ordr: ["ordre/ordin-", "秩序", "order"],
    lo:   ["loi/lég-", "法律", "law"],
    gouv: ["gouvern-", "治理", "govern"],
    chef: ["chef/capit-", "首领", "chief"],
    numér:["nombre/numér-", "数", "number"],
    comm: ["comm-/commun-", "共同", "common"],
    soci: ["soci-", "社会,伙伴", "society"],
    natur:["natur-", "自然", "nature"],
    nais: ["naiss-/nat-", "出生", "birth"],
    cult: ["cult-", "耕,文化", "cultivate, culture"],
    vent: ["vent-", "风", "wind"],
    plui: ["pluie/pluv-", "雨", "rain"],
    neig: ["neige/niv-", "雪", "snow"],
    nuag: ["nuage/nub-", "云", "cloud"],
    chemin:["chemin-", "路", "path"],
    voyag:["voyag-", "旅行", "travel"],
    fête: ["fête/fest-", "节日", "festival"],
    cadeau:["cadeau-", "礼物", "gift"],
    besoin:["besoin-", "需要", "need"],
    aid:  ["aid-", "帮助", "help"],
    serv: ["serv-", "服务", "serve"],
    gard: ["gard-", "看守", "guard"],
    sauv: ["sauv-/salv-", "救", "save"],
    laiss:["laiss-", "留下,让", "leave, let"],
    tir:  ["tir-", "拉,射", "pull, shoot"],
    pouss:["pouss-", "推", "push"],
    jet:  ["jet-/ject-", "扔", "throw"],
    coup: ["coup-", "打,切", "blow, cut"],
    cass: ["cass-", "打破", "break"],
    frapp:["frapp-", "敲打", "strike"],
    touch:["touch-", "触碰", "touch"],
    tenir2:["tenir-", "持有", "hold"],
    montr:["montr-/monstr-", "展示", "show"],
    cach: ["cach-", "藏", "hide"],
    lav:  ["lav-", "洗", "wash"],
    vend: ["vend-", "卖", "sell"],
    coût: ["coût-", "花费", "cost"],
    compt:["compt-/comput-", "数,算", "count"],
    mesur:["mesur-", "测量", "measure"],
    pes:  ["pes-/pond-", "称重", "weigh"],
    mach: ["machin-", "机器", "machine"],
    lettr:["lettre/littér-", "字母,信", "letter"],
    papier:["papier-", "纸", "paper"],
    journ:["journ-", "日,报", "day, newspaper"],
    fen:  ["fin-/fén-", "细,精", "fine"],
    sign: ["sign-", "符号", "sign"],
    ray:  ["ray-/radi-", "光线", "ray"],
    couleur:["couleur/color-", "颜色", "color"],
    somm: ["somm-", "睡眠,总和", "sleep, sum"],
    rêv:  ["rêv-", "梦", "dream"],
    pouvoir2:["puiss-", "力量", "power"],
  },
  words: [
    /* ---- motion verbs & families ---- */
    ["venir","来","come","ven"], ["devenir","变成","become","ven"], ["revenir","回来","come back","ven"], ["l'avenir","未来","future","ven"], ["souvenir","回忆","memory","ven"], ["se souvenir","记得","remember","ven"], ["convenir","适合","suit","ven"], ["prévenir","预防,告知","warn","ven"], ["l'événement","事件","event","ven"], ["parvenir","达到","reach","ven"], ["bienvenue","欢迎","welcome","ven"], ["l'aventure","冒险","adventure","ven"],
    ["porter","带,穿","carry, wear","port"], ["apporter","带来","bring","port"], ["emporter","带走","take away","port"], ["rapporter","带回,报告","bring back, report","port"], ["supporter","忍受","bear","port"], ["important","重要的","important","import"], ["l'importance","重要性","importance","import"], ["le transport","运输","transport","port"], ["le rapport","报告,关系","report, relation","port"], ["le sport","运动","sport","port"], ["le passeport","护照","passport","port"], ["exporter","出口","export","port"],
    ["mettre","放","put","mett"], ["permettre","允许","allow","mett"], ["promettre","承诺","promise","mett"], ["la promesse","承诺","promise","mett"], ["admettre","承认","admit","mett"], ["remettre","交给,推迟","hand over, postpone","mett"], ["soumettre","提交,使服从","submit","mett"], ["la mission","任务","mission","mett"], ["commettre","犯(错)","commit","mett"], ["la permission","许可","permission","mett"],
    ["tenir","拿着","hold","ten"], ["obtenir","获得","obtain","ten"], ["contenir","包含","contain","ten"], ["le contenu","内容","content","ten"], ["appartenir","属于","belong","ten"], ["maintenir","维持","maintain","ten"], ["maintenant","现在","now","ten"], ["soutenir","支持","support","ten"], ["retenir","留住,记住","retain","ten"], ["entretenir","保养","maintain","ten"], ["le lieutenant","中尉","lieutenant","ten"],
    ["prendre","拿","take","pren"], ["apprendre","学","learn","apprend"], ["comprendre","理解","understand","prehend"], ["surprendre","使惊讶","surprise","pren"], ["la surprise","惊喜","surprise","pren"], ["reprendre","重新拿起","take back","pren"], ["entreprendre","着手","undertake","pren"], ["l'entreprise","企业","company","pren"], ["la prise","抓取","grip","pren"], ["l'apprentissage","学习","learning","apprend"], ["compréhensible","可理解的","understandable","prehend"],
    ["dire","说","say","dic"], ["le dictionnaire","词典","dictionary","dic"], ["contredire","反驳","contradict","dic"], ["prédire","预言","predict","dic"], ["interdire","禁止","forbid","dic"], ["l'interdiction","禁令","ban","dic"], ["la dictée","听写","dictation","dic"], ["le verdict","裁决","verdict","dic"], ["la bénédiction","祝福","blessing","dic"],
    ["voir","看","see","voir"], ["la vue","视力,景色","sight, view","voir"], ["revoir","再见","see again","voir"], ["prévoir","预见","foresee","voir"], ["la vision","视觉","vision","voir"], ["visible","可见的","visible","voir"], ["la visite","访问","visit","voir"], ["visiter","参观","visit","voir"], ["évident","明显的","obvious","voir"], ["la télévision","电视","television","voir"], ["le visage","脸","face","voir"],
    ["faire","做","do, make","fair"], ["refaire","重做","redo","fair"], ["défaire","拆开","undo","fair"], ["satisfaire","满足","satisfy","fair"], ["le fait","事实","fact","fair"], ["parfait","完美的","perfect","fair"], ["la façon","方式","way","fair"], ["l'affaire","事务,生意","affair, business","fair"], ["difficile","困难的","difficult","diffic"], ["facile","容易的","easy","facil"], ["la facilité","轻松","ease","facil"], ["la difficulté","困难","difficulty","diffic"], ["la fabrique","工厂","factory","fair"],
    ["poser","放","place","pos"], ["proposer","建议","propose","pos"], ["la proposition","建议","proposal","pos"], ["composer","组成","compose","pos"], ["supposer","假设","suppose","pos"], ["imposer","强加","impose","pos"], ["reposer","休息","rest","pos"], ["disposer","安排,拥有","arrange, have","pos"], ["la position","位置","position","pos"], ["opposer","反对","oppose","pos"], ["exposer","展出","exhibit","pos"], ["l'exposition","展览","exhibition","pos"],
    ["conduire","驾驶,引导","drive, lead","duc"], ["le conducteur","司机","driver","duc"], ["produire","生产","produce","duc"], ["le produit","产品","product","duc"], ["réduire","减少","reduce","duc"], ["traduire","翻译","translate","duc"], ["la traduction","翻译","translation","duc"], ["introduire","引入","introduce","duc"], ["l'éducation","教育","education","duc"], ["séduire","诱惑","seduce","duc"], ["le duc","公爵","duke","duc"],
    ["écrire","写","write","scrib"], ["l'écriture","文字","writing","scrib"], ["l'écrivain","作家","writer","scrib"], ["décrire","描述","describe","scrib"], ["inscrire","登记","register","scrib"], ["la description","描述","description","scrib"], ["le manuscrit","手稿","manuscript","scrib"],
    ["lire","读","read","lect"], ["la lecture","阅读","reading","lect"], ["le lecteur","读者","reader","lect"], ["élire","选举","elect","lect"], ["l'élection","选举","election","lect"], ["la leçon","课","lesson","lect"], ["collecter","收集","collect","lect"],
    ["savoir","知道","know","sav"], ["le savant","学者","scholar","sav"], ["la science","科学","science","sav"], ["la conscience","意识,良心","conscience","sav"], ["connaître","认识","know (person)","conn"], ["la connaissance","知识,熟人","knowledge","conn"], ["reconnaître","认出","recognize","conn"], ["inconnu","未知的","unknown","conn"],
    ["courir","跑","run","cour"], ["le cours","课程,进程","course","cour"], ["la course","赛跑,购物","race, errand","cour"], ["le courrier","邮件","mail","cour"], ["le secours","救援","help","cour"], ["le concours","竞赛","competition","cour"], ["le parcours","路线","route","cour"], ["le discours","演讲","speech","cour"], ["courant","流行的,水流","current","cour"],
    ["passer","经过","pass","pass"], ["le passé","过去","past","pass"], ["le passage","通道","passage","pass"], ["le passager","乘客","passenger","pass"], ["dépasser","超过","exceed","pass"], ["se passer","发生","happen","pass"], ["le passant","路人","passer-by","pass"],
    ["partir","离开","leave","part"], ["la partie","部分","part","part"], ["partager","分享","share","part"], ["le départ","出发","departure","part"], ["à part","除了","apart","part"], ["particulier","特别的","particular","part"], ["participer","参加","participate","part"], ["le parti","政党","party (political)","part"], ["la part","份","share","part"], ["repartir","再出发","set off again","part"],
    ["finir","结束","finish","fin"], ["la fin","结束","end","fin"], ["enfin","终于","finally","fin"], ["définir","定义","define","fin"], ["final","最后的","final","fin"], ["infini","无限的","infinite","fin"], ["la finance","金融","finance","fin"], ["fin","细的,精致","fine, thin","fen"],
    ["la forme","形状","shape","form"], ["former","形成","form","form"], ["la formation","培训","training","form"], ["l'information","信息","information","form"], ["informer","告知","inform","form"], ["transformer","改变","transform","form"], ["la réforme","改革","reform","form"], ["le formulaire","表格","form (paper)","form"], ["uniforme","统一的","uniform","form"],
    /* ---- nature ---- */
    ["la terre","土地,地球","earth","terr"], ["le territoire","领土","territory","terr"], ["enterrer","埋葬","bury","terr"], ["atterrir","着陆","land","terr"], ["le terrain","地面,场地","ground","terr"], ["souterrain","地下的","underground","terr"], ["la Méditerranée","地中海","Mediterranean","terr"],
    ["l'eau","水","water","aqu"], ["l'aquarium","水族馆","aquarium","aqu"], ["aquatique","水生的","aquatic","aqu"], ["la lumière","光","light","lum"], ["allumer","点亮","light up","lum"], ["lumineux","发光的","luminous","lum"], ["illuminer","照亮","illuminate","lum"], ["la lune","月亮","moon","lun"], ["lundi","星期一","Monday","lun"], ["le soleil","太阳","sun","sol"], ["solaire","太阳的","solar","sol"], ["l'étoile","星星","star","étoil"], ["la constellation","星座","constellation","étoil"], ["le ciel","天空","sky","ciel"], ["céleste","天上的","celestial","ciel"], ["le feu","火","fire","feu"], ["l'air","空气","air","air"], ["la pierre","石头","stone","pierr"], ["l'arbre","树","tree","arbr"], ["la fleur","花","flower","fleur"], ["fleurir","开花","bloom","fleur"], ["la farine","面粉","flour","fleur"], ["le vent","风","wind","vent"], ["la pluie","雨","rain","plui"], ["pleuvoir","下雨","rain (verb)","plui"], ["la neige","雪","snow","neig"], ["neiger","下雪","snow (verb)","neig"], ["le nuage","云","cloud","nuag"], ["la mer","海","sea","mer"], ["le marin","水手","sailor","mer"], ["maritime","海的","maritime","mer"], ["la montagne","山","mountain","mont"], ["monter","上升","go up","mont2"], ["la montée","上坡","ascent","mont2"], ["descendre","下降","go down","descend"], ["la descente","下坡","descent","descend"],
    ["le monde","世界","world","mond"], ["tout le monde","大家","everyone","mond"], ["mondial","全球的","worldwide","mond"], ["la nature","自然","nature","natur"], ["naturel","自然的","natural","natur"], ["naître","出生","be born","nais"], ["la naissance","出生","birth","nais"], ["né","出生的","born","nais"], ["la nation","国家","nation","nais"], ["renaître","重生","be reborn","nais"], ["la Renaissance","文艺复兴","Renaissance","nais"],
    ["l'animal","动物","animal","anim"], ["l'âme","灵魂","soul","âm"], ["animer","使活跃","animate","anim"], ["l'oiseau","鸟","bird","ois"], ["l'avion","飞机","airplane","ois"], ["le cheval","马","horse","chev"], ["le chevalier","骑士","knight","chev"], ["la chevalerie","骑士精神","chivalry","chev"], ["le chien","狗","dog","chien"], ["le poisson","鱼","fish","pois"], ["la piscine","游泳池","swimming pool","pois"],
    /* ---- body & life ---- */
    ["la main","手","hand","man"], ["manuel","手工的","manual","man"], ["maintenir","维持","maintain","man"], ["la manière","方式","manner","man"], ["manier","操作","handle","man"], ["le pied","脚","foot","ped"], ["le piéton","行人","pedestrian","ped"], ["la pédale","踏板","pedal","ped"], ["le cœur","心","heart","cœur"], ["le courage","勇气","courage","cœur"], ["courageux","勇敢的","brave","cœur"], ["d'accord","同意","agreed","cœur"], ["la tête","头","head","tête"], ["le capitaine","队长","captain","tête"], ["la capitale","首都","capital","tête"], ["le chapitre","章","chapter","tête"], ["l'œil","眼","eye","œil"], ["les yeux","眼睛","eyes","œil"], ["la bouche","嘴","mouth","bouch"], ["la voix","声音","voice","voix"], ["la vocation","使命","vocation","voix"], ["le vocabulaire","词汇","vocabulary","voix"], ["l'oreille","耳朵","ear","oreil"], ["le sang","血","blood","sang"], ["la dent","牙齿","tooth","dent"], ["le dentiste","牙医","dentist","dent"], ["le corps","身体","body","corps"], ["l'esprit","精神","spirit, mind","esprit"],
    ["la vie","生命","life","vit"], ["vivre","活","live","vit"], ["vivant","活的","alive","vit"], ["survivre","幸存","survive","vit"], ["la mort","死亡","death","mort"], ["mourir","死","die","mort"], ["mort","死的","dead","mort"], ["mortel","致命的","mortal","mort"], ["immortel","不朽的","immortal","mort"], ["la santé","健康","health","santé"], ["sain","健康的","healthy","santé"], ["la douleur","疼痛","pain","doul"], ["douloureux","痛苦的","painful","doul"], ["le médecin","医生","doctor","médec"], ["la médecine","医学","medicine","médec"], ["le médicament","药","medication","médec"],
    ["dormir","睡","sleep","dorm"], ["le dortoir","宿舍","dormitory","dorm"], ["s'endormir","入睡","fall asleep","dorm"], ["le sommeil","睡眠","sleep","somm"], ["le rêve","梦","dream","rêv"], ["rêver","做梦","dream (verb)","rêv"], ["manger","吃","eat","mang"], ["boire","喝","drink","boi"], ["la boisson","饮料","drink","boi"], ["cuisiner","做饭","cook","cuis"], ["la cuisine","厨房,菜肴","kitchen, cuisine","cuis"], ["le pain","面包","bread","pain"], ["habiter","住","live","habit"], ["l'habitant","居民","inhabitant","habit"], ["l'habitude","习惯","habit","habit"], ["bâtir","建造","build","bât"], ["le bâtiment","建筑","building","bât"], ["croître","生长","grow","croi"], ["la croissance","增长","growth","croi"], ["le croissant","新月,羊角包","crescent","croi"],
    /* ---- feelings ---- */
    ["aimer","爱,喜欢","love, like","aim"], ["l'amour","爱","love","am"], ["l'ami","朋友","friend","ami"], ["l'amitié","友谊","friendship","ami"], ["amical","友好的","friendly","ami"], ["l'amateur","爱好者","amateur","am"], ["aimable","和蔼的","kind","aim"], ["croire","相信","believe","croir"], ["la croyance","信仰","belief","croir"], ["incroyable","难以置信","incredible","croir"], ["le crédit","信贷","credit","croir"], ["espérer","希望","hope","esp"], ["l'espoir","希望","hope","esp"], ["l'espérance","期望","expectation","esp"], ["désespéré","绝望的","desperate","esp"], ["la peur","恐惧","fear","peur"], ["avoir peur","害怕","be afraid","peur"], ["peureux","胆小的","fearful","peur"], ["la joie","喜悦","joy","joi"], ["joyeux","快乐的","joyful","joi"], ["rire","笑","laugh","rid"], ["le sourire","微笑","smile","rid"], ["ridicule","可笑的","ridiculous","rid"], ["pleurer","哭","cry","pleur"], ["crier","喊","shout","cri"], ["le cri","喊声","cry, shout","cri"],
    ["vouloir","想要","want","voul"], ["la volonté","意志","will","voul"], ["volontaire","自愿的","voluntary","voul"], ["pouvoir","能","can","pouv"], ["le pouvoir","权力","power","pouv"], ["puissant","强大的","powerful","pouvoir2"], ["la puissance","力量","power","pouvoir2"], ["possible","可能的","possible","poss"], ["impossible","不可能","impossible","poss"], ["devoir","应该,欠","must, owe","dev"], ["le devoir","作业,义务","duty, homework","dev"], ["la dette","债务","debt","dev"], ["falloir","需要","be necessary","fall"], ["il faut","必须","one must","fall"], ["la faute","错误","fault","fall"],
    ["demander","问,要","ask","demand"], ["la demande","请求","request","demand"], ["répondre","回答","answer","répond"], ["la réponse","回答","answer","répond"], ["responsable","负责的","responsible","répond"], ["penser","想","think","pens"], ["la pensée","思想","thought","pens"], ["le penseur","思想家","thinker","pens"], ["sentir","感觉,闻","feel, smell","sent"], ["le sentiment","感情","feeling","sent"], ["le sens","意义,方向","meaning, direction","sent"], ["sensible","敏感的","sensitive","sent"], ["consentir","同意","consent","sent"], ["oublier","忘记","forget","oubli"], ["l'oubli","遗忘","oblivion","oubli"], ["la mémoire","记忆","memory","mémoir"], ["mémoriser","记住","memorize","mémoir"],
    ["chercher","找","look for","cherch"], ["la recherche","研究","research","cherch"], ["le chercheur","研究者","researcher","cherch"], ["trouver","找到","find","trouv"], ["retrouver","找回","find again","trouv"], ["se trouver","位于","be located","trouv"], ["perdre","丢失","lose","perd"], ["la perte","损失","loss","perd"], ["perdu","迷路的","lost","perd"], ["gagner","赢,赚","win, earn","gagn"], ["le gagnant","赢家","winner","gagn"], ["donner","给","give","don"], ["le don","礼物,天赋","gift","don"], ["pardonner","原谅","forgive","don"], ["le pardon","原谅","pardon","don"], ["abandonner","放弃","abandon","don"], ["recevoir","收到","receive","recev"], ["la réception","接待","reception","recev"], ["envoyer","送","send","env"], ["l'envoi","发送","dispatch","env"], ["ouvrir","开","open","ouvr"], ["l'ouverture","开口,开幕","opening","ouvr"], ["ouvert","开着的","open","ouvr"], ["fermer","关","close","ferm"], ["fermé","关着的","closed","ferm"], ["la ferme","农场","farm","ferm"], ["ferme","坚定的","firm","ferm"],
    ["tomber","落","fall","tomb"], ["la tombe","坟墓","grave","tomb"], ["lever","举起","raise","lev"], ["se lever","起床","get up","lev"], ["élever","抚养,抬高","raise","élèv"], ["l'élève","学生","pupil","élèv"], ["entrer","进入","enter","entr"], ["l'entrée","入口","entrance","entr"], ["sortir","出去","go out","sort"], ["la sortie","出口","exit","sort"], ["rester","留下","stay","rest"], ["le reste","剩余","rest","rest"], ["changer","改变","change","chang"], ["le changement","变化","change","chang"], ["l'échange","交换","exchange","chang"], ["tourner","转","turn","tourn"], ["le tour","一圈,轮次","turn, tour","tourn"], ["retourner","返回","return","tourn"], ["le retour","返回","return","tourn"], ["la tour","塔","tower","tourn"], ["suivre","跟随","follow","suiv"], ["suivant","下一个","following","suiv"], ["la suite","后续","continuation","suiv"], ["poursuivre","追赶","pursue","suiv"], ["arriver","到达","arrive","arriv"], ["l'arrivée","到达","arrival","arriv"], ["atteindre","到达","reach","atteind"], ["commencer","开始","begin","commenc"], ["le commencement","开始","beginning","commenc"],
    ["enseigner","教","teach","enseign"], ["l'enseignant","教师","teacher","enseign"], ["le signe","符号","sign","sign"], ["signifier","意味着","mean","sign"], ["la signification","意义","meaning","sign"], ["signer","签名","sign","sign"], ["la signature","签名","signature","sign"], ["désigner","指定","designate","sign"], ["le dessin","图画","drawing","sign"], ["dessiner","画","draw","sign"],
    /* ---- time ---- */
    ["le temps","时间,天气","time, weather","temps"], ["temporaire","临时的","temporary","temps"], ["le printemps","春天","spring","temps"], ["contemporain","当代的","contemporary","temps"], ["le jour","日","day","jour"], ["la journée","一天","day (duration)","jour"], ["aujourd'hui","今天","today","jour"], ["le journal","报纸","newspaper","journ"], ["le journaliste","记者","journalist","journ"], ["bonjour","你好","hello","jour"], ["l'an","年","year","an"], ["l'année","一年","year","an"], ["l'anniversaire","生日","birthday","an"], ["annuel","每年的","annual","an"], ["la nuit","夜","night","nuit"], ["nocturne","夜间的","nocturnal","nuit"], ["bonne nuit","晚安","good night","nuit"], ["le matin","早晨","morning","matin"], ["le soir","晚上","evening","soir"], ["la soirée","晚会","evening party","soir"], ["bonsoir","晚上好","good evening","soir"], ["la semaine","周","week","semain"], ["le mois","月份","month","mois"], ["mensuel","每月的","monthly","mois"], ["l'heure","小时","hour","heur"], ["l'horaire","时间表","timetable","heur"], ["l'horloge","钟","clock","heur"],
    /* ---- people & society ---- */
    ["le père","父亲","father","père"], ["paternel","父亲的","paternal","père"], ["la patrie","祖国","homeland","père"], ["le patron","老板","boss","père"], ["la mère","母亲","mother","mère"], ["maternel","母亲的","maternal","mère"], ["le fils","儿子","son","fils"], ["la fille","女儿,女孩","daughter, girl","fils"], ["le frère","兄弟","brother","frère"], ["fraternel","兄弟般的","fraternal","frère"], ["la sœur","姐妹","sister","sœur"], ["l'homme","男人,人","man","hum"], ["humain","人类的","human","hum"], ["l'humanité","人类","humanity","hum"], ["la femme","女人,妻子","woman, wife","femm"], ["féminin","女性的","feminine","femm"], ["l'enfant","孩子","child","enf"], ["l'enfance","童年","childhood","enf"], ["le roi","国王","king","roi"], ["la reine","王后","queen","roi"], ["royal","王室的","royal","roi"], ["le royaume","王国","kingdom","roi"], ["la règle","规则","rule","roi"], ["régner","统治","reign","roi"], ["la région","地区","region","roi"], ["diriger","领导","direct","droit"], ["le dieu","神","god","dieu"], ["la déesse","女神","goddess","dieu"], ["divin","神圣的","divine","dieu"], ["adieu","永别","farewell","dieu"], ["le peuple","人民","people","peupl"], ["populaire","流行的","popular","peupl"], ["la population","人口","population","peupl"], ["public","公共的","public","peupl"],
    ["la maison","房子","house","mais"], ["la chambre","房间","room","chambr"], ["la porte","门","door","port3"], ["la fenêtre","窗","window","fenêtr"], ["la table","桌子","table","tabl"], ["le lit","床","bed","lit"], ["le vêtement","衣服","clothing","vêt"], ["la veste","外套","jacket","vêt"], ["se vêtir","穿衣","get dressed","vêt"], ["la chaussure","鞋","shoe","chauss"], ["la chaussette","袜子","sock","chauss"],
    ["le livre","书","book","livr"], ["la librairie","书店","bookshop","livr"], ["le mot","词","word","mutt"], ["le nom","名字","name","nom"], ["nommer","命名","name","nom"], ["le prénom","名","first name","nom"], ["renommé","著名的","renowned","nom"], ["parler","说话","speak","parl"], ["la parole","话语","speech","parl"], ["le parlement","议会","parliament","parl"], ["chanter","唱","sing","chant"], ["la chanson","歌","song","chant"], ["le chanteur","歌手","singer","chant"], ["danser","跳舞","dance","dans"], ["la danse","舞","dance","dans"], ["jouer","玩","play","jou"], ["le jeu","游戏","game","jou"], ["le joueur","玩家","player","jou"], ["le jouet","玩具","toy","jou"], ["travailler","工作","work","trav"], ["le travail","工作","work","trav"], ["le travailleur","劳动者","worker","trav"], ["l'œuvre","作品","work (art)","œuvr"], ["l'ouvrier","工人","worker","œuvr"], ["le chef-d'œuvre","杰作","masterpiece","œuvr"], ["opérer","操作,手术","operate","œuvr"],
    ["acheter","买","buy","ach"], ["l'achat","购买","purchase","ach"], ["vendre","卖","sell","vend"], ["le vendeur","售货员","seller","vend"], ["la vente","销售","sale","vend"], ["payer","付","pay","pay"], ["le paiement","付款","payment","pay"], ["l'argent","钱,银","money, silver","arg"], ["l'or","金","gold","or"], ["doré","金色的","golden","or"], ["le prix","价格,奖","price, prize","prix"], ["précieux","珍贵的","precious","prix"], ["apprécier","欣赏","appreciate","prix"], ["coûter","花费","cost","coût"], ["le coût","成本","cost","coût"], ["compter","数","count","compt"], ["le compte","账户","account","compt"], ["raconter","讲述","tell","compt"], ["le conte","故事","tale","compt"], ["mesurer","测量","measure","mesur"], ["la mesure","尺寸,措施","measure","mesur"], ["peser","称重","weigh","pes"], ["le poids","重量","weight","pes"], ["marcher","走","walk","march"], ["la marche","步行,台阶","walk, step","march"], ["le marché","市场","market","march"],
    ["le lieu","地方","place","lieu"], ["local","当地的","local","lieu"], ["le milieu","中间,环境","middle","milieu"], ["le pays","国家","country","pays"], ["le paysage","风景","landscape","pays"], ["le paysan","农民","peasant","pays"], ["la ville","城市","city","ville"], ["le village","村庄","village","ville"], ["la villa","别墅","villa","ville"], ["la rue","街","street","rue"], ["le pont","桥","bridge","pont"], ["le bateau","船","boat","boat"], ["la voiture","汽车","car","voit"], ["la voie","道路","way","voi"], ["le voyage","旅行","journey","voyag"], ["voyager","旅行","travel","voyag"], ["le voyageur","旅行者","traveler","voyag"], ["le chemin","路","path","chemin"], ["le chemin de fer","铁路","railway","chemin"], ["voler","飞,偷","fly, steal","vol"], ["le vol","航班,盗窃","flight, theft","vol"], ["le voleur","小偷","thief","vol"], ["nager","游泳","swim","nag"], ["la natation","游泳","swimming","nag"],
    /* ---- qualities ---- */
    ["grand","大","big","grand"], ["grandir","长大","grow up","grand"], ["la grandeur","伟大","greatness","grand"], ["agrandir","扩大","enlarge","grand"], ["petit","小","small","petit"], ["le petit-déjeuner","早餐","breakfast","petit"], ["haut","高","high","haut"], ["la hauteur","高度","height","haut"], ["l'altitude","海拔","altitude","haut"], ["long","长","long","long"], ["la longueur","长度","length","long"], ["longtemps","很久","a long time","long"], ["fort","强","strong","fort"], ["la force","力量","strength","forc"], ["forcer","强迫","force","forc"], ["l'effort","努力","effort","forc"], ["renforcer","加强","reinforce","forc"], ["le confort","舒适","comfort","forc"], ["bon","好","good","bon"], ["bien","好地","well","bon"], ["la bonté","善良","goodness","bon"], ["le bonheur","幸福","happiness","bon"], ["mal","坏地","badly","mal"], ["mauvais","坏的","bad","mal"], ["le malheur","不幸","misfortune","mal"], ["malade","生病的","sick","mal"], ["la maladie","疾病","illness","mal"], ["nouveau","新","new","nouv"], ["la nouvelle","消息,短篇","news, short story","nouv"], ["nouvellement","新近","newly","nouv"], ["rénover","翻新","renovate","nouv"], ["vieux","老","old","vieux"], ["la vieillesse","老年","old age","vieux"], ["vieillir","变老","grow old","vieux"], ["jeune","年轻","young","jeun"], ["la jeunesse","青春","youth","jeun"], ["beau","美","beautiful","beau"], ["la beauté","美","beauty","beau"], ["embellir","美化","embellish","beau"], ["chaud","热","hot","chaud"], ["la chaleur","热量","heat","chaud"], ["chauffer","加热","heat","chaud"], ["froid","冷","cold","froid"], ["le frigo","冰箱","fridge","froid"], ["clair","清楚,亮","clear","clair"], ["la clarté","清晰","clarity","clair"], ["éclairer","照亮","light up","clair"], ["déclarer","宣布","declare","clair"], ["noir","黑","black","noir"], ["blanc","白","white","blanc"], ["rouge","红","red","roug"], ["rougir","脸红","blush","roug"], ["vert","绿","green","vert"], ["bleu","蓝","blue","bleu"], ["la couleur","颜色","color","couleur"], ["colorer","上色","color","couleur"],
    ["un","一","one","un"], ["unique","唯一","unique","un"], ["unir","联合","unite","un"], ["l'union","联合","union","un"], ["l'unité","单位,统一","unity","un"], ["deux","二","two","deux"], ["deuxième","第二","second","deux"], ["double","双倍","double","deux"], ["trois","三","three","trois"], ["troisième","第三","third","trois"], ["le triangle","三角形","triangle","trois"], ["cent","百","hundred","cent"], ["le siècle","世纪","century","cent"], ["le centime","分","cent","cent"], ["mille","千","thousand","mill"], ["le millier","约一千","thousand","mill"], ["le million","百万","million","mill"], ["le nombre","数","number","numér"], ["nombreux","许多的","numerous","numér"], ["le numéro","号码","number","numér"],
    ["tout","全部","all","tout"], ["toujours","总是","always","tout"], ["le total","总数","total","tout"], ["plein","满","full","plein"], ["remplir","填满","fill","plein"], ["vide","空","empty","vid"], ["vider","清空","empty","vid"], ["les vacances","假期","holidays","vid"], ["seul","单独","alone","seul"], ["seulement","仅仅","only","seul"], ["la solitude","孤独","solitude","seul"], ["ensemble","一起","together","ensembl"], ["autre","其他","other","autr"], ["autrement","否则","otherwise","autr"], ["même","同样","same","mêm"], ["dessus","上面","above","dessus"], ["au-dessus","在…上","over","dessus"], ["dessous","下面","below","dessous"], ["sous","在…下","under","dessous"], ["avant","之前","before","avant"], ["l'avantage","优势","advantage","avant"], ["après","之后","after","après"], ["l'après-midi","下午","afternoon","après"], ["loin","远","far","loin"], ["lointain","遥远的","distant","loin"], ["près","近","near","près"], ["proche","近的","close","près"], ["s'approcher","靠近","approach","près"], ["vite","快","fast","vit2"], ["la vitesse","速度","speed","vit2"], ["lent","慢","slow","lent"], ["lentement","慢慢地","slowly","lent"], ["dur","硬,难","hard","dur"], ["durer","持续","last","dur"], ["la durée","时长","duration","dur"], ["doux","柔软,甜","soft, sweet","doux"], ["la douceur","温柔","softness","doux"], ["riche","富","rich","riche"], ["la richesse","财富","wealth","riche"], ["pauvre","穷","poor","pauvr"], ["la pauvreté","贫困","poverty","pauvr"], ["cher","贵,亲爱","expensive, dear","cher"], ["chéri","亲爱的","darling","cher"], ["la charité","慈善","charity","cher"],
    ["nécessaire","必要的","necessary","nécess"], ["la nécessité","必要","necessity","nécess"], ["utile","有用","useful","utile"], ["utiliser","使用","use","utile"], ["inutile","没用的","useless","utile"], ["le danger","危险","danger","dang"], ["dangereux","危险的","dangerous","dang"], ["sûr","确定,安全","sure, safe","sûr"], ["la sécurité","安全","safety","sûr"], ["assurer","确保,保险","ensure, insure","sûr"], ["bien sûr","当然","of course","sûr"], ["vrai","真","true","vér"], ["la vérité","真理","truth","vér"], ["vraiment","真的","really","vér"], ["vérifier","核实","verify","vér"], ["juste","公正,恰好","just, exactly","just"], ["la justice","正义","justice","just"], ["le droit","权利,法","right, law","droit"], ["droit","直的,右","straight, right","droit"], ["adroit","灵巧的","skilful","droit"], ["la direction","方向","direction","droit"], ["libre","自由的","free","liber"], ["la liberté","自由","liberty","liber"], ["libérer","解放","free","liber"], ["la paix","和平","peace","pai"], ["paisible","平静的","peaceful","pai"], ["la guerre","战争","war","guerr"], ["le guerrier","战士","warrior","guerr"], ["le combat","战斗","fight","combat"], ["combattre","战斗","fight","combat"], ["battre","打","beat","combat"], ["vaincre","征服","defeat","vainc"], ["la victoire","胜利","victory","vainc"], ["le vainqueur","胜者","victor","vainc"], ["convaincre","说服","convince","vainc"], ["saint","神圣的","holy","saint"], ["l'honneur","荣誉","honor","honn"], ["honnête","诚实的","honest","honn"], ["fidèle","忠诚的","faithful","fidèl"], ["la fidélité","忠诚","fidelity","fidèl"], ["la foi","信仰","faith","fidèl"], ["se fier","信赖","trust","fidèl"], ["la cour","庭院,宫廷","courtyard, court","cour2"], ["le soldat","士兵","soldier","sold"], ["l'épée","剑","sword","ép"], ["le héros","英雄","hero","hér"], ["héroïque","英勇的","heroic","hér"], ["la magie","魔法","magic","magi"], ["magique","神奇的","magical","magi"], ["la merveille","奇迹","marvel","merveil"], ["merveilleux","奇妙的","marvellous","merveil"], ["le château","城堡","castle","chât"], ["l'église","教堂","church","égl"], ["l'école","学校","school","écol"], ["l'écolier","小学生","schoolchild","écol"], ["le maître","主人,老师","master, teacher","maîtr"], ["la maîtresse","女教师","mistress, teacher","maîtr"], ["maîtriser","掌握","master","maîtr"], ["l'histoire","历史,故事","history, story","histoir"], ["historique","历史的","historic","histoir"], ["l'image","图像","image","image"], ["imaginer","想象","imagine","image"], ["l'imagination","想象力","imagination","image"], ["l'ordre","秩序,命令","order","ordr"], ["ordinaire","普通的","ordinary","ordr"], ["l'ordinateur","电脑","computer","ordr"], ["la loi","法律","law","lo"], ["légal","合法的","legal","lo"], ["le gouvernement","政府","government","gouv"], ["gouverner","治理","govern","gouv"], ["le chef","首领,厨师","chief, chef","chef"], ["commun","共同的","common","comm"], ["la communauté","社区","community","comm"], ["communiquer","交流","communicate","comm"], ["la commune","市镇","municipality","comm"], ["social","社会的","social","soci"], ["la société","社会,公司","society, company","soci"], ["l'associé","合伙人","partner","soci"], ["la culture","文化","culture","cult"], ["cultiver","耕种","cultivate","cult"], ["l'agriculture","农业","agriculture","cult"], ["la fête","节日","party, festival","fête"], ["fêter","庆祝","celebrate","fête"], ["le festival","音乐节","festival","fête"], ["le cadeau","礼物","gift","cadeau"], ["le besoin","需要","need","besoin"], ["avoir besoin","需要","need","besoin"], ["aider","帮助","help","aid"], ["l'aide","帮助","help","aid"], ["servir","服务","serve","serv"], ["le service","服务","service","serv"], ["le serviteur","仆人","servant","serv"], ["garder","看守,保留","keep, guard","gard"], ["le garde","卫兵","guard","gard"], ["regarder","看","look at","gard"], ["le regard","目光","look","gard"], ["sauver","救","save","sauv"], ["le sauvetage","救援","rescue","sauv"], ["sauf","除了","except","sauv"], ["laisser","留下,让","leave, let","laiss"], ["tirer","拉,射","pull, shoot","tir"], ["attirer","吸引","attract","tir"], ["retirer","撤回","withdraw","tir"], ["pousser","推","push","pouss"], ["jeter","扔","throw","jet"], ["rejeter","拒绝","reject","jet"], ["projeter","投射,计划","project","jet"], ["le projet","计划","project","jet"], ["l'objet","物体","object","jet"], ["le sujet","主题","subject","jet"], ["le coup","一击","blow","coup"], ["couper","切","cut","coup"], ["beaucoup","很多","a lot","coup"], ["casser","打破","break","cass"], ["frapper","敲打","strike","frapp"], ["toucher","触碰","touch","touch"], ["montrer","展示","show","montr"], ["le monstre","怪物","monster","montr"], ["démontrer","证明","demonstrate","montr"], ["cacher","藏","hide","cach"], ["caché","隐藏的","hidden","cach"], ["laver","洗","wash","lav"], ["la machine","机器","machine","mach"], ["la lettre","字母,信","letter","lettr"], ["la littérature","文学","literature","lettr"], ["le papier","纸","paper","papier"], ["le rayon","光线,货架","ray, shelf","ray"], ["la radio","收音机","radio","ray"],
  ]
};
