/* =====================================================
   FUGA MYTHICA — CURSUS Spanish 🇪🇸 · batch 9 — topical vocabulary: business, law, IT, media, environment, science, health, society, arts, travel, weather
   ===================================================== */
(function () {
  const p = VOCAB.es;
  Object.assign(p.roots, {});
  p.words.push(
    ["la sociedad anónima", "股份公司", "corporation", "topic"],
    ["el accionista", "股东", "shareholder", "topic"],
    ["la Bolsa", "证券交易所", "stock market", "topic"],
    ["el bono", "债券", "bond", "topic"],
    ["el inversor", "投资者", "investor", "topic"],
    ["la facturación", "营业额", "turnover", "topic"],
    ["los ingresos", "收入", "revenue", "topic"],
    ["el presupuesto", "预算", "budget", "topic"],
    ["el balance", "资产负债表", "balance sheet", "topic"],
    ["el plazo", "截止日期", "deadline", "topic"],
    ["el tipo de interés", "利率", "interest rate", "topic"],
    ["los ahorros", "储蓄", "savings", "topic"],
    ["el tipo de cambio", "汇率", "exchange rate", "topic"],
    ["la inflación", "通胀", "inflation", "topic"],
    ["el competidor", "竞争者", "competitor", "topic"],
    ["el pedido", "订单", "order", "topic"],
    ["la entrega", "交货", "delivery", "topic"],
    ["las existencias", "库存", "stock", "topic"],
    ["el marketing", "市场营销", "marketing", "topic"],
    ["el comercio minorista", "零售", "retail", "topic"],
    ["el comercio mayorista", "批发", "wholesale", "topic"],
    ["el arancel", "关税", "tariff", "topic"],
    ["el IVA", "增值税", "VAT", "topic"],
    ["el contribuyente", "纳税人", "taxpayer", "topic"],
    ["la auditoría", "审计", "audit", "topic"],
    ["el gerente", "经理", "manager", "topic"],
    ["el empleador", "雇主", "employer", "topic"],
    ["el personal", "员工", "staff", "topic"],
    ["la contratación", "招聘", "recruitment", "topic"],
    ["el despido", "裁员", "dismissal", "topic"],
    ["la huelga", "罢工", "strike", "topic"],
    ["el sindicato", "工会", "trade union", "topic"],
    ["el desempleo", "失业", "unemployment", "topic"],
    ["el turno", "班次", "shift", "topic"],
    ["las horas extras", "加班", "overtime", "topic"],
    ["el orden del día", "议程", "agenda", "topic"],
    ["el acta", "会议记录", "minutes", "topic"],
    ["el objetivo", "目标", "goal", "topic"],
    ["la negociación", "谈判", "negotiation", "topic"],
    ["la asociación", "合作关系", "partnership", "topic"],
    ["la adquisición", "收购", "takeover", "topic"],
    ["la quiebra", "破产", "bankruptcy", "topic"],
    ["la startup", "初创公司", "startup", "topic"],
    ["el empresario", "企业家", "entrepreneur", "topic"],
    ["el proyecto de ley", "法案", "bill", "topic"],
    ["el parlamento", "议会", "parliament", "topic"],
    ["el diputado", "议员", "deputy", "topic"],
    ["el primer ministro", "总理", "prime minister", "topic"],
    ["el presidente", "总统", "president", "topic"],
    ["la coalición", "联合政府", "coalition", "topic"],
    ["el referéndum", "公投", "referendum", "topic"],
    ["la monarquía", "君主制", "monarchy", "topic"],
    ["el tribunal", "法院", "court", "topic"],
    ["el fiscal", "检察官", "prosecutor", "topic"],
    ["el acusado", "被告", "defendant", "topic"],
    ["el testigo", "证人", "witness", "topic"],
    ["la multa", "罚款", "fine", "topic"],
    ["la cárcel", "监狱", "prison", "topic"],
    ["el delito", "罪行", "crime", "topic"],
    ["el delincuente", "罪犯", "criminal", "topic"],
    ["el ladrón", "小偷", "thief", "topic"],
    ["el asesinato", "谋杀", "murder", "topic"],
    ["el fraude", "欺诈", "fraud", "topic"],
    ["la corrupción", "腐败", "corruption", "topic"],
    ["el soborno", "贿赂", "bribe", "topic"],
    ["el contrabando", "走私", "smuggling", "topic"],
    ["el sospechoso", "嫌疑人", "suspect", "topic"],
    ["la investigación", "调查", "investigation", "topic"],
    ["la detención", "逮捕", "arrest", "topic"],
    ["la cláusula", "条款", "clause", "topic"],
    ["el notario", "公证人", "notary", "topic"],
    ["el testamento", "遗嘱", "will", "topic"],
    ["la custodia", "监护权", "custody", "topic"],
    ["el asilo", "庇护", "asylum", "topic"],
    ["la embajada", "大使馆", "embassy", "topic"],
    ["el embajador", "大使", "ambassador", "topic"],
    ["la alianza", "联盟", "alliance", "topic"],
    ["el ataque", "攻击", "attack", "topic"],
    ["el terrorismo", "恐怖主义", "terrorism", "topic"],
    ["la manifestación", "示威", "demonstration", "topic"],
    ["los derechos humanos", "人权", "human rights", "topic"],
    ["la tableta", "平板电脑", "tablet", "topic"],
    ["el teléfono inteligente", "智能手机", "smartphone", "topic"],
    ["la impresora", "打印机", "printer", "topic"],
    ["el archivo", "文件", "file", "topic"],
    ["la carpeta", "文件夹", "folder", "topic"],
    ["el software", "软件", "software", "topic"],
    ["el hardware", "硬件", "hardware", "topic"],
    ["la aplicación", "应用程序", "app", "topic"],
    ["la actualización", "更新", "update", "topic"],
    ["la descarga", "下载", "download", "topic"],
    ["el internet", "互联网", "internet", "topic"],
    ["el buscador", "搜索引擎", "search engine", "topic"],
    ["el enlace", "链接", "link", "topic"],
    ["el archivo adjunto", "附件", "attachment", "topic"],
    ["el usuario", "用户", "user", "topic"],
    ["los datos", "数据", "data", "topic"],
    ["la base de datos", "数据库", "database", "topic"],
    ["el virus", "病毒", "virus", "topic"],
    ["el hacker", "黑客", "hacker", "topic"],
    ["la inteligencia artificial", "人工智能", "AI", "topic"],
    ["el robot", "机器人", "robot", "topic"],
    ["el código", "代码", "code", "topic"],
    ["la red social", "社交网络", "social network", "topic"],
    ["el seguidor", "关注者", "follower", "topic"],
    ["el pódcast", "播客", "podcast", "topic"],
    ["el titular", "标题", "headline", "topic"],
    ["el artículo", "文章", "article", "topic"],
    ["el editor", "编辑", "editor", "topic"],
    ["la rueda de prensa", "新闻发布会", "press conference", "topic"],
    ["el canal", "频道", "channel", "topic"],
    ["las noticias falsas", "假新闻", "fake news", "topic"],
    ["la censura", "审查", "censorship", "topic"],
    ["el medio ambiente", "环境", "environment", "topic"],
    ["la contaminación", "污染", "pollution", "topic"],
    ["el cambio climático", "气候变化", "climate change", "topic"],
    ["el calentamiento global", "全球变暖", "global warming", "topic"],
    ["el efecto invernadero", "温室效应", "greenhouse effect", "topic"],
    ["el dióxido de carbono", "二氧化碳", "CO2", "topic"],
    ["la energía renovable", "可再生能源", "renewable energy", "topic"],
    ["el panel solar", "太阳能板", "solar panel", "topic"],
    ["el aerogenerador", "风力涡轮机", "wind turbine", "topic"],
    ["el combustible fósil", "化石燃料", "fossil fuel", "topic"],
    ["el carbón", "煤", "coal", "topic"],
    ["el gas natural", "天然气", "natural gas", "topic"],
    ["la energía nuclear", "核能", "nuclear power", "topic"],
    ["la central eléctrica", "发电厂", "power station", "topic"],
    ["el reciclaje", "回收", "recycling", "topic"],
    ["los residuos", "废物", "waste", "topic"],
    ["el plástico", "塑料", "plastic", "topic"],
    ["la sequía", "干旱", "drought", "topic"],
    ["el huracán", "飓风", "hurricane", "topic"],
    ["el incendio forestal", "野火", "wildfire", "topic"],
    ["la deforestación", "森林砍伐", "deforestation", "topic"],
    ["la especie en peligro", "濒危物种", "endangered species", "topic"],
    ["el hábitat", "栖息地", "habitat", "topic"],
    ["la fauna", "野生动物", "wildlife", "topic"],
    ["la capa de ozono", "臭氧层", "ozone layer", "topic"],
    ["la sostenibilidad", "可持续性", "sustainability", "topic"],
    ["el experimento", "实验", "experiment", "topic"],
    ["el laboratorio", "实验室", "laboratory", "topic"],
    ["la teoría", "理论", "theory", "topic"],
    ["la medición", "测量", "measurement", "topic"],
    ["el ADN", "DNA", "DNA", "topic"],
    ["la velocidad de la luz", "光速", "speed of light", "topic"],
    ["la galaxia", "星系", "galaxy", "topic"],
    ["el satélite", "卫星", "satellite", "topic"],
    ["la nave espacial", "宇宙飞船", "spacecraft", "topic"],
    ["la vacuna", "疫苗", "vaccine", "topic"],
    ["el síntoma", "症状", "symptom", "topic"],
    ["la infección", "感染", "infection", "topic"],
    ["la pandemia", "大流行", "pandemic", "topic"],
    ["la presión arterial", "血压", "blood pressure", "topic"],
    ["el infarto", "心脏病发作", "heart attack", "topic"],
    ["el derrame cerebral", "中风", "stroke", "topic"],
    ["el cáncer", "癌症", "cancer", "topic"],
    ["la diabetes", "糖尿病", "diabetes", "topic"],
    ["la dieta", "饮食", "diet", "topic"],
    ["la salud mental", "心理健康", "mental health", "topic"],
    ["la depresión", "抑郁症", "depression", "topic"],
    ["el estrés", "压力", "stress", "topic"],
    ["los ancianos", "老年人", "elderly", "topic"],
    ["la desigualdad", "不平等", "inequality", "topic"],
    ["el sinhogarismo", "无家可归", "homelessness", "topic"],
    ["la organización benéfica", "慈善机构", "charity", "topic"],
    ["el voluntario", "志愿者", "volunteer", "topic"],
    ["la asistencia social", "社会福利", "welfare", "topic"],
    ["la alfabetización", "识字", "literacy", "topic"],
    ["la beca", "奖学金", "scholarship", "topic"],
    ["el título", "学位", "degree", "topic"],
    ["la clase magistral", "讲座", "lecture", "topic"],
    ["el seminario", "研讨会", "seminar", "topic"],
    ["la matrícula", "学费", "tuition fees", "topic"],
    ["el racismo", "种族主义", "racism", "topic"],
    ["el feminismo", "女权主义", "feminism", "topic"],
    ["la tradición", "传统", "tradition", "topic"],
    ["la costumbre", "习俗", "custom", "topic"],
    ["la sinagoga", "犹太会堂", "synagogue", "topic"],
    ["el templo", "寺庙", "temple", "topic"],
    ["el infierno", "地狱", "hell", "topic"],
    ["el funeral", "葬礼", "funeral", "topic"],
    ["el cementerio", "墓地", "cemetery", "topic"],
    ["el bautizo", "洗礼", "baptism", "topic"],
    ["la arquitectura", "建筑学", "architecture", "topic"],
    ["la escultura", "雕塑", "sculpture", "topic"],
    ["la pintura", "绘画", "painting", "topic"],
    ["la galería", "画廊", "gallery", "topic"],
    ["la orquesta", "管弦乐队", "orchestra", "topic"],
    ["el director de orquesta", "指挥", "conductor", "topic"],
    ["el ballet", "芭蕾", "ballet", "topic"],
    ["el piano", "钢琴", "piano", "topic"],
    ["el violín", "小提琴", "violin", "topic"],
    ["la flauta", "长笛", "flute", "topic"],
    ["la trompeta", "小号", "trumpet", "topic"],
    ["el ensayo", "排练", "rehearsal", "topic"],
    ["el escenario", "舞台", "stage", "topic"],
    ["la audiencia", "观众", "audience", "topic"],
    ["la trama", "情节", "plot", "topic"],
    ["el personaje", "角色", "character", "topic"],
    ["la editorial", "出版社", "publisher", "topic"],
    ["el cuento de hadas", "童话", "fairy tale", "topic"],
    ["el villano", "反派", "villain", "topic"],
    ["el documental", "纪录片", "documentary", "topic"],
    ["los dibujos animados", "动画片", "cartoon", "topic"],
    ["la banda sonora", "原声音乐", "soundtrack", "topic"],
    ["el festival", "节日", "festival", "topic"],
    ["los fuegos artificiales", "烟花", "fireworks", "topic"],
    ["el carnaval", "狂欢节", "carnival", "topic"],
    ["el disfraz", "服装", "costume", "topic"],
    ["el guía", "导游", "guide", "topic"],
    ["el mapa", "地图", "map", "topic"],
    ["el itinerario", "行程", "itinerary", "topic"],
    ["el camping", "营地", "campsite", "topic"],
    ["la tienda de campaña", "帐篷", "tent", "topic"],
    ["el senderismo", "徒步", "hiking", "topic"],
    ["el sendero", "小径", "trail", "topic"],
    ["la cumbre", "山顶", "summit", "topic"],
    ["la cascada", "瀑布", "waterfall", "topic"],
    ["el volcán", "火山", "volcano", "topic"],
    ["el acantilado", "悬崖", "cliff", "topic"],
    ["el faro", "灯塔", "lighthouse", "topic"],
    ["el trueno", "雷", "thunder", "topic"],
    ["el relámpago", "闪电", "lightning", "topic"],
    ["el granizo", "冰雹", "hail", "topic"],
    ["la brisa", "微风", "breeze", "topic"],
    ["la ola de calor", "热浪", "heatwave", "topic"]
  );
})();
