/* =====================================================
   FUGA MYTHICA — CURSUS English 🇬🇧 · batch 11 — topical vocabulary 4: family & life events, personal care, fashion, shopping, restaurant & drinks, airport & hotel, emergencies, colours, geography names, celebrations, phone & mail
   ===================================================== */
(function () {
  const p = VOCAB.en;
  Object.assign(p.roots, { therio: ["ther / therio", "野兽", "beast"], });
  p.words.push(
    ["stepfather", "继父", "stepfather", "topic"],
    ["stepmother", "继母", "stepmother", "topic"],
    ["stepbrother", "继兄弟", "stepbrother", "topic"],
    ["half-sister", "同父异母姐妹", "half-sister", "topic"],
    ["father-in-law", "岳父,公公", "father-in-law", "topic"],
    ["mother-in-law", "岳母,婆婆", "mother-in-law", "topic"],
    ["son-in-law", "女婿", "son-in-law", "topic"],
    ["daughter-in-law", "儿媳", "daughter-in-law", "topic"],
    ["brother-in-law", "姐夫,妹夫", "brother-in-law", "topic"],
    ["sister-in-law", "嫂子,弟媳", "sister-in-law", "topic"],
    ["grandson", "孙子", "grandson", "topic"],
    ["granddaughter", "孙女", "granddaughter", "topic"],
    ["great-grandfather", "曾祖父", "great-grandfather", "topic"],
    ["nephew", "侄子", "nephew", "topic"],
    ["niece", "侄女", "niece", "topic"],
    ["twin", "双胞胎", "twin", "topic"],
    ["only child", "独生子女", "only child", "topic"],
    ["orphan", "孤儿", "orphan", "topic"],
    ["widow", "寡妇", "widow", "topic"],
    ["widower", "鳏夫", "widower", "topic"],
    ["fiancé", "未婚夫", "fiancé", "topic"],
    ["bride", "新娘", "bride", "topic"],
    ["groom", "新郎", "groom", "topic"],
    ["couple", "情侣", "couple", "topic"],
    ["partner", "伴侣", "partner", "topic"],
    ["descendant", "后代", "descendant", "topic"],
    ["relative", "亲戚", "relative", "topic"],
    ["godfather", "教父", "godfather", "topic"],
    ["godmother", "教母", "godmother", "topic"],
    ["guardian", "监护人", "guardian", "topic"],
    ["acquaintance", "熟人", "acquaintance", "topic"],
    ["stranger", "陌生人", "stranger", "topic"],
    ["roommate", "室友", "roommate", "topic"],
    ["pregnancy", "怀孕", "pregnancy", "topic"],
    ["toddler", "幼儿", "toddler", "topic"],
    ["teenager", "青少年", "teenager", "topic"],
    ["adult", "成年人", "adult", "topic"],
    ["pensioner", "退休者", "pensioner", "topic"],
    ["engagement", "订婚", "engagement", "topic"],
    ["honeymoon", "蜜月", "honeymoon", "topic"],
    ["christening", "洗礼", "christening", "topic"],
    ["retirement", "退休", "retirement", "topic"],
    ["mourning", "哀悼", "mourning", "topic"],
    ["coffin", "棺材", "coffin", "topic"],
    ["toothbrush", "牙刷", "toothbrush", "topic"],
    ["toothpaste", "牙膏", "toothpaste", "topic"],
    ["soap", "肥皂", "soap", "topic"],
    ["shampoo", "洗发水", "shampoo", "topic"],
    ["towel", "毛巾", "towel", "topic"],
    ["razor", "剃须刀", "razor", "topic"],
    ["comb", "梳子", "comb", "topic"],
    ["hairbrush", "发刷", "hairbrush", "topic"],
    ["hairdryer", "吹风机", "hairdryer", "topic"],
    ["lipstick", "口红", "lipstick", "topic"],
    ["make-up", "化妆品", "make-up", "topic"],
    ["nail polish", "指甲油", "nail polish", "topic"],
    ["cream", "面霜", "cream", "topic"],
    ["sunscreen", "防晒霜", "sunscreen", "topic"],
    ["toilet paper", "卫生纸", "toilet paper", "topic"],
    ["nappy", "尿布", "nappy", "topic"],
    ["haircut", "理发", "haircut", "topic"],
    ["beard", "胡子", "beard", "topic"],
    ["moustache", "小胡子", "moustache", "topic"],
    ["fringe", "刘海", "fringe", "topic"],
    ["ponytail", "马尾辫", "ponytail", "topic"],
    ["wrinkle", "皱纹", "wrinkle", "topic"],
    ["freckle", "雀斑", "freckle", "topic"],
    ["scar", "疤痕", "scar", "topic"],
    ["tattoo", "纹身", "tattoo", "topic"],
    ["piercing", "穿孔", "piercing", "topic"],
    ["sleeve", "袖子", "sleeve", "topic"],
    ["collar", "衣领", "collar", "topic"],
    ["pocket", "口袋", "pocket", "topic"],
    ["hood", "兜帽", "hood", "topic"],
    ["lace", "蕾丝", "lace", "topic"],
    ["stripe", "条纹", "stripe", "topic"],
    ["pattern", "花纹", "pattern", "topic"],
    ["striped", "条纹的", "with stripes", "topic"],
    ["checked", "格子的", "with squares", "topic"],
    ["spotted", "圆点的", "with dots", "topic"],
    ["bow tie", "领结", "bow tie", "topic"],
    ["waistcoat", "马甲", "waistcoat", "topic"],
    ["blouse", "女衬衫", "blouse", "topic"],
    ["cardigan", "开襟毛衣", "cardigan", "topic"],
    ["hoodie", "连帽衫", "hoodie", "topic"],
    ["tracksuit", "运动服", "tracksuit", "topic"],
    ["shorts", "短裤", "shorts", "topic"],
    ["tights", "连裤袜", "tights", "topic"],
    ["underwear", "内衣", "underwear", "topic"],
    ["pyjamas", "睡衣", "pyjamas", "topic"],
    ["dressing gown", "睡袍", "dressing gown", "topic"],
    ["swimsuit", "泳衣", "swimsuit", "topic"],
    ["raincoat", "雨衣", "raincoat", "topic"],
    ["sandals", "凉鞋", "sandals", "topic"],
    ["slippers", "拖鞋", "slippers", "topic"],
    ["trainers", "运动鞋", "trainers", "topic"],
    ["high heels", "高跟鞋", "high heels", "topic"],
    ["shoelace", "鞋带", "shoelace", "topic"],
    ["necklace", "项链", "necklace", "topic"],
    ["bracelet", "手镯", "bracelet", "topic"],
    ["earring", "耳环", "earring", "topic"],
    ["brooch", "胸针", "brooch", "topic"],
    ["wallet", "钱包", "wallet", "topic"],
    ["purse", "零钱包", "purse", "topic"],
    ["handbag", "手提包", "handbag", "topic"],
    ["sunglasses", "太阳镜", "sunglasses", "topic"],
    ["changing room", "试衣间", "changing room", "topic"],
    ["shop window", "橱窗", "shop window", "topic"],
    ["shelf", "货架", "shelf", "topic"],
    ["trolley", "购物车", "trolley", "topic"],
    ["checkout", "收银台", "checkout", "topic"],
    ["queue", "队列", "queue", "topic"],
    ["exchange", "换货", "exchange", "topic"],
    ["guarantee", "保修", "guarantee", "topic"],
    ["label", "标签", "label", "topic"],
    ["barcode", "条形码", "barcode", "topic"],
    ["voucher", "优惠券", "voucher", "topic"],
    ["loyalty card", "会员卡", "loyalty card", "topic"],
    ["online shopping", "网购", "online shopping", "topic"],
    ["customer service", "客服", "customer service", "topic"],
    ["complaint", "投诉", "complaint", "topic"],
    ["jeweller", "珠宝店", "jeweller", "topic"],
    ["greengrocer", "蔬果店", "greengrocer", "topic"],
    ["fishmonger", "鱼店", "fishmonger", "topic"],
    ["delicatessen", "熟食店", "deli", "topic"],
    ["stationer", "文具店", "stationer", "topic"],
    ["hardware store", "五金店", "hardware store", "topic"],
    ["dry cleaner", "干洗店", "dry cleaner", "topic"],
    ["launderette", "自助洗衣店", "launderette", "topic"],
    ["starter", "前菜", "starter", "topic"],
    ["main course", "主菜", "main course", "topic"],
    ["dessert", "甜点", "dessert", "topic"],
    ["side dish", "配菜", "side dish", "topic"],
    ["set menu", "套餐", "set menu", "topic"],
    ["speciality", "特色菜", "speciality", "topic"],
    ["portion", "一份", "portion", "topic"],
    ["sauce", "酱汁", "sauce", "topic"],
    ["dressing", "沙拉酱", "dressing", "topic"],
    ["stew", "炖菜", "stew", "topic"],
    ["omelette", "煎蛋卷", "omelette", "topic"],
    ["sandwich", "三明治", "sandwich", "topic"],
    ["pancake", "薄饼", "pancake", "topic"],
    ["pie", "馅饼", "pie", "topic"],
    ["pastry", "酥皮糕点", "pastry", "topic"],
    ["bun", "小圆面包", "bun", "topic"],
    ["jam", "果酱", "jam", "topic"],
    ["honey", "蜂蜜", "honey", "topic"],
    ["cereal", "麦片", "cereal", "topic"],
    ["yoghurt", "酸奶", "yoghurt", "topic"],
    ["mustard", "芥末", "mustard", "topic"],
    ["ketchup", "番茄酱", "ketchup", "topic"],
    ["mayonnaise", "蛋黄酱", "mayonnaise", "topic"],
    ["herb", "香草", "herb", "topic"],
    ["spice", "香料", "spice", "topic"],
    ["cinnamon", "肉桂", "cinnamon", "topic"],
    ["ginger", "姜", "ginger", "topic"],
    ["vanilla", "香草", "vanilla", "topic"],
    ["chocolate", "巧克力", "chocolate", "topic"],
    ["sweet", "糖果", "sweet", "topic"],
    ["chewing gum", "口香糖", "chewing gum", "topic"],
    ["crisps", "薯片", "crisps", "topic"],
    ["popcorn", "爆米花", "popcorn", "topic"],
    ["lemonade", "柠檬水", "lemonade", "topic"],
    ["fizzy drink", "汽水", "fizzy drink", "topic"],
    ["smoothie", "果昔", "smoothie", "topic"],
    ["cocktail", "鸡尾酒", "cocktail", "topic"],
    ["champagne", "香槟", "champagne", "topic"],
    ["cider", "苹果酒", "cider", "topic"],
    ["whisky", "威士忌", "whisky", "topic"],
    ["liqueur", "利口酒", "liqueur", "topic"],
    ["straw", "吸管", "straw", "topic"],
    ["ice cube", "冰块", "ice cube", "topic"],
    ["tip", "小费", "tip", "topic"],
    ["vegetarian", "素食的", "no meat", "topic"],
    ["vegan", "纯素的", "no animal products", "topic"],
    ["organic", "有机的", "organic", "topic"],
    ["homemade", "自制的", "homemade", "topic"],
    ["takeaway", "外带", "takeaway", "topic"],
    ["boarding pass", "登机牌", "boarding pass", "topic"],
    ["departure", "出发", "departure", "topic"],
    ["arrival", "到达", "arrival", "topic"],
    ["baggage", "行李", "baggage", "topic"],
    ["hand luggage", "手提行李", "hand luggage", "topic"],
    ["conveyor belt", "传送带", "conveyor belt", "topic"],
    ["security check", "安检", "security check", "topic"],
    ["runway", "跑道", "runway", "topic"],
    ["crew", "机组", "crew", "topic"],
    ["stewardess", "空姐", "stewardess", "topic"],
    ["aisle", "过道", "aisle", "topic"],
    ["window seat", "靠窗座位", "window seat", "topic"],
    ["turbulence", "颠簸", "turbulence", "topic"],
    ["jet lag", "时差", "jet lag", "topic"],
    ["stopover", "中途停留", "stopover", "topic"],
    ["return ticket", "往返票", "return ticket", "topic"],
    ["single ticket", "单程票", "single ticket", "topic"],
    ["timetable", "时刻表", "timetable", "topic"],
    ["carriage", "车厢", "carriage", "topic"],
    ["compartment", "隔间", "compartment", "topic"],
    ["sleeper", "卧铺", "sleeper", "topic"],
    ["ticket inspector", "检票员", "ticket inspector", "topic"],
    ["lobby", "大堂", "lobby", "topic"],
    ["single room", "单人间", "single room", "topic"],
    ["double room", "双人间", "double room", "topic"],
    ["room service", "客房服务", "room service", "topic"],
    ["half board", "半食宿", "half board", "topic"],
    ["full board", "全食宿", "full board", "topic"],
    ["check-out", "退房", "check-out", "topic"],
    ["youth hostel", "青年旅舍", "youth hostel", "topic"],
    ["bed and breakfast", "民宿", "B&B", "topic"],
    ["guesthouse", "旅社", "guesthouse", "topic"],
    ["travel agency", "旅行社", "travel agency", "topic"],
    ["package holiday", "跟团游", "package holiday", "topic"],
    ["insurance", "保险", "insurance", "topic"],
    ["exchange office", "货币兑换处", "exchange office", "topic"],
    ["fire engine", "消防车", "fire engine", "topic"],
    ["fire extinguisher", "灭火器", "fire extinguisher", "topic"],
    ["fire alarm", "火警", "fire alarm", "topic"],
    ["emergency exit", "紧急出口", "emergency exit", "topic"],
    ["first aid", "急救", "first aid", "topic"],
    ["first aid kit", "急救箱", "first aid kit", "topic"],
    ["stretcher", "担架", "stretcher", "topic"],
    ["crutch", "拐杖", "crutch", "topic"],
    ["wheelchair", "轮椅", "wheelchair", "topic"],
    ["poisoning", "中毒", "poisoning", "topic"],
    ["rescue", "救援", "rescue", "topic"],
    ["lifeguard", "救生员", "lifeguard", "topic"],
    ["lifeboat", "救生艇", "lifeboat", "topic"],
    ["life jacket", "救生衣", "life jacket", "topic"],
    ["warning", "警告", "warning", "topic"],
    ["danger sign", "危险标志", "danger sign", "topic"],
    ["siren", "警报器", "siren", "topic"],
    ["evacuation", "疏散", "evacuation", "topic"],
    ["shelter", "避难所", "shelter", "topic"],
    ["survivor", "幸存者", "survivor", "topic"],
    ["victim", "受害者", "victim", "topic"],
    ["beige", "米色", "beige", "topic"],
    ["turquoise", "绿松石色", "turquoise", "topic"],
    ["navy blue", "海军蓝", "navy", "topic"],
    ["crimson", "深红", "crimson", "topic"],
    ["scarlet", "猩红", "scarlet", "topic"],
    ["maroon", "栗色", "maroon", "topic"],
    ["lilac", "淡紫", "lilac", "topic"],
    ["violet", "紫罗兰色", "violet", "topic"],
    ["olive green", "橄榄绿", "olive green", "topic"],
    ["emerald", "翡翠绿", "emerald", "topic"],
    ["ivory", "象牙色", "ivory", "topic"],
    ["bronze", "青铜色", "bronze", "topic"],
    ["khaki", "卡其色", "khaki", "topic"],
    ["amber", "琥珀色", "amber", "topic"],
    ["faded", "褪色的", "faded", "topic"],
    ["shade", "色调", "shade", "topic"],
    ["Europe", "欧洲", "Europe", "topic"],
    ["Asia", "亚洲", "Asia", "topic"],
    ["Africa", "非洲", "Africa", "topic"],
    ["North America", "北美洲", "North America", "topic"],
    ["South America", "南美洲", "South America", "topic"],
    ["Oceania", "大洋洲", "Oceania", "topic"],
    ["Antarctica", "南极洲", "Antarctica", "topic"],
    ["Atlantic", "大西洋", "Atlantic", "topic"],
    ["Pacific", "太平洋", "Pacific", "topic"],
    ["Alps", "阿尔卑斯山", "Alps", "topic"],
    ["Pyrenees", "比利牛斯山", "Pyrenees", "topic"],
    ["Rhine", "莱茵河", "Rhine", "topic"],
    ["Danube", "多瑙河", "Danube", "topic"],
    ["Nile", "尼罗河", "Nile", "topic"],
    ["North Pole", "北极", "North Pole", "topic"],
    ["tropics", "热带", "tropics", "topic"],
    ["time zone", "时区", "time zone", "topic"],
    ["county", "郡", "county", "topic"],
    ["state", "国家,州", "state", "topic"],
    ["Germany", "德国", "Germany", "topic"],
    ["France", "法国", "France", "topic"],
    ["Spain", "西班牙", "Spain", "topic"],
    ["Italy", "意大利", "Italy", "topic"],
    ["England", "英格兰", "England", "topic"],
    ["United Kingdom", "英国", "UK", "topic"],
    ["United States", "美国", "USA", "topic"],
    ["China", "中国", "China", "topic"],
    ["Japan", "日本", "Japan", "topic"],
    ["Russia", "俄罗斯", "Russia", "topic"],
    ["Greece", "希腊", "Greece", "topic"],
    ["Switzerland", "瑞士", "Switzerland", "topic"],
    ["Netherlands", "荷兰", "Netherlands", "topic"],
    ["Egypt", "埃及", "Egypt", "topic"],
    ["India", "印度", "India", "topic"],
    ["Brazil", "巴西", "Brazil", "topic"],
    ["New Year", "新年", "New Year", "topic"],
    ["Christmas Eve", "平安夜", "Christmas Eve", "topic"],
    ["Christmas tree", "圣诞树", "Christmas tree", "topic"],
    ["Easter egg", "复活节彩蛋", "Easter egg", "topic"],
    ["Valentine's Day", "情人节", "Valentine's Day", "topic"],
    ["Mother's Day", "母亲节", "Mother's Day", "topic"],
    ["Halloween", "万圣节", "Halloween", "topic"],
    ["national holiday", "国庆日", "national holiday", "topic"],
    ["bank holiday", "公共假日", "public holiday", "topic"],
    ["birthday party", "生日派对", "birthday party", "topic"],
    ["birthday cake", "生日蛋糕", "birthday cake", "topic"],
    ["candle", "蜡烛", "candle", "topic"],
    ["balloon", "气球", "balloon", "topic"],
    ["invitation", "邀请", "invitation", "topic"],
    ["guest", "客人", "guest", "topic"],
    ["toast", "祝酒", "toast", "topic"],
    ["greeting card", "贺卡", "greeting card", "topic"],
    ["gift wrap", "礼品包装纸", "gift wrap", "topic"],
    ["ribbon", "丝带", "ribbon", "topic"],
    ["phone call", "电话", "phone call", "topic"],
    ["phone number", "电话号码", "phone number", "topic"],
    ["area code", "区号", "area code", "topic"],
    ["voicemail", "语音信箱", "voicemail", "topic"],
    ["text message", "短信", "text message", "topic"],
    ["missed call", "未接来电", "missed call", "topic"],
    ["ringtone", "铃声", "ringtone", "topic"],
    ["charger", "充电器", "charger", "topic"],
    ["SIM card", "SIM卡", "SIM card", "topic"],
    ["landline", "座机", "landline", "topic"],
    ["sender", "寄件人", "sender", "topic"],
    ["address", "地址", "address", "topic"],
    ["postcode", "邮编", "postcode", "topic"],
    ["postcard", "明信片", "postcard", "topic"],
    ["registered letter", "挂号信", "registered letter", "topic"],
    ["postman", "邮递员", "postman", "topic"],
    ["mailbox", "邮箱", "mailbox", "topic"],
    ["dear", "亲爱的", "dear", "topic"],
    ["yours sincerely", "此致敬礼", "yours sincerely", "topic"],
    ["subject line", "主题行", "subject", "topic"],
    ["spam", "垃圾邮件", "spam", "topic"],
    ["inbox", "收件箱", "inbox", "topic"]
  );
})();
