/* =====================================================
   FUGA MYTHICA — CURSUS vocabulary pack: German 🇩🇪
   roots: id -> [rootForm, zhGist, enGist]
   words: [word, zhGist, enGist, rootId]   (order = frequency tier; 500 per tier)
   Gists are deliberately approximate: the goal is instant recognition, not precision.
   ===================================================== */
VOCAB.de = {
  name: { zh: "德语", en: "German" }, flag: "🇩🇪",
  roots: {
    geh:  ["geh-/gang-", "走", "go"],
    komm: ["komm-/kunft-", "来", "come"],
    steh: ["steh-/stand-", "站,立", "stand"],
    sitz: ["sitz-/setz-", "坐,放", "sit, set"],
    leg:  ["leg-/lieg-", "放,躺", "lay, lie"],
    fahr: ["fahr-/fuhr-", "行驶", "travel, drive"],
    trag: ["trag-", "扛,穿", "carry, wear"],
    geb:  ["geb-/gab-", "给", "give"],
    nehm: ["nehm-/nahm-", "拿", "take"],
    sprech:["sprech-/sprach-", "说", "speak"],
    seh:  ["seh-/sicht-", "看", "see"],
    hör:  ["hör-", "听", "hear"],
    schreib:["schreib-/schrift-", "写", "write"],
    les:  ["les-", "读", "read"],
    lern: ["lern-/lehr-", "学,教", "learn, teach"],
    denk: ["denk-/dank-", "想,谢", "think, thank"],
    wiss: ["wiss-", "知", "know"],
    kenn: ["kenn-", "认识", "know (be familiar)"],
    find: ["find-", "找到", "find"],
    such: ["such-", "寻找", "seek"],
    halt: ["halt-", "持,停", "hold, stop"],
    zieh: ["zieh-/zug-", "拉,拖", "pull, draw"],
    fall: ["fall-", "落", "fall"],
    brech:["brech-/bruch-", "断,破", "break"],
    schlag:["schlag-", "打", "strike"],
    lauf: ["lauf-", "跑", "run"],
    spiel:["spiel-", "玩", "play"],
    arbeit:["arbeit-", "工作", "work"],
    hand: ["hand-", "手", "hand"],
    haus: ["haus-", "房子", "house"],
    stadt:["stadt-/stätt-", "城,地点", "town, place"],
    land: ["land-", "土地,国家", "land"],
    weg:  ["weg-", "路", "way"],
    zeit: ["zeit-", "时间", "time"],
    tag:  ["tag-", "日", "day"],
    jahr: ["jahr-", "年", "year"],
    kind: ["kind-", "孩子", "child"],
    freund:["freund-", "朋友", "friend"],
    lieb: ["lieb-", "爱", "love"],
    leb:  ["leb-", "活,生命", "live, life"],
    kauf: ["kauf-", "买", "buy"],
    zahl: ["zahl-", "数,付", "number, pay"],
    wasser:["wasser-", "水", "water"],
    licht:["licht-/leucht-", "光", "light"],
    wort: ["wort-", "词,话", "word"],
    frag: ["frag-", "问", "ask"],
    antwort:["antwort-", "答", "answer"],
    mach: ["mach-", "做", "make"],
    tu:   ["tu-/tat-", "做,行为", "do, deed"],
    kraft:["kraft-/kräft-", "力", "strength"],
    macht:["macht-/mög-", "权力,可能", "power, may"],
    dienst:["dien-", "服务", "serve"],
    schul:["schul-", "学校", "school"],
    bild: ["bild-", "图,形", "picture, form"],
    ordn: ["ordn-", "秩序", "order"],
    recht:["recht-", "正确,权利", "right"],
    wahr: ["wahr-", "真", "true"],
    schön:["schön-", "美", "beautiful"],
    groß: ["groß-", "大", "big"],
    klein:["klein-", "小", "small"],
    hoch: ["hoch-/höh-", "高", "high"],
    tief: ["tief-", "深", "deep"],
    lang: ["lang-/läng-", "长", "long"],
    kurz: ["kurz-/kürz-", "短", "short"],
    alt:  ["alt-/ält-", "老", "old"],
    neu:  ["neu-", "新", "new"],
    gut:  ["gut-/güt-", "好", "good"],
    schwer:["schwer-", "重,难", "heavy, hard"],
    leicht:["leicht-", "轻,容易", "light, easy"],
    stark:["stark-/stärk-", "强", "strong"],
    krank:["krank-", "病", "sick"],
    gesund:["gesund-", "健康", "healthy"],
    voll: ["voll-/füll-", "满", "full"],
    frei: ["frei-", "自由", "free"],
    warm: ["warm-/wärm-", "暖", "warm"],
    kalt: ["kalt-/kält-", "冷", "cold"],
    schnell:["schnell-", "快", "fast"],
    fest: ["fest-", "牢固,节日", "firm, festival"],
    reich:["reich-", "富,帝国", "rich, realm"],
    öffn: ["offen-/öffn-", "开", "open"],
    schließ:["schließ-/schluss-", "关,结束", "close, end"],
    end:  ["end-", "结束", "end"],
    anfang:["fang-", "抓,开始", "catch, begin"],
    glaub:["glaub-", "相信", "believe"],
    hoff: ["hoff-", "希望", "hope"],
    fürcht:["furcht-/fürcht-", "怕", "fear"],
    freu: ["freu-", "高兴", "joy"],
    lach: ["lach-", "笑", "laugh"],
    wein: ["wein-", "哭", "cry"],
    schlaf:["schlaf-", "睡", "sleep"],
    ess:  ["ess-/aß-", "吃", "eat"],
    trink:["trink-/trunk-", "喝", "drink"],
    koch: ["koch-", "煮", "cook"],
    wohn: ["wohn-", "住", "dwell"],
    bau:  ["bau-", "建造", "build"],
    wachs:["wachs-", "生长", "grow"],
    bring:["bring-/bracht-", "带来", "bring"],
    send: ["send-/sand-", "送", "send"],
    reis: ["reis-", "旅行", "journey"],
    flieg:["flieg-/flug-", "飞", "fly"],
    schwimm:["schwimm-", "游泳", "swim"],
    sing: ["sing-/sang-", "唱", "sing"],
    tanz: ["tanz-", "跳舞", "dance"],
    kämpf:["kampf-/kämpf-", "战斗", "fight"],
    sieg: ["sieg-", "胜利", "victory"],
    tod:  ["tod-/töt-", "死", "death"],
    gott: ["gott-/gött-", "神", "god"],
    himmel:["himmel-", "天", "sky, heaven"],
    erde: ["erd-", "地", "earth"],
    feuer:["feuer-", "火", "fire"],
    luft: ["luft-", "空气", "air"],
    stein:["stein-", "石", "stone"],
    baum: ["baum-", "树", "tree"],
    blum: ["blum-/blüh-", "花,开花", "flower, bloom"],
    tier: ["tier-", "动物", "animal"],
    vogel:["vogel-", "鸟", "bird"],
    fisch:["fisch-", "鱼", "fish"],
    hund: ["hund-", "狗", "dog"],
    pferd:["pferd-", "马", "horse"],
    kopf: ["kopf-", "头", "head"],
    herz: ["herz-", "心", "heart"],
    aug:  ["aug-", "眼", "eye"],
    mund: ["mund-/münd-", "口", "mouth"],
    fuß:  ["fuß-", "脚", "foot"],
    sprach:["sprach-", "语言", "language"],
    buch: ["buch-/büch-", "书", "book"],
    zahn: ["zahn-", "牙", "tooth"],
    nam:  ["nam-/nenn-", "名", "name"],
    mut:  ["mut-", "勇气,心情", "courage, mood"],
    sinn: ["sinn-", "感觉,意义", "sense, meaning"],
    geist:["geist-", "精神,灵", "spirit, mind"],
    seel: ["seel-", "灵魂", "soul"],
    ruh:  ["ruh-", "安静", "rest"],
    laut: ["laut-", "响,声", "loud, sound"],
    still:["still-", "静", "quiet"],
    dunkel:["dunkel-", "暗", "dark"],
    farb: ["farb-/färb-", "颜色", "color"],
    rot:  ["rot-/röt-", "红", "red"],
    weiß: ["weiß-", "白", "white"],
    schwarz:["schwarz-", "黑", "black"],
    grün: ["grün-", "绿", "green"],
    blau: ["blau-", "蓝", "blue"],
    gelb: ["gelb-", "黄", "yellow"],
    eins: ["ein-", "一", "one"],
    zwei: ["zwei-/zwi-", "二", "two"],
    drei: ["drei-", "三", "three"],
    zehn: ["zehn-/zig-", "十", "ten"],
    hundert:["hundert-", "百", "hundred"],
    tausend:["tausend-", "千", "thousand"],
    mitt: ["mitt-", "中", "middle"],
    ober: ["ob-/ober-", "上", "upper"],
    unter:["unter-", "下", "under"],
    vor:  ["vor-", "前", "before, fore"],
    nach: ["nach-", "后,向", "after, toward"],
    zurück:["rück-", "回,背", "back"],
    aus:  ["aus-/äuß-", "外,出", "out"],
    ein:  ["ein-/inn-", "内,入", "in"],
    über: ["über-", "超,过", "over"],
    durch:["durch-", "穿过", "through"],
    um:   ["um-", "环绕,改", "around, change"],
    wieder:["wieder-", "再", "again"],
    zusammen:["sammel-", "一起,收集", "together, collect"],
    teil: ["teil-", "部分,分", "part"],
    ganz: ["ganz-", "整个", "whole"],
    art:  ["art-", "种类,方式", "kind, manner"],
    ding: ["ding-", "东西", "thing"],
    sach: ["sach-", "事物", "matter"],
    mensch:["mensch-", "人", "human"],
    mann: ["mann-/männ-", "男人", "man"],
    frau: ["frau-", "女人", "woman"],
    vater:["vater-/väter-", "父", "father"],
    mutter:["mutter-/mütter-", "母", "mother"],
    bruder:["bruder-/brüder-", "兄弟", "brother"],
    schwester:["schwester-", "姐妹", "sister"],
    volk: ["volk-/völk-", "民族", "people"],
    krieg:["krieg-", "战争", "war"],
    fried:["fried-", "和平", "peace"],
    welt: ["welt-", "世界", "world"],
    meer: ["meer-", "海", "sea"],
    berg: ["berg-", "山", "mountain"],
    wald: ["wald-/wäld-", "森林", "forest"],
    stern:["stern-", "星", "star"],
    sonn: ["sonn-", "太阳", "sun"],
    mond: ["mond-", "月亮", "moon"],
    nacht:["nacht-/nächt-", "夜", "night"],
    morgen:["morgen-", "早晨,明天", "morning, tomorrow"],
    abend:["abend-", "晚上", "evening"],
    woch: ["woch-", "周", "week"],
    monat:["monat-", "月份", "month"],
    stund:["stund-/stünd-", "小时", "hour"],
    weg2: ["weg-", "离开,走开", "away"],
    los:  ["los-/lös-", "松开,解决", "loose, solve"],
    bind: ["bind-/band-/bund-", "绑,联合", "bind, bond"],
    schneid:["schneid-/schnitt-", "切", "cut"],
    wasch:["wasch-", "洗", "wash"],
    wechsel:["wechsel-", "换", "exchange"],
    wend: ["wend-/wand-", "转", "turn"],
    weis: ["weis-", "指示,智慧", "point, wise"],
    zeig: ["zeig-/zeich-", "指,画,符号", "show, sign"],
    rat:  ["rat-/rät-", "建议,猜", "advise, guess"],
    ruf:  ["ruf-", "叫,呼", "call"],
    heiß: ["heiß-", "叫做,热", "be called, hot"],
    fehl: ["fehl-", "缺,错", "lack, error"],
    fühl: ["fühl-", "感觉", "feel"],
    wünsch:["wunsch-/wünsch-", "愿望", "wish"],
    woll: ["woll-/will-", "想要,意志", "want, will"],
    müss: ["muss-/müss-", "必须", "must"],
    könn: ["kann-/könn-", "能", "can"],
    dürf: ["darf-/dürf-", "允许", "may"],
    soll: ["soll-", "应该", "should"],
    brauch:["brauch-", "需要,习俗", "need, custom"],
    nutz: ["nutz-/nütz-", "用,益", "use, benefit"],
    dank: ["dank-", "感谢", "thanks"],
    bitt: ["bitt-", "请求", "request"],
    grüß:["gruß-/grüß-", "问候", "greet"],
    wart: ["wart-", "等,看守", "wait, keep"],
    zweifel:["zweifel-", "怀疑", "doubt"],
    schuld:["schuld-", "过错,债", "guilt, debt"],
    lohn: ["lohn-", "报酬", "wage"],
    geld: ["geld-/gelt-", "钱,有效", "money, be valid"],
    preis:["preis-", "价格,奖", "price, prize"],
    markt:["markt-", "市场", "market"],
    stell:["stell-", "放置,位置", "place, position"],
    setz: ["setz-/satz-", "放,句子,法律", "set, sentence, law"],
    ziel: ["ziel-", "目标", "goal"],
    weit: ["weit-", "远,宽", "far, wide"],
    nah:  ["nah-/näh-", "近", "near"],
    heim: ["heim-", "家", "home"],
    tür:  ["tür-/tor-", "门", "door, gate"],
    fenster:["fenster-", "窗", "window"],
    tisch:["tisch-", "桌", "table"],
    bett: ["bett-", "床", "bed"],
    kleid:["kleid-", "衣服", "dress"],
    schuh:["schuh-", "鞋", "shoe"],
    brot: ["brot-", "面包", "bread"],
    milch:["milch-", "奶", "milk"],
    apfel:["apfel-/äpfel-", "苹果", "apple"],
    wagen:["wag-/weg-", "车,敢", "wagon, dare"],
    straß:["straß-", "街", "street"],
    brück:["brück-", "桥", "bridge"],
    schiff:["schiff-", "船", "ship"],
    bahn: ["bahn-", "轨道,铁路", "track, railway"],
    stück:["stück-", "块,件", "piece"],
    zug:  ["zug-/züg-", "拉,火车,列", "pull, train"],
    mal:  ["mal-", "次,画", "time (occasion), paint"],
    spät: ["spät-", "晚", "late"],
    früh: ["früh-", "早", "early"],
    jung: ["jung-/jüng-", "年轻", "young"],
    schwach:["schwach-/schwäch-", "弱", "weak"],
    arm:  ["arm-/ärm-", "穷,手臂", "poor, arm"],
    heil: ["heil-", "治愈,神圣", "heal, holy"],
    ehr:  ["ehr-", "荣誉", "honor"],
    treu: ["treu-/trau-", "忠诚,信任", "loyal, trust"],
    wund: ["wund-", "伤,奇", "wound, wonder"],
    wunder:["wunder-", "奇迹", "wonder"],
    zauber:["zauber-", "魔法", "magic"],
    held: ["held-", "英雄", "hero"],
    könig:["könig-", "国王", "king"],
    herr: ["herr-", "主,先生", "lord, mister"],
    kirch:["kirch-", "教堂", "church"],
    grund:["grund-/gründ-", "基础,理由", "ground, reason"],
    fest2:["fest-", "确定", "fixed"],
  },
  words: [
    /* ---- Tier 1: core verbs & their families ---- */
    ["gehen","走,去","go","geh"], ["der Gang","走廊,步伐","corridor, gait","geh"], ["der Eingang","入口","entrance","geh"], ["der Ausgang","出口","exit","geh"], ["vergehen","逝去","pass away (time)","geh"], ["der Übergang","过渡,通道","transition","geh"], ["vergangen","过去的","past","geh"],
    ["kommen","来","come","komm"], ["ankommen","到达","arrive","komm"], ["bekommen","得到","get, receive","komm"], ["die Zukunft","未来","future","komm"], ["die Ankunft","到达","arrival","komm"], ["willkommen","欢迎","welcome","komm"], ["die Herkunft","来源,出身","origin","komm"],
    ["stehen","站","stand","steh"], ["verstehen","理解","understand","steh"], ["entstehen","产生","arise","steh"], ["der Stand","状态,摊位","state, stall","steh"], ["der Verstand","理智","intellect","steh"], ["der Zustand","状况","condition","steh"], ["bestehen","存在,通过(考试)","exist, pass (exam)","steh"], ["der Aufstand","起义","uprising","steh"],
    ["sitzen","坐","sit","sitz"], ["setzen","放,坐下","set, sit down","sitz"], ["besitzen","拥有","own","sitz"], ["der Sitz","座位","seat","sitz"], ["der Besitz","财产","possession","sitz"], ["übersetzen","翻译","translate","sitz"], ["ersetzen","替换","replace","sitz"],
    ["legen","放","lay","leg"], ["liegen","躺,位于","lie","leg"], ["die Lage","位置,形势","position, situation","leg"], ["überlegen","考虑","consider","leg"], ["die Anlage","设施,天赋","facility, talent","leg"], ["vorlegen","呈交","present","leg"], ["erlegen","击毙","bring down","leg"],
    ["fahren","行驶","drive, ride","fahr"], ["die Fahrt","行程","trip","fahr"], ["erfahren","经历,得知","experience, learn of","fahr"], ["die Erfahrung","经验","experience","fahr"], ["die Gefahr","危险","danger","fahr"], ["gefährlich","危险的","dangerous","fahr"], ["das Fahrrad","自行车","bicycle","fahr"],
    ["tragen","扛,穿","carry, wear","trag"], ["der Vertrag","合同","contract","trag"], ["der Beitrag","贡献","contribution","trag"], ["der Auftrag","任务,委托","assignment","trag"], ["ertragen","忍受","endure","trag"], ["übertragen","传送","transmit","trag"], ["der Antrag","申请","application","trag"],
    ["geben","给","give","geb"], ["die Gabe","礼物,天赋","gift","geb"], ["die Aufgabe","任务,作业","task","geb"], ["die Ausgabe","支出,版本","expense, edition","geb"], ["aufgeben","放弃","give up","geb"], ["ergeben","产生,投降","result, surrender","geb"], ["das Ergebnis","结果","result","geb"], ["die Umgebung","周围环境","surroundings","geb"],
    ["nehmen","拿","take","nehm"], ["annehmen","接受,假设","accept, assume","nehm"], ["die Annahme","假设","assumption","nehm"], ["teilnehmen","参加","take part","nehm"], ["unternehmen","从事","undertake","nehm"], ["das Unternehmen","企业","company","nehm"], ["die Ausnahme","例外","exception","nehm"], ["angenehm","舒适的","pleasant","nehm"],
    ["sprechen","说","speak","sprech"], ["die Sprache","语言","language","sprech"], ["das Gespräch","谈话","conversation","sprech"], ["versprechen","承诺","promise","sprech"], ["besprechen","讨论","discuss","sprech"], ["der Spruch","格言","saying","sprech"], ["entsprechen","符合","correspond","sprech"],
    ["sehen","看","see","seh"], ["die Sicht","视野","view","seh"], ["die Absicht","意图","intention","seh"], ["die Aussicht","景色,前景","view, prospect","seh"], ["die Rücksicht","顾及","consideration","seh"], ["übersehen","忽视","overlook","seh"], ["vorsichtig","小心的","careful","seh"], ["offensichtlich","显然","obvious","seh"],
    ["hören","听","hear","hör"], ["gehören","属于","belong","hör"], ["aufhören","停止","stop","hör"], ["zuhören","倾听","listen","hör"], ["der Zuhörer","听众","listener","hör"], ["verhören","审问","interrogate","hör"],
    ["schreiben","写","write","schreib"], ["die Schrift","文字","script","schreib"], ["beschreiben","描述","describe","schreib"], ["die Zeitschrift","杂志","magazine","schreib"], ["die Vorschrift","规定","regulation","schreib"], ["unterschreiben","签名","sign","schreib"], ["schriftlich","书面的","written","schreib"],
    ["lesen","读","read","les"], ["der Leser","读者","reader","les"], ["vorlesen","朗读","read aloud","les"], ["die Vorlesung","讲座","lecture","les"], ["auslesen","挑选","pick out","les"],
    ["lernen","学","learn","lern"], ["lehren","教","teach","lern"], ["der Lehrer","老师","teacher","lern"], ["die Lehre","学说,学徒期","doctrine, apprenticeship","lern"], ["der Lehrling","学徒","apprentice","lern"],
    ["denken","想","think","denk"], ["der Gedanke","想法","thought","denk"], ["danken","感谢","thank","denk"], ["nachdenken","思考","reflect","denk"], ["das Andenken","纪念品","souvenir","denk"], ["bedenken","考虑","consider","denk"],
    ["wissen","知道","know","wiss"], ["die Wissenschaft","科学","science","wiss"], ["gewiss","确定的","certain","wiss"], ["das Gewissen","良心","conscience","wiss"], ["bewusst","有意识的","conscious","wiss"], ["der Beweis","证据","proof","wiss"],
    ["kennen","认识","know (person)","kenn"], ["die Kenntnis","知识","knowledge","kenn"], ["erkennen","认出","recognize","kenn"], ["bekannt","著名的","well-known","kenn"], ["anerkennen","承认","acknowledge","kenn"],
    ["finden","找到","find","find"], ["erfinden","发明","invent","find"], ["die Erfindung","发明","invention","find"], ["empfinden","感受","feel","find"], ["stattfinden","举行","take place","find"],
    ["suchen","寻找","search","such"], ["besuchen","拜访","visit","such"], ["der Besuch","访问","visit","such"], ["versuchen","尝试","try","such"], ["der Versuch","尝试,实验","attempt","such"], ["untersuchen","检查","examine","such"],
    ["halten","持,停","hold, stop","halt"], ["erhalten","收到,保存","receive, preserve","halt"], ["der Inhalt","内容","content","halt"], ["das Verhalten","行为","behavior","halt"], ["der Haushalt","家务,预算","household","halt"], ["unterhalten","娱乐,交谈","entertain, converse","halt"], ["behalten","保留","keep","halt"],
    ["ziehen","拉","pull","zieh"], ["der Zug","火车,拉","train, pull","zieh"], ["erziehen","教育","educate","zieh"], ["die Erziehung","教育","upbringing","zieh"], ["anziehen","穿,吸引","put on, attract","zieh"], ["umziehen","搬家","move house","zieh"], ["die Beziehung","关系","relationship","zieh"], ["der Bezug","关联","reference","zieh"],
    ["fallen","落","fall","fall"], ["der Fall","情况,案例","case, fall","fall"], ["gefallen","让人喜欢","please","fall"], ["der Unfall","事故","accident","fall"], ["der Zufall","巧合","coincidence","fall"], ["auffallen","引人注目","stand out","fall"], ["der Einfall","想法","idea","fall"],
    ["brechen","断","break","brech"], ["der Bruch","断裂","break, fracture","brech"], ["das Verbrechen","犯罪","crime","brech"], ["unterbrechen","打断","interrupt","brech"], ["der Ausbruch","爆发","outbreak","brech"], ["der Aufbruch","出发","departure","brech"],
    ["schlagen","打","hit","schlag"], ["der Schlag","一击","blow","schlag"], ["vorschlagen","建议","propose","schlag"], ["der Vorschlag","建议","proposal","schlag"], ["der Anschlag","袭击,公告","attack, notice","schlag"], ["nachschlagen","查阅","look up","schlag"],
    ["laufen","跑","run","lauf"], ["der Lauf","跑,进程","run, course","lauf"], ["der Verlauf","过程","course","lauf"], ["verlaufen","进行,迷路","proceed, get lost","lauf"], ["der Ablauf","流程","sequence","lauf"],
    ["spielen","玩","play","spiel"], ["das Spiel","游戏","game","spiel"], ["der Spieler","玩家","player","spiel"], ["das Beispiel","例子","example","spiel"], ["das Schauspiel","戏剧","play (drama)","spiel"],
    ["arbeiten","工作","work","arbeit"], ["die Arbeit","工作","work","arbeit"], ["der Arbeiter","工人","worker","arbeit"], ["arbeitslos","失业的","unemployed","arbeit"], ["die Zusammenarbeit","合作","cooperation","arbeit"],
    ["machen","做","make","mach"], ["aufmachen","打开","open","mach"], ["ausmachen","关掉,约定","turn off, agree","mach"], ["die Macht","权力","power","macht"], ["mächtig","强大的","mighty","macht"], ["möglich","可能的","possible","macht"], ["die Möglichkeit","可能性","possibility","macht"], ["vermögen","能够,财富","be able; fortune","macht"],
    ["tun","做","do","tu"], ["die Tat","行为","deed","tu"], ["der Täter","作案者","perpetrator","tu"], ["tätig","活跃的","active","tu"], ["die Tätigkeit","活动","activity","tu"],
    /* ---- Tier 1: nouns & families ---- */
    ["die Hand","手","hand","hand"], ["handeln","行动,做生意","act, trade","hand"], ["der Handel","贸易","trade","hand"], ["die Handlung","行动,情节","action, plot","hand"], ["behandeln","对待,治疗","treat","hand"], ["verhandeln","谈判","negotiate","hand"], ["das Handy","手机","cell phone","hand"],
    ["das Haus","房子","house","haus"], ["zu Hause","在家","at home","haus"], ["der Haushalt","家庭,家务","household","haus"], ["das Krankenhaus","医院","hospital","haus"], ["das Rathaus","市政厅","town hall","haus"],
    ["die Stadt","城市","city","stadt"], ["die Stätte","场所","site","stadt"], ["die Werkstatt","车间","workshop","stadt"], ["stattfinden","举行","take place","stadt"], ["die Hauptstadt","首都","capital","stadt"],
    ["das Land","土地,国家","land, country","land"], ["landen","着陆","land (verb)","land"], ["das Ausland","外国","abroad","land"], ["die Landschaft","风景","landscape","land"], ["das Bundesland","联邦州","federal state","land"],
    ["der Weg","路","way","weg"], ["bewegen","移动","move","weg"], ["die Bewegung","运动","movement","weg"], ["unterwegs","在路上","on the way","weg"], ["der Umweg","绕路","detour","weg"], ["weg","离开,不见了","away, gone","weg2"], ["wegen","因为","because of","weg"],
    ["die Zeit","时间","time","zeit"], ["die Zeitung","报纸","newspaper","zeit"], ["zeitig","及时的","timely","zeit"], ["die Freizeit","空闲","leisure","zeit"], ["die Jahreszeit","季节","season","zeit"], ["gleichzeitig","同时","simultaneous","zeit"],
    ["der Tag","日","day","tag"], ["täglich","每天","daily","tag"], ["der Alltag","日常","everyday life","tag"], ["heutzutage","如今","nowadays","tag"], ["der Feiertag","节假日","holiday","tag"],
    ["das Jahr","年","year","jahr"], ["jährlich","每年","yearly","jahr"], ["das Jahrhundert","世纪","century","jahr"], ["die Jahreszahl","年份","year (number)","jahr"],
    ["das Kind","孩子","child","kind"], ["die Kindheit","童年","childhood","kind"], ["kindisch","幼稚的","childish","kind"], ["das Enkelkind","孙辈","grandchild","kind"],
    ["der Freund","朋友","friend","freund"], ["freundlich","友好的","friendly","freund"], ["die Freundschaft","友谊","friendship","freund"], ["die Freundin","女性朋友","female friend","freund"],
    ["lieben","爱","love","lieb"], ["die Liebe","爱","love","lieb"], ["lieb","亲爱的","dear","lieb"], ["lieber","更愿意","rather","lieb"], ["beliebt","受欢迎的","popular","lieb"], ["der Liebling","宠儿","darling","lieb"],
    ["leben","活","live","leb"], ["das Leben","生命","life","leb"], ["lebendig","活生生的","alive","leb"], ["erleben","经历","experience","leb"], ["das Erlebnis","经历","experience (event)","leb"], ["überleben","幸存","survive","leb"],
    ["kaufen","买","buy","kauf"], ["verkaufen","卖","sell","kauf"], ["der Verkäufer","售货员","seller","kauf"], ["einkaufen","购物","shop","kauf"], ["der Kaufmann","商人","merchant","kauf"],
    ["die Zahl","数字","number","zahl"], ["zahlen","付款","pay","zahl"], ["zählen","数","count","zahl"], ["bezahlen","支付","pay for","zahl"], ["erzählen","讲述","tell","zahl"], ["die Erzählung","故事","tale","zahl"], ["die Anzahl","数量","quantity","zahl"],
    ["das Wasser","水","water","wasser"], ["wässrig","水汪汪的","watery","wasser"], ["der Wasserfall","瀑布","waterfall","wasser"], ["das Trinkwasser","饮用水","drinking water","wasser"],
    ["das Licht","光","light","licht"], ["leuchten","发光","shine","licht"], ["die Leuchte","灯","lamp","licht"], ["erleuchten","照亮,启发","illuminate","licht"], ["der Leuchtturm","灯塔","lighthouse","licht"],
    ["das Wort","词","word","wort"], ["wörtlich","逐字的","literal","wort"], ["das Wörterbuch","词典","dictionary","wort"], ["verantworten","负责","answer for","antwort"], ["die Antwort","回答","answer","antwort"], ["antworten","回答","answer","antwort"], ["die Verantwortung","责任","responsibility","antwort"],
    ["fragen","问","ask","frag"], ["die Frage","问题","question","frag"], ["fraglich","可疑的","questionable","frag"], ["befragen","询问","question","frag"], ["die Umfrage","调查","survey","frag"], ["die Nachfrage","需求","demand","frag"],
    ["die Kraft","力","strength","kraft"], ["kräftig","强壮的","strong","kraft"], ["das Kraftwerk","发电站","power plant","kraft"], ["die Arbeitskraft","劳动力","workforce","kraft"],
    ["dienen","服务","serve","dienst"], ["der Dienst","服务,值班","service, duty","dienst"], ["der Diener","仆人","servant","dienst"], ["verdienen","赚,应得","earn, deserve","dienst"], ["der Verdienst","收入,功劳","earnings, merit","dienst"], ["bedienen","招待,操作","serve, operate","dienst"],
    ["die Schule","学校","school","schul"], ["der Schüler","学生","pupil","schul"], ["die Hochschule","高校","college","schul"], ["schulen","培训","train","schul"],
    ["das Bild","图片","picture","bild"], ["bilden","形成,教育","form, educate","bild"], ["die Bildung","教育","education","bild"], ["die Ausbildung","职业培训","training","bild"], ["einbilden","想象(自以为)","imagine","bild"], ["die Abbildung","插图","illustration","bild"], ["der Bildschirm","屏幕","screen","bild"],
    ["die Ordnung","秩序","order","ordn"], ["ordnen","整理","arrange","ordn"], ["der Ordner","文件夹","folder","ordn"], ["die Verordnung","法规","decree","ordn"], ["ordentlich","整齐的","tidy","ordn"],
    ["das Recht","权利,法","right, law","recht"], ["recht","对的,右的","right","recht"], ["richtig","正确的","correct","recht"], ["die Richtung","方向","direction","recht"], ["gerecht","公正的","just","recht"], ["das Gericht","法院,菜肴","court, dish","recht"], ["berichten","报道","report","recht"], ["der Bericht","报告","report","recht"], ["einrichten","布置","furnish","recht"], ["der Unterricht","课","lesson","recht"],
    ["wahr","真的","true","wahr"], ["die Wahrheit","真理","truth","wahr"], ["wahrscheinlich","很可能","probably","wahr"], ["bewahren","保存","preserve","wahr"], ["wahrnehmen","感知","perceive","wahr"],
    ["schön","美的","beautiful","schön"], ["die Schönheit","美","beauty","schön"], ["verschönern","美化","beautify","schön"],
    ["groß","大","big","groß"], ["die Größe","尺寸","size","groß"], ["großartig","了不起","great","groß"], ["die Großmutter","祖母","grandmother","groß"], ["vergrößern","放大","enlarge","groß"],
    ["klein","小","small","klein"], ["die Kleinigkeit","小事","trifle","klein"], ["verkleinern","缩小","reduce","klein"],
    ["hoch","高","high","hoch"], ["die Höhe","高度","height","hoch"], ["erhöhen","提高","raise","hoch"], ["der Höhepunkt","高潮","climax","hoch"], ["höchstens","至多","at most","hoch"],
    ["tief","深","deep","tief"], ["die Tiefe","深度","depth","tief"], ["vertiefen","加深","deepen","tief"],
    ["lang","长","long","lang"], ["die Länge","长度","length","lang"], ["langsam","慢","slow","lang"], ["verlangen","要求","demand","lang"], ["die Langeweile","无聊","boredom","lang"], ["gelangen","到达","reach","lang"],
    ["kurz","短","short","kurz"], ["kürzlich","最近","recently","kurz"], ["die Abkürzung","缩写,近路","abbreviation, shortcut","kurz"], ["verkürzen","缩短","shorten","kurz"],
    ["alt","老,旧","old","alt"], ["das Alter","年龄","age","alt"], ["die Eltern","父母","parents","alt"], ["veraltet","过时的","outdated","alt"], ["das Altertum","古代","antiquity","alt"],
    ["neu","新","new","neu"], ["die Neuigkeit","新闻","news","neu"], ["erneuern","更新","renew","neu"], ["neulich","最近","recently","neu"], ["neugierig","好奇的","curious","neu"],
    ["gut","好","good","gut"], ["die Güte","善良,质量","goodness","gut"], ["das Gut","财产,货物","estate, goods","gut"], ["gütig","仁慈的","kind","gut"], ["das Guthaben","余额","credit balance","gut"],
    ["schwer","重,难","heavy, difficult","schwer"], ["die Schwere","重量,严重","weight, gravity","schwer"], ["schwierig","困难的","difficult","schwer"], ["die Schwierigkeit","困难","difficulty","schwer"],
    ["leicht","轻,容易","light, easy","leicht"], ["erleichtern","减轻","relieve","leicht"], ["vielleicht","也许","perhaps","leicht"], ["leichtsinnig","轻率的","careless","leicht"],
    ["stark","强","strong","stark"], ["die Stärke","力量,淀粉","strength, starch","stark"], ["verstärken","加强","reinforce","stark"],
    ["krank","病的","sick","krank"], ["die Krankheit","疾病","illness","krank"], ["der Kranke","病人","patient","krank"], ["die Krankenschwester","护士","nurse","krank"], ["kränken","伤害(感情)","hurt (feelings)","krank"],
    ["gesund","健康的","healthy","gesund"], ["die Gesundheit","健康","health","gesund"], ["gesundheitlich","健康方面的","health-related","gesund"],
    ["voll","满","full","voll"], ["füllen","装满","fill","voll"], ["erfüllen","实现","fulfill","voll"], ["völlig","完全","completely","voll"], ["die Fülle","丰富","abundance","voll"], ["vollständig","完整的","complete","voll"],
    ["frei","自由","free","frei"], ["die Freiheit","自由","freedom","frei"], ["befreien","解放","liberate","frei"], ["freiwillig","自愿的","voluntary","frei"], ["die Freizeit","空闲","free time","frei"],
    ["warm","暖","warm","warm"], ["die Wärme","温暖","warmth","warm"], ["erwärmen","加热","warm up","warm"],
    ["kalt","冷","cold","kalt"], ["die Kälte","寒冷","cold (noun)","kalt"], ["erkälten","感冒","catch cold","kalt"], ["die Erkältung","感冒","a cold","kalt"],
    ["schnell","快","fast","schnell"], ["die Schnelligkeit","速度","speed","schnell"], ["beschleunigen","加速","accelerate","schnell"],
    ["fest","牢固","firm","fest"], ["das Fest","节日","festival","fest"], ["feiern","庆祝","celebrate","fest"], ["festlegen","确定","fix, set","fest"], ["die Festung","要塞","fortress","fest"], ["befestigen","固定","fasten","fest"],
    ["reich","富","rich","reich"], ["das Reich","帝国","empire","reich"], ["reichen","递,够","hand, suffice","reich"], ["erreichen","到达,达到","reach","reich"], ["der Bereich","领域","area","reich"], ["reichlich","丰富的","plentiful","reich"],
    ["offen","开着的","open","öffn"], ["öffnen","打开","open (verb)","öffn"], ["die Öffnung","开口","opening","öffn"], ["die Öffentlichkeit","公众","the public","öffn"], ["öffentlich","公开的","public","öffn"], ["eröffnen","开幕","inaugurate","öffn"],
    ["schließen","关","close","schließ"], ["der Schluss","结束","end, conclusion","schließ"], ["der Schlüssel","钥匙","key","schließ"], ["das Schloss","锁,城堡","lock, castle","schließ"], ["beschließen","决定","decide","schließ"], ["der Beschluss","决议","decision","schließ"], ["anschließen","连接","connect","schließ"], ["der Anschluss","连接","connection","schließ"], ["ausschließlich","仅仅","exclusively","schließ"],
    ["das Ende","结束","end","end"], ["enden","结束","end (verb)","end"], ["endlich","终于","finally","end"], ["unendlich","无限的","infinite","end"], ["beenden","完成","finish","end"],
    ["fangen","抓","catch","anfang"], ["der Anfang","开始","beginning","anfang"], ["anfangen","开始","begin","anfang"], ["empfangen","接收","receive","anfang"], ["der Empfang","接待,接收","reception","anfang"], ["der Gefangene","囚犯","prisoner","anfang"],
    ["glauben","相信","believe","glaub"], ["der Glaube","信仰","belief","glaub"], ["glaubwürdig","可信的","credible","glaub"], ["unglaublich","难以置信","unbelievable","glaub"],
    ["hoffen","希望","hope","hoff"], ["die Hoffnung","希望","hope (noun)","hoff"], ["hoffentlich","但愿","hopefully","hoff"], ["hoffnungslos","绝望的","hopeless","hoff"],
    ["die Furcht","恐惧","fear","fürcht"], ["fürchten","害怕","fear (verb)","fürcht"], ["furchtbar","可怕的","terrible","fürcht"], ["befürchten","担心","be afraid that","fürcht"],
    ["die Freude","快乐","joy","freu"], ["sich freuen","高兴","be glad","freu"], ["freudig","欢快的","joyful","freu"], ["erfreulich","令人高兴的","gratifying","freu"],
    ["lachen","笑","laugh","lach"], ["das Lachen","笑声","laughter","lach"], ["lächeln","微笑","smile","lach"], ["lächerlich","可笑的","ridiculous","lach"],
    ["weinen","哭","cry","wein"], ["das Weinen","哭泣","crying","wein"],
    ["schlafen","睡","sleep","schlaf"], ["der Schlaf","睡眠","sleep (noun)","schlaf"], ["einschlafen","入睡","fall asleep","schlaf"], ["das Schlafzimmer","卧室","bedroom","schlaf"], ["verschlafen","睡过头","oversleep","schlaf"],
    ["essen","吃","eat","ess"], ["das Essen","食物","food","ess"], ["essbar","可食用的","edible","ess"], ["das Abendessen","晚餐","dinner","ess"], ["fressen","(动物)吃","eat (animal)","ess"],
    ["trinken","喝","drink","trink"], ["das Getränk","饮料","beverage","trink"], ["betrunken","醉的","drunk","trink"], ["ertrinken","溺水","drown","trink"],
    ["kochen","煮","cook","koch"], ["der Koch","厨师","cook (person)","koch"], ["die Küche","厨房","kitchen","koch"], ["der Kuchen","蛋糕","cake","koch"],
    ["wohnen","住","live (reside)","wohn"], ["die Wohnung","公寓","apartment","wohn"], ["der Bewohner","居民","inhabitant","wohn"], ["gewöhnen","习惯","get used to","wohn"], ["gewöhnlich","通常","usual","wohn"], ["die Gewohnheit","习惯","habit","wohn"],
    ["bauen","建","build","bau"], ["der Bau","建筑","building, construction","bau"], ["das Gebäude","建筑物","building","bau"], ["der Bauer","农民","farmer","bau"], ["anbauen","种植","cultivate","bau"], ["aufbauen","建立","build up","bau"],
    ["wachsen","生长","grow","wachs"], ["das Wachstum","增长","growth","wachs"], ["erwachsen","成年的","grown-up","wachs"], ["der Erwachsene","成年人","adult","wachs"],
    ["bringen","带来","bring","bring"], ["mitbringen","带来","bring along","bring"], ["verbringen","度过","spend (time)","bring"], ["umbringen","杀死","kill","bring"], ["beibringen","教会","teach","bring"],
    ["senden","发送","send","send"], ["die Sendung","节目,邮件","broadcast, shipment","send"], ["der Sender","电台","broadcaster","send"], ["versenden","寄出","dispatch","send"],
    ["reisen","旅行","travel","reis"], ["die Reise","旅行","journey","reis"], ["der Reisende","旅客","traveler","reis"], ["das Reisebüro","旅行社","travel agency","reis"],
    ["fliegen","飞","fly","flieg"], ["der Flug","航班","flight","flieg"], ["der Flughafen","机场","airport","flieg"], ["das Flugzeug","飞机","airplane","flieg"], ["die Fliege","苍蝇","fly (insect)","flieg"],
    ["schwimmen","游泳","swim","schwimm"], ["das Schwimmbad","游泳池","swimming pool","schwimm"], ["der Schwimmer","游泳者","swimmer","schwimm"],
    ["singen","唱","sing","sing"], ["der Sänger","歌手","singer","sing"], ["der Gesang","歌唱","singing","sing"],
    ["tanzen","跳舞","dance","tanz"], ["der Tanz","舞","dance (noun)","tanz"], ["der Tänzer","舞者","dancer","tanz"],
    ["kämpfen","战斗","fight","kämpf"], ["der Kampf","斗争","fight, struggle","kämpf"], ["der Kämpfer","战士","fighter","kämpf"], ["bekämpfen","对抗","combat","kämpf"],
    ["der Sieg","胜利","victory","sieg"], ["siegen","获胜","win","sieg"], ["der Sieger","胜者","winner","sieg"], ["besiegen","打败","defeat","sieg"],
    ["der Tod","死亡","death","tod"], ["tot","死的","dead","tod"], ["töten","杀","kill","tod"], ["tödlich","致命的","deadly","tod"],
    ["der Gott","神","god","gott"], ["die Göttin","女神","goddess","gott"], ["göttlich","神圣的","divine","gott"], ["der Gottesdienst","礼拜","church service","gott"],
    ["der Himmel","天空","sky, heaven","himmel"], ["himmlisch","天堂般的","heavenly","himmel"], ["die Himmelsrichtung","方位","compass direction","himmel"],
    ["die Erde","地球,土","earth","erde"], ["irdisch","尘世的","earthly","erde"], ["das Erdgeschoss","一楼","ground floor","erde"], ["das Erdbeben","地震","earthquake","erde"],
    ["das Feuer","火","fire","feuer"], ["die Feuerwehr","消防队","fire brigade","feuer"], ["feurig","火热的","fiery","feuer"], ["das Feuerzeug","打火机","lighter","feuer"],
    ["die Luft","空气","air","luft"], ["lüften","通风","air out","luft"], ["die Luftpost","航空邮件","airmail","luft"],
    ["der Stein","石头","stone","stein"], ["steinig","多石的","stony","stein"], ["der Edelstein","宝石","gem","stein"],
    ["der Baum","树","tree","baum"], ["der Weihnachtsbaum","圣诞树","Christmas tree","baum"], ["der Apfelbaum","苹果树","apple tree","baum"],
    ["die Blume","花","flower","blum"], ["blühen","开花","bloom","blum"], ["die Blüte","花朵,盛期","blossom, heyday","blum"],
    ["das Tier","动物","animal","tier"], ["der Tierarzt","兽医","vet","tier"], ["tierisch","动物的","animal (adj)","tier"], ["das Haustier","宠物","pet","tier"],
    ["der Vogel","鸟","bird","vogel"], ["der Hund","狗","dog","hund"], ["der Fisch","鱼","fish","fisch"], ["fischen","钓鱼","fish (verb)","fisch"], ["das Pferd","马","horse","pferd"],
    ["der Kopf","头","head","kopf"], ["das Kopfweh","头痛","headache","kopf"], ["das Herz","心","heart","herz"], ["herzlich","衷心的","hearty, warm","herz"], ["das Auge","眼睛","eye","aug"], ["der Augenblick","瞬间","moment","aug"], ["der Mund","嘴","mouth","mund"], ["mündlich","口头的","oral","mund"], ["der Fuß","脚","foot","fuß"], ["der Fußball","足球","football","fuß"], ["der Fußgänger","行人","pedestrian","fuß"],
    ["das Buch","书","book","buch"], ["der Buchstabe","字母","letter (of alphabet)","buch"], ["die Buchhandlung","书店","bookshop","buch"], ["buchen","预订","book (verb)","buch"], ["der Zahn","牙","tooth","zahn"], ["der Zahnarzt","牙医","dentist","zahn"],
    ["der Name","名字","name","nam"], ["nennen","称呼","call, name","nam"], ["nämlich","即,也就是","namely","nam"], ["der Vorname","名","first name","nam"], ["der Nachname","姓","surname","nam"],
    ["der Mut","勇气","courage","mut"], ["mutig","勇敢的","brave","mut"], ["die Demut","谦卑","humility","mut"], ["die Vermutung","猜测","assumption","mut"], ["vermuten","猜想","suppose","mut"],
    ["der Sinn","意义,感官","sense, meaning","sinn"], ["sinnvoll","有意义的","meaningful","sinn"], ["der Unsinn","胡说","nonsense","sinn"], ["die Gesinnung","态度","mindset","sinn"],
    ["der Geist","精神,鬼","spirit, ghost","geist"], ["geistig","精神上的","mental","geist"], ["begeistert","热情的","enthusiastic","geist"], ["die Begeisterung","热情","enthusiasm","geist"],
    ["die Seele","灵魂","soul","seel"], ["seelisch","心灵的","psychological","seel"],
    ["die Ruhe","安静","calm","ruh"], ["ruhig","安静的","quiet","ruh"], ["beruhigen","安抚","calm down","ruh"], ["ausruhen","休息","rest","ruh"], ["der Ruhestand","退休","retirement","ruh"],
    ["laut","响","loud","laut"], ["der Laut","声音","sound","laut"], ["lauten","(内容)为","read (text says)","laut"], ["läuten","响铃","ring","laut"], ["still","静","still, quiet","still"], ["die Stille","寂静","silence","still"],
    ["dunkel","暗","dark","dunkel"], ["die Dunkelheit","黑暗","darkness","dunkel"], ["die Farbe","颜色","color","farb"], ["färben","染色","dye","farb"], ["farbig","彩色的","colored","farb"],
    ["rot","红","red","rot"], ["die Röte","红色","redness","rot"], ["erröten","脸红","blush","rot"], ["weiß","白","white","weiß"], ["schwarz","黑","black","schwarz"], ["grün","绿","green","grün"], ["blau","蓝","blue","blau"], ["gelb","黄","yellow","gelb"],
    ["eins","一","one","eins"], ["einzeln","单个的","individual","eins"], ["einzig","唯一的","only","eins"], ["die Einheit","单位,统一","unit, unity","eins"], ["einig","一致的","agreed","eins"], ["vereinigen","联合","unite","eins"], ["einsam","孤独的","lonely","eins"], ["einfach","简单","simple","eins"],
    ["zwei","二","two","zwei"], ["der Zweifel","怀疑","doubt","zweifel"], ["zweifeln","怀疑","doubt (verb)","zweifel"], ["zweifellos","毫无疑问","undoubtedly","zweifel"], ["der Zwilling","双胞胎","twin","zwei"], ["der Zweig","树枝,分支","branch","zwei"],
    ["drei","三","three","drei"], ["das Dreieck","三角形","triangle","drei"], ["zehn","十","ten","zehn"], ["zwanzig","二十","twenty","zehn"], ["hundert","百","hundred","hundert"], ["das Jahrhundert","世纪","century","hundert"], ["tausend","千","thousand","tausend"],
    ["die Mitte","中间","middle","mitt"], ["das Mittel","手段,药","means, remedy","mitt"], ["mitten","在中间","in the middle","mitt"], ["der Mittag","中午","noon","mitt"], ["die Mitteilung","通知","notice","mitt"], ["mitteilen","告知","inform","mitt"], ["unmittelbar","直接的","immediate","mitt"], ["der Mittelpunkt","中心","center","mitt"],
    ["oben","上面","above","ober"], ["der Ober","侍者","waiter","ober"], ["die Oberfläche","表面","surface","ober"], ["das Oberhaupt","首领","head (leader)","ober"], ["unten","下面","below","unter"], ["unter","在…下","under","unter"], ["der Untergang","灭亡,日落","downfall, sunset","unter"], ["unterhalb","在…下方","below","unter"],
    ["vor","在…前","before","vor"], ["vorher","之前","beforehand","vor"], ["vorn","前面","in front","vor"], ["der Vorteil","优点","advantage","vor"], ["vorbei","过去了","past, over","vor"], ["voraus","预先","ahead","vor"], ["die Vorstellung","想象,介绍","idea, introduction","vor"], ["vorstellen","介绍,想象","introduce, imagine","vor"],
    ["nach","向,之后","to, after","nach"], ["nachher","之后","afterwards","nach"], ["der Nachbar","邻居","neighbor","nach"], ["die Nachricht","消息","news","nach"], ["der Nachteil","缺点","disadvantage","nach"], ["nachdem","在…之后","after","nach"],
    ["zurück","回","back","zurück"], ["der Rücken","背","back (body)","zurück"], ["die Rückkehr","返回","return","zurück"], ["rückwärts","向后","backwards","zurück"], ["die Rücksicht","顾及","consideration","zurück"],
    ["aus","出","out of","aus"], ["außen","外面","outside","aus"], ["außer","除了","except","aus"], ["äußern","表达","express","aus"], ["die Äußerung","言论","statement","aus"], ["äußerst","极其","extremely","aus"],
    ["in","在…里","in","ein"], ["innen","里面","inside","ein"], ["das Innere","内部","interior","ein"], ["innerhalb","在…之内","within","ein"], ["der Inhalt","内容","content","ein"], ["hinein","进去","into","ein"],
    ["über","在…上","over","über"], ["überall","到处","everywhere","über"], ["überhaupt","根本","at all","über"], ["übrig","剩下的","remaining","über"], ["übrigens","顺便说","by the way","über"], ["überzeugen","说服","convince","über"], ["überraschen","使惊讶","surprise","über"],
    ["durch","穿过","through","durch"], ["durchaus","完全","absolutely","durch"], ["der Durchschnitt","平均","average","durch"], ["durchführen","执行","carry out","durch"], ["durchsetzen","贯彻","push through","durch"],
    ["um","围绕","around","um"], ["die Umwelt","环境","environment","um"], ["der Umstand","情况","circumstance","um"], ["umgekehrt","相反","reversed","um"], ["die Umgebung","周围","surroundings","um"], ["umfassen","包括","comprise","um"],
    ["wieder","再","again","wieder"], ["wiederholen","重复","repeat","wieder"], ["die Wiederholung","重复","repetition","wieder"], ["wiedersehen","再见","see again","wieder"], ["die Wiedervereinigung","统一","reunification","wieder"],
    ["zusammen","一起","together","zusammen"], ["sammeln","收集","collect","zusammen"], ["die Sammlung","收藏","collection","zusammen"], ["die Versammlung","集会","assembly","zusammen"], ["der Zusammenhang","关联","connection","zusammen"],
    ["der Teil","部分","part","teil"], ["teilen","分","divide, share","teil"], ["die Teilnahme","参与","participation","teil"], ["der Vorteil","优点","advantage","teil"], ["das Urteil","判决,判断","judgment","teil"], ["urteilen","判断","judge","teil"], ["mitteilen","告知","inform","teil"], ["verteilen","分发","distribute","teil"], ["der Anteil","份额","share","teil"],
    ["ganz","整个","whole","ganz"], ["das Ganze","整体","the whole","ganz"], ["gänzlich","完全","entirely","ganz"], ["ergänzen","补充","complement","ganz"],
    ["die Art","种类,方式","kind, manner","art"], ["artig","乖的","well-behaved","art"], ["die Sache","事物","thing, matter","sach"], ["sachlich","客观的","objective","sach"], ["die Ursache","原因","cause","sach"], ["die Tatsache","事实","fact","sach"], ["das Ding","东西","thing","ding"], ["bedingen","以…为条件","condition","ding"], ["die Bedingung","条件","condition","ding"], ["unbedingt","一定","absolutely","ding"],
    ["der Mensch","人","human","mensch"], ["die Menschheit","人类","humanity","mensch"], ["menschlich","人性的","human (adj)","mensch"], ["der Mann","男人","man","mann"], ["männlich","男性的","male","mann"], ["die Mannschaft","队伍","team","mann"], ["die Frau","女人,妻子","woman, wife","frau"], ["das Fräulein","小姐","miss","frau"],
    ["der Vater","父亲","father","vater"], ["väterlich","父亲般的","fatherly","vater"], ["das Vaterland","祖国","fatherland","vater"], ["die Mutter","母亲","mother","mutter"], ["die Muttersprache","母语","mother tongue","mutter"], ["der Bruder","兄弟","brother","bruder"], ["brüderlich","兄弟般的","brotherly","bruder"], ["die Schwester","姐妹","sister","schwester"],
    ["das Volk","民族","people, nation","volk"], ["die Bevölkerung","人口","population","volk"], ["der Volkswagen","大众汽车","people's car","volk"], ["völkisch","民族的","folkish","volk"],
    ["der Krieg","战争","war","krieg"], ["der Krieger","战士","warrior","krieg"], ["kriegen","得到(口语)","get (colloquial)","krieg"], ["der Frieden","和平","peace","fried"], ["friedlich","和平的","peaceful","fried"], ["zufrieden","满意的","satisfied","fried"], ["der Friedhof","墓地","cemetery","fried"],
    ["die Welt","世界","world","welt"], ["weltweit","全世界","worldwide","welt"], ["die Weltanschauung","世界观","worldview","welt"], ["das Meer","海","sea","meer"], ["der Berg","山","mountain","berg"], ["bergen","救出,藏有","rescue, hold","berg"], ["verbergen","隐藏","hide","berg"], ["der Wald","森林","forest","wald"], ["der Stern","星","star","stern"], ["die Sonne","太阳","sun","sonn"], ["der Sonntag","星期日","Sunday","sonn"], ["der Mond","月亮","moon","mond"], ["der Montag","星期一","Monday","mond"],
    ["die Nacht","夜","night","nacht"], ["nachts","在夜里","at night","nacht"], ["die Mitternacht","午夜","midnight","nacht"], ["Weihnachten","圣诞节","Christmas","nacht"], ["der Morgen","早晨","morning","morgen"], ["morgen","明天","tomorrow","morgen"], ["der Abend","晚上","evening","abend"], ["abends","在晚上","in the evening","abend"], ["die Woche","周","week","woch"], ["wöchentlich","每周","weekly","woch"], ["der Monat","月份","month","monat"], ["monatlich","每月","monthly","monat"], ["die Stunde","小时","hour","stund"], ["stündlich","每小时","hourly","stund"],
    ["los","松开,出发!","loose, go!","los"], ["lösen","解决,松开","solve, loosen","los"], ["die Lösung","解答","solution","los"], ["auflösen","溶解,解散","dissolve","los"], ["erlösen","拯救","redeem","los"], ["binden","绑","bind","bind"], ["das Band","带子","ribbon, band","bind"], ["der Bund","联盟","federation","bind"], ["verbinden","连接","connect","bind"], ["die Verbindung","联系","connection","bind"], ["das Bündnis","联盟","alliance","bind"],
    ["schneiden","切","cut","schneid"], ["der Schnitt","切口,剪裁","cut","schneid"], ["der Abschnitt","段落","section","schneid"], ["entscheiden","决定","decide","schneid"], ["die Entscheidung","决定","decision","schneid"], ["waschen","洗","wash","wasch"], ["die Wäsche","衣物","laundry","wasch"], ["die Waschmaschine","洗衣机","washing machine","wasch"],
    ["wechseln","换","change, exchange","wechsel"], ["der Wechsel","更换","change","wechsel"], ["die Abwechslung","变化,调剂","variety","wechsel"], ["wenden","转","turn","wend"], ["die Wand","墙","wall","wend"], ["die Wende","转折","turning point","wend"], ["verwenden","使用","use","wend"], ["anwenden","应用","apply","wend"], ["die Anwendung","应用","application","wend"], ["notwendig","必要的","necessary","wend"], ["das Gewand","长袍","robe","wend"],
    ["weise","智慧的","wise","weis"], ["die Weise","方式","manner","weis"], ["die Weisheit","智慧","wisdom","weis"], ["beweisen","证明","prove","weis"], ["hinweisen","指出","point out","weis"], ["der Hinweis","提示","hint","weis"], ["der Ausweis","证件","ID card","weis"], ["zeigen","显示","show","zeig"], ["das Zeichen","符号","sign","zeig"], ["zeichnen","画","draw","zeig"], ["die Zeichnung","图画","drawing","zeig"], ["bezeichnen","称为","designate","zeig"], ["verzeichnen","记录","record","zeig"],
    ["der Rat","建议,委员会","advice, council","rat"], ["raten","建议,猜","advise, guess","rat"], ["das Rätsel","谜","riddle","rat"], ["beraten","咨询","advise","rat"], ["verraten","背叛,泄露","betray","rat"], ["das Gerät","设备","device","rat"], ["der Vorrat","储备","stock","rat"],
    ["rufen","叫","call","ruf"], ["der Ruf","呼喊,名声","call, reputation","ruf"], ["anrufen","打电话","phone","ruf"], ["der Beruf","职业","profession","ruf"], ["berufen","任命","appoint","ruf"], ["heißen","叫做","be called","heiß"], ["heiß","热","hot","heiß"], ["die Hitze","炎热","heat","heiß"],
    ["fehlen","缺少","be missing","fehl"], ["der Fehler","错误","mistake","fehl"], ["fehlerhaft","有错的","faulty","fehl"], ["befehlen","命令","command","fehl"], ["der Befehl","命令","order","fehl"], ["empfehlen","推荐","recommend","fehl"], ["die Empfehlung","推荐","recommendation","fehl"],
    ["fühlen","感觉","feel","fühl"], ["das Gefühl","感情","feeling","fühl"], ["mitfühlen","同情","sympathize","fühl"], ["der Wunsch","愿望","wish","wünsch"], ["wünschen","希望","wish (verb)","wünsch"], ["erwünscht","被期望的","desired","wünsch"],
    ["wollen","想要","want","woll"], ["der Wille","意志","will","woll"], ["freiwillig","自愿","voluntary","woll"], ["müssen","必须","must","müss"], ["das Muss","必需","a must","müss"], ["können","能","can","könn"], ["die Kunst","艺术","art","könn"], ["der Künstler","艺术家","artist","könn"], ["künstlich","人工的","artificial","könn"], ["dürfen","可以","may","dürf"], ["sollen","应该","should","soll"], ["das Soll","应有,指标","target","soll"],
    ["brauchen","需要","need","brauch"], ["der Brauch","习俗","custom","brauch"], ["gebrauchen","使用","use","brauch"], ["der Gebrauch","使用","usage","brauch"], ["verbrauchen","消耗","consume","brauch"], ["der Verbraucher","消费者","consumer","brauch"], ["nutzen","利用","use","nutz"], ["der Nutzen","益处","benefit","nutz"], ["nützlich","有用的","useful","nutz"], ["benutzen","使用","use","nutz"], ["der Benutzer","用户","user","nutz"],
    ["der Dank","感谢","thanks","dank"], ["dankbar","感激的","grateful","dank"], ["die Bitte","请求","request","bitt"], ["bitten","请求","ask for","bitt"], ["bitte","请","please","bitt"], ["der Gruß","问候","greeting","grüß"], ["grüßen","问候","greet","grüß"], ["begrüßen","欢迎","welcome","grüß"],
    ["warten","等待","wait","wart"], ["erwarten","期待","expect","wart"], ["die Erwartung","期望","expectation","wart"], ["die Gegenwart","现在","present","wart"], ["verantwortlich","负责的","responsible","antwort"], ["die Schuld","过错,债","guilt, debt","schuld"], ["schuldig","有罪的","guilty","schuld"], ["entschuldigen","原谅","excuse","schuld"], ["die Entschuldigung","道歉","apology","schuld"], ["die Schulden","债务","debts","schuld"],
    ["der Lohn","工资","wage","lohn"], ["belohnen","奖励","reward","lohn"], ["die Belohnung","奖赏","reward","lohn"], ["sich lohnen","值得","be worthwhile","lohn"], ["das Geld","钱","money","geld"], ["gelten","有效,算作","be valid, count","geld"], ["gültig","有效的","valid","geld"], ["der Preis","价格,奖","price, prize","preis"], ["preiswert","划算","good value","preis"], ["der Markt","市场","market","markt"], ["der Supermarkt","超市","supermarket","markt"],
    ["die Stelle","位置,职位","place, position","stell"], ["stellen","放","put","stell"], ["die Stellung","职位,立场","position","stell"], ["herstellen","制造","produce","stell"], ["die Herstellung","生产","production","stell"], ["darstellen","描绘","depict","stell"], ["feststellen","确定","determine","stell"], ["die Ausstellung","展览","exhibition","stell"], ["bestellen","订购","order","stell"], ["die Bestellung","订单","order (noun)","stell"], ["der Satz","句子","sentence","setz"], ["das Gesetz","法律","law","setz"], ["der Gegensatz","对立","contrast","setz"], ["der Ersatz","替代","replacement","setz"], ["der Vorsatz","决心","resolution","setz"],
    ["das Ziel","目标","goal","ziel"], ["zielen","瞄准","aim","ziel"], ["erzielen","取得","achieve","ziel"], ["weit","远","far","weit"], ["die Weite","宽广","expanse","weit"], ["erweitern","扩大","expand","weit"], ["weiter","继续,更远","further","weit"], ["nah","近","near","nah"], ["die Nähe","附近","vicinity","nah"], ["nähern","接近","approach","nah"], ["beinahe","几乎","almost","nah"],
    ["das Heim","家","home","heim"], ["die Heimat","家乡","homeland","heim"], ["heimlich","秘密的","secret","heim"], ["das Geheimnis","秘密","secret","heim"], ["geheim","秘密的","secret (adj)","heim"], ["die Tür","门","door","tür"], ["das Tor","大门,进球","gate, goal","tür"], ["das Fenster","窗","window","fenster"], ["der Tisch","桌子","table","tisch"], ["das Bett","床","bed","bett"], ["das Kleid","连衣裙","dress","kleid"], ["die Kleidung","衣服","clothing","kleid"], ["der Schuh","鞋","shoe","schuh"], ["das Brot","面包","bread","brot"], ["das Brötchen","小面包","bread roll","brot"], ["die Milch","牛奶","milk","milch"], ["der Apfel","苹果","apple","apfel"],
    ["der Wagen","车","car, wagon","wagen"], ["wagen","敢","dare","wagen"], ["die Straße","街","street","straß"], ["die Brücke","桥","bridge","brück"], ["das Schiff","船","ship","schiff"], ["die Bahn","轨道","track, railway","bahn"], ["der Bahnhof","火车站","train station","bahn"], ["die Autobahn","高速公路","motorway","bahn"], ["das Stück","块","piece","stück"], ["das Frühstück","早餐","breakfast","stück"],
    ["das Mal","次","time (occasion)","mal"], ["malen","画","paint","mal"], ["der Maler","画家","painter","mal"], ["das Denkmal","纪念碑","monument","mal"], ["manchmal","有时","sometimes","mal"], ["damals","当时","back then","mal"], ["spät","晚","late","spät"], ["später","以后","later","spät"], ["die Verspätung","延误","delay","spät"], ["früh","早","early","früh"], ["früher","以前","earlier","früh"], ["der Frühling","春天","spring","früh"], ["jung","年轻","young","jung"], ["die Jugend","青年","youth","jung"], ["der Junge","男孩","boy","jung"],
    ["schwach","弱","weak","schwach"], ["die Schwäche","弱点","weakness","schwach"], ["arm","穷","poor","arm"], ["der Arm","手臂","arm","arm"], ["die Armut","贫困","poverty","arm"], ["heilen","治愈","heal","heil"], ["heilig","神圣的","holy","heil"], ["das Heil","救赎","salvation","heil"], ["das Heilmittel","药物","remedy","heil"], ["die Ehre","荣誉","honor","ehr"], ["ehrlich","诚实的","honest","ehr"], ["verehren","崇敬","revere","ehr"], ["treu","忠诚的","loyal","treu"], ["die Treue","忠诚","loyalty","treu"], ["vertrauen","信任","trust","treu"], ["das Vertrauen","信任","trust (noun)","treu"], ["trauen","敢,信任","dare, trust","treu"], ["die Trauer","悲伤","grief","treu"],
    ["die Wunde","伤口","wound","wund"], ["verwunden","打伤","wound (verb)","wund"], ["das Wunder","奇迹","miracle","wunder"], ["wunderbar","精彩","wonderful","wunder"], ["sich wundern","感到惊讶","be surprised","wunder"], ["der Zauber","魔法","magic","zauber"], ["zaubern","施魔法","do magic","zauber"], ["der Zauberer","魔法师","wizard","zauber"], ["der Held","英雄","hero","held"], ["die Heldin","女英雄","heroine","held"], ["heldenhaft","英勇的","heroic","held"], ["der König","国王","king","könig"], ["die Königin","王后","queen","könig"], ["das Königreich","王国","kingdom","könig"], ["der Herr","先生,主人","mister, lord","herr"], ["herrschen","统治","rule","herr"], ["der Herrscher","统治者","ruler","herr"], ["herrlich","壮丽的","magnificent","herr"], ["die Kirche","教堂","church","kirch"], ["der Grund","理由,地面","reason, ground","grund"], ["gründen","创立","found","grund"], ["gründlich","彻底的","thorough","grund"], ["der Hintergrund","背景","background","grund"], ["die Grundlage","基础","basis","grund"], ["begründen","论证","justify","grund"],
  ]
};
