/* =====================================================
   FUGA MYTHICA — CURSUS Italian 🇮🇹 · batch 9 — topical vocabulary: business, law, IT, media, environment, science, health, society, arts, travel, weather
   ===================================================== */
(function () {
  const p = VOCAB.it;
  Object.assign(p.roots, {});
  p.words.push(
    ["l'azienda", "公司", "business", "topic"],
    ["la ditta", "公司", "firm", "topic"],
    ["la società per azioni", "股份公司", "corporation", "topic"],
    ["l'azionista", "股东", "shareholder", "topic"],
    ["la Borsa", "证券交易所", "stock market", "topic"],
    ["l'obbligazione", "债券", "bond", "topic"],
    ["l'investitore", "投资者", "investor", "topic"],
    ["il profitto", "利润", "profit", "topic"],
    ["il fatturato", "营业额", "turnover", "topic"],
    ["le entrate", "收入", "revenue", "topic"],
    ["il bilancio", "预算", "budget", "topic"],
    ["lo stato patrimoniale", "资产负债表", "balance sheet", "topic"],
    ["la scadenza", "截止日期", "deadline", "topic"],
    ["il prestito", "贷款", "loan", "topic"],
    ["il mutuo", "抵押贷款", "mortgage", "topic"],
    ["il tasso d'interesse", "利率", "interest rate", "topic"],
    ["i risparmi", "储蓄", "savings", "topic"],
    ["il bonifico", "转账", "bank transfer", "topic"],
    ["il prelievo", "取款", "withdrawal", "topic"],
    ["il tasso di cambio", "汇率", "exchange rate", "topic"],
    ["l'inflazione", "通胀", "inflation", "topic"],
    ["la concorrenza", "竞争", "competition", "topic"],
    ["il concorrente", "竞争者", "competitor", "topic"],
    ["il cliente", "客户", "customer", "topic"],
    ["il fornitore", "供应商", "supplier", "topic"],
    ["la consegna", "交货", "delivery", "topic"],
    ["le scorte", "库存", "stock", "topic"],
    ["il marketing", "市场营销", "marketing", "topic"],
    ["il commercio al dettaglio", "零售", "retail", "topic"],
    ["il commercio all'ingrosso", "批发", "wholesale", "topic"],
    ["il dazio", "关税", "tariff", "topic"],
    ["la tassa", "税", "tax", "topic"],
    ["l'IVA", "增值税", "VAT", "topic"],
    ["il contribuente", "纳税人", "taxpayer", "topic"],
    ["il contabile", "会计", "accountant", "topic"],
    ["la revisione contabile", "审计", "audit", "topic"],
    ["il dirigente", "经理", "manager", "topic"],
    ["il datore di lavoro", "雇主", "employer", "topic"],
    ["il personale", "员工", "staff", "topic"],
    ["l'assunzione", "招聘", "recruitment", "topic"],
    ["il licenziamento", "裁员", "dismissal", "topic"],
    ["lo sciopero", "罢工", "strike", "topic"],
    ["il sindacato", "工会", "trade union", "topic"],
    ["la disoccupazione", "失业", "unemployment", "topic"],
    ["il turno", "班次", "shift", "topic"],
    ["lo straordinario", "加班", "overtime", "topic"],
    ["l'ordine del giorno", "议程", "agenda", "topic"],
    ["il verbale", "会议记录", "minutes", "topic"],
    ["l'obiettivo", "目标", "goal", "topic"],
    ["la trattativa", "谈判", "negotiation", "topic"],
    ["la partnership", "合作关系", "partnership", "topic"],
    ["l'acquisizione", "收购", "takeover", "topic"],
    ["il fallimento", "破产", "bankruptcy", "topic"],
    ["la startup", "初创公司", "startup", "topic"],
    ["l'imprenditore", "企业家", "entrepreneur", "topic"],
    ["il disegno di legge", "法案", "bill", "topic"],
    ["il deputato", "议员", "deputy", "topic"],
    ["il primo ministro", "总理", "prime minister", "topic"],
    ["il presidente", "总统", "president", "topic"],
    ["la coalizione", "联合政府", "coalition", "topic"],
    ["il referendum", "公投", "referendum", "topic"],
    ["la monarchia", "君主制", "monarchy", "topic"],
    ["il tribunale", "法院", "court", "topic"],
    ["il pubblico ministero", "检察官", "prosecutor", "topic"],
    ["l'imputato", "被告", "defendant", "topic"],
    ["il testimone", "证人", "witness", "topic"],
    ["la multa", "罚款", "fine", "topic"],
    ["il carcere", "监狱", "prison", "topic"],
    ["il reato", "罪行", "crime", "topic"],
    ["il furto", "盗窃", "theft", "topic"],
    ["il ladro", "小偷", "thief", "topic"],
    ["la frode", "欺诈", "fraud", "topic"],
    ["la corruzione", "腐败", "corruption", "topic"],
    ["la tangente", "贿赂", "bribe", "topic"],
    ["il contrabbando", "走私", "smuggling", "topic"],
    ["il sospettato", "嫌疑人", "suspect", "topic"],
    ["l'indagine", "调查", "investigation", "topic"],
    ["il commissariato", "警察局", "police station", "topic"],
    ["la clausola", "条款", "clause", "topic"],
    ["il notaio", "公证人", "notary", "topic"],
    ["il testamento", "遗嘱", "will", "topic"],
    ["l'affidamento", "监护权", "custody", "topic"],
    ["l'ambasciata", "大使馆", "embassy", "topic"],
    ["l'ambasciatore", "大使", "ambassador", "topic"],
    ["l'alleanza", "联盟", "alliance", "topic"],
    ["l'esercito", "军队", "army", "topic"],
    ["l'attacco", "攻击", "attack", "topic"],
    ["il terrorismo", "恐怖主义", "terrorism", "topic"],
    ["la manifestazione", "示威", "demonstration", "topic"],
    ["i diritti umani", "人权", "human rights", "topic"],
    ["il portatile", "笔记本电脑", "laptop", "topic"],
    ["il tablet", "平板电脑", "tablet", "topic"],
    ["lo smartphone", "智能手机", "smartphone", "topic"],
    ["il mouse", "鼠标", "mouse", "topic"],
    ["la stampante", "打印机", "printer", "topic"],
    ["il file", "文件", "file", "topic"],
    ["il software", "软件", "software", "topic"],
    ["l'hardware", "硬件", "hardware", "topic"],
    ["l'applicazione", "应用程序", "app", "topic"],
    ["l'aggiornamento", "更新", "update", "topic"],
    ["il download", "下载", "download", "topic"],
    ["l'internet", "互联网", "internet", "topic"],
    ["il sito web", "网站", "website", "topic"],
    ["il browser", "浏览器", "browser", "topic"],
    ["il motore di ricerca", "搜索引擎", "search engine", "topic"],
    ["il link", "链接", "link", "topic"],
    ["l'e-mail", "电子邮件", "email", "topic"],
    ["l'allegato", "附件", "attachment", "topic"],
    ["l'utente", "用户", "user", "topic"],
    ["l'account", "账号", "account", "topic"],
    ["i dati", "数据", "data", "topic"],
    ["il database", "数据库", "database", "topic"],
    ["il cloud", "云", "cloud", "topic"],
    ["il server", "服务器", "server", "topic"],
    ["il virus", "病毒", "virus", "topic"],
    ["l'hacker", "黑客", "hacker", "topic"],
    ["l'intelligenza artificiale", "人工智能", "AI", "topic"],
    ["il robot", "机器人", "robot", "topic"],
    ["il codice", "代码", "code", "topic"],
    ["il social network", "社交网络", "social network", "topic"],
    ["il post", "帖子", "post", "topic"],
    ["il follower", "关注者", "follower", "topic"],
    ["il podcast", "播客", "podcast", "topic"],
    ["il titolo", "标题", "headline", "topic"],
    ["l'articolo", "文章", "article", "topic"],
    ["il redattore", "编辑", "editor", "topic"],
    ["la conferenza stampa", "新闻发布会", "press conference", "topic"],
    ["il canale", "频道", "channel", "topic"],
    ["le notizie false", "假新闻", "fake news", "topic"],
    ["la censura", "审查", "censorship", "topic"],
    ["l'ambiente", "环境", "environment", "topic"],
    ["l'inquinamento", "污染", "pollution", "topic"],
    ["il cambiamento climatico", "气候变化", "climate change", "topic"],
    ["il riscaldamento globale", "全球变暖", "global warming", "topic"],
    ["l'effetto serra", "温室效应", "greenhouse effect", "topic"],
    ["l'anidride carbonica", "二氧化碳", "CO2", "topic"],
    ["l'energia rinnovabile", "可再生能源", "renewable energy", "topic"],
    ["il pannello solare", "太阳能板", "solar panel", "topic"],
    ["la pala eolica", "风力涡轮机", "wind turbine", "topic"],
    ["il combustibile fossile", "化石燃料", "fossil fuel", "topic"],
    ["il carbone", "煤", "coal", "topic"],
    ["il gas naturale", "天然气", "natural gas", "topic"],
    ["l'energia nucleare", "核能", "nuclear power", "topic"],
    ["la centrale elettrica", "发电厂", "power station", "topic"],
    ["il riciclaggio", "回收", "recycling", "topic"],
    ["i rifiuti", "废物", "waste", "topic"],
    ["la plastica", "塑料", "plastic", "topic"],
    ["la siccità", "干旱", "drought", "topic"],
    ["l'alluvione", "洪水", "flood", "topic"],
    ["l'uragano", "飓风", "hurricane", "topic"],
    ["l'incendio boschivo", "野火", "wildfire", "topic"],
    ["la deforestazione", "森林砍伐", "deforestation", "topic"],
    ["la specie in pericolo", "濒危物种", "endangered species", "topic"],
    ["l'habitat", "栖息地", "habitat", "topic"],
    ["la fauna", "野生动物", "wildlife", "topic"],
    ["lo strato di ozono", "臭氧层", "ozone layer", "topic"],
    ["la sostenibilità", "可持续性", "sustainability", "topic"],
    ["l'esperimento", "实验", "experiment", "topic"],
    ["il laboratorio", "实验室", "laboratory", "topic"],
    ["la teoria", "理论", "theory", "topic"],
    ["la misurazione", "测量", "measurement", "topic"],
    ["il DNA", "DNA", "DNA", "topic"],
    ["la velocità della luce", "光速", "speed of light", "topic"],
    ["la galassia", "星系", "galaxy", "topic"],
    ["il satellite", "卫星", "satellite", "topic"],
    ["la navicella spaziale", "宇宙飞船", "spacecraft", "topic"],
    ["il vaccino", "疫苗", "vaccine", "topic"],
    ["il sintomo", "症状", "symptom", "topic"],
    ["l'infezione", "感染", "infection", "topic"],
    ["la pandemia", "大流行", "pandemic", "topic"],
    ["la pressione sanguigna", "血压", "blood pressure", "topic"],
    ["l'infarto", "心脏病发作", "heart attack", "topic"],
    ["l'ictus", "中风", "stroke", "topic"],
    ["il cancro", "癌症", "cancer", "topic"],
    ["il diabete", "糖尿病", "diabetes", "topic"],
    ["la dieta", "饮食", "diet", "topic"],
    ["la salute mentale", "心理健康", "mental health", "topic"],
    ["la depressione", "抑郁症", "depression", "topic"],
    ["lo stress", "压力", "stress", "topic"],
    ["gli anziani", "老年人", "elderly", "topic"],
    ["la disuguaglianza", "不平等", "inequality", "topic"],
    ["il fenomeno dei senzatetto", "无家可归", "homelessness", "topic"],
    ["l'ente di beneficenza", "慈善机构", "charity", "topic"],
    ["il volontario", "志愿者", "volunteer", "topic"],
    ["l'assistenza sociale", "社会福利", "welfare", "topic"],
    ["l'alfabetizzazione", "识字", "literacy", "topic"],
    ["la borsa di studio", "奖学金", "scholarship", "topic"],
    ["il seminario", "研讨会", "seminar", "topic"],
    ["le tasse universitarie", "学费", "tuition fees", "topic"],
    ["il razzismo", "种族主义", "racism", "topic"],
    ["il femminismo", "女权主义", "feminism", "topic"],
    ["la tradizione", "传统", "tradition", "topic"],
    ["l'usanza", "习俗", "custom", "topic"],
    ["la moschea", "清真寺", "mosque", "topic"],
    ["la sinagoga", "犹太会堂", "synagogue", "topic"],
    ["il tempio", "寺庙", "temple", "topic"],
    ["la preghiera", "祈祷", "prayer", "topic"],
    ["il paradiso", "天堂", "heaven", "topic"],
    ["l'inferno", "地狱", "hell", "topic"],
    ["il funerale", "葬礼", "funeral", "topic"],
    ["il cimitero", "墓地", "cemetery", "topic"],
    ["il battesimo", "洗礼", "baptism", "topic"],
    ["l'architettura", "建筑学", "architecture", "topic"],
    ["la scultura", "雕塑", "sculpture", "topic"],
    ["la pittura", "绘画", "painting", "topic"],
    ["la galleria", "画廊", "gallery", "topic"],
    ["l'orchestra", "管弦乐队", "orchestra", "topic"],
    ["il direttore d'orchestra", "指挥", "conductor", "topic"],
    ["il balletto", "芭蕾", "ballet", "topic"],
    ["il violino", "小提琴", "violin", "topic"],
    ["il flauto", "长笛", "flute", "topic"],
    ["la tromba", "小号", "trumpet", "topic"],
    ["il palcoscenico", "舞台", "stage", "topic"],
    ["la trama", "情节", "plot", "topic"],
    ["il personaggio", "角色", "character", "topic"],
    ["l'editore", "出版社", "publisher", "topic"],
    ["la fiaba", "童话", "fairy tale", "topic"],
    ["il cattivo", "反派", "villain", "topic"],
    ["il documentario", "纪录片", "documentary", "topic"],
    ["il cartone animato", "动画片", "cartoon", "topic"],
    ["la colonna sonora", "原声音乐", "soundtrack", "topic"],
    ["il festival", "节日", "festival", "topic"],
    ["i fuochi d'artificio", "烟花", "fireworks", "topic"],
    ["il carnevale", "狂欢节", "carnival", "topic"],
    ["il costume", "服装", "costume", "topic"],
    ["il giro turistico", "观光", "sightseeing", "topic"],
    ["la guida", "导游", "guide", "topic"],
    ["la mappa", "地图", "map", "topic"],
    ["l'itinerario", "行程", "itinerary", "topic"],
    ["l'escursionismo", "徒步", "hiking", "topic"],
    ["la vetta", "山顶", "summit", "topic"],
    ["la grotta", "洞穴", "cave", "topic"],
    ["la cascata", "瀑布", "waterfall", "topic"],
    ["il vulcano", "火山", "volcano", "topic"],
    ["la scogliera", "悬崖", "cliff", "topic"],
    ["il faro", "灯塔", "lighthouse", "topic"],
    ["l'alba", "日出", "sunrise", "topic"],
    ["il tramonto", "日落", "sunset", "topic"],
    ["il tuono", "雷", "thunder", "topic"],
    ["il fulmine", "闪电", "lightning", "topic"],
    ["la brezza", "微风", "breeze", "topic"],
    ["l'ondata di caldo", "热浪", "heatwave", "topic"],
    ["le previsioni", "天气预报", "forecast", "topic"]
  );
})();
