/* =====================================================
   FUGA MYTHICA — CURSUS French 🇫🇷 · batch 9 — Greek scientific / medical / cultural families
   ===================================================== */
(function () {
  const p = VOCAB.fr;
  Object.assign(p.roots, {"cardi": ["cardi-", "心", "heart"], "ophthalm": ["ophthalm-", "眼", "eye"], "nephr": ["nephr-", "肾", "kidney"], "phot": ["phot-", "光", "light"], "astr": ["astr- / aster-", "星", "star"], "polit": ["polit- / polis", "城邦,政治", "city, politics"], "econ": ["econom- / oik-", "家,经济", "household, economy"], "chem": ["chem-", "化学", "chemistry"], "math": ["mathem-", "学习,数学", "learning, maths"], "geometr": ["geometr-", "测地,几何", "geometry"], "gram": ["gram- / gramm-", "写下的东西", "written thing"], "troph": ["troph-", "营养", "nourishment"], "zoo": ["zo- / zoo-", "动物", "animal"], "ornith": ["ornith-", "鸟", "bird"], "ichthy": ["ichthy-", "鱼", "fish"], "entom": ["entom-", "昆虫", "insect"], "hipp": ["hipp-", "马", "horse"], "aut": ["aut- / auto-", "自己", "self"], "homo": ["homo- / homeo-", "相同", "same"], "meta": ["meta-", "之后,变化", "after, change"], "para": ["para-", "旁边,反常", "beside, beyond"], "epi": ["epi-", "在上", "upon"], "endo": ["endo- / ento-", "内", "inside"], "exo": ["exo- / ecto-", "外", "outside"], "hemi": ["hemi-", "半", "half"], "tetra": ["tetra-", "四", "four"], "penta": ["penta-", "五", "five"], "hexa": ["hexa-", "六", "six"], "deca": ["deca- / deka-", "十", "ten"], "proto": ["prot- / proto-", "第一", "first"], "pseudo": ["pseud- / pseudo-", "假", "false"], "sthen": ["sthen-", "力量", "strength"], "algia": ["-algia / alg-", "痛", "pain"], "itis": ["-itis", "炎症", "inflammation"], "oma": ["-oma", "肿瘤", "tumour"], "osis": ["-osis", "病态,过程", "condition, process"], "ectomy": ["-ectomy / tom-", "切除", "cutting out"], "podo": ["pod- / -pus", "足", "foot"], "arthr": ["arthr-", "关节", "joint"], "my": ["my- / myo-", "肌肉", "muscle"], "encephal": ["encephal-", "脑", "brain"], "glyc": ["glyc- / gluc-", "甜,糖", "sweet, sugar"], "cyt": ["cyt- / -cyte", "细胞", "cell"], "nucle": ["nucle-", "核", "nucleus"], "phyll": ["phyll-", "叶", "leaf"], "rhiz": ["rhiz-", "根", "root"], "zym": ["zym- / -ase", "发酵", "ferment"], "magnet": ["magnet-", "磁", "magnet"], "atom": ["atom- / tom-", "不可分", "uncuttable"], "latr": ["-latry / latr-", "崇拜", "worship"], "drom": ["drom-", "跑,路", "running, course"], "bolo": ["ball- / bol-", "投掷", "throw"], "thes": ["thes- / thet-", "放置", "placing"], "phen": ["phen- / phan-", "显现", "show"], "ops": ["ops- / opt-", "视觉", "sight"], "acou": ["acou- / acous-", "听", "hearing"], "aesth": ["aesth- / esth-", "感觉", "feeling"], "mnem": ["mnem- / mnes-", "记忆", "memory"], "gloss": ["gloss- / glott-", "舌,语言", "tongue, language"], "rhet": ["rhet-", "说话", "speaking"], "chore": ["chore-", "舞蹈", "dance"], "melo": ["mel- / melo-", "歌,曲", "song"], "harmon": ["harmon-", "接合,和谐", "fitting together"], "hier": ["hier-", "神圣", "sacred"], "icon": ["icon-", "图像", "image"], "idio": ["idi- / idio-", "个人的", "one's own"], "cine": ["cine- / kine-", "动", "movement"], "ergo": ["erg- / -urgy", "工作", "work"], "heli": ["helic-", "螺旋", "spiral"], "heter": ["heter-", "不同", "different"], "aristo": ["arist-", "最好", "best"], "olig": ["olig-", "少", "few"], "pleth": ["pleth- / plethor-", "充满", "fullness"], "thanat": ["thanat-", "死", "death"], "ger": ["ger- / geront-", "老", "old age"], "paed": ["paed- / ped-", "儿童", "child"], "gyn": ["gyn- / gynec-", "女", "woman"], "andr": ["andr-", "男", "man"], "ecol": ["ec- / oec-", "家,栖息地", "house, habitat"], "steno": ["sten-", "窄", "narrow"], "brady": ["brady-", "慢", "slow"], "tachy": ["tachy-", "快", "fast"], "baro": ["bar- / baro-", "重,压", "weight, pressure"], "seism": ["seism-", "震动", "shaking"], "cryo": ["cry- / cryo-", "冷", "cold"], "xero": ["xer- / xero-", "干", "dry"], "hygr": ["hygr-", "湿", "moist"], "meteor": ["meteor-", "高空之物", "thing in the air"], "ocean": ["ocean-", "大洋", "ocean"], "nes": ["nes- / -nesia", "岛", "island"], "potam": ["potam-", "河", "river"], "thalass": ["thalass-", "海", "sea"], "ur": ["ur- / uro-", "尿", "urine"], "pyret": ["pyret-", "发热", "fever"], "narc": ["narc-", "麻木", "numbness"], "hypn": ["hypn-", "睡", "sleep"], "phren": ["phren-", "心智", "mind"], "nous": ["no- / noe-", "心智", "mind"], "ethic": ["eth- / ethic-", "习俗,品格", "custom, character"], "dox": ["dox- / -doxy", "意见,教义", "opinion"], "heres": ["heres- / haer-", "选择", "choice"], "martyr": ["martyr-", "见证", "witness"], "angel": ["angel-", "信使", "messenger"], "evangel": ["evangel-", "好消息", "good news"], "apocal": ["apocalyp- / calyp-", "揭开", "uncover"], "myst": ["myst-", "闭口,秘密", "secret"]});
  p.words.push(
    ["cardiaque", "心脏的", "of the heart", "cardi"],
    ["la cardiologie", "心脏病学", "heart medicine", "cardi"],
    ["le cardiologue", "心脏科医生", "heart doctor", "cardi"],
    ["le cardiogramme", "心电图", "heart trace", "cardi"],
    ["cardiovasculaire", "心血管的", "heart and vessels", "cardi"],
    ["la tachycardie", "心动过速", "fast heartbeat", "cardi"],
    ["le myocarde", "心肌", "heart muscle", "cardi"],
    ["le péricarde", "心包", "heart sac", "cardi"],
    ["l'ophtalmologie", "眼科学", "eye medicine", "ophthalm"],
    ["l'ophtalmologue", "眼科医生", "eye doctor", "ophthalm"],
    ["ophtalmique", "眼的", "of the eye", "ophthalm"],
    ["la néphrologie", "肾脏病学", "kidney medicine", "nephr"],
    ["la néphrite", "肾炎", "kidney inflammation", "nephr"],
    ["le néphrologue", "肾科医生", "kidney doctor", "nephr"],
    ["le photographe", "摄影师", "photo-taker", "phot"],
    ["photographique", "摄影的", "of photos", "phot"],
    ["la photocopie", "复印件", "copy", "phot"],
    ["le photon", "光子", "light particle", "phot"],
    ["la photosynthèse", "光合作用", "light-making", "phot"],
    ["la photothérapie", "光疗", "light treatment", "phot"],
    ["photogénique", "上镜的", "looks good in photos", "phot"],
    ["photovoltaïque", "光伏的", "light-to-electricity", "phot"],
    ["l'astronome", "天文学家", "star scientist", "astr"],
    ["astronomique", "天文的,巨大的", "of stars; huge", "astr"],
    ["l'astrologie", "占星术", "star fortune-telling", "astr"],
    ["l'astéroïde", "小行星", "small planet", "astr"],
    ["l'astrophysique", "天体物理", "star physics", "astr"],
    ["politique", "政治的", "of government", "polit"],
    ["le politicien", "政治家", "political figure", "polit"],
    ["la métropole", "大都市", "major city", "polit"],
    ["métropolitain", "大都市的", "of a big city", "polit"],
    ["cosmopolite", "世界主义的", "worldly", "polit"],
    ["l'économiste", "经济学家", "economy expert", "econ"],
    ["économe", "节约的", "thrifty", "econ"],
    ["écologique", "生态的", "environmental", "ecol"],
    ["l'écologiste", "生态学家", "environment expert", "ecol"],
    ["la chimie", "化学", "science of substances", "chem"],
    ["chimique", "化学的", "of chemistry", "chem"],
    ["le chimiste", "化学家", "chemistry expert", "chem"],
    ["la biochimie", "生物化学", "chemistry of life", "chem"],
    ["pétrochimique", "石化的", "oil-chemistry", "chem"],
    ["l'alchimie", "炼金术", "old chemistry", "chem"],
    ["l'alchimiste", "炼金术士", "old chemist", "chem"],
    ["les mathématiques", "数学", "number science", "math"],
    ["mathématique", "数学的", "of maths", "math"],
    ["le mathématicien", "数学家", "maths expert", "math"],
    ["le polymathe", "博学者", "widely learned person", "math"],
    ["géométrique", "几何的", "of shapes", "geometr"],
    ["grammatical", "语法的", "of grammar", "gram"],
    ["le programme", "程序,节目", "plan; software", "gram"],
    ["le diagramme", "图表", "drawing", "gram"],
    ["l'anagramme", "字谜", "letter-swap word", "gram"],
    ["l'épigramme", "警句", "witty saying", "gram"],
    ["le monogramme", "花押字", "initials design", "gram"],
    ["le kilogramme", "千克", "1000 grams", "gram"],
    ["l'hologramme", "全息图", "3D image", "gram"],
    ["l'atrophie", "萎缩", "wasting away", "troph"],
    ["l'hypertrophie", "肥大", "overgrowth", "troph"],
    ["la dystrophie", "营养不良", "faulty growth", "troph"],
    ["trophique", "营养的", "of nutrition", "troph"],
    ["la zoologie", "动物学", "animal science", "zoo"],
    ["le zoologiste", "动物学家", "animal scientist", "zoo"],
    ["le zodiaque", "黄道带", "star-sign circle", "zoo"],
    ["le protozoaire", "原生动物", "single-celled animal", "zoo"],
    ["l'ornithologie", "鸟类学", "bird science", "ornith"],
    ["l'ornithologue", "鸟类学家", "bird scientist", "ornith"],
    ["l'ichtyologie", "鱼类学", "fish science", "ichthy"],
    ["l'entomologie", "昆虫学", "insect science", "entom"],
    ["l'entomologiste", "昆虫学家", "insect scientist", "entom"],
    ["l'hippopotame", "河马", "river horse", "hipp"],
    ["l'hippodrome", "赛马场", "horse track", "hipp"],
    ["l'autobiographie", "自传", "own life story", "aut"],
    ["autonome", "自主的", "self-governing", "aut"],
    ["l'autocratie", "独裁", "one-person rule", "aut"],
    ["authentique", "真正的", "genuine", "aut"],
    ["l'authenticité", "真实性", "genuineness", "aut"],
    ["l'autopsie", "尸检", "post-mortem exam", "aut"],
    ["l'automatisation", "自动化", "machine operation", "aut"],
    ["l'autisme", "自闭症", "autism", "aut"],
    ["homogène", "同质的", "uniform", "homo"],
    ["l'homonyme", "同音词", "same-name word", "homo"],
    ["homosexuel", "同性恋的", "same-sex", "homo"],
    ["l'homéopathie", "顺势疗法", "like-cures-like", "homo"],
    ["homologue", "同源的", "corresponding", "homo"],
    ["la métaphore", "隐喻", "figure of speech", "meta"],
    ["métaphorique", "隐喻的", "figurative", "meta"],
    ["la métamorphose", "变形", "transformation", "meta"],
    ["la métaphysique", "形而上学", "philosophy of being", "meta"],
    ["méthodique", "有条理的", "systematic", "meta"],
    ["la méthodologie", "方法论", "system of methods", "meta"],
    ["le paradoxe", "悖论", "self-contradiction", "para"],
    ["paradoxal", "自相矛盾的", "contradictory", "para"],
    ["le parasite", "寄生虫", "freeloader organism", "para"],
    ["parallèle", "平行的", "side by side", "para"],
    ["le paramètre", "参数", "setting", "para"],
    ["la paranoïa", "偏执", "irrational suspicion", "para"],
    ["la paralysie", "瘫痪", "loss of movement", "para"],
    ["paralyser", "使瘫痪", "disable", "para"],
    ["l'épidémie", "流行病", "widespread disease", "epi"],
    ["l'épiderme", "表皮", "outer skin", "epi"],
    ["l'épilepsie", "癫痫", "seizure disorder", "epi"],
    ["l'épitaphe", "墓志铭", "tomb inscription", "epi"],
    ["l'épicentre", "震中", "quake centre", "epi"],
    ["l'épilogue", "尾声", "closing section", "epi"],
    ["l'épiphanie", "顿悟,主显节", "sudden insight", "epi"],
    ["l'endoscopie", "内窥镜检查", "inside viewing", "endo"],
    ["endocrinien", "内分泌的", "internal-secreting", "endo"],
    ["endogène", "内生的", "from within", "endo"],
    ["exotique", "异国的", "foreign", "exo"],
    ["exogène", "外源的", "from outside", "exo"],
    ["l'exosquelette", "外骨骼", "outer skeleton", "exo"],
    ["l'hémisphère", "半球", "half-globe", "hemi"],
    ["l'hémicycle", "半圆形会场", "half-circle", "hemi"],
    ["l'hexagone", "六边形", "six-sided shape", "hexa"],
    ["hexagonal", "六边形的", "six-sided", "hexa"],
    ["le décathlon", "十项全能", "ten-event contest", "deca"],
    ["le décalogue", "十诫", "ten commandments", "deca"],
    ["le prototype", "原型", "first model", "proto"],
    ["le protocole", "协议,礼仪", "set of rules", "proto"],
    ["le protagoniste", "主角", "main character", "proto"],
    ["le proton", "质子", "positive particle", "proto"],
    ["la protéine", "蛋白质", "body-building nutrient", "proto"],
    ["la pseudoscience", "伪科学", "fake science", "pseudo"],
    ["l'asthénie", "无力", "weakness", "sthen"],
    ["la neurasthénie", "神经衰弱", "nerve exhaustion", "sthen"],
    ["la névralgie", "神经痛", "nerve pain", "algia"],
    ["la nostalgie", "怀旧", "homesickness", "algia"],
    ["nostalgique", "怀旧的", "longing for the past", "algia"],
    ["l'analgésique", "止痛药", "painkiller", "algia"],
    ["la myalgie", "肌肉痛", "muscle pain", "algia"],
    ["la bronchite", "支气管炎", "airway inflammation", "itis"],
    ["l'arthrite", "关节炎", "joint inflammation", "itis"],
    ["l'hépatite", "肝炎", "liver inflammation", "itis"],
    ["la gastrite", "胃炎", "stomach inflammation", "itis"],
    ["la dermatite", "皮炎", "skin inflammation", "itis"],
    ["l'appendicite", "阑尾炎", "appendix inflammation", "itis"],
    ["la méningite", "脑膜炎", "brain-lining inflammation", "itis"],
    ["l'amygdalite", "扁桃体炎", "tonsil inflammation", "itis"],
    ["la sinusite", "鼻窦炎", "sinus inflammation", "itis"],
    ["la conjonctivite", "结膜炎", "eye inflammation", "itis"],
    ["le carcinome", "癌", "cancer tumour", "oma"],
    ["le mélanome", "黑色素瘤", "skin cancer", "oma"],
    ["le lymphome", "淋巴瘤", "lymph tumour", "oma"],
    ["le glaucome", "青光眼", "eye-pressure disease", "oma"],
    ["le sarcome", "肉瘤", "tissue tumour", "oma"],
    ["la névrose", "神经症", "anxiety disorder", "osis"],
    ["la psychose", "精神病", "loss of reality", "osis"],
    ["la tuberculose", "结核病", "lung disease", "osis"],
    ["l'osmose", "渗透", "gradual absorption", "osis"],
    ["l'hypnose", "催眠", "trance state", "osis"],
    ["la thrombose", "血栓", "blood clot", "osis"],
    ["l'appendicectomie", "阑尾切除", "appendix removal", "ectomy"],
    ["l'amygdalectomie", "扁桃体切除", "tonsil removal", "ectomy"],
    ["l'anatomie", "解剖学", "body structure", "ectomy"],
    ["anatomique", "解剖的", "of body structure", "ectomy"],
    ["la dichotomie", "二分法", "split in two", "ectomy"],
    ["le podium", "讲台,领奖台", "platform", "podo"],
    ["le podologue", "足科医生", "foot doctor", "podo"],
    ["les antipodes", "对跖点", "opposite side of earth", "podo"],
    ["l'arthropode", "节肢动物", "jointed-leg animal", "arthr"],
    ["l'arthroscopie", "关节镜检查", "joint viewing", "arthr"],
    ["la myopie", "近视", "short-sightedness", "ops"],
    ["myope", "近视的", "short-sighted", "ops"],
    ["la myocardite", "心肌炎", "heart-muscle inflammation", "my"],
    ["la myologie", "肌学", "muscle science", "my"],
    ["l'encéphalite", "脑炎", "brain inflammation", "encephal"],
    ["l'électroencéphalogramme", "脑电图", "brain-wave trace", "encephal"],
    ["le glucose", "葡萄糖", "blood sugar", "glyc"],
    ["la glycérine", "甘油", "sweet oil", "glyc"],
    ["l'hypoglycémie", "低血糖", "low blood sugar", "glyc"],
    ["la cytologie", "细胞学", "cell science", "cyt"],
    ["le cytoplasme", "细胞质", "cell substance", "cyt"],
    ["le leucocyte", "白细胞", "white blood cell", "cyt"],
    ["l'érythrocyte", "红细胞", "red blood cell", "cyt"],
    ["le lymphocyte", "淋巴细胞", "immune cell", "cyt"],
    ["le noyau", "核", "centre", "nucle"],
    ["nucléaire", "核的", "atomic", "nucle"],
    ["le nucléotide", "核苷酸", "DNA unit", "nucle"],
    ["la chlorophylle", "叶绿素", "green leaf pigment", "phyll"],
    ["le rhizome", "根茎", "underground stem", "rhiz"],
    ["l'enzyme", "酶", "biological catalyst", "zym"],
    ["l'aimant", "磁铁", "attracting metal", "magnet"],
    ["magnétique", "磁的", "attracting", "magnet"],
    ["le magnétisme", "磁性", "magnetic force", "magnet"],
    ["électromagnétique", "电磁的", "electric-magnetic", "magnet"],
    ["atomique", "原子的", "of atoms", "atom"],
    ["l'idolâtrie", "偶像崇拜", "image worship", "latr"],
    ["l'idolâtre", "偶像崇拜者", "image worshipper", "latr"],
    ["le syndrome", "综合征", "set of symptoms", "drom"],
    ["l'aérodrome", "小型机场", "airfield", "drom"],
    ["le palindrome", "回文", "reads-same-backwards", "drom"],
    ["le vélodrome", "自行车赛场", "cycling track", "drom"],
    ["le dromadaire", "单峰驼", "running camel", "drom"],
    ["balistique", "弹道的", "of projectiles", "bolo"],
    ["la balistique", "弹道学", "projectile science", "bolo"],
    ["problématique", "有问题的", "difficult", "bolo"],
    ["symbolique", "象征的", "representing", "bolo"],
    ["symboliser", "象征", "stand for", "bolo"],
    ["diabolique", "恶魔般的", "devilish", "bolo"],
    ["la thèse", "论文,论点", "argument", "thes"],
    ["l'hypothèse", "假设", "proposed explanation", "thes"],
    ["hypothétique", "假设的", "supposed", "thes"],
    ["synthétique", "合成的", "artificial", "thes"],
    ["synthétiser", "合成", "combine", "thes"],
    ["l'antithèse", "对立面", "direct opposite", "thes"],
    ["la parenthèse", "括号", "bracket", "thes"],
    ["la prothèse", "假体", "artificial body part", "thes"],
    ["le thème", "主题", "subject", "thes"],
    ["thématique", "主题的", "of the subject", "thes"],
    ["l'épithète", "称号", "descriptive name", "thes"],
    ["le phénomène", "现象", "observable event", "phen"],
    ["phénoménal", "非凡的", "remarkable", "phen"],
    ["la phase", "阶段", "stage", "phen"],
    ["l'emphase", "强调", "stress", "phen"],
    ["la fantaisie", "幻想", "imagination", "phen"],
    ["fantastique", "极好的,奇幻的", "wonderful", "phen"],
    ["le fantôme", "幽灵", "ghost", "phen"],
    ["diaphane", "透明的", "see-through", "phen"],
    ["l'optique", "光学", "science of light", "ops"],
    ["optique", "光学的,视觉的", "of sight", "ops"],
    ["l'opticien", "配镜师", "glasses-maker", "ops"],
    ["le synopsis", "概要", "summary", "ops"],
    ["la biopsie", "活检", "tissue sample test", "ops"],
    ["acoustique", "声学的", "of sound", "acou"],
    ["l'acoustique", "声学", "sound science", "acou"],
    ["esthétique", "美学的", "of beauty", "aesth"],
    ["l'esthétique", "美学", "study of beauty", "aesth"],
    ["l'anesthésie", "麻醉", "numbing", "aesth"],
    ["l'anesthésique", "麻醉剂", "numbing drug", "aesth"],
    ["l'anesthésiste", "麻醉师", "numbing doctor", "aesth"],
    ["mnémonique", "助记的", "memory-aiding", "mnem"],
    ["l'amnistie", "大赦", "official pardon", "mnem"],
    ["le glossaire", "词汇表", "word list", "gloss"],
    ["le polyglotte", "通晓多语者", "many-language speaker", "gloss"],
    ["l'épiglotte", "会厌", "throat flap", "gloss"],
    ["la glose", "注释", "explanatory note", "gloss"],
    ["la rhétorique", "修辞", "art of persuasion", "rhet"],
    ["rhétorique", "修辞的", "for effect", "rhet"],
    ["la chorégraphie", "编舞", "dance design", "chore"],
    ["le chorégraphe", "编舞者", "dance designer", "chore"],
    ["le chœur", "合唱团", "choir", "chore"],
    ["choral", "合唱的", "of a choir", "chore"],
    ["mélodique", "旋律的", "tuneful", "melo"],
    ["mélodramatique", "夸张的", "over-dramatic", "melo"],
    ["l'harmonie", "和谐", "agreement", "harmon"],
    ["harmonieux", "和谐的", "well-matched", "harmon"],
    ["harmoniser", "使和谐", "bring into agreement", "harmon"],
    ["l'harmonica", "口琴", "mouth organ", "harmon"],
    ["la hiérarchie", "等级制", "ranking order", "hier"],
    ["hiérarchique", "等级的", "ranked", "hier"],
    ["le hiéroglyphe", "象形文字", "sacred carving", "hier"],
    ["l'icône", "图标,圣像", "image", "icon"],
    ["iconique", "标志性的", "symbolic", "icon"],
    ["l'iconoclaste", "破除偶像者", "image-breaker", "icon"],
    ["l'iconographie", "图像学", "image study", "icon"],
    ["l'idiome", "习语,语言", "expression; language", "idio"],
    ["idiomatique", "地道的", "natural-sounding", "idio"],
    ["l'idiot", "傻瓜", "fool", "idio"],
    ["idiot", "愚蠢的", "foolish", "idio"],
    ["l'idiosyncrasie", "个人癖好", "personal quirk", "idio"],
    ["cinématographique", "电影的", "of film", "cine"],
    ["cinétique", "动力的", "of motion", "cine"],
    ["la kinésiologie", "运动机能学", "movement science", "cine"],
    ["la télékinésie", "隔空移物", "mind-moving", "cine"],
    ["énergique", "精力充沛的", "full of energy", "ergo"],
    ["ergonomique", "符合人体工学的", "comfortable to use", "ergo"],
    ["la chirurgie", "外科手术", "operation", "ergo"],
    ["le chirurgien", "外科医生", "operating doctor", "ergo"],
    ["chirurgical", "外科的", "of operations", "ergo"],
    ["la métallurgie", "冶金", "metal-working", "ergo"],
    ["la liturgie", "礼拜仪式", "worship service", "ergo"],
    ["l'allergie", "过敏", "allergic reaction", "ergo"],
    ["allergique", "过敏的", "reacting badly", "ergo"],
    ["l'hélice", "螺旋", "spiral", "heli"],
    ["l'hélicoptère", "直升机", "rotor aircraft", "heli"],
    ["hélicoïdal", "螺旋形的", "spiral-shaped", "heli"],
    ["hétérogène", "异质的", "mixed", "heter"],
    ["hétérosexuel", "异性恋的", "opposite-sex", "heter"],
    ["hétérodoxe", "非正统的", "unorthodox", "heter"],
    ["l'aristocrate", "贵族", "noble person", "aristo"],
    ["aristocratique", "贵族的", "noble", "aristo"],
    ["l'oligarchie", "寡头政治", "rule by few", "olig"],
    ["l'oligarque", "寡头", "powerful few", "olig"],
    ["la pléthore", "过多", "excess", "pleth"],
    ["l'euthanasie", "安乐死", "mercy killing", "thanat"],
    ["gériatrique", "老年病的", "of old age", "ger"],
    ["la gériatrie", "老年医学", "old-age medicine", "ger"],
    ["la gérontologie", "老年学", "ageing science", "ger"],
    ["la pédiatrie", "儿科", "child medicine", "paed"],
    ["le pédiatre", "儿科医生", "child doctor", "paed"],
    ["la pédagogie", "教育学", "teaching method", "paed"],
    ["pédagogique", "教学的", "of teaching", "paed"],
    ["orthopédique", "骨科的", "bone-correcting", "paed"],
    ["la gynécologie", "妇科", "women's medicine", "gyn"],
    ["le gynécologue", "妇科医生", "women's doctor", "gyn"],
    ["la misogynie", "厌女", "hatred of women", "gyn"],
    ["l'androïde", "人形机器人", "human-like robot", "andr"],
    ["androgyne", "雌雄同体的", "both-sex", "andr"],
    ["la polyandrie", "一妻多夫", "many husbands", "andr"],
    ["la sténographie", "速记", "shorthand", "steno"],
    ["la sténose", "狭窄", "narrowing", "steno"],
    ["la bradycardie", "心动过缓", "slow heartbeat", "brady"],
    ["le tachymètre", "转速表", "speed gauge", "tachy"],
    ["le baromètre", "气压计", "pressure gauge", "baro"],
    ["barométrique", "气压的", "of pressure", "baro"],
    ["le baryton", "男中音", "deep male voice", "baro"],
    ["sismique", "地震的", "of earthquakes", "seism"],
    ["la sismologie", "地震学", "earthquake science", "seism"],
    ["le sismographe", "地震仪", "quake recorder", "seism"],
    ["cryogénique", "低温的", "very cold", "cryo"],
    ["la cryothérapie", "冷冻疗法", "cold treatment", "cryo"],
    ["le xérophyte", "旱生植物", "dry-land plant", "xero"],
    ["l'hygromètre", "湿度计", "moisture gauge", "hygr"],
    ["l'hygiène", "卫生", "cleanliness", "hygr"],
    ["hygiénique", "卫生的", "clean", "hygr"],
    ["le météore", "流星", "shooting star", "meteor"],
    ["la météorite", "陨石", "fallen space rock", "meteor"],
    ["la météorologie", "气象学", "weather science", "meteor"],
    ["le météorologue", "气象学家", "weather scientist", "meteor"],
    ["l'océan", "海洋", "sea", "ocean"],
    ["océanique", "海洋的", "of the ocean", "ocean"],
    ["l'océanographie", "海洋学", "ocean science", "ocean"],
    ["la Polynésie", "波利尼西亚", "many islands", "nes"],
    ["l'Indonésie", "印度尼西亚", "Indian islands", "nes"],
    ["le Péloponnèse", "伯罗奔尼撒", "island of Pelops", "nes"],
    ["la Mésopotamie", "美索不达米亚", "between rivers", "potam"],
    ["la thalassothérapie", "海水疗法", "sea treatment", "thalass"],
    ["l'urologie", "泌尿科", "urinary medicine", "ur"],
    ["l'urologue", "泌尿科医生", "urinary doctor", "ur"],
    ["l'urine", "尿", "urine", "ur"],
    ["le diurétique", "利尿剂", "water pill", "ur"],
    ["l'antipyrétique", "退烧药", "fever-reducer", "pyret"],
    ["le narcotique", "麻醉品", "numbing drug", "narc"],
    ["la narcose", "麻醉状态", "drug stupor", "narc"],
    ["la narcolepsie", "发作性睡病", "sleep attacks", "narc"],
    ["hypnotique", "催眠的", "sleep-inducing", "hypn"],
    ["hypnotiser", "催眠", "put in a trance", "hypn"],
    ["l'hypnotiseur", "催眠师", "trance-inducer", "hypn"],
    ["la schizophrénie", "精神分裂症", "split mind", "phren"],
    ["frénétique", "狂热的", "frantic", "phren"],
    ["la frénésie", "狂乱", "wild excitement", "phren"],
    ["paranoïaque", "偏执的", "irrationally suspicious", "nous"],
    ["l'ethos", "精神特质", "character", "ethic"],
    ["orthodoxe", "正统的", "conventional", "dox"],
    ["l'orthodoxie", "正统", "accepted belief", "dox"],
    ["la doxologie", "荣耀颂", "hymn of praise", "dox"],
    ["l'hérésie", "异端", "false belief", "heres"],
    ["l'hérétique", "异端者", "dissenter", "heres"],
    ["hérétique", "异端的", "against doctrine", "heres"],
    ["le martyr", "殉道者", "one who dies for belief", "martyr"],
    ["le martyre", "殉道", "death for belief", "martyr"],
    ["l'ange", "天使", "heavenly messenger", "angel"],
    ["angélique", "天使般的", "like an angel", "angel"],
    ["l'archange", "大天使", "chief angel", "angel"],
    ["évangélique", "福音派的", "of the gospel", "evangel"],
    ["l'évangéliste", "传福音者", "gospel preacher", "evangel"],
    ["l'évangile", "福音", "good news", "evangel"],
    ["l'apocalypse", "天启,末日", "revelation; end of world", "apocal"],
    ["apocalyptique", "末日的", "world-ending", "apocal"],
    ["le mystère", "神秘", "secret", "myst"],
    ["mystérieux", "神秘的", "puzzling", "myst"],
    ["le mystique", "神秘主义者", "spiritual seeker", "myst"],
    ["mystique", "神秘主义的", "spiritual", "myst"],
    ["le mysticisme", "神秘主义", "spiritual belief", "myst"],
    ["mystifier", "使迷惑", "puzzle", "myst"]
  );
})();
