/* =====================================================
   FUGA MYTHICA — CURSUS Italian 🇮🇹 · batch 3 (band 2000–3000)
   Academic / news vocabulary by Latin root (third group), plus Greek roots as used in Italian.
   ===================================================== */
(function () {
  const p = VOCAB.it;
  Object.assign(p.roots, {
    agr: ["agr- / campo", "田", "field"], ambul: ["ambul- / and-", "走", "walk"], apt: ["att- / apt-", "合适", "fit"], cert: ["cert-", "确定", "sure"],
    cult: ["cult- / col-", "耕,培养", "cultivate"], dur: ["dur-", "硬,持久", "hard, last"], div: ["div- / divis-", "分", "divide"], ess: ["ess- / ent-", "存在", "be"],
    fabr: ["fabbr- / forg-", "制作", "make"], fat: ["fa- / fab-", "说", "speak"], fend: ["fend- / fens-", "打击", "strike"], flor: ["flor- / fior-", "花", "flower"],
    gest: ["gest- / ger-", "携带,做", "carry, do"], glob: ["glob-", "球", "ball"], grat: ["grat- / grad-", "感谢,愉快", "thankful"], hum: ["um-", "土,人", "earth, human"],
    imag: ["immag- / imit-", "像", "image"], integr: ["integr- / inter-", "完整", "whole"], jur: ["giur- / gius-", "法,誓", "law, swear"], lig: ["leg- / lig-", "绑", "bind"],
    lingu: ["lingu-", "舌,语", "tongue"], loqu: ["loqu- / locu-", "说", "speak"], medic: ["medic-", "治", "heal"], mens: ["mens- / misur-", "量", "measure"],
    merc: ["merc-", "买卖", "trade"], mir: ["mir-", "惊奇,看", "wonder, look"], misc: ["misc- / mesc-", "混", "mix"], mun: ["mun-", "职责,公共", "duty, public"],
    mut: ["mut-", "变", "change"], noc: ["noc- / nuoc-", "害", "harm"], norm: ["norm-", "规则", "rule"], numer: ["numer-", "数", "number"],
    nutr: ["nutr-", "喂养", "nourish"], oper: ["oper-", "工作", "work"], or: ["or- / orat-", "口,说", "mouth, speak"], par: ["par- / pari", "相等", "equal"],
    part: ["part-", "部分", "part"], pass: ["pass-", "步", "step"], pen: ["pen- / pun-", "罚", "punish"], plaud: ["plaud- / plos-", "拍手", "clap"],
    priv: ["priv-", "私,夺", "private, deprive"], prud: ["prud-", "远见", "foresight"], pur: ["pur-", "净", "pure"], radi: ["radi- / raggi-", "光线", "ray"],
    rap: ["rap-", "抓", "seize"], rot: ["rot- / ruot-", "轮", "wheel"], rur: ["rur- / rust-", "乡村", "country"], san: ["san-", "健康", "healthy"],
    sec: ["sec- / sez-", "切", "cut"], sen: ["sen- / sign-", "老", "old"], sol2: ["sol-", "独", "alone"], somn: ["sonn-", "睡", "sleep"],
    spond: ["spond- / spos-", "承诺", "pledge"], string: ["string- / strett-", "拉紧", "bind tight"], sum: ["sum- / sunt-", "拿", "take"], tex: ["tess- / test-", "织", "weave"],
    tim: ["tim-", "怕", "fear"], tox: ["toss-", "毒", "poison"], ult: ["ult- / oltr-", "最远", "last"], und: ["ond-", "波", "wave"],
    ut: ["ut- / us-", "用", "use"], vest: ["vest-", "衣", "clothe"], volv: ["volg- / volu-", "滚", "roll"], vulner: ["vulner- / fer-", "伤", "wound"],
    log: ["-logia / log-", "学,言", "study, word"], graph: ["graf- / -gramma", "写", "write"], phon: ["fon-", "声", "sound"], bio: ["bio-", "生命", "life"],
    geo: ["geo-", "地", "earth"], chron: ["cron-", "时间", "time"], path: ["pat-", "感受,病", "feeling, disease"], tele: ["tele-", "远", "far"],
    micro: ["micro-", "小", "small"], scop: ["-scopio", "看", "look"], meter: ["-metro", "量", "measure"], crat: ["-crazia", "统治", "rule"],
    anthrop: ["antrop-", "人", "human"], psych: ["psic-", "心灵", "mind"], phil: ["fil-", "爱", "love"], theo: ["teo-", "神", "god"],
    hydr: ["idr-", "水", "water"], cycl: ["cicl-", "圈", "circle"], phob: ["-fobia", "怕", "fear"], onym: ["-onimo", "名", "name"],
    syn: ["sin- / sim-", "一起", "together"], anti: ["anti-", "反", "against"], hyper: ["iper-", "过度", "over"], mono: ["mono-", "单", "one"],
    poly: ["poli-", "多", "many"], neo: ["neo-", "新", "new"], dia: ["dia-", "穿过", "through"], a: ["a- / an-", "无", "without"],
  });
  p.words.push(
    ["l'agricoltura","农业","agriculture","agr"], ["l'agricoltore","农民","farmer","agr"], ["agricolo","农业的","agricultural","agr"], ["il pellegrino","朝圣者","pilgrim","agr"], ["agrario","农业的","agrarian","agr"],
    ["l'ambulanza","救护车","ambulance","ambul"], ["ambulante","流动的","itinerant","ambul"], ["il preambolo","序言","preamble","ambul"], ["andare","去","go","ambul"], ["l'andamento","走势","trend","ambul"],
    ["adatto","适合的","suitable","apt"], ["adattare","适应","adapt","apt"], ["l'attitudine","天资","aptitude","apt"], ["inetto","无能的","inept","apt"], ["l'adattamento","适应","adaptation","apt"],
    ["certo","确定的","certain","cert"], ["certificare","证明","certify","cert"], ["il certificato","证书","certificate","cert"], ["la certezza","确信","certainty","cert"], ["il concerto","音乐会","concert","cert"], ["accertare","查明","ascertain","cert"], ["l'incertezza","不确定","uncertainty","cert"],
    ["la cultura","文化","culture","cult"], ["coltivare","培养","cultivate","cult"], ["la coltivazione","种植","cultivation","cult"], ["la colonia","殖民地","colony","cult"], ["il culto","崇拜","cult","cult"], ["colto","有教养的","cultured","cult"],
    ["durevole","持久的","durable","dur"], ["durare","持续","last","dur"], ["la durata","时长","duration","dur"], ["duro","硬的","hard","dur"], ["durante","在…期间","during","dur"], ["indurire","变硬","harden","dur"], ["la durezza","硬度","hardness","dur"],
    ["dividere","分","divide","div"], ["la divisione","分割","division","div"], ["l'individuo","个人","individual","div"], ["il dividendo","红利","dividend","div"], ["la divisa","制服,货币","uniform, currency","div"], ["individuale","个人的","individual","div"], ["condividere","分享","share","div"],
    ["l'essenza","本质","essence","ess"], ["essenziale","必要的","essential","ess"], ["l'entità","实体","entity","ess"], ["presente","在场的","present","ess"], ["assente","缺席的","absent","ess"], ["l'interesse","兴趣,利息","interest","ess"], ["l'essere","存在","being","ess"], ["l'ente","机构","body","ess"],
    ["la fabbrica","工厂","factory","fabr"], ["fabbricare","制造","make","fabr"], ["la fabbricazione","制造","manufacture","fabr"], ["forgiare","锻造","forge","fabr"], ["il fabbro","铁匠","blacksmith","fabr"],
    ["la favola","寓言","fable","fat"], ["favoloso","传奇的","fabulous","fat"], ["l'infante","婴儿","infant","fat"], ["la prefazione","前言","preface","fat"], ["confessare","承认","confess","fat"], ["ineffabile","难以言喻的","ineffable","fat"], ["la fama","名声","fame","fat"], ["affabile","和蔼的","affable","fat"],
    ["difendere","保卫","defend","fend"], ["la difesa","防御","defence","fend"], ["offendere","冒犯","offend","fend"], ["l'offesa","冒犯","offence","fend"], ["offensivo","进攻的","offensive","fend"], ["il difensore","捍卫者","defender","fend"],
    ["il fiore","花","flower","flor"], ["fiorire","开花","bloom","flor"], ["il fioraio","花商","florist","flor"], ["fiorente","繁荣的","flourishing","flor"], ["la flora","植物群","flora","flor"], ["Firenze","佛罗伦萨","Florence","flor"],
    ["il gesto","手势","gesture","gest"], ["digerire","消化","digest","gest"], ["suggerire","建议","suggest","gest"], ["gestire","管理","manage","gest"], ["la gestione","管理","management","gest"], ["il registro","登记簿","register","gest"], ["esagerare","夸张","exaggerate","gest"], ["il suggerimento","建议","suggestion","gest"],
    ["il globo","地球仪","globe","glob"], ["globale","全球的","global","glob"], ["il globulo","血球","globule","glob"], ["inglobare","包括","encompass","glob"],
    ["gratis","免费","free","grat"], ["la gratitudine","感激","gratitude","grat"], ["grazioso","可爱的","graceful","grat"], ["gradevole","愉快的","pleasant","grat"], ["gradire","喜欢","appreciate","grat"], ["ringraziare","感谢","thank","grat"], ["la grazia","优雅,恩典","grace","grat"], ["gratuito","免费的","free","grat"],
    ["umano","人的","human","hum"], ["l'umanità","人类","humanity","hum"], ["umile","谦逊的","humble","hum"], ["l'umiltà","谦卑","humility","hum"], ["umiliare","羞辱","humiliate","hum"], ["esumare","挖出","exhume","hum"], ["postumo","死后的","posthumous","hum"],
    ["l'immagine","图像","image","imag"], ["immaginare","想象","imagine","imag"], ["imitare","模仿","imitate","imag"], ["l'immaginazione","想象力","imagination","imag"], ["l'imitazione","模仿","imitation","imag"],
    ["intero","整个的","whole","integr"], ["l'integrità","诚信","integrity","integr"], ["integrare","整合","integrate","integr"], ["l'integrazione","整合","integration","integr"], ["integro","正直的","honest","integr"],
    ["la giuria","陪审团","jury","jur"], ["giurare","发誓","swear","jur"], ["il giurista","法学家","jurist","jur"], ["la giurisdizione","管辖权","jurisdiction","jur"], ["l'ingiuria","侮辱","insult","jur"], ["il giuramento","誓言","oath","jur"], ["la giustizia","正义","justice","jur"], ["giusto","正确的","right","jur"],
    ["legare","绑","bind","lig"], ["il legame","联系","link","lig"], ["obbligare","迫使","oblige","lig"], ["la religione","宗教","religion","lig"], ["l'alleato","盟友","ally","lig"], ["la lega","联盟","league","lig"], ["l'obbligo","义务","obligation","lig"], ["collegare","连接","connect","lig"],
    ["la lingua","舌,语言","tongue, language","lingu"], ["il linguaggio","语言","language","lingu"], ["il linguista","语言学家","linguist","lingu"], ["bilingue","双语的","bilingual","lingu"], ["la linguistica","语言学","linguistics","lingu"],
    ["eloquente","雄辩的","eloquent","loqu"], ["l'eloquenza","口才","eloquence","loqu"], ["il colloquio","面试,谈话","interview","loqu"], ["il soliloquio","独白","soliloquy","loqu"], ["loquace","健谈的","talkative","loqu"], ["la locuzione","短语","phrase","loqu"],
    ["la medicina","医学","medicine","medic"], ["il medico","医生","doctor","medic"], ["medico","医学的","medical","medic"], ["il rimedio","补救","remedy","medic"], ["il medicinale","药物","medication","medic"],
    ["misurare","测量","measure","mens"], ["la misura","测量,措施","measure","mens"], ["la dimensione","维度","dimension","mens"], ["immenso","巨大的","immense","mens"], ["smisurato","过度的","excessive","mens"], ["il mese","月","month","mens"],
    ["il mercato","市场","market","merc"], ["il commercio","商业","commerce","merc"], ["la merce","商品","merchandise","merc"], ["commerciale","商业的","commercial","merc"], ["la mercé","恩惠","mercy","merc"], ["il mercenario","雇佣兵","mercenary","merc"], ["il commerciante","商人","merchant","merc"], ["il mercoledì","星期三","Wednesday","merc"],
    ["il miracolo","奇迹","miracle","mir"], ["ammirare","钦佩","admire","mir"], ["mirare","瞄准","aim","mir"], ["la mira","目标","aim","mir"], ["la meraviglia","奇迹","marvel","mir"], ["ammirevole","令人钦佩的","admirable","mir"], ["il miraggio","海市蜃楼","mirage","mir"],
    ["mescolare","混合","mix","misc"], ["la miscela","混合物","mixture","misc"], ["misto","混合的","mixed","misc"], ["la mischia","混战","melee","misc"], ["mischiare","混杂","mingle","misc"],
    ["municipale","市政的","municipal","mun"], ["il municipio","市政厅","town hall","mun"], ["la comunità","社区","community","mun"], ["comunicare","交流","communicate","mun"], ["immune","免疫的","immune","mun"], ["comune","共同的","common","mun"], ["il comune","市镇","municipality","mun"], ["la comunicazione","交流","communication","mun"],
    ["mutare","改变","change","mut"], ["la mutazione","突变","mutation","mut"], ["mutuo","相互的,贷款","mutual, mortgage","mut"], ["immutabile","不变的","immutable","mut"], ["commutare","减刑,交换","commute","mut"], ["il mutamento","变化","change","mut"],
    ["innocente","无辜的","innocent","noc"], ["nocivo","有害的","harmful","noc"], ["nuocere","伤害","harm","noc"], ["l'innocenza","清白","innocence","noc"], ["innocuo","无害的","innocuous","noc"],
    ["normale","正常的","normal","norm"], ["enorme","巨大的","enormous","norm"], ["anormale","异常的","abnormal","norm"], ["la norma","标准","norm","norm"], ["normalmente","通常","normally","norm"],
    ["il numero","数","number","numer"], ["numeroso","众多的","numerous","numer"], ["enumerare","列举","enumerate","numer"], ["innumerevole","无数的","innumerable","numer"], ["numerico","数字的","numerical","numer"],
    ["la nutrizione","营养","nutrition","nutr"], ["nutrire","喂养","nourish","nutr"], ["nutriente","有营养的","nutritious","nutr"], ["il nutrimento","养分","nourishment","nutr"], ["la nutrice","奶妈","wet nurse","nutr"],
    ["operare","操作,手术","operate","oper"], ["cooperare","合作","cooperate","oper"], ["l'opera","作品,歌剧","work, opera","oper"], ["l'operazione","操作,手术","operation","oper"], ["l'operaio","工人","worker","oper"], ["la manovra","操作","manoeuvre","oper"], ["l'operatore","操作员","operator","oper"],
    ["orale","口头的","oral","or"], ["l'oratore","演说家","orator","or"], ["l'oracolo","神谕","oracle","or"], ["adorare","崇拜","adore","or"], ["inesorabile","不可阻挡的","inexorable","or"], ["l'orazione","演说,祷告","oration, prayer","or"],
    ["pari","相等的","equal","par"], ["la parità","平等","parity","par"], ["paragonare","比较","compare","par"], ["il paragone","比较","comparison","par"], ["il paio","一对","pair","par"], ["la disparità","差异","disparity","par"], ["pareggiare","打平","equalize","par"],
    ["la parte","部分","part","part"], ["la particella","粒子","particle","part"], ["parziale","部分的","partial","part"], ["particolare","特别的","particular","part"], ["partecipare","参与","participate","part"], ["partire","离开","leave","part"], ["il partito","政党","party","part"], ["ripartire","分配,重新出发","distribute, set off again","part"], ["spartire","分","share out","part"],
    ["il passaggio","通道","passage","pass"], ["il passeggero","乘客","passenger","pass"], ["sorpassare","超越","overtake","pass"], ["il passo","步","step","pass"], ["passare","经过","pass","pass"], ["il passato","过去","past","pass"], ["passeggiare","散步","stroll","pass"],
    ["la pena","痛苦,刑罚","pain, penalty","pen"], ["penale","刑事的","penal","pen"], ["punire","惩罚","punish","pen"], ["la punizione","惩罚","punishment","pen"], ["l'impunità","免罚","impunity","pen"], ["pentirsi","悔改","repent","pen"], ["penoso","痛苦的","painful","pen"],
    ["applaudire","鼓掌","applaud","plaud"], ["l'applauso","掌声","applause","plaud"], ["plausibile","貌似合理的","plausible","plaud"], ["esplodere","爆炸","explode","plaud"], ["l'esplosione","爆炸","explosion","plaud"],
    ["privato","私人的","private","priv"], ["privare","剥夺","deprive","priv"], ["la privacy","隐私","privacy","priv"], ["il privilegio","特权","privilege","priv"], ["privatizzare","私有化","privatize","priv"],
    ["prudente","谨慎的","prudent","prud"], ["la prudenza","谨慎","prudence","prud"], ["imprudente","轻率的","imprudent","prud"], ["la giurisprudenza","法学","jurisprudence","prud"],
    ["puro","纯的","pure","pur"], ["purificare","净化","purify","pur"], ["la purezza","纯洁","purity","pur"], ["depurare","净化","purify","pur"], ["la purga","清洗","purge","pur"],
    ["il raggio","光线,半径","ray, radius","radi"], ["irradiare","辐射","radiate","radi"], ["il ravanello","萝卜","radish","radi"], ["la radio","收音机","radio","radi"], ["raggiante","光芒四射的","radiant","radi"], ["la radice","根","root","radi"],
    ["rapido","快速的","rapid","rap"], ["la rapidità","速度","speed","rap"], ["rapire","绑架","abduct","rap"], ["il rapimento","绑架","abduction","rap"], ["rapace","贪婪的,猛禽","rapacious, raptor","rap"], ["la rapina","抢劫","robbery","rap"],
    ["la ruota","轮子","wheel","rot"], ["rotolare","滚动","roll","rot"], ["la rotazione","旋转","rotation","rot"], ["il rotolo","卷","roll","rot"], ["controllare","控制","control","rot"], ["il controllo","控制","control","rot"], ["ruotare","轮换","rotate","rot"], ["rotondo","圆的","round","rot"],
    ["rurale","乡村的","rural","rur"], ["rustico","乡土的","rustic","rur"],
    ["sano","健康的","healthy","san"], ["la sanità","卫生","health service","san"], ["sanitario","卫生的","sanitary","san"], ["insano","不健康的","unhealthy","san"], ["risanare","恢复","restore","san"], ["sanare","治愈","heal","san"],
    ["la sezione","部分","section","sec"], ["il settore","部门","sector","sec"], ["l'insetto","昆虫","insect","sec"], ["sezionare","解剖","dissect","sec"], ["il segmento","段","segment","sec"], ["la setta","教派","sect","sec"],
    ["il senato","参议院","senate","sen"], ["il senatore","参议员","senator","sen"], ["senile","衰老的","senile","sen"], ["il signore","先生","sir","sen"], ["la signora","女士","madam","sen"], ["la signoria","领主权","lordship","sen"],
    ["solo","独自的","alone","sol2"], ["la solitudine","孤独","solitude","sol2"], ["solitario","孤独的","solitary","sol2"], ["desolato","荒凉的","desolate","sol2"], ["isolare","隔离","isolate","sol2"], ["il solista","独奏者","soloist","sol2"],
    ["il sonno","睡眠","sleep","somn"], ["l'insonnia","失眠","insomnia","somn"], ["sonnecchiare","打盹","doze","somn"], ["il sonnambulo","梦游者","sleepwalker","somn"], ["il sonnifero","安眠药","sleeping pill","somn"], ["assonnato","昏昏欲睡的","drowsy","somn"],
    ["lo sponsor","赞助者","sponsor","spond"], ["rispondere","回答","answer","spond"], ["la risposta","回答","answer","spond"], ["corrispondere","符合","correspond","spond"], ["lo sposo","新郎","groom","spond"], ["la sposa","新娘","bride","spond"], ["sposare","娶,嫁","marry","spond"], ["responsabile","负责的","responsible","spond"],
    ["stretto","狭窄的,严格的","narrow, strict","string"], ["stringere","握紧","tighten","string"], ["la restrizione","限制","restriction","string"], ["il distretto","地区","district","string"], ["costringere","强迫","constrain","string"], ["la costrizione","约束","constraint","string"], ["il prestigio","威望","prestige","string"], ["la stretta","握手","grip","string"],
    ["assumere","承担,雇用","assume, hire","sum"], ["consumare","消费","consume","sum"], ["il consumo","消费","consumption","sum"], ["presumere","推测","presume","sum"], ["riassumere","总结","summarize","sum"], ["il riassunto","摘要","summary","sum"], ["sontuoso","奢华的","sumptuous","sum"],
    ["il testo","文本","text","tex"], ["il tessile","纺织品","textile","tex"], ["la tessitura","质地,纺织","texture, weaving","tex"], ["il contesto","语境","context","tex"], ["il pretesto","借口","pretext","tex"], ["il tessuto","织物,组织","fabric, tissue","tex"], ["tessere","织","weave","tex"],
    ["timido","胆小的","timid","tim"], ["intimidire","恐吓","intimidate","tim"], ["la timidezza","胆怯","shyness","tim"], ["temere","害怕","fear","tim"], ["il timore","恐惧","fear","tim"],
    ["tossico","有毒的","toxic","tox"], ["la tossina","毒素","toxin","tox"], ["intossicare","使中毒","poison","tox"], ["l'intossicazione","中毒","poisoning","tox"],
    ["ultimo","最后的","last","ult"], ["l'ultimatum","最后通牒","ultimatum","ult"], ["ulteriore","进一步的","further","ult"], ["oltre","超过","beyond","ult"], ["ultimare","完成","finalize","ult"],
    ["l'onda","波","wave","und"], ["ondeggiare","起伏","undulate","und"], ["abbondante","丰富的","abundant","und"], ["l'abbondanza","丰富","abundance","und"], ["inondare","淹没","flood","und"], ["l'inondazione","洪水","flood","und"], ["ridondante","多余的","redundant","und"],
    ["utile","有用的","useful","ut"], ["l'utilità","效用","utility","ut"], ["utilizzare","使用","use","ut"], ["l'utensile","器具","utensil","ut"], ["l'uso","用法","usage","ut"], ["abusare","滥用","abuse","ut"], ["usare","用","use","ut"], ["usato","用过的","used","ut"],
    ["il vestito","裙子","dress","vest"], ["vestire","穿衣","clothe","vest"], ["investire","投资","invest","vest"], ["l'investimento","投资","investment","vest"], ["la veste","长袍","robe","vest"], ["rivestire","覆盖","coat","vest"],
    ["evolvere","进化","evolve","volv"], ["l'evoluzione","进化","evolution","volv"], ["la rivoluzione","革命","revolution","volv"], ["il volume","卷,体积","volume","volv"], ["avvolgere","包裹","wrap","volv"], ["sviluppare","发展","develop","volv"], ["volgere","转向","turn","volv"], ["rivolgere","转向,对…说","turn, address","volv"], ["coinvolgere","涉及","involve","volv"],
    ["vulnerabile","脆弱的","vulnerable","vulner"], ["la vulnerabilità","脆弱性","vulnerability","vulner"], ["ferire","伤害","wound","vulner"], ["la ferita","伤口","wound","vulner"],
    /* Greek in Italian */ ["la logica","逻辑","logic","log"], ["la biologia","生物学","biology","log"], ["il dialogo","对话","dialogue","log"], ["la tecnologia","技术","technology","log"], ["la psicologia","心理学","psychology","log"], ["il catalogo","目录","catalogue","log"], ["il prologo","序言","prologue","log"], ["l'archeologia","考古学","archaeology","log"], ["l'ecologia","生态学","ecology","log"],
    ["il grafico","图表","graph","graph"], ["la fotografia","照片","photograph","graph"], ["l'autografo","亲笔签名","autograph","graph"], ["la biografia","传记","biography","graph"], ["la geografia","地理","geography","graph"], ["il paragrafo","段落","paragraph","graph"], ["il telegramma","电报","telegram","graph"], ["la grammatica","语法","grammar","graph"], ["l'ortografia","拼写","spelling","graph"],
    ["il telefono","电话","telephone","phon"], ["il microfono","麦克风","microphone","phon"], ["la sinfonia","交响乐","symphony","phon"], ["fonetico","语音的","phonetic","phon"], ["il sassofono","萨克斯","saxophone","phon"],
    ["l'antibiotico","抗生素","antibiotic","bio"], ["biologico","生物的,有机的","biological, organic","bio"], ["la simbiosi","共生","symbiosis","bio"], ["la biodiversità","生物多样性","biodiversity","bio"],
    ["la geologia","地质学","geology","geo"], ["la geometria","几何","geometry","geo"], ["geografico","地理的","geographical","geo"],
    ["cronico","慢性的","chronic","chron"], ["la cronaca","新闻,编年史","news, chronicle","chron"], ["la cronologia","年表","chronology","chron"], ["sincronizzare","同步","synchronize","chron"], ["il cronometro","秒表","stopwatch","chron"],
    ["la simpatia","好感","sympathy","path"], ["l'empatia","共情","empathy","path"], ["l'apatia","冷漠","apathy","path"], ["patetico","可悲的","pathetic","path"], ["la patologia","病理学","pathology","path"],
    ["la televisione","电视","television","tele"], ["il telescopio","望远镜","telescope","tele"], ["il telecomando","遥控器","remote control","tele"], ["il telegiornale","电视新闻","TV news","tele"],
    ["il microscopio","显微镜","microscope","micro"], ["il microbo","微生物","microbe","micro"], ["il microonde","微波炉","microwave","micro"],
    ["il periscopio","潜望镜","periscope","scop"], ["l'oroscopo","星座运势","horoscope","scop"], ["il caleidoscopio","万花筒","kaleidoscope","scop"],
    ["il termometro","温度计","thermometer","meter"], ["il diametro","直径","diameter","meter"], ["il perimetro","周长","perimeter","meter"], ["la simmetria","对称","symmetry","meter"], ["il chilometro","千米","kilometre","meter"],
    ["la democrazia","民主","democracy","crat"], ["l'aristocrazia","贵族","aristocracy","crat"], ["la burocrazia","官僚制","bureaucracy","crat"], ["democratico","民主的","democratic","crat"],
    ["l'antropologia","人类学","anthropology","anthrop"], ["la filantropia","慈善","philanthropy","anthrop"], ["il misantropo","厌世者","misanthrope","anthrop"],
    ["psichico","心理的","psychic","psych"], ["la psichiatria","精神病学","psychiatry","psych"], ["lo psicologo","心理学家","psychologist","psych"],
    ["la filosofia","哲学","philosophy","phil"], ["il filosofo","哲学家","philosopher","phil"], ["filarmonico","爱乐的","philharmonic","phil"],
    ["la teologia","神学","theology","theo"], ["l'ateo","无神论者","atheist","theo"], ["il monoteismo","一神教","monotheism","theo"], ["l'entusiasmo","热情","enthusiasm","theo"],
    ["l'idrogeno","氢","hydrogen","hydr"], ["idraulico","水力的,水管工","hydraulic, plumber","hydr"], ["disidratare","脱水","dehydrate","hydr"],
    ["il ciclo","循环","cycle","cycl"], ["la bicicletta","自行车","bicycle","cycl"], ["riciclare","回收","recycle","cycl"], ["il ciclone","气旋","cyclone","cycl"], ["l'enciclopedia","百科全书","encyclopedia","cycl"],
    ["la fobia","恐惧症","phobia","phob"], ["la claustrofobia","幽闭恐惧","claustrophobia","phob"], ["la xenofobia","仇外","xenophobia","phob"],
    ["il sinonimo","同义词","synonym","onym"], ["il contrario","反义词","antonym","onym"], ["anonimo","匿名的","anonymous","onym"], ["lo pseudonimo","笔名","pseudonym","onym"],
    ["la sintesi","合成","synthesis","syn"], ["il simbolo","符号","symbol","syn"], ["il sistema","系统","system","syn"], ["la sintassi","句法","syntax","syn"],
    ["l'antidoto","解毒剂","antidote","anti"], ["antisociale","反社会的","antisocial","anti"], ["l'antichità","古代","antiquity","anti"], ["l'anticorpo","抗体","antibody","anti"],
    ["iperattivo","过度活跃的","hyperactive","hyper"], ["l'ipermercato","大型超市","hypermarket","hyper"], ["l'ipertensione","高血压","hypertension","hyper"],
    ["il monopolio","垄断","monopoly","mono"], ["il monologo","独白","monologue","mono"], ["monotono","单调的","monotonous","mono"], ["il monarca","君主","monarch","mono"],
    ["il poligono","多边形","polygon","poly"], ["poliglotta","通晓多语的","polyglot","poly"], ["il poliambulatorio","综合诊所","polyclinic","poly"],
    ["il neon","氖","neon","neo"], ["il neologismo","新词","neologism","neo"], ["neolitico","新石器的","Neolithic","neo"],
    ["la diagnosi","诊断","diagnosis","dia"], ["la diagonale","对角线","diagonal","dia"], ["la diapositiva","幻灯片","slide","dia"],
    ["l'atomo","原子","atom","a"], ["l'anarchia","无政府","anarchy","a"], ["l'amnesia","失忆","amnesia","a"], ["apatico","冷漠的","apathetic","a"]
  );
})();
