/* =====================================================
   FUGA MYTHICA — CURSUS Latin 🏛️ · extra batch 3
   Remaining high-frequency verb stems (feeling, speech, motion, daily life) with their families;
   merged into LATIN_EXTRA before buildLatinPack() runs.
   ===================================================== */
(function () {
  Object.assign(LATIN_EXTRA.roots, {
    amo: ["am- / amat-", "爱", "love"], laudo: ["laud-", "赞美", "praise"], iubeo: ["iub- / iuss-", "命令", "order"], iuvo: ["iuv- / iut-", "帮助", "help"],
    rogo: ["rog- / rogat-", "问,求", "ask"], puto: ["put- / putat-", "想,算", "think, reckon"], doleo: ["dol-", "痛", "grieve"], gaudeo: ["gaud- / gavis-", "高兴", "rejoice"],
    rideo: ["rid- / ris-", "笑", "laugh"], fleo: ["fle- / flet-", "哭", "weep"], sileo: ["sil-", "沉默", "be silent"], maneo: ["man- / mans-", "留", "remain"],
    licet: ["lic- / licit-", "允许", "be allowed"], placeo: ["plac- / placit-", "取悦", "please"], pareo: ["par- / parit-", "服从,出现", "obey, appear"], servio: ["serv-", "服务,保存", "serve, keep"],
    valeo: ["val- / valit-", "强健", "be strong"], careo: ["car-", "缺乏", "lack"], disco: ["disc- / discipl-", "学", "learn"], scio: ["sci- / scit-", "知", "know"],
    memini: ["memor-", "记", "remember"], morior: ["mor- / mort-", "死", "die"], alo: ["al- / alt- / alit-", "养", "nourish"], bibo: ["bib- / pot-", "喝", "drink"],
    edo: ["ed- / es-", "吃", "eat"], coquo: ["coqu- / coct-", "煮", "cook"], dormio: ["dorm-", "睡", "sleep"], vigilo: ["vigil-", "醒着", "be awake"],
    surgo: ["surg- / surrect-", "起", "rise"], iaceo: ["iac-", "躺", "lie"], ambulo: ["ambul-", "走", "walk"], eo: ["i- / it-", "去", "go"],
    findo: ["find- / fiss-", "劈", "split"], fodio: ["fod- / foss-", "挖", "dig"], aro: ["ar- / arat-", "耕", "plough"], sero: ["ser- / sat-", "播种", "sow"],
    pingo: ["ping- / pict-", "画", "paint"], salto: ["salt- / sal-", "跳", "jump"], nato: ["nat- / nav-", "游,航", "swim, sail"], porto: ["port-", "运", "carry"],
    do: ["d- / dat-", "给", "give"], vendo: ["vend- / ven-", "卖", "sell"], numero: ["numer-", "数", "count"], opto: ["opt- / optat-", "选,愿", "choose, wish"],
    cupio: ["cup- / cupid-", "渴望", "desire"], odi: ["od- / os-", "恨", "hate"], invideo: ["invid-", "嫉妒", "envy"], culpo: ["culp-", "责备", "blame"],
    accuso: ["accus- / caus-", "控告", "accuse"], damno: ["damn-", "定罪", "condemn"], nego: ["neg-", "否认", "deny"], narro: ["narr-", "讲述", "tell"],
    honos: ["honor- / honest-", "荣誉", "honour"], dubito: ["dubit- / dub-", "怀疑", "doubt"], cogito: ["cogit-", "思考", "think"], existimo: ["aestim-", "估计", "estimate"],
    regno: ["regn-", "统治", "reign"], dominor: ["domin-", "支配", "rule"], sepelio: ["sepel- / sepult-", "埋葬", "bury"], morbus: ["morb-", "病", "disease"],
    dolor: ["dolor-", "痛苦", "pain"], labor2: ["labor-", "劳动", "toil"], otium: ["oti- / negoti-", "闲暇", "leisure"], pretium: ["preti-", "价格", "price"],
    lucrum: ["lucr-", "利润", "profit"], pecunia: ["pecun- / pecu-", "钱,牲畜", "money, cattle"], ager: ["agr-", "田", "field"], silva: ["silv-", "森林", "forest"],
    mons: ["mont-", "山", "mountain"], flumen: ["flumin- / fluvi-", "河", "river"], ignis3: ["flamm-", "火焰", "flame"], nix: ["niv-", "雪", "snow"],
    arbor: ["arbor-", "树", "tree"], herba: ["herb-", "草", "grass"], radix: ["radic-", "根", "root"], semen: ["semin-", "种子", "seed"],
    avis: ["avi- / auc-", "鸟", "bird"], piscis: ["pisc-", "鱼", "fish"], bos: ["bov- / bu-", "牛", "ox"], equus: ["equ- / equit-", "马", "horse"],
    canis: ["can-", "狗", "dog"], lupus: ["lup-", "狼", "wolf"], leo: ["leon-", "狮", "lion"], serpens: ["serp- / angu-", "蛇", "snake"],
  });
  LATIN_EXTRA.words.push(
    ["amo","爱","love","amo"], ["amor","爱","love","amo"], ["amicus","朋友","friend","amo"], ["amicitia","友谊","friendship","amo"], ["inimicus","敌人","enemy","amo"], ["amabilis","可爱的","lovable","amo"], ["amator","爱慕者","lover","amo"], ["amatorius","爱情的","amatory","amo"], ["amoenus","宜人的","pleasant","amo"],
    ["laudo","赞美","praise","laudo"], ["laus","赞美","praise","laudo"], ["laudabilis","值得赞美的","praiseworthy","laudo"], ["laudator","赞美者","praiser","laudo"], ["collaudo","高度赞扬","praise highly","laudo"],
    ["iubeo","命令","order","iubeo"], ["iussum","命令","command","iubeo"], ["iussus","被命令的","ordered","iubeo"], ["iniussu","未经命令","without orders","iubeo"],
    ["iuvo","帮助","help","iuvo"], ["adiuvo","援助","assist","iuvo"], ["adiutor","助手","helper","iuvo"], ["adiumentum","帮助","aid","iuvo"], ["iucundus","愉快的","pleasant","iuvo"],
    ["rogo","问,求","ask","rogo"], ["interrogo","询问","question","rogo"], ["interrogatio","询问","interrogation","rogo"], ["abrogo","废除","repeal","rogo"], ["arrogo","僭取","claim","rogo"], ["arrogans","傲慢的","arrogant","rogo"], ["derogo","减损","detract","rogo"], ["prorogo","延期","prolong","rogo"], ["surrogo","代替","substitute","rogo"], ["rogatio","提案","bill","rogo"],
    ["puto","想,认为","think","puto"], ["computo","计算","calculate","puto"], ["deputo","估计,指派","assign","puto"], ["disputo","讨论","dispute","puto"], ["disputatio","辩论","debate","puto"], ["imputo","归咎","impute","puto"], ["reputo","反复思考","consider","puto"], ["reputatio","名声","reputation","puto"], ["amputo","切除","cut off","puto"],
    ["doleo","痛,悲伤","grieve","doleo"], ["dolor","痛苦","pain","doleo"], ["dolorosus","痛苦的","painful","doleo"], ["indolens","不痛的","painless","doleo"], ["condoleo","同情","sympathize","doleo"],
    ["gaudeo","高兴","rejoice","gaudeo"], ["gaudium","喜悦","joy","gaudeo"], ["gavisus","高兴的","glad","gaudeo"],
    ["rideo","笑","laugh","rideo"], ["risus","笑","laughter","rideo"], ["ridiculus","可笑的","ridiculous","rideo"], ["derideo","嘲笑","mock","rideo"], ["irrideo","嘲弄","ridicule","rideo"], ["subrideo","微笑","smile","rideo"],
    ["fleo","哭","weep","fleo"], ["fletus","哭泣","weeping","fleo"], ["flebilis","可悲的","lamentable","fleo"], ["defleo","哀悼","mourn","fleo"],
    ["sileo","沉默","be silent","sileo"], ["silentium","寂静","silence","sileo"], ["silens","无声的","silent","sileo"],
    ["maneo","留","remain","maneo"], ["permaneo","持续","last","maneo"], ["permanens","永久的","permanent","maneo"], ["remaneo","留下","remain","maneo"], ["mansio","停留,住所","stay, dwelling","maneo"], ["immanens","内在的","immanent","maneo"],
    ["licet","允许","it is allowed","licet"], ["licentia","许可,放纵","licence","licet"], ["licitus","合法的","lawful","licet"], ["illicitus","非法的","illicit","licet"],
    ["placeo","取悦","please","placeo"], ["placidus","平静的","calm","placeo"], ["placo","安抚","appease","placeo"], ["complaceo","使满意","please greatly","placeo"], ["displiceo","使不悦","displease","placeo"], ["placitum","决定","decision","placeo"],
    ["pareo","服从,出现","obey, appear","pareo"], ["appareo","出现","appear","pareo"], ["apparens","明显的","apparent","pareo"], ["apparitio","出现","appearance","pareo"], ["transpareo","透明","be transparent","pareo"],
    ["servio","服务","serve","servio"], ["servus","奴隶","slave","servio"], ["servitus","奴役","slavery","servio"], ["servo","保存","keep","servio"], ["conservo","保护","preserve","servio"], ["observo","观察","observe","servio"], ["observatio","观察","observation","servio"], ["praeservo","预防","preserve","servio"], ["reservo","保留","reserve","servio"], ["servilis","奴性的","servile","servio"], ["servitium","服务","service","servio"],
    ["valeo","强健","be strong","valeo"], ["validus","强壮的","strong","valeo"], ["invalidus","虚弱的","weak","valeo"], ["valetudo","健康","health","valeo"], ["valor","价值","worth","valeo"], ["praevaleo","占优势","prevail","valeo"], ["convalesco","康复","recover","valeo"], ["aequivaleo","等值","be equivalent","valeo"], ["vale","再见","farewell","valeo"],
    ["careo","缺乏","lack","careo"], ["carens","缺乏的","lacking","careo"], ["castus","纯洁的","chaste","careo"],
    ["disco","学","learn","disco"], ["discipulus","学生","pupil","disco"], ["disciplina","训练,学科","discipline","disco"], ["addisco","学到","learn in addition","disco"], ["edisco","背诵","learn by heart","disco"],
    ["scio","知道","know","scio"], ["scientia","知识","knowledge","scio"], ["sciens","知情的","knowing","scio"], ["nescio","不知道","not know","scio"], ["nescius","不知的","unaware","scio"], ["conscius","知情的","aware","scio"], ["conscientia","良心","conscience","scio"], ["scilicet","当然","of course","scio"], ["omniscius","全知的","omniscient","scio"], ["praescius","预知的","foreknowing","scio"],
    ["memini","记得","remember","memini"], ["memor","记着的","mindful","memini"], ["memoria","记忆","memory","memini"], ["memoro","提及","mention","memini"], ["commemoro","纪念","commemorate","memini"], ["memorabilis","值得纪念的","memorable","memini"], ["immemor","忘记的","forgetful","memini"], ["memorandum","备忘录","memo","memini"],
    ["morior","死","die","morior"], ["mors","死亡","death","morior"], ["mortuus","死的","dead","morior"], ["mortalis","凡人的","mortal","morior"], ["immortalis","不朽的","immortal","morior"], ["mortifer","致命的","deadly","morior"], ["moribundus","垂死的","dying","morior"], ["emorior","死去","die off","morior"],
    ["alo","养","nourish","alo"], ["alimentum","食物","food","alo"], ["alumnus","养子,学生","foster child","alo"], ["altus","高的","high","alo"], ["adultus","成年的","grown up","alo"], ["adolesco","成长","grow up","alo"], ["adolescens","青年","youth","alo"], ["proles","后代","offspring","alo"], ["almus","养育的","nourishing","alo"],
    ["bibo","喝","drink","bibo"], ["potus","饮料","drink","bibo"], ["poto","喝","drink","bibo"], ["potio","饮料","drink","bibo"], ["potator","酒徒","drinker","bibo"], ["imbibo","吸收","absorb","bibo"], ["bibulus","嗜酒的","fond of drink","bibo"],
    ["edo","吃","eat","edo"], ["esca","食物","food","edo"], ["esculentus","可食的","edible","edo"], ["edax","贪吃的","voracious","edo"], ["comedo","吃光","eat up","edo"], ["obesus","肥胖的","fat","edo"],
    ["coquo","煮","cook","coquo"], ["coquus","厨师","cook","coquo"], ["coctus","煮熟的","cooked","coquo"], ["culina","厨房","kitchen","coquo"], ["praecox","早熟的","precocious","coquo"], ["biscoctum","饼干","biscuit","coquo"],
    ["dormio","睡","sleep","dormio"], ["dormitorium","宿舍","dormitory","dormio"], ["dormitio","睡眠","sleeping","dormio"], ["obdormio","入睡","fall asleep","dormio"],
    ["vigilo","醒着","be awake","vigilo"], ["vigil","守夜人","watchman","vigilo"], ["vigilia","守夜","vigil","vigilo"], ["vigilans","警惕的","vigilant","vigilo"], ["vigilantia","警惕","vigilance","vigilo"], ["evigilo","醒来","wake up","vigilo"],
    ["surgo","起","rise","surgo"], ["resurgo","再起","rise again","surgo"], ["resurrectio","复活","resurrection","surgo"], ["insurgo","起义","rise up","surgo"], ["insurrectio","起义","insurrection","surgo"], ["exsurgo","站起","stand up","surgo"], ["surrectus","竖立的","raised","surgo"],
    ["iaceo","躺","lie","iaceo"], ["adiaceo","毗邻","lie near","iaceo"], ["adiacens","相邻的","adjacent","iaceo"], ["subiaceo","位于下","lie under","iaceo"], ["circumiaceo","环绕","lie around","iaceo"], ["interiaceo","位于其间","lie between","iaceo"],
    ["ambulo","走","walk","ambulo"], ["ambulatio","散步","walk","ambulo"], ["deambulo","漫步","stroll","ambulo"], ["perambulo","走遍","walk through","ambulo"], ["praeambulus","先行的","going before","ambulo"],
    ["eo","去","go","eo"], ["abeo","离开","go away","eo"], ["adeo","接近","approach","eo"], ["exeo","出去","go out","eo"], ["exitus","出口,结局","exit, outcome","eo"], ["ineo","进入","enter","eo"], ["initium","开始","beginning","eo"], ["pereo","灭亡","perish","eo"], ["redeo","返回","return","eo"], ["reditus","返回","return","eo"], ["transeo","越过","cross","eo"], ["transitus","通过","passage","eo"], ["obeo","去世,履行","die, perform","eo"], ["obitus","死亡","death","eo"], ["praetereo","经过,忽略","pass by","eo"], ["ambitio","野心","ambition","eo"], ["circuitus","环绕","circuit","eo"], ["comes","同伴","companion","eo"], ["comitatus","随从","retinue","eo"], ["iter","旅程","journey","eo"], ["itinerarium","行程","itinerary","eo"], ["seditio","叛乱","sedition","eo"],
    ["findo","劈","split","findo"], ["fissura","裂缝","fissure","findo"], ["fissus","裂开的","split","findo"], ["diffindo","劈开","split apart","findo"],
    ["fodio","挖","dig","fodio"], ["fossa","沟","ditch","fodio"], ["fossor","挖掘者","digger","fodio"], ["effodio","挖出","dig out","fodio"], ["confodio","刺穿","stab","fodio"],
    ["aro","耕","plough","aro"], ["aratrum","犁","plough","aro"], ["arator","农夫","ploughman","aro"], ["arvum","耕地","field","aro"], ["arabilis","可耕的","arable","aro"],
    ["sero","播种","sow","sero"], ["semen","种子","seed","sero"], ["sementis","播种","sowing","sero"], ["satio","播种","sowing","sero"], ["sator","播种者","sower","sero"], ["insero","插入","insert","sero"], ["consero","种植","plant","sero"], ["dissemino","散布","scatter","sero"],
    ["pingo","画","paint","pingo"], ["pictor","画家","painter","pingo"], ["pictura","画","painting","pingo"], ["pictus","彩绘的","painted","pingo"], ["depingo","描绘","depict","pingo"], ["pigmentum","颜料","pigment","pingo"],
    ["salio","跳","jump","salto"], ["salto","跳舞","dance","salto"], ["saltus","跳跃,林地","leap; woodland","salto"], ["saltatio","舞蹈","dance","salto"], ["saltator","舞者","dancer","salto"], ["assilio","跳向","leap at","salto"], ["desilio","跳下","jump down","salto"], ["exsilio","跳起","spring up","salto"], ["insulto","侮辱","insult","salto"], ["resulto","反弹","rebound","salto"], ["salax","好色的","lustful","salto"],
    ["nato","游泳","swim","nato"], ["natatio","游泳","swimming","nato"], ["navigo","航行","sail","nato"], ["navigatio","航行","voyage","nato"], ["navis","船","ship","nato"], ["navalis","海军的","naval","nato"], ["nauta","水手","sailor","nato"], ["naufragus","遇难者","shipwrecked","nato"], ["naufragium","海难","shipwreck","nato"],
    ["porto","运","carry","porto"], ["apporto","带来","bring","porto"], ["asporto","带走","carry off","porto"], ["comporto","收集","collect","porto"], ["deporto","带走,放逐","carry away, banish","porto"], ["exporto","运出","export","porto"], ["importo","运入","import","porto"], ["reporto","带回","bring back","porto"], ["supporto","运送","carry up","porto"], ["transporto","运过去","transport","porto"], ["portus","港口","harbour","porto"], ["porta","门","gate","porto"], ["portabilis","可携带的","portable","porto"], ["opportunus","合适的","suitable","porto"], ["importunus","不合时宜的","troublesome","porto"],
    ["do","给","give","do"], ["datum","给予物","gift","do"], ["dator","给予者","giver","do"], ["addo","加","add","do"], ["additio","加法","addition","do"], ["condo","建立,收藏","found, store","do"], ["conditor","创建者","founder","do"], ["abscondo","藏","hide","do"], ["dedo","交出","surrender","do"], ["deditio","投降","surrender","do"], ["edo (ēdō)","发出,出版","publish","do"], ["editio","版本","edition","do"], ["editor","出版者","publisher","do"], ["perdo","毁掉,失去","destroy, lose","do"], ["perditio","毁灭","ruin","do"], ["prodo","背叛,泄露","betray","do"], ["proditor","叛徒","traitor","do"], ["reddo","归还","give back","do"], ["trado","交付,传授","hand over","do"], ["traditio","传统","tradition","do"], ["vendo","卖","sell","vendo"], ["venditor","卖家","seller","vendo"], ["venditio","出售","sale","vendo"], ["venalis","可出售的","for sale","vendo"], ["venum","出售","sale","vendo"],
    ["numero","数","count","numero"], ["numerus","数","number","numero"], ["numerator","计数者","counter","numero"], ["enumero","列举","enumerate","numero"], ["dinumero","清点","count up","numero"],
    ["opto","选择,希望","choose, wish","opto"], ["optio","选择","choice","opto"], ["optatus","希望的","desired","opto"], ["adopto","收养","adopt","opto"], ["adoptio","收养","adoption","opto"], ["optimus","最好的","best","opto"], ["optime","极好地","excellently","opto"],
    ["cupio","渴望","desire","cupio"], ["cupidus","渴望的","desirous","cupio"], ["cupiditas","贪欲","greed","cupio"], ["Cupido","丘比特","Cupid","cupio"], ["concupisco","贪求","covet","cupio"],
    ["odi","恨","hate","odi"], ["odium","仇恨","hatred","odi"], ["odiosus","可恨的","hateful","odi"], ["exosus","憎恶的","hating","odi"],
    ["invideo","嫉妒","envy","invideo"], ["invidia","嫉妒","envy","invideo"], ["invidus","嫉妒的","envious","invideo"], ["invidiosus","招人嫉妒的","envied","invideo"],
    ["culpo","责备","blame","culpo"], ["culpa","过错","fault","culpo"], ["culpabilis","有罪的","culpable","culpo"], ["inculpatus","无罪的","blameless","culpo"], ["exculpo","开脱","exculpate","culpo"],
    ["accuso","控告","accuse","accuso"], ["accusatio","控告","accusation","accuso"], ["accusator","原告","accuser","accuso"], ["causa","原因,案件","cause, case","accuso"], ["causor","借口","plead","accuso"], ["excuso","辩解","excuse","accuso"], ["excusatio","辩解","excuse","accuso"], ["recuso","拒绝","refuse","accuso"], ["incuso","指责","accuse","accuso"],
    ["damno","定罪","condemn","damno"], ["damnum","损失","loss","damno"], ["damnatio","定罪","condemnation","damno"], ["condemno","判罪","condemn","damno"], ["indemnis","未受损的","unharmed","damno"], ["damnosus","有害的","harmful","damno"],
    ["nego","否认","deny","nego"], ["negatio","否定","denial","nego"], ["negativus","否定的","negative","nego"], ["abnego","拒绝","refuse","nego"], ["denego","拒绝","deny","nego"], ["negotium","事务","business","nego"], ["negotior","经商","do business","nego"], ["negotiator","商人","merchant","nego"],
    ["narro","讲述","tell","narro"], ["narratio","叙述","narrative","narro"], ["narrator","讲述者","narrator","narro"], ["enarro","详述","explain","narro"], ["gnarus","知道的","knowing","narro"], ["ignarus","不知的","ignorant","narro"],
    ["honos","荣誉","honour","honos"], ["honor","荣誉","honour","honos"], ["honoro","尊敬","honour","honos"], ["honestus","诚实的","honourable","honos"], ["honestas","诚实","honesty","honos"], ["inhonestus","不光彩的","dishonourable","honos"], ["honorarius","荣誉的","honorary","honos"], ["honorificus","授予荣誉的","honorific","honos"],
    ["dubito","怀疑","doubt","dubito"], ["dubium","疑问","doubt","dubito"], ["dubius","可疑的","doubtful","dubito"], ["indubitatus","无疑的","undoubted","dubito"], ["dubitatio","犹豫","hesitation","dubito"],
    ["cogito","思考","think","cogito"], ["cogitatio","思想","thought","cogito"], ["excogito","想出","devise","cogito"], ["recogito","反思","reconsider","cogito"], ["cogitabundus","沉思的","thoughtful","cogito"],
    ["existimo","估计","estimate","existimo"], ["aestimo","估价","value","existimo"], ["aestimatio","估价","valuation","existimo"], ["existimatio","名声","reputation","existimo"], ["inaestimabilis","无法估量的","inestimable","existimo"],
    ["regno","统治","reign","regno"], ["regnum","王国","kingdom","regno"], ["regnator","统治者","ruler","regno"], ["interregnum","空位期","interregnum","regno"],
    ["dominor","支配","rule","dominor"], ["dominus","主人","master","dominor"], ["domina","女主人","mistress","dominor"], ["dominatio","统治","domination","dominor"], ["dominium","所有权","ownership","dominor"], ["domesticus","家庭的","domestic","dominor"], ["domicilium","住所","dwelling","dominor"],
    ["sepelio","埋葬","bury","sepelio"], ["sepulcrum","坟墓","tomb","sepelio"], ["sepultura","埋葬","burial","sepelio"], ["sepultus","埋葬的","buried","sepelio"],
    ["morbus","病","disease","morbus"], ["morbidus","病态的","diseased","morbus"], ["morbosus","病的","sickly","morbus"], ["aegrotus","病人","sick person","morbus"], ["aeger","生病的","sick","morbus"],
    ["dolor","痛苦","pain","dolor"], ["doloris","痛的","of pain","dolor"], ["indolentia","无痛","freedom from pain","dolor"],
    ["labor","劳动","toil","labor2"], ["laboro","劳作","work","labor2"], ["laboriosus","费力的","laborious","labor2"], ["elaboro","精心制作","work out","labor2"], ["laboratorium","工作场所","workshop","labor2"],
    ["otium","闲暇","leisure","otium"], ["otiosus","闲的","idle","otium"], ["negotium","事务","business","otium"], ["negotiosus","忙碌的","busy","otium"],
    ["pretium","价格","price","pretium"], ["pretiosus","珍贵的","precious","pretium"], ["appretio","估价","appraise","pretium"], ["depretio","贬值","depreciate","pretium"],
    ["lucrum","利润","profit","lucrum"], ["lucror","获利","gain","lucrum"], ["lucrosus","有利的","profitable","lucrum"], ["lucrativus","盈利的","lucrative","lucrum"],
    ["pecunia","钱","money","pecunia"], ["pecuniarius","金钱的","pecuniary","pecunia"], ["pecus","牲畜","cattle","pecunia"], ["peculium","私产","private property","pecunia"], ["peculiaris","特有的","peculiar","pecunia"], ["peculator","贪污者","embezzler","pecunia"],
    ["ager","田","field","ager"], ["agricola","农民","farmer","ager"], ["agricultura","农业","agriculture","ager"], ["agrestis","乡野的","rustic","ager"], ["peregrinus","外来的","foreign","ager"], ["peregrinor","漫游","travel abroad","ager"], ["agrarius","土地的","agrarian","ager"],
    ["silva","森林","forest","silva"], ["silvestris","林中的","wooded","silva"], ["silvaticus","野生的","wild","silva"], ["Silvanus","森林之神","Silvanus","silva"],
    ["mons","山","mountain","mons"], ["montanus","山地的","mountainous","mons"], ["promontorium","海角","promontory","mons"], ["monticulus","小山","hillock","mons"], ["transmontanus","山那边的","beyond the mountains","mons"],
    ["flumen","河","river","flumen"], ["fluvius","河","river","flumen"], ["fluvialis","河的","fluvial","flumen"], ["flumineus","河的","of a river","flumen"],
    ["flamma","火焰","flame","ignis3"], ["flammeus","火焰般的","flaming","ignis3"], ["inflammo","点燃","inflame","ignis3"], ["inflammatio","炎症","inflammation","ignis3"], ["flagro","燃烧","blaze","ignis3"], ["conflagratio","大火","conflagration","ignis3"], ["flagrans","炽热的","flagrant","ignis3"],
    ["nix","雪","snow","nix"], ["niveus","雪白的","snowy","nix"], ["nivalis","雪的","snowy","nix"], ["ninguit","下雪","it snows","nix"],
    ["arbor","树","tree","arbor"], ["arboreus","树的","of trees","arbor"], ["arbustum","灌木丛","shrubbery","arbor"], ["arboretum","树园","arboretum","arbor"],
    ["herba","草","grass","herba"], ["herbosus","多草的","grassy","herba"], ["herbarium","植物标本","herbarium","herba"], ["herbidus","长满草的","grassy","herba"],
    ["radix","根","root","radix"], ["radicalis","根本的","radical","radix"], ["eradico","根除","uproot","radix"], ["radicitus","连根地","by the roots","radix"],
    ["semen","种子","seed","semen"], ["seminarium","苗圃","nursery","semen"], ["semino","播种","sow","semen"], ["dissemino","传播","disseminate","semen"],
    ["avis","鸟","bird","avis"], ["aviarium","鸟舍","aviary","avis"], ["auspicium","占卜","augury","avis"], ["augur","占卜官","augur","avis"], ["augurium","预兆","omen","avis"], ["avicula","小鸟","little bird","avis"],
    ["piscis","鱼","fish","piscis"], ["piscator","渔夫","fisherman","piscis"], ["piscor","捕鱼","fish","piscis"], ["piscina","鱼池","fishpond","piscis"], ["piscosus","多鱼的","full of fish","piscis"],
    ["bos","牛","ox","bos"], ["bovinus","牛的","bovine","bos"], ["bubulcus","牧牛人","ploughman","bos"], ["bucula","小母牛","heifer","bos"],
    ["equus","马","horse","equus"], ["equa","母马","mare","equus"], ["eques","骑士","horseman","equus"], ["equester","骑士的","equestrian","equus"], ["equitatus","骑兵","cavalry","equus"], ["equito","骑马","ride","equus"], ["equinus","马的","equine","equus"],
    ["canis","狗","dog","canis"], ["caninus","狗的","canine","canis"], ["canicula","小狗,天狼星","little dog; Sirius","canis"],
    ["lupus","狼","wolf","lupus"], ["lupa","母狼","she-wolf","lupus"], ["lupinus","狼的","of wolves","lupus"],
    ["leo","狮","lion","leo"], ["leaena","母狮","lioness","leo"], ["leoninus","狮子的","leonine","leo"],
    ["serpens","蛇","snake","serpens"], ["serpo","爬","creep","serpens"], ["anguis","蛇","snake","serpens"], ["anguilla","鳗鱼","eel","serpens"]
  );
})();
