/* =====================================================
   FUGA MYTHICA — CURSUS French 🇫🇷 · batch 12 — topical vocabulary 3: adverbs & connectors, time & quantity, hobbies, sport, music, nationalities, animals, plants, house, office, abstract nouns
   ===================================================== */
(function () {
  const p = VOCAB.fr;
  Object.assign(p.roots, {});
  p.words.push(
    ["néanmoins", "尽管如此", "even so", "topic"],
    ["par conséquent", "结果", "as a result", "topic"],
    ["de plus", "此外", "also", "topic"],
    ["en outre", "而且", "in addition", "topic"],
    ["pendant ce temps", "同时", "at the same time", "topic"],
    ["à l'avance", "事先", "in advance", "topic"],
    ["immédiatement", "立刻", "at once", "topic"],
    ["soudain", "突然", "without warning", "topic"],
    ["progressivement", "逐渐", "step by step", "topic"],
    ["récemment", "最近", "not long ago", "topic"],
    ["dernièrement", "近来", "recently", "topic"],
    ["de nos jours", "如今", "these days", "topic"],
    ["autrefois", "以前", "in the past", "topic"],
    ["actuellement", "目前", "now", "topic"],
    ["de temps en temps", "偶尔", "sometimes", "topic"],
    ["fréquemment", "经常", "often", "topic"],
    ["constamment", "不断地", "all the time", "topic"],
    ["quotidiennement", "每天", "every day", "topic"],
    ["chaque semaine", "每周", "every week", "topic"],
    ["mensuellement", "每月", "every month", "topic"],
    ["annuellement", "每年", "every year", "topic"],
    ["deux fois", "两次", "two times", "topic"],
    ["une fois", "一次", "one time", "topic"],
    ["à peine", "几乎不", "barely", "topic"],
    ["plutôt", "宁可,相当", "fairly", "topic"],
    ["extrêmement", "极其", "very", "topic"],
    ["légèrement", "稍微", "a little", "topic"],
    ["entièrement", "完全", "completely", "topic"],
    ["en partie", "部分地", "not completely", "topic"],
    ["principalement", "主要地", "mostly", "topic"],
    ["particulièrement", "特别", "especially", "topic"],
    ["exactement", "恰好", "precisely", "topic"],
    ["précisément", "精确地", "exactly", "topic"],
    ["apparemment", "显然", "it seems", "topic"],
    ["évidemment", "明显地", "clearly", "topic"],
    ["certainement", "当然", "surely", "topic"],
    ["probablement", "可能", "likely", "topic"],
    ["espérons-le", "但愿", "it is hoped", "topic"],
    ["malheureusement", "不幸地", "sadly", "topic"],
    ["heureusement", "幸运地", "luckily", "topic"],
    ["étonnamment", "令人惊讶地", "unexpectedly", "topic"],
    ["honnêtement", "老实说", "truthfully", "topic"],
    ["en gros", "基本上", "essentially", "topic"],
    ["spécifiquement", "具体地", "in particular", "topic"],
    ["à savoir", "即", "that is", "topic"],
    ["par exemple", "例如", "for example", "topic"],
    ["autrement dit", "换句话说", "that is to say", "topic"],
    ["d'autre part", "另一方面", "conversely", "topic"],
    ["en plus", "此外", "also", "topic"],
    ["bref", "简而言之", "briefly", "topic"],
    ["au moins", "至少", "minimum", "topic"],
    ["au plus", "至多", "maximum", "topic"],
    ["de toute façon", "无论如何", "in any case", "topic"],
    ["à moins que", "除非", "except if", "topic"],
    ["tant que", "只要", "provided that", "topic"],
    ["au cas où", "以防", "if it happens", "topic"],
    ["même si", "即使", "despite", "topic"],
    ["concernant", "关于", "about", "topic"],
    ["tout au long de", "贯穿", "during all of", "topic"],
    ["au-delà de", "超过", "further than", "topic"],
    ["la quinzaine", "两周", "two weeks", "topic"],
    ["l'ère", "时代", "period", "topic"],
    ["l'échéance", "期限", "time limit", "topic"],
    ["l'année bissextile", "闰年", "366-day year", "topic"],
    ["le montant", "数额", "quantity", "topic"],
    ["la plupart", "大多数", "most", "topic"],
    ["la poignée", "一把", "small number", "topic"],
    ["le tas", "堆", "pile", "topic"],
    ["le bouquet", "一束", "group", "topic"],
    ["la tranche", "一片", "thin piece", "topic"],
    ["la goutte", "一滴", "small amount of liquid", "topic"],
    ["la miette", "面包屑", "tiny piece", "topic"],
    ["le morceau", "块", "piece", "topic"],
    ["la cuillerée", "一勺", "spoon amount", "topic"],
    ["la pincée", "一撮", "tiny amount", "topic"],
    ["la rangée", "排", "line", "topic"],
    ["le passe-temps", "爱好", "pastime", "topic"],
    ["les loisirs", "休闲", "free time", "topic"],
    ["le jardinage", "园艺", "growing plants", "topic"],
    ["la poterie", "陶艺", "clay work", "topic"],
    ["le tricot", "编织", "wool craft", "topic"],
    ["la couture", "缝纫", "needlework", "topic"],
    ["la menuiserie", "木工", "woodwork", "topic"],
    ["le collectionneur", "收藏家", "one who collects", "topic"],
    ["le puzzle", "拼图", "jigsaw", "topic"],
    ["les mots croisés", "填字游戏", "word puzzle", "topic"],
    ["le jeu de société", "桌游", "table game", "topic"],
    ["les échecs", "国际象棋", "chess", "topic"],
    ["les cartes", "扑克牌", "playing cards", "topic"],
    ["les dés", "骰子", "dice", "topic"],
    ["le jeu vidéo", "电子游戏", "video game", "topic"],
    ["la console", "游戏机", "games machine", "topic"],
    ["le karaoké", "卡拉OK", "karaoke", "topic"],
    ["le pique-nique", "野餐", "outdoor meal", "topic"],
    ["le barbecue", "烧烤", "grill party", "topic"],
    ["la canne à pêche", "钓竿", "fishing pole", "topic"],
    ["la raquette", "球拍", "bat", "topic"],
    ["le ballon", "球", "ball", "topic"],
    ["le gardien de but", "守门员", "goalie", "topic"],
    ["l'arbitre", "裁判", "umpire", "topic"],
    ["le sifflet", "哨子", "whistle", "topic"],
    ["la piste", "跑道", "running course", "topic"],
    ["le marathon", "马拉松", "long race", "topic"],
    ["le sprint", "短跑", "fast run", "topic"],
    ["le javelot", "标枪", "throwing spear", "topic"],
    ["la lutte", "摔跤", "grappling sport", "topic"],
    ["la boxe", "拳击", "fist fighting", "topic"],
    ["l'escrime", "击剑", "sword sport", "topic"],
    ["le tir à l'arc", "射箭", "bow sport", "topic"],
    ["l'aviron", "赛艇", "oar sport", "topic"],
    ["le surf", "冲浪", "wave riding", "topic"],
    ["la plongée", "潜水", "underwater sport", "topic"],
    ["l'escalade", "攀岩", "rock sport", "topic"],
    ["le patinage", "滑冰", "ice sport", "topic"],
    ["le skateboard", "滑板", "board", "topic"],
    ["le casque", "头盔", "head protection", "topic"],
    ["le trophée", "奖杯", "prize cup", "topic"],
    ["le tournoi", "锦标赛", "competition", "topic"],
    ["la demi-finale", "半决赛", "match before final", "topic"],
    ["le penalty", "点球", "penalty kick", "topic"],
    ["le hors-jeu", "越位", "offside", "topic"],
    ["le corner", "角球", "corner kick", "topic"],
    ["la mi-temps", "中场休息", "break", "topic"],
    ["les prolongations", "加时赛", "added time", "topic"],
    ["la musique classique", "古典音乐", "classical", "topic"],
    ["le jazz", "爵士乐", "jazz", "topic"],
    ["le rock", "摇滚", "rock", "topic"],
    ["la musique pop", "流行音乐", "pop", "topic"],
    ["la musique folk", "民谣", "folk", "topic"],
    ["le rap", "说唱", "rap", "topic"],
    ["les paroles", "歌词", "song words", "topic"],
    ["la gamme", "音阶", "scale", "topic"],
    ["l'album", "专辑", "record", "topic"],
    ["le groupe", "乐队", "group", "topic"],
    ["le batteur", "鼓手", "drum player", "topic"],
    ["le guitariste", "吉他手", "guitar player", "topic"],
    ["le pianiste", "钢琴家", "piano player", "topic"],
    ["le violoniste", "小提琴手", "violin player", "topic"],
    ["le compositeur", "作曲家", "music writer", "topic"],
    ["le haut-parleur", "扬声器", "speaker", "topic"],
    ["britannique", "英国的", "from Britain", "topic"],
    ["irlandais", "爱尔兰的", "from Ireland", "topic"],
    ["écossais", "苏格兰的", "from Scotland", "topic"],
    ["néerlandais", "荷兰的", "from the Netherlands", "topic"],
    ["belge", "比利时的", "from Belgium", "topic"],
    ["suisse", "瑞士的", "from Switzerland", "topic"],
    ["autrichien", "奥地利的", "from Austria", "topic"],
    ["polonais", "波兰的", "from Poland", "topic"],
    ["tchèque", "捷克的", "from Czechia", "topic"],
    ["hongrois", "匈牙利的", "from Hungary", "topic"],
    ["suédois", "瑞典的", "from Sweden", "topic"],
    ["norvégien", "挪威的", "from Norway", "topic"],
    ["danois", "丹麦的", "from Denmark", "topic"],
    ["finlandais", "芬兰的", "from Finland", "topic"],
    ["portugais", "葡萄牙的", "from Portugal", "topic"],
    ["turc", "土耳其的", "from Turkey", "topic"],
    ["égyptien", "埃及的", "from Egypt", "topic"],
    ["marocain", "摩洛哥的", "from Morocco", "topic"],
    ["indien", "印度的", "from India", "topic"],
    ["coréen", "韩国的", "from Korea", "topic"],
    ["vietnamien", "越南的", "from Vietnam", "topic"],
    ["thaïlandais", "泰国的", "from Thailand", "topic"],
    ["australien", "澳大利亚的", "from Australia", "topic"],
    ["canadien", "加拿大的", "from Canada", "topic"],
    ["mexicain", "墨西哥的", "from Mexico", "topic"],
    ["brésilien", "巴西的", "from Brazil", "topic"],
    ["argentin", "阿根廷的", "from Argentina", "topic"],
    ["le scarabée", "甲虫", "beetle", "topic"],
    ["la coccinelle", "瓢虫", "ladybird", "topic"],
    ["la sauterelle", "蚱蜢", "grasshopper", "topic"],
    ["le grillon", "蟋蟀", "cricket", "topic"],
    ["la guêpe", "黄蜂", "wasp", "topic"],
    ["le papillon de nuit", "飞蛾", "moth", "topic"],
    ["l'escargot", "蜗牛", "snail", "topic"],
    ["la limace", "鼻涕虫", "slug", "topic"],
    ["le ver", "蠕虫", "worm", "topic"],
    ["le lézard", "蜥蜴", "lizard", "topic"],
    ["le crocodile", "鳄鱼", "crocodile", "topic"],
    ["le crapaud", "蟾蜍", "toad", "topic"],
    ["le phoque", "海豹", "seal", "topic"],
    ["le morse", "海象", "walrus", "topic"],
    ["le requin", "鲨鱼", "shark", "topic"],
    ["la méduse", "水母", "jellyfish", "topic"],
    ["l'étoile de mer", "海星", "starfish", "topic"],
    ["l'hippocampe", "海马", "seahorse", "topic"],
    ["la moule", "贻贝", "mussel", "topic"],
    ["le calmar", "鱿鱼", "squid", "topic"],
    ["la truite", "鳟鱼", "trout", "topic"],
    ["le saumon", "三文鱼", "salmon", "topic"],
    ["la morue", "鳕鱼", "cod", "topic"],
    ["la sardine", "沙丁鱼", "sardine", "topic"],
    ["l'anguille", "鳗鱼", "eel", "topic"],
    ["le perroquet", "鹦鹉", "parrot", "topic"],
    ["le pingouin", "企鹅", "penguin", "topic"],
    ["l'autruche", "鸵鸟", "ostrich", "topic"],
    ["la cigogne", "鹳", "stork", "topic"],
    ["le héron", "鹭", "heron", "topic"],
    ["la mouette", "海鸥", "seagull", "topic"],
    ["le corbeau", "乌鸦", "crow", "topic"],
    ["la pie", "喜鹊", "magpie", "topic"],
    ["le pic", "啄木鸟", "woodpecker", "topic"],
    ["le rouge-gorge", "知更鸟", "robin", "topic"],
    ["le pigeon", "鸽子", "pigeon", "topic"],
    ["la dinde", "火鸡", "turkey", "topic"],
    ["la chauve-souris", "蝙蝠", "bat", "topic"],
    ["le hérisson", "刺猬", "hedgehog", "topic"],
    ["l'écureuil", "松鼠", "squirrel", "topic"],
    ["la taupe", "鼹鼠", "mole", "topic"],
    ["le rat", "大鼠", "rat", "topic"],
    ["le hamster", "仓鼠", "hamster", "topic"],
    ["le blaireau", "獾", "badger", "topic"],
    ["la loutre", "水獭", "otter", "topic"],
    ["le castor", "海狸", "beaver", "topic"],
    ["l'élan", "驼鹿", "moose", "topic"],
    ["le renne", "驯鹿", "reindeer", "topic"],
    ["le sanglier", "野猪", "boar", "topic"],
    ["l'âne", "驴", "donkey", "topic"],
    ["le mulet", "骡子", "mule", "topic"],
    ["le poney", "小马", "pony", "topic"],
    ["le veau", "小牛", "calf", "topic"],
    ["le chaton", "小猫", "kitten", "topic"],
    ["le chiot", "小狗", "puppy", "topic"],
    ["la girafe", "长颈鹿", "giraffe", "topic"],
    ["le zèbre", "斑马", "zebra", "topic"],
    ["le rhinocéros", "犀牛", "rhino", "topic"],
    ["le léopard", "豹", "leopard", "topic"],
    ["le guépard", "猎豹", "cheetah", "topic"],
    ["le gorille", "大猩猩", "gorilla", "topic"],
    ["le kangourou", "袋鼠", "kangaroo", "topic"],
    ["le koala", "考拉", "koala", "topic"],
    ["le panda", "熊猫", "panda", "topic"],
    ["l'ours polaire", "北极熊", "polar bear", "topic"],
    ["la baleine", "鲸", "whale", "topic"],
    ["le dauphin", "海豚", "dolphin", "topic"],
    ["la fourrure", "毛皮", "fur", "topic"],
    ["la griffe", "爪子", "claw", "topic"],
    ["la patte", "爪", "paw", "topic"],
    ["la plume", "羽毛", "feather", "topic"],
    ["l'aile", "翅膀", "wing", "topic"],
    ["la queue", "尾巴", "tail", "topic"],
    ["la corne", "角", "horn", "topic"],
    ["le sabot", "蹄", "hoof", "topic"],
    ["la crinière", "鬃毛", "mane", "topic"],
    ["la coquille", "壳", "shell", "topic"],
    ["la nageoire", "鳍", "fin", "topic"],
    ["le nid", "巢", "nest", "topic"],
    ["la tanière", "兽穴", "den", "topic"],
    ["le troupeau", "兽群", "herd", "topic"],
    ["la tulipe", "郁金香", "tulip", "topic"],
    ["la marguerite", "雏菊", "daisy", "topic"],
    ["le lis", "百合", "lily", "topic"],
    ["l'orchidée", "兰花", "orchid", "topic"],
    ["le coquelicot", "罂粟花", "poppy", "topic"],
    ["la lavande", "薰衣草", "lavender", "topic"],
    ["le jasmin", "茉莉", "jasmine", "topic"],
    ["le lierre", "常春藤", "ivy", "topic"],
    ["la fougère", "蕨类", "fern", "topic"],
    ["le cactus", "仙人掌", "cactus", "topic"],
    ["le buisson", "灌木", "bush", "topic"],
    ["la pelouse", "草坪", "lawn", "topic"],
    ["la mauvaise herbe", "杂草", "weed", "topic"],
    ["le bourgeon", "花蕾", "bud", "topic"],
    ["le pétale", "花瓣", "petal", "topic"],
    ["la tige", "茎", "stem", "topic"],
    ["l'épine", "刺", "thorn", "topic"],
    ["l'écorce", "树皮", "bark", "topic"],
    ["la brindille", "细枝", "twig", "topic"],
    ["l'érable", "枫树", "maple", "topic"],
    ["le saule", "柳树", "willow", "topic"],
    ["le peuplier", "杨树", "poplar", "topic"],
    ["le sapin", "冷杉", "fir", "topic"],
    ["le cyprès", "柏树", "cypress", "topic"],
    ["le palmier", "棕榈树", "palm", "topic"],
    ["le marron", "栗子", "chestnut", "topic"],
    ["la noix", "核桃", "walnut", "topic"],
    ["l'amande", "杏仁", "almond", "topic"],
    ["la noisette", "榛子", "hazelnut", "topic"],
    ["l'abricot", "杏", "apricot", "topic"],
    ["la prune", "李子", "plum", "topic"],
    ["la figue", "无花果", "fig", "topic"],
    ["le melon", "甜瓜", "melon", "topic"],
    ["l'ananas", "菠萝", "pineapple", "topic"],
    ["la mangue", "芒果", "mango", "topic"],
    ["la noix de coco", "椰子", "coconut", "topic"],
    ["la framboise", "覆盆子", "raspberry", "topic"],
    ["la myrtille", "蓝莓", "blueberry", "topic"],
    ["le pamplemousse", "柚子", "grapefruit", "topic"],
    ["la citrouille", "南瓜", "pumpkin", "topic"],
    ["le concombre", "黄瓜", "cucumber", "topic"],
    ["le poivron", "甜椒", "pepper", "topic"],
    ["l'aubergine", "茄子", "aubergine", "topic"],
    ["la courgette", "西葫芦", "courgette", "topic"],
    ["les épinards", "菠菜", "spinach", "topic"],
    ["le chou", "卷心菜", "cabbage", "topic"],
    ["le chou-fleur", "花椰菜", "cauliflower", "topic"],
    ["le brocoli", "西兰花", "broccoli", "topic"],
    ["le céleri", "芹菜", "celery", "topic"],
    ["le poireau", "韭葱", "leek", "topic"],
    ["le petit pois", "豌豆", "pea", "topic"],
    ["le haricot", "豆", "bean", "topic"],
    ["la lentille", "扁豆", "lentil", "topic"],
    ["le pois chiche", "鹰嘴豆", "chickpea", "topic"],
    ["l'avoine", "燕麦", "oats", "topic"],
    ["l'orge", "大麦", "barley", "topic"],
    ["le seigle", "黑麦", "rye", "topic"],
    ["la cheminée", "烟囱", "chimney", "topic"],
    ["la gouttière", "排水沟", "gutter", "topic"],
    ["le grenier", "阁楼", "attic", "topic"],
    ["le porche", "门廊", "porch", "topic"],
    ["l'abri de jardin", "棚屋", "shed", "topic"],
    ["la serrure", "锁", "lock", "topic"],
    ["la charnière", "铰链", "hinge", "topic"],
    ["le volet", "百叶窗", "shutter", "topic"],
    ["le store", "窗帘", "blind", "topic"],
    ["le papier peint", "壁纸", "wallpaper", "topic"],
    ["le plafond", "天花板", "ceiling", "topic"],
    ["la latte de plancher", "地板条", "floorboard", "topic"],
    ["le radiateur", "暖气片", "radiator", "topic"],
    ["la chaudière", "锅炉", "boiler", "topic"],
    ["le tuyau", "管道", "pipe", "topic"],
    ["la prise de courant", "插座", "socket", "topic"],
    ["l'interrupteur", "开关", "switch", "topic"],
    ["l'ampoule", "灯泡", "bulb", "topic"],
    ["le fusible", "保险丝", "fuse", "topic"],
    ["le câble", "电缆", "cable", "topic"],
    ["le compteur", "电表", "meter", "topic"],
    ["le bail", "租约", "lease", "topic"],
    ["le déménagement", "搬家", "move", "topic"],
    ["le tiroir", "抽屉", "drawer", "topic"],
    ["le classeur", "文件柜", "filing cabinet", "topic"],
    ["l'agrafeuse", "订书机", "stapler", "topic"],
    ["le trombone", "回形针", "paper clip", "topic"],
    ["le post-it", "便利贴", "sticky note", "topic"],
    ["le surligneur", "荧光笔", "highlighter", "topic"],
    ["la photocopieuse", "复印机", "photocopier", "topic"],
    ["la déchiqueteuse", "碎纸机", "shredder", "topic"],
    ["le tableau blanc", "白板", "whiteboard", "topic"],
    ["le projecteur", "投影仪", "projector", "topic"],
    ["le calendrier", "日历", "calendar", "topic"],
    ["le badge", "工牌", "badge", "topic"],
    ["le stagiaire", "实习生", "intern", "topic"],
    ["le réceptionniste", "前台", "receptionist", "topic"],
    ["la cruauté", "残忍", "cruelty", "topic"],
    ["l'honnêteté", "诚实", "honesty", "topic"],
    ["la patience", "耐心", "patience", "topic"],
    ["la sagesse", "智慧", "wisdom", "topic"],
    ["l'avidité", "贪婪", "greed", "topic"],
    ["la paresse", "懒惰", "laziness", "topic"],
    ["l'entêtement", "固执", "stubbornness", "topic"],
    ["la confiance en soi", "自信", "confidence", "topic"],
    ["la créativité", "创造力", "creativity", "topic"],
    ["l'intelligence", "智力", "intelligence", "topic"],
    ["la bêtise", "愚蠢", "stupidity", "topic"],
    ["la folie", "疯狂", "madness", "topic"],
    ["la faiblesse", "弱点", "weakness", "topic"],
    ["la lenteur", "缓慢", "slowness", "topic"],
    ["le silence", "寂静", "silence", "topic"],
    ["le bruit", "噪音", "noise", "topic"],
    ["l'obscurité", "黑暗", "darkness", "topic"],
    ["la luminosité", "明亮", "brightness", "topic"],
    ["la froideur", "冷淡", "coldness", "topic"],
    ["la dureté", "硬度", "hardness", "topic"],
    ["la saleté", "污垢", "dirt", "topic"],
    ["la chance", "运气", "luck", "topic"],
    ["l'échec", "失败", "failure", "topic"],
    ["la routine", "例行公事", "routine", "topic"],
    ["l'occasion", "机会", "opportunity", "topic"],
    ["le risque", "风险", "risk", "topic"],
    ["l'inconvénient", "劣势", "disadvantage", "topic"],
    ["le but", "目的", "purpose", "topic"],
    ["la raison", "原因", "reason", "topic"],
    ["l'excuse", "借口", "excuse", "topic"],
    ["la blague", "笑话", "joke", "topic"],
    ["le mensonge", "谎言", "lie", "topic"],
    ["la rumeur", "谣言", "rumour", "topic"],
    ["la dispute", "争吵", "quarrel", "topic"],
    ["le souhait", "愿望", "wish", "topic"],
    ["le cauchemar", "噩梦", "nightmare", "topic"],
    ["l'adolescence", "青春期", "adolescence", "topic"],
    ["l'âge adulte", "成年", "adulthood", "topic"]
  );
})();
