/* =====================================================
   RADIX LATINA — 音变篇:从拉丁语推出法/意/西/英的换字母规律
   每条: id | 分组 | 名字 | 一句话规则 | 为什么 | 例子[拉丁, 法, 意, 西, 英(同源或借词)] | 反推提示
   依据:通俗拉丁 → 罗曼语的常规音变(Väänänen《通俗拉丁语导论》一类教材的共识),
   以及日耳曼语的格林定律。只写有把握的规律,个别例外在条目里点明。
   ===================================================== */
const LAWS = [
/* ---------------- 元音 ---------------- */
{ id:"e-ie", grp:"元音", name:"重读短 ĕ 裂成 ie", rule:"拉丁重读的短 ĕ,在西班牙语里几乎一律裂成 ie,意大利语裂成 ie,法语变成 ie/i。",
  why:"通俗拉丁的重音元音拉长后裂开(diphthongisation),这是罗曼语最整齐的一条元音规律。",
  ex:[["pedem","pied","piede","pie","pedal(借词)"],["terram","terre","terra","tierra","terrain"],["septem","sept","sette","siete","September"],["ferrum","fer","ferro","hierro","ferrous"],["tempus","temps","tempo","tiempo","tempo"]],
  back:"看到西语 ie,先压回 e,常能还原拉丁词根:tierra→terra、siempre→semper。" },
{ id:"o-ue", grp:"元音", name:"重读短 ŏ 裂成 ue / uo / eu", rule:"拉丁重读短 ŏ:西语 → ue,意语 → uo,法语 → eu。",
  why:"与 ĕ→ie 同一条裂化规律,只是后元音方向。",
  ex:[["portam","porte","porta","puerta","port"],["focum","feu","fuoco","fuego","focus(借词)"],["mortem","mort","morte","muerte","mortal"],["corpus","corps","corpo","cuerpo","corpse"],["novum","neuf","nuovo","nuevo","novel"]],
  back:"西语 ue → 拉丁 o;法语 eu 也多半来自 o 或 ō。" },
{ id:"iu-eo", grp:"元音", name:"短 ĭ → e,短 ŭ → o", rule:"通俗拉丁把短 ĭ 并入 e,短 ŭ 并入 o;长 ī、ū 不变。",
  why:"古典拉丁靠长短区分元音,通俗拉丁改成靠音质区分,十个元音塌缩成七个。",
  ex:[["pilum","poil","pelo","pelo","pile(无关,勿混)"],["buccam","bouche","bocca","boca","buccal"],["minus","moins","meno","menos","minus"],["gulam","gueule","gola","gula","gullet"],["siccum","sec","secco","seco","desiccate"]],
  back:"看到罗曼语的 e/o,别忘了它可能来自拉丁的 i/u:西 pelo ← pilum、boca ← bucca。" },
{ id:"au-o", grp:"元音", name:"au → o", rule:"拉丁双元音 au 在西、意变成 o;法语也变 o(拼 o/or)。",
  why:"双元音单化(monophthongisation),从帝国晚期就开始了。",
  ex:[["aurum","or","oro","oro","aureate"],["causam","chose","cosa","cosa","cause(书面借词)"],["paucum","peu","poco","poco","paucity"],["taurum","taureau","toro","toro","Taurus"],["audīre","ouïr","udire","oír","audible"]],
  back:"英语里的 au 词多半是后来从书面拉丁借的(cause、audio),而法语 chose、西语 cosa 走的是口语路。" },
{ id:"synco", grp:"元音", name:"法语吃掉非重读元音", rule:"拉丁词里非重读的中间元音,法语几乎全部脱落,西、意常保留。",
  why:"法语重音集中在词末,前后音节被压缩(syncope)。这是法语词比意/西短的主因。",
  ex:[["tabulam","table","tavola","tabla","table"],["calidum","chaud","caldo","caliente","scald(相关)"],["oculum","œil","occhio","ojo","ocular"],["frigidum","froid","freddo","frío","frigid"],["masculum","mâle","maschio","macho","masculine"]],
  back:"法语词看着对不上时,把拉丁词的中间音节补回去:mâle ← mas(cu)lum。" },
/* ---------------- 辅音 ---------------- */
{ id:"lenis", grp:"辅音", name:"元音之间的 p t k 浊化", rule:"拉丁 -p- -t- -c- 夹在元音之间:西语浊化成 -b- -d- -g-,法语更进一步弱化或脱落,意大利语多保留。",
  why:"这叫 lenition(弱化),是西罗曼语区最核心的辅音规律。",
  ex:[["vītam","vie","vita","vida","vital"],["amīcum","ami","amico","amigo","amicable"],["sapēre","savoir","sapere","saber","sapient"],["mūtāre","muer","mutare","mudar","mutate"],["rīpam","rive","riva","riba","river"]],
  back:"西语 -d- 常来自拉丁 -t-,西语 -g- 常来自 -c-:vida←vita、amigo←amicum、lago←lacum。" },
{ id:"f-h", grp:"辅音", name:"西班牙语词首 f- → h-", rule:"拉丁词首 f- 在西班牙语里先变送气 h,再不发音,但拼写保留 h。",
  why:"一般认为受巴斯克语底层影响,从中世纪卡斯蒂利亚语扩散开。",
  ex:[["farīnam","farine","farina","harina","farinaceous"],["facere","faire","fare","hacer","fact"],["fīlium","fils","figlio","hijo","filial"],["ficum","figue","fico","higo","fig"],["fōrmōsum","—","formoso","hermoso","formosity"]],
  back:"西语 h- 开头且法/意是 f- 的,基本都是这条:hijo←filius、hacer←facere、hierro←ferrum。" },
{ id:"pl-ll", grp:"辅音", name:"pl- cl- fl- 的三种走向", rule:"拉丁 pl-/cl-/fl-:西语变 ll-,葡语变 ch-,意语变 pi-/chi-/fi-,法语保留 pl-/cl-/fl-。",
  why:"辅音丛里的 l 腭化(palatalisation),各语言腭化的程度不同。",
  ex:[["plēnum","plein","pieno","lleno","plenary"],["clāvem","clé","chiave","llave","clavicle"],["flammam","flamme","fiamma","llama","flame"],["plūviam","pluie","pioggia","lluvia","pluvial"],["plangere","plaindre","piangere","llanto(名词)","plangent"]],
  back:"西语 ll- 开头的老词,试着还原成 pl-/cl-/fl-,就能对上法语与英语借词。" },
{ id:"ct", grp:"辅音", name:"-ct- 的四张脸", rule:"拉丁 -ct-:西语 → ch,法语 → it,意语 → tt,葡语 → it。",
  why:"c 先弱化成半元音 /j/,再与后面的 t 融合(西语)或形成双元音(法语)。",
  ex:[["noctem","nuit","notte","noche","nocturnal"],["factum","fait","fatto","hecho","fact"],["lactem","lait","latte","leche","lactose"],["octō","huit","otto","ocho","octave"],["tēctum","toit","tetto","techo","protect"]],
  back:"这条最好用:看到西语 ch 而英语是 ct,直接对应(noche/nocturnal、leche/lactose)。" },
{ id:"palat", grp:"辅音", name:"c / g 在 e i 前软化", rule:"拉丁的硬 /k/ /g/ 在 e、i 前:意语 → /tʃ/ /dʒ/,法语 → /s/ /ʒ/,西语 → /θ~s/ /x/。",
  why:"前元音把舌位拉前(palatalisation),发生在帝国晚期,是拉丁语与罗曼语最大的听感分界。",
  ex:[["centum","cent","cento","ciento","cent"],["caelum","ciel","cielo","cielo","celestial"],["gentem","gens","gente","gente","gentle"],["circum","cirque","circo","circo","circus"],["gelāre","geler","gelare","helar","gelatin"]],
  back:"读音变了,拼写常没变。所以 ce/ci 的词在四种语言里几乎同形,只是读法不同。" },
{ id:"qu-cu", grp:"辅音", name:"qu 的分家", rule:"拉丁 qu(/kʷ/):意语保留 qu,西语写成 cu,法语写 qu 但只读 /k/。",
  why:"唇化成分 /w/ 在高卢地区丢失,在伊比利亚写法改写。",
  ex:[["quattuor","quatre","quattro","cuatro","quart"],["quandō","quand","quando","cuando","—"],["aquam","eau","acqua","agua","aquatic"],["quaerere","quérir","chiedere","querer","query"],["equam","—","—","yegua","equine"]],
  back:"西语 cu- 与法语 qu- 对齐,英语的 qu- 词多是从法语借的。" },
{ id:"s-esp", grp:"辅音", name:"s + 辅音:西语加 e,法语丢 s", rule:"拉丁词首 s + 辅音:西语前面加一个 e,法语把 s 丢掉并在元音上写 ^。",
  why:"这个组合在通俗拉丁里不好发音,两边各找了一个办法。",
  ex:[["scholam","école","scuola","escuela","school"],["spīritum","esprit","spirito","espíritu","spirit"],["stēllam","étoile","stella","estrella","stellar"],["hospitālem","hôpital","ospedale","hospital","hospital"],["forestem","forêt","foresta","floresta","forest"]],
  back:"看到法语的 ^,那里原来有个 s:hôtel←hospitem、île←insula、pâte←pasta。这是法语词最好认的暗号。" },
{ id:"rhot", grp:"辅音", name:"拉丁语内部的 s → r", rule:"两个元音之间的 s,在古拉丁语里变成了 r(rhotacism)。所以同一个词根会 s/r 交替。",
  why:"公元前 4 世纪的音变,发生在拉丁语自己身上,比罗曼语早得多。",
  ex:[["flōs / flōris","fleur","fiore","flor","floral"],["honōs / honōris","honneur","onore","honor","honour"],["genus / generis","genre","genere","género","genus/general"],["corpus / corporis","corps","corpo","cuerpo","corporal"],["tempus / temporis","temps","tempo","tiempo","temporal"]],
  back:"看到英语里 -us 与 -or-/-er- 并存(corpus/corporal、genus/general),就是这条老规律。" },
{ id:"tion", grp:"词缀", name:"-tiōnem 的四张脸", rule:"拉丁抽象名词后缀 -tiōnem:法 -tion,意 -zione,西 -ción,葡 -ção,英语直接借 -tion。",
  why:"-ti- 在元音前先变 /ts/,再各自演化。",
  ex:[["actiōnem","action","azione","acción","action"],["nātiōnem","nation","nazione","nación","nation"],["ratiōnem","raison","ragione","razón","ration/reason"],["statiōnem","station","stazione","estación","station"],["lectiōnem","leçon","lezione","lección","lesson/lection"]],
  back:"这一条等于一次学会四种语言的抽象名词:把 -ción 换成 -tion / -zione 即可。" },
{ id:"arium", grp:"词缀", name:"-ārium:做这行的人 / 放这东西的地方", rule:"拉丁 -ārium:法 -aire/-ier,意 -aio/-ario,西 -ero/-ario,英 -ary/-eer。",
  why:"同一个后缀,口语路与书面路走出两种形式(西 -ero 是口语,-ario 是后来从书面拉丁再借的)。",
  ex:[["panārium","panier","panaio","panera","pannier"],["librārium","libraire","libraio","librero","library"],["argentārium","argentier","argentiere","argentero","—"],["mīlitārem","militaire","militare","militar","military"],["prīmārium","premier","primario","primero","primary"]],
  back:"看到西语 -ero 与 -ario 并存(librero 书商 / biblioteca 相关的 -ario),前者是继承词,后者是借词。" },
{ id:"nn-ni", grp:"辅音", name:"-nn- / -ni- → ñ / gn", rule:"拉丁 -nn- 与 -ni- 生出腭化鼻音:西语写 ñ,法/意写 gn,葡语写 nh。",
  why:"西语的 ñ 上面那条波浪线,本来就是抄工省写的第二个 n。",
  ex:[["annum","an","anno","año","annual"],["seniōrem","seigneur","signore","señor","senior"],["montāneam","montagne","montagna","montaña","mountain"],["Hispāniam","Espagne","Spagna","España","Spain"],["cuneum","coin","cuneo","cuño","cuneiform"]],
  back:"西语 ñ ↔ 法/意 gn ↔ 英 n(+i/e):año/annual、señor/senior。" },
{ id:"ll-ela", grp:"辅音", name:"-ll- 的腭化与小称 -ellum", rule:"拉丁 -ll- 在西语变 /ʎ/(写 ll),小称后缀 -ellum 给出西 -illo、意 -ello、法 -eau。",
  why:"双写的 l 在西语腭化;小称后缀极高产,今天仍在造词。",
  ex:[["caballum","cheval","cavallo","caballo","cavalier"],["castellum","château","castello","castillo","castle"],["agnellum","agneau","agnello","—","—"],["novellum","nouveau","novello","novillo","novel"],["bellum(美)","beau","bello","bello","beautiful"]],
  back:"法语 -eau 结尾的词,几乎都对应意/西的 -ello/-illo:château/castillo、beau/bello。" },
{ id:"b-v", grp:"辅音", name:"西班牙语 b 与 v 合并", rule:"西班牙语里 b 和 v 读同一个音,拼写全靠词源决定。",
  why:"通俗拉丁的 /w/(写 V)变成 /β/,与 /b/ 的弱化形式撞在一起。",
  ex:[["bibere","boire","bere","beber","imbibe"],["vīvere","vivre","vivere","vivir","vivid"],["habēre","avoir","avere","haber","habit"],["caballum","cheval","cavallo","caballo","cavalry"],["nāvem","nef","nave","nave","naval"]],
  back:"西语拼 b 还是 v,查拉丁词源最可靠:haber←habēre(b),vivir←vīvere(v)。" },
{ id:"prefix", grp:"词缀", name:"前缀会跟着后面的字母变形", rule:"ad- in- con- ex- sub- ob- 碰到不同的辅音会同化:ad+f→aff-,in+m→imm-,con+l→coll-,sub+f→suff-。",
  why:"发音省力(assimilation)。同一个前缀因此有十几种写法。",
  ex:[["ad+ferre → afferre","affaire","afferire","aferir","affer/offer"],["in+mortālem → immortālem","immortel","immortale","inmortal","immortal"],["con+laborāre → collaborāre","collaborer","collaborare","colaborar","collaborate"],["sub+ferre → sufferre","souffrir","soffrire","sufrir","suffer"],["ex+facere → efficere","effet","effetto","efecto","effect"]],
  back:"看到 aff-/att-/acc-/all- 开头,先还原成 ad-;imm-/ill-/irr- 还原成 in-;coll-/corr-/comm- 还原成 con-。" },
{ id:"grimm", grp:"跨语", name:"格林定律:英语的日耳曼层怎样对上拉丁", rule:"拉丁 p→英 f,拉丁 t→英 th,拉丁 k(c)→英 h,拉丁 d→英 t,拉丁 g→英 k。",
  why:"日耳曼语在公元前一千纪发生了整体的辅音推移(Grimm 1822),所以英语的本族词与拉丁词看似不同,其实同源。",
  ex:[["pater","père","padre","padre","father"],["trēs","trois","tre","tres","three"],["cornū","corne","corno","cuerno","horn"],["dentem","dent","dente","diente","tooth"],["genus","genre","genere","género","kin"]],
  back:"英语里成对出现的\"本族词 + 拉丁借词\",常是同一个印欧词:father/paternal、tooth/dental、heart/cardiac、fish/piscine。" },
{ id:"case", grp:"词形", name:"罗曼语的名词来自宾格,不是主格", rule:"拉丁词尾 -m 早就不发音了,罗曼语名词几乎都由宾格形式演变而来。",
  why:"口语里主格与宾格合并,留下的是使用频率更高的宾格。",
  ex:[["nox / noctem","nuit","notte","noche","nocturnal"],["homō / hominem","homme","uomo","hombre","human"],["flōs / flōrem","fleur","fiore","flor","floral"],["lac / lactem","lait","latte","leche","lactic"],["caput / capitem*","chef","capo","cabo","captain"]],
  back:"学拉丁词根时直接记宾格词干(noct-、homin-、flōr-、lact-),推罗曼语词最省事。*capitem 是通俗拉丁的类推形。" },
{ id:"double", grp:"词形", name:"同一个拉丁词的两条路:继承词与借词", rule:"一个拉丁词常在同一种语言里留下两个后代:口语继承的(变形大)和后来从书面拉丁再借的(形状接近原词)。",
  why:"中世纪以后学者不断从拉丁文里重新借词,造成\"双式词\"(doublets)。",
  ex:[["fabricam","forge / fabrique","fabbrica","fragua / fábrica","forge / fabric"],["causam","chose / cause","cosa / causa","cosa / causa","thing / cause"],["dēlicātum","délié / délicat","—","delgado / delicado","delicate"],["integrum","entier / intègre","intero / integro","entero / íntegro","entire / integral"],["hospitālem","hôtel / hôpital","ostello / ospedale","hostal / hospital","hostel / hospital"]],
  back:"看到一对意思相近、长得一个土一个洋的词,多半就是双式词:hôtel/hôpital、entero/íntegro。" },
];
