/* =====================================================
   RADIX LATINA — 字母篇:26 个拉丁字母的来历与它们在拼写里的变身
   每条: id | 字母 | 一句话来历 | 详细来历 | 读音与变体(音值) | 变身规则(拼写替换)
   来历依据:腓尼基字母 → 希腊字母 → 伊特鲁里亚 → 罗马;
   拼写变体依据:罗曼语语音史(通俗拉丁 → 法/意/西)与英语借词层。
   ===================================================== */
const LETTERS = [
{ id:"A", g:"𐤀 → Α → A", short:"公牛的头翻了个身",
  long:"腓尼基字母 ʾālep 本义是\"公牛\",字形就是一个牛头(𐤀:两只角朝左)。希腊人不需要它代表的喉塞音,把它转用来写元音 /a/,并把字形转正立起,成了 Α(alpha)。罗马人经伊特鲁里亚人接过 Α,写成 A——把牛角朝下,就是今天的 A。",
  sound:"拉丁语 a 只有长短之分(ă/ā),没有英语那种\"字母名\"读音。罗曼语里重读的 ā 大多稳定:māter → 意 madre、西 madre、法 mère(法语把重读 a 抬高成了 è)。",
  shift:"a 在法语里最爱变:拉丁 cantāre → 法 chanter(ca- → cha-),amātum → aimé。西语保守:cantar、amado。记忆法:看到法语 ch-,先还原成拉丁 ca-。" },
{ id:"B", g:"𐤁 → Β → B", short:"一座房子的平面图",
  long:"腓尼基 bēt 是\"房子\",字形是简化的房屋平面(𐤁)。希腊语借为 Β(beta),罗马人写作 B。希腊语后来把 β 读成了 /v/(今天的希腊语 β 就念 v),所以拜占庭时期传入的词里 β 常对应 v。",
  sound:"拉丁 b 是双唇浊塞音 /b/。西班牙语里 b 与 v 在发音上已经合并(都读 [b~β]),所以西语拼写常混:beber(喝)、vivir(活)。",
  shift:"两个规律最值钱:① 拉丁 b 在元音之间,法语常脱落或变 v:habēre → avoir、bibere → boire。② 拉丁 p 在元音间浊化成 b(西语)或 v(法语):sapere → 西 saber / 法 savoir。" },
{ id:"C", g:"𐤂 → Γ → C", short:"本来是 G,后来分了家",
  long:"腓尼基 gīml(\"投石索\"或\"骆驼\")→ 希腊 Γ(gamma)→ 伊特鲁里亚人没有 /g/ 与 /k/ 的对立,把它写成 C 并读作 /k/。早期拉丁语因此用 C 同时表示 /k/ 和 /g/(古铭文 Caius = Gaius,缩写至今写作 C.)。公元前 3 世纪,有人在 C 上加一横造出 G,两个音才分家。",
  sound:"古典拉丁 c 永远读 /k/:Cicero 读\"基凯罗\"而非\"西塞罗\"。中世纪起,c 在 e/i/ae/oe 前软化:意 /tʃ/(cento)、法/西 /s/(cent、cien)。这一条叫\"软腭音腭化\",是罗曼语最重要的音变之一。",
  shift:"c ↔ ch ↔ qu ↔ g 的互换极常见:拉丁 canem(狗)→ 法 chien、意 cane、西 can;拉丁 quattuor → 法 quatre、意 quattro、西 cuatro。英语从法语借词时常连 ch 一起借:chief(< caput 头)与 captain(同源另一路)。" },
{ id:"D", g:"𐤃 → Δ → D", short:"一扇门",
  long:"腓尼基 dālet 是\"门\"(𐤃),希腊写作 Δ(delta)——尼罗河的三角洲就因形状像 Δ 得名。罗马人把圆角写法定型为 D。",
  sound:"拉丁 d 是 /d/。元音间的 d 在西语里弱化成近音 [ð](nada 听起来像 na-a),在法语里常常整个脱落:audīre → ouïr、crēdere → croire。",
  shift:"记住\"d 在两元音之间会消失\"就能还原很多法语词:vidēre → voir、sudāre → suer。西语保留 d:ver 是例外(< vidēre 也脱落了),但 sudar、nadar(< natāre)显示 t → d 的浊化。" },
{ id:"E", g:"𐤄 → Ε → E", short:"一个举手欢呼的人",
  long:"腓尼基 hē 是\"窗\"或\"欢呼的人\",表示 /h/。希腊人又一次把闲置的辅音字母改作元音,写成 Ε(epsilon,\"简单的 e\")。罗马人接手,形状几乎没变。",
  sound:"拉丁短 e 与长 ē 分工明确。通俗拉丁把短 ĕ 在重读开音节里裂成双元音:ferrum → 西 hierro、意 ferro;pedem → 西 pie、意 piede、法 pied。这条\"ĕ → ie\"是西班牙语最好认的指纹。",
  shift:"看到西语 ie,先把它压回 e,往往就得到拉丁词根:tiempo ← tempus、siempre ← semper、tierra ← terra。同理西语 ue ← 短 ŏ:puerta ← porta、fuego ← focus。" },
{ id:"F", g:"𐤅 → Ϝ → F", short:"钉子,也是失传的希腊字母",
  long:"腓尼基 wāw(\"钉子\")进入希腊语成了 Ϝ(digamma,读 /w/)。希腊语后来丢掉了 /w/,digamma 从字母表里消失,却留在了伊特鲁里亚与拉丁的 F 里。",
  sound:"拉丁 f 是 /f/。西班牙语有一条著名音变:词首 f- 在中世纪先变成送气 h-,再彻底不发音,但拼写保留 h:farīna → harina、facere → hacer、ficus → higo。",
  shift:"这条规律是西语词汇的一把钥匙:看到 h- 开头的西语词,试着换回 f-,就能对上法语/意大利语:hijo ← filius(法 fils、意 figlio)、hablar ← fabulārī。而 ph 是希腊 φ 的拉丁转写,英语 philosophy、法语 philosophie 都保留它。" },
{ id:"G", g:"C + 一横", short:"罗马人自己造的字母",
  long:"公元前 230 年前后,教语法的自由民 Spurius Carvilius Ruga 在 C 上加一横造出 G,专门写 /g/,并把它放进字母表里原属 Z 的位置(Z 当时已被废弃)。这是拉丁字母表里少数有\"发明人\"的字母。",
  sound:"g 在 a/o/u 前读硬音 /g/,在 e/i 前软化:意 /dʒ/(gente)、法 /ʒ/(gens)、西 /x/(gente,喉音)。与 c 的软化完全平行。",
  shift:"拉丁 g 在元音间常脱落:magis → 西 más、法 mais;rēgālem → 法 royal(g 消失,a 变 oy)。反过来,看到法语 -oy-、西语 -ay- 常可还原出拉丁 -ag-/-eg-。" },
{ id:"H", g:"𐤇 → Η → H", short:"篱笆:从辅音到长音符号",
  long:"腓尼基 ḥēt(\"篱笆\")本表示一个喉擦音。希腊人用它写 /h/,后来在东方方言里改用它表示长元音 ē(eta)。罗马人取的是\"/h/\"这一支,写成 H。",
  sound:"拉丁 h 读音很弱,通俗拉丁里就不发音了;所以罗曼语的 h 一律不发音(法 homme、西 hombre、意 uomo 干脆不写 h)。英语 h 发音是日耳曼层的。",
  shift:"h 常被用作\"修饰符\":ch、ph、th、rh 都是希腊字母 χ φ θ ρ 的拉丁转写。意大利语用 h 保住硬音:chi 读 /ki/、ghe 读 /ge/——这就是为什么 Chianti 读\"基安蒂\"。" },
{ id:"I", g:"𐤉 → Ι → I", short:"一只手,后来分裂成 I 和 J",
  long:"腓尼基 yōd 是\"手\",表示 /j/。希腊写作 Ι(iota),细到成为\"一点点\"的代名词(iota)。拉丁语用 I 同时写元音 /i/ 和半元音 /j/:IVLIVS 既是 Iulius 也是 Julius。直到 16 世纪,法国人 Pierre de la Ramée 等人才把 J 分出来专写辅音。",
  sound:"拉丁 i 长短对立。半元音 /j/ 在罗曼语里发展成 /dʒ/(意 Giulio)、/ʒ/(法 Jules)、/x/(西 Julio)。",
  shift:"记住 i ↔ j ↔ y 是同一个字母的三张脸:iustitia = justitia,英语 justice、法语 justice、西语 justicia。词中的 -i- 也常变成 -e-(拉丁 fidem → 西 fe、法 foi)。" },
{ id:"J", g:"I 的长尾写法", short:"最年轻的拉丁字母之一",
  long:"J 原本只是 I 在词首或连写末尾的花体(如 iij = 3)。文艺复兴时期的语法学家把它固定为辅音字母。英语直到 17 世纪才把 I/J 当成两个字母,所以老词典里 Jack 排在 Iamb 附近。",
  sound:"法语 /ʒ/、西班牙语 /x/(喉音 h)、意大利语没有 j(用 gi-)、德语 /j/、英语 /dʒ/。同一个字母在欧洲读法差别最大。",
  shift:"看到西语 j,常对应法语 g/j 与意大利语 gi:西 mujer ← mulier(法 mouiller 无关),西 hijo / 法 fils / 意 figlio 显示 -li- 的不同走向。" },
{ id:"K", g:"𐤊 → Κ → K", short:"手掌;拉丁人几乎不用它",
  long:"腓尼基 kap 是\"手掌\",希腊 Κ(kappa)。拉丁语有了 C 表示 /k/,K 几乎只留在少数古词与借词里:Kalendae(每月初一,calendar 的来源)、Karthago。中世纪以后靠日耳曼语与希腊语借词才复活。",
  sound:"/k/。罗曼语基本不用 K,除了外来词(kilo、karate)。德语、北欧语大量使用。",
  shift:"英语里 c/k 的分工是诺曼人带来的:king(日耳曼)对 royal(法语),kin 对 gene(希腊-拉丁)。同源对照时,日耳曼 k 常对应拉丁 g:kin ↔ genus、know ↔ gnōscere(格林定律)。" },
{ id:"L", g:"𐤋 → Λ → L", short:"赶牛的刺棒",
  long:"腓尼基 lāmed(\"刺棒、教鞭\")→ 希腊 Λ(lambda)→ 拉丁 L。字形从弯钩变成直角。",
  sound:"拉丁 l 有\"清亮\"与\"沉暗\"两种,今天的葡萄牙语、加泰罗尼亚语还保留区别。",
  shift:"三条高产规律:① 拉丁 pl-/cl-/fl- 在西语变 ll-:plēnum → lleno、clāvem → llave、flamma → llama;在葡语变 ch-:cheio、chave、chama。② 拉丁 -ll- 在西语变 /ʎ/(caballum → caballo)。③ 拉丁 -l- 在元音间于法语常保留但被软化:filia → fille。" },
{ id:"M", g:"𐤌 → Μ → M", short:"水波",
  long:"腓尼基 mēm 是\"水\",字形是波浪(𐤌);希腊 Μ(mu),拉丁 M。同一个\"水\"符号,后来在罗马数字里表示 1000(mille 的首字母)。",
  sound:"/m/,各语言都稳定。拉丁词尾 -m 在古典口语里就已弱化成鼻化,所以罗曼语基本丢掉了宾格词尾 -m:rosam → rosa。",
  shift:"这条\"词尾 -m 脱落\"解释了为什么罗曼语名词几乎都来自拉丁宾格:法 nuit、意 notte、西 noche 都来自 noctem 而不是主格 nox。学词根时直接记宾格更省事。" },
{ id:"N", g:"𐤍 → Ν → N", short:"一条鱼",
  long:"腓尼基 nūn(\"鱼\")→ 希腊 Ν(nu)→ 拉丁 N。",
  sound:"/n/。拉丁 -nn- 与 -ni- 在罗曼语里生出腭化鼻音:annum → 西 año(ñ 其实是省写的两个 n,上面的波浪线就是第二个 n!),意 anno、法 an。",
  shift:"看到西语 ñ,还原成 nn 或 ni 就能对上拉丁:señor ← seniōrem、mañana ← *maneāna。法语用 gn 写同一个音:seigneur、montagne(< montānea)。" },
{ id:"O", g:"𐤏 → Ο → O", short:"眼睛",
  long:"腓尼基 ʿayin 是\"眼睛\",表示一个喉音。希腊人第三次把闲置辅音改成元音,写作 Ο(omicron,\"小 o\");后来又造了 Ω(omega,\"大 o\")表示长音。拉丁只取了 O。",
  sound:"拉丁短 ŏ 在重读开音节里,西语裂成 ue、意大利语裂成 uo、法语变 eu:focus → 西 fuego / 意 fuoco / 法 feu。",
  shift:"这是最好用的还原规律之一:西语 ue ← 拉丁 ŏ(puerta ← porta、cuerpo ← corpus、muerte ← mortem)。反推时把 ue 压回 o 即可。" },
{ id:"P", g:"𐤐 → Π → P", short:"嘴",
  long:"腓尼基 pē(\"嘴\")→ 希腊 Π(pi)→ 拉丁 P(右边的圈闭合了)。",
  sound:"/p/。拉丁 p 在元音之间浊化:西 saber ← sapere、意 sapere 保留、法 savoir(p→v)。",
  shift:"拉丁 ph 是希腊 φ 的转写,读 /f/:philosophia。英语里 ph 词几乎全是希腊来源,f 词多是日耳曼或拉丁来源——photograph 对 father,一眼分出两层。" },
{ id:"Q", g:"𐤒 → Ϙ → Q", short:"猴子?一个只跟 U 同行的字母",
  long:"腓尼基 qōp(可能是\"猴子\"或\"线团\")→ 希腊早期有 Ϙ(qoppa),后来废弃 → 伊特鲁里亚与拉丁保留下来,专门写 /kʷ/。拉丁语里 Q 后面必跟 U:qui、quod、aqua。",
  sound:"/kʷ/。这个唇化音在罗曼语里分化:拉丁 quattuor → 意 quattro(保留)、西 cuatro(写作 cu)、法 quatre(读 /k/,唇化丢了)。",
  shift:"记忆法:西语的 cu- 常对应拉丁 qu-(cuando ← quando、cuatro ← quattuor);法语的 qu- 只读 /k/。英语借了两层:quart(法语路)与 cook(日耳曼路,< 拉丁 coquere 的早期借词)。" },
{ id:"R", g:"𐤓 → Ρ → R", short:"人头",
  long:"腓尼基 rēš 是\"头\"(𐤓),希腊 Ρ(rho),拉丁为了与 P 区分,在下面加了一条腿,成了 R。",
  sound:"拉丁 r 是齿龈颤音。法语后来把它移到小舌(今天的 /ʁ/),西班牙语保留颤音并区分单双(pero 但是 / perro 狗)。",
  shift:"最漂亮的规律叫\"rhotacism 音变\":元音之间的 s 在古拉丁变成 r。所以 flōs(花)的属格是 flōris,honōs → honor,genus → generis。看到一组词里 s/r 交替,就是这条老规律在起作用:corpus/corporis、tempus/temporis。" },
{ id:"S", g:"𐤔 → Σ → S", short:"牙齿",
  long:"腓尼基 šīn 是\"牙\",字形像 W(𐤔);希腊写成 Σ(sigma),拉丁把它拉成 S。",
  sound:"/s/。拉丁 s 在元音间读浊 /z/ 的倾向,在意大利北部与法语里成了常态:rosa 读 /ˈrɔza/。",
  shift:"两条:① 词首 s + 辅音的词,西语要加一个 e:schola → escuela、spīritus → espíritu、stella → estrella。法语更进一步把 s 丢掉,只留长音符号:hôpital ← hospitālem、forêt ← forestem、école ← schola。② 看到法语的 ^,就知道那里原来有个 s。" },
{ id:"T", g:"𐤕 → Τ → T", short:"一个记号,一个十字",
  long:"腓尼基 tāw 意思就是\"记号\",字形是叉(𐤕);希腊 Τ(tau),拉丁 T。",
  sound:"/t/。拉丁 -ti- 在元音前于通俗拉丁变成 /ts/,再变 /sj/:nātiōnem → 法 nation(/sj/)、意 nazione(/ts/)、西 nación。",
  shift:"因此 -tion / -zione / -ción / -ção 是同一个拉丁后缀 -tiōnem 的四张脸。只要记住这一条,英、法、意、西的抽象名词几乎可以互相换算:action / azione / acción。" },
{ id:"U", g:"𐤅 → Υ → V/U", short:"V 与 U 本是一个字母",
  long:"腓尼基 wāw 除了给出 F,还给了希腊 Υ(upsilon)。拉丁借来写成 V,同时表示元音 /u/ 和半元音 /w/:VENI VIDI VICI 读作 /weːniː wiːdiː wiːkiː/。中世纪抄工用圆的 u 写词中、尖的 v 写词首;16 世纪以后才按读音分工。W 则是中世纪日耳曼语言把两个 V 连写造出来的\"double u\"。",
  sound:"拉丁 /w/ 在通俗拉丁变成 /v/(所以今天教会拉丁 veni 读 /ˈvɛni/)。西班牙语把 v 与 b 合并。",
  shift:"看到英语里同源却一个 u 一个 v 的词对,多半是这段历史的残留:universe/verse。拉丁 au 在罗曼语里单元音化:aurum → 西 oro、意 oro、法 or。" },
{ id:"V", g:"同 U", short:"军团碑上的 U",
  long:"古罗马碑铭只有 V。IVLIVS、AVGVSTVS 都是这种写法。今天区分 U/V 是印刷时代的规范。",
  sound:"古典 /w/ → 通俗拉丁 /v/。",
  shift:"拉丁 -v- 在元音间于法语常脱落:pavōrem → peur;在西语保留:pavor。" },
{ id:"W", g:"VV", short:"为日耳曼语造的字母",
  long:"拉丁语没有 W。7–8 世纪的英格兰与法兰克抄工为了写日耳曼语的 /w/,把两个 V(或 U)连写,11 世纪定型为 W。法语、意大利语、西班牙语至今只在外来词里用它。",
  sound:"英语/德语 /v/ 或 /w/。德语 W 读 /v/,V 读 /f/——正好与英语相反,这是德语初学者最常踩的坑。",
  shift:"日耳曼 w- 常对应拉丁 v-(或 gu-):wine ↔ vīnum;法语把日耳曼 w- 借成 gu-:werra → guerre(战争)、wardōn → garder。所以 war/guerre、ward/guard 是同一个日耳曼词的两条路。" },
{ id:"X", g:"Χ/Ξ → X", short:"一个字母顶两个音",
  long:"希腊有两个相关字母:Χ(chi,/kʰ/)与 Ξ(xi,/ks/)。拉丁取了西希腊字母表里的 X 来写 /ks/。所以拉丁 X 永远是 /ks/,而希腊借词里的 ch 才是 Χ。",
  sound:"/ks/。西班牙语历史上用 x 写 /ʃ/(Quixote 读\"基肖特\"),16 世纪后这个音变成喉音 /x/,拼写多改成 j(Quijote、México 保留旧拼写但读 /x/)。",
  shift:"拉丁 x 在罗曼语里常变成 s 或 j:exemplum → 西 ejemplo、法 exemple;dīxī → 西 dije。看到西语 j 而法语 x/s,多半来自拉丁 x 或 -ct-。" },
{ id:"Y", g:"Υ → Y", short:"专为希腊词进口的字母",
  long:"共和末期,罗马人为了转写希腊语 Υ(upsilon,读 /y/,像德语 ü)把它原样搬进字母表,排在最后。所以拉丁词里凡有 y 的,几乎都是希腊借词:physica、syllaba、hymnus。",
  sound:"古典拉丁读 /y/,后来读同 i。法语 y 读 /i/,西语 y 是 /j/ 或\"和\"(拉丁 et → 西 y)。",
  shift:"看到 y 就想\"希腊\":psychology、system、rhythm。同样的信号还有 ph、th、ch、rh 与词尾 -sis、-ma。" },
{ id:"Z", g:"𐤆 → Ζ → Z", short:"被赶出去又请回来的字母",
  long:"腓尼基 zayin(\"武器\")→ 希腊 Ζ(zeta)。早期拉丁字母表里本有 Z,但拉丁语用不上,公元前 300 年左右被删除(空出的位置给了新造的 G)。一百多年后,为了转写希腊词又把 Z 请回来,只能排在字母表末尾——这就是 Z 至今殿后的原因。",
  sound:"拉丁 z 读 /dz/ 或 /z/,只出现在希腊借词。意大利 z 读 /ts/(pizza)、西语 z 读 /θ/(西班牙)或 /s/(拉美)、法语 z 读 /z/。",
  shift:"意大利语的 -zione 与西语的 -ción、法语的 -tion 同源(见 T);西语的 z 与 c(在 e/i 前)读同一个音,所以 lápiz → lápices 这样的拼写交替只是写法,不是音变。" },
];
